### PR TITLE
Make use of Vue more universal

### PR DESCRIPTION
**Pull request by Morlinest**
Init Vue on any page where exists element with `id="app"`. Don't need to create `new Vue()` for each page. Vue components should be used for logic.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
How would you handle multiple places of Vue components in single page. Probably change to class vue-app and loop throu them and create Vue for each of them would be better?

**Review by lafriks — CHANGES_REQUESTED** [review]
See my comment

**Comment by Morlinest** [comment]
@lafriks I think we should use only 1 Vue instance on page and we can use any number of components (globally registered) inside. If your logic is inside component, we don't need more instances of Vue. Just set `id` on wrapping element. It is not best solution, but we have simple pages and it's ok with few components. For bigger project you would need use of some bundler like webpack.

**Comment by lafriks** [comment]
Than probably just set I'd id=app globally to body element

**Comment by lafriks** [comment]
As for webpack I think there was already issue for that or at least it was talked somewhere that it should be used

**Comment by Morlinest** [comment]
@lafriks Yes, `id="app"` on body element is my future goal. But for now, we don't need to do it. Waiting for more components on more pages.

**Comment by lafriks** [comment]
@Morlinest I already have PR for other component so if you would add Vue app to body I could change my PR to use that

**Comment by Morlinest** [comment]
@lafriks I've found I can't do it right now because my template is included in `script` tag and template can not be inside `app`. There is no space (without refactoring) between included scripts and end of page (`footer.tmpl` contains both). How do you create/include component templates?

**Comment by Morlinest** [comment]
If #2317 will be merged and we add language data as resource, than we can add template to js in  `index.js` or create some bundle with components like `components.js`.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
ok, let's leave like it is currently. Later in 1.3 we can do more refactoring

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
