### PR TITLE
Git migration UX improvements

### PR DESCRIPTION
**Pull request by jolheiser**
This PR aims to fix some bugs and improve overall migration UX.

Closes #9096 

## Bugs

1. GitHub token authentication had a bug where private repositories would not get their release assets correctly because the code was trying to retrieve them without auth.
2. GitLab's API wants a very specific format for their repo name, which would probably fail more often than not.
   * While munging the clone address we retrieved the "project path", however it retained `.git` at the end which would cause the client to fail

If you would like me to split out the bugs into a separate patch, I could probably take out the GitLab one. The GH one, however, mostly relies on other changes in this PR to get the downloader inside the uploader for retrieving assets with auth.

## Enhancements

1. No more "username is a token" magic
   * If the git service supports a token, the UI will disable basic auth fields and handle it appropriately on the backend
2. Migration options are always shown, however they are disabled if no authentication is provided
3. Authentication remains optional for _all_ service types, however just as before items will not be available

-----

Overall I hope the UI is a little clearer as to what is expected from the user.

This PR was tested with a private repository on both GitHub/GitLab, and was able to fully migrate everything in both cases.  
I was also able to do a plain migration from private repositories on BitBucket as well as Gitea.

## UI Example

Screenshot from 2020-08-26 22-41-17

### CODE REVIEW

**Comment by lunny** [comment]
Could you consider my propose on https://github.com/go-gitea/gitea/pull/9096#issuecomment-622860040

**Review by lafriks — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]
This looks great as a new base! Probably need to reuse some of this code for the mirror settings in a repo as well which currently have the same username/password issue

**Comment by lafriks** [comment]
:rocket:

**Review by 6543 — APPROVED** [review]
🎉 

sidenote: https://try.gitea.io/api/swagger#/repository/repoMigrate has to adapt this if it got merged

**Comment by 6543** [comment]
had a look how this afect the API ... and the only downside I noticed is that the GitServiceType is an integer
to change this to a string would require just too mouch ... the beter way is to document it and warp it on the Client sides

so the answer of this pull is: https://gitea.com/gitea/go-sdk/pulls/392

**Comment by lafriks** [comment]
@6543 it can be made as enum in API also

**Comment by 6543** [comment]
@lafriks if we do so, we should cange it with in v1.13 to not inteoduce a api break

**Comment by lafriks** [comment]
@6543 yes, that's right

**Pull request merged**
