### PR TITLE
Fix emoji replacements, make emoji images consistent

### PR DESCRIPTION
**Pull request by silverwind**
- Fix emoji not being replaced in issue title change text
- Make the image attributes consistent, add alt, remove align

Before:
Screen Shot 2020-08-22 at 20 02 15

After:
Screen Shot 2020-08-22 at 21 01 15

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by CL-Jeremy** [comment]
This _could_ lead to some confusion when changing title between emoji literals and shorthands. Not a big thing though.

Anyway, found [this amazing snippet](https://stackoverflow.com/a/26186450) to fix **:gitea:** not getting struck through, as well as the misalignment due to `span.emoji` having a `vertical-align` offset:

```css
strike {
    text-decoration: none;
    position: relative;
    display: inline-block;
}
strike:after {
    content: "";
    position: absolute;
    bottom: 0;
    left: 0;
    height: calc(50% - 0.5px);
    width: 100%;
    border-top: 1px solid;
}
```

Bildschirmfoto 2020-08-23 um 20 47 59

**Comment by silverwind** [comment]
Not sure if it's a good idea to alter browser styles like that (some browser might want render strikethrough lines differently), but I'd do a slight variation (perfect centering and line does not interfere with clicks):

```css
.strike {
  text-decoration: none;
  position: relative;
}

strike::after {
  content: "";
  position: absolute;
  left: 0;
  right: 0;
  top: calc(50% - 0.5px);
  height: 1px;
  background: currentcolor;
  pointer-events: none;
}
```

Probably stuff for another PR.

**Comment by silverwind** [comment]
Also, that method would break on wrapped lines, so I don't think it's a good idea.

**Comment by CL-Jeremy** [comment]
> Also, that method would break on wrapped lines

See my updated comment. There are some tests to be done there.

**Comment by silverwind** [comment]
You can probably never perfectly immidate browser strikethrough styles because the spec  does not dictate them to be pixel-perfect so this will always be kind of a hack.

**Comment by silverwind** [comment]
FWIW, one can also not strikethrough GitHub's images: ~~. ❤️ :shipit: ❤️~~

**Comment by CL-Jeremy** [comment]
Confirmed to be Chromium-specific. Firefox looks perfect (my suggested imitation resembles the graphical rendering of Chromium though, not Firefox).

> 
```
  top: calc(50% - 0.5px);
```

In your variation it should be `calc(50% + 0.5px)`

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
