### PR TITLE
Fix panic: template: repo/issue/list:210: unexpected "=" in operand

### PR DESCRIPTION
**Pull request by gzsombor**
It seems, that a recent change introduced invalid template content, which resulted in a startup failure:

```

 AppPath: /opt/gitea/gitea
 AppWorkPath: /var/lib/gitea
 Custom path: /var/lib/gitea/custom
 Log path: /var/log/gitea
 panic: template: repo/issue/list:210: unexpected "=" in operand
 goroutine 1 [running]:
 html/template.Must(0x0, 0x192b4a0, 0xc420d1a070, 0x0)
         /var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.10.3/src/html/template/template.go:372 +0x54
 code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.compile(0x17d26f2, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42000c120, 0x2, 0x2, ...)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/render.go:292 +0x21d
 code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*TemplateSet).Set(0xc4207e6630, 0x17cc1cb, 0x7, 0xc4207e4000, 0x0)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/render.go:318 +0x61
 code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.renderHandler(0x17d26f2, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42000c120, 0x2, 0x2, ...)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/render.go:385 +0x12d
 code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.Renderer(0xc4208d5240, 0x1, 0x1, 0xc42000c100, 0x0)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/render.go:422 +0x165
 code.gitea.io/gitea/modules/templates.HTMLRenderer(0xc42002ed80, 0x16218a0)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/modules/templates/static.go:117 +0x155
 code.gitea.io/gitea/routers/routes.NewMacaron(0xc420231680)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/routers/routes/routes.go:107 +0x2fe
 code.gitea.io/gitea/cmd.runWeb(0xc420231680, 0x0, 0x0)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/cmd/web.go:125 +0xb2
 code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x15aeb40, 0x1848c20, 0xc420231680, 0xc42014d200, 0x0)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
 code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x17c6b46, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x17f092c, 0x16, 0x0, ...)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xa0e
 code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc4205801a0, 0xc4200be040, 0x4, 0x4, 0x0, 0x0)
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x5b8
 main.main()
         /var/lib/jenkins/workspace/build_gitea/src/code.gitea.io/gitea/main.go:57 +0x495

```

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for PR @gzsombor, which version of Golang are you using?

**Comment by gzsombor** [comment]
I'm using 1.10.4

**Comment by adelowo** [comment]
This is pretty weird I must say since it is already defined at the top

https://github.com/go-gitea/gitea/blob/48a90253463f8e5bf99471575190fa15fd604aa5/templates/repo/issue/list.tmpl#L184

**Comment by lafriks** [comment]
Updating variables was added in GoLang v1.11: https://golang.org/doc/go1.11#text/template

So we should either rewrite this part of code or raise GoLang version requirements

EDIT: I would prefer moving such logic out of template

**Comment by lafriks** [comment]
Proposed change will fix template rendering but won't fix problem as assigning new variables inside `if` will break logic imho

**Comment by adelowo** [comment]
> Updating variables was added in GoLang v1.11:

My bad

**Comment by lunny** [comment]
We still needs support go1.10 on until Gitea v1.9 I think.

**Comment by gzsombor** [comment]
I can submit a proper fix in evening, I just wanted to quickly re-enable my nightly built server, at first, I though it's just a typo

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
