### PR TITLE
Set autocomplete off on branches selector

### LINKED ISSUE #15782: Overlapped branches list on project view
- Gitea version (or commit ref): 1.14.1
- Operating system: Ubuntu 20.04.2
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

In Chrome (Version 90.0.4430.93 (Offizieller Build) (64-Bit)) when I open the list with the branches the focus is set to the input field and the suggestions I used are shown. I have to clickt outside of the input field to close the suggestions.

Is:
image

Should be:
image

### PR DESCRIPTION
**Pull request by zeripath**
Fix #15782

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm I think we rather want to prevent the field getting autofocus, autocomplete may still be useful.

**Comment by jtran** [comment]
> Hmm I think we rather want to prevent the element from getting autofocus, autocomplete may still be useful.

IMHO, the dropdown is a custom implementation of autocomplete.  Having both a custom implementation and the browser's is conflicting.  On the compare/New Pull Request page, you can select a branch by using the arrow keys to navigate the dropdown.  Unfortunately, the branch selector in this pull request uses a separate implementation and doesn't have the cursor movement functionality.  But presumably, they'll get unified at some point.

Anyway, for what it's worth, I think this is a good change.

**Comment by jtran** [comment]
For me, the browser's autocomplete shows in Firefox 88.0.1 if I click on the input, after it already has the focus.  So the steps are: click the branch selector (the dropdown should open and the input should have the focus), then click the input.  I don't know if there are other ways to trigger it.

**Comment by zeripath** [comment]
> I can't seem to reproduce the original issue, whatever I do, it won't show any dropdown over the input. Tested in Firefox 89 and Chromium 90.

I can reliably reproduce the issue and my PR fixes the issue.

**Comment by silverwind** [comment]
>  So the steps are: click the branch selector (the dropdown should open and the input should have the focus), then click the input.

Strange, doing that in Firefox 89 on Mac just brings up the browser-native dropdown menu, which I don't find too distracting. This behaviour might actually be platform-dependant.

**Review by techknowlogick — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
