### PR TITLE
Add Created & Updated to Milestone

### LINKED ISSUE #12655: [API] Milestone expose Times
expose Creation and Update times

### PR DESCRIPTION
**Pull request by 6543**
close #12655

### CODE REVIEW

**Comment by a1012112796** [comment]
Hmm, maybe we can get these messages from comment.

**Comment by 6543** [comment]
@a1012112796 this would be a lot of extra SQL querys on each milestone related thing ...

**Comment by a1012112796** [comment]
> @a1012112796 this would be a lot of extra SQL querys on each milestone related thing ...

Sorry, I misunderstood.

**Comment by a1012112796** [comment]
Suggest show it on ui also.
image

**Comment by 6543** [comment]
@a1012112796 I think it will get to overloaded with this:
Bildschirmfoto zu 2020-09-01 04-45-33

**Review by a1012112796 — APPROVED** [review]
👍

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
