### PR TITLE
Fix integrations test error with space in CURDIR path

### LINKED ISSUE #14055: Integration tests fail with space in path
- Gitea version (or commit ref): `fdaa050`
- Git version: 
- Operating system: Windows
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description
When I run integration tests with the following:

`TEST_PGSQL_HOST=127.0.0.1:5432 TEST_PGSQL_DBNAME=gitea_test TEST_PGSQL_USERNAME=gitea TEST_PGSQL_PASSWORD=gitea TEST_PGSQL_SCHEMA='' make test-pgsql#Download`

I get an error from make: `/usr/bin/sh: -: command not found`. 

Root cause is the space in my base path which isn't handled by make `${CURDIR}`.

### PR DESCRIPTION
**Pull request by kdumontnu**
Closes #14055

Put all instances of `${CURDIR}` in makefile within quotes to allow running integration tests in a directory with space in the path.

### CODE REVIEW

**Comment by silverwind** [comment]
Thanks. Can you make it `"$(CURDIR)"`. Those braces behave exactly the same but we generally use round ones throughout the Makefile so these curly ones just seem inconsistent to me.

**Review by silverwind — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
It should be possible to make setting GITEA_ROOT unnecessary. 

However this does what it says on the tin

**Comment by techknowlogick** [comment]
@kdumontnu you're on a roll, thanks for another PR :) Could you press the "update branch" button on this page (right above where comment box is)? When contributing from a fork from an org Github doesn't provide permissions to maintainers to update that branch on our side.

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
