### PR TITLE
Add captcha support to OpenID based signup

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by lunny** [comment]
maybe some screenshots?

**Comment by strk** [comment]
Screenshots are expensive for me.
Look at the registration screen from try.gitea.io.
You get the same thing :)

**Comment by pgaskin** [comment]
Maybe some screenshots so we can see the nice captchas? :smiley: LGTM

**Comment by lunny** [comment]
LGTM except @geek1011 's comment.

**Comment by strk** [comment]
@bkcsoft can you merge now ?  :)

captcha

**Pull request merged**
