### PR TITLE
Fix typos in i18n variable names.

### PR DESCRIPTION
**Pull request by mrichar1**
Simple search/replace across the whole project: `visiblity` -> `visibility`

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Thanks for the PR @mrichar1. The reason I've "requested changes" on this PR is that there is a system in place to automatically update these translation files from Crowdin. You can find out more information on how to contribute to these files here: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#translation

**Review by techknowlogick — APPROVED** [review]
Ack. I should've looked at the PR changes first instead of just the file list. Sorry for confusion. This looks good.

Thanks again for contribution.

**Review by sapk — APPROVED** [review]
I think that all the locales except en-us will be overwritten by the bot but it will be easy to update them on crowdin since the string doesn't change they will appear in suggestions.

**Comment by lafriks** [comment]
Blocking just in case to not braeak translations as we are close to 1.5 release date

**Comment by lafriks** [comment]
@mrichar1 please resolve conflicts in en-US file

**Review by lafriks — CHANGES_REQUESTED** [review]
`options/locale/locale_*` only en-US are allowed to change. Other files will be regenerated from translations on crowdin

**Comment by mrichar1** [comment]
Hi - I've modified the original commit to only change the en-us locale as requested - however I was half-asleep so did it as a slightly messy rebase/merge.

Let me know if this is ok, or if you need it done without the rebasing...

**Review by lafriks — APPROVED** [review]

**Pull request merged**
