### PR TITLE
Added email notification option to receive all own messages (#20179)

### PR DESCRIPTION
**Pull request by tyroneyeh**
Backport #20179

### CODE REVIEW

**Review by a1012112796 — COMMENTED** [review]
it's not necessay to backport the feature ...

**Comment by tyroneyeh** [comment]
But 1.17 has not been released yet, I hope this feature can be included from the old version update, what do other people think?

**Comment by wxiaoguang** [comment]
Thank you for your PR and backport.

According Gitea's release plan, the stable and rc releases only get bug fixes, but not features or enhancements.

https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#release-cycle

```
All the feature pull requests should be merged before feature freeze. 
And, during the frozen period, a corresponding release branch is open for fixes backported from main branch.
Release candidates are made during this period for user testing to obtain a final version that is maintained in this branch.
A release is maintained by issuing patch releases to only correct critical problems such as crashes or security issues.
```

**Comment by 6543** [comment]
sorry enhancements where backported in some edgecases, but features wont

**Comment by tyroneyeh** [comment]
😭

**Pull request closed without merging**
