### PR TITLE
fix gofmt error.

### PR DESCRIPTION
**Pull request by appleboy**
refer to go report card: https://goreportcard.com/report/github.com/go-gitea/gitea#gofmt

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Review by lunny — COMMENTED** [review]
Bin data should modify by generator?

**Comment by strk** [comment]
Agreed, bindata should not be included

**Comment by appleboy** [comment]
@strk @lunny My apologies. I removed bindata.

**Comment by strk** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
