### PR TITLE
Fix ini format incomiptable with crowdin

### LINKED ISSUE #1174: Wrong link in activity tab
- Gitea version (or commit ref): 1.1.0+4-g05f0c4bb
- Git version: 1.7.4
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)

## Description

In anyone's activity tab, someone like this: [lalaland - Gitea: Git with a cup of tea](https://try.gitea.io/lalaland?tab=activity))

Click on the link like [lalaland/gitea](https://try.gitea.io/%5C%22/lalaland/gitea%5C%22) or [lalaland/test](https://try.gitea.io/%5C%22/lalaland/test%5C%22) will redirect to 404 page.

### PR DESCRIPTION
**Pull request by lunny**
will fix #1174 and #1175

### CODE REVIEW

**Comment by tboerger** [comment]
Have you changed that manually? We have to upload the English changed version to crowdin to reflect the translated changes.

**Comment by lunny** [comment]
I manually changed the other files except English so you can upload English safely.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
We need to merge this PR first. LGTM

**Comment by andreynering** [comment]
Trusted LGTM

**Pull request merged**
