### PR TITLE
Detect delimiter in CSV rendering

### LINKED ISSUE #7868: render CSV with different delimiters than ,
Currently CSV files are only properly rendered with a `,` delimiter.
`;` and `\t` delimiters are common as well, and should be rendered as well.

golangs `encoding/csv` does not have delimiter detection built in, so we need to implement that.
I'm willing to implement that feature.

### PR DESCRIPTION
**Pull request by noerw**
Extends the CSV parser to detect the file's delimiter, in order to render correct previews of files with different delimiters than the default `,`.
Also applies the parser to `.tsv` files which is a common extension for CSV with a `\t` delimiter.

Fixes #7868.

### CODE REVIEW

**Comment by lunny** [comment]
CI failed.

**Review by zeripath — COMMENTED** [review]
It's a cool idea to be able to guess the delimiter and although I can only imagine pathological failure cases to your algorithm - I think it would be good to add a way to override the guessed delimiter.

**Comment by lunny** [comment]
@zeripath But we have no UI to select delimiter so I think that's not this PR's work.

**Comment by noerw** [comment]
@lunny CI works now.

@zeripath Re manual override:
Even for CSV files with less structure, `bestDelimiter()` still gives quite good results (see testcase). So an override would be needed for rare edgecases only, which is not worth the complexity and dev time imho. After all this is a file preview only.

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by noerw** [comment]
@lunny, sorry I messed the last commit up, CI should work now again.

You have an impressively fast pace going here with PRs!

**Comment by silverwind** [comment]
Does this detection ignore delimiters inside quotes? E.g. it should detect `;` as the delimiter in this case:

```
1;2;"a,b,c,d,e"

**Comment by noerw** [comment]
@silverwind It does not explicitly look for quotes. Do you have a fast implementation in mind?

Instead we count total occurences of a possible delimiter, and have a penalty for irregularity (different occurences between lines).
This fails for cases like your example, but works well for files with more than 1-2 lines, which I suppose is the most common case.

**Comment by silverwind** [comment]
While looping lines, replace quoted content with empty strings via regex like https://regex101.com/r/FJHHyg/2, effectively hiding that quoted content while counting delimiters.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
