### PR TITLE
Expose default theme in meta and API

### PR DESCRIPTION
**Pull request by jolheiser**
As title, this was requested in Discord primarily for a dark reader to be able to check the DOM for the default theme.

As well, this adds the default theme to the UI API.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by techknowlogick — DISMISSED** [review]
This is default theme, we should report what the user’s current theme is as well

**Comment by lunny** [comment]
@techknowlogick That could be another PR. :)

**Comment by jolheiser** [comment]
> This is default theme, we should report what the user’s current theme is as well

A separate meta tag (that would only show up when the user is signed it)?

**Comment by lafriks** [comment]
What is use case for default theme in meta tag as we don't use it in javascript

**Comment by silverwind** [comment]
Default theme is probably fine, but please don't do user's theme. I plan on moving the user's theme setting to JavaScript (e.g. removing it from the database and having it in localStorage only) later.

**Comment by silverwind** [comment]
Thought, I'm not sure yet how to do the theme loading is JS because accessing local storage during page load will be problematic (requires inline script), so we might end up keeping the theme in the database after all.

**Comment by 6543** [comment]
:rocket:

**Comment by silverwind** [comment]
We'll remove this meta tag in https://github.com/go-gitea/gitea/pull/24960, it is non-standard and does not reflect current theme, just the server's default.

I don't know what "dark reader" the original PR is refering to, but it's not the official one. Such extensions should either check `color-scheme` or our custom `--is-dark-theme` variable set on the HTML node.

https://github.com/go-gitea/gitea/blob/7314726babecb04da7f5e38db79c2115f8eedafe/web_src/css/themes/theme-arc-green.css
https://github.com/go-gitea/gitea/blob/7314726babecb04da7f5e38db79c2115f8eedafe/web_src/css/themes/theme-arc-green.css#L185

**Pull request merged**
