### PR TITLE
Re-add initial wiki page text when editing the page

### LINKED ISSUE #23979: WebGUI Wiki Editor does not show Text of wiki page. Pressing save deletes all.
### Description

When i edit any existing wiki page, gitea will not show the wiki pages content in the editor view.
There is no content. If i press save on the empty page, all the previous content is gone.
This makes it impossible for to use the Web GUI editor.

I am using getea as it is hosted on gitea.com
https://gitea.com/henri/wiki/wiki/Testpage
was able to reproduce it on 
https://try.gitea.io/henri/wikitest-repo/wiki/Home

This issue started a few day ago after the editor was changed to not be WYSIWYG any more.
I have tested it with Firefox and Chrome. Both have the bug.

Sorry, if this is the wrong place to report this issue.

### Screenshots

gite wiki bug 1
gitea wiki bug 2

### Gitea Version

Version: 1.20.0+dev-349-g17f23182f

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 7

### Browser Version

Firefox 111.0.1 (64-bit)

### PR DESCRIPTION
**Pull request by wxiaoguang**
The `$content` was prepared above, but forgot to put it into the editor ....

Fix #23979

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
This could be `skip-changelog`

**Comment by delvh** [comment]
Agreed

**Comment by silverwind** [comment]
Can we add `TextareaPlaceholder` here as well? I think every textarea should have one?

**Comment by wxiaoguang** [comment]
> Can we add `TextareaPlaceholder` here as well? I think every textarea should have one.

No need, there is always `$content`

See above

```
			{{$content := .content}}
			{{if not .PageIsWikiEdit}}
				{{$content = .locale.Tr "repo.wiki.welcome"}}
			{{end}}

```

**Comment by silverwind** [comment]
> > Can we add `TextareaPlaceholder` here as well? I think every textarea should have one.
> 
> No need, there is always `$content`
> 
> See above
> 
> ```
> 			{{$content := .content}}
> 			{{if not .PageIsWikiEdit}}
> 				{{$content = .locale.Tr "repo.wiki.welcome"}}
> 			{{end}}
> ```

Unless it's being deleted 😉

**Pull request merged**
