### PR TITLE
Fix api route

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport

**Comment by Cherrg** [comment]
i don't know why, but since merging this drone build seems broken

**Comment by techknowlogick** [comment]
@Cherrg fail is due to an upstream dependency not related to this PR

**Comment by Cherrg** [comment]
ok, only looked what was merged before it was broken :)

unfortunately i cant reproduce this on my local machine to track down the error

**Pull request merged**
