### PR TITLE
Improve commit list/view on mobile

### PR DESCRIPTION
**Pull request by Gusted**
- This is a continuation on [the work](https://github.com/go-gitea/gitea/pull/19546) I've done for improving mobile experience on Gitea.
- The current behavior of going trough the commits list is horrible, each individual item gets it's own row and thereby isn't quite compact as it should be on mobile. The commit view's header is in a bit better state, it's quite only that content is overlapping each other.
- This patch fixes those problems. Each row in the commit list table will actually take a row in the UI. The commit view's header has now a better organized way of placing the information.

## Before
<details></details>
<details></details>

## After
<details></details>
<details></details>

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Seems fine.
The only thing I noticed is:
Do we perhaps still want to display the `(un)verified` icon when present?
That is so small that it can fit even into such a small screen and lets users know whether to trust this commit.

**Comment by Gusted** [comment]
Hmm not sure where to place such item, but definitely a good addition to still have the icon.

**Comment by delvh** [comment]
I can see two options for that:
a) Directly after the author and before the commit title
b) Directly after the commit title and before the commit date

Which one do you prefer?

**Comment by Gusted** [comment]
I think b makes the most sense logically.

**Review by 6543 — APPROVED** [review]

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I appreciate the work done in this PR and on improving the mobile UX overall.
One question, though: won't it be confusing to users (such as myself) used to seeing commit hashes *along* with commit messages when *suddenly* (ref img After-1) there's just commit messages left and it's necessary to click to see the actual hash as well as commit signing status, that is visually indicated by the colour of the frame around the commit message that's now hidden..?
I wish I could bring this up before this was merged but hey, no biggie, just a thought.

**Comment by Gusted** [comment]
> One question, though: won't it be confusing to users (such as myself) used to seeing commit hashes _along_ with commit messages when _suddenly_ (ref img After-1) there's just commit messages left and it's necessary to click to see the actual hash as well as commit signing status, that is visually indicated by the colour of the frame around the commit message that's now hidden..?

The commit hash is simply too long to be shown on a screen where horizontal space is very limited. In my viewpoint, I never really use the commit hash from such list unless I want to have a commit hash from a specific commit(which is now on mobile one more click away). Yeah I wanted to some work on commit signing status but got stalled by school, but now it's already merged 🤷🏽.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> The commit hash is simply too long to be shown on a screen where horizontal space is very limited. In my viewpoint, I never really use the commit hash from such list unless I want to have a commit hash from a specific commit(which is now on mobile one more click away).

understood, that's fair, I guess it can get used to. mobile is not a workstation anyway (convergence yay)..


> Yeah I wanted to some work on commit signing status but got stalled by school, but now it's already merged 🤷🏽.

oh..it's fine then, really. perhaps another time?
thanks for the improvements anyway.

**Pull request merged**
