### PR TITLE
Fix email header X-Gitea-Reason

### LINKED ISSUE #26582: Email header X-Gitea-Reason shows unexpected reason
### Description

When a notification is generated, there there are two similar but slightly different values that affect how the email is formed. Currently we use the action type to select the an email template to execute. This same value is then used as the reason string in both the -Reason and -NotificationReason headers.

e.g. all email notifications send on pull request activities show this header even for comments.
```
X-Gitea-Reason: pull
```

I searched through the Gitea issues and PRs to see if this was by design and I don't think it is. I also checked on some Github messages and they do set the reason to the corresponding action, e.g. push, comment, etc.

### Gitea Version

v1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.41.0

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Self-built from v1.20.2 running from systemd on Ubuntu 22.04

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by corytodd**
The email headers -NotificationReason and -Reason should indicate the action that has occured, not the type of event that originally generated the notification.

Fix #26582

### CODE REVIEW

**Comment by KN4CK3R** [comment]
The change is not better. Now the reason is just `new` for example.

**Comment by corytodd** [comment]
It would be nice to have an additional header to disambiguate between `issue` and `pull` so the reason has proper context. Would that be an acceptable approach? Github headers use `subscribed` which I believe corresponds to Gitea `new`.

In any case I'm open to ideas how to support the idea of a more precise X-Gitea-Reason header. I understand we can modify the email template but in filtering the email body tends to be less accurate than filtering on headers.

**Comment by KN4CK3R** [comment]
Do we have a list what Github / Gitlab uses?

**Comment by corytodd** [comment]
Github - There is a CC address and a matching X-Github-Reason header [1].

> assign: You were assigned to an issue or pull request.
> author: You created an issue or pull request.
> ci_activity: A GitHub Actions workflow run that you triggered was completed.
> comment: You commented on an issue or pull request.
> manual: There was an update to an issue or pull request you manually subscribed to.
> mention: You were mentioned on an issue or pull request.
> push: Someone committed to a pull request you're subscribed to.
> review_requested: You or a team you're a member of was requested to review a pull request.
> security_alert: GitHub detected a vulnerability in a repository you receive alerts for.
> state_change: An issue or pull request you're subscribed to was either closed or opened.
> subscribed: There was an update in a repository you're watching.
> team_mention: A team you belong to was mentioned on an issue or pull request.
> your_activity: You opened, commented on, or closed an issue or pull request.

Gitlab - There is a X-GitLab-NotificationReason [2] header 

> own_activity
> assigned
> review_requested
> mentioned
> subscribed

as well as a X-GitLab-(Resource)-ID [3] header to disambiguate the reason.

> Issue
> MergeRequest
> Commit

The X-GitLab-(Resource)-ID header might be nice.

[1]: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#filtering-email-notifications
[2]: https://docs.gitlab.com/ee/user/profile/notifications.html#x-gitlab-notificationreason
[3]: https://docs.gitlab.com/ee/user/profile/notifications.html#email-headers-you-can-use-to-filter-email

**Comment by puni9869** [comment]
@techknowlogick  pinging for this PR.

**Comment by lunny** [comment]
So maybe we could follow what github did in this PR?

**Pull request closed without merging**
