### PR TITLE
Add `is_archived` option for issue indexer

### LINKED ISSUE #32697: Pull Requests view shows PRs in archived repos
### Description

The Pull Request view serves as a TODO list of sorts.  It's quite nice.  However, it gets cluttered up when partial tickets are still open when a dead project is archived.

Steps to reproduce:

* Have a team (org) with a repository
* One of your team members opens a PR
* Comment on the PR
* Archive the repository
* Open the Pull Request view
* Choose the "Reviewed by you" menu option
* See the PR that can no longer be closed

I don't know if this affects all of the Pull Request menu options.  While writing up this report, I noticed that it affects the Issues ("Mentioning you" and "Created by you") views, too.

These things are not actionable, and I guess they will live forever.  So, could we exclude them from the lists and the counts?

I think a workaround is to close everything manually before archiving a dead project repo.  Is that what we should do?

Thanks!

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

PR view showing a partial PR in a dead (archived) repo:

image

Issue view showing multiple open issues from that same dead (archived) repo:

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

self hosted container

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by yp05327**
Try to fix #32697

Reason:
`is_archived` is already defined in the query options, but it is not implemented in the indexer.

### CODE REVIEW

**Comment by lunny** [comment]
You need update the index once a repository changed from/to archived.

**Review by delvh — APPROVED** [review]
Why is the PR WIP?
LGTM otherwise.

**Comment by yp05327** [comment]
I only tested the DB indexer manually. Others are not tested manually.

**Comment by lunny** [comment]
unarchived should also trigger the index rebuilding.

**Review by Zettat123 — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
The index will be used both in global search and repository search. In the archived repository, it should be searched. But from a global issue search, the issues in the archived repositories should not be displayed.

**Review by lunny — APPROVED** [review]

**Pull request merged**
