### PR TITLE
Add missing exclusive in advanced label options

### PR DESCRIPTION
**Pull request by LucaZulberti**
Hi, I think these changes could be useful for default labels when creating new repos.

The PR includes the following changes:
 - Add missing exclusive flag for Kind/ scope in labels.
 - Move Breaking label into new Compat/ scope.

### CODE REVIEW

**Comment by lafriks** [comment]
Kind/* should not be exclusive but I agree on moving breaking to different category

**Comment by LucaZulberti** [comment]
May non-exclusive labels also be displayed with scoped colour boxes as exclusive ones?

**Comment by lafriks** [comment]
Yes, I would like that also, there is issue for this #23665

**Comment by denyskon** [comment]
@LucaZulberti Could you adapt your PR to only move breaking label? The label style change can then be addressed in another PR

**Comment by LucaZulberti** [comment]
Done ;-)

**Review by denyskon — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
