### PR TITLE
Add missing History link to directory listings

### PR DESCRIPTION
**Pull request by decke**
The feature to list commits from a subdirectory is already there but
so far the history link to it was missing. There is a History button
in the view_file.tmpl already so avoid showing two history buttons in
that case.

The GitHub webinterface has the same History button in the same place
so this makes gitea a little bit more compatible.

Signed-off-by: Bernhard Froehlich <decke@bluelife.at>

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by daviian — COMMENTED** [review]
I think the button should be added to the "New File" and "Upload File" button group instead.

**Review by appleboy — APPROVED** [review]

**Comment by decke** [comment]
I will try to move the history button to the file actions and update the pull request.

**Comment by lunny** [comment]
@decke any update?

**Comment by decke** [comment]
I'm currently on a business trip and will provide an update when I am back. Sorry for the delay.

**Comment by decke** [comment]
That squashing didn't seem to work out properly. I will close this PR and create a new one.

**Pull request closed without merging**
