### PR TITLE
Renaming OSX to macOS

### PR DESCRIPTION
**Pull request by Fastidious**
Using the current name of the OS (and hopefully, the last, for a while).

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by tboerger** [comment]
You have changed the .Icon line

**Comment by Fastidious** [comment]
@tboerger, I did not change it. I simply renamed the file (using GitHub, through the web browser, that is), and submitted a PR -- did the same for `gogs`, which has been already accepted. Maybe we have found a GitHub bug?

**Comment by lunny** [comment]
It should be a github's bug.

**Comment by andreynering** [comment]
LGTM

**Comment by lunny** [comment]
No. See @tboerger 's comment.

**Comment by Fastidious** [comment]
@lunny I opened the file with `vim` and the `^M^M` are still present. You can check it yourself.

**Comment by lunny** [comment]
I think you have to do the operation on your git command. I have tested it myself, it works. see https://github.com/lunny/gitea/commit/20481ab5acebf4447fc4b4bfff560165e2a9629f

**Comment by lunny** [comment]
@Fastidious, do you mind to pick my commit to this PR?

**Comment by Fastidious** [comment]
@lunny I would, if I knew how. 😄

**Comment by lunny** [comment]
Just check rightbar here to allow maintainers push.

**Comment by lunny** [comment]
@Fastidious please confirm.

**Comment by lunny** [comment]
Why close this one? It seems I have pushed the correct commit?

**Pull request closed without merging**
