### PR TITLE
Update to mod enabled version goquery

### PR DESCRIPTION
**Pull request by sapk**
Changelog: https://github.com/PuerkitoBio/goquery/compare/ed7d758e9a34...v1.5.0

### CODE REVIEW

**Comment by lafriks** [comment]
Build fails

**Comment by guillep2k** [comment]
> 
> 
> Build fails

@lafriks @sapk I'm having the same problem in #7767 ;
```
Please run 'make vendor' and commit the result:
diff --git a/vendor/modules.txt b/vendor/modules.txt
index 020e50b98..ade08e5b4 100644
--- a/vendor/modules.txt
+++ b/vendor/modules.txt
@@ -400,7 +400,7 @@ golang.org/x/text/internal/language/compact
golang.org/x/text/internal/utf8internal
golang.org/x/text/runes
golang.org/x/text/internal/tag
-# google.golang.org/appengine v1.6.1
+# google.golang.org/appengine v1.6.2
google.golang.org/appengine/cloudsql
google.golang.org/appengine/urlfetch
google.golang.org/appengine/internal
make: *** [Makefile:192: test-vendor] Error 1
```

`make vendor` does not render any differences.

**Comment by sapk** [comment]
I had too much confidence on a simple git rebase over master :smile:. I will redo the step in https://github.com/go-gitea/gitea/issues/8019#issuecomment-525900202 and should be good.

**Comment by sapk** [comment]
Or not

**Comment by guillep2k** [comment]
> 
> 
> Or not

@sapk I was about to tell you. That change is already merged and in my case, merging from it didn't help.

**Comment by sapk** [comment]
What is strange is that google.golang.org/appengine v1.6.2 is not referenced in any go.mod

**Comment by sapk** [comment]
Yes but I can find a way to force the update on my machine...

**Comment by sapk** [comment]
Yes I try to set GOPROXY to the one from CI but with no luck. I updated manually the module.txt

**Comment by guillep2k** [comment]
I'll try that myself.

**Review by lunny — APPROVED** [review]

**Review by typeless — APPROVED** [review]

**Pull request merged**
