### PR TITLE
Issue and Pulls lists rework

### PR DESCRIPTION
**Pull request by silverwind**
Reorganized and restyled the issue and pull request lists.

image
image
image
image

### CODE REVIEW

**Comment by mrsdizzie** [comment]
This looks great could these be incorporated into https://github.com/go-gitea/gitea/blob/master/templates/user/dashboard/issues.tmpl too?

**Comment by silverwind** [comment]
@mrsdizzie did just that:

Screen Shot 2020-11-17 at 19 40 10
Screen Shot 2020-11-17 at 19 40 20

**Comment by lunny** [comment]
The link for issue creator is not differ from other texts?

**Comment by silverwind** [comment]
It's following GitHub design where those links are also not colored unless hovered but I guess we could diverge from that design a bit as I generally think links should be distinguishable. Will think about it.

**Comment by 6543** [comment]
what about using different octicons on pulls?

**Comment by silverwind** [comment]
> what about using different octicons on pulls, so you know if it's a pull or an issue?

That should already be the case, see:

https://github.com/go-gitea/gitea/pull/13594/files#diff-511ca3487e2c8c1cb1c144ad5cfe6189bceb0da2ee7ae47d7ae578fa92e12cc3R13-R29

**Comment by silverwind** [comment]
@lunny I think it's fine if we not color those links for aesthetic reason and to draw the attention to the  title instead.

**Comment by 6543** [comment]
@silverwind I think only one thing is missing: fix/refactor issue-pull list of milestones:
Bildschirmfoto zu 2020-11-24 21-00-31

**Comment by silverwind** [comment]
Milestone list fixed as well: 

image

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by silverwind** [comment]
While diffing the milestone list I found two differences to issue lists:

1. Milestones don't render
2. The link on labels does not include the `milestone=id` query

I fixed those differences now by introducing a new `merge` template helper which is basically a superiour version of the `dict` helper which preserves the root "dict" and merges additional values into it. This will allow us to more easily consolidate slightly differing templates into the future.

**Comment by lafriks** [comment]
🚀

**Pull request merged**
