### PR TITLE
Don't replace underscores in auto-generated IDs in goldmark

### LINKED ISSUE #12196: Replacement of underscores with dashes in auto-generated IDs for titles in markdown doesn't match Github
- Gitea version (or commit ref): 1.12.1
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/annelauref/underscore
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
In Markdown files, during the generation of the IDs for titles Gitea replaces underscore ( _ ) with dashes ( - ).
Github doesn't do that.
The impact is that links will be broken for repos with remotes on both Gitea and Github (or mirrors).

## Screenshots
on gitea:
image

on github:
image

### PR DESCRIPTION
**Pull request by zeripath**
Fix #12196

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Technically this is breaking.

**Review by mrsdizzie — APPROVED** [review]

**Comment by silverwind** [comment]
Are these underscores coming out of Goldmark like that or are we actually replacing them elsewhere ourselves? I have a suspicion that the latter is the case and then this fix may not be right.

**Comment by zeripath** [comment]
@silverwind this is the place we replace them in goldmark. Outside of goldmark we simply assert that ids need the prefix user-content-

**Comment by silverwind** [comment]
So they are coming out like that of Goldmark?

**Comment by zeripath** [comment]
We have to protect ids - without prefixing these how do you propose this?

**Comment by zeripath** [comment]
FYI IDs are generated within our variant of goldmark using:

https://github.com/go-gitea/gitea/blob/29ac1f91223d020cd82f7d4dcb84cebec320b721/modules/markup/markdown/goldmark.go#L197-L217

Goldmark's default generator is:

https://github.com/go-gitea/gitea/blob/29ac1f91223d020cd82f7d4dcb84cebec320b721/vendor/github.com/yuin/goldmark/parser/parser.go#L75-L115

when I moved us to Goldmark that generator was significantly different from our previous blackfriday generator therefore to make the changes as non-breaking as possible I created the above one.

---

Going back to why we have to prefix IDs:

I cannot stress this enough, we absolutely have to prefix ids. 

Github also does this. 

Our JS code and our CSS relies on IDs in several places - if you do not prefix user content ids you will get conflicts with multiple ids and will break rendering and potentially create security holes.

**Comment by silverwind** [comment]
> we absolutely have to prefix ids.

I never understood the reason behind this. Why are user-generated ids so bad?

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
