### PR TITLE
Add releases/latest{file} route

### PR DESCRIPTION
**Pull request by dboreham**
Possible partial fix (the "download url for latest release" part) for https://github.com/go-gitea/gitea/issues/3712
Draft PR posted for comment, tests currently missing.

### CODE REVIEW

**Comment by JakobDev** [comment]
`{repo}/releases/latest` is already a existing download link. So you should use `{repo}/releases/latest/{filename}` instead of `{repo}/releases/download-latest/{filename}`. A big problem I see here, is that many Projects tend to include the Version on the filename.

**Comment by dboreham** [comment]
I don't think `{repo}/releases/latest` works here because it only redirects to the specific release page.
It doesn't allow for downloading a named artifact from the latest release, like:

```
$ curl http://gitea.local:3000/org/repo/releases/download-latest/file
```

**Comment by JakobDev** [comment]
I know, that currently you can't download through `{repo}/releases/latest`, as it's only a redirect. I was suggest, that you use `{repo}/releases/latest/{file}` instead of `{repo}/releases/download-latest/{file}`as route in this PR, as this is more intuitive.

**Comment by dboreham** [comment]
> I was suggest, that you use `{repo}/releases/latest/{file}` instead of `{repo}/releases/download-latest/{file}`as route in this PR

I didn't do that because the download route seems to be subject to different auth checks and I don't understand enough about the routing library to know if that would be problematic. But if you think it's ok, it's fine with me.

**Comment by dboreham** [comment]
Pushed a commit that changes the path to `{repo}/releases/latest/{file}`.
Manually tested. Auth works as expected (unauthenticated access to `{repo}/releases/latest/{file}` is permitted while still disallowed to `{repo}/releases/latest`).

Now looking at how to add a test...

**Comment by dboreham** [comment]
I found existing tests here: https://github.com/go-gitea/gitea/blob/main/tests/integration/api_releases_test.go but doesn't look like there is a test for download already. I will look at adding one for the existing download, and the latest release download code added in this PR.

**Comment by silverwind** [comment]
Should we expose the new link on UI somewhere?

**Comment by dboreham** [comment]
> Should we expose the new link on UI somewhere?

I'm not sure. GH just documents this (search for "Linking to the latest release").

**Comment by silverwind** [comment]
A test would be nice, likely in `tests/integration/release_test.go`.

**Comment by dboreham** [comment]
Closing because [this PR](https://github.com/go-gitea/gitea/pull/26748) has already been merged. It seems to achieve roughly the same goal, except presumably will cause problems if anyone ever makes a real tag named "latest". This PR handled that case by using a distinct route rather than overloading the meaning of the vTag.

**Pull request closed without merging**
