### PR TITLE
webhook tag sha fix (#286)

### LINKED ISSUE #286: Add commit sha to create tag webhook payload
- Gitea version (or commit ref): - (latest gogs tested 0.9.99)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite

## Description
Drone 0.5 can not support tag hooks from Gitea when no commit sha is present in the webhook payload.
Drone needs the commit sha to request the `.drone.yml` config file through the Gitea API.

Drone issue link: https://github.com/drone/drone/issues/1870

Desired webhook payload:
```diff
{
+ "sha": "940bd336248efae0f9ee5bc7b2d5c985887b16ac",
  "ref": "v1.0.0",
  "ref_type": "tag",
  "repository": {
    "id": 1,
    "owner": {
      "id": 1,
      "username": "gordon",
      "full_name": "Gordon the Gopher",
      "email": "gordon@golang.org",
      "avatar_url": "https://secure.gravatar.com/avatar/8c58a0be77ee441bb8f8595b7f1b4e87"
    },
    "name": "hello-world",
    "full_name": "gordon/hello-world",
    "description": "",
    "private": true,
    "fork": false,
    "html_url": "http://gogs.golang.org/gordon/hello-world",
    "ssh_url": "git@gogs.golang.org:gordon/hello-world.git",
    "clone_url": "http://gogs.golang.org/gordon/hello-world.git",
    "default_branch": "master",
    "created_at": "2015-10-22T19:32:44Z",
    "updated_at": "2016-11-24T13:37:16Z"
  },
  "sender": {
    "id": 1,
    "username": "gordon",
    "full_name": "Gordon the Gopher",
    "email": "gordon@golang.org",
    "avatar_url": "https://secure.gravatar.com/avatar/8c58a0be77ee441bb8f8595b7f1b4e87"
  }
}
```

### PR DESCRIPTION
**Pull request by bkcsoft**
Fixes #286 
Depends on go-gitea/go-sdk#21 ~(**Don't merge** before I've vendored it!)~

Tag-hooks are pretty useless without specifying which shasum the new tag points at, this PR fixes that :)

Question: ~Should we also send the Shasum for "create branch"-events? (need to add another line in that case ^.^ )~ Yes

### CODE REVIEW

**Comment by strk** [comment]
Why not ?
LGTM, but I guess you'll need to also add the vendor/ update once upstream is fixed (before merging this)

**Comment by bkcsoft** [comment]
@strk Not sure if we need it for new branches? and yes, need to vendor, but waiting for dep to be merged first :)

**Comment by lunny** [comment]
ci failed. and it seems your code is not the latest master.

**Comment by tboerger** [comment]
Just bump it with a comment when everything is done.

**Comment by bkcsoft** [comment]
@tboerger @lunny done :)

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
