### PR TITLE
Improve error feedback for duplicate deploy keys

### LINKED ISSUE #13110: Adding deploy key with duplicate name: unclear error message
- Gitea version (or commit ref): 845d0afb3326f147dc78059bbdcecf45c3a9a0df
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Gitea only displays a HTTP 500 error page when the user attempts to add a deploy key that has the same name as an existing key (the keys themselves are different). I'd like to work on the displaying of a more informative error message when this occurs.

## Screenshots

image

### PR DESCRIPTION
**Pull request by chrisshyi**
Instead of a generic HTTP 500 error page, a flash message is rendered with the deploy key page template to inform the user that a key with the intended title already exists. Resolves #13110

### CODE REVIEW

**Comment by zeripath** [comment]
Hi thanks for the PR!

Could you add handling to `routers/api/v1/repo/key.go:172-183:func HandleAddKeyError(ctx *context.APIContext, err error) {` too?

**Review by 6543 — APPROVED** [review]
:+1:

**Comment by zeripath** [comment]
also I suspect that we need to "handle" more of the "expected" errors  in `models/user.go:1751-1772:func addLdapSSHPublicKeys(usr *User, s *LoginSource, sshPublicKeys []string) bool {` but that could be a different PR. (Mostly switching them to `log.Trace(...)` instead of `log.Error(...)`

**Comment by 6543** [comment]
I'm fine with as is and yes it's true there could be handled more of that stuff witch is currently not

**Review by 6543 — APPROVED** [review]

**Comment by chrisshyi** [comment]
> Could you add handling to routers/api/v1/repo/key.go:172-183:func HandleAddKeyError(ctx *context.APIContext, err error) { too?

Already did!

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by chrisshyi** [comment]
> also I suspect that we need to "handle" more of the "expected" errors in models/user.go:1751-1772:func addLdapSSHPublicKeys(usr *User, s *LoginSource, sshPublicKeys []string) bool {

I'll see if I can tackle that in another PR. Thank you both for the speedy review!

**Pull request merged**
