### PR TITLE
Fix lfs preview bug (#14428)

### PR DESCRIPTION
**Pull request by 6543**
Backport #14428

### CODE REVIEW

**Comment by zeripath** [comment]
Are you sure that this needs a backport? 1.13 just has GoGit.

**Comment by 6543** [comment]
@zeripath I dont think it has to do with NoGoGit ... since code aroud this is ~2years old ... and your change didn't cange modules/lfs/pointers.go (lfs.ReadMetaObject) ...

**Comment by 6543** [comment]
@zeripath -> https://github.com/go-gitea/gitea/blame/master/modules/lfs/pointers.go#L68

**Comment by zeripath** [comment]
ah it's the storage changes.

**Review by zeripath — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
