### PR TITLE
Update emoji regex

### PR DESCRIPTION
**Pull request by mrsdizzie**
Replace regex matching with string index matching from our existing list of known emoji. This makes it more performant and now accurately matches two emoji next to each other (previously didn't always know the difference between two emoji and one emoji made up of two separate emoji)

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
looks not bad, hope it does not comsume mouch mem ...
... emoji at all eat mem 😅 throu it should be worth it 🍏

**Comment by lafriks** [comment]
Looks good. Can't we use finding `:` characters and doing map key lookup for text between them?

**Review by lafriks — APPROVED** [review]

**Comment by mrsdizzie** [comment]
@lafriks this one isn't for short codes -- it is for unicode points for literal emoji

The short code one already does do that, finds the text between : and then does a map lookup.

**Comment by mrsdizzie** [comment]
I think this should be back port to 1.12 also since it fixes some code not released yet

**Comment by zeripath** [comment]
make lg-tm work

**Comment by zeripath** [comment]
When you're quite ready LGTM...

**Comment by zeripath** [comment]
@mrsdizzie I think you're right. I've marked this as kind/bug too.

**Comment by zeripath** [comment]
Please send backport

**Pull request merged**
