### PR TITLE
Prevent a user with a different email from accepting the team invite

### PR DESCRIPTION
**Pull request by jackHay22**
## Changes
- Fixes the case where a logged in user can accept an email invitation even if their email address does not match the address in the invitation

### CODE REVIEW

**Comment by wxiaoguang** [comment]
What's the reason behind this change?

Suppose:

1. A user uses email my-a@domain.com
2. They gets an invitation
3. They changes its email to my-b@domain.com
4. They wants to accept the invitation

I guess it is expected behavior?

**Comment by jackHay22** [comment]
> What's the reason behind this change?

This change fixes the case where a user is logged into a different account than expected and accepts the invitation. Since the invitation is issued for an explicit email, this check should be enforced.

> I guess it is expected behavior?

I think the expected behavior is for the user to get a new invitation with the updated email. This allows the invitation to be more explicit about the invitation recipient's address.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
> What's the reason behind this change?
> 
> Suppose:
> 
>     1. A user uses email [my-a@domain.com](mailto:my-a@domain.com)
> 
>     2. They gets an invitation
> 
>     3. They changes its email to [my-b@domain.com](mailto:my-b@domain.com)
> 
>     4. They wants to accept the invitation
> 
> 
> I guess it is expected behavior?

Since the email is sent to the original email address, we should limit the link just for that email address. If he changed his email, a new invitation link should be sent.

**Comment by wxiaoguang** [comment]
Agree to revert.

**Pull request merged**
