### PR TITLE
Display tags in commit table UI

### LINKED ISSUE #20167: Highlight/mark tags and branches in commit view
### Feature Description

When showing the list of commits, it would be nice to have a sign/mark indicating when a given commit matches a tag or branch. I have not seen this in any git GUI, however newer command line version do this.

### Screenshots

view-tags

### PR DESCRIPTION
**Pull request by lunny**
Fix #20167

### CODE REVIEW

**Comment by silverwind** [comment]
Think this classifies as a feature.

**Comment by silverwind** [comment]
We may want to refactor the commits table to no longer be a `table`, but a flexbox list.

Also, this is WIP, it's not adding UI yet.

**Comment by silverwind** [comment]
Watch https://github.com/go-gitea/gitea/pull/24423.

**Comment by lunny** [comment]
should be replaced by #24755

**Comment by silverwind** [comment]
I hope I can get back to commit list rework soon, then we can talk about this feature.

**Pull request closed without merging**
