### PR TITLE
Limit clone depth when drone-building

### PR DESCRIPTION
**Pull request by strk**
Drone agents don't need to clone the whole history to run tests.
Last 50 commits must be enough to find the one needed for test
(would break if Drone starts after more than 50 commits have been
pushed)

### CODE REVIEW

**Comment by sapk** [comment]
LGTM

**Comment by sapk** [comment]
This will need a new-sign (cc @lunny ?)

**Comment by lunny** [comment]
@sapk done.

**Comment by lunny** [comment]
LGTM

**Pull request merged**
