### PR TITLE
Replace `interface{}` with `any`

### PR DESCRIPTION
**Pull request by silverwind**
Result of running `perl -p -i -e 's#interface\{\}#any#g' **/*` and `make fmt`.

Basically the same [as golang did](https://github.com/golang/go/commit/2580d0e08d5e9f979b943758d3c49877fb2324cb).

### CODE REVIEW

**Review by delvh — APPROVED** [review]
LGTM as soon as the CI passes.
Unfortunately, it is potentially not as easy as that (but the CI will show that): https://stackoverflow.com/questions/71628061/difference-between-any-interface-as-constraint-vs-type-of-argument

**Comment by silverwind** [comment]
It seems `gofmt` can do this as well with rewrite rules, I will try that as well, if it works, `make fmt` will automatically fix these.

**Comment by silverwind** [comment]
I don't think I'll chase this further to autofix via `make fmt` because it would mean we have to run the two formatters back to back, something which I'm absolutely not fond of doing.

**Comment by silverwind** [comment]
> LGTM as soon as the CI passes. Unfortunately, it is potentially not as easy as that (but the CI will show that): https://stackoverflow.com/questions/71628061/difference-between-any-interface-as-constraint-vs-type-of-argument

I guess the difference should hopefully not matter, but there is a certain risk of runtime error, so I'll also try to review the changes for any usage inside generic functions.

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
I will do the same on the 1.20 branch, just to make backports easier.

**Pull request merged**
