### PR TITLE
Plural form for changelog

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix: https://gitea.com/gitea/changelog/issues/16

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]

**Comment by guillep2k** [comment]
Ironically, this will need to be backported. 😉

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@guillep2k created two backports

**Comment by techknowlogick** [comment]
Backport is not needed. Changelog tool can generate changelog when in master branch for any changelog

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
:D -> I'll delete backports ...

**Pull request merged**
