### PR TITLE
Attempt to prevent the deadlock in the QueueDiskChannel Test again

### PR DESCRIPTION
**Pull request by zeripath**
This time we're going to adjust the pause tests to only test the right
flag.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by Gusted — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
A new failure:

```
2022/01/27 03:12:30 .../queue/workerpool.go:121:zeroBoost() [W] WorkerPool: 1 (for TestChannelQueue) has zero workers - adding 5 temporary workers for 5m0s
2022/01/27 03:12:30 ...eue/queue_channel.go:150:func1() [W] ChannelQueue: first-channel Terminated before completed flushing
2022/01/27 03:12:30 .../queue/workerpool.go:121:zeroBoost() [W] WorkerPool: 8 (for second-level) has zero workers - adding 1 temporary workers for 5m0s
2022/01/27 03:12:30 ...ueue_disk_channel.go:183:func3() [W] LevelQueue: second-level shut down before completely flushed
2022/01/27 03:12:30 ...disk_channel_test.go:207:func1() [I] pausing
2022/01/27 03:12:31 ...eue/queue_channel.go:150:func1() [W] ChannelQueue: first-channel Terminated before completed flushing
--- FAIL: TestPersistableChannelQueue_Pause (0.75s)
    queue_disk_channel_test.go:449: 
        	Error Trace:	queue_disk_channel_test.go:449
        	Error:      	Handler processing should have stopped
        	Test:       	TestPersistableChannelQueue_Pause
2022/01/27 03:12:31 .../queue/workerpool.go:121:zeroBoost() [W] WorkerPool: 14 (for second-level) has zero workers - adding 1 temporary workers for 5m0s
2022/01/27 03:12:31 ...disk_channel_test.go:207:func1() [I] pausing
2022/01/27 03:12:31 .../queue/workerpool.go:121:zeroBoost() [W] WorkerPool: 18 (for TestChannelQueue) has zero workers - adding 5 temporary workers for 5m0s
FAIL
```

**Comment by zeripath** [comment]
I think this might be sorted now.

**Comment by zeripath** [comment]
Argh! I've still not fixed this!

**Comment by zeripath** [comment]
ah this is another test problem

**Review by lafriks — APPROVED** [review]

**Pull request merged**
