### PR TITLE
Improve scroll behavior when folding files on pull request "files changed" tab

### LINKED ISSUE #23515: Scroll position after marking file as viewed
### Feature Description

When you are reviewing a pull request, it's pretty common in our team to use the great feature of marking files as "viewed". 

When you click viewed the file folds closed. When you have large diffs they have a sticky header and you can still click "viewed" even though you are at the bottom of the file, great!

**The issue now:**
When you mark a file as viewed while at the end of the big file, your scroll position ends up weird because the page got smaller. Now you might have skipped a few files or part of a diff and need to scroll back up to the "next" file. 

**Possible solution:**
My idea was just scrolling the view to the folded file at the moment you mark the file as "viewed". 
Then you would know where you are on the page.

Other suggestions are of course welcome.

In the video below I'm reviewing the docker-compose.yml and mark it as viewed. I expect the next file for me to review to be status.go (because it's the next file vertically). But I land in the middle of a main.go file.

### Screenshots

https://user-images.githubusercontent.com/9765622/225540882-e86b2e5b-7a3d-4015-8aa1-5646baeb18b4.mov

### PR DESCRIPTION
**Pull request by HesterG**
Close #23515 

As described in the issue above, right now when "fold file" icon or "viewed" is clicked to fold files, it will scroll to the position before folding, resulting in confusing file jumping when `scrollY` is greater than certain value(approximately the `offsetTop` of current diff file header). This PR is to adjust scrolling behavior when folding the files (no scrolling when expanding the files).

Files can be folded in two ways: clicking viewed or clicking "fold file" icon. The folding of these two behaviors will be a little different in this PR(which can be discussed):

1. If folded by clicking "fold file" icon and the `scrollY` is greater than current diff file header, scroll to header of the folded file.
2. If folded by clicking "viewed" checkbox and the `scrollY` is greater than current diff file header, scroll to next file. 

File folding behavior after this PR:

https://user-images.githubusercontent.com/17645053/226501035-cd8208b4-62a5-40e0-8dde-19dcf6eeb42c.mov

Update:

Make the behavior the same in both cases(first behavior)

https://user-images.githubusercontent.com/17645053/226550527-8b76fd9a-02d1-4f64-8063-248bafb929c4.mov

### CODE REVIEW

**Comment by gempir** [comment]
I think behaviour 1. is great. 

But 2. looks a little odd to me. I think when a user clicks on an UI element and then suddenly that UI element is gone from his view he might be confused. Ideally the filled checkbox of "viewed" would still be directly under the cursor of the user. 
This costs a little more space, but gives the user feedback on his change in a way.


At least that sounds more intuitive behaviour to me, no?

**Comment by HesterG** [comment]
> I think behaviour 1. is great.
> 
> But 2. looks a little odd to me. I think when a user clicks on an UI element and then suddenly that UI element is gone from his view he might be confused. Ideally the filled checkbox of "viewed" would still be directly under the cursor of the user. This costs a little more space, but gives the user feedback on his change in a way.
> 
> At least that sounds more intuitive behaviour to me, no?

Yes I think so. And I think that means to make them have the same behavior (1st one). Added a commit to change that, please check the update video in description or checkout to try.

**Comment by gempir** [comment]
Don't have the time to check it out locally right now but from the video it looks great! 
I think this makes a ton of sense UI wise and is easy for the user to understand.

Thank you! ❤️

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
There is an alternate ?

* #23702

**Pull request closed without merging**
