### PR TITLE
Fix git hooks update to receive required arguments

### LINKED ISSUE #2090: Git-Hook for update does not get the refname, oldrev, newrev as parameter
- Gitea version (or commit ref): v1.1
- Git version: 2.10.1 (Apple Git-78)
- Operating system: OSX/Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Hi, I have tested some simple scripts from here:

> https://git-scm.com/book/uz/v2/Customizing-Git-An-Example-Git-Enforced-Policy 

and put that as update-hook via Git-Hooks->update

```ruby
#!/usr/bin/env ruby

$refname = ARGV[0]
$oldrev  = ARGV[1]
$newrev  = ARGV[2]
$user    = ENV['USER']

puts "Enforcing Policies..."
puts "(#{$refname}) (#{$oldrev[0,6]}) (#{$newrev[0,6]})"
```

But it seems that the ARGV is empty.

Also a very simple

```bash
#!/bin/bash
echo "$1 $2 $3"
```

doesn't print out anything.

From where in the "hook call" of gitea I will be able to read the refs?

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #2090

* Changed migration calling so that migrations can use models package

### CODE REVIEW

**Comment by lunny** [comment]
@lafriks any chance to integrate your test codes on this PR?

**Comment by bkcsoft** [comment]
@lunny unless the test runs `git push` we can't test this :(

**Comment by lunny** [comment]
Oh. This clone test PR #1682 need go1.8

**Comment by lafriks** [comment]
It's not easy to test this as this need clone and later push and parsing push output to check if this

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Pull request merged**
