### PR TITLE
Revamp repo header

### PR DESCRIPTION
**Pull request by denyskon**
Redesign repo header with following new aspects:
- responsive & better-looking repo title
- hide repo button text instead of icons in mobile view
- use same tab style as on explore and org page

<details>
<summary>Before:</summary>

grafik
grafik
grafik
grafik

</details>

<details>
<summary>After:</summary>

grafik
grafik
grafik
grafik

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm I think I still prefer the `user / repo` rendering with bigger font than this two-line thing.

**Comment by denyskon** [comment]
Well if others think the same I can bring it back, but then we'd need a way for it to no longer look horrible on mobile if the repo name is even a bit longer :)

**Comment by JakobDev** [comment]
> show owner displayname instead of username

I'm not a fan of this. The Username is used for all technical purposes (repo url, git clone etc.), s we should show the username instead of the displayname.

**Comment by puni9869** [comment]
I am biased with 
image

horizontal scroller.  
Could you make it like github `...` for mobile approach if the row items are not accomodated in row we will shift them to `...`
image

And I agree with @JakobDev  point we should use the username. Not displayed name.

For `Private` label you can show the lock icon in mobile view. this will use less space.
image


IMO desktop view looks good in gitea, we need to focus on mobile view and Accessibility more.

**Comment by denyskon** [comment]
Alright, so I brought back the one-line-view and showing username instead of display name. Opinions welcome!

grafik
grafik
grafik
grafik
grafik

**Comment by puni9869** [comment]
This hurts my soul for mobile view. Since you are an UI expert, could you do some magic here.` 🪄 `
image

**Comment by denyskon** [comment]
@puni9869 

grafik

What do you think?

**Comment by puni9869** [comment]
😃  Much better, just the `template` icon is should be standard,  Add a tooltip if applicable in mobile view.

Overall looks good.

**Comment by denyskon** [comment]
This is the standard template icon:

grafik

Tooltip added:

grafik

**Comment by silverwind** [comment]
>  Could you make it like github ... for mobile approach if the row items are not accomodated in row we will shift them to ...

Yes we should do this but I think the implementation will be complex as it can not be done in CSS and it needs JS with an [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to dynamically populate the dropdown. I would defer this to another PR.

**Comment by denyskon** [comment]
I agree that we should do it at some point, but to be honest, my JS skills are not good enough to create something that would be maintainable 😆

**Comment by mpeter50** [comment]
Hi!
I have noticed that the empty space around objects have also increased. I think with the exception of [the 2nd "before" image](https://user-images.githubusercontent.com/47871822/277476573-d4117f79-a5f5-4f36-bf65-bbada3e7e73b.png), the margins were better the way it was originally.

Relatively a lot of software projects have adopted huge margins, but I don't think thats a good change. Screens are larger to fit more information nicely, not to have larger empty spaces, and at the same time, not everyone has large screens.
I agree that too small margins would make it a mess, but I don't think that was the case (with the exception of the 2nd "before" image, because of the wrapped button line).

**Comment by denyskon** [comment]
@mpeter50

I also am a fan of small margins as long as you can still visually separate elements without thinking about it. For me, the sheer amount of different elements in that header justifies the big margins, but I can try to play with it a bit and maybe I'll find a better combination

**Comment by lafriks** [comment]
I really dislike that background in repo name

**Comment by denyskon** [comment]
@lafriks I thought it would be a good highlight on hover, but I can remove it if others think the same

**Comment by lafriks** [comment]
Personally it makes it harder to read because of less contrast and the UI too crowded :)

**Comment by denyskon** [comment]
@mpeter50 I reduced the paddings and updated the screenshots.

@lafriks I removed that hover effect

**Comment by denyskon** [comment]
Some more reviews would be nice :) Are there any things left that should be changed?

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
ping for reviewers.

**Review by lunny — APPROVED** [review]

**Pull request merged**
