### PR TITLE
Fix:Circular loading spinner is oval in safari browser

### PR DESCRIPTION
**Pull request by HEREYUA**
**Fix**:[#29041](https://github.com/go-gitea/gitea/issues/29041)

When defining height and aspect-ratio, Safari will calculate the width based on these two values. However, it appears that Safari applies the aspect-ratio based on the total height (which includes border-width), which may cause the total width of the element to be twice the border-width more than the total height. 

image

When defining width and aspect-ratio, it seems that Safari accurately calculates the height based on these two values

image

**Update:**
In the following discussion, we found the same issue  on the webkit bug：https://bugs.webkit.org/show_bug.cgi?id=267625

When absolute positioning is not used on `::after`, the problem mentioned above can be avoided, but this might affect some UI

### CODE REVIEW

**Review by techknowlogick — DISMISSED** [review]
thanks so much!

**Comment by silverwind** [comment]
This will likely break this rule below which only sets height:

https://github.com/go-gitea/gitea/blob/8d55eaff851f397d4f5356a7a303b0b251f366c7/web_src/css/modules/animations.css#L48

Further below it sets both:

https://github.com/go-gitea/gitea/blob/8d55eaff851f397d4f5356a7a303b0b251f366c7/web_src/css/modules/animations.css#L64-L65

So I think we should make all 3 rules the same, either set only 1 dimension, or both in all 3.

Regarding the Safari issue: Does changing `box-sizing` fix it? It sounds like a Webkit bug, check https://bugs.webkit.org/.

**Comment by HEREYUA** [comment]
> This will likely break this rule below which only sets height:
> 
> https://github.com/go-gitea/gitea/blob/8d55eaff851f397d4f5356a7a303b0b251f366c7/web_src/css/modules/animations.css#L48
> 
> Further below, another variant sets both:
> 
> https://github.com/go-gitea/gitea/blob/8d55eaff851f397d4f5356a7a303b0b251f366c7/web_src/css/modules/animations.css#L64-L65
> 
> So I think we should make all 3 rules the same, either set only 1 dimension, or both in all three rules.
> 
> Regarding the Safari issue: Does changing `box-sizing` fix it? It sounds like a Webkit bug, check https://bugs.webkit.org/.

I tried changing box-sizing but it did not solve it, perhaps it would be more appropriate to set both width and height

**Comment by silverwind** [comment]
I think https://bugs.webkit.org/show_bug.cgi?id=244697 might be the related bug.

**Comment by HEREYUA** [comment]
> I think [this](https://bugs.webkit.org/show_bug.cgi?id=244697) might be the related bug, but there are also [others](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&field0-0-0=product&field0-0-1=component&field0-0-2=alias&field0-0-3=short_desc&field0-0-4=status_whiteboard&field0-0-5=content&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&query_format=advanced&type0-0-0=substring&type0-0-1=substring&type0-0-2=substring&type0-0-3=substring&type0-0-4=substring&type0-0-5=matches&value0-0-0=aspect-ratio&value0-0-1=aspect-ratio&value0-0-2=aspect-ratio&value0-0-3=aspect-ratio&value0-0-4=aspect-ratio&value0-0-5=%22aspect-ratio%22).



I might have found the related one in the list you provided：https://codepen.io/legion80/pen/ZEPeLdz
It displays correctly when absolute positioning is not used on `::after`（It has been centered using flex layout）
image

**Comment by silverwind** [comment]
Yes, it's the same bug. It's strange that it only happens with `height` but not `width`. The workaround is likely good but we should add a link comment to the webkit bug and adjust the two subsequent selectors I linked to only set `width`.

**Comment by HEREYUA** [comment]
updated:[3102bd9](https://github.com/go-gitea/gitea/pull/29713/commits/3102bd9fb23d9f59892ab608aa93feab1bd8d974)

**Comment by silverwind** [comment]
Hmm, we need to be really careful with these spinner CSS adjustments, they are used in many places in the UI.

**Comment by HEREYUA** [comment]
You're right, I've already checked everything I could notice about the spinner's CSS, could there maybe be something I've missed?

**Comment by HEREYUA** [comment]
>You're right, could there possibly be something that I've missed in my adjustments? Perhaps we can also opt for minimal changes, just fixing the positioning issue with `::after`, so that even if the `height` and `aspect-ratio` are used together, it won't cause a problem on Safari.

**Comment by HEREYUA** [comment]
> Hmm, we need to be really careful with these spinner CSS adjustments, they are used in many places in the UI.

You're right, could there possibly be something that I've missed in my adjustments? Perhaps we can also opt for minimal changes, just fixing the positioning issue with `::after`, so that even if the `height` and `aspect-ratio` are used together, it won't cause a problem on Safari.

**Comment by silverwind** [comment]
I'd say keep changeset minimal to fix the issue. I think just switching `width` to `height` in the `.is-loading` class and the classes below that extend the selector. There might also be some non-CSS code that adjust height currently, if they exist, they need to switch as well. Also add a comment linking to the webkit bug.

**Comment by HEREYUA** [comment]
> I'd say keep changeset minimal to fix the issue. I think just switching `width` to `height` in the `.is-loading` class and the classes below that extend the selector. 
   updated

> There might also be some non-CSS code that adjust height currently, if they exist, they need to switch as well.
  It seems that no results were found through the `is-loading` search.

>  Also add a comment linking to the webkit bug.
  updated

**Comment by wxiaoguang** [comment]
It breaks the loading UI http://localhost:3000/devtest/gitea-ui

Before:

image


After:

image

**Comment by HEREYUA** [comment]
> It breaks the loading UI http://localhost:3000/devtest/gitea-ui
> 
> Before:
> 
> image
> 
> After:
> 
> image

This seems to be caused by the flexible layout, it doesn't seem to be an effective method to solve

**Comment by silverwind** [comment]
It does reproduce on /devtest, let's see if I find a simpler fix.

image

**Comment by silverwind** [comment]
Found a better workaround: https://github.com/go-gitea/gitea/pull/29801

**Comment by techknowlogick** [comment]
Thanks for your effort in this PR @HEREYUA, I think we'll use the alternative proposed in the other PR. This PR was helpful in progressing towards the solution and is very much appreciated :)

**Pull request closed without merging**
