### PR TITLE
Allow rendering alerts in dashboard

### PR DESCRIPTION
**Pull request by strk**
NOTE: useful when logging in via OpenID and connecting to user

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
Any screenshot? It seems all other files put it below `<div class="twelve wide column content">` except this PR?

**Comment by strk** [comment]
Alert screenshot: 

alert

**Comment by lunny** [comment]
LGTM

**Pull request merged**
