### PR TITLE
Fix #6813: Allow git.GetTree to take both commit and tree names

### LINKED ISSUE #6812: Use runtime/debug for providing the version
Since go1.12 we can get the version from runtime/debug for the main module (gitea itself) and also submodules (lib) we are using. https://github.com/golang/go/commit/45e9c5538b3956d98ef0337fc19ed8d45eb17090

So when we will only support 1.12 and 1.13 we could migrate to this system and clear some makefile and also wiil fix #4782 since we will not rely on env variable.

### LINKED ISSUE #6813: Git Trees API no longer returns absolute paths + fails to find any other sha apart from head.
- Gitea version (or commit ref): eb8632b/master.
- Git version: 2.11.0
- Operating system: N/A.
- Database (use `[x]`): N/A.
- Can you reproduce the bug at https://try.gitea.io: N/A.

## Description
According to https://developer.github.com/v3/git/trees/. The paths returned should be absolute paths like so:
```json
{
  "sha": "fc6274d15fa3ae2ab983129fb037999f264ba9a7",
  "url": "https://api.github.com/repos/octocat/Hello-World/trees/fc6274d15fa3ae2ab983129fb037999f264ba9a7",
  "tree": [
    {
      "path": "subdir/file.txt",
      "mode": "100644",
      "type": "blob",
      "size": 132,
      "sha": "7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b",
      "url": "https://api.github.com/repos/octocat/Hello-World/git/7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b"
    }
  ],
  "truncated": false
}
```

However, the path being returned is only the filename, like so:
```json
{
  "sha": "fc6274d15fa3ae2ab983129fb037999f264ba9a7",
  "url": "https://api.github.com/repos/octocat/Hello-World/trees/fc6274d15fa3ae2ab983129fb037999f264ba9a7",
  "tree": [
    {
      "path": "file.txt",
      "mode": "100644",
      "type": "blob",
      "size": 132,
      "sha": "7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b",
      "url": "https://api.github.com/repos/octocat/Hello-World/git/7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b"
    }
  ],
  "truncated": false
}
```

It doesn't seem to be able to find any other sha than head either:

https://i.imgur.com/rW3mREC.png
https://i.imgur.com/Qdm4S22.png

Commit which introduced this bug: https://github.com/go-gitea/gitea/commit/2af67f6044af1cad7136ce8c123e37ab090ca9bc

modules/git/tree.go

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes two separate bugs reported in #6813:
- Allow git.GetTree to take both commit and tree names; this matches GitHub behavior on the Trees API
- Return full paths on entries listed through Tree.ListEntriesRecursive. Technically this is abuse of the API but I am just doing a hot-fix here. A proper fix would be to move the recursive enumeration to different layer and add unit tests for it.

### CODE REVIEW

**Comment by lafriks** [comment]
Looks like unit tests needs to be updated as well

**Comment by filipnavara** [comment]
I will look into the failures later today. It should not have broken any tests...

**Comment by filipnavara** [comment]
Ah, I propagate wrong SHA into the Tree object now. :/

**Comment by zeripath** [comment]
Hmm...

I  wonder would it better to use:

```go
object, err := repo.gogitRepo.Object(plumbing.AnyObject, plumbing.Hash(id))
if err != nil {
    return nil, err
}
```

And then test the type of the object, if it's a Commit - then grab the Tree, if it's a Tree cool.

If it's a Blob then there's likely nothing we can do

If it's a Tag then we can check the target -> Commit-> Tree, Tree, and so on.

**Comment by filipnavara** [comment]
@zeripath Perhaps. I don't like the code as-is and I like your way of restructuring it a bit more than whatever is in this PR. Then again, before doing any bigger change I would prefer to update the unit tests to test those cases. The tests currently don't test tree hashes, tag hashes (which doesn't work; thanks for pointing it out) or the error case with blob hash.

**Comment by lunny** [comment]
@filipnavara It seems we should also change the test if there is one.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@filipnavara @zeripath that most probably would ok to be in other PR

**Review by zeripath — APPROVED** [review]

**Pull request merged**
