### PR TITLE
Revert en-US locale

### PR DESCRIPTION
**Pull request by lafriks**
Revert wrongly updated `options/locale/locale_en-US.ini` file back to previous version

### CODE REVIEW

**Comment by daviian** [comment]
LGTM

**Comment by bkcsoft** [comment]
Won't this just get changed again by the CI job?

**Comment by lunny** [comment]
@lafriks Maybe we have to fix drone at first if it will update en_US ini file again?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work

**Pull request merged**
