### PR TITLE
Fix sticky header in diff view

### PR DESCRIPTION
**Pull request by silverwind**
Ressurection of #23549.

Fix regression https://github.com/go-gitea/gitea/pull/23513#issuecomment-1474356817 from #23271.
The previous sticky CSS did assume the content is always 2 rows, but since that PR, it's single-row above 993px width.
Adjust the sticky offset to match and add a small tweak that hides content behind the `border-radius`.

Single row:
Screenshot 2023-03-17 at 21 33 05

Double row:
Screenshot 2023-03-17 at 21 32 53

### CODE REVIEW

**Comment by silverwind** [comment]
Left a bit of a mess with the PRs, but this is the one that is the bugfix and it would be nice to have it for 1.19.0 release ideally.

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
Moving to 1.19.0 milestone as this fixes a pretty important bug imho.

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
Yes, while it should be fixed before 1.19.0, it is probably still a good idea to let it target 1.20, so that it is correctly classified.

**Comment by delvh** [comment]
:trumpet: :robot:

**Pull request merged**
