### PR TITLE
Ui correction in mobile view nav bar left aligned items.

### PR DESCRIPTION
**Pull request by puni9869**
As title
From the long time I was looking for this UI, Now its the time to fix it.

Before
image

image

### CODE REVIEW

**Comment by denyskon** [comment]
Ehm... I don't really see a reason to "fix" this. I think it looks better if it is centered.

**Comment by puni9869** [comment]
According to the Ux in mobile view all the nav items are left aligned IMO.

I am open for suggestions.

**Comment by denyskon** [comment]
To me, it looks better to have them centered. If they're all left-aligned, we have A LOT of empty space on the right, which doesn't look good to me. Just my opinion - I won't block if other maintainers disagree with me

**Comment by puni9869** [comment]
@wxiaoguang  any thoughts on this.

**Comment by silverwind** [comment]
I think left-aligned does look slightly better.

**Comment by puni9869** [comment]
> I think left-aligned does look slightly better, but I think it could be done CSS only with `justify-content: flex-start` instead of introducing wrappers. Just need to be careful with the selector.

No doubt this will work but navigation button will defer 
image

Need  to shift the button

**Comment by wxiaoguang** [comment]
> @wxiaoguang any thoughts on this.

I seldom use mobile to work, while maybe "keeping the dropdown menu on mobile" is also a choice, then there won't be alignment or extra-space problem any more.

**Comment by puni9869** [comment]
> > @wxiaoguang any thoughts on this.
> 
> I seldom use mobile to work, while maybe "keeping the dropdown menu on mobile" is also a choice, then there won't be alignment or extra-space problem any more.

Agree.

**Comment by silverwind** [comment]
Looks like a mess. Duplicate classes, wrappers not entirely removed and I recommend adding a `justify-start` helper for this, ideally without `!important` on it.

https://tailwindcss.com/docs/justify-content

**Comment by puni9869** [comment]
> Looks like a mess. Duplicate classes, wrappers not entirely removed and I recommend adding a `justify-start` helper for this, ideally without `!important` on it.
> 
> https://tailwindcss.com/docs/justify-content

worth of giving a try. I am giving a try if tailwind is installed in gitea.

**Comment by silverwind** [comment]
I guess I will soon contribute either tailwind or unocss. Have not decided whether to `!important` those tailwind rules, but I guess it's likely it will have to be to ensure proper overrides of fomantic. So I would not mind if you add the helper with `!important`.

**Comment by wxiaoguang** [comment]
I am sure many helpers are not necessary. For this case, why not just clean up `#navbar .item` ? I do not think it is right to keep overriding styles.

**Comment by wxiaoguang** [comment]
According to my test, the only thing needs to do is to remove the `justify-content: center;`. Feel free to revert my change if it is wrong.

**Comment by puni9869** [comment]
> According to my test, the only thing needs to do is to remove the `justify-content: center;` if you want to make the items left-aligned. Feel free to revert my change if it is wrong. (maybe in the future "keeping the dropdown menu on mobile" is a better choice, then there won't be alignment or extra-space problem any more)

I was about to push this change today, but you did it. already. Thanks a ton.

**Comment by puni9869** [comment]
And thanks for accepting this change from UX perspective.

**Comment by puni9869** [comment]
Tested, look good to me.
🚀

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by puni9869** [comment]
Let's roll 🚀

**Pull request merged**
