### PR TITLE
HTML-escape plain-text READMEs in previews

### PR DESCRIPTION
**Pull request by antiprime**
Previews of plain-text README files are not currently HTML-escaped; this causes issues when READMEs contain characters like `<` and `>`, including constructs like `Copyright 2018 Example <me@example.com>`, which currently renders as `Copyright 2018 Example`.

This PR ensures that plain-text READMEs are HTML-escaped.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by daviian** [comment]
@nickolas360 Does it really work for you? At least it doesn't work for me. Your example renders as you've described after applying your PR.

**Review by daviian — CHANGES_REQUESTED** [review]
~@nickolas360 Does it really work for you? At least it doesn't work for me. Your example renders as you've described after applying your PR.~

**Review by daviian — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@nickolas360 can you please backport this (by cherry-pick 2bb73fe) to release/v1.4?

**Comment by ghost** [comment]
BTW, it's related to #3903 but fix only a part of it.
EDIT: I'm talking about markdown escaping.

**Pull request merged**
