### PR TITLE
Backport translations to v1.21

### PR DESCRIPTION
**Pull request by denyskon**
I manually fixed most of the files so that used translation keys don't get deleted.

### CODE REVIEW

**Comment by lunny** [comment]
Have you generated them via `build/backport-locale.go` ?

**Comment by denyskon** [comment]
I first tried, but for some reason the output of that command produced a lot of unnecessary spacing and quotation changes which according to the feedback in previous PRs may break everything, so I ended up doing it manually.

**Comment by wxiaoguang** [comment]
> which according to the feedback in previous PRs may break everything

That's impossible. The generated ini should be able to be loaded correctly.

**Comment by denyskon** [comment]
All ``` are replaced by `"`. If that's okay I can redo it using the script, however I don't see a reason why.

**Comment by wxiaoguang** [comment]
> All backticks are replaced by double quotes. If that's okay I can redo it using the script, however I don't see a reason why.

Crowdin doesn't recognize backticks. `` key = ` value` `` then Crowdin treats it as ``key = "` value`"``.

The legacy INI package only uses backticks when it is necessary, so `` key = ` val` `` will become ``key = " val"`` when it saves the INI to a file.

**Comment by denyskon** [comment]
Alright, so I now did it using the tool

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
