### PR TITLE
Fix orgs not being displayed on create repo form

### LINKED ISSUE #11258: organization listed multiple times when creating a repository
- Gitea version (or commit ref): 1.11.4
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - see e.g. https://try.gitea.io/org/testMaxOrg/teams 2 teams each with 'Create repository' permission

## Description
If an organization has multiple teams with 'Create repository' permission, then whenever a user belonging to several such teams tries to create a repository they see the organization name listed multiple times under "Owner" (see screenshot). The number of times matches the number of teams they are member of.
This is probably a bug, but at the same time it would be cool if it would show team names here, and the repository would be created and added to that team automatically...

## Screenshots
create

### PR DESCRIPTION
**Pull request by CirnoT**
#11183 prevents the Create Repository dialog from displaying orgs that the user has the createRepository permission on.

Steps to reproduce:

* User 1 creates an organization A
* When User 1 attempts to create a new repository, A should be allowed to be chosen as the owner

The problem is that the function MUST put the Orgs list in to the context before second conditional

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
This fixes the bug for the moment but all of this code needs rationalising

**Review by mrsdizzie — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Comment by guillep2k** [comment]
Fixes #11258

**Comment by lunny** [comment]
Please send back port to v1.11

**Comment by CirnoT** [comment]
Are you sure @lunny? #11183 was not backported and this PR depends on it and simply fixes what it has broken.

@guillep2k I am unsure if this PR or #11183 fixes the mentioned issue as it refers to v1.11, so before original PR landed and broke things.

**Comment by CirnoT** [comment]
Can confirm now that neither of these PR fixes the mentioned issue @guillep2k

**Comment by guillep2k** [comment]
Thank you @CirnoT, I got confused about the issue. 👍

**Pull request merged**
