### PR TITLE
Milestone Link / Buttons visible while usage external issue tracker /…

### PR DESCRIPTION
**Pull request by khmarbaise**
… using issue tracker is turned off (#13779)

 * visibility of milestones links / buttons
   * if issue tracker for repository is turned off
   * or use only external issue tracker.

Signed-off-by: Karl Heinz Marbaise <kama@soebes.de>

### CODE REVIEW

**Comment by jolheiser** [comment]
Labels/milestones are also applied to PRs, though.

**Comment by silverwind** [comment]
May also need to handle `templates/repo/issue/new_form.tmpl`. Oh and please indent after a `if`.

**Comment by khmarbaise** [comment]
> Labels/milestones are also applied to PRs, though.

Hm.. If I have turned off issue tracking at all or using external issue tracking only. Then I would say nothing exists in the gitea repository to relay with milestones cause I suppose milestones would be done outside gitea. The usage of labels sounds like a usable way to apply to an pr... Maybe I misunderstand a thing here.

>  May also need to handle `templates/repo/issue/new_form.tmpl`. 
I will take look at that. Thanks for the hint.

> Oh and please indent after a `if`.
You mean something like the following:
```
{{if not (.Permission.CanRead $.UnitTypeExternalTracker)}}
  <div class="ui divider"></div>
  < div class="ui {{if or (not .HasIssuesOrPullsWritePermission) .Repository.IsArchived}}disabled{{end}} floating jump select-milestone dropdown">
{{end}
```
instead of the this:
```
{{if not (.Permission.CanRead $.UnitTypeExternalTracker)}}
<div class="ui divider"></div>
<div class="ui {{if or (not .HasIssuesOrPullsWritePermission) .Repository.IsArchived}}disabled{{end}} floating jump select-milestone dropdown">
{{end}
```
I can fix that of course.

**Comment by jolheiser** [comment]
I don't know that I agree, and actually sometimes (at least in this specific project) it's the opposite.

We don't always know which milestone an issue will be fixed in, however _all_ PRs get a milestone. That's how we deal with feature freeze, etc.

**Comment by khmarbaise** [comment]
> Users that use external tracking for issues are more likely to be tracking their progress/milestones there as well)

This is exactly the point.

**Comment by lafriks** [comment]
> > Users that use external tracking for issues are more likely to be tracking their progress/milestones there as well)
> 
> This is exactly the point.

Not true, in our company we use external issue tracker and we still extensively use labels and milestones for PR management!

**Review by lafriks — CHANGES_REQUESTED** [review]
This will not allow to use labels and milestones for PRs

**Comment by mrsdizzie** [comment]
Agree this PR doesn't really make sense -- as mentioned above you can (and people do) use milestones for PRs regardless of issue tracker. 

If you don't want to see the links you could remove them with a custom template or script.

**Comment by khmarbaise** [comment]
Ok. No problem. Would be a configuration element a solution to make that configurable? I understand that other projects have different requirements/setups etc. ?

**Comment by lafriks** [comment]
I would not mind settings in repository settings "Enable labels" and "Enable milestones" that are enabled by default

**Comment by lunny** [comment]
@khmarbaise If you also disable pull request, then the milestone will be disappeared.

**Comment by khmarbaise** [comment]
> @khmarbaise If you also disable pull request, then the milestone will be disappeared.

But that is exactly what I'd like to keep to use pull requests.

So it would be a way to go to introduce separate configuration for labels and milestones which are enabled by default. 

So I will close this PR and create a issue to introduce configuration elements for labels and milestones.

**Pull request closed without merging**
