### PR TITLE
Docker: Rework

### PR DESCRIPTION
**Pull request by Kreyren**
# !!! DO NOT MERGE !!!

---

I've reworked the docked backend, because i needed a more flexible development environment.

Do you want this in gitea? I would polish it more prior to merge and implement handling for other databases. ^-^

The important files are:
- https://github.com/go-gitea/gitea/pull/14626/files#diff-7056ac181b6ee63e9510d8b82a9be9d372e8d2d01e207f893d29bb184e4b133b
- https://github.com/go-gitea/gitea/pull/14626/files#diff-aaccb0b91d60e80a8b88404e3e0109604f5ea6e4ed73825aa360a0043f81dd36

Blocked by: https://github.com/go-gitea/gitea/pull/14644 (This Merge Request will be finished after this one assuming that upstream wants it)

## TODO
- [x] Upstream wants to merge this
- [ ] Handling of user and group
	- [ ] Do a research to see whether we want to segregate the UNIX permission e.g. standalone group handling repositories
	- [ ] Build caching
		- [ ] User
			- [ ] User name
			- [ ] UID
			- [ ] Home location
		- [ ] Group
			- [ ] Group Name
			- [ ] GID
		- [ ] Add user to the group
	- [ ] Runtime configuration
		- [ ] User, change the build-configured X as needed
			- [ ] X=User name
			- [ ] X=UID
			- [ ] X=Home location
		- [ ] Group, change the build-configured X as needed
			- [ ] X=Group name
			- [ ] X=GID
	- [ ] Complies with expectations in https://github.com/go-gitea/gitea/pull/14785
- [ ] Resolve DNM tags
- [ ] Peer-review by docker community
- [ ] Automatization
	- [ ] Optimize Continuous integration (CI)
		- [ ] Hadolint
		- [ ] Shellcheck
	- [ ] Optimize Continuous Delivery (CD)
		- [ ] Publish docker container on merged update
	- [ ] Peer-review by DroneCI community
- [ ] Update documentation
	- [ ] Consider blaming Golang devs to improve godoc inspired by rustdoc.
	- [ ] Proof-reading
- [ ] Certificate of origin

---

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.

Done - Krey

2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md

To comply with https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#discuss-your-design:

This implement handling through variables allowing to change the file hierarchy and used configuration during a build time and on runtime through the use of `docker-compose` on which it does not have hard dependency (uses script that generates the config from variables that is called from docker-compose's `command` otherwise it uses `gitea web`)

It's designed to avoid maintaining two dockerfiles to make the maintenance more efficient by avoiding duplicate code through utilizing FHS3_0 service directory in alpine image to allow root and rootless run with option to run in a sandbox (e.g. chroot) within a docker environment.

To comply with https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-dco:

Will be provided prior to non-draft merge request

3. Describe what your pull request does and which issue you're targeting (if any)

Originally designed to test implementation to r e s o l v e https://github.com/go-gitea/gitea/issues/14562 intended to provide multiple services in a dockerfile to make sure that the implementation works with supported databases and to implement tests.

### CODE REVIEW

**Comment by kdumontnu** [comment]
Thanks for contributing! Can you explain what you mean by wanting more flexibility?

I've been doing some work recently on my own docker environment. I'm quite happy with how it's ended up, so I thought I might share in case you find it useful.

What I needed was to be able to deploy to multiple environments (development, staging, production) with CI, using rev-managed configurations. I figure I will share my solution here in case it helps you.

- I packaged this [util function](https://github.com/go-gitea/gitea/pull/9519) in my docker file by adding the following to dockerfile:
```
RUN go build contrib/environment-to-ini/environment-to-ini.go
...
COPY --from=build-env /go/src/code.gitea.io/gitea/environment-to-ini /usr/local/bin/environment-to-ini
```
This takes any environment variables in the form: `GITEA__section-name__KEY-NAME` and sets them in `app.ini` - super helpful!

- I use multiple docker-compose files to mix in the settings I want using .env files. For example:
```
TAG="${DRONE_COMMIT_SHA:0:7}" docker-compose \
        -f docker-compose.yml \
        -f docker-compose.staging.yml \
        -f docker-compose.mailer.yml up -d
```
If I want to enable the mailer I just add the mailer config file above. For instance, the mailer config looks like this:
```
version: "3"
# Use this mixin to add smtp mail server
services:
  server:
    environment:
    - GITEA__mailer__ENABLED=true
    - GITEA__mailer__FROM=${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
    - GITEA__mailer__MAILER_TYPE=smtp
    - GITEA__mailer__HOST=${GITEA__mailer__HOST:?GITEA__mailer__HOST not set}
    - GITEA__mailer__IS_TLS_ENABLED=true
    - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
    - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
```
 - Finally, my endpoint (`/etc/s6/gitea/setup`) is changed to:
```
environment-to-ini --config ${GITEA_CUSTOM}/conf/app.ini \
                   --prefix "ALLSPICE"
chown ${USER}:git ${GITEA_CUSTOM}/conf/app.ini
```

I left all of the s6 stuff pretty much as is because I don't know much about it. Curious if you don't think it's useful.

Currently, I'm trying to make the same process work with rootless docker.

**Comment by Kreyren** [comment]
> Thanks for contributing! +1 for shellcheck. @kdumontnu 

Also hadolint (https://github.com/hadolint/hadolint) which is fork of shellcheck designed to be used in dockerfiles.

> Can you explain what you mean by wanting more flexibility? @kdumontnu

I find the current design too limiting as it makes it difficult to deploy multiple gitea instances with different configuration files and databases for testing purposes.

So this way it's generating the `app.ini` on runtime through the use of `gitea-wrapper.sh` only if the command is specified to use the wrapper otherwise it calls the gitea executable.

Note that currently this design is not meant to be used for production as it's depending on `COPY . $GOPATH/code.gitea...`. I want to do more research on that after https://github.com/go-gitea/gitea/pull/14644 is merged so that it can either use the local source code or fetch the remote where the idea is just giving people `docker-compose.yml` file to run `docker-compose up` and get gitea deployed.

I also find it too limiting to have it depending on volumes so i've designed it to use FHS3_0 service directory (/srv/gitea) that allows for root/rootless without the need for second dockerfile and if desired the service operators can define volumes through docker-compose.

---

Looking at the provided gist

> This takes any environment variables in the form: GITEA__section__KEY and sets them in app.ini - super helpful!

I've done this through the shell wrapper that is using `GITEA_SECTION_KEY` as well, the difference that i see is to also define file hierarchy and user/group which i found helpful for my development.

---

About the env-file i found that too limiting as it doesn't support string replacement with default value:

```sh
# Sets variable kreyren to store value 'default' unless kreyren is already set
export kreyren="${kreyren:-"default"}"
```

It seems that docker is using a simple python interpreter to set these variables that are then not available in the `CMD` scope thus the shell wrapper.

> -f docker-compose.yml \
> -f docker-compose.staging.yml \

My design expects the runtime defined within the `docker-compose.yml` or if needed it can use `docker run ...` as well which was done to use one database for multiple services so that i don't have to create the user on deployment.

**Comment by Kreyren** [comment]
@kdumontnu Btw. i am happy to discuss my design decisions more if you want to adapt them for your design.

**Comment by martencassel** [comment]
What i can see from these changes it that its only possible to change the default username/group/uid/gid by rebuilding the docker (ARG command is used) image, not setting it during run.

**Comment by Kreyren** [comment]
> I don't see that is possible to specify what user context to run gitea in (user/group/uid/gid). @martencassel

Data defined in https://github.com/go-gitea/gitea/pull/14626/files#diff-7056ac181b6ee63e9510d8b82a9be9d372e8d2d01e207f893d29bb184e4b133bR55 which will be processed further

Expected configuration is:
a) `GITEA_USER="kreyren" docker-command-here`
b) Adding the `GITEA_USER` in docker-compose.yml `environment` property.

> You only have the option by rebuilding the image with your custom --build-arg. @martencassel

I plan to add a handling to make this changable on runtime through the provided and optional script.

> Can we make it possible to start gitea by switching to a user from environment variables. For example like this: minio/minio@2a79ea0/dockerscripts/docker-entrypoint.sh#L100

I find that yes i want to do something like this, but i also want to cache the step during a build.

---

Note that the handling is not full implemented and that this was created to aid development of https://github.com/go-gitea/gitea/pull/14644

I will be reworking this whole merge request based on my finding from that development and feedback here.

Added your https://github.com/go-gitea/gitea/issues/14780 in the TODO list.

**Comment by martencassel** [comment]
FYI
Did some work here before finding your PR https://github.com/martencassel/gitea/blob/switch_user/docker/rootless/usr/local/bin/docker-entrypoint.sh

**Comment by Kreyren** [comment]
> #14785

my fault!

**Comment by pat-s** [comment]
@Kreyren I haven't followed the full discussion but it seems this PR is not going to be merged, isn't it? Can we close here?

**Comment by Kreyren** [comment]
@pat-s Will be finished once i handle https://github.com/go-gitea/gitea/pull/14644 currently being in work in github.com/kreytea (doing more changes on it as i need these for a development of my project)

feel free to close if this is inconvinient in the merge tracker will submit non-draft in that case once it's ready.

**Comment by pat-s** [comment]
I was just wondering since I haven't read whether the proposed changes will be accepted in the end and there are a lof of conflicts in the current PR :) 

Just wanted to check base and clean up a bit - the decision whether to close is on you :)

**Pull request closed without merging**
