### PR TITLE
Vendor Update

### PR DESCRIPTION
**Pull request by 6543**
* github.com/yuin/goldmark v1.2.1 -> v1.3.1
 * github.com/xanzy/go-gitlab v0.39.0 -> v0.42.0
 * github.com/pquerna/otp v1.2.0 -> v1.3.0
 * github.com/olivere/elastic/v7 v7.0.21 -> v7.0.22
 * github.com/niklasfasching/go-org v1.3.2 -> v1.4.0
 * github.com/minio/minio-go/v7 v7.0.6 -> v7.0.7
 * github.com/mgechev/revive 246eac737dc7 -> v1.0.3
 * github.com/mattn/go-sqlite3 v1.14.4 -> v1.14.6
 * github.com/markbates/goth v1.65.0 -> v1.66.1
 * github.com/lib/pq 083382b7e6fc -> v1.9.0
 * github.com/klauspost/compress v1.11.3 -> v1.11.7
 * github.com/google/uuid v1.1.2 -> v1.2.0
 * github.com/go-swagger/go-swagger v0.25.0 -> v0.26.0
 * code.gitea.io/sdk/gitea v0.13.1 -> v0.13.2

### CODE REVIEW

**Comment by techknowlogick** [comment]
I don't think we should backport all of these, I think only backporting the vendor libraries that fix the bug.

**Comment by 6543** [comment]
@techknowlogick I know ... I'm already on it ... just give me some time

**Comment by 6543** [comment]
@techknowlogick -> #14497

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Did we need to back port all of the vendors if we even don't know it will fix or result in bugs?

**Comment by 6543** [comment]
no we dont ... already done - was mainly the sdk ...

**Pull request merged**
