### PR TITLE
Disable auto-migrate in docker container

### LINKED ISSUE #5688: Permission denied after latest docker upgrade
- Gitea version (or commit ref):  31aa00f
- Git version: 2.11.0
- Operating system: Debian
- Database (use `[x]`):
  - [X] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant
- Log gist:
```
gitea     | Found app.ini config file, migrating database
gitea     | migrate: /data/gitea/conf/app.ini: Permission denied
gitea     | Jan 10 15:41:14 syslogd started: BusyBox v1.28.4
gitea     | Jan 10 15:41:14 sshd[22]: Server listening on :: port 22.
gitea     | Jan 10 15:41:14 sshd[22]: Server listening on 0.0.0.0 port 22.
gitea     | 2019/01/10 15:41:14 [T] AppPath: /app/gitea/gitea
gitea     | 2019/01/10 15:41:14 [T] AppWorkPath: /app/gitea
gitea     | 2019/01/10 15:41:14 [T] Custom path: /data/gitea
gitea     | 2019/01/10 15:41:14 [T] Log path: /data/gitea/log
db_1_260cddf62aee | 2019-01-10T15:41:14.327150Z 2 [Note] Aborted connection 2 to db: 'gitea' user: 'gitea' host: '192.168.144.3' (Got an error reading communication packets)
```
## Description

After upgrading my docker-compose instance from Gitea to the latest version I get the following error (as seen above).  
I already tried chowning the my mounted gitea volume to 999 (docker) and 1000 (default Gitea user) with now success.

### PR DESCRIPTION
**Pull request by techknowlogick**
Credit to @zeripath

Hopefully fixes #5688 

ping @AragurDEV

### CODE REVIEW

**Review by zeripath — CHANGES_REQUESTED** [review]
This doesn't match the line I suggested:

```sh
(cd /app/gitea; exec su-exec $USER /app/gitea/gitea migrate)
```

Your suggested working directory isn't correct.

The thing is we need try to replicate the exact environment that docker runs Gitea in so that relative paths in the conf file work. See https://github.com/go-gitea/gitea/blob/master/docker/etc/s6/gitea/run

**Comment by techknowlogick** [comment]
@zeripath updated path

**Review by zeripath — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
I think we should just remove it rather than comment it out but in either case disabling this seems appropriate.

**Review by lunny — APPROVED** [review]

**Comment by pr4xx** [comment]
But what was this used for? As far as I understand this is used to auto migrate for things like docker and using image :latest.

**Comment by zeripath** [comment]
There was a misunderstanding about why a user provided app.ini was not working. I think the issue actually might have been that the app.ini was not readable by Gitea.

In any case this fix caused more problems than it should have

**Pull request merged**
