### PR TITLE
fix: squashed nuget texts

### PR DESCRIPTION
**Pull request by lonix1**
If both description and release notes are available, then they are rendered as one long line.

@KN4CK3R

### CODE REVIEW

**Comment by yekanchi** [comment]
why is this not merging?
looks like small pr.
if needs revise I'm interested on working on this

**Comment by lunny** [comment]
Sorry missed that. Looks like this there is a conflict because other PR has also changed that place.

**Comment by techknowlogick** [comment]
I've just resolved the conflicts.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
I think this has been replaced by #30280

**Pull request closed without merging**
