### PR TITLE
Replace jquery-datetimepicker with native date input

### PR DESCRIPTION
**Pull request by silverwind**
This removes the jQuery plugin as well as the associated config options. Native input[type=date] does not require a language attribute as it is localized by default, except for the placeholder attribute for which I currently piggy-back the repo.issues.due_date_form localization option.

Implementation should pretty much match GH. Of note is that Safari does not provide a UI for this input type, but I don't think providing one is neccessary and GH did not bother either.

Before:
image

After:
image

### CODE REVIEW

**Comment by CirnoT** [comment]
Something very weird is going on, when I select any date, the date set is always +1 day from what I selected.

**Comment by silverwind** [comment]
Works in my end:

image

**Comment by CirnoT** [comment]
Works fine on GitHub; the issue isn't with native date picker, the date selected and sent to server is fine, but date saved in database is always +1 day.

**Comment by silverwind** [comment]
Weird. I see `"2020-05-05"` in the POST and on the rendered date afterwards.

**Comment by CirnoT** [comment]
Chromium sends
```due_date: "2020-05-25T00:00:00.000Z"```
And I see May 26 on rendered page.

**Comment by CirnoT** [comment]
In database it is set to `1590451199`, that's why. Gitea timezone is +2 for me so 23:59 on 2020-05-25 is indeed 26th of May.

**Comment by silverwind** [comment]
Is this a Chrome bug? I thought `type=date` should always send `yyyy-mm-dd`.

**Comment by silverwind** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) says:

> Value | A DOMString representing a date in YYYY-MM-DD format, or empty

**Comment by silverwind** [comment]
Chrome 83 does the right thing:

image

Why is there `due_date` in your example?

**Comment by CirnoT** [comment]
I'm testing it on issue due date, assuming it should behave the same way.

**Comment by silverwind** [comment]
Due date also sends with time info so there is a bug there that is not present on milestone.

**Comment by CirnoT** [comment]
Indeed, works fine on milestone. Wonder why due date sends time.

**Comment by silverwind** [comment]
It's wrongly passing the date to the JS `Date` contructor.

**Comment by silverwind** [comment]
I tried changing it to send `yyyy-mm-dd` format but the backend rejects that. Definitely a separate issue.

**Review by CirnoT — APPROVED** [review]

**Comment by silverwind** [comment]
Any more reviews? This is ready from my side.

**Comment by CirnoT** [comment]
Need to resolve conflicts @silverwind

**Comment by silverwind** [comment]
Yeah, just noticed that, rebased.

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
