### PR TITLE
Prevent double decoding of % in url params 

### LINKED ISSUE #17938: WebGUI: Escape character in folder or file name prevents access
* Gitea version (or commit ref): 1.15.7 built with GNU Make 4.1, go1.16.10 : bindata, sqlite, sqlite_unlock_notify
* Git version: 2.30.2
* Operating system: Debian GNU/Linux 11 (bullseye)
* Database (use [x]):
   - [x]  PostgreSQL
   - [ ] MySQL
   - [ ] MSSQL
   - [ ] SQLite
* Can you reproduce the bug at https://try.gitea.io:
   - [x] Yes (provide example URL): https://try.gitea.io/sebveit/meta-openwrt
   - [ ] No

### Description
I've cloned a repository from GitHub that uses the percentage character (%) in file and folder names a lot. This %-char prevents the access, via the web GUI of Gitea, to the file or folder containing this char in its name.
It looks like Gitea is displaying the %-char correctly but fails to provide the correct URL when clicking on it.
When I modify the URL and try to access it, nginx answers with `400 Bad Request`.

### Example
Expected URL: https://try.gitea.io/sebveit/meta-openwrt/src/branch/master/recipes-tweaks/busybox/busybox_%.bbappend
Actual URL: https://try.gitea.io/sebveit/meta-openwrt/src/branch/master/recipes-tweaks/busybox/busybox_%25.bbappend

### Reverse Proxy
I'm using nginx (1.18) as a reverse proxy for Gitea. My config for nginx is the following:

```
server {
    listen 443 ssl;
    server_name gitea.somedomain.tld;
    ssl_certificate     /etc/nginx/ssl/gitea.somedomain.tld.crt;
    ssl_certificate_key /etc/nginx/ssl/gitea.somedomain.tld.key;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 50M;
    }
}
```

I hope that helps pinpointing the bug. Let me know if you need additional information.
BTW, Gitea is really nice and slim compared to the bloated GitLab.

### PR DESCRIPTION
**Pull request by zeripath**
There was an unfortunate regression in go-gitea#14293 which has led to the double decoding
of url parameter elements if they contain a '%'. This is due to an issue
with the way chi decodes its RoutePath. In detail the problem lies in
mux.go where the routeHTTP path uses the URL.RawPath or even the
URL.Path instead of the escaped path to do routing.

This PR simply forcibly sets the routePath to that of the EscapedPath.

Fix #17938

## :warning: BREAKING :warning:
 
Although this fixes a bug - users may have worked around this bug by creating links that would make this work - especially in the wiki. As users may need to be aware of this I am marking this PR as breaking in order to highlight this issue.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Reviewers please check this PR with your own specific evil test cases. 

We will need to double check the redirects are correct too.

**Comment by zeripath** [comment]
Damn this is weird... 

So this will work for things only containing %25 but if there's something like:  a£"a#!?.md - then this breaks.

I don't get this...

**Comment by zeripath** [comment]
Ah ok the problem is much more complicated...

The issue is that chi has:

```go
// routeHTTP routes a http.Request through the Mux routing tree to serve
// the matching handler for a particular http method.
func (mx *Mux) routeHTTP(w http.ResponseWriter, r *http.Request) {
	// Grab the route context object
	rctx := r.Context().Value(RouteCtxKey).(*Context)

	// The request routing path
	routePath := rctx.RoutePath
	if routePath == "" {
		if r.URL.RawPath != "" {
			routePath = r.URL.RawPath
		} else {
			routePath = r.URL.Path
		}
		if routePath == "" {
			routePath = "/"
		}
	}
...
```

The routePath should really use the `r.URL.EscapedPath()` not `r.URL.RawPath` or even `r.URL.Path`

**Comment by KN4CK3R** [comment]
Are you sure we are not using chi in the wrong way? It looks like a workaround now.

**Comment by zeripath** [comment]
If you don't use the escapedpath you use partially decoded URLs for routing and get partially decoded results assigned to ctx.Params.

The only consistent (and safe) thing to do is to use the encoded URL for routing.

Feel free to play around with it though.

Here are few (unencoded) filenames you might want to try to make it possible to route to:

```
10%.md
£15&$6.txt
%3Fis?and#afile
This+file%20has 1space
%%2525mightnotplaywell
```

**Comment by wxiaoguang** [comment]
Nice catch.

Should we add some documents and unit tests to describe the expected behavior?

And I am not sure how most reverse proxies process these encoded URLs (what will be passed to backend)

* `/%.html`  (it should be `/%.html`)
* `/%25.html` (questionable, `/%.html` or `/%25.html` for backend ? )
* `/%2525.html`  ...

**Comment by lunny** [comment]
Isn't this an upstream problem?

**Comment by zeripath** [comment]
Not sure if it's definitely an upstream problem - this may be by design. 

Partial decoding of the urls may or may not be nice depending on your application - in our case it's bad because we're rendering urls that we have little to no control over so we have to have a simple mapping. Other users may not mind that if you want to have a % in your url it needs to be double escaped.

The solution proposed here is to use the mechanisms already available to us as provided by chi to tell it to use the EscapedPath instead of the partially escaped one.

**Comment by zeripath** [comment]
> Nice catch.
> 
> Should we add some documents and unit tests to describe the expected behavior?

I've added unit tests. I'm not sure what kind of document be beneficial - this PR is simply making sure that ctx.Params() always gives you the non-url encoded parameter from the url. 

> And I am not sure how most reverse proxies process these encoded URLs (what will be passed to backend)

That's a configuration issue. The reverse proxy should be passing the escaped url correctly - if it's de-escaping things then that's incorrect configuration.

> * `/%.html`  (it should be `/%.html`, although it is incorrect)

It's simple: a file that is named `/%.html` should be exposed as an url at `/%25.html` and if you send  `GET /owner/repo/src/branch/master/%25.html` you should get that file.  If you send a request `GET /owner/repo/src/branch/master/%.html` then go's url handler will clean that up to `.../%25.html` and you'll get the same file.

> * `/%25.html` (questionable, `/%.html` or `/%25.html` for backend ? )

a file that is named `/%25.html` should be exposed as an url at `.../%2525.html` and if you send  `GET /owner/repo/src/branch/master/%2525.html` you should get that file.  If you send a request `GET /owner/repo/src/branch/master/%25.html` then you should get `%.html` not `%25.html`.

> * `/%2525.html`  ...

a file that is named `/%2525.html` should be exposed as an url at `/%252525.html` and if you send  `GET /owner/repo/src/branch/master/%252525.html` you should get that file.  If you send a request `GET /owner/repo/src/branch/master/%2525.html` then you should get `%25.html` not `%2525.html` and certainly not `%.html`.

**Comment by wxiaoguang** [comment]
@zeripath I didn't say clearly. Let's see an example:

For a simple Go http server:

```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func (w http.ResponseWriter, r *http.Request) {
		_, _ = fmt.Fprintf(w, "URI: %s\n", r.RequestURI)
		_, _ = fmt.Fprintf(w, "URL: %s\n", r.URL.Path)
	})
	_ = http.ListenAndServe(":3000", nil)
}
```


nginx config:
```
server {
    listen 127.0.0.1:80;
    location / {
        proxy_pass http://127.0.0.1:3000/;
    }
}
```


We see different behaviors:

image

**Review by techknowlogick — APPROVED** [review]
❤️ the tests

**Comment by zeripath** [comment]
@wxiaoguang this partial decoding of URI paths containing %2f is not anl problem. It would only be a problem if filenames were allowed to contain / in them - and we don't use the URI but the escaped URL which is the same in both of these cases. (IIRC URLs aren't actually allowed %2f in path components.)

It would be a problem if %252f in an URI became %2f in an URL because then that would map to looking at a file with '/' in its name and prevent looking at files with %2f in their names.

**Review by wxiaoguang — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
