### PR TITLE
fix code review on mssql

### LINKED ISSUE #5458: [mssql] Pull Request Database Issue
- Gitea version (or commit ref): 20c54f8
- Git version: Docker Container
- Operating system: Docker Container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
```log
[...outers/repo/issue.go:835 ViewIssue()] [E] GetReviewersByPullID: mssql: Column 'user.lower_name' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```
Create a pull request.
If i want to look at my pull requests i get the following issue 500 ServerError.
`1.6.0` does not have this issue.

### PR DESCRIPTION
**Pull request by lunny**
will fix #5458

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by chdxD1** [comment]
Hi,
thanks for looking into this!
I have tested and verified that PRs are now working on MSSQL (despite not being the nicest code :see_no_evil: Thanks Microsoft for implementing plain relational logic...)

**Comment by lunny** [comment]
@chdxD1 Yes, this is a quick fix. And we can refactor that later.

**Review by sapk — APPROVED** [review]

**Comment by Cellebyte** [comment]
@lunny, @chdxD1 tested it this morning and pull requests are working again.

**Comment by lunny** [comment]
This bug is for review summary, no need to back port to v1.6

**Pull request merged**
