### PR TITLE
Improve dashboard repo search

### PR DESCRIPTION
**Pull request by andreynering**
Improvement of https://github.com/go-gitea/gitea/pull/872

I think the last thing to discuss is wether we should remove the other repo panels, since this one now show all repos visible to the logged in user.

### CODE REVIEW

**Comment by bkcsoft** [comment]
well, LGTM to me, as for removing the other panel I'm fine with that 🙂

**Comment by lunny** [comment]
This is my screenshot. It seems it's not ready?
untitled

**Comment by andreynering** [comment]
@lunny Not sure what could be wrong, it works for me.

Did you run `make assets`? Any error on the JS console?

**Comment by lunny** [comment]
I didn't run `make assets`, `make: Nothing to be done for `assets'.`.

**Comment by andreynering** [comment]
@lunny Sorry, `make assets` by now is just for CSS, not JS.

If you are compiling with bindata you should run `make generate`.

Can also be a an cache issue. Otherwise, I don't know what's the problem. 🤔

**Comment by andreynering** [comment]
Updated. I fixed an issue with the repos/orgs/mirrors tabs switching.

@bkcsoft I decided to keep the other panel for now, because the api is not yet showing repos you're just a colaborator and not owner. That panel shows exactly that. We could change that in another PR.

@lunny Which browser are you using? Any errors on JS console?

**Comment by lunny** [comment]
I used chrome on Mac OS. but seems it fixed when I update to the latest commit of this PR.

**Comment by lunny** [comment]
so LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Comment by lunny** [comment]
don't merge this until v1.2 released.

**Comment by bkcsoft** [comment]
@lunny Why wait until after 1.2? (Added `status/blocked` in the meanwhile)

**Comment by lunny** [comment]
I don't know. @andreynering maybe we can put it back to v1.2 since this is not a big feature.

**Comment by andreynering** [comment]
I'm ok with that

Em 08/05/2017 5:26 AM, "Lunny Xiao" <notifications@github.com> escreveu:

**Pull request merged**
