### PR TITLE
Fix overflow in commit graph

### LINKED ISSUE #17944: Formatting of commit graph does not consider longer real name
### Gitea Version

1.16.0+dev-670-gc7e23401a

### Git Version

2.34

### Operating System

Windows 

### How are you running Gitea?

windows service 

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

if a user has a full name longer than TBD, in conjunction with a long commit message, the datetime reference is overwritten with the commit+name

https://try.gitea.io/eeyrjmr/test_issues/graph

NOTE: "full name" is not unexpected, colleague's name is 20characters, mine is 23 but this is just a red-herring as the clash is with the commit message

### Screenshots

Annotation 2021-12-10 001112

### PR DESCRIPTION
**Pull request by silverwind**
Limit commit message to 50% width. This is rather crude but should work for common use cases with not too-long author names.

Fixes: #17944

Before:
Screenshot 2021-12-10 at 11 09 59

After:
Screenshot 2021-12-10 at 11 10 39

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
It seems better, and the spaces between `#203` appears.

**Comment by silverwind** [comment]
Yes, that's another bug fixed (caused by flexbox not rendering HMTL whitespace).

**Comment by wxiaoguang** [comment]
ps: there is still some overlapping (That's fine for me and I can ignore it 😂)

image

**Comment by silverwind** [comment]
Yeah it's best-effort. Stuff can still overflow on long author name or broad graph.

**Comment by silverwind** [comment]
Checking if there's a solution without static width.

**Comment by silverwind** [comment]
Now it's working correctly with any width of commit message or author name and the time will no longer clip into the author name either (caused by fomantic rule `max-width` on all images).

image

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
