### PR TITLE
Narrow down Edge version in browser support docs

### PR DESCRIPTION
**Pull request by silverwind**
I noticed that Edge 14 has a pretty buggy `fetch` implementation and because it has already reached end of support I think it's better we don't specifically state support for it, even if it may work to some extend.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by CirnoT** [comment]
Might need to differentiate between EdgeHTML-based and Chromium-based. Also the current number  (14) refers to EdgeHTML engine, not browser version, unlike others.

**Comment by silverwind** [comment]
I wouldn't differentiate. The last two EdgeHTML versions should still support everything we need and new Chromium versions will only get better.

Yes I realized the 14 was an error on my side, it should have been 38.

**Comment by CirnoT** [comment]
In time we might want to deprecate support for EdgeHTML entirely.

I'm also sure that some companies would want to know whether EdgeHTML is supported or not (note that on Pro and Enterprise Chromium Edge is still manual process) so I think it would be worth to note that we support EdgeHTML 38+ and last 2 versions of Chromium Edge.

**Comment by silverwind** [comment]
Splitted it up:

Last two EdgeHTML is 42 and 44
Last two Chromium is 81 and 83

I'm sure older versions do work to some extend but we should only offer support for the mentioned versions.

**Comment by CirnoT** [comment]
Oh yeah, 38+ was error on my part.

**Comment by CirnoT** [comment]
Looks weird with
>Edge and Edge

**Comment by silverwind** [comment]
> Looks weird

I think it's fine. "Edge (Chromium and EdgeHTML)" would less clear.

**Review by mrsdizzie — APPROVED** [review]

**Review by CirnoT — APPROVED** [review]

**Pull request merged**
