### PR TITLE
Allow assignee on Pull Creation when Issue Unit is deactivated

### LINKED ISSUE #9824: I cannot assign a user when creating a PR
- Gitea version (or commit ref): 1.11.0+rc1
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: n/a

## Description

If a repository does not have its own issue tracker, you cannot select a user when creating a pull request. However, if the repository has an issue tracker, it works.

### PR DESCRIPTION
**Pull request by 6543**
close #9824

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Comment by guillep2k** [comment]
Unrelated, but there seems to be a problem with the dark mode theme about this:

image

(Only for the _create PR_ page; in the _view PR_ the assignees are displayed correctly).

**Comment by 6543** [comment]
ready to merge :rocket:

**Comment by lunny** [comment]
Please send backport

**Comment by 6543** [comment]
@lunny already done :sweat_smile:

**Pull request merged**
