### PR TITLE
Match GH with Commit page

### LINKED ISSUE #12296: Signed commits reveal email addresses (and spammers are scraping Gitea for email addresses)
I've been testing Gitea for just one week today and I just received spam on an address dedicated to catch this exact event and tell me where it was sourced. It is already default to hide the user's email address on their profile but anyone who signs their code has their email address broadcast to anyone scraping the service.

It is sufficient to say the email address has been verified for an account on Gitea. It is unnecessary to include the email address in the web interface.

Please remove the email address from the interface. Thank you.

**Edit**: @canarysnort01 has found another leak. On the /commits/ page if you hover over signed commits the leaked email address will match your account's primary email address instead of the address on the PGP key.

### PR DESCRIPTION
**Pull request by techknowlogick**
fix #12296

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport

**Comment by CirnoT** [comment]
Don't really see much point of it given that email is still visible in commit message (Gitea adds fields like Reviewed-by) and on user profile page.

**Comment by CirnoT** [comment]
Oh also email is visible on signed commit signature
chrome_2020-08-05_12-09-51

**Comment by lafriks** [comment]
Does github hide emails somehow in commit messages?

**Comment by silverwind** [comment]
I think GH preserves original commit messages (incuding emails) but never adds emails by itself (in contrast to gitea which may according to comments here).

**Comment by zeripath** [comment]
@lafriks If the user matches then they don't display the email address but you can always get the real email by adding an appropriate suffix to the commit url.

I do wonder if they realise that - or even that they can just pull the damned git sources themselves over http?

Or is the issue the rate limiting? Maybe that's where we need focus next?

**Pull request merged**
