### PR TITLE
Use modules/git for git commands

### PR DESCRIPTION
**Pull request by typeless**
Updating them incrementally.

### CODE REVIEW

**Comment by lunny** [comment]
I found there are 38 revokes to `process.GetManager().ExecDir`.

**Comment by typeless** [comment]
@lunny I don't intend to do all replacements in one PR.

**Review by kolaente — APPROVED** [review]

**Comment by zeripath** [comment]
Please take a look at #6672 I moved some commands in to modules/git there and also made hooks run on pushes.

**Comment by zeripath** [comment]
Sorry looks like I've caused conflicts

**Comment by typeless** [comment]
@zeripath never mind. PTAL when CI finished.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
