### PR TITLE
Support envs on external render commands

### PR DESCRIPTION
**Pull request by lunny**
An improvement for #5201. @Cellebyte

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm... I'm not sure there should be differential expansion based on whether the machine is running windows or otherwise. `os.Expand` and `os.ExpandEnv` only do `$var` and `${var}` by design. (This PR should also probably cover `${...}` expansion too.)

I guess we only want `GITEA_PREFIX_SRC`, `GITEA_PREFIX_RAW` expanded at present but it may be better to restructure this to use `os.Expand`.

(In passing I'm also quite suspicious of the use of `strings.Field`. It could be a bit of a gotcha to want an external command which passes an argument `-c "Gitea made this"`. This will get munched into: `["-c", "\"Gitea", "made", "this\""]` which will effectively tell the command that the argument to the `-c` is `\"Gitea` not `Gitea made this`. I'd have to check though.)

**Comment by lunny** [comment]
@zeripath see https://github.com/golang/go/issues/24848, `os.Expand` didn't support windows and also wont do that. We could use `golang.org/x/sys/windows/registry` when windows but I would like to write the function myself since it's a function too short.

**Comment by zeripath** [comment]
It's not that os.Expand doesn't support Windows, but that it won't support Windows-style variables. Currently we're not doing any expansion of variables, so the choice is to support different variable expansion regimes for Windows vs. others or just to do the same.

Hmm... Arguments in favour of 'doze expansion:

* The other arguments in the command be passed to the windows command unchanged - therefore paths referred to in the command will have to be backslash file-separated.
* It matches the expected format for the command knowing that they're on windows

Arguments against specific 'doze expansion:

* The variable format will be different on different systems.

I'm sorry, I think you're right we should do 'doze expansion. 

(I've just checked go's documentation, is my interpretation right in that the filepath for the command would have to be in 'doze format with backslashes? e.g. "C:\Program Files (x86)\Why so many spaces\command.exe" -  if not that probably needs looking at too.)

It might still be worth handling `${..}` expansion. Are there other variables we might want to allow expansion for, or is it just these two?

**Comment by lunny** [comment]
@zeripath currently just these two and I don't think we need to support `${..}` because it's not an unix/windows environment variables syntax.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
