### PR TITLE
Exclude vendor dirs from git CRLF normalization

### PR DESCRIPTION
**Pull request by silverwind**
Should get rid of a few warnings like at the end of `lint-backend` like https://drone.gitea.io/go-gitea/gitea/23117/1/4.

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind you have to `make vendor` and commit with new-old line endings

**Comment by silverwind** [comment]
Done, let's see if it passes now without warnings.

**Comment by 6543** [comment]
passed :+1:

**Comment by silverwind** [comment]
It passed and warnings are gone: https://drone.gitea.io/go-gitea/gitea/23122/1/4 🎉

**Comment by 6543** [comment]
first ;)

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
