### PR TITLE
WIP: Add theme generator and new theme 'gitea-dark'

### PR DESCRIPTION
**Pull request by silverwind**
`generate.js` creates theme css out built of `public/css` files by by remapping existing colors to new ones. The major benefit with this method is that contributors only touch the base theme and other themes are generated based on it. Only if new colors are introduced, the themes need to be updated.

TODO:

 - handle hljs and codemirror colors
 - handle arc-green in a best effort approach
 - evaluate removal of THEMES options so more installations will get the new theme(s)
 - parse less+css sources instead of public files (needs a less-to-css conversion for [`remap-css`](https://github.com/silverwind/remap-css))
- fix more things

Screenshot:

image

### CODE REVIEW

**Comment by lunny** [comment]
图片

**Comment by lunny** [comment]
More internal themes means we need more work once something changed. I proposal we create a theme market and users could upload / download and apply themes.

**Comment by silverwind** [comment]
There is minimal work here. Only when new color are added on the base white theme, new mappings need to be added. 

The missing text was removed for the screenshot.

**Comment by silverwind** [comment]
> I proposal we create a theme market

Sure, but I think a base light/dark theme should be first-party. I will try to make this theme as unopinionated as possible, this means I will remove the background texture and probably just call it "dark".

Color variation themes can come from third parties, but keep in mind that our CSS is a fast moving target so it will break if not constantly maintained and I guess most theme authors are not willing to put up with that.

**Comment by silverwind** [comment]
Here's my plan for the `THEMES = gitea,arc-green` option:

- Remove/ignore the `THEMES`
- Add new option `DISABLED_THEMES=` (no default)

This way, both new and existing installation would automatically get the new theme enabled. A blacklist-based approach should be much more future-proof and I imagine the new option would rarely if ever being used.

**Comment by silverwind** [comment]
Renamed to `gitea-dark`, screenshot updated, script moved. Still a few things to do.

**Comment by ShalokShalom** [comment]
> I proposal we create a theme market and users could upload / download and apply themes.

Our distro has build one for its user packages, you could consider it:
https://kaos-community-packages.github.io/

Another solution is pling, former opendesktop.

This gives also a showcase, some people will discover Gitea through it.

**Comment by silverwind** [comment]
Closing this for now as  it's nowhere near finished. Will follow up with something more substantial once I've figured out multi-stage webpack builds and stuff.

**Comment by septatrix** [comment]
Do you still continue development on your private branch where I could take a look at it?

**Comment by silverwind** [comment]
It's currently halted. There are a few prereqs I want to solve first before continueing.

**Pull request closed without merging**
