### PR TITLE
Move all static files to go-bindata

### PR DESCRIPTION
**Pull request by tboerger**
I have moved all static files into go-bindata and i have split them into multiple packages to include only the required parts. As a part of it I moved all files into the `static/´ folder. Local tests are already looking pretty good.

This change makes it possible to do real single binary deployments as all required files are included. A user should be still able to overwrite single files locally.

### CODE REVIEW

**Comment by tboerger** [comment]
Maybe we should move `modules/bindata/` to `bindata/` as this is not a real module like the other modules.

**Comment by lunny** [comment]
I will review the codes and do some tests before merging it.

**Comment by linquize** [comment]
What I wish to is to update bindata as few as possible, during development period.
This may make the commit history clearer and smaller.
Only update them before a release version is out.
When the developer wants to try an embedded version, he can run a script to update bindata.

**Comment by vtolstov** [comment]
Yes I build from source and create package,so I don't need allinone.may be
add build tag,and embed for example install bundled   version,but defaults
not embed all?
05 авг. 2015 г. 13:21 пользователь "linquize" <notifications@github.com>
написал:

**Comment by lunny** [comment]
A build tag is more flexsible.

**Comment by tboerger** [comment]
Ok, let me figure out some functionality including optional local overwrites for the embedded version as well.

**Comment by tboerger** [comment]
Is it ok to have the tag only for the non bindata build? or do you want to use the bindata obly with the tag?

**Comment by vtolstov** [comment]
I'm for embed only when provided tag
07 авг. 2015 г. 13:11 пользователь "Thomas Boerger" <
notifications@github.com> написал:

**Comment by tboerger** [comment]
I'm for embedding per default, the default should be published on github releases as a single binary with an optional archive of the assets. For packaging or your deployment they can define the tag and move the files as required...

**Comment by vtolstov** [comment]
OK, as for github release I think that's good
07 авг. 2015 г. 14:58 пользователь "Thomas Boerger" <
notifications@github.com> написал:

**Comment by lunny** [comment]
OK.

**Comment by tboerger** [comment]
It's done! Maybe somebody wants to try it out? With the ```nobindata``` tag you have to provide the folders from ```static``` within the config options ```STATIC_ROOT_PATH```.

**Comment by lunny** [comment]
I will try it.

**Comment by tboerger** [comment]
So this stuff now really works. Tested it locally totally fine! @lunny something that needs to be done as well?

**Pull request merged**
