### PR TITLE
WIP: Implement Issue forms

### PR DESCRIPTION
**Pull request by Wazzaps**
Implements #20232.

There's no dev-facing API for this feature, it's pretty much all GUI.

This is my first time writing Go beyond 10 lines of code, look for beginner mistakes :)

### Screenshots:
<details>
  <summary>Click to expand</summary>
#### Choose template
2022-08-13 04 40 34 localhost d13ea5841a5e

#### Form
2022-08-13 04 42 39 localhost 4d60d2ea450b

#### Result
2022-08-13 04 41 21 localhost fd3706962352

</details>

### Features:
- [x] Parsing most of Github's syntax for issue forms
- [x] Form-style templates show up in template selector
- [x] Template rendering
- [x] Backend that converts the form fields to Markdown (with no clientside js!)
- [x] Display template validation errors in template chooser
- [ ] Optionally place certain fields in yaml frontmatter instead
- [ ] File upload
- [ ] A good design
- ~~Multi-select dropdowns~~ -> replaced with checkboxes in the meantime
- [x] "Required" tag for most field types
- ~~Auto-Assign people based on template~~ -> Need to be done for md templates as well, out of scope
- ~~PR form templates~~ -> out of scope for this PR
- ~~Graphical issue builder~~ -> later
- [ ] Template linting when editing online
- [ ] A way to extract the form fields reliably / programmatically (maybe a webhook during submit?)
- [ ] Form localization
- [ ] Don't include empty fields? (deviates from GH behaviour)
- [ ] Additional (gitea) features
- [ ] `config.yml`
  - [ ] Contact links
    - [ ] Warn when leaving site?
  - [ ] `blank_issues_enabled: false`

### Known issues:
- [x] ~~Tabindex is broken (cannot tab between fields)~~ Fixed
  - Seems like you can't tab out of a markdown editor, affects normal issues too, out of scope
- [ ] Clicking submit while required fields aren't set breaks the submit button
- [ ] Pasting images doesn't upload them in form (because no file upload widget in page)

### CODE REVIEW

**Comment by Wazzaps** [comment]
Hmm, I cannot reproduce the "Imports are sorted wrong" lint error on my side, and I can't find a tool that reorders differently them from what they are currently.
Could you take a look? @lunny

**Comment by lunny** [comment]
> Hmm, I cannot reproduce the "Imports are sorted wrong" lint error on my side, and I can't find a tool that reorders differently them from what they are currently. Could you take a look? @lunny

Thanks @zeripath did that.

**Comment by Wazzaps** [comment]
Added indication if templates don't pass validation, with an error string.
Need to localize this.

image

**Comment by lunny** [comment]
> Added indication if templates don't pass validation, with an error string. Need to localize this.
> 
> image

Shouldn't the error be displayed nearby the related input or textarea?

**Comment by Wazzaps** [comment]
I chose to show it in the chooser since the form may be broken and I wouldn't want users to submit a broken form (because they will ignore the error) so I hide any form template with errors.
Also, this lets me show errors such "the 'name' field of the issue template are required".

**Comment by lunny** [comment]
Since #20987 merged, this PR could be rebased.

**Comment by delvh** [comment]
Or closed?

**Comment by Wazzaps** [comment]
I'll close this and open a new PR for any other enhancements :)

**Pull request closed without merging**
