### PR TITLE
Fix the spacing issue in the Project view

### LINKED ISSUE #30388: No padding between buttons and above line in Project view UI.
image

### PR DESCRIPTION
**Pull request by HEREYUA**
Fixes: https://github.com/go-gitea/gitea/issues/30388

**before**

image

**after**

image

### CODE REVIEW

**Review by silverwind — APPROVED** [review]
Could also add class it to parent node I suppose. Such wrapper divs should be avoided where possible.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Wait a bit on comment above.

**Comment by HEREYUA** [comment]
Okay, I noticed that there were several other similar usages, so I added margins this way. 
https://github.com/go-gitea/gitea/blob/0fe9f93eb4c94d55e43b18b9c3cc6d513a34c0b5/templates/org/projects/list.tmpl#L17-L19
https://github.com/go-gitea/gitea/blob/0fe9f93eb4c94d55e43b18b9c3cc6d513a34c0b5/templates/user/profile.tmpl#L9-L11
https://github.com/go-gitea/gitea/blob/0fe9f93eb4c94d55e43b18b9c3cc6d513a34c0b5/templates/user/overview/package_versions.tmpl#L17-L19
https://github.com/go-gitea/gitea/blob/0fe9f93eb4c94d55e43b18b9c3cc6d513a34c0b5/templates/user/overview/packages.tmpl#L17-L20

**Comment by silverwind** [comment]
Yes, I would recommend adding the helper class on the existing parent in all cases.

**Comment by HEREYUA** [comment]
> Yes, I would recommend adding the helper class on the existing parent in all cases.

Updated

**Review by silverwind — APPROVED** [review]

**Comment by yp05327** [comment]
@HEREYUA @lunny 
Didn't link to the issue correctly. Can you fix the description?

**Comment by silverwind** [comment]
I recommend using `Fixes: <link-or-#id>` in the future.

**Comment by HEREYUA** [comment]
updated

**Comment by silverwind** [comment]
Always use absolute links insted of `#1234` because those will not work if the repo is hosted somewhere else than GitHub.

I edited just for the sake of correctness:

```
Fixes: https://github.com/go-gitea/gitea/issues/30388
```

**Pull request merged**
