### PR TITLE
Manage port in submodule refurl

### LINKED ISSUE #11304: Submodule listings do not use full URL (missing port) with gitea in docker
- Gitea version (or commit ref): Powered by Gitea Version: 1.12.0+dev-186-g41f05588e
- Git version: git version 2.17.1
- Operating system: Ubuntu 18.04.4
- Docker version: Docker version 19.03.8, build afacb8b7f0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant - not running docker using port 3000
- Log gist:

## Description
Running gitea in docker, started as follows
```
docker run --rm --name gitea \
    -e TZ=America/New_York \
    -e USER_UID=1001 \
    -e USER_GID=1001 \
    -p 3000:3000 \
    -p 127.0.0.1:2222:22 \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/timezone:/etc/timezone:ro \
    -v /stuff/gitea:/data \
    gitea/gitea:latest
```
Everything runs fine, except for submodules.  They work fine, but rendering in the gui is missing the port **3000** for links.  Cannot reproduce on **try.gitea.io** as that is on regular port 443, not port 3000 as the dockerized version.

Gitea Base URL: _http://myhost.local:3000/_
SSH Server Domain: _myhost.local_

## Steps to reproduce
Create a new repo "test1"
Create a new repo "sub1" to act as submodule to test1
Clone test1 locally, then add sub1 as a submodule
```
$ git clone git@myhost.local:Halfwalker/test1.git
$ cd test1
$ mkdir subs
$ cd subs
$ git submodule add git@myhost.local:Halfwalker/sub1.git
```
Check what we've done
```
$ cd ..
$ git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .gitmodules
        new file:   subs/sub1
```
Add files to repo, commit
```
$ git add .
$ git commit -m "Intial commit"

[master (root-commit) 1eae353] Intial commit
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 subs/sub1
```
Push to gitea
```
$ git push

Counting objects: 4, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 359 bytes | 359.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
remote: . Processing 1 references
remote: Processed 1 references in total
To myhost.local:Halfwalker/test1.git
 * [new branch]      master -> master
```
Now look test1 repo on gitea - looks fine
Click into "subs" directory - works fine
  _http://myhost.local:3000/Halfwalker/test1/src/branch/master/subs_

sub1 submodule directory has link _http://myhost.local/Halfwalker/sub1_
commit has link _http://myhost.local/Halfwalker/sub1/commit/5436......_

MISSING port **3000**, should be _http://myhost.local:3000/Halfwalker/sub1_

### PR DESCRIPTION
**Pull request by zeripath**
Fix #11304

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]

**Comment by guillep2k** [comment]
Very strange error on golangci-lint. 🤔

**Comment by guillep2k** [comment]
Can reproduce in my setup! Doesn't happen on `master` (`golangci-lint 1.24.0`).

**Comment by guillep2k** [comment]
Oh, it's an import cycle:
```
import cycle not allowed
package code.gitea.io/gitea
        imports code.gitea.io/gitea/cmd
        imports code.gitea.io/gitea/models
        imports code.gitea.io/gitea/modules/auth/oauth2
        imports code.gitea.io/gitea/modules/setting
        imports code.gitea.io/gitea/modules/git
        imports code.gitea.io/gitea/modules/util
        imports code.gitea.io/gitea/modules/setting
```

😕

**Comment by guillep2k** [comment]
I think `util.IsExternalURL()` should probably moved out of `util`. Maybe even move it to `setting`.

**Comment by zeripath** [comment]
Ugh

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
