### PR TITLE
Fix migration bug

### PR DESCRIPTION
**Pull request by lunny**
If you start your gitea failed, please follow the steps,
1) stop gitea if it's still running
2) change table `version`'s value from 79 to 78
1) try start gitea

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
So sorry about this peeps. As penance I'll make some migration integration tests.

**Comment by securitaas** [comment]
It now works for me on mariadb. Thank you.

**Comment by zeripath** [comment]
I think we may need to do the above recommended changes on try.gitea.io

**Comment by zeripath** [comment]
Hmm... I've just had a similar issue on sqlite moving from v1.7.0-rc3 to master. The migration is still wrong.

**Pull request merged**
