### PR TITLE
Enable borders in all labels

### PR DESCRIPTION
**Pull request by Monter**
Enable borders in all labels

### CODE REVIEW

**Comment by techknowlogick** [comment]
Please edit less file the run `make generate-stylesheets`, and provide screenshots.

**Comment by Monter** [comment]
Before: 
before

After: 
after

**Comment by silverwind** [comment]
Something's wrong here, your change only affects the .css file, but it should also be in .less. You should just edit the less file, run `make generate-stylesheet` and then commit both files.

**Comment by lunny** [comment]
conflicted

**Pull request closed without merging**
