### PR TITLE
Storage configuration support `[storage]`

### PR DESCRIPTION
**Pull request by lunny**
This PR adjusted the override sequence, `[storage]` <- `[storage.minio]` <- `[storage.attachments]`. Right section will override left.

In fact, `[storage]` is expected because it's more easier to remember.

This will also enable storage tests with minio when mysql integration tests.

This also changed the behaviour of lfs serve when given a range start value out of bounds, now it will return 416, but not ignore that like before.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
`TestGetLFSRange` test fail with minio

**Comment by lunny** [comment]
The file tested in LFS is 10 bytes, and the request is range=11-, so the correct response of HTTP standard is to return an error or just ignore that?

**Comment by lafriks** [comment]
It should be fixed for file and minio to behave the same and handle that

**Comment by lunny** [comment]
@lafriks Yes, so which one should choose? Return io.EOF or just ignore them?

**Comment by lunny** [comment]
OK. I think https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests explained we should return 416.

```
Partial request responses

There are three relevant statuses, when working with range requests:

    In case of a successful range request, the 206 Partial Content status is sent back from a server.
    In case of a range request that is out of bounds (none of the range values overlap the extent of the resource, i.e first-byte-pos of all ranges is greater than the resource length), the server responds with a 416 Requested Range Not Satisfiable status.
    In case of no support of range requests, the 200 OK status is sent back from a server.
```

**Comment by techknowlogick** [comment]
🚀

**Comment by techknowlogick** [comment]
@lunny please send backport :)

**Pull request merged**
