### PR TITLE
Add Type SimpleUser

### PR DESCRIPTION
**Pull request by 6543**
... and repo.GetAssignees() now use it

- [ ] Test if it Improves speed / mem usage

### CODE REVIEW

**Comment by 6543** [comment]
@lunny I chery-picked this - let me know if it is the way it should :D

**Comment by sapk** [comment]
@6543 what is the use case ? Use less memory ?

**Comment by 6543** [comment]
for example the repo.GetAssignees() load a lot of user objects and only the ID, Name & Avatar is used sometimes

and with this struct i simply order xorm to only load importand stuff into mem and use it

@sapk yes its only for optimisation purpose

**Comment by sapk** [comment]
In that case, even if it seems obviously better (memory or cpu time) some optimization are counter productive. I would suggest you to set a benchmark to demonstrate the optimization compared to the overhead it add.
Don't take this as a blocking comment just a suggestion to prove your point.

**Comment by 6543** [comment]
If i know how to (exact) test it - I'll do :)

**Comment by 6543** [comment]
since It doesnt look like a SimpleUser is needed and I had no time to test if it has any memory/cpu impruvements ... I'll close this

**Pull request closed without merging**
