### PR TITLE
Update code.gitea.io/git

### LINKED ISSUE #1836: 500 Error after changing the repository branch
- Gitea version (or commit ref): master (642f844)
- Git version: 2.1.4
- Operating system: Debian 8.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I forked/cloned a repository from Github to Gitea. 

If I switch within this repository from the master branch to an other branch or tag then I got a 500 Error Website.  
It could be that my repository is very screwed-up but I need the other branches :o)

You can find the repository here: https://try.gitea.io/oszilloskop/site-ffffm

### PR DESCRIPTION
**Pull request by andreynering**
Closes #1836

/cc @ethantkoenig

### CODE REVIEW

**Comment by lafriks** [comment]
Did you update correctly with fetch command? CI fails with localy modified file error

**Comment by andreynering** [comment]
@lafriks No, I did a `go get -u code.gitea.io/git` + `govendor update +external`. I just tried `govendor fetch code.gitea.io/git` and nothing changed.

/cc @tboerger

**Comment by sapk** [comment]
@andreynering I don't have anything to debug. But I think that you may have change in GOPATH that make a different hash and `govendor update +external` import form GOPATH. govendor fetch may not update from remote because it is the same git commit id ...

Remove folder before or simply `govendor remove code.gitea.io/git` to force fetch and just do `govendor fetch code.gitea.io/git`. You should have a different hash in vendor.json.

**Comment by sapk** [comment]
And don't hesitate to test `make test-vendor` locally.

**Comment by andreynering** [comment]
@sapk Thank you for the help.

`make test-vendor` don't work on Windows, it seems. I tried recloning `code.gitea.io/git`, updating govendor, etc..., there's no change. 🤔 

If no one create a new PR, I'll try on Ubuntu later.

**Comment by sapk** [comment]
@andreynering maybe this is related to windows. I will make a PR from a linux os. Sorry for the inconvenience.

**Pull request closed without merging**
