### PR TITLE
fixes 500 error on dashboard when using MSSQL

### PR DESCRIPTION
**Pull request by bradder555**
MSSQL rejects the query:
```
  SELECT "repository"."id" FROM "repository"
  INNER JOIN "team_repo" ON "team_repo".repo_id="repository".id AND
  "repository".is_mirror=1
  WHERE (
    ("repository".owner_id=2 AND "repository".is_private=0)
        OR team_repo.team_id IN (1)
        )
        GROUP BY "repository".id ORDER BY updated_unix DESC
```
when the order by term (updated_unix) is not included in the group by term.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by bradder555** [comment]
any feedback on the quality of my commit message would be appreciated. Thanks

**Comment by lafriks** [comment]
It describes changes so it is understandable what change fixes, I think it is good ;)

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work :)

**Comment by lafriks** [comment]
@bradder555 can you backport it to 1.2 branch?

**Pull request merged**
