### PR TITLE
Temporarily patch go-ini/ini with fork

### LINKED ISSUE #2197: Cannot boot docker image when mount a custom app.ini configuration
- Gitea version (or commit ref): Since 2eeae84cbd80544157a82c7f031489eaaceaa873 (`master` branch)
- Git version: `2.8.5`
- Operating system: macOS 10.12.5 + Docker for Mac (17.06)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Since commit 2eeae84cbd80544157a82c7f031489eaaceaa873, which belongs to #1471, the docker image, which I built with `TAGS="sqlite" make docker`, cannot be booted with an `app.ini` file mounted, and following error will be shown:

```bash
$ docker run -it --rm -p 3001:3000 -v $PWD/conf/sqlite/app.ini:/data/gitea/conf/app.ini gitea/gitea:latest
Generating /data/ssh/ssh_host_ed25519_key...
Jul 22 16:58:03 syslogd started: BusyBox v1.24.2
Generating /data/ssh/ssh_host_rsa_key...
Generating /data/ssh/ssh_host_dsa_key...
Generating /data/ssh/ssh_host_ecdsa_key...
Jul 22 16:58:03 sshd[12]: Server listening on :: port 22.
Jul 22 16:58:03 sshd[12]: Server listening on 0.0.0.0 port 22.
2017/07/22 16:58:03 [...s/setting/setting.go:803 NewContext()] [E] Error saving generated JWT Secret to custom config: rename /data/gitea/conf/app.ini.821764490.tmp /data/gitea/conf/app.ini: device or resource busy
2017/07/22 16:58:04 [...s/setting/setting.go:803 NewContext()] [E] Error saving generated JWT Secret to custom config: rename /data/gitea/conf/app.ini.342639761.tmp /data/gitea/conf/app.ini: device or resource busy
...
```

After dig into the code, I found it's related to this part of code:

https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L831-L838

```go
		cfgSave.Section("security").Key("INTERNAL_TOKEN").SetValue(InternalToken)

		if err := os.MkdirAll(filepath.Dir(CustomConf), os.ModePerm); err != nil {
			log.Fatal(4, "Failed to create '%s': %v", CustomConf, err)
		}
		if err := cfgSave.SaveTo(CustomConf); err != nil {
			log.Fatal(4, "Error saving generated JWT Secret to custom config: %v", err)
		}
```

`cfgSave.SaveTo()` is actually create a temporary file first, then write to the temporary file, after that, it then delete the old file, and rename the temporary file to the deleted file name.

I think this kind of operation causes the problem, as we `mount` the `/data/gitea/conf/app.ini` file inside the docker, so `rm` or `rename` operation will not be allowed. Here is what I tried to manually `rm` or `rename` the file:

```bash
$ docker run -it --rm -p 3001:3000 -v $PWD/conf/sqlite/app.ini:/data/gitea/conf/app.ini gitea/gitea:latest bash
bash-4.3# cd /data/gitea/conf/
bash-4.3# mount | grep app
osxfs on /data/gitea/conf/app.ini type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
bash-4.3# rm app.ini
rm: can't remove 'app.ini': Resource busy
bash-4.3# mv app.ini app.ini.tmp
mv: can't rename 'app.ini': Resource busy
```

The docker image of current version, `v1.1.2`, can be booted without any problem:

```bash
$ docker run -it --rm -p 3001:3000 -v $PWD/conf/sqlite/app.ini:/data/gitea/conf/app.ini gitea/gitea:1.1.2
Jul 22 17:31:02 syslogd started: BusyBox v1.24.2
Generating /data/ssh/ssh_host_ed25519_key...
Generating /data/ssh/ssh_host_rsa_key...
Generating /data/ssh/ssh_host_dsa_key...
Generating /data/ssh/ssh_host_ecdsa_key...
Jul 22 17:31:03 sshd[14]: Server listening on :: port 22.
Jul 22 17:31:03 sshd[14]: Server listening on 0.0.0.0 port 22.
2017/07/22 17:31:03 [T] Custom path: /data/gitea
2017/07/22 17:31:03 [T] Log path: /data/gitea/log
2017/07/22 17:31:03 [I] Gitea v1.1.2 built with: bindata, sqlite
2017/07/22 17:31:03 [I] Log Mode: Console(Trace)
2017/07/22 17:31:03 [I] XORM Log Mode: Console(Trace)
2017/07/22 17:31:03 [I] Cache Service Enabled
2017/07/22 17:31:03 [I] Session Service Enabled
2017/07/22 17:31:03 [I] PING DATABASE sqlite3
2017/07/22 17:31:03 [I] [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? [args] [version]
...
2017/07/22 17:31:11 Serving [::]:3000 with pid 13
2017/07/22 17:31:11 [I] Listen: http://0.0.0.0:3000
```

### PR DESCRIPTION
**Pull request by ethantkoenig**
~A short-term fix for #2197.~

~Fixing the underlying problem will involve changing the `SaveTo(..)` method in the `go-ini/ini` package, but this will at least~
1. ~Let Docker users run gitea in the meantime~
2. ~Mitigate the problem enough to not block the 1.2.0 release~

Fixes #2197. Updates the `SaveTo(..)` method in the `go-ini/ini` package. For the sake of not blocking the 1.2.0 release, I've temporarily updated the dependency to a fork. Once the fix to the `SaveTo(..)` method is merged into the main repository (go-ini/ini#115), we can revert.

### CODE REVIEW

**Comment by ethantkoenig** [comment]
See also https://github.com/go-ini/ini/pull/115

**Comment by sapk** [comment]
Why not updating vendor to migrate to a temporary fork if the issue take to much time?(https://github.com/kardianos/govendor/blob/master/doc/faq.md#q-ive-forked-a-package-and-i-havent-upstreamed-the-changes-yet-what-should-i-do) 
This would avoid ignoring error, no change on gitea code, and be revert when change is in upstream.

**Comment by lafriks** [comment]
I think that go-ini/ini fork with that change should be moved under gitea org

**Comment by ethantkoenig** [comment]
@lafriks Done

**Comment by sapk** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
