### PR TITLE
(Discontinued) Enforce two-factor authentication

### PR DESCRIPTION
**Pull request by wxiaoguang**
**Disclaimer**: Since this PR doesn't seem to be merged easily (https://github.com/go-gitea/gitea/issues/13606#issuecomment-947320267), and much more work need to do.

I just keep this PR for my personal usage, and update it with main branch regularly.

Anyone who want to continue the work for Enforced 2FA can pick this PR or start a new one.

----

* https://github.com/go-gitea/gitea/issues/880

Design:

1. A global setting `security.ENFORCE_TWO_FACTOR_AUTH`.
2. A user without 2FA can login and may explore, but can NOT read or write to any repositories.
3. Keep things as simple as possible.

### CODE REVIEW

**Comment by lunny** [comment]
How did you control the permssion?

**Comment by wxiaoguang** [comment]
> How did you control the permssion?

I just studied the logic of `IsRestricted`. For my understanding, the key points of permission control are `accessLevel` and `HasAccess`. In these two functions, if `GetTwoFactorByUID` fails, the return value is `AccessModeNone`. 

And unit tests are also updated with 2FA cases.

**Comment by techknowlogick** [comment]
There are new commits to this, is it still discontinued, or is it now a WIP?

**Comment by lunny** [comment]
Does this affect the first admin user registry?

**Comment by wxiaoguang** [comment]
Discontinued, I won't spend time on it.

**Comment by wxiaoguang** [comment]
A new try:  Enforce two-factor auth (2FA: TOTP or WebAuthn) #34187

**Pull request closed without merging**
