### PR TITLE
fix: delete attachment after remove comment.

### PR DESCRIPTION
**Pull request by appleboy**
We need to merge XORM bugs first https://github.com/go-xorm/xorm/pull/525 and also update vendor files.

ref: https://github.com/go-gitea/gitea/issues/677#issuecomment-273945141

### CODE REVIEW

**Comment by lunny** [comment]
@appleboy  go-xorm/xorm#525 merged.

**Comment by appleboy** [comment]
@lunny update `go-xorm` package and rebased.

**Comment by lunny** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
Make LGTM WORK!

**Pull request merged**
