### PR TITLE
Add thumbnail to dropzone when pasting images in to comments

### LINKED ISSUE #20130: Copy and paste the images has list legend
### Feature Description

At the moment, the pasted image in the issue content doesn't appear in the file list below (dropzone).

It's better to make the pasted image added into the file list legend below as the general upload file.

### Screenshots

image

### PR DESCRIPTION
**Pull request by tyroneyeh**
When pasting images into comment with an attached dropzone, add a thumbnail into the dropzone area.

Closes #20130

### CODE REVIEW

**Comment by zeripath** [comment]
```
Closes #20130
```

Doesn't describe what this PR is doing and what it is fixing.

Please update your description to make this clearer.

**Review by zeripath — APPROVED** [review]

**Comment by tyroneyeh** [comment]
> ```
> Closes #20130
> ```
> 
> Doesn't describe what this PR is doing and what it is fixing.
> 
> Please update your description to make this clearer.
> 
> I've done this for you.

Thank you very much

**Review by wxiaoguang — DISMISSED** [review]
I will take a look at this later (and make some changes). For exmplae: 

`this.element.parentElement.parentElement.querySelector('textarea')._data_easyMDE;`, is not ideal to access the internal member, there was a helper function (`getAttachedEasyMDE`).

And the duplicate code like `dropzone.dropzone.emit` could be removed after  #19776 .

And there are two different editors, one is EasyMDE, one is textarea, I do not think `editor.value(editor.value().replace(oldval, ''));` is suitable for both of them (maybe it's suitable, I will confirm later ... 😊)

**Comment by wxiaoguang** [comment]
I made some changes:

* Bug fix:
    * the removal doesn't work for simple textarea
    * the removal seems not working for `edit` on existing comment
* Refactaor
    * add files to dropzone in `uploadFile`, only one copy of the code
    * introduce general `removeUploadedFileFromEditor`
* Improvment
    * use regexp to remove texts in editor. eg: user may upload with filename "unamed" and get `unamed`, then they may change the text to `MyDocName`, the new logic can remove such changed text correctly.
* TODO
    * the logic in `initGlobalDropzone` is still fragile
    * the `fileUuidDict` is very suspicious

Although there are still TODOs, I have left comments there. I think this PR has done what it should do.

**Comment by wxiaoguang** [comment]
Hmm ... still some tricky bugs. I think I have fixed most of them and tested these pages: comment (new/edit), pull-request (new/edit/approve), release edit.

Almost done from my side. If no objection, I could vote a L-G-T-M after several days.

**Comment by tyroneyeh** [comment]
> Hmm ... still some tricky bugs. I think I have fixed most of them and tested these pages: comment (new/edit), pull-request (new/edit/approve), release edit.
> 
> Almost done from my side. If no objection, I could vote a L-G-T-M after several days.

https://github.com/go-gitea/gitea/blob/f07b0de997125c9b79cc5af27966a7cdd1803a4d/web_src/js/features/repo-legacy.js#L414

Maybe this is the event that triggers the removal of the file. If the pages are all refreshed, is this reload required?

**Comment by wxiaoguang** [comment]
Some `reload` events are for AJAX comment edit. For example, you click the `Edit` in the menu for an existing comment, cancel, and edit it again.

Some trivial logics here are still not 100% correct, but they were there and could be considered as out scope of this PR, so I think this PR is enough at the moment. Feel free to do more tests to see whether everything works.

FYI, the editor related pages are (IIRC):

* New Issue / View Issue: new comment, edit comment
* New PR / View PR: new comment, edit comment, approve/reject PR
* Release: New / Edit

(and every EasyMDE editor has simple textarea mode)

**Comment by tyroneyeh** [comment]
Hi @wxiaoguang any suggestions?

**Comment by wxiaoguang** [comment]
I haven't got time to test your new patch. Since the insert code changes again, have you tested it with simple textarea mode?

**Comment by tyroneyeh** [comment]
The simple text area mode can be uploaded normally, but the link of the attachment is not pasted to text area, I am researching this problem, thank you

**Comment by tyroneyeh** [comment]
So don't want this PR anymore?  close it?

**Comment by tyroneyeh** [comment]
I created a new PR #20263, so close this
Thanks

**Comment by wxiaoguang** [comment]
Maybe we can take this one first, IIRC I might have fixed the bug in this PR:
* https://github.com/go-gitea/gitea/issues/21588

The new PR (https://github.com/go-gitea/gitea/pull/20263#issuecomment-1206005837) is much more complex and I'm afraid it will be too difficult to maintain in the future, and I haven't got time to test or optimize it.

**Pull request closed without merging**
