### PR TITLE
Fix task-list checkbox styling

### LINKED ISSUE #9656: Missing space after checkbox
- Gitea version (or commit ref): v1.11.0-rc1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/transferkraM/markdown-checkbox-table
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Missing space between checkbox and following string.
## Screenshots

checkbox

### PR DESCRIPTION
**Pull request by cipherboy**
This pull request does two things:
 - Resolves #9656, by updating goldmark to v1.1.25 to incorporate [`goldmark-pr#112`](https://github.com/yuin/goldmark/pull/112). 
 - Styles task-lists to remove the bullets, when rendered with pandoc.

#9656 strictly describes the missing space. However, commenters asked for the bullet to be removed as well. This is a little more tricky as the [GFM spec](https://github.github.com/gfm/#task-list-items-extension-) doesn't mention adding a class to the `<ul>` (the way pandoc does). It might be possible to convince the goldmark maintainer to add that class though, I'm not sure.

An alternative is to wait until CSS4 selectors are available. This should include the [`:has()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has), which would allow us to select based on containing an input field. Something like `li:has(input[type="checkbox"])`. But caniuse says I [can't use it](https://caniuse.com/#search=%3Ahas) because nobody supports it.

----

When rendered with Pandoc, it now looks like:
Screenshot from 2020-03-08 10-22-36

----

When rendered with Goldmark, it now looks like:
Screenshot from 2020-03-08 10-25-07

----

**Note**: I'm using go v1.13.6 and it looks like the `go.sum` file didn't change correctly. What version of go should I be using to match this project's `go.sum` file preferences?

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
> What version of go should I be using to match this project's go.sum file preferences

Latest go 1.13 should be fine. We're not on 1.14 [yet](https://github.com/go-gitea/gitea/pull/10467).

This is LGTM, besides the odd checkbox rendering in those screenshots, but it's not related to this PR.

**Comment by silverwind** [comment]
Tried the PR. It does not seem to add the class for me:

image

image

**Comment by silverwind** [comment]
Nevermind, it does work with pandoc enabled, e.g. 

```
[markup.markdown]
ENABLED         = true
FILE_EXTENSIONS = .md,.markdown
RENDER_COMMAND  = pandoc -f markdown -t html --katex

**Comment by cipherboy** [comment]
> This is LGTM, besides the odd checkbox rendering in those screenshots, but it's not related to this PR.

Sorry, what's wrong with the checkboxes? If/when we get a class on the `<ul>` element or CSS4 selectors, we could fix the indentation to be consistent with GitHub (where a task list isn't indented and is more left-justified, unless it is nested obviously).

But the checkboxes themselves are correct. I'm on Fedora 31, under GNOME, and they match the system theme: 

Screenshot from 2020-03-08 14-44-19

> Tried the PR. It does not seem to add the class for me:

What are your rendering settings? As I mentioned above ("Styles task-lists to remove the bullets, when rendered _with pandoc_."), you have to use pandoc. My config is:

```ini
[markup.sanitizer]
ELEMENT    = span
ALLOW_ATTR = class
REGEXP     = ^(math\s*|inline\s*|display\s*){0,3}$

[markup.markdown]
ENABLED         = true
FILE_EXTENSIONS = .md,.markdown
RENDER_COMMAND  = bash /home/git/custom/conf/pandoc.sh
```

```bash
$ cat pandoc.sh
#!/bin/bash

export PANDOC_GITEA_PREFIX_SRC="$GITEA_PREFIX_SRC"
export PANDOC_GITEA_PREFIX_RAW="$GITEA_PREFIX_RAW"

pandoc -f markdown -t html -M PANDOC_GITEA_PREFIX_SRC="$GITEA_PREFIX_SRC" -M PANDOC_GITEA_PREFIX_RAW="$GITEA_PREFIX_RAW" --lua-filter=/home/git/custom/conf/pandoc.lua --katex
```

**Comment by silverwind** [comment]
> GNOME

Ah, that's why. They just look a bit "unusual" to me 😉 

Thanks for the pandoc info, I just switched to it.

**Comment by silverwind** [comment]
So to get this to work with the bluemonday sanitizer too, we need goldmark to add the class, right? Would you mind opening a goldmark issue on it?

**Comment by cipherboy** [comment]
@silverwind Yes, I can file the issue when I get back. I was trying to figure out how to add the class earlier but I didn't get far enough.

**Comment by cipherboy** [comment]
@silverwind -- filed as https://github.com/yuin/goldmark/issues/113.

**Pull request merged**
