### PR TITLE
Make repo private to not interfere with other tests

### PR DESCRIPTION
**Pull request by sapk**
Since dev of #2266 some tests were added. Change made in PR #2266 add a repo fixture that interfere with thoses tests. 

To fix that, I made the repo fixture private.

### CODE REVIEW

**Comment by strk** [comment]
trusted LGTM

**Comment by lafriks** [comment]
LGTM

**Comment by sapk** [comment]
Even if PR CI and local tests passed, It seems that it make master failed on gpg test ...

**Comment by lunny** [comment]
I have tested master(95c408f), tests is work.

**Comment by sapk** [comment]
@lunny It's seems that tests are randomly failing : https://drone.gitea.io/go-gitea/gitea/455 :cry: so maybe not related.

**Pull request merged**
