### PR TITLE
C preprocessor colors improvement

### LINKED ISSUE #18670: Wrong CSS for C code highlighting (light theme)
### Gitea Version

1.16.1

### Operating System

N/A

### Browser Version

N/A

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The light theme does not make a difference between preprocessor directives (`.cp`) and comment lines (`.cm`):
```
.chroma .cm { color: #999988; } /* CommentMultiline */
.chroma .cp { color: #999999; } /* CommentPreproc */
.chroma .cpf { color: #999999; } /* CommentPreprocFile */
```

 This makes the code difficult to read :

Screenshot_2022-02-08_11-50-04

`.cp` (and  possibly `.cpf`) should be different than comments.

For example (I am not an artist, so the values below are not a suggestion :-) : 
```
.chroma .cp { color: #109295 } /* CommentPreproc */
.chroma .cpf { color: #4C4DBC; } /* CommentPreprocFile */
```
Allow to  have a more readable code :

Screenshot_2022-02-08_11-54-40

### PR DESCRIPTION
**Pull request by braoult**
Fixes https://github.com/go-gitea/gitea/issues/18670

C comments and preprocessor had nearly-same colors in light theme.
Old values:
```
.chroma .cm { color: #999988; } /* CommentMultiline */
.chroma .cp { color: #999999; } /* CommentPreproc */
.chroma .cpf { color: #999999; } /* CommentPreprocFile */
```
Proposed values:
```
.chroma .cp { color: #109295 } /* CommentPreproc */
.chroma .cpf { color: #4C4DBC; } /* CommentPreprocFile */
```

### CODE REVIEW

**Comment by lunny** [comment]
Hi, could you post some screenshots before and after?

**Comment by braoult** [comment]
> Hi, could you post some screenshots before and after?

Screenshots were in #18670.

Before: 
Screenshot_2022-02-08_11-50-04

After:
Screenshot_2022-02-08_11-54-40

**Comment by braoult** [comment]
> Please also check/show screenshot in dark theme (Settings -> Account -> Select default theme).

Dark theme has different colors for preprocessor lines, this is why I did not change anything there :
Screenshot_2022-02-08_14-18-36

It does not have a different color for filenames, but this is not really an issue (I did hesitate before doing it to light theme).

**Comment by silverwind** [comment]
Background color comes from `--color-code-bg` which is defined here:

https://github.com/go-gitea/gitea/blob/c14ca34d576ab6be82ff93c05ddd1a9537269830/web_src/less/_base.less#L124
https://github.com/go-gitea/gitea/blob/c14ca34d576ab6be82ff93c05ddd1a9537269830/web_src/less/themes/theme-arc-green.less#L121

So essentially, the chroma files do not set background because background comes from the base theme (we need to restructure these variables later to be more clear).

Colors seem fine.

**Review by lafriks — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
