### PR TITLE
Don't ignore gravatar error

### PR DESCRIPTION
**Pull request by ethantkoenig**
Related to (__but ~does~ may not fix__) #2073.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by cez81** [comment]
LGTM

**Comment by lafriks** [comment]
I think on error it should return default avatar url

**Comment by cez81** [comment]
Hmm, guess you have a point there

**Comment by ethantkoenig** [comment]
@lafriks Good suggestion, updated

**Comment by andreynering** [comment]
Let LG-TM work

**Pull request merged**
