### PR TITLE
Don't print SQL in unit tests

### PR DESCRIPTION
**Pull request by ethantkoenig**
Currently, all SQL commands, from all tests, are printed to stdout (or maybe stderr?) when a unit test fails. This is too much output (thousands of lines) to be helpful as the default; you have to scroll through a bunch of unrelated output just to see which test failed.

Now, output will only be printed if the environment variable `$GITEA_UNIT_TESTS_VERBOSE` is set to true.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by techknowlogick** [comment]
LGTM

**Comment by lunny** [comment]
How about add an environment to enable that? Sometimes we need to know where is the error.

**Comment by ethantkoenig** [comment]
@lunny Done

**Pull request merged**
