### PR TITLE
Fix delete repo will hang on postgres

### LINKED ISSUE #1018: Deleting repos deletes from disk but not database
I created some repos as a normal (non-admin) user, which I can push to, etc. However I cannot delete them.

If I attempt to, on the "type the name of the repo to confirm" screen, it hangs forever when I click "Confirm".

On disk, the physical repo directory is deleted. However, the entries for the deleted repos remain on dashboard. If you click one you get a 500.

Attached [xorm.txt](https://github.com/go-gitea/gitea/files/795024/xorm.txt) is a snippet from `xorm.log` of all entries that are printed after clicking the button.

Primary server log (even at Trace level) shows only this:

    [Macaron] 2017-02-22 14:35:29: Started POST /morrildl/lol/settings for 172.17.0.1

I don't see any other relevant log output. Database is Postgres 9.6.

### PR DESCRIPTION
**Pull request by lunny**
fix #1018

### CODE REVIEW

**Comment by ethantkoenig** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by theAkito** [comment]
It's Oct 2018 and[ this issue ](https://github.com/go-gitea/gitea/issues/1018)still exists.

**Comment by lunny** [comment]
@Akito13 please fire another issue, since https://github.com/go-gitea/gitea/issues/1018#issuecomment-282356410 said he can confirm this issue fixed.

**Pull request merged**
