### PR TITLE
Fix org/team filter bugs

### LINKED ISSUE #26512: Teams filter has no effect in org level dashboard
### Description

This filter should select the repos belongs to the selected team.
image
But you can see that there's no repo belongs to this team, and all count numbers are `0`, but there are still some issues here.
image

Maybe the problem is that we will search all repos when the repo list is empty in the background. 
So I think not only issues but also PR and milestone dashboard have the same problem.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by CaiCandong**
fix #26512
relate https://github.com/go-gitea/gitea/pull/26012
### Before:
image

### After:
image

### CODE REVIEW

**Comment by lunny** [comment]
Maybe we need to fix other indexer types?

**Comment by CaiCandong** [comment]
> Maybe we need to fix other indexer types?

I am checking it

**Comment by wolfogre** [comment]
No, it's incorrect, we don't have to do this.

**Comment by CaiCandong** [comment]
> No, it's incorrect, we don't have to do this. I will send a alternative PR later.

how about #26490?

**Comment by wolfogre** [comment]
> how about #26490?

#26542

**Pull request closed without merging**
