### PR TITLE
Reduce usage of allcols on update

### PR DESCRIPTION
**Pull request by lunny**
Reduce some unneccessary of `AllCols` on update.

### CODE REVIEW

**Comment by lafriks** [comment]
Test fails for this

**Comment by lunny** [comment]
@lafriks done.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

Out of curiosity, what is the main benefit of only updating affected columns? Performance, or something else?

**Comment by lunny** [comment]
@ethantkoenig I think there are two reasons. One is for performance, another is to reduce the possibility of wrong updates. I remember the random avatar bug is affected by updating all the columns when login.

**Pull request merged**
