### PR TITLE
Fixed Issue of Review Menu Shown Behind

### LINKED ISSUE #31144: Review Menu Shown Behind
### Description

after #31062 popup menu shown behind if section collapsed

all headers are sticky and their `z-index` are same. so upper menu cant visible on front

https://github.com/go-gitea/gitea/blob/4fe415683e685838fde4e11f14f0309bbadb36e4/templates/repo/diff/box.tmpl#L113

if i decrease z-index of second header it work but i believe this is not the correct solution

### Screenshots

image

Edit:

Github uses extra class for menu's header

image

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

latest

### PR DESCRIPTION
**Pull request by kerwin612**
Fixed #31144  
054c7719ce64acf22e0b0aecba4910f

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — DISMISSED** [review]
I do not think the new JS code is right or maintainable.

**Comment by wxiaoguang** [comment]
And there is a regression bug from  Simplify review UI #31062 , the dropdown doesn't get properly initialized when "show more files"

**Comment by wxiaoguang** [comment]
Overall it should be like this 1957c87ac31b125035a8d4c76a0ca7038d387672

**Comment by kerwin612** [comment]
https://github.com/go-gitea/gitea/pull/32631/commits/9faaa4084588490d65e73b1b23d567669750a162

before:
ac67f50ea3444a00d0754c4c468825e

after:
013de5209d4d598acbe4f764124aa5d

**Review by wxiaoguang — COMMENTED** [review]
I guess some tests need to be fixed too

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
