### PR TITLE
hard code oauth app git-credential-oauth

### LINKED ISSUE #25189: Preconfigure Git Credential Manager as instance-wide OAuth application
### Feature Description

It would be really nice if there would be a instance-wide OAuth application only for the purpose of using it with the [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager) or [git-credential-oauth](https://github.com/hickford/git-credential-oauth). This would allow Git authentication *just work* without passwords, personal access tokens or SSH keys.

The OAuth client details for both helpers are redirect URI http://127.0.0.1/, only the client-id needs to be same between all instances.

There is also a similar request to Gitlab: https://gitlab.com/gitlab-org/gitlab/-/issues/374172

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by hickford**
Fixes https://github.com/go-gitea/gitea/issues/25189

### CODE REVIEW

**Comment by hickford** [comment]
Tested with https://github.com/hickford/git-credential-oauth/pull/28 and it works

**Review by 6543 — CHANGES_REQUESTED** [review]
hardcode ?!?

**Comment by wxiaoguang** [comment]
Hard-coding seems an interesting idea, but I think some questions should be answered first:

1. How to document it and how to display it?
2. How to disable it? 

It doesn't seem easy to maintain hard-coded oauth2 application

**Comment by hickford** [comment]
While authentication works, I think it will be buggy, because the application is missing the unique ID field.

For instance, the application is missing under Authorized OAuth2 Applications

**Pull request closed without merging**
