### PR TITLE
add quotation around ports in docker-compose.yml

### PR DESCRIPTION
**Pull request by bibaijin**
Without quotation around ports in docker-compose.yml, an error will occur when `docker-compose up`:

```
Creating network "test_gitea" with the default driver                                                                                            
Creating volume "test_gitea" with local driver                                                                                                   
Creating test_server_1 ...                                                                                                                       
Creating test_server_1 ... error
                                                                                                                                                 
ERROR: for test_server_1  Cannot create container for service server: b'invalid port specification: "601342"'

ERROR: for server  Cannot create container for service server: b'invalid port specification: "601342"'
ERROR: Encountered errors while bringing up the project.
```

According to yaml's specification, `:` is a special mark, which denotes map, so quotation is necessary to avoid ambiguity.

### CODE REVIEW

**Comment by lunny** [comment]
@bibaijin any rule reference link from docker?

**Comment by bibaijin** [comment]
@lunny [Here](https://docs.docker.com/compose/compose-file/compose-file-v2/#ports) is the example from docker-compose, although not described explicitly, all of the example port items is enclosed by quotation. And [https://github.com/docker/compose/issues/3109](https://github.com/docker/compose/issues/3109) describe this same problem, the solution is adding quotation.

Actually, it's related to yaml specification, not to docker-compose file specification. [Here](http://yaml.org/type/int.html) is yaml's referrence for int, in which colon expression is mentioned.

**Comment by lunny** [comment]
LGTM

**Comment by techknowlogick** [comment]
LGTM

**Pull request merged**
