### PR TITLE
Allow commit status popup on /pulls page

### PR DESCRIPTION
**Pull request by parnic**
The /pulls page doesn't contain a "repository" element, so the early-out here was preventing the commit status popup hook from working. However, the only thing the .repository element is being used for here is determining whether the popup should be on the right or on the left, so we don't actually need the element to exist for the hook to work.

### CODE REVIEW

**Comment by parnic** [comment]
Pull request #19375 allows the statuses on /pulls pages to appear clickable, but this commit is required to make the popup actually work there, so consider this an amendment to that PR (I would have just added this there, but that PR is already approved and waiting on being merged, so I didn't want to muddy the waters).

**Comment by wxiaoguang** [comment]
Which template? If the page (template) is repository related, it should have the CSS class `repository`.

Otherwise the `commit-statuses-trigger` related code could be extracted into a new dedicated function, instead of mixing them together.

**Comment by parnic** [comment]
> Which template? If the page (template) is repository related, it should have the CSS class `repository`.
> 
> Otherwise the `commit-statuses-trigger` related code could be extracted into a new dedicated function, instead of mixing them together.

This originates from `routers\web\user\home.go`'s `func Pulls(ctx *context.Context)` which ultimately ends up rendering `user/dashboard/issues`. For the Try.Gitea page, that would be https://try.gitea.io/pulls and the org/team-filtered-org version of the same page. No element on this page uses the `repository` class.

I'm happy to move that function somewhere else if that's more desirable.

**Comment by parnic** [comment]
@wxiaoguang pushed those changes.

**Review by wxiaoguang — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
:rock:

**Pull request merged**
