### PR TITLE
Change general form binding to gogs form

### PR DESCRIPTION
**Pull request by aamsur**
This PR is related to #7692 #8332

### CODE REVIEW

**Comment by guillep2k** [comment]
If I understand it correctly, this PR just specializes `newGenericWebhookPost` into `newGogsWebhookPost`, but does not change any behavior. Is that the intention? What is the motivation?

**Comment by lunny** [comment]
@guillep2k No. the emphasis is it changed the binding form

**Review by guillep2k — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by aamsur** [comment]
@guillep2k yes, and it will solves **_"HTTPMethod cannot be empty problem"_** when create gogs webhook. https://github.com/go-gitea/gitea/issues/8332

**Comment by 6543** [comment]
@lunny add lable backport done?

**Pull request merged**
