### PR TITLE
Milestone Issue/Pull List: Add octicons type

### LINKED ISSUE #11069: [UI] [Imprufement] Make Issue & Pull different view on Milestone list
Gitea Version: master

It's hard to see if it's a pull or an issue on milestone since there are both we should make them look different - at leas in a way to distinguish them

### PR DESCRIPTION
**Pull request by 6543**
close #11069

## Preview:
Screenshot at 2020-08-16 13-20-08 Screenshot at 2020-08-16 13-20-31

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Bit unrelated, but does the issue number need to be so prominent? Maybe move it to the second line similar to GH:

image

**Comment by 6543** [comment]
@silverwind in **my** opinion I like gitea's look more :)

**Comment by silverwind** [comment]
I think it's too distracting, but I can probably put up a PR later to restyle these lists. I think they also aren't properly vertically centered.

**Review by silverwind — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind thanks and 👀 to your pull :)

**Pull request merged**
