### PR TITLE
[WIP] confidential Issue

### PR DESCRIPTION
**Pull request by 6543**
as described in #3217 

## Who will be able to access: RepAdmin, Assignee, Poster

# ToDo
 * [x] FilterFunction
 * [ ] create caching table
 * [ ] use cached permissions in normal querys as condition
 * [ ] create UI things

# Take care of:
 * [ ] Issue API
 * [ ] Comment API
 * [ ] reaction API
 * [ ] Dashboard
 * [ ] Milestone
 * [ ] Dependency search
 * [ ] notifications
 * [ ] IssueCounters ?!?

# Notes:
 * creating query builder for "has addmin acces to repo of issue or is assignee or is poster" is getting to big
 * solution: simple filter function where needed + caching who has access to this issue in own table

### CODE REVIEW

**Comment by 6543** [comment]
Didnt had time the last days ...

**Comment by 6543** [comment]
Will have the next 1,5h not many free time - feel free to work on this - after this periotlde I'll do my best to get it in :)

**Comment by 6543** [comment]
.

**Comment by yardenshoham** [comment]
This is in progress for a while now, I'm closing it. Please reopen when it's ready for review.

**Pull request closed without merging**
