### PR TITLE
Support http service graceful restart

### PR DESCRIPTION
**Pull request by lunny**
This PR will let gitea support graceful upgrade. The upgrae setps are belwo:

1. Copy new gitea binary to replace gitea when gitea is running
2. run `kill -USR2 <gitea_pid>`

That's OK. Detail information please see github.com/facebookgo/grace

### CODE REVIEW

**Comment by bkcsoft** [comment]
Why not use https://github.com/fvbock/endless ?

**Comment by bkcsoft** [comment]
Disregard the previous question, endless only handles HTTP...

@lunny Why not use this for SSH as well? :)

**Comment by lunny** [comment]
I will try to send another PR for builtin SSH grace restart.

**Comment by metalmatze** [comment]
Isn't that going to be a feature of Go 1.8 in the stdlib? If so we should rather wait the couple of days left for the release to come out instead of using some external lib.

**Comment by lunny** [comment]
Go1.8 only support graceful shutdown, it's not enough.  `github.com/facebookgo/grace` is the most best lib I know.

**Comment by lunny** [comment]
@bkcsoft is https://github.com/fvbock/endless better?

**Comment by metalmatze** [comment]
https://tylerchr.blog/golang-18-whats-coming/
I think you're wrong. This is coming in 1.8.

**Comment by lunny** [comment]
@metalmatze only graceful shutdown? We need to write some code ourself to implement graceful restart.

**Comment by bkcsoft** [comment]
@lunny I've used endless before, hence the recommendation. BUT it only supports HTTP(S), not regular tcp-sockets

**Comment by bkcsoft** [comment]
LGTM with conflict

**Comment by lunny** [comment]
Let L-G-T-M work.

**Comment by appleboy** [comment]
@lunny `facebookgo/grace` doesn't support windows platform now. ref: https://github.com/facebookgo/grace/issues/15 .

**Pull request merged**
