### PR TITLE
word-break the WebHook url to prevent a ui-break

### LINKED ISSUE #5416: Webhook Url too long in UI
- Gitea version (or commit ref): 1.6.0
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
## Description
If the URL for a webhook is too long it will run out of the UI. Maybe a forced word-wrap could fix it.

## Screenshots
image

### PR DESCRIPTION
**Pull request by r-52**
right now, the url is displayed with an anchor tag with no classes. If the url is really really long, the url will break out of the containing div and (depending on the url length) the browser shows the horizontal scrollbar.
This pr makes use of the already existing css class `dont-break-out` which gives all the anchor the necessary properties to prevent the break.
Another solution could be to introduce some classes like `text text-break-word`, but that would duplicate the `dont-break-out` class just for text elements that use the `text` class.

fixes: https://github.com/go-gitea/gitea/issues/5416

Before:
image

After:
image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by adelowo** [comment]
You seem to be missing the  definition for “dont-break-out" ? Or is it an already defined class ?

Sorry I’m on mobile and cannot check or test the PR.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@adelowo it is already defined in gitea css

**Comment by lafriks** [comment]
@romankl can you please backport commit 06ef5b6 to `release/v1.6` branch?

**Comment by r-52** [comment]
Backport PR #5445

**Pull request merged**
