### PR TITLE
Add option to disable automatic mirror syncing.

### LINKED ISSUE #3562: Mirror settings -> interval: -1
- Gitea version (or commit ref): _Not relevant_
- Git version: _Not relevant_
- Operating system: _Not relevant_ 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: _Not relevant_

## Description

Maybe I'm the only one needing this feature, I don't know. The mirror interval setting is taking a value in "h", "m", "s" (with 10 minutes as the minimal value on [try.gitea.io](https://try.gitea.io/) which is not printed but anyway).

Imagine I want a repo to be a mirror but without automatic syncing. This way, when a click to the `Sync Now` button, the equivalent of a `git pull` would be done. However, I don't want the sync to be automatic (just for my case, the branch would be deleted for example).

So the idea is that the mirror interval setting would take `-1` as a value and this would mean no automatic syncing. Is this a too specific and personal functionality or can it be useful to other people too ? (maybe I'm using the tools is a bad way ..)

## Screenshots

_Not relevant_

### PR DESCRIPTION
**Pull request by cez81**
Setting the interval to 0 will disable to automatic syncing.

Closes https://github.com/go-gitea/gitea/issues/3562

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
hmm... why not just set the mirror interval to blank to disable automatic sync?

**Comment by lafriks** [comment]
@zeripath because it is number and can not be empty, imho

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Ah but it's not a number - It's an interval :wink: . You have units.

By using `0` to mean `never` you're breaking the semantics of the interval - `0` could easily mean `always`, `once`, `never`. A blank field is clearly not a valid interval. If there are other uses of an essentially nonsense number being used as flag in the UI - it's ok to add another, but it's a very C way doing things. 

~~BTW are there any limits on how often a mirroring can take place, e.g. should we really be able to set this to `1s`?~~ (Edit: stupid me of course there's a minimal interval it's even in the diffs)

**Comment by lafriks** [comment]
@zeripath but in the end interval is still converted to number of seconds (golang variable is number so it can not contain anything fancy :) )

**Comment by zeripath** [comment]
Ah, I see - using 0 makes the minimal change to the codebase.

Sorry, I was coming at it from a UI view. Exposing the 0 semantics doesn't make for the nicest UI - but it could be improved later with a little switch that says autosynchronize on/off and the interval box - requiring a non-zero value if on. 

I'll lgtm this though in the meantime from a point of view that it works, is simple and can be improved later.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
