### PR TITLE
respect value of REQUIRE_SIGNIN_VIEW

### LINKED ISSUE #5899: View releases  is visible with REQUIRE_SIGNIN_VIEW=true
- Gitea version (or commit ref): 1.7.0
- Git version: 2.20.1
- Operating system: Ubuntu 14.04.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

URL/user/project/releases is visible when **REQUIRE_SIGNIN_VIEW** is set to **true**

### PR DESCRIPTION
**Pull request by adelowo**
Fixes https://github.com/go-gitea/gitea/issues/5899

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Good catch. 

Is there an obvious test we can add?

I wonder if we can do some rationalisation of the :username/:repo routes. It might help prevent future situations like this if it was more explicit in the routes what had to be protected.

**Comment by zeripath** [comment]
@techknowlogick you mean #1763 ? Should we just review and get that in instead?

**Comment by techknowlogick** [comment]
@zeripath yes, that's the PR. However I'm not sure it covers all cases, so we should get this PR in as well.

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
Please backport to release v1.7

**Pull request merged**
