### PR TITLE
Improve grammar

### PR DESCRIPTION
**Pull request by pgaskin**

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
make L-G-TM work

**Comment by ulm0** [comment]
It would great if grammar for other languages is improved as well (e.g. I've seen some bad grammar that can be improve in Spanish)

**Comment by lafriks** [comment]
@klud1 you can fix errors/add missing translations to Spanish in crowdin: https://crowdin.com/translate/gitea/

**Comment by ulm0** [comment]
@lafriks it returns 404 page

**Comment by lafriks** [comment]
@klud1 Sorry, you are right, this will be right link https://crowdin.com/project/gitea

**Pull request merged**
