### PR TITLE
Add better error checking for inline html diff code

### PR DESCRIPTION
**Pull request by mrsdizzie**
A better fix for #13191 which cleans up this code a bit and adds basic checking which should avoid ever writing broken HTML in future situations.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
please send backport :)

**Comment by lafriks** [comment]
Please send backport

**Comment by mrsdizzie** [comment]
@lafriks already done : )

**Comment by zeripath** [comment]
keep the backport label so we know what it was backported to.

**Pull request merged**
