### PR TITLE
Update gitea/sdk vendor

### PR DESCRIPTION
**Pull request by ethantkoenig**
Brings in changes from https://github.com/go-gitea/go-sdk/commit/559190dbdcc3b73773d2866fa9f3ac7780a00820

### CODE REVIEW

**Comment by lunny** [comment]
drone failed

**Comment by ethantkoenig** [comment]
@lunny Fixed (some RPC issue with `git clone` in the first build; reran and it passed)

**Comment by lunny** [comment]
LGTM

**Comment by bkcsoft** [comment]
@ethantkoenig Why is this needed?

**Comment by ethantkoenig** [comment]
@bkcsoft I am planning to add API endpoints for editing/removing an organization's teams, and that will require `EditTeamOption`. See https://github.com/go-gitea/go-sdk/pull/25

**Comment by tboerger** [comment]
Than you should update the sdk together with that pr

**Comment by ethantkoenig** [comment]
@tboerger The SDK has already been updated; https://github.com/go-gitea/go-sdk/pull/25 has been merged.

It was my understanding that to make an update to the SDK, one first issues a PR to the SDK repo, and when that is merged, then issue a second PR to gitea that updates `vendors/` accordingly. Apologies if this isn't the right workflow.

**Comment by tboerger** [comment]
I was talking about updating vendor together with the api changes :)

**Comment by ethantkoenig** [comment]
Oh, will do!

**Pull request closed without merging**
