### PR TITLE
Disable Firefox E2E tests

### PR DESCRIPTION
**Pull request by silverwind**
Make CI green again, until we figure out https://github.com/go-gitea/gitea/issues/21355.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
Generally I'm against disabling tests to make CI work but this is too annoying and so I'm going agree with this.

**Comment by wxiaoguang** [comment]
Indeed, no real (useful) test is running in test-e2e step.

**Comment by silverwind** [comment]
And even if, I see browser testing in general as a unstable and risky business and by running multiples of them, we amplify that risk. I personally don't do browser testing any more, it's just a mess imho.

**Comment by wxiaoguang** [comment]
I would agree with silverwind, and I doubt whether there would be any useful  e2e  test cases  in the open-sourced Gitea repository. I don't mean that e2e is bad, but that might be the fact we are facing 😂

**Pull request merged**
