### PR TITLE
Update color theme for heatmap

### PR DESCRIPTION
**Pull request by MayMeow**
Creating this PR in case of update theme for heatmap as in issue in palette v4.

Related to #5864 

Signed-off-by: May <themaymeow@gmail.com>

### CODE REVIEW

**Comment by MayMeow** [comment]
changes can be viewed here

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
Can you please post before/after pictures?

**Comment by guillep2k** [comment]
> 
> 
> changes can be viewed here https://kittyverse.co/may?tab=activity

I actually see nothing. 😢

**Review by zeripath — APPROVED** [review]

**Comment by MayMeow** [comment]
Updated theme colors as its above...

Current scheme used by gitea has those colors

firefox_2019-10-27_21-56-16

This are colors which is in heatmap after changes

firefox_2019-10-27_21-56-42

Colors are from palette nr 4



which was discured [here](https://github.com/go-gitea/gitea/issues/5864#issuecomment-458242375)

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@lunny ready to merge :)

**Comment by 6543** [comment]
@lafriks backport to 1.10?

**Comment by lafriks** [comment]
It's not bugfix so it should not be backported to 1.10

**Pull request merged**
