### PR TITLE
Improve arc-green code theme (#21039)

### PR DESCRIPTION
**Pull request by silverwind**
Backport #21039

- Increase contrasts overall
- Add various missing theme classes
- Ensure strings and constants are colored the same across languages

Before:
Screen Shot 2022-09-03 at 15 20 19
Screen Shot 2022-09-03 at 15 10 12

After:
Screen Shot 2022-09-03 at 15 19 31
image

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by delvh** [comment]
?
Why are you targeting main?

**Comment by delvh** [comment]
image
Now I'm even more confused…

**Comment by lunny** [comment]
> image Now I'm even more confused…

I just want to help to change the base branch but found I cannot so I revert my change. Maybe @silverwind could rebase himself.

**Review by 6543 — APPROVED** [review]
didn't noticed wrong targeting branch first as pull diff was right :laughing:

**Comment by 6543** [comment]
fixed ;)

**Comment by silverwind** [comment]
Thanks for the branch fixes, looks good now I think.

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
