### PR TITLE
De-emphasize issue sidebar buttons

### PR DESCRIPTION
**Pull request by silverwind**
I find the colored buttons in the issue sidebar distracting, given that they are not primary actions, I think we can de-colorize them.

Before:
Screenshot 2023-07-26 at 19 42 22
Screenshot 2023-07-26 at 19 43 06
Screenshot 2023-07-26 at 19 44 36:

After:
Screenshot 2023-07-26 at 19 42 04
Screenshot 2023-07-26 at 19 42 51
Screenshot 2023-07-26 at 19 45 15

### CODE REVIEW

**Review by denyskon — APPROVED** [review]
Agree on it 👍

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
If there isn't a visual difference between the `Start Timer` and `Add time` button, we should perhaps add an icon to signify what button does what.
That helps for orientation when skimming through the sidebar.

**Comment by silverwind** [comment]
Indeed, we can add some icons to them.

**Review by puni9869 — APPROVED** [review]

**Comment by techknowlogick** [comment]
still WIP?

**Comment by silverwind** [comment]
Read now. Icons added:

Screenshot 2023-07-29 at 13 37 12
Screenshot 2023-07-29 at 13 36 56

Modal form margins and borders fixed:

Screenshot 2023-07-29 at 13 38 19

Links muted:

Screenshot 2023-07-29 at 13 41 02

**Pull request merged**
