### PR TITLE
[docker] drop the docker Makefile from the image

### PR DESCRIPTION
**Pull request by das7pad**
The `-` in front of the `include` statement causes `make` to ignore a missing file [1].

`make docker` will continue to work on the dev machine.

[1] https://www.gnu.org/software/make/manual/html_node/Include.html

### CODE REVIEW

**Comment by sapk** [comment]
@das7pad What is the goal/use case ?

**Comment by das7pad** [comment]
There is no need to have a Makefile with docker commands in the docker container.

**Comment by sapk** [comment]
@das7pad I was thinking that we only copy subfolder usr and etc. It must have changed or was on my todo list and think it was allready done.

**Review by sapk — APPROVED** [review]
I am more in favor on only copying subfolder etc and usr than re-adding another file at root project folder. But still LGTM

**Comment by das7pad** [comment]
I am fine with adding the two directories (`/etc` and `/usr`) explicit instead of re-adding the ignore file.

While preparing a patch I noticed that the Dockerfile commands `COPY` and `ADD` do not include the source directory. This line `COPY docker/etc docker/usr /` copies the contents of `docker/etc` and `docker/usr` into the root.
For example `docker/etc/nsswitch.conf` ends up as `/nsswitch.conf`.

I see two options at hand:
 - two layers for the 
 - copy `docker/etc` and `docker/usr` into a new directory and copy this directory into the docker images root
  e.g. `docker/etc` -> `docker/root/etc` and the Dockerfile line `COPY docker/root /`

Let's see what the other maintainers think about it.

**Comment by lafriks** [comment]
imho second option would be better

**Review by sapk — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
