### PR TITLE
Improve natural sort

### PR DESCRIPTION
**Pull request by wxiaoguang**
Hugely simplify the code, and add more tests (only new approach could pass)

### CODE REVIEW

**Comment by silverwind** [comment]
Maybe add some test cases from https://github.com/maruel/natural as well.

**Comment by wxiaoguang** [comment]
> How does the current algorithm compare to that package in terms of memory consumption/speed? Would it make sense to just depend on that package?

1. I would like to trust the official Golang package, and it has already been used.
2. The "NaturalSortLess" is not on the hot path. The code around it is much slower than it. So there should be no performance problem.


image

**Comment by wxiaoguang** [comment]
> If current implementation is kept, maybe add some test cases from https://github.com/maruel/natural as well.

`natural` doesn't work and won't pass the tests, because it doesn't handle "unicode"

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
> > If current implementation is kept, maybe add some test cases from https://github.com/maruel/natural as well.
> 
> `maruel/natural` doesn't work and won't pass the tests, because it doesn't handle "unicode"
> 
> And I think the current tests are good enough.

right, if it doesn't even support unicode, it's a no-go.

**Review by silverwind — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Pull request merged**
