### PR TITLE
Add support for ed25519_sk and ecdsa_sk SSH keys

### LINKED ISSUE #11203: ssh key ecdsa_sk support
- Gitea version (or commit ref): 1.11.4
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [ ] mariadb
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

openssh 8.2 introduced native u2f support with the new key type `ecdsa_sk`.  
Currently it is not possible to add such key to your gitea profile

error log
```
2020/04/24 06:50:06 ...user/setting/keys.go:96:KeysPost() [E] AddPublicKey: calcFingerprintSSHKeygen: 'ssh-keygen -lf /tmp/gitea_keytest979760198' failed with error 'exec(101286:AddPublicKey) failed: exit status 255(<nil>) stdout:  stderr: /tmp/gitea_keytest979760198 is not a public key file.\01503d
	': /tmp/gitea_keytest979760198 is not a public key file.\01503d
```
example public key

```
sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBGh2rclhwbyMMGVsERVKAgbYMlVmF7r7AYSddt6cZsTnG4V6XA2/mbKZlohsMRRJvURrUb0FR+izCIK9FY52cJwAAAAEc3NoOg== solo

```

### PR DESCRIPTION
**Pull request by artemist**
Fixes #11203
OpenSSH 8.2 or higher supports storing SSH keys on standard U2F keys using two new key types, one for P-256 ECDSA and one for ed25519 EdDSA. The Go built-in SSH server and OpenSSH server 8.2 or higher support these new types as client authentication keys. This PR allows users to specify these new key types as their SSH auth keys. I have tested that I am able to connect to gitea using both the built-in SSH server and OpenSSH server 8.3.

### CODE REVIEW

**Comment by artemist** [comment]
The build test failure appears to be because golang:1.15 uses Debian buster, which has OpenSSH 7.9, while OpenSSH 8.2 is required for support. I'm not sure how to workaround this cleanly.

**Comment by silverwind** [comment]
> OpenSSH 8.2 is required for support.

Probably need to detect OpenSSH version in the test and skip if too old.

**Comment by mrsdizzie** [comment]
IMO these changes are very minimal and don't touch any existing logic. These tests could just be commented out until it is possible to run them in the future with the golang container we use. 

Don't need to add extra code to detect a particular version of openssh if the version in our CI is always going to be too low and they will never run anyway.

**Comment by zeripath** [comment]
do we know if this very old version of ssh will always show a help page on `ssh-keygen --help` that includes the text:

```
                  [-t dsa | ecdsa | ed25519 | rsa]
```
?

If so it would be possible to parse this line and determine what keys ssh-keygen would accept.

**Comment by zeripath** [comment]
Arguably we'd be better off figuring out what things the SSH would accept.

**Comment by silverwind** [comment]
One can get a list of supported key algorithms via `ssh -Q key`:

````
 $ ssh -Q key
ssh-ed25519
ssh-ed25519-cert-v01@openssh.com
sk-ssh-ed25519@openssh.com
sk-ssh-ed25519-cert-v01@openssh.com
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
sk-ecdsa-sha2-nistp256@openssh.com
ssh-rsa-cert-v01@openssh.com
ssh-dss-cert-v01@openssh.com
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com
```

**Comment by zeripath** [comment]
that's ssh not sshd.

**Comment by silverwind** [comment]
Can't we just assume they are from the same package?

**Comment by zeripath** [comment]
even if they are the same package - just because the ssh command will accept these keys and has support for them does not mean that the sshd will accept them. It's entirely possible to set them differently - and quite common - for example note that your `ssh -Q` has reported `ssh-dss` - I would not be surprised if your sshd did not support `ssh-dss`.

**Comment by silverwind** [comment]
Maybe search the manpage? 😆 

```console
$ man sshd | grep "supported key" -A10
     is optional.  The supported key types are:

           sk-ecdsa-sha2-nistp256@openssh.com
           ecdsa-sha2-nistp256
           ecdsa-sha2-nistp384
           ecdsa-sha2-nistp521
           sk-ssh-ed25519@openssh.com
           ssh-ed25519
           ssh-dss
           ssh-rsa
```

**Comment by silverwind** [comment]
Should we disable the failing tests?

**Comment by mscherer** [comment]
Isn't that a way to see what is supported:
```
$ ssh -vvv 127.0.0.1 id 2>&1 |grep 'host key algorithms'
```

It return 2 lines and  the 2nd one is the remote supported keys after the key negociation:
```
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
```

I tested on a Debian and a RHEL 7, and indeed and it doesn't return the same lines: (for the 2nd line)
```
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa
```

So wouldn't it be sufficient ?

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/pull/13462#issuecomment-734241696 is probably the only way we can get t
autodetection working but I suspect even that is not going to work for every case - (for example it could easily be that you can't reach the SSH server from the Gitea or it's firewalled off.)

I think we might just have to have a set a of allowed types configured manually, (or at least some way of falling back to this.)

Probably can just reuse the SSH server settings already provided for the internal SSH server for this and we can try to add an autodetection option in some other pr. I guess that just means the best way of moving this PR forward is to comment out the tests or make it recognise the settings disallowing it.

**Comment by mscherer** [comment]
I only suggested autodetection for the tests, to implement the suggestion on  https://github.com/go-gitea/gitea/pull/13462#issuecomment-723537202 

E.g., we can detect what is supported on the platform with a ssh connection, and test only those type of keys. If we can't connect by ssh during the tests, they would fail anyway no matter what keys we try.

**Comment by zeripath** [comment]
OK I've updated the test to just skip it

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
@lafriks do we know if our docker openssh supports ed25519_sk, ecdsa_sk keys?

**Comment by lafriks** [comment]
We now have alpine 3.13 that has OpenSSH 8.4 so it should support it

**Pull request merged**
