### PR TITLE
Include --work-path flag in commands in authorized_keys

### LINKED ISSUE #15973: Properly set working directory in authorized_keys
- Gitea version (or commit ref): 1.14.2
- Git version: 2.20.1
- Operating system: Debian 10
- Using gitea from the official downloads
- Running gitea using the sample systemd service
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description

My `app.ini` doesn't explicitly configure any of the directories gitea uses, which means they're all set as their default values which are relative to AppWorkPath. In the systemd service, the `GITEA_WORK_DIR` environment variable is explicitly set as /var/lib/gitea, which is where I set up all of gitea's directories, so everything works fine.

However, I'm running gitea using the system SSH server. In authorized_keys, that environment variable isn't set, which means that AppWorkPath defaults to the location of the gitea binary (/usr/local/bin, as recommended in the official install instructions). With an incorrect AppWorkPath, gitea can't find any of the files it needs to run (aside from /etc/gitea/app.ini, which is preserved as a command-line option in authorized_keys, but which doesn't explicitly configure any of the other directories on my system). Therefore, nobody can access their repositories over SSH.

To fix this, we need to do one of:
- add a setting in app.ini to explicitly configure AppWorkPath
- add the --work-path command-line flag to the command in authorized_keys, as was suggested in #9481 but not implemented
- encourage placing the gitea binary in the desired work path, rather than in /usr/local/bin
- if the repository path, data path, etc, ought to be explicitly configured, then get rid of the defaults and die with an appropriate error when they're not configured

### PR DESCRIPTION
**Pull request by duxovni**
Fixes #15973

### CODE REVIEW

**Comment by jolheiser** [comment]
It looks like the tests are failing a comparison check. Can you please update them? :slightly_smiling_face:

**Comment by duxovni** [comment]
Sorry about that, I neglected to run `make test-sqlite` after `make test`. I'm doing a full test run now to make sure I've fixed it, and then I'll push here.

**Comment by zeripath** [comment]
I'm really not certain that this is necessary.

Why are you needing this? Gitea Serv and Hook shouldn't really need any thing that depends of AppWorkPath.

Could you please explain

**Comment by duxovni** [comment]
I explained in the linked issue. gitea definitely needs to know where my repositories are, and in the default config, those are defined relative to AppWorkPath.

**Comment by zeripath** [comment]
I've made a PR that makes the authorized_keys command a template

**Comment by techknowlogick** [comment]
Closing per merge of linked PR

**Pull request closed without merging**
