### PR TITLE
Fix dark theme highlight for "NameNamespace"

### PR DESCRIPTION
**Pull request by wxiaoguang**
The color is taken from "Name"

Before:

image

After:

image

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
BTW, this "_" seems like a bug:

image

**Comment by wxiaoguang** [comment]
> BTW, this "_" seems like a bug:

Because that element uses "class=divider", but the "ui divider" was also renamed to "divider", then the path divider is polluted.

**Comment by silverwind** [comment]
> 

working on it

**Comment by silverwind** [comment]
> > Because that element uses "class=divider", but the "ui divider" was also renamed to "divider", then the path divider is polluted.
> 
> working on it

https://github.com/go-gitea/gitea/pull/26524 for it.

**Review by lunny — APPROVED** [review]

**Pull request merged**
