### PR TITLE
Use single line per selector & don't strip license comments

### PR DESCRIPTION
**Pull request by xf-**
**Why?**
Every PR touching css needs a rebase after a single change in an merged PR. Single line will only conflict if the same line/area is modified. Less Builds, less conflicts

Also i added -s0 option. No comments with `?*!` will be removed (used for licenses).

I also would like the source map option, but isn't in code like all other options.

**Doku**
https://github.com/jakubpawlowicz/clean-css/tree/v3.0.1#how-to-use-clean-css-cli

### CODE REVIEW

**Comment by lafriks** [comment]
What is the size difference?

**Comment by xf-** [comment]
with gzip/brotli or without?

**Comment by xf-** [comment]
**With line-breaks:**

**Filesystem**:
98.8KB index.css
20.1KB theme-arc-green.css

**Transfered**
16.46KB (gzip level 6)
image

15.07KB (brotli standard level)
image

**Without line breaks**

**Filesystem**:
94.8KB index.css
19.8KB theme-arc-green.css

**Transfered**
16.41KB (gzip level 6)
image

15.03KB (brotli standard level)
image

**Comment by xf-** [comment]
@about few bytes. could be saved by removing some insane nesting like `.repository.file.list .non-diff-file-content .code-view .lines-commit .blame-info .blame-data .blame-message`.

Normally a linter is used to avoid stuff like this and get an more consistent less/sass file.

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
