### PR TITLE
[WIP] Search for issues/pulls

### PR DESCRIPTION
**Pull request by ethantkoenig**
Issue #379.

### CODE REVIEW

**Comment by tboerger** [comment]
As I already said I dislike this kind of search. IMHO this have to be resolved with an indexer

**Comment by tboerger** [comment]
This looks already promising, but maybe we should move the functionality into a service and also update the index in the background.

**Comment by lunny** [comment]
Yes. A service or a index queue is right action, not directly write index.

**Comment by ethantkoenig** [comment]
I've moved the index writes to a background service. It still uses one index per repository.

@lunny, in #379 you mentioned using a single index for all issues/pulls, and that we then wouldn't even need a SQL query for searching issues/pulls. I am confused how we could continue support existing filters (by tag, or by creator) only using a index. If you could explain, I would happy to work on that next.

**Comment by tboerger** [comment]
You need to index it with more attributes. Than you can still filter based on that.

**Comment by ethantkoenig** [comment]
So the index essentially becomes a second copy of the `issues` table (plus extra information like labels and mentions)?

**Comment by tboerger** [comment]
With the benefit to be a real search index, yes.

**Comment by ethantkoenig** [comment]
@lunny @tboerger I've added a single bleve indexer for all issues, containing all necessary attributes. I've also added a background service to asynchronously update the indexer when issues are created/edited/deleted.

**Comment by lunny** [comment]
I will review this

**Comment by tboerger** [comment]
This PR is broken, you need to properly rebase it.

**Comment by lunny** [comment]
```
git rebase master
# resolve conflicts
git push --force ethantkoenig:search_bar
```

**Pull request closed without merging**
