### PR TITLE
Enable packages by default again

### PR DESCRIPTION
**Pull request by delvh**
#19323 used the wrong default value to check if packages are globally disabled.
This means that unexpectedly, users that did not set `[packages] ENABLE = true` in their app.ini would simply not be able to use packages.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
> It may be better to remove that code and add something like this outside that method:
> 
> ```diff
> diff --git a/modules/setting/setting.go b/modules/setting/setting.go
> index 5e317b39e..553445658 100644
> --- a/modules/setting/setting.go
> +++ b/modules/setting/setting.go
> @@ -1024,6 +1024,10 @@ func loadFromConf(allowEmpty bool, extraConfig string) {
>  
>         newPackages()
>  
> +       if !Packages.Enabled {
> +               Repository.DisabledRepoUnits = append(Repository.DisabledRepoUnits, "repo.packages")
> +       }
> +
>         if err = Cfg.Section("ui").MapTo(&UI); err != nil {
>                 log.Fatal("Failed to map UI settings: %v", err)
>         } else if err = Cfg.Section("markdown").MapTo(&Markdown); err != nil {
> ```

unrelated but I think we should have a look at this too ...

**Comment by 6543** [comment]
same for Projects(KanBan)...

**Comment by lunny** [comment]
> ```diff
> loadFromConf
> ```

Yes, this maybe better because then there is only one place to read package configuration.

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
ok let's merge this and we can talk about refactoring next ...

**Pull request merged**
