### PR TITLE
Fix double scroll in branch dropdown

### PR DESCRIPTION
**Pull request by vedranMv**
Fixes double vertical scroll bar shown when creating new issue and opening branch dropdown (confirmed on Firefox, Chrome, IE)
firefox

Menu is created with a fixed height of 300px. Inner (#branch_list) list with branches, however, is the same size (I presume) as the list of branches on ``<Code>`` page - larger. Overflow results in second scrollbar. 
**Proposed fix:** remove height constraint on the dropdown as #branch_list already has ``max-height`` defined and scrollbar for y-overflow.

### CODE REVIEW

**Comment by guillep2k** [comment]
Hi, thank you for your contribution. Please change the `.less` file instead as the `.css` is generated from it.

**Comment by vedranMv** [comment]
Thanks for the tip, I'm still new and finding my way around this project :) Should the commit include only change to .less file, or do I include new index.css and package-lock.json?

**Comment by zeripath** [comment]
Unfortunately you need to change the CSS then run make css and commit the changes. (I think that's the command there's been a lot of changes in the past day and I've been deeply thinking about restart, queues and processing pools so have not been paying attention.)

**Comment by vedranMv** [comment]
I don't think I understand, sorry. .css is overwritten after ``make css``. What I see if i change _repository.less is that index.css and package-lock.json get changed as well. So I was wondering if I should include all 3 files in PR or just _repository.less

**Comment by zeripath** [comment]
I would just commit the CSS and the less - push it up and see if the CI complains. If it does then commit and push up the package-lock.json - however I suspect you're running Windows and your package-lock is likely changing because, well Windows, so if you straight commit that file CI might fail.

**Comment by vedranMv** [comment]
Okay e6197a2 should be it. I am actually developing from linux machine, but paths might be different nevertheless ^^

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Pull request merged**
