### PR TITLE
Unit tests for models/access.go

### PR DESCRIPTION
**Pull request by ethantkoenig**
Also adds some more test fixtures to `models/fixtures/`

### CODE REVIEW

**Comment by strk** [comment]
Thank you @ethantkoenig ! LGTM
Are you interested in becoming a maintainer of Gitea ? Would be great to have you onboard

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by ethantkoenig** [comment]
@strk Yes, I'm interested :smile:

**Comment by strk** [comment]
@ethantkoenig send a PR for the MAINTAINERS file

**Pull request merged**
