### PR TITLE
Move sdk structs to modules/structs

### PR DESCRIPTION
**Pull request by lunny**
This PR will move all structs maintaining APIs needed from `code.gitea.io/sdk-go` to this main repository's sub package `code.gitea.io/gitea/modules/structs`. That will make maintaining APIs easier. When creating a new API for gitea, an extra PR to `code.gitea.io/sdk-go` will not be a necessary.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
🎉 Thanks for PR :)

**Comment by techknowlogick** [comment]
CI Fail

**Comment by techknowlogick** [comment]
needs `make fmt`

**Comment by techknowlogick** [comment]
needs `make vendor` to cleanup `vendor/modules.txt `

**Comment by zeripath** [comment]
Hmm 2 things:
* Would it actually be better to call modules/structs modules/api?
* Is the SDK just going to import these from its code or will it keep its own copy?

**Comment by lunny** [comment]
@zeripath 
First, It only includes structs but not any codes we called `API`, so I don't think we should call it `API`.
Second, Yes, after this PR merged I will send another PR to `code.gitea.io/sdk-go` to remove all structs there and depend on this new package's specify version. That means you have to use `go mod` build `code.gitea.io/sdk-go` because `code.gitea.io/gitea/modules/structs` may have broken changes.

**Comment by zeripath** [comment]
Ok.

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
Should fixed #5954

**Pull request merged**
