### PR TITLE
Migrate to go-enry new version

### LINKED ISSUE #10476: More colors for language bar / language mapping like linguist
First of all: it's _awesome_ that @lafriks implemented this! :pray: 

- Gitea version (or commit ref): `1.12.0+dev-379-ge5944a952`
- Git version: -
- Operating system: -
- Database (use `[x]`): -
- Can you reproduce the bug at https://try.gitea.io:
  - yes, simply explore `try.gitea.io` for more examples
- Log gist: -

## Description

Languages are perfectly recognized but some colors are missing.

Maybe it would need a mapping or so?
Some examples:

| Detected language | Possible color mapping |
| ----------------- | ---------------------- |
| `HTML+ERB` | `HTML` ([example](https://try.gitea.io/AlexWayfer/flame)) |
| `Haml` | `HTML` ([example](https://try.gitea.io/alexanderadam/puzzle-puzzletime)) |
| `SCSS` | `CSS` ([example](https://try.gitea.io/alexanderadam/puzzle-puzzletime)) |

Github uses groups for this and properties are inherited from the parent group. For example [Haml inherits from HTML](https://github.com/github/linguist/blob/96ca71ab99c2f9928d5d69f4c08fd2a51440d045/lib/linguist/languages.yml#L2089-L2090).

## Screenshots

Screenshot_20200226_140920

Screenshot_20200226_141331

### PR DESCRIPTION
**Pull request by lafriks**
Migrate to https://github.com/go-enry/go-enry as projects under https://github.com/src-d  are no longer supported.

* Supports more languages by sync with Linguist v7.9.0

Fixes #10476

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
please run `make vendor` using go1.14.1

**Comment by lafriks** [comment]
@techknowlogick done ;)

**Review by mrsdizzie — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by techknowlogick** [comment]
ARM runners fail, I've tried restarting a few times, and it still fails, so something related to this PR is affecting it.

**Comment by techknowlogick** [comment]
This PR adds 9mins to the average CI build :(

**Comment by lunny** [comment]
> This PR adds 9mins to the average CI build :(

But why?

**Comment by lafriks** [comment]
Seems to be that only arm tests are affected... But I can not seem to see reason for this

**Comment by sapk** [comment]
CI seems fine now (without too much extra time). Can you update the PR ?

**Comment by lafriks** [comment]
Make lgtm work

**Comment by lafriks** [comment]
Again :)

**Pull request merged**
