### PR TITLE
Remove direct user adding to organization members

### PR DESCRIPTION
**Pull request by lafriks**
Reason for this as this button is very confusing and there is no much point in adding user directly as organization member he will still not be able to do anything more than if he would not be added. It just makes people more confusion why user can not access or do anything. Users should be to added to repository members by adding user to one or more this organization team

### CODE REVIEW

**Comment by Morlinest** [comment]
LGTM

**Comment by lunny** [comment]
So why github has this feature?

**Comment by lafriks** [comment]
@lunny because in github that actually grants some rights for members (like creating new repositories under that organization and new teams) while in Gitea it does nothing and all rights are checked only by team. And to be honest Gitea way to me seems a lot better and could be used for more use cases

**Comment by lunny** [comment]
LGTM

**Comment by Morlinest** [comment]
One question before sleep. What about users that was added this way? Do you want to ignore it or make migration to remove them?

**Comment by lunny** [comment]
@Morlinest they will stay the same behavior with before. Organization owners could remove them from organization or add them to some teams.

**Comment by lafriks** [comment]
They do not do any harm so they can stay. This change is just so that it would be less confusing and there would not be regular questions and issues that user is added to org. members but he still does not see nor can do anything

**Pull request merged**
