### PR TITLE
Remove go version check for make fmt

### PR DESCRIPTION
**Pull request by lafriks**
To not have problems with new versions of go

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by sapk** [comment]
We could simply use go1.7 tag on main.go ? This would drop support for 1.6 and below (even for compilation).

**Comment by sapk** [comment]
otherwise we should keep checking version for fmt and add 1.9 for required-gofmt-version.

**Comment by andreynering** [comment]
LGTM

**Comment by andreynering** [comment]
@sapk I think document which version are supported is enough. Otherwise will ever have to keep updating it for future versions of Go.

**Pull request merged**
