### PR TITLE
feat: add search repository on dashboard.

### PR DESCRIPTION
**Pull request by appleboy**
screen shots:

screen shot 2017-01-27 at 11 25 09 pm

### CODE REVIEW

**Comment by lunny** [comment]
How about put it in the topbar near the logo, just like github?

**Comment by appleboy** [comment]
This search bar just like GitHub dashboard.

screen shot 2017-01-27 at 11 52 06 pm

Login your account and try it out on https://github.com

**Comment by appleboy** [comment]
Related Gogs Issue comment. https://github.com/gogits/gogs/issues/4028#issuecomment-275635251

**Comment by andreynering** [comment]
LGTM

There's a thing that we may consider in the future.

Gitea will show only 15 repos in this box. GitHub do search for all repos, while this patch will search only for those 15 being showed.

**Comment by appleboy** [comment]
screen shot 2017-01-30 at 1 17 48 pm

@andreynering Github only shows 20 items and click bottom button to show all repositories.

**Comment by appleboy** [comment]
Maybe we can change Gitea behavior to load user all reposotories.

**Comment by lunny** [comment]
LGTM

**Comment by gsantner** [comment]
@appleboy My 2c:
Nice, thank you for implementing. I would suggest to include some repositories favorited/stared by user.

And also to push up repos in the repo list, if their wiki gets updated by the user. Currently repos only get to top if there were commits to the repo. -> Makes it also appear as search result

**Comment by bkcsoft** [comment]
> Maybe we can change Gitea behavior to load user all reposotories.

Please no. We should have a separate search-function that still limits (paginates) to the set limit :)

**Comment by appleboy** [comment]
@gsantner The search bar feature has been implemented by #787

**Comment by gsantner** [comment]
@appleboy Oh, yeah, but not merged to develop, so didn't test. Would the wiki part be much work?

**Comment by appleboy** [comment]
@gsantner No. not include wiki module.

**Pull request merged**
