### PR TITLE
API: Expose its limitation settings

### LINKED ISSUE #12664: [API] Expose MAX_RESPONSE_ITEMS for API
settings -> api.MaxResponseItems could differ from instance to instance

this makes it hard to implement a proper client pagination

### PR DESCRIPTION
**Pull request by 6543**
close #12664

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]
All of the new settings API should get tests at some point : )

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
**Lable** `kind/api` needed and milestone

**Review by techknowlogick — APPROVED** [review]

**Comment by 6543** [comment]
no it's still failing https://drone.gitea.io/go-gitea/gitea/29769/3/5 :(

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
