### PR TITLE
Handle base64 decoding correctly to avoid panic

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix the panic if the "base64 secret" is too long.

```
cmd/web.go:212:func1() [F] PANIC: runtime error: index out of range [2] with length 2
/usr/lib/go/src/runtime/panic.go:114 (0x56498b06155b)
        goPanicIndex: }
/usr/lib/go/src/encoding/base64/base64.go:378 (0x56498b21ee58)
        (*Encoding).decodeQuantum: case 3:
/usr/lib/go/src/encoding/base64/base64.go:546 (0x56498b21fd3e)
        (*Encoding).Decode: return n, err
/build/gitea/src/gitea/modules/setting/oauth2.go:129 (0x56498b689519)
/build/gitea/src/gitea/modules/setting/setting.go:123 (0x56498b6942f3)
/build/gitea/src/gitea/modules/setting/setting.go:108 (0x56498b694224)
```

### CODE REVIEW

**Comment by techknowlogick** [comment]
Could you add a test case?

**Comment by wxiaoguang** [comment]
Isn't there already one?

image

**Comment by techknowlogick** [comment]
@wxiaoguang ah yes, you are right. I tried to get one review in before sleep, but clearly I should've waited until tomorrow ;)

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by Zulgrib** [comment]
Thank you @wxiaoguang for your help yesterday, and for the fix!

**Pull request merged**
