### PR TITLE
 we need  use format as 'git clone https://oauth2:<token>@gitea.com/u…

### PR DESCRIPTION
**Pull request by GQH1993**
…sername/testcode.git' to clone code ,and failure occurred in the process!

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

### CODE REVIEW

**Comment by zeripath** [comment]
I don't understand how this could be helpful.

Let's take a look at the code:

https://github.com/go-gitea/gitea/blob/73cf0e2614263c8c4ad6d55d06e753b28d2b6091/routers/repo/http.go#L170-L247

First of all, L171 checks if the password is empty or equals the special string `"x-oauth-basic"`. If it is we set the flag `isUsernameToken` that the username should be checked if it is the oauth token. L173-L177 then set the potential `authToken` to either the username or password. Your change does not change this.

L178 checks if this `authToken` is an oauth token, returning a `uid` if so which is then used as the user. 

L189-L218 allows local tokens to override oauth tokens but they're almost never going to collide.

At L220 if you have successfully looked up an oauth user at L178 authUser will not be nil - so these sections will not be used - if not your change makes no difference as `isUsernameToken` is not used here and there are no further references to `isUsernameToken`.

**Review by zeripath — CHANGES_REQUESTED** [review]
This cannot be helpful. In this case the Username is not the Token the Password is the token.

**Comment by GQH1993** [comment]
We use a different format&nbsp; ,like gitlab use token clone code "&nbsp;git&nbsp;clone&nbsp;https://oauth2:ACCESS_TOKEN@somegitlab.com/vendor/pac...",&nbsp;&nbsp;



In order to be compatible with this way of use ;I recommend that when the username field is identified as 'oauth2',



Determines that the current request is to use ACCESS TOKEN clone code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zeripath"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 晚上6:00
收件人:&nbsp;"go-gitea/gitea"<gitea@noreply.github.com&gt;;
抄送:&nbsp;"像风一样飞翔"<gaiquanhe@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [go-gitea/gitea]  we need  use format as 'git clone https://oauth2:<token&gt;@gitea.com/u… (#10902)





 
@zeripath requested changes on this pull request.
  
This cannot be helpful. In this case the Username is not the Token the Password is the token.

**Comment by zeripath** [comment]
It already does that. Your PR does nothing to change that.

**Comment by zeripath** [comment]
If the password is an oauth token the username can be absolutely anything AFAIC from that code.

**Comment by GQH1993** [comment]
Thank&nbsp;you&nbsp;for&nbsp;your&nbsp;response ,and you can see&nbsp; at len 171 if&nbsp;authPasswd mismatch&nbsp;condition ,isUsernameToken Will always be false;
&nbsp;at len 191 because&nbsp;isUsernameToken is false , token will not be used




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zeripath"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 晚上6:12
收件人:&nbsp;"go-gitea/gitea"<gitea@noreply.github.com&gt;;
抄送:&nbsp;"像风一样飞翔"<gaiquanhe@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [go-gitea/gitea]  we need  use format as 'git clone https://oauth2:<token&gt;@gitea.com/u… (#10902)





 
If the password is an oauth token the username can be absolutely anything AFAIC from that code.

**Comment by GQH1993** [comment]
When&nbsp; authUsername is 'oauth2' isUsernameToken will&nbsp;be changed to true. and token will be used;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zeripath"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 晚上6:12
收件人:&nbsp;"go-gitea/gitea"<gitea@noreply.github.com&gt;;
抄送:&nbsp;"像风一样飞翔"<gaiquanhe@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [go-gitea/gitea]  we need  use format as 'git clone https://oauth2:<token&gt;@gitea.com/u… (#10902)





 
If the password is an oauth token the username can be absolutely anything AFAIC from that code.

**Comment by GQH1993** [comment]
Thank you for your response ,and you can see  at len 171 if authPasswd mismatch condition ,isUsernameToken Will always be false;
 at len 191 because isUsernameToken is false , token will not be used

**Comment by GQH1993** [comment]
When  authUsername is 'oauth2' isUsernameToken will be changed to true. and token will be used;

**Comment by zeripath** [comment]
I suggest you take another look.

**Comment by GQH1993** [comment]
I accept your opinion，but when we use 'https://oauth2:ACCESS_TOKEN@somegitlab.com/vendor/pac...' to clone code ，The system returns an exception in 198L, the query fails because the authUsername is 'oauth2' ; it will not continue to execute to 220L.

**Comment by GQH1993** [comment]
I have changed the modification method, please have a look,thank you~~

**Comment by zeripath** [comment]
OK, So if I understand correctly - you're not talking about an external OAUTH2 token - but rather tokens that Gitea creates?

Here you're suggesting relaxing the constraint that Gitea's tokens require you to login with the username and a valid token for that username?

**Comment by GQH1993** [comment]
That's right. I agree with you completely.

**Comment by GQH1993** [comment]
I think better compatibility will extend the life of the software，I recommend that you support additional ways to clone code,This is also the purpose of my modification

**Review by techknowlogick — CHANGES_REQUESTED** [review]
You could pass token as `http://token@gitea.example/api/v1/version` with no password currently, and as such I am hesitant to include this change.

**Comment by GQH1993** [comment]
Under the current logic, you can only support clone code with a token at the username location；And I think it is necessary to recognize the token in the password position, which will improve our compatibility and user experience；Just like the scene, we now use is http://oauth2:token@gitea.example/api/v1/version to clone code

**Comment by GQH1993** [comment]
I recommend that you consider supporting tokens in the password position

**Comment by zeripath** [comment]
We do - but with the correct username. That's what @techknowlogick was saying above.

Would it be possible to explain why you have the fake username oauth2? Is this fake username provided from some other thing? I guess we could add another option but it we're loathe to end-up with an explosion of options.

Do Github/Bitbucket/Gitlab do this?

**Comment by zeripath** [comment]
I honestly don't want to be awkward just want to do the correct thing.

**Comment by GQH1993** [comment]
I agree with you,this form like ’http://oauth2:token@gitea.example/api/v1/version‘ is used in gitlab clone code;

**Comment by GQH1993** [comment]
> We do - but with the correct username. That's what @techknowlogick was saying above.
> 
> Would it be possible to explain why you have the fake username oauth2? Is this fake username provided from some other thing? I guess we could add another option but it we're loathe to end-up with an explosion of options.
> 
> Do Github/Bitbucket/Gitlab do this?

This form like ’http://oauth2:token@gitea.example/api/v1/version‘ is used in gitlab clone code;

**Comment by zeripath** [comment]
OK, So looking again at our AccessToken structure - I don't think we can safely do this with our AccessTokens.

The tokens are structureless and are essentially just a password - so there is no guarantee that an accesstoken is unique. They're not OAuth2 tokens.

I think you need to look at how you're generating these tokens - as they're not OAuth2 tokens. You wouldn't have to change anything if you were using the OAuth2 grant system.

**Comment by zeripath** [comment]
So I've actually looked a bit further into this. I was mistaken slightly earlier.

It would be perfectly consistent to simply remove the username check completely from the accesstoken checks. The situation we have at present is inconsistent.

What I'm going to do is to put up two PRs:

1. Add two options REQUIRE_PROVIDED_USERNAME_MATCHES_TOKEN & REQUIRE_USERNAME_WITH_TOKEN and the resultant changes these would require. #11014 
2. Remove the checks on username. #11015 

Sorry to have misunderstood your requests earlier.

**Comment by GQH1993** [comment]
> So I've actually looked a bit further into this. I was mistaken slightly earlier.
> 
> It would be perfectly consistent to simply remove the username check completely from the accesstoken checks. The situation we have at present is inconsistent.
> 
> What I'm going to do is to put up two PRs:
> 
> 1. Add two options REQUIRE_PROVIDED_USERNAME_MATCHES_TOKEN & REQUIRE_USERNAME_WITH_TOKEN and the resultant changes these would require. #11014
> 2. Remove the checks on username. #11015
> 
> Sorry to have misunderstood your requests earlier.

It doesn't matter. Do you mean that I need to make more modifications according to the above two pr now?

**Pull request closed without merging**
