### PR TITLE
[Vendor] Update xanzy/go-gitlab v0.31.0 => v0.37.0

### PR DESCRIPTION
**Pull request by 6543**
as title

and adapt breaking changes (2d05d08)

### CODE REVIEW

**Comment by 6543** [comment]
@techknowlogick yes this was it ... go1.13 was needed

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
@6543 Please resolve the conflicts. I think this could be moved to v1.13 if it's ready to merge in time.

**Comment by 6543** [comment]
@lunny done

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
