### PR TITLE
[API] Load issue attributes when editing an issue

### LINKED ISSUE #6721: [API] Issue edit API does not replace assignee
- Gitea version (or commit ref): 1.8.0

Issue edit API(PATCH) does not replace assignees, but it adds though.
Example:
Add user1, then just pass user2 in the next call. Issue will have two assignees instead of only one user2.

https://try.gitea.io/api/v1/swagger#/issue/issueEditIssue

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #6721

Previously assignees on the issue were nil since they weren't loaded, which messed up any ranging that happened when comparing.

### CODE REVIEW

**Review by adelowo — APPROVED** [review]

**Comment by adelowo** [comment]
Nice catch... We really need more tests for the api handlers

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@jolheiser thanks for PR :) I'll be merging this once build is complete, could you create a backport PR once I merge this one?

**Comment by jolheiser** [comment]
@techknowlogick Sure thing! 😄

**Comment by lafriks** [comment]
Please create backport to 1.8 branch

**Pull request merged**
