### PR TITLE
Add link to example webhook receiver in documentation

### PR DESCRIPTION
**Pull request by mrexodia**
Adds a link to an example of a webhook receiver (https://github.com/mrexodia/go-gitea-webhook)

### CODE REVIEW

**Comment by lunny** [comment]
I think an unknown external link could not be accepted.

**Comment by mrexodia** [comment]
Yeah that makes sense, however I think it’s important to show examples in the documentation. Perhaps I could transfer the repository to the gitea organization after a code review?

**Comment by lunny** [comment]
@mrexodia yes, you can do that. Please send a PR and put the example in a suitable sub folder.

**Comment by mrexodia** [comment]
@lunny what would be a suitable location? I think it would be easier to transfer the repository to the `go-gitea` organisation. Should I do that?

**Comment by lunny** [comment]
@mrexodia I think we ever have a repository named `examples`.

**Comment by techknowlogick** [comment]
Closing per @lunny's comment.

**Comment by mrexodia** [comment]
My transfer request for the repository was never accepted, so I'm confused why this has been closed. I will create a new pull request though, which simply includes the code in the documentation so there is no problem with external links...

**Pull request closed without merging**
