### PR TITLE
change PIDFile default from /var/run/gitea.pid to /run/gitea.pid

### PR DESCRIPTION
**Pull request by flokli**
On most modern distributions, /var/run is deprecated and only kept for backwards compat according to
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html, and is a symlink to `/run/` on modern distributions.

Old Distros that still don't have `/run` can update the gitea default as described in from-source.en-us.md to point to the old location.

Follow-up on https://github.com/go-gitea/gitea/pull/12391#issuecomment-674449861 and https://github.com/go-gitea/gitea/pull/12485.

### CODE REVIEW

**Comment by 6543** [comment]
lable: kind/breaking

do we realy have to change this default?

**Comment by flokli** [comment]
> do we realy have to change this default?

I'm not sure why gitea would need to still point to a long-deprecated location.
The burden of using outdated paths should really be on those outdated distros, not applications.

Most userspace tools have defaulted to use `/run` these days (so packagers of such distros are used to having to change this).

Gitea provides a documented way to change the default, and it would be part of the release notes, too.

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
Kind of unrelated, but I question if we even need to have a PID file in the default configuration. Service managers like systemd can do just without one and by not having one, we can eliminate a whole class of potential errors related to stale pid files.

**Comment by zeripath** [comment]
@silverwind We don't create a pid file by default - it is only if the user requests one.

**Comment by silverwind** [comment]
Is that an undocumented option? I can't find anything related to pid files in `app.example.ini` or the cheat sheet docs.

**Comment by zeripath** [comment]
That's because it's not an app.ini option. It's a command line option:

https://docs.gitea.io/en-us/command-line/#web

**Pull request merged**
