### PR TITLE
Use media links for img in post-process

### LINKED ISSUE #8830: [Bug/Feature Request] Markdown parse Relative Links
Version: 1.11.0+dev-163-g86a44f6b4

## Support Relative Links

for example:
`picture`
**currently:** `https://<gitea-instance/<user>/img/00.png`
**how it should be:** `https://<gitea-instance/<user>/s/raw/branch/<branch>/img/00.png`

we also should parse something like:
**this:**  `` 
**to:** `/s/raw/branch/<branch>/metadata/en-US/phoneScreenshots/02.png" width="200" />`

since other github and gitlab? support this avter repo migration lot of broken links hapen ...

### LINKED ISSUE #10484: Few images in a row, only the first image works
- Gitea version (or commit ref): c161bb013e091c0bcc5

## Description

With a few images in a row, one per line, only the first image works. E.g. on https://try.gitea.io/kasbah/ruler , migrated from https://github.com/kitspace/ruler. On GitHub it's fine. Relevant markdown:

```markdown
![](front_no_panel.jpg)
![](back_no_panel.jpg)
![](front.jpg)
![](back.jpg)
![](front_populated.png)
```

If you put empty lines in between, it's fine. 

## Screenshots

image

### LINKED ISSUE #10506: issues with embedded images
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (<https://try.gitea.io/jonas-l/rechnen-android>)

## Description

It looks like two images without something in between are processed wrongly. In the linked case, a browser http basic auth dialog is shown. When scrolling down, then there is a row with one image and to the right of it, there is just the alternative text. The first image path is correctly <https://try.gitea.io/jonas-l/rechnen-android/media/branch/master/art/old-1.png>, the second one is <https://try.gitea.io/jonas-l/art/old-2.png> in the rendered version which does not work. In the source code, both are just relative urls:

```
![old config screen](./art/old-1.png)
![old training screen](./art/old-2.png)
```

...

## Screenshots

GitHub always rejected my screenshot uploads ...

### LINKED ISSUE #11482: Only first embedded image get correctly resolved to media/branch
Im am writing this issue because #10484 and #10506 are closed but the issue isn't fixed.

## Description

When you embed images only the first embedded image is shown.

E.g.:
```
![Coverage Branches](./coverage/badge-branches.png)
![Coverage Lines](./coverage/badge-lines.png)
![Coverage Functions](./coverage/badge-functions.png)
![Coverage Statements](./coverage/badge-statements.png)
```

Only my Coverage Branches gets resolved to `media/branch` the other images are resolved to a `src/branch` URL.

I didn't had this problem with old versions from Gitea, but since i upgraded to version 1.11.5 i have this problem too ... (i think i hadn't had this problem with 1.10.4)

## Screenshots

gitea_img_resolve

### PR DESCRIPTION
**Pull request by zeripath**
during the change to goldmark the relative links in markdown images were supported. This PR fixes the post-processor to do relative links for embedded html

Fix #8830 
Fixes #10484
Fixes #10506
Fixes #11482

### CODE REVIEW

**Comment by zeripath** [comment]
There is an issue in that imgs inside `<a>` are not munged at present because we can't detect if their text is already munged - I will have a think, I suspect it's quite simple that we don't run textNode processor once we're inside a link

**Comment by guillep2k** [comment]
Now I don't know if this is `kind/regression` or not.... 🤔

**Comment by 6543** [comment]
I'll test ...

**Review by 6543 — APPROVED** [review]
works lige a charm -  thx goldmark

**Review by guillep2k — APPROVED** [review]

**Pull request merged**
