### PR TITLE
Fix mkdir jwt - permission denied

### LINKED ISSUE #16218: [Bug] - mkdir jwt - permission denied
- Gitea version (or commit ref): `1.15.0+dev-453-g4fcae3d06` via Docker image `gitea/gitea:latest-rootless`
  
- Database:
  - [x] SQLite
## Description

```
...th2/jwtsigningkey.go:360:loadOrCreateAsymmetricKey() [F] Error generating private key: mkdir /var/lib/gitea/custom/jwt: permission denied
```

This causes the Docker container to continually restart.

Related issue: https://github.com/go-gitea/gitea/issues/15912
Related pull request: #16010

### PR DESCRIPTION
**Pull request by KN4CK3R**
The JWT certificate is now expected in the data directory. That's the same the ssh part does.

Ref #16010
Fixes #16218

### CODE REVIEW

**Comment by zeripath** [comment]
This is a difficult one because the other certificates are based in the custom directory too.

**Comment by KN4CK3R** [comment]
Personally I don't like that Gitea generates secrets if they are missing. If the user configured something which needs another setting it should just fail. In case of the JWT part it should not fallback to another hashing algorithm too.
The HTTPS and mail certificate are expected in the conf directory (not generated by Gitea). The SSH certificate is expected in the data directory (generated by Gitea) (maybe because of the same reason?).

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
we're probably gonna have to think of some way of migrating current users to the new form.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
