### PR TITLE
Fix bug in getting merged pull request by commit (#32079)

### LINKED ISSUE #32027: API shows unexpected PR for a commit
### Description

The API endpoint `GET /repos/{owner}/{repo}/commits/{sha}/pull` returns a pull request in more cases than I would expect:
I created the example repo https://demo.gitea.com/betanummeric/pr-test1 as an example:
```
* 2e0af5a76e4e02ff9ee4d52949d25fd229683754  (HEAD -> yetanother, origin/yetanother)
| * a8a7c696d7de8abd600798966caa4a47a6c420ca  (origin/other, other)
| * 827ed730869e32856e56da7be2a294dbf89a1b93  (origin/mergeme, mergeme)
|/  
* bd0050a443969356bf847bed330aa34a53be00cf  (origin/main, main)
```
I created a PR from branch `mergeme` to `main`: https://demo.gitea.com/betanummeric/pr-test1/pulls/1

The API returns that PR for every commit hash of the repo. I would have expected this to return the PR only for commit `827ed730869e32856e56da7be2a294dbf89a1b93`, because only that will be applied to the target branch in the PR.

I'm using this endpoint to determine if a push event relates to some PR. I work around by checking if the PR head matches the head of the push event.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

tested with gitea 1.22.1 and https://demo.gitea.com/ at 1.23.0+dev-464-g19af534462

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Backport #32079

Fix #32027

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by yp05327** [comment]
image
Where is this?

**Comment by lunny** [comment]
> image Where is this?

I think `:sha` is actually equal to `sha` here.

**Comment by yp05327** [comment]
It is equal, but the change not backport. 😕

**Comment by Zettat123** [comment]
> It is equal, but the change not backport. 😕

v1.22 does not have the `ctx.PathParam` method. So I just keep this line unchanged.

**Comment by yp05327** [comment]
It is not `does not have the ctx.PathParam method`, just a rename, see #31405

**Review by yp05327 — APPROVED** [review]

**Comment by Zettat123** [comment]
> It is not `does not have the ctx.PathParam method`, just a rename, see #31405 ps: I'm using `Gitlens` to check the line history. image

I've fixed the `:sha` param. Please help review again, thanks

**Comment by yp05327** [comment]
I have approved.
ps: `Gitlens` is not included in the dev container. Maybe we can add it.

**Review by wolfogre — APPROVED** [review]

**Pull request merged**
