### PR TITLE
remove unused vendor packages

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by sapk** [comment]
LGTM. By curiosity how do you found them ?

**Comment by lunny** [comment]
`govendor list` and if you found `vu` mark before a package. `u` means `unused`.

**Comment by sapk** [comment]
Strange that there not listed in `govendor status +outside +unused`

**Comment by sapk** [comment]
My mistake `govendor status` -> "Lists any packages missing, out-of-date, or modified locally." but not the unused ...

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
make L-G-T-M work

**Pull request merged**
