### PR TITLE
Check primary keys for all tables and drop ForeignReference

### LINKED ISSUE #21086: Primary keys are required in MySQL DB cluster
### Description

We use a hosted MySQL DB cluster service on digital ocean which requires that all tables have primary keys. Since version 1.17 there are tables without primary keys. This has happened once already in #16802. 

Are you able to fix this regression so we are able to update to the newest version? Thank you for your time.

### Gitea Version

1.16.9 (trying to update to 1.17)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/aqos156/b9b9b9f097ab926bec9be84fb34a1910

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker on swarm

### Database

MySQL

### PR DESCRIPTION
**Pull request by wolfogre**
Some dbs require that all tables have primary keys, see
- #16802
- #21086

We can add a test to keep it from being broken again.

Edit:

~Added missing primary key for `ForeignReference`~ Dropped the `ForeignReference` table to satisfy the check, so it closes #21086.

More context can be found in comments.

### CODE REVIEW

**Comment by wolfogre** [comment]
The CI check will keep failing until #21086 is resolved.

```text
--- FAIL: TestPrimaryKeys (0.00s)
    engine_test.go:84: table "foreign_reference" has no primary key
FAIL
```

**Comment by zeripath** [comment]
@wolfogre just add a primary key to the ForeignReference table and make a migration to add it

**Review by lunny — APPROVED** [review]

**Comment by wolfogre** [comment]
> @wolfogre just add a primary key to the ForeignReference table and make a migration to add it. This should do it:
> 
> PATCH

@zeripath Maybe we should open another PR to add a primary key and mark it closing #21086, I'll follow up once it has been merged. What do you think?

**Comment by zeripath** [comment]
Nah we'd be better off getting the primary key in in this pr and adding the check at the same time.

This is almost there. The only problem is that the migration isn't working for sqlite which probably should be changed to use the recreate table for that db. There's a previous migration that does similar for other tables so those should be checked in case I've missed something.

Then we can merge the fix and do the enforcement at the same time. If we don't then the enforcement may never be possible.

**Comment by wxiaoguang** [comment]
My opinion is to drop that table and remove all dead code.

**Comment by wolfogre** [comment]
😂 See? The [context](https://github.com/go-gitea/gitea/issues/21086#issuecomment-1318217453) is too complicated for me, so I prefer to solve the problem of ForeignReference table in another PR. We need a better place to discuss how to do it, adding a primary key? or dropping it?

I believe it should be neither here nor #21086, so a new PR is needed.

**Comment by zeripath** [comment]
@wolfogre I've fixed the migration.

@wxiaoguang I'm not sure what you mean - is this stuff entirely unused?

**Comment by wxiaoguang** [comment]
> @wolfogre I've fixed the migration.
> 
> @wxiaoguang I'm not sure what you mean - is this stuff entirely unused?

Yes, I have read the logic  again:
1.  It's not used at the moment (only inserts, no read) 
2. It's badly designed and doesn't look like to be used any more. https://github.com/go-gitea/gitea/issues/21086#issuecomment-1318217453

**Comment by lunny** [comment]
I think removing `ForeignReference` needs more work. I prefer to merge this one and removing it on another PR if we really want to remove it. We can find some context in #18446 .

**Comment by wxiaoguang** [comment]
> I think removing `ForeignReference` needs more work. I prefer to merge this one and removing it on another PR if we really want to remove it. We can find some context in #18446 .

What do you mean by "more  work"? At most, 30-minute work is enough, that's far less than the time wasted,  then no more dirty and dead code.

**Comment by wolfogre** [comment]
And now we have a new situation, the CI failed with:

```text
        testlogger.go:77: 2022/12/23 03:20:41 ...igrations/base/db.go:67:RecreateTable() [E] Unable to create uniques for table tmp_recreate__foreign_reference. Error: Error 1061: Duplicate key name 'UQE_tmp_recreate__foreign_reference_repo_foreign_type'
        migration_test.go:307: 
            	Error Trace:	/drone/src/migration_test.go:307
            	            				/drone/src/migration_test.go:335
            	Error:      	Received unexpected error:
            	            	migrate: Error 1061: Duplicate key name 'UQE_tmp_recreate__foreign_reference_repo_foreign_type'
            	Test:       	TestMigrations/Migrate-mysql-1.7.0
```

It was caused by recreating the `ForeignReference` table, I have no idea why. As wxiaoguang said, maybe it's a waste of time to figure it out.

I've changed my mind. I'll try to drop the table, let's see if it's easier.

**Review by wxiaoguang — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
