### PR TITLE
Remove unused vars

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
let L-G-T-M work

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by lunny** [comment]
It seems drone down

**Comment by tboerger** [comment]
But these vars should be used by protected branches

**Comment by lunny** [comment]
No. It's no need and no reference any more since I refactor the protected branch in #1030

**Comment by tboerger** [comment]
OK, LGTM

**Comment by lunny** [comment]
but it seems drone down.

**Comment by tboerger** [comment]
Maybe do some force push to retrigger a build. Other prs have been tested fine

**Comment by lunny** [comment]
let L-G-T-M work

**Pull request merged**
