### PR TITLE
Support reverse proxy providing email

### PR DESCRIPTION
**Pull request by zeripath**
This PR implements #2347 by allowing the reverse proxy to set the email address on auto-register.

The current implementation does not allow for changing the email address using the reverse proxy - perhaps it should?

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Please add to example app.ini the conf value as well

**Comment by zeripath** [comment]
I knew there was somewhere else. The other values aren't in the example app.ini - I guess I should add those too

**Comment by zeripath** [comment]
> I knew there was somewhere else. The other values aren't in the example app.ini - I guess I should add those too

OK that was weird - so I searched again today and the original values pop up in the app.ini.sample ... I'm not sure what happened there!

**Comment by zeripath** [comment]
@techknowlogick : I've added the appropriate lines to `custom/conf/app.ini.sample`

**Review by techknowlogick — APPROVED** [review]
@zeripath Look's great!

**Review by lafriks — APPROVED** [review]

**Pull request merged**
