### PR TITLE
Add title attribute to dependencies in sidebar

### LINKED ISSUE #19806: can not read the full title of issues in dependency list of an issue
### Description

See the list on dependencys/ blocks of issues https://try.gitea.io/company/testsB/issues/1

A fix: Each link need a title attribute containing the `<a ..title="MISSING" ...>` node value. thats all. Hover over the link displays the complete title. its hidden by css 

### Gitea Version

1.6.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

FF 91.9.1esr (64-Bit)

### PR DESCRIPTION
**Pull request by zeripath**
Add the full title as the title attribute on dependencies in
the sidebar.

Fix #19806

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
I think class `tooltip` with `data-content` should be prefered over `title`.

**Comment by delvh** [comment]
As far as I can see:
The only thing speaking against `title` is its release date:
It seems to have been accepted into the standard not too long ago, resulting in only being usable on about 55% of all devices.
For the future (say perhaps in three years), I think we should abandon using `tooltip` with `data-content` for using `title` instead as it makes more sense to use the browser-native version than one depending on external JS.

**Review by techknowlogick — APPROVED** [review]

**Review by hello-smile6 — COMMENTED** [review]
Would approve, but I can't.

**Comment by silverwind** [comment]
> As far as I can see: The only thing speaking against `title` is its release date: It seems to have been accepted into the standard not too long ago, resulting in only being usable on about 55% of all devices. For the future (say perhaps in three years), I think we should abandon using `tooltip` with `data-content` for using `title` instead as it makes more sense to use the browser-native version than one depending on external JS.

`title` attribute is not a new browser features, it' ancient. It can not be styled and at least in Firefox, it results in a tiny text, with like 10px font size which is borderline unreadable to me, that's why I advocate JS-based tooltips. While there are also CSS-based tooltips, those have far too many issues with z-index and such and I would not consider them.

**Comment by delvh** [comment]
> `title` attribute is not a new browser features, it' ancient.

Ancient?
Why do both `Firefox` and `Chrome` only support it since late April 2022 then?
The only browsers it is ancient for are `IE` and `Edge`...
(https://caniuse.com/mdn-html_global_attributes_title)

> It can not be styled and at least in Firefox, it results in a tiny text, with like 10px font size which is borderline unreadable to me, that's why I advocate JS-based tooltips. While there are also CSS-based tooltips, those have far too many issues with z-index and such and I would not consider them.

That, however, is a valid reason, even though I think this is one of the things, we actually don't want to style ourselves...
The browsers should know themselves what a good default value for it is.

**Comment by silverwind** [comment]
>  Why do both Firefox and Chrome only support it since late April 2022 then?

Seems like inaccurate CanIUse data, the MDN table is better: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#browser_compatibility

`title` attribute dates back to Netscape days I think, it's really ancient.

**Review by silverwind — APPROVED** [review]
Better than before, but I'd still prefer all `title` usage to be refactored to use `tooltip` later. It's just better UX than `title`.

**Review by delvh — APPROVED** [review]

**Pull request merged**
