### PR TITLE
Fix repo graph JS

### LINKED ISSUE #31376: Promise rejection when filtering branch in commit graph
### Description

[self-hosted private Gitea 1.22]

In the commit graph, I start filtering for the master branch.

image

I sometimes get the following error, although a page refresh fixes it.

> JavaScript promise rejection: un.getElementById is not a function. Open browser console to see more details.

image

In the console I get

```
Uncaught (in promise) TypeError: un.getElementById is not a function
    si repo-graph.js:72
```

image

When looking up the JS, this is the part it refers to

```js
  const updateGraph = () => {
    const queryString = params.toString();
    const ajaxUrl = new URL(url);
    ajaxUrl.searchParams.set('div-only', 'true');
    window.history.replaceState({}, '', queryString ? `?${queryString}` : window.location.pathname);
    document.getElementById('pagination').innerHTML = '';
    hideElem('#rel-container');
    hideElem('#rev-container');
    showElem('#loading-indicator');
    (async () => {
      const response = await GET(String(ajaxUrl));
      const html = await response.text();
      const div = document.createElement('div');
      div.innerHTML = html;
*FAIL* document.getElementById('pagination').innerHTML = div.getElementById('pagination').innerHTML;
      document.getElementById('rel-container').innerHTML = div.getElementById('rel-container').innerHTML;
      document.getElementById('rev-container').innerHTML = div.getElementById('rev-container').innerHTML;
      hideElem('#loading-indicator');
      showElem('#rel-container');
      showElem('#rev-container');
    })();
  };
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Debian

### How are you running Gitea?

Self hosted, running on the host debian system (a VM, not a container), using the pre-built binaries from official release

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #31376
Regression of #30395

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
So the bug has been fixed in v1.23?

**Comment by wxiaoguang** [comment]
> So the bug has been fixed in v1.23?

We do not use getElementById in 1.23

**Comment by silverwind** [comment]
Note that this is `div.getElementById`, which was invalid of course. This is something typescript would have detected.

**Comment by silverwind** [comment]
The bug was actually fixed as a side-effect during the refactor:

https://github.com/go-gitea/gitea/commit/507fbf4c3ceffba9143edbe421a134b904210a4c#diff-b1b78ba5dc4cc4c29c14bdb3285dcb7e2893f4afd4904659c6afdad99a49b917R72-R74

This is actually a bug in the eslint rule that it even touched this.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Typescript addition is no rewrite. It's more of an enhancement of existing code. Adding type signatures to function already gets you 90% there because the type inference is very good.

**Comment by wxiaoguang** [comment]
Most bugs are caused by refactoring & rewriting & accessing HTML data/HTTP response. I do not see how typescript would really help daily development at the moment if it doesn't help the refactoring&rewriting work. So at the moment I am not sure whether it is the right time to introduce it. That's just my opinion, I don't understand and I won't block.

**Comment by wxiaoguang** [comment]
My suggestion is: if a new approach would be introduced, then start it from the hardest part, for example: rewrite `repo-legacy` or something similar to make sure the new approach really works as expected.

**Comment by silverwind** [comment]
If I refactor a part of the code, I would definitely want the new parts to be type-safe so it would definitely help in combing the work of type safety and general refactoring which both can be done in one go.

I have been writing a lot of typescript lately, and I find it quite scary to touch a JS codebase now given the lack of "safety nets" provided by typescript.

**Pull request merged**
