### PR TITLE
Unifies commit list in repository commit table and wiki revision page

### PR DESCRIPTION
**Pull request by saitho**
I noticed that there are two commit lists (repository and wiki) that are mostly identical, with the only difference being that the commit is linked for repository and is not in wiki.

We should merge those in order to reduce LOC and to ensure changes made to the commit list are valid for all occurences.

### CODE REVIEW

**Review by typeless — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Please resolve conflicts.

**Comment by lunny** [comment]
@saitho Please resolve conflicts.

**Comment by saitho** [comment]
Conflicts resolved. Three changes were made to the commit list which I transfered to the new template file:

- zeripath* 16.10.19, 15:42 Sign merges, CRUD, Wiki and Repository initialisation with gpg key (#7631)
- jaqra* 10.09.19, 11:03 Make link last commit massages in repository home page and commit tables (#8006)
- Gary Kim* 20.08.19, 14:40 Provide links in commit summaries in commits table/view list (#7659)

I currently don't have a test case covering signed commits. To be sure someone should test that with the respective test cases and look at the different commit lists. ;)

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
@saitho your changes appear to work correctly for signed commits

**Comment by zeripath** [comment]
Thanks @saitho sorry it took so long to merge.

**Pull request merged**
