### PR TITLE
Reduce unnecessary build on ci

### PR DESCRIPTION
**Pull request by lunny**
There are too much build on CI. I think most of them are necessary. This PR remove unnecessary build on CI.

### CODE REVIEW

**Comment by yp05327** [comment]
Some steps are `depends_on: [build]`

**Comment by lunny** [comment]
> Some steps are `depends_on: [build]`

fixed.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
```
make[1]: *** No rule to make target 'modules/public/bindata.go', needed by 'migrations.mysql.test'.  Stop.
```

Might need to run `generate`, thought I'm still hoping for https://github.com/go-gitea/gitea/pull/22887 to be ready so we can get rid of `generate`.

**Comment by lunny** [comment]
CI has been changed in other PRs, so I think this could be closed.

**Pull request closed without merging**
