### PR TITLE
Apply to became a maintainer.

### PR DESCRIPTION
**Pull request by puni9869**
Hi Gitea Team, 
I would like to apply as a maintainer.
I don't have that much in-depth knowledge of the codebase, but I would like to help to review PRs for the beginning in my free time and contribute in frontend, backend tasks and new proposals. 

Here is my PR list:-  https://github.com/go-gitea/gitea/pulls?q=is%3Apr+author%3Apuni9869+is%3Amerged+

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wolfogre** [comment]
Welcome! 🎉

BTW, maybe "And myself to maintainers" or "Apply to become a maintainer" is good enough as the title. I am not a native English speaker, I can understand "Application as a maintainer", but it sounds weird to me, something like:

<details>
<summary>Just a friendly joke, if you find it offensive, please don't expend</summary>

image

</details>

Never mind, welcome again!

**Review by wolfogre — APPROVED** [review]

**Comment by puni9869** [comment]
> Welcome! 🎉
> 
> 
> 
> BTW, maybe "And myself to maintainers" or "Apply to become a maintainer" is good enough as the title. I am not a native English speaker, I can understand "Application as a maintainer", but it sounds weird to me, something like:
> 
> 
> 
> <details>
> 
> <summary>Just a friendly joke, if you find it offensive, I will remove it</summary>
> 
> 
> 
> image
> 
> 
> 
> </details>
> 
> 
> 
> Never mind, welcome again!

Haha.. Its fine.

**Review by KN4CK3R — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@puni9869 whats your discord handle?

**Comment by puni9869** [comment]
> @puni9869 whats your discord handle?

The same as @puni9869

**Comment by puni9869** [comment]
> (Sidenote: That was not relevant anymore, as I was already able to make you a maintainer in Discord 😄)

For the record...

**Pull request merged**
