### PR TITLE
Improve URL validation for external wiki  and external issues

### LINKED ISSUE #4703: [Security] Stored XSS. Account Takeover possilble.
- Gitea version (or commit ref): any version with external issue tracker
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #4703

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lafriks I have some thoughts about blocking localhost URLs. Some users might host Gitea behind a reverse proxy under a sub-path which means they might need to have localhost (or 127.0.0.1) as a valid external issues URL (assuming they host everything on same machine).

Edit: We should deal with blocking in the SSRF patch to make it customizable.

**Comment by lafriks** [comment]
@techknowlogick even if you run gitea behind reverse proxy this validates only URL's that will be presented for user not server<->server communication.

**Comment by techknowlogick** [comment]
@lafriks yes, I understand. But a user might run JIRA locally (hopefully they don't), but that might be possible, this would block them from doing that.

**Comment by lafriks** [comment]
when creating these function I had in mind to reused/extend them for SSRF fix later but this is not what this PRs is about :)

**Comment by lafriks** [comment]
You mean user is running gitea&jira on local laptop and accessing it by localhost? Chance of such need is close to zero and anyway you can use your hostname/lan ip. Besides this PR will not break existing configurations but just won't allow adding such urls in future

**Comment by techknowlogick** [comment]
@lafriks lolya. that's correct. I also believe chance is near zero, but as this wouldn't prevent a DNS re-binding attach (say for example I set local.techknowlogick.com to 127.0.0.1) this would bypass our validation and would be accepted, so I think unless we do a DNS lookup for the URL we shouldn't block it unless we block all cases.

My opinion is weakly held, I also see the merits of what you've said, so my LG-TM on this PR still applies.

Edit: Fixed my typos

**Comment by techknowlogick** [comment]
@lafriks I see the TODO now (thanks for the reminder in chat). That's acceptable for me. Please disregard what I've said above. My LG-TM is now 100%

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work

**Comment by lunny** [comment]
@lafriks  please send a back port PR.

**Comment by wxiaoguang** [comment]
-> Remove IsValidExternalURL/IsAPIURL and use IsValidURL at call sites #37364

**Pull request merged**
