### PR TITLE
Fix relative markdown links with anchors

### LINKED ISSUE #3784: markdown link anchor issue
- Gitea version (or commit ref): 1.4.0
- Git version: *not related*
- Operating system: *not related*
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/g/test-anchor-bug/src/branch/master/README.md
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

A markdown link with anchor is rendered as a html URL `page%23anchor` instead of `page#anchor`.
On https://try.gitea.io/g/test-anchor-bug/src/branch/master/README.md 
the link to "foo.md#bar" is
https://try.gitea.io/g/test-anchor-bug/src/branch/master/foo.md%23bar
but should be
https://try.gitea.io/g/test-anchor-bug/src/branch/master/foo.md#bar

The README.md content:
```
# test-anchor-bug

* [link bug 1](foo.md#bar)
* [link bug 2][bug2]

[bug2]: foo.md#bar
```

## Screenshots

Screenshot is not usefull.

### PR DESCRIPTION
**Pull request by jonasfranz**
Fix #3784 

This is not the most elegant solution but it works.

### CODE REVIEW

**Review by sapk — CHANGES_REQUESTED** [review]
Please use https://golang.org/pkg/net/url/#URL.ResolveReference .
As it is the recommended way to do it.

**Comment by jonasfranz** [comment]
@sapk If I use `URL.ResolveReference`, the other test cases fail.

**Comment by sapk** [comment]
@JonasFranzDEV Only relative one are failing https://play.golang.org/p/kk0OHdtTg0i

**Comment by sapk** [comment]
And this could easely be check by u.IsAbs()

**Review by sapk — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
@JonasFranzDEV please send back port to release/v1.4

**Pull request merged**
