### PR TITLE
fix truncate utf8 string

### PR DESCRIPTION
**Pull request by palytoxin**
<del>I removed the truncate operation before updating because it goes through the form validation before updating again. the truncate operation is redundant.

And</del> I fixed the problem of truncating utf8 strings, in special cases, the truncation operation would cause the database storage to fail to detect the encoding

### CODE REVIEW

**Comment by a1012112796** [comment]
> And I fixed the problem of truncating utf8 strings, in special cases, the truncation operation would cause the database storage to fail to detect the encoding

Suggest move this change to a new pull request, Thanks.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
I dont think we need a sec pull for this nit. Throu when backporting we should only backport the fix

**Review by a1012112796 — APPROVED** [review]

**Review by zeripath — DISMISSED** [review]
blocked

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Sorry about that @palytoxin - it would be fine to make it a config option with the current default but realistically these fields shouldn't be in models.User. They need to be in some other table models.Settings or Config or UserConfig. Most of the time we're loading the user object we do not want or care about the contents of the location or description attributes and it's fine to load them if they're small but if you're allowing them to get big well ... Then we need to move them off of user.

**Comment by palytoxin** [comment]
yes, I got. bug move them off of user may need to be modified by someone who knows more about this project, otherwise it makes new bugs.

---

But these columns have been validated before saving(in form valid ). https://github.com/go-gitea/gitea/blob/dd81c290529eb5692b46553b2fac120820872a1c/services/forms/org.go#L54 There won't be too long a string here, and this code is redundant (#15838)

**Comment by 6543** [comment]
@palytoxin please "update" this pull or allow maintainer to do so :)

**Comment by palytoxin** [comment]
@6543 Please check it ;D

**Comment by lunny** [comment]
@palytoxin Please send backport to v1.14

**Comment by zeripath** [comment]
I've sent the backport for you @palytoxin . If you would rather have the PR under your name please feel free to send another backport PR and we can close the one I've opened.

**Comment by palytoxin** [comment]
@zeripath  It's all right.
image

**Pull request merged**
