### PR TITLE
Fix ref parsing in commit messages

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fix bug where commit messages containing `/#` would cause an error, and the rest of the commit message would not be parsed for issue references. This is because `GetIndexByRef` would return `ErrInvalidReference` when it encountered `/#`.

This PR also
* Improves the regexps for issue refs to avoid superfluous matches (`issueReferenceKeywordsPat` previously matched every word!)
* Refactor common code so that it can be reused
* Adds unit tests for commit message parsing

### CODE REVIEW

**Comment by lafriks** [comment]
Tests seems to be failing

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
