### PR TITLE
Add ui.explore settings to control view of explore pages

### LINKED ISSUE #2908: Hide users from public view
- Gitea version (or commit ref): 1.2.3
- Git version: 2.15
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I think there should exist a config option to prevent the viewing of user accounts from public view. I have user accounts on my Gitea instance that I would not like others to see. This might be doable with templates but I am not sure at the moment.

### PR DESCRIPTION
**Pull request by zeripath**
Add `[ui.explore]` settings to allow restricting the
explore pages to logged in users only and to restrict
the showing of users to only those with publically available
repositories.

The two proposed settings are:

- `REQUIRE_SIGNIN_VIEW`: Only allows access to the explore pages if the
user is signed in. Also restricts
  - `/api/v1/user/search`
  - `/api/v1/users/{username}`
  - `/api/v1/users/{username}/repos`
  - but does not restrict `/api/v1/users/{username}/heatmap`
- `ONLY_SHOW_USERS_WITH_PUBLIC_REPOS`: Only shows users with public
repos on the explore page. `/api/v1/user/search` will only show users
with public repos unless the user the is signed in.

Fix #2908

Close #14094

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by lafriks** [comment]
Imho we don't need special app.ini settings for this. My proposal would be:
* Remove users explore page completely
* Limit API call to users list to require authorization

**Comment by zeripath** [comment]
I think there's still likely to be a point for findability for public repositories and users with public repos.

**Comment by zeripath** [comment]
I would guess however that we should default to only showing users with public repositories

**Comment by lafriks** [comment]
There is not much point in listing users with public repositories, it will be resource intensive imho and usually everyone are still using repository listing

**Comment by lunny** [comment]
Please resolve the conflicts

**Comment by zeripath** [comment]
Conflicts fixed

**Comment by zeripath** [comment]
conflicts fixed again

**Pull request closed without merging**
