### PR TITLE
Fix bug isEnd detection on getIssues/getPullRequests

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
I don't understand why this fixes anything but it looks fine

**Comment by lunny** [comment]
> I don't understand why this fixes anything but it looks fine

Sorry I haven't explain this bug. 

When the parameter `getIssues(page, perPage int)` perPage > maxPerPage, it will return `isEnd` as true always on first page. So that you can always only get only 1 page. that means 100 issues.

If a repository has over 100 issues, only 100 issues will be migrated.

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
please backport :)

**Comment by 6543** [comment]
@lunny sorry I did missed that somehow :/

**Pull request merged**
