### PR TITLE
Fix container layer display overflow

### PR DESCRIPTION
**Pull request by lafriks**
Before:
attels

After:
attels

### CODE REVIEW

**Comment by silverwind** [comment]
Better to add a [overflow-x-auto](https://tailwindcss.com/docs/overflow) helper, but I think it should probably just wrap.

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Try with the existing [word-break helper](https://github.com/go-gitea/gitea/blob/3affb02df517e9081593473137fc287ad51057b7/web_src/less/helpers.less#L32-L36) instead.

**Comment by lafriks** [comment]
@silverwind done

**Review by delvh — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Is this the universal version of #21251?

**Comment by silverwind** [comment]
The helper should be pretty universal, but tables may need special care as many CSS properties that work everywhere else do not work on tables.

**Pull request merged**
