### PR TITLE
Fix avatar radius problem on the new issue page

### LINKED ISSUE #31502: Avatars are squared when opening new issue
### Description

image

when editing issue - avatars are ok, but "check" is not centered
image

### Gitea Version

1.23.0+dev-278-gb5326a431f

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by charles7668**
Close #31502

Related to #31419.

In this PR, the avatar width is set to 3em, but the height is not set, so the image is not squared.

When object-fit is set to contain, it can't maintain the radius of the image.

Result:
圖片

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by yp05327 — APPROVED** [review]

**Comment by yp05327** [comment]
Wait it looks strange in my local:
before (main branch)
image
after(too big):
image

**Comment by yp05327** [comment]
So my suggestion is 
image

**Comment by silverwind** [comment]
Ideally we should size avatars correctly inside the templates only and remove all the CSS that alters their size, it's unnecessary.

**Comment by charles7668** [comment]
> So my suggestion is image
> 
> After: image

This seems to be a better solution.

I have been updated.

**Comment by yp05327** [comment]
> Ideally we should size avatars correctly inside the templates only and remove all the CSS that alters their size, it's unnecessary.

@silverwind 
I agree, how do you think about this PR, close it or merged it first as a quick fix and do that later.

**Comment by silverwind** [comment]
Fix is fine to take as a quick fix. Ultimately it was a regression from https://github.com/go-gitea/gitea/pull/31419.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
