### PR TITLE
Backport: Fix lint, fmt and integration testing errors

### PR DESCRIPTION
**Pull request by ethantkoenig**
Backport of #2547.

### CODE REVIEW

**Comment by ethantkoenig** [comment]
:cry:
```
We require go version 1.7 or 1.8 to format code
make: *** [Makefile:60: required-gofmt-version] Error 1
```

**Comment by tboerger** [comment]
```
# docker run --rm webhippie/golang:edge go version
go version go1.9 linux/amd64
```

**Comment by lafriks** [comment]
Depends on #2561

**Comment by sapk** [comment]
LGTM

**Comment by daviian** [comment]
LGTM

**Comment by lafriks** [comment]
@ethantkoenig cherry-pick other PR commit here

**Comment by lafriks** [comment]
~~@ethantkoenig `git cherry-pick a1ed239bf277b0f17694e2e5685368d373e010c7` to your branch. I tried but had no rights to push to your repository :)~~

EDIT: need to use ssh to be able to push to your repo

**Comment by lafriks** [comment]
Backport also Hotfix for integration testing (#2473)

**Comment by ethantkoenig** [comment]
@lafriks Rebased on `release/v1.2`, with fmt fixes

**Comment by lafriks** [comment]
@ethantkoenig `git cherry-pick fd85e25f5f48823c4e65f3bd23662fd26d1398b3` otherwise integration tests will fail

**Comment by lafriks** [comment]
@ethantkoenig I also added backport/cherry-pick for integration test fixes

**Pull request merged**
