### PR TITLE
Adjust Fork API to allow setting a custom repository name

### LINKED ISSUE #6442: Extend fork API to support custom repo name and owner
- Gitea Version: 1.6.4
- Git Version: 2.15.3
- Operating System: Alpine Linux 3.7.1

The current fork API (implemented in routers/api/v1/repo/fork.go) support forking a repo with two restrictions:
1. The forked repo name remains the same as the source repo name
2. The forked repo is owned by the API caller

My suggestion is to support a custom repo name for the forked repo, and to allow an admin user to create forks for other users.

Do you think such an extension is reasonable? Should I send a PR for this?

### PR DESCRIPTION
**Pull request by realaravinth**
> closes #6442 

## Changes
- name: new parameter in `CreateForkOption` to give the forked repository a custom name, intended to be used when there's a name conflict
- When a fork request results in a name conflict, HTTP 409: Conflict is
  returned instead of 500
- API documentation for the above mentioned changes

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by jpraet** [comment]
If we support it via the API, we should also support it via the web UI?

**Comment by realaravinth** [comment]
It's already supported by the web UI. [The web form accepts a name and a description paramanter](https://github.com/go-gitea/gitea/blob/ba6efb105abd2a64b53491952a96a0a7af4b5ab9/routers/web/repo/pull.go#L234) while forking through the webpage.

**Comment by jpraet** [comment]
> It's already supported by the web UI. [The web form accepts a name and a description paramanter](https://github.com/go-gitea/gitea/blob/ba6efb105abd2a64b53491952a96a0a7af4b5ab9/routers/web/repo/pull.go#L234) while forking through the webpage.

Ah, indeed. However, when I tried that out yesterday it didn't seem to work properly for me. You can indeed choose a different repository name the first time you fork the repo. But hen you then want to fork it again under the same account with a different name, the UI does not allow it. The "Owner" dropdown list doesn't show the accounts that have already forked the repo.

Or is that by design? I'm not sure. In any case it should not block this PR, sorry.

**Review by jpraet — APPROVED** [review]

**Comment by realaravinth** [comment]
> But hen you then want to fork it again under the same account with a different name, the UI does not allow it. The "Owner" dropdown list doesn't show the accounts that have already forked the repo.

If I understand you correctly, you are trying to force the same repository twice, right? That doesn't work, even with the changes introduced by this PR. A namespace(user, org, etc.) can fork a repository only once. 

This PR simply provides an option to choose a custom name for the forked repo, so that name clashes can be avoided.

**Review by noerw — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
