### PR TITLE
Draft: implement mirroring for issues and pull requests

### PR DESCRIPTION
**Pull request by silentcodeg**

### CODE REVIEW

**Comment by harryzcy** [comment]
I just noticed this pull request is the same as my work at #20311. Only one PR between this one and #20311 will be merged eventually.

How are you planning to going forward with this? I don't want the duplicated work going in parallel, so I think it's better to discuss now and sort out the approach.

**Comment by silentcodeg** [comment]
> How are you planning to going forward with this? 

Yes.

This is a difficult problem to solve. It is easy to hack and test manually but there will be recurring undetected regressions so frequently that it will not be widely usable (check the latest commits related to dump-repo/restore-repo for instance) and very difficult to maintain. The challenge is to build a sound codebase that is thoroughly tested and properly architectured.

I believe the [Friendly Forge Format](https://lab.forgefriends.org/friendlyforgeformat) (F3) is a good way to approach this, reason why I'm motivated to make it work for Gitea. F3 is a new project but is actively developed.

If you'd like to discuss it further, there is a [forum](https://forum.forgefriends.org/c/friendly-forge-format/38) and a [chatroom](https://matrix.to/#/#general-forgefed:matrix.batsense.net).

**Comment by harryzcy** [comment]
Given that 'F3 Go' uses AGPL license, it can't be imported by Gitea directly right? Gitea can only use the file format specification and implement them internally.

**Comment by Gusted** [comment]
Per usual, I'm not a lawyer.

> Given that 'F3 Go' uses AGPL license, it can't be imported by Gitea directly right?

Well, slight correction it can be imported by Gitea. But according to the GPL terms(given this is derivative work on AGPL as otherwise the program won't function), Gitea must (and only can be) licensed under AGPL license, which isn't the case. 

Currently(according to [go-license](https://github.com/google/go-licenses)) Gitea only imports MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, MPL-2.0, ISC. So I was initially going to say "Oh Gitea likely already uses a GPL-alike license, so it should be fine", however this isn't the case and doing some searches does explicitly imply that there is no exception to be able to use the library and not distribute Gitea under GPL. So it seems to be that Gitea cannot use the F3 Go library.

**Comment by Gusted** [comment]
I've asked [Loïc Dachary](https://lab.forgefriends.org/dachary), the main contributor of F3 Go in the [Forge Federation general](https://matrix.to/#/!SakSkZqjzMsaPCVqlv:matrix.batsense.net/$bsuhl5rtdzzDHbLUq2eTM2-w4bcW6F9ZHjiojauzcDQ?via=matrix.org&via=t2bot.io&via=matrix.batsense.net) matrix room about the license. I quote:

```
I will change the license to be compatible with the Gitea license
when and if the pull request is accepted. That won't be a blocker.
```

So it's fine to use the F3 Go library.

**Comment by silentcodeg** [comment]
@harryzcy a short note to let you know I'm still motivated to move forward with this pull request. I'm following the progress of the [F3](https://lab.forgefriends.org/friendlyforgeformat/gof3/) and will update the PR once it is more stable than it currently is. There is daily work done [here](https://lab.forgefriends.org/friendlyforgeformat/gof3/-/merge_requests/6/commits) and it looks promising.

**Comment by earl-warren** [comment]
Unless there is an objection I'm willing to work on landing this pull request. With a different approach which is more likely to be accepted, by proposing an optional new feature instead of a large replacement of the existing codebase.

**Comment by silentcodeg** [comment]
@earl-warren there is no easy way to hand over this pull request so I'll just close it so another one can be opened. That makes sense.

**Pull request closed without merging**
