### PR TITLE
Fix Safari spinner rendering

### LINKED ISSUE #29041: Circular loading spinner is an oval on mobile
### Description

When doing any operation that starts a loading spinner on mobile. It is always an oblong shape instead of a perfect circle. Most notably I see this when loading the user dashboard, logging in with passkey, or in any loading spinner. 

### Screenshots

IMG_0226

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

iOS 17.3

### Browser Version

AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Mobile/15E148 Safari/604.1

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/29041
Fixes: https://github.com/go-gitea/gitea/pull/29713

Any of the `width: *-content` properties seem to workaround this Webkit bug, this one seemed most suitable.

Before:
Screenshot 2024-03-14 at 22 29 58

After:
Screenshot 2024-03-14 at 22 30 30

### CODE REVIEW

**Review by denyskon — APPROVED** [review]
This change is straight-forward, but I have no ability to test on Safari, trusting you that it fixes the issue😆

**Comment by silverwind** [comment]
Tested in Safari 17.4 😉

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
Not sure if 1.20 will see more releases, but this should be a clean merge 😆

**Comment by silverwind** [comment]
Ah, I think I may have confused the bot. Well, I assume 1.20 isn't going to get any more releases.

**Pull request merged**
