### PR TITLE
Remove User.GetOrganizations()

### PR DESCRIPTION
**Pull request by 6543**
followup of #13994

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by zeripath — DISMISSED** [review]
I can't point to a definite place where this will be wrong but I am certain that this will get the NumRepos incorrect in cases where a user cannot see all of the repositories of an organisation.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/blob/8af9df00360a812d31281179f4c6e095959e487e/models/org.go#L390-L408

does not account for the num repos that are accessible to the user.

https://github.com/go-gitea/gitea/blob/8af9df00360a812d31281179f4c6e095959e487e/models/user.go#L557-L587

Checks how many repositories are accessible to the user along with the organizations. An organization should only be shown if there is a repository accessible to the user as far as I can see.

**Comment by 6543** [comment]
hmm we should fix getOrgsByUserID then ...

**Comment by lunny** [comment]
Is this ready to review?

**Comment by 6543** [comment]
@lunny sadly no: `...getOrgsByUserID() does not account for the num repos that are accessible to the user...`

**Comment by 6543** [comment]
@techknowlogick since latest refactors we can savely remove it cc @zeripath

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
