### PR TITLE
Fix version-validation for GO 1.13 (go-macaron/cors)

### PR DESCRIPTION
**Pull request by 6543**
https://tip.golang.org/doc/go1.13#version-validation

will solve https://github.com/go-gitea/gitea/issues/8387

### CODE REVIEW

**Comment by techknowlogick** [comment]
Note for maintainers reviewing: This has been solved for gitea 1.10, however as we changed the upstream dependency we couldn't backport. This will allow 1.9.4 to be built with golang 1.13

**Comment by techknowlogick** [comment]
@6543 please update vendor/modules.txt as well

**Comment by techknowlogick** [comment]
nvm. I was looking at an old CI build

**Comment by 6543** [comment]
build was succesfull!! 
just runn the rest of the CI ...

**Comment by 6543** [comment]
@techknowlogick works :dagger:

**Review by techknowlogick — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Comment by 6543** [comment]
CI done

**Comment by 6543** [comment]
now we can build 1.9.x with new fixes ...

**Pull request merged**
