### PR TITLE
Hide Local Login UI

### PR DESCRIPTION
**Pull request by kimbj95**
related issue https://github.com/go-gitea/gitea/issues/13606#issuecomment-1013798933

### CODE REVIEW

**Comment by kimbj95** [comment]
related issue https://github.com/go-gitea/gitea/issues/13606

**Review by zeripath — CHANGES_REQUESTED** [review]
Hiding the login without actually disabling it is tantamount to a security hole.

This PR should disable the local DB login completely

**Comment by kimbj95** [comment]
@zeripath I found out that setting the `ProhibitLogin = true` can block the local login, and confirmed that the setting can be done using apis. In this case, wouldn't it be enough to hide local login UI? 

https://github.com/go-gitea/gitea/blob/c174bdc494e44ac6b52373e86b7a3ac225091a80/models/user/user.go#L126

**Comment by TwoTwenty** [comment]
> This PR should disable the local DB login completely

Only if your server admin leaves local accounts with bad passwords
For me I want 1 break glass local admin account and in general all my users using a openidconnect login.

**Pull request closed without merging**
