### PR TITLE
Upgrade golang.org/x/crypto

### LINKED ISSUE #17798: RSA public keys cannot authenticate against internal SSH if the client has a recent ssh version (which disables ssh-rsa algorithm)
### Gitea Version

1.15.x/1.16.x till the latest

### Operating System

- Any SSH client with ssh-rsa algorithm disabled (ex: OpenSSH >= 8.8)

### How are you running Gitea?

Builtin/Internal SSH (ex: docker-rootless or START_SSH_SERVER=true in app.ini)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The `ssh-rsa` key signing algorithm is disabled on recent ssh versions. Although #17281 means that Gitea will offer `rsa-sha2-256` and `rsa-sha2-512` for the host key verification - it does not fix the issue of advertising and handling the public key signing algorithm. 

This failure then results in ssh authentication failing.

## How to reproduce

Use a newer version of SSH where this is disabled and attempt to authenticate using an RSA key.

On older versions of SSH:

```
ssh -o PubkeyAcceptedKeyTypes=-ssh-rsa,+rsa-sha2-256 ...
```

Unfortunately OpenSSH have changed the name of this option across versions and in newer versions, including the affected version, this option is called: `PubkeyAcceptedAlgorithms`

So if the above fails with an error try:

```
ssh -o PubkeyAcceptedAlgorithms=-ssh-rsa ...
```

## Workaround

* On affected clients, add `-o PubkeyAcceptedAlgorithms=+ssh-rsa` to the ssh command line (In the unlikely event you have an older version which has deliberately disabled the ssh-rsa algorithm you will need to add 
`-o PubkeyAcceptedKeyTypes=+ssh-rsa`)
* Use other supported SSH key formats
* Use OpenSSH server instead of builtin SSH server (ex: use Docker instead of Docker-rootless)

## History of this issue

For speed I'm going to collect things here:

* #17175 reported that there was a key negotiation failure with newer versions of SSH and Gitea.
* Through investigation this was revealed to be a HostKey algorithm failure due to the key type being used to determine the signing algorithms available for the key. 
* Fortunately the HostSigners are exposed on the underlying ssh server so although there is a fundamental flaw in the way signers (their type is not reportable separate from the key) #17281 was able to work around this by wrapping those keys around something to pretend to be signers.
* This then fixes the hostkey issue - however, I was unaware of the next issue...
* @andypost then commented on https://github.com/go-gitea/gitea/issues/9691#issuecomment-955776326 (Which is unfortunately an unrelated feature request issue relating to HTTPS not SSH.)
* My comment here https://github.com/go-gitea/gitea/issues/9691#issuecomment-956753681 describes that the issue is actually relating to the next step of authentication - the pubkeyalgorithm 
* I then discovered that the problem is relating to the pubkey signing algorithms offered to the client https://github.com/go-gitea/gitea/issues/9691#issuecomment-962434683
* There is an upstream issue: https://github.com/golang/go/issues/49269 relating to supporting the required extension.
* And there is a PR here: https://github.com/golang/crypto/pull/197 that implements this but I'm not completely convinced its totally correct.
* In the meantime go have merged: https://github.com/golang/crypto/commit/b4de73f9ece8163b492578e101e4ef8923ac2c5c
* This does a similar bodge to the one I did in #17281, however, whereas #17281 leaves the possibility of disabling certain host key signing algorithms in the future, if we support ssh-rsa we have to support rsa-sha2-256 and rsa-sha2-512, and no way is provided to support only  rsa-sha2-256 and rsa-sha2-512. (The above commit does provide certificate support which is something that #17281 missed.)
* Now alpine linux are having to build gitea with a patch that adds the above workaround to fix issues with testing and #17786 proposes upstreaming that patch - but our testing version of OpenSSH is not affected by this problem as it is too old and this PR fails because it uses the new option which our version does not (!).

## What is actually needed

The fundamental issue is not resolvable within Gitea without forking and otherwise reimplementing the ssh server. We will need to address this problem upstream.

There are two major structural issues:

* Signers need to be separately configurable and advertisable apart from the key types that they sign. The commit mentioned above may have degraded the ability of users of the upstream ssh package to disable the `ssh-rsa` signing algorithm in future and this needs to be addressed.
* The Handshake needs to support extension negotiation https://datatracker.ietf.org/doc/html/rfc8308 and in particular the SSH_MSG_EXT_INFO extension described therein.

### PR DESCRIPTION
**Pull request by Gusted**
- Update the crypto dependency to include https://github.com/golang/crypto/commit/6fad3dfc18918c2ac9c112e46b32473bd2e5e2f9
- Resolves #17798

Executed: `go get golang.org/x/crypto@6fad3dfc18918c2ac9c112e46b32473bd2e5e2f9 && rm go.sum && go mod tidy`

### CODE REVIEW

**Comment by Gusted** [comment]
Should this be backported?

**Comment by zeripath** [comment]
Yes please backport

**Review by zeripath — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by Gusted** [comment]
https://github.com/go-gitea/gitea/pull/21793 & https://github.com/go-gitea/gitea/pull/21794

**Comment by zeripath** [comment]
I'm fairly sure that there was a test that @6543 wrote in a pr that would demonstrate that this solves the problem.

**Comment by 6543** [comment]
uh that problem :sweat_smile: ... let me add this pull to my todo list for now :D

**Review by delvh — APPROVED** [review]
:relieved:

**Comment by delvh** [comment]
Wait, is the CI fail related?
It looks similar, but I think it is not related.

**Comment by Gusted** [comment]
Doesn't seem to be, hidden in the logs we can see that the token is empty for some reason, just a coincidence that it's related to some cryptographic part of Gitea. I will push an empty commit to hopefully resolve the flaky test.
image

**Comment by jolheiser** [comment]
:trumpet: :robot:

**Pull request merged**
