### PR TITLE
Fix password checks on admin create/edit user

### PR DESCRIPTION
**Pull request by guillep2k**
This PR fixes password requirement checks for the admin's new/edit user pages.

To my surprise, normal users are not created with `LoginType` = `LoginPlain` but `LoginNoType`. I don't know the reason for that, but all my local users are created that way. I went on to fixing the check on the admin's new user page (which wasn't triggering because of this) and I've found that password length was not being checked either.

So, this PR adds/fixes the missing checks. However, if the intention is that the admin does no need to abide password requirements, a different PR is required to remove the (currently inactive?) code.

Maybe we should consider creating local users with `LoginType` = `LoginPlain`:

```
const (
	LoginNoType LoginType = iota
	LoginPlain            // 1
	LoginLDAP             // 2
	LoginSMTP             // 3
	LoginPAM              // 4
	LoginDLDAP            // 5
	LoginOAuth2           // 6
)
```

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by jolheiser** [comment]
Should this also show password requirements like #9074 ?

**Comment by guillep2k** [comment]
> Should this also show password requirements like #9074 ?

@jolheiser Not until it's merged, I guess

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
#9074 is merged now...

**Comment by guillep2k** [comment]
Let me fix the conflicts.

**Comment by guillep2k** [comment]
> 
> 
> Let me fix the conflicts.

Done. I've also removed an invalid TrimSpace() I had copied from the original validation, in case you guys want to check (it's the second commit).

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
