### PR TITLE
Fix index produces problem when issues/pulls deleted

### PR DESCRIPTION
**Pull request by lunny**
When an issue of a repo has been deleted( we haven't implement that on gitea currently) or the number counting failed on repository, creating issue/pull will always failed. This PR will fix that problem and when both two issue are created then retry will resolve the problem. This is not the final resolution, but it will not block user creating issue.

### CODE REVIEW

**Review by BetaCat0 — APPROVED** [review]

**Comment by lafriks** [comment]
Does xorm support to use expressions on inserts? Most correct solution would be to use `insert into .... values (xxx, xxx, (select max(col)+1 from ...), xxx)` sql statement to have less possibility for race condition

**Comment by lunny** [comment]
@lafriks xorm support that but mysql and maybe other databases don't support.

**Comment by zeripath** [comment]
Hmm we're going to have problems with this if we have a very active repository. 

This is a lot better than our current implementation.

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
Make L-G-T-M work

**Comment by lafriks** [comment]
MySQL, postgres and mssql support that, don't know about sqlite tho, need to test that :)

**Comment by lunny** [comment]
It should be, see http://www.sqlitetutorial.net/sqlite-functions/sqlite-coalesce/ `coalesce` is a SQL92 standard I think.

**Pull request merged**
