### PR TITLE
Failed authentications are logged to level Error (#31968)

### PR DESCRIPTION
**Pull request by itzonban**
PR for issue #31968.

Failed authentications are now logged to level Error instead of Info.

### CODE REVIEW

**Comment by delvh** [comment]
But… it isn't an error.
I somewhat agree with increasing the level to `Warning`, but no higher than that.
I'm even torn if we shouldn't leave it as `Info` since especially on public instances your logs will get spammed with unnecessary logs you cannot change.

**Comment by itzonban** [comment]
> But… it isn't an error. I somewhat agree with increasing the level to `Warning`, but no higher than that. I'm even torn if we shouldn't leave it as `Info` since especially on public instances your logs will get spammed with unnecessary logs you cannot change.

I don't know how useful it is to argue about semantics in this case... I can see your point, that a failed login could just be an `Info` but on the other hand it is a failed login process in a code block which deals explicitly with errors.

If you can live with raising it to `Warning` that would be also fine for me... my issue is, that on our productive system the log has a lot of unnecessary Info logs I don't need BUT I need to see the failed logins for fail2ban, therefore I would like to be able to raise the log level.

**Comment by lunny** [comment]
I agree those are not errors. `Errors` should be a system problem, but when inputting the wrong password, the system is right but the man inputting the password may made a mistaken. Or it's an attack. But whatever which one it is, it's not an error.

**Comment by itzonban** [comment]
> I agree those are not errors. `Errors` should be a system problem, but when inputting the wrong password, the system is right but the man inputting the password may made a mistaken. Or it's an attack. But whatever which one it is, it's not an error.

How about the the alternative setting it to `Warning`?

**Pull request closed without merging**
