### PR TITLE
Some optimizations for uploading to minio

### LINKED ISSUE #15253: git LFS and storage type minio: Massive memory usage
- Gitea version (or commit ref): 1.14.0-rc2
- Git version: 2.30.2
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Log gist (heap, allocs, gitea.log): 
[Logs.zip](https://github.com/go-gitea/gitea/files/6248792/Logs.zip)

## Description
This is a follow up issue from the discord general channel. 
Running git lfs push with very small LFS files (330kb in size total) and storage type minio causes a massive use of memory of gitea (around 2.2 GB). Pushing another round of small files quickly exceeds 5GB.

I’ve attached a zip containing a docker compose and test data so that you can reproduce the issue easily.
[docker.zip](https://github.com/go-gitea/gitea/files/6248812/docker.zip)

Reproduction steps:
1. Extract docker.zip
2. Adjust IP address for server.root_url and storage.minio.minio_endpoint in config/app.ini
3. Run: docker-compose -f docker-compose.yml up -d
4. Go to localhost and setup gitea
5. Create a new repo + initialize
6. Run: git clone 
7. Cd into cloned repo
8. Run: git lfs install
9. Run: git lfs track *.png
10. Copy provided PNG images to repository
11. Run: git add .
12. Run: git lfs status     - and verify that LFS files are tracked correctly
13. Run: git commit and push
14. Observe gitea memory usage spikes from 180 mb to around 2.2 GB

### PR DESCRIPTION
**Pull request by lunny**
A fixed size to minio upload sdk may spend less memory than give it a `-1`. So let's give the size when possible.

close  #15253

### CODE REVIEW

**Comment by J0Nes90** [comment]
I can confirm that this PR fixes https://github.com/go-gitea/gitea/issues/15253

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
I see a number of architectural issues with this approach. 

I can understand why an argument polymorphism approach has been chosen instead of an explicit argument approach here and whilst I'm not genuinely not sure it's the right thing - I think it's probably OK.  

But I absolutely do not think that the `ReadSizer` interface should be outside of modules/storage - (whether the `WithSize` constructor function should be is another question.) 

The `ReadSizer` interface should be within `modules/storage` and the documentation for the `storage.Save` function should refer to it explaining that if  an `io.Reader` is passed that matches the interface `storage.ReadSizer` then the `Size` reported from that will be used.

Thus it's documented in one place and self contained. See https://github.com/golang/go/wiki/CodeReviewComments#interfaces


In terms of the `WithSize` constructor function - its name is not ideal - `ReaderWithSize(...)` would be better unless that function is going to end up in a reader specific module, e.g. : `modules/ioutil/reader`. (In which case the the `git.LimitedReadCloser` from `modules/git/util.go` should get moved there with a constructor `WithLimitCloser(...)`

But further everything that is using a `ReadSizer` has a direct dependency on storage anyway so you're just adding another module for no great reason. If we genuinely want to use this in places where there isn't a direct dependency on storage later on then we can move the `ReaderWithSize(...)` function into another module and lightly bind its interface dependence on storage through a test within `modules/storage` that uses it.

**Comment by zeripath** [comment]
Actually this is argument polymorphism really not going to work at all...

Consider what happens if you pass a bufio.Reader into Save.

**Comment by lunny** [comment]
> Actually this argument polymorphism is really going to be confusing:
> 
> Consider what happens if you pass a bufio.Reader into Save... to a cursory glance it looks like it implements ReadSizer but it doesn't - thankfully as its Size function means a very different thing.
> 
> We really should be implementing and using the io/fs interfaces but in the meantime just add a size argument to Save

Please send a PR to replace this one.

**Pull request closed without merging**
