### PR TITLE
Fix spelling in API docs of adminDeleteHook

### PR DESCRIPTION
**Pull request by bilogic**
spelling fix

### CODE REVIEW

**Comment by techknowlogick** [comment]
thanks for this PR! The CI is failing due to the attached documentation being out of alignment with the code comment, could you run 'make generate-swagger' and commit the result?

**Comment by bilogic** [comment]
saw your message after my 2nd commit, let me try `make generate-swagger`, coz all I did was modify the spelling on github.com itself

**Comment by silverwind** [comment]
Updated the title. You should put descriptive PR titles in the future. And also please don't raise pull requests from your `main` branch. Create topic branches for each PR.

**Comment by wxiaoguang** [comment]
@bilogic The CI lint still fails. I guess it really needs to run `make generate-swagger` to re-generate the swagger JSON.

**Comment by silverwind** [comment]
Tried to fix this branch but did not work out for some reason, I assume it was because source branch was `main` and github has special rules around that branch. One should never open a PR from `main`.

I opened https://github.com/go-gitea/gitea/pull/24310 which contains the commits and the regenration.

**Pull request closed without merging**
