### PR TITLE
WIP: Steam Oauth2 support

### LINKED ISSUE #9094: Steam Oauth2 support
Read the title!

### PR DESCRIPTION
**Pull request by M4RKUS-11111**
Close: #9094

### CODE REVIEW

**Comment by silverwind** [comment]
Logo is quite big and I suggest SVG instead:

````svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 233 233"><defs><linearGradient id="a" x1="50%" x2="50%" y2="100%"><stop offset="0" stop-color="#111D2E"/><stop offset=".21" stop-color="#051839"/><stop offset=".41" stop-color="#0A1B48"/><stop offset=".58" stop-color="#132E62"/><stop offset=".74" stop-color="#144B7E"/><stop offset=".87" stop-color="#136497"/><stop offset="1" stop-color="#1387B8"/></linearGradient></defs><path fill="url(#a)" d="M4.9 150.01C19.27 198.02 63.8 233 116.5 233c64.34 0 116.5-52.16 116.5-116.5S180.84 0 116.5 0C54.76 0 4.24 48.03.25 108.76c7.54 12.66 10.48 20.49 4.64 41.25z"/><path fill="#fff" d="M110.5 87.32l.01.58-28.5 41.41c-4.63-.21-9.26.6-13.65 2.41a31.7 31.7 0 00-5.46 2.88L.3 108.83s-1.45 23.83 4.59 41.59l44.25 18.26a32.28 32.28 0 0061.33 5.42 32.45 32.45 0 002.49-13.31l40.79-29.15 1 .02a44.33 44.33 0 000-88.66 44.34 44.34 0 00-44.25 44.32zm-6.84 83.92a24.94 24.94 0 01-32.6 13.45 24.78 24.78 0 01-12.83-12.24l14.4 5.97a18.38 18.38 0 0014.11-33.93l-14.88-6.17a24.77 24.77 0 0118.38.28c6.16 2.56 10.93 7.38 13.46 13.54s2.52 12.96-.04 19.1m51.09-54.38a29.55 29.55 0 010-59.07 29.55 29.55 0 0129.49 29.53 29.55 29.55 0 01-29.49 29.54m-22.09-29.58c0-12.26 9.92-22.2 22.14-22.2a22.17 22.17 0 0122.15 22.2 22.17 22.17 0 01-22.15 22.18 22.16 22.16 0 01-22.14-22.18z"/></svg>
````

**Review by techknowlogick — COMMENTED** [review]
Please update templates as well. You can refer to https://github.com/go-gitea/gitea/pull/13293/files for an example of what you need to do (add an entry with help text for linking to how to create Steam Oauth key/secret)

**Comment by techknowlogick** [comment]
Seems you need to create support ticket and ask Steam for OAuth2 information: https://partner.steamgames.com/doc/webapi_overview/oauth#Getting+Started

**Comment by BytewaveMLP** [comment]
@techknowlogick That's for Steamworks OAuth, but I believe Steam still acts as an OpenID provider for authentication purposes. See https://steamcommunity.com/dev .

**Pull request closed without merging**
