### PR TITLE
Allow enable LDAP source and disable user sync via CLI

### PR DESCRIPTION
**Pull request by justusbunsi**
The current `admin auth` CLI for managing authentication source of type
LDAP via BindDN and Simple LDAP does not allow enabling the respective
source, once disabled via `--not-active`.
The same applies to `--synchronize-users` specifially for LDAP via
BindDN.

These changes add two new flags to LDAP related CLI commands:

- `--active` for both LDAP authentication source types
- `--disable-synchronize-users` for LDAP via BindDN

Signed-off-by: justusbunsi <61625851+justusbunsi@users.noreply.github.com>

### CODE REVIEW

**Comment by zeripath** [comment]
Whilst you might think that `--not-active` implies that you cannot set things to active you'd probably find that `--not-active=false` would activate it. 

I'm guessing that we should really be making pairs for all of our boolFlags...

**Comment by zeripath** [comment]
hmm... could we actually create something that would make pairs like this?It should be possible to create a function that returns two bool flags that are opposites of each other perhaps using the destination.

**Review by zeripath — APPROVED** [review]

**Comment by justusbunsi** [comment]
> Whilst you might think that `--not-active` implies that you cannot set things to active you'd probably find that `--not-active=false` would activate it. 
> 
> I'm guessing that we should really be making pairs for all of our boolFlags...

😳 I tried it with `--not-active false` which didn't work. Tested it now and well, as you suggested: It works with =.

**Comment by justusbunsi** [comment]
TBH, my changes are not necessary. The issue is the printed help for the command line, IMO. It does not indicate that you can toggle it and does not provide an example of doing so. If that would be clear, I wouldn't had created the PR.

**Comment by justusbunsi** [comment]
Maybe it would be enough to extend the help for the boolean flags in general to tell users how they can toggle those flags. I personally am not used to the `--flag=<boolean>` notation, so I haven't even thought of it.

**Review by Gusted — APPROVED** [review]
If you want to minimalise this PR you probably want to make a breaking change and change the `not-active` -> `set-active`. Current changes looks good.

**Comment by justusbunsi** [comment]
> If you want to minimalise this PR you probably want to make a breaking change and change the `not-active` -> `set-active`. Current changes looks good. 

I don't want to make a breaking change out of this, if avoidable. 😉 Seems like everyone is ok with the current implementation. So I am fine with it, too.

**Comment by 6543** [comment]
.

**Pull request merged**
