### PR TITLE
Migrate ActivityHeatmap to Vue SFC

### PR DESCRIPTION
**Pull request by gary-kim**
Follow up to #10188

Migrate ActivityHeatmap to use Vue SFC and compile at build time.

Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

**Comment by 6543** [comment]
@gary-kim eatmap works just fine but "dashboard-repos" are gone ?!?

**Comment by 6543** [comment]
> @gary-kim heatmap works just fine but "dashboard-repos" are gone ?!?

Dont remove alias in `webpack.config.js` and it works all fine

**Comment by gary-kim** [comment]
> Dont remove alias in `webpack.config.js` and it works all fine

Okay then. Added it back in here. At some point, I'll go through to see what's left using compile on the browser and migrate them.

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work.

**Pull request merged**
