### PR TITLE
Handle expected errors in AddGPGkey API 

### PR DESCRIPTION
**Pull request by 6543**
as title

### CODE REVIEW

**Comment by 6543** [comment]
needed for #11641

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I don't think this is breaking. This might sound a bit harsh but we never said that 500 was a valid result - so although people might have been using it - it does not form an advertised API.

TBH If they had been using the 500 they should have reported it as a bug.

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
ready to merge

**Comment by techknowlogick** [comment]
@6543 please backport :)

**Comment by 6543** [comment]
@techknowlogick #11661

**Pull request merged**
