### PR TITLE
Restore compatibility with SQLServer 2008 R2 in migrations

### LINKED ISSUE #13615: MSSQL, Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
- Gitea version (or commit ref): 1.12.6 (same error on 1.13.0-rc2)
- Git version: 2.15.1
- Operating system: Microsoft Server 2012 R2
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL v2017
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I am trying to install gitea 1.12.6 on SQL Server 2017. I have database and user using the following query:
```
CREATE DATABASE giteadb
ALTER DATABASE giteadb COLLATE SQL_Latin1_General_CP1_CS_AS

USE master
CREATE LOGIN giteauser WITH PASSWORD=N'giteapass', DEFAULT_DATABASE=giteadb, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
ALTER AUTHORIZATION ON DATABASE::giteadb TO giteauser
```
When I click 'Install Gitea' from localhost:3000, a bunch of tables are generated in the database but then I get the below error.

...

## Log
```
2020/11/18 09:31:03 ...dules/setting/log.go:279:newLogService() [I] Gitea Log Mode: File(File:info)
2020/11/18 09:31:03 ...les/setting/cache.go:70:newCacheService() [I] Cache Service Enabled
2020/11/18 09:31:03 ...les/setting/cache.go:81:newCacheService() [I] Last Commit Cache Service Enabled
2020/11/18 09:31:03 ...s/setting/session.go:63:newSessionService() [I] Session Service Enabled
2020/11/18 09:31:03 routers/init.go:63:initDBEngine() [I] Beginning ORM engine initialization.
2020/11/18 09:31:03 routers/init.go:70:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/11/18 09:31:03 ...rm/session_schema.go:25:Ping() [I] PING DATABASE mssql
2020/11/18 09:31:03 ...eue/queue_wrapped.go:75:setInternal() [W] [Attempt: 1] Failed to create queue: level for notification-service cfg: queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"notification-service-level"}, DataDir:"D:\\gitea\\var\\lib\\gitea\\data\\queues\\notification-service"} error: The process cannot access the file because it is being used by another process.
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] select * from sysobjects where id = object_id(N'version') and OBJECTPROPERTY(id, N'IsUserTable') = 1 [] - 3.9997ms
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] IF NOT EXISTS (SELECT [name] FROM sys.tables WHERE [name] = 'version' ) CREATE TABLE [version] ([id] BIGINT PRIMARY KEY IDENTITY NOT NULL, [version] BIGINT NULL); [] - 12.0016ms
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT "COLUMN_NAME" FROM "INFORMATION_SCHEMA"."COLUMNS" WHERE "TABLE_NAME" = ? AND "COLUMN_NAME" = ? [version id] - 32.998ms
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT "COLUMN_NAME" FROM "INFORMATION_SCHEMA"."COLUMNS" WHERE "TABLE_NAME" = ? AND "COLUMN_NAME" = ? [version version] - 14.0031ms
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT TOP 1 [id], [version] FROM [version] WHERE [id]=? [1] - 997.5µs
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] INSERT INTO [version] ([version]) OUTPUT Inserted.id VALUES (?) [141] - 2.9998ms
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] select name from sysobjects where xtype ='U' [] - 2.0005ms
2020/11/18 09:31:03 ...eue/queue_wrapped.go:75:setInternal() [W] [Attempt: 2] Failed to create queue: level for notification-service cfg: queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"notification-service-level"}, DataDir:"D:\\gitea\\var\\lib\\gitea\\data\\queues\\notification-service"} error: The process cannot access the file because it is being used by another process.
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] select a.name as name, b.name as ctype,a.max_length,a.precision,a.scale,a.is_nullable as nullable,
			  "default_is_null" = (CASE WHEN c.text is null THEN 1 ELSE 0 END),
		      replace(replace(isnull(c.text,''),'(',''),')','') as vdefault,
			  ISNULL(p.is_primary_key, 0), a.is_identity as is_identity
	          from sys.columns a 
			  left join sys.types b on a.user_type_id=b.user_type_id
	          left join sys.syscomments c on a.default_object_id=c.id
			  LEFT OUTER JOIN (SELECT i.object_id, ic.column_id, i.is_primary_key
				FROM sys.indexes i
			  LEFT JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
				WHERE i.is_primary_key = 1
			) as p on p.object_id = a.object_id AND p.column_id = a.column_id
	          where a.object_id=object_id('user') [] - 88.9988ms
2020/11/18 09:31:03 ...m.io/xorm/core/db.go:154:QueryContext() [I] [SQL] SELECT
	IXS.NAME                    AS  [INDEX_NAME],
	C.NAME                      AS  [COLUMN_NAME],
	IXS.is_unique AS [IS_UNIQUE]
	FROM SYS.INDEXES IXS
	INNER JOIN SYS.INDEX_COLUMNS   IXCS
	ON IXS.OBJECT_ID=IXCS.OBJECT_ID  AND IXS.INDEX_ID = IXCS.INDEX_ID
	INNER   JOIN SYS.COLUMNS C  ON IXS.OBJECT_ID=C.OBJECT_ID
	AND IXCS.COLUMN_ID=C.COLUMN_ID
	WHERE IXS.TYPE_DESC='NONCLUSTERED' and OBJECT_NAME(IXS.OBJECT_ID) =?
	 [user] - 1.0002ms
2020/11/18 09:31:03 routers/init.go:76:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2020/11/18 09:31:03 routers/init.go:77:initDBEngine() [I] Backing off for 3 seconds
2020/11/18 09:31:03 ...eue/queue_wrapped.go:75:setInternal() [W] [Attempt: 3] Failed to create queue: level for notification-service cfg: queue.LevelQueueConfiguration{ByteFIFOQueueConfiguration:queue.ByteFIFOQueueConfiguration{WorkerPoolConfiguration:queue.WorkerPoolConfiguration{QueueLength:20, BatchLength:20, BlockTimeout:1000000000, BoostTimeout:300000000000, BoostWorkers:5, MaxWorkers:6}, Workers:1, Name:"notification-service-level"}, DataDir:"D:\\gitea\\var\\lib\\gitea\\data\\queues\\notification-service"} error: The process cannot access the file because it is being used by another process.
```

### LINKED ISSUE #16483: ORM engine initialization failed: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
- Gitea version (or commit ref): gitea-1.14.4-windows-4.0-amd64
- Git version: 2.32.0
- Operating system: Windows
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
```
2021/07/19 13:22:43 routers/init.go:68:initDBEngine() [I] Beginning ORM engine initialization.
2021/07/19 13:22:43 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #1/10...
2021/07/19 13:22:43 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE  mssql
2021/07/19 13:22:43 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:22:43 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:22:46 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #2/10...
2021/07/19 13:22:46 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:22:46 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:22:46 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:22:49 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #3/10...
2021/07/19 13:22:49 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:22:49 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #3/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:22:49 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:22:52 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #4/10...
2021/07/19 13:22:52 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:22:52 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #4/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:22:52 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:22:55 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #5/10...
2021/07/19 13:22:55 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:22:55 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #5/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:22:55 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:22:58 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #6/10...
2021/07/19 13:22:58 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:22:59 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #6/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:22:59 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:23:02 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #7/10...
2021/07/19 13:23:02 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:23:02 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:23:02 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:23:05 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #8/10...
2021/07/19 13:23:05 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:23:05 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #8/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:23:05 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:23:08 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #9/10...
2021/07/19 13:23:08 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:23:08 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #9/10 failed. Error: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
2021/07/19 13:23:08 routers/init.go:82:initDBEngine() [I] Backing off for 3 seconds
2021/07/19 13:23:11 routers/init.go:75:initDBEngine() [I] ORM engine initialization attempt #10/10...
2021/07/19 13:23:11 ...om/urfave/cli/app.go:524:HandleAction() [I] PING DATABASE mssql
2021/07/19 13:23:11 routers/init.go:157:GlobalInit() [F] ORM engine initialization failed: sync database struct error: mssql: Invalid object name 'SYS.INDEXES'.
```

SQL Server V18.5

## Description

After Gitea setup, when I want to run it, I get the previously mentioned errors.
I checked the created database (gitea) but I couldn't find a table called 'dbo.sys' in it (I can see all of the other tables including 'dbo.project', 'dbo.user', etc). I'm not sure where I should look for this 'sys.indexes' column. Is there any suggestion? How can I fix this problem?

P.S: There is another issue like this as well with no solution. [issues-6201](https://github.com/go-gitea/gitea/issues/6201)

### LINKED ISSUE #16625: Failed attempt to migrate to 1.15-rc2 windows SQL Server 2008 R2 sp3
- Gitea version (or commit ref):  v1.15.0-rc2
- Git version: 2.32.0.windows.2
- Operating system:  Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description
from my initial discord post.
Just tried 1.15-rc2 windows go-git version and it fails to start, with sql errors during migration.
We're using SQL 2008 R2 which doesn't support IF EXISTS option.
~~~~
2021/07/29 11:33:53 ...ations/migrations.go:49:Migrate() [I] [SQL] ALTER TABLE [hook_task] DROP CONSTRAINT IF EXISTS [IDX_tmp_recreatehook_task_typ] []
2021/07/29 11:33:53 ...ations/migrations.go:422:Migrate() [I] [SQL] ROLLBACK [] - 504.6µs
2021/07/29 11:33:53 routers/init.go: 100:GlobalInit() [F] ORM engine initialization failed: migrate: do migrate: Drop table hook_task index constraint `IDX_tmp_recreatehook_task_typ`: mssql: Incorrect syntax near the keyword 'IF'
~~~~

### PR DESCRIPTION
**Pull request by zeripath**
This fixes two problems with MSSQL:

* `ALTER TABLE DROP ... IF EXISTS ...` is only supported in SQL Server >16.

The `IF EXISTS` here is a belt-and-braces and does not need to be present. Therefore
can be dropped. Also stop attempting to drop the indexes as constraints as they're indexes!

* System tables like: `sys.indexes` should be lowercase not uppercase because of collation issues.

Fix #16625
Fix #13615
Fix #16483

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by lafriks** [comment]
This seems to break migrations

**Comment by silverwind** [comment]
> We need to figure out some way of restricting our SQL syntax against the minimum version of SQL Server we will support.

Should probably add that minimum version on CI and then run all migrations/tests against it, that should lead to CI failures in case of incompatible syntax. 2012 is the oldest version supported by MS, but I think only 2017 and above are available for Linux so we might need to set minimum version to 2017 to be able to test it.

**Comment by zeripath** [comment]
yup it does because it seems that we will need to check if the thing is a constraint or an index.

Damn.

**Comment by zeripath** [comment]
Ah that seems to be now working

**Comment by lunny** [comment]
You can check if the index is exist at first.

**Comment by zeripath** [comment]
Line 854 only selects the indexes that exist. The `IF EXIST` is belt and braces and unnecessary. The `DROP CONSTRAINT` code was only there because of an earlier problem - solved by lines 843-853.

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
