### PR TITLE
Change default size of issue/pr attachments and repo file

### PR DESCRIPTION
**Pull request by nanguanlin6**
As title. Some attachments and file sizes can easily be larger than these limits

### CODE REVIEW

**Comment by silverwind** [comment]
How about 50MiB which is also the default on GitHub currently? We do want to find some reasonable default values that prevent abuse from uploading too large files.

**Comment by lng2020** [comment]
50MiB is okay for the repo file. But the `attachment ->MAX_SIZE` is also used in the `release` page. I think it's better to use a larger one. But we should probably separate the limit of PR/issue attachment and the `release` file.
image

**Comment by lng2020** [comment]
BTW, the alert of the file exceeding limits is broken. Haven't found out root reason yet but it's probably because the function `initGlobalDropzone`
https://github.com/go-gitea/gitea/blob/481e738e7f3ee22a5a8280d155a1b7d1ff09bc7f/web_src/js/features/common-global.js#L199-L253

**Comment by silverwind** [comment]
Right, releases need a bigger limit. GitHub has this at 2GB per file currently.

**Review by silverwind — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
