### PR TITLE
Improvements surrounding merge box, add 24px octicons

### PR DESCRIPTION
**Pull request by silverwind**
- Remove box top margins
- Generate 24px octicon variants
- Change merge box "avatar" to background effect and use 24px octicon on it
- Add margin inside merge button between icon and text

These 24px variants will prove useful for some cases where we render these icons bigger.

Before:

Screenshot 2023-05-29 at 22 36 23

After:
Screenshot 2023-05-29 at 22 35 58

### CODE REVIEW

**Comment by silverwind** [comment]
Regarding 24px octicons, I think we could make the `svg` functions automtically output the 24px variant if rendered size is >= 24.

**Comment by silverwind** [comment]
WIP until autoselection of 24px octicons is implemented.

**Comment by silverwind** [comment]
> 图片
> 
> The icon's style is not the same as others?

Yes that's intentional. I will update our `svg` function so they automatically choose 24px variants if requested size is >= 24, this is how it works on GitHub too. The icons look better in their higher pixel numbers.

**Comment by silverwind** [comment]
All should have, need to check.

**Comment by denyskon** [comment]
@silverwind Is this PR still WIP? What is missing here?

**Comment by silverwind** [comment]
I would like to autmatically select 24px octicons based on passed icon size but haven't gotten around to it yet. It is a non-trivial change on both frontend and backend.

**Comment by silverwind** [comment]
I think I will separately introduce the "24px" octicons in another PR. Then we can start making use of them.

**Pull request closed without merging**
