### PR TITLE
Handle ErrUserProhibitLogin in http git (#7586, #7591)

### LINKED ISSUE #7558: 500 returned trying to git clone with user that cannot sign in
- Gitea version (or commit ref): 1.8.1
- Git version: 2.20.1
- Operating system: Gitea Docker Image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2019/07/22 02:04:57 [...s/context/context.go:238 func1()] [E] UserSignIn: user is not allowed login [uid: 5, name: <username>]
2019/07/22 02:04:57 [...routers/repo/http.go:205 HTTP()] [E] UserSignIn error: %v: user is not allowed login [uid: 5, name: <username>]
```

## Description
When trying to `git clone` with an account that is activated but has disable sign in checked, Gitea returns 500. It should return a more appropriate HTTP status code, i.e. 401 or 403, since 500 may lead people to believe that something is wrong on Gitea's side when it isn't.

(The context for this was that I was trying to get a user account that was allowed read-only git access, but not web ui access - like a service account. I tried to keep the account active but disabled sign-in...)

## Screenshots

N/A

### PR DESCRIPTION
**Pull request by zeripath**
Backport #7586 & #7591 

Fix #7558

### CODE REVIEW

**Comment by sapk** [comment]
After reviewing https://github.com/go-gitea/gitea/pull/7586#discussion_r306445837. I think we should send and 403 and not a 401 response in this case.

**Comment by zeripath** [comment]
I think that would mean that the backport and master were not aligned unless we added another PR to apply that.

**Comment by sapk** [comment]
The best would be to not merged this backport and do a new PR on master that will be backported. I can do it if you don't have time.

**Comment by lafriks** [comment]
I agree with @sapk that master should be fixed first

**Comment by zeripath** [comment]
see #7591

**Comment by zeripath** [comment]
Ok @sapk and @lafriks that's done.

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by sapk** [comment]
Thanks @zeripath for your reactivity.

**Pull request merged**
