### PR TITLE
Fix wiki preview links

### LINKED ISSUE #1900: Links broken in Wiki page preview
- Gitea version (or commit ref): 1.1.1
- Operating system: Arch Linux
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes at https://try.gitea.io/hans/w00t/wiki/Home

## Description
If you add relative links and go to preview mode, the base url has an extra slash ('/') character which makes the links fail.

E.g. the link `[this](/)` expands to `https://try.gitea.io//hans/w00t//`. When the page is saved, the link correctly expands to `https://try.gitea.io/hans/w00t//`

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #1900, which was caused by a bug in `markdown.URLJoin(..)`. I've also added unit tests for `markdown.URLJoin(..)`.

### CODE REVIEW

**Comment by lafriks** [comment]
Why did all resulting test urls change?

**Comment by ethantkoenig** [comment]
@lafriks The old tests were broken. The expected strings were of the form `.../rawimage/foo.png` instead of `.../raw/image/foo.png`. And before `URLJoin(..)` was fixed, the actual strings were similarly wrong (which is why tests had been passing)

**Comment by lafriks** [comment]
Ok, than it LGTM

**Comment by sapk** [comment]
LGTM

**Review by sapk — APPROVED** [review]

**Pull request merged**
