### PR TITLE
Improve some modal action buttons

### PR DESCRIPTION
**Pull request by wxiaoguang**
Follow #24097 and #24285

And add a devtest page for modal action button testing. http://localhost:3000/devtest/fomantic-modal

Now the `modal_actions_confirm.tmpl` could support: green / blue / yellow positive buttons, the negative button is "secondary".

ps: this PR is only a small improvement, there are still a lot of buttons not having proper colors. In the future these buttons could be improved by this approach.

These buttons could also be improved according to the conclusion of #24285 in the future.

image

And add GitHub-like single danger button (context: https://github.com/go-gitea/gitea/issues/24285#issuecomment-1519100312)

image

### CODE REVIEW

**Comment by silverwind** [comment]
Can all three styles of https://github.com/go-gitea/gitea/issues/24285#issuecomment-1519117518 be supported in [modal_actions_confirm.tmpl](https://github.com/go-gitea/gitea/pull/24289/files#diff-d97744a14ca448e747b4d0cca2321658ad37465719a947e7632ff2c9edd6bea3)?

**Comment by silverwind** [comment]
Maybe we should rename `gitea-confirm-modal` to `gt-confirm-modal` for consistency with other classes?

Personally, I'd go even shorter, `g-confirm-modal` 😆

**Comment by wxiaoguang** [comment]
> Can all three styles of [#24285 (comment)](https://github.com/go-gitea/gitea/issues/24285#issuecomment-1519117518) be supported in [modal_actions_confirm.tmpl](https://github.com/go-gitea/gitea/pull/24289/files#diff-d97744a14ca448e747b4d0cca2321658ad37465719a947e7632ff2c9edd6bea3)?

It could support. But I think we should reduce different styles. Some styles doesn't work well (and I guess many people agree with this, I also agree):

1. Making "positive" button as "red": it is counterintuitive ,  you may see "Green Negative" / "Red Positive" sometimes and   "Red Negative" / "Green Positive" sometimes, I do not see any UI framework / web site does so.
2. "filled primary" : sometimes the button is "blue" (default theme) sometimes the button is "green" (arc-green), it really doesn't look good to me. I believe the Positive button should have stable colors.
3. "All other buttons just basic outlined buttons without color": only one negative button, it could be supported by only 2-line changing.

And we shouldn't depend on color too much, because many people could have difficulty for green-red.

----

> Maybe we should rename `gitea-confirm-modal` to `gt-confirm-modal` for consistency with other classes?
> Personally, I'd go even shorter, g-confirm-modal 😆

`gt-` is reversed for tailwind-style styles, so I think it shouldn't be used for Gitea's private styles.

`g-` could be fine IMO, will make a new change.

**Comment by wxiaoguang** [comment]
@silverwind new changes in latest commits.

1. Always use `secondary` for negative buttons
2. Rename `gitea-confirm-modal` to `g-confirm-modal` , and add comments/documents

**Comment by silverwind** [comment]
> gt- is reversed for tailwind-style styles, so I think it shouldn't be used for Gitea's private styles.

I would rename all `gt-` to `g-`. Less to type and there is no point in namespacing off the helpers from other elements, they can share the namespace.

**Review by HesterG — APPROVED** [review]

**Comment by silverwind** [comment]
> I have objection for mixing tailwind style helpers `gt-` and Gitea's own private component styles `g-`, they would cause unsolvable conflicts if we really want to introduce tailwind one day.

They all live in the same file, but whatever, let's keep the naming for now.

**Comment by silverwind** [comment]
image

This "No" button looks ugly in terms of border, but I'll accept it for now and will probably re-style it in another PR to match other basic buttons.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
.

**Comment by wxiaoguang** [comment]
> This "No" button looks ugly in terms of border, but I'll accept it for now and will probably re-style it in another PR to match other basic buttons.

The "thick" border is added by ":focus". 

The problem of old Gitea styles is: there is no obvious UI feedback for focused elements, that's very unfriendly to a11y.

**Pull request merged**
