### PR TITLE
Migrate WatchInfo struct to api

### PR DESCRIPTION
**Pull request by sapk**
So that the api repo contain all struct for api response and resquest.

Need : go-gitea/go-sdk#50

### CODE REVIEW

**Comment by sapk** [comment]
This is ready just need  go-gitea/go-sdk#50 so I will update govendor when merged.

**Comment by appleboy** [comment]
@sapk Please go ahead.

**Comment by sapk** [comment]
go-gitea/go-sdk#50 is merged.
I remove temporary change in vendor and this is ok to be review/merged.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
