### PR TITLE
Changed colors of delete-modal

### PR DESCRIPTION
**Pull request by mawoka-myblock**
The "Confirm"-Delete button is now red and the cancel-button green.

  
---

The colors of the buttons in the delete-modal are swapped, so that the cancel-button is now green and the confirm-button is now red.

### CODE REVIEW

**Comment by delvh** [comment]
Could you please paste a screenshot how it looks like now?
Because while I can generally guess how it would look like, it most likely won't hurt to see it visualized?

**Comment by mawoka-myblock** [comment]
## Old
Nein_alt
Ja_alt



## New
Nein_neu
Ja_neu

**Comment by mawoka-myblock** [comment]
Any updates @delvh ?

**Review by delvh — COMMENTED** [review]
In general, I can absolutely see this change.
The only problem: There are currently many self-built delete modals inside the templates:
Simply search for `delete modal` inside files in the templates folder, and you'll see what I mean.
And those other modals all have the previous behavior.

Due to the complexity introduced by Go templates, they likely won't be converted into calls of this template for quite some time.
So, they should be adapted then as well.

**Comment by wxiaoguang** [comment]
Now we have a totally new "modal button" system. #24289

The "negative" button could never be "green" anymore.

But there are still many modal buttons do not have consistent colors, eg: some "delete modal" buttons are yellow, some are green.

**Comment by mawoka-myblock** [comment]
Then this pr isn't needed anymore

**Pull request closed without merging**
