### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by typeless**
Apply for maintainership.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
🎉

**Review by guillep2k — APPROVED** [review]
Welcome!

**Comment by techknowlogick** [comment]
@typeless can you post your discord username here (or email me at techknowlogick@gitea.io) so I can give you the appropriate permissions? Also watch for an email from github with an invite to the gitea org :)

**Comment by typeless** [comment]
@techknowlogick typeless#8123. Thanks.

**Pull request merged**
