### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by jfcg**
Add Github CodeQL security checks for Go and Javascript.

### CODE REVIEW

**Comment by 6543** [comment]
@jfcg can you provide some more info hat this is?

links to docs etc ...

**Comment by jfcg** [comment]
Hi. See https://securitylab.github.com/tools/codeql

**Comment by silverwind** [comment]
Note that adding this would be a vendor lock-in to Github, we don't use Actions.

**Comment by jfcg** [comment]
In my fork under `/security/code-scanning` I see:
gitea

Cheers ;)

**Comment by silverwind** [comment]
Guess that page is not publically accessible. I'm not generally opposed to this as an extra security check. 101 issues seems a bit much, I guess there may be many false-positives.

**Comment by zeripath** [comment]
@jfcg are you able to look into any of those "problems" to see if they actually represent real issues? As @silverwind says I suspect these are all false positives. 

I'm not averse to fixing stuff but frankly we have enough noise to deal with already.

**Comment by jfcg** [comment]
On some repositories that I have reported the same issue, repo owners are able to see the affects of a PR, including extra .github/workflows.

**Pull request closed without merging**
