### PR TITLE
Fixed form control is not focusable #687

### LINKED ISSUE #687: Can't add ldap simple auth source
- Gitea version (or commit ref):1.0.0+126-g302fa429 (pulled from docker in the last few days
- Git version: has nothing to do with git
- Operating system: official docker container on a fedora host
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Gitea prompts me to fill out "this field" with an arrow to the top left corner, where no field is.
I have filled out all required fields.
[I have put a demonstration of this behaviour on youtube.](https://youtu.be/v5-9wQ-KZxk)

It works fine via BindDN, so this is not that bad, but it would be better if simple auth worked too, since I gitea is now the only of my five or so webapps that has an entry in my ldap database..

### PR DESCRIPTION
**Pull request by shyim**
Fixes #687 
I have tried any auth type and it works

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
let L-G-T-M work

**Pull request merged**
