### PR TITLE
[wip] Pin repositories

### PR DESCRIPTION
**Pull request by era**
Just a placeholder for #10375 MR in order to get feedback as I go with the changes (my first time coding at gitea).

My plan is:

- Add the fields pinned (boolean) and pinnedOrder (int) to the repo itself, and for now, allow changing these fields with the edit repository API call. I'm not sure if this is the best path or I should create an API just for this.
- We probably want to limit the number of pinned repositories. Even if we don't use it right now, I think I will code the ability to do it in the backend.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
I don't think that should be a field of the repo but simply a new table which lists all pinned repos for a user.

**Comment by era** [comment]
It makes sense to be a new table, I have something working using the new field at: https://github.com/era/gitea/pull/1

I will try to make the change to use a new table next week. Thanks for the feedback :)

**Comment by r10r** [comment]
Hey @era I just stumbled upon your pull request. Are you still working on this?

**Comment by era** [comment]
No, feel free to pick it up if you have the time :)

**Comment by r10r** [comment]
Unfortunately I have no time left right now. But I'll keep an eye on it :)

**Pull request closed without merging**
