### PR TITLE
Rectify and enhance signup/login test

### PR DESCRIPTION
**Pull request by typeless**
Use the URL of the redirected GET response as checkpoints for POST endpoints, instead of using the 200 OK HTTP status code.

### CODE REVIEW

**Comment by strk** [comment]
Since you are at it, why not also checking for correct handling of the redirect_to query string ?

**Comment by typeless** [comment]
@strk It's not required for the following steps (like creating repos). I can add it, but I am not sure if checking the status code (200 OK) solely is sufficient. What do you think the things I should look at (to make sure it's actually tested)?

**Comment by strk** [comment]
Maybe I misread the code but you seem to be checking the URL you are redirected to after login.
As I know this can be specified on the login url (with the `?return_to` query string parameter) it would be useful to check that doing so works too (in addition to checking the default redirection url)

**Comment by typeless** [comment]
In favor of #1290

**Pull request closed without merging**
