### PR TITLE
update copyright gitea license

### PR DESCRIPTION
**Pull request by avelino**

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
LGTM, although legally speaking you can't just change ownership of copyright... (moot point as neither "Gogs authors" nor "Gitea authors" have any legal meaning)

**Comment by strk** [comment]
either mine or @lunny LGTM wasn't counted ?

**Comment by tboerger** [comment]
This is simply wrong and needs to be changed. Look at the readme of the go-sdk repo.

**Comment by strk** [comment]
Yes (the LICENSE) that one looks better:
https://github.com/go-gitea/go-sdk/blob/master/LICENSE

**Comment by strk** [comment]
Please review https://github.com/go-gitea/gitea/pull/115

**Pull request merged**
