### PR TITLE
Add mermaid JS renderer

### LINKED ISSUE #12307: Mermaid Js not rendering in Readme but in Issues and Wiki
- Gitea version (or commit ref): 1.13.0+dev-283-g56f222d44
- Git version: 2.26.2
- Operating system: linux Unraid
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:

## Description

Mermaid.js rendering is only working in Issues & Wiki. Not in README.md files.

Code used to test: 
```mermaid
sequenceDiagram
    loop Daily query
        Alice->>Bob: Hello Bob, how are you?
        alt is sick
            Bob->>Alice: Not so good :(
        else is well
            Bob->>Alice: Feeling fresh like a daisy
        end

        opt Extra response
            Bob->>Alice: Thanks for asking
        end
    end
```

## Screenshots
Gitea_Issue_Wiki
Gitea_Issue_Readme

### PR DESCRIPTION
**Pull request by silverwind**
For feature parity with GitLab. Tested in files, issues, wiki, editor. arc-green only does an inversion because the renderer seems to like to render white backgrounds on boxes.

Ref: https://github.com/go-gitea/gitea/issues/3340
Fixes: https://github.com/go-gitea/gitea/issues/12307

Previews:

image
image

Sample for testing:

````
```mermaid
    stateDiagram
    [*] --> Active

    state Active {
        [*] --> NumLockOff
        NumLockOff --> NumLockOn : EvNumLockPressed
        NumLockOn --> NumLockOff : EvNumLockPressed
    }
```
````

### CODE REVIEW

**Comment by silverwind** [comment]
The only real downside I see with this is that the library is a bit heavy at 1.4MiB so will add a bit to our webpack build time. The code itself is rather trivial and should not require much to maintain.

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Took a few hints from the [gitlab](https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/behaviors/markdown/render_mermaid.js) implementation. Now renders without a border and with neutral theme. Updating screenshots...

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
This may break the user's customerized mermaid rendering. We should have a warnning for that.

**Comment by techknowlogick** [comment]
🚀

**Comment by silverwind** [comment]
> This may break the user's customerized mermaid rendering

I don't think it will. Our script will likely run before the user-supplied one and then their script is essentially a noop because it won't find any matching elements.

**Comment by lafriks** [comment]
Looks like editor is now broken withe error:
```
Uncaught (in promise) TypeError: e[t] is undefined
    o https://try.gitea.io/js/index.js?v=2e108e628cde5272a8a152c33efb9249:1
    t https://try.gitea.io/js/index.js?v=2e108e628cde5272a8a152c33efb9249:1
```

**Comment by silverwind** [comment]
It does work for me https://try.gitea.io/silverwind/symlink-test/issues/7. Try refreshing the page a few times? There's still a unresolved issue with bad serviceworker cache which I'll soon look into.

**Comment by silverwind** [comment]
Ah, misread. What exactly do you do to trigger that error?

**Comment by lafriks** [comment]
Just edit file in repository (I was trying to edit README.md)

**Comment by lafriks** [comment]
nevermind, now it does work :sweat_smile:

**Comment by silverwind** [comment]
Yeah, serviceworker strikes again. I plan to experiment with `contenthash` chunks which will hopefully bust that cache and fix these issues after frontend rebuilds.

**Pull request merged**
