### PR TITLE
Fix dropdown content overflow

### LINKED ISSUE #31602: Adding .gitignore templates overflow
### Description

On creating a repo, when choosing too many .gitignore templates it overflows

URL
https://demo.gitea.com/repo/create

### Screenshots

Screenshot_20240710_005416

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

kubuntu 6.5.0-41-generic  x86_64

### Browser Version

Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by charles7668**
close #31602 

圖片

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by silverwind — DISMISSED** [review]
This is definitely the wrong place to put this and I guarantee this will cause regressions. I would put it on selector `.ui.multiple.search.selection.dropdown` or maybe just `.ui.ui.dropdown` (but more dangerous) and test if any other similar dropdowns work fine.

**Comment by charles7668** [comment]
> This is definitely the wrong place to put this and I guarantee this will cause regressions. I would put it on selector `.ui.multiple.search.selection.dropdown` or maybe just `.ui.ui.dropdown` (but more dangerous) and test if any other similar dropdowns work fine.

Would it be better to put the `tw-flex-wrap` class in the div that has this issue?

Here is a test of adding `tw-flex-wrap` in the place where I know this issue occurs.

圖片
圖片
圖片

**Comment by 6543** [comment]
I personally prevere tailwind classes over own css ...

**Review by 6543 — DISMISSED** [review]

**Comment by silverwind** [comment]
> I personally prevere tailwind classes over own css ...

The problem is unfortunately because we set `display: flex` on `.ui.dropdown` which is something Fomantic's CSS does not anticipate. Tailwind is not ideal in this case because it needs to be replicated to every such dropdown in the UI and we need to fix all of them, so it would be a hacky fix if we do it with Tailwind.

Ideally I would like to see whether we can remove this `display: flex` entirely, and if that is deemed to problematic, I can accept a override on `.ui.multiple.search.selection.dropdown` as well.

**Comment by 6543** [comment]
Uh in this cas its hands of for me ... feel free to ping me if it's just about testing the result 😅 

@silverwind can you describe your solution so @charles7668 can implement it ☺️ ?

**Comment by charles7668** [comment]
I changed the `.ui.ui.dropdown` display style to `inline-block` and checked the dropdown divs that I know of, and it seems to work fine.

In single selection: seems like no difference.
In multiple selection: the display is the same as `flex-wrap`.

The following are the areas where I checked multiple selection:
1. Create repository page: `.gitignore` section
2. Commit graph page
3. Repository settings page -> Tags

**Comment by wxiaoguang** [comment]
> I changed the `.ui.ui.dropdown` display style to `inline-block` and checked the dropdown divs that I know of, and it seems to work fine.

It is still not right. Check every edge-case and add your edge-case to the "devtest" pages.

**Comment by charles7668** [comment]
Updated and add some test case
empty:
image

no overflow:
image

overflow:
image

**Comment by wxiaoguang** [comment]
image

**Comment by silverwind** [comment]
> I changed the .ui.ui.dropdown display style to inline-block and checked the dropdown divs that I know of, and it seems to work fine.

How about just removing the `display: flex` and let the original Fomantic CSS take effect? If there is a specific reason for `inline-block` in some places, I recommend overwriting with tailwind classes there.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/25163 had added this `display: flex`, so that is the PR where this was regressed. @wxiaoguang do you recall the reason for `display: flex`?

**Comment by wxiaoguang** [comment]
> #25163 had added this `display: flex`, so that is the PR where this was regressed.
> 
> @wxiaoguang do you recall the reason for `display: flex`?

To make the UI align. All known cases were written into the devtest page in #25163

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
@6543 why "outdated" ? only one line change.

**Comment by lunny** [comment]
> This is definitely the wrong place to put this and I guarantee this will cause regressions. I would put it on selector `.ui.multiple.search.selection.dropdown` or maybe just `.ui.ui.dropdown` (but more dangerous) and test if any other similar dropdowns work fine.

Please review again.

**Comment by wxiaoguang** [comment]
> @6543 why "outdated" ? only one line change.

@6543

**Review by delvh — APPROVED** [review]

**Pull request merged**
