### PR TITLE
Support secure cookie for csrf-token

### LINKED ISSUE #1734: COOKIE_SECURE doesn't flag _csrf cookie as 'Secure'
- Gitea version (or commit ref): 1.1.1
- Git version: 2.1.4
- Operating system: Debian GNU/Linux 8.8 (jessie) x86_4
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I was under the impression that setting COOKIE_SECURE to true will make all cookies have the 'Secure' flag set. However it only seem to apply to the i_like_gitea cookie.

https://try.gitea.io doesn't seem to be configured with COOKIE_SECURE.

### PR DESCRIPTION
**Pull request by AleksandrBulyshchenko**
Fixes #1734

Currently SetCookie for csrf has secure hardcodded to false.
This passes security argument to cookie creation and set it by COOKIE_SECURE config var.

### CODE REVIEW

**Comment by thehowl** [comment]
Thank you for your pull request! And thanks for spotting the problem - I created #3833 yesterday (perhaps you didn't see it?). In any case, we should not modify vendor dependencies directly - we should try to modify the upstream repo first then pull it on Gitea (and Unknwon seems to be in the part of the year where he's actually active on the internet, so if you make PRs they have a chance to be merged).

Can you please do it on that repo and then pull the changes with Govendor?

**Comment by lafriks** [comment]
Yes, first PR in go-macron should be submitted and only than when it's merged we can do govendor fetch to update dependency from upstream

**Comment by AleksandrBulyshchenko** [comment]
@thehowl,
Sorry for the mess.

> Can you please do it on that repo and then pull the changes with Govendor?

I've created go-macaron/csrf#7

**Comment by thehowl** [comment]
@AleksandrBulyshchenko upstream PR seems to have been merged. Can you update deps with govendor on this PR?

Many thanks!

**Comment by AleksandrBulyshchenko** [comment]
@thehowl,
I've updated the PR with fetched go-macaron/csrf

But as I can see build verification has failed - probably it requires projects in GOPATH on build server to be in sync.

**Comment by lafriks** [comment]
did you use `govendor fetch github.com/go-macaron/csrf`?

**Comment by AleksandrBulyshchenko** [comment]
@lafriks,
> did you use govendor fetch github.com/go-macaron/csrf?

yes, exactly

**Comment by techknowlogick** [comment]
@AleksandrBulyshchenko The project is now using `dep` to manage dependencies. Could you update this PR to match? If you are unable (perhaps you don't have time) let us know and we can submit a new PR on your behalf.

cc: @sapk

**Comment by AleksandrBulyshchenko** [comment]
- Rebased onto `master`.
- Updated `github.com/go-macaron/csrf` with `dep` instead of `govendor`.

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
