### PR TITLE
remove and disable package-lock

### LINKED ISSUE #6967: `make css` generate a different `package-lock.json` on master
Don't know if this is related with #6952 
```
$ make css
npx lesshint public/less/
npx lessc --clean-css="--s0 -b" public/less/index.less public/css/index.css
npx lessc --clean-css="--s0 -b" public/less/themes/arc-green.less > public/css/theme-arc-green.css;
npx postcss --use autoprefixer --no-map --replace public/css/*

/Volumes/data/Projects/gitea/gitea on  master! ⌚ 20:08:29
$ ls
BSDmakefile       Dockerfile        README.md         contrib           docker            go.sum            main.go           options           routers           templates
CHANGELOG.md      LICENSE           README_ZH.md      coverage.out      docs              indexers          models            package-lock.json scripts           vendor
CONTRIBUTING.md   MAINTAINERS       assets            custom            gitea             integrations      modules           package.json      snap
DCO               Makefile          cmd               data              go.mod            log               node_modules      public            sqlite-log

/Volumes/data/Projects/gitea/gitea on  master! ⌚ 20:08:32
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

### PR DESCRIPTION
**Pull request by silverwind**
Using exact versions in package.json has almost the same effect as lockfiles without all the troubles the lockfiles bring (different versions of package manager generating different lockfiles primarily).

Ensured we only use exact versions in package.json and stopped generation of new lockfiles via .npmrc which is support by both the npm and yarn package managers.

Fixes: https://github.com/go-gitea/gitea/issues/6967

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by silverwind** [comment]
Small tweak pushed: The `save-exact` option makes modules installed via `npm install <module>` to save with a exact (what we want) over the default caret `^` versions, so mistakes like for the lesshint case should no longer happen.

**Comment by InExtremaRes** [comment]
It is very unlikely but I once saw a weird (minor) bug in one machine that doesn't happened in the other. After some tracking we found the problem was for a dependency of one of our dependencies, that has the bug in a minor version update, so the machine that executed `npm install` last installed the bugged dep. It was fixed very soon, but wasn't obvious where the problem come from.

The point of having a `package-lock.json` is not only to lock your own dependencies, but the entire tree of dependencies (the deps of the deps of your deps... and so on), ensuring the same exact tree version of them are installed across all systems.

I have suffered the weird things about maintaining a `package-lock.json` (as npm adding/deleting `"dev": true` or changing https to http, etc) so I understand the motive behind this change, but I wanted to remark the reason of its existence so you are sure this is the right path.

Regards

**Comment by lafriks** [comment]
I do also agree that it is best to have package-lock.json even though it could change depending on npm version

**Comment by silverwind** [comment]
We don't really know what happened for @lunny there, it's just a guess that the reason for the change is a npm version difference. @lunny if you can still reproduce after reverting this change, can you show a diff what changed?

**Comment by lunny** [comment]
@lafriks It's annoying that every time I build gitea, the git workspace will be changed.
@silverwind I'm not using the recent npm version.

```
/xxxxx/gitea/gitea on  lunny/revert_lock ⌚ 14:12:49
$ npm install
npm WARN gitea No repository field.

updated 1 package and audited 4465 packages in 5.238s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.1.0 → 6.9.0       │
   │   Changelog: https://github.com/npm/npm/releases/tag/v6.9.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯


/xxxxx/gitea/gitea on  lunny/revert_lock! ⌚ 14:12:58
$ npm --version
6.1.0
```

**Comment by lafriks** [comment]
@lunny but you have to do `npm install` only once, than you can discard lock file changes as we have only tools in node_modules directory currently anyway

**Comment by silverwind** [comment]
We could opt to keep the setting to disable lockfile generation in `.npmrc`, so in @lunny's case, `npm install` would not rewrite it. If one wants to do a package upgrade they'd have to do `npm install --package-lock` to enable it again, maybe via dedicated `make` target.

**Comment by lafriks** [comment]
@silverwind that would be the best option imho

**Comment by silverwind** [comment]
Not 100% certain it will work. npm's docs say:

> The --no-package-lock argument will prevent npm from creating a package-lock.json file. When running with package-lock’s disabled npm will not automatically prune your node modules when installing.

Depending on interpretation, this could also mean it would ignore the file while installing modules which is not what we want. Need to check in npm's source code.

**Pull request merged**
