### PR TITLE
Make Ctrl+Enter work for issue/comment edit

### LINKED ISSUE #30710: `Ctrl`+`Enter` works when creating but not when updating a comment
### Description

I often use `Ctrl` + `Enter` when saving comments, but it only works when creating a new comment/issue, has no effect when trying to POST after editing a comment.

### Gitea Version

1.21.11+9-g0e20ccfe32

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #30710

### CODE REVIEW

**Comment by bilogic** [comment]
came from #30710, cheering for the quick fix :)

**Comment by silverwind** [comment]
`<div class="ui form">` is an abuse, they should be `<form class="ui form">` but I see the abuse is extensive, a quick search shows 35 matches.

**Review by silverwind — APPROVED** [review]
ok as a short-term fix. long-term we should fix those forms to be `<form>`.

**Comment by wxiaoguang** [comment]
> `<div class="ui form">` is an abuse, they should be `<form class="ui form">` but I see the abuse is extensive, a quick search shows 35 matches.

No, it isn't if you are familiar with Fomantic UI

<details>

image

</details>

**Comment by silverwind** [comment]
> > `<div class="ui form">` is an abuse, they should be `<form class="ui form">` but I see the abuse is extensive, a quick search shows 35 matches.
> 
> No, it isn't if you are familiar with Fomantic UI

I see, but it would still be desirable to change to `<form>`, right?

**Comment by wxiaoguang** [comment]
> I see, but it would still be desirable to change to `<form>`, right?

I think for most AJAX cases, it's better not to use `<form>`. Maybe we could leave this problem for the future.

**Comment by silverwind** [comment]
AJAX-submitted forms need to `preventDefault` the `submit` event, but yes, something for later.

**Review by lunny — APPROVED** [review]

**Pull request merged**
