### PR TITLE
Use path not filepath in routers/editor

### PR DESCRIPTION
**Pull request by zeripath**
The incorrect use of filepath instead of path means that
it is possible to cause a stackoverflow on Windows

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
🚀

**Comment by 6543** [comment]
@zeripath pleace backport ;)

**Comment by 59lx** [comment]
Hi, I am the problem's reporter. Could I cite this page to get a cve id?(For the sake of confirmation) :p

**Comment by lunny** [comment]
> Hi, I am the problem's reporter. Could I cite this page to get a cve id?(For the sake of confirmation) :p

Please.

**Pull request merged**
