### PR TITLE
Modernize docs/assets/js/search.js

### PR DESCRIPTION
**Pull request by silverwind**
- reformated file with eslint's --fix
- did some minor rule adjustments
- removed unneccesary console debug
- fixed a typo

### CODE REVIEW

**Comment by silverwind** [comment]
I know it's not ideal to lint this in the webpack step, but I plan to move it to a dedicated lint target soon.

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Note the code is not IE11 compatible, but I guess the JS features on the page are not that essential for its function.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Branch was messed up, fixed.

**Comment by silverwind** [comment]
rebased

**Comment by guillep2k** [comment]
PING LG-TM

**Pull request merged**
