### PR TITLE
Fix 500 when change user setting email to an exist email

### PR DESCRIPTION
**Pull request by lunny**
This PR fix a 500 when you change your email to an exist email address.

before

untitled

after 

untitled2

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by strk** [comment]
I like the checking *after* the error, will want to do it in other places too.
LGTM - does it need to be backported too or unique constraint was only added later ?

Any chance to add a test for this ?

**Comment by lunny** [comment]
Maybe you mean an integrated test, but I don't know how to do that.

**Comment by strk** [comment]
`vendor/gopkg.in/testfixtures.v2/README.md` might help

**Comment by andreynering** [comment]
LGTM

**Pull request merged**
