### PR TITLE
Upgrade vendor "git"

### PR DESCRIPTION
**Pull request by thibaultmeyer**
Upgrade "git" via the command `govendor`

### CODE REVIEW

**Comment by strk** [comment]
I've tried merging your PR locally and then issuing `govendor update`.
The result is more files changed, with vendor/vendor.json diff being:

```
diff --git a/vendor/vendor.json b/vendor/vendor.json
index 14feb1e..34c0384 100644
--- a/vendor/vendor.json
+++ b/vendor/vendor.json
@@ -3,10 +3,10 @@
        "ignore": "test",
        "package": [
                {
-                       "checksumSHA1": "X4WaxEtgFkM4VHg6TcNk2xkrqCI=",
+                       "checksumSHA1": "wpNJd6wl1MHYKjKiso1rzAcaMA0=",
                        "path": "code.gitea.io/git",
-                       "revision": "0807b517283977be34f0ff5510b21e676fc1527c",
-                       "revisionTime": "2016-11-13T14:20:52Z"
+                       "revision": "8e450d945dc3abda09b064617fdb31084b4e7447",
+                       "revisionTime": "2016-11-12T10:45:46Z"
                },
                {
                        "checksumSHA1": "/uhZZppDeb3Rbp3h8C0ALR3hdrA=",
```

Can you understand what does that mean ?

**Comment by strk** [comment]
FYI: `go get` works fine with git submodules starting with versione 1.6: https://github.com/golang/go/commit/761ac75a948e14fcd8472684effedf75f3fc316e

**Comment by thibaultmeyer** [comment]
@strk, I don't know why your command `govendor` use a too older commit hash (8e450d945d  who is ~30 commits back from last commit on master branch).

**Comment by strk** [comment]
Maybe my call is wrong, how do you invoke it ? I did `govendor update code.gitea.io/git`

**Comment by thibaultmeyer** [comment]
Maybe is me...  I have called `go vendor fetch code.gitea.io/git`

**Comment by strk** [comment]
Figured, `go vendor update code.gitea.io/git` took the code from my GOPATH, which was outdated.
Updating my local code and/or using `fetch` gives me a single change from your PR:

```
diff --git a/vendor/vendor.json b/vendor/vendor.json
index 14feb1e..59fe8fa 100644
--- a/vendor/vendor.json
+++ b/vendor/vendor.json
@@ -3,7 +3,7 @@
        "ignore": "test",
        "package": [
                {
-                       "checksumSHA1": "X4WaxEtgFkM4VHg6TcNk2xkrqCI=",
+                       "checksumSHA1": "NG9QAxoTz9rFH8054YQ3a9e9hs8=",
                        "path": "code.gitea.io/git",
                        "revision": "0807b517283977be34f0ff5510b21e676fc1527c",
                        "revisionTime": "2016-11-13T14:20:52Z"
```

Ideas about what that checksum is about ?

**Comment by strk** [comment]
govendor v1.0.3, go version go1.6.2 linux/amd64

**Comment by thibaultmeyer** [comment]
```
D:\Users\thiba\Documents>go version
go version go1.7.3 windows/amd64
```

```
D:\Users\thiba\Documents>govendor --version
v1.0.8
```

**Comment by strk** [comment]
Question: is there anything particular you need from the new version of the `git` module ?
(ie: it may be useful to reduce vendor/ changes)

It looks like we're not alone with the checksum issue: https://github.com/kardianos/govendor/issues/233#issuecomment-254037185

**Comment by thibaultmeyer** [comment]
Yes, to get the newly added function `GetCommitsInfoWithCustomConcurrency`

**Comment by strk** [comment]
Could you maybe include the vendor update as part of the PR making use of the new function ?

**Comment by strk** [comment]
@bkcsoft, @tboerger, @lunny what do you think about setting a policy for vendor/ updating ?

**Comment by thibaultmeyer** [comment]
if @bkcsoft, @tboerger, @lunny are OK with that, of course I can merge into one PR git module upgrade and new gitea feature.

**Comment by lunny** [comment]
Yes, we need a policy. Who can draft one?

**Comment by tboerger** [comment]
We can write a policy for it but for now LGTM

**Comment by strk** [comment]
Well, given I can confirm this PR does upgrade 'git' module to an existing upstream state, it also LGTM.
Figuring out `govendor`'s `checksumSHA1` can wait...

**Pull request merged**
