### PR TITLE
Refactor markdown attention render

### PR DESCRIPTION
**Pull request by wxiaoguang**
* Remove some deadcode
* Use 2-word name for CSS class names
* Remove "gt-*" rules for sanitizer

The UI doesn't change much.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
(I will propose some following improvements and tests after this gets merged)

**Review by lunny — APPROVED** [review]

**Comment by yardenshoham** [comment]
Switching tabs between `main` and this branch:
demo

I think it looks worse. We lose some padding/margins and the icons are out of place.

**Comment by wxiaoguang** [comment]
> Switching tabs between `main` and this branch:

Hmm, it is just a alignment trick, TBH the old `gt-vm (vertical-align: middle)` doesn't really align for most cases, and the best solution to align svg + text is "flex".

For this case, I think using the "margin" trick could make it good enough 68dc134a61397b7de78f06ed98d962ab4b389dac

image

**Review by yardenshoham — APPROVED** [review]
I still think the loss of spacing makes it look worse but it's not that big of a difference
demo

**Pull request merged**
