### PR TITLE
Fix config session missing data row & resolved #517

### LINKED ISSUE #517: Admin Config -> Session Info missing a data row
- Gitea version (or commit ref): 1.0.0 (6aacf4d)
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (no admin access)
  - [ ] Not relevant

## Description

There is a missing row of data under Admin Panel -> Configuration -> Session Configuration

image

It seems "session provider" or "provider config" is missing data, hence all rows are shifted up.

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by appleboy** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by tboerger** [comment]
Should that always be set and just get lost because of the app.ini bindata?

**Comment by lunny** [comment]
No. Some config depends other config, maybe empty or not.

**Comment by tboerger** [comment]
Backport to 1.0.1?

**Pull request merged**
