### PR TITLE
Add "mirror" field to repo API

### PR DESCRIPTION
**Pull request by andreynering**
Requires https://github.com/go-gitea/go-sdk/pull/41

### CODE REVIEW

**Comment by lunny** [comment]
build failed

**Comment by andreynering** [comment]
Failed because I still have to update vendor after https://github.com/go-gitea/go-sdk/pull/41 get merged

**Comment by lunny** [comment]
OK

**Comment by andreynering** [comment]
Vendor updated. This is done to be merged.

**Comment by lunny** [comment]
Since it's a minor change, maybe put it to 1.1. build failed.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
Please rebase master to fix lint error.

**Comment by andreynering** [comment]
Rebased and build fixed

**Comment by lunny** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
