### PR TITLE
Fix duplicate modals when clicking on "remove all" repository button

### PR DESCRIPTION
**Pull request by HesterG**
Under Team tab of an organization, click on "remove all" repositories button will trigger two modals. Because `data-modal-id` is not proerly added.

Before:

https://user-images.githubusercontent.com/17645053/231988545-ac690b86-e3fe-4bf5-81c6-5ef09302e849.mov

After:

https://user-images.githubusercontent.com/17645053/231989678-53be4f91-fdc9-4bc5-ba11-a08aa4548e37.mov

### CODE REVIEW

**Comment by wxiaoguang** [comment]
It doesn't look good to me .....

IMO the `Remove all` button should declare which model it uses explicitly.

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
please do this c99db35ee4e4f73e0067c23d2a1cd4c361017bfc

**Comment by HesterG** [comment]
> please do this [c99db35](https://github.com/go-gitea/gitea/commit/c99db35ee4e4f73e0067c23d2a1cd4c361017bfc)

I see, this makes more sense. Thanks.

**Comment by HesterG** [comment]
I think this PR is ready for review again.

**Review by lunny — APPROVED** [review]

**Pull request merged**
