### PR TITLE
Add LibreJS support

### LINKED ISSUE #1200: Add LibreJS support
This was added in Gogs on February 8 2017:
https://github.com/gogits/gogs/pull/4092

Would be good to have that PR ported to Gitea too.

### PR DESCRIPTION
**Pull request by strk**
See See https://www.gnu.org/software/librejs/

Closes #1200

### CODE REVIEW

**Comment by lunny** [comment]
Why we need to add this?

**Comment by strk** [comment]
We want (not need) this to properly advertise the license of the Javascript code we ask users to execute.
Some users don't want to run proprietary software so refuse to run Javascript code if it's not free software. There are browser plugins for that. You can read more about the rationale (the "Javascript trap") in the link placed in the original submission.

**Comment by strk** [comment]
Reporting the link here: https://www.gnu.org/philosophy/javascript-trap.html

**Comment by pgaskin** [comment]
This should be merged because it is not a big change, and it will make managing the licenses of different libraries easier.

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
