### PR TITLE
Add `DEFAULT_MIRROR_REPO_UNITS` and `DEFAULT_TEMPLATE_REPO_UNITS` options

### LINKED ISSUE #30350: Disable Action unit by default when mirroring a repo?
### Feature Description

For a mirror, the workflows are designed for the original repo, so something like secrets would not work or some unexpected things may happen? e.g. CD run twice when there's a runner with same label and no secret checks or something which would block the CD? ( original and mirror)

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Zettat123**
Resolve #30350

The action unit of mirrors and templates should be disabled by default. This PR adds `DEFAULT_MIRROR_REPO_UNITS` and `DEFAULT_TEMPLATE_REPO_UNITS` options to allow users to specify default units for mirrors and templates.

Thanks to @lng2020 for the [idea](https://github.com/go-gitea/gitea/issues/30350#issuecomment-2053942243)

### CODE REVIEW

**Comment by lunny** [comment]
If a template is a fork of another template repository, which default should it follow? Forked or template?

**Comment by yp05327** [comment]
Maybe this can be done one by one.

**Comment by Zettat123** [comment]
> If a template is a fork of another template repository, which default should it follow? Forked or template?

It should use `DEFAULT_FORK_REPO_UNITS` because a fork of a template will no longer be a template.

**Comment by Zettat123** [comment]
> Maybe this can be done one by one.

Since this PR is to add some new features rather than fix bugs, I think we can do this in one PR.

**Comment by Zettat123** [comment]
Docs: https://gitea.com/gitea/docs/pulls/91

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Please resolve the conflict

**Comment by Zettat123** [comment]
> Please resolve the conflict

Done

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
