### PR TITLE
Fix failing migration v67

### PR DESCRIPTION
**Pull request by KubqoA**
Fixes issue number #5848

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
The accessLevel function should also probably make its requests within the session too - although shouldn't deadlock.

There's a few other places in that file where X is used to perform queries within the transaction. I think we should probably just move those over too.

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
https://github.com/KubqoA/gitea/blob/044cd806b0be8642e9ff51fe4994a8d4012d0ae3/models/migrations/v67.go#L133

Needs to also be in the sess

**Comment by KubqoA** [comment]
@zeripath I changed line 133 and line 63, which contained `x.get` to `sess.get`

**Comment by KubqoA** [comment]
Changing line 63 broke the build, so I reverted the change on that line.

**Comment by zeripath** [comment]
@KubqoA I took the liberty of fixing the remaining deadlocks. Unfortunately I guess that means that I can't really LGTM this anymore...

**Comment by KubqoA** [comment]
Thanks, so now we need to wait for someone else to LGTM this?

**Comment by zeripath** [comment]
@KubqoA does it work?

**Comment by KubqoA** [comment]
How would I check if it works? I am running the docker version. Does it mean I need to create a custom Docker image and check it?

**Comment by zeripath** [comment]
OK I've just cherry-picked my migration test PR on top of this and it doesn't break the migration tests for v1.5.3 onwards so I'm going to say it works

**Review by zeripath — APPROVED** [review]

**Review by Bwko — APPROVED** [review]

**Comment by KubqoA** [comment]
You are an awesome person @zeripath, thanks to you, my Gitea instance is again up and running without any problems so far. I am very happy for the power of open-source project communities. Keep on going!

**Pull request merged**
