### PR TITLE
Fix one performance/correctness regression in #6478 found on Rails repository.

### PR DESCRIPTION
**Pull request by filipnavara**
Fix flaw in the commit history lookup that caused unnecessary traversal when the repository contains a lot of merge commits.

Also return the merge commit as the changed one if the file or directory was changed as part of the merge, eg. through conflict resolution. This matches behavior observed on GitHub.

Note that this doesn't fix the listing performance regression just yet. There's still problem when listing directories containing very old files. In that case the commit history has to be traversed all the way back to when the file was last modified.

### CODE REVIEW

**Comment by lunny** [comment]
The rails home page will load from 8s to 6.4s on my macOS after merge this PR.

**Comment by filipnavara** [comment]
@lunny Thanks for trying it. That corresponds with numbers from my local testing.

**Comment by filipnavara** [comment]
@lunny Can you also try the branch at https://github.com/filipnavara/gitea/tree/go-git-perf-fixes? It contains this PR + some optimizations to go-git. On my machine that's enough to push it to around ~4.5 seconds. There's still room for some improvement but I wanted to address the low-hanging fruit first.

For the root directory it's now similar to the performance I got before #6478. That may not necessarily be good enough since invoking `git` is super slow on Windows by comparison. For subdirectories it's significantly faster.

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
@filipnavara Do you want to update go-git recent version on this PR?

**Comment by filipnavara** [comment]
@lunny not worth it at the moment. I have some go-git PR waiting in the pipeline that have to be merged first.

**Review by lunny — APPROVED** [review]

**Pull request merged**
