### PR TITLE
Fix google logo in security page

### PR DESCRIPTION
**Pull request by Sirherobrine23**
Fix google logo in user security page: #28701

Before

before user security page

after

user security page

### CODE REVIEW

**Comment by lafriks** [comment]
SVG file needs to be formatted

**Review by lafriks — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
> SVG file needs to be formatted

You mean pretty-printed? I'd classify that as optional for  the file in `web_src`.

**Comment by Sirherobrine23** [comment]
> SVG file needs to be formatted

I've never used SVG, I wanted to understand a little, I got the base from Google fonts file and added class to file, and after changing SVG to this pull, google logo fixed in settings page

**Comment by lafriks** [comment]
> > SVG file needs to be formatted
> 
> You mean pretty-printed? I'd classify that as optional for the file in `web_src`.

no it was before force push

**Comment by Sirherobrine23** [comment]
Oh, ok, thanks to merge

**Pull request merged**
