### PR TITLE
Move all docker stuff under docker/ directory

### PR DESCRIPTION
**Pull request by strk**
Makes the link in the home template more meaningful

### CODE REVIEW

**Review by appleboy — CHANGES_REQUESTED** [review]
You need to update the drone config.

**Comment by tboerger** [comment]
That breaks the docker build pipeline.

**Comment by sapk** [comment]
But since official alpine imge is now multi-arch (armhf, x64) we coud drop the rpi docker file.

**Comment by strk** [comment]
Uhm, I don't see in drone config where path to Dockerfile is given

**Comment by sapk** [comment]
Add why move docker/ → docker/root/docker ? 
futhermore the `COPY root /` is not good since it should be `COPY root/docker /` with this path change.

I am not a fan of this PR. I would rather prefer to use new docker solution multi-arch base image (even officials are now multi-arch for most version) to have only one Dockerfile for all platform. 
Edit : Also multi-stage Dockerfile could remove the step of building the binary in another image and define it in the Dockerfile.

**Comment by strk** [comment]
On Sun, Oct 01, 2017 at 11:05:27AM +0000, Antoine GIRARD wrote:
> Add why move docker/ → docker/root/docker ? 

It was a mistake, now fixed.

> I am not a fan of this PR. I would rather prefer to use new docker solution multi-arch base image (even officials are now multi-arch for most version) to have only one Dockerfile for all platform. 

I didn't change the multi-arch thing, just wanted to put all
docker-related thing under docker/ dir. As it is linked by README

**Comment by sapk** [comment]
@strk No problem, I just say that we could only need one Dockerfile if the goal is cleaning. And maybe faltly, but most of the time, having a Dockerfile at repo root indicate that a docker image exist.

Now, PR looks good in itself but from my point of view I would keep Dockerfile at the repo root.

**Comment by strk** [comment]
If Dockerfile is kept at the root, the home.tmpl file should be
changed NOT to link to docker/ tree to find more info about
installing from Docker (as the Dockerfile would not be there).

**Comment by sapk** [comment]
Is this PR still relevant ? Only the Dockerfile is now at the root maybe we can close this PR if you are ok with that @strk ?

**Comment by techknowlogick** [comment]
Closing PR per @sapk's comment.

**Pull request closed without merging**
