### PR TITLE
Improve testing and try to fix MySQL hanging

### PR DESCRIPTION
**Pull request by wxiaoguang**
It's strange that TestLinguist hangs a lot with MySQL (and only MySQL). Update: due to MySQL tests have different indexer&queue behaviors.

Now, by some CI fine tunes (`run tests`), SQLite & MSSQL could complete in about 12~13 minutes (before > 14), MySQL could complete in 18 minutes (before: about 23 or even > 30)

Major changes:

1. use tmpfs for MySQL storage
1. run `make test-mysql` instead of `make integration-test-coverage` because the code coverage is not really used at the moment.
1. refactor testlogger to make it more reliable and be able to report stuck stacktrace
1. do not requeue failed items when a queue is being flushed (failed items would keep failing and make flush uncompleted)
1. reduce the file sizes for testing
1. use math ChaCha8 random data instead of crypot/rand (for testing purpose only)
1. no need to `DeleteRepository` in `TestLinguist`
1. other related refactoring to make code easier to maintain

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
By some CI fine tunes, MSSQL could complete in 13 minutes, MySQL could complete in 18 minutes (before: about 32 or even > 30)

**Comment by bohde** [comment]
Am I right that the major changes are as follows?

* Use ChaCha8 for generating random test files instead of a cryptographic generator, saving 2 minutes per integration tests
* Adjust MySQL to run on a tmpfs, saving 4 minutes per mysql integration test
* Don't re-enqueue failed jobs when flushing, which makes tests more reliable

**Review by bohde — APPROVED** [review]

**Comment by bohde** [comment]
> Exactly, these are the major changes, and by the way remove the "deleting repo" code in TestLinguist, it also saves a little time.
> 
> And fine-tune the testlogger to make it output correct durations, and report the stack if a test gets stuck.

Thanks for the confirmation!

**Comment by wxiaoguang** [comment]
> Thanks for the confirmation!

Yup, a lot of things are mixed in one PR .... (I haven't thought that it would become more and more complex .....)

Update the description of the PR, hopefully everything is listed there.

**Pull request merged**
