### PR TITLE
Use random bytes to generate access token

### PR DESCRIPTION
**Pull request by wolfogre**
Use `hex.EncodeToString(util.CryptoRandomBytes(20))` to replace `base.EncodeSha1(gouuid.New().String())`.

### CODE REVIEW

**Comment by wolfogre** [comment]
> Is the output URL-safe? It should be. If not, use `util.CryptoRandomString`.

1. Is the output URL-safe?
  a. Yes, the output is a hexadecimal encoding of bytes.
2. Why not `util.CryptoRandomString`?
  a. Try to be in the same format of the old output(`[0-9a-f]+`), `util.CryptoRandomString` can't do that. 

More context: https://github.com/go-gitea/gitea/pull/21937#discussion_r1033089470

**Review by silverwind — APPROVED** [review]
Output is same length as well, LGTM.

**Review by a1012112796 — APPROVED** [review]

**Comment by wolfogre** [comment]
@Gusted I can't find you in the search box of reviewers, but I wish you could review it. :)

**Comment by Gusted** [comment]
Yeah this looks good to me, never occurred to me that this code already existed in Gitea. 

I'm [not a maintainer](https://pad.gusted.xyz/s/PoIQp8OfL) anymore, that's why you don't find me in the reviewers box.

**Review by delvh — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Pull request merged**
