### PR TITLE
European Portuguese translation

### PR DESCRIPTION
**Pull request by emansije**
This PR includes the modifications necessary to make use of the European Portuguese translation, hopefully still in time for the 1.12 release.

I'm not sure if there is a specific order in which the entries should be placed, so I chose to put it right after the Brazilian Portuguese. The exception is in the file `config/config.yaml` because of the `weight` parameter, since I didn't know the consequences of altering that order.

### CODE REVIEW

**Comment by lunny** [comment]
Please go to https://crowdin.com/project/gitea .

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Comment by zeripath** [comment]
please send backport 

Simple commands below:

```go
git checkout origin/release/v1.12 -b backport-11568
git cherry-pick a39557f
# Optional: git commit --amend  to add Backport #11568 as the first line of the long commit form
git push fork backport-11568
```

**Comment by emansije** [comment]
> please send backport
> 
> Simple commands below:
> 
> ```bash
> git checkout origin/release/v1.12 -b backport-11568
> git cherry-pick a39557f
> ```

When I submitted the `cherry-pick` command I got:
```bash
fatal: bad revision 'a39557f'
```
Any idea why?

**Comment by zeripath** [comment]
Did you pull the latest changes before attempting the cherry pick?

**Comment by emansije** [comment]
Oops! Sorry! I forgot to fetch upstream.

**Pull request merged**
