### PR TITLE
Replace `issues_model.GetReviewersByIssueID()` with more generic `issues_model.GetReviews()`

### PR DESCRIPTION
**Pull request by 6543**
Replace `issues_model.GetReviewersByIssueID()` with more generic `issues_model.GetReviews()`

### CODE REVIEW

**Comment by lunny** [comment]
Looks like this is a bug fix.

**Comment by 6543** [comment]
well if we like to backport it ... I could not do refactoring ... but If you think it's worth backporting I'll work around it for the backport

**Comment by 6543** [comment]
(test pass localy now ;) -wait for ci ...)

**Comment by Fogapod** [comment]
is this supposed to resolve https://github.com/go-gitea/gitea/issues/16536 ?

**Comment by 6543** [comment]
> is this supposed to resolve #16536 ?

no

**Comment by 6543** [comment]
-> #20197

**Comment by wxiaoguang** [comment]
Stale and conflicted, what's the purpose of this PR and what's the status? 🙏

**Comment by wxiaoguang** [comment]
Kindly second ping ~~

**Comment by wxiaoguang** [comment]
Maybe this PR could be closed? Feel free to complete the description and reopen.

**Pull request closed without merging**
