### PR TITLE
Get rid of bin folder within makefile, enabled TiDB

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
I have added more commits which drops multiple build tags to avoid checksum missmatches for the drone config because all of them need changes on the drone configuration.

**Comment by strk** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by lunny** [comment]
`go get github.com/pingcap/tidb` is not work, you have to call `make` in tidb root dir.

**Comment by tboerger** [comment]
But tidb have built fine with the vendor libs, and drone also built the tidb support

**Pull request merged**
