### PR TITLE
Fix markdown rendering

### PR DESCRIPTION
**Pull request by Morlinest**
Fix rendering bug caused by PR #186.

Simplify nested "if".

### CODE REVIEW

**Comment by strk** [comment]
Maybe you should wait for #1527 before touching this file. \cc @lunny

**Comment by lunny** [comment]
Could you give an example of this bug on https://try.gitea.io?

**Comment by lunny** [comment]
@strk I don't think so.

**Comment by Morlinest** [comment]
Should fix #1273, #1265.

**Comment by Morlinest** [comment]
@lunny https://try.gitea.io/morli/test
Before:
image

After:
image

**Comment by andrew-boyarshin** [comment]
Yeah, looks like an issue I've missed. Thanks, @Morlinest!
It would also be great to have tests written for this case.

**Comment by lunny** [comment]
LGTM

**Review by ethantkoenig — APPROVED** [review]

**Comment by ethantkoenig** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
