### PR TITLE
Update JS dependencies

### PR DESCRIPTION
**Pull request by silverwind**
- Update all JS dependencies
- Regenerate SVGs
- Remove unused postcss dependency
- Remove removed webpack option

### CODE REVIEW

**Comment by 6543** [comment]
`make frontend`

will change package.json & package-lock.json

**Comment by silverwind** [comment]
@6543 try again

**Comment by silverwind** [comment]
Bumped Node.js to 16 on CI which ships npm v7, eliminating the lockfile warning.

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
Drone build seems bugged or something, should be nothing related to this PR.

**Review by 6543 — APPROVED** [review]

**Comment by techknowlogick** [comment]
@silverwind `node:16` isn't an image (at least I haven't been able to do a docker pull locally or find it on the tags tab of https://hub.docker.com/_/node)

**Comment by silverwind** [comment]
Ah, right. It usually takes them a few days to release new major version images.

**Comment by silverwind** [comment]
`postcss` added again as it is a peer dependency of `cssnano` which I seem to always forget. Also opened https://github.com/cssnano/cssnano/pull/1056 to fix it on their side. Ultimately it does not matter with npm v7 because it will always install `peerDependencies` and it even worked in v6 because we have like 20 instances of postcss already in the dependency tree.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
