### PR TITLE
Left-Align text in Unicode warning boxes

### PR DESCRIPTION
**Pull request by silverwind**
Wrapped text is more readable when left-aligned.

Before:
Screen Shot 2022-01-19 at 17 44 05
Screen Shot 2022-01-19 at 17 44 16

After:
Screen Shot 2022-01-19 at 17 44 59
Screen Shot 2022-01-19 at 17 44 51

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by delvh** [comment]
Are you sure that it is more readable?
I disagree.
I like the current implementation more.

**Comment by silverwind** [comment]
It was initially raised in https://github.com/go-gitea/gitea/pull/17562#issuecomment-970811585. I guess two-line content is kind-of okay, but any more lines and it gets harder to read because lines start at different x-positions.

**Comment by zeripath** [comment]
Yup codeberg specifically asked for this. 

I put it in to the PR but it looks like it was removed or merged away.

I think we have to do this.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I think codeberg wanted other messages to be left aligned too - I think originally my PR also covered those too.

**Review by Gusted — APPROVED** [review]

**Pull request merged**
