### PR TITLE
Show tokens in prominent modal

### LINKED ISSUE #13600: [discussion] scratch token UX
Its easy to overlook the scratch token if presented after enrolling 2FA. I find it to subtle presented and easy to miss.

A modal/popover or something more “in ya face” might be better to not forget to store that key, since its important. Even the opportunity to block users to proceed without having at least stored it to the clipboard, might be an option here.

### PR DESCRIPTION
**Pull request by noerw**
..to avoid them being accidentally overlooked:

- app access tokens
- scratch token after enabling 2FA

demo

fixes #13600

I left the alerts showing the token in for accessibility, as the new approach does not work without JS.

I also renamed "scratch token" to "recovery token" throughout the UI, because this term converys much more meaning and is more common.

### Help Wanted:
I was unable to pass the token to next request after the redirect to display the modal, so i switched redirects to render the page instead. This is hacky, but I didn't find a way to use ctx.Flash() in a non-alert / more generic way..

### CODE REVIEW

**Comment by silverwind** [comment]
Can you use a regular, non-basic modal? I hate these basic modals 😉

**Comment by noerw** [comment]
@silverwind i actually like them ;) but done anyway:

grafik

**Comment by lunny** [comment]
CI failed is related.

**Comment by noerw** [comment]
@lunny as mentioned in PR header:

I was unable to pass the token to next request after the redirect to display the modal, so i switched redirects to render the page instead. This is hacky, but I didn't find a way to use ctx.Flash() in a non-alert / more generic way..

So any inputs are welcome :)

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
sorry I'm late to the party and maybe if this is not the best place to discuss, please, tell me.. but would it be possible to maybe *not* use a modal and still make the token more prominent on the page? i.e.
it's just that I personally don't find modals neither practical nor appealing, rather distracting (just one opinion).
there surely is another way to gently grab users attention.

**Pull request closed without merging**
