### PR TITLE
if a repo does not exist, show a 404 not a 500

### LINKED ISSUE #5892: Pull request overview page getting 404 (?repo=)
- Gitea version (or commit ref): 1.7.0 (3fa49f3)
- Operating system: Docker (Ubuntu Host)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
When I go to ```mygitea.com/pulls?type=all&repo=9&sort=&state=open``` I get a white page in Safari, Chrome simply shows the Chrome 404 page. When I change the ?repo= to be 0 it works and shows the correct repo. All other repos work fine. When I go to the Pull-Request page in the top menu and I select this one repo that is in my namespace I get this crazy error, but all other repos work fine. 

No custom 404 Gitea page is shown. 
## Log
```
gitea-mailcow_1      | [Macaron] 2019-01-29 20:01:32: Completed GET /pulls?type=all&repo=9&sort=&state=open 404 Not Found in 37.341391ms
gitea-mailcow_1      | [Macaron] 2019-01-29 20:01:32: Started GET /serviceworker.js for 192.168.32.4
gitea-mailcow_1      | [Macaron] 2019-01-29 20:01:32: Completed GET /serviceworker.js 200 OK in 4.827606ms
```

## Screenshots
ohne titel

### PR DESCRIPTION
**Pull request by adelowo**
Fixes https://github.com/go-gitea/gitea/issues/5892

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Is that really the OPs issue? Great catch!

**Comment by adelowo** [comment]
I believe so

> When I change the ?repo= to be 0 it works and shows the correct repo. All other repos work fine.


But then again maybe we can wait till he replies to https://github.com/go-gitea/gitea/issues/5892#issuecomment-458924495. But I sincerely believe this is the fix.

**Comment by zeripath** [comment]
It's certainly a fix!

**Comment by adelowo** [comment]
Can someone with the correct rights restart the build?

The failure seem unrelated as it passed at https://drone.gitea.io/go-gitea/gitea/5598 

> Failed to restart your build

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
