### PR TITLE
wiki - page revisions list 

### LINKED ISSUE #7: display page revisions on wiki
Hi guys,

Wiki on Gogs is very fine, I liked a lot, but I think that is good idea to be possible see other revisions from page as a page history.

What you think?

Reference: https://github.com/gogits/gogs/issues/2991

### PR DESCRIPTION
**Pull request by Cherrg**
add wiki page revision list

- list who, how often and when a wiki page was changed

fix #7

Signed-off-by: Michael Gnehr <michael@gnehr.de>

# images

|Wiki Button|Desktop|Mobile|
|--|--|--|
| grafik  | grafik  | grafik  |

### CODE REVIEW

**Comment by lunny** [comment]
I think it's better to extract `renderWikiPage` to 3 functions.

**Comment by Cherrg** [comment]
i will try this. The important part of renderWikiPage is the check if page exists and if this is the case to get the treeElement. On #7225 this will be extended to handle multiple directories;

I will try to refactor a litte and see if i can split it up.

**Comment by Cherrg** [comment]
I think the original author decided to use a function with flags to not have replicated code.
3331335 only does some clean up, so there is still one function.

Next commit (952f40d) will split them up. I think one function is better. Feel free to compare them, and may remove last commit.

**Comment by Cherrg** [comment]
build errors should be gone

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
