### PR TITLE
WIP: Add OAuth2 Application Settings UI

### PR DESCRIPTION
**Pull request by jonasfranz**
This PR adds the UI for managing and creating OAuth2 applications.

Blocked by #5378 

## Screenshots
Hint: The application type option will be removed in the future.

screenshot_2019-01-05 gitea git with a cup of tea
screenshot_2019-01-05 gitea git with a cup of tea 1

### CODE REVIEW

**Comment by techknowlogick** [comment]
@jonasfranz would you be able to provide screenshots?

**Comment by jonasfranz** [comment]
@techknowlogick Added some screenshots

**Comment by filipnavara** [comment]
When trying to remove an existing app I get error 'Type cannot be empty.'. The log says
`2019/01/08 19:00:32 [...s/context/context.go:147 NotFoundOrServerError()] [E] GetRepositoryByOwnerAndName: repository does not exist [id: 0, uid: 0, owner_name: user, name: settings]`

**Comment by jonasfranz** [comment]
#5378 will include these changes

**Pull request closed without merging**
