### PR TITLE
[Docs] Cloud Backup Providers

### PR DESCRIPTION
**Pull request by bagasme**
As title, Gitea dump files can be uploaded to Arq, Carbonite, CrashPlan, or alikes.

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
I'm not sure if this is needed as we expect that users would do something with the zip once they have generated it.

**Comment by bagasme** [comment]
@techknowlogick including uploading dump zips to cloud backups?

If this is the case, I will close this PR as it is unnecessary.

**Comment by lunny** [comment]
How to store the dump file should be a user behaviour I don't think we need docs for that.

**Comment by bagasme** [comment]
Close as @lunny note.

**Pull request closed without merging**
