### PR TITLE
Removable media support

### PR DESCRIPTION
**Pull request by EndrII**
# Note
The snap version of the gitia are most convenient way to quickly install the gitea service. But snap version can not get accses to removable devices. For example mounted external drives.  So it is looks as a bug, so i create this PR to v1.14 branch.

# Descritpion
Added support removable media for snap version of gitia.
For get more info about removable media interface see the snapcraft [documentation](https://snapcraft.io/docs/removable-media-interface)

### CODE REVIEW

**Comment by 6543** [comment]
@EndrII could you target `main` first, if it got merged it will be backported to 1.14

**Comment by EndrII** [comment]
> @EndrII could you target `main` first, if it got merged it will be backported to 1.14

okay, no problem

**Comment by EndrII** [comment]
ups

**Comment by EndrII** [comment]
i reopen this PR for main branch

**Comment by EndrII** [comment]
See #16136 PR

**Pull request closed without merging**
