### PR TITLE
IsBranchExist: return false if provided name is empty

### LINKED ISSUE #8482: 500 Error On Release Page
- Gitea version (or commit ref): 1.9.3
- Git version: 2.23.0
- Operating system: Freebsd
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/carc1n0gen/85b5b52130ea7be722eb85da202be158

## Description

I created a repo on my gitea instance, added as a remote on an existing repo, and pushed.  That was fine.  I then noticed the releases page was empty since I hadn't pushed the tags.  So I pushed the tags.  Now the releases page yields a 500 error page.

The repo is public, so here it is: https://gitea.carsonevans.ca/carson/quickpaste/releases

### PR DESCRIPTION
**Pull request by zeripath**
There appears to unfortunately be a slight difference between `git show-ref --verify -- "refs/heads/"name` used in `git.IsBranchExists()` and `repo.gogitRepo.Reference(plumbing.ReferenceName(BranchPrefix+name)` used in `(*git.Repo) IsBranchExists()` . 

In that the first will return an error if the name is empty however, the second appears not to return an error. 

This PR adds a simple check to ensure that empty names return false and also checks that the eventual reference returned is not an InvalidReference.

Fixes #8482

### CODE REVIEW

**Comment by zeripath** [comment]
hmm... this might not be actually needed and could be a particular issue with the freebsd port.

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by lafriks** [comment]
Please backport

**Comment by 6543** [comment]
in a minit @lafriks

**Comment by 6543** [comment]
@zeripath which one was faster ;)

**Comment by 6543** [comment]
-> I'll close mine

**Comment by zeripath** [comment]
Hehe

**Pull request merged**
