### PR TITLE
Fix delete user failed on sqlite

### LINKED ISSUE #1281: sqlite db  delete user error
admin delete log:
2017/03/16 15:23:00 [...uters/admin/users.go:257 DeleteUser()] [E] DeleteUser: ExternalLoginUser: database table is locked

user delete self:
2017/03/16 15:25:15 [...ters/user/setting.go:707 SettingsDelete()] [E] DeleteUser: ExternalLoginUser: database table is locked

### PR DESCRIPTION
**Pull request by lunny**
fix #1281, @zileyuan and @crocket please confirm this PR will resolve your problem.

### CODE REVIEW

**Comment by crocket** [comment]
How do I test this?
The instructions on https://docs.gitea.io/en-us/install-from-source are not applicable to this.

**Comment by strk** [comment]
LGTM

**Comment by lunny** [comment]
fix #1145

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
let L-G-T-M work

**Pull request merged**
