### PR TITLE
Set `ref` to fully-formed of the tag when trigger event is `release`

### LINKED ISSUE #23943: Can't get tagname when workflow trigger event is `release`
### Description

This issue is report from [gitea.com](https://gitea.com/gitea/act_runner/issues/93).
` docker/metadata-action ` cannot get the tag name of relase when the trigger event is `release`.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by sillyguodong**
Fix #23943
When trigger event is `release`, ref should be like `refs/tags/<tag_name>` instead of `CommitID`

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by delvh** [comment]
1. Isn't changing the format of `ref_name` breaking?
2. If yes, this change shouldn't be backported.
3. Isn't this going to cause future problems where we cannot distinguish between what is intended for a tag, and what is intended for a branch?

**Comment by silverwind** [comment]
> Isn't changing the format of ref_name breaking

Tend to agree, I'd say it is breaking as some workflows may rely on the "broken" behaviour.

**Comment by wolfogre** [comment]
I have a different opinion. It was previously incorrect, so what it broke was a mistake. I would say it's not breaking and should be backported.

See the comment.

> The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by push, this is the branch or tag ref that was pushed. For workflows triggered by pull_request, this is the pull request merge branch. **For workflows triggered by release, this is the release tag created.** For other triggers, this is the branch or tag ref that triggered the workflow run. This is only set if a branch or tag is available for the event type. The ref given is fully-formed, meaning that for branches the format is refs/heads/<branch_name>, for pull requests it is refs/pull/<pr_number>/merge, and for tags it is refs/tags/<tag_name>. For example, refs/heads/feature-branch-1.

https://github.com/go-gitea/gitea/blob/ed7245f997e980fe5daa9e0d298539bc5e62ac59/routers/api/actions/runner/utils.go#L100

It follows https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

**Review by wolfogre — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖

**Comment by jolheiser** [comment]
🎺 🤖

**Pull request merged**
