### PR TITLE
Upgrade golangci-lint to 1.24.0

### PR DESCRIPTION
**Pull request by zeripath**
* upgrade golangci-lint to 1.24.0 to allow go 1.14 compatibility
* fix golangci-lint errors
* make `make golangci-lint` work when out of go-path

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
I finaly be able to run it localy again - thanks!

**Comment by silverwind** [comment]
Note that this will not upgrade locally installed `golangci-lint` because it only checks for existance of any binary. I guess we have that kind of issue on all globally installed binaries.

**Comment by zeripath** [comment]
yeah

**Comment by zeripath** [comment]
This is where coolaj plan of vendoring/go.modding the build dependencies would be helpful

**Comment by jolheiser** [comment]
Or a Docker image with the tools injected into the container. (Though that wouldn't help local testing.)

**Comment by techknowlogick** [comment]
> I guess we have that kind of issue on all globally installed binaries.

There was previously a suggestion of vendoring tools such as this via go modules, perhaps that could be revisited (although if we ever get rid of vendored go, then at least keep it in go modules file)

**Comment by silverwind** [comment]
Yes, something with go modules would be ideal because global installs can conflict with other projects that may require different versions of those tools.

**Comment by lunny** [comment]
We should make `GO111MODUlE=on` as default on makefile.

**Comment by 6543** [comment]
It's in my .bashrc  :D

**Pull request merged**
