### PR TITLE
Add repository setting to enable/disable health checks

### PR DESCRIPTION
**Pull request by aswild**
New Feature:
  * Repository struct field for IsFsckEnabled (default true of course)
  * Admin Settings section on repo options page, accessible only by
    admin users

Possible Enhancements:
  * There's no way to force running health checks on all repos
    regardless of their IsFsckEnabled setting. This would be useful if
    there were an admin API or dashboard button to run fsck immediately.

Signed-off-by: Allen Wild <allenwild93@gmail.com>

### CODE REVIEW

**Comment by aswild** [comment]
Rationale:
* Issue #1712 requests an option to disable health checks, but I made an option to enable them to avoid  confusing inverse logic
* By default, health checks are enabled for all repos, including mirrors
  * This keeps behavior consistent with older version
  * Git fsck verifies the integrity of the files on disk, just because a repo is a mirror doesn't mean it couldn't become corrupted
* I added the new admin settings as a section on the Settings->Options tab rather than adding a whole new tab just for one checkbox

Testing:
* The migration works on sqlite3, I don't have a MySQL or PostgreSQL setup to test on
* I used BurpSuite to alter a POST request to try to set the admin option as a non-admin user. It returned 403 as expected

**Comment by lafriks** [comment]
Why it must be only server admin option?

**Comment by aswild** [comment]
Enabling, configuring, running, and viewing the results of fsck are things that only admins have access to (via app.ini and the admin panel), so it seemed to make sense that normal users don't need this setting exposed. 

The main reason to disable fsck is for large repos which take too long to check, but only an admin would know when that's the case. If users could toggle that setting, they a) wouldn't be able to see any actual result and b) might annoy admins who intentionally it set a particular way.

If this is the wrong view, I can remove the admin-only restriction.

**Comment by lafriks** [comment]
@aswild that makes sense :)

**Review by lafriks — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Pull request merged**
