### PR TITLE
Pack web_src/js/draw.js to public/js/index.js

### PR DESCRIPTION
**Pull request by lunny**
Currently all javascript functions are stored on `web_src/js/index.js`, it's difficult to maintain. So we should split it according the logic or pages. This PR makes it possible. As the first js file, I packed `web_src/js/draw.js` to `public/js/index.js`

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
I think it's better to have a single entry point and import/require the files from there, but this can work as a interim solution.

**Comment by lunny** [comment]
@silverwind yes, I think so.

**Comment by zeripath** [comment]
Why not do the drop-down one at the same time?

**Comment by lunny** [comment]
@zeripath `semantic.dropdown.custom.js` is 144405 bytes and after pack, index.js maybe increased from 58KB to over 100KB. I think maybe we should split the js to serval files? That needs more work.

**Review by zeripath — APPROVED** [review]

**Comment by guillep2k** [comment]
> 
> 
> @zeripath `semantic.dropdown.custom.js` is 144405 bytes and after pack, index.js maybe increased from 58KB to over 100KB. I think maybe we should split the js to serval files? That needs more work.

@lunny unless we're removing sdc from some pages (I know that's what you're aiming for, anyway), having them in the same file is usually faster than two files when the ping to the server is high, becose it reduces roundtrip delays (except for heavily configured HTTP/2 sites, I think).

**Comment by lunny** [comment]
@guillep2k I don't think so. I think download a 200KB's javascript is best prictice. I think we should split javascript serval files.

**Comment by silverwind** [comment]
It depends on use case. Modules that are always required should be in the main bundle. Other occasionally useful things can be lazy-loaded, ideally using dynamic imports (https://webpack.js.org/guides/code-splitting/#dynamic-imports).

200kB JS is not much really. I have apps where I serve 3 MB bundles and it still loads reasonably fast with compression.

**Comment by silverwind** [comment]
To correct my previous comment a bit: I was thinking in the context of SPA's where you pay the cost of the bundle size only once on initial load while in a non-SPA, you pay it on every page load where costs add up. It makes sense to be careful on what we put in the main bundle.

**Pull request merged**
