### PR TITLE
fix missed RenderLabel change in card template

### LINKED ISSUE #29770: Project boards fail to render after newest docker nightly update
### Description

Below is copied verbatim from the top of the page when trying to view any of my Projects:

```
An error occurred:

Render failed, failed to render template: repo/projects/view, error: template error: builtin(bindata):repo/issue/card:64:75 : executing "repo/issue/card" at <RenderLabel>: wrong number of args for RenderLabel: want 3 got 2
----------------------------------------------------------------------
			<a target="_blank" href="{{$.Issue.Repo.Link}}/issues?labels={{.ID}}">{{RenderLabel ctx .}}</a>
			                                                                        ^
----------------------------------------------------------------------
Gitea Version: 1.22.0+dev-1019-g85c59d6c2
```

My URL is `https://<host>/<user>/<repo>/projects/1`.

### Gitea Version

1.22.0+dev-1019-g85c59d6c2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

- Official docker container
- nightly

### Database

None

### PR DESCRIPTION
**Pull request by 6543**
regression of #29680
close  #29770

PS: it would be nice to have a linter that is able to check template helpers ...

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
It seems it's impossible. Maybe you should add those links to `links_test.go` in integrations to test whether the template have been broken.

**Comment by wxiaoguang** [comment]
> PS: it would be nice to have a linter that is able to check template helpers ...

I have a plan to refactor these "Render" functions by our ctx function, I just haven't find a good timing.

(Other `ctx` refactorings like `ctx.AvatarUtils` is pretty stable, no regression anymore)

**Comment by silverwind** [comment]
> PS: it would be nice to have a linter that is able to check template helpers ...

No such linter exists to my knowledge. `djlint` does not even look into go files. Would likely need to write one ourselves.

**Comment by wxiaoguang** [comment]
> > PS: it would be nice to have a linter that is able to check template helpers ...
> 
> No such linter exists to my knowledge. `djlint` does not even look into go files. Would likely need to write one ourselves.

The real problem is that Golang template is a pure dynamic system, many calls and types can't be known before execution.

**Comment by silverwind** [comment]
> The real problem is that Golang template is a pure dynamic system, many calls and types can't be known before execution.

Yeah it would never be fully lintable, but at least basic stuff like argument count for functions without vararg shouldn't too hard to lint for I guess.

**Review by denyskon — APPROVED** [review]

**Pull request merged**
