### PR TITLE
disable image check for non binary files

### PR DESCRIPTION
**Pull request by Loutro**
The check for image on each file is really heavy, and i don't think it's mandatory for non binary files.
So i just propose to skip this IsImage check for non binary file.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
SVG files are not binary but image files.

**Comment by Loutro** [comment]
> SVG files are not binary but image files.

I tested for this, but in my case it was not detected as image file.
So it's not binary and the image check returned false.

Is there a test case with a svg file detected a image?

**Comment by Loutro** [comment]
to be clear, what is the good option:
- should the svg be detected as an image, so there is a bug here?
- the svg doesn't need to be detected as an image, so i can bypass it with the non binary test i introduced.

**Comment by KN4CK3R** [comment]
Have a look at #14867

**Comment by Loutro** [comment]
ok perfect, i'm going to close this PR and try to find an other approach.

**Pull request closed without merging**
