### PR TITLE
Recolor dark theme to blue shade

### LINKED ISSUE #27097: New dark theme and default theme rename
### Feature Description

I think generally we agree that `arc-green` is a rather unconventional color theme and I don't like it very much. The idea is to make a new default dark theme with light blue primary color and almost-greyscale blue overall color. So I propose:

- Rename `gitea` theme to `gitea-light` and migrate existing users
- Rename and update `arc-green` theme to `gitea-dark` and migrate existing users

The colors I'd be aiming for are greyscale with a very subtle blue tint. Very similar to [this blender theme](https://projects.blender.org/infrastructure/gitea-custom/src/branch/main/public/css/theme-bthree-dark.css) and to Discord's dark theme, but not as blue as GitHub's dark theme.

### Screenshots

image

### PR DESCRIPTION
**Pull request by silverwind**
Now uses the same primary color as light theme. The secondary colors are shifted towards a slightly blue shade. Could maybe desaturate a bit more, but overall I think I'm happy with it.

Fixes: https://github.com/go-gitea/gitea/issues/27097

Screenshot 2024-02-27 at 22 21 46
image

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by denyskon** [comment]
Could we maybe delay this PR a bit for other maintainers to be able to take a look and say their opinion if something still is to be improved here? :) Myself included, as I don't have the time currently 😆

**Review by jolheiser — CHANGES_REQUESTED** [review]
Just blocking so others have time to take a peek. Feel free to dismiss as needed. :slightly_smiling_face:

**Comment by delvh** [comment]
To me, it sounded like this is only part one of the new theme.
Or did I misunderstand something, @silverwind?

**Comment by silverwind** [comment]
No this is all. A recolor from green to blue primary color with adjustment of the secondary colors. Right now primary color matches light theme and while it works, I could see it being darkened slightly as well.

**Comment by silverwind** [comment]
Will give this a few more minor adjustments like making it slightly darker and desaturating a tiny bit more.

**Review by denyskon — APPROVED** [review]

**Comment by silverwind** [comment]
Ready again. I desaturated secondary colors by 40%, but it's barely noticeable in the screenshots above which are updated. I then tried to darken these colors by 6%, but the result ended up seemingly too dark.

**Comment by silverwind** [comment]
Actually there are some small copy paste errors and I will try one more desaturate, WIP shortly.

**Comment by silverwind** [comment]
Reduced by another 30% in saturation, now it looks almost like Discord in terms of secondary color saturation. I like it.

**Comment by denyskon** [comment]
I'm not sure about the contrast of those count labels - everything else looks great.

**Comment by silverwind** [comment]
> I'm not sure about the contrast of those count labels - everything else looks great.



> I'm not sure about the contrast of those count labels - everything else looks great.
> 
> 

Still passes AAA contrast testing:

image

**Comment by silverwind** [comment]
That said, I guess making the text one notch brighter wouldn't hurt, I guess.

**Comment by silverwind** [comment]
Tweaked those labels a bit, brighter background and text. 7.63:1 text contrast ratio currently:

image

**Review by denyskon — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by denyskon** [comment]
Also the about.gitea.com website, before someone suggests again that we're selling a proprietary theme :)

**Pull request merged**
