### PR TITLE
WIP: Add directory support for wiki

### LINKED ISSUE #823: Hierarchy (sub directory) in Wiki
### Feature Description
This Feature Request is about Support for Hierarchy/Subdirectories in Gitea Wiki. That includes below content.

- [ ] Files Can be Put in Subdirectories from UI or git client side
- [ ] Files In Subdirectories can be normally Visited from UI and git client side
- [ ] Files In Subdirectories can be normally Linked in Markdown to
- [ ] Subdirectories pages can be listed in the Pages View.
- [ ] Files Renamed in Sudirs stay in them. (API support for Subdirs)
- [ ] / in File names is interpreted as Path/folder even if it's in a Windows OS

### Why the feature is necessary

I think Support for Subdirectories is a Great Feature, because:
- It helps to bring better structure into a Wiki, especially for those big wiki
- It would work with a lot of Tools Out of the Box like: Obsidian and Logseq

### PR DESCRIPTION
**Pull request by lunny**
Fix #823 

It's not ready to review.

图片

### CODE REVIEW

**Comment by wxiaoguang** [comment]
But would you like to clean up your stale PRs first?

**Comment by lunny** [comment]
> But would you like to clean up your stale PRs first?

Yes, I'm waiting for #32343, #32178, and #32987 to be reviewed and merged. Most of the others, including this one, will be kept in draft status until those ready-to-view PRs are merged.

**Comment by wxiaoguang** [comment]
> Yes, I'm waiting for #32343, #32178, and #32987 to be reviewed and merged.

If you could make time right, then no wait I guess.


----


> Most of the others, including this one, will be kept in draft status until those ready-to-view PRs are merged.

Maybe you could close these stale PRs to reduce the pending list since most they have various essential problems and not worth to review, and in case others would work on them.

**Comment by lunny** [comment]
Closed as there is no time to continue.

**Pull request closed without merging**
