### PR TITLE
Fix column name ambiguity in GetUserIssueStats()

### LINKED ISSUE #8231: Mentionin you error
After #8201 i check mentionin you group on try.gitea.io. but response 500 status code

When i check same repo on local there is no error, works well :thinking:

### PR DESCRIPTION
**Pull request by guillep2k**
In theory, fixes #8231 (can't reproduce)

Added a test for `TestGetUserIssueStats()`, but currently unit tests only run for SQLite, where this issue doesn't seem to trigger.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by lunny** [comment]
Please send back port to v1.9

**Comment by jaqra** [comment]
@lunny that feature (#8201) added in  is 1.10. cant backport

**Comment by lunny** [comment]
@jaqra Oh. right #7750 should not be related.

**Pull request merged**
