### PR TITLE
WIP: Add "ring" message logger to review last N messages on /admin/logging

### LINKED ISSUE #15: Log option on admin area
Hi guys,

Sometimes I want to see Gogs logs to see if anything is wrong, but today I need to go to gogs `log` folder to see logs.

Then I think that is good idea to add a Logs options on Gogs admin area and display `gogs.log`, `http.log`, `serv.log`, `update.log` and other Gogs logs. With this will be possible to see logs on Gogs install more easy and to report issues too.

What you think guys?

Reference: https://github.com/gogits/gogs/issues/3721

### PR DESCRIPTION
**Pull request by zeripath**
Add a ring message logger to make it possible to see the last N log messages from the admin settings screen.

Very much WIP. UI not ready etc. 

Current hacky way to add in the messages logger is to add:

```ini
[log]
MODE=console,messages; e.g. just append messages to current logging settings.
...

```

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Just FYI: there was an old issue for this:

* https://github.com/go-gitea/gitea/issues/15

**Comment by 6543** [comment]
this ring buffer does live within an instance ... for clustering this will be an issue ...

**Comment by singuliere** [comment]
> NOTE: this ring buffer does live within an instance ... for clustering this will be an issue ...

What is clustering?

**Comment by singuliere** [comment]
What about adding a method to get the current content of a named provider? It could be empty if the provider does not support that (smtp for instance). Or it could be the full content of the log file for the file provider. Or the content of the rotated list of messages for this new provider.

**Comment by silverwind** [comment]
> What is clustering?

Multiple gitea instances running off the same databases/caches.

**Comment by yardenshoham** [comment]
This is in progress for a while now, I'm closing it to avoid stale pull requests. Please reopen when it's ready for review.

**Pull request closed without merging**
