### PR TITLE
fix testing instructions in CONTRIBUTING.md

### LINKED ISSUE #6243: Testing instructions in CONTRIBUTING.md need to include drone-cli version and disk space requirements
The drone exec command in CONTRIBUTING.md isn't working again as of 7548037a64fd42bf11ad0d11a49fc3ae8dc731ff:

`drone exec --local --build-event pull_request`

This is using a newly-downloaded drone 1.0.4, which no longer supports the --local flag.

We last fixed this in #4055.  If anyone seeing this has the correct command for non-maintainers to run, just let me know and I'll fix CONTRIBUTING.md again.  

Meta-wise, does anyone have any ideas about how to somehow test the testing instructions to ensure that the drone command in CONTRIBUTING.md stays up to date?  Having this broken has got to be discouraging contributors.  The only bright idea I've had so far is to put the command itself into a separate file that is referred to by CONTRIBUTING.md and also automatically executed during regression testing.

### PR DESCRIPTION
**Pull request by stevegt**
- fixes #6243
- ~~partial fix for #6269~~

Signed-off-by: Steve Traugott <stevegt@t7a.org>

### CODE REVIEW

**Comment by lunny** [comment]
I think maybe many of us are using macOS?or windows?

**Comment by stevegt** [comment]
@lunny I finally started bringing myself up to speed on go this past week; am thinking of converting this script from bash to go so it will be more portable.  Should we kill this PR, or keep it open and I update it with the go version?

**Comment by stevegt** [comment]
On the other hand, I worded the changes to CONTRIBUTING.md such that if you're on non-Linux you would still install drone-cli manually just like now; for manual installation I'm adding the info about disk space and drone-cli version.  This means we have the option of accepting this PR as-is; it would be better than what we have in CONTRIBUTING.md right now.  (Right now the testing instructions in CONTRIBUTING.md don't work at all, due to the release of drone-cli 1.x.)

I do think that the script should be in go rather than bash for portability though, and if we were to accept this PR now I think the script should be replaced with a go version later.

**Comment by stevegt** [comment]
I've removed the idea of automated drone run at PR submission from both this PR and from #6269.  Still thinking. Maybe the right thing to do with this PR is to remove the script itself and remove mention of the script from CONTRIBUTING.md, leaving in there the new instructions about disk space and drone version.  That will fix #6243.

**Comment by stevegt** [comment]
Okay, I've removed the bash script and left in place an updated set of run instructions in CONTRIBUTING.md.  This fixes #6243.

Until we have the go version, I'll leave the bash script at https://github.com/stevegt/gitea/blob/drone-cli-bash/scripts/test-local.sh for reference.

**Review by techknowlogick — APPROVED** [review]

**Review by adelowo — APPROVED** [review]
👏👏

**Pull request merged**
