### PR TITLE
Fix compiling without sqlite and gcc

### LINKED ISSUE #2172: Building Gitea will build go-sqlite3 with or without the sqlite build tag
- Gitea version (or commit ref): master
- Git version: 2.8.1
- Operating system: Windows 10
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
  - [x] Not relevant

## Description
Even without specifying "sqlite" as a build tag, the command `go build main.go` will also build the vendor `go-sqlite3`, which requires gcc.

## Screenshots
sqlitebuild

## Note
Currently, two of Gitea's files import this vendor: `models/models_sqlite.go` and `models/unit_tests.go`. The former has the `sqlite` build constraint, while the latter does not. This is probably the root of this issue.

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #2172

### CODE REVIEW

**Comment by lunny** [comment]
No. the build tag is not in the correct place

**Comment by lafriks** [comment]
@lunny sorry that build tag was leftover from first try to fix compilation with no gcc, it was not needed, fixed

**Comment by lunny** [comment]
maybe rename models/unit_tests.go to models/unit_test.go is better?

**Comment by ethantkoenig** [comment]
@lunny No, it is important that `models/unit_tests.go` is not treated as a test file; otherwise the integration tests will not be able to import it.

**Comment by ethantkoenig** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by lunny** [comment]
make CI work

**Pull request merged**
