### PR TITLE
Fix margin and alignment in dashboard repolist

### PR DESCRIPTION
**Pull request by silverwind**
Seems this has recently regressed, previously, there was a significant whitespace between icon and text, but it seems to be gone, so I added the margin and also vertically aligned the icon because it was slightly misaligned.

Before:
Screenshot 2022-12-13 at 20 03 51

After:
image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Putting in draft, need to fix text truncation in the flexbox.

**Comment by silverwind** [comment]
Truncation fixed. The repo name can now stretch the full box instead of the previous arbitrary 70% value:

image

**Review by KN4CK3R — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by zeripath** [comment]
please send backport

**Comment by silverwind** [comment]
Was already backported to 1.18 in https://github.com/go-gitea/gitea/pull/22122 and 1.17 does not have the bug.

**Pull request merged**
