### PR TITLE
Display pull request head branch even the branch deleted or repository deleted

### LINKED ISSUE #10347: [Feature] Expose name of deleted PR branches
- Gitea version (or commit ref): 1.11.0
- Git version: 2.24.1
- Operating system: Linux (Alpine)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x]  SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/ppmathis/test/pulls/1
  - [ ] No
  - [ ] Not relevant

# Description
When the head branch of a pull request in either state gets deleted, the pull request no longer exposes the original branch name. This is directly related to #9158, which requested tracking the ref to the tip of the deleted branch and a working commit/changes view.

I would like to suggest to also expose the name of the branch which got deleted through both UI and API instead of just showing `from deleted into <target branch>`. The name of the branch can usually be accessed as `head.ref` in the API, however the whole `head` property is `null` as soon as the branch got deleted.

# Screenshots
## PR with correct branch name before branch deletion
before branch deletion
## PR with missing branch name after branch deletion
after branch deletion

### PR DESCRIPTION
**Pull request by lunny**
This PR did some improvments.

- [x]  Merge loadBaseRepo/getBaseRepo, loadHeadRepo/getHeadRepo on pull request
- [x] Only load once on loadHeadRepo if no system error
- [x] Use issue.Repo if possible
- [x] Display pull request head branch information even branch deleted or head repository deleted.
- [x] Get sha if possilbe, from pull/x/head

Fix #10347

### CODE REVIEW

**Comment by ppmathis** [comment]
Thank you for implementing this feature request! As I would mainly need this functionality for Renovate as you correctly discovered, I would like to ask if this PR also exposes the head branch name through the API, specifically `/api/v1/pulls` and `/api/v1/pulls/<PR>`? Haven't tested it yet, but based on the diff view this currently looks like UI/view-only, is that correct?

**Comment by lunny** [comment]
@ppmathis Updated. OK, now it should include headbranch information on API also.

**Review by 6543 — APPROVED** [review]
pleace update tests ...

**Review by zeripath — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport

**Pull request merged**
