### PR TITLE
WIP: wiki - page toc and directory support

### LINKED ISSUE #823: Hierarchy (sub directory) in Wiki
### Feature Description
This Feature Request is about Support for Hierarchy/Subdirectories in Gitea Wiki. That includes below content.

- [ ] Files Can be Put in Subdirectories from UI or git client side
- [ ] Files In Subdirectories can be normally Visited from UI and git client side
- [ ] Files In Subdirectories can be normally Linked in Markdown to
- [ ] Subdirectories pages can be listed in the Pages View.
- [ ] Files Renamed in Sudirs stay in them. (API support for Subdirs)
- [ ] / in File names is interpreted as Path/folder even if it's in a Windows OS

### Why the feature is necessary

I think Support for Subdirectories is a Great Feature, because:
- It helps to bring better structure into a Wiki, especially for those big wiki
- It would work with a lot of Tools Out of the Box like: Obsidian and Logseq

### PR DESCRIPTION
**Pull request by Cherrg**
# This PR

* add a "List of pages" to internal wiki (**page tree**). They will be generated with JS like #822, so it will be fast and don't burden the server. This feature could be disabled per configuration flag, or inside repository settings.
* add support for **directories** inside wiki. Create/update/delete pages works well. If an old page is updated, the file will be moved to subdirectory.
* allows to read files with nearly all letters, as it is possible to push all via wiki gitrepo.
  * Now it's possible to always access misspelled wikipages, which may be pushed via git. The fallback for old plain file structure is only kept (and used) to support old links inside existing wikipages.
So there is no priority on rendering old or new file, as it is decided by link.
  * duplicate pages (old structure and new page inside directory, may pushed via git) will be marked red on Page-TOC mentioned above. 
    * If there are an file in old and new structure, writing will delete both old files, while delete deletes sequential. First delete call will only delete file in old plain structure.
* add button 'Abort' to wiki `edit` and `new` page
* fixes issure mentioned in js/index.js line 1139
* fix 500 error if wiki contains pages with invalid uri encoding (e.g. filename: badescaping%%)

Unlike my last comment on #823  images relative to directory are OK now.

**Requires:**  #7182 
As this PR uses some script and css i've added there, it is nessesary to pull that first.
Changes made by this PR could be seen here [Compare this PR with #7182](https://github.com/Cherrg/gitea/compare/gitea_md_wiki_auto_toc...Cherrg:gitea_wiki_page_toc?expand=1)
If you read commit messages/names, it should be clear what and why i've done something. 

fix #823

# Some Images

_(Note the list symbol on `Small` and `Mobile` in top left corner)_

| **Large**        | **Mobile**       | 
|:------------- |:------------- |
| image    |  image |
| **Small**       | **Mobile Open**  |
| image | image |
| **Light** | |
| image | image |
| | image |

# Question
* Is `modules\markup\html shortLinkProcessorFull` still working with this? Where is it used? Does anyone know?

Signed-off-by: Michael Gnehr <michael@gnehr.de>

### CODE REVIEW

**Comment by Cherrg** [comment]
Should I split this PR up and seperate `wiki tree toc` from `wiki directory support`?
The TOC is the only part, that requires #7182 to work.

**Comment by lunny** [comment]
I would like that if it's not too difficult. @Cherrg

**Comment by Cherrg** [comment]
as i need to refactor this anyway, i split it up

**Comment by Cherrg** [comment]
i will close this when i opened a new pr for page tree

**Comment by lunny** [comment]
Please resolve conflicts.

**Comment by lunny** [comment]
Is this still WIP?

**Comment by gsantner** [comment]
?

**Comment by techknowlogick** [comment]
@gsantner conflicts need to be resolved before this can be merged.

**Comment by Cherrg** [comment]
@gsantner 
This PR was too bulky and huge, so directory support was extracted from this PR (#7390 + #8891).
I will refactor this when  #7182 + directory support are done

**Comment by FreeSaltedFish** [comment]
Will this feature eventually be released?

**Comment by Tanami** [comment]
would really love to see this feature live

**Comment by psykro** [comment]
Hello,

Do you know when this feature is planned ? 

Currently having all wiki pages on the same folder make it unusable for large projects.

**Comment by ehrenfeu** [comment]
Gitea 1.17 has support for TOCs (see #19873), so this PR here is probably *partially* obsolete.

However, I would **REALLY** love to see the folders feature! ❤️

**Comment by wxiaoguang** [comment]
It has been stale for a long time and I can't think of a way to handling it other than closing it. Feel free to reopen if there's any new progress and I could also help.

**Pull request closed without merging**
