### PR TITLE
Show different config documents for different releases

### PR DESCRIPTION
**Pull request by wxiaoguang**
# Background

Currently the `config-cheat-sheet` document misleads many users, there are some new setting options only available in 1.16, while many users who are using 1.15 may be confused why these options don't work.

# Solution

This PR splits the `config-cheat-sheet` document into different releases, just as most projects do.

Feel free to edit on this PR directly and push your commits.

Some other fixes:
* remove `minNodeVersion`, we always recommend developers to use Node.js LTS
* redirect: `/en-us/config-cheat-sheet/` => `/en-us/config-cheat-sheet-dev/`

image

### CODE REVIEW

**Comment by silverwind** [comment]
I think ideally we'd have a site-wide version switch mechanism so everything is versioned, not only this one page.

**Comment by wxiaoguang** [comment]
It's good to have a more general version switch mechanism. ps: I think maybe it is not really site-wide, some pages may not be suitable for the version switch mechanism.

If there is a better implementation of the document version mechanism, feel free to use it replace this one.

If we do not have one in recent future, maybe we can merge this one to make Gitea documents more friendly and clear to users, and then design a better mechanism later to replace this one.

**Comment by silverwind** [comment]
I think a build script would need to be added that checks out all release branches and generate different docs versions and this also should be reflected in the URL, e.g. `https://docs.gitea.io/en-us/$VERSION/config-cheat-sheet/` where `$VERSION` is in major.minor format with a `latest` pointing to the latest version and being the default version loaded.

**Comment by wxiaoguang** [comment]
I have thought about it, but the idea doesn't work now. 

1. It requires a refactoring about the docs build system. I have no confidence such work can be approved.
2. Some links in old documents are incorrect, for example, in https://github.com/go-gitea/gitea/blob/release/v1.8/docs/content/doc/advanced/config-cheat-sheet.en-us.md , there is a link https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample , I can not fix these problem in one PR, using `sed` to replace is too dirty and hacky.

**Comment by silverwind** [comment]
Maybe it's worth migrating docs to https://github.com/facebook/docusaurus, I imagine it has built-in support for stuff like versioning.

**Comment by wxiaoguang** [comment]
Yep, if there is a better choice, we can try.

**Comment by lunny** [comment]
> https://docs.gitea.io/en-us/$VERSION/config-cheat-sheet/

I think `https://docs.gitea.io/e$VERSION/n-us/config-cheat-sheet/` is better. I will try to send a PR to do that.

**Comment by wxiaoguang** [comment]
Any update? Should we drop/close this one or continue on this one?

**Comment by lunny** [comment]
> Any update? Should we drop/close this one or continue on this one?

I think a multiple version around the whole site is better.

**Comment by wxiaoguang** [comment]
I do not think `multiple version around the whole site` works.

For example: this PR https://github.com/go-gitea/gitea/pull/18109 fixes a dead domain in document. It's risky, even worse if someone puts malware on it. If we have `multiple version around the whole site`, I do not think any of the maintainers has the interest to update all documents from 1.8 to 1.15 on every branch.

**Comment by lunny** [comment]
> I do not think `multiple version around the whole site` works now (it works for some documents, but it seems it's hard to work for all)
> 
> For example: this PR #18109 fixes a dead domain in document. It's risky, even worse if someone puts malware on it. If we have `multiple version around the whole site`, I do not think anyone has the interest to update all documents from 1.8 to 1.15 on every branch.

We should not maintain all the versions. We could maintain recent 3 versions documents.

**Comment by wxiaoguang** [comment]
OK, this one can be closed. Hopefully we can make some progress soon, otherwise many users will be misled.

**Pull request closed without merging**
