### PR TITLE
Fixup app.example.ini for task section, which is now queue.task

### PR DESCRIPTION
**Pull request by xor-gate**
I am running gitea v1.21.11 and was using the `app.example.ini` from git on the previous tag. It seems `[task]` has been deprecated in favor of `[queue.task]`. See #30554

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I think this section should be removed, because all other types of queues also shared the same section above:

image

**Comment by wxiaoguang** [comment]
The `task` section in config cheatsheet should also be removed:


image

**Comment by wxiaoguang** [comment]
Made some changes, I think we should keep `[queue]`, remove `[task]`

**Review by wxiaoguang — APPROVED** [review]

**Comment by xor-gate** [comment]
> Made some changes, I think we should keep `[queue]`, remove `[task]`

Sorry I mis understood what needed to be changed and accidently also removed the `[queue]` section. Now it is clear.

**Comment by wxiaoguang** [comment]
> > Made some changes, I think we should keep `[queue]`, remove `[task]`
> 
> Sorry I mis understood what needed to be changed and accidently also removed the `[queue]` section. Now it is clear.

I realized that I didn't say it clearly before, the word `this` is quite ambiguous in that context 🤣  sorry for the confusing.

**Pull request merged**
