### PR TITLE
Simple fix release attachment links to human readable

### LINKED ISSUE #10919: Attachment links are not human readable again
- Gitea version (or commit ref): 1.11.4
- Operating system: CentOS 7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
After upgrading to v1.11.3 release attachment links are not human-readable again and now looks like `https://gitea.example/attachments/a0023262-7abf-461d-9271-2e9f195ecebc` instead of `https://gitea.example/xoxys/cups-rpm/releases/download/v.1.0.0`.

### PR DESCRIPTION
**Pull request by ghost**
close https://github.com/go-gitea/gitea/issues/10919, which is stalled for a long time.

Before

	https://gitea.com/attachments/c15910d0-736c-4dc3-846b-6440ad2048fd

After

	https://gitea.com/gitea/tea/releases/download/v0.9.0/tea-0.9.0-darwin-amd64

---

Next step:

- [ ] Check an attachment with that filename alreadly exists. 
  - [ ] do backend duplicated filenames check when updating a release
  - [ ] do frontend duplicated filenames check whatever creating or updating a release
- [ ] #13750

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Tested it on try.gitea using
```js
document.querySelector('a[href="https://gitea.com/attachments/e670ea07-5998-443d-95c0-fd64c91cd06b"]').href="https://gitea.com/gitea/distea/releases/download/v0.0.5/distea_0.0.5_linux_x86_64.tar.gz"
```
---

It works.

**Review by wxiaoguang — COMMENTED** [review]
There was one:

* https://github.com/go-gitea/gitea/pull/13750

**Comment by xin-u** [comment]
> There was one:
> 
> * #13750

I see WIP.... from 2020

**Comment by wxiaoguang** [comment]
Yup, I do not understand the blocker of the problem at the moment and haven't looked into it carefully. So I just hold my reviews.

**Comment by delvh** [comment]
Well, as far as I've seen the original problem was that only the first attachment with that name can be downloaded.
However, I think that is rather expected behavior as uploading multiple attachments with the same name will not only confuse the computer, but also the humans…
The WIP PR wanted to add logic to disallow uploading release attachments with the same name (by replacing it with the new content), so I assume the problem is currently that the logic to block double uploads does not exist.

**Comment by xin-u** [comment]
What GitHub does is just show: "An attachment with that filename alreadly exists."

**Comment by delvh** [comment]
Yes, that's also my proposed behavior, at least for the first step.
Afterward, we can still examine if we want to auto-replace a duplicated attachment with a new one, which has both advantages and disadvantages.

**Comment by xin-u** [comment]
I'd like to add a filename duplicate check for upload release attachments in server side, but I found that the method did not store the correct `release_id` for each attachment.  https://github.com/go-gitea/gitea/blob/6f3efdfe117b46978d449f9223394326e39067ce/routers/web/repo/attachment.go#L48


Gitea Vs GitHub upload release attachments:

<details>

- POST |  URL: https://gitea.com/someone/test/releases/attachments

```
------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Disposition: form-data; name="file"; filename="gitea.png"
Content-Type: image/png


------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

- POST | https://github.com/upload/policies/releases

```
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="name"

gitea.png
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="size"

48819
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="content_type"

image/png
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="authenticity_token"

pxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="repository_id"

559475857
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="release_id"

82910646
-----------------------------00000000000000000000000000000
Content-Disposition: form-data; name="deletion_candidates"

84458524
-----------------------------00000000000000000000000000000--
```


</details>


Do we need to store a real `releaseID`  in database for each attachment before implement a Duplicate name checker.

**Review by 6543 — CHANGES_REQUESTED** [review]
sorry that does not solve the unerlying issue

it was done so intentionaly

**Comment by 6543** [comment]
see #13750 - please fix the open TODOs first and I'll ack to this (didn't had time myself to do so...)

**Comment by xin-u** [comment]
The current workflow is:
1. Upload an attachment (no release-related context, just set release_id=0), and get a set of attachmentUUIDs
2. Create Release: Query a set of uploaded attachments through GetAttachmentsByUUIDs, and edit the release_id for each attachment (if release_id>0, permission denied)

I'm afraid the current workflow is hard to change correctly. Maybe a simple policy should be in the upload stage to check if each attachment of a release has the same name.

---

When I upload a file on GitHub, the frontend sends a POST containing name, size, content_type, authentication_token, repository_id, release_id

The server can easily check whether the attachments under a release have the same name according to repository_id, release_id, name

**Comment by lunny** [comment]
The problem is when creating a new release, how should we check the same filename? I think maybe we have to check them in frontend whatever creating or updating a release and only do backend duplicated filenames check when updating a release.

**Pull request closed without merging**
