### PR TITLE
In TestViewRepo2, convert computed timezones to local time

### PR DESCRIPTION
**Pull request by kousu**
This fixes up https://github.com/go-gitea/gitea/pull/10446; in that, the *expected* timezone was changed to the local timezone, but the computed timezone was left in UTC.

The result was this failure, when run on a non-UTC system:

```
	Diff:
    --- Expected
    +++ Actual
    @@ -5,3 +5,3 @@
       commitMsg: (string) (len=12) "init project",
    -  commitTime: (string) (len=29) "Wed, 14 Jun 2017 09:54:21 EDT"
    +  commitTime: (string) (len=29) "Wed, 14 Jun 2017 13:54:21 UTC"
      },
    @@ -11,3 +11,3 @@
       commitMsg: (string) (len=12) "init project",
    -  commitTime: (string) (len=29) "Wed, 14 Jun 2017 09:54:21 EDT"
    +  commitTime: (string) (len=29) "Wed, 14 Jun 2017 13:54:21 UTC"
      }
    Test:       	TestViewRepo2
```

I assume this was probably missed since the CI servers all run in UTC?

The Format() string "Mon, 02 Jan 2006 15:04:05 UTC" was incorrect: 'UTC' isn't recognized as a variable placeholder, but was just being copied verbatim. It should use 'MST' in order to command Format() to output the attached timezone, which is what `time.RFC1123` has.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
Wonder why @GiteaBot does not rebase here.

**Comment by yardenshoham** [comment]
Maintainers don't have push access here

**Comment by lunny** [comment]
@kousu please rebase the branch

**Comment by kousu** [comment]
> The fork is from an org. GitHub doesn't allow maintainer to edit the org fork's PRs.

Yep. I've run into this with every PR I've submitted to you so far. @jolheiser [explained](https://github.com/go-gitea/gitea/pull/22898#issuecomment-1470848780)

> Nope, not your fault, I believe it's a GitHub thing that doesn't let us update it because it's from an org vs a user account.

So thank you for just going ahead and squash-merging it in. Plus I'm in a different timezone than most of you, so I wouldn't have gotten to it for a while!

By the way, 

> @kousu please rebase the branch

Is this policy now? In [this](https://github.com/go-gitea/gitea/pull/22177#issuecomment-1367508952) I was told off  for using rebases:

> > why forcepush, that make it hard to review

**Comment by yardenshoham** [comment]
Don't rebase, lunny and silverwind meant `merge`

**Comment by lunny** [comment]
> > The fork is from an org. GitHub doesn't allow maintainer to edit the org fork's PRs.
> 
> Yep. I've run into this with every PR I've submitted to you so far. @jolheiser [explained](https://github.com/go-gitea/gitea/pull/22898#issuecomment-1470848780)
> 
> > Nope, not your fault, I believe it's a GitHub thing that doesn't let us update it because it's from an org vs a user account.
> 
> So thank you for just going ahead and squash-merging it in. Plus I'm in a different timezone than most of you, so I wouldn't have gotten to it for a while!
> 
> By the way,
> 
> > @kousu please rebase the branch
> 
> Is this policy now? In [this](https://github.com/go-gitea/gitea/pull/22177#issuecomment-1367508952) I was told off for using rebases:
> 
> > > why forcepush, that make it hard to review

I made a mistake and I have corrected it.

**Pull request merged**
