### PR TITLE
Avoid bad database state after failed migration

### LINKED ISSUE #7039: Failed migration leaves database in a bad state
- Gitea version (or commit ref): `df255783`
- Git version: 2.17.1
- Operating system: Linux x86_64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) - https://try.gitea.io/rob2/nope
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Failed migration does not rollback database properly.

**To recreate:**

1. Visit https://try.gitea.io/repo/migrate
2. Enter clone URL `https://github.com/nope/nope.git` and repo name `nope`
3. Leave clone authentication blank
4. Submit form

**Expected behaviour: **

See error message _Authentication failed: Clone: exit status 128 - fatal: could not read Username for 'https://github.com': No such device or address_ and no repo is created in the database

**Actual behaviour**

Error message above is displayed but an empty repo is also created in the database, shows on the user's profile and generates a 500 when visited.

Note that deleting the repo from the DB is not enough to clean this up, there are also entries in the `action` table too (and possibly elsewhere)

## Screenshots

N/A

### PR DESCRIPTION
**Pull request by rfwatson**
Ensure `g.repo` is not nil after a failed migration, this allows the cleanup [here](https://github.com/rfwatson/gitea/blob/0c73755e039fbc62d000af79cf563ce29c136f41/modules/migrations/gitea.go#L397) to be triggered as expected.

Fixes #7039

### CODE REVIEW

**Comment by rfwatson** [comment]
Is there any docs for setting up integration tests locally? I'll add a test case if I can get them running

**Comment by zeripath** [comment]
`make test-sqlite` will run the integration tests on sqlite which is probably all you need to run unless you're very keen.

I think `CONTRIBUTING.md` has some information about how to run drone to perform a pull-request check.

`drone exec --local --build-event pull_request`

**Review by zeripath — APPROVED** [review]

**Comment by rfwatson** [comment]
Thanks. 

Out of interest, is there a reason we don’t rollback a database transaction here, instead of cleaning up manually?

**Comment by zeripath** [comment]
It's not in a transaction unfortunately. Keeping it in a transaction would cause the entire database to be locked whilst you're migrating potentially large repositories.

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@rfwatson good catch.

**Pull request merged**
