### PR TITLE
add Index to comment for migrations and mirroring

### PR DESCRIPTION
**Pull request by singuliere**
See original [merge request from Loïc Dachary @ forgefriends](https://lab.forgefriends.org/forgefriends/forgefriends/-/merge_requests/46)

---

Comments have an id (see Gitea[0], GitLab[1] or GitHub[2], etc.), and the
comment migration format must represent it during migrations so that
it can be used during mirroring or incremental migrations.

[0] https://try.gitea.io/api/swagger#/issue/issueGetComment
[1] https://docs.gitlab.com/ee/api/discussions.html#get-single-issue-discussion-item
[2] https://docs.github.com/en/rest/reference/issues#get-an-issue-comment

### CODE REVIEW

**Comment by lunny** [comment]
What's the definition of comment index?

**Comment by singuliere** [comment]
> What's the definition of comment index?

It is the unique identifier of the comment.

**Comment by singuliere** [comment]
The CI failure is unrelated to this PR, could someone please restart it?

```
+ make lint-backend

golangci-lint run --timeout 10m

level=error msg="[linters context] typechecking error: pattern ./...: open /drone/src/node_modules/esbuild-android-arm64: no such file or directory"

make: *** [Makefile:782: golangci-lint] Error 7
```

**Comment by singuliere** [comment]
It would be too complicated to add the comment identifier in the database. This pull request was simplified to only add the information in the migration files. It can later be used to set the information in the `ForeignReference` table when [this pull request is merged](https://github.com/go-gitea/gitea/pull/18446).

**Comment by lunny** [comment]
The Index is per repository or per issue? Since there is no id or index from Github, what should be stored?

**Comment by singuliere** [comment]
> The Index is per repository or per issue? 

It depends. The index for `Gitea` is absolute even though the [API endpoint is relative](https://try.gitea.io/api/swagger#/issue/issueGetComment) to the repository. The API endpoint for `GitHub` is also [relative to the repository](https://docs.github.com/en/rest/reference/issues#get-an-issue-comment) but the documentation does not specify if the `id` field is relative to the repository or not. However, since the API endpoint is not relatve to the issue, I think the `id` is not per issue.

> Since there is no id or index from Github, what should be stored?

There is an `id`for comments from GitHub. And for GitLab too and every other forge supported by Gitea at the moment.

Maybe I misunderstood your question?

**Review by lunny — APPROVED** [review]

**Comment by Gusted** [comment]
In simple words this PR provide a value for the [`GetForeignIndex()`](https://github.com/go-gitea/gitea/pull/18446) for the comment structs?

**Review by Gusted — APPROVED** [review]

**Comment by singuliere** [comment]
make l-g-t-m work

**Comment by singuliere** [comment]
make l-g-t-m work

**Pull request merged**
