### PR TITLE
Fix tags view

### PR DESCRIPTION
**Pull request by wiktor-k**
Hi,

This PR fixes several issues reported in https://github.com/go-gitea/gitea/issues/23221.

It does three things:
1. Fixes the `DefaultBranch` variable that has not been set.
2. Sets `Title` and `Message` for newly created tags from the Tag message. This makes it easier to create releases from tags that have messages and for those that don't it doesn't have any effect.
3. Makes UI changes so that tags look more like proper releases.

Before:

After:

I purposefully didn't reformat the template so that the diff is cleaner but can do so if that's welcome.

Thanks for your time!

### CODE REVIEW

**Comment by silverwind** [comment]
I'm a bit confused because in the issue, the GitHub screenshot shows a tag, but in the gitea screenshot, it shows a release.

Release body text is from the manually created release.
Tag body text is from the git tag message.

Is this how this works? It almost seems like you are using the tag message as the release body text, but I don't think this is matching GitHub's behaviour.

**Comment by wiktor-k** [comment]
> I'm a bit confused because in the issue, the GitHub screenshot shows a tag, but in the gitea screenshot, it shows a release.

It shows a tag. Why do you think it shows a release? The PR makes the display of tags similar to releases. (Or maybe I misunderstood something...)


>  -  Release body text is from the manually created release UI.
>  -  Tag body text is from the git tag message.
>
> Is this how this works? It almost seems like you are using the tag message as the release body text, but I don't think this is matching GitHub's behaviour.

In my experience it matches GitHub's behavior, see for yourself here: https://github.com/wiktor-k/pysequoia/releases/tag/v0.1.14 and compare with https://try.gitea.io/wiktor/pysequoia/releases/tag/v0.1.14

Then if you compare with my second screenshot it looks more similar to what GitHub renders.

Maybe I misunderstood your question...

**Comment by silverwind** [comment]
Ah, I see Github has a separate page for display of a single tag, which gitea lacks (clicking the tag takes you to the code view).

Do you think we can match GitHub in this regard? E.g. Releases tab should only be for manual releases, and single Tags could be viewed on a separate page just like https://github.com/wiktor-k/pysequoia/releases/tag/v0.1.14.

**Comment by wiktor-k** [comment]
> Ah, I see Github has a separate page for display of a single tag, which gitea lacks (clicking the tag takes you to the code view). 

Actually the route is there and the single tag view is also there it's just not used when you click the tag. This is one more thing that I've fixed in this PR. 

(replacing src in URL takes to the single tag view: https://try.gitea.io/wiktor/pysequoia/releases/tag/v0.1.15 ).

> Do you think we can match GitHub in this regard? E.g. Releases tab should only be for manually created releases, and single Tags should be viewable on a separate page just like https://github.com/wiktor-k/pysequoia/releases/tag/v0.1.14.

I think it already almost works like that. See the URL above. IMHO the tag view just lacked a little bit of polish that the release view had. I hope that this PR bridges the gap a little.

**Comment by silverwind** [comment]
Sounds good, I will test this and I think we should change the link in the tag list to point to the single tag instead. The old link to repo view could then either be moved to the footer or dropped altogether.

**Comment by wiktor-k** [comment]
Great! Thanks for your time!

**Comment by wiktor-k** [comment]
@a1012112796 Indeed, this looks better. I've captured your diff into a commit and added it here. Thanks!

**Comment by silverwind** [comment]
Gave it a test, there's still a few things missing from the Tag view:

Compare GitHub to this PR:

image
Screenshot 2023-03-14 at 22 40 15

- Big header should be added
- Tag message (as seen via `git show <tag>`) is missing

I'm not sure the backend infrastructure is there to obtain the tag message, so if it isn't we could defer that to another PR.

**Comment by wiktor-k** [comment]
> Tag message (as seen via git show <tag>) is missing

@silverwind are you observing a tag that was pushed before this change? Since [this commit](https://github.com/go-gitea/gitea/pull/23243/commits/6dedc7ddc9e9cc2f6e7345ec94b3fd7ef8cac717) I fixed the message update for pushed tags. But that will only work for new tags, as the code runs on tag push. (For testing you can remove the tag from UI and `git push --follow-tags` from console).

> Big header should be added

Agreed. I'll fix that right away.

**Comment by silverwind** [comment]
> @silverwind are you observing a tag that was pushed before this change

Yes, old tag. Do we store the tag message in the database? We should not, this is retrievable live from the git repo.

**Comment by lunny** [comment]
> > @silverwind are you observing a tag that was pushed before this change
> 
> Yes, old tag. Do we store the tag message in the database? We should not, this is retrievable live from the git repo.
> 
> Releases are fine to store in the database, but tag name and message is part of the git repo.

Tags have been synced to databases when necessary because they just could be added or deleted, and cannot be modified. I think branches should also be synced to databases in future PRs. The beneficial of the operations will help in better performance, better paginations, better search, and better sort.

**Comment by silverwind** [comment]
It sound completely wrong to me to sync tags to database.

You can for example not delete a tag without also deleting it from git itself. Releases are fine in the DB as they are unrelated to git, but tags should be purely based on git. I would suggest at minimum falling back to reading tag info from git if DB does not info on it, but really this sounds completely broken to me.

**Comment by silverwind** [comment]
It's fine to have additional attributes related to a tag in the DB, but the tag base attributes like tag name, message, signature and the tag's existance should come from git only.

**Comment by lunny** [comment]
> It sound completely wrong to me to sync tags to database.
> 
> 
> 
> You can for example not delete a tag without also deleting it from git itself. Releases are fine in the DB as they are unrelated to git, but tags should be purely based on git. I would suggest at minimum falling back to reading tag info from git if DB does not have it, but really this sounds completely broken to me.

But the code was there for many years from @lafriks. And there is no better method to resolve the problem to search, sort, pagination problem. If there is any better idea, I think we can discuss them.

**Comment by silverwind** [comment]
Sure, but I would like to at least see the tag message,signature etc of past tags, just like GitHub show, I think it should be possible to fallback to git in case db does not have the tag, right?

**Comment by silverwind** [comment]
I guess we can postpone the tag discussion, and take this PR purely as an UI improvment. I strongly believe that all tag data should come from git and git only. Releases on the other hand are a concept specific to Gitea, of course and have nothing to do with git, except that they can optionally point to tags.

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by wiktor-k** [comment]
Resolved conflict, rebased on top of `main`. Tested at it still looks nice:

**Review by lunny — APPROVED** [review]

**Pull request merged**
