### PR TITLE
Make openid support default false for compitable with v1.1

### PR DESCRIPTION
**Pull request by lunny**
And also disable OpenID register if OpenID sign in disabled.

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Comment by sapk** [comment]
LGTM

**Comment by strk** [comment]
Please make sure try.gitea.io still supports openid sign-in and
registration. \cc @bkcsoft

**Pull request merged**
