### PR TITLE
Allow to change primary email before account activation

### PR DESCRIPTION
**Pull request by wxiaoguang**
image

image

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by wolfogre** [comment]
Maybe I haven't read the code carefully, but is there a CAPTCHA validation (if it's enabled) to change email before account activation? I mean I can:
- Register with an email address, pass the CAPTCHA validation on the registration page manually.
- Use a bot script to resend validation emails automatically, and each time with a different email address.

**Comment by wxiaoguang** [comment]
> Maybe I haven't read the code carefully, but is there a CAPTCHA validation (if it's enabled) to change email before account activation? I mean I can:
> 
>     * Register with an email address, pass the CAPTCHA validation on the registration page manually.
> 
>     * Use a bot script to resend validation emails automatically, and each time with a different email address.

There is no difference. Because the "limit" is done by username:

image

**Comment by lunny** [comment]
> > Maybe I haven't read the code carefully, but is there a CAPTCHA validation (if it's enabled) to change email before account activation? I mean I can:
> > ```
> > * Register with an email address, pass the CAPTCHA validation on the registration page manually.
> > 
> > * Use a bot script to resend validation emails automatically, and each time with a different email address.
> > ```
> 
> There is no difference. Because the "limit" is done by username:
> 
> image

As I have tested, it's unavailable since it's unrelated to this PR.

**Review by lunny — APPROVED** [review]

**Comment by a1012112796** [comment]
why not allow not actived user using '/user/settings' router directly?

**Comment by lunny** [comment]
> why not allow not actived user using '/user/settings' router directly?

Inactive users should have the minimum services.

**Pull request merged**
