### PR TITLE
fixed the dropdown menu for the top New button to expand to the left

### PR DESCRIPTION
**Pull request by kerwin612**
before: 

after:

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Not sure if that is really something Fomantic supports officially, but if it works, we can go with it.

**Comment by silverwind** [comment]
Actually fix is correct, I checked the CSS, there are two rules the left-align `.menu.left`.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Unfortunately this introduced a regression where the menu flashes on page load. Will investigate later.

**Comment by kerwin612** [comment]
> Unfortunately this introduced a regression where the menu flashes on page load. Will investigate later. It needs a fix similar to #30215.

https://discord.com/channels/322538954119184384/322910365237248000/1248480303719252029 Can we discuss it?

**Comment by silverwind** [comment]
Not right now, but to explain the issue: There is this CSS:

```css
.ui.menu:not(.vertical) .left.item, .ui.menu:not(.vertical) .left.menu {
  display: flex;
}
```

Dropdown menus are hidden on page load via
```css
.ui.dropdown .menu {
  display: none;
}
```

Above selector has more specificity so dropdown shows before JS has loaded which takes a few milliseconds usually. Once JS loads, it hides the menu via `hidden` class.

Maybe as a more general solution we can remove the first CSS, but I'm not sure whether there would be side effects of doing that.

**Comment by kerwin612** [comment]
Maybe it could be changed like this?:
```
.ui.dropdown .menu {
  display: none!important;
}
```

**Comment by silverwind** [comment]
I don't think it's worth the time trying to make `left menu` work. Fomantic only specifies left/right for sub-menus, not the root menu:

https://fomantic-ui.com/modules/dropdown.html#menu-direction

So a `left menu` is essentially not supported and that is already shady territory and any attempt trying to make it work is likely to introduce regressions in other dropdowns which have very brittle CSS.

So I suggest you leave it be and find some other areas to work on :)

**Comment by kerwin612** [comment]
OK, I changed it because I saw this code:  
https://github.com/go-gitea/gitea/blob/ab1948d4a30aee919ba1ffc2402a2a9a7222e68c/web_src/fomantic/build/semantic.js#L5291  
https://github.com/go-gitea/gitea/blob/ab1948d4a30aee919ba1ffc2402a2a9a7222e68c/web_src/fomantic/build/semantic.js#L3796  
https://github.com/go-gitea/gitea/blob/ab1948d4a30aee919ba1ffc2402a2a9a7222e68c/web_src/fomantic/build/semantic.js#L4528  

OK, that's the end of the suggest.

**Pull request merged**
