### PR TITLE
Update go dev dependencies

### PR DESCRIPTION
**Pull request by silverwind**
`golangci-lint` [deprecated](https://github.com/golangci/golangci-lint/issues/1841) a bunch of linters, removed them.

### CODE REVIEW

**Comment by silverwind** [comment]
Lint now passes so it should be ready for review now.

**Comment by lunny** [comment]
> - `air` is updated to the [commit](https://github.com/cosmtrek/air/commit/25c287e039e931fb440c3c50ef481fee1bbd472f) that added `include_file` which allows watching `main.go`
> 
> - `golangci-lint` [deprecated](https://github.com/golangci/golangci-lint/issues/1841) a bunch of linters, removed them.

Air is not a released version?

**Comment by silverwind** [comment]
No because auther hasn't released in a while, but I guess I will revert, it's a minor issue.

**Comment by silverwind** [comment]
Reverted air and squashed.

**Review by a1012112796 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
