### PR TITLE
Remove duplicate logic in initListSubmits

### PR DESCRIPTION
**Pull request by a1012112796**
Using the same logic to handle Choosing reviewers and assignees as choosing label. It's the first step of #10926.

### CODE REVIEW

**Comment by 6543** [comment]
could it potentialf fix #12643 ?

**Comment by a1012112796** [comment]
> could it potentialf fix #12643 ?

Not fixed. And I  think this logic is  necessary, Because if user choose one item then
quickly dischoose it, nothing should be done, which is same with GH. Maybe we should do something to check close page...

**Comment by a1012112796** [comment]
> could it potentialf fix #12643 ?

@6543 By the way, I have registered for a new count in Codeberg, but I can't receive an active email... :(

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
asign asignees and re-review-request do not work anymore

**Comment by a1012112796** [comment]
> asign asignees and re-review-request do not work anymore

Hello, I‘m sorry, but I haven't faced the bug which you reported. So I don't know why either. Can you tell me which type of browser you are using? or give me some screenshoots. Thanks. 
@CirnoT @silverwind @Sorien , Please have a look. Thanks.

**Comment by a1012112796** [comment]
@6543 Maaybe because of ``ban-change`` undefined, Please test again. Thanks.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
now it works

**Comment by a1012112796** [comment]
Suggest backport :)

**Comment by 6543** [comment]
@a1012112796 since its a refactor and no bugfix, why should we backport?

**Comment by a1012112796** [comment]
> @a1012112796 since its a refactor and no bugfix, why should we backport?
the small nit about ``ban-change`` :)

**Comment by 6543** [comment]
well then I only would pick out the bugfix for backport ...

**Pull request merged**
