### PR TITLE
Fix migration v141 (#14387)

### PR DESCRIPTION
**Pull request by 6543**
Backport of #14387

### CODE REVIEW

**Comment by zeripath** [comment]
could you add a doctor command?

**Comment by 6543** [comment]
@zeripath It's already here `./gitea doctor recreate-table user` or should I add an alias?

**Comment by zeripath** [comment]
No I mean to fix the nulls

**Comment by 6543** [comment]
@zeripath with 79b014c user dont have to migrate db and manualy fix things ...

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
