### PR TITLE
Add DefaultMergeStyle option to repository

### LINKED ISSUE #12293: Allow to specify default PR merge option
Currently, there are four different ways to merge PRs
* Merge pull request
* Rebase and merge
* Rebase and merge (--no-ff)
* Squash and merge

Usually, the first one in the list which has been activated via repository settings is the default and is achieved when clicking on the big button. I would like to be able to specify the default action for the large button in the repository settings.

### PR DESCRIPTION
**Pull request by parnic**
This pull request adds support for configuring the default merge style for pull requests in a repository.

Fixes #12293

Note: I haven't added tests or anything yet, mostly because I wanted to make sure this was
1. Something you all are willing to merge at all
2. Meets contribution guidelines/requirements.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
DefaultMergeStyle should be selected on pull request view merge dropdown button.

**Comment by parnic** [comment]
> DefaultMergeStyle should be selected on pull request view merge dropdown button.

@lunny do you mean `templates/repo/issue/view_content/pull.tmpl`? If so, that's what the `routers/repo/issue.go` change is accomplishing. If not, where do you mean?

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by pat-s** [comment]
@parnic Could you resolve the merge conflicts? :) there are already two approvals.

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
