### PR TITLE
Use github actions instead of drone to release versions

### PR DESCRIPTION
**Pull request by lunny**
This PR removed drone file and cherry pick the release workflow from main branch but removed docker latest and 1 tags, Only keep 1.x and 1.x.x tags.

### CODE REVIEW

**Comment by techknowlogick** [comment]
some makefile changes are also required

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
> some makefile changes are also required

Which changes? Could you send some commits?

**Comment by jolheiser** [comment]
From what I can tell, the changes for GHA are already in the `1.20` version of the Makefile, and a comparison of other commits made to e.g. the `1.21` branch only shows some updates to linting actions etc. 
Are those required here as well?

**Comment by techknowlogick** [comment]
@jolheiser ah, I guess I backported them already lol

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
