### PR TITLE
Style code review comment for arc-green

### PR DESCRIPTION
**Pull request by CirnoT**
Lot of styling fixes in this one, but I'd like to think I got it somewhat usable.

Before:
chrome_2020-05-23_03-20-30

After:
chrome_2020-05-23_16-38-23

Few issues that still remain should be fixed by https://github.com/go-gitea/gitea/pull/11570 and https://github.com/go-gitea/gitea/pull/11571

### CODE REVIEW

**Comment by silverwind** [comment]
The border around "Review" should be light, not dark. Otherwise it looks like a good improvment.

**Comment by lafriks** [comment]
There seems to be unneeded margin between comment author and content

**Comment by CirnoT** [comment]
@lafriks Fixed by https://github.com/go-gitea/gitea/pull/11571

**Comment by CirnoT** [comment]
Changed border color around "Review" tag to be light and adjusted border around textarea to match proposed changes in https://github.com/go-gitea/gitea/pull/11570

Updated screenshot in first post

**Review by 6543 — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
