### PR TITLE
Fixed emoji alias not parsed in links

### LINKED ISSUE #12331: Emoji alias not parsed in links
- Gitea version (or commit ref): 1.13.0+dev-322-g54513452a docker version
- Git version:
- Operating system: Docker on Arch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) : https://try.gitea.io/toc-test/emoji-markdown-tests
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When using an emoji alias in an inline link, it is not displayed as an emoji but keeps its alias. The test page created shows the result of emoji alias in most cases. The inline link does not show an emoji but its alias.

## Screenshots

image

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #12331

I'm not sure why there was this exclusion (#10515 @zeripath)
The test document from @silverwind works now.

### CODE REVIEW

**Comment by zeripath** [comment]
Couldn't this cause double processing of links?

**Comment by 6543** [comment]
we should consider this precisely

**Comment by zeripath** [comment]
In fact it is causing repeated processing of links:
```
 	runtime: goroutine stack exceeds 1000000000-byte limit
59s
40	runtime: sp=0xc029880370 stack=[0xc029880000, 0xc049880000]
```

**Comment by zeripath** [comment]
You need to make it so that only the emoji things fire on the link text.

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
