### PR TITLE
move package `modules/git` into `modules/git/backend`

### PR DESCRIPTION
**Pull request by 6543**
address 1. of https://github.com/go-gitea/gitea/issues/25070#issuecomment-1625499126

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by 6543** [comment]
> Isn't everything "backend"?

what do you refer to?!?

**Comment by 6543** [comment]
if it's just about the name ... something like "current_mixed_git_backend_implementation" did sound bad ... so i did go with "backend" untill we do start to move things around ...

**Comment by KN4CK3R** [comment]
Yes, I talk about the name. If we implement something like Gitaly it's still "backend" for me. But to be honest, I don't have a better name at the moment. I think I would go with "internal" / "local" and "external" / "remote" (for data coming from somewhere else) but we can choose a name when we know what we will implement.

**Comment by 6543** [comment]
we already have two gogit and nogogit ... but they are intertwined ... so one work will be to separate them into it's own packages ... and in our case depend gogit on nogogit

and yes we need a better name for them ...
I propose:
- gogit
- gitbin

but that's nothing for this pull

**Comment by wxiaoguang** [comment]
I have some questions about these changes:

1. Is "backend" really a good name? We also talk about "backend" code a lot, in most cases, the "backend" refers to the whole Gitea's Golang code base.
2. Is the "moving" necessary? Even without "moving", the old code can be left there, and there can be a new package for future refactoring work.
3. What's the next plan? I think it's better to have a global design for next steps about: how to separate types into sub packages and what types should be moved out, what the new engine would look like and how would it use the old git code?

**Comment by 6543** [comment]
1. well propose a better one :D
2. yes if we want to follow https://docs.gitea.com/contributing/guidelines-backend#packages-list
3. https://github.com/go-gitea/gitea/issues/25070#issuecomment-1625499126

**Comment by 6543** [comment]
and we cant just simply refactor it in one move ... we have to do it like the migration from macaron to go-chi ...
... move, build new structure and then migrate parts until we are done

the new interface can not be completly planed as it will be created on demand while the migration of parts is happening

we can just define roules and guidelines ...

**Comment by wxiaoguang** [comment]
> 1. the "package name"

Will think about it

> 2. yes if we want to follow https://docs.gitea.com/contributing/guidelines-backend#packages-list

The guideline should follow the best practice, but the refactoring and better architecture shouldn't be limited by an old guideline.

> 3. [Proposal] Gitea repository storage abstract

I have read that comment, but I didn't get the point so I asked here. That comment is only a brief idea, no details about "how to separate types into sub packages and what types should be moved out, what the new engine would look like and how would it use the old git code?"

**Comment by 6543** [comment]
to 3. :  well quite a lot is in my head ... and just need to enter the keyboard :sweat_smile: 

if there are more concerns I propose a video talk and lay out some strategik-roadmap - but for now I only see me and lunny involved int that kind of refactoring ?

**Comment by wxiaoguang** [comment]
For big refactoring, I think a document is better (ps: I also proposed similar documents when refactoring the frontend like #17149 , I think it helped)

**Comment by 6543** [comment]
will take me some time to write it ... I'm better with code that with documents

**Comment by lunny** [comment]
I can see there are two abstract layers here. One is for the file system, another is for git command result. I didn't know how this PR help the two abstract layers.

**Comment by delvh** [comment]
So, what will happen with this refactoring PR?
Will it be closed or merged?

**Comment by lunny** [comment]
> So, what will happen with this refactoring PR? Will it be closed or merged?

I think we can decide it after some changes:
- [ ] A description is necessary about the changes or considerations. The task list is too simple.
- [ ] The name `backend` maybe not a good name for an implementation of the abstract?

**Comment by 6543** [comment]
Well I'll open a new pull but it looks like a clear roadmap should be formulated first ... so 
1. I'll close this
2. create an summary issue that describes the core issue, idea and how i want to address it and the steps i like to address this part by part (this text creation will take me some time as mentioned)
3. we write some comments get a consensus, update the summary
4. actually do the parts as seperate pulls

**Pull request closed without merging**
