### PR TITLE
Use octicon-verified for gpg signatures

### PR DESCRIPTION
**Pull request by silverwind**
Before:
Screenshot 2023-03-16 at 23 40 47
Screenshot 2023-03-16 at 23 51 05

After:
Screenshot 2023-03-16 at 23 40 37
image

### CODE REVIEW

**Comment by silverwind** [comment]
Will also fix unverified state.

**Comment by delvh** [comment]
Hmm… I'm not sure if that's a good change.
I think I like the shield more.

**Comment by silverwind** [comment]
Iconology matches GitHub thought:

image

**Comment by delvh** [comment]
I know, but GitHub has always annoyed me with that.
That's why I meant I'm not sure if that's a good change.

**Comment by silverwind** [comment]
I recall introducing these icons like 1-2 years ago, previously it was a lock icon. Now I always want to slap myself when I view a commit and see the "wrong" icon I had introduced 😉.

**Review by lafriks — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping lg-tm

**Pull request merged**
