### PR TITLE
fix wrong rendering of commit detail page

### PR DESCRIPTION
**Pull request by daviian**
As title. Targets #2502

### CODE REVIEW

**Comment by Morlinest** [comment]
Can confirm, it fixes #2502. Tested on commit detail page and PR commit page.

**Comment by lafriks** [comment]
LGTM

**Comment by bkcsoft** [comment]
Got a screenshot?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
maybe provide before and after screenshot.

**Comment by lafriks** [comment]
@bkcsoft @appleboy 

Before:
image

After:
image

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
