### PR TITLE
Fix forget migration for wiki hooks (#1227)

### PR DESCRIPTION
**Pull request by lunny**
back port from #1227

### CODE REVIEW

**Comment by strk** [comment]
Adding a migration in a point release ? Is it really needed to be in 1.1.1 ? Wouldn't it confuse things (ie: which database version is in which X.Y release ?)

**Comment by lunny** [comment]
@strk this is a backport. I think it should be needed.

**Comment by andreynering** [comment]
Trusted LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Pull request merged**
