### PR TITLE
Check if column exist before rename if exist, just return with no error

### PR DESCRIPTION
**Pull request by lunny**
Some people upgrade failed because of duplicated column message on task. Don't know how it addressed, but this PR could  prevent the failed upgrade.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by wxiaoguang** [comment]
We should also drop the `errors` column if it exists.

**Comment by lunny** [comment]
> We should also drop the `errors` column if it exists.
> 
> And more comments about why we need this hacky patch.

Since it has been renamed, if `message` exist, `errors` should have been dropped.

**Comment by wxiaoguang** [comment]
But the users do meet the bug that `message` and `errors` co-exist. That's how the bug stops users from upgrading.

**Comment by lunny** [comment]
> But the users do meet the bug that `message` and `errors` co-exist. That's how the bug stops users from upgrading.

done.

**Review by wxiaoguang — APPROVED** [review]
LGTM. But I still think we had better comment this patch about `why we need it`. Otherwise developers in future will be confused why we wrote the strange logic today.

**Comment by lunny** [comment]
> LGTM. But I still think we had better comment this patch about `why we need it`. Otherwise developers in future will be confused why we wrote the strange logic today.

I will add some comments there.

**Comment by zeripath** [comment]
It's due to them running the install page when the db already exists.

**Comment by zeripath** [comment]
#17486 will prevent this issue.

It's just not been in a release.

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
