### PR TITLE
[API] indicate on user object if field provides information or not

### PR DESCRIPTION
**Pull request by 6543**
currently  "is_admin", "language", "active", "prohibit_login" and "last_login" field does return *false* information if user requesting that information is not permitted to know. With this pull that user still wont get that information but can see that there is no information ...

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
This should be a break change.

**Comment by zeripath** [comment]
Can you show me what the JSON output now looks like?

I'm concerned that this might actually be more breaking than intended. 

This may have to be the beginning of api/v2

**Comment by 6543** [comment]
that's why I marked it as proposal ...

json:
```diff
-is_admin: false
+is_admin: null
```

**Comment by zeripath** [comment]
Ok, I think instead of emitting null we should be omitting the entry.

Omitting the entry is far far less breaking and looks better.

**Comment by 6543** [comment]
@zeripath done

**Comment by zeripath** [comment]
This breaks the API. It's less breaking than before but is still a hard API break. You either have to pass a flag into the requests to switch to this or we have to create a v2 API.

**Comment by 6543** [comment]
well i think it's not that breaking that some json fields are missing - but I dont want to do api/v2

**Pull request closed without merging**
