### PR TITLE
Replaced docker docs with netlify deployment

### PR DESCRIPTION
**Pull request by tboerger**
Just to clarify the intention of this PR for those who have not been involved into the discussion. I have created an account at Netlify (a free static website hosting service including a worldwide CDN) where we want to host our website, blog, redirects and docs.

This PR enables the Drone pipeline to deploy the docs directly to Netlify, after a successful merge and build we just need to switch the DNS records.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
CI fail seems unrelated

**Comment by tboerger** [comment]
Yep, fails because of the flaky swagger stuff.

**Comment by tboerger** [comment]
@xxxtonixxx why confused? because I missed the explanation of the PR?

**Review by jonasfranz — APPROVED** [review]

**Comment by tonivj5** [comment]
@tboerger yes, thanks for clarify :+1:

**Pull request merged**
