### PR TITLE
Use "main" as default branch name

### LINKED ISSUE #19351: Set default branch name to "main" instead of "master".
### Feature Description

When creating new repos, we should no longer use the word "master" for the branch. Just like GitHub and GitLab now use "main" instead of "master" as the default initial branch name.

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

### Screenshots

image
image

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #19351

## :warning: BREAKING :warning:

This changes the the default value of `repository.DEFAULT_BRANCH` from `master` to `main`.
If some users have to use `master` as the default branch name, they should set the `DEFAULT_BRANCH` option manually in `app.ini`

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by jolheiser** [comment]
Not sure if this is "breaking", but it likely deserves a mention on the changelog/blog for any tools that are assuming default is `master`.

**Comment by Alumniminium** [comment]
why did you have to do this silly thing too

**Comment by wxiaoguang** [comment]
> why did you have to do this silly thing too? Virtue signalling is the worst.

That's nothing with `virtue signalling` IMO, that's the eco-system.

The Git community is doing so.

* GitLab https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/
* GitHub https://github.com/github/renaming

And more and more repositories and tools are using main as the default name.

Sooner or later, the main will be the default name for all git eco-system. Following the community and eco-system will reduce many pains in the future.

If you have other feasible plans, please suggest.

**Comment by jolheiser** [comment]
I am going to lock this PR. Any further discussion should happen in a new issue so it's not lost to the void.

**Pull request merged**
