### PR TITLE
Revert "[skip ci] Updated translations via Crowdin"

### PR DESCRIPTION
**Pull request by lunny**
This reverts commit cb4473692f2f9fd24a175691bae98be64abe4816.

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by yardenshoham** [comment]
Any idea what happened?

**Comment by delvh** [comment]
I guess Crowdin introduced a critical bug in their API?
Or, what could also be: Didn't @techknowlogick mention something about needing to migrate to another Crowdin API version?
Those are the only two things I can imagine…

**Review by wolfogre — APPROVED** [review]

**Comment by 6543** [comment]
I'll pause the cronjob for sync until it's fixed!

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@lunny @go-gitea/owners this wont trigger a ci as it has 'skip ci' in text ... you need to manually force merge it!

**Pull request merged**
