### PR TITLE
Rootless Docker - Mistake with the repo-avatars parent folder name

### PR DESCRIPTION
**Pull request by melroy89**
There was a mistake when choosing the structure for the repo avatars parent folder and it added a spurious /gitea.

The `data` directory should contain folders like:

  - `attachments/`
  - `avatars/`
  - `log/`
  - `repo-avatars/`

### CODE REVIEW

**Comment by wolfogre** [comment]
I would say, it's not a big mistake, it's just a mistake.

**Review by wolfogre — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> I would say, it's not a big mistake, it's just a mistake.

But if this PR gets merged, there will be the biggest mistake. You break the existing users ....

**Comment by wolfogre** [comment]
> But if this PR gets merged, there will be the biggest mistake. It breaks the existing users ....

I don't think so, the file is a template to generate the config file, and it works only if there's no config file. I think this is the only place it's used:

https://github.com/go-gitea/gitea/blob/74466eb1334386148caa50ccfd18b0f218e413d7/docker/rootless/usr/local/bin/docker-setup.sh#L47

**Comment by wxiaoguang** [comment]
> > But if this PR gets merged, there will be the biggest mistake. It breaks the existing users ....
> 
> I don't think so, the file is a template to generate the config file, and it works only if there's no config file. I believe this is the only place it's used:
> 

Yup, you are right, edited the previous comment, I worried too much (in history, some users just do re-install without app.ini and causes various problems, I think there won't be such problem any more nowadays).

**Review by lunny — APPROVED** [review]

**Comment by danger89** [comment]
This is the only folder that was left over in this wrong directory right?

Last night I did a major migration from postgresql database as well as gitea rootless migration. Which involved moving quite some directories.

So my point is; maybe there are other folder locations/configurations that also need to be updated. Or this is the last one..?

**Comment by lunny** [comment]
> This is the only folder that was left over in this wrong directory right?
> 
> Last night I did a major migration from postgresql database as well as gitea rootless migration. Which involved moving quite some directories.
> 
> So my point is; maybe there are other folder locations/configurations that also need to be updated. Or this is the last left over change..?

Looks like it's the last one in this app.ini template file.

**Comment by danger89** [comment]
I see a lot commits getting pushed into this PR? Is that intentionally? 

Or is the PR already merge into `main`?

**Comment by jolheiser** [comment]
It is when someone updates the branch from main, as we require PRs to be up-to-date before merging. It's in the list to get merged. 🙂

**Comment by zeripath** [comment]
Merged using :magic_wand: as this could not fail tests.

**Comment by zeripath** [comment]
Please send backport

**Comment by danger89** [comment]
> Merged using 🪄 as this could not fail tests.

That depends how you wrote your tests and what it is testing 😉

**Comment by danger89** [comment]
> It is when someone updates the branch from main, as we require PRs to be up-to-date before merging. It's in the list to get merged. slightly_smiling_face

I can still give feedback on this response? 

It's a good practice to use `git rebase` instead of `git merge` for this. Which gives a much cleaner result.

**Comment by delvh** [comment]
Well… not if you use `git merge --squash` like we do.

**Comment by danger89** [comment]
...then it doesn't matter indeed, it will squashed into 1 commit which will produce a new commit on the main branch.

**Comment by lunny** [comment]
> ...then it doesn't matter indeed, it will squashed into 1 commit which will produce a new commit on the main branch.

If you merge, all pull request review history(the checkbox on the files of the pull request) could be reserved. If there are many files changed on the pull request, it's very useful. But if you rebase, those history will be disappeared.

**Pull request merged**
