### PR TITLE
add missing lfs config on example file

### LINKED ISSUE #2018: LFS options missing in default app.ini
Is it intentional the the LFS options (`LFS_START_SERVER`, `LFS_CONTENT_PATH` and `LFS_JWT_SECRET`) are missing in the [app.ini](https://github.com/go-gitea/gitea/blob/master/conf/app.ini) template? They are described in the [cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/).

### PR DESCRIPTION
**Pull request by lunny**
fix #2018

### CODE REVIEW

**Review by lafriks — CHANGES_REQUESTED** [review]
Do not add jwt secret here, leave it empty!

**Comment by lunny** [comment]
@lafriks done.

**Comment by lafriks** [comment]
LGTM

**Review by lafriks — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
