### PR TITLE
add HTTPSCloneURL to settings

### PR DESCRIPTION
**Pull request by w9n**
#2428

### CODE REVIEW

**Comment by lafriks** [comment]
I don't think it is good idea as it will return different url that you are using to access UI and from outside clone url will not be usable...

**Comment by w9n** [comment]
As default I totally agree. But there are also use cases where gitea is reachable through different urls in different networks by different clients. I guess its arguable if this should be prevented by the dns service of the networks. This just gives an easy option to make the git http protocol available to one network url and all the other usages of `setting.AppURL`available by another network url.

**Comment by lafriks** [comment]
Yes but client from outside will get wrong url in this case even when accessing UI correctly

**Comment by w9n** [comment]
in my case the outside client cant use the standard git http protocol anyways, because the http port is published through a reverse proxy that does authentification. If needed only the ssh port and interface can be completly published to reduce the attack surface.

I could also set the AppURL to the internal URL, but then i would need at least a setting for the OAuth redirect url and the git protocol url (which depend on the outside url)

**Comment by lafriks** [comment]
And the problem here is that you will get inner clone url for ALL clients no matter from where you are accessing ui

**Comment by lafriks** [comment]
Sorry accidently closed :)

**Comment by w9n** [comment]
yes, thats what i want because this interface is only available for clients in the internal network. if a outside (non browser) client trys to use any git http protocol it will fail at the proxy and has to use the ssh protocol which is correctly displayed in the ui.

**Comment by lafriks** [comment]
I think it should be implemented somehow otherwise as currently it seems to be useful only in so rare cases.

**Comment by bkcsoft** [comment]
There's already the `LocalURL` that is used by anything internal (e.g. `gitea serv` => `gitea web`) 🤔

**Comment by w9n** [comment]
I tried simply setting the `LocalURL` with no success but also didnt find any documentation about the private module. Does it need to be run in a specific mode?

Drone gets the gitea URI from somewhere [here](https://github.com/drone/drone/blob/master/remote/gitea/gitea.go#L89). Im sadly still fighting with go-guru and cant find out from where the Opts paramter with the URI is comming from...

**Comment by w9n** [comment]
closed for bad design :)

**Pull request closed without merging**
