### PR TITLE
Add integration test for repository forking

### PR DESCRIPTION
**Pull request by typeless**
Add integration test for repository forking.

### CODE REVIEW

**Comment by strk** [comment]
LGTM go tests go !

**Comment by lafriks** [comment]
It would be great if after POST request it would check also forked repository GET request that is redirected to from POST request response

**Comment by typeless** [comment]
@lafriks Good idea.

**Comment by typeless** [comment]
~~Please hold on, I am working on some tests for pulls-merging which will be combined into this PR.~~
I changed my mind. I will base my follow-up PRs on this.

**Comment by lafriks** [comment]
LGTM

**Comment by andreynering** [comment]
Thank you very much

**Pull request merged**
