### PR TITLE
 Fix  install.tmpl input default value and Format index.js

### PR DESCRIPTION
**Pull request by vcaesar**
- Fix install.tmpl input default value(index.js 212-214)
- Format index.js

### CODE REVIEW

**Comment by tboerger** [comment]
The css file gets only generated via less.

**Comment by vcaesar** [comment]
Ok,I restored it.I will look more source code.

**Comment by denji** [comment]
Was questions only to unnecessary changes to whitespace.
These changes will be here #341 ([`standard-js`](https://github.com/feross/standard), [`stylefmt`](https://github.com/morishitter/stylefmt)).

I see the change:
```js
    $('#db_host').val('127.0.0.1:3306');
    $('#db_user').val('root');
    $('#db_name').val('gitea');
```

**Comment by vcaesar** [comment]
@denji  many files changed, I do not know what happened,Although I think engineering is a must.I did not see  fix install Default value.I only fix install Default value and By the way format index.js

**Comment by denji** [comment]
I see the change only spaces &:
```js
    $('#db_host').val('127.0.0.1:3306');
    $('#db_user').val('root');
    $('#db_name').val('gitea');
```

**Comment by strk** [comment]
Please don't mix functional and style changes

**Comment by vcaesar** [comment]
@strk ok,I closed pr,I only want fix install Default value,I resubmit.

**Pull request closed without merging**
