### PR TITLE
Import additional secrets via file uri

### LINKED ISSUE #25034: It should be possible to provide a file to LFS_JWT_SECRET
### Feature Description

**TLDR:** `LFS_JWT_SECRT` should be able to be stored in a separate file outlined by outlined by `LFS_JWT_SECRET_URI` 

Secrets in the `[security]` section of config allow providing both an inline secret as well as a file where the secret is stored with the `_URI` suffix.

For example
```
# /etc/gitea/app.ini
[security]
INTERNAL_TOKEN=#SOME_SECRET_VALUE

# Can be replaced by:
# /etc/bites/app.ini
[security]
INTERNAL_TOKEN_URL=/etc/gitea/secrets/internal_token

# /etc/gitea/secrets/internal_token then contains the #SOME_SECRET_VALUE
```

This allows for better installation/maintenance of Gitea, as /etc/gitea/app.ini could be stored in version control, as all secrets would be outlined separately.

## Proposal:

I propose adding a new config key `LFW_JWT_SECRET_URI` that would work the same as `INTERNAL_TOKEN_URI` by allowing users to specify a separate file where the `LFS_JWT_SECRET` is stored

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by techknowlogick**
Fixes #25034

### CODE REVIEW

**Comment by wxiaoguang** [comment]
The error message in `loadSecret` could be updated together.

image

**Comment by techknowlogick** [comment]
removed WIP as I've tested this now

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
It seems that the app.ini and cheatsheet.md should also get updates, the old `INTERNAL_TOKEN_URI` and `SECRET_KEY_URI` were documented.

**Comment by wxiaoguang** [comment]
ping~. does it need documentation?

**Pull request merged**
