### PR TITLE
Dockerfile: Support socat use cases

### PR DESCRIPTION
**Pull request by bbros-dev**
In some contexts it is necessary to provide access to Gitea via TCP ports and unix sockets.
Gitea (`gitea web`) can be configured to listen for connections via unix-socket or TCP port, but not both.
When Gitea is installed to the host this limitation can be worked around by installing socat on the host.
When running Gitea from a container this limitation cannot be workaround.

Add socat to Gitea container.

### CODE REVIEW

**Review by techknowlogick — COMMENTED** [review]
Thanks for PR, just wondering why such a specific version of socat?

**Comment by bbros-dev** [comment]
> Thanks for PR, just wondering why such a specific version of socat?

Our practice to try eliminate surprises, and socat has that versioning convention.

**Comment by lafriks** [comment]
It does not build as alpine has `1.7.3.4-r0` version currently. We should stick to same convention as other packages, either none of them with specific version or all of them :)

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by sapk** [comment]
I think we should revert this commit for security reason. 
Introducing socat could allow an attacker with a limited shell to pop a permanent two-way connection. 
The very few users that need socat can easily create a custom image based on gitea one with socat or even add a new step to the startup script to load socat on gitea image, or even simply mounting the binary, or any other method that could add socat. 
And they can do so by mitigating the risk by any mean they need.

This is not a big security risk but we shouldn't make it more easy to an attacker by default.

**Comment by 6543** [comment]
:point_up: because of #13369

**Pull request merged**
