### PR TITLE
Convert tabs to spaces in .less files

### PR DESCRIPTION
**Pull request by silverwind**
Out of the 3469 lines of code in the `.less` files, 2004 were indented with spaces while 1465 were indented with tabs. I converted all tab indendation to 4 spaces as specified in [`.editorconfig`](https://github.com/go-gitea/gitea/blob/35cc5b0402d46d672e02bbe1ad15d1460077e8f4/.editorconfig#L18-L20) using this command:

````
find . ! -type d -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' {} \;
````

If we want to use tabs in these files, I'd be open to that too, but it should be consistent and in `.editorconfig`.

### CODE REVIEW

**Comment by lafriks** [comment]
Need to resolve conflicts

**Comment by lafriks** [comment]
But otherwise LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by silverwind** [comment]
Rebased.

**Pull request merged**
