### PR TITLE
Added webkit-font-smoothing

### PR DESCRIPTION
**Pull request by Bwko**
Obsoletes #489

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
This will also close #489? But why there is no css file changes?

**Comment by Bwko** [comment]
@lunny Yes, this will close #489. I've added the css file
I've also added the missing less entry's from #530

**Comment by strk** [comment]
Ready to merge, although I don't see how this would be a `kind/bug`

**Pull request merged**
