### PR TITLE
Add changelog for 1.22.2

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by yp05327 — APPROVED** [review]

**Comment by lunny** [comment]
wait https://github.com/go-gitea/gitea/pull/31939

**Review by wolfogre — APPROVED** [review]

**Comment by silverwind** [comment]
Also might want to wait on https://github.com/go-gitea/gitea/pull/31941 because it contains a security fix.

**Comment by lunny** [comment]
wait #31944 and backport of #31931

**Comment by lunny** [comment]
Don't merge to wait more PRs.

**Comment by yp05327** [comment]
Wait #31922 ?

**Comment by lunny** [comment]
Wait backports of #31966 and #31967

**Comment by hoo29** [comment]
Will gitea actions workflow dispatch support make it into this release? https://github.com/go-gitea/gitea/pull/28163

**Comment by lunny** [comment]
> Will gitea actions workflow dispatch support make it into this release? #28163

No. That PR will be in the next big release v1.23.

**Pull request merged**
