### PR TITLE
Fix API leaking Usermail if not logged in (#25097)

### PR DESCRIPTION
**Pull request by wxiaoguang**
Backport #25097

The API should only return the real Mail of a User, if the caller is logged in. The check do to this don't work. This PR fixes this. This not really a security issue, but can lead to Spam.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
GiteaBot didn't do the backport, so backport it manually.

**Review by delvh — APPROVED** [review]

**Comment by yardenshoham** [comment]
> GiteaBot didn't do the backport, so backport it manually.

It tries backports on the next `push`

**Comment by wxiaoguang** [comment]
> > GiteaBot didn't do the backport, so backport it manually.
> 
> It tries backports on the next `push`

Sorry I didn't quite understand how it works. Could you help to explain the details? What is "next push"?

**Review by lunny — APPROVED** [review]

**Comment by yardenshoham** [comment]
> > > GiteaBot didn't do the backport, so backport it manually.
> > 
> > 
> > It tries backports on the next `push`
> 
> Sorry I didn't quite understand how it works. Could you help to explain the details? What is "next push"?

Next time a commit is pushed to `go-gitea/gitea`

**Comment by mapreri** [comment]
Hello,

I haven't tried to do a proper bisect yet, but I have reasons to suspect that this change broke the "pusher.email" field of webhooks.  With gitea 1.20.2 it had the real email address, with 1.20.3 it has the placeholder `username@noreply@domainname`.

I believe the webhook playload should not be censored by this API.  Was this an intended side-effected?

**Comment by lunny** [comment]
The email now depends on login user's permission and whether the email is public.

**Comment by JakobDev** [comment]
The E-Mail should not be shown, if you are not logged in. The Preference in your Profile only applies to logged in users.

**Comment by mapreri** [comment]
Alright, but it has always been shown in the webhooks payload, and it now
disappeared in 1.20.3, I can't imagine this being a wanted change from
this.  Besides, here it's not "being shown", it is actually being sent by
gitea to what is, one assumes, a trusted recipients for that content.

Note that, for example, emails are visible in the `commits[X].author`
field, just that that does not always cover my use case, where I need to
notify the person who actually pushed the changes.  How could I go about
this now?

Besides, the pusher.email field is even invalid now, since it has two @
signs.....

**Comment by Ibmurai** [comment]
@lunny We're having the same issue as mapreri...

We experience the issue, exclusively it seems, when creating a release/tag from the gitea frontend.

**Comment by XuluniX** [comment]
It looks like that also broke ${{gitea.event.pusher.email}} in actions.
Actions now return the same placeholder instead of the actual users email.
We need the email address to notify the user about the results of tests running in actions after a commit.

**Comment by mapreri** [comment]
(my use case is pretty much the same: the webhook invokes some code running
deployment that takes a while, and email the results to the pusher)

**Pull request merged**
