### PR TITLE
Align review-item svg octicons

### PR DESCRIPTION
**Pull request by CirnoT**
Aligns svg octicons in `review-item` properly.

Before:
firefox_2020-04-14_14-52-49

After:
firefox_2020-04-14_14-53-08

This also solves the issue where different icon types (image and svg) are not aligned

Before:
firefox_2020-04-12_20-31-58
firefox_2020-04-14_14-56-17

After:
firefox_2020-04-14_14-56-23

### CODE REVIEW

**Comment by silverwind** [comment]
I see unequal padding in that box, e.g. there's more padding below the text than on top. I think this may be elegantly solved via flexbox instead of more pixel hacks. Put the left- and right-aligned content into a flexbox with `justify-content: space-between` and make those two children another flexbox with `align-items: center` for vertical alignment.

**Comment by CirnoT** [comment]
I don't see any unequal padding after the removal of pixel hack.

**Comment by guillep2k** [comment]
Is it me or the hourglass is still slightly misaligned?

image

**Comment by CirnoT** [comment]
This is due to icon size vs `svg` element size. I am sure this can be somehow solved but I am unsure how.

**Comment by CirnoT** [comment]
> Put the left- and right-aligned content into a flexbox with justify-content: space-between and make those two children another flexbox with align-items: center for vertical alignment.

That would require significant refactoring of template, as currently both left and right aligned element are just shoved in and it's CSS job to align them (ie. the template doesn't know what should be left or right).

**Comment by silverwind** [comment]
> I don't see any unequal padding

The text line is just so slightly pushed 1 or 2 px to the top, presumably because of the icons. Proper fix will be flexbox, but I guess this is still a improvement until then.

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
as silverwind wrote ... better than nothing

**Comment by 6543** [comment]
ping lgtm

**Comment by guillep2k** [comment]
Ping LG-TM

**Pull request merged**
