### PR TITLE
Fix the color of PR comment hyperlinks.

### PR DESCRIPTION
**Pull request by rebeckanylander**
Fix issue #12995 by limiting the grey-color span up to cover the comment header only.

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Comment by mrsdizzie** [comment]
Thanks!

**Review by zeripath — APPROVED** [review]

**Review by bagasme — COMMENTED** [review]
You may want to differentiate link color between unvisited and visited link, something like:

```css
a:visited {
    color: something;
}

a:link {
    color: other;
}
```

Otherwise, ack.

**Comment by mrsdizzie** [comment]
> You may want to differentiate link color between unvisited and visited link, something like:
> 
> ```css
> a:visited {
>     color: something;
> }
> 
> a:link {
>     color: other;
> }
> ```
> 
> Otherwise, ack.

That shouldn't change (and example above would be a site wide change) and PR is good as is.

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
