### PR TITLE
Backport to 1.2: Fix sending mail with a non-latin display name

### PR DESCRIPTION
**Pull request by ptman**
https://github.com/go-gitea/gitea/pull/2559

### CODE REVIEW

**Comment by lafriks** [comment]
Can you force push to trigger drone again?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
@lafriks I trigger rebuild process manually.

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
