### PR TITLE
fix: remove `str2html` from org full name

### PR DESCRIPTION
**Pull request by appleboy**
We need to remove `str2html` from org full name.

screen shot 2017-03-25 at 9 26 16 pm

### CODE REVIEW

**Comment by lunny** [comment]
Any security consider?

**Comment by appleboy** [comment]
@lunny NO

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
I'm confused here. Are we converting the "FullName" field of an organization *TO* HTML ? Why ? I am assuming that the template framework will strip HTML tags from the input, is that correct ?

**Comment by cez81** [comment]
Same problem in tab name, see https://try.gitea.io/Test123

2017-03-25 12_32_23- lt gt amp amp - gitea_ git with a cup of tea

**Comment by appleboy** [comment]
@lunny @strk I will update this PR for security issue.

**Comment by appleboy** [comment]
@strk @lunny done. I updated origin comments.

**Comment by strk** [comment]
Now it makes sense, thank you @appleboy, LGTM

**Comment by appleboy** [comment]
@lunny Can you confirm this PR again?

**Comment by lunny** [comment]
500 when after I changed the org's name to `<a href='#'>teets</a>` and visit org home page.

**Comment by appleboy** [comment]
@lunny Can't reproduce 500 error page.

@strk Please help to test again?

**Comment by lunny** [comment]
@appleboy I can't reproduce it also. Let's merge this at first.

**Pull request merged**
