### PR TITLE
Fix commit_status problem when testing

### LINKED ISSUE #29661: Flaky test `TestMergeRequiredContextsCommitStatus`
https://github.com/go-gitea/gitea/actions/runs/8199270074/job/22424432087

```
--- FAIL: TestMergeRequiredContextsCommitStatus (0.00s)
    commit_status_test.go:62: 
        	Error Trace:	/home/runner/work/gitea/gitea/services/pull/commit_status_test.go:62
        	Error:      	Test case failed
        	Test:       	TestMergeRequiredContextsCommitStatus
        	Messages:   	Test case 4 failed
FAIL
```

### PR DESCRIPTION
**Pull request by charles7668**
Close #29661

fix #29656

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
I want to know why the CI PASS when tests in PR.

**Review by lunny — APPROVED** [review]

**Comment by charles7668** [comment]
> I want to know why the CI PASS when tests in PR.

The problem is related to the behavior of the for range loop with map structures in Go. The order of iteration is not the same every time, so not every test will fail.

**Comment by silverwind** [comment]
> > I want to know why the CI PASS when tests in PR.
> 
> The problem is related to the behavior of the for range loop with map structures in Go. The order of iteration is not the same every time, so not every test will fail.

The code itself does not depend on order, right? If it does we may need something like https://github.com/iancoleman/orderedmap.

**Comment by yp05327** [comment]
Maybe the test cases can be merged together, instead of using the index?

**Comment by charles7668** [comment]
> > > I want to know why the CI PASS when tests in PR.
> > 
> > 
> > The problem is related to the behavior of the for range loop with map structures in Go. The order of iteration is not the same every time, so not every test will fail.
> 
> The code itself does not depend on order, right? If it does we may need something like https://github.com/iancoleman/orderedmap.

Yes , it doesn't depend .

**Comment by charles7668** [comment]
> Maybe the test cases can be merged together, instead of using the index? e.g.
> 
> ```
> testCases := []struct{
>   commitStatus []*git_model.CommitStatus
>   required []string
>   expected structs.CommitStatusState
> }
> ```

This sounds like a great change. However, should I make this change in this PR? It seems like an unrelated change.

**Comment by silverwind** [comment]
I agree, let's do that in another PR.

**Pull request merged**
