### PR TITLE
replace jquery-minicolors with coloris (#30055)

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #30055 by @silverwind

Get rid of one more jQuery dependant and have a nicer color picker as well.

Now there is only a single global color picker init because that is all that's necessary because the elements are present on the page when the init code runs. The init is slightly weird because the module only takes a selector instead of DOM elements directly.

The label modals now also perform form validation because previously it was possible to trigger a 500 error `Color cannot be empty.` by clearing out the color value on labels.

Screenshot 2024-03-25 at 00 21 05
Screenshot 2024-03-25 at 00 20 48

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
Is this backport necessary? Looks like it's not a bugfix.

**Comment by wxiaoguang** [comment]
I think it needs a clear roadmap about how to refactor. I ever wrote something in https://docs.gitea.com/contributing/guidelines-refactoring

> Non-bug refactoring is preferred to be done at the beginning of a milestone, it would be easier to find problems before the release.

What I meant for `at the beginning of a milestone` is:

1. It should start at next milestone's beginning when the last release is overall stable (eg: after RC or after the first 1.22.1 or 1.22.2 with bug fixes)
2. It should start before the RC period, to avoid introduce unnecessary regressions.

----

However, since there are really a lot of frontend refactorings for 1.22 (especially when it was going into freezing time), so I think this time it is still better to merge some PRs back to 1.22, to make the future bug fixes easier to backport.

**Comment by lunny** [comment]
I think yes. We can backport some necessary to fix bugs easier but that needs case by case. I will not block this one if you think it's necessary.

**Comment by silverwind** [comment]
I do think it's a necessary enhancement 😆

**Comment by silverwind** [comment]
Can skip this one.

**Pull request closed without merging**
