### PR TITLE
Get repo list with OrderBy alpha should respect owner too

### PR DESCRIPTION
**Pull request by 6543**
instead of:
- zowner/gcode
- awesome/nul
- zowner/nul
- zowner/zzz

we will get:
- awesome/nul
- zowner/gcode
- zowner/nul
- zowner/zzz

### CODE REVIEW

**Comment by lunny** [comment]
Maybe we should have both? For dashaboard repositories, this order is better. But for explore, maybe order by repository name is better?

**Comment by silverwind** [comment]
Hmm I think I prefer new order in both cases.

**Review by silverwind — APPROVED** [review]

**Comment by 6543** [comment]
> Maybe we should have both? For dashaboard repositories, this order is better. But for explore, maybe order by repository name is better?

no at the moment it's just **random** if you want to sort in explore! - and for single owner lists this does not have any effect so we are fine there too

**Comment by 6543** [comment]
@lunny PS: all other sort types are not affected at all ... so the pull request i cherry picked it form dose not have anything to do with this bugfix. in the end its just a bugfix :)

**Comment by lunny** [comment]
What's pages will this change affect? I have tested locally on explore -> repositories -> sort=alphabetically and looks no any affection. Looks like there is a bug here, the code expect `alpha` but the URL parameter is `alphabetically`. Can you do a manual test in your local machine to confirm that?

**Comment by 6543** [comment]
sore

**Review by lunny — APPROVED** [review]
Looks like this change will only affect the dashboard right sidebar's repositories sequences and related APIs but not other places. But I'm confused as to why there is the sort parameter. Looks like it will only be used by API.

**Comment by 6543** [comment]
yes i can confirm, it's only used at the repo search api and the web route for repo search that the dashbord explicite use ...

PS: we might refactor other repo search code paths to use that ... but thats not a bugfix but a refactoring then :)

so i can confirm it

**Comment by 6543** [comment]
@lunny -> https://github.com/go-gitea/gitea/pull/30876/files#r1591176082

**Pull request merged**
