### PR TITLE
bump go-deps (#27489)

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #27489 by @techknowlogick

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]

**Comment by silverwind** [comment]
@techknowlogick failure related to `go-cron` update?

```
--- FAIL: TestAddTaskToScheduler (0.00s)
    tasks_test.go:38: 
        	Error Trace:	/home/runner/work/gitea/gitea/services/cron/tasks_test.go:38
        	Error:      	Not equal: 
        	            	expected: "task 2"
        	            	actual  : "task 1"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-task 2
        	            	+task 1
        	Test:       	TestAddTaskToScheduler
    tasks_test.go:39: 
        	Error Trace:	/home/runner/work/gitea/gitea/services/cron/tasks_test.go:39
        	Error:      	Not equal: 
        	            	expected: "30 5 4 * * *"
        	            	actual  : "5 4 * * *"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-30 5 4 * * *
        	            	+5 4 * * *
        	Test:       	TestAddTaskToScheduler
```

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27511 may fix it.

**Comment by techknowlogick** [comment]
@silverwind thanks for the PR, are you able to push your cron changes directly to this PR? (If not I can in a few hours)

**Comment by silverwind** [comment]
Pushed the downgrade.

**Comment by techknowlogick** [comment]
Thanks @silverwind 🙏

**Pull request merged**
