### PR TITLE
Expose the OpenID registration setting at install time

### PR DESCRIPTION
**Pull request by strk**
See #1363

To be honest, I don't really like this even myself :P

### CODE REVIEW

**Comment by strk** [comment]
Ok don't merge this, I got a better idea.

**Comment by strk** [comment]
So  @Schnouki I'm thinking that at installation time you'd still ony have a DISABLE_REGISTRATION setting, then at runtime you should be able to override it for *just* openid anyway, but by not specifying an explicit setting for it it owuld default to whatever the global specified.

**Comment by strk** [comment]
Uhm, my idea is problematic because the DisableRegistration config variable is read in a *different* function than the place where EnableOpenIDRegistration is read.

**Comment by lunny** [comment]
Why we need another option to disable OpenID registered?

**Comment by strk** [comment]
@lunny because some admins want to keep registration open only for those who can provide a valid OpenID identity

**Comment by strk** [comment]
Ok see #1369 for an implementation of that idea of mine

**Pull request closed without merging**
