### PR TITLE
Reduce number of docker pulls on ci

### PR DESCRIPTION
**Pull request by silverwind**
Should reduce errors like https://drone.gitea.io/go-gitea/gitea/32989/7/2 by only pulling each distinct image once per pipeline. Also remove useless `pull: default` entries.

### CODE REVIEW

**Review by techknowlogick — COMMENTED** [review]
On ARM64 it is ok if we do pull always as we are paying for a pro dockerhub account, and have credentials passed, however as amd64 is auto scaled I haven’t setup credentials for those as they usually only last up to 1 hour.

**Comment by silverwind** [comment]
>  it is ok if we do pull always

I guess it's still pointless to pull the same image twice in a pipeline, even if we have no limit.

**Comment by zeripath** [comment]
I think our integration tests take so long that anything that makes them take a shorter time has to be good.

**Comment by techknowlogick** [comment]
But we aren't truly pulling each time, rather it does a docker pull and checks if there is a new image and if not carries on as per usual. This is useful for us as we tag for ex. Golang:1.15 which "auto updates" on every minor version change so we don't need many maintenance updates to increase minor version

**Comment by silverwind** [comment]
The only downside here is that one needs to carfully check where a image first occured in a pipeline, so it's a bit more work than just using `pull:always` everywhere.

**Comment by silverwind** [comment]
@techknowlogick that should still be happening. All this PR does it eliminate subsequent pulls of the same image in the same pipeline.

**Comment by techknowlogick** [comment]
Ah I missed that. Thanks for clarifying:)

**Review by techknowlogick — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
