### PR TITLE
Show ssh command directly in template instead of i18n translation

### PR DESCRIPTION
**Pull request by junjieyuan**
Signed-off-by: Junjie Yuan <yuan@junjie.pro>

If missing space, ssh-keygen will report "Too few arguments for sign: missing namespace" and failed to generate ssh token.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Translations are maintained by https://crowdin.com/translate/gitea/68/enus-zhcn , the edits on these locale files will be overwritten by the crowdin translations. 

So you can submit the translations at crowdin.

**Comment by junjieyuan** [comment]
> Translations are maintained by https://crowdin.com/translate/gitea/68/enus-zhcn , the edits on these locale files will be overwritten by the crowdin translations.
> 
> So you can submit the translations at crowdin.

Hello, @wxiaoguang. Can you submit new translations for me? I don't plan to sign up for a Crowdin account right now. Thanks!

**Review by wxiaoguang — APPROVED** [review]
This ssh command shouldn't use i18n translation. So I just edited on your PR directly, show the command directly in the tmpl

**Comment by junjieyuan** [comment]
> This ssh command shouldn't use i18n translation. So I just edited on your PR directly, show the command directly in the tmpl

Thank you for your help!

**Review by delvh — APPROVED** [review]

**Pull request merged**
