### PR TITLE
Use tailwind instead of `gt-[wh]-` helper classes

### PR DESCRIPTION
**Pull request by lunny**
Follow #29357 
- Replace `gt-w-*` -> `tw-w-*` and remove `gt-w-*`
- Replace `gt-h-*` -> `tw-h-*` and remove `gt-h-*`

### CODE REVIEW

**Comment by silverwind** [comment]
Remove `gt-w-full` from helpers.css if there are no more occurences. We can do more such migrations in one PR, does not have to be 1 property per PR.

**Comment by silverwind** [comment]
> I agree with removing the helper class, but I disagree with more than one property per PR. From my previous experience, the smaller and easier a PR can be reviewed, the faster it will be merged, as we've seen with the jQuery removal.

Fine with me in any case.

**Comment by wxiaoguang** [comment]
> I agree with removing the helper class, but I disagree with more than one property per PR.

Similar classes could be done in the same PR. eg: `gt-w-* / gt-h-*` to `tw-w-* / tw-h-*`

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
> I agree with removing the helper class, but I disagree with more than one property per PR. From my previous experience, the smaller and easier a PR can be reviewed, the faster it will be merged, as we've seen with the jQuery removal.

I did some of them because the previous changes are too small. I think it's still small enough to be reviewed.

**Review by wxiaoguang — DISMISSED** [review]
https://github.com/go-gitea/gitea/pull/29423#issuecomment-1964060005

Without `!important`, `tw-*` might not work in some cases.

**Comment by delvh** [comment]
https://tailwindcss.com/docs/configuration#important

**Comment by delvh** [comment]
The config option is intended exactly for our usecase:
Introducing tailwind to an existing system.

**Comment by silverwind** [comment]
> The config option is intended exactly for our usecase: Introducing tailwind to an existing system.

Yes, it's equivalent to adding the `!` on all classes, but the class prefix gives the option to later remove it on a per-case basis. I'm not sure yet what way would be better for us.

**Comment by wxiaoguang** [comment]
Then it needs to test every change carefully. To see whether it needs `!important`.

Otherwise, `gt-` can't be replaced by `tw-` directly, because some `!important` is used to "fine tune" the existing styles.

So what do you think about these possible approaches?

1. Test every change when replacing `gt-` to `tw-`, only use `!` when necessary
2. Replace all `gt-` to `!tw-`
3. Add `!important` to all `tw-`

**Comment by silverwind** [comment]
👍 and 🚀 are both acceptable for me. 🎉 would be too limiting long-term.

**Comment by wxiaoguang** [comment]
Sorry but it is not really fully tests. At least, I can see:

```
ui container center tw-w-screen

.page-content .ui.ui.ui.container:not(.fluid) {
  width: 1280px;
  max-width: calc(100% - 64px);
  margin-left: auto;
  margin-right: auto;
}

```

**Comment by wxiaoguang** [comment]
> Assuming @lunny has tested the cases here, this PR would be an example of an ideal 👍 where all `!important` are removed.

If we would like to avoid regression, then we can't assume anything.

If we would like to tolerate some regressions, then maybe the rule could be relaxed.

**Comment by silverwind** [comment]
> If we would like to avoid regression, then we can't assume anything.

Yes, that' why I redacted my review actually 😆.

**Comment by wxiaoguang** [comment]
> I'm starting leaning towards option 3 actually, the only downside is that the CSS would end up a few bytes bigger because of all these `!important` strings, but it will compress well.

That's also my first preference. But I guess few people would agree with it if I said so 😁 so I spent some more time on "finding bugs".

**Review by delvh — APPROVED** [review]
LGTM apart from the pending rewrite to the chosen important mechanism

**Comment by silverwind** [comment]
I strongly believe 🎉 is the way to go now. Developers should not have to worry about CSS precedence when using a atomic CSS framework like tailwind.

**Comment by silverwind** [comment]
> I strongly believe 🎉 is the way to go now. Developers should not have to worry about CSS precedence when using a atomic CSS framework like tailwind.

https://github.com/go-gitea/gitea/pull/29437 for this.

**Comment by wxiaoguang** [comment]
After #29423 , I think it is safe to use `tw-` to replace `gt-` directly now.

**Review by wxiaoguang — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
