### PR TITLE
SetDefaultBranch on pushing to empty repository

### LINKED ISSUE #7601: Setting "Default Branch" does not update the symbolic ref in .git/HEAD
- Gitea version (or commit ref): 1.8.3
- Git version: 2.17.2
- Operating system: Amazon Linux 2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/vg-c/testdefaultbranch)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When a repository uses a default branch whose name is not "master", Gitea still maintains the .git/HEAD file with the content: "ref: refs/heads/master", and even if you try to explicitly set or update the default branch using the Settings/Branches page, it does not change the content of the HEAD file. Consequently, when you try to clone such a repository on your local machine, you get a warning from git: "warning: remote HEAD refers to nonexistent ref, unable to checkout." and then you have to explicitly checkout the default branch of the repository.

Exact steps to reproduce the issue are given below (tested and confirmed on https://try.gitea.io/vg-c/testdefaultbranch):

$ mkdir testdefaultbranch
$ cd testdefaultbranch
$ git init
$ touch README
$ git add README
$ git commit
$ git branch -m master newbranch
$ git branch -vv
* newbranch e2b1ee7 init commit
$ cat .git/HEAD
ref: refs/heads/newbranch

$ git remote add origin https://try.gitea.io/vg-c/testdefaultbranch.git
$ git push -u origin newbranch
...
Counting objects: 3, done.
Writing objects: 100% (3/3), 192 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://try.gitea.io/vg-c/testdefaultbranch.git
 * [new branch]      newbranch -> newbranch
Branch newbranch set up to track remote branch newbranch from origin.

$ cd ..
$ mkdir t
$ cd t
$ git clone https://try.gitea.io/vg-c/testdefaultbranch.git
Cloning into 'testdefaultbranch'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.

$ cat testdefaultbranch/.git/HEAD 
ref: refs/heads/master

### PR DESCRIPTION
**Pull request by zeripath**
Set the default branch for empty repositories to be the first branch that is pushed to. 

Fixes #7601

### CODE REVIEW

**Review by vg-c — CHANGES_REQUESTED** [review]
Hi zeripath,

Thank you for this patch. But it would only address the initial push no? Is it also possible to make the explicit action of setting the default branch in the Settings page also do the same for an existing/non-empty repository?

**Comment by zeripath** [comment]
That should already happen:

https://github.com/go-gitea/gitea/blob/2af67f6044af1cad7136ce8c123e37ab090ca9bc/routers/repo/setting_protected_branch.go#L72

**Comment by vg-c** [comment]
Apologies if I have misunderstood what's going on, but isn't one point in my bug report that setting the default branch explicitly does not change the actual value inside the .git/HEAD file?

**Comment by zeripath** [comment]
What a local clone of a repository has as its default branch has nothing to do with what the default branch on the remote should be - and in fact the remote never gets told what the local repository thinks is the default. In the case of using a push to initialise an empty repository it may make sense to set the default branch to the first branch that's pushed - however, this may be incorrect and I may have missed something (meaning that this PR is incorrect.)

You can change the default branch on the repository settings page.

**Comment by vg-c** [comment]
The .git/HEAD file that I'm talking about is on the REMOTE server repository - I have confirmed that the .git/HEAD file on the server itself is erronous becuase I have shell access to the Gitea installation that I use.

**Comment by zeripath** [comment]
Yes, I understand that the HEAD is on the server. 

Try the following on your local machine from a temporary directory:

```
git init --bare push-to.git
git init to-push
cd to-push
touch README
git add README
git commit -a -m'Add Readme'
git branch -m master newbranch
git remote add origin ../push-to.git
git push -u origin newbranch
cd ..
git clone push-to.git to-clone
```

Git push does not tell origin that HEAD should be something else.

**Review by lunny — APPROVED** [review]

**Review by richmahn — APPROVED** [review]

**Pull request merged**
