### PR TITLE
Added support for gopher URLs.

### LINKED ISSUE #14748: Can't enter gopher hole in profile
I would like to put a link to my gopher hole in the website section of my profile. However, when I enter its URL, it tells me that it's not a valid URL because is starts with `gopher://`.

### PR DESCRIPTION
**Pull request by 4y8**
Close  #14748

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
I don't know that this would be the right place for this check, as I believe it is used for the HTTP client which can fetch via these schemes.

**Comment by jolheiser** [comment]
> I don't know that this would be the right place for this check, as I believe it is used for the HTTP client which can fetch via these schemes.

True that it could certainly be used elsewhere. 

-----

To be more specific from my response in the issue, the binding rule is defined here and simply leverages this func
https://github.com/go-gitea/gitea/blob/9c5bb2b23760c8300060c80a68fe9c880b6e4c36/modules/validation/binding.go#L82-L98

However, it is good to point out that this affects all `ValidUrl` bindings.

**Comment by yul3n** [comment]
So for the profile the function is used here:
https://github.com/go-gitea/gitea/blob/afbddf1f0e93cf8b38a7244dfd434b448c81037d/modules/forms/user_form.go#L212-L221
Maybe the check `ValidUrl` could be removed or replace by something like `ValidSite` which would be more permissive.

**Comment by zeripath** [comment]
OK I've switched this to make this a) Server settable so the server host can decide if they allow http/https or additionally gopher etc.

**Comment by zeripath** [comment]
I'm not sure how common this kind of setting would be used. @4y8 why do you need gopher urls as your website?

**Review by techknowlogick — APPROVED** [review]

**Comment by 4y8** [comment]
@zeripath Because when I created this PR and the associated issue, my main website was on gopher. And I guess that other people use non-http protocol like gopher or gemini.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
