### PR TITLE
Redirect to the commit page after applying patch

### LINKED ISSUE #22621: 404 Response after successfully applying patch from diff file
### Description

When applying a patch (via code tab -> Add File -> Apply Patch) the patch is applied correctly, but the server responds with a 404. The after creating the patch commit the redirect that 404s is for USER/REPOSITORY/branch/main/diff.patch, which does not exist of course.

I could reproduce it here:
https://try.gitea.io/pahofmann/patch-404-test/
After I applied the patch I was redirected to https://try.gitea.io/pahofmann/patch-404-test/src/branch/main/diff.patch

### Gitea Version

1.18.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/pahofmann/fb2c2e9daa8ff8d2c846b85e1eca3598

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Fresh setup in container.

### Database

SQLite

### PR DESCRIPTION
**Pull request by yp05327**
Fixes https://github.com/go-gitea/gitea/issues/22621

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Please resolve the conflicts

**Comment by yp05327** [comment]
> Please resolve the conflicts

Done.

**Review by wolfogre — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Comment by zeripath** [comment]
please send backport

**Pull request merged**
