### PR TITLE
Improve swagger doc

### PR DESCRIPTION
**Pull request by sapk**
All is in the title

Need go-gitea/go-sdk#67

### CODE REVIEW

**Comment by sapk** [comment]
This is just comments, so it could make it in 1.2.0 without effect.

Edit: This will update sdk package that added `issue_tracked_time.go` but I don't think this will have a big impact.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@sapk if it's in time, I will move this to v1.2

**Comment by sapk** [comment]
@lunny I updated go-gitea/go-sdk#67. I will sync this when sdk is merged.

**Comment by lunny** [comment]
@sapk go-gitea/go-sdk#67 merged.

**Comment by sapk** [comment]
sdk updated and swagger re-generated.
PR is ready to be merged

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
