### PR TITLE
Fix issue where ecdsa and other key types are not synced from LDAP (#5092)

### PR DESCRIPTION
**Pull request by xor-gate**
Implements #5092 

Currently LDAP sync support only `ssh` prefixed keytypes, so other keytypes are simply ignored. This PR improves the check by using the native parsing of the public authorized key line. I tried to find out to add a test ecdsa key but not sure where to place it.

I think this are only the calculated fingerprints:

https://github.com/go-gitea/gitea/blob/master/integrations/auth_ldap_test.go#L43-L46

Based on this

https://github.com/go-gitea/gitea/blob/master/integrations/api_admin_test.go
or this
https://github.com/go-gitea/gitea/blob/master/integrations/api_keys_test.go

I would like some advice on the test, as it is highly valuable.

### CODE REVIEW

**Review by adelowo — APPROVED** [review]

**Comment by xor-gate** [comment]
Could somebody help me out how to test this case?

**Comment by lunny** [comment]
@xor-gate drone CI has LDAP service by @lafriks, maybe you can test with it.

**Comment by xor-gate** [comment]
Yes I understand, I had a look at the CI some time ago. We should add at least an ecdsa key to the LDAP server test image then. At here https://github.com/go-gitea/test-openldap/blob/master/bootstrap/data/10_people_hermes.ldif#L24

**Comment by xor-gate** [comment]
I have added an ecdsa key to the test-openldap image as PR.

**Comment by lafriks** [comment]
@xor-gate feel free to submit PR to add key to that test ldap server

**Comment by xor-gate** [comment]
I updated the PR with the latest changes from master https://github.com/go-gitea/gitea/commit/e2292c7a1c42e024ed6da313fac91228c2a31746 seems master has broken CI build: https://drone.gitea.io/go-gitea/gitea/3652/10

**Comment by lafriks** [comment]
@xor-gate you need to update tests as more ssh keys are now returned from ldap in test `TestLDAPUserSSHKeySync`

**Comment by xor-gate** [comment]
@lafriks finaly the ldap integration test passes now horay 👍 gives me more trust with the added test key

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
