### PR TITLE
Migration to fix existing owner team units

### LINKED ISSUE #1797: Transfer ownership of private repository to Organization HTTP404
- Gitea version (or commit ref): ff2464c 
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes

## Description
I did this on try.gitea.io:
1. Make an Organization (AvalancsOrg)
2. Make a private repository (TestRepo)
3. Go to Settings
4. Transfer Ownership to the Org (AvalancsOrg)
5. Try to access the repository from the dashboard

Step 5 causes a HTTP404 to be shown istead of opening the repository. I did not push anything into the repository, so it should be empty. 

## Screenshot
The dashboard shows the transfer of the repository as my last step
ava_issue

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #1797 for pre-existing organizations.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by camlafit** [comment]
Hi

Sorry doesn't look enough :/ 
I've just compiled from master

```
2017/06/06 17:49:38 [I] Migration: add user openid table
2017/06/06 17:49:41 [I] Migration: change the key_id and primary_key_id type
2017/06/06 17:49:48 [I] Migration: add show field in user openid table
2017/06/06 17:49:48 [I] Migration: generate and migrate repo and wiki Git hooks
2017/06/06 17:49:52 [I] Migration: change mirror interval from hours to time.Duration
2017/06/06 17:49:53 [I] Migration: add field for repo size
2017/06/06 17:49:53 [I] This migration could take up to minutes, please be patient.
2017/06/06 17:50:16 [I] Migration: add commit status table
2017/06/06 17:50:18 [I] Migration: add primary key to external login user
2017/06/06 17:50:21 [I] Migration: add field for login source synchronization
2017/06/06 17:50:22 [I] Migration: add units for team
2017/06/06 17:50:22 [I] Migration: remove columns from action
2017/06/06 17:51:25 [I] Migration: give all units to owner teams
2017/06/06 17:51:36 [I] Git Version: 2.1.4
2017/06/06 17:51:37 [I] Run Mode: Production
2017/06/06 17:51:37 [I] Listen: http://0.0.0.0:3001
2017/06/06 17:52:10 [...routers/repo/view.go:270 Home()] [E] Home: Cannot find any unit on this repository which you are allowed to access
```

**Comment by ethantkoenig** [comment]
@camlafit Are you logged in as an owner of the organization whose repo you're trying to view?

**Comment by camlafit** [comment]
It's an admin account and set in owner team

**Pull request merged**
