### PR TITLE
Use raw Wiki links for non-renderable Wiki files

### LINKED ISSUE #27121: Wiki: Files are not downloadable
### Description

I tried to provide some files in the wiki via the link markdown

So I cloned the repo, I added a new folder, added the files and linked them as described [here](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2)

When you click the link, the wiki opens a new page

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

None

### PR DESCRIPTION
**Pull request by rafaelsgirao**
In Wiki pages, short-links created to local Wiki files were always expanded as regular Wiki Links. In particular, if a link wanted to point to a file that Gitea doesn't know how to render (e.g, a .zip file), a user following the link would be silently redirected to the Wiki's home page.

This change makes short-links* in Wiki pages be expanded to raw wiki links, so these local wiki files may be accessed without manually accessing their URL.

* only short-links ending in a file extension that isn't renderable are affected.

Closes #27121.

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for this PR! The CI is failing for unrelated reasons, but will hopefully start passing once an upstream change is resolved. Maintainers are still able to run tests locally, so don't worry about any delay in reviewing :)

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by tropappar** [comment]
This breaks links to markdown files containing a dash -

**Comment by silverwind** [comment]
Please open an issue with steps to reproduce.

**Comment by wxiaoguang** [comment]
Bug report:  Regression - after update to 1.22 wiki links to wiki pages with hyphens or dots in the name only return plain text #31395

**Comment by wxiaoguang** [comment]
->  Fix rendered wiki page link #31398

**Comment by wxiaoguang** [comment]
This change needs to be reverted or re-designed.

It still causes regression #31395 : wiki pages like `meeting on 2024.07.01` is incorrectly considered as "raw" media.

**Comment by wxiaoguang** [comment]
ps: I don't have time to work on Gitea at the moment. So if anyone has interest, feel free to fix or revert.

**Pull request merged**
