### PR TITLE
Upgrade to golang-jwt 3.2.2

### PR DESCRIPTION
**Pull request by zeripath**
Upgrade to the latest version of golang-jwt.

* Forcibly update the vendored versions too
* Update our minimal go lang version to 1.16

Signed-off-by: Andrew Thornton <art27@cantab.net>

### :warning: BREAKING :warning: 

This PR raises the minimal version of go supported to 1.16 which will mean the end of support of 32-bit Mac and Mac OS versions before Sierra.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Argh this new version of jwt has increased the required version of golang.

**Comment by techknowlogick** [comment]
> Argh this new version of jwt has increased the required version of golang.

w/ Golang 1.17 right around the corner we can bump our min version of go to 1.16, although for Gitea 1.15 and below I suspect using your fork of golang-jwt to achieve that compatibility with the versions of golang that we support.

**Comment by techknowlogick** [comment]
One tiny nit, can the makefile and docs config be updated to note the new minimum go version required?

**Comment by zeripath** [comment]
> One tiny nit, can the makefile and docs config be updated to note the new minimum go version required?

makefile done but where in the `docs config`?

**Comment by jolheiser** [comment]
> > One tiny nit, can the makefile and docs config be updated to note the new minimum go version required?
> 
> makefile done but where in the `docs config`?

https://github.com/go-gitea/gitea/blob/80b7889fee833d4d80c5581dc182b4a499b4bad4/docs/config.yaml#L22

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
