### PR TITLE
Update outdated Go toolchain version for .drone.yml

### PR DESCRIPTION
**Pull request by typeless**
Other CI pipelines already use Go1.11. So, we update this one too.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by adelowo — APPROVED** [review]

**Comment by lafriks** [comment]
Nooooo.... Please send PR to change it back as it was intentionally left this way to test if gitea builds with lowest supported golang toolchain version

**Comment by lunny** [comment]
@lafriks for Gitea v1.7 maybe we should change the lowest go version from go1.9 to go1.11 for using go modules?

**Comment by lafriks** [comment]
@lunny probably but this change should come also with that migration to go modules and updated docs

**Comment by lunny** [comment]
OK

**Pull request merged**
