### PR TITLE
Add migration to set IsArchived false if it is null

### LINKED ISSUE #11824: Repository listing filter broken after upgrading from gogs 0.11.91 to gitea 1.12.0-rc2
- Gitea version (or commit ref): 0.12.0-rc2
- Git version: 2.20.1
- Gogs version: 0.11.91
- Operating system: Debian Buster (stable with all current updaes installed)
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

After migrating from gogs 0.11.91 to gitea 1.12.0-rc2 the "Repositories" list to the right is broken. It was still working with 1.11.6. It seems to be a filtering issue: if I select archived (✓) or not archived (-) it works - with the empty checkbox (which should list both archived and non-archived) I get an empty list as per the attached screenshot.

Steps taken for the migration:
* stop gogs
* create a new minimal app.ini
* set DB version to 13 as per #5318
* start gitea 1.6.4 (since #5318 seems to imply this is supported without going through previous versions)
* sop gitea
* start gitea 1.11.6 (with #10026 dropping migrations from before 1.6.x in current code that to me implies going from 1.6.4 to 1.11.6 should be safe)
* Run "Reinitialize all missing Git repositories for which records exist"
* Remove gogs hooks: find $REPO_DIR -path \*-receive.d/\*-receive -delete (see #3558 for Details)
* Run "Resynchronize pre-receive, update and post-receive hooks of all repositories" (or PRs will break #8208)
* stop gitea
* start gitea 1.12.0-rc2

## Screenshots

gitea-repositories-empty

### PR DESCRIPTION
**Pull request by zeripath**
Fix #11824

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
I've set this as backport as I believe that we can still do this.

**Comment by 6543** [comment]
@zeripath I think this is a task for doctor?

**Comment by 6543** [comment]
(DB Consistency)

**Comment by techknowlogick** [comment]
Sadly we cannot backport this migration due to KeepActivityPrivate migration not being present in 1.12

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
I guess we add it to doctor then.

**Comment by 6543** [comment]
Is models/migrations/v142.go migration still needed?

**Comment by techknowlogick** [comment]
Yes, as it means that users don't have to run doctor.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
I would still add the backport lable since we can partialy backport the doctor part

**Comment by techknowlogick** [comment]
ping LG-TM

**Comment by techknowlogick** [comment]
@zeripath please backport docker changes :)

**Pull request merged**
