### PR TITLE
Remove unused commit

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by 6543** [comment]
It schould be used

**Comment by lunny** [comment]
> It schould be used

No. All transaction begin in the loop and commit end in the loop. This commit is out of the loop and no related begin invoked.

**Comment by 6543** [comment]
@lunny this commit is only for https://github.com/go-gitea/gitea/pull/14741/files#diff-2729db0e3433a55764350519b9ea1640501f848b666f5accb4e68635aef9ce86R108-R112

**Comment by lunny** [comment]
For a single SQL, claim a transaction is unnecessary. And even if you want to do that, you need a `Begin` before `Update`.

**Comment by 6543** [comment]
@lunny we should then apply this:
```diff
diff --git a/models/migrations/v166.go b/models/migrations/v166.go
index 3d6cf4f57..c26f29da6 100644
--- a/models/migrations/v166.go
+++ b/models/migrations/v166.go
@@ -106,7 +106,7 @@ func recalculateUserEmptyPWD(x *xorm.Engine) (err error) {
        }
 
        // delete salt and algo where password is empty
-       if _, err = sess.Where(builder.Eq{"passwd": ""}.And(builder.Neq{"salt": ""}.Or(builder.Neq{"passwd_hash_algo": ""}))).
+       if _, err = x.Where(builder.Eq{"passwd": ""}.And(builder.Neq{"salt": ""}.Or(builder.Neq{"passwd_hash_algo": ""}))).
                Cols("salt", "passwd_hash_algo").Update(&User{}); err != nil {
                return err
        }
```

**Review by 6543 — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]
just a small nit: https://github.com/lunny/gitea/pull/13

**Review by 6543 — APPROVED** [review]

**Pull request merged**
