### PR TITLE
Correctly rollback in ForkRepository

### PR DESCRIPTION
**Pull request by zeripath**
The rollback functionality in
services/repository/repository.go:ForkRepository is incorrect and could
lead to a deadlock as it uses DeleteRepository to delete the rolled-back
repository - a function which creates its own transaction.

This PR adjusts the rollback function to only use RemoveAll as any
database changes will be automatically rolled-back. It also handles
panics and adjusts the Close within WithTx to ensure that if there is a
panic the session will always be closed.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
While I can completely understand the implementation,
adding a test might be beneficial here so that this potential deadlock does not occur again sometime else.

**Review by axifive — APPROVED** [review]

**Comment by zeripath** [comment]
> While I can completely understand the implementation,
> adding a test might be beneficial here so that this potential deadlock does not occur again sometime else.

I don't think it's testable. The deadlock could only happen if there was an error whilst creating the fork, even then it would only occur extremely randomly. We can't force an error, we can't force the deadlock. Even if we had a fully mocked up xorm we'd have to code in what it means to deadlock.

There some very complex solutions that could help reduce the risk of these errors in future but they'd come with their own issues too. 

If you can think of a test then I'm happy to discuss.

**Comment by delvh** [comment]
That is unfortunately correct.
The only thing we could test is whether it behaves correctly under normal circumstances.

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
