### PR TITLE
Private issues comments shouldn't be in the public activity feed

### PR DESCRIPTION
**Pull request by nounoursheureux**
Fix gogits/gogs#1112

### CODE REVIEW

**Comment by tboerger** [comment]
That's all that needs to be fixed?

**Comment by nounoursheureux** [comment]
Yes :ok_hand:

**Comment by tboerger** [comment]
I have nit tested it but LGTM

**Comment by lunny** [comment]
Is this pull request cannot be merged automatically?

**Comment by tboerger** [comment]
@nounoursheureux please do a force push to trigger travis again. As far as i can see it's not directly related to this PR.

**Comment by da-kid** [comment]
@tboerger ^ Can be merged.Please do so.

**Comment by da-kid** [comment]
Thank you!

**Pull request merged**
