### PR TITLE
fix pulls broken when fork repository deleted

### LINKED ISSUE #6702: Panic when viewing pull requests on a repo with a deleted fork
- Gitea version (or commit ref): b83114f1407247415b184f77f8f2f6ecea8cb994
- Git version: 2.21.0
- Operating system: Linux (openSUSE Tumbleweed)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/ollien/bad-pr-target/pulls 
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/ollien/6f09291db568d30ad2ae69969357dba0

## Description
1. Create a repository.
2. Fork that repository as another user.
3. Make a PR to the original repository.
4. Delete the fork.
5. The `/pulls` page of the original repo will now 500

### PR DESCRIPTION
**Pull request by lunny**
fix #6702

### CODE REVIEW

**Comment by lafriks** [comment]
Drone fail

**Review by adelowo — APPROVED** [review]

**Comment by lafriks** [comment]
Where does it check for this new error?

**Comment by lunny** [comment]
@lafriks `GetLastCommitStatus` now will check if the headRepo exist or not, and will return  new error `ErrPullRequestHeadRepoMissing`. The panic caused by unchecked `headRepo` nil.

**Comment by lafriks** [comment]
But shouldn't we check later for that error and show some kind of error in PR?

**Comment by lunny** [comment]
When list pull requests, the last commit status error could be ignored.

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
v1.8 don't have this problem.

**Comment by ntimo** [comment]
Is this going to be backported to 1.8? :)

**Comment by lunny** [comment]
v1.8 should not be affected by this issue.

**Pull request merged**
