### PR TITLE
Add Primary Key to Topic and RepoTopic tables

### LINKED ISSUE #8920: Add primary key to repo_topic table
- Git version: 1.9.5
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In MySQL group replication, it is mandatory to that every table has primary key. Gitea schema has repo_topic table that does not have primary key. Please consider adding pk also to that table.
https://dev.mysql.com/doc/refman/8.0/en/group-replication-requirements.html

Currently gitea runs fine in group replicated mysql instance, but for obvious reasons I can't alter repo topics.

### LINKED ISSUE #12061: Upgrade from 1.11.6 to 1.12.1 fails (MySQL 8 Innodb cluster)
- Gitea version (or commit ref): 1.12.1
- Git version:  1.8.3.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

When trying to start up binary version 1.12.1, it fails with following messages in gitea.log
```

2020/06/26 11:21:34 ...ations/migrations.go:300:Migrate() [I] Migration[126]: Fix topic reposito
ry count
2020/06/26 11:21:34 ...m.io/xorm/core/db.go:277:ExecContext() [I] [SQL] DELETE FROM `repo_topic`
 WHERE `repo_id` NOT IN (SELECT `id` FROM `repository`) [] - 496.336µs
2020/06/26 11:21:34 routers/init.go:77:initDBEngine() [E] ORM engine initialization attempt #9/1
0 failed. Error: migrate: do migrate: Error 3098: The table does not comply with the requirement
s by an external plugin.
2020/06/26 11:21:34 routers/init.go:78:initDBEngine() [I] Backing off for 3 seconds
2020/06/26 11:21:37 routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #10/
10...
```

Since I run gitea on mysql 8 innodb cluster, then best bet is that gitea schema is not compliant with Innodb cluster requirements. Mainly primary key requirement.
I actually reported missing PK a while ago: https://github.com/go-gitea/gitea/issues/8920

I opened this issue, because I'm not 100% sure DB migration fails due to missing PK.

### PR DESCRIPTION
**Pull request by zeripath**
Add a primary key to Topic and RepoTopic tables

Fix #8920

Should also fix #12061

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
I gave this version of `recreate-tables` a try, it does apparently do something but still leaves many if not all tables with the issue for me. For example on MariaDB 10.5.5:

````
> show create table star\G;
*************************** 1. row ***************************
       Table: star
Create Table: CREATE TABLE `star` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` bigint(20) DEFAULT NULL,
  `repo_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQE_tmp_recreate__star_s` (`uid`,`repo_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC
````

````
./gitea doctor recreate-table | grep star
2020/08/29 19:49:08 [W] Table user Column num_stars db default is NULL, struct default is
2020/08/29 19:49:08 [W] Table repository Column num_stars db default is NULL, struct default is
2020/08/29 19:49:08 [W] Table star Column uid db default is NULL, struct default is
2020/08/29 19:49:08 [W] Table star Column repo_id db default is NULL, struct default is
2020/08/29 19:49:08 [W] Table task Column start_time db default is NULL, struct default is
2020/08/29 19:49:09 [I] Recreating Table: star for Bean: Star
2020/08/29 19:49:13 [W] Table user Column num_stars db default is NULL, struct default is
2020/08/29 19:49:13 [W] Table repository Column num_stars db default is NULL, struct default is
2020/08/29 19:49:13 [W] Table star Column uid db default is NULL, struct default is
2020/08/29 19:49:13 [W] Table star Column repo_id db default is NULL, struct default is
2020/08/29 19:49:13 [W] Table task Column start_time db default is NULL, struct default is
````

Maybe you can reproduce with above `CREATE TABLE` statement.

**Comment by zeripath** [comment]
@silverwind the code is the same here as it is in #12407 - let's discuss that over there.

In any case the tables are being created exactly as Xorm creates them. I'm really not sure what is happening. It's the same as with the MSSQL - it doesn't make any sense xorm is creating the tables - I'm suspicious that there is a bug with Xorm.

**Review by techknowlogick — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
seems resonable

**Comment by 6543** [comment]
for release: leave a note to realy BACKUP DB

**Comment by zeripath** [comment]
## BLOCKED 

We need to check that the topics end up with the same ID. I'm concerned that topic ID might always be 0.

**Review by techknowlogick — DISMISSED** [review]
adding blocking review so it isn't accidentally merged.

**Comment by zeripath** [comment]
Panic over it was right.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
