### PR TITLE
Add ARIA support for Fomantic UI checkboxes

### PR DESCRIPTION
**Pull request by wxiaoguang**
Replace #22593 (partially)

This is a general approach to add ARIA support for all Fomantic UI checkboxes (including radioboxes)

* Pros:
    * General approach, it works for all Fomantic UI checkboxes /  radioboxes
    * No need to write IDs manually everywhere
    * No need to tell new contributors to write IDs again and again

* Cons:
    * Slightly affects performance, but it's really trivial, because there was already a heavy `$('.ui.checkbox').checkbox()` for Fomantic UI before. So everything is still fine.

Screenshot (from the repo setting page, which has various checkboxes):

<details>

image

</details>

### CODE REVIEW

**Review by yardenshoham — APPROVED** [review]
This is better

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by jolheiser** [comment]
cc @fsologureng

**Comment by fsologureng** [comment]
Why this IDs are not subject of [point 3 of Gitea specific Frontend Development Guidelines](https://docs.gitea.io/en-us/guidelines-frontend/#gitea-specific-guidelines)?

**Comment by jolheiser** [comment]
> Why this IDs are not subject of [point 3 of Gitea specific Frontend Development Guidelines](https://docs.gitea.io/en-us/guidelines-frontend/#gitea-specific-guidelines)?

Technically also point 2, but I think the answer to both is because this is an auto-generation rather than a JS-specific feature.

**Comment by fsologureng** [comment]
I will add a Con:
You still won't resolve fomantic inputs without label content, as [this](https://github.com/go-gitea/gitea/blob/main/templates/admin/config.tmpl#L306) [recent contribution](https://github.com/go-gitea/gitea/blob/main/templates/admin/config.tmpl#L313), or [this](https://github.com/go-gitea/gitea/blob/main/templates/repo/editor/commit_form.tmpl#L64) or [this](https://github.com/go-gitea/gitea/blob/main/templates/repo/issue/list.tmpl#L34), because lack of content means lack of awareness and concern of accessibility consecuences in design, as in [this non-fomantic case](https://github.com/go-gitea/gitea/blob/main/modules/markup/markdown/goldmark.go#L444). That change is not automatizable, and you just added another incentive to not be aware of.

It would be very positive that you tell (new) contributors to do accessible design again and again and again.

In any case, an advance is an advance. Thanks for that.

**Comment by wxiaoguang** [comment]
Yup, this PR only fix the ID/FOR problem partially. At least, the ID/FOR problem can have a simple solution at the moment.

And I also vote for your PR #22593 about the necessary changes (like `title` related improvements). And I also agree with some valuable changes of your PR #21964 (I explained the L-G-T-M part and reasons)

ARIA is a big topic, it really needs a lot of work. ❤️

**Pull request merged**
