### PR TITLE
Fix inconsistent user profile layout across tabs

### LINKED ISSUE #24871: User Profile Page  Tabs Have Inconsistent Layout and Style
### Description

in the user profile page the `Packages` and `Projects` tab have small icons for user but other tabs have bigger profile picture with user info:

### **For Packages  And  Projects:**
image
### **For Other Tabs:**
image

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

110

### PR DESCRIPTION
**Pull request by puni9869**
Fix ::User Profile Page  Project Tab Have Inconsistent Layout and Style
Added the big_avator for consistency in the all header_items tabs.
Fixes: #24871
> ### Description
> in the user profile page the `Packages` and `Projects` tab have small icons for user but other tabs have bigger profile picture with user info:
> 
> ### Screenshots
> ### **For Packages And Projects:**
> image
> 
> ### **For Other Tabs:**
> image
> 

## Before
image

 ## After changes
Project View 
image

Packages View
image

## Org view for projects page
image

## Org view for packages page
image

### CODE REVIEW

**Comment by puni9869** [comment]
I tried my best to not use `if-else` based check in templates.
As mentioned here https://github.com/go-gitea/gitea/pull/25108#discussion_r1230374706 by [wxiaoguang](https://github.com/wxiaoguang)

tagging @delvh @lunny @silverwind

**Comment by puni9869** [comment]
@denyskon  Please tag this pr to v1.21 milestone

**Comment by denyskon** [comment]
I don't have the permission to assign to milestone

**Comment by wxiaoguang** [comment]
Some problems:

1. The `shared/user.PrepareContextForProfileBigAvatar(ctx *context.Context)` duplicates a lot code of `web/user.Profile(ctx *context.Context)`
   * if the "shared" functions does the right thing, the `web/user.Profile` should also use it.
2. The layout seems not right. There should be only one `<div main page-content>`

image

**Comment by puni9869** [comment]
> Some problems:
> 
> 1. The `shared/user.PrepareContextForProfileBigAvatar(ctx *context.Context)` duplicates a lot code of `web/user.Profile(ctx *context.Context)`
>    
>    * if the "shared" functions does the right thing, the `web/user.Profile` should also use it.

Yes, I agree with your point. But with profile page the code is shared between followers, followings, stars, activity and in repository tags. The impact radius is large so I don't want to touch that code. 


> 2. The layout seems not right. There should be only one `<div main page-content>`
> 
> image

Fixed.

**Comment by wxiaoguang** [comment]
What are the `<div class="page-content">` and `<div class="ui repository packages">` used for in 8eb033e9cd9de3038f0f2b4e41e375fde916248f ?  I do not think they make sense.

The "page-content" means a whole page's main content in Gitea's templates, so only one for each page. Mixing them would cause unintentional style/selector conflicts.

**Comment by puni9869** [comment]
> ui repository packages

There was a previous style tagged to below code. That was creating the problem.
image

**Comment by wxiaoguang** [comment]
You can use "curl" to push a generic package.

https://docs.gitea.com/packages/usage/packages/generic

**Comment by puni9869** [comment]
Need reviews on this PR.

**Comment by wxiaoguang** [comment]
I tried to play with the templates a while, and found the problem is still more complicated and more fragile than it looks.

For example, I guess the "projects" related pages are still broken (view a project with kanban boards)

**Comment by silverwind** [comment]
Needs a merge with main because of conflicts. Screenshots do look good to me, but I don't understand the current problem either.

**Comment by puni9869** [comment]
> Needs a merge with main because of conflicts. Screenshots do look good to me, but I don't understand the current problem either.

@silverwind  I am working on the conflicts they are small.

**Comment by puni9869** [comment]
> I tried to play with the templates a while, and found the problem is still more complicated and more fragile than it looks.
> 
> For example, I guess the "projects" related pages are still broken (view a project with kanban boards)
> 
> Update: I reset my changes on this PR.

No prob @wxiaoguang . Thanks a ton for your support on this PR. I know the blast radius is huge more than we aspected, so incremently we can manage.

**Review by silverwind — APPROVED** [review]
Still looks good from a quick test

**Comment by silverwind** [comment]
Regarding org header: I wonder if it's really worth to switch it to small on tabs besides first. It's not overly big that we couldn't use it on all tabs. I think this is one case where we could diverge from GitHub's layout.

**Comment by puni9869** [comment]
> diverge

Make sense. Changes are coming soon. 💯

**Comment by silverwind** [comment]
Oh and one small style fix you can apply here:

```diff
diff --git a/web_src/css/org.css b/web_src/css/org.css
index 400f4fbbd9..d579443ce1 100644
--- a/web_src/css/org.css
+++ b/web_src/css/org.css
@@ -102,8 +102,9 @@
 }

 .organization.profile #org-info {
   overflow-wrap: anywhere;
+  flex: 1;
 }

 .organization.profile #org-info .ui.header {
   display: flex;
```

It moves the Org "Follow" button to the correct place top-right. This has recently regressed, but not by this PR.

image

**Comment by puni9869** [comment]
> 

About to push this minor update. And you did the similar thing.

**Comment by silverwind** [comment]
Actually no, don't put that fix. I will make a separare PR because the fix needs backporting.

**Comment by puni9869** [comment]
> Actually no, don't put that fix. I will make a separare PR because the fix needs backporting.

Sure, the PR is all yours. If any chages require let me know.
I think making  small the org logo we can address in next followup pr. Let this PR stand with profile and packages changes.
image

**Comment by silverwind** [comment]
Yes, let's keep it for now, limiting the scope of review.

**Comment by puni9869** [comment]
> Yes, let's keep it for now, limiting the scope of review.

Thanks @silverwind  for the quick feedbacks and support.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/25688 for the button.

**Comment by puni9869** [comment]
> #25688 for the button.

Shall I merge this branch into this.

**Comment by silverwind** [comment]
No that change is CSS so will be independent of here.

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
There are many problems in this PR. 

1. The merge seems not clear, some code is different from main branch now. See the screenshot

2. As I said before, the "project" related pages are broken. I am not sure whether it is a problem on my side or whether you have tested it.

> I tried to play with the templates a while, and found the problem is still more complicated and more fragile than it looks.
> For example, I guess the "projects" related pages are still broken (view a project with kanban boards)

I know that there is a good wish to improve the UI, but, the task seems pretty difficult by just "patching" the code without a clear refactoring.

<details>

image

image

</details>

**Comment by puni9869** [comment]
> There are many problems in this PR. 
> 
> 
> 
> 1. The merge seems not clear, some code is different from main branch now. See the screenshot
> 
> 
> 
> 2. As I said before, the "project" related pages are broken. I am not sure whether it is a problem on my side or whether you have tested it.
> 
> 
> 
> > I tried to play with the templates a while, and found the problem is still more complicated and more fragile than it looks.
> 
> > For example, I guess the "projects" related pages are still broken (view a project with kanban boards)
> 
> 
> 
> I know that there is a good wish to improve the UI, but, the task seems pretty difficult by just "patching" the code without a clear refactoring.
> 
> 
> 
> <details>
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 
> 
> </details>
> 
> 
> 
> 
> 
> 

Project tab with kanban board is working fine for me.

Let me recheck again.

Can you again take latest pull of my branch and test it.
I made some changes last day.

**Comment by wxiaoguang** [comment]
Have you tried and share the screenshot of the sub pages like http://localhost:3000/root/-/projects/2 ?

**Comment by puni9869** [comment]
> Have you tried the sub pages like http://localhost:3000/root/-/projects/2 and could you share the screenshot of it?
> 
> (oops, sorry mis-clicking the close button ....)

I can confirm this issue., There was some issue with cache at my local. Sending the fix.

**Comment by puni9869** [comment]
@wxiaoguang  Can you confirm now.

Jul-05-2023 08-52-02

There is a small thing to fix at bottom edit project. we can do that in next pr.
image

**Comment by puni9869** [comment]
> Have you tried the sub pages like http://localhost:3000/root/-/projects/2 and could you share the screenshot of it?
> 
> (oops, sorry mis-clicking the close button ....)

After fix the sub pages.

**Comment by wxiaoguang** [comment]
Sorry I still do not think the problem is fixed.

Comparing to https://try.gitea.io/wxiaoguang/-/projects/3632 , you can see there is a "user header".

For this PR, when viewing the project page, I can't know which user this page belongs to, because there is no such header.

**Comment by puni9869** [comment]
> Sorry I still do not think the problem is fixed.
> 
> Comparing to https://try.gitea.io/wxiaoguang/-/projects/3632 , you can see there is a "user header".
> 
> For this PR, when viewing the project page, I can't know which user this page belongs to, because there is no such header.

I am logged in with user.

**Comment by puni9869** [comment]
> Sorry I still do not think the problem is fixed.
> 
> Comparing to https://try.gitea.io/wxiaoguang/-/projects/3632 , you can see there is a "user header".
> 
> For this PR, when viewing the project page, I can't know which user this page belongs to, because there is no such header.

Can you check now.  @wxiaoguang 

BTS: I spilited the code of org avatar and repository user profile avatar. So I need to add all the places where `{{template "user/overview/header" .}}` is called.

**Comment by wxiaoguang** [comment]
I will take a look again and make some improvements.

**Comment by wxiaoguang** [comment]
Almost done from my side.

Now the "nav menu" has consistent layouts, and a lot of duplicate code has been merged.

There might be still some problems in code, but I think it's easier to fix any problem in the future after this PR.

image

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
I like this `+411 −349` better :)

**Comment by silverwind** [comment]
Gave it another quick test, still working fine. Pushed one small indendation fix.

**Comment by puni9869** [comment]
> Gave it another quick test, still working fine. Pushed one small indendation fix.

Looks good. Tested.

**Pull request merged**
