### PR TITLE
Update css

### PR DESCRIPTION
**Pull request by zeripath**
Remove -o-tab-size selectors from generated tab-sze-* css

### CODE REVIEW

**Comment by apricote** [comment]
For reference: https://caniuse.com/#search=tab-size

Only active browser that still requires the `-o-` prefix is Opera Mini with ~1.43% global market share.

**Review by techknowlogick — APPROVED** [review]

**Review by kolaente — APPROVED** [review]

**Comment by silverwind** [comment]
These prefixes are generated by `autoprefixes` based on this browserslist:

https://github.com/go-gitea/gitea/blob/392fe6c943c9fcd70857d1f5bff177bdf7c5f69e/package.json#L11-L15

I think this change here will not survive `make css`. To exclude a browser with 1.43% market share, I thing you could just change `> 1%` to `> 1.5%`.

**Comment by zeripath** [comment]
@silverwind these changes are due to make css. 

I'm happy if you want to restore this by changing package JSON though.

**Comment by silverwind** [comment]
Indeed, I see it too now after reinstalling node_modules. I guess something must've changed further down in the dependency tree and I think it may actually be unintentional so it might come back eventually. Locking dependencies will solve this kind of issues, I will soon have something ready to reintroduce a lockfile.

**Comment by zeripath** [comment]
Congratulations on your maintainership btw!

**Pull request merged**
