### PR TITLE
Replace `jquery.are-you-sure` with `@github/session-resume`

### PR DESCRIPTION
**Pull request by silverwind**
With [@github/js-session-resumable](https://github.com/github/session-resume), content in `<input>` and `<textarea>` is automatically saved and restored on page reload, eliminating the need to display a popup. This is using a allowlist-based approach where each restorable element needs to have a `js-session-resumable` class, which is much better than the previous `ignore-dirty` madness.

Currently I've only added this to the markup editor and the new issue/pr form.

@wxiaoguang there seems to be an existing mechanism somewhere that restores the markup editor content even without this resumation enabled. Can you help me find it so I can remove it?

### CODE REVIEW

**Comment by wxiaoguang** [comment]
* https://github.com/go-gitea/gitea/issues/23290#issuecomment-1574682080

Actually `session-resume` doesn't work well either. Think about 2 cases:

1. Content in the textarea -> submit the form -> clean the draft -> network fails -> content lost
2. Content in the textarea -> submit the form by AJAX -> draft is still in local storage

That's why "AJAX" is before the "LocalStorage Draft" in this summary issue.

**Comment by silverwind** [comment]
I don't understand these points entirely but I think they are not blockers.

**Comment by wxiaoguang** [comment]
1. Content in the textarea -> submit the form -> clean the draft -> network fails -> content lost
    * It still causes content losing, doesn't really help
2. Content in the textarea -> submit the form by AJAX -> draft is still in local storage
    * Wrong content will be left in the local storage and confuse users in next page.

**Comment by silverwind** [comment]
What is "clean the draft"?

**Comment by wxiaoguang** [comment]
And one more problem: some UI heavily depends on the "input" event.

Even if the "input" element content is restored, the UI would be in a inconsistent state (eg: auto showing something when the input has some contents).


I do not think "session-resume" is the right approach.

**Comment by silverwind** [comment]
> And one more problem: some UI heavily depends on the "input" event.

We can trigger a manual `input` event after restoration if really needed. I don't see an issue.

> I do not think "session-resume" is the right approach.

I think it is absolutely the right approach and a huge improvement over previous annoying modal popup.

**Comment by wxiaoguang** [comment]
> > And one more problem: some UI heavily depends on the "input" event.
> 
> We can trigger a manual `input` event after restoration if really needed. I don't see an issue.

It needs a complete framework design with documents and demos.

**Comment by puni9869** [comment]
I agree with silvermind here, point 2 as mentioned by wxiaoguang ajax is successful we can call the form to reset.
but for point 1  doubt if network fails then we need to think the work-around.

**Comment by silverwind** [comment]
I don't want to go overboard with this. Just a simple replacement. If there are issues later, we can solve them individually.

**Comment by puni9869** [comment]
>

**Comment by wxiaoguang** [comment]
> I don't want to go overboard with this. Just a simple replacement. If there are issues later, we can solve them individually.

It might go on the wrong way, just like some old designs ........

**Comment by puni9869** [comment]
Sorry, I accidentally closed this PR

**Comment by silverwind** [comment]
The module already dispatches a [change](https://github.com/github/session-resume/blob/b1892f5d65c01a80baa8a69ed02a48118ff92520/src/index.ts#L119) event, which is all that is needed. A `input` event would be incorrect because there was no user input.

**Comment by wxiaoguang** [comment]
One more problem, I do not think GitHub's "session-resume" works for various cases. I have experienced content losing many times on GitHub. Actually, GitHub session-resume declares:

> .... revisits the page again in their current browser session (excludes separate tabs).
> Not designed for persisted crash recovery.

I guess if people close the tab, then the content won't be able to recover.

**Comment by silverwind** [comment]
`sessionStorage` only lives for the duration of the tab, but we can easily switch to `localStorage` which persists essentially indefinitely, at the cost of likely bloating the storage over long-term.

**Comment by wxiaoguang** [comment]
> `sessionStorage` only lives for the duration of the tab, but we can easily switch to `localStorage` which persists indefinitely, at the cost of likely bloating the storage over long-term with unsaved content.

Yup, so, there are really a lot of questions. That's why I believe that it needs a design document and demos first, it needs to have explicitly defined stable behaviors.

**Comment by silverwind** [comment]
I'm not going to write documents for this, sorry.

For me, this is good enough. All I personally need is persistence across F5 and I am happy how it works on GitHub. A more elborate system that persists into `localStorage` could come later, but it will likely need some form of cleanup mechanism, e.g. store entries with timestamps and discard older than x days.

**Comment by silverwind** [comment]
@wxiaoguang I hope you can accept the current simple solution. It works for GitHub, so it likely will work for us.

I'm definitely not going to write a overengineered implementation for something I don't personally need.

**Comment by wxiaoguang** [comment]
> IDK why you want to blow everything out of proportions.

Do you have real cases to say so? I have fixed so many unfixable bugs, a lot of them are caused bad designs. Even for the markdown editor, the refactoring got stale for that long time, it's also partially caused by the messy code / bad design in history. I have spent so many time on making the code base clear and stable.


At least, isn't it nature to make every developers understand the behavior clearly?

**Comment by silverwind** [comment]
I think we can try switchting this to use localStorage. That will persist data pretty much indefinitely at the cost of potentially accumulating some garbage over time. If garbage deletion is desired, we likely would have to fork the module.

**Comment by silverwind** [comment]
I guess using `localStorage` will be the way to go, even without a garbage collection, meaning it will persist unsaved content forever. This mechanism will be active only on very few selected pages, so with current implementation, one will have at most 4 stored values per repo (issue/pr title/body), which should be acceptable.

Another candidate for this storage may be the install page.

**Comment by silverwind** [comment]
@wxiaoguang do you by chance know which mechanism currently restores the issue/pr textarea? Is that a browser-native mechanism or something from our JS?

**Comment by delvh** [comment]
Not @wxiaoguang, but I think it is the local storage/browser cache

**Comment by silverwind** [comment]
As I understand it, browser should clear a textarea on page reload. Hit `Run` here:

https://jsfiddle.net/silverwind/48oqL6y2/

The only reason a browser might keep it when the page is in bfcache, but bfcache does not apply on a reload.

**Comment by wxiaoguang** [comment]
> @wxiaoguang do you by chance know which mechanism currently restores the issue/pr textarea? Is that a browser-native mechanism or something from our JS?

Maybe related to:

* https://github.com/go-gitea/gitea/pull/22604#issuecomment-1572737226


?

**Comment by silverwind** [comment]
Hmm could be, but I guess this behaviour may vary between browsers. Generally bfcache seems to be something that is not standardized at all, so it will be good to have our own restoration in any case.

**Comment by silverwind** [comment]
Not going to continue here, but I still feel the approach is right and it should be attempted again to migrate away from `are-you-sure`, especially once we are close to ripping out jQuery from the frontend it will become necessary.

**Pull request closed without merging**
