### PR TITLE
Add a check for when the command is canceled by the program on Window…

### LINKED ISSUE #29509: Unable to open checker on windows
### Description

https://github.com/go-gitea/gitea/issues/29349#issuecomment-1972295839

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

run binary

### Database

None

### PR DESCRIPTION
**Pull request by charles7668**
Close #29509

Windows, unlike Linux, does not have signal-specified exit codes. Therefore, we should add a Windows-specific check for Windows. If we don't do this, the logs will always show a failed status, even though the command actually works correctly.

If you check the Go source code in exec_windows.go, you will see that it always returns exit code 1.
image

The exit code 1 does not exclusively signify a SIGNAL KILL; it can indicate any issue that occurs when a program fails.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Could the code be simplified to this?

```
if ctx.Err() == Deadline || ctx.Err() == Canceled {
    return ctx.Err()
}
return err
```

I think it should cover all cases.

* If the command is killed by context, then use context error
* Otherwise use command error

**Comment by charles7668** [comment]
> Could the code be simplified to this?
> 
> ```
> if ctx.Err() != nil {
>     return ctx.Err()
> }
> return err
> ```
> 
> I think it should cover all cases.
> 
>     * If the command is killed by context, then use context error
> 
>     * Otherwise use command error
> 
> 
> (I haven't carefully thought about this problem at the moment, just a brief idea)

this is hard to test , considering the context may be canceled anywhere by the parent, I can't be sure that the error always returns before the context is canceled. If not, the real error will be ignored.

**Comment by wxiaoguang** [comment]
Hmm, I think it's worth to do the change. According to the "Context" document:

```
	// If Done is not yet closed, Err returns nil.
	// If Done is closed, Err returns a non-nil error explaining why:
	// Canceled if the context was canceled
	// or DeadlineExceeded if the context's deadline passed.
	// After Err returns a non-nil error, successive calls to Err return the same error.
	Err() error
```

I think using ctx.Err() correctly would make code more correct. If you have worries about it .... I could do such "refactoring", if I am wrong I will follow it and propose related fixes. 😁

**Review by wxiaoguang — APPROVED** [review]
The check is pretty strict, so it could be good enough.

**Review by lunny — APPROVED** [review]

**Pull request merged**
