### PR TITLE
Fix coverage reports

### PR DESCRIPTION
**Pull request by ethantkoenig**
The previous `egrep` regex was wrong, so no coverage information from integration tests was included in `coverage.all`.

Also simplifies the `make coverage` rule by removing an unnecessary loop.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work

**Comment by ethantkoenig** [comment]
@lafriks Why do you comment "Make LG-TM work" on PRs that already have the `lgtm/done` label?

**Comment by lafriks** [comment]
@ethantkoenig because when you update branch to latest master github loses status checks, so commenting anything makes LG-TM update status for latest commit that is now merge commit. Otherwise GitHub does not allow to merge it as there are no all needed checks passed

**Comment by ethantkoenig** [comment]
I see, that makes sense

**Pull request merged**
