### PR TITLE
Remove Unused Functions

### PR DESCRIPTION
**Pull request by 6543**
each commit is one related remove ... so feel free to point to a specific commit hash to revert ...

It is a huge imprvement for the modules/structs package ;) since it should not contain any function ...

### CODE REVIEW

**Comment by 6543** [comment]
-------------------------------------- space ----------------------------------------------

**Comment by sapk** [comment]
Removing code is the best change. 
I am curious of how you discover thoses unused functions ?

**Comment by 6543** [comment]
@sapk via golands "code inspection" and a lot of recusrive grep + time to look throu the code
ps: the code inspection suggested **a lot** more but I wasn't aggressiv with removing stuff (somebody may use this or that func in the future ...) but I found some nice things :D (#10513 was also based on this)

**Comment by sapk** [comment]
@6543 Ok, it looks good at first glance. For code part you hesitate we could use the [Deprecated:](https://github.com/golang/go/wiki/Deprecated) syntax to highlight part that need to be cleaned later. But that already a good batch. Thanks for the time taken.

**Review by sapk — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
