### PR TITLE
Speed up make

### PR DESCRIPTION
**Pull request by silverwind**
- stop `find` from venturing into node_modules and other directories that do not contain *.go files
- only run `find` once for *.go files
- move image tempdir generation to that task
- rename GOFILES to GO_SOURCES_OWN for consistency and to indicate that vendor files are not included
- pre-resolve FOMANTIC_SOURCES

On my machine, the first action alone speeds up make initialization by around 400%.

### CODE REVIEW

**Comment by silverwind** [comment]
I wonder if `templates/*.tmpl` should be included in the `EXECUTABLE` dependencies. It seems like an oversight that they are absent.

**Comment by lafriks** [comment]
Compliance check fails

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
> 
> 
> I wonder if `templates/*.tmpl` should be included in the `EXECUTABLE` dependencies. It seems like an oversight that they are absent given that they influence the binary.

Anything that builds into `bindata.go` should be a dependency, but we're forcing the `generate` step, so...

**Comment by silverwind** [comment]
So templates go into bindata? I thought they were built as part of the go compilation.

**Comment by lafriks** [comment]
Templates are included as files in bindata.go and compiled at runtime not at compilation step

**Comment by silverwind** [comment]
Ok. Once will keep that in mind for once we make the `generate` step properly track its prereqs. Not an issue currently as it runs unconditionally.

**Comment by jolheiser** [comment]
This change seems to output errors on Windows?

I get this a handful of times.
```
find: paths must precede expression: tools.go
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
```

Is it related to a specific version of `find` perhaps?  
My `find --version` is `4.6.0`

**Comment by silverwind** [comment]
Hmm, check your `man find` if it supports `-prune`. I did verify it's present on Linux and BSD, but Windows versions may differ after all.

You can also manually run the find:

````
find . -type d \( -path ./node_modules -o -path ./docs -o -path ./public -o -path ./options -o -path ./contrib -o -path ./data \) -prune -o -type f -name '*.go' -print
````
It should output a list of all go files.

**Comment by silverwind** [comment]
It does at least work on 4.6.0, Cygwin version:

````
$ find --version
find (GNU findutils) 4.6.0
Packaged by Cygwin (4.6.0-1)
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CBO(level=2)
````

**Comment by silverwind** [comment]
Also try changing `'*.go'` to `"*.go"`. `paths must precede expression` seems related to shell expansion, but I can't see any happening here.

**Comment by jolheiser** [comment]
Seems it's related to escaping. The following works on Windows, but _not_ on Linux.  
```
GO_SOURCES ?= $(shell find . -type d \\( -path ./node_modules -o -path ./docs -o -path ./public -o -path ./options -o -path ./contrib -o -path ./data \\) -prune -o -type f -name '*.go' -print)
```

I think we can get a solution propped up shortly. 😃

**Comment by silverwind** [comment]
Backslash should need no escaping. Try this:

````
GO_SOURCES ?= $(shell find . -type d \( -path ./node_modules -o -path ./docs -o -path ./public -o -path ./options -o -path ./contrib -o -path ./data \) -prune -o -type f -name \*.go -print)

**Comment by jolheiser** [comment]
Nope, still angry. #10577 works, though.

**Pull request merged**
