### PR TITLE
WIP: tests use ed25519 ssh key

### PR DESCRIPTION
**Pull request by 6543**
close #17786

test: https://go.dev/play/p/Mu0H8t4_p_J

alternative (ecdsa): https://go.dev/play/p/98zK-E7CAfy  
old rsa: https://go.dev/play/p/IpCJ7AnCyTR

### CODE REVIEW

**Comment by 6543** [comment]
```
[E] {"message":"Invalid key content: failed to parse DER encoded public key as either PKIX or PEM RSA Key: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:\u003cnil\u003e tag:\u003cnil\u003e stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2 asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:\u003cnil\u003e tag:\u003cnil\u003e stringType:0 timeType:0 set:false omitEmpty:false} PublicKey @2","url":"http://localhost:3003/api/swagger"}
        --- FAIL: TestGit/SSH/CreateUserKey (0.01s)
            api_helper_for_declarative_test.go:179: 
                	Error Trace:	integration_test.go:508
                	            				integration_test.go:337
                	            				api_helper_for_declarative_test.go:179
                	Error:      	Not equal: 
                	            	expected: 201
                	            	actual  : 422
                	Test:       	TestGit/SSH/CreateUserKey
                	Messages:   	Request: POST /api/v1/user/keys?token=2b1a1cb4cd1ed88d02e6acaa1ea662462854b12d
```

**Comment by 6543** [comment]
if I add them manually via web interface they work ?!?

**Comment by Gusted** [comment]
Could you try to use the marshaling code from #18835 ? I had to do a few tweaks to get Ed25519 keypairs nicely working with all software.

**Comment by wxiaoguang** [comment]
Second ping

**Comment by wxiaoguang** [comment]
I guess this could be closed.

Feel free to reopen ~~~~

**Pull request closed without merging**
