### PR TITLE
Fix #2470

### LINKED ISSUE #2470: UI bug - View File pushed out
- Gitea version (or commit ref): 1.2.0+rc2
- Git version: 2.14.1
- Operating system: Arch Linux
- Database: MySQL

## Description

When looking at changed files in a commit, if the path to the file is long, button "View File" is pushed out of the box.

## Screenshots

screen shot 2017-09-06 at 16 04 20

### PR DESCRIPTION
**Pull request by Albert221**
It fixes #2470. I've used flexbox to do that which has the same (or better) browser compatibility as Semantic UI. It looks like this:

image
image

The only needed thing is to compile LESS to CSS which I couldn't do because  I couldn't find any instructions to it. Maybe you should provide them?

### CODE REVIEW

**Comment by Albert221** [comment]
CSS added.

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Comment by lafriks** [comment]
Please rebase your changes on master

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
Test failures seems unrelated?

**Pull request merged**
