### PR TITLE
Collapse Swagger UI tags by default

### PR DESCRIPTION
**Pull request by silverwind**
This makes is slightly faster to navigate through the swagger docs by initially collapsing the tags like 'admin' or 'miscellaneous'.

Before:

image

After:

image

### CODE REVIEW

**Comment by 6543** [comment]
@silverwind I dont know how hard this is but can we add an symbol to show it is colapsed? like [:chevron-down:](https://primer.style/octicons/chevron-down-16)

**Comment by silverwind** [comment]
It's already there provided by swagger ui, I just ommited it in the screenshot:

image

**Review by 6543 — APPROVED** [review]
how could I missed this :)

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
