### PR TITLE
Don't attempt to close issue if already closed

### LINKED ISSUE #9695: Error 500 when closing already closed issue from pull request
- Gitea version (or commit ref): v1.11.0-rc1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Making a pull request referencing an issue with keyword "closes" on an already closed issue will return error page 500 when the pull request is merged.
...

### PR DESCRIPTION
**Pull request by guillep2k**
Fixes #9695

~~Couldn't reproduce, however, neither with a commit message or a text reference. Tested with `master` (0c0ebe49ea4fd0d3ecc2aac9dfe2d7ce64381145) and `v1.11.0-rc1`.~~

#### Update

I can reproduce if the issue is closed from both the commit message _and_ a text reference. This PR fixes that.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
I would say backport ;)

**Comment by guillep2k** [comment]
> 
> 
> I would say backport ;)

I always wait for the approvals and merge before backporting. You never know... 😁

**Comment by 6543** [comment]
sure :)

I thought about the **lable**

Am January 10, 2020 7:33:15 PM UTC schrieb guillep2k <notifications@github.com>:

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@guillep2k Please send back port to v1.11

**Pull request merged**
