### PR TITLE
Add a 'this' to issue close/reopened messages

### PR DESCRIPTION
**Pull request by silverwind**
Change english message on issue closure/reopen from `<user> closed now` to `<user> closed this now` to match GitHub.

Is it sufficient like this for other locales to eventually be updated as well?

### CODE REVIEW

**Comment by guillep2k** [comment]
For better adaptability we could have separate messages for PRs.

**Comment by silverwind** [comment]
Hmm, I think I still have a slight preference for the shorter `closed this now` vs. `closed this issue now.`

**Comment by guillep2k** [comment]
> 
> 
> Hmm, I think I still have a slight preference for the shorter `closed this now` vs. `closed this issue now.`

I don't mean the messages should be different in English, only that they should have different entries in case other languages require e.g. gender diferentiation.

**Comment by silverwind** [comment]
Updated as suggested:

image

image

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Pull request merged**
