### PR TITLE
Upgrade bleve from v2.0.6 to v2.3.0

### LINKED ISSUE #18118: range over the pointer of a slice
### Gitea Version

e4e3df6c66dbeac6ac5bceff8ac4f05dbea30d70

### Git Version

2.34

### Operating System

CentOS 7

### How are you running Gitea?

In go 1.18 beta1:
TAGS="bindata" make build

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

`modules/indexer/code/bleve.go:427:23: cannot range over languagesFacet.Terms (variable of type *search.TermFacets)`

A similar bug in StackOverflow
[golang-cannot-range-over-pointer-to-slice](https://stackoverflow.com/questions/21278023/golang-cannot-range-over-pointer-to-slice)

### Screenshots

image

### PR DESCRIPTION
**Pull request by lunny**
Possible fix #18118

### CODE REVIEW

**Comment by 6543** [comment]
@lunny we have to migrate code ...

`modules/indexer/code/bleve.go:427:17: cannot range over languagesFacet.Terms (type *search.TermFacets)`

**Comment by Gusted** [comment]
> Possible fix #18118

Unless some package is using bleve v2.3.0 whereby the compiled code is using that version instead of the vendored v2.0.6, then their isn't anything to fix. V2.3.0 introduces some breaking changes(which we are impacted by), but they shouldn't be happening on our current version. So it's rather how the question that it comes someone is using v2.3.0 instead of the vendored one. I'm not against this change, I'd just feel that it kind of works around a problem that shouldn't be happening.

**Comment by lunny** [comment]
> @lunny we have to migrate code ...
> 
> `modules/indexer/code/bleve.go:427:17: cannot range over languagesFacet.Terms (type *search.TermFacets)`

done.

**Comment by lunny** [comment]
Looks like some performance optimization https://github.com/blevesearch/bleve/pull/1404

**Review by wxiaoguang — APPROVED** [review]
My only question is that whether bleve 2.3.0 can read/write the data of 2.0.6.

If yes, it's good to follow the latest vendor package.

If no .... well, it's still fine to me but we need to tell users (or re-generate the indexers).

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
> My only question is that whether bleve 2.3.0 can read/write the data of 2.0.6.
> 
> If yes, it's good to follow the latest vendor package.
> 
> If no .... well, it's still fine to me but we need to tell users (or re-generate the indexers).

There is no break changelog from 2.0.6 to 2.3.0 and I have a simple test, the upgrade is smooth.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
