### PR TITLE
Add namespace to global click event

### PR DESCRIPTION
**Pull request by derekhu**
Sovle :  #15687

### CODE REVIEW

**Comment by silverwind** [comment]
I see, wasn't aware of that jQuery feature. Do you think it can be done without jQuery too? I don't like to deepen the integration with it any more and I think we should generally strive to eliminate the jQuery dependency eventually because the DOM APIs are sufficient and much faster.

**Comment by derekhu** [comment]
> I see, wasn't aware of that jQuery feature. Do you think it can be done without jQuery too (feel free to replace `.on` with `.addEventListener`)? I don't like to deepen the integration with it any more and I think we should strive to eliminate the jQuery dependency eventually because the DOM APIs are sufficient and much faster.

yeah, I agree. remove jQuery just like github did. I am not a jQuery fan. 


So when?

It seems that I have to continue to overwrite the whole index.js to turn off the feature of auto clean hash. Maybe for another months.
it’s okay, I already did that.

that you for the Great Gitea, again .

**Comment by silverwind** [comment]
I think I get it now what you want. You want to unregister our event handler in a userscript to implement custom behavior with hashes. While I think the best solution is probably to add a user-facing option, we simply don't have the infrastructure to support such options easily. What I could see being done is to use `.addEventListener` and expose the listener function on `windows`, e.g.

````js
window.listeners.hashClickListener = () => {}
document.addEventListener('click', window.listeners.hashClickListener);
````

That way, you could easily unregister it by name from userscripts.

**Comment by derekhu** [comment]
> I think I get it now what you want. You want to unregister our event handler in a userscript to implement custom behavior with hashes. While I think the best solution is probably to add a user-facing option, we simply don't have the infrastructure to support such options easily. What I could see being done is to use `.addEventListener` and expose the listener function on `windows`, e.g.
> 
> ```js
> window._listeners.hashClickListener = () => {}
> document.addEventListener('click', window._listeners.hashClickListener);
> ```
> 
> That way, you could easily unregister it by name from userscripts.

Yeah. It’s a way. However global variables especially the handlers in window is what frontend programmers should avoid to. Gitea need to design the custom way of that properly. But it’s a way, if Gitea team can accept it, it is okay for me:-)

**Comment by silverwind** [comment]
Yeah, I don't like polluting `window` either. We already do it [here](https://github.com/go-gitea/gitea/blob/cad70599a65894651d91ad230b57857a443a4d26/web_src/js/features/codeeditor.js#L54-L57) for the code editor. Maybe there is a better way.

**Comment by wxiaoguang** [comment]
I think the behavior can be fixed by a `capture` event listener.

https://stackoverflow.com/questions/12462721/does-stoppropgation-stop-the-event-from-propagating-in-the-capture-phase

Then we do not need to add event namespaces one by one.

I will close this issue and PR, feel free to feedback.

**Pull request closed without merging**
