### PR TITLE
Add IDEA IntelliJ to .gitignore

### PR DESCRIPTION
**Pull request by thibaultmeyer**
This pull request add ".idea" folder into .gitignore file

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by metalmatze** [comment]
I have this in my global `.gitignore` in my home directory, because it's my choice that I use that editor, but nevertheless having this in ours as well won't do bad.

LGTM

**Comment by tboerger** [comment]
Just WHY??? This is nothing that should be handled by projects, we would end up with so many useless ignores. That is something everybody got to have in his personal global gitignore. I'm not amused about such a crap -.-

**Comment by lunny** [comment]
In fact, I dont' like global config.

**Comment by tboerger** [comment]
But than you have to add so much editor/user specific stuff. Just add a simple gitignore to your local gitconfig which ignores files/folders specific to YOUR editor and don't put this general stuff in there :(

**Comment by tboerger** [comment]
```
echo ".DS_Store" >| ~/.gitignore
echo ".idea" >> ~/.gitignore

echo "[core]" >> ~/.gitconfig
echo "  excludesfile = ~/.gitignore" >> ~/.gitconfig
```

And nobody cares about the editor configs anymore.

**Comment by stevenroose** [comment]
IDE-specific files should be in a user's own global `.gitignore`, not in the project-specific ones.

**Comment by lunny** [comment]
So where should it be?

**Comment by stevenroose** [comment]
@lunny 
http://stackoverflow.com/a/7335487/749521

**Comment by stevenroose** [comment]
That way, it will ignore IDEA files for all Git repo's you have.

**Pull request merged**
