### PR TITLE
Fix API-Endpoint release (#3005)

### LINKED ISSUE #3005: Creating release via API Endpoint resulting in internal server Error
- Gitea version (or commit ref): 1.3.0-rc2
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hey, can someone help me out? I try to use the api to create a release. I get no reply, but the server log shows me an internal server error.

```
curl -X POST "https://SERVER/api/v1/repos/USER/REPO/releases" -H "Content-Type: application/json"  -H "Authorization: token TOKEN" -d "{ \"body\": \"test\", \"draft\": false, \"name\": \"test\", \"prerelease\" : false, \"tag_name\": \"v2.1.1\", \"target_commitish\": \"f34f281e6045a20cd79f85d31a585bd40cbe473d\"}"
```

Obfuscated SERVER, USER, REPO, TOKEN.

This is the log:

```
2017-11-27T17:03:01.137374967Z [Macaron] 2017-11-27 17:03:01: Started POST /api/v1/repos/USER/REPO/releases for 172.18.0.1
2017-11-27T17:03:01.800166648Z [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
2017-11-27T17:03:01.800205336Z /usr/lib/go/src/runtime/panic.go:491 (0x55bda72acf86)
2017-11-27T17:03:01.800215354Z /usr/lib/go/src/runtime/panic.go:63 (0x55bda72abe5f)
2017-11-27T17:03:01.800279081Z /usr/lib/go/src/runtime/signal_unix.go:367 (0x55bda72c47af)
2017-11-27T17:03:01.800289125Z /srv/app/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_tag.go:23 (0x55bda75a77d4)
2017-11-27T17:03:01.800296677Z /srv/app/src/code.gitea.io/gitea/routers/api/v1/repo/release.go:128 (0x55bda7efa52c)
2017-11-27T17:03:01.800304168Z /usr/lib/go/src/runtime/asm_amd64.s:511 (0x55bda72dc9b3)
2017-11-27T17:03:01.800517981Z /usr/lib/go/src/reflect/value.go:434 (0x55bda7346466)
2017-11-27T17:03:01.800525379Z /usr/lib/go/src/reflect/value.go:302 (0x55bda7345a25)
2017-11-27T17:03:01.800531154Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x55bda7662f4a)
2017-11-27T17:03:01.800537039Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x55bda766283b)
2017-11-27T17:03:01.800543141Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x55bda7690b7f)
2017-11-27T17:03:01.800584809Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x55bda7690ab7)
2017-11-27T17:03:01.800593886Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:186 (0x55bda76e81f8)
2017-11-27T17:03:01.800612785Z /usr/lib/go/src/runtime/asm_amd64.s:509 (0x55bda72dc89c)
2017-11-27T17:03:01.800620445Z /usr/lib/go/src/reflect/value.go:434 (0x55bda7346466)
2017-11-27T17:03:01.800626154Z /usr/lib/go/src/reflect/value.go:302 (0x55bda7345a25)
2017-11-27T17:03:01.800792497Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x55bda7662f4a)
2017-11-27T17:03:01.800835961Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x55bda766283b)
2017-11-27T17:03:01.800844438Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x55bda7690b7f)
2017-11-27T17:03:01.800850411Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x55bda7690ab7)
2017-11-27T17:03:01.800856194Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x55bda76a378c)
2017-11-27T17:03:01.800861874Z /usr/lib/go/src/runtime/asm_amd64.s:509 (0x55bda72dc89c)
2017-11-27T17:03:01.800867354Z /usr/lib/go/src/reflect/value.go:434 (0x55bda7346466)
2017-11-27T17:03:01.800872888Z /usr/lib/go/src/reflect/value.go:302 (0x55bda7345a25)
2017-11-27T17:03:01.801022591Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x55bda7662f4a)
2017-11-27T17:03:01.801032071Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x55bda766283b)
2017-11-27T17:03:01.801038126Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x55bda7690b7f)
2017-11-27T17:03:01.801076954Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x55bda7690ab7)
2017-11-27T17:03:01.801085176Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:43 (0x55bda76a2a5d)
2017-11-27T17:03:01.801092394Z /usr/lib/go/src/runtime/asm_amd64.s:509 (0x55bda72dc89c)
2017-11-27T17:03:01.801098348Z /usr/lib/go/src/reflect/value.go:434 (0x55bda7346466)
2017-11-27T17:03:01.801103816Z /usr/lib/go/src/reflect/value.go:302 (0x55bda7345a25)
2017-11-27T17:03:01.801109404Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x55bda7662f4a)
2017-11-27T17:03:01.801115014Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x55bda766283b)
2017-11-27T17:03:01.801120576Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x55bda7690b7f)
2017-11-27T17:03:01.801306984Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:184 (0x55bda76a4a74)
2017-11-27T17:03:01.801315628Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:288 (0x55bda769ccbd)
2017-11-27T17:03:01.801321300Z /srv/app/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x55bda7694d89)
2017-11-27T17:03:01.801327820Z /srv/app/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x55bda796843c)
2017-11-27T17:03:01.801334688Z /usr/lib/go/src/net/http/server.go:1918 (0x55bda7558cf5)
2017-11-27T17:03:01.801348651Z /usr/lib/go/src/net/http/server.go:2619 (0x55bda755ba15)
2017-11-27T17:03:01.801354840Z /usr/lib/go/src/net/http/server.go:1801 (0x55bda7557bae)
2017-11-27T17:03:01.801360509Z /usr/lib/go/src/runtime/asm_amd64.s:2337 (0x55bda72df140)
2017-11-27T17:03:01.801365924Z [Macaron] 2017-11-27 17:03:01: Completed /api/v1/repos/USER/REPO/releases 500 Internal Server Error in 662.850942ms
```

### PR DESCRIPTION
**Pull request by SnowMB**
I'm just getting started with go. But here is my try to fix #3005 😁

### CODE REVIEW

**Comment by lunny** [comment]
Could you explain why we need that change?

**Comment by SnowMB** [comment]
When I tried to create a release via the api, I always got an internal server error (#3005).

Digging around I found out that in `\vendor\code.gitea.io\git\repo_tag.go` the following lines crashed, because repo was `nil`(l. 21-24):
```golang
// IsTagExist returns true if given tag exists in the repository.
func (repo *Repository) IsTagExist(name string) bool {
	return IsTagExist(repo.Path, name)
}
```

That call comes from `\routers\api\v1\repo\release.go` (l. 128-130), where `ctx.Repo` is fine but `ctx.Repo.GitRepo` is not initialized. 
```golang
if !ctx.Repo.GitRepo.IsTagExist(form.TagName) {
		ctx.Status(404)
		return
	}
```

**Comment by lafriks** [comment]
@SnowMB Try using `context.ReferencesGitRepo()` instead

**Comment by SnowMB** [comment]
@lafriks done. Also fixed the same error in the PATCH route.

**Comment by lafriks** [comment]
Integration test for this would be great but otherwise LGTM

**Comment by lunny** [comment]
Yes, it's better to have tests.

**Comment by SnowMB** [comment]
Would love to add some tests. But I've got some problems to get the tests running on my machine (windows 10 / vs code). My error is that the environment variable `GITEA_ROOT` is not set. Any hints how to configure this properly?

**Comment by vtemian** [comment]
@SnowMB I'm also new here, but I've managed to run the tests, on a Linux machine.
You can take a look at the `Makefile`.

The target to start is `integration-test-coverage` (since it is the one executed by the CI https://github.com/go-gitea/gitea/blob/master/.drone.yml#L122). That target depends on `integrations.cover.test`.

`integrations.cover.test:` will compile `code.gitea.io/gitea/integrations` into `integrations.cover.test`, which is the binary used to run the integration tests.

Besides that, you will need the `gitea` binary, that can be easily obtained via `make build` or by following the instructions from the `Makefile` (https://github.com/go-gitea/gitea/blob/master/Makefile#L221).
`GITEA_ROOT` is actually the directory in which the newly compiled gitea binary can be found, which, in the `Makefile`, is set to `${CURDIR}`, meaning the current working directory.

I suggest to work with the `Makefile`, is much easier and on Windows, I think that you can do that via MinGW (https://stackoverflow.com/questions/12881854/how-to-use-gnu-make-on-windows)

**Comment by lunny** [comment]
@SnowMB it's still panic on my test:

```

<html>
<head><title>PANIC: runtime error: invalid memory address or nil pointer dereference</title>
<meta charset="utf-8" />
<style type="text/css">
html, body {
	font-family: "Roboto", sans-serif;
	color: #333333;
	background-color: #ea5343;
	margin: 0px;
}
h1 {
	color: #d04526;
	background-color: #ffffff;
	padding: 20px;
	border-bottom: 1px dashed #2b3848;
}
pre {
	margin: 20px;
	padding: 20px;
	border: 2px solid #2b3848;
	background-color: #ffffff;
	white-space: pre-wrap;       /* css-3 */
	white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
	white-space: -pre-wrap;      /* Opera 4-6 */
	white-space: -o-pre-wrap;    /* Opera 7 */
	word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
</style>
</head><body>
<h1>PANIC</h1>
<pre style="font-weight: bold;">runtime error: invalid memory address or nil pointer dereference</pre>
<pre>/Users/lunny/goroot/src/runtime/panic.go:491 (0x402d692)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/Users/lunny/goroot/src/runtime/panic.go:63 (0x402c59d)
	panicmem: panic(memoryError)
/Users/lunny/goroot/src/runtime/signal_unix.go:367 (0x4044d3b)
	sigpanic: panicmem()
/Users/lunny/gopath/src/code.gitea.io/gitea/models/repo.go:467 (0x4895436)
	(*Repository).getOwner: if repo.Owner != nil {
/Users/lunny/gopath/src/code.gitea.io/gitea/models/repo.go:481 (0x48955b2)
	(*Repository).mustOwner: if err := repo.getOwner(e); err != nil {
/Users/lunny/gopath/src/code.gitea.io/gitea/models/repo.go:239 (0x4893a62)
	(*Repository).MustOwner: return repo.mustOwner(x)
/Users/lunny/gopath/src/code.gitea.io/gitea/models/repo.go:244 (0x4893aae)
	(*Repository).FullName: return repo.MustOwner().Name + "/" + repo.Name
/Users/lunny/gopath/src/code.gitea.io/gitea/models/release.go:82 (0x488de88)
	(*Release).APIURL: setting.AppURL, r.Repo.FullName(), r.ID)
/Users/lunny/gopath/src/code.gitea.io/gitea/models/release.go:102 (0x488e24e)
	(*Release).APIFormat: URL:          r.APIURL(),
/Users/lunny/gopath/src/code.gitea.io/gitea/routers/api/v1/repo/release.go:176 (0x4a403a0)
	CreateRelease: ctx.JSON(201, rel.APIFormat())
/Users/lunny/goroot/src/runtime/asm_amd64.s:511 (0x405c121)
	call128: CALLFN(·call128, 128)
/Users/lunny/goroot/src/reflect/value.go:434 (0x40c24d4)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/Users/lunny/goroot/src/reflect/value.go:302 (0x40c1ab3)
	Value.Call: return v.call("Call", in)
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x43ca498)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x43c9d99)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43f91ed)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x43f9125)
	(*Context).Next: c.run()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:186 (0x4450ea6)
	Sessioner.func1: ctx.Next()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:79 (0x43f8fd0)
	ContextInvoker.Invoke: invoke(params[0].(*Context))
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x43ca153)
	(*injector).fastInvoke: return f.Invoke(in)
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x43c9e8a)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43f91ed)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x43f9125)
	(*Context).Next: c.run()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x440c60a)
	Recovery.func1: c.Next()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x43fc4bb)
	LoggerInvoker.Invoke: invoke(params[0].(*Context), params[1].(*log.Logger))
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x43ca153)
	(*injector).fastInvoke: return f.Invoke(in)
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x43c9e8a)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43f91ed)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x43f9125)
	(*Context).Next: c.run()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:52 (0x440b89b)
	Logger.func1: ctx.Next()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x43fc4bb)
	LoggerInvoker.Invoke: invoke(params[0].(*Context), params[1].(*log.Logger))
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x43ca153)
	(*injector).fastInvoke: return f.Invoke(in)
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x43c9e8a)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43f91ed)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:187 (0x440d8f2)
	(*Router).Handle.func1: c.run()
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:303 (0x4405a5b)
	(*Router).ServeHTTP: h(rw, req, p)
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x43fda27)
	(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
/Users/lunny/gopath/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x46e7fda)
	ClearHandler.func1: h.ServeHTTP(w, r)
/Users/lunny/goroot/src/net/http/server.go:1918 (0x42d5b03)
	HandlerFunc.ServeHTTP: f(w, r)
/Users/lunny/goroot/src/net/http/server.go:2619 (0x42d87e3)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/Users/lunny/goroot/src/net/http/server.go:1801 (0x42d49dc)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/Users/lunny/goroot/src/runtime/asm_amd64.s:2337 (0x405e870)
	goexit: BYTE	$0x90	// NOP
</pre>
</body>
</html>%
```

**Comment by lunny** [comment]
@SnowMB please fix this or could you give the push permission to maintainers on this PR.
```diff
diff --git a/routers/api/v1/repo/release.go b/routers/api/v1/repo/release.go
index 17cddc565..d26d337cb 100644
--- a/routers/api/v1/repo/release.go
+++ b/routers/api/v1/repo/release.go
@@ -146,6 +146,7 @@ func CreateRelease(ctx *context.APIContext, form api.CreateReleaseOption) {
                        IsDraft:      form.IsDraft,
                        IsPrerelease: form.IsPrerelease,
                        IsTag:        false,
+                       Repo:         ctx.Repo.Repository,
                }
                if err := models.CreateRelease(ctx.Repo.GitRepo, rel, nil); err != nil {
                        if models.IsErrReleaseAlreadyExist(err) {
@@ -167,6 +168,8 @@ func CreateRelease(ctx *context.APIContext, form api.CreateReleaseOption) {
                rel.IsPrerelease = form.IsPrerelease
                rel.PublisherID = ctx.User.ID
                rel.IsTag = false
+               rel.Repo = ctx.Repo.Repository
+               rel.Publisher = ctx.User

                if err = models.UpdateRelease(ctx.Repo.GitRepo, rel, nil); err != nil {
                        ctx.Handle(500, "UpdateRelease", err)
```

**Comment by SnowMB** [comment]
Hey @lunny, 

Unfortunately I don't have time to fix this myself. But you should have permission to add commits to the pr. (`allow edits from maintainers` is checked). Is there something else I have to do, so that you can work on the branch in my fork?

**Comment by lunny** [comment]
@SnowMB thanks. I have sent a commit. I think it's ready to review now.

**Comment by strk** [comment]
I'd also like to see a test added for this

**Comment by lafriks** [comment]
@SnowMB @strk @lunny I added tests for this

**Review by sapk — APPROVED** [review]

**Pull request merged**
