### PR TITLE
fix: case typo

### PR DESCRIPTION
**Pull request by pd4d10**

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
please run `make generate-swagger`

**Comment by pd4d10** [comment]
@techknowlogick Done

**Review by zeripath — APPROVED** [review]

**Comment by techknowlogick** [comment]
@pd4d10 could you mark your PRs as allow edits from maintainers, as we need to be able to rebase and squash changes before merging

**Comment by pd4d10** [comment]
@techknowlogick It seems to be caused by the organization fork. I'll try to send another PR from my personal account's fork.

**Comment by techknowlogick** [comment]
@pd4d10 No need to send another PR I'll use my admin override

**Pull request merged**
