### PR TITLE
Fix thick scrollbar on filter menu

### PR DESCRIPTION
**Pull request by CirnoT**
Before:
firefox_2020-03-26_12-32-26
firefox_2020-03-26_12-32-45

After:
firefox_2020-03-26_12-38-38
firefox_2020-03-26_12-44-49

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by CirnoT** [comment]
Unsure what happened with CI here, looks like some UTF-8 issue?

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
@CirnoT What browser did you see this on?

**Review by zeripath — CHANGES_REQUESTED** [review]
We should really be ensuring that a scrollbar doesn't need to be shown I think...

@silverwind What do you think?

**Comment by zeripath** [comment]
@go-gitea/mergers feel free to dismiss my request changes if I have missed something here.

**Comment by CirnoT** [comment]
> @CirnoT What browser did you see this on?

Firefox, Windows 10

> We should really be ensuring that a scrollbar doesn't need to be shown I think...

That might be little un-intuitive as there would be no indication to user that the area is scrollable.

**Comment by silverwind** [comment]
1. If content overflows unexpectedly, it's better to fix the underlying root issue why it overflows in first place than to use `overflow: hidden` which I see as a last-ditch effort. Based on the screenshot, I think some style might limit the horizontal width of the popup. Try removing that limit and let it naturally expand based on content.

2. `scrollbar-width` is Firefox-only currently. There are ways to do it on webkit browsers too but it's very finicky and I would not recommend it there. That said, I think I'd be slightly in favor of adding site-wide thin scrollbars, e.g.

````css
*:not(select) {
  scrollbar-width: thin;
}
````

(taken from https://github.com/StylishThemes/Overlay-Scrollbars/blob/master/github-overlay-scrollbars.user.css)

**Review by silverwind — CHANGES_REQUESTED** [review]
See above

**Comment by CirnoT** [comment]
>If content overflows unexpectedly, it's better to fix the underlying root issue why it overflows in first place than to use overflow: hidden which I see as a last-ditch effort. Based on the screenshot, I think some style might limit the horizontal width of the popup. Try removing that limit and let it naturally expand based on content.

I am afraid that would be hard to achieve, the width is decided by browser dynamically and I see no direct CSS stylesheet that would limit it. It is properly calculated based on the content, however the vertical scrollbar eats away at the pixels causing the element body inside to overflow.

The one solution I could see helping it would be to remove `width: 100px` from `.ui.menu .ui.dropdown.item .menu .item` as well as override Fomantic's own `margin: 0;` on `.ui.menu .ui.dropdown .menu > .item`

If you believe this is worth blocking this PR for, I fully understand that and step down - this was supposed to be a quick fix for visual glitch with rather deep roots, I have no intentions on digging any deeper into trying to hack unfamiliar to me framework.

**Comment by CirnoT** [comment]
For what it's worth, from quick check it does seem to be Firefox specific and partially caused by `white-space: nowrap;` applied by Fomantic to these menu elements as well.

**Comment by guillep2k** [comment]
Don't sweat about the CI failing. It happens from time to time. I've just restarted the task.

**Comment by silverwind** [comment]
I can't seem to quite replicate the horizontal scrollbar. For some reason, this `Use alt..` hint does not show for me and. What I do see is that items are limited to 250px via this:

```` css
.repository .select-label .item {
    max-width: 250px;
    overflow: hidden;
    text-overflow: ellipsis;
}
````

This seems to be the rule that eliminates the horizontal on these. I think one solution could be to just ensure the `.item` class is present on all children.

Alternatively, can you post the HTML you see when the horizontal scrollbar is visible?

**Comment by CirnoT** [comment]
The rule you linked does not apply to these elements as they are never inside container with class `select-label`. 

If you looked at screenshots you would see that the issue happens on "Assignee" where hint is not shown at all, as such it is red herring.

Have HTML as requested, tho i have no idea why it would be necessary as it can be easily replicated.

```
<div class="menu transition visible" tabindex="-1" style="display: block !important;">
  <a class="item" href="*****" tabindex="-1" role="menuitem" id="menuitem_37">All assignees</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_38"><img src="/user/avatar/*****/-1"> *****</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_39"><img src="/user/avatar/*****/-1"> *****</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_40"><img src="/user/avatar/*****/-1"> *****</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_41"><img src="/user/avatar/*****/-1"> *****</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_42"><img src="/user/avatar/*****/-1"> *****</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_43"><img src="/user/avatar/*****/-1"> *****</a>
  <a class=" item" href="*****" tabindex="-1" role="menuitem" id="menuitem_44"><img src="/user/avatar/*****/-1"> *****</a>
</div>
```

**Comment by CirnoT** [comment]
Looking at it, it would seem that ensuring `select-label` on container div does solve the issue everywhere except on `Label` search where hint is shown.

Because the hint uses `<span>`, adding `item` on it and ensuring `select-label` on parent does solve the issue, however at the same time it results in hint being partially hidden.

```
<span class="info">Use <code>alt</code> + <code>click/enter</code> to exclude labels</span>
```

**Comment by silverwind** [comment]
I think we can use this general approach to limit width of all direct children to `.menu` on the sidebar:

````css
.metas .menu > * {
  max-width: 250px;
  overflow: hidden;
  text-overflow: ellipsis;
}
````

Remove the `.repository .select-label .item` after adding that.

**Comment by silverwind** [comment]
This seems to work for me:

````css
.metas .menu.transition > *, #issue-filters .menu.transition > * {
  max-width: 250px;
  overflow: hidden;
  text-overflow: ellipsis;
}
````
Fomantic-UI does not seem to have a distinct class for dropdowns, so hopefully the `.transition` class addition will help with only matching those.

**Comment by CirnoT** [comment]
This does seem to work everywhere aside for the hint.

```
<span class="info">Use <code>alt</code> + <code>click/enter</code> to exclude labels</span>
```

Is there any reason why we can't ensure `select-label` to be present on container for these dropdowns?

**Comment by silverwind** [comment]
I would aim for a more general solution for all dropdowns. According to [this](https://fomantic-ui.com/modules/dropdown.html) a dropdown is defined by `.dropdown > .menu`, so I think we can just use:

```css
.dropdown > .menu > * {
  max-width: 300px;
  overflow-x: hidden;
  text-overflow: ellipsis;
}
```
I'm pretty sure there are no dropdowns around that would require more width. Note I bumped the width by 50px as I think we can show a bit more of overly long labels. The `.info` needs a width adjustment to stretch the parent:

```css
.repository .filter.menu.labels .label-filter .menu .info {
  width: 100%;
}
```

**Comment by CirnoT** [comment]
It does work, however the tip ends up like this:
firefox_2020-03-30_14-20-13

**Comment by silverwind** [comment]
> Hold alt while selecting to exclude

Sounds good to me

**Comment by CirnoT** [comment]
Should I close this PR and you will open new one with changes? @silverwind

**Comment by silverwind** [comment]
Yes, I'll open a new one soon.

**Comment by CirnoT** [comment]
See #10897

**Pull request closed without merging**
