### PR TITLE
Change loading animation frame order

### PR DESCRIPTION
**Pull request by lafriks**
image

### CODE REVIEW

**Comment by lunny** [comment]
The original animated image hints that you could go to drink a cup of tea now. :)

**Review by silverwind — APPROVED** [review]
Filling cup seems more appropriate to me given that this represents a loading bar.

**Comment by lafriks** [comment]
@lunny I did not thought about such perspective :) For me it just looked awkward that data is being imported but tea is getting less and less :)

**Review by 6543 — APPROVED** [review]
I asked a "normal" person - he choose the new one :) so lgtm

**Comment by silverwind** [comment]
New one is also 30% smaller, I wonder why 😉

**Comment by lafriks** [comment]
Could be because of different tool used, I don't know :) I used Linux cli tool apngasm

**Comment by silverwind** [comment]
Too bad we can't optimize it further, both `pngcrush` and `zopflipng` destroy the animation.

**Comment by silverwind** [comment]
Actually managed to squeeze out 500 bytes using [apngopt](https://sourceforge.net/projects/apng/files/APNG_Optimizer):



This image would be a good candidate for SVG SMIL animation 😉

**Comment by silverwind** [comment]
Not sure why you landed that but I opened https://github.com/go-gitea/gitea/pull/10372 for the optimization.

**Comment by lafriks** [comment]
I did not thought that you wanted me to change it :)

**Pull request merged**
