### PR TITLE
[Vendor] Update directly used dependencies 

### PR DESCRIPTION
**Pull request by 6543**
* github.com/6543/go-version v1.2.4 -> v1.3.1
* github.com/xanzy/go-gitlab v0.44.0 -> v0.48.0
* github.com/prometheus/client_golang v1.9.0 -> v1.10.0
* github.com/pelletier/go-toml v1.8.1 -> v1.9.0
* github.com/olivere/elastic v7.0.22 -> v7.0.24
* github.com/niklasfasching/go-org v1.4.0 -> v1.5.0
* github.com/microcosm-cc/bluemonday v1.0.7 -> v1.0.8
* github.com/mgechev/revive v1.0.3 -> v1.0.6
* github.com/klauspost/compress v1.11.8 -> v1.12.1
* github.com/issue9/identicon v1.0.1 -> v1.2.0
* github.com/go-testfixtures/testfixtures v3.5.0 -> v3.6.0
* github.com/mattn/go-sqlite3 v1.14.6 -> v1.14.7
* github.com/lib/pq v1.9.0 -> v1.10.1
* github.com/go-swagger/go-swagger v0.26.1 -> v0.27.0
* github.com/go-sql-driver/mysql v1.5.0 -> v1.6.0
* github.com/go-redis/redis v8.6.0 -> v8.8.2
* github.com/go-ldap/ldap v3.2.4 -> v3.3.0
* github.com/go-git/go-git v5.2.0 -> v5.3.0
* github.com/go-git/go-billy v5.0.0 -> v5.1.0
* github.com/go-chi/cors v1.1.1 -> v1.2.0
* github.com/editorconfig/editorconfig-core-go v2.4.1 -> v2.4.2
* github.com/denisenkom/go-mssqldb v0.9.0 -> v0.10.0
* github.com/blevesearch/bleve v2.0.2 -> v2.0.3

### CODE REVIEW

**Comment by 6543** [comment]
note: https://github.com/go-ldap/ldap/releases/tag/v3.3.0
 -> we had issues with ldap deleting users on timeout, we now should be able to handle it

**Review by silverwind — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind added `github.com/6543/go-version v1.2.4 -> v1.3.1` since upstream v1.3.0 got released ...

**Comment by techknowlogick** [comment]
LGTM, what is your process for this, do you manually go through each and create a commit per dep, or do you have a script to do this?

**Comment by 6543** [comment]
I first do `go get -u` and look whats changed.
I ignore updates if indirect imports and manualy fo throu all of them who have changed (read release note if there is one, ...)
making a commit for a import update is done half-automated ...

We could create a more automaded prosses via dependabot etc ...

**Pull request merged**
