### PR TITLE
Add `--work-path` and `--custom-path` to git hooks

### LINKED ISSUE #25107: Inconsistent value for [repository].ROOT causes errors on `git push`
### Description

I am running gitea via the snap package, and have overridden the systemd unit file to set the `--work-path` and `--custom-path` to a mounted volume on my server, since there is no other way that I know about to override the environment variables in the `snapcraft.yml`.

In `/etc/systemd/system/snap.gitea.web.service.d/override.conf`:
```
[Service]
ExecStart=
ExecStart=/usr/bin/snap run gitea.web --config /mnt/mina-gitea-data/custom/conf/app.ini --work-path /mnt/mina-gitea-data --custom-path /mnt/mina-gitea-data/custom
User=git
```

In the logs for gitea I see the values that I expect:

```
34 cmd/web.go:105:runWeb() [I] Starting Gitea on PID: 1653
:34 ...ules/setting/time.go:58:loadTimeFrom() [I] Default UI Location is Europe/London
:34 cmd/web.go:159:runWeb() [I] Global init
:34 ...ules/setting/time.go:58:loadTimeFrom() [I] Default UI Location is Europe/London
:34 routers/init.go:118:GlobalInitInstalled() [I] Git Version: 2.17.1 (home: /mnt/mina-gitea-data/data/home)
:34 routers/init.go:119:GlobalInitInstalled() [I] AppPath: /snap/gitea/6474/gitea
:34 routers/init.go:120:GlobalInitInstalled() [I] AppWorkPath: /mnt/mina-gitea-data
:34 routers/init.go:121:GlobalInitInstalled() [I] Custom path: /mnt/mina-gitea-data/custom
:34 routers/init.go:122:GlobalInitInstalled() [I] Log path: /mnt/mina-gitea-data/log
:34 routers/init.go:123:GlobalInitInstalled() [I] Configuration file: /mnt/mina-gitea-data/custom/conf/app.ini
:34 routers/init.go:124:GlobalInitInstalled() [I] Run Mode: Dev
:34 routers/init.go:125:GlobalInitInstalled() [I] Gitea v1.19.3 built with GNU Make 4.1, go1.20.4 : bindata, sqlite, sqlite_unlock_notify, pam, cert
```
The `doctor` command shows the Repository Root Path that I expect:
```
gregory@mina-gitea:~$ sudo runuser -u git -- gitea --config /mnt/mina-gitea-data/custom/conf/app.ini --work-path /mnt/mina-gitea-data/ --custom-path /mnt/mina-gitea-data/custom/ doctor
ERROR: Unable to write logs to provided file due to permissions error: doctor.log
       failed to create sublogger (doctor): open doctor.log: permission denied
WARN: Logging will be disabled
       Use `--log-file` to configure log file location
[1] Check paths and basic configuration
 - [I] Configuration File Path:    "/mnt/mina-gitea-data/custom/conf/app.ini"
 - [I] Repository Root Path:       "/mnt/mina-gitea-data/data/gitea-repositories"
 - [I] Data Root Path:             "/mnt/mina-gitea-data/data"
 - [I] Custom File Root Path:      "/mnt/mina-gitea-data/custom/"
 - [I] Work directory:             "/mnt/mina-gitea-data/"
 - [I] Log Root Path:              "/mnt/mina-gitea-data/log"
OK
```
However when I push commits to a repository, I receive the following error:
```
remote: Gitea: Incorrect configuration, no repository directory.
remote: Directory `[repository].ROOT` "/var/snap/gitea/common/data/gitea-repositories" was not found, please check if $GITEA_WORK_DIR is passed to the SSH connection or make `[repository].ROOT` an absolute value.
remote: panic: cannot create context from nil parent
```
It seems like different bits of gitea disagree about the value of this configuration setting?

Happy to provide more logs/info if needed!

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.34.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

The Gitea server is provisioned using cloud-init and gitea is started using the systemd unit file.

The unit file has been overridden to specify the data paths and user:

```
[Service]
ExecStart=
ExecStart=/usr/bin/snap run gitea.web --config /mnt/mina-gitea-data/custom/conf/app.ini --work-path /mnt/mina-gitea-data --custom-path /mnt/mina-gitea-data/custom
User=git
```

It has been given the `removable-media` permission via `snap connect gitea:removable-media` before launching.

The entire `app.ini` can be viewed as part of the cloud-init configuration [here](https://codeberg.org/mina-lang/mina-infrastructure/src/commit/671128cca4e6a8f987dae60072e53492c3a7d9cf/templates/gitea-cloud-init.yml.tftpl#L35).

### Database

SQLite

### PR DESCRIPTION
**Pull request by DavidGregory084**
Fixes #25107.

This adds explicit `--work-path` and `--custom-path` flags to the generated git hooks.

This should prevent hooks from inheriting different values for `AppWorkPath` and `CustomPath` than those used in the main gitea process.

### CODE REVIEW

**Comment by delvh** [comment]
Hmm… I'm not quite sure how similar this is to https://github.com/go-gitea/gitea/pull/22754, especially if the same discussion still applies.

**Comment by DavidGregory084** [comment]
Hmm that is an interesting discussion.

The root of this entire problem seems to be that the `app.ini` is not authoritative.
 
There are too many entry points to the application used in a single deployment to allow command-line and environment variable overrides that affect something fundamental like the working directories.

**Comment by lunny** [comment]
Maybe we should store them into some runtime files and share for different processes.

**Comment by wxiaoguang** [comment]
We shouldn't do this. There are more problem for these "config options".

* https://github.com/go-gitea/gitea/issues/24818

I will fix the path problem in 1.21 (I do not want to introduce too many breaking changes in 1.20 since it is releasing soon)

**Pull request closed without merging**
