### PR TITLE
Add oauth sign-in to registration page

### PR DESCRIPTION
**Pull request by jackHay22**
This is a follow-on to https://github.com/go-gitea/gitea/pull/26550 and includes oauth signin on the registration page. 

This is particularly important for invitations by email. A user without an account may be invited to join a team and will receive an activation link that first navigates to the registration page. However, this will be a confusing flow if they intend to use an external auth provider.

Screen Shot 2023-09-06 at 12 55 49 PM

### CODE REVIEW

**Review by kdumontnu — APPROVED** [review]
If users navigate first to the registration, they won't necessarily know what external auth sources are available. Most web apps I've seen have external auth sources available on the registration page. 

Imo, this is only loosely related to the team invite PR.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Resolve 

* #19809
* #20242

But I think it's better to move the code into a shared template. I guess the code was just copied&pasted.

**Comment by lunny** [comment]
> Resolve
> 
>     * [External openid connect (oidc, oauth) providers missing on sign up/register page #19809](https://github.com/go-gitea/gitea/issues/19809)
> 
>     * [Show OpenID Connect and OAuth on signup page #20242](https://github.com/go-gitea/gitea/pull/20242)
> 
> 
> But I think it's better to move the code into a shared template. I guess the code was just copied&pasted.
> 
> And I think #20242 should be fixed and merged, because it came early but nobody reviews (well, community driven, so it's also fine to close that one and take this one)

So let's review that one. I think that PR includes all of this PR.

**Comment by jackHay22** [comment]
> > Resolve
> > ```
> > * [External openid connect (oidc, oauth) providers missing on sign up/register page #19809](https://github.com/go-gitea/gitea/issues/19809)
> > 
> > * [Show OpenID Connect and OAuth on signup page #20242](https://github.com/go-gitea/gitea/pull/20242)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I think it's better to move the code into a shared template. I guess the code was just copied&pasted.
> > And I think #20242 should be fixed and merged, because it came early but nobody reviews (well, community driven, so it's also fine to close that one and take this one)
> 
> So let's review that one. I think that PR includes all of this PR.

Agreed, that PR looks nearly identical to mine 👍

**Comment by jackHay22** [comment]
Replaced by: https://github.com/go-gitea/gitea/pull/20242

**Pull request closed without merging**
