### PR TITLE
Make compare button URL aware if current repo is a fork (#2162)

### PR DESCRIPTION
**Pull request by Weyzu**
The following merge request fixes the issue addressed in #2162. 

Long story short: The change prevents 404 when the template tries to compare non-existing branch by assuming that every repo is a fork (i.e. by providing `username:branchname` every time).

Since it was possible to determine if the repository is a fork from within the template, I've added a check in the `home` template. I'm not aware of any side effects of this solution.

### CODE REVIEW

**Comment by lafriks** [comment]
Thanks for PR, I hope you don't mind that did a small code optimization. Tested and works just fine, so LGTM

**Comment by Weyzu** [comment]
Not at all. :) Thanks for the quick response. ✌️

**Comment by lafriks** [comment]
@Weyzu I was thinking and maybe check IsFork is not needed but only check if signed in user has fork of base repository. What do you think?

**Comment by sapk** [comment]
LGTM

**Review by sapk — APPROVED** [review]

**Comment by lafriks** [comment]
I removed check for IsFork as otherwise if user would click button form fork that he is not owner and that user has no its own fork it would still get 404 error so check explicitly that user has fork

**Pull request merged**
