### PR TITLE
Fix changelog (main)

### PR DESCRIPTION
**Pull request by wxiaoguang**
1. The 1.21.11 changelog is missing
2. Split the old content to CHANGELOG-archived.md, to reduce the size of CHANGELOG.md

### CODE REVIEW

**Comment by lunny** [comment]
1.21.8~ 1.21.10 are also missed.

**Comment by wxiaoguang** [comment]
> 1.21.8~ 1.21.10 are also missed.

I know, there are a lot, not in this PR's scope IMO since they are missing for long time.

**Comment by wxiaoguang** [comment]
> > 1.21.8~ 1.21.10 are also missed.
> 
> I know, there are a lot, not in this PR's scope IMO since they are missing for long time.

OK, I will copy some old changelogs into it without checking.

I am just quite unsatisfied about the release procedure: every release, there must be something missing. I have asked many times, would there be some documents and check steps to guarantee there won't be any low-level mistake during the release? No progress. If nobody cares, I won't waste time on it either, anyway it doesn't affect me and I don't use these releases.

**Comment by wxiaoguang** [comment]
@go-gitea/technical-oversight-committee

**Comment by lunny** [comment]
> @go-gitea/technical-oversight-committee

Maybe we should create an issue for every release which includes all tasks we need to do.

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Pull request merged**
