### PR TITLE
Dockerfile for ARM (RPi)

### PR DESCRIPTION
**Pull request by ulm0**
### Dockerfile for ARM
I had some problems when using the Dockerfile.rpi file to build the image for my RPi3 as mentioned in #531 so i made some modifications to the current Dockerfile, such as downloading the binary from the [official folder](https://dl.gitea.io/gitea/master/) provided by gitea in their web site, and creating the folder ```/app/gitea``` within the image.

### CODE REVIEW

**Comment by Morlinest** [comment]
Hi, I do not know how are you doing images guys, but personaly i do not like the idea of downloading the binary (and you still have to copy docker folder). You can not use your own build, test features, can not be use with CI and autobuild etc. Now its posible to download repo and build everything from it, with this new solution you will have to download repo and hope your version of files (docker folder and also Dockerfile) are compatible with downloaded binary (example: you want older version of program but binary is latest or you want program with the newest features but binary is old).


_Sorry for english, not my native language._

**Comment by ulm0** [comment]
@Morlinest, you're right, this is not the best approach. Because you can't just use the Dockerfile alone and build it. This ```Dockerfile.rpi``` file is based on the [current one](https://github.com/go-gitea/gitea/blob/129b0d6a4b408555c579e7ccb2fb15d3d8fcef29/Dockerfile.rpi) which depends on the repo by copying the docker folder into the image, i tried to use it to build the images but faced some problems as mentioned in #531 so i came up with this approach which i built using an [ARM runner](https://gitlab.com/klud/gitea/blob/master/.gitlab-ci.yml) i have in GitLab, of course you can build the binary on the go when building the image (instead of downloading it, though you can compare checksums and so on), but it ends being a really heavy image and imho the image should be as lightweight as possible. This is just my point of view since i'm far from being a docker expert. But i'll come up with a better approach as soon as i can.

**Comment by tboerger** [comment]
:-1: for these changes. Just add one more make task like docker-rpi.

**Comment by tboerger** [comment]
That being said the Dockerfile is structured like that on purpose.

**Pull request closed without merging**
