### PR TITLE
Disable Stars config option

### PR DESCRIPTION
**Pull request by kdumontnu**
If `DISABLE_STARS = true` remove the option to star repositories

image

The "Starred Repositories" tab in user profile is replaced with "Watched Repositories"
image

This is helpful for enterprise/private accounts where the ability to "star" repositories is not very useful and creates confusion compared to "watching".

Note: I'm working on a separate PR to toggle Watch status in the Profile repo list

### CODE REVIEW

**Comment by 6543** [comment]
I think the "watching repos" is a nice func anyway :) ... just if we going to add it, can we add a prifacy opt-out add too?

like it exist for `Hide the activity from the profile page`

**Comment by kdumontnu** [comment]
> I think the "watching repos" is a nice func anyway :) ... just if we going to add it, can we add a prifacy opt-out add too?
> 
> like it exist for `Hide the activity from the profile page`

I used the same settings as "Starred Repositories". Should that be hidden as well? The setting is also ignored for Repositories, Following, and Followed. This seems like a separate PR, but I'm happy to open one to fix that.

**Comment by kdumontnu** [comment]
@6543 did you still want me to make the change to put this behind the `KeepActivityPrivate` flag?
It appears right now this flag is only checked for the `Activity` tab, not Repositories, Stars, Following, or Followed.
I'm happy to make the change, but honestly I think it's better to do in a separate PR to address all cases.

**Comment by 6543** [comment]
@kdumontnu I think we can seperate it ...

**Review by noerw — APPROVED** [review]

**Comment by 6543** [comment]
@kdumontnu sorry that it wont get reviewed and merged right away... just for you as an info: gitea is in feature freeze at the moment ...

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
OK I think this looks fine - I don't quite understand why the feature needs disabling but the PR does do everything needed to disable the feature completely.

**Comment by kdumontnu** [comment]
> OK I think this looks fine - I don't quite understand why the feature needs disabling but the PR does do everything needed to disable the feature completely.

Excellent! I understand the hesitation, but generally speaking for private projects "stars" provide very little value and can add unnecessary complexity for users.

**Comment by techknowlogick** [comment]
@kdumontnu just reaching out to you here to let you know I sent a PM to your discord, hoping you saw it :)

**Comment by zeripath** [comment]
Please resolve conflicts

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@kdumontnu can you "update branch" please?

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
