### PR TITLE
Revert #13857

### LINKED ISSUE #14271: 2FA issues in dev version
- Gitea version (or commit ref): 1.14.0+dev-514-gd2ee1221c (Docker `:latest`)
- Git version: irrelevant I guess
- Operating system: Dockerized installation
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (at least is gives me a 500 as well)
  - [ ] No
- Log gist: https://gist.github.com/binfalse/2ca6706fb1244545649f218af1c6bce2

## Description

2FA seems to be broken in the current dev version.

I've had 2FA enabled and couldn't log in anymore after I updated the Docker image. After some debugging I disabled 2FA for my account (by deleting the corresponding line in the `two_factor` table) and was able to login again. (Actually, I needed to clean cookies as well, as it was then asking me for a scratch code...)

When trying to re-enable 2FA I get a 500 at the frontend (I can reproduce that at https://try.gitea.io -- at least I'll get a 500 as well if I try to setup 2FA there). The logs show

    [E] PANIC: interface conversion: interface {} is nil, not string

see: https://gist.github.com/binfalse/2ca6706fb1244545649f218af1c6bce2  -- please note:
* I replaced sensitive information with placeholders
* even though I set `COLORIZE  = false` the messages are apparently still colorized.. not sure what's going wrong there...? Just ignore the `#011` commands..
* logs went through rsyslog -> extra syslog prefixes, see https://binfalse.de/2018/02/21/logging-with-docker/

To me it looks like there is an issue with 2FA...? Let me know if you need further information or if I can do anything else to debug the issue! :)

## Screenshots
Web interface just shows a 500..

### PR DESCRIPTION
**Pull request by CirnoT**
This reverts #13857 and subsequently #14263 with the exception of keeping modified Drone config that performs tests against Windows builds.

The current implementation of #13857 is broken as it creates two separate sessions that fight, overwriting each other and making logging in impossible on any session provider that is not `memory`.

Fixes #14271

### CODE REVIEW

**Comment by 6543** [comment]
@lunny do how far is chi migration going?

If it's quit finished, I think we dont need to revert, but if it will take still some time we could consider this here as hotfix

**Comment by CirnoT** [comment]
This is critical and breaking, it NEEDS to be reverted if fix is not being proposed

**Review by 6543 — APPROVED** [review]

**Review by 6543 — COMMENTED** [review]
.

**Review by 6543 — CHANGES_REQUESTED** [review]
https://github.com/go-gitea/gitea/issues/14271#issuecomment-756497940

**Comment by CirnoT** [comment]
As you wish

**Pull request closed without merging**
