### PR TITLE
Simplified README and added a release badge

### PR DESCRIPTION
**Pull request by tboerger**
/cc @lunny for ZH translation

### CODE REVIEW

**Comment by lunny** [comment]
So we need give a reference to website or docs and move the deleted documents to docs site.

**Comment by tboerger** [comment]
> So we need give a reference to website or docs and move the deleted documents to docs site.

I have linked to the docs within the `## Docs` section.

**Review by lunny — COMMENTED** [review]
LGTM

**Comment by metalmatze** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Pull request merged**
