### PR TITLE
[Fix] Release attachment should use DownloadURL() not Name

### PR DESCRIPTION
**Pull request by 6543**
**Problem: attachments with same name (only first uploaded is downloadable)**

* fix `templates/repo/release/list.tmpl `
* template refactor `templates/repo/issue/view_content/attachments.tmpl`
* code refactor `routers/repo/repo.go`

### CODE REVIEW

**Comment by 6543** [comment]
@techknowlogick should i backport?

**Comment by davidsvantesson** [comment]
Should we really allow files with same name on same release in the first place? I think most people would expect to replace the old file if they upload a new.

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
@davidsvantesson no opinion on it .. - for now it works this way and ths PR make sure nothing break ...

We can considder a `replace atatchment when same name on uplaod` in future PR ?

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
This PR has reverted the change to give attachments human-readable names.  

@6543 Was that part specifically causing an issue?

**Comment by 6543** [comment]
@jolheiser yes it did - you can creat multible attachments with the same name!

and they were displayed all but you can just download the first one they all have the same link

**Comment by 6543** [comment]
@jolheiser if #9534 got implemented we can switch back to human redable

**Pull request merged**
