### PR TITLE
Fix tab indentation in code view

### LINKED ISSUE #5596: First indentation is shorter by one character
Gitea version: 1.6.0, 1.5.0

## Description

The first level indentation in file preview is in fact by one character shorten than all other levels indentations. For example, if the tab size is 8, first indentation will be 7 characters, not 8. This breaks many source codes rendering.

In the built-in web editor, the indentation works as expected. 

## Screenshots

Gitea .go code on GitHub:

indent-github

Gitea .go code on Gitea itself:

indent-gitea

### PR DESCRIPTION
**Pull request by cipherboy**
Resolves: #5596

`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`

----

On my system (F31, Firefox 73), this almost works. It does move the code over by one character, without having the prefixed space affect the tab indentation. The issue is that Firefox can't seem to correctly calculate the offset of the size of 8 spaces in the selected font (Liberation Mono). 

See attached screenshots:

Screenshot from 2020-03-08 11-59-36

When this font is disabled, it does work:

Screenshot from 2020-03-08 11-59-47

We can probably leave the width as-is, I just updated it to keep the same original width.

### CODE REVIEW

**Comment by cipherboy** [comment]
FWIW, I can reproduce the font rendering issue in Firefox when viewing the raw file. So, this is a Firefox/Linux/Liberation Mono bug. This PR can continue. 

Screenshot from 2020-03-10 12-17-27

**Comment by zeripath** [comment]
In which case we should remove Liberation Mono from the suggested fonts I think.

**Review by 6543 — APPROVED** [review]
all in all - I like the change of this pull

**Comment by cipherboy** [comment]
@zeripath said:
> In which case we should remove Liberation Mono from the suggested fonts I think.

I've filed a [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1621955) bug about it. I've tried two different versions of Liberation Mono from Fedora and they both seem to have this problem. There's also a historical [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=557862), but that's been marked as resolved and I can't reproduce this issue in `gedit`. It seems to only be a Firefox problem for some reason.

I'd prefer to leave it in the list for now. I think Liberation Mono is a fairly common font on Linux systems.

**Review by mrsdizzie — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Comment by cipherboy** [comment]
Thanks for the merge!

**Pull request merged**
