### PR TITLE
Refactor filetype is not allowed errors

### PR DESCRIPTION
**Pull request by sapk**
Refactor of common code across various parts.
In order to help in issue like #7302 by defining a specific error type and adding the filetype to the message.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
The name `utils` is not very suitable as the package name and it is unnecessary to improt models from that package.

**Comment by sapk** [comment]
@lunny to be fair, I hesitate to where to put this to be available across package and don't loop. I re-use the utils package already existing for similar pattern. 
As for models, it is where errors are defined. I could define it locally if needed.

**Comment by lunny** [comment]
@sapk Maybe we should move all errors to `modules/error` and `models` and other package will depend on that.

**Comment by sapk** [comment]
@lunny But that would be an other PR. Would you like that I do a separate PR for that before ?

**Comment by zeripath** [comment]
I'm not certain that modules/errors is quite the right way to go. Things should define their own errors.

I suspect modules/errors would become very quickly a dumping ground that everything depends on and everything refers to.

**Comment by zeripath** [comment]
Maybe rename routers/util -> routers/upload ? Then more of the generic upload stuff could be moved there?

**Comment by lunny** [comment]
@sapk or just keep the error with this package and give a suitable name for it?

**Comment by sapk** [comment]
@zeripath @lunny I created a specific import modules/upload. Let me know if it is ok with you.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
CI failed

**Comment by sapk** [comment]
@lunny should be good. I forgot (more specially my IDE) to fmt :man_facepalming:.

**Comment by zeripath** [comment]
@sapk I just restarted the build. That problem with the dryrun failing randomly is concerning though...

**Comment by sapk** [comment]
I think it is related to download(or/and checks) of deps that failed sometime. I don't know if setting up a module proxy would help in this case.

**Comment by lunny** [comment]
@sapk a module proxy should accelerate the build process.

**Pull request merged**
