### PR TITLE
ui: change time-line event icons tyle

### LINKED ISSUE #10864: [ui] make more icon types onto the time-line like github
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello! I found a problem that now on gitea's time-line , we can only make ``x``, ``eye`` ``circle-slash`` on it , but ``lock`` , ``key`` , and many other types can't on it. which is doesn't look good enough. I think It will be fun if we can make them onto the time-line.  also it will be more good if we can make them style like github , which means all icons except dot combine whith a circle. but I have no idea about how to do them , so add this issue to find help. Thanks.

## Screenshots
jft1

------

jft2

### PR DESCRIPTION
**Pull request by a1012112796**
* Fix timeline icons offset #10864

Co-authored-by: Sorien <sorien@mail.com>

* change icons style on time-line to a more meaningfull icon like github instead of  primitive-dot

* change merge comment style to distinguish it from close

view:
js1

----

js2

----

js3

----

js4

-----

js5

Close #10864

### CODE REVIEW

**Comment by Sorien** [comment]
personaly i'd try to align icon and avatar together

could you try 
```css
issue-symbol {
    float: left;
    width: 30px;
    height: 30px;
    background-color: #eee;
    border: 2px solid #fff;
    align-items: center;
    margin-left: -36px;
    border-radius: 50%;
    vertical-align: middle;
    padding: 5px;
}
```
and change all svg icons to theirs original width & height of 16px

**Comment by mrsdizzie** [comment]
Maybe beyond the scope of this PR, but it would also be nice if the avatar was on the other side of the time line for review comments or approvals, like on Github:

Screen Shot 2020-04-03 at 12 55 18 PM

**Comment by a1012112796** [comment]
> Maybe beyond the scope of this PR, but it would also be nice if the avatar was on the other side of the time line for review comments or approvals, like on Github:
> 
> Screen Shot 2020-04-03 at 12 55 18 PM

Yes, and it's same size and position with comment , I will check and try it. Thanks

**Comment by Sorien** [comment]
@a1012112796 finally i'm able to build gittea from sources, could you give me few days i'll try to come with proper solution

**Comment by a1012112796** [comment]
> > Maybe beyond the scope of this PR, but it would also be nice if the avatar was on the other side of the time line for review comments or approvals, like on Github:
> > Screen Shot 2020-04-03 at 12 55 18 PM
> 
> Yes, and it's same size and position with comment , I will check and try it. Thanks

That's fun, Thanks!

**Comment by a1012112796** [comment]
> @a1012112796 finally i'm able to build gittea from sources, could you give me few days i'll try to come with proper solution

That's fun, Thanks!

**Comment by a1012112796** [comment]
Close this PR, It's duplicate #10972, Let's wait it.
@guillep2k  Please remove this PR from Milestone.

**Pull request closed without merging**
