### PR TITLE
Add review requested filter on pull request overview

### LINKED ISSUE #13682: Add review requests filter on pull request overview
## Description

A "Review requests" filter can be added on the pull request overview page.

Currently these 4 filter options exist:
image

An additional option "Review requests" can be added, just like on github:

image

I'm currently working on a pull request for this. I am uncertain about something though: should this filter also return review requests that you have already accepted at some point, but have gone stale by now?

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #13682

This adds a filter on the pull request overview pages that allows you to find the pull requests that are requesting your review.

* Is the name "Review Requested" for the filter OK? On GitHub it is called "Review Requests". Most clear is probably something like "Requesting your review", which is consistent in phrasing with the existing "Mentioning you" filter. What do you think?
* Review requests records are not deleted once the review has taken place, so in the query I had to add a subselect to only take the last review record into account. I worry a bit about performance impact? Is there a better way?
* With https://github.com/go-gitea/gitea/pull/13514 the existing "created", "assigned" and "mentioned" issue filters were made available through the API as well. Would you like me to add API support for the "review_requested" filter as well?

### CODE REVIEW

**Comment by silverwind** [comment]
This will need a rebase now after https://github.com/go-gitea/gitea/pull/13594.

**Comment by lynxplay** [comment]
Is there any update on this PR? Our team would really appreciate the change for the main workflow of our release cycle.

**Comment by jpraet** [comment]
TODO: also return review requests for teams you belong to.

When looking at the code for team review requests, I notice that when a user submits a review with status Reject or Approve, any existing review requests for the *teams* the user belongs to are removed. So I do wonder why we wouldn't also remove review requests for the user there? It would remove the need for these subselects in all the queries. Is there a reason we need to keep these superseded user review request records?

**Comment by jpraet** [comment]
This is done. Added team review requests to the filter + a refactoring to remove the code duplication in the issue filtering conditions.

**Comment by lunny** [comment]
> Fixes #13682
> 
> This adds a filter on the pull request overview pages that allows you to find the pull requests that are requesting your review.
> 
> * Is the name "Review Requested" for the filter OK? On GitHub it is called "Review Requests". Most clear is probably something like "Requesting your review", which is consistent in phrasing with the existing "Mentioning you" filter. What do you think?
I like `Review Requested` which is shorter than "Requesting your review"
> * Review requests records are not deleted once the review has taken place, so in the query I had to add a subselect to only take the last review record into account. I worry a bit about performance impact? Is there a better way?
Maybe we should have another PR to delete the review requests when user reviewed or PR merged/closed ?
> * With #13514 the existing "created", "assigned" and "mentioned" issue filters were made available through the API as well. Would you like me to add API support for the "review_requested" filter as well?
Yes, please!!!

**Review by zeripath — APPROVED** [review]

**Comment by jpraet** [comment]
> > * Review requests records are not deleted once the review has taken place, so in the query I had to add a subselect to only take the last review record into account. I worry a bit about performance impact? Is there a better way?
> 
> Maybe we should have another PR to delete the review requests when user reviewed or PR merged/closed ?

This can indeed be done in another PR. It would also require a data migration to delete the obsoleted review requests.

> > * With #13514 the existing "created", "assigned" and "mentioned" issue filters were made available through the API as well. Would you like me to add API support for the "review_requested" filter as well?
> 
> Yes, please!!!

Already done in 92c25fa992ca21882e23202699d55d4f1750d61c. So as far as I'm concerned this PR is ready for review and merge.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@jpraet can you update the branch ;)

**Pull request merged**
