### PR TITLE
Optimize png images via Google zopflipng [ci skip]

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use zopfli to re-compress the PNG images internally and losslessly to speed up webpage loading and save bandwidth.

149 PNG images re-compressed as below:
```
 public/img/404.png                                                          | Bin 4583 -> 4516 bytes
 public/img/500.png                                                          | Bin 5276 -> 5230 bytes
 public/img/avatar_default.png                                               | Bin 35142 -> 32491 bytes
 public/img/emoji/100.png                                                    | Bin 2630 -> 2622 bytes
 public/img/emoji/anger.png                                                  | Bin 2494 -> 2445 bytes
 public/img/emoji/ant.png                                                    | Bin 2154 -> 2151 bytes
 public/img/emoji/arrows_clockwise.png                                       | Bin 1399 -> 1380 bytes
 public/img/emoji/baby_bottle.png                                            | Bin 2353 -> 2313 bytes
 public/img/emoji/baby_symbol.png                                            | Bin 2178 -> 2170 bytes
 public/img/emoji/back.png                                                   | Bin 2449 -> 2394 bytes
 public/img/emoji/bamboo.png                                                 | Bin 2482 -> 2473 bytes
 public/img/emoji/banana.png                                                 | Bin 2431 -> 2380 bytes
 public/img/emoji/bar_chart.png                                              | Bin 2341 -> 2110 bytes
 public/img/emoji/battery.png                                                | Bin 2387 -> 2325 bytes
 public/img/emoji/beer.png                                                   | Bin 3345 -> 3141 bytes
 public/img/emoji/beers.png                                                  | Bin 3255 -> 3202 bytes
 public/img/emoji/beetle.png                                                 | Bin 2744 -> 2721 bytes
 public/img/emoji/bicyclist.png                                              | Bin 3144 -> 3130 bytes
 public/img/emoji/black_medium_small_square.png                              | Bin 1865 -> 1219 bytes
 public/img/emoji/black_medium_square.png                                    | Bin 2358 -> 1567 bytes
 public/img/emoji/black_small_square.png                                     | Bin 1569 -> 949 bytes
 public/img/emoji/black_square.png                                           | Bin 1332 -> 1183 bytes
 public/img/emoji/black_square_button.png                                    | Bin 1337 -> 1228 bytes
 public/img/emoji/blossom.png                                                | Bin 2590 -> 2513 bytes
 public/img/emoji/blue_book.png                                              | Bin 2925 -> 2863 bytes
 public/img/emoji/boat.png                                                   | Bin 2401 -> 2340 bytes
 public/img/emoji/bookmark.png                                               | Bin 2619 -> 2616 bytes
 public/img/emoji/bread.png                                                  | Bin 3454 -> 3435 bytes
 public/img/emoji/busstop.png                                                | Bin 1662 -> 1630 bytes
 public/img/emoji/cd.png                                                     | Bin 3334 -> 3330 bytes
 public/img/emoji/chart_with_downwards_trend.png                             | Bin 2334 -> 2236 bytes
 public/img/emoji/chart_with_upwards_trend.png                               | Bin 2310 -> 2273 bytes
 public/img/emoji/checkered_flag.png                                         | Bin 1675 -> 1619 bytes
 public/img/emoji/chestnut.png                                               | Bin 3231 -> 3126 bytes
 public/img/emoji/clap.png                                                   | Bin 3508 -> 3493 bytes
 public/img/emoji/clapper.png                                                | Bin 2587 -> 2544 bytes
 public/img/emoji/clock1230.png                                              | Bin 2797 -> 2789 bytes
 public/img/emoji/clock130.png                                               | Bin 2837 -> 2809 bytes
 public/img/emoji/clock230.png                                               | Bin 2853 -> 2820 bytes
 public/img/emoji/clock330.png                                               | Bin 2739 -> 2705 bytes
 public/img/emoji/clock5.png                                                 | Bin 2624 -> 2621 bytes
 public/img/emoji/clock530.png                                               | Bin 2832 -> 2806 bytes
 public/img/emoji/clock630.png                                               | Bin 2730 -> 2706 bytes
 public/img/emoji/clock730.png                                               | Bin 2794 -> 2789 bytes
 public/img/emoji/clock8.png                                                 | Bin 2603 -> 2601 bytes
 public/img/emoji/clock930.png                                               | Bin 2746 -> 2718 bytes
 public/img/emoji/clubs.png                                                  | Bin 1685 -> 1647 bytes
 public/img/emoji/confetti_ball.png                                          | Bin 2678 -> 2596 bytes
 public/img/emoji/couple.png                                                 | Bin 3465 -> 3402 bytes
 public/img/emoji/cupid.png                                                  | Bin 2805 -> 2793 bytes
 public/img/emoji/cyclone.png                                                | Bin 2753 -> 2722 bytes
 public/img/emoji/date.png                                                   | Bin 2596 -> 2545 bytes
 public/img/emoji/de.png                                                     | Bin 2220 -> 2144 bytes
 public/img/emoji/diamonds.png                                               | Bin 2405 -> 2396 bytes
 public/img/emoji/disappointed_relieved.png                                  | Bin 3160 -> 3128 bytes
 public/img/emoji/dolls.png                                                  | Bin 3476 -> 3390 bytes
 public/img/emoji/door.png                                                   | Bin 2729 -> 2584 bytes
 public/img/emoji/ear_of_rice.png                                            | Bin 2598 -> 2589 bytes
 public/img/emoji/earth_americas.png                                         | Bin 3193 -> 3152 bytes
 public/img/emoji/earth_asia.png                                             | Bin 3315 -> 3277 bytes
 public/img/emoji/eight_pointed_black_star.png                               | Bin 2337 -> 2323 bytes
 public/img/emoji/exclamation.png                                            | Bin 1175 -> 1108 bytes
 public/img/emoji/fearful.png                                                | Bin 2918 -> 2835 bytes
 public/img/emoji/fire.png                                                   | Bin 2778 -> 2752 bytes
 public/img/emoji/fireworks.png                                              | Bin 3197 -> 3142 bytes
 public/img/emoji/fr.png                                                     | Bin 2398 -> 2341 bytes
 public/img/emoji/fu.png                                                     | Bin 2614 -> 2603 bytes
 public/img/emoji/globe_with_meridians.png                                   | Bin 3431 -> 3357 bytes
 public/img/emoji/hatched_chick.png                                          | Bin 2941 -> 2896 bytes
 public/img/emoji/hatching_chick.png                                         | Bin 3226 -> 3164 bytes
 public/img/emoji/headphones.png                                             | Bin 1910 -> 1887 bytes
 public/img/emoji/heavy_minus_sign.png                                       | Bin 176 -> 172 bytes
 public/img/emoji/horse_racing.png                                           | Bin 2945 -> 2937 bytes
 public/img/emoji/hotel.png                                                  | Bin 2965 -> 2916 bytes
 public/img/emoji/ideograph_advantage.png                                    | Bin 2598 -> 2550 bytes
 public/img/emoji/it.png                                                     | Bin 2305 -> 2303 bytes
 public/img/emoji/last_quarter_moon.png                                      | Bin 3287 -> 3254 bytes
 public/img/emoji/ledger.png                                                 | Bin 3388 -> 3362 bytes
 public/img/emoji/lemon.png                                                  | Bin 3314 -> 3247 bytes
 public/img/emoji/lips.png                                                   | Bin 2367 -> 2187 bytes
 public/img/emoji/mag.png                                                    | Bin 2808 -> 2796 bytes
 public/img/emoji/mailbox_with_no_mail.png                                   | Bin 2240 -> 2155 bytes
 public/img/emoji/milky_way.png                                              | Bin 3190 -> 3177 bytes
 public/img/emoji/mountain_railway.png                                       | Bin 3100 -> 3031 bytes
 public/img/emoji/mouse2.png                                                 | Bin 2519 -> 2515 bytes
 public/img/emoji/musical_keyboard.png                                       | Bin 1944 -> 1813 bytes
 public/img/emoji/musical_score.png                                          | Bin 1497 -> 1433 bytes
 public/img/emoji/name_badge.png                                             | Bin 2800 -> 2777 bytes
 public/img/emoji/nose.png                                                   | Bin 2524 -> 2433 bytes
 public/img/emoji/notes.png                                                  | Bin 1536 -> 1525 bytes
 public/img/emoji/ok_woman.png                                               | Bin 3544 -> 3531 bytes
 public/img/emoji/pill.png                                                   | Bin 2770 -> 2681 bytes
 public/img/emoji/postbox.png                                                | Bin 2454 -> 2408 bytes
 public/img/emoji/question.png                                               | Bin 1640 -> 1581 bytes
 public/img/emoji/radio.png                                                  | Bin 3248 -> 3136 bytes
 public/img/emoji/radio_button.png                                           | Bin 2198 -> 2189 bytes
 public/img/emoji/railway_car.png                                            | Bin 2299 -> 2293 bytes
 public/img/emoji/raised_hands.png                                           | Bin 3122 -> 3036 bytes
 public/img/emoji/ram.png                                                    | Bin 3315 -> 3288 bytes
 public/img/emoji/rooster.png                                                | Bin 3162 -> 3087 bytes
 public/img/emoji/rotating_light.png                                         | Bin 3101 -> 3073 bytes
 public/img/emoji/rowboat.png                                                | Bin 2803 -> 2629 bytes
 public/img/emoji/ru.png                                                     | Bin 2349 -> 2337 bytes
 public/img/emoji/runner.png                                                 | Bin 2217 -> 2195 bytes
 public/img/emoji/running.png                                                | Bin 2217 -> 2195 bytes
 public/img/emoji/sailboat.png                                               | Bin 2401 -> 2340 bytes
 public/img/emoji/scissors.png                                               | Bin 2492 -> 2471 bytes
 public/img/emoji/shipit.png                                                 | Bin 4598 -> 4517 bytes
 public/img/emoji/slot_machine.png                                           | Bin 2861 -> 2571 bytes
 public/img/emoji/small_blue_diamond.png                                     | Bin 1555 -> 1525 bytes
 public/img/emoji/spades.png                                                 | Bin 1719 -> 1645 bytes
 public/img/emoji/speedboat.png                                              | Bin 2226 -> 2172 bytes
 public/img/emoji/squirrel.png                                               | Bin 4598 -> 4517 bytes
 public/img/emoji/sunrise.png                                                | Bin 2848 -> 2727 bytes
 public/img/emoji/sweet_potato.png                                           | Bin 3175 -> 3120 bytes
 public/img/emoji/tent.png                                                   | Bin 2916 -> 2910 bytes
 public/img/emoji/thought_balloon.png                                        | Bin 2521 -> 2494 bytes
 public/img/emoji/tongue.png                                                 | Bin 2765 -> 2676 bytes
 public/img/emoji/trident.png                                                | Bin 2705 -> 2609 bytes
 public/img/emoji/trolleybus.png                                             | Bin 2531 -> 2526 bytes
 public/img/emoji/trollface.png                                              | Bin 3262 -> 3258 bytes
 public/img/emoji/tropical_drink.png                                         | Bin 2305 -> 2276 bytes
 public/img/emoji/tulip.png                                                  | Bin 2955 -> 2923 bytes
 public/img/emoji/two_men_holding_hands.png                                  | Bin 3340 -> 3278 bytes
 public/img/emoji/two_women_holding_hands.png                                | Bin 3464 -> 3412 bytes
 public/img/emoji/violin.png                                                 | Bin 2571 -> 2552 bytes
 public/img/emoji/waning_gibbous_moon.png                                    | Bin 3513 -> 3474 bytes
 public/img/emoji/whale2.png                                                 | Bin 3249 -> 3236 bytes
 public/img/emoji/white_circle.png                                           | Bin 2477 -> 2457 bytes
 public/img/emoji/white_large_square.png                                     | Bin 1411 -> 1285 bytes
 public/img/emoji/white_medium_small_square.png                              | Bin 1800 -> 1260 bytes
 public/img/emoji/white_medium_square.png                                    | Bin 2085 -> 1593 bytes
 public/img/emoji/white_small_square.png                                     | Bin 1391 -> 958 bytes
 public/img/emoji/white_square_button.png                                    | Bin 1725 -> 1577 bytes
 public/img/emoji/womans_clothes.png                                         | Bin 2833 -> 2713 bytes
 public/img/emoji/x.png                                                      | Bin 1994 -> 1971 bytes
 public/img/emoji/zzz.png                                                    | Bin 1915 -> 1779 bytes
 public/img/gitea-large-resize.png                                           | Bin 16470 -> 16263 bytes
 public/img/gitea-lg.png                                                     | Bin 26945 -> 26939 bytes
 public/img/openid-16x16.png                                                 | Bin 230 -> 172 bytes
 public/img/slack.png                                                        | Bin 1516 -> 1424 bytes
 public/plugins/jquery.minicolors-2.2.3/jquery.minicolors.png                | Bin 68627 -> 68076 bytes
 public/plugins/pdfjs-1.4.20/web/images/loading-small.png                    | Bin 7402 -> 602 bytes
 public/plugins/pdfjs-1.4.20/web/images/loading-small@2x.png                 | Bin 16131 -> 1341 bytes
 public/plugins/pdfjs-1.4.20/web/images/toolbarButton-menuArrows.png         | Bin 108 -> 107 bytes
 public/plugins/pdfjs-1.4.20/web/images/toolbarButton-viewAttachments@2x.png | Bin 871 -> 866 bytes
 public/plugins/pdfjs-1.4.20/web/images/treeitem-collapsed-rtl.png           | Bin 183 -> 142 bytes
 public/plugins/pdfjs-1.4.20/web/images/treeitem-collapsed-rtl@2x.png        | Bin 205 -> 161 bytes
 vendor/gopkg.in/macaron.v1/macaronlogo.png                                  | Bin 88924 -> 70272 bytes
```

### CODE REVIEW

**Comment by sapk** [comment]
Vendored `vendor/gopkg.in/macaron.v1/macaronlogo.png` should not be modified so it will failed at CI check.

**Comment by bkcsoft** [comment]
The first 3 in there is fine, the rest you should send upstream since we just vendor them :)

**Comment by PeterDaveHello** [comment]
@bkcsoft it'll be good to send the updates to upstream, in the meantime, as they are committed in this repository, maybe it's fine to directly optimize the images here?

**Comment by lunny** [comment]
@bkcsoft  emoji is upstream files?

**Comment by bkcsoft** [comment]
@PeterDaveHello No, we should not tamper with external resources :)

@lunny Yes, seems to be [emojify](https://github.com/Ranks/emojify.js) https://github.com/gogits/gogs/commit/3b0c2cb480de28c97fced6857f9c0e006ac2a943#diff-c9b5a1b845abb8d0bcebdaf23d497b61R47

**Comment by appleboy** [comment]
agree with @bkcsoft just the first 3 files.

**Comment by PeterDaveHello** [comment]
What about the gitea logo?
```
 public/img/404.png                | Bin 4583 -> 4516 bytes
 public/img/500.png                | Bin 5276 -> 5230 bytes
 public/img/avatar_default.png     | Bin 35142 -> 32491 bytes
 public/img/gitea-large-resize.png | Bin 16470 -> 16263 bytes
 public/img/gitea-lg.png           | Bin 26945 -> 26939 bytes
```

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
