### PR TITLE
Fix require external registration password

### PR DESCRIPTION
**Pull request by guillep2k**
Investigating #8558, I've found that `REQUIRE_EXTERNAL_REGISTRATION_PASSWORD` was incorrectly applied in the registration form. Unrelated `REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA` was used instead to drive the password requirement.

### CODE REVIEW

**Comment by guillep2k** [comment]
:flushed: Sorry, it was not me who found this, it was @jolheiser !!! I'm just absentminded as usual. :sweat_smile:

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by jolheiser** [comment]
For the record, I think this is the root of #8558 as well.  
It mistakenly asks you for a password, but accounts created from GitHub don't set a password in Gitea and so when you go to delete your account or change your password, you need to use an empty password.

**Comment by guillep2k** [comment]
> 
> 
> For the record, I think this is the root of #8558 as well.
> It mistakenly asks you for a password, but accounts created from GitHub don't set a password in Gitea and so when you go to delete your account or change your password, you need to use an empty password.

@jolheiser Unfortunately, it doesn't seem to be the case. I've made all kinds of checks with and without this PR. But there's something stranger going on there. Check my latest comments.

**Comment by jolheiser** [comment]
Shouldn't `LinkAccountPostSignIn` also match? Currently it just has `ctx.Data["DisablePassword"] = setting.Service.AllowOnlyExternalRegistration`

**Comment by guillep2k** [comment]
> 
> 
> Shouldn't `LinkAccountPostSignIn` also match? Currently it just has
> `ctx.Data["DisablePassword"] = setting.Service.AllowOnlyExternalRegistration`

@jolheiser You're right. Although it's an edge case in case of some error happens before `ctx.HasError()` (some network timeout, perhaps). Fixed.

**Review by jolheiser — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Pull request merged**
