### PR TITLE
Consolidate the two review boxes into one

### PR DESCRIPTION
**Pull request by silverwind**
View diff: https://github.com/go-gitea/gitea/pull/24738/files?diff=unified&w=1

Improve layout and functionality in review area:

Screenshot 2023-05-15 at 20 10 01

Remove the "Reviewers" timeline box that appears before the merge box. it's a duplicate of the top-right review area and all functionality of it has been moved to the other box:

Screenshot 2023-05-15 at 19 39 31

Increase timeline item vertical padding from 12px to 16px:

Screenshot 2023-05-15 at 19 43 50

### CODE REVIEW

**Comment by silverwind** [comment]
There appears to be one feature in the old review box which is not yet in the top-right, which is "Dismiss Review". I will integrate that into top-right menu.

**Comment by silverwind** [comment]
Dismiss button re-added and working:

Screenshot 2023-05-15 at 20 03 04

**Comment by silverwind** [comment]
One more icon I missed is the stale icon, I've added it to top-right as well:

Screenshot 2023-05-15 at 20 10 01

**Comment by silverwind** [comment]
Conflict resolved automatically with rebase. Git was actually smart enough to apply the changes on the renamed `repo.css` file, which was a positive surprise.

**Comment by wxiaoguang** [comment]
I think it looks good.

If there is no other concern, I will vote my LGTM later.

**Comment by silverwind** [comment]
One thing I will check/fix is how the box behaves on smaller viewports. Up to a certain downsizing, the sidebar uses percentage width, which is not ideal here. Will likely change that to fixed width.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/24738/commits/42063164d9c841d770e17a4464be0f9d21af9255?diff=unified&w=1 changes the layout of issue/pr pages from previous fomantic layout which was problematic because the sidebar width was `25%` which changes with screen width, to a new flexbox layout where sidebar is always 300px above the mobile breakpoint, ensuring enough space on intermediate screen sizes.

I also fixed some small layout bugs as well.

### New PR Before - Incorrect avatar size and boxes not aligned

Screenshot 2023-05-16 at 22 29 46

### New PR After - Avatar fixed, boxes aligned, less margin

Screenshot 2023-05-16 at 22 27 36

### PR view before

Screenshot 2023-05-16 at 22 29 31

### PR view after - less margin, wider sidebar

Screenshot 2023-05-16 at 22 28 08

**Comment by delvh** [comment]
Question: What's the difference between `Re-requesting` and `dismissing` a review?
As far as I know, the only difference is the little icon being a waiting symbol instead of a commented icon.
Does it make sense to keep the two separate?
I don't see a benefit in keeping the two separate actions.
Should we merge them into one?
That would simplify both the API, UI, and implementation.
Additionally, problems as we've seen with the GitHub API for the @GiteaBot cannot happen…

**Comment by delvh** [comment]
(I know, it's slightly offtopic, but given that the two are now right next to each other, I had to ask the question)

**Comment by silverwind** [comment]
> Question: What's the difference between Re-requesting and dismissing a review?

As I understand, re-request is to revert the approval state to pending, and dismissal is to revert the rejection state to "not requested", e.g. to dismiss reviews that are otherwise blocking the merge.

>  Does it make sense to keep the two separate?

These are distinct features on GitHub's UI too. I think there is a slight distinction between resetting to "pending" vs. resetting to "not requested", but I'm not sure it makes any practical difference, so  a merge could be attempted, but I'd rather leave this effort for another PR and leave this one to a UI-only refactor.

**Comment by silverwind** [comment]
Another notable difference is that only repo admins can dismiss, while I think re-request does not have such strict rules and more roles can do it.

**Review by delvh — COMMENTED** [review]
Basically LGTM. However, this PR introduces two regressions at the moment:
```html
 templates/package/view.tmpl
44:                                     <div class="ui segment metas">
templates/explore/repo_list.tmpl
41:                             <div class="metas gt-df gt-ac text grey">
```
(and one remaining CSS style
```css
web_src/css/explore.css
31:.ui.repository.list .item .ui.header .metas {
```
)
Both use the removed `metas` styles.
So, we should think about completely removing this class in this PR.

**Comment by silverwind** [comment]
Ah, I had thought I removed `metas` everywhere, but thanks for double-checking. Will fix these soon.

**Comment by silverwind** [comment]
`.metas` removal done. Packages page also adjusted to use the new layout that issue page uses. View diff with https://github.com/go-gitea/gitea/pull/24738/files?diff=unified&w=1

Screenshot 2023-05-27 at 23 44 02

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
