### PR TITLE
Dont show expansion for empty actions steps

### PR DESCRIPTION
**Pull request by silverwind**
This hides the chevron icon and makes the step header unclickable for skipped steps because there is no content to expand on those.

Before:

Screenshot 2024-03-21 at 20 06 47

After:
Screenshot 2024-03-21 at 20 03 07

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
There was a bug because `tw-w-4` resolved to 14px instead of expected 16px because it's using `rem` units but out root element has 14px, so pixels sizes in tailwind docs currently do not apply to us.

Screenshot 2024-03-21 at 20 16 10

**Comment by silverwind** [comment]
Maybe I should just make a blank SVG instead of this hacky div 😆.

**Comment by silverwind** [comment]
> Maybe I should just make a blank SVG instead of this hacky div 😆.

Actually not, the JS parser can not correctly parse string `<svg/>` and I don't feel like making it do so.

**Comment by silverwind** [comment]
Found a better solution with `tw-invisible` to hide it.

**Comment by silverwind** [comment]
There are likely more statuses that are not expandable, but I need some help to know which ones out of these have not output and should not be expandable:

```
unknown <- no output?
waiting <- no output?
running
success
failure
cancelled
skipped <- no output
blocked <- no output?
```

**Comment by silverwind** [comment]
I made it now like this, I think it's likely correct, but confirmation would still be great.

```
running - expandable
success - expandable
failure - expandable
cancelled - expandable
skipped - not expandable
blocked - not expandable
unknown - not expandable
waiting - not expandable
```

**Comment by wolfogre** [comment]
> I made it now like below, I think it's likely correct, but confirmation would still be great. I'm especially uncertain about `blocked` and `unknown`.
> 
> ```
> running - expandable
> success - expandable
> failure - expandable
> cancelled - expandable
> skipped - not expandable
> blocked - not expandable
> unknown - not expandable
> waiting - not expandable
> ```

I believe it's entirely correct. There absolutely cannot be any logs for statuses `skipped`, ﻿`blocked`, ﻿`unknown` and ﻿`waiting`, while there may be for others.

**Review by denyskon — APPROVED** [review]

**Pull request merged**
