### PR TITLE
Add edit button to wiki sidebar and footer

### LINKED ISSUE #16655: Edit wiki sidebar via UI
- Gitea version (or commit ref): 1.16.0+dev-88-geaa791bed
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes at https://try.gitea.io/fnetx/wikistuff/wiki/Home

## Description
Editing the wiki is possible via the web. There is the _Sidebar.md file that is rendered as a sidebar (although I can't find it documented after all). We are looking into documenting this to the Codeberg Docs and noticed that it wasn't possible to edit it afterwards via the Web UI (https://codeberg.org/Codeberg/Documentation/issues/160#issuecomment-246327)

Please either allow to edit this special page, or add an "Edit Sidebar" button. Maybe also a "Create Sidebar" button to make people aware of this opportunity.

## Screenshots

Screenshot of a Gitea wiki index, there is a rendered sidebar, an edit button for the current page and a site navigation that does not show the special Sidebar page

### PR DESCRIPTION
**Pull request by n194**
This PR adds an edit button to wiki sidebars and footer

Closes #16655

### CODE REVIEW

**Comment by silverwind** [comment]
I think it should either be with a transparent background or with border and background (e.g. replace `label` with `button` class).

**Comment by n194** [comment]
@silverwind I tried it with the button class but there were some alignment/overflow issues. I can make it transparent, is there a class that I can use to revert the blue color of a link?

**Comment by silverwind** [comment]
Yes, add `muted` class to the `<a>`.

**Comment by n194** [comment]
Fixed
screenshot

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
BTW we really need to add some UI later to create sidebar and footer.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
