### PR TITLE
Change "show more repos" to  extend the repo list

### PR DESCRIPTION
**Pull request by lafriks**
Replaces #8230

image

image

### CODE REVIEW

**Comment by zeripath** [comment]
I think paging would be better, the repo list could be very very large indeed.

**Comment by lafriks** [comment]
I don't think paging would best option here as this is more for fast access to repos not for browsing

**Comment by silverwind** [comment]
Maybe just always extend it to the whole rendered page height?

**Comment by silverwind** [comment]
I also have a UX concern. Say my mouse is over the repo list but my intention is to scroll the whole page. Now I'd be inadvertently scrolling the repo list.

**Comment by lafriks** [comment]
@silverwind this is tricky from UX point in both ways :) If you do not add scrollbar you will always have to scroll up to access tabs, search box etc

**Comment by davydov-vyacheslav** [comment]
unstale (?)

**Comment by zeripath** [comment]
Obsoleted by #11321

**Pull request closed without merging**
