### PR TITLE
Update gitea version on docs/install-from-binary

### PR DESCRIPTION
**Pull request by bkcsoft**

### CODE REVIEW

**Comment by thehowl** [comment]
Yeah, but no, this will need to be manually updated; bad. Perhaps in the release script we could add the following?

```sh
rm -f latest
ln -s "$LATEST_RELEASE" latest
```
 
this way this can just point to the `latest` symlink

**Comment by bkcsoft** [comment]
@thehowl There's no "release script" 😞

**Review by lafriks — APPROVED** [review]

**Comment by strk** [comment]
LGTM, but I agree this should be somehow automated. Drone is uploading those packages, right ? So cannot it also create symlink ?

**Comment by lafriks** [comment]
@bkcsoft do not create new branches in main repo as it triggers too much task for drone ;)

**Comment by bkcsoft** [comment]
@lafriks Make me :trollface:

**Pull request merged**
