### PR TITLE
Revert "Fix delete u2f keys bug (#18042)"

### LINKED ISSUE #18096: Regression: Fix U2F modal bug - backport introduced issue into 1.15
> although double check that 1.15 is actually affected.

_Originally posted by @zeripath in https://github.com/go-gitea/gitea/issues/18040#issuecomment-997990906_

---

Well ... The backport #18042 seems to have introduced the bug it was about to fix in Gitea 1.15. As far as I can reproduce locally, Gitea 1.15 was not affected before that PR was merged, but starting with the merge (commit 91f5be889af4081b05d63aadecb1373689e1f57c), I can reproduce the issue / all modals pop up.

Reverting the backport appears to be fine.

Noticed this a few days ago, but was bumped by a user reporting this on [Codeberg](https://codeberg.org/Codeberg/gitea/issues/30) after 1.15.8+ was deployed.

### PR DESCRIPTION
**Pull request by lunny**
This reverts commit 91f5be889af4081b05d63aadecb1373689e1f57c. Fix #18096

I will send another PR to fix that bug.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by zeripath** [comment]
But I don't understand. This works fine on Chrome and Firefox when you download the binary from Gitea. It's also working for me on codeberg right now. 

Is it possible that the people who were having the bug had old cached js?

**Comment by wxiaoguang** [comment]
In `footer.tmpl`, the JS is loaded by `<script src="{{AssetUrlPrefix}}/js/index.js?v={{MD5 AppVer}}"></script>`, in most cases a new release will refresh the HTTP cache on client side, the only exception is that some CDN may ignore the dynamic parameters.

ps: I have no idea, either. But I have seen other bug reports for #18096 also, the bug seems not a rare case, likely many users meet it.

**Comment by wxiaoguang** [comment]
Maybe we should use `<script src="{{AssetUrlPrefix}}/js/index-{release-hash}.js"></script>` instead.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Ah I understand what the problem is now - it's not the u2f but everything else!

**Comment by wxiaoguang** [comment]
trigger bot

**Pull request merged**
