### PR TITLE
Moved defaults in defaults.go to setting.go

### PR DESCRIPTION
**Pull request by jolheiser**
As titled, I moved the few defaults in `defaults.go` to `setting.go` and removed `defaults.go` since it was then unused.

### CODE REVIEW

**Comment by adelowo** [comment]
¯\_(ツ)_/¯

**Comment by zeripath** [comment]
Hmm this looks like it's a nice simple fix but I don't know enough about our infrastructure - is it possible that our crowdin script or another script uses the defaults.go? @tboerger do you know if any of our infrastructure (ab)uses this file?

**Comment by zeripath** [comment]
I meant is there a dirty bash script out there that will "parse" the defaults file and update its values.

**Comment by tboerger** [comment]
I have not introduced something hacky like that.

**Review by zeripath — APPROVED** [review]

**Comment by adelowo** [comment]
`defaultThemes` isn't here anyways

**Review by lunny — CHANGES_REQUESTED** [review]
Please take `defaultThemes` back.

**Comment by zeripath** [comment]
@lunny `defaultThemes` isn't mentioned anywhere else in the codebase and appears to be completely redundant 

```
$ grep -r defaultThemes ~/go/src/code.gitea.io/gitea                [16:36:01]
~/go/src/code.gitea.io/gitea/modules/setting/defaults.go:	defaultThemes                            = strings.Split("gitea", "arc-green")
```

**Comment by lunny** [comment]
@zeripath  you are right. See https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L335

**Review by lunny — APPROVED** [review]

**Comment by adelowo** [comment]
Haha... Sorry my bad 😂. I could have sworn I used it somewhere

**Pull request merged**
