### PR TITLE
[Backport] Fix issues/pr list broken when there are many repositories (#8409)

### PR DESCRIPTION
**Pull request by 6543**
Backport of https://github.com/go-gitea/gitea/pull/8409

### CODE REVIEW

**Comment by guillep2k** [comment]
@lunny the version of xorm is OK for this?

**Comment by 6543** [comment]
```
routers/user/home.go:20:2: imported and not used: "github.com/Unknwon/com"
make: *** [Makefile:311: gitea] Fehler 2

```

**Comment by lunny** [comment]
@guillep2k  Only `SetExpr` with `Where` is a new feature of recent xorm but this PR has no that usecase. `release/v1.9` use builder v0.3.5 which supports `In` with subquery, https://gitea.com/xorm/builder/src/tag/v0.3.5/cond_in.go#L189 .
But I will wait until a new try instance upgrade before merge this.

**Review by guillep2k — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
sh*#, did not see blocked label :/

**Pull request merged**
