### PR TITLE
Update mergebase in pr checker

### LINKED ISSUE #10502: Squash merge message and compare incorrect following force-push
- Gitea version (or commit ref): 1.11.1
- Git version: 2.25
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/klinki/squash-merge-rebase-bug/pulls/1
  - [ ] No
  - [ ] Not relevant

## Description
Squash and merge functionality gets broken when branch is rebased.

It seems it caches original parent commit and when the parent changes (after rebase) it doesn't reflect those changes.

1) In commit message it shows unrelated messages from previous commits
2) After completing squash and merge it shows invalid commits in PR

Try looking at commit message on provided URL and also try doing squash and merge.

## Screenshots
gitea-screenshot

### PR DESCRIPTION
**Pull request by zeripath**
During PR check we should update the merge-base if it changes.

Fix #10502

### CODE REVIEW

**Comment by lunny** [comment]
I think we also need a migration to fix the old PRs.

**Comment by zeripath** [comment]
Hmm so on restart of Gitea all unmerged PRs should get their mergebase updated.

The issue with merged ones will be that it'll be difficult to decide what it should be after it's merged.

**Comment by zeripath** [comment]
OK just doing some testing on my system this fix does appear to fix #10502

**Review by guillep2k — APPROVED** [review]
Somehow I was expecting a PR with 17 files and 300+ lines changed. 😅

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
Ping lgtm

**Comment by 6543** [comment]
For migration: do we realy need one or just add this as option to the docktor?

**Comment by lunny** [comment]
Fixing old merged PR could be another PR.

**Comment by jolheiser** [comment]
Please send backport. :slightly_smiling_face:

**Comment by lunny** [comment]
migrations/v128.go:79:fixMergeBase() [E] Unable to get merge base for PR ID 4314, Index 6 in gitea/gitea-private. Error: exit status 128 - fatal: Not a valid object name fix-admin-2-master
	 & exit status 128 - fatal: ambiguous argument 'refs/heads/fix-admin-2-master': unknown revision or path not in the working tree.
	Use '--' to separate paths from revisions, like this:
	'git <command> [<revision>...] -- [<file>...]'

found some logs from gitea.com

**Comment by zeripath** [comment]
That means the base branch was deleted - so the merge base is impossible to recalculate. If the pr compare page was broken it will remain broken.

**Comment by zeripath** [comment]
Interestingly - and concerningly - viewing that PR gives me a 500. That entry will be skipped by the migration - therefore it's not that v128.go has broken this - but rather that we're not handling deleted base branches very well.

**Pull request merged**
