### PR TITLE
Forbid jQuery AJAX

### PR DESCRIPTION
**Pull request by yardenshoham**
Please use the fetch wrapper instead, or even better `htmx`.

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Depends on the remaining Ajax PRs.

**Comment by yardenshoham** [comment]
Thanks for the help reviewers! The work to remove jQuery is not done but this is a nice milestone to achieve.

**Comment by silverwind** [comment]
Indeed, I've been meaning to do this for a long time, good that you picked it up. One step closer to being jQuery-free.

**Review by delvh — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]
🎉

**Review by 6543 — APPROVED** [review]

**Comment by Snowiiii** [comment]
Can someone explain why we want to remove jQuery?  Isn't it a popular library, Whats the Problem?

**Comment by silverwind** [comment]
Because of performance and because it's considered a legacy library because DOM APIs have caught up to make it unnecessary.

FWIW, GitHub has completed the [same migration](https://github.blog/2018-09-06-removing-jquery-from-github-frontend/) in 2018 already, so we are very late in fact.

**Comment by 6543** [comment]
> Can someone explain why we want to remove jQuery? Isn't it a popular library, Whats the Problem?

https://youmightnotneedjquery.com/

**Comment by Snowiiii** [comment]
> Because of performance and because it's considered a legacy library because DOM APIs have caught up to make it unnecessary.
> 
> FWIW, GitHub has completed the [same migration](https://github.blog/2018-09-06-removing-jquery-from-github-frontend/) in 2018 already.

Thanks just rad trough the github site was very informative, So when we approximately will complete the migration ?

**Comment by 6543** [comment]
I would say as soon as the linter forbid all jquery 😆 

-> no timeline just steady progress

**Comment by silverwind** [comment]
The big problem is the fomantic ui dependency which needs to be ripped out first.

**Pull request merged**
