### PR TITLE
Add GPG check before commit message in repository table

### PR DESCRIPTION
**Pull request by lafriks**
Just made this by accident while making #1678 

Do not know performance implications for this so I did split these changes in other PR

### Screenshot (combined with other PR):
attels

### CODE REVIEW

**Comment by lunny** [comment]
I don't know why we need to put the lock there. Maybe put the commit build status is better?

**Comment by lafriks** [comment]
I don't know if status is that important in this view. GitHub does show GPG signature verification in repository file view but as I don't know what impact does it have on performance it's hard to tell if it's really that needed here also.

**Comment by lunny** [comment]
don't find github show GPG signature verification in repository file.

**Comment by lafriks** [comment]
You are right, github does not do that. I think this can be closed then

**Comment by sapk** [comment]
Signing the last commit can also be interpreted as signing/validating all the commit before since the hash of the last commit depend of previous commits (tree). So the only good information is that the last commit is signed. It would be impossible/hard to modify a old commit and still have newer singature valid.

**Pull request closed without merging**
