### PR TITLE
Respect the REGISTER_MANUAL_CONFIRM setting when registering via OIDC

### LINKED ISSUE #23392: OAuth registration flow doesn't respect manual confirmation requirement
### Description

Hi all,

The OAuth registration flow will log a newly registered user in regardless of the value of `GITEA__service__REGISTER_MANUAL_CONFIRM`.

Where the standard registration flow creates a user and lets [`handleUserCreated()` activate it](https://github.com/go-gitea/gitea/blob/542cec98f8c07e0f046a35f1d516807416536e74/routers/web/auth/auth.go#L578) if appropriate, the OAuth flow will [activate the user, conditional only on `GITEA__service__REGISTER_EMAIL_CONFIRM`](https://github.com/go-gitea/gitea/blob/542cec98f8c07e0f046a35f1d516807416536e74/routers/web/auth/oauth.go#L966), thereby bypassing the manual-approval check in `handleUserCreated()`.

It's not clear to me whether or not the activation overwrite in oauth.go is actually necessary at all.

### Gitea Version

1.17.4

### Operating System

Linux

### How are you running Gitea?

Docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by garymoon**
This change prevents Gitea from bypassing the manual approval process for newly registered users when OIDC is used.

- Resolves https://github.com/go-gitea/gitea/issues/23392

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
@kdumontnu care to review?

**Comment by garymoon** [comment]
> @kdumontnu care to review?

We try to avoid the conflict of interest since we work together at AllSpice.

**Review by wxiaoguang — APPROVED** [review]

**Comment by yp05327** [comment]
Maybe this PR also fixes #24138 ?
And it seems that there was a discussion about this issue before in #19310

**Comment by garymoon** [comment]
I agree #24138 does sound like the same issue. The discussion in #19310 seems to be around addressing this type of issue more generally, which would be good, but will be quite an undertaking by the sounds of it.

**Pull request merged**
