### PR TITLE
Update json-iterator to allow compilation with go1.18

### PR DESCRIPTION
**Pull request by Gusted**
- Update json-iterator/go to handle 1.18's new memory model with slices.
- Don't panic while running gitea with go 1.18

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
once gitea's minGo==1.18 we can clean up some utils & helpers with generics :D

**Comment by Gusted** [comment]
> once gitea's minGo==1.18 we can clean up some utils & helpers with generics :D

Given that happens we are on go 1.19, that should be fine and generics has been know for a while and hopefully the golang team has a "effective go generics" guide to do certain things a idiomatic way.

**Comment by 6543** [comment]
just one example that could use generics: https://github.com/go-gitea/gitea/blob/main/modules/util/paginate.go#L9-L34

**Comment by Gusted** [comment]
> just one example that could use generics: https://github.com/go-gitea/gitea/blob/main/modules/util/paginate.go#L9-L34

That would be one of the more straight-forward cases. But when it comes into advanced generics, it should take a conservative approach 😄

**Review by zeripath — APPROVED** [review]

**Pull request merged**
