### PR TITLE
Improve mobile review ui

### LINKED ISSUE #31071: Bad ui in mobile view when the language is not english
### Description

in english: (not too bad)
IMG_3912

in other language:
IMG_3911

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/31071

Not perfect but much better than before.

Before: Overflows, sticky not working, filename unreadable:

Screenshot 2024-05-27 at 02 02 40

After:
Screenshot 2024-05-27 at 01 59 06

### CODE REVIEW

**Comment by silverwind** [comment]
Should be ready now.

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Header after latest master merge, still looks fine.

image

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
https://github.com/go-gitea/gitea/issues/31071#issuecomment-2134760718

**Comment by silverwind** [comment]
> [#31071 (comment)](https://github.com/go-gitea/gitea/issues/31071#issuecomment-2134760718)

That should also be fixed here because the resolved placeholder no longer has a fixed height, so it will expand instead of overflow.

**Pull request merged**
