### PR TITLE
update git module to fix bugs in fact

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by cez81** [comment]
LGTM

**Comment by cez81** [comment]
make L-G-T-M work

**Comment by sapk** [comment]
@lunny have you updated the repo from a windows os ? I suspect that hash are not the same between linux and windows. (related go-gitea/gitea#1888)

**Comment by lunny** [comment]
I updated the repo on macOS Sierra.

**Comment by cez81** [comment]
I tried updating too and hash on Ubuntu is `Ju4zZF8u/DPrZYEEY40rogh3hyQ=`.

**Comment by sapk** [comment]
Same here (on archlinux with latest govendor) : 
```
{
-                       "checksumSHA1": "Ve00iavGUw8bQmDeXuEJ51wEk40=",
+                       "checksumSHA1": "Ju4zZF8u/DPrZYEEY40rogh3hyQ=",
                        "path": "code.gitea.io/git",        
-                       "revision": "a34a13dea30c0d242c5256cc321b48f8041ce095",
-                       "revisionTime": "2017-06-20T02:08:21Z"
+                       "revision": "51eca9e92242b93a0510edd19f1db6fc11ca1028",
+                       "revisionTime": "2017-06-21T01:06:07Z"
}
```

**Comment by sapk** [comment]
It seems that there is some inconsistency with the checksumSHA1 in govendor based on platform and mostly because of EOL difference between os.

**Comment by lafriks** [comment]
I have created new one #2037 that should be correct

**Pull request closed without merging**
