### PR TITLE
Update UI for topics labels on projects

### PR DESCRIPTION
**Pull request by MayMeow**
I updated ui for topics labels. Now labels are smaller with bottom margin on projects list which is missing in current version.

fixing #6621

### CODE REVIEW

**Comment by jolheiser** [comment]
Can you provide any screenshots for reference? 😃 
(I know it's a small change, but it's nice to be able to refer to before/after images)

**Comment by techknowlogick** [comment]
@jolheiser please see linked ticket for screenshots.

**Comment by jolheiser** [comment]
🤦‍♂️ Thanks

**Review by zeripath — APPROVED** [review]

**Comment by MayMeow** [comment]
adding some screenshots how it is looks now from localhost

Project list 

Screenshot from 2019-04-15 20-17-40

Project detail

Screenshot from 2019-04-15 20-17-57

Running version you can check here https://git.maymeow.red/explore/repos

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
