### PR TITLE
Remove jQuery `.attr` from the image diff again

### PR DESCRIPTION
**Pull request by yardenshoham**
- Follows https://github.com/go-gitea/gitea/pull/29917

Missed these

### CODE REVIEW

**Comment by yardenshoham** [comment]
I don't know how to test this one

**Comment by silverwind** [comment]
> I don't know how to test this one

A SVG file with defined `width` and `height` should hit this code.

**Comment by yardenshoham** [comment]
This is what I see on both `main` and this branch
image

The SVG:
```svg
<svg viewBox="0 0 16 16" class="svg octicon-star" aria-hidden="true" width="16" height="16"><path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.751.751 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25m0 2.445L6.615 5.5a.75.75 0 0 1-.564.41l-3.097.45 2.24 2.184a.75.75 0 0 1 .216.664l-.528 3.084 2.769-1.456a.75.75 0 0 1 .698 0l2.77 1.456-.53-3.084a.75.75 0 0 1 .216-.664l2.24-2.183-3.096-.45a.75.75 0 0 1-.564-.41z"></path></svg>
```

**Comment by silverwind** [comment]
Yes I think this is currently broken. It's okay if rendering is same before and after.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
