### PR TITLE
Fix the complete display of avatar

### LINKED ISSUE #31990: Unable to display complete avatar
### Description

Unable to display complete avatar, the avatar class of object-fit is `contain`.

GitHub can display the complete avatar because when GitHub changes the avatar, it must be cropped.

Maybe set the avatar class of `object-fit : cover` for the better.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

image

image

image

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by seepine**
Fix #31990

### CODE REVIEW

**Comment by lunny** [comment]
Can you paste the screenshot before and after?

**Review by delvh — APPROVED** [review]
Non-quadratic images might now look strange, but I think that's okay.

**Comment by silverwind** [comment]
I think I'm against it. `cover` will crop the avatar to the smallest dimension. I see more value in showing the full avatar.

**Review by silverwind — CHANGES_REQUESTED** [review]
I think I'm against it. `cover` will crop the avatar to the smallest dimension. I see more value in showing the full avatar. For example https://en.wikipedia.org/wiki/Longcat#/media/File:Longcat_is_loooooooooong.jpg:

`contain`:

image

`cover` (head cut off):

image

Ideally we should provide a cropping UI for avatar uploads, until then users need to pre-crop their images:

image

**Comment by silverwind** [comment]
I'd keep it as-is with `contain` as that ensures no cut-off content which is arguably better then the auto-cropping of `contain` which may crop wrongly. We should integrate a JS solution to crop images before upload. Maybe I will contribute that later.

**Pull request closed without merging**
