### PR TITLE
Use DO spaces to upload assets

### PR DESCRIPTION
**Pull request by techknowlogick**
before this gets merged I need to add secrets to drone for new access keys

### CODE REVIEW

**Comment by lunny** [comment]
How about to add a CNAME `storage.gitea.io` to `ams3.digitaloceanspaces.com`?

**Comment by techknowlogick** [comment]
@lunny that wouldn't work for uploads. Adding CNAME is just for CDN downloads.

**Comment by lunny** [comment]
@techknowlogick I don't think so. It should work since both them support AWS S3 interface.

**Comment by techknowlogick** [comment]
ok. maybe we do a test with `test-storage.gitea.io` to see if uploads work with drone plugin.

**Comment by techknowlogick** [comment]
Trying to enable `test-storage.gitea.io` on DO space, it seems we need to give DNS control of `gitea.io` to DO for letsencrypt certificate request. I prefer `gitea.io` stays with cloudflare.

**Comment by techknowlogick** [comment]
Closing as drone yaml conversion should happen before this PR is merged.

**Pull request closed without merging**
