### PR TITLE
Disable SSH key deletion of externally managed Keys

### LINKED ISSUE #13983: SSH keys should not be allowed to be deleted when coming from LDAP
When SSH keys are retrived from LDAP it makes no sense to allow removing them in Gitea (as they would be re-added anyway on next login). I would also go a step further and disallow also _adding_ them, as LDAP would then be the only point-of-truth.

### PR DESCRIPTION
**Pull request by zeripath**
When a user has a login source which has SSH key management
deletion of keys from that source using the UI should be disabled.

Fix #13983

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
Is it breaking? What happens to keys already added? Do they become unremovable?

**Comment by zeripath** [comment]
Oh crap I've just realised that I missed something - the keys do actually have a login_source.

**Comment by zeripath** [comment]
Lets try again - this time the buttons are disabled if the key is an externally managed key

**Review by lunny — APPROVED** [review]

**Comment by strk** [comment]
LGTM (not tested). I think for our goal we'll just drop all buttons and replace with a single button to direct users to the LDAP user management external url, which would still require a custom template, but it's good that there's no risk of some commandline tool removing externally managed keys

**Comment by techknowlogick** [comment]
🚀

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
