### PR TITLE
Fix visibility of organization repositories

### LINKED ISSUE #2399: Dashboard shows all organization repositories, not respecting access rights
- Gitea version (or commit ref): f61a1d21
- Git version:
- Operating system:
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

See title.

### PR DESCRIPTION
**Pull request by Morlinest**
Fixes #2399.

### CODE REVIEW

**Comment by ethantkoenig** [comment]
We shouldn't assume that the searcher doesn't have access to any of the privates repos in his/her organizations.

For instance, the searcher might be the owner of an organization, and therefore should have access to that organization's private repos.

**Comment by Morlinest** [comment]
@ethantkoenig I did tests before pushing this PR. It's working because if you are owner or any type of member with rights to repositories, you are in "access" table (I was also checking DB table). So this is perfectly fine and you see everything you should see.

**Comment by Morlinest** [comment]
That means, if you use `Collaborate` option, you see private repositories of organization too, if not, you see only public repositories of organization you are in.

**Comment by Morlinest** [comment]
Closing in favor of #2371.

**Pull request closed without merging**
