### PR TITLE
Add loading yaml label template files (#22976)

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #22976

Extract from #11669 and enhancement to #22585 to support exclusive scoped labels in label templates

* Move label template functionality to label module
* Fix handling of color codes
* Add Advanced label template

### CODE REVIEW

**Comment by delvh** [comment]
I've added the `breaking` label now so that we will reference in the blog post that the old files should be converted sooner than later, as the legacy format should probably removed in a few versions.

**Comment by lafriks** [comment]
I don't think we need to remove legacy format as that allows keeping compatibility with Github

**Review by lafriks — APPROVED** [review]

**Review by delvh — APPROVED** [review]
Nonetheless, users should upgrade their label sets.
And let it just be so they are able to set the `exclusive` attribute and whatever else we add in the future.
I'm not sure if keeping compatibility with GitHub makes sense in the longterm, if our two formats differ a lot by then.
As I said, in a few years (i.e. 3-5), we can think about removing the legacy version.

**Comment by lafriks** [comment]
In long term I agree that it can be removed

**Pull request merged**
