### PR TITLE
Remove external API calls in `TestPassword`

### PR DESCRIPTION
**Pull request by silverwind**
The test had a dependency on `https://api.pwnedpasswords.com` which caused many failures on CI recently:

```
--- FAIL: TestPassword (2.37s)
    pwn_test.go:41: Get "https://api.pwnedpasswords.com/range/e6b6a": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
FAIL
coverage: 82.9% of statements
```

This mocks the service using [gock](https://github.com/h2non/gock) and tests one positive and one negative case, removing this dependency and removing the need to have a password generator in the test because we control the responses.

Regarding concerns about compatibility, i think it's totally fine to mock this because if that service introduces a breaking change in their API, they better make a `/v2/` path or similar.

### CODE REVIEW

**Comment by jolheiser** [comment]
Rather than introduce a new dep we could just pull out the parse logic and make unit tests for this instead?

**Comment by silverwind** [comment]
> Rather than introduce a new dep we could just pull out the parse logic and make unit tests for that instead?

But is it a realistic test? I use such http mocks all the time, I think they are great.

**Review by jolheiser — APPROVED** [review]
I still don't think this test is as useful as a real integration test, but I'll concede that it's better than a flaky test.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
If the mocking framework becomes a problem, it can be replaced with the more manual way of https://pkg.go.dev/net/http/httptest but I don't see that currently being necessary.

**Pull request merged**
