### PR TITLE
[Backport] Fix milestone num_issues (#8221)

### PR DESCRIPTION
**Pull request by 6543**
Backport of https://github.com/go-gitea/gitea/pull/8221

### CODE REVIEW

**Comment by 6543** [comment]
@lunny @techknowlogick backport ...

**Comment by 6543** [comment]
sory for the Copy/Paste title mistake - changed

**Comment by 6543** [comment]
@lunny @techknowlogick backport ...
... drone done

**Comment by 6543** [comment]
will close https://github.com/go-gitea/gitea/issues/8069

**Comment by 6543** [comment]
@guillep2k point

**Review by guillep2k — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
