### PR TITLE
Unify doc links to use paths relative to doc folder

### PR DESCRIPTION
**Pull request by HesterG**
Changes:

1. Use uniform links types relative to doc folder (start with `doc/`)
2. According to [docusaurus links](https://docusaurus.io/docs/markdown-features/links), if `<a>` is used, the `href` is resolved as URL location, but not file location.  So need to use `[text]({{< relref "path" >}})` instead.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Could we have a check to prevent users to add newly wrong links in future PRs? This could also be another PR and will not block this one.

**Comment by silverwind** [comment]
> Could we have a check to prevent users to add newly wrong links in future PRs? This could also be another PR and will not block this one.

Doesn't either markdownlint or the docs build already do that?

**Comment by silverwind** [comment]
BTW, there is a docasaurus eslint plugin, but it does not do link verification:

https://docusaurus.io/docs/api/misc/@docusaurus/eslint-plugin

**Review by silverwind — APPROVED** [review]

**Comment by HesterG** [comment]
> https://docusaurus.io/docs/api/misc/@docusaurus/eslint-plugin

Thanks, I will check this.

> > Could we have a check to prevent users to add newly wrong links in future PRs? This could also be another PR and will not block this one.
> 
> Doesn't either markdownlint or the docs build already do that?

Looks like `markdownlint` does not have link checks? And `docs` copied files but did not do checks?

**Pull request merged**
