### PR TITLE
Make "cancel" buttons have proper type in modal forms

### LINKED ISSUE #25438: Pressing 'Enter' on repo settings modals hides the modal
### Description

When trying to delete/transfer/archive a repo from its settings, entering the name and pressing enter, the modal is simply being hidden instead of deleting the repo.

### Gitea Version

1.20-nightly

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker rootful

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Replace #25446, fix #25438

All "cancel" buttons which do not have "type" should not submit the form, should not be triggered by "Enter".

This is a complete fix for all modal dialogs.

The major change is "modules/aria/modal.js", "devtest" related code is for demo/test purpose.

### CODE REVIEW

**Comment by denyskon** [comment]
Thank you! I planned to simply go through all the modals and inserting proper button types, but this is an easier fix.

**Comment by wxiaoguang** [comment]
Yes, to make a project healthy, framework level support is a must.

**Review by denyskon — APPROVED** [review]

**Comment by delvh** [comment]
Backport?
If I've understood the problem correctly, I guess yes?

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Backport? If I've understood the problem correctly, I guess yes?

Yes, I will do manually backport, I guess the "devtest" part would conflict with 1.20

**Comment by lunny** [comment]
This needs to be backport.

**Comment by wxiaoguang** [comment]
Hasn't it been backported already?

->  Make "cancel" buttons have proper type in modal forms (#25618) #25641

**Pull request merged**
