### PR TITLE
websocket: response does not implement http.Hijacker

### PR DESCRIPTION
**Pull request by marxangels**

### CODE REVIEW

**Comment by techknowlogick** [comment]
Could you provide a description on the motivation for this PR, and perhaps some more details?

**Comment by marxangels** [comment]
Use WebSocket to do the notification, and keep `polling /user/events` as a fallback.

**Comment by zeripath** [comment]
You know /user/events is not actually polling right?

**Comment by marxangels** [comment]
> You know /user/events is not actually polling right?

Great! It's good enough.

**Pull request closed without merging**
