### PR TITLE
Add more milestone choices on issues list view

### LINKED ISSUE #11924: Milestone filter for pull requests shows either only open or closed milestones
- Gitea version (or commit ref): 1.11.4 
- Git version: 2.26.2
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/otbutz99/broken-milestones/pulls)
  - [ ] No
  - [ ] Not relevant

## Description

While browsing open PRs i'm only able to select open milestones in the filter and vice-versa. This way i'm unable to search for old PRs which targeted a milestone which is closed now or search for open PRs targeting a closed milestone.

The milestone filter should behave similar to the dropdown which is used to select the target milestone of a pull request. It should display all milestones but could provide a visual separation for open/closed ones:

milestone-dropdown

## Screenshots

open-prs
In this case i'm unable to filter open PRs targeting `v1.0.0` because it's a closed milestone.

closed-prs
Here i'm unable to filter PRs targeting milestone `v4.0.0` which is still open.

### PR DESCRIPTION
**Pull request by a1012112796**
As title

view:
image

fix #11924

### CODE REVIEW

**Comment by silverwind** [comment]
Can you add this to the bottom of arc-green to fix the header colors?

```css
.ui.dropdown .menu > .header:not(.ui) {
  color: rgba(255,255,255,.85);
}
```

**Comment by silverwind** [comment]
This dropdown can get quite large with a few milestones, maybe remove the dividers to save some vertical space (and I think they are unnecessary).

**Comment by CirnoT** [comment]
Does it even make sense to allow filtering via closed milestone on open issue? In what kind of situation would that be even useful?

**Comment by a1012112796** [comment]
> Does it even make sense to allow filtering via closed milestone on open issue? In what kind of situation would that be even useful?

Because, in my opinion, whether issue is open has no logical connection with whether milestone is open, it seems to impose a connection, that open issue must be in an open Milestone and closed issue must in closed Milestone. But, I found that the github also uses this strategy, so it should be reasonable.

**Comment by CirnoT** [comment]
Generally milestone is closed when all issues and PRs connected to it are also closed.

**Comment by otbutz** [comment]
Well, we can't filter closed issues based on open milestones either which makes perfect sense to me. See #11924

**Pull request closed without merging**
