### PR TITLE
Load issue/PR context popup data only when needed

### LINKED ISSUE #16257: Markdown references should be fetched asynchronously or be limited in count
- Gitea version (or commit ref): 1.15.0+dev-499-gca18c4d44
- Git version:
- Operating system: linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
When a markdown file or a comment contains lots of references (looking at you, CHANGELOG.md), they are all resolved, inducing very high server load: loading the view page of gitea's CHANGELOG.md takes ~15secs!

I'm not sure if it's sensible to just limit the number of references that are preloaded, as that change has quite a impact on functionality.
Loading those issue cards on demand (on hover?) might be a better approach, though inducing latency.
Maybe a hybrid approach is best: load max 5 references on page render, and resolve the rest on hover via ajax

### PR DESCRIPTION
**Pull request by lafriks**
Partially replaces #15293

Refactors to use Vue component for popup content

fix  #16257

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by jolheiser** [comment]
Can the title be renamed? I would not otherwise guess this also converts the feature to Vue. 🙂

**Comment by silverwind** [comment]
Can you do it in Vue 3 JSX format? I think we should start migrating to it :)

**Comment by lafriks** [comment]
that would require migrating all Vue components to Vue 3

**Comment by lunny** [comment]
Not all components should be converted to JSX. Only those components which have less 10 lines HTML could be implemented via JSX. Others, a SFC file is better.

**Comment by silverwind** [comment]
When I build UI components, I usually end up with many very small re-usable components, like for example a tooltip wrapper, or like in my other PR a label. I think JSX lends itself much better to such an approach and I think long-term JSX is the future of Vue anyways.

Will take a look at this PR later, possibly next week.

**Comment by lafriks** [comment]
ping @silverwind

**Comment by noerw** [comment]
This also fixes https://github.com/go-gitea/gitea/issues/16257

**Review by 6543 — APPROVED** [review]
works

**Comment by 6543** [comment]
@lafriks can you update the pull :)

**Comment by 6543** [comment]
.

**Pull request merged**
