### PR TITLE
Update mssql driver

### PR DESCRIPTION
**Pull request by sapk**
The mssql driver was blocked to an old version from 2016 because of a replace rule.

Changelog: https://github.com/denisenkom/go-mssqldb/compare/e32ca5036449...master

### CODE REVIEW

**Comment by lafriks** [comment]
Migrations does not seem to work anymore

**Comment by techknowlogick** [comment]
Looking at some of the logs it seems that during migration tests an earlier migration didn’t empty as there are errors about duplicate table:

`Error: mssql: There is already an object named 'access_token' in the database.`

**Comment by zeripath** [comment]
Looks like dropping the database between the migration tests didn't work

**Comment by zeripath** [comment]
They should be being dropped by:

 https://github.com/go-gitea/gitea/blob/7dd983797c218d7ae45e67d79517e95ad3dd24b8/integrations/migration-test/migration_test.go#L199

But this doesn't seem to be happening and it doesn't seem to be complaining about it

**Comment by zeripath** [comment]
Has some auto transaction support been added? It might be that it's expecting us to commit before it moving on?

**Comment by sapk** [comment]
I forget that I have done this PR before :man_facepalming:. 
This is now superseded by #7306 and futur work in #7294 to completely remove the replace in go.mod.

**Pull request closed without merging**
