### PR TITLE
Prevent clipping input text in Chrome + Segoe UI Font

### LINKED ISSUE #14162: Bottom text truncated on input text
- Gitea version (or commit ref): `1.14.0`
- Git version: N/A
- Operating system: Windows, Chrome
  
  
  
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/sdkjfhsadf/flectra2
  - [ ] No
- Log gist:

## Description

Bottom text truncated for input text. 

For some reason the line height in semantic UI is set to `line-height: 1.21428571em`. This results in hanging characters (such as `g`) to be truncated by padding.

Seems like this could be fixed by increasing the line-height in `semantic.css`, but not sure if this the appropriate fix.

## Screenshots

image

### PR DESCRIPTION
**Pull request by kdumontnu**
Closes https://github.com/go-gitea/gitea/issues/14162

### Before
image

### After
image

The overall element height stays the same. 

There is an issue in Chrome + Windows where the line-height is cropped too short. It seems like at least partially an issue with how Chrome calculates the height, but this fix should be more stable for different user fonts.

Note: I changed only the clone panel css classes. The other input elements remain as they were, as they didn't have the same issue with cropping the text.

### CODE REVIEW

**Comment by silverwind** [comment]
Can't reproduce on macOS but I wonder what's causing the clipping in first place. Normally, such clipping is caused by `overflow: hidden` but it's not set and even if I set a lower `line-height` like `.5em`, it would never clip because `padding` essentially counter-acts it. I must be missing something.

**Comment by kdumontnu** [comment]
> Can't reproduce on macOS

Perhaps if you use Segoe UI font (which is what I get with `system-ui` on Windows). 

> even if I set a lower line-height like .5em, it would never clip because padding essentially counter-acts it.

Hmm, appears your right. I assumed that since left/right padding clip text that the bottom padding would clip as well. However, when I set `height: 28px` the bottom padding doesn't clip the text. Only the low `line-height` clips the text (in Chrome). 

image

I'll update the [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1162116#c3).

I'm okay if you want to close this and just wait for a fix to come in Chrome. I'll probably merge the change in my fork.

**Comment by zeripath** [comment]
@silverwind I've seen clipping like this too.

**Comment by zeripath** [comment]
got it

**Comment by zeripath** [comment]
clipping

https://try.gitea.io/arandomer/merge-test

**Comment by zeripath** [comment]
this pr does fix that issue

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
Please update with base branch

**Pull request merged**
