### PR TITLE
Accept punctuation after simple+cross repository issue references

### LINKED ISSUE #10074: Cross reference doesn't render as a link if followed by punctuation signs (colon, semicolon, question, ...)
- Gitea version (or commit ref): 1.12.0+dev-220-gd7f4f87aa (current at try.gitea.io)
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/inextremares/testing/issues/5
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When a message references another issue with `#number` syntax the reference doesn't show as a link if there is a colon, semicolon, question sign or others punctuation signs just after it. I didn't test more but I thinks these are very common and should be supported.

## Screenshots

image

### PR DESCRIPTION
**Pull request by guillep2k**
This PR adds `,`, `;` and `:` as valid characters following a simple issue or PR ref, as long as there's a spacing character following:

```
#123 was supported.
#123. was supported.
#123, was not supported, now it is.
#123; was not supported, now it is.
#123: was not supported, now it is.
#123.456 is not supported.
```

Attempts to close (?) #10074, but I've left a few cases out; I feel a little uncomfortable trying to read too much out of the text with just a regexp, I don't want to start getting too many false positives:

- I didn't add question or exclamation marks... Seems excesive? I think exclamation marks look weird in the case of PRs (`Look at !1234!`) but it may work with issues (`Look at #1234!`).
- I did this only for simple and cross repository references, not external alphanumeric (`AAAA-1234`) references.

Fixes #10074

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
i think it close #10074

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
And `?` and `!`?
> Can `?` and `!` be supported as well? I think if the rule is the same (space or EOL immediately after) then it isn't ambiguous, but I can say nothing about the troubles to implement that.

**Comment by guillep2k** [comment]
> 
> 
> And `?` and `!`?

No problem, I can add those.

**Review by zeripath — CHANGES_REQUESTED** [review]
As per above awaiting addition of ? and !

**Review by zeripath — APPROVED** [review]

**Comment by guillep2k** [comment]
Added `!` and `?`. Fixed a bug where mentions/references were not detected if they were consecutive and shared a space:

```
......._REF1_REF2_.....
.......XXXXXX..........
............YYYYYY.....
```
This was not apparent in markdown rendering because the function takes them one by one.

**Comment by guillep2k** [comment]
> 
> 
> And `?` and `!`?

@lunny done.

**Pull request merged**
