### PR TITLE
refactor: ignore LGTM from author of pull request.

### PR DESCRIPTION
**Pull request by appleboy**
1. ignore LGTM from the author of the pull request.
2. remove MAINTAINERS file.
3. remove ignore case in the pattern.

### CODE REVIEW

**Comment by lunny** [comment]
No, no. Why deleted the MAINTAINERS file?

**Comment by appleboy** [comment]
@lunny `ignore_maintainers_file` set as `true` will ignore parse the `maintainers` file so we don't need this file anymore.

**Comment by appleboy** [comment]
It will load team member from GitHub API but you can't restrict some member of Gitea team to use the `L-GTM` service.

**Comment by lunny** [comment]
@appleboy all members of team `Maintainers` on `Gitea organization`  could L-GTM.

**Comment by appleboy** [comment]
@lunny Yes, I know but I don't know why we need to keep the `MAINTAINERS` file? It always calls the GitHub API. 

See: https://github.com/go-gitea/lgtm/blob/master/web/hook.go#L55-L74

**Comment by lunny** [comment]
@appleboy that's not for lgtm.

**Comment by appleboy** [comment]
@lunny revered and change lgtm pattern to `(?)LGTM`.

**Comment by appleboy** [comment]
@lunny @lafriks merge this PR?

**Pull request merged**
