### PR TITLE
disallow leading zeroes in Less

### PR DESCRIPTION
**Pull request by silverwind**
Because we're all lazy typers.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by guillep2k** [comment]
@silverwind somehow our CI doesn't like this change

**Comment by techknowlogick** [comment]
@guillep2k it's likely due to a recent change to less files that had rules with 0 prefix not caught by this, as the first time it was run it passed.

**Comment by silverwind** [comment]
Fixed new violations, should now pass.

**Comment by bagasme** [comment]
@silverwind Did you mean disallowing `099` but allowing `99`?

**Comment by silverwind** [comment]
@bagasme: Yes, `099` should be forbidden as well, but the primary aim is decimals, e.g. `0.5` -> `.5` which is quicker to type.

**Comment by guillep2k** [comment]
Ping LGTM

**Pull request merged**
