### PR TITLE
improve possible performance bottleneck

### PR DESCRIPTION
**Pull request by lunny**
Replace #28500

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Can't you just join the repository table to that query and get rid of the iteration?

**Review by 6543 — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Comment by fnetX** [comment]
Just adding here a quote from the Forgejo fix at https://github.com/go-gitea/gitea/pull/28500

> which is not possible in a UPDATE query for SQLite

We noticed that you apparently did not make a special case for SQLite, which likely breaks support for this database as per this PR.Test coverage for this part is not enough, thus not detected, I assume. Maybe I'm completely blind, but can you explain how the PR is supposed to work with SQLite?

**Comment by lunny** [comment]
Acorrding to the https://www.sqlite.org/lang_update.html, sqlite supports `Update Join`. But I also sent a PR

**Comment by fnetX** [comment]
Okay, maybe I confused it with DELETE and JOIN, sorry for bothering in this case. Did you check whether it works or not, so we don't attempt to fix bugs that don't actually exist? There is no automated testing for this one, and creating a test case with migrations wasn't trivial. I did not yet spend time on it.

**Comment by lunny** [comment]
> Okay, maybe I confused it with DELETE and JOIN, sorry for bothering in this case. Did you check whether it works or not, so we don't attempt to fix bugs that don't actually exist? There is no automated testing for this one, and creating a test case with migrations wasn't trivial. I did not yet spend time on it.

Yes, I will send a PR with tests for it.

**Comment by lunny** [comment]
I will send a revert first and then try to send a new PR. #28593

**Pull request merged**
