### PR TITLE
Create Mirror List

### PR DESCRIPTION
**Pull request by jakimfett**
Per conversation in #1029, [creating a mirror list](https://github.com/go-gitea/gitea/issues/1029#issuecomment-504835624) file.

cc @weyusi

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by mrsdizzie** [comment]
Hmm what is the purpose or advantage of including this list in the official repo? Seems very easy for abuse for us to link to repo we have no control over and give it some sort of official listing as a mirror. Those links could easily point somewhere else or include malicious content in the future.

Neither of the two links listed seem to be "mirrors" in the git sense (using --mirror). They are just regular clones of the Gitea repo and the first one is already two weeks old.

Sorry to come off as negative since it was suggested for the author to create this PR/list, but this doesn't feel thought out as-is and I don't think we should include this in the official repo for reasons above.

**Comment by techknowlogick** [comment]
Yes, I agree with @mrsdizzie.

**Comment by weyusi** [comment]
> Seems very easy for abuse for us to link to repo we have no control over and give it some sort of official listing as a mirror.

Indeed that's a concern, which is why I suggested _official_ mirror. Obviously that involves setting up an account over those websites.

> Those links could easily point somewhere else or include malicious content in the future.

There should a disclaimer that those links are not officially endorsed. Alternatively, it could be a list on @jakimfett website/repo which is more obvious to the users that the links are not affiliated.

---
My main intention of suggesting mirrors is to let (new) users know about some free gitea hosting, regardless whether this repo is mirrored. It's easier for them to get into gitea. Something that allows them to evaluate longer, compared to try.gitea.io.

If gitea.com is free (I don't know), then my suggestion doesn't apply.

**Comment by lunny** [comment]
@weyusi gitea.com is free. :)

**Comment by jakimfett** [comment]
> @mrsdizzie [commented](https://github.com/go-gitea/gitea/pull/7339#issuecomment-507508921):
> what is the purpose or advantage of including this list in the official repo?

The purpose of a mirror list is threefold.

First, and foremost, it is to provide a template for officially vetted mirrors.
As a part of that, I would recommend the project owner(s) defining what, exactly, constitutes an official mirror.

Secondly, it is to facilitate the move off Github, and to give users of gitea a non-Github option for obtaining the source code.

Thirdly, it is because git, outside the increasingly-walled-garden paradigm of Github, is inherently distributed, and establishing community mirrors reduces the load (and therefore, cost) on the 'flagship' host, eg gitea.com etc.

> mrsdizzie also commented:
> Seems very easy for abuse...

Such can be said of literally any software, in literally any paradigm that comes from a non-authoritative source, and especially when the command line and remote hosts are involved.

And yet, other software manages to have mirrors, 3rd party repositories, and a measure of peer-to-peer source sharing.

**If this is a core concern:**
Please state the threat model which gitea expects compliance with in regards to this, otherwise this is just F/U/D in a case where the distributed nature of git already provides checks against.

> mrsdizzie also commented:
> ...Neither of the two links listed seem to be "mirrors" in the git sense...

I've re-created the Assorted Tech repo with the `--mirror` flag, previously it was 'just' using `--bare` and `--shared` as flags.

The other repo (Codeberg) was suggested by another comment contributor, and was mostly included to avoid having my mirror as the only one on the list. I could just as easily have included the current [gitea.com](https://gitea.com/gitea/gitea_mirror) unofficial mirror, or done a websearch for other copies of the source code.

> mrsdizzie also commented:
> ...this doesn't feel thought out as-is...

Yeah, because there's a bit of a lack of functional requirements for this type of community resource, and I've got other problems that I'm focusing my semi-full attention on.

Provide me a clearly defined list of functional requirements, and the PR will be adjusted to meet it/them.

> mrsdizzie also commented:
> ...Sorry to come off as negative...

You're raising valid concerns. Thank you for doing so.

---
> @techknowlogick commented:
> Yes, I agree...

Okay, want to expand on that?  
Can you explain a bit about what point(s) you agree with?
Perhaps your analysis of where the PR could be adjusted?  

Provide some constructive criticism, rather than just a 'me too' comment?

Because if all you have is agreement, that's why the emoji responses exist.

---
> @weyusi commented: 
> ...a disclaimer that those links are not officially endorsed...

Yup, that's a good idea.  
I'll add that next time I have enough spare time on my plate to adjust the PR.

> weyusi also commented:
> ...free hosting...

I think you might be conflating a publicly hosted instance of the compiled gitea application with a mirror of the source code.

The former provides services to users, the latter is a distributed copy of text files.

**Comment by techknowlogick** [comment]
> I could just as easily have included the current gitea.com unofficial mirror

gitea.com is official, and soon development will move to it per #1029 

> Provide some constructive criticism, rather than just a 'me too' comment? Because if all you have is agreement, that's why the emoji responses exist.

As one of the Leads of Gitea I wanted to explicitly state my support for @mrsdizzie's concerns, which could've been missed if I had just used the emoji.

**Comment by jakimfett** [comment]
As a levelset, I've been following the progress of #1029 for quite a while.  
Getting involved [now-ish](https://github.com/go-gitea/gitea/issues/1029#issuecomment-496037711) because it's to a point where I judged my input, and potentially my resources, might be useful to the community.

> @techknowlogick commented:
> ...gitea.com is official...  

Per @lunny 's [comment on #1029](https://github.com/go-gitea/gitea/issues/1029#issuecomment-504711000), and the lack of inclusion of the `https://gitea.com/gitea/gitea_mirror` URL on [any official documentation](https://duckduckgo.com/?q=gitea_mirror) (or at least any that I was able to find through [a cursory search](https://duckduckgo.com/?q=gitea_mirror)), combined with the lack of a direct answer to [this question (again in #1029)](https://github.com/go-gitea/gitea/issues/1029#issuecomment-473701335), my assumption has been that gitea.com is _not_ production-ready until project ownership explicitly states it to be so.

Is [your comment](https://github.com/go-gitea/gitea/pull/7339#issuecomment-508359696) an official statement on the production-ready status of that particular host&cluster?  

And if so, do you have plans to make public the service level(s), backup paradigm, and threat model that can be expected from non-official repos hosted on the flagship instance?


> techknowlogick also commented:
> As one of the Leads of Gitea...could've been missed if I had just used the emoji...

Fair point.
I still maintain that you missed an opportunity to provide constructive feedback.
But I digress.

> techknowlogick also commented:
> ...support for @mrsdizzie's concerns...

Once again:
Which of the concerns?
What is your thought process on the individual concerns?

And, 
Did [my comment](https://github.com/go-gitea/gitea/pull/7339#issuecomment-508325784) address any of them, from your perspective?

---
Give me something actionable, and I'll do it.
Give me generic agreement, and I'll be frustrated by the lack of clarity and ask probing questions.
Which do you think is a more beneficial path?

**Comment by lunny** [comment]
@jakimfett I think I have replied @BNolet on https://github.com/go-gitea/gitea/issues/1029#issuecomment-485059518 . We are on the middle of migrating gitea. See my progress update on https://github.com/go-gitea/gitea/issues/1029#issue-209680985 . So we haven't update the document. https://gitea.com/gitea/gitea_mirror is just a mirror and the final gitea address will be https://gitea.com/gitea/gitea .

As I said before, gitea.com is free to host your public or private repositories. But we encourage you host them on yourselves' gitea instances. We cannot public a service level or something like that but we will take effort to do because we have decided to host gitea's development on it (I think we have to do that). But it's not a commercial production and we will not afford anything.

In fact, even if famous git services have ever lost users' git data. So I don't think production-ready is meaningful for a service. I just want to say we have done many things on the service to prevent repositories data loss(k8s/ceph). And it's almost ready to host gitea's development.

**Comment by jakimfett** [comment]
> @lunny commented:
> ...middle of migrating gitea...

Yup, noted, I'm following #1029 closely and I am a sysadmin, so I understand how migrations work.

May your scripts work well and your database stay in sync.  
Clustering properly is hard, and I'm glad someone not-me is doing it in this case.

> lunny also commented:
> ...So we haven't update the document...

That's the information I was looking for. Thanks.

If anyone wants to point me at specific documentation needs, I'm more than happy to help with that.

> lunny also commented:
> ...it's not a commercial production and we will not afford anything...

Having a "best practices for this (free) service" document placed in front of potential users of the service will most likely save you a lot of grief down the road.

> lunny also commented:
> ...we encourage you host them on yourselves' gitea instances...

Yes, which is the point of this PR, and the point of much of my comment, the focus on making the distributed cloud of gitea instances interoperate and cross-support as much as possible for the betterment of the community at large.

> lunny also commented:
> ... don't think production-ready is meaningful for a service...it's almost ready to host gitea's development.

You say it's not meaningful, but you use the same term ("ready") to define the gitea.com instance's status. Hence, my continued confusion.

---

That said, **I am still lacking concrete direction on this PR**.

Do you want me to close it (as a bad idea)?
Do you want me to update it in a specific (or general) way?
Do you want me to automate the process of keeping this branch up to date so the merge isn't blocked by commits to `master`?
Do you want me to open an issue specifically for the conversation around mirroring (eg definitions, processes, and reasoning for various adjacent topics like gitea mirror vs vanilla mirror)?
Do you want me to further explain anything further?
Do you have other questions?

...?

**Comment by lunny** [comment]
@jakimfett sorry made you confusion. I have rethink my approval and I agree with @mrsdizzie 's idea on https://github.com/go-gitea/gitea/pull/7339#issuecomment-507508921 . Please close this one but we will not lock this and people still could discuss furthermore.

**Comment by lafriks** [comment]
If there would be way to be able to verify that mirror repository has not been modified than this would be ok (like gitea binaries have gpg signatures that can be used to verify that binary has not been altered). Otherwise this can result in security problem if at first mirror is good when added to such list and later modified in rouge way

**Comment by Perflyst** [comment]
Before this gets merged I would wait until https://gitea.com/gitea/gitea is there. Otherwise everyone mirrors github.com/go-gitea/gitea which will be "deprecated" in the future.

**Comment by jakimfett** [comment]
Per @lunny, closing this until prerequisites are more firmly established and some consensus on what exactly mirroring means can be established.

**Pull request closed without merging**
