### PR TITLE
Handle yaml frontmatter in markdown

### LINKED ISSUE #5377: YAML frontmatter rendered improperly
Exemplary, in a Jekyll project, markdown files have a YAML front matter like this default one in `index.md`:
```markdown
---
# Feel free to add content and custom Front Matter to this file.
# To modify the layout, see https://jekyllrb.com/docs/themes/#overriding-theme-defaults

layout: default
---
```
Gitea tries to render it as if it was regular Markdown:

screenshot from 2018-11-22 10-28-41

Instead, it should detect it being the YAML frontmatter and render it properly, e.g. like this (screenshot created by adding four spaces in front of each line in the front matter):

screenshot from 2018-11-22 10-30-03

- Gitea Version: 4c1f1f9

### PR DESCRIPTION
**Pull request by zeripath**
Add goldmark-meta to render yaml frontmatter as a table

Fix #5377

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
OK, so issues with this approach:

* the yaml frontmatter is always rendered as table - so if you put something on an issue it will also be rendered

**Review by 6543 — APPROVED** [review]
smal diff huge efect ;)

I'm ok how it is formated - hiding it behind a icon is a nice idear but in my view not so importand

**Comment by zeripath** [comment]
make lg-tm work

**Comment by zeripath** [comment]
OK I'm going to merge but will continue to improve

**Pull request merged**
