### PR TITLE
update goth to add pkce support

### LINKED ISSUE #21376: Implement PKCE for OpenID Connect - Unable to login with LogTo
### Description

Hi,
I want to connect my Gitea instance to Logto OpenID connect
but I'm getting 421 status code with the error below in gitea container logs

```
2022/10/08 09:53:16 ...rs/web/auth/oauth.go:834:SignInOAuthCallback() [I] [63411754] Failed OAuth callback: (invalid_request) Authorization Server policy requires PKCE to be used for this request
```

I'm not able to do it in demo site since my logto instance is not fully available in public

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker Container

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by techknowlogick**
fix https://github.com/go-gitea/gitea/issues/21376

credit to @zeripath for the PR to goth

### CODE REVIEW

**Comment by zeripath** [comment]
I think we need to add a few more things to our openconnectid to hook it in

**Comment by mhkarimi1383** [comment]
CI is failing...
from the logs:
```
Please run 'make tidy' and commit the result
```

**Comment by Gusted** [comment]
CI failure still related, likely due to the changes in `assets/go-licenses.json`

**Comment by mhkarimi1383** [comment]
Any update on this?

**Comment by lunny** [comment]
> I think we need to add a few more things to our openconnectid to hook it in

What did you mean? Should we have more changes in this PR?

**Comment by silverwind** [comment]
Might want to update to [v1.75.1](https://github.com/markbates/goth/releases/tag/v1.75.1).

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
> > I think we need to add a few more things to our openconnectid to hook it in
> 
> What did you mean? Should we have more changes in this PR?

Yes, AFAIU we will need some more things in the openconnectid code to ensure that the PKCE stuff is hooked in.

**Comment by mhkarimi1383** [comment]
> > > I think we need to add a few more things to our openconnectid to hook it in
> > 
> > 
> > What did you mean? Should we have more changes in this PR?
> 
> Yes, AFAIU we will need some more things in the openconnectid code to ensure that the PKCE stuff is hooked in.

If you can give me a test docker image I can test it for git.karimi.dev (I have LogTo and gitea)

**Comment by wolfogre** [comment]
> > > > I think we need to add a few more things to our openconnectid to hook it in
> > > 
> > > 
> > > What did you mean? Should we have more changes in this PR?
> > 
> > 
> > Yes, AFAIU we will need some more things in the openconnectid code to ensure that the PKCE stuff is hooked in.
> 
> If you can give me a test docker image I can test it for git.karimi.dev (I have LogTo and gitea)

@mhkarimi1383

You could try this image `docker.io/wolfogre/gitea-dev:pr21426`, please note that it's for testing only.

**Comment by mhkarimi1383** [comment]
> > > > > I think we need to add a few more things to our openconnectid to hook it in
> > > > 
> > > > 
> > > > What did you mean? Should we have more changes in this PR?
> > > 
> > > 
> > > Yes, AFAIU we will need some more things in the openconnectid code to ensure that the PKCE stuff is hooked in.
> > 
> > 
> > If you can give me a test docker image I can test it for git.karimi.dev (I have LogTo and gitea)
> 
> @mhkarimi1383
> 
> You could try this image `docker.io/wolfogre/gitea-dev:pr21426`, please note that it's for testing only.


@wolfogre

the problem persist

```log
gitea       | 2022/11/09 21:08:56 [636ba668] router: completed GET /user/oauth2/Logto for 51.89.252.106:0, 307 Temporary Redirect in 3.6ms @ auth/oauth.go:801(auth.SignInOAuth)
gitea       | 2022/11/09 21:08:56 ...rs/web/auth/oauth.go:860:SignInOAuthCallback() [I] [636ba668-2] Failed OAuth callback: (invalid_request) Authorization Server policy requires PKCE to be used for this request
gitea       | 2022/11/09 21:08:56 [636ba668-2] router: completed GET /user/oauth2/Logto/callback?error=invalid_request&error_description=Authorization%20Server%20policy%20requires%20PKCE%20to%20be%20used%20for%20this%20request&state=39f9aeb6-70d4-4724-aa4b-7674620d762c&iss=https%3A%2F%2Fauth.karimi.dev%2Foidc for 51.89.252.106:0, 303 See Other in 2.6ms @ auth/oauth.go:835(auth.SignInOAuthCallback)
gitea       | 2022/11/09 21:08:57 [636ba669] router: completed GET /user/login for 51.89.252.106:0, 200 OK in 4.5ms @ auth/auth.go:152(auth.SignIn)
```

**Comment by mhkarimi1383** [comment]
Any updates?

**Comment by zeripath** [comment]
conflicts resolved

**Comment by zeripath** [comment]
> Any updates?

I haven't had any time to do the work to add the PKCE code in.

**Comment by lunny** [comment]
> conflicts resolved

Looks like it's a blank PR now

**Comment by mhkarimi1383** [comment]
But issue for PKCE Persist

**Pull request closed without merging**
