### PR TITLE
Fix wrong commit status in web ui

### PR DESCRIPTION
**Pull request by yp05327**
Before:
image
After:
image

There's a bug in the recent logic, `CalcCommitStatus` will always return the first item of `statuses` or error status, because `state` is defined with default value which should be `CommitStatusSuccess`

Then
``` golang
if status.State.NoBetterThan(state) {
```
this `if` will always return false unless `status.State = CommitStatusError` which makes no sense.
So `lastStatus` will always be `nil` or error status.
Then we will always return the first item of `statuses` here  or only return error status, and this is why in the first picture the commit status is `Success` but not `Failure`.
https://github.com/go-gitea/gitea/blob/af1ffbcd63569df8646b20c524378f25710f129e/models/git/commit_status.go#L204-L211

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by yp05327** [comment]
It seems that this logic problem comes from #25839
In old code, `CalcCommitStatus` will return true when the input is an empty string(default value).
``` golang
default:
    return css2 != CommitStatusError && css2 != CommitStatusFailure && css2 != CommitStatusWarning && css2 != CommitStatusPending
```

**Comment by silverwind** [comment]
Possible to add a test that verifies that "ok, fail" results in "fail"?

**Comment by yp05327** [comment]
> Possible to add a test that verifies that "ok, fail" checks result in "fail"?

Maybe a unit test for `CalcCommitStatus` is enough?

**Review by wxiaoguang — APPROVED** [review]
It could be simplified to:

```
	var lastStatus *CommitStatus
	if lastStatus == nil || status.State.NoBetterThan(lastStatus.state) {
		lastStatus = status
	}
```

**Comment by CaiCandong** [comment]
> It seems that this logic problem comes from #25839

My fault, the `status.State.NoBetterThan` I wrote only handles `CommitStatusError`, `CommitStatusFailure` `CommitStatusPending`, `CommitStatusSuccess`. A better way to work around this bug would be to make the `NoBetterThan` function more robust?

**Comment by wolfogre** [comment]
I believe this PR is good enough to merge, @CaiCandong please help to improve if you have any ideas.

**Pull request merged**
