### PR TITLE
switch to use packr to embed static assets

### LINKED ISSUE #4250: go-bindata is no longer maintained
go-bindata is no longer maintained as stated here: https://github.com/jteeuwen/go-bindata#warning

We should replace it with a maintained alternative like [packr](https://github.com/gobuffalo/packr).

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #4250

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by zeripath — COMMENTED** [review]
Need to change the snap/snapcraft.yaml too.

I can't believe that go-bindata isn't more clearly reported as required when building from source but it looks like it's not really mentioned. I think we need to add something to the documentation to say we're no longer using go-bindata and have moved to packr with URL - explaining that it should just be downloaded as necessary.

**Comment by techknowlogick** [comment]
Good idea @zeripath. I've updated snap, and in terms of documentation I agree. I think https://docs.gitea.io/en-us/hacking-on-gitea/ needs more information overall, especially in regards to use of make file (in addition to exactly how bindata is used).

If you are just waking up now that means it means I should've been asleep hours ago. If you want to get a head start on documentation feel free to push directly to my branch, otherwise I will add some when I wake up. Good night 😴

**Comment by zeripath** [comment]
hmm... So I just pulled this repo and tried to build:

```
Error: open /home/andrew/go/src/code.gitea.io/gitea/templates/repo/settings/deploy_keys.tmpl: too many open files
```

It's also extremely verbose whilst building...

**Comment by zeripath** [comment]
This too many open files problem is rather distasteful - it's a packing program why does it need to have >1000 file descriptors open?

**Comment by techknowlogick** [comment]
@zeripath I've reduced the number of files open required, let me know if this works for you.

**Comment by techknowlogick** [comment]
@zeripath docs added

**Comment by zeripath** [comment]
Thanks @techknowlogick . I'm still getting a too many files open error. 

The default ulimit on ubuntu is:

```bash
$ ulimit -n
1024
```
It really shouldn't be having open that many file-descriptors! There's something not right in packr I think.

What's your `ulimit -n`? Is it wildly higher?

**Comment by techknowlogick** [comment]
Thanks for checking again 😄 I really appreciate it.

`ulimit -n` is `4864` for me. I think packr is trying to parallelize packing the files by loading as many as it can at once. However, as 1024 is the default for ubuntu I'm going to set this PR as blocked as I don't want to tell potential devs to increase the file descriptor limit to be able to contribute to Gitea.

**Comment by zeripath** [comment]
I'm still shocked that it's doing this. I'm fairly certain that it must be leaking file descriptors somewhere.

Looking on my phone I've seen one place in decompress that's leaking fds: https://github.com/gobuffalo/packr/blob/b0dc8ae47dc76a183765618fbece41cd433a8e2c/box.go#L127

This reader isn't being closed...

But I don't know if that is the cause. I'd need to recompile and see.

**Comment by zeripath** [comment]
Hmm. OK so I upgraded to go 1.11 and this problem has disappeared...

I'm not sure whether that makes this a blocker or not?

---

I spoke too soon... It's still there.

**Comment by techknowlogick** [comment]
Closing this PR for now, if anyone wants to pick this up feel free. I may come back to this later, but for now bindata works.

**Pull request closed without merging**
