### PR TITLE
fixed URL joining problem

### PR DESCRIPTION
**Pull request by mzch**
fixed a general ResolveReference problem and a reCAPTCHA error.

### CODE REVIEW

**Comment by mzch** [comment]
The following line (in utils/url.go):
`if !baseURL.IsAbs() && !strings.HasPrefix(base, "/") {`
is a typo error?
`if !baseURL.IsAbs() && strings.HasPrefix(base, "/") {`

**Comment by zeripath** [comment]
@mzch yeah I think that might be a typo but I'm not sure what that line is supposed to be doing at all. I think it could do with some tests to ensure that this is doing what it says it should be doing, that is acting like path.Join but for URLs.

**Comment by mzch** [comment]
@zacheryph This line will delete a top char of relative URL. e.g. "wiki" + "?user=bob" -> "iki?user=bob"

**Comment by zacheryph** [comment]
How do I get people to stop tagging me in tickets? This is the third ticket this month I have been tagged in that I am completely unrelated to. :slightly_frowning_face:

**Comment by zeripath** [comment]
@mzch yeah I realise it would do that clearly incorect thing but what I'm trying to work out is what it was ever supposed to do...

@zacheryph sorry, I think they've all meant to be to me...

**Comment by lafriks** [comment]
Sorry @zacheryph your username is so close to @zeripath :)

**Comment by lafriks** [comment]
Imho this could break markdown URLs... If you specify url in markdown like: `[test](/test)` it  should result in `https://domain/test` not `https://domain/repo/subpath/test`

**Comment by lafriks** [comment]
Imho previous PR with was correct

**Comment by mzch** [comment]
@lafriks OK. I'll remake PR.

**Comment by guillep2k** [comment]
> 
> 
> @lafriks OK. I'll remake PR.

@mzch You probably only need to reopen it.

**Comment by zeripath** [comment]
Ok this dropping to / isn't going to work when Gitea is mounted on a suburl.

It's probably the cause of multiple bugs with suburls and it disagrees with the comment that the function says it does. 

https://github.com/go-gitea/gitea/blob/69d81b656978a03ff277a611f5c3d9ef1814d001/modules/util/url.go#L26

If we're gonna keep it this way we need to investigate every use of urljoin and think about how it's going to work with Gitea mounted on suburls. Any use of urljoin without removing an initial slash outside of markdown is suspect.

**Comment by guillep2k** [comment]
> If we're gonna keep it this way we need to investigate every use of urljoin and think about how it's going to work with Gitea mounted on suburls. Any use of urljoin without removing an initial slash outside of markdown is suspect.

Is it useful to keep two versions of the function, with different behaviors?

**Pull request closed without merging**
