### PR TITLE
Don't try to close related PRs when deleting a non-fork repository

### LINKED ISSUE #14775: Delete repository don't send issues notifications
When deleting a repository, I received many emails about closing the issues of the repository.

### PR DESCRIPTION
**Pull request by lunny**
Fix #14775

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm actually thinking on...

What do you mean you received lots of emails?

What kind of emails?

Are you fixing this at the right level?

**Review by zeripath — CHANGES_REQUESTED** [review]
Hmm thinking on I  don't think this is correct

**Comment by zeripath** [comment]
I think #14823 is more likely to be the correct thing.

**Comment by 6543** [comment]
#14823 got merged ...

**Pull request closed without merging**
