### PR TITLE
Add ActionRunStatus component

### PR DESCRIPTION
**Pull request by yp05327**
Related to: https://github.com/go-gitea/gitea/pull/23212#discussion_r1122856231

Decrease duplication of SvgIcon when display a run status svg.

### CODE REVIEW

**Comment by HesterG** [comment]
A question about the structure, why isn't `runstatus.js` put into the `js/components` folder?

**Comment by yp05327** [comment]
> A question about the directory structure, why isn't `runstatus.js` put into the `web_src/js/components` folder?

I didn't notice this problem, as `svg.js` was in `web_src/js`.

Then, 
I also have a question, why `.vue` files are in `web_src/js/components`.
And,
we also have a folder called `webcomponents`, what is the difference between them.

**Comment by wxiaoguang** [comment]
> we also have a folder called `webcomponents`, what is the difference between them.

See  Add document for webcomponents #23261

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
It should be another `vue` file.

**Review by lunny — APPROVED** [review]

**Comment by delvh** [comment]
Should we backport this PR?

**Comment by wolfogre** [comment]
> Should we backport this PR?

I think yes.

**Review by wolfogre — APPROVED** [review]

**Pull request merged**
