### PR TITLE
Build gitea1.11 with go1.13

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

### CODE REVIEW

**Comment by zeripath** [comment]
Go 1.13 instead of?

**Comment by techknowlogick** [comment]
It defaults to latest version of XGO, which is currently 1.14 so this PR brings it down to 1.13 support.

**Comment by zeripath** [comment]
Hmm could you check if an equivalent to #10583 makes building on go 1.14 work? That might be better than forcibly downgrading to 1.13 (although perhaps the archivist in me likes the idea of forcibly saying what this did build on)

**Comment by techknowlogick** [comment]
> although perhaps the archivist in me likes the idea of forcibly saying what this did build on

I completely agree. We already do this with our docker builds, and so we should keep same approach with our binary builds too. 

Your PR will solve one of the issues that 1.14 brings (specifically solves the linked issue), I'll create a patch file that you can apply to your PR that'll catch a few others (that others have yet to run into, but thankfully our tests catch).

**Review by zeripath — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
