### PR TITLE
Fixed heatmap not working in mssql

### LINKED ISSUE #5212: Dashboard heatmap always loading on mssql
```
/api/v1/user/user.go:170 GetUserHeatmapData()] [E] GetUserHeatmapDataByUser: mssql: Invalid column name 'timestamp'.
```

### PR DESCRIPTION
**Pull request by kolaente**
Fixes #5212

### CODE REVIEW

**Review by jonasfranz — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@kolaente please send backport to release/v1.6 branch

**Comment by kolaente** [comment]
@techknowlogick It looks like the heatmap isn't even included in 1.6, so there's no need to make a backport.

**Comment by techknowlogick** [comment]
@kolaente thanks for the reminder

**Comment by Cellebyte** [comment]
@kolaente, build a docker image from the master today which is integrated with our MsSQL Database.

The database schema is Latin1_General_CI_AI.

The return code is 500 "Internal Server Error".

Do we use the wrong schema?
```json
{
    "message":"arg timestamp as int: strconv.ParseInt: parsing \"2018-11-13T00:00:00Z\": invalid syntax",
    "url":"https://godoc.org/github.com/go-gitea/go-sdk/gitea"
}
```

**Comment by lafriks** [comment]
@Cellebyte please report new issue

**Comment by Cellebyte** [comment]
> @kolaente, build a docker image from the master today which is integrated with our MsSQL Database.
> 
> The database schema is Latin1_General_CI_AI.
> 
> The return code is 500 "Internal Server Error".
> 
> Do we use the wrong schema?
> 
> ```json
> {
>     "message":"arg timestamp as int: strconv.ParseInt: parsing \"2018-11-13T00:00:00Z\": invalid syntax",
>     "url":"https://godoc.org/github.com/go-gitea/go-sdk/gitea"
> }
> ```

#5328

**Pull request merged**
