### PR TITLE
Add merge files files to GetCommitFileStatus

### PR DESCRIPTION
**Pull request by jasugun**
Hi,

We'd like to add merge files files to GetCommitFileStatus fucntions so API returns the list of all the files associated to a merged pull request commit, like GitHub API does.
The list of affectedFiles for an API commit is fetched from toCommit() function in routers/api/v1/repo/commits.go, and API was returning no file in case of a pull request with no conflict, or just files associated to the confict resolution, but NOT the full list of merged files.

This would lead to situations where a CI polling a repo for changes could miss some file changes due to API returning an empty / partial list in case of such merged pull requests. (Hope this makes sense :) )

NOTE: I'd like to add a unittest in integrations/api_repo_git_commits_test.go but failed to understand how to add my own test bare repo so I can make a test on a merged pull request commit to check for affectedFiles.
Is there a merged pull request in there that I could use maybe?
Could someone please direct me to the relevant ressources with informations on how to do that please?

Thanks for your time,
Laurent.

### CODE REVIEW

**Comment by tdesveaux** [comment]
Hey,
I took this over from Laurent.
I managed to add and run a test on this but I'm not sure how to update test data for unit-testing to work.

What I did locally was to add two commits to the `user2/repo16` test data.
One which only commit a `new-file-to-merge.txt` empty file and a second merging it into `master` with `git merge --no-ff` to force a merge commit.

If someone could give any pointer on how to update this, I'd be grateful.

**Comment by lunny** [comment]
You can just checkout the bare repo and commit and push.

**Comment by tdesveaux** [comment]
I added a new bare repository in `modules/git/tests/repos/repo6_merge` as none of the existing felt appropriate, let me know if you see one you'd prefer to add this to.

This repo has this history:
```
$ git log --all --graph --oneline
*---.   022f4ce621 (HEAD -> main, origin/main) Merge remote-tracking branches 'origin/merge/add_file', 'origin/merge/remove_file' and
'origin/merge/modify_file'
|\ \ \
| | | * d179264139 (origin/merge/modify_file, merge/modify_file) modify file
| |_|/
|/| |
| | * 38ec3e0cdc (origin/merge/remove_file, merge/remove_file) remove file
| |/
|/|
| * ae4b035e7c (origin/merge/add_file, merge/add_file) add file
|/
* 37d35c7ed3 setup test files
```

I choose an octopus merge to test a case where a commit has >2 parents.

I also choose to do a test in the git module rather than an integration test as the issue is contained to the `GetCommitFileStatus` function.

Lastly, in addition to the `-c` -> `-m` change. I changed `--parents` to `--first-parent`. Without it, a file from the main branch which was not changed at all in the merged branch would be listed as well.
This change allowed the command output to stay the same so I removed the change to `parseCommitFileStatus`.

(Sorry, I forgot about the guildelines to merge main and not rebase the history of a PR. I should be able to find the previous branch if necessary. Although, this is basically a new PR at this point).

**Comment by lunny** [comment]
Please remove those unnecessary files like `description`.

**Comment by tdesveaux** [comment]
I think I stripped everything I could

**Review by lunny — APPROVED** [review]

**Comment by tdesveaux** [comment]
The e2e-tests failure seem unrelated to the changes AFAIK.
Managed to reproduce in one run out of 10, strange.

**Review by wxiaoguang — APPROVED** [review]
PRs from an org can't be updated/edited by maintainers.

So either keep the PR update-to-date by the author (to make sure it passes all checks), or let owners merge it without the update-to-date check.

**Comment by tdesveaux** [comment]
> PRs from an org can't be updated/edited by maintainers.

Didn't know that! Will keep it mind if I open another PR.

**Pull request merged**
