### PR TITLE
Issue 5924 fix compare button

### PR DESCRIPTION
**Pull request by zeripath**
Unfortunately the changes in #5877 caused breakage of #5924.

These changes revert the changes in #5877 and prevent the 404 on compare. 

It's not a complete fix for the compare button, we need to allow users to suggest their own branches.

### CODE REVIEW

**Comment by adelowo** [comment]
I will take a look

**Comment by zeripath** [comment]
Basically what we need to do is to a) make it clearer which repositories they're comparing and then allow them to suggest other repositories which on pressing enter should redirect to the appropriate URL.

**Review by techknowlogick — APPROVED** [review]

**Review by kolaente — APPROVED** [review]

**Comment by adelowo** [comment]
Anything else to do here ?

**Comment by lafriks** [comment]
please backport to release/v1.7 branch

**Pull request merged**
