### PR TITLE
Have time.js use UTC-related getters/setters

### LINKED ISSUE #30851: Activity pages (besides Pulse) seem to no longer work
### Description

Not sure if other users encountered this, but it appears that the contributors, contributor frequency, and recent commit graphs seem to no longer work currently i.e. I don't see any chart data.

To reproduce this, simply look at any of these pages while in a repository with recent commits.

The backend seems fine as I do see JSON responses from the related endpoints (e.g. /{username}/{repo}/activity/data for the `Contributors` page). Because of this, it looks like this maybe a problem with the frontend.

I also decided to checkout 21331be30cb8f6c2d8b9dd99f1061623900632b9 (when the contributors graph was introduced) and rebuilt my dev environment. Weirdly enough I still have the same problem, so I'm not sure what's going on (maybe some direct/transitive dependency causing this break?). 

### Gitea Version

53b55223d167c3fc996dd0278a656f421408ace7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

git version 2.44.0

### Operating System

Debian

### How are you running Gitea?

In a Docker dev container firing up a Gitea dev environment using the `launch.json` configurations found in Gitea's VSCode docs.

I did also use try.gitea.io and looked for other user repos with chart data but they seem to have the same problem.

### Database

SQLite

### PR DESCRIPTION
**Pull request by kemzeb**
Before this patch, we were using `Date` getter/setter methods that worked with local time to get a list of Sundays that are in the range of some start date and end date. The problem with this was that the Sundays are in Unix epoch time and when we changed the "startDate" argument that was passed to make sure it is on a Sunday, this change would be reflected when we convert it to Unix epoch time. More specifically, I observed that we may get different Unix epochs depending on your timezone when the returned list should rather be timezone-agnostic.

This led to issues in US timezones that caused the contributor, code frequency, and recent commit charts to not show any chart data. This fix resolves this by using getter/setter methods that work with UTC since it isn't dependent on timezones.

Fixes #30851.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Thank you for the fix.

TBH I didn't quite get the point how the bug occurs, and why UTC fixes the bug .... if the problem could be clarified, maybe we could also add some tests

**Comment by kemzeb** [comment]
Yes, after looking at this for some time I observed that the output of `startDaysBetween()` was different when I switched from PDT -> to China Standard Time. This should not be the case because each element in the array should be in Unix epoch time, which isn't dependent on timezones.

I'm am not well versed in working with Date-related APIs yet, but I believed that these differing values were caused by the `while` loop trying to modify the start date to be on a Sunday. Depending on your timezone, `startDate` would be given a different Unix epoch time because it may have been changed in the loop. I thought by working with UTC time, the start date won't be changed depending on your timezone.

If you see this approach as an issue please let me know!

**Comment by wxiaoguang** [comment]
Take a quick look:

1. There is another `getDay` call in `firstStartDateAfterDate` , is it right or not?
2. There are tests in `time.test.js`, I think this case should be covered.

**Comment by kemzeb** [comment]
> 1. There is another getDay call in firstStartDateAfterDate , is it right or not?

Sorry I wasn't specific enough about describing the problem. It is caused by both `startDaysBetween()` generating bad Unix epochs and the following function failing to map to the backend's own "start of the week" list that we pass to it:
https://github.com/go-gitea/gitea/blob/bb0e4ce581721afabbfcdf8d5a894ba124465577/web_src/js/utils/time.js#L39-L47

This is what causes the chart data to not be displayed. Regarding your question, I don't think it would be an issue to use UTC-based methods here too. I'll make the changes.

> 2. There are tests in time.test.js, I think this case should be covered.

I agree, I'll go ahead and add one or two there.

**Comment by kemzeb** [comment]
Recent changes has `firstStartDateAfterDate()` use UTC-related methods.

Having some trouble writing a test for `startDaysBetween()` since I want the test to make sure that its output remains the same when working with `Date` objects that have different local times. There doesn't seem to be a way to change the timezone that local time refers to but I'll keep looking

**Comment by kemzeb** [comment]
Decided to refactor `startDaysBetween() to use dayjs's `utc` plugin. By default `dayjs()` would assume we are working with local time when making calls like the `add()` call does. This change no longer has us worry about working with local time here.

I wondered if the `dayjs.extend()` call would be a problem (i.e. if it would be used elsewhere in the future), but dayjs handles this case. See [here](https://github.com/iamkun/dayjs/blob/3737c8c35459562d4e345136cbb83290e88c6692/src/index.js#L449).

I am still pondering how to test this. As I said this test should ensure that the output of this function remains the same when dealing with different timezones, but I haven't seen a way to temporarily change the timezone when working with `Date` or `dayjs` objects.

**Comment by kemzeb** [comment]
So... after integrating dayjs's utc plugin it worked perfectly fine in my dev environment but when running the frontend tests it freezes when it reaches `time.test.js` (deadlock?). I decided to revert my changes to keep using the `Date` object for now as I not sure what caused the freeze.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by kemzeb** [comment]
Thanks! Looking at the `main`'s commit history, it looks like embarrassingly forgot to set my git username and email on another machine I was using 😂.

**Pull request merged**
