### PR TITLE
Speed up CI: only reset fixture repositories when they have been changed

### PR DESCRIPTION
**Pull request by zeripath**
This PR creates a watcher that will watch the setting.RepoRootPath for changes during the integration test, and only if there is changes will the repo fixtures be recreated.

This should save substantial time when running CI.

This PR could be further improved by only resetting the repos that need to be reset but that would be a lot more complicated.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Does that really save time? Both successfull builds took a similar time then builds without this change.

**Comment by wxiaoguang** [comment]
> Does that really save time? Both successfull builds took a similar time then builds without this change.

I have the same question. Is it really worth to make it that complex? How much time would be saved?

**Comment by zeripath** [comment]
It's difficult to assess the speed improvement over a few runs as the improvement will be most apparent when there is IO bound related slowness - this will be dependent on the load on the CI server.

In general testing I've definitely noticed that there can be a lot of time between tests - and part of that I assumed was due to this copying but it's perhaps its a smaller proportion than I was expecting and the problem is elsewhere?  Certainly most tests do not need the LFS data copied every time and most don't need the repos reset either - this PR will be saving some time but it appears not much.

One of the slow downs with MSSQL related tests is likely something to do with the way DB fixtures are loaded/reloaded and I would not be surprised if there was a way to improve that.

---

I'm not sure how "Have the repo fixtures changed? If so reset them" is particularly complicated. Yes it's more complicated than deleting and recopying them every time - but it's not particularly complicated.

A more complicated improvement would be to only copy across the repos that have actually changed. We'd have to assess whether that is worth it. I suspect not given the majority of tests do not need the repos copying.

---

I guess I'll have to add timers to see if this is really worth doing and get some numbers on how much of an improvement this causes and where the delays truly are. I wonder if [trace annotations](https://pkg.go.dev/runtime/trace@go1.20.1) might be helpful.

**Comment by zeripath** [comment]
OK adding some specific timing information this saves just about half of the time taken within prepareTestEnv over the course of the CI suite on my very fast laptop.

That sounds impressive but it's saving 15s of 31s that call takes on my computer. I think it's possibly still worth doing but it's not necessarily impressive.

**Comment by delvh** [comment]
I wanted to suggest using nested transactions.
Then I googled, and apparently that's not possible cross-platform.
If it had worked, it would allow us to wrap our tests in a parent transaction, and simply rollback the parent transaction after every transaction…
That way, we would only need to populate the db once, and subsequently no changes could be made between tests.
But unfortunately that's not feasible for Gitea as it isn't locked into a single database…

**Comment by wxiaoguang** [comment]
> however my laptop takes around 6 minutes to run the test suite.

I think maybe it's worth to upgrade these CI servers first. The question is that why the CI servers run so slowly? Use faster SSD? Use in-memory file system?

Spending more money on hardware sometimes is better than spending a lot of work time - time is precious. More complicated, more time has been spent, more time (in the future) is needed.

**Comment by zeripath** [comment]
I'm telling you that this improves test-sqlite times by 15s over a 6min run on my computer.

That is 4% decrease in CI time for me for just doing a little less work during set-up.

That's a significant decrease in CI time for me personally AND I am running on a very fast laptop with an SSD.

**Comment by wxiaoguang** [comment]
My experience of resolving problems is: clarify the problems first.

1. What's the problem? The CI time is too long.
2. What causes that long time?
    * Is it that long everywhere? No, local tests are fast. (maybe 20min vs 6min?)
    * Is there any bottleneck on CI server? CPU? Memory? Disk? No proof yet.
    * Is some code the bottleneck? Maybe, not sure (no proof yet). This PR improves 4%

I think the second question is not clear at the moment. Even if some fine tunes on the CI server could make the test-sqlite finish in 15min, that's 25% improvement, far more than 4%.

I am not saying this PR is not good, but I just want to clarify the problem first.

**Comment by wxiaoguang** [comment]
This PR: test-mysql8: 27:10 (it doesn't seem to be a noticeable improvement comparing to old PRs)

Latest PR: testing-mysql8: 14:55


I think other improvements really do better than the this PR's 4% improvement.

So I think this PR could be closed.

**Comment by wxiaoguang** [comment]
New record (with far more new test cases):

https://github.com/go-gitea/gitea/actions/runs/25539930833/job/74963492613?pr=37603

* mysql: 11:56
* mssql: 12:12

**Pull request closed without merging**
