### PR TITLE
Add --quiet and --verbose to gitea web to control initial logging

### PR DESCRIPTION
**Pull request by zeripath**
One of the repeatedly reported issues has been that gitea produces too much console
logging during set up even if the console logger is turned off.

Fundamentally this is due to some otherwise very helpful logging that has to occur
before logging is set up. This has come to a head with the merging of #16243 where
otherwise potentially helpful Trace logging in the git module now appears on the
console.

This PR proposes three things:

1. Change the initial default logger to Info not Trace.
2. Change the logging for the AppPath things to Info in recompense.
3. Add two new command line options to gitea web: --quiet and --verbose

`gitea web -q` or `gitea web --quiet` will only log Fatal level initially.
`gitea web -verbose` will log at Trace.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Sorry to add this to 1.15 but I think it's actually needed otherwise #16243 will need to be reverted.

**Comment by 6543** [comment]
@zeripath conflicts

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Well it didn't before you made it conflict (!)

**Comment by zeripath** [comment]
conflicts resolved

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
Fixes #13464

**Pull request merged**
