### PR TITLE
refactor: remove workaround after the golang 1.7 release.

### PR DESCRIPTION
**Pull request by appleboy**
This workaround has been fixed on Go 1.7.

### CODE REVIEW

**Comment by bkcsoft** [comment]
We still support 1.6 though AFAIK

**Comment by appleboy** [comment]
@bkcsoft I think we can recommend user using go 1.7 version to build binary and update README. This main purpose for this repo is offering the binary, not package.

**Comment by strk** [comment]
I think one of the purposes of a free software project is making users able to exercise their freedom of building/modifying the software. The least barriers we put to build, the better. Latest stable *Ubuntu* distribution (not Debian) comes with Go 1.6, I would not drop support of that.

My rule of thumb to be friendly with free software developers is: reduce deps to those available on latest Debian Stable. Does anyone know what that ships ?

**Comment by strk** [comment]
So Debian 8 ships 1.6.1, Ubuntu LTS ships 1.6.2 - I am using 1.6.2 for everyday development, so please don't make my contributions harder

**Comment by lunny** [comment]
We should add a tag to ask go build version.

**Comment by strk** [comment]
If you handle to split the file so to have go-version specific versions, chances are build tags on that are implicit

**Comment by appleboy** [comment]
@lunny @bkcsoft Done. Please review again.

**Comment by lunny** [comment]
LGTM

**Comment by pgaskin** [comment]
Seems fine. LGTM

**Comment by appleboy** [comment]
@strk Any concerns about this? We use `os.RemoveAll` function in windows after go1.7 now and backward compatibility.

**Comment by strk** [comment]
Is the go1.7 tag implicit? LGTM anyway

**Pull request merged**
