### PR TITLE
Prevent webhook action buttons from shifting

### LINKED ISSUE #15443: Shrink view url hooks
When adding a hook the url should have a fixed size to avoid moving the action buttons.
**Url**: org/orgname/settings/hooks

Captura realizada el 2021-04-13 00 34 55

### PR DESCRIPTION
**Pull request by justusbunsi**
Before:
(Really) Long webhook URLs forced the corresponding action buttons to be relocated so that they are below the URL text. This breaks the UI.

Now:
The URL text will be truncated (`https://my-really-long-...`) if it would overflow the reserved space on the site. For accessibility the full URL is available for screen readers as `title` attribute and will be visible when hovering over the truncated text.

Screenshots in the comments below.

------
Fixes: #15443
Signed-off-by: Steven Kriegler <61625851+justusbunsi@users.noreply.github.com>

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for PR :) Could you add somescreenshots to show the differences?

**Comment by justusbunsi** [comment]
@techknowlogick Sure.

Before:
image

Now:
image

I tested different widths and think 90% fits most. 92% was too close to the action icons.

**Comment by justusbunsi** [comment]
Just realized that it's is not fully fixed. If you reduce the browser window size, the buttons will be relocated. I think, `@media` based widths should do the trick, right?

**Comment by techknowlogick** [comment]
I've just set the WIP label so people will be sure not to merge or review.

**Comment by justusbunsi** [comment]
@techknowlogick Now the webhook url is properly truncated for all the supported `@media` sizes. I've noticed that it's duplicated style definition. Should I reduce these duplicated style definitions (I made) with a placeholder or something else?

**Comment by justusbunsi** [comment]
If this duplication is OK, you can remove the wip label.

**Comment by techknowlogick** [comment]
Awesome. I've removed the WIP label.

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
I think this can probably be solved much more elegantly using CSS truncation using `text-overflow: ellipsis` and no media query fiddling like that. Can you try it?

**Comment by justusbunsi** [comment]
@silverwind I am using `text-overflow: ellipsis`. It's declared inside the css class `truncate`. As per [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) `text-overflow: ellipsis` only affects block elements or elements with specified `width` or `max-width` at itself or some parent element. Since the anchor element is no block element (and in this context not even via css) and no parent element has a `width` or `max-width`, I had to define a width for the anchor element. With that `width` it was not responsive without different values for different browser sizes.

Maybe I am overcomplicating this, but after testing this with a smaller browser size I was not happy with just one fixed width since it behave the same as mentioned in the issue.

**Comment by silverwind** [comment]
You can usually force block-level via `display: inline-block` or similar but sometimes the changes necessary can be a bit more far-reaching depending on the surrounding structure/CSS. I think such a solution is certainly preferrable instead of introducing a dependency on the site's media query breakpoints.

**Comment by justusbunsi** [comment]
Will try you suggestion.

**Comment by silverwind** [comment]
Here's some sample CSS that should get you somewhere:

```css
.selector {
  overflow: hidden;
  display: inline-block;
  text-overflow: ellipsis;
  white-space: nowrap;
}

**Comment by justusbunsi** [comment]
Now i got it. Without the media queries. 😃 Your hint with the parent element structure was gold. I solved it by adding `truncated-item-container` to the `.item` div parent element which makes it `display: flex`. Combining it with the `.truncate` (that includes your ellipsis snippet) at the anchor element and a small inline css to align the buttons horizontally instead of underneath each others, the end result looks like that:

image

which is pretty much the same as the media query approach. Except for the space between text and button.

**Comment by justusbunsi** [comment]
@silverwind This is ready for your feedback when you have time for it. 😉

**Review by noerw — APPROVED** [review]

**Pull request merged**
