### PR TITLE
UI: Tweak tab text and icon colors

### PR DESCRIPTION
**Pull request by silverwind**
This adds a hover highlight and fades out inactive tabs.

##### Before
Screenshot 2019-04-25 at 20 20 43

##### After
Screenshot 2019-04-25 at 20 34 02

##### After (Dark)
Screenshot 2019-04-25 at 20 15 07

### CODE REVIEW

**Comment by silverwind** [comment]
Updated. Turns out the dark theme already had this hover effect implemented, so I removed the styling there and simplified it a bit.

**Review by lafriks — APPROVED** [review]

**Review by jonasfranz — APPROVED** [review]

**Comment by silverwind** [comment]
Sorry, had to do one more minor tweak. Inactive tabs are faded out a tiny bit more now (.5 over .6):

Screenshot 2019-04-26 at 13 55 55

**Comment by silverwind** [comment]
Anything blocking the merge here?

**Comment by techknowlogick** [comment]
@silverwind once the conflict has been resolved, I can merge this.

**Comment by silverwind** [comment]
It's the damn CSS file as always, rebased, regenerated and force-pushed.

**Comment by techknowlogick** [comment]
Merged. Thanks for your contribution 😄. I will also take this time and suggest to you that you'd make a great candidate for a maintainer of Gitea. One benefit would be you'd be able to provide reviews on other PRs. The only requirement is that you participate in one PR review every few months, or contribute code in the same time frame (which you already meet). I understand it is asking for a minor time commitment, and so please don't feel pressured to accept.

**Comment by silverwind** [comment]
Guess I can do that. Just put up a PR to add myself to maintainers file?

**Comment by techknowlogick** [comment]
@silverwind yup

**Pull request merged**
