### PR TITLE
Remove unnecessary goroutine

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Queue.pushfunc may block.

Are you sure that this is actually unnecessary?

I remember leaving this in because of this potential.

**Comment by lunny** [comment]
> Queue.pushfunc may block.
> 
> Are you sure that this is actually unnecessary?
> 
> I remember leaving this in because of this potential.

The implementation should keep this function not block I think. We may add a comment on the interface method.

And I think for block condition, `PushFunc` is the same as `Push`, but we used `Push` many places with no goroutine.

Also I checked the implementation of levelqueue and redisqueue, they should not block the function.

**Comment by zeripath** [comment]
They can all block - just hopefully and usually for not very long. The point of the goroutine was because I think in this particular instance we didn't want any delay to the calling function - I can't quite remember which one that was - and because I suspect there was a potential chance of a deadlock in the original pre-Queue implementation as PRs. 

There could still be a deadlock potential here. IIRC the handler for this Queue calls this function. If you're using a channel or persistable channel then if the channel is full and there's no more boosts available you could have the worker for the queue blocked waiting for a worker to pop work off the queue. 

So if that's the case then we need this or we need to adjust the queue.push implementations for channel etc to do a select send and goroutine if blocked.

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
