### PR TITLE
gofmt

### PR DESCRIPTION
**Pull request by ethantkoenig**
Run `make fmt`.

Sorry if this is nitpicky, but in development it would be convenient to run `make fmt` on my working changes without causing a bunch of changes elsewhere in the codebase.

### CODE REVIEW

**Comment by appleboy** [comment]
@ethantkoenig Maybe we can wait for https://github.com/go-gitea/gitea/pull/1366 PR?

**Comment by ethantkoenig** [comment]
@appleboy This is (part of) the reason the build for #1366 is failing

**Comment by sapk** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
