### PR TITLE
Add dependabot config for automatic gomod/npm update PRs

### PR DESCRIPTION
**Pull request by dbast**
Merging this opens update PRs like they can be seen here https://github.com/dbast/gitea/pulls

Proposed updates can be merged if CI is green or closed to be ignored.

There are also commands to tell dependabot e.g. to ignore specific major versions `@dependabot ignore this major version` as described in the PRs.

### CODE REVIEW

**Comment by silverwind** [comment]
I'm against it for at least the JS because JS is mostly untested, so updates can and will break it. Also, many of those updates require additional work like that dependabot can not execute. It's not much work to do this manually where one can actually validate the changes instead of blindly merging PRs.

**Comment by wxiaoguang** [comment]
Agree with silverwind.

If we want to update, the developer should take the responsibility for the feasibility and stability, instead of updating blindly.

**Comment by silverwind** [comment]
I guess it might be debatable to enable it for golang dependencies, the testing situation is certainly better there, but I'm not sure if it's enough to allow blind updates.

**Comment by wxiaoguang** [comment]
"golang dependencies, the testing situation is certainly better there", well ... just better, the coverage is still not high .... 😂

**Comment by dbast** [comment]
While using dependabot a lot in other projects, merging blindly can be dangerous of test don't cover specific functionalities, though the update PRs with the summary/changelog they provide I always find to be good read to see how the dependency is evolving and to check if there are breaking changes or security updates included.

**Comment by Gusted** [comment]
Just my 2cents.

If you have a repo with quite few dependencies, you will slowly hate those emails/notifications you will get about dependabot. Yeah, you will get them weekly, but each update has their own PR(which is really spammy, because dependabot tends to like force pushes and other things to just get you on the edge on emails github can send to you). See https://github.com/dependabot/dependabot-core/issues/1190

**Comment by techknowlogick** [comment]
Thank you for this PR.

I have similar feelings as @Gusted. In terms of overloading maintainers with notifications. I already get hundreds a day from non-bots and think adding to that would be too much. We also generally group our dep updates (for both go and npm). I think @6543 even has a script for updating the go deps.

**Comment by 6543** [comment]
yes: https://github.com/go-gitea/gitea/blob/main/contrib/update_dependencies.sh

I'm for closing this too - sorry dependabot has it's pro&cons and for us i see more con than pro :/

**Pull request closed without merging**
