### PR TITLE
Lint and document manager api

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by tboerger** [comment]
There is already a pr that updates it heavily?

**Comment by lunny** [comment]
this PR will be conflicted with #75.

**Comment by strk** [comment]
#75 is targetted at 1.1.0 and currently blocked

**Comment by tboerger** [comment]
You have set it to 1.1, it was set to 1.0

**Comment by strk** [comment]
Oh, I did. It was a WIP and I thought we were going to release 1.0.0 with the least change to allow for upgrades. If it's ready to merge and you think it is safe then change it back (I cannot modify milestones anymore).
Once again, this PR is smaller in scope.

**Comment by lunny** [comment]
`Golint` fixed is always welcome. Since both `sdk` and `git` are `Golint` OK. I think we could fix this repo's Golint problems before v1.0.0.
So let's see #75's progress to decide how to resovle this one.

**Comment by strk** [comment]
#75 by @metalmatze is blocked on drone availability, for which a PR also by @metalmatze exists (#96)

Does it really make sense to wait on all these semaphores rather than merging small PRs ?

**Comment by lunny** [comment]
So let's LGTM this and let #75 rebase.

**Comment by tboerger** [comment]
LGTM

**Comment by lunny** [comment]
resolved #70

**Pull request merged**
