### PR TITLE
Revisions (second try)

### LINKED ISSUE #5254: Implement Pull Requests history
It would be nice to have history of changes in the pull requests as it is in gitlab, for example: if someone pushes commit with `force`, it would be nice to have diff of what was before this push, so, probably, we should store changes for that and notify user on each push event as in gitlab.

### LINKED ISSUE #12604: Versions in Pull requests.
After someone opened a PR from a branch every push that introduces new commits (including the cases where some or all of the previous commits are removed/changed) should generate an entry, a kind of "new version" in the Pull Request's page.

It should be possible to quickly look at this entry generated and find out what has changed between the versions (by taking the user to a diff/compar page)

This is supported in Github, Gitlab, and Gerrit. 

Also on the changes _Files changed_ tab the user should be able to compare any two versions and see what has changed between those versions.
(This is supported in Gitlab and Gerrit but not in Github at the moment, or at least its not clearly reachable from the PR's page).

### LINKED ISSUE #12800: Create tree compare page for comparing two changesets/patchsets each consisting multiple commits.
The current diff page only shows how the content tracked by the repo changes between two commits.

Some people would like to do PR review not just reviewing the content of the change but also the fact of how it is structured into commits. To be able to track PR evolution it would be useful to see how the change is moving between commits for changesets/PR revisions. (The reason why some people want this is mostly that they have the philosophy that they are trying to keep a tidy/clean history. Also they are maybe trying to  make "atomic changes" which are  self contained enough to easily move between branches, by e.g.: cherry-picking )

How this should look like visually is an interesting question.

Basically you want to continue to see the change contained in the changesets but also there is an extra additional "dimension" about comparing how they are distributed between commits how they moved between commits. Also the number of commits can change, some or all could be squashed into one commit. 

New additional changes between changesets (e.g.: revisions of a PR) could come in either as brand new separate commits or as part of a previously existing commit.

I am not aware of any system that have UI for something like this.

### PR DESCRIPTION
**Pull request by ghost**
Second try of: #12665

Fixes #12604
Fixes #5254
Fixes #12800

For the range-diff page to work the interdiff (part of the patchtools package) is required on the server.

### CODE REVIEW

**Comment by alvardes** [comment]
Somebody could please add `interdiff` to the test environment? @lunny

**Comment by lafriks** [comment]
Can something like be reused/extended https://github.com/kordianbruck/interdiff to not introduce dependency on something that everybody would need to install as it does not come by default on most OS

**Comment by alvardes** [comment]
@lafriks Maybe. I tried it with this:

`diff1.txt`:
```
diff --git a/asdf b/asdf
deleted file mode 100644
index 8bd6648..0000000
--- a/asdf
+++ /dev/null
@@ -1 +0,0 @@
-asdf
diff --git a/binder b/binder
new file mode 100644
index 0000000..048e138
--- /dev/null
+++ b/binder
@@ -0,0 +1 @@
+binder
diff --git a/uuu b/uuu
new file mode 100644
index 0000000..1802629
--- /dev/null
+++ b/uuu
@@ -0,0 +1,5 @@
+asdf2
+
+ttt
+
+
```

`diff2.txt`:
```
diff --git a/asdf b/asdf
deleted file mode 100644
index 8bd6648..0000000
--- a/asdf
+++ /dev/null
@@ -1 +0,0 @@
-asdf
diff --git a/binder b/binder
new file mode 100644
index 0000000..048e138
--- /dev/null
+++ b/binder
@@ -0,0 +1 @@
+binder
diff --git a/mmmm b/mmmm
new file mode 100644
index 0000000..1802629
--- /dev/null
+++ b/mmmm
@@ -0,0 +1,5 @@
+asdf
+
+ttt
+
+
```

Interdiff says:

`interdiff diff1.txt diff2.txt`:
```
reverted:
--- b/uuu
+++ /dev/null
@@ -1,5 +0,0 @@
-asdf2
-
-ttt
-
-
only in patch2:
unchanged:
--- /dev/null
+++ b/mmmm
@@ -0,0 +1,5 @@
+asdf
+
+ttt
+
+
```

Which is not bad.

That function says:

```
--- /dev/null
+++ /dev/null
--- b/binder
+++ b/binder
--- b/uuu
+++ b/mmmm
@@ -1,5 +1,5 @@
-asdf2
-
-ttt
-
-
+asdf
+
+ttt
+
+
```

**Comment by alvardes** [comment]
@lafriks I was playing with these go interdiff implementations and honestly implementing interdiff is probably easier than I initially thought. I will change this to use a go implementation of interdiff instead of the patchutils one. Until that is done I will put this PR back into draft mode.

**Comment by alvardes** [comment]
Hm. The version here, works somewhat good: https://github.com/google/go-patchutils. But it still doesn't deal with extra lines created by git and the a/filename b/filename thing correctly. The repo requires the google contributor whatever to be signed to contribute so... not ideal.

**Comment by lafriks** [comment]
As it is only single file we could move it into Gitea modules and change it to work as we need

**Comment by alvardes** [comment]
@lafriks  Yes. I am doing it. 

I am changing it to track the `diff --git` extra lines like "rename from" and "rename to" and to output instead of a regural interdiff a `diff --git` format.

I have done some part of it but it is not yet ready.

**Comment by lunny** [comment]
Closed as the author disappeared.

**Pull request closed without merging**
