### PR TITLE
CI: Update license & gitignore by cron

### LINKED ISSUE #12684: Suggest auto do generate-license & generate-gitignore
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

As title, I think it's necessary to do generate-license & generate-gitignore Periodically. Maybe we can use drone cron work to do it. Thanks. It maybe looks like this

```YML
---
kind: pipeline
name: license_gitignore_update

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - cron # each one or two month is enough

# do something ....
```

### PR DESCRIPTION
**Pull request by a1012112796**
close #12684

### CODE REVIEW

**Comment by lunny** [comment]
You should check if there are real changes.

**Comment by a1012112796** [comment]
> You should check if there are real changes.

Hmm, How about this way?
``` DIFF
diff --git a/.drone.yml b/.drone.yml
index 8aaf5c7e6..280cdba9a 100644
--- a/.drone.yml
+++ b/.drone.yml
@@ -457,6 +457,7 @@ trigger:
   image: golang:1.15
   commands:
     - timeout -s ABRT 40m make generate-license generate-gitignore
+    - git diff --quiet && ( echo 'not need update'; exit 1)
 
 - name: push
   pull: always
```

**Comment by lunny** [comment]
> > You should check if there are real changes.
> 
> Hmm, How about this way?
> 
> ```diff
> diff --git a/.drone.yml b/.drone.yml
> index 8aaf5c7e6..280cdba9a 100644
> --- a/.drone.yml
> +++ b/.drone.yml
> @@ -457,6 +457,7 @@ trigger:
>    image: golang:1.15
>    commands:
>      - timeout -s ABRT 40m make generate-license generate-gitignore
> +    - git diff --quiet && ( echo 'not need update'; exit 1)
>  
>  - name: push
>    pull: always
> ```

If there is no change, the second push step should not be run

**Comment by techknowlogick** [comment]
@lunny the git push plugin is smart and if there are no changes then it won't commit or push anything. See our current translations pipeline for example.

**Comment by lunny** [comment]
So why we need a cron job for not like we did on translations?

**Comment by a1012112796** [comment]
> So why we need a cron job for not like we did on translations?

Because they not change frequently like translation file. so I think do it monthly by cron job is better.

**Review by 6543 — APPROVED** [review]
like it ...

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by 6543** [comment]
Screenshot at 2021-01-23 03-54-34
added ...

**Pull request merged**
