### PR TITLE
Update JS dependencies

### PR DESCRIPTION
**Pull request by silverwind**
- Update all JS dependencies
- For octicons, rename trashcan to trash
- For svgo, migrate to v2 api, regenerate files
- For stylelint, update config, fix custom property duplicates
- For monaco, drop legacy Edge support
- For eslint, enable new rules, fix new issues
- For less-loader, remove deprecated import syntax

### CODE REVIEW

**Comment by silverwind** [comment]
Will check later on the reason behind the SVG path changes. It looks like a svgo regression because the files are mostly larger than before.

**Comment by TrySound** [comment]
This is a fix for wider environments support. Not a regression.

**Comment by silverwind** [comment]
Yeah, I just read into https://github.com/svg/svgo/pull/1353 and it looks to be a compatibilty fix for SVG renderers that can not deal with the condensed `arcto` syntax. I think we can keep the change.

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind 
```sh
- /home/user/git/gitea/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/user/git/gitea/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/user/git/gitea/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:14:41)
    at Module._compile (/home/user/git/gitea/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)

ERROR in ./web_src/less/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
TypeError: (0 , _schemaUtils.validate) is not a function
    at Object.lessLoader (/home/user/git/gitea/node_modules/less-loader/dist/index.js:26:29)
    at processResult (/home/user/git/gitea/node_modules/webpack/lib/NormalModule.js:583:19)
    at /home/user/git/gitea/node_modules/webpack/lib/NormalModule.js:676:5
    at /home/user/git/gitea/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /home/user/git/gitea/node_modules/loader-runner/lib/LoaderRunner.js:252:18

ERROR in ./web_src/less/standalone/swagger.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
TypeError: (0 , _schemaUtils.validate) is not a function
    at Object.lessLoader (/home/user/git/gitea/node_modules/less-loader/dist/index.js:26:29)
    at processResult (/home/user/git/gitea/node_modules/webpack/lib/NormalModule.js:583:19)
    at /home/user/git/gitea/node_modules/webpack/lib/NormalModule.js:676:5
    at /home/user/git/gitea/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /home/user/git/gitea/node_modules/loader-runner/lib/LoaderRunner.js:252:18

ERROR in ./web_src/less/themes/theme-arc-green.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
TypeError: (0 , _schemaUtils.validate) is not a function
    at Object.lessLoader (/home/user/git/gitea/node_modules/less-loader/dist/index.js:26:29)
    at processResult (/home/user/git/gitea/node_modules/webpack/lib/NormalModule.js:583:19)
    at /home/user/git/gitea/node_modules/webpack/lib/NormalModule.js:676:5
    at /home/user/git/gitea/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /home/user/git/gitea/node_modules/loader-runner/lib/LoaderRunner.js:252:18

3 ERRORS in child compilations
webpack 5.11.0 compiled with 13 errors in 28410 ms
make: *** [Makefile:665: public/js/index.js] Fehler 1
```

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
@6543 can't reproduce locally and google does not help on it either. Try a `rm -rf node_modules`?

**Comment by 6543** [comment]
.

**Pull request merged**
