### PR TITLE
Make AllowedUsers configurable in sshd_config

### PR DESCRIPTION
**Pull request by jpellegrini**
docker/root/usr/bin/entrypoint already allows for the specification
of USER, USER_UID, USER_GID. But since AllowedUsers is hardcoded in
sshd_config, one cannot log in as a user different ftom git.
This change substitutes ${USER} for git in the sshd_config template.

This would solve #7969

Signed-off by: Jeronimo Pellegrini

### CODE REVIEW

**Comment by sapk** [comment]
That should be already taken care by https://github.com/go-gitea/gitea/blob/dab38c375df5c4719d35f1be29278d254d68390f/docker/root/usr/bin/entrypoint#L3-L8

**Review by sapk — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by sapk** [comment]
Thanks for you contribution. Can you send a backport of this change? This is basicly the same PR but on the `release/v1.9` branch instead of `master`.

**Comment by jpellegrini** [comment]
> Thanks for you contribution. Can you send a backport of this change? This is basicly the same PR but on the `release/v1.9` branch instead of `master`.

Sure, but there is no sshd_config template in the 1.9 branch. and docker/root/etc/s6/openssh/setup does not even read a template... Itwould be necessary to make all changes so s6 would do templating on sshd_config. Is that what you mean?

**Comment by sapk** [comment]
Yes sorry you don't need to backport in this case.
I didn't check if 1.9 was still using the previous sed command and not overriden by the template.

**Pull request merged**
