### PR TITLE
Fix `DEFAULT_SHOW_FULL_NAME=false` has no effect in commit list and commit graph page

### LINKED ISSUE #20446: Commits Showing Author By Full Name Not Username
### Description

It seems that #6710 added supported to toggle showing full names, but commit messages still show the full name of the Gitea user. This is confirmed by changing the full name under account to anything else, which the commit author then takes on.

The commit graph has the same issue, although I do believe it (and other portions) are linked to the same thing.

The user heatmap and other areas such as pull requests behave as expected, respecting the `DEFAULT_SHOW_FULL_NAME` config setting when set to `false` and only showing the username.

Expected behaviour: The author section under commits shows the username of the user, and not their full name.

Having an option/toggle for this would be extremely helpful. To ensure consistent username display site-wide with regards to repos.

### Screenshots

Repo_Issue

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10

### Browser Version

Firefox 102

### PR DESCRIPTION
**Pull request by yp05327**
Fix #20446

This PR will fix the username in:
repo home page
image
repo commit list page
image
repo commit graph page
image
pr commit page
image

Will not fix:
wiki revisions page:
image
ps: the author name is `FullName` by default

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by delvh** [comment]
Wait… `DEFAULT_SHOW_FULL_NAME` is used as `ENABLE_SHOW_FULL_NAME`?
Sounds a bit weird to me.

**Comment by delvh** [comment]
Do we need to rename the config key?
Or how should we handle that?

**Comment by wxiaoguang** [comment]
> Do we need to rename the config key? Or how should we handle that?

The "user name" display needs a complete rewriting. IMO it could be used by 3 methods:

1. `UserName`
2. `GetDisplayNameFull()`:
    * If DEFAULT_SHOW_FULL_NAME == true:
        * `UserName` if `FullName` is empty; `UserName (FullName)` if `FullName` is not empty
    * If DEFAULT_SHOW_FULL_NAME == false:
        * `UserName`
3. `GetDisplayNameShort()`:
    * `UserName` if `FullName` is empty; `FullName` if `FullName` is not empty
    * Actually I think this case should be avoided for most cases, it only cause confusing.

**Comment by silverwind** [comment]
Yes, it does sound like this logic belongs in Go, not in the templates.

**Comment by yp05327** [comment]
Actually, we already have a function (same to `GetDisplayNameFull` mentioned above ) for `User`:
image

I'm confuseing which one to use, `commit.Author.Name/FullName` or `commit.User.Name/FullName`

**Review by techknowlogick — APPROVED** [review]
I agree with others that this is a suitable interim approach

**Pull request merged**
