### PR TITLE
Fix ldap admin privileges update bug

### LINKED ISSUE #27049: LDAP admin updata bug
### Description

When you have set administrator privileges for a user through LDAP settings, and after some time, you cancel the administrator privileges for that user in LDAP. You will find that the administrator privileges cannot be canceled.

The problem comes from the LDAP settings, if the Gitea instance does not specify a username query rule, for `user_model.IsUserExist(db.DefaultContext, 0, sr.Username)`, `sr.Username` is an empty string `""`,  `isExist` always be `false`, so can't update the user.

image

https://github.com/go-gitea/gitea/blob/a55ff0dd99439eb96151e64be38e0f14f6e723b7/services/auth/source/ldap/source_authenticate.go#L27-L36

### Gitea Version

a55ff0dd99439eb96151e64be38e0f14f6e723b7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

source code

### Database

None

### PR DESCRIPTION
**Pull request by CaiCandong**
When the user does not set a username lookup condition, LDAP will get an empty string `""` for the user, hence the following code
```
if isExist, err := user_model.IsUserExist(db.DefaultContext, 0, sr.Username)
```
The user presence determination will always be nonexistent, so updates to user information will never be performed.

Fix #27049

### CODE REVIEW

**Comment by lunny** [comment]
Could you add some tests?

**Review by silverwind — APPROVED** [review]

**Comment by CaiCandong** [comment]
@lng2020, I don't have time to write test cases. Could you help me implement it?

**Comment by CaiCandong** [comment]
> Could you add some tests?

Writing tests for this function is a bit difficult.

**Comment by 6543** [comment]
should we backport it?

**Review by 6543 — APPROVED** [review]

**Pull request merged**
