### PR TITLE
[sourcery] Choose Emojis, as a browser-rendered block

### PR DESCRIPTION
**Pull request by c4lliope**
Original: please see https://gitea.com/sourcery/sourcery/pulls/1
Please also see #14581 as background.

My code here replaces a golang `.tmpl` files using a React component, or a "block".
Necessary information for each component is placed in a JSON blob inside the `.tmpl` file,
and is read by `index.js` to build the block.

This is a drop-in replacement for the Emoji `add_reaction` template,
and paves our road for making similar changes in:

* [x] `templates/repo/issue/view_content/add_reaction.tmpl`
* [ ] `templates/repo/issue/view_content/reactions.tmpl`
* [x] `templates/repo/issue/view_content/context_menu.tmpl`
* [ ] `templates/repo/issue/view_content/attachments.tmpl`

I am opening this issue in case you would like to keep these changes inside mainline Gitea.
Perhaps, you can also deny my changes and I shall keep going inside https://gitea.com/sourcery/sourcery.
Small merges are easier, so if you like my goal maybe we can keep our codebases aligned.
I hope my ideas make your grade.

Cheers and 干杯, @lunny and squad. 🚢

### CODE REVIEW

**Comment by jolheiser** [comment]
I don't know if I'm comfortable adding React to our stack. We already use a weird mix of vanilla, jQuery, and some Vue.

**Comment by 6543** [comment]
I'm also not comfortable with this.  ... I think there is an Issue with this discussion if we should have a one-page app or not and the consensus was. That dont do that. Instead enhance the api so others can make it as an own project ... we would then present it as alternative fronted to the docs ...

**Comment by c4lliope** [comment]
https://github.com/c4lliope/gitea/commit/7d8a225557d4e4b86ccdcbf6b78244e41506a458
handles `templates/repo/issue/view_content/context_menu.tmpl`

**Comment by techknowlogick** [comment]
Putting on project owner hat, and first want to thank you for your PR. However, we won't be merging this, as @jolheiser has said, we have already many frameworks in our stack, and elsewhere we have previously stated we won't be moving towards including react in the project for those reasons as well as as a project we need to maintain these additions of which as a project we are more familiar with Vue. The great thing about SPAs is that you can build one without changing the project at all. In fact, there is one public project that has already build react components for interacting with Gitea (on mobile now, so I can't find link).

**Comment by c4lliope** [comment]
@jolheiser and @6543, I'm glad you responded.

I am hoping by changing `.tmpl` files to React-based blocks, our code can:

* drop [reliance on JQuery](https://github.com/go-gitea/gitea/pull/14612/files#diff-a15e36f2f9c13339f7fdd38bc2887db2ff2945cb8434464318ab9105fcc846bdL256) by using [core browser apis](https://github.com/go-gitea/gitea/pull/14612/files#diff-ee8ef237ff458cb9ca707fdc2286b4ca64771cd76f43cb22d5db0f553a2cd6c6R14-R18).
* Drop reliance on Vue, choosing React because it requires [less preprocessing](https://github.com/go-gitea/gitea/pull/14612/files#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fL146-R146).
* Make use of [CSS-in-JS](https://styled-components.com/) rendering libraries, enabling more unique designs.
* [Make clear](https://github.com/c4lliope/gitea/commit/7d8a225557d4e4b86ccdcbf6b78244e41506a458#diff-d998e758fb6c1244cd2d75550a1ecbd64065e0e8bf155d89e95bd7aec72ad55fR14-R35) missing API resources which are needed by single-page apps and API consumers.

As I described in #14581, I imagine these goals are enough reason to make a branch of the codebase. I'm only curious how aligned you'd like to keep them.

**Comment by 6543** [comment]
I'm aware that the api is not *jet* feature complete ... I like to address this in the [next release](https://github.com/go-gitea/gitea/issues/14477) ... 

For API's the goal is to be backwards compatible as long as it doesn't affect security ... so If you program an interface for gitea's api you can assume it will stay as is for the upcoming releases - if not consider it as a bug.

Proposals for needed API's are welcome!

**Pull request closed without merging**
