### PR TITLE
fix: Add secret to all webhook's payload where it has been missing

### PR DESCRIPTION
**Pull request by HoffmannP**
* Updated dependency manager via `dep ensure -update code.gitea.io/sdk`
* Gopkg.toml was not changed as sdk version is set to "master"
* affects webhooks for: Delete, Fork, IssueComment, Release
* also contains changes from go-gitea/go-sdk#125 and hence a swagger update

Signed-off-by: Berengar W. Lehr <Berengar.Lehr@kompetenztest.de>
Resolves: #4732, #5173

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by HoffmannP** [comment]
@lunny this is the backport/1.6 for #5199. It contains other, unrelated changes gitea/go-sdk#125 by another party that were not merged until then.

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@HoffmannP just found I made a wrong label. backport/1.6 means should be backport to release 1.6

**Comment by lafriks** [comment]
@HoffmannP this label should be added to PRs to master branch that needs to be backported to release/1.x branches

**Comment by HoffmannP** [comment]
@lafriks thank you for the clear up. I'm felling like I'm getting there

**Comment by AuspeXeu** [comment]
I just tested the latest version `1.6.0-rc2` and it seems like this issue is still not resolved. Now, if I trigger a test delivery for a custom event of the type release, no request is queued whatsoever. Before (`1.5.3`) it simply didn't contain the secret.

**Comment by HoffmannP** [comment]
@AuspeXeu Could you open an issue? Do you get any error log?

**Comment by AuspeXeu** [comment]
@HoffmannP I added it to my initial issue #5173 I do not get any error logged unfortunately.

**Pull request merged**
