### PR TITLE
Bypass vitest bug

### PR DESCRIPTION
**Pull request by wxiaoguang**

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by kerwin612 — APPROVED** [review]

**Comment by silverwind** [comment]
https://github.com/capricorn86/happy-dom/issues/1620 might be related.

**Comment by wxiaoguang** [comment]
Yup, I also have thought about it and I also felt that it might be highly related to DOM.

But I couldn't detect happy-dom by checking `window.happyDOM`, the only detectable clue is `window.vitest`, so the comments were left as "vitest". The comment (or the bug itself) could be fixed later if there is any upstream progress

**Comment by silverwind** [comment]
I think the canonical way to detect vitest environment is either `process.env.NODE_ENV === 'test'` or `VITEST_POOL_ID in process.env`. Ref: https://vitest.dev/guide/migration#envs

**Comment by wxiaoguang** [comment]
Then it comes the question: how could it access `process.env` in `queryElemChildren` clearly?

**Comment by silverwind** [comment]
Webpack will compile out `process.env.XXX === 'xxx'` expressions, at least when this plugin is enabled:

https://webpack.js.org/plugins/environment-plugin/

**Comment by wxiaoguang** [comment]
> Webpack will compile out `process.env.XXX === 'xxx'` expressions, at least when this plugin is enabled:
> 
> https://webpack.js.org/plugins/environment-plugin/

I know this, but I mean ` how could it access process.env in queryElemChildren clearly? ` ?  `if (typeof process !== 'undefined')`?

**Comment by wxiaoguang** [comment]
Maybe we need this  Make frontend unit test code could know it is in testing #32656  , to distinguish from backend's "testing"

**Pull request merged**
