### PR TITLE
Switch to golang vendoring

### PR DESCRIPTION
**Pull request by tboerger**
~~I have prepared a switch to the golang vendoring introduced by golang 1.5. This pull requests obsoletes #208. The only small downside is that it requires golang >= 1.5 now for building.~~

As the vendoring of golang 1.5 currently doesn't work for us (some dependencies from macaron-contrib are using internal packages which gets blocked by go) I have rebuilt this pull request with a godeps setup that is working quite goo now. This still obsoletes #208.

To keep the barrier small for other people I will do some followup tasks like introducing automatically built binaries for various platforms and for master as well as the develop branch created and published by Drone.

### CODE REVIEW

**Comment by tboerger** [comment]
Should I add golang.org/x/tools/cmd/goimports and github.com/remyoudompheng/go-misc/deadcode to the mak.go as well?

**Comment by tboerger** [comment]
```
# go get github.com/remyoudompheng/go-misc/deadcode
# go list ./... | sed -e 's/github.com\/go-gitea\/gitea\///' | sed -e '/github.com\/go-gitea\/gitea/d' | xargs deadcode
deadcode: modules/base/tool.go:340:1: bytesSizeTable is unused
deadcode: modules/log/smtp.go:16:1: subjectPhrase is unused
deadcode: routers/repo/pull.go:162:1: hasPullRequested is unused
```

**Comment by tboerger** [comment]
```
# go get golang.org/x/tools/cmd/goimports
# goimports -l .
cmd/generate.go
modules/bindata/bindata.go
```

**Comment by tboerger** [comment]
As discussed on Gitter let's close this and see if we can really switch to vendoring later on.

**Comment by lunny** [comment]
OK.

**Pull request closed without merging**
