### PR TITLE
Fix releases to be counted from database not tags

### LINKED ISSUE #2154: Releases didn't display
see https://try.gitea.io/lunny/core/releases for examples. This repo is migrated from https://github.com/go-xorm/core. The counter is 8, but nothing listed.

### PR DESCRIPTION
**Pull request by lafriks**
First step to fix #2154

### CODE REVIEW

**Comment by sapk** [comment]
LGTM

**Review by sapk — APPROVED** [review]

**Comment by lunny** [comment]
CI failed.

**Comment by sapk** [comment]
@lunny I am not sure that this is related to this PR maybe a bug when copying the integration env.
@lafriks can you please restart the build via commit --amend or rebase ?

**Comment by lafriks** [comment]
@lunny @sapk done

**Comment by lunny** [comment]
LGTM

**Pull request merged**
