### PR TITLE
[Patch] Fix closed PR also triggers Webhooks and actions

### LINKED ISSUE #23707: Closed PRs trigger synchronize webhooks when new PR with same branch name is created
### Description

PRs that were previously closed unmerged will trigger webhook of `synchronize` type when new PR is opened with same branch name. This is directly caused by https://github.com/go-gitea/gitea/pull/23189

If a user has CI integration configured, this will cause additional jobs to be spawned for each closed (but unmerged) PR that matches branch name of newly created PRs. In extreme cases this can be in hundreds. In such case, closed PRs will also inherit all status checks from new PRs, overwriting previous status checks.

Several tools such as RenovateBot reuse same branch name when creating PRs and it is not uncommon to sometimes close (aka ignore update) PRs created by Renovate.

---

For now, proposed fix would be to skip `synchronize` event on closed PRs, however this is very much a temporary band-aid and there are more code paths that might get confused by behavior change introduced by https://github.com/go-gitea/gitea/pull/23189.

I am not entirely sure how one could attempt to fix it. The only one possible solution I can think of would still result in PR that can not be reopened in case when source branch was force-pushed to.

Additionally, I do not believe closed PRs should be reopenable in all conditions, especially when source branch head has changed while PR was in closed state as that usually indicates that while branch name is identical, its content is very likely not applicable to closed PR and name collision is just coincidental.

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

`gitea/gitea:1.19-rootless`

### Database

None

### PR DESCRIPTION
**Pull request by sillyguodong**
Fix #23707 
Cause by #23189
This PR is a quick fix that, when pushing commits to closed PR, webhook and actions also be triggered.

### CODE REVIEW

**Comment by silverwind** [comment]
Was there an open issue for this?

**Comment by jolheiser** [comment]
> Was there an open issue for this? I think preferences may vary on this one and we may need an option to control this behaviour.

https://github.com/go-gitea/gitea/issues/23707

**Comment by silverwind** [comment]
Do we know GitHub behaviour? Do they run CI on closed PRs?

**Comment by sillyguodong** [comment]
> Do we know GitHub behaviour? Do they run CI on closed PRs?

On GH,  only open PR will trigger action

**Review by wolfogre — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
