### PR TITLE
Fix some org style problems

### PR DESCRIPTION
**Pull request by KN4CK3R**
(Important lines in `new.tpml` are 4 and 5. Other lines are unchanged except indentation.)

1. 2px offset
2. fixed width of menu

old:
grafik

new:
grafik

3. wrong width

old:
grafik

new:
grafik

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
I don't encounter your problem. Have you zoom out the interface?

**Comment by KN4CK3R** [comment]
Which one?

**Comment by lunny** [comment]
> Which one?

Both.

**Comment by wxiaoguang** [comment]
> I didn't encounter your problem. Have you zoom out the interface?

@lunny  The bug can be triggered when the window width is small. For example, on my side, I can also trigger the bug:

<details>

image

</details>

**Comment by KN4CK3R** [comment]
The two pixel offset is always there. The fixed width looks bad on wide screens (large gap) or if you shrink the screen (overlapping with content).

**Pull request merged**
