### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Comment by silverwind** [comment]
That's not a typo and the text is just a copy of the original MIT license:

https://opensource.org/licenses/MIT

**Comment by silverwind** [comment]
That's not a typo and the text is just a copy of the original MIT license:

https://opensource.org/licenses/MIT

**Comment by rishitsaiya** [comment]
Ok, but I think that change would reflect good! We can customize license, isn't it?

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Thank you for this PR. As @silverwind mentioned, our License is an exact copy of the OSI approved version. We also have a legal requirement to maintain the exact text of the file.

**Comment by techknowlogick** [comment]
Per my message above I am going to close this issue.

**Pull request closed without merging**
