### PR TITLE
Fix fmt errors

### PR DESCRIPTION
**Pull request by ethantkoenig**
With the recent changes to `.drone.yml`, we should double check that `make fmt-check` (or something that has it as a dependency) always runs in CI.

### CODE REVIEW

**Comment by lunny** [comment]
depends on #2547 ?

**Comment by ethantkoenig** [comment]
@lunny yes

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
