### PR TITLE
Fix handling of logout event

### PR DESCRIPTION
**Pull request by zeripath**
It appears that there is a slight bug in the handling of the data of logout event -
the javascript should be testing the data field of the data field for the logout
instruction.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
Don't you need to `JSON.parse(event.data)` like it's done in `receiveUpdateCount`? Also that method uses uppercase properties so maybe it's `.Data` actually?

**Comment by zeripath** [comment]
> Don't you need to `JSON.parse(event.data)` like it's done in `receiveUpdateCount`?

Don't appear to need it. Have you found that you do need it?

> Also that method uses uppercase property access like `.Count` so maybe it's `.Data` actually?

What method?

**Comment by silverwind** [comment]
Just a few lines above `event.data` is passed into `receiveUpdateCount`:

https://github.com/go-gitea/gitea/pull/15323/files#L65

which then does `JSON.parse` on `event.data.data` (argument to the function is deceivingly mislabeled, it should be `data`):

https://github.com/go-gitea/gitea/pull/15323/files#R23

And finally it accesses title-cased `.Count` on the parsed object:

https://github.com/go-gitea/gitea/pull/15323/files#L32

**Comment by zeripath** [comment]
the data from a logout event is simply text. So this is correct as it stands.

**Comment by silverwind** [comment]
The only way `receiveUpdateCount` can work is that in the event `notification-count`, data is a JSON object while for `logout` it is just the `here` string (and invalid JSON). I think for clarify we should just always send JSON-parseable data.

**Comment by zeripath** [comment]
No you've got it wrong. Why don't you test it.

**Comment by silverwind** [comment]
That's something I've meaning to ask. How does one generate fake eventsource events on the server? Is there some convenient way to do so?

**Comment by zeripath** [comment]
there's no built in way of doing this. All of the events are created in `routers/events.go`:

https://github.com/go-gitea/gitea/blob/426ebbfc3b6b50fc7e1cb1e645716635b7cad947/routers/events/events.go#L35-L40

is the simplest example.

In this case the important event is:

https://github.com/go-gitea/gitea/blob/426ebbfc3b6b50fc7e1cb1e645716635b7cad947/routers/events/events.go#L130-L134


Which will simply be emitted as:

```
event: logout
data: here

```

The eventsource will then send a js object event: 
```js
{
  ...
  "data": {
    "type": "logout",
    "data": "here",
  }
}
```

which gets pushed to the workers as an "event":
```js
{
   "type": "logout",
   "data": {
    "type": "logout",
    "data": "here",
   },
}
```

The double wrapping of the data is an unfortunate consequence of the way events are passed around js - this could be stopped by  changing:

https://github.com/go-gitea/gitea/blob/426ebbfc3b6b50fc7e1cb1e645716635b7cad947/web_src/js/features/eventsource.sharedworker.js#L50-L54

L53 to `event.data.data` instead of `event.data` but then you lose the ID and Retry time should we wish to use those.

---

In the case of notification events the data is []byte of json data in the Event struct.

**Comment by zeripath** [comment]
I need to move the stopwatches query out of the event stream and instead consider a similar db query to how we do the notification stream but I've not had the inclination do that yet.

**Comment by silverwind** [comment]
I think I understand now. My assumption was that the inner `data` would always be a JSON object but that's just not the case (would still prefer if we would not mix types like that for different events).

```go
Event{
  Name: "notification-count",
  Data: uidCount,
}

Event{ 
  Name: "logout", 
  Data: "here", 
}

# uidCount 
type UserIDCount struct {
	UserID int64
	Count  int64
}
```

I did not find where the JSON serlialzation happens but it must be somewhere.

Refactoring this `data.data` stuff would certainly be welcome for another PR.

**Review by silverwind — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
