### PR TITLE
Disable federation by default

### PR DESCRIPTION
**Pull request by Gusted**
- A Gitea instance should choose whetever they want to federate(as once it has more features also brings extra costs/moderation/unexpected behavior) with other AP/ForgeFed software.

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Given that it doesn't even really exist in 1.17 it isn't even breaking :)

**Comment by Gusted** [comment]
> Given that it doesn't even really exist in 1.17 it isn't even breaking :)

Ah thanks for reminding, this does need backporting.

**Comment by delvh** [comment]
That wasn't even what I intended to say, but yeah, you're right, it can also be backported...

**Review by jolheiser — APPROVED** [review]

**Comment by Gusted** [comment]
Backport: #20046

**Comment by lunny** [comment]
LGTM

**Pull request merged**
