### PR TITLE
Apply to became a maintainer

### PR DESCRIPTION
**Pull request by kerwin612**

### CODE REVIEW

**Review by denyskon — APPROVED** [review]
Welcome!

**Comment by CaiCandong** [comment]
https://github.com/go-gitea/gitea/pulls?q=is%3Apr+author%3Akerwin612+is%3Amerged

**Review by CaiCandong — APPROVED** [review]

**Comment by 6543** [comment]
👋 ;)

**Comment by denyskon** [comment]
@kerwin612 Do you have Discord and an account on gitea.com? so that you can be added to maintainers there

**Comment by delvh** [comment]
@go-gitea/technical-oversight-committee can someone add @kerwin612 to the maintainers team?

**Comment by kerwin612** [comment]
> @kerwin612 Do you have Discord and an account on gitea.com? so that you can be added to maintainers there  

I have all of them. The account ID is unified as: **kerwin612**

**Pull request merged**
