### PR TITLE
Replace more icons with SVG, repo search tweaks

### PR DESCRIPTION
**Pull request by silverwind**
- Replace remaining icons on admin page with SVG
- Fix vertical menu background on arc-green
- Minor improvements to frontpage repo search
- Improve webhooks list
- More icon replacements here and there
- Dropdown color fixes for arc-green

Screen Shot 2020-12-05 at 16 11 03
Screen Shot 2020-12-05 at 16 24 17
image
Screen Shot 2020-12-05 at 16 48 14
Screen Shot 2020-12-05 at 15 57 14
Screen Shot 2020-12-05 at 15 23 27
Screen Shot 2020-12-05 at 14 53 23
Screen Shot 2020-12-05 at 15 06 49

### CODE REVIEW

**Comment by 6543** [comment]
ping

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@bot

**Comment by 6543** [comment]
LGTM

**Comment by silverwind** [comment]
Rebased and a comment added.

**Comment by silverwind** [comment]
Description updated to mention everything this includes like repo search and dropdown fixes.

**Comment by silverwind** [comment]
Maybe I'll swap the icons back to unchecked/checked checkboxes which I like more then check/cross personally. Would be individual SVG files instead of from the icon font.

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
> Maybe I'll swap the icons back to unchecked/checked checkboxes which I like more then check/cross personally. Would be individual SVG files instead of from the icon font.

I have no preference, but I'll block this PR for you in case you do want to make this change.

**Comment by silverwind** [comment]
I'll decide soon. It also depends whether I can find a suitable set of icons. I kind of like this one from the Feather set:

image

https://icomoon.io/app/#/select

**Comment by silverwind** [comment]
I'll unblock this, it's ready to go. I'll keep cross/check icons on the notion that a cross is a better icon for "no" then a empty box which could be misinterpreted when seen alone.

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
