### PR TITLE
Display image size for multiarch container images

### LINKED ISSUE #23771: Reported container image size on UI seems incorrect
### Description

A report from Discord channel, thanks to Fascinated.

> Container registry works perfectly fine but the size of the images always shows as 856 B
> Same size on 2 different packages

image

### Gitea Version

1.19.0

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #23771

Changes the display of different architectures for multiarch images to show the image size:
grafik

### CODE REVIEW

**Comment by KN4CK3R** [comment]
> Could we display the summmary size of all images in the right siderbar?

I see no benefit doing that because that value is meaningless. The docker client downloads just the matching architecture and not every possible image.

**Comment by lunny** [comment]
But it's confusing the size is 770B on the right sidebar on your image. What's that size?

**Comment by KN4CK3R** [comment]
The image is a manifest list (a json file) which just references other images (which this PR lists with their size now). So the package you are looking at is small, 770B.

**Comment by lunny** [comment]
> The image is a manifest list (a json file) which just references other images (which this PR lists with their size now). So the package you are looking at is small, 770B.

Yes, I know. That's why I think it's confusing. I think users don't care about the manifest's size because they know it's small. They should care about the total size of this package.

**Comment by KN4CK3R** [comment]
But there is no "total" size because a client will never download all of it (if you don't enforce it). How about not displaying the size if it's a manifest list?

**Comment by Zettat123** [comment]
I think it's not necessary to show size for multi-arch images, just like Docker Hub.

**Comment by lunny** [comment]
> I think it's not necessary to show the size (the size of manifest) for multi-arch images, just like Docker Hub.

Hide the manifest size is also OK for me to make it less confusing.

**Review by lunny — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]

**Pull request merged**
