### PR TITLE
Fix fork button

### LINKED ISSUE #6222: Cannot go to my fork when on main org project
- Gitea version (or commit ref): 8e266c3
- Operating system: Ubuntu 18.04 (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Not being able to click on the forks of a project in order to get to my own fork of the organizational project I have forked. Again, I am set as an owner of the organization. I think this may be related to #6195. The desired behavior is that I would see a list of the forks and be able to click on my fork to navigate to it.

## Screenshots
image

I have also tested this with a developer (non-owner) of the org and the result is the same, he can't get to the list of forks, whereas in the past he could. Area now appears disabled.

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #6222 

When disabling only the first part, I didn't like how semantic displayed it.
fork_basic

So instead I moved the `basic` class into an if-else.  
It appears `basic` when a user **can** fork (no change from existing style)  
It appears normal (but `disabled`) if they **cannot** fork. (image below)
fork_fix

There was also the case of a non-signed in user, which is why this is a separate if-else within the element to avoid any doubled up classes in favor of another logic flow.

### CODE REVIEW

**Review by hexfs — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Still looks kind of weird, I'd fix the disabled CSS to use something like `opacity: .5` on the whole button. Plus points for also adding `cursor: not-allowed`.

**Comment by silverwind** [comment]
Also, I think some manual styling to make `border-right` change on hover would be nice.

**Comment by jolheiser** [comment]
After messing with CSS for a bit, this is what I came up with. Note that the right-button to get to forks is still available and the cursor is a pointer like normal.
It adds the `cursor: not-allowed;` change as well to the left-button. Since I needed to manually counteract any prior hover event styling, there's a chance I missed something that would show up differently in another browser.  
Please let me know what further changes, if any, are needed. 

fork-disabled

**Comment by silverwind** [comment]
I'd change the disabled class to something a bit more more generic like `.disabled-repo-button` so it could be used on the other buttons too. Or even go full out on overriding the `.disabled` class. `pointer-events: none` might be required to actually make the button unclickable.

Some lightly tested suggestions (the margin change on the label makes border-right on the left button show). I'm sure more improvements are possible (the color/box-shadow change seems unneccessary):

```` css
.repo-buttons .disabled-repo-button .label {
  opacity: .5;
}

.repo-buttons .disabled-repo-button a.button {
  opacity: .5;
  cursor: not-allowed;
  pointer-events: none;
}

.repo-buttons .disabled-repo-button a.button:hover {
  background: none !important;
  color: rgba(0,0,0,.6) !important;
  box-shadow: 0 0 0 1px rgba(34,36,38,.15) inset !important;
}

.repo-buttons .button > .label {
  border-left: none !important;
  margin: 0 !important;
}
````

**Comment by jolheiser** [comment]
I left `pointer-events` on because otherwise you lose the cursor and tooltip.  
Clicking on it didn't seem to do anything in Chromium (which is intended behavior), however at the moment I cannot test on other browsers.

**Comment by silverwind** [comment]
Almost there, but we need to modify the last style to make the inner border show:

````css
.repo-buttons .ui.labeled.button > .label {
  margin: 0 !important;
}
````

Reason being the `!important` in Semantic here:

screenshot 2019-03-03 at 17 11 04

**Comment by jolheiser** [comment]
Okay, updated. Thanks for the input, @silverwind 
I can make UI changes, but I am definitely not a styling expert. :sweat_smile:

**Review by silverwind — APPROVED** [review]

**Comment by hexfs** [comment]
Conflict

**Comment by jolheiser** [comment]
> Conflict

Resolved

**Comment by hexfs** [comment]
@techknowlogick GTM

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
