### PR TITLE
Add gitea-dark theme

### PR DESCRIPTION
**Pull request by silverwind**
Second take on a general dark theme that is close to an inversion of the gitea theme. This is not quite ready yet but good enough for a preview.

The way it work is it hooks into webpack's output to grab index.css, remap all colors within to dark colors and prepend the result to the theme file. One benefit of this method is is that maintainers generally don't need to touch the theme as long a they are using colors already present on the page.

The hook may fail on watch mode builds after the first, I will look into possible solutions. Also, lazy-loaded chunks like dropzone are not handled yet.

image

### CODE REVIEW

**Comment by lafriks** [comment]
Imho we should move out colors to less variables like ($text-color, $link-color, $button-background-color etc) that could be tuned than for different themese

**Comment by bagasme** [comment]
@silverwind the message text in `<div class="ui positive message"` should be made white for readability, e.g.:
current
white text

**Comment by lunny** [comment]
I like the dark theme but I think we should keep less themes to maintain easier. Currently we have two internal themes, if we merge this, we will have three. Every PR which will add a new feature(i.e. board) have to change the three themes.

Maybe we should add a theme market feature and the site `https://themes.gitea.io` to allow user upload and download the themes but not merge them into the main thread branches.

**Comment by silverwind** [comment]
> I like the dark theme but I think we should keep less themes to maintain easier. Currently we have two internal themes, if we merge this, we will have three.

I'm not sure yet what to do about arc-green but I imagine we could eventually phase it out or move it to the automated approach with the color remapping. Maintaining these theme will be less work than it currently is where you need to copy every color-affecting selector to arc-green because as long as no new colors are introduced, the mechanism will automatically generate the selectors for you.

> Maybe we should add a theme market feature

A noble idea but I think it's currently unfeasible because manually created themes would need constant maintenance to be kept up to date with changes in the base theme. This might become feasible once we move all colors to CSS varibles, but currently it isn't.

**Comment by lafriks** [comment]
@silverwind yes but this way we can build multiple themes by just specifying different variable colors. Also we can specify them to css variables to get them changeable at runtime (auto dark theme)

**Comment by silverwind** [comment]
CSS vars can do anything that Less vars can do, I see no benefit in using Less vars. We can define a set of base vars in the default theme, to be overridden in each theme individually. There is one major problem which is Fomantic hardcodes all their colors so the approach can not properly work unless we fork Fomantic's CSS or generate the base-theme using the ThemeBuilder mechanism too (I think that is the way to go).

**Comment by silverwind** [comment]
@bagasme fixed that:

image

**Comment by silverwind** [comment]
Can't see any more obvious issues, so ready for review.

**Comment by silverwind** [comment]
Maybe should label this as a feature.

I'll do another pass on this shortly.

**Comment by silverwind** [comment]
Theme is now completely running on CSS vars.

**Comment by silverwind** [comment]
Will do a few more tweaks later. If anyone has feedback on the CSS variable approach, it'd be welcome. The variable naming is certainly not ideal and I'm contemplating using shorter names like `black-alpha-20`. Now I think best practice is to have semantic names only but I have a hard time semantically naming 15+ shades of gray.

I imagine we can switch the base theme to the same approach using `remap-css` later. I recently introduced a new [keep](https://github.com/silverwind/remap-css#remapcsssources-mappings-opts) option which would allow to completely replace `index.css` with the remapped variant which means we can introduce CSS vars even for fomantic's styles.

**Comment by silverwind** [comment]
Will probably follow up on this later once we have converted everything to CSS vars.

**Pull request closed without merging**
