### PR TITLE
Add changelog for 1.20.1

### PR DESCRIPTION
**Pull request by delvh**

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Should it wait for #26007 (revert the fatal log for lfs path)

I am neutral for it, but actually:

* If it needs to wait, then wait for it
* If it doesn't need to wait, then `#26007` doesn't seem useful after this release, because there might be a long time to next release.

**Comment by wxiaoguang** [comment]
And this one:  Fix the route for pull-request's authors #26016

**Review by wxiaoguang — APPROVED** [review]

**Comment by delvh** [comment]
As it seems, #26007 will likely not be merged.
As such, all changes for 1.20.1 are present.

**Comment by wxiaoguang** [comment]
> As it seems, #26007 will likely not be merged.

TBH, I don't understand, and I don't see any objection for it.

(merging or not either is fine to me, I just don't understand how Gitea maintainers come to an agreement)

**Comment by delvh** [comment]
Well, my reasoning is the following:
I've said that I don't care about the outcome, as long as we decide **quickly**. Almost nothing has happened the last two days.
You yourself said that we should shutdown **if the logic changes drastically** to prevent unintended things.
The change from `[server].LFS_CONTENT_PATH` to `[lfs].PATH` is one such thing.
I've interpreted the maintainer chat as that there's general consensus to not remove the fatal warning.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> I've interpreted the maintainer chat as that there's general consensus to not remove the fatal warning.

I guess there are some misunderstanding on this problem and that PR. My understanding is that the fatal should be kept if the option is removed, but if the option is still supportted, there is no disagreement for reverting. 

I won't waste time on it either.....

**Comment by wxiaoguang** [comment]
> Almost nothing has happened the last two days.

The owner/TOC team just seem disappearing for such big/urgent decision

**Pull request merged**
