### PR TITLE
Simplify settings pages with item list

### PR DESCRIPTION
**Pull request by sapk**
Gitea SSH key seeting page display a column with a point indicating if the key is used recently.
It's more simple to display recent use of key like github and color the key icon and date of recent use.

**Before :** 
before-deploy-keys
before-apps
before-keys
before-email

**After :** 
after-deploy-keys
after-apps
after-keys
after-email

Still need to be apply in repository key list.

### CODE REVIEW

**Comment by sapk** [comment]
I have gone a little further in little cleaning. In some case there we're item with grid with only one column and other with a "useless" column (the point) for indicating activity when it could be display in icon.

**Before :** 
before-deploy-keys
before-apps
before-keys
before-email

**After :** 
after-deploy-keys
after-apps
after-email

Note : I don't know why lessc add !important and simplify color #bbb it also does it on master branch ...

**Comment by strk** [comment]
Why not keeping the `octicon-key` icon in deploy-keys as in your first screenshot ?

About `!important` CSS I'm afraid I removed that with a9de85d31d8ba3ce8801d03e66866e527f5f39d7 by using `lessc 1.6.3 (LESS Compiler) [JavaScript]` (lessc --version). Similar to the `gofmt` issue, this may be one of those cases in which different tooling version result in different behavior, which would require us to restrict the allowed version to run generative commands (see #1366)

**Comment by strk** [comment]
Please also check if we need to update the templates version (I'm pretty sure Gogs had the concept of a "template version" to make sure templates and code reading them would be consistent, not sure if that concept is still working in Gitea)

**Comment by sapk** [comment]
@strk I have use a icon from semantic because it need the class .icon to be well display in .item but the class .icon override .octicon-* classes so I will need add some "hack" to fix it. If we want to keep octicon icon.

**Comment by sapk** [comment]
Looking at it should be only add 
.ui.list > .item > i.octicon (or mega-octicon){
    display: table-cell;
    margin: 0;
    padding-top: .07142857em;
    padding-right: .28571429em;
    vertical-align: top;
    -webkit-transition: color .1s ease;
    transition: color .1s ease;
}
based from .ui.list > .item > i.icon

**Comment by sapk** [comment]
I replace key icon with original octicon key 
image

**Comment by strk** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by Morlinest** [comment]
@sapk Why you delete ".key" class from less file? I am working (testing) on patch to fix multiple broken pages after your commit and this one missing word is problem. You changed styling in whole "settings" scope. Can i revert this little change?

**Comment by sapk** [comment]
This PR simplify the html and remove some specific css "hack" with a more generic and global css for all items lists.

**Comment by sapk** [comment]
In fact the .key is not completely removed but only the .key.meta specific code is kept for color and better spacing between line.

**Comment by sapk** [comment]
Looking at your issue, I will have a look if it doesn't have impacted others pages

**Comment by Morlinest** [comment]
@sapk It has impact also on dropdown options (repo ->collaborators -> user rights). If i revert ".key" in less file it looks OK and your change should still work fine (tested booth shh key settings).

**Comment by sapk** [comment]
Make a PR because I don't see exactly what you mean.
For dropdown impact just restrict parent with > is enough without further impact.

I will force me to take time to propose a quick solution or look at your PR soon. 
I think you catch that more part of template could be simplify and follow more semantic ui design overall (so +1 for the good catch). That could be done in a other PR after a simple fix.

**Pull request merged**
