### PR TITLE
Migration failure during reaction migration from gitea

### LINKED ISSUE #13262: Migration with pull requests from other gitea instance fails
- Gitea version (or commit ref):
1.14.0+dev-18-gd453533be
- Git version:
2.26.2
- Operating system:
docker Alpine Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:
2020/10/22 13:25:46 ...ules/task/migrate.go:64:func1() [E] DeleteRepository: repository does not exist [id: 208, uid: 75, owner_name: , name: ]
2020/10/22 13:25:46 modules/task/task.go:51:handle() [E] Run task failed: error while loading reactions: 403 Forbidden

## Description
Migration without pull requests works fine for the same repo.
...

### PR DESCRIPTION
**Pull request by zeripath**
There are two problems in #13262 which is a situation whereby a migration fails due to reactions migration failing.

1. A failure during migrating reactions should not cause failure of migration - yes they're nice but really?!
2. The underlying reaction failure is due to the API checking the wrong permission for pull requests.
3. And the same error was present on the API for comment reactions...

Fix #13262

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
I've made this backport to v1.12 - only for the second commit in this PR - the reactions API should check the correct permission.

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by techknowlogick** [comment]
🚀

**Comment by zeripath** [comment]
Damn this is missing the last commit!

There's another place in the same file that has the wrong check

**Comment by zeripath** [comment]
https://github.com/zeripath/gitea/blob/6cd544638a36f010b1ae32f768ecf37b74aa8f7f/routers/api/v1/repo/issue_reaction.go#L60

Is also the wrong permission check. It appears that the last commit in the branch didn't get pushed up - not sure why!

**Comment by 6543** [comment]
v1.12 backport is #13346 @techknowlogick why did you remove the label?

**Pull request merged**
