### PR TITLE
Fix for #320

### PR DESCRIPTION
**Pull request by Bwko**
Suppress the error when we're removing a file that may not exist

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by andreynering** [comment]
Merged. Remember that in some situations makes sense to print to log or create a notice (there's a notice table on DB). Where the file often doesn't exist it is OK to ignore.

**Comment by tboerger** [comment]
To gather more errors and to make errcheck happy we added that, but in this case it fails unintentionally

**Comment by bkcsoft** [comment]
We should probably use `log.Infof` instead here...

**Comment by Bwko** [comment]
I think suppressing these 2 errors is the best solution. Since 90% of the time os.remove will fail and we don't want to flood the log with `x does not exist` errors.

**Comment by bkcsoft** [comment]
Aah right, nvm then. I didn't read the comments above the commands 😛

**Pull request merged**
