### PR TITLE
[Branch View] code format

### PR DESCRIPTION
**Pull request by 6543**
part of PR https://github.com/go-gitea/gitea/pull/7520
and issue https://github.com/go-gitea/gitea/issues/7454

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
This is change does not really warrant classing as a PR.

Surely this could be folded into a different PR?

**Comment by 6543** [comment]
i can add it to https://github.com/go-gitea/gitea/pull/7602 or the once wich will folow?

**Comment by zeripath** [comment]
Oh I agree about having good code formatting but I think you're changing all the lines nearby this in another pr - so just put it there. Small formatting PRs are just noise.

**Comment by 6543** [comment]
-> https://github.com/go-gitea/gitea/pull/7622

**Pull request closed without merging**
