### PR TITLE
Fix repo search broken because of profile page added

### LINKED ISSUE #25433: Repository Search Broken in 1.20.0-rc
### Description

When attempting to use the repository search function with a profile readme, upon entering the query, it kicks back to the overview tab.

### Gitea Version

1.20.0-rc

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Linux

### How are you running Gitea?

Docker image

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #25433 
Caused by #23260

### CODE REVIEW

**Comment by silverwind** [comment]
Is a regression test possible for this? Serious regressions like this shouldn't be missed by the integration tests.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Is a regression test possible for this? Serious regressions like this shouldn't be missed by the integration tests.

ps: that's why I don't like  PRs like "Fix ::User Profile Page - Project/Packages Tabs Have Inconsistent Layout #25108", these `if` blocks are too fragile.

**Comment by puni9869** [comment]
> > Is a regression test possible for this? Serious regressions like this shouldn't be missed by the integration tests.
> 
> ps: that's why I don't like PRs like "Fix ::User Profile Page - Project/Packages Tabs Have Inconsistent Layout #25108", these `if` blocks are too fragile.

Would you please suggest an approach to tackle the problem using a small code example? Your guidance will greatly assist me in understanding the solution.

**Comment by wxiaoguang** [comment]
Background: the thing I like doesn't mean it's liked by others, and the thing I don't like doesn't mean others don't like 😄  So, I share some my personal opinions, just for reference:

* For the "template" part, I think the shared parts could be made as page-independent as possible. It means that, the shared parts  (components) layouts themselves, eg: use "width 100%" provided by its container.
* Let the caller's page decided the container layout, instead of `{{if ThisPage}} <div "page-content foo"></div> {{else}} <div "page-content bar"></div>` in the shared templates.
* For the backend part, the pages could be covered by integration tests.

**Pull request merged**
