### PR TITLE
API: fix set milestone on PR creation

### PR DESCRIPTION
**Pull request by noerw**
PR creation via API failed with 404, because we searched
for milestoneID 0, due to uninitialized var usage D: (isn't this what linters are for?)

### CODE REVIEW

**Review by 6543 — COMMENTED** [review]
how did we missed that one!

would it be possible to extend one test case to get this covered?

**Comment by 6543** [comment]
if you need help for the fixtures (witch are broken right now) just ask

**Comment by noerw** [comment]
@6543 HELP! :D

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@noerw please backport

**Pull request merged**
