### PR TITLE
Implement "embedded" command to extract static resources

### LINKED ISSUE #9413: A new command to list and extract template files
When you want to customize your templates, you have to go to find source and download them. And also the same version. When you are in a stable version, you could find it easy. But for a dev branch, it's not as easy as before.

Since all templates has been embedded in binary, if we can list them and extract them. That's better.

**update**:

Maybe we could extract template files from a gitea sub command like

```
gitea resource list
gitea resource view templates/repo/migrating
gitea resource extract templates/repo/migrating
```

Then it will load the special template file from binary embbed resources to current directory.

**update**:
I rename `template` to `resource` so that we could also view/extract js/css files to inspect purpose.

### PR DESCRIPTION
**Pull request by guillep2k**
This PR adds a command for extracting static files from `gitea`. The purpose is to assist users in the customization process.

```
$ gitea embedded list '**openid**'
public/img/auth/openid_connect.png
public/img/openid-16x16.png
templates/user/auth/finalize_openid.tmpl
templates/user/auth/signin_openid.tmpl
templates/user/auth/signup_openid_connect.tmpl
templates/user/auth/signup_openid_navbar.tmpl
templates/user/auth/signup_openid_register.tmpl
templates/user/settings/security_openid.tmpl

$ gitea embedded extract --destination ~/work --overwrite 'templates/mail/**.tmpl'
Extracting to tempdir:
tempdir/templates/mail/auth/activate.tmpl
tempdir/templates/mail/auth/activate_email.tmpl
tempdir/templates/mail/auth/register_notify.tmpl
tempdir/templates/mail/auth/reset_passwd.tmpl
tempdir/templates/mail/issue/assigned.tmpl
tempdir/templates/mail/issue/default.tmpl
tempdir/templates/mail/notify/collaborator.tmpl

$ gitea embedded extract --custom 'templates/mail/issue/default.tmpl'
Extracting to /var/lib/gitea/custom
/var/lib/gitea/custom/templates/mail/issue/default.tmpl already exists; skipped.

$ gitea embedded extract --custom --rename 'templates/mail/issue/default.tmpl'
Extracting to /var/lib/gitea/custom
/var/lib/gitea/custom/templates/mail/issue/default.tmpl

$ ls /var/lib/gitea/custom/templates/mail/issue/
default.tmpl
default.tmpl.bak
```

### Status

- [x] Basic functionality
- [x] Acknowledge Windows is a thing
- [x] Add docs

Other examples:
```
$ gitea embedded list '**sidebar**'
public/fomantic/components/sidebar.css
public/fomantic/components/sidebar.js
public/fomantic/components/sidebar.min.css
public/fomantic/components/sidebar.min.js
templates/org/team/sidebar.tmpl
templates/repo/issue/view_content/sidebar.tmpl

$ mkdir temp
$ gitea embedded extract --destination temp '**sidebar.tmpl'
Extracting to temp:
temp/templates/org/team/sidebar.tmpl
temp/templates/repo/issue/view_content/sidebar.tmpl
$
```

Closes #9413

### CODE REVIEW

**Comment by zeripath** [comment]
I would allow extract to extract to the custom folder by default so that this can be used to prepopulate the templates folder.

**Comment by lafriks** [comment]
Probably should also add --force option to override already existing file

**Comment by guillep2k** [comment]
Ready for review.

@lafriks I've implemented the `--overwrite` and `--rename` flags. `--rename` will create a `.bak`. I can change `--overwrite` into `--force` if it's preferred.

@zeripath I've included a `--custom` flag to extract directly into Gitea's `custom` directory. I've refrained from make it the default option for the following considerations:

- Most extraction tools (e.g. `unzip`, `tar -x`, `gzip -d`, etc.) will extract to the current directory.
- The location of the `custom` directory is easy for the command to establish.... provided that `app.ini` is in the expected location, relative paths play as intended, etc. I figured that when everything is "default", typing in `--custom` is easy, but if anything is not default, perhaps it's better to let the user enter `--destination {dir}` and figure the `custom` location by themselves.

**Comment by guillep2k** [comment]
@lunny I've just realized that you've suggested a command syntax for this in #9413. This PR doesn't follow that syntax closely. Let me know if the new syntax is OK.

**Comment by lunny** [comment]
@guillep2k Great work!!! I'm OK with the syntax on this PR.

**Comment by lunny** [comment]
Could we view some files before we extract them?

**Comment by guillep2k** [comment]
> 
> 
> Could we view some files before we extract them?

Certainly! What about a `--view` flag? I would however give an error if many files match the pattern, in order to simplify things. Otherwise I'd need to deal with headers, separators, etc.

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
How about `gitea embedded view <filepath>`?

**Review by jolheiser — COMMENTED** [review]
looks good so far, will re-review when the view command/flag is implemented.

**Comment by guillep2k** [comment]
@lunny Done.

**Comment by guillep2k** [comment]
@jolheiser Done.

**Review by lunny — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
