### PR TITLE
Remove box-shadow from UI, fix dashboard issue

### PR DESCRIPTION
**Pull request by silverwind**
Two tweaks here:

1. Remove box-shadow from menus and segments. I think it generally looks better this way because most of the UI elements are already flat, and the box-shadowed elements look out-of-place.

#### Before
screen shot 2017-12-02 at 18 41 40

#### After
screen shot 2017-12-02 at 18 41 58

2. Fix a issue where the repo list in the dashboard sidebar was 2px wider than the pill menu above it. The cause of the issue looks to be some hacks in Semantic UI and that added artificial width to that repo box.

#### Before
screen shot 2017-12-02 at 18 41 04

#### After
screen shot 2017-12-02 at 18 39 42

### CODE REVIEW

**Comment by silverwind** [comment]
Fun fact: gogs has done a [similar change](https://github.com/gogits/gogs/commit/ebc0943713196abe939e445f35e0f726f5cbee1e#diff-55ceecf712d36e64d0cc61b96617263a) on hiding the box-shadows. I just went ahead and adopted the change as it seemed cleaner.

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lafriks** [comment]
@silverwind please resolve conflicts

**Comment by silverwind** [comment]
Rebased.

**Comment by lafriks** [comment]
Can you please force push?

**Comment by silverwind** [comment]
done

**Pull request merged**
