### PR TITLE
Fix repo-transfer-and-team-repo-count bug

### PR DESCRIPTION
**Pull request by ethantkoenig**
Remove code in `TransferOwnership` which decrements teams' number of repos, since that is already done by the `removeOrgRepo(..)` method. Also adds a unit test for a `TransferOwnership`.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
will fix #3233

**Comment by lafriks** [comment]
LGTM

**Comment by lafriks** [comment]
@ethantkoenig please backport

**Pull request merged**
