### PR TITLE
Ignore files in diff with .gitattributes

### LINKED ISSUE #12653: [Feature] Ability to exclude files from diffs
Github uses Linguist for code analysis in its repositories, and resulting from that introduced a nifty feature in its .gitattributes definitions: `linguist-generated`. This attribute can be used to exclude specific file types from diffs, code reviews, and hide it from showing in the file listing.
I've found that to be invaluable to working with Unity3D in order to keep .meta and .prefab files from cluttering code reviews. It would be cool to have a similar feature in Gitea

---

[Bountysource](https://www.bountysource.com/issues/92731348-feature-ability-to-exclude-files-from-diffs)

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #12653
close #16262
first step for #14786, #14528

This PR adds a `.gitattributes` parser to Gitea. It works like on Gitlab and "caches" the `.gitattribute` file from the root of the default branch in `repo.git/info/attributes`. The diff supports now the `linguist-generated` keyword and hides these file in the output.
test

### CODE REVIEW

**Comment by kdumontnu** [comment]
I still need to try this out, but does it also hide the diff for `linguist-generated`, like in GitHub?
I think even better would be to collapse the diff (AND not run the diffing algo, but that's not required here).
image

**Comment by zeripath** [comment]
nope.

This is not the way. 

git check-attr is the correct tool.

**Comment by KN4CK3R** [comment]
> I still need to try this out, but does it also hide the text diff by default for `linguist-generated`, like in GitHub?
> I think even better would be to collapse the diff (AND not run the diffing algo until it's needed).

The diff is initially hidden like on Github. The diff is not delayed because that's how Gitea works at the moment. See https://github.blog/2016-12-06-how-we-made-diff-pages-3x-faster/ how Github may do it.

**Comment by KN4CK3R** [comment]
> git check-attr is the correct tool.

Yes, the correct tool but it does not work with bare repos. See https://gitlab.com/gitlab-org/gitlab-foss/-/issues/2315#note_3339982 and the following posts.

**Comment by zeripath** [comment]
> > git check-attr is the correct tool.
> 
> Yes, the correct tool but it does not work with bare repos. See https://gitlab.com/gitlab-org/gitlab-foss/-/issues/2315#note_3339982 and the following posts.

False. We already use git check-attr in bare repositories.

Please look at:

https://github.com/go-gitea/gitea/blob/main/modules/git/repo_attribute.go

There is already an aborted partial attempt at getting the language from the repo attributes in #14833 which is almost there.

**Comment by KN4CK3R** [comment]
Cool, don't know why it didn't work for me yesterday 🤷‍♂️ 
I added a new version of this PR which uses check-attr. The copy of the `.gitattributes` skips the creation of a temporary index.

**Comment by lafriks** [comment]
It should also check enry.IsGenerated

**Comment by 6543** [comment]
replaced by #16773

**Pull request closed without merging**
