### PR TITLE
Update to github.com/lafriks/xormstore@v1.3.0

### PR DESCRIPTION
**Pull request by sapk**
Following #8309

Related to : https://github.com/lafriks/xormstore/pull/10

Commands used:

```
GO111MODULE=on go get -u -v github.com/lafriks/xormstore@v1.3.0
GO111MODULE=on go mod tidy
GO111MODULE=on go mod vendor
```

### CODE REVIEW

**Comment by lafriks** [comment]
Seems too much changes

**Comment by sapk** [comment]
@lafriks yes seems strange but I re-do it with the same result.

**Comment by sapk** [comment]
I seems to have something that is falling to generate a good update if someone can try on i side (and create an other PR ?)

**Comment by lunny** [comment]
I have the same result with you. I think it's because mssql have a new version.

**Comment by sapk** [comment]
Redoing it with go1.13 seems to fix it.

**Review by lafriks — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Pull request merged**
