### PR TITLE
Fix update avatar via email

### PR DESCRIPTION
**Pull request by liamcottam**
Minor fix:

When attempting to update an avatar via email address it will produce an error stating that the image is invalid when no image has been provided.

### CODE REVIEW

**Comment by techknowlogick** [comment]
Closing this as the code has added in #3988.

cc: @daviian

**Comment by daviian** [comment]
@liamcottam @techknowlogick 
My PR fixes that partially. Actually we should restructure the avatar settings module, as it is currently misleading. Changing from custom avatar to gravatar requires to click "Delete Avatar" instead of selecting the radio button and then "Update Avatar".
I stumbled across that problem myself.

**Comment by daviian** [comment]
@liamcottam I wanted to apologize that we didn't merge your PR before I introduced mine. I wasn't aware that there was already a proposal to fix that :worried:
And I've to add that we are always very pleased about contributions! Just wanted to make that clear :smiley:

**Comment by daviian** [comment]
You can follow https://github.com/go-gitea/gitea/issues/4025 for UI improvements on the avatar settings.
If you've an idea how to restructure the settings such that everything's clear just post it there.

**Comment by khera** [comment]
I see this is reported as a committed fix from May 21, but I still observe this problem with release 1.4.2 which was released in June. It is unclear to me if it is going to be held until 1.5.0 because that milestone was added and removed.  When would it be reasonable to expect it to make it to a release?

**Comment by lafriks** [comment]
@khera It has been already merged and will be part of 1.5.0 release

**Pull request closed without merging**
