### PR TITLE
Proposed changelog for 1.7.4

### PR DESCRIPTION
**Pull request by jolheiser**
As titled

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
So I think #6300 also fixes #6292 as that should have been pulled in to.

**Comment by techknowlogick** [comment]
@jolheiser Can you create a PR for release/v1.7 branch? Usually we merge changelog into release branch first.

**Comment by jolheiser** [comment]
Agh! I had selected that branch, I must have forgot to switch to it again when making an edit. Will do!

EDIT: Changing it here did not do what I was hoping. 😅

**Comment by techknowlogick** [comment]
Thanks 😄

**Comment by jolheiser** [comment]
Going to close this as I'll just cherry-pick the other PR once it's merged.

**Pull request closed without merging**
