### PR TITLE
Work around fomantic 2.8.5 bugs

### LINKED ISSUE #11759: bug:ui bug on merge way choose box
- Gitea version (or commit ref): 1.13.0+dev-120-gb534a5164 (master last commit)
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

See Screenshots

## Screenshots

image

### PR DESCRIPTION
**Pull request by CirnoT**
Closes https://github.com/go-gitea/gitea/issues/11759

https://github.com/fomantic/Fomantic-UI/pull/1372 and https://github.com/fomantic/Fomantic-UI/pull/1473

Before:
chrome_2020-06-05_10-35-30
chrome_2020-06-05_10-35-41

After:
chrome_2020-06-05_10-34-55
chrome_2020-06-05_10-34-39

### CODE REVIEW

**Comment by CirnoT** [comment]
The slight change in icon alignment is caused by https://github.com/fomantic/Fomantic-UI/commit/c9e768de50c91854c15fce8a6cc1e03005b6a629

**Review by lafriks — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Any related Fomantic issues for these? I guess at least https://github.com/fomantic/Fomantic-UI/issues/1502?

**Comment by CirnoT** [comment]
Yes that's the one for dropdown, as for icon vertical align, not sure it can be considered bug on Fomantic end aside from the fact that change was introduced in patch release.

For icon alignment looks like just a change on FA side, most likely they won't consider it as bug either.

**Comment by lubber-de** [comment]
Holy!  👀 We'll look into and will fix the dropdown issue asap! (although the `left menu` fix will also work (has no impact) in 2.8.4)

Regarding the icon issue, i cannot reproduce the drastical icon alignment difference as shown in your screenshots of gitea

I prepared 2 little jsfiddles out of the relevant gitea template code for the merge button and the underlying out-of-date info

I also see a slight difference in vertical positioning, but not as much as in your code. Am i missing some additional gitea class here? We will investigate, if we will revert the icon vertical align change .

### 2.8.4 OK
https://jsfiddle.net/usfh3tpw
image

### 2.8.5 Around 2px difference
https://jsfiddle.net/usfh3tpw/1/
image

### Gitea Screenhots (around 16px difference)
image

**Comment by lubber-de** [comment]
We fixed the icon alignment by https://github.com/fomantic/Fomantic-UI/pull/1503

**Comment by CirnoT** [comment]
@lubber-de The exlamation mark in your fiddle uses standard icon, but we use `<svg>` there.

2.8.4: https://jsfiddle.net/uzkmheLo/
2.8.5: https://jsfiddle.net/eokpj6rz/1/

**Comment by zeripath** [comment]
make lg-tm work

**Comment by lubber-de** [comment]
Fomantic-UI 2.8.6 has just been released which should fix the issues in the core now.

**Comment by silverwind** [comment]
Thanks! @CirnoT would you like to attempt this upgrade, removing workarounds where possible?

**Pull request merged**
