### PR TITLE
[WIP] Fix 6778

### LINKED ISSUE #6778: GPG not using correct UID
- Gitea version (or commit ref): 1.7.0
- Git version: 2.21.0
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

My GPG key has a revoked UID attached to it (it was revoked since I no longer own the email address it refers to). My primary UID is valid, and the email address it points to has been added to my Gitea account. However, when trying to add my key, Gitea displays the old (revoked) UID as the primary, and any commits signed using the updated key are marked as `No known key`. I tried removing my old email address from my account, and now Gitea just says my I need to have my old address attached in order to load the key.

It seem that Gitea is not correctly loading the primary UID. In addition, the commits should still be verified even with the updated key; it should be loading *all* UIDs ideally. Any help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by sapk**
- [X] Add test to reproduce the bug
- [ ] Fix #6778

### CODE REVIEW

**Comment by sapk** [comment]
The lib we use shouldn't return revoked ident but in this case it does. 
For details, the relative test in the lib : https://github.com/keybase/go-crypto/blob/master/openpgp/keys_test.go#L519

**Comment by sapk** [comment]
Rebased after #10234 to find it fix the bug.

**Comment by 6543** [comment]
Your test sucseeded but unit test failed?

**Comment by sapk** [comment]
@6543 the test is in the unit tests. And it is the one that failed.
This test should be ported to the source library to fix it there.

I haven't time to do so and only just quickly look at the code failing. but from time to time I update the lib to find if it fixed it 🤞 :smile: .

**Comment by sapk** [comment]
Also we should maybe create a new key without user information. (I think it is order dependant)

**Comment by 6543** [comment]
@sapk can you update :)

**Comment by 6543** [comment]
is it fixed upstream?

**Comment by 6543** [comment]
we should update after  #12481 got merged

**Comment by 6543** [comment]
ok @sapk can you update to test?

**Comment by zeripath** [comment]
Are we sure it's still needed?

**Comment by 6543** [comment]
#6778 is still open so I guess

**Comment by 6543** [comment]
update?

**Comment by zeripath** [comment]
#6778 was fixed by #12486 - I think we can close this

**Pull request closed without merging**
