### PR TITLE
Add dumb-init to rootless docker

### PR DESCRIPTION
**Pull request by viceice**
Add dumb-init as process reaper to the rootless image.
I've very often defunc hung git processes, which are not cleaned by gitea.

### CODE REVIEW

**Comment by viceice** [comment]
I'm using it here[^1] and it's working fine. Docuum is running docker cli which could also hung some times.

[^1]: https://github.com/visualon/docker-docuum/blob/fe8284b66b187dc3d53157886e0581b8e0738420/linux/Dockerfile#L45

**Comment by silverwind** [comment]
> I've very often defunc hung git processes, which are not cleaned by gitea

I think we better fix the root issue so that deployments in docker-less environments can benefit too.

**Comment by viceice** [comment]
> > I've very often defunc hung git processes, which are not cleaned by gitea
> 
> I think we better fix the root issue so that deployments in docker-less environments can benefit too. Or at least, do the reaping in-process.

on normal systems the init process does the process reaping, so no need to do anything there.

the reaping should do the process with id zero.

https://iximiuz.com/en/posts/dealing-with-processes-termination-in-Linux/

**Comment by silverwind** [comment]
The rootful images uses [s6](https://skarnet.org/software/s6/s6-svscan.html) which seems to include a reaper. I'm not sure the reasoning why the rootless images does not have one, but I don't think we should have two different ones.

**Comment by viceice** [comment]
so should I refactor to use s6 instead of dumb-init? 

dumb-init was a much simpler solution 😅

**Comment by silverwind** [comment]
I'm not sure what the state-of-the-art reaper is but your dumb-init seems generally more popular than s6. Maybe we should get rid of s6, but please wait on more opinions, I'm no expert on this and we might overlook functionality provided by s6 that dumb-init does not have.

https://github.com/Yelp/dumb-init
https://github.com/skarnet/s6

**Comment by viceice** [comment]
> I'm not sure what the state-of-the-art reaper is but your dumb-init seems generally more popular than s6. Maybe we should get rid of s6, but please wait on more opinions, I'm no expert on this and we might overlook functionality provided by s6 that dumb-init does not have.
> 
> https://github.com/Yelp/dumb-init
> https://github.com/skarnet/s6

ok, s6 is more like systemd, it can watch and restart multiple processes. dumb-init just starts one child process and exits when child dies.

**Comment by techknowlogick** [comment]
> it can watch and restart multiple processes

Yup, that's why it is used for the rootful one as we use opensshd in it as well. I think it's reasonable to use dumb-init for rootless.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I'd also be happy if we could just do the reaping from within Gitea itself but I'm not against dumb-init being used.

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport to 1.18

**Comment by zeripath** [comment]
@xin-u how is this breaking?

**Comment by viceice** [comment]
> Please send backport to 1.18

will do tomorrow

**Comment by lafriks** [comment]
> > @xin-u how is this breaking?
> 
> `ENTRYPOINT` was changed.

But arguments will still be passed to entrypoint.sh and and if you have provided custom entrypoint it would still work so I don't see use case that would break 🤔

**Comment by viceice** [comment]
> If user would pass `--entrypoint` to docker, they would overwrite the whole entrypoint, but I guess all bets are off if that is done. Arguments should still pass through without breakage.

yes, but it's not breaking. it overrided before the same.

**Comment by viceice** [comment]
> Please send backport to 1.18

- #22046

**Comment by lafriks** [comment]
> If user would pass `--entrypoint` to docker, they would overwrite the whole entrypoint, but I guess all bets are off if that is done. Arguments should still pass through without breakage.

But it would still work for user with his custom entrypoint as no paths or anything else claws changed, it would still work for him as it was before just dumb init would not be used

**Pull request merged**
