### PR TITLE
Use more specific test methods

### PR DESCRIPTION
**Pull request by KN4CK3R**

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Good catch ... just curious, how do you find so many different improper styles?

**Comment by KN4CK3R** [comment]
With the power of friendship! And regex. Mostly regex...: `assert.Equal` + `len`/`[]`/`true`/`false`

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
.

**Comment by silverwind** [comment]
.

**Comment by silverwind** [comment]
.

**Review by delvh — APPROVED** [review]

**Pull request merged**
