### PR TITLE
Remove legacy handling of drone token

### PR DESCRIPTION
**Pull request by techknowlogick**
Drone has removed support for basic user/pass handling which had used tokens. This is no longer needed.

### CODE REVIEW

**Comment by lunny** [comment]
Which drone version did it implement that?

**Comment by techknowlogick** [comment]
1.4

And Oauth2 support with Gitea has been in drone since 1.1

**Review by sapk — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@techknowlogick Will this PR break the users who use drone 1.1~ 1.3 ?

**Comment by lafriks** [comment]
If they use deprecated version of not using oauth2 than yes

**Pull request merged**
