### PR TITLE
Remove check on username when using AccessToken authentication for the API

### LINKED ISSUE #10903: can not use "https://oauth2:<token>@url" to clone code
we need  use format as 'oauth2:<token>' to clone code ,and failure occurred in the process!

- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

...

### PR DESCRIPTION
**Pull request by zeripath**
As highlighted by #10902 the current situation of authentication with access tokens is inconsistent.

This PR is an alternative to #11014, and simply removes the username check making this consistent with Oauth2 tokens.

Closes #10902
Closes #11014 
Fixes #10903

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
I'm ok with this since it wont make a huge diff in securety

**Comment by 6543** [comment]
@zeripath can you add the specivic labels to this pull :)

**Review by guillep2k — APPROVED** [review]
Code looks good to me, but I don't know much about the several auth options required by different usage scenarios, so I don't have an opinion whether this or #11014 should prevail.

**Comment by jolheiser** [comment]
Ping lgtm

**Comment by jolheiser** [comment]
Ping lgtm

**Pull request merged**
