### PR TITLE
Fixed incorrect locale references

### PR DESCRIPTION
**Pull request by kerwin612**
Fixed two incorrect headers for setting the page navigation bar:
* User settings page, should not use the title "`org.settings`"
* Repo settings page, should not use the title "`org.settings`"

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by puni9869** [comment]
Any screenshots?

**Review by puni9869 — APPROVED** [review]

**Comment by lunny** [comment]
Could you post screenshots before and after?

**Comment by kerwin612** [comment]
before：
4UJL8P76PWV`53Q0}~C`J81
}_KJ55V%@$A_WI(S@MX0UC5

after：
HLSM%4CK43~6$I@ZWRM1GO8
8IL~ 23DUDEG)P5JLPA%V6D

**Comment by lunny** [comment]
Should this be backport to v1.20?

**Review by lunny — APPROVED** [review]

**Comment by puni9869** [comment]
> Should this be backport to v1.20?

Yes, we need this one to be backported.

**Pull request merged**
