### PR TITLE
Fix adding branch as protected to not allow pushing to it

### LINKED ISSUE #2517: Protected branchs doesn't work
- Gitea version (or commit ref): 1.2.0+rc1-4-g0c910af 
- Git version:  2.14.1
- Operating system: amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

I have tried protected branch, but it still push successfully.
When I tried via 1.1.3 again, it works fine.

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #2517

This PR targets 1.2 branch as bug is present only in it. In master branch it works fine as @lunny did rewrite protected branch UI & functionality with whitelist support

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by daviian** [comment]
@lafriks IMO there should be a migration from old protected branches as well, since existing protected branches do not work after that change.

**Comment by lafriks** [comment]
@daviian they will not work only for those who added protected branches in 1.2-rcX. Protected branches when upgrading from 1.1 to 1.2 they will work and adding new migration here would break upgrade path from 1.2 to 1.3 later

**Comment by daviian** [comment]
@lafriks But when upgrading from 1.1 to 1.2 existing protected branches have `can_push=true`, so after this PR they are not protected and need to be readded.

**Comment by daviian** [comment]
I would suggest a quick'n'dirty workaround to release v1.2 since it is already fixed in current master.

Simply remove the `CanPush` check in https://github.com/lafriks/gitea/blob/1773e88643a2df7e7efbe86ec424409b45a4d576/cmd/hook.go#L130

**Comment by lunny** [comment]
@daviian in fact, canpush never be used, when remove from protected branch, the database record will be deleted not updated canpush to false.

**Comment by lunny** [comment]
that means, this PR will not break anything, I think.

**Comment by lafriks** [comment]
@lunny @daviian no `private.GetProtectedBranchBy(repoID, branchName)` will not return nil when there is no protected record, it will just return type object with `CanPush: true` set. I might add new migration to both master & 1.2 than that updates all rows to can_push = false.

**Comment by lafriks** [comment]
also this column will be needed anyway later to be able to set that branch can be pushed to always but are protected only from deletion

**Comment by daviian** [comment]
@lunny @lafriks I've simulated an update from `1.1.4` to `1.2` (including this PR) with a fresh database (only one new created repository and a protected branch in it) and everything and the PR in its current state doesn't fix the issue.
So I agree with @lafriks to create a migration in master and 1.2

**Comment by lafriks** [comment]
@lunny @daviian Migration PR that I will chery-pick to this PR when it is merged to master: #2560

**Comment by lafriks** [comment]
@daviian @lunny migration added so upgrade path should work just fine now also

**Comment by daviian** [comment]
@lafriks Tested and works like a charm 👍

**Comment by daviian** [comment]
LGTM

**Comment by daviian** [comment]
Make LG-TM work

**Comment by lafriks** [comment]
Make LG-TM work again

**Pull request merged**
