### PR TITLE
SHA in merged commit comment should be rendered ui sha

### LINKED ISSUE #15049: [UI] SHA links in timeline (sub)events may look better in monospace
- Gitea version (or commit ref): 1.14.0+dev-864-gdf891dc59
- Git version: -
- Operating system: -
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://gitea.com/gitea/go-sdk/pulls/485
  - [ ] No
- Log gist:

## Description

...

Somehow I stumbled on this while reworking on frontend. I compared the relevant snippets from [/repo/issue/view_content/comments.tmpl](https://github.com/go-gitea/gitea/blob/master/templates/repo/issue/view_content/comments.tmpl#L128-L130) and [pull.tmpl](https://github.com/go-gitea/gitea/blob/a5279b74b63248902a6572df5afa3745367e6cb9/templates/repo/issue/view_content/pull.tmpl#L133-L135) and see no real difference whatsoever. Any thoughts?

## Screenshots

-3 - --gitignore- を更新 - Test - Gitea- Git with a cup of tea 3-19-2021 5-37-29 PM

### PR DESCRIPTION
**Pull request by zeripath**
On a PR page the sha of the merge commit should be rendered in monospace
as a SHA. Also fixes an issue with the manually merged string and issues.force_push_codes

Fix #15049

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
This is a difficult one. Ideally it would be backported but then we'd need to change the locale strings too.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Hmm it might be possible to fix all translations with some `sed` action.

**Comment by silverwind** [comment]
There might be more similar cases, I'm not sure.

```
issues.commit_ref_at = `referenced this issue from a commit <a id="%[1]s" href="#%[1]s">%[2]s</a>`

**Comment by silverwind** [comment]
`issues.force_push_codes` should be a affected one.

**Comment by zeripath** [comment]
yup agreed

**Comment by silverwind** [comment]
Can't find any more.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
