### PR TITLE
Run fmt on files on master

### PR DESCRIPTION
**Pull request by davidsvantesson**
When running `make fmt` on master this file (added in #8964) is modified (at least on linux and mingw).

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]
I encountered the same issue.

**Comment by guillep2k** [comment]
Running `make fmt` on this branch works without changing any files now. 👍

**Review by jolheiser — APPROVED** [review]
Also happened to me earlier.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Sorry I relied on vscode and make release-windows to fix these for me - unfortunately I seem to be having a bit of trouble with the new go language server implementation and clearly it didn't run fmt on these.

**Comment by davidsvantesson** [comment]
No problem, I was just surprised it wasn't catched by CI.

**Pull request merged**
