### PR TITLE
init suport for org mode

### LINKED ISSUE #1272: rendering of org readme files, in particular headings bullets and codeblocks
I noticed that gitea does not render org files which would be rendered on github I would like to see this supported.

Is this something that would be reasonably easy to add, anyone able to outline what might be needed in case I decide to tackle the issue.

I generally use org over md because it has better table support and allows you to run the code blocks directly instead of copying and pasting.

not sure if golang has an org parser currently to aid in adding this feature ?

### PR DESCRIPTION
**Pull request by lunny**
will resolve #1272

### CODE REVIEW

**Comment by strk** [comment]
Wow, lots of files changed. Did you add specific tests for the new support ?

**Comment by lunny** [comment]
@strk have not. I will add some. And in fact, only file `orgmode.go` and `orgmode_test.go` is new functions. But I have splitted `markdown.go` to many files.

**Comment by lunny** [comment]
Todo: 
- [ ] let org's extension name configurable
- [ ] add unit tests for orgmode

**Comment by lunny** [comment]
will be part of #374

**Comment by lunny** [comment]
replaced by #2525

**Pull request closed without merging**
