### PR TITLE
Return a UserList from /api/v1/admin/users

### PR DESCRIPTION
**Pull request by zeripath**
The new /api/v1/admin/users endpoint doesn't return a UserList as described on swagger and doesn't return `api.User` but rather an unsanitised form of `models.User`.

This PR fixes this.

### CODE REVIEW

**Comment by lunny** [comment]
How about make a function `convertUser` to convert a `models.User` to `api.User` so that two places could use it?

**Comment by lunny** [comment]
And any test for this API is better!

**Review by sapk — APPROVED** [review]

**Review by adelowo — APPROVED** [review]

**Comment by lunny** [comment]
But CI build failed.

**Comment by zeripath** [comment]
*Sigh* sorry about that.

**Comment by techknowlogick** [comment]
@zeripath merged 😃 please backport.

**Pull request merged**
