### PR TITLE
Configure update checker on installation page

### PR DESCRIPTION
**Pull request by Gusted**
- I recently became aware that this was enabled by-default, I don't necessary agree with that and this should rather be configured by the user(this patch does that on the installation page) as it connects to a homeserver, which I'd prefer to avoid on my instance.

image

### CODE REVIEW

**Comment by Gusted** [comment]
Should we mark this as breaking?

**Comment by jolheiser** [comment]
I think this is reasonable, but I'm wondering if it should be more prominent on the page.

Given Gitea usually fixes a few security issues between releases, staying up to date is important.

**Comment by Gusted** [comment]
> but I'm wondering if it should be more prominent on the page.

We can move it to the general section, which is not hidden under a `<summary>`.

**Comment by Gusted** [comment]
43b4a9e6fcc1cb9038a6881b740ce662422b14df moved it to the General section, updated the screenshot accordingly.

**Comment by lunny** [comment]
Why not check it by default so that will be no break?

**Comment by Gusted** [comment]
> Why not check it by default so that will be no break?

It wouldn't break for new instances(as they can explicitly configure this option), but existing instances who follow the default value of the code will "break", as the update checker will now be disabled by-default.

**Comment by lunny** [comment]
> > Why not check it by default so that will be no break?
> 
> It wouldn't break for new instances(as they can explicitly configure this option), but existing instances who follow the default value of the code will "break", as the update checker will now be disabled by-default.

Like @jolheiser said, default check because we want the default values are security when possible. Both privacy and security are very important for users, we need a balance here.

**Comment by Gusted** [comment]
> we need a balance here.

I agree, but I think the privacy aspect is more important here (especially because it was enabled without notice, in my opinion) than the security aspect. We should encourage it, as such I moved it to the general area, and I can even make it check by default. However, enabling this should be entirely up to the user.

**Comment by lunny** [comment]
> > we need a balance here.
> 
> I agree, but I think the privacy aspect is more important here (especially because it was enabled without notice, in my opinion) than the security aspect. We should encourage it, as such I moved it to the general area, and I can even make it check by default. However, enabling this should be entirely up to the user.

I can't agree this privacy is more important than security, because it will only expose your IP address. If the instance is a public instance, the IP address of course has been exposed by himself. If the instance is not a public one, it should be behind at some public gateway, so the IP is that gateway's not this machine. I agree this PR is necessary to let user chose but we need to remind what's the option meaning.

**Comment by zeripath** [comment]
I think making this disabled by default when there is no config is too breaking. People will have relied on this functionality and therefore changing the default is a BREAKING change and hence a bad thing no matter what your views of whether update-checkers should be running by default or not. 

Therefore as questionable as it is that it is enabled by default and I missed that it had been set that way - it has been this way for a long time and therefore we have to leave it that way for those users.

---

I certainly agree that making an option on the install page is very helpful and useful and should have been there from the start.

--- 

It would however be easy to make it default to disabled for new installs:

* Set the app.ini templates for the dockers to have `[cron.update_checker]` `ENABLED=false` set
* Set the default in the install page to set this checkbox to false.

**Comment by Gusted** [comment]
Alright seems like more people agree on leaving it enabled, rolling that particular code back. https://github.com/go-gitea/gitea/pull/21655/commits/c47cd923ffa9e88893d34dd0ce5e21ab85c513c7

**Review by zeripath — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by techknowlogick** [comment]
Thanks for this PR @Gusted, as you can see from the original PR I wanted it to be disabled, however both @lafriks and @6543 requested it be made enabled by default.

I also added in a privacy enabling section, so if people didn't want to check the dl.gitea.io site, they could also check an alternative json file fully under their control.

**Comment by wxiaoguang** [comment]
The UI is broken.

The box should be in the same line of the text.

image


image

**Comment by Gusted** [comment]
https://github.com/go-gitea/gitea/pull/21660

**Pull request merged**
