### PR TITLE
Fix files/commits of merged PRs

### LINKED ISSUE #2797: PR revisions tab show more commits after being merged
- Gitea version (or commit ref): 1.2.1+6-g33e1641
- Git version: 
- Operating system: Docker
- Database:
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/deguif/test-pr-commits)

## Description
After merging a PR, the revisions tab on the PR page show more commits than when the PR was merged.
For example, in my case the PR had one commit in its revisions tab, once merged it got a lot more commits.

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #2797. Instead of looking at the range `<base>...<merge-commit>`, look at the range `<base>...<end-commit>` for determining commits and file diffs.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by deguif** [comment]
Anyone to review it?
Would love to see this merged quickly as this a really inconvenient issue.

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
Please send back port to v1.3

**Pull request merged**
