### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by muesli**
Simple, nit-picky typo fixes.

### CODE REVIEW

**Review by sapk — CHANGES_REQUESTED** [review]
Thx for your contrib and your catch. 
The function name is also malformated (golang comments need to start with function name). The function should be renamed and any reference to it also.

**Comment by muesli** [comment]
Wow, hah, didn't notice that! Will fix.

**Comment by muesli** [comment]
Ok, I see: this stems from a typo in go-macaron. Will try to fix this upstream first. Could be interesting as it's a breaking API change.

**Comment by muesli** [comment]
For reference: https://github.com/go-macaron/session/pull/29

**Review by lafriks — APPROVED** [review]

**Review by lafriks — CHANGES_REQUESTED** [review]
Methods must be renamed also

**Comment by muesli** [comment]
@lafriks Yeah, see comments above in this PR. It's a bit of an upstream-induced mess.

**Review by zeripath — CHANGES_REQUESTED** [review]
Sorry this won't work. They're part of an external API

**Comment by zeripath** [comment]
Thanks for your attempt but this just won't work unless we either:

* Get upstream fixed (unlikely as there's been a pr proposing this fix for years)
* Fork upstream, bring in-house and fix ourselves - in which case we can remove these files and fix the session provider directly
* Migrate to some other session provider

**Comment by 6543** [comment]
fix this on our side: https://gitea.com/macaron/session/ ?

**Comment by zeripath** [comment]
@6543 I think the macaron.Session.Destory ones have been fixed and are in the gitea git. Not sure if the session shim was updated at the same time though. I'll remove my review if you want to bring this PR back to life.

**Comment by 6543** [comment]
If so not now

**Comment by lunny** [comment]
Yes, this could be closed I think.

**Comment by sapk** [comment]
Updating the PR with last changes master seems to pass and the change is void now.

This was implemented by https://gitea.com/macaron/session/pulls/7 and https://github.com/go-gitea/gitea/pull/7933 

I will close this PR has it has been implemented elsewhere and not needed anymore. Thanks @muesli for the finding and PR.

**Pull request closed without merging**
