### PR TITLE
Add ZH readme

### PR DESCRIPTION
**Pull request by lunny**
We ever removed this file. But I get it back. It is very important for localization and I think it's very attractive for Chinese People.

### CODE REVIEW

**Comment by lunny** [comment]
I think I can translate it from the main version when it changed.

**Comment by metalmatze** [comment]
Hmm. Maybe this should be rather a part of the docs. I don't like the idea to have n README.md for each language in the project. 😉

**Comment by tboerger** [comment]
I'm also not really happy with that. I would prefer to reduce the content of the readme and reference to a multilingual documentation.

**Comment by lunny** [comment]
In fact it's difficult to me to tell Chinese people to move to Gitea from Gogs since there are so many Gogs users in China. I think gitea needs more localization even if it need more work on translations. For Chinese, I think I can do that. So I think this PR is needed and I wish we can add more locale README if there is a man to maintain it. I have created a Chinese discuss place and added it on README_ZH.md so that more Chinese people could add to that QQ Qun. In China, most people is very difficult to visit gitter and google groups because of difference languages and Great Wall.

**Comment by lunny** [comment]
I think currently it is.

**Comment by tboerger** [comment]
Maybe we should also add a joint to the pull request template if somebody changed the readme to /cc @lunny to update the translation

**Comment by andreynering** [comment]
I don't see a problem with having a Chinese README.

LGTM

**Comment by strk** [comment]
I'm also ok with the Chinese special case, at least until there's an active maintainer for it. LGTM

**Comment by lunny** [comment]
Thanks!

**Pull request merged**
