### PR TITLE
MySQL, Postgres integration tests in drone

### PR DESCRIPTION
**Pull request by ethantkoenig**
Run `make test-mysql` and `make test-pgsql` in drone.

### CODE REVIEW

**Comment by lunny** [comment]
@ethantkoenig I resigned drone.

**Comment by ethantkoenig** [comment]
@lunny There was a mistake in `.drone.yml`, so I will need a new signature

**Comment by lunny** [comment]
@ethantkoenig rebased and resigned

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
@lunny sig file conflict.

**Comment by appleboy** [comment]
make L-G-T-M work

**Pull request merged**
