### PR TITLE
Fix bare-repo bugs

### PR DESCRIPTION
**Pull request by ethantkoenig**
Check if that repo is not bare for the following endpoints:
- `:owner/:repo/commits`
- `:owner/:repo/raw/*`
- `:owner/:repo/commit/:sha`
- `:owner/:repo/graph`

Previously, accessing these endpoints with a bare repo resulted in a 500.

### CODE REVIEW

**Comment by lafriks** [comment]
Integration tests for this would be nice

**Comment by andreynering** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by lunny** [comment]
please force empty push

**Comment by lunny** [comment]
Maybe some tests? @ethantkoenig

**Comment by ethantkoenig** [comment]
@lunny @lafriks Added tests

**Comment by lafriks** [comment]
In test there is unused import

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
