### PR TITLE
Check for zero time instant in `TimeStamp.IsZero()`

### PR DESCRIPTION
**Pull request by Gusted**
- Currently, the 'IsZero' function for 'TimeStamp' just checks if the unix time is zero, which is not the behavior of 'Time.IsZero()', but Gitea is using this method in accordance with the behavior of 'Time.IsZero()'.
- Adds a new condition to check for the zero time instant.
- Fixes a bug where non-expiring GPG keys where shown as they expired on Jan 01, 0001.
- Related https://codeberg.org/Codeberg/Community/issues/791

Before:
image

After:
image

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]
Generally looks fine, but do we want to refactor the code checking for `0` as well, since as you've noted that is a divergence from `time.Time`?

Just wondering if this will affect other parts of the code that expects this 0-based implementation. Seems unlikely, though.

**Comment by Gusted** [comment]
> Just wondering if this will affect other parts of the code that expects this 0-based implementation. Seems unlikely, though.

It wouldn't surprise me if a lot of code actually things unix(0) == zero time. So better safe than sorry to keep to `0` check.

**Review by zeripath — APPROVED** [review]

**Comment by KN4CK3R** [comment]
I touched that method some weeks ago #21593 See my comment there why I changed it.

**Comment by Gusted** [comment]
Yeah, but the return value of a forever valid key is `time.Time{}`, so I'm essentially hacking that condition back in, as some code does rely on that specific condition.

https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/models/asymkey/gpg_key_common.go#L85

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
