### PR TITLE
Fixes #12341: Release date should only be set to current time if draft or tag created

### LINKED ISSUE #12341: Release date keeps getting updated even if you're updating the content of the release notes
- Gitea version (or commit ref): 1.12.2
- Git version: 2.14.5
- Operating system: MacOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I make a release, the created unix time gets set to the time I make the release, no the commit, which is right.

Yet if I now update my release by editing its content, its date changes.

This is a problem if I update an old release, such as tell users not to use, it becomes the release at the top of the release page!

Related to this change: https://github.com/go-gitea/gitea/pull/11218

Basically you should only change the release created_unix if it is making an actual tag (going from Draft to pre-release or release), do not touch it if updating a release or pre-release.

...

## Screenshots
On try.gitea.io, making two releases v1, then v2, then edit v1. It now is at the top.

Screen Shot 2020-07-27 at 3 39 54 PM
Screen Shot 2020-07-27 at 3 40 14 PM
Screen Shot 2020-07-27 at 3 40 32 PM

### PR DESCRIPTION
**Pull request by richmahn**
We should only change the created_unix of a release when the tag is made or if it is a draft. Currently it changes it whenever any edit is done to the release.

### CODE REVIEW

**Comment by richmahn** [comment]
Will make backport to 1.12

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
Need to `make fmt`.

**Review by 6543 — APPROVED** [review]
tests :heart_eyes:

**Comment by richmahn** [comment]
@silverwind Looks like @techknowlogick did it for me. Was going to do that this morning. Noticed the stray commas when looking at why my tests were failing.

So @techknowlogick, I fixed the tests. Waiting for build.

**Comment by richmahn** [comment]
@silverwind  I `make fmt` all the time, especially in my company's fork of Gitea, yet I still get unformatted code in my commits. I can't win! LOL

**Comment by zeripath** [comment]
@richmahn the results of `go fmt` can differ between different versions of go - if you're not running the same version of go as drone you may find that this is a problem.

I've never had to run make fmt explicitly what editor are you using?

**Comment by richmahn** [comment]
@zeripath What do you mean by running it explicitly? Do your IDE format whatever you write after you change lines? I use GoLand, even though I want to use VSCode but never successfully got it to build and run tests.

**Comment by jolheiser** [comment]
I believe both GoLand and VSCode can automatically format saved files (or however they are configured to watch).

**Comment by richmahn** [comment]
@jolheiser Hmm, ok, will have to look into how to configure it. I have done that in VSCode for Javascript before.

**Comment by 6543** [comment]
I prevere a `make fmt` befor commiting, so code is not flowing around while typing

**Comment by 6543** [comment]
> ... I make fmt all the time, especially in my company's fork of Gitea, yet I still get unformatted code in my commits. I can't win! LOL

don't know how this can happen, do you use the IDE to do git stuff?

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
