### PR TITLE
Bugfix for image compare and minor improvements to image compare

### LINKED ISSUE #8226: "call of nil" exception when comparing images
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/saitho/test2/pulls/3/files

## Description

Opening a pull request that adds or modifies an image works fine.

However in the file view of the pull request an error is thrown:

> template: repo/diff/image_diff:14:29: executing "repo/diff/image_diff" at <call .root.FileExistsInBaseCommit .file.OldName>: error calling call: call of nil

### PR DESCRIPTION
**Pull request by saitho**
- Resolves #8226: error when comparing files
- Updated behaviour: also show image metadata for newly added images
- Updated behaviour: Check if file exists in commit via blob instead of git-ls

### CODE REVIEW

**Comment by guillep2k** [comment]
There's a case that it's still not covered:

* Go to the repository front page (`<Code>`)
* Upload File
* Drag & drop an image (leave the directory empty)
* Commit to master (no pull request)
* In the main page (`<Code>`), find the new picture and click on the commit message:

image

image

**Comment by saitho** [comment]
Should be fixed now.

**Comment by lafriks** [comment]
Code style issue:
```
routers/repo/commit.go:244:33: should drop = nil from declaration of var parentCommit; it is the zero value (golint)
--
39 | var parentCommit *git.Commit = nil
```

**Comment by guillep2k** [comment]
It works for me now!

**Comment by guillep2k** [comment]
Please correct the following:
```
routers/repo/commit.go:244:33: should drop = nil from declaration of var parentCommit; it is the zero value (golint)
var parentCommit *git.Commit = nil
make: *** [Makefile:517: golangci-lint] Error 1
```

**Comment by guillep2k** [comment]
Now it complains about missing comments:
```
services/compare/compare.go:17:1: exported function SetPathsCompareContext should have comment or be unexported
services/compare/compare.go:30:1: exported function SetImageCompareContext should have comment or be unexported
```

**Comment by guillep2k** [comment]
Really, it would be nice if the linter wouldn't stop at the first error.

**Review by guillep2k — APPROVED** [review]

**Comment by lunny** [comment]
I don't think a service depends `context.Context` is a good practice. `Services` should be depends by routers.

**Comment by saitho** [comment]
Moved it back into routers package, as the files that use the functions are in that package as well, so that works. ;)

**Comment by lunny** [comment]
I found only when delete an image, the preview is not shown but added or changed an image it will show the preview UI. If that is expected, I will give my LGTM.

**Comment by guillep2k** [comment]
> 
> 
> I found only when delete an image, the preview is not shown but added or changed an image it will show the preview UI. If that is expected, I will give my LGTM.

@saitho could you please check why deleting an image doesn't show the previous one?

**Review by guillep2k — APPROVED** [review]
Fix LG-TM

**Comment by saitho** [comment]
Not intended - fixed. Also simplified the logic for checking if an image should be displayed.
Before it checked if the file exists in the commit. Now it uses the already existing IsDeleted and IsAdded flags in file.

**Pull request merged**
