### PR TITLE
Fix for #361, renamed username to login

### PR DESCRIPTION
**Pull request by Bwko**

### CODE REVIEW

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Comment by richmahn** [comment]
Any reason API is being updated (not just this PR of course, but what it is fixing) but not changed to v2?  We have thousands of users/tablets with our app which logs into our Gogs/Gitea. While I understand changing "username" to "login" like Github, that breaks the API when companies like our rolled this out. Just something to remember.

**Comment by tboerger** [comment]
You are right, at least it should provide a fallback with a deprecation message

**Comment by bkcsoft** [comment]
@tboerger how do you implement deprecation messages for this? how do we know that `username` is used instead of `login` ?

**Comment by bkcsoft** [comment]
@richmahn This was broken by a refactor in go-gogs-client a while back, I didn't really see the point in changing the api-version. it should however obviously be documented in the Changelog when 1.0 is released. 🙂

**Comment by bkcsoft** [comment]
Also, for clients using the latest version of `go-sdk` this isn't a problem since the struct member haven't changed name

**Comment by tboerger** [comment]
I need to search for an example we used for drone, but we have done it with a customized marshal/unmarshal

**Comment by bkcsoft** [comment]
Well sure, for `go-sdk` that works... but not when they consume the API in any other way. And like I said, `go-sdk` havn't changed it's internal format

**Pull request merged**
