### PR TITLE
use LC_ALL=C in unit-test's

### PR DESCRIPTION
**Pull request by 6543**
make test uses same locales always !

### CODE REVIEW

**Comment by 6543** [comment]
@mrsdizzie created PR ...

**Comment by zeripath** [comment]
Is this because git commands may run in different locales and you get different error messages? If so #8548 will fix this.

**Comment by 6543** [comment]
@zeripath #8548 didn't fix my locale issue

**Comment by 6543** [comment]
```
--- FAIL: TestRepoIsEmpty (0.02s)                                                                                                                                                                                                                                                                                             
    repo_test.go:34:                                                                                                                                                                                                                                                                                                          
                Error Trace:    repo_test.go:34                                                                                                                                                                                                                                                                               
                Error:          Received unexpected error:                                                                                                                                                                                                                                                                    
                                check empty: exit status 128 - fatal: Ihr aktueller Branch 'master' hat noch keine Commits.                                                                                                                                                                                                   
                Test:           TestRepoIsEmpty
```

**Comment by 6543** [comment]
```
--- FAIL: TestGetDiffPreviewErrors/empty_repo (0.01s)                                                                                                                                                                                                                                                                     
        diff_test.go:129:                                                                                                                                      
                Error Trace:    diff_test.go:129                                                                                                               
                Error:          Error message not equal:                                                                                                       
                                expected: "repository does not exist [id: 0, uid: 0, owner_name: , name: ]"
                                actual  : "Clone: exec(33:Clone (git clone -s --bare): /tmp/appdata135631676/tmp/local-repo/upload-283806141.git) failed: exit status 128(<nil>) stdout:  stderr: fatal: Repository '/tmp/repos629996817/error/.git' existiert nicht.\n fatal: Repository '/tmp/repos629996817/error/.git' exi
stiert nicht.\n"                                                                                                                                                                                                                                                 
```

**Comment by 6543** [comment]
```
--- FAIL: TestGetDiffPreviewErrors/bad_branch (0.02s)                                                                                                      
        diff_test.go:136: 
                Error Trace:    diff_test.go:136
                Error:          Error message not equal:
                                expected: "branch does not exist [name: bad_branch]"
                                actual  : "Clone: exec(34:Clone (git clone -s --bare): /tmp/appdata135631676/tmp/local-repo/upload-292271397.git) failed: exit status 128(<nil>) stdout:  stderr: Klone in Bare-Repository '/tmp/appdata135631676/tmp/local-repo/upload-292271397.git' ...\nfatal: Remote-Branch bad_branch ni
cht im Upstream-Repository origin gefunden\nfatal: Die Gegenseite hat unerwartet abgebrochen.\n Klone in Bare-Repository '/tmp/appdata135631676/tmp/local-repo/upload-292271397.git' ...\nfatal: Remote-Branch bad_branch nicht im Upstream-Repository origin gefunden\nfatal: Die Gegenseite hat unerwartet abgebrochen.\n"
                Test:           TestGetDiffPreviewErrors/bad_branch
```

**Comment by 6543** [comment]
```
--- FAIL: TestRelease_MirrorDelete (0.16s)
    mirror_test.go:88:                                
                Error Trace:    mirror_test.go:88              
                Error:          Not equal:              
                                expected: 1                    
                                actual  : 2             
                Test:           TestRelease_MirrorDelete
```

**Comment by guillep2k** [comment]
Why not just...?
```
GO ?= go
SED_INPLACE := sed -i
SHASUM ?= shasum -a 256

export PATH := $($(GO) env GOPATH)/bin:$(PATH)
export LC_ALL := C                     <==== added here
```

**Comment by mrsdizzie** [comment]
> Why not just...?
> 
> ```
> GO ?= go
> SED_INPLACE := sed -i
> SHASUM ?= shasum -a 256
> 
> export PATH := $($(GO) env GOPATH)/bin:$(PATH)
> export LC_ALL := C                     <==== added here
> ```

I don't think you'd want to set that for every command run (you probably do want to keep most things in your language). This is just a particular work around for the fact that unit tests require things to be output in English and can be limited to that.

**Comment by 6543** [comment]
@zeripath big thanks!

**Pull request closed without merging**
