### PR TITLE
reserve .well-known username

### PR DESCRIPTION
**Pull request by ashimokawa**
backport of #7637

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by zeripath** [comment]
I don't understand why but it appears that make swagger-generate and then commit the changes needs to performed.

**Comment by techknowlogick** [comment]
Upstream swagger has changed output which we resolved in 1.9 and master. As we are releasing 1.8 soon I’m not sure this needs a backport to 1.8

**Comment by sapk** [comment]
We will just need to indicate that we strongly suggest to update to 1.9 branch due to security bug that will not be fixed in 1.8. 
Or we can disable the swagger-check for 1.8 branch (to pass this PR) since it will not have any update later.

**Comment by techknowlogick** [comment]
@sapk I'm writing the changelog for 1.9.0 right now, so I'm going to close this PR.

**Pull request closed without merging**
