### PR TITLE
Update xorm to latest version

### PR DESCRIPTION
**Pull request by lafriks**
Update xorm to latest version to remove debug output from console that have been fixed upstream

### CODE REVIEW

**Comment by lunny** [comment]
@lafriks Thanks. But maybe you have to update `github.com/go-xorm/core` and `github.com/go-xorm/builder` too since they are the dependencies of `xorm`.

**Comment by lafriks** [comment]
xorm/core has not changed but updated also builder

**Comment by lunny** [comment]
LGTM

**Comment by sapk** [comment]
LGTM

**Pull request merged**
