### PR TITLE
Fix new pull request link

### LINKED ISSUE #3131: 404 when clicking "New pull request".
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (cannot provide link, since a link I provide would only work if you're authenticated as me. See steps for reproduction below.)
  - [ ] No
  - [ ] Not relevant

You can get a 404 by clicking the "New Pull Request" button. Steps to reproduce:
1. Create an org (call it `org1`)
2. Create a repo in `org1` (call it `org1/repo1`)
3. Fork `org1/repo1` to your user (`username/repo1`)
4. Add a branch to `org1/repo1` (call it `branchThatOnlyExistsUpstream`)
5. View the `branchThatOnlyExistsUpstream` of `org1/repo1`, and press the "New Pull Request" button

I will have a fix soon.

image

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #3131 and #3132. Now, clicking the "New request button" creates a pull request whose head is the currently-viewed branch (like Github does). The button is not shown when viewing a tag or commit.

### CODE REVIEW

**Comment by lunny** [comment]
If click on the baserepo?

**Comment by ethantkoenig** [comment]
@lunny I'm not sure what you're asking

**Comment by lafriks** [comment]
@ethantkoenig if you click on new pull request in base repository (to create PR between it's branches)

**Comment by ethantkoenig** [comment]
If you click on the button in the base repo, you'll create a PR from whatever branch you're currently looking at (in the base repo) to the default branch (presumably master) in the base repo.

**Comment by lafriks** [comment]
Tested and both cases seems to be working just as expected. LGTM

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Pull request merged**
