### PR TITLE
Allow change line of admin-dl-horizontal dt

### LINKED ISSUE #25389: Full config options are not visible in admin/config page
### Description

When you click on gitea's version you see /admin/config page. There, some long options are cut on display, however there's a lot of space to show the in full

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by HesterG**
Close #25389

After:

Screen Shot 2023-06-26 at 11 00 12

admin/dashboard:

Screen Shot 2023-06-26 at 10 59 51

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I do not think it's right .... actually, it should allow text breaking/wrapping.

**Comment by HesterG** [comment]
> I do not think it's right .... actually, it should allow text breaking/wrapping.

Removed ellipsis instead, and updated screenshots.

**Review by lunny — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Sorry, it's merged too fast ............

**Comment by wxiaoguang** [comment]
Please review this one

 Fix admin-dl-horizontal #25512

**Pull request merged**
