### PR TITLE
Tweak reaction buttons

### PR DESCRIPTION
**Pull request by silverwind**
Alternative to https://github.com/go-gitea/gitea/pull/11491.

- Vertical centering using flexbox
- Very slightly decreased size of the boxes

image

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Review by CirnoT — APPROVED** [review]
Looks good; the eyes reaction still looks off-center to me but that's just how it is made sadly

**Review by adelowo — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Comment by techknowlogick** [comment]
@silverwind please send backport :)

**Comment by lafriks** [comment]
Please send backport

**Pull request merged**
