### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by ethantkoenig**
`make lint` is failing in CI. See https://drone.gitea.io/go-gitea/gitea/693/5, for example.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by jonasfranz** [comment]
Could you add a backport to v1.2 too, since the CI test is failong too?

**Comment by lafriks** [comment]
LGTM

**Comment by jonasfranz** [comment]
@ethantkoenig Could you add a backport to v1.2 too, since the CI test is failong too?

**Pull request merged**
