### PR TITLE
add 'fonts' into 'KnownPublicEntries'

### LINKED ISSUE #15184: organization name url route conflict
Gitea version 1.13.6 built with GNU Make 4.1, go1.15.10 : bindata, sqlite, sqlite_unlock_notify

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] No
  - [ ] Yes (provide example URL)

## Description

Hello, it appears certain `organization names` can conflict with the built-in URL routes. If you create an organization named `fonts` for instance, and try to visit it, web server goes to limbo.

## Screenshots

image

### PR DESCRIPTION
**Pull request by a1012112796**
fix #15184

### CODE REVIEW

**Comment by a1012112796** [comment]
Proposal: add an root subtree like ``/_public/xxxx`` or ``/_static/xxx`` for static subtrees, then these simple words can be used as user name, Thanks.

**Comment by a1012112796** [comment]
I found ``favicon.ico`` is not a subtree in ``public`` tree, maybe should move it into ``reservedUsernames``

**Comment by silverwind** [comment]
> Proposal: add an root subtree like /_public/xxxx or /_static/xxx for static subtrees

I would call it "assets", probably with an additional invalid username character to prevent collision with existing usernames.

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
please backport to 1.14

**Comment by 6543** [comment]
Backport ->  #15317

**Pull request merged**
