### PR TITLE
Update JS dependencies, highlight.js 10.0.0

### PR DESCRIPTION
**Pull request by silverwind**
[Breaking changes in higlight.js](https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md) do not affect us.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
tested works

**Comment by 6543** [comment]
a question related to highlightjs: do we already use "Web Worker" mode ?

**Comment by silverwind** [comment]
Yes web worker is used since https://github.com/go-gitea/gitea/pull/11017.

Of note here. The changelog says IE11 no longer works but I believe this is not true in our case because we transpile. But I'll give it a test in that browser later.

**Review by sapk — APPROVED** [review]

**Comment by silverwind** [comment]
Gave it a go in IE11. Syntax highlighting is already broken on master in it and all it logs is

````
SCRIPT0: Syntax error
blob:70400007-61CE-4F5D-B229-6657B357E693 (1,1)
````

Adding `fallback: true` to `worker-loader` does not fix it, and neither does writing the worker script in ES5. I guess we can count it as "graceful degradation".

Anyways, I think this PR does not add new regressions, so should be good to go.

**Review by lafriks — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
Make lgtm work.

**Pull request merged**
