### PR TITLE
Make copy/paste work for source code

### LINKED ISSUE #12184: Copying text from source code view/diff view adds or removes newlines
- Gitea version (or commit ref): dbd5e4bb8d0f9d35e19549ecf0c9d8a1d5df167f
- Git version: `gitea:latest`
- Operating system: `gitea:latest`
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Copying selected chunk of text from source code/diff view either removes all newlines or produces additional ones when unnecessary. Removal happens on Chromium, while on Firefox newlines are added.

## Screenshots

https://try.gitea.io/L0veSunshine/drone-gitea-release/src/branch/master/Dockerfile.arm

Original:
chrome_2020-07-08_13-43-12

Firefox:
```
FROM plugins/base:multiarch

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \

  org.label-schema.name="Drone Gitea Release" \

  org.label-schema.vendor="Drone.IO Community" \

  org.label-schema.schema-version="1.0"

ADD release/linux/arm/drone-gitea-release /bin/

ENTRYPOINT [ "/bin/drone-gitea-release" ]
```

Chromium:
```
FROM plugins/base:multiarch
LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Gitea Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"
ADD release/linux/arm/drone-gitea-release /bin/
ENTRYPOINT [ "/bin/drone-gitea-release" ]
```

### PR DESCRIPTION
**Pull request by mrsdizzie**
Fix regression casued by #12047 so copy/paste works properly in all browsers.

Fixes #12184

Also while looking at this I saw a small display issue for blame view. I think #12023 was merged into original PR through an update branch before #12047 was merged and made one of the css rules not apply anymore.

Also fix existing and unrelated bug where copy/paste from PR diff would select the + symbol from add comment features

### CODE REVIEW

**Comment by silverwind** [comment]
Looking pretty good now. One thing I've noticed it that copying two or more lines out of a diff appends a trailing newline in both Firefox and Chrome. It does not do that on the file view, and I think that newline should ideally not be copied.

**Comment by mrsdizzie** [comment]
@silverwind will take a look

**Comment by mrsdizzie** [comment]
Actually can't reproduce the diff issue -- can you link to an example to copy?

**Comment by silverwind** [comment]
Any diff like https://try.gitea.io/silverwind/updates/commit/7c5b7c608d95fa85644c05d9a33355511a3ae492

Select at least two lines, copy them and paste them into an editor and you'll notice the cursor being on the line after the two lines.

image

**Comment by CirnoT** [comment]
Can't reproduce on this PR @silverwind

@mrsdizzie Copying from PR diff view where you have [+] buttons for code comment still copies the '+' character from it.

**Comment by mrsdizzie** [comment]
@CirnoT ah OK -- appears that it has always been like this for PR diff rather than a regression from recent changes. I'll try and fix it for this PR too since it should just be similar to regular diff

**Comment by silverwind** [comment]
Generally, adding `user-select: none` should make something like that `[+]` uncopyable.

**Comment by mrsdizzie** [comment]
@CirnoT should be fixed for PR diff -- seems ok in Firefox/Chrome from testing.

**Comment by silverwind** [comment]
Regarding the newline copying issue in diff, it seems to be because each line in the diff has a trailing newline which is not present on regular view lines. In regular file, there's no newline after the last chroma token (last `<span`):

````html
<code>  <span class="nt">"license"</span><span class="p">:</span> <span class="s2">"BSD-2-Clause"</span><span class="p">,</span></code>
````

but in diff view, there's a newline after it

````html
<span class="mono wrap">  <span class="s2">"license"</span><span class="err">:</span> <span class="s2">"BSD-2-Clause"</span><span class="err">,</span>
</span>
````

Can we chop it off maybe?

**Comment by mrsdizzie** [comment]
@silverwind I pushed a change to fix that if you can test -- I see the new lines in the source but don't experience the copy/paste issue so can't verify that it would fix it.

**Comment by CirnoT** [comment]
@mrsdizzie It works fine now, thanks.

**Comment by CirnoT** [comment]
Actually the newest commit broke newlines again, they're no longer present on copy.

**Comment by silverwind** [comment]
Copy/paste is now fixed for me. @CirnoT which newlines exactly?

**Comment by CirnoT** [comment]
Between lines obviously

**Comment by mrsdizzie** [comment]
ah ok I see sheesh sorry, will fix next commit

**Comment by silverwind** [comment]
I mean diff or code view, or both? It does seem to work fine here in Firefox 79 and Chrome 83.

**Comment by CirnoT** [comment]
```
## New features in version 2
--
  |   |   |  
  |   |   | - 500+ new supported file types
  |   |   | - Batch mode
  |   |   | - Scan only mode to determine file types without extracting
  |   |   | - Scan only mode to detect the type of any given file
  |   |   | - Built-in updater
  |   |   | - 100+ new supported file types
  |   |   | - Audio and video extraction for multimedia files
  |   |   | - Cascading context menu
  |   |   | - Support for password list for common archives
  |   |   | - Improved optional status box with progress indicator
  |   |   | - Improved context menu integration and status box
  |   |   | - Better and faster file analysis
  |   |   | - Support for some extractors not shipping with UniExtract as plugins
  |   |   | - Silent mode, not showing any prompts
  |   |   | - Many interface improvements and redesigned dialogs
  |   |   | - Resource usage/speed improvements, lots of fixes
  |   |   | - Auto-using 64 bit versions of extractors if supported by OS
  |   |   | - Resource usage/speed improvements, lots of bug fixes

```

Is what I get when I copy this:
chrome_2020-07-08_21-56-13

**Comment by CirnoT** [comment]
Copying it outside browser however produces this:
```
## New features in version 2
- 500+ new supported file types
- Batch mode
- Scan only mode to determine file types without extracting
- Scan only mode to detect the type of any given file
- Built-in updater
- 100+ new supported file types
- Audio and video extraction for multimedia files
- Cascading context menu
- Support for password list for common archives
- Improved optional status box with progress indicator
- Improved context menu integration and status box
- Better and faster file analysis
- Support for some extractors not shipping with UniExtract as plugins
- Silent mode, not showing any prompts
- Many interface improvements and redesigned dialogs
- Resource usage/speed improvements, lots of fixes
- Auto-using 64 bit versions of extractors if supported by OS
- Resource usage/speed improvements, lots of bug fixes
```

**Comment by silverwind** [comment]
I don't understand. Where do you paste to get these vertical lines?

**Comment by CirnoT** [comment]
Just here in GH textarea

**Comment by silverwind** [comment]
Indeed, I see very strange paste results when copy/pasting inside Firefox but it does work normally when I paste into an external editor, wtf.

**Comment by CirnoT** [comment]
What OS if I can ask @silverwind. Neither me nor @mrsdizzie can't reproduce your original report about stray newline at the end?

**Comment by silverwind** [comment]
Final newline issue was both in Windows and macOS, Firefox and Chrome. Thought in Chrome, not always.

**Comment by CirnoT** [comment]
Must be some GH feature; try it on any other site that has simple unmodified <textarea> element.

**Comment by CirnoT** [comment]
Windows here, could not reproduce on Chrome and Firefox alike.

**Comment by CirnoT** [comment]
I can reproduce it If i try, by which I mean specifically try to move cursor so that it catches empty element on next line by ending drag selection on line below. I wouldn't consider that a bug however?

**Comment by silverwind** [comment]
Yeah apparantly GH textarea does magic to break pasted text, nice. Try pasting into a pristine textarea like https://jsfiddle.net/silverwind/znpcLo4w/.

Not sure what else to tell you, I start selecton on bottom right of the line, move cursor to top left, hit copy and then paste.

Current version is LGTM.

**Comment by CirnoT** [comment]
No, the current version does not preserve empty newlines on diff view

**Comment by mrsdizzie** [comment]
@CirnoT I believe that last push should fix copying newline in diff again

**Comment by silverwind** [comment]
Ah right, I can see the empty newline issue too. Testing latest fix.

**Comment by silverwind** [comment]
Confirming everything working now for me.

**Comment by CirnoT** [comment]
Works fine now here too

**Review by CirnoT — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
