### PR TITLE
Better styling for code review comment textarea

### PR DESCRIPTION
**Pull request by CirnoT**
Before:
chrome_2020-05-15_23-23-04

After:
chrome_2020-05-16_15-42-13

### CODE REVIEW

**Comment by silverwind** [comment]
Can you align the left borders?

**Comment by silverwind** [comment]
I'm not sure if breaking the textarea's border with the tab is good idea. Maybe separate them with a small `.25rem` gap.

**Comment by CirnoT** [comment]
Looks weird with a gap in my opinion; the gap would make sense if textarea was styled like others however.

**Comment by CirnoT** [comment]
Aligned the textarea as you asked

**Comment by zeripath** [comment]
I think the border needs to go on the div.ui.active.tab not the textarea. I'm getting a weird appearing corner issue:

Screenshot from 2020-05-16 13-26-31

**Comment by CirnoT** [comment]
Please check now

chrome_2020-05-16_15-05-28

**Comment by zeripath** [comment]
That's better, thanks @CirnoT . Now should the corners have a radius ?

**Comment by CirnoT** [comment]
Pretty annoying because top corners can't be set (looks weird in `Preview` when only left is unset)

chrome_2020-05-16_15-33-35
chrome_2020-05-16_15-33-45

**Comment by CirnoT** [comment]
Okay, managed to fix the border edge case

chrome_2020-05-16_15-42-13
chrome_2020-05-16_15-42-44

**Review by zeripath — APPROVED** [review]
We need to sort out our border-radii in our less files... we have 3px, 6px, 4px, 5px, 50%, 100%, .28571429rem

Think we should set these to .28571429rem but otherwise LGTM

**Comment by CirnoT** [comment]
Changed to `.28571429rem` for consistency sake

**Review by mrsdizzie — APPROVED** [review]

**Pull request merged**
