### PR TITLE
Add fluid to ui container class to remove margin

### PR DESCRIPTION
**Pull request by stanthetiger**
While using a mobile device, there's an 14px margin on the signin and signup page that will create a horizontal scroll space. Adding "fluid" class to the ui container div element resolves the problem.

Another way to fix this is to modify the .ui.ui.ui.container:not(.fluid) css margin to 0px. Not sure which is the best way.

### CODE REVIEW

**Comment by lunny** [comment]
Could you give some screen shots before and after?

**Comment by stanthetiger** [comment]
> Could

A screenshot would not be able to show the issue. To see the issue you can browse to https://try.gitea.io/user/login on a mobile phone and see that there's a small horizontal scroll space that allows you to scroll horizontally on a mobile phone. It's a small annoyance that this PR fixes.

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rabbit:

**Comment by lafriks** [comment]
🚀

**Pull request merged**
