### PR TITLE
Modify linkRegex to require http|https

### PR DESCRIPTION
**Pull request by mrsdizzie**
Ugh sorry this is the same as #6153 which I broke by deleting my branch (which github didn't like)

Anyway, this is the same request to modify linkRegex so it only matches text starting with http|https when creating links. I've also added the requested tests for this to the current test suite as well.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
I'm going to approve, as leaving the broken autolinker for www.* in is of no use whatsoever.

**Comment by lunny** [comment]
Is this a break change?

**Comment by zeripath** [comment]
Well the current situation is that the auto links to say www.google.com just don't work and have never worked.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
So this should be back port to release/v1.7

**Comment by lunny** [comment]
Please send back port to release/v1.7

**Pull request merged**
