### PR TITLE
Only update mirror last update after successful sync

### LINKED ISSUE #2535: Incorrect last updated time of mirrors after save settings
- Gitea version (or commit ref): 93f8157
- Git version: 2.7.4
- Operating system: Windows
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) settings page in any mirror repository
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Save settings in 'mirror' section updates mirror's last updated time despite not doing a real repository sync.

### PR DESCRIPTION
**Pull request by cez81**
Fix #2535

Last updated was set every time the mirror object was updated. Change so that it's only updated after a successful sync.

### CODE REVIEW

**Comment by pgaskin** [comment]
Trusted LGTM, but a question: what is considered a successful sync? When a commit is added? When git returns no errors? Something else?

**Comment by lafriks** [comment]
LGTM - @geek1011 successful sync is when sync ends without errors (even if there was nothing new)

**Comment by cez81** [comment]
@geek1011 I have another issue concerning mirror last updated times, https://github.com/go-gitea/gitea/issues/1329. Will have look at that next.

**Comment by lafriks** [comment]
Make LG-TM work again

**Pull request merged**
