### PR TITLE
[doctor] authorized-keys: fix displayed check name

### PR DESCRIPTION
**Pull request by pilou-**
The registered check name is `authorized-keys`, not `authorized_keys`:
```
$ ./gitea-1.16.5-linux-amd64 --config /etc/gitea/gitea.ini --work-path /srv/gitea doctor --all
[...]
[6] Check if OpenSSH authorized_keys file is up-to-date
 - [C] authorized_keys file "/srv/gitea/.ssh/authorized_keys" is out of date.
	Regenerate it with:
		"gitea admin regenerate keys"
	or
		"gitea doctor --run authorized_keys --fix"
ERROR
[...]
$ gitea-1.16.5-linux-amd64 --config /etc/gitea/gitea.ini --work-path /srv/gitea doctor --run authorized_keys --fix # nothing is done
$ gitea-1.16.5-linux-amd64 --config /etc/gitea/gitea.ini --work-path /srv/gitea doctor --run authorized-keys --fix
[1] Check if OpenSSH authorized_keys file is up-to-date
 - [W] authorized_keys is out of date. Attempting rewrite...
[...]
OK
```

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
might be helpful to make the doctor make "_" and "-" synonymic

**Review by wxiaoguang — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by 6543** [comment]
@pilou- if you like to backport ... feel free to do so

**Comment by pilou-** [comment]
> @pilou- if you like to backport ... feel free to do so

#19484

**Pull request merged**
