### PR TITLE
Clarify Indexer MAX_FILE_SIZE (#3469)

### PR DESCRIPTION
**Pull request by cez81**
Backport of #3469

### CODE REVIEW

**Review by sapk — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by cez81** [comment]
Tried force push but still fails on tests (not related to the change).

**Comment by lafriks** [comment]
@cez81 something has broke in 1.4 branch tests that is already merged :(

**Comment by cez81** [comment]
Make LG-TM work

**Comment by cez81** [comment]
@lafriks This is good to go now :)

**Pull request merged**
