### PR TITLE
update to mermaid v10

### LINKED ISSUE #23153: Update Mermaid to version 10.0.0 for mindmap features
### Feature Description

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
```

```mermaid
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectivness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by techknowlogick**
fix #23153

### CODE REVIEW

**Comment by delvh** [comment]
> ERROR in License: elkjs@0.8.2 has disallowed license EPL-2.0

Hmm…

**Comment by silverwind** [comment]
If the lincense is okay, add it to the array in the webpack config.

Changelog [here](https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0). The module has switched from CJS to ESM, it may be necessary to change how we import it, the [`default` export](https://github.com/go-gitea/gitea/blob/067b0c2664d127c552ccdfd264257caca4907a77/web_src/js/markup/mermaid.js#L24) is a crutch for CJS that is probably no longer necessary.

**Comment by delvh** [comment]
The problem is:
If I've seen it correctly, this license **isn't** compatible.
It would require every user to use the EPL2 or a related license as well.
MIT doesn't have this restriction, so they should be incompatible.

**Comment by delvh** [comment]
Actually, this should be a problem on Mermaid's side, since they are violating their own license with that package.
Or is my superficial license knowledge wrong about that?

**Comment by silverwind** [comment]
I think generally most open source software does not take license violations seriously, so I think we may have to follow suit and just relax the (currently strict) validation.

**Comment by lunny** [comment]
> Most open source software does not seem to take license violations seriously, so I think we may have to follow suit and just relax the (currently strict) validation, or add an `override` for this module.

But that may break those company users who care about this. Before this change, they could choose not to open source their special code.

**Comment by silverwind** [comment]
> Actually, this should be a problem on Mermaid's side, since they are violating their own license with that package

Do you know which part of [that license](https://github.com/kieler/elkjs/blob/master/LICENSE.md) is violated?

**Comment by silverwind** [comment]
If I read [Wikipedia](https://en.wikipedia.org/wiki/Eclipse_Public_License) correctly, it's not actually viral of you just depend on it:

> Linking to code (for example to a library) licensed under EPL automatically does not mean that your program is a derivative work. Eclipse Foundation interprets the term "derivative work" in a way that is consistent with the definition in the U.S. Copyright Act, as applicable to computer software.[[12]](https://en.wikipedia.org/wiki/Eclipse_Public_License#cite_note-12)

So I think we can just allow it in the SPDX expression in webpack.

**Comment by delvh** [comment]
Yep, right.
If we modified the code, we would need to be EPL as well.
Simply using it should not be derivative work then.

**Comment by wxiaoguang** [comment]
> > Actually, this should be a problem on Mermaid's side, since they are violating their own license with that package
> 
> Do you know which part of [that license](https://github.com/kieler/elkjs/blob/master/LICENSE.md) is violated?
> 
> I think this license qualifies as a viral one, similar to GPL, is this the issue?

```
3.1 If a Contributor Distributes the Program in any form, then:
    a) the Program must also be made available as Source Code
```

If EPL is included, does it mean that all downstream Gitea users have to make their own-built Gitea open-source?

**Comment by silverwind** [comment]
I don't think "running" a program qualifies as "distributing".

**Comment by silverwind** [comment]
I adapted to [v10 API changes](https://github.com/mermaid-js/mermaid/blob/master/CHANGELOG.md#1000), should be fully working now.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
