### PR TITLE
Fix JS error when edit project column twice and fix empty column title

### PR DESCRIPTION
**Pull request by yp05327**
Reproduce:
- click edit project column
- click confirm
- click edit project column again

image

And fix column title will be changed if the input is empty

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Should this be backport?

**Comment by yp05327** [comment]
Not sure which PR caused this issue.
Tested in 1.22.0-rc1, it works.

**Comment by silverwind** [comment]
Odd. I can't imagine https://github.com/go-gitea/gitea/pull/30723 having caused this which is the only possible related commit not on the branch.

**Review by wxiaoguang — COMMENTED** [review]
This fix doesn't seem complete.

The root problem is that all modals are destroyed.

https://github.com/go-gitea/gitea/pull/30723/files#r1587350910

image

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
need a proper fix

**Comment by wxiaoguang** [comment]
-> https://github.com/go-gitea/gitea/pull/30831/files#r1587965477

**Comment by silverwind** [comment]
Better fix in https://github.com/go-gitea/gitea/pull/30831

**Pull request closed without merging**
