### PR TITLE
Add v3.18 to TestPackageAlpine

### PR DESCRIPTION
**Pull request by sonjek**
Add Alpine 3.18 to TestPackageAlpine

### CODE REVIEW

**Comment by silverwind** [comment]
Can you explain what this test does with these alpine versions?

**Comment by sonjek** [comment]
This test verifies the ability to push a package for the specified version of Alpine, checks the correctness of filling in all the data, and performs package removal.

This test verifies the ability to push a package for the specified version of Alpine, checks the correctness of filling in all the data, and performs package removal. Alpine 3.18 is a last one stable version. Currently, Gitea is using Alpine version 3.18, so it is valid to also test it accordingly.

**Review by yardenshoham — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by KN4CK3R** [comment]
This PR is useless. The different versions in the test are only needed to... test different versions. The name could be `dummy-123` and it would still work.

**Comment by silverwind** [comment]
Okay, let's keep that in mind and not accept any further updates to that list.

**Comment by sonjek** [comment]
Got it @KN4CK3R. Thank you for explanation.

**Pull request merged**
