### PR TITLE
Add missing forks key for dashboard repository component

### PR DESCRIPTION
**Pull request by lafriks**
Missing key that is used in #2285

### CODE REVIEW

**Comment by appleboy** [comment]
@lafriks Please don't push your branch to Gitea repo since it will trigger push event in Drone. Otherwise LGTM

**Review by appleboy — APPROVED** [review]

**Comment by lafriks** [comment]
@appleboy it was by accident. When editing from github web it was creating new branch in my forked repository previously but now that I'm member on gitea org it seams to create branch in gitea repo :(

**Comment by appleboy** [comment]
@lafriks Yes. so I don't try to edit the file from GitHub web. :)

**Comment by lunny** [comment]
@lafriks there was already `forks` key in line 480.

**Comment by lafriks** [comment]
@lunny but it is in different scope (`forks` as used for tab in component vs `repo.forks` - key that already exists and used for page header in forks page)

**Comment by lunny** [comment]
LGTM

**Pull request merged**
