### PR TITLE
Fix bound address/port for caddy's certmagic library

### PR DESCRIPTION
**Pull request by bminer**
My apologies for the confusion.  This PR fixes a bug introduced in #15848 and (I believe) solves the underlying issue this time around.

### CODE REVIEW

**Comment by techknowlogick** [comment]
In fact this might be my bad, I suspect the `ManageSync` may be the culprit. I wonder if LE would work without that call.

**Review by zeripath — APPROVED** [review]

**Comment by bminer** [comment]
> In fact this might be my bad, I suspect the `ManageSync` may be the culprit. I wonder if LE would work without that call.

That is an excellent question. I suspect that `ManageSync` is not necessary based on the [example shown here](https://pkg.go.dev/github.com/caddyserver/certmagic#readme-advanced-use).

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
make LGTM work

**Comment by zeripath** [comment]
Please send backport

**Pull request merged**
