### PR TITLE
Localize numbers server-side (maintainers' opinion requested)

### PR DESCRIPTION
**Pull request by yardenshoham**
This one started when I encountered #12637. I wrote `RenderNumber` in https://github.com/go-gitea/gitea/commit/b9319f9a46d2b1a6fe549ec12971fa38315bfea6 to format the number of commits, then I thought "Why not format all other numbers in a nice way?". So I did it in https://github.com/go-gitea/gitea/commit/c929ad212f962204fd6ac2b690bae58047a0d5f0.

While running a search for numbers in templates I encountered `JsPrettyNumber` and `CountFmt`. `JsPrettyNumber` seems to localize the numbers client-side (therefore with a "flash of unstyled content") and `CountFmt` does it server-side disregarding the user's locale. So this PR can go a few ways:
1. Land `RenderNumber` + use it in the places of https://github.com/go-gitea/gitea/commit/c929ad212f962204fd6ac2b690bae58047a0d5f0 (current PR state)
2. Do 1 + refactor the codebase to use only `RenderNumber` and drop `JsPrettyNumber` and `CountFmt`
3. Drop everything I did and just use `JsPrettyNumber` for number of commits

What do you prefer?

### CODE REVIEW

**Comment by delvh** [comment]
I don't think we can drop `CountFmt` as that suffixes with `k`/ `M`/ `G`, and I don't want to have for example `7,654,321B` instead of `7,6MB` but perfectly localized.
Then, in favor of pure JS side rendering is that it knows best how to format a number for the user.
Against the JS solution speaks especially that it needs JS, and a bit of frontend time, which is especially bad for users with bad hardware or users that disable JS.

Hmm, I don't think that is a strong enough argument not to push the work to the frontend.
So I'm probably in favor of rendering all numbers (where possible) in the frontend.

**Comment by yardenshoham** [comment]
Thanks @delvh, look like a vote for option 3

**Comment by lunny** [comment]
The frontend language should not always follow web browser, it's a default option. And users could set their prefer language which maybe different from web browser. And for a more complicated example, users' prefer location and language should become two options, but I think we currently can hold only one.

**Comment by 6543** [comment]
I think that's a frontend concern and should be in JS code ...

**Comment by yardenshoham** [comment]
Option 3 decided then, thank you all

**Comment by yardenshoham** [comment]
Continued in #21786

**Comment by 6543** [comment]
still thanks :heart:

**Pull request closed without merging**
