### PR TITLE
Move `generate-images` dependencies to package.json

### LINKED ISSUE #30685: Reproducible builds and strict dependency verification
### Description

Gitea build process [was found](https://github.com/go-gitea/gitea/issues/30596#issuecomment-2075483451) not reproducible. Please force strict verification against committed checksums for every dependency to avoid surprises and to better protect against supply chain attacks.

`npi ci` [should](https://stackoverflow.com/a/53325242) probably be used instead `npm install` and break install process if any checksum mismatch occurs. Same for go modules (if works different now).

Related: https://github.com/go-gitea/gitea/issues/29326#issuecomment-1960365704

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Compiled from sources.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/30685

I consider it fixed because `npm i --no-save` with lockfile should be fully reproducible, faster and have less bugs than `npm ci`, unless someone proves me wrong.

### CODE REVIEW

**Comment by pboguslawski** [comment]
According to [the npm manual](https://docs.npmjs.com/cli/v10/commands/npm-install) `--no-save` only prevents saving to `dependencies` (doesn't say nothing about installation of versions locked with checksums). So it's not designed for reproducible builds problably. See [more](https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci) opinions about using `npm ci` for reliable builds.

**Comment by silverwind** [comment]
The important part of `no-save` is "Will also prevent writing to package-lock.json if set to false.", so it will reproduce a `node_modules` a bit less strict than `npm ci` but it's not a issue because we [validate our lockfile is consistent](https://github.com/go-gitea/gitea/blob/a19d2bbd90dd22a897220425a1221af8ed065ba7/Makefile#L930-L939) on CI.

**Comment by silverwind** [comment]
That said, I'm leaving it open for the future to run `npm ci` for example when `build` is in `MAKECMDGOALS`, which would kind of be an extra reinforcement during the build.

**Comment by silverwind** [comment]
On topic of this PR, I'm still unsure if it's really worth the trouble to expose us to build failures of the `canvas` module. https://github.com/go-gitea/gitea/issues/30596#issuecomment-2075483451 says removing `--no-package-lock` solved the issue and we have that already removed on main branch since a while, so I think I'm leaning towards leaving it at that and closing this PR.

**Comment by silverwind** [comment]
Closing, I'll take another approach with separate lockfile.

**Pull request closed without merging**
