### PR TITLE
Fix always-on SSL Mode checkbox in admin page

### LINKED ISSUE #3207: SSL Mode showed as ON while instead is OFF
As of bdf18560110ac642c196054be38729760a4bbc39 (1.3.0-dev) installed locally, the `/admin/config` page under the ` Database Configuration ` section has `SSL Mode` checkbox checked, but custom/config/app.ini has `SSL_MODE = disable` under the `[database]` section (and would not work otherwise, because my server does not support SSL.

### PR DESCRIPTION
**Pull request by strk**
Closes #3207

Needs backport to 1.3 branch too

### CODE REVIEW

**Comment by strk** [comment]
Actually the supported values are:
> only "require" (default), "verify-full", "verify-ca", and "disable" supported

So a checkbox is really not a good idea!

**Comment by ethantkoenig** [comment]
Since this is a UI change (albeit a minor one), could you please include before/after screenshots?

**Comment by lafriks** [comment]
LGTM

**Comment by strk** [comment]
Screenshot is not much interesting, imagine a string like the one you get for `Path` instead of a checkbox. It takes too much time for me to create the screenshot(s) and blur out the passwords etc. And you should review the code, not trust screenshots :)

**Comment by strk** [comment]
Found the time: this is _after_:
selection_002

**Comment by ethantkoenig** [comment]
LGTM @strk with hindsight, screenshot was probably not necessary, my apologies

**Pull request merged**
