### PR TITLE
Fix double border introduced by #13434

### PR DESCRIPTION
**Pull request by CirnoT**
Quick fix for #13434 introducing double border on certain elements.

### Before:
chrome_2020-11-07_17-12-55
chrome_2020-11-07_17-13-58
chrome_2020-11-07_17-12-12

---

### After:
chrome_2020-11-07_17-10-14
chrome_2020-11-07_17-10-31
chrome_2020-11-07_17-10-46

### CODE REVIEW

**Comment by CirnoT** [comment]
Would like @silverwind to check this out before merging.

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Looks good. 

There are some minor issue with the triangles on the left side of the header I just noticed, maybe you can fix those too while you're at it:

Background too bright:
image

Triangle not centered:
image

**Comment by CirnoT** [comment]
Outside of scope for this PR really, there are more places where these triangles are off-centered or broken (often in color or positioning).

**Comment by silverwind** [comment]
Hmm yeah, can check that separately.

**Review by silverwind — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
