### PR TITLE
When Administrator is logged in it should be visual different from normal user

### PR DESCRIPTION
**Pull request by xor-gate**
This feature enables visual appareance when the logged in user has administrator rights. It colors the toplevel navigation bar red.

See https://github.com/go-gitea/gitea/issues/32885 for discussion

### CODE REVIEW

**Comment by lunny** [comment]
Style is not allowed for the change.

**Comment by wxiaoguang** [comment]
Gitea doesn't use inline-styles.

So either add a new CSS class name, or use `tw-xxx` and existing  color helpers.

**Comment by xor-gate** [comment]
Thanks for the feedback, I normally don't do frontend. But I agree with both of you. Need to figure out what CSS classes are available and what needs to be added. I'm running my dev-env on FreeBSD but could not get the frontend to build with node22, i used prebuild frontend from nightly.

What do you think by putting this behaviour behind a config option, or making it default? Then I also need some backend work to be investigated and implemented. Some people will not going to like this when it is not configurable. But its a matter of taste.

**Comment by wxiaoguang** [comment]
Before making more changes, I think we need to figure how to make the UI overall look good.

To be honest, such color pattern doesn't look to me .... somewhat ugly.

Could you share how other softwares do? What's their color palette?

And maybe @silverwind  could have some ideas.


image

**Comment by silverwind** [comment]
I don't think this is needed and just coloring red is far too crude. Admin can see whether they are admin by opening the user menu where "Site Administration" will be present.

**Comment by wxiaoguang** [comment]
> Admin can see whether they are admin by opening the user menu where "Site Administration" will be present.

It doesn't resolve user's problem.

The real requirement is to make the "admin UI" more eye-catching to make sure admin users could know they are using an admin account, to avoid making some over-permission operations in unrelated repositories.

> Only other idea is to overlay a cog icon over the user avatar on top right.

It's better to have some more eye-catching UI differences.

**Comment by silverwind** [comment]
> It's better to have some more eye-catching UI differences.

I disagree. It seems over the top and unprofessional to do things like color the navbar.

**Comment by xor-gate** [comment]
> > It's better to have some more eye-catching UI differences.
> 
> I disagree. It seems over the top and unprofessional to do things like color the navbar.

It was just a draft after comment from @lunny in the ticket. I would prefer a small bar above the navbar with color and text "Logged in as Site Administrator". After discussing and showing this, the navbar color is also ugly compared to the other UI elements. I'm no UI or frontend expert, but it should feel and look nice.

**Comment by xor-gate** [comment]
Something like this (AI generated):

image

> Could you share how other softwares do? What's their color palette?

Unfortunatly I have no example from other software (yet)

**Comment by silverwind** [comment]
The only thing I can accept is a small cog overlay over the avatar. Cog is a common iconology to display admin status: https://www.google.com/search?q=administrator+icon. E.g. like this:

```
      -----
------| c | 
|     -----
|   u   |
|       |
---------
```

The relevant CSS can be copied from the notification icon's blue dot.

**Comment by xor-gate** [comment]
Okay so there is no general consensus. Then we leave it as-is.

**Comment by lunny** [comment]
> I don't think this is needed and just coloring red is far too crude. Admin can see whether they are admin by opening the user menu where "Site Administration" will be present.
> 
> 
> 
> Only other idea is to overlay a cog icon over the user avatar on top right.

This is the same as my second idea in the original issue.

**Comment by wxiaoguang** [comment]
->  Improve navbar: add "admin" tip, add "active" style #32927

**Comment by xor-gate** [comment]
@wxiaoguang you are an UI expert, this is much better then coloring the navbar. That felt not very natural, but was only be done to discus the idea. Thanks for considering this feature request! Up to v1.24.0 🚀  and beyond the stars.

**Pull request closed without merging**
