### PR TITLE
Add all `no-query` rules to eslint config

### PR DESCRIPTION
**Pull request by silverwind**
Add rules of `no-jquery` rules to the config and enable all non-violating ones.

### CODE REVIEW

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
After this, I think I will start with some rule enablement and refactoring, likely starting with `ajax` stuff that will be replaced with `fetch`.

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
.

**Comment by yardenshoham** [comment]
image

**Comment by silverwind** [comment]
.

**Pull request merged**
