### PR TITLE
Clean less files

### PR DESCRIPTION
**Pull request by xf-**
- replace tabs with spaces
- remove unit from 0 values
- add empty lines between selectors
- split important with a space in all occurrences
- combine margin: 0 with margin-top, -bottom, left, right to one line.

(And maybe add a linter afterwards, new code is more unified, easier to understand)

### CODE REVIEW

**Comment by techknowlogick** [comment]
I think some of the empty lines were removed in a recent PR by @lafriks

**Comment by xf-** [comment]
@techknowlogick this is most common usage. easy to find a selector. 

No empty lines if no selector/ attribute is in between. eg.
```
  }
}
```

i try to get an linter into lessc - it has an plugin (i mostly use sass and a gulp build pipeline). Source map is the next goal. Is only loaded if Development console is open

**Comment by techknowlogick** [comment]
Sounds good. If you could get that linter in here as well that'd be awesome.

Thanks for all your contributions recently.

**Comment by lafriks** [comment]
@techknowlogick nope, I also added some newlines :) But only in one file that I was changing

**Comment by techknowlogick** [comment]
@lafriks ah ok. I just remembered something about empty lines. Thanks for clarification.

**Review by zeripath — APPROVED** [review]

**Review by adelowo — APPROVED** [review]

**Pull request merged**
