### PR TITLE
Disable arm7 builds

### PR DESCRIPTION
**Pull request by techknowlogick**
As arm6 works on arm7 platforms with no noticeable performance difference

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Such a pity we're not able to work this one out. Hopefully we'll be able to fix this in future.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Please send backport

**Comment by Beluk** [comment]
Without arm7 i am not able to run it on my Synology anymore with a newer Version :-(

**Comment by zeripath** [comment]
does arm6 not work for you?

**Comment by Beluk** [comment]
Unfortunately not. Tried to build a new package for my Synology with this package:
https://github.com/flipswitchingmonkey/gitea-spk 
I was always fine with arm7, but with one of the last version arm7 did not work anymore. I read about arm6 would being an alternative. I tried it with the script. First it did not accept. I changed the build script to accept also arm6. But on my Synology it did not start. Not sure what the problem is exactly but i gave up after several hours of try and hoped it will be solved in one of the future releases of gitea.

The german guides i used for Synology running Gitea are:
https://www.ipod-infos.de/gitea-auf-einer-synology-ds918-installieren/
https://canox.net/2017/12/gitea-auf-einer-synology-diskstation/

**Comment by techknowlogick** [comment]
@Beluk do the current arm7 builds work for you?

**Comment by Beluk** [comment]
The last one i tried was:
https://github.com/go-gitea/gitea/releases/download/v1.8.0/gitea-1.8.0-linux-arm-7
and this one did not worked. Did you change something on 1.8.1?

**Comment by zeripath** [comment]
@Beluk yeah there's been a problem with our static arm7 builds that has forced us to have to stop providing them. If you're able to cross-compile non-static arm7 builds do work.

**Comment by Beluk** [comment]
Thanks for the hint. I will give it a try...

**Comment by IzzySoft** [comment]
Will arm7 support return, or is this final?

**Comment by lunny** [comment]
It will return. This is a temporary disable.

**Comment by IzzySoft** [comment]
Thanks, @lunny! Besides: The last two available ARMv7 (1.8.0 and 1.8.1) seem broken as well (which of course could be "only me"). The latest one working for me is 1.7.5. But indeed, the ARMv6 binaries do work on my BananaPi, so until working ARMv7 return I'll stick to those (currently running v1.8.3 that way).

**Comment by funkythings** [comment]
> binaries do work on my BananaPi, so until working ARMv7 return I'll stick to those (currently running v1.8.3 that way).

Are you using docker for that? 

Is there a way to force the docker image to use armv6, until armv7 is officially supported again?

**Comment by IzzySoft** [comment]
@funkythings why should I use docker to run a simple binary? No, the BananaPi is running Armbian, and I simply drop in the binary. I've never worked with docker, to be honest.

**Comment by funkythings** [comment]
once you have multiple services running with docker already, one more doesn't hurt.

**Comment by techknowlogick** [comment]
This PR is in regards to the binaries, not the docker container. For general discussion please don't use PRs as hundreds of people get these emails.

**Pull request merged**
