### PR TITLE
Change webhook-type in create-view

### PR DESCRIPTION
**Pull request by zokkis**
It's now possible to change webhook-type in create-view.

before:
image

after:
image

### CODE REVIEW

**Comment by silverwind** [comment]
Pushed some styling fixes and fixed the regression with the SVGs. We need to render the matrix icon as `<svg>`, because only with that the color will be changed to white on dark theme because if `fill: currentcolor`. I also removed the `Class` option because we can easily vertically center with flexbox from the parent instead and because `vertical-align: middle`should not be used for vertical centering because it does not work in all cases.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
It's a inherited value from the fomantic-ui dependency. They have some calculations ongoing and a lot of their margin/padding etc are based on these Sass calculations:

https://github.com/fomantic/Fomantic-UI/blob/6daf34d16395f8aa9b964719095c775fc8e4e95b/src/themes/default/globals/site.variables#L219

E.g. 11 / 14 = 0.785714285714286

**Review by a1012112796 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Maybe a regression, invalid link:

image

**Comment by wxiaoguang** [comment]
Opened a new issue to track:  Incorrect menu/link on webhook edit page #29699

**Pull request merged**
