### PR TITLE
Always use `user/branch` for source branch display in PR

### LINKED ISSUE #20408: Source branch reference should probably be `user/repo`
### Feature Description

There seem to be various ways that systems refer to the source branch of a PR:

- `user/repo:branch` is used by gitea
- `user:branch` is used by github
- `user/branch` is used by gitlab and in git cli (if remote name is user name)

I'd argue we should go with the format of `user/branch`, because it lends itself for copy-paste with git cli when  remote name equals username, where one can do `git checkout -t user/branch`. Anyone agree?

### Screenshots

image

### PR DESCRIPTION
**Pull request by silverwind**
Before:

image

After:
image

Fixes: https://github.com/go-gitea/gitea/issues/20408

### CODE REVIEW

**Review by yardenshoham — CHANGES_REQUESTED** [review]
Maybe `:` instead of `/` to match GitHub?

**Comment by silverwind** [comment]
> Maybe `:` instead of `/` to match GitHub?

As mentioned [here](https://github.com/go-gitea/gitea/issues/20408#issuecomment-1488073959), I believe `/` is superior because that's what `git` cli accepts. `:` is not useful on git cli. Gitlab also uses the `/` separator, so I believe the `:` is a GitHub-specific quirk.

**Comment by silverwind** [comment]
There is more discussion in https://github.com/go-gitea/gitea/issues/20408. Current format is useful for gitea UI, the format in this PR is useful with `git` cli. I'm wondering if we should maybe support both cases with a second copy button specific for `git` cli maybe.

**Comment by lunny** [comment]
> There is more discussion in #20408. Current format is useful for gitea UI, the format in this PR is useful with `git` cli. I'm wondering if we should maybe support both cases with a second copy button specific for `git` cli maybe, or just prefer git cli, which matches gitlab.

But we already have command line hint although it's at the end of the page.

**Comment by silverwind** [comment]
> But we already have command line hint although it's at the end of the page.

Those instructions do not match [my workflow](https://github.com/go-gitea/gitea/issues/20408#issuecomment-1487977935) unfortunately.

**Comment by silverwind** [comment]
Think we'll try another approach by improving the PR instructions.

**Pull request closed without merging**
