### PR TITLE
Enable GO111MODULE=on globally in Makefile

### PR DESCRIPTION
**Pull request by mrsdizzie**
Now that our minimum required go version is 1.12 we can remove code that disables GO111MODULE globally and turn it on, so each command doesn't need it set specifically.

Also fixes a small bug with make pr that didn't work because GO111MODULE=on wasn't set

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
```
go run -mod=vendor github.com/go-swagger/go-swagger/cmd/swagger generate
```
is no failing because of this

**Comment by mrsdizzie** [comment]
This is actually failing because with GO111MODULE=on it tries to vendor the tools we download with go get (revive in this case). Will get fixed in another PR

**Review by lunny — APPROVED** [review]
Approved if CI PASS

**Review by jolheiser — APPROVED** [review]
Approved, waiting on #10942

**Comment by guillep2k** [comment]
```
+ make coverage
go: cloud.google.com/go@v0.45.0: module lookup disabled by GOPROXY=off
make: *** [Makefile:296: coverage] Error 1
```

🙁

**Comment by mrsdizzie** [comment]
@guillep2k waiting on https://github.com/go-gitea/gitea/pull/10947 for that

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
