### PR TITLE
Add integration test for issue creating

### PR DESCRIPTION
**Pull request by typeless**

### CODE REVIEW

**Comment by ethantkoenig** [comment]
Would it be possible to check that the issue was actually created? (by `models.AssertExistsAndLoadBean(..)`, or if that's not possible by making a GET request to view it)

**Comment by ethantkoenig** [comment]
@typeless Also, thank you for adding integration tests! I appreciate your willingness to do unglamorous-but-important tasks like writing tests.

**Comment by typeless** [comment]
@ethantkoenig I have added a GET request to check the existence of the issue page. And I don't quite understand how `AssertExistsAndLoadBean` is used here.

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
