### PR TITLE
Fix slice out of bounds error in mailer

### LINKED ISSUE #2472: Testmail produces 500 Internal Server Error
- Gitea version (or commit ref): 1.2.0+rc2
- Git version: 2.11.0
- Operating system: Ubuntu 17.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/davidmehren/447b7a8f265e79927a2e264ea8abbb41

## Description
When trying to send a test mail via the admin interface (`/admin/config` which uses `/admin/config/test_mail`), Gitea responds with a 500 Internal Server Error.
I'm not an expert in Go, but I believe this is because the testmail body from https://github.com/go-gitea/gitea/blob/95c408ffa593efa781442a46394cadb0e401d2da/models/mail.go#L43 is not 100 characters long and so the array slice operation in https://github.com/go-gitea/gitea/blob/95c408ffa593efa781442a46394cadb0e401d2da/modules/mailer/mailer.go#L44 fails.
You can find the stacktrace in the log gist.

### PR DESCRIPTION
**Pull request by cez81**
Fix #2472 by using TruncateString() instead of just slicing and hoping for the best.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lunny** [comment]
@cez81 please rebase

**Comment by cez81** [comment]
@lunny Rebase done

**Pull request merged**
