### PR TITLE
Refactor Milestone related

### PR DESCRIPTION
**Pull request by 6543**
as title

moved from #10148 to have a smaler diff for it

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]

**Comment by 6543** [comment]
ping lgtm - it now need only 1 lgtm

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Comment by techknowlogick** [comment]
@6543 please update to latest master, or check allow edits from maintainers.

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
