### PR TITLE
Remove fomantic checkbox module (#30162)

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #30162 by @silverwind

CSS is pretty slim already and the `.ui.toggle.checkbox` sliders on admin page also still work. The only necessary JS is the one that links `input` and `label` so that it can be toggled via label. All checkboxes except the markdown ones render at `--checkbox-size: 16px` now.

Screenshot 2024-03-28 at 22 15 10

Screenshot 2024-03-28 at 21 00 07

Screenshot 2024-03-28 at 22 14 34

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I would suggest to re-consider it: https://github.com/go-gitea/gitea/pull/30165#issuecomment-2026753913

**Comment by lunny** [comment]
per https://github.com/go-gitea/gitea/pull/30165#issuecomment-2026793610

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
I think this is a neccesary enhancement 😆.

**Review by wxiaoguang — APPROVED** [review]
rc1 should be a real RC -- stable, only fix bugs

**Comment by silverwind** [comment]
I will give it another special round of testing before merging this.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Can't find anything wrong, let's merge.

**Comment by silverwind** [comment]
@techknowlogick can you adjus the "required checks" config for `release/v1.22` branch so that `test-mysql5` and `test-mysql8` are removed and `test-mysql` is added?

**Comment by lunny** [comment]
> @techknowlogick can you adjus the "required checks" config for `release/v1.22` branch so that `test-mysql5` and `test-mysql8` are removed and `test-mysql` is added?

Done.

**Pull request merged**
