### PR TITLE
[Discusion] Localize Commit Message for PullRequest Update

### PR DESCRIPTION
**Pull request by 6543**
come up in #9784

question is Yes/No

### CODE REVIEW

**Comment by 6543** [comment]
I personaly dont like to localice ... reason:

Lunny has set the gitea language to: Chinese ...
Lafriks to Latvian ...
Me to German ...

If we update a branch no one knows what is going on!!! 

think thats why github use englisch only for the update function too

**Comment by guillep2k** [comment]
We solved this problem for other resources (like `WIP`, `closes`, `fixes`, etc.) by setting up a value in `app.ini`, so site admins can tailor it to a better suited language in their case. Ultimately, these options should also be configurable per repo or per repo-owner, but site-wide is more than enough for now.

I agree that this is not a job for Crowdin.

**Comment by 6543** [comment]
@guillep2k I'm for a repo setting

**Comment by lunny** [comment]
A per repository setting maybe better.

**Comment by lafriks** [comment]
It can be app.ini setting as default and changeable by org/repo settings

**Comment by guillep2k** [comment]
Let's vote:

- `app.ini`: 👍
- by repository, default in `app.ini`: 😄 
- by repository owner (e.g. all of go-gitea), default in `app.ini`: 👀
- Via Crowdin: 🚀  
- Nothing at all: 👎

**Comment by lafriks** [comment]
@guillep2k it can be both changeable in org settings and per-repo

**Comment by davidsvantesson** [comment]
I would suggest .md files in the repository (like the PR template)
That is something I have though about also for the PR merge commit message.

**Comment by lafriks** [comment]
@davidsvantesson not current user but repo owner

**Comment by davidsvantesson** [comment]
That would only work for user repos? Would you add a language for organizations as well?
I think many would not want their commit messages translated just because they choosed to have the UI in a specific language. Many (or most?) organizations have a policy to only use english.

**Comment by guillep2k** [comment]
> 
> 
> That would only work for user repos? Would you add a language for organizations as well?
> I think many would not want their commit messages translated just because they choosed to have the UI in a specific language. Many (or most?) organizations have a policy to only use english.

We seem to be keeping two different discussions here, and I'm not sure what are we talking about anymore 🤔. In my mind, this issue was about customizing the _commit message_ for updating a PR, and that only. And by customizing I mean type in any text you want, not choosing a locale. It seems, however that others are thinking of using the locale data and customize which language will be used for each org/repo, which of course is a different matter.

Anyone want to add/clarify about their position? 😬 We may need another vote.

**Comment by 6543** [comment]
I think discusion was if commit-message shuld be localiced ... and the towards solution was: No but changable via settings

**Comment by davidsvantesson** [comment]
@guillep2k You mean that when pressing `Update branch` you get option to change the commit message? I think that should be a drop-down option in that case to avoid unnecessary clicking. You can only use the Update branch button if there are no merge conflicts, and I don't see why you would to alter the commit message at different occasions.

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k You mean that when pressing `Update branch` you get option to change the commit message? I think that should be a drop-down option in that case to avoid unnecessary clicking. You can only use the Update branch button if there are no merge conflicts, and I don't see why you would to alter the commit message at different occasions.

Ha ha ha, no, that would be yet another possibility 🤣. I meant it to be a setting at the site level (`app.ini`), user level (owner, applying to all of their repositories) or repository level.

**Comment by davidsvantesson** [comment]
I think there are two main alternatives discussed here:
 - Localized using crowdin (by some user's or even org's preferred language)
 - A setting that can be made at different levels.

It seems not many are in favour of the first alterantive. For the settings alternatives, I don't see them as opposing each other. If it is first added as a app.ini setting, someone can then make a new PR with a repository setting (that would take precedence) and then even an organization setting (with in-between precedence).

**Comment by guillep2k** [comment]
> 
> 
> If it is first added as a app.ini setting, someone can then make a new PR with a repository setting (that would take precedence) and then even an organization setting (with in-between precedence).

I really like that plan. 👍

**Comment by 6543** [comment]
I would sugesst to use placeholders for branch name so they could be added remived and orderd head or base branch first ...

**Comment by sapk** [comment]
We could also manage a template for the merge commit in the same way.

**Pull request closed without merging**
