### PR TITLE
Fix eslint parsing errors, remove eslint-plugin-html

### PR DESCRIPTION
**Pull request by silverwind**
Introduce a separate `.eslintrc.yaml` in the Vue components folder to selectively enable vue-eslint-parser there, so that the rest of the files can use eslint's core parser which can deal with hashbangs.

The fact that the eslint-disable comments worked in HTML was a unintended side-effect of the files being parsed via vue-eslint-parser, so I had to disable the parsing of these files in .eslintrc.yaml to make it work.

For more context see https://github.com/go-gitea/gitea/pull/20113 and linked issues.

### CODE REVIEW

**Comment by silverwind** [comment]
BTW, if `eslint-plugin-html` is proving to much of a pain because it can't work with the template syntax, we could remove it. There's not much JS in HTML anyways, so it's not much value lost by removing it.

**Review by Gusted — APPROVED** [review]

**Comment by silverwind** [comment]
Decided to remove `eslint-plugin-html` as it causes more issues than it solves.

@wxiaoguang you probably want to review this.

**Review by wxiaoguang — APPROVED** [review]
I think it's fine. The only flaw is that the scripts in tmpl do not get linted?

IIRC we worried about the scripts in tmpl before (eg: #19209)

I am fine to either, since now we have explicitly JS error prompt (#18971)

**Comment by silverwind** [comment]
Yes, inline scripts won't get linted anymore, need to be review those extra-carefully.

**Comment by wxiaoguang** [comment]
bot

**Pull request merged**
