### PR TITLE
Rename to Gitea

### PR DESCRIPTION
**Pull request by tboerger**
As there are still many places where we reference to Gogs instead of Gitea I started to replace that. It's not  done yet, but I want to get feedback and reviews early :)

### CODE REVIEW

**Comment by lunny** [comment]
This PR will be not compitable with gogs.

**Comment by tboerger** [comment]
> This PR will be not compitable with gogs.

So how do you want to archive to stay compatible with Gogs?

**Comment by lunny** [comment]
I mean maybe we need create a documentation to introduce how to migrate from gogs to gitea since the database's name, binary name and data dir name are changed.

**Comment by tboerger** [comment]
> I mean maybe we need create a documentation to introduce how to migrate from gogs to gitea since the database's name, binary name and data dir name are changed.

That is something we can do quite easy on the documentation and add a link to it at the top of the readme :)

**Comment by vtolstov** [comment]
2015-06-30 11:55 GMT+03:00 Lunny Xiao <notifications@github.com>:

> I mean maybe we need create a documentation to introduce how to migrate
> from gogs to gitea since the database's name, binary name and data dir name
> are changed.


May be add config variable ?=)


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by lunny** [comment]
Yes. database name could be configed. So that migration will be more easy.

**Comment by vtolstov** [comment]
2015-06-30 12:04 GMT+03:00 Lunny Xiao <notifications@github.com>:

> Yes. database name could be configed. So that migration will be more easy.


I think branding name can be setted in config, so all gogs needs to be
replaced to variable...


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by tboerger** [comment]
As you can see on the current changes not everything can be configured, but the most important things like data path and database path can be configured so the migration can be quite easy, even including this changes.

**Comment by tboerger** [comment]
I have tried it locally and it seems to work fine, so I removed the WIP from the title and if you are fine with it feel free to merge it. Or make suggestions what can be improved :).

**Comment by lunny** [comment]
But this cannot be merged automatically? @tboerger

**Comment by tboerger** [comment]
@lunny rebased and updated!

**Pull request merged**
