### PR TITLE
New multiple languages structs for docs

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by delvh** [comment]
Before I have to endure a lot more problems with the current implementation of the `comment on file` implementation of GitHub:
What's the point of files like `/doc/en-us/content/advanced/adding-legal-pages.zh-cn.md`?
And why are these files in English?

**Comment by wolfogre** [comment]
I don't get it, for what purpose?

**Comment by lunny** [comment]
> I don't get it, for what purpose?

For easier maintenance.

**Comment by wxiaoguang** [comment]
> > I don't get it, for what purpose?
> 
> For easier maintenance.

I guess it needs a detailed description or design to describe how to maintain the documents in the future.

If the PR becomes stale for long time like others, it doesn't make sense.

**Comment by lunny** [comment]
> I think the point both @wolfogre and I have: This is a surprisingly large PR for `no description provided`. I guess a description of what this changes and why it's needed would certainly help here.

Yes, it needs more details but I haven't finished it so I just marked it as wip.

**Comment by lunny** [comment]
Closed as my another PR merged and so many conflicted files.

**Pull request closed without merging**
