### PR TITLE
Fix comment box not showing on PR commit replies

### LINKED ISSUE #5237: Reply button disappear on click in PR when language is spanish
- Gitea version (or commit ref): 7edb930
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/xxxtonixxx/asdf/pulls/1#issuecomment-8383
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I think it's self-explanatory

## Screenshots
- Pre-clicked
image
- Post-clicked
image
- In another languages (Deutsch). It works
image
- However, in files changed I can click and reply :laughing:  
image

### PR DESCRIPTION
**Pull request by jamesa**
Fixes #5237

The form that gets revealed when clicking on the "Reply" button mentioned in #5237, and the button, do not share the same parent. The button ends up getting wrapped in a link which causes this issue.

I have no idea how or why this worked on the English translation though. Didn't dig in that deep. :)

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm.. it's very interesting in the English translation the comment button appears in the following structure (This is presumably the case for every translation that works):

```html
<div id="code-comments-...">
    <div class="ui comments">...</div>
    <button class="comment-form-reply ui green labeled icon tiny button">...</button>
    <form class="ui form hide comment-form comment-form-reply" action="..." method="post">...</form>
</div>
```

However, in the Spanish translation it becomes:

```html
<div id="code-comments-X">
    <div class="ui comments">...</div>
    <a href="#issuecomment-X">
        <button class="comment-form-reply ui green labeled icon tiny button">...</button>
    </a>
    <form class="ui form hide comment-form comment-form-reply" action="..." method="post">...</form>
</div>
```

**Comment by zeripath** [comment]
OK I think that the locale-es_ES.ini file has a problem. There are likely other problems in that file too.

line 459: 
```ini
...
issues.commented_at=`comentado <a href="#%s"> %s`</a>
...
```

is the cause of this issue. The backtick (\`) before the `</a>` means that the `<a href="...">` is never closed.

**Comment by jamesa** [comment]
Nice find! This might not be the best fix then. It works but it might not be the most efficient.

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Seems as though the translation files may be an issue. See: https://github.com/go-gitea/gitea/issues/5237#issuecomment-436409305

**Review by zeripath — CHANGES_REQUESTED** [review]
This PR is attempting to fix the problem in the wrong place. The issue lies in the locale file for Spanish and the problem should be fixed in the translation.

**Comment by jamesa** [comment]
If you guys are fine with it, I can use this PR to make those changes. Unless @zeripath you would like to, or if another PR should be raised for this issue.

**Comment by techknowlogick** [comment]
The translations should be done via crowdin, as otherwise they will be overwritten by crowdin.

**Comment by zeripath** [comment]
line 795: auths.tip.facebook also needs adjustment as it has an open double-quote.

**Comment by techknowlogick** [comment]
Closing as translation files have been updated.

**Pull request closed without merging**
