### PR TITLE
fix compare button failed when there is no fork repos

### LINKED ISSUE #936: Compare-Button leads to 404
- Gitea version (or commit ref): 1.0.0+272-gcf47532e
- Git version: 2.8.3
- Operating system: Linux ad0c0ea10d83 4.4.0-62-generic #83-Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/gitea/gitea/compare/master...gitea:master
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When creating a repository, next to the branch-dropdown, it shows an image to compare branches. That link is always 404, since it will be of the form 
`try.gitea.io/<user>/<repo>/compare/<branch1>...<user>:<branch2>`
It should be:
`try.gitea.io/<user>/<repo>/compare/<branch1>...<branch2>`
If I change the address in the bar and remove the second user reference, the site loads fine.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/42030136-compare-button-leads-to-404?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lunny**
fix #936 and deprecate #948

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by appleboy** [comment]
build fails 

```
# code.gitea.io/gitea/vendor/github.com/boltdb/bolt
vendor/github.com/boltdb/bolt/db.go:98: undefined: maxMapSize
vendor/github.com/boltdb/bolt/db.go:98: invalid array bound maxMapSize
2017/03/03 02:33:36 Failed to cross compile package: exit status 2.
Makefile:108: recipe for target 'release-build' failed
make: *** [release-build] Error 1
```

Same errors :(

**Comment by lunny** [comment]
Yes, it's the new arch mips doesn't supported by boltdb.

**Pull request merged**
