### PR TITLE
Remove `font-awesome` and fomantic `icon` module

### LINKED ISSUE #10410: Remove font-awesome
We currently only use 4 icons out of it. I suggest replacing it with individual SVGs using the same build process like for octicons. I did not find a maintained npm repo of FA SVGs so we need to manually collect SVGs from tools like [icomoon](http://icomoon.io/app/#/select), or even better, use existing icons from the octicons set.

Here are the unique `fa-*` strings I found in the source:

```
fa-angle-right
fa-check-square-o
fa-file
fa-square-o
```
(Last check: 2023-04-30 by @delvh)

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/10410. I think that's it, but we should double check the code and ui whether anything was missed. This PR removes around 150kB.

Gitea no longer ships with the `font-awesome` icon font. Any custom templates that relied on these icons need to be updated to either embed SVGs or load their own version of `font-awesome`.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
🎉

**Comment by silverwind** [comment]
Found 4 more icons, fixing...

```
templates/repo/issue/labels/edit_delete_label.tmpl:60:      <i class="save icon"></i>
templates/repo/issue/view_content/pull.tmpl:252:            <i class="icon unlock"></i>
templates/repo/issue/view_content/pull.tmpl:277:              <i class="icon lock green"></i>
templates/repo/issue/view_content/pull.tmpl:282:              <i class="icon unlock"></i>
```

**Review by delvh — APPROVED** [review]
I agree with @techknowlogick

**Comment by silverwind** [comment]
Added breaking info.

**Comment by wxiaoguang** [comment]
-> EasyMDE toolbar is broken #24486

**Comment by delvh** [comment]
How is that breaking given our definition of breaking?

**Comment by techknowlogick** [comment]
@delvh it shouldn't be, as we don't consider template changes to be breaking.

**Comment by delvh** [comment]
Thought so.

**Pull request merged**
