### PR TITLE
Notifications: trying to get a better layout

### PR DESCRIPTION
**Pull request by andreynering**
I'm not an UI guy, so feedback welcome.

[Screenshot](https://cloud.githubusercontent.com/assets/7011819/21912569/e48964ea-d90d-11e6-93cf-b8eb6e8e525e.png)

### CODE REVIEW

**Comment by appleboy** [comment]
@andreynering Could your provide origin screenshot?

**Comment by Bwko** [comment]
@appleboy Current situation: 
current-notifiactions

@andreynering Looks good :+1: , LGTM

**Comment by lunny** [comment]
@Bwko it's still wip

**Comment by Bwko** [comment]
@Lunny I know but it looks good enough to me. Only the bell icon is slightly off-center
untitled

**Comment by appleboy** [comment]
origin screenshot:

screen shot 2017-01-13 at 9 56 30 pm

**Comment by andreynering** [comment]
This is done to be merged.

**Comment by lunny** [comment]
LGTM

**Pull request merged**
