### PR TITLE
Fix remaining typescript issues, enable `tsc`

### PR DESCRIPTION
**Pull request by silverwind**
Fixes 79 typescript errors. Discovered at least two bugs in `notifications.ts`, and I'm pretty sure this feature was at least partially broken and may still be, I don't really know how to test it.

After this, only like ~10 typescript errors remain in the codebase but those are harder to solve.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
There should be no "tsc" error now

**Comment by silverwind** [comment]
Those `.vue` import errors can be fixed by using `vue-tsc` instead of `tsc`, but it's currently broken for typescript 5.7 which we already use: https://github.com/vuejs/language-tools/issues/5018.

**Comment by silverwind** [comment]
I guess I will just uninstall `vue-tsc` and we live with those few `@ts-expect-error`. vue-tsc is monkeypatching `tsc` and that will likely break again in the future, so I think we are better off using official typescript tooling only.

**Comment by silverwind** [comment]
`tsc` is now enabled as part of `make lint-js` and is passing for me and should do too on CI.

**Comment by silverwind** [comment]
I switched back to `vue-tsc`, to a fork of mine that is from their `master` branch which works with typescript 5.7, but for some reason was not released yet (see https://github.com/vuejs/language-tools/issues/5018).

`.vue` files are getting type-checked again and the errors on the imports on `.vue` files go away. Interestingly a new error shows in `vitest.config.ts`, so I added a `@ts-expect-error` there. I hope we can resolve this later.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
FYI I opened https://github.com/vitejs/vite-plugin-vue/issues/487 regarding this `not callable` error.

**Comment by silverwind** [comment]
So I think I found the magic incantation that requires the least amount of `@ts-expect-error`:

```
    "module": "esnext",
    "moduleResolution": "bundler",
```

This is suboptimal as we do have a few node.js scripts, but we can likely split the tsconfig into two later, one for node files and one for `web_src`.

**Comment by silverwind** [comment]
I added type definitions for all named exports from `*.vue` files, so `npx tsc` is now also clean. It does not typecheck the `.vue` files because it can not parse them, so we need to use `vue-tsc` for that.

Long-term, I'd like to forbid named exports from Vue SFCs, they don't seem worth it.

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
