### PR TITLE
Remove expire from context cache

### PR DESCRIPTION
**Pull request by lunny**
Once a request took more than 10s, the warning `[W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}`, ref https://github.com/go-gitea/gitea/issues/31757#issuecomment-2334561325 .
The expiration has been introduced in #23330 and I approved. But now I'm suspecting if it's necessary. Since every request has it's own expiration time, the context cache should have the same lifecycle as the request.
So this PR just removed the expire checking, the context cache will still be available even if a SQL took over 10 seconds.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
Wait for @wolfogre 's review.

**Comment by wolfogre** [comment]
Please hold on. Why was the expiration time design introduced, to solve what problem, and why is it safe to remove it now that it is no longer a concern? This PR does not address these questions. I will check it and review it later.

**Review by wolfogre — CHANGES_REQUESTED** [review]
It doesn't LGTM. Please read the discussion in the comments of #23218. The expiration is used to avoid the context cache being used for long-term work. It is not really related to the lifecycle of the context itself.

My original idea was 5 minutes, not 10 seconds. So I suggest changing the duration from 10s to 5 minutes to reduce false reports instead of removing it entirely.

**Comment by wolfogre** [comment]
#32011

**Pull request closed without merging**
