### PR TITLE
Better oauth2 button and make horizontal navbar scroll on overflow

### PR DESCRIPTION
**Pull request by pgaskin**
Better oauth2 button and make horizontal navbar scroll on overflow

login

scrolling

### CODE REVIEW

**Comment by strk** [comment]
LGTM but I'd like to see it in action to check how it behaves upon resizing the browser window

**Comment by pgaskin** [comment]
@strk I will add it to my server and fyi it will put the scrollbar the moment there is an overflow.

**Comment by pgaskin** [comment]
@strk https://staging.geek1011.net

**Comment by strk** [comment]
Ok now I see it. The scrollbar kicks in too late so I can handle to have a view with truncated labels rather than a scrollbar.

Attaching screenshot:
navbar

**Comment by strk** [comment]
btw, maybe it would be good to rename `Email Addresses` to `Email` and `Two-Factor Authentication` to `2FA` (not sure about this)

**Comment by pgaskin** [comment]
@strk I'll rename that in another PR. I have updated my server with the bugfixes.

**Comment by strk** [comment]
Better, thank you.

**Comment by strk** [comment]
I just spotted this overlap in current master, dunno if your branch also fixes this (btw, needs to resolve conflicts)

navbar-overlap

**Comment by pgaskin** [comment]
I think your merge did that because it was fine before.

**Comment by pgaskin** [comment]
@strk I fixed it in #1316

**Comment by strk** [comment]
Yes @geek1011 it conflicted after the merge of the OpenID branch. Please fix the conflict and rebase.

**Comment by Quix0r** [comment]
Only  `templates/user/auth/signin_inner.tmpl ` is left.

**Comment by pgaskin** [comment]
Fixed, sorry about the delay.

**Comment by strk** [comment]
@appleboy, @lunny can you please review/merge this ?

**Comment by lunny** [comment]
@strk @geek1011 this will conflict with #1010

**Comment by strk** [comment]
@lunny you found #1010 broken while this is ready, let's merge this and let conflicts be resolved in #1010

**Comment by lunny** [comment]
Is this ready to review?

**Comment by pgaskin** [comment]
Yes

**Comment by lunny** [comment]
chrome on mac the github login button is not center.
untitled

**Comment by lunny** [comment]
any news?

**Comment by pgaskin** [comment]
I'm closing this PR, I will rewrite it with a better design because this is conflicted and will not look good with more than 2 providers.

**Comment by pgaskin** [comment]
@lunny #1777

**Pull request closed without merging**
