### PR TITLE
Fix incorrect test code for error handling

### PR DESCRIPTION
**Pull request by wxiaoguang**
If `assert.NoError` fails, it should return. Otherwise the code could still execute even if the error occurs.

### CODE REVIEW

**Comment by delvh** [comment]
But if `assert.NoError` fails, the test will already be marked as failed, correct?

**Comment by wxiaoguang** [comment]
> But if `assert.NoError` fails, the test will already be marked as failed, correct?

Yes. But there could be no different no matter the "defer" comes before or after if there is no return, the could could still execute to `defer nil.Close()` if the assert fails.

**Review by delvh — APPROVED** [review]

**Review by puni9869 — APPROVED** [review]

**Comment by puni9869** [comment]
🚀

**Comment by KN4CK3R** [comment]
This code is cleaner than the panic but we would need to rewrite lots of tests. At the moment we don't evade panics and I see not much value in doing so. The code in this PR for example should check the returned repo with `assert.NotNil` too. Here we would need the return too. And for every slice length check and so on. That will just bloat our tests.

It would be better to use `require` which instantly fails and aborts execution of the test. But for that we still would need to rewrite lots of tests.

**Comment by wxiaoguang** [comment]
> At the moment we don't evade panics and I see not much value in doing so.

Agree with it (also my comment https://github.com/go-gitea/gitea/pull/27139#issuecomment-1725923377: `I do not consider it as a serious problem in test code. But since 27129 has been merged, I think it's better to show the right approach.`)

In some cases, `if assert` is helpful, while for other cases, it's safe to leave the panic in the test.

**Comment by wxiaoguang** [comment]
I think we can merged this. If it doesn't look good or need future improvements, feel free to revert and/or propose new fixes.

**Pull request merged**
