### PR TITLE
Don't skip compliance on docs only PRs

### PR DESCRIPTION
**Pull request by yardenshoham**
We should make sure the docs linting happens

### CODE REVIEW

**Comment by delvh** [comment]
Hmm… Except that seems like a lot of unnecessary CI overhead.
What about splitting `compliance` into `compliance-backend`, `compliance-frontend`, and `compliance-docs`?
That will probably work the best, and even offer future CI optimizations.

**Comment by silverwind** [comment]
>  What about splitting compliance into compliance-backend, compliance-frontend, and compliance-docs?

Will probably make it a lot slower because every one these pipelines needs to re-install both the go and js dependencies. I dislike introducing more pipelines because of this issue.

**Review by silverwind — APPROVED** [review]
We don't have so many docs-only PRs, so this is fine imho.

Could introduce a optimized docs-only pipeline later that does the markdownlint only.

**Comment by silverwind** [comment]
Such a docs-only pipeline could consist of singe `time npx markdownlint docs *.md` command. With `node_modules` absent, `npx` will install into global cache. The only issue with this is that it would use the latest version instead of the one in package.json. That could be done via something like this:

```bash
npx markdownlint-cli@$(cat package.json | jq -r '.devDependencies["markdownlint-cli"]') docs *.md
```

**Comment by yardenshoham** [comment]
Would you like this in this PR or a future one?

**Comment by silverwind** [comment]
Let's do later. It depends on `jq` which is currently absent in the test-env:

https://gitea.com/gitea/test-env/pulls/22

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
No, I object to this change. I think we should have a separate pipeline for docs.
It's a chicken and egg problem. Why do we have so few docs-only PRs? Because CI took too long for every change of a docs-only PR.  This PR will make docs-only PR have to compile the source which is necessary.

**Comment by yardenshoham** [comment]
Ok. I'll try again after https://gitea.com/gitea/test-env/pulls/22 lands. Just know that until then, we will push docs code to `main` without linting

**Comment by silverwind** [comment]
I guess a `node_modules` installation may acceptable in that pipeline, it only takes 15 seconds, and in such a case we don't need `jq`. I'll try adding that now.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/24021 for that.

**Pull request closed without merging**
