### PR TITLE
  Fix the header key for repo-archive configuration in docs

### PR DESCRIPTION
**Pull request by dvjn**
Fixed the header key for repo-archive configuration in docs

### CODE REVIEW

**Comment by wxiaoguang** [comment]
According to the example(https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini#L2343-L2351) and the code, the old document seems correct.

**Comment by dvjn** [comment]
Strange.

When I tried to use the below configuration,

```ini
[storage.custom_s3]
STORAGE_TYPE = minio
SERVE_DIRECT = true
MINIO_ENDPOINT = s3.ap-south-1.amazonaws.com
MINIO_ACCESS_KEY_ID = ***
MINIO_SECRET_ACCESS_KEY = ***
MINIO_BUCKET = ***
MINIO_LOCATION = ap-south-1
MINIO_BASE_PATH = /gitea/misc
MINIO_USE_SSL = true

[attachment]
STORAGE_TYPE = custom_s3
MINIO_BASE_PATH = /gitea/attachments

[lfs]
STORAGE_TYPE = custom_s3
MINIO_BASE_PATH = /gitea/lfs

[storage.repo-archive]
STORAGE_TYPE = custom_s3
MINIO_BASE_PATH = /gitea/repo-archive
```

Only the repo archive config would fail with some error like invalid storage type.

**Comment by wxiaoguang** [comment]
The document could be incorrect. The storage type only supports internal pre-defined types: either `local` or `minio`, no customized type.

**Comment by dvjn** [comment]
Oh, nevermind

My bad

**Pull request closed without merging**
