### PR TITLE
Open external wiki in new window

### LINKED ISSUE #2217: Open new tab when clicking on external wiki
When setting an external wiki in a repository, the link of the `Wiki` button should open a new tab/window instead of being opened in the same tab. 

It is common behaviour of many websites that links to external sites are either marked as such or open in a separate tab.

### PR DESCRIPTION
**Pull request by cez81**
Change external wiki to open in new tab.

Fix #2217

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lafriks** [comment]
drone build was canceled? 😮 please force push

**Comment by cez81** [comment]
Rebased and succesfully built 👍

**Pull request merged**
