### PR TITLE
Include thread related headers in issue/coment mail

### PR DESCRIPTION
**Pull request by mrsdizzie**
Make it so mail programs will group comments from an issue into the same thread by setting Message-ID on initial issue and then using In-Reply-To and References headers to reference that later on. Also indicate a reply in the subject if it is a comment.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by kolaente — COMMENTED** [review]
Would you mind adding a small test for the `Re:` part?

**Comment by mrsdizzie** [comment]
> Would you mind adding a small test for the `Re:` part?

I'm not actually sure how to unit test this since ```&mailBody``` pointer always appears to be empty during testing here and throws an error:

https://github.com/go-gitea/gitea/blob/2771619acfd8a690c610363b12dd5b8e12f62e12/models/mail.go#L174-L176

If anybody has any ideas I'm open.

**Comment by mrsdizzie** [comment]
I got a bit further and was able to manually force it to load a template, but I can't seem to get the mailer service to run properly in a unit test because it is disabled by default and I see no way to start it without a config file.

I suspect all of this complication is why there are currently no mail related unit tests, and adding one wouldn't be small :(

**Comment by mrsdizzie** [comment]
OK have a working test for that

**Review by kolaente — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
