### PR TITLE
disable web preview for telegram webhook

### LINKED ISSUE #6682: Some messages without line feed and disable page preview in Telegram Webhook
- Gitea version (or commit ref): b9d1fb6
- Operating system: Docker
(rest is irrelevant)

## Description

First of all thank you @techknowlogick for #4227. I found some issues and suggestion for the message.

As you can see here

image

when someone comments an issue the bot message doesn't have a new line before the content. Same with comments for a PR. I haven't tested every message to see if this happens elsewhere.

**EDIT:**
PR #6719 fixes the page preview of the messages (description below) but the line feed in some messages (description above) is still missing.

***

Also in Telegram, by default a message sent that includes a link will put a preview of the web, a little header and description. I think for the main purpose users want this feature (notifications of events) it is just noise. You can see what I mean here:

image

The method [sendMessage](https://core.telegram.org/bots/api#sendmessage) in telegram bot API includes a parameter `disable_web_page_preview` that could be set to `false`. I think this should be `false` by default, maybe with an option to enable it.

### PR DESCRIPTION
**Pull request by techknowlogick**
Linked to #6682

### CODE REVIEW

**Comment by InExtremaRes** [comment]
I've tested and looks better now. Thank you.

What about the issue with the content of comments? As I commented in #6682 there is no line feed (or blank line) before the content of an issue or PR comment.

**Review by lunny — APPROVED** [review]

**Comment by techknowlogick** [comment]
@InExtremaRes I'm currently traveling right now so I can't get to adding in the line breaks, but if you want to attempt it the changes would be in same file as this PR (`models/webhook_telegram.go`).

**Comment by InExtremaRes** [comment]
@techknowlogick I don't have tools to edit Go nor experience with it :cry:. But I think that piece is far less important than the one you've fixed. Nonetheless, I wouldn't mark #6682 as fixed (and closed) by this PR, or is it better to open a new issue for those?

**Comment by techknowlogick** [comment]
@InExtremaRes that's ok. We appreciate the bug reports as well, without them there might be something that is broken which affects users that wouldn't be fixed because we wouldn't know.

I've edited my PR so it won't closed the linked ticket, but maybe once this is merged I'll update linked ticket to be just about the line breaks.

**Comment by InExtremaRes** [comment]
Hi @techknowlogick. Why was this closed?

**Comment by techknowlogick** [comment]
@InExtremaRes ack. Seems I deleted this branch during a regularly planned cleanup of my fork (I usually do them after a major release) and I got this one. I’ll relish the branch and open a PR again for it. Thanks for catching this :)

**Pull request closed without merging**
