### PR TITLE
vendor: update github.com/yuin/goldmark to v1.1.24

### LINKED ISSUE #10542: Markdown issue for bold
- Gitea version (or commit ref): `1.12.0+dev-403-g154b137b6`
- Can you reproduce the bug at https://try.gitea.io:
  - yes: https://try.gitea.io/alexanderadam/636f7374-cherry.cr#user-content-contributors

## Description

Bold text within a table isn't rendered bold?

This code:
```markdown
|Bold text below|
|:---:|
|**[this should be bold](…)**|
```
should render like

|Bold text below|
|:---:|
|**[this should be bold](…)**|

## Screenshots
[github](https://github.com/636f7374/cherry.cr#contributors) on the left and [gitea](https://try.gitea.io/alexanderadam/636f7374-cherry.cr#user-content-contributors) on the right
Screenshot_20200228_231225

### PR DESCRIPTION
**Pull request by sapk**
Fix #10542

### CODE REVIEW

**Comment by sapk** [comment]
I will block because it seems to have updated too much files in the vendor folder

**Comment by sapk** [comment]
It seems that vendor are not uptodate with go.mod but they should have failed previously on CI. 😑

**Comment by sapk** [comment]
This is good for review now.

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
ping lgtm

**Pull request merged**
