### PR TITLE
Update Octicons to v10

### LINKED ISSUE #11889: Octicons v2
Octicons v2 (v10.0.0) have been released https://primer.style/octicons/

Will require some work during upgrade; there are inconsistencies with how icons are used now and certain are missing. Some examples:
- Private repo has no template icon now, and this is confirmed to be exact on GitHub however they also decided to present the type of repository in this way:
chrome_2020-06-15_09-03-15
Interestingly they decided to keep one for public templates :\
- Internal repos now use same icon as normal, but with organization avatar absolutely positioned near actual octicon (presumably, based on public discussion on octicons-v2 repo; the alternative is that there is unpublished v2 variant or organization icon is used along with avatar; would need to wait for GHE update)

The iconset now contains both 24px and 16px icons, all of them have identical width however not all icons exists in 24px set!

Other issues might be present but were not catched yet, feel free to add your observations here.

### PR DESCRIPTION
**Pull request by silverwind**
Besides a few renames, these icons are no longer present in v10 that we've used, so had to change:

file-symlink-directory -> file-submodule
internal-repo -> repo
repo-force-push -> repo-push
repo-template-private -> repo-template

Fixes: https://github.com/go-gitea/gitea/issues/11889
Ref: https://github.com/primer/octicons/releases/tag/v10.0.0

### CODE REVIEW

**Comment by CirnoT** [comment]
>repo-template-private -> repo-template
internal-repo -> repo

These two should be fine thanks to previous PRs that explicitly display repo visibility/type as label.

**Comment by CirnoT** [comment]
```diff
Index: templates/repo/header.tmpl
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- templates/repo/header.tmpl	(revision d6c55b0ab0130fca7d93b0ef52b1414e990b4e0a)
+++ templates/repo/header.tmpl	(date 1594663288676)
@@ -50,8 +50,7 @@
 						{{$.CsrfTokenHtml}}
 						<div class="ui labeled button" tabindex="0">
 							<button type="submit" class="ui compact basic button">
-								<!-- TODO use star-filled once octicons v2 are in place */ -->
-								{{if $.IsStaringRepo}}{{svg "octicon-star" 16}}{{$.i18n.Tr "repo.unstar"}}{{else}}{{svg "octicon-star" 16}}{{$.i18n.Tr "repo.star"}}{{end}}
+								{{if $.IsStaringRepo}}{{svg "octicon-star-fill" 16}}{{$.i18n.Tr "repo.unstar"}}{{else}}{{svg "octicon-star" 16}}{{$.i18n.Tr "repo.star"}}{{end}}
 							</button>
 							<a class="ui basic label" href="{{.Link}}/stars">
 								{{.NumStars}}
```

**Comment by silverwind** [comment]
Removed settings icon fixed: 

image

**Comment by silverwind** [comment]
Admin dashboard now uses `play`:

image

**Comment by CirnoT** [comment]
Aside from `octicon-mirror` you should also update `octicon-clone`, as they're now same icon.

**Comment by silverwind** [comment]
You mean `repo-clone`? I guess I can add a copy `gitea-repo-clone`.

**Comment by CirnoT** [comment]
I think Octicons switched to single `octicon-mirror` icon (that is, `repo-clone` is removed) but mirror icon itself is missing from v10 for now so we don't know for sure. Based on GH usage however most likely we should just rename usages of  `octicon-repo-clone` to `octicon-mirror` as 99% in next version they'll remove clone and add mirror icon instead.

**Comment by silverwind** [comment]
I'll just move out current usage of `repo-clone` to `gitea-mirror`. If they decide to add `octicon-mirror` it'll be an easy switch for us.

**Comment by silverwind** [comment]
Done. I also changed to "New Migration" icon to `repo-push` which seemed more appropriate than the mirror icon:

image

**Comment by silverwind** [comment]
Conflicts were also using this `repo-clone` icon which when turned into a mirror icon seemed unfitting. Changed them to `octicon-x`:

image

**Comment by silverwind** [comment]
One more semi-related change. Timeline icons slightly adjusted and background of commit icon fixed:

image

**Comment by silverwind** [comment]
Comment button `...` replaced with octicon and slightly tweaked:

image

**Comment by CirnoT** [comment]
Actually mirror octicon is in set; https://primer.style/octicons/mirror-16. Very sorry for suggesting that it isn't. We can remove `gitea-mirror` in that case.

**Comment by CirnoT** [comment]
Can't we use https://primer.style/octicons/tools-16 or https://primer.style/octicons/gear-16 instead of v1 sliders for settings?

**Comment by silverwind** [comment]
@CirnoT both done.

One more semi-related change: Replaced two icons on Wiki with octicons:

image
image

I think this is looking pretty good now overall.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
devDependencies are only for build tools, so it should be moved back to dependencies

**Comment by silverwind** [comment]
I've moved both `svgo` and `@primer/octicons` to devDependencies because they are not used during the main build process (only during the `make svg` task), but I guess it's probably better to have them in `dependencies`.

**Comment by lafriks** [comment]
svgo is used for building so it is devDependency but octicons are dependency

**Comment by silverwind** [comment]
They are both used in the same script so they shoud be together. Let's keep them in dependencies. The primary reason I've moved them to devDeps is to avoid some unnecessary installs but it's no big deal.

**Comment by lafriks** [comment]
@silverwind but not the same way. Svgo is used as a lib for build script while octicons are needed get svg files from so that's different uses

**Comment by silverwind** [comment]
Done, I guess I don't really care :)

**Review by CirnoT — APPROVED** [review]

**Comment by lafriks** [comment]
:rocket:

**Pull request merged**
