### PR TITLE
#4354 Fix translation

### LINKED ISSUE #4354: [Translation] delete_inactivate_accounts -> Delete all inactive accounts
- Gitea version (or commit ref): _Not relevant_
- Git version: _Not relevant_
- Operating system: _Not relevant_
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In the admin page, in the Dashboard -> Operations, the first operation (in English) is:
`Delete all inactive accounts`

However, I wanted to know what inactive means (1 week, 1 month, 1 year ?). After some researches, I found that the string is the translation of `delete_inactivate_accounts` which calls the function `DeleteInactivateUsers` of `models/user.go`.
If we look at the function, it deletes users not activated.

So there is a misunderstanding between _inactive_ and _inactivate_. It seems that other languages are also badly translated. How can we fix the meaning of the function in all the different languages ?

### PR DESCRIPTION
**Pull request by Pofilo**
Fix https://github.com/go-gitea/gitea/issues/4354 for en-US.

### CODE REVIEW

**Comment by Arbyy** [comment]
Shouldn't it be _Delete all **de**activate**d** accounts_ and _All **de**activate**d** accounts have been deleted_?
Correct me if I'm missing something here.

**Comment by daviian** [comment]
@Arbyy I think you are partially correct, however your translation in a way implies that they have been deactivated beforehand.
So I propose to use *not activated* instead of *inactivate*

**Comment by sapk** [comment]
I would suggest "Delete all un-activated accounts" but "not activated" seems more simple and clear.

**Comment by Pofilo** [comment]
@sapk I do agree, I put _not activated_ to be understandable from anyone from the admin page.

**Review by sapk — APPROVED** [review]

**Review by daviian — APPROVED** [review]

**Pull request merged**
