### PR TITLE
Import git from alpine 3.16 repository as 2.30.4 is needed for `safe.directory = '*'` to work but alpine 3.13 has 2.30.3

### PR DESCRIPTION
**Pull request by singuliere**
Refs: #19455

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
I really think we need to make it clear that this is not needed if people set up their docker configurations correctly.

Gitea is requires that its repositories are owned by the user running Gitea, (usually `git`.) This configuration is *ONLY* needed if the configuration is not mapping ownership correctly.

**Review by zeripath — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Git 2.36 is not a must (and is not the first version) for the `safe.directory`. For example:

https://git-scm.com/docs/git-config/2.30.4#Documentation/git-config.txt-safedirectory
https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory


So, I can not understand why the 2.36 must be used as a backport.

**Comment by singuliere** [comment]
Because the wildcard was introduced in 2.36:

https://git-scm.com/docs/git-config/2.36.1#Documentation/git-config.txt-safedirectory

See also [this blog post](https://hostea.org/blog/unsafe-repository-is-owned-by-someone-else/#bug-fix) for an extended analysis of the problem and the conditions for the workaround to be effective.

**Comment by wxiaoguang** [comment]
image

**Comment by zeripath** [comment]
I wonder if the problems people are experiencing may relate to a vendor provided versions of git which whilst badged 2.30.x may not actually match 2.30.x?

**Comment by singuliere** [comment]
The wild card is documented in 2.30.4 but the git version provided with alpine-3.13 is 2.30.3 which is the base image for the Gitea docker files is:

https://git-scm.com/docs/git-config/2.30.3#Documentation/git-config.txt-safedirectory

**Comment by wxiaoguang** [comment]
> The wild card is documented in 2.30.4 but the git version provided with alpine-3.13 is 2.30.3 which is the base image for the Gitea docker files:
> 
> https://git-scm.com/docs/git-config/2.30.3#Documentation/git-config.txt-safedirectory

That's clear and reasonable. (hopefully the git from alpine-3.16 is compatible with alpine-3.13)

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
@singuliere I changed the title I think it's more accurate than before. If it's not, please change it directly.

**Pull request merged**
