### PR TITLE
Convert JS to use double quotes

### PR DESCRIPTION
**Pull request by silverwind**
We already use double quotes in Go, Templates and CSS, so I think it makes sense to use them in JS too. Files were converted automatically by eslint.

### CODE REVIEW

**Comment by lafriks** [comment]
Please, no 🙃 Mostly all javascript linters default to single quotes by default and that is what most libraries also use now days, so at least for me it is more convenient to use single quotes in javascript

**Comment by silverwind** [comment]
Which linters? I think JS quote style is purely a preference. I use them in all my projects. If it matters, the prettier formatter (which we could use) defaults to double too 😉. Thought I guess all relevant tooling can be configured to use either style.

**Comment by lafriks** [comment]
airbnb config that is most common ;)

**Comment by zeripath** [comment]
I'm also a fan of single quotes for js (and python and r)

This may sound ridiculous but I find ' easier to type than "

**Comment by silverwind** [comment]
> This may sound ridiculous but I find ' easier to type than "

Opposite for me. But I guess if this doesn't gain traction, we could introduce prettier so I could still write double-quotes and let the formatter do the rest 😉

**Comment by zeripath** [comment]
This might be a function of keyboard layouts on mine (UK format) " requires a shift key and left finger whereas ' is a single key under a right finger.

**Comment by 6543** [comment]
hmm this only irritates git-blame views I think

**Comment by silverwind** [comment]
Yeah, US/UK layouts have them on the same key while many european ones have double on the number row with shift and single in a (imho) awkward position besides right shift.

Anyways, it doesn't seem like this it's gaining acceptance.

**Pull request closed without merging**
