### PR TITLE
Simplify text color selectors and tweak arc-green colors

### PR DESCRIPTION
**Pull request by silverwind**
Move the text color rules out of the unneeded `.ui` block, add missing colors, tweak colors on arc-green to be more readable (red was particulary bad to read).

Also, this removes the previous inheritance of link colors. I think links should always be in primary color and if they are to be discolored, the color should be set on them explicitely.

Screenshot 2022-11-12 at 13 28 30

Screenshot 2022-11-12 at 13 18 48

HTML to test with:

```html
<div class="text red">some text with <a href="#foo">a link</a>.</div>
<div class="text orange">some text with <a href="#foo">a link</a>.</div>
<div class="text yellow">some text with <a href="#foo">a link</a>.</div>
<div class="text olive">some text with <a href="#foo">a link</a>.</div>
<div class="text green">some text with <a href="#foo">a link</a>.</div>
<div class="text teal">some text with <a href="#foo">a link</a>.</div>
<div class="text blue">some text with <a href="#foo">a link</a>.</div>
<div class="text violet">some text with <a href="#foo">a link</a>.</div>
<div class="text purple">some text with <a href="#foo">a link</a>.</div>
<div class="text pink">some text with <a href="#foo">a link</a>.</div>
<div class="text brown">some text with <a href="#foo">a link</a>.</div>
<div class="text grey">some text with <a href="#foo">a link</a>.</div>

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Does the change work with something like `<a class="text read">`? 

image

**Comment by delvh** [comment]
Yes:
image

<details>
<summary>Corresponding HTML</summary>

```html
<!DOCTYPE html>
<html>
<style>
  /* colors */
  
 * { 
  --color-red: #7d3434;
  --color-red: #cc4848;
  --color-orange: #cc580c;
  --color-orange: #cc580c;
  --color-yellow: #cc9903;
  --color-yellow: #cc9903;
  --color-olive: #91a313;
  --color-olive: #91a313;
  --color-green: #87ab63;
  --color-green: #87ab63;
  --color-teal: #00918a;
  --color-teal: #00918a;
  --color-blue: #1a6aa6;
  --color-blue: #3a8ac6;
  --color-violet: #502aa1;
  --color-violet: #906ae1;
  --color-purple: #8229a0;
  --color-purple: #b259d0;
  --color-pink: #c21e7b;
  --color-pink: #d22e8b;
  --color-brown: #845232;
  --color-brown: #a47252;
  --color-grey: #5e626a;
  --color-grey: #5e626a;
  /* light variants */
  /* light variants */
  --color-red-light: #984646;
  --color-red-light: #c23636;
  --color-orange-light: #e6630d;
  --color-orange-light: #b84f0b;
  --color-yellow-light: #e5ac04;
  --color-yellow-light: #b88a03;
  --color-olive-light: #a3b816;
  --color-olive-light: #839311;
  --color-green-light: #9fbc82;
  --color-green-light: #7a9e55;
  --color-teal-light: #00a39c;
  --color-teal-light: #00837c;
  --color-blue-light: #1e78bb;
  --color-blue-light: #347cb3;
  --color-violet-light: #5a30b5;
  --color-violet-light: #7b4edb;
  --color-purple-light: #932eb4;
  --color-purple-light: #a742c9;
  --color-pink-light: #db228a;
  --color-pink-light: #be297d;
  --color-brown-light: #955d39;
  --color-brown-light: #94674a;
  --color-grey-light: #6a6e78;
  --color-grey-light: #55585f;
  /* other colors */
  /* other colors */
  --color-black: #1e222e;
  --color-black: #1e222e;
  --color-gold: #a1882b;
  --color-gold: #b1983b;
  --color-white: #ffffff;
  --color-white: #ffffff;
}
.text.red { color: var(--color-red) !important; }
.text.orange { color: var(--color-orange) !important; }
.text.yellow { color: var(--color-yellow) !important; }
.text.olive { color: var(--color-olive) !important; }
.text.green { color: var(--color-green) !important; }
.text.teal { color: var(--color-teal) !important; }
.text.blue { color: var(--color-blue) !important; }
.text.violet { color: var(--color-violet) !important; }
.text.purple { color: var(--color-purple) !important; }
.text.pink { color: var(--color-pink) !important; }
.text.brown { color: var(--color-brown) !important; }
.text.black { color: var(--color-text) !important; }
.text.grey { color: var(--color-text-light) !important; }
.text.light.grey { color: var(--color-grey-light) !important; }
.text.gold { color: var(--color-gold) !important; }
</style>
<body>
<div class="text red">some text with <a href="#foo" class="text red">a link</a>.</div>
<div class="text orange">some text with <a href="#foo" class="text orange">a link</a>.</div>
<div class="text yellow">some text with <a href="#foo" class="text green">a link</a>.</div>
<div class="text olive">some text with <a href="#foo">a link</a>.</div>
<div class="text green">some text with <a href="#foo">a link</a>.</div>
<div class="text teal">some text with <a href="#foo">a link</a>.</div>
<div class="text blue">some text with <a href="#foo">a link</a>.</div>
<div class="text violet">some text with <a href="#foo">a link</a>.</div>
<div class="text purple">some text with <a href="#foo">a link</a>.</div>
<div class="text pink">some text with <a href="#foo">a link</a>.</div>
<div class="text brown">some text with <a href="#foo">a link</a>.</div>
<div class="text grey">some text with <a href="#foo">a link</a>.</div>
</body>

</html>
```
</details>

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
The mainly changed UI is here. Other places seem fine.

 (I think maybe it could be acceptable to make the links use primary link color)

### Before

image

### After

image

**Comment by wxiaoguang** [comment]
@silverwind do you think whether these inconsistent colors should be fixed?

**Comment by silverwind** [comment]
The timeline links being colors should be fixed by adding `muted` class, yes.

**Comment by silverwind** [comment]
> Does the change work with something like <a class="text red">?

Yes it should. In fact, I think we can also remove the `!important` on these text classes, and potentially also make  them single-class (`text-red`). I may check that out later, it certainly has potential for side-effects.

**Pull request merged**
