### PR TITLE
Quick fix milestone deadline 9999 for 1.22

### PR DESCRIPTION
**Pull request by wxiaoguang**

### CODE REVIEW

**Review by Zettat123 — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]

**Comment by lunny** [comment]
The year becomes 9998, maybe we should use 9998 but 9999

**Comment by wxiaoguang** [comment]
> The year becomes 9998, maybe we should use 9998 but 9999

Why?

**Comment by lunny** [comment]
> > The year becomes 9998, maybe we should use 9998 but 9999
> 
> Why?

I haven't figured it out. But I just found that.

**Comment by wxiaoguang** [comment]
> > > The year becomes 9998, maybe we should use 9998 but 9999
> > 
> > 
> > Why?
> 
> I haven't figured it out. But I just found that.

How could it be possible?

**Comment by lunny** [comment]
This is not a block because I cannot reproduce it now.

**Pull request merged**
