### PR TITLE
Use forked macaron/session and macaron/cache libraries

### LINKED ISSUE #7670: Update go-macaron/cache and go-macaron/session
I would like to update the go-macaron/cache and go-macaron/session packages to use the latest version of go-redis client. The latest client has support for Redis cluster. I opened prs against the macaron repos for 2 months which have not been merged.

- https://github.com/go-macaron/cache/pull/12
- https://github.com/go-macaron/session/pull/28

How can gitea use my updated version of the macaron libraries?

### PR DESCRIPTION
**Pull request by tamalsaha**
Fix https://github.com/go-gitea/gitea/issues/7670

Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
If you would approve https://gitea.com/macaron/session/pulls/7 , I would like to vendor that in this pr also.

**Comment by tamalsaha** [comment]
There is still dependency on 

- [ ] go-macaron/session because of the go-macaron/csrf plugin
https://github.com/go-macaron/csrf/blob/master/csrf.go#L24

- [ ] go-macaron/cache because of go-macaron/captcha
https://github.com/go-macaron/captcha/blob/master/captcha.go#L27

Should csrf and captcha plugin repos be forked too?

**Comment by techknowlogick** [comment]
yes, let me fork them now.

**Comment by techknowlogick** [comment]
ok, forked at https://gitea.com/macaron/csrf and https://gitea.com/macaron/csrf

**Comment by tamalsaha** [comment]
Thanks @techknowlogick . Can you please add drone ci for those repos? I can open a pr after that.

**Comment by tamalsaha** [comment]
@techknowlogick / @lunny / @zeripath , it seems that the following macaron repos a should be forked also, since the main macaron repo has been forked.

- github.com/go-macaron/binding
- github.com/go-macaron/cors
- github.com/go-macaron/i18n
- github.com/go-macaron/inject
- github.com/go-macaron/toolbox

**Pull request closed without merging**
