### PR TITLE
Remove CodeMirror dependencies

### PR DESCRIPTION
**Pull request by silverwind**
Use webpack dynamic import to load the markdown mode for easymde, eliminating the need to ship the outdated vendored version of codemirror we had, while at the same time updating the markdown mode to the latest version too.

This should also bring a reduction in memory usage because we no long need to include all these unnecessary files in the bindata.

Solution is based on https://github.com/codemirror/CodeMirror/issues/5484.

### CODE REVIEW

**Comment by silverwind** [comment]
The diff is unfortunately spammed by all the file removals. There is only one actual file change in `web_src/js/features/comp/EasyMDE.js` which is visible when scrolling to the bottom of the diff.

**Review by Gusted — APPROVED** [review]

**Comment by wxiaoguang** [comment]
1. Is `window.CodeMirror = CodeMirror;` still needed? If yes, `import(/* webpackChunkName: "markdown" */'codemirror/mode/markdown/markdown.js')` comes before it, how can it work.
2. `Promise.all` doesn't have loading order, what if `markdown.js` is loaded before `codemirror.js`?
3. Should CodeMirror support dynamic plugin loading in future, if yes, does `modeURL` still work? if no need to support then it's fine.

**Comment by silverwind** [comment]
I ended up just removing the direct CodeMirror dependency altogether. EasyMDE already loads all the modes and plugins it needs, so there is no reason for neither the webpack dependency nor the vendored copy:

https://github.com/Ionaru/easy-markdown-editor/blob/f573560bb44886d7cc8d412a0b6712f18c3081f0/src/js/easymde.js#L2-L13

Syntax highlighting in EasyMDE still works as expected. I suspect the reason why we left CodeMirror in was because it was previously in direct use by the code editor, which was replaced by monaco.

**Review by wxiaoguang — APPROVED** [review]
That's what we are glad to see

**Comment by zeripath** [comment]
Did anyone check if this breaks the Git Hooks editor?

**Comment by wxiaoguang** [comment]
image

**Pull request merged**
