### PR TITLE
API: Move AllowedReactions endpoint into GetGenneralUI endpoint + creat new swagger section settings

### PR DESCRIPTION
**Pull request by 6543**
as title

come up in <https://github.com/go-gitea/gitea/pull/11758#issuecomment-641375632>

### CODE REVIEW

**Comment by 6543** [comment]
WIP because if there are more usefull settings to expose in the UI scope:

-> change GetAllowedReactions to a getGeneralUISettings ...

**Comment by 6543** [comment]
@mrsdizzie ping

WIP because if there are more usefull settings to expose in the UI scope:

-> change GetAllowedReactions to a getGeneralUISettings ...

**Comment by mrsdizzie** [comment]
@6543  that change is fine but I mean that you shouldn't have an endpoint for one single setting like /settings/allowed_reactions -- it should be /settings/ui that can return 

```
{
  "allowedReactions": []
}
```

That way you can eventually add other settings without having to create new endpoints for each one, just like how the check for mirrors uses /settings/repository. 

I only pick 'ui' because that is the section in config.ini just as repository is for the other example

**Comment by 6543** [comment]
@mrsdizzie done

**Comment by mrsdizzie** [comment]
Test fail changes seem good otherwise

**Comment by 6543** [comment]
@mrsdizzie passed - fail seems unrelated

**Review by mrsdizzie — APPROVED** [review]
🚀

**Review by techknowlogick — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
