### PR TITLE
Set the default branch for repositories generated from templates

### LINKED ISSUE #19082: When generating repo from template, default_branch returns as blank string
### Gitea Version

1.16.3

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3 LTS (Focal Fossa)

### How are you running Gitea?

I'm running gitea from the binary, through systemctl. I installed it from a tutorial I found online, recently updating it to the latest version, so I can use the generate repo endpoint.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

Whenever I create a new repo from a template repo, I get back the repository detail as the request response, but the `default_branch` property is returned as an empty string. I think It should be the default branch, since when I fetch the detail of it in the next request, it's there, therefore I concluded this is a bug.

Allow me to send a gist with the entire response from the API [https://gist.github.com/truesteps/43b4b13ac3619c92cbdc70c5622c6e02](https://gist.github.com/truesteps/43b4b13ac3619c92cbdc70c5622c6e02)

### Screenshots

Screenshot 2022-03-14 at 16 08 41

### PR DESCRIPTION
**Pull request by abheekda1**
Should fix #19082

The generate repository function generates a repository from a template, but when used from the API, it does not seem to have any value returned for the default branch. Seeing as the API was simply returning the generated repository object converted to JSON using a function (which did indeed have the default branch filled out), it seemed likely that the default branch was just not being set for the generate repository. This was fixed simply enough (hopefully correctly) with this PR. Please let me know if I missed something, did something wrong, or anything else :)

### CODE REVIEW

**Comment by ADawesomeguy** [comment]
Not sure if the most recent commit will work, if anyone has any suggestions please let me know how to best approach making this simple change functional.

**Comment by jolheiser** [comment]
Will review when I get to my machine, but the CI is failing because you need to `make generate-swagger`

**Comment by ADawesomeguy** [comment]
Yep, thanks :)

**Review by jolheiser — CHANGES_REQUESTED** [review]
Firstly, this should also be added to the UI, as currently it only uses default branch.

Second, the current changes are only setting the default in the database, however they are not being passed along to any of the git commands when the repo is initialized. 
The API response gives the input default branch, but the actual repository doesn't reflect it. 

Particularly, if you follow https://github.com/go-gitea/gitea/blob/60fbaa90683add2a8af891fc2ca8448b9b75c92e/services/repository/template.go#L36 you should run into spots that are currently using default branch that will need to change.

**Comment by ADawesomeguy** [comment]
https://github.com/go-gitea/gitea/blob/60fbaa90683add2a8af891fc2ca8448b9b75c92e/modules/repository/generate.go#L211

It seems this is where the default branch for the generated repo is being defined. A request missing the key for `default_branch` would just fill in the object with an empty string for `DefaultBranch` right? So would it make sense to check whether `repo.DefaultBranch` is an empty string and only define the default branch using the template repo if it is?

**Comment by ADawesomeguy** [comment]
I think once the API is figured out the UI can be implemented as well.

**Comment by jolheiser** [comment]
Default branch is also used here https://github.com/go-gitea/gitea/blob/60fbaa90683add2a8af891fc2ca8448b9b75c92e/modules/repository/init.go#L106

**Comment by ADawesomeguy** [comment]
@jolheiser think that should also be implemented in a similar way as of the latest commit.

**Comment by ADawesomeguy** [comment]
Hey @jolheiser sorry to bother you but I think I got it now, would you mind taking a look?

**Comment by jolheiser** [comment]
It looks like this is working via API now.

**Comment by ADawesomeguy** [comment]
Is there anything left for me to do or is this PR mostly set?

**Review by jolheiser — APPROVED** [review]
I would like to see this available in the UI for parity, but I suppose that can be a separate PR since this one also fixes a bug.

**Review by wxiaoguang — APPROVED** [review]

**Comment by zeripath** [comment]
> Any clue why this is failing CI?

it's not your fault - it's this TestRepoIndexer. The test is inherently racey and things have now started to become super racey there. I've added #19225 which should resolve the issue.

**Comment by ADawesomeguy** [comment]
Alright, nice! Seems like it finally passed this time.

**Pull request merged**
