### PR TITLE
Remove duplicate "Max Diff Lines" from config view

### PR DESCRIPTION
**Pull request by mrexodia**

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lunny** [comment]
Is this still on v1.3?

**Comment by lafriks** [comment]
I think yes

**Comment by lunny** [comment]
So please send a back port

**Comment by lafriks** [comment]
@mrexodia can you backport this to release/v1.3 branch?

**Comment by mrexodia** [comment]
Should I do something for this?

**Comment by lafriks** [comment]
Create new PR targeting v1.3 branch with cherry-pick'ed  merge commit of this PR

**Pull request merged**
