### PR TITLE
rename TotalTimes() to TotalTimesForEachUser()

### PR DESCRIPTION
**Pull request by 6543**
make function name more descriptive as it would otherwise imply it could be used for e.g. #26672 too ...

---
*Sponsored by Kithara Software GmbH*

### CODE REVIEW

**Comment by lunny** [comment]
It depends on `FindTrackedTimesOptions`. How about there are two or three users in this options?

**Review by delvh — APPROVED** [review]
Alternatively, `TotalTimesPerUser`.

**Comment by 6543** [comment]
> It depends on `FindTrackedTimesOptions`. How about there are two or three users in this options?

in this cases the option misses totally the point and that's why we need to rename this function!
so using this function in combination with the user filter is a missuse ... 
... I can optionally add a check and return an error in this case

**Comment by 6543** [comment]
> Alternatively, `TotalTimesPerUser`.

I don't mind whatever is more preferred ... as long as the name is not so miss-leading as it is now ;)

**Review by silverwind — APPROVED** [review]

**Pull request merged**
