### PR TITLE
Change drone token name to let users know to use oauth2

### PR DESCRIPTION
**Pull request by techknowlogick**
This changes the name of the drone token so that basic auth is still allowed (but points user in direction of using oauth2)

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Lgtm but I know nothing about Drone

**Review by adelowo — APPROVED** [review]

**Comment by lafriks** [comment]
Is this really only option?

**Comment by techknowlogick** [comment]
What users should be doing is using OAuth2, however some don't. So this will resolve the broken connection when they try to use basic auth with drone, however it'll let them know they should be using OAuth2.

Basic auth connection with drone is already not working due with users that use 2FA, and so if users want to be secure they should be using OAuth2. And as we've seen from recent attacks against SCM providers, 2FA is essentially mandatory if you want to keep your code safe.

I see this PR as temporary, and once 1.9.0 is final we can put in blog post that users should switch to OAuth2 for Drone, and then we can remove it for 1.10.0

**Comment by lafriks** [comment]
But wouldn't generate lots of tokens this way?

**Comment by techknowlogick** [comment]
@lafriks yes, it would. This encourages users to switch to OAuth2 (basic auth for Gitea will be removed in next release of Drone)

**Pull request merged**
