### PR TITLE
Bump unrolled/render to v1.1.0

### PR DESCRIPTION
**Pull request by nsmith5**
`unrolled/render` is used to render content. For HTML templates, it uses a buffer pool. A buffer must be used when HTML templating to check for templating errors before writing content to the response writer (because the first write will implicitly set the status to 200 if not already set). 

In versions <= v1.0.3 the buffer pool used was set to 64 buffers that could grow indefinitely. In practice this would lead to 64 * the largest template size in memory usage. In v1.1.0, the buffer pool is configurable, but defaults to a more reasonable 32 * 512KiB buffers. Instead of growing indefinitely, buffers are garbage collected if they grow pasted the 512KiB limit. This means the buffer pool has a fixed cost of 16MiB.

Further details and profiling results can be seen in the pull request upstream : https://github.com/unrolled/render/pull/87

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@nsmith5 can you send a backport to v1.14. If you need help just ask :)

**Comment by nsmith5** [comment]
@6543 yeah absolutely. Is there a release branch or something I need to target for v.1.14?

**Comment by 6543** [comment]
@nsmith5 yes -> just **cherry-pick** the squashed commit and create a pull targeting `release/v1.14`

**Comment by zeripath** [comment]
@nsmith5 the below is my script for creating backports quickly.

```bash
#!/bin/sh
PR="$1"
SHA="$2"
VERSION="$3"

if [ -z "$SHA" ]; then
    SHA=$(gh api /repos/go-gitea/gitea/pulls/$PR -q '.merge_commit_sha')
fi

if [ -z "$VERSION" ]; then
    VERSION="v1.14"
fi

echo git checkout origin/release/"$VERSION" -b backport-$PR-$VERSION
git checkout origin/release/"$VERSION" -b backport-$PR-$VERSION
git cherry-pick $SHA && git commit --amend && git push zeripath backport-$PR-$VERSION && xdg-open https://github.com/go-gitea/gitea/compare/release/"$VERSION"...zeripath:backport-$PR-$VERSION
```

**Comment by nsmith5** [comment]
Backported here #15608

**Pull request merged**
