### PR TITLE
Fix dropdown icon misalignment when using fomantic icon

### PR DESCRIPTION
**Pull request by wxiaoguang**
There are still many dropdowns using fomantic icon. For example: new issue with issue template.

Avoid polluting the fomantic styles.

Before:

image

After:

image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
How many remaining cases of fomantic dropdown arrow are there? We could also just replace them with SVG, which will eventually allow the removal of FontAwesome.

**Comment by wxiaoguang** [comment]
> How many remaining cases of fomantic dropdown arrow are there? We could also just replace them with SVG, which will eventually allow the removal of FontAwesome.

I guess not only a few (but not too many). And I see new code still uses that `fomantic icon`.

**Comment by wxiaoguang** [comment]
And one more thing, the dynamically generated "labels" for multiple selection, are constructed by Fomantic UI template, they all still uses "<i delete icon>`

See #23346 for example.

**Comment by silverwind** [comment]
I think new code should not use `<i>` icons anymore, only SVG. Fomatic CSS usually matches for `.icon` so if you add that class to the SVG, the styling should work.

I will check what's left to get rid of FontAwesome.

**Comment by wxiaoguang** [comment]
1. There are still new PRs like #23522, because people just like to copy the Fomantic UI examples, and following the examples is the best practice, to avoid misusing Fomantic UI.
2. Before get rid of `<i delete icon>`, at least, the dynamically generated dropdown selection labels should have a clear solution first.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
@wxiaoguang backport this?

**Pull request merged**
