### PR TITLE
Use vfsgen instead of go-bindata

### LINKED ISSUE #4250: go-bindata is no longer maintained
go-bindata is no longer maintained as stated here: https://github.com/jteeuwen/go-bindata#warning

We should replace it with a maintained alternative like [packr](https://github.com/gobuffalo/packr).

### PR DESCRIPTION
**Pull request by lunny**
The embed package `github.com/shurcooL/vfsgen` has been vendored and will be invoke on `go generate ./modules/...`. So gitea build process will not be broken even the embed package API changed or not maintained. This should fix #4250.

 @lafriks @tboerger maybe you can give some ideas.

@lafriks Just noticed your comment at https://github.com/go-gitea/gitea/issues/4250#issuecomment-496952264 .

### CODE REVIEW

**Comment by tboerger** [comment]
I personally use gorunpkg to execute scripts from modules instead of adding this kind of run wrapper :)

**Comment by lunny** [comment]
Script will be only invoked on mac/linux, but a go wrapper will be called much platforms.

**Comment by lunny** [comment]
It's ready to review.

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
I noticed that this PR will increase gitea start memory from 64MB to 81MB on macOS. Should I enable some compress?

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
@lunny if you think it will help - sometimes compression can actually even speed things up!

**Comment by lunny** [comment]
@zeripath yes, for public resouces(except images), we could provide compressed bytes to browser. Currently  vsfgen will always save compressed bytes on memory with a map. So for a HTTP request, it will be decompress and compress. This will waste some CPUs. I will send another PR to resolve that.

**Pull request merged**
