### PR TITLE
Remember diff view style

### PR DESCRIPTION
**Pull request by andreynering**
Whether the user choose to see the unified or split view, remember this option for the next time.

### CODE REVIEW

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM

**Comment by stevenroose** [comment]
Seems strange to store this as a string.. Any specific reason it would not be stored as an int value tied to an enum?

**Comment by andreynering** [comment]
@stevenroose I understand... I usually use a single letter for enums (would be `U` for unified and `S` for split). But here, I tried to use the existing convetion Gogs used.

**Pull request merged**
