### PR TITLE
Change "Mentioning you" filter to mean any kind of reference to the user

### PR DESCRIPTION
**Pull request by brechtvl**
Including @ mention, poster, assignee, commenter or reviewer. Effectively any issue or pull request where your name is mentioned on the page.

The reasoning is that @ mentions are a somewhat arbitrary subset of issues and pull requests that involve you. For example it's rather random if someone @ mentioned you to pull you into the conversation, or if you made a comment yourself.

Instead anything involving you is useful to find issues in a big repository where there is a lot of activity irrelevant to you.

### CODE REVIEW

**Comment by brechtvl** [comment]
The main downside I can think of here is performance, as the query is relatively complicated compared to the existing ones. I found the existing "Mentioning you" filter just not useful in practice, but maybe I'm missing some use cases.

**Comment by lunny** [comment]
But maybe we need rename `Mentioning you` to another word because it will not only include `mentioning` issues.
Another way is we can add more filters? Like `You posted`, `Assigned to you`, `Reviewed by you` and etc.

**Comment by brechtvl** [comment]
Maybe "Involving you" is better? Or something along the lines of "Your Issues" or "Your Activity", though I don't think either of those sound right.

The problem with more filters I find is that they overlap a lot, so that clicking through the filters means you encounter the same issues or pulls multiple times. It's more conceptually clear but seems less convenient in practice.

For me it would also be convenient to have a list of issues I commented on or was mentioned in, but where I'm not a creator, assignee or reviewer. But communicating that behavior to users seems too difficult.

I now noticed GitHub has the same "Mentioning" filter that only includes @ mentions. Maybe that means there are users interested in specifically that? Though I personally can't think of cases where I would not want to see issues or pulls I commented on in the same list.

**Comment by brechtvl** [comment]
I'll close this in favor of #22927 which addresses the main thing I want.

I still think the `Mentioning you` filter is not that useful as is, but this gets a bit into tricky design topics.

**Pull request closed without merging**
