### PR TITLE
Make actions default enabled for newly created repository if global configuraion enabled

### PR DESCRIPTION
**Pull request by lunny**
Users can still use `[repository].DEFAULT_REPO_UNITS=` to define the default units.

### CODE REVIEW

**Review by a1012112796 — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
It seems to be suitable to be backported?

**Comment by denyskon** [comment]
Is it really a good idea? I think that there are more repos that do not need Actions than those that do. Basically the same argument, if your specific instance needs Actions nearly every time, you can enable it through the config - but I'd leave it disabled per default.

**Comment by wxiaoguang** [comment]
> Is it really a good idea? I think that there are more repos that do not need Actions than those that do. Basically the same argument, if your specific instance needs Actions nearly every time, you can enable it through the config - but I'd leave it disabled per default.

IMO the enabled "actions" feature doesn't harm anyone, if you don't use it.

**Comment by lunny** [comment]
> Is it really a good idea? I think that there are more repos that do not need Actions than those that do. Basically the same argument, if your specific instance needs Actions nearly every time, you can enable it through the config - but I'd leave it disabled per default.

But many people do not use projects, pull requests packages, wiki but those are enabled by default, why actions is special?

**Review by appleboy — APPROVED** [review]

**Pull request merged**
