### PR TITLE
Make PKCS8, PEM and SSH2 keys work

### LINKED ISSUE #7581: Remove broken support for PEM-encoded SSH public keys
Trying to add a PEM-encoded public SSH key like

````
-----BEGIN RSA PUBLIC KEY-----
MIIBigKCAYEA7lqx/TJQQBSbMRNrwp+uAnBo2wTB/8Awb63Z8GwvDAH12Jz9JWYy
SE5ZglIw/JZ9h1zAK3F/ka8w0brLrzlQWyumjN1Rso4esl4yEOKbOdEDrA/rGyxJ
7wlUO8krU4Wd+BDo5yp/n+ugM6kEbrYSDKgFk/1g13kBiW3aLj5rlMYUJiy6hZkn
tSSVJ8w6zY6yj23UAgc2JmeAzSzutAx5NHeDdTeYl98nhu44JGNKkxHBCrAUizp0
FcNhMoApzONhStKJ2EhbXic2aasMTb91EzRW/7flJBJVtQLxOoQUYmzKKQGJJCkw
KJQuOj9GqtDDvV2v3meBUoTJE86j4Uu3TBAAhnH9XUGvploI6WrLm3n+Jp9Y/XJI
S65fqu9xBCoEl64jLf4dFSuCMRK02MAQV2siIRyIui3M4O5K5UEOwaReuVOOWzMj
vRoGeXYhMfuBA432qQTAtC6gBIn9UcejPdk2f5KErOhJeYGue3pHOagx3l7NWfZt
fEFyGifkl9k/AgMBAAE=
-----END RSA PUBLIC KEY-----
````
on a user or repo results in this weird error coming from [here](https://github.com/go-gitea/gitea/blob/bcbc9f33d73393c47b27793ac91b8f9faf98d349/models/ssh_key.go#L91):
````
extractTypeFromBase64Key: invalid key format: not enough length 813826442
````

This has probably been broken for years.

### PR DESCRIPTION
**Pull request by zeripath**
Fix #7581

### CODE REVIEW

**Comment by lafriks** [comment]
Can you add test also for ssh2 key?

**Comment by silverwind** [comment]
Tested this, unfortunately both test cases in the issue did not work.

With the SSH2 case, I got a 500 in the UI and this in the log:
```
2019/07/24 21:47:07 models/ssh_key.go:456:AddPublicKey() [T] ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEApoYJFnGDNis/2oCT6/h9Lzz2y0BVHLv8joXMs4SYcYUVwBxNzqJsDWbikBn/h32AC36qAW24Bft+suGMtJGS3oSX53qR7ozsXs/DlCO5FzRxi4JodStiYaz/pPK24WFOb4sLXr758tz2u+ZP2lfDfzn9nLxregZvO9m+zpToLCWlXrzjZxDesJOcfh/eszU9KUKXfXn6Jsey7ej8TYqB2DgYCfv8jGm+oLVeUOLEl7fxzjgcDdiLaXbqq7dFoOsHUABBV6kaXyE9LmkbXZB9lQ==
2019/07/24 21:47:07 ...user/setting/keys.go:96:KeysPost() [E] AddPublicKey: calcFingerprintSSHKeygen: 'ssh-keygen -lf /home/git/tmp/gitea_keytest263200511' failed with error 'exec(7:AddPublicKey) failed: exit status 255(<nil>) stdout:  stderr: /home/git/tmp/gitea_keytest263200511 is not a public key file.\01503d
	': /home/git/tmp/gitea_keytest263200511 is not a public key file.\01503d
```

With the PEM one, I get this error in the UI:

```
Can not verify your SSH key: failed to parse DER encoded public key: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:385 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue: tag: stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @4
```

**Comment by silverwind** [comment]
Looks my SSH2 key was broken, generated a fresh one, it did successfully import:

````
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "a comment"
AAAAB3NzaC1kc3MAAACBALxXNF58qO1TJGzqu7EWh6or9L3lGssPmt9dBrBIPWfRQb02Xp
hhshjahXKvlhT9eTHPvSJ0Vb96JA+xCE6+NjQtuslgScsrOnKOLSmBF/tuo5ya+XtxGpFe
2RGW/0ayIbQZNg6SIlPJKvxDsjqQ7v0VgW00ekS01XGZDQdBFoI3AAAAFQCg1viT5/u1C8
nI2Q7Fvha1sewEDwAAAIEAlhS65Nz0tmSMuy8qcwnAziZR1dIy0G2+cuDScrLZ/l+S07Sy
C/CKkhgIldJ+9eUJKlbsOwp23+i6O+JM7P7xy8gdPKiH5wZkv+6V6Uh36HmCN6E5dncaU+
aDnThefawG5dtA8fSfhsA4xMJYPyv1jyp3Mb1Irws6v9TXt0Vjq84AAACBAK20hgAcXwNF
CqaGxixOlbwsxynOLkkxtpUsCOHIIZvfwvUJJ17CI+fgHaguh2ObQYuPkcGVt215lekybo
F7EB1Vq1xMaZAxD9Rj7SRry8G7HdjdCyKj/nI+rKl9dLREd3QO060paHtbNJPB4hwphOAl
1Kppf632Bw/6oOXvJxem
---- END SSH2 PUBLIC KEY ----
````

Feel free to add it as a test case.

**Comment by silverwind** [comment]
Can't seem to get PEM to work, tought. You can generate one via `ssh-keygen -t rsa -m pem -f tempfile`

**Comment by zeripath** [comment]
@silverwind How were you adding these PEM cases?

**Comment by zeripath** [comment]
So I was actually using `-m pkcs8` not `-m pem`. Let me check.

**Comment by zeripath** [comment]
Done.

**Comment by zeripath** [comment]
If anyone has good documentation for this stuff I'd be really happy to read (skim) through it.

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Sorry about that @silverwind although I was aware of the difference I'd forgotten it during testing and because you use pem to decode both before interpreting the asn.1 data differently. 

PEM encoded RSA keys literally just an asn.1 modulus and prime encoded as PEM whereas pkcs8 is a slightly more complex asn.1 structure also encoded as PEM.

We probably can use the pem block to choose rather than just attempt to decode but you can't actually mistake either case for the other this way round - so I think this might actually be more robust.

**Comment by silverwind** [comment]
Will retest later. One more minor thing: Can you ensure that trying to add this invalid key does propagate the errror back to the UI and not cause a 500?

```
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20160816"
AAAAB3NzaC1yc2EAAAABJQAAAQEApoYJFnGDNis/2oCT6/h9Lzz2y0BVHLv8joXM
s4SYcYUVwBxNzqJsDWbikBn/h32AC36qAW24Bft+suGMtJGS3oSX53qR7ozsXs/D
lCO5FzRxi4JodStiYaz/pPK24WFOb4sLXr758tz2u+ZP2lfDfzn9nLxregZvO9m+
zpToLCWlXrzjZxDesJOcfh/eszU9KUKXfXn6Jsey7ej8TYqB2DgYCfv8jGm+oLVe
UOLEl7fxzjgcDdiLaXbqq7dFoOsHUABBV6kaXyE9LmkbXZB9lQ==
---- END SSH2 PUBLIC KEY ----

**Comment by zeripath** [comment]
OK @silverwind that's done. I've just added a final sanitisation step of trying to parse the regenerated authorized keys line.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
If we decide to backport this, #7522 should be included as well in the backport PR (don't want to backport that one alone as I think it may have regressed SSH2 keys).

**Comment by zeripath** [comment]
Hmm... It could be worth backporting as it's rather self contained and it does fix a bug in 1.9. What do the others think?

**Pull request merged**
