### PR TITLE
Update to go-git v5.1.0

### LINKED ISSUE #9938: sub-branches throw 500
- Gitea version (or commit ref): 1.9.3 built with go1.13.1
- Git version: 2.23.0
- Operating system: FreeBSD (Freenas)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
I'm able to create a feature/nameoffeature branch but when I try to load it on gitea it throws 500 errors
...

## Screenshots

image

### PR DESCRIPTION
**Pull request by zeripath**
Update to go-git v5.1.0.

Fix #9938

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
I suspect that we should probably backport this to 1.12 and possibly 1.11 as #9938 badly affects our FreeBSD users.

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
I can confirm the fix is there, @kevans91's PR https://github.com/go-git/go-git/pull/39 is included in 5.1.0 release of go-git per the release notes: https://github.com/go-git/go-git/releases/tag/v5.1.0 (and I can also see the code change in the vendor dir)

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
"backport" -> #11941

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
