### PR TITLE
Refix notification bell placement

### LINKED ISSUE #20245: fix for mobile view messed up non-mobile view
the fix of https://github.com/go-gitea/gitea/pull/20236 does indeed hide the "non-mobile" bell in the mobile view (as it's supposed to), however, the bell in my "non-mobile" toolbar got a little messed up as a result.

you can see in the picture that it's positioned a little above the toolbar centerline, compared to surrounding elements.

pic:
image

_Originally posted by @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf in https://github.com/go-gitea/gitea/pull/20236#pullrequestreview-1028415075_

### PR DESCRIPTION
**Pull request by zeripath**
The use of `m-4 text black` for the notification bell results in this
icon being shifted upwards. Instead we should use the `item` class but
adjust `not-mobile` and `mobile-only` to make their `display: none`
settings `!important`.

(As an aside: This is probably one of the only times we should use
`!important` in our less files and the rest should be avoided or
removed.)

Ref #20069
Revert #20236
Fix #20245

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf

@tyroneyeh 

Does this work for you?

**Comment by tyroneyeh** [comment]
Looks like it should be fine, thanks

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf
> 
> @tyroneyeh
> 
> Does this work for you?

let me do a clean rebuild after applying the patch.

this should then also fix https://github.com/go-gitea/gitea/issues/20245.

**Comment by zeripath** [comment]
Yeah sorry I forgot you'd opened a bug from the comment!

**Comment by zeripath** [comment]
I suspect that the `!important` should help other things too.

**Review by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf — COMMENTED** [review]
works well, I'd officially approve if I could (apparently only maintainers can do that now)...

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]
> works well, I'd officially approve if I could (apparently only maintainers can do that now)...

I'll do it for you :)

**Comment by zeripath** [comment]
make lgtm work

**Comment by lunny** [comment]
LGTM

**Pull request merged**
