### PR TITLE
[UI] swagger UI: hide iretating search field

### LINKED ISSUE #8184: swagger returns an error
- Gitea version (or commit ref): 1.9.2
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/api/swagger)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
swagger returms an error if click "explore" with empty search argument

image

### PR DESCRIPTION
**Pull request by 6543**
## remove this:
Bildschirmfoto zu 2019-12-31 00-28-38

close #8184

### CODE REVIEW

**Comment by 6543** [comment]
for reviewers:
```diff
-.download-url-wrapper{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-flex:3;-ms-flex:3;flex:3;-webkit-box-pack:end;-ms-flex-pack:end;justify-content:flex-end}.swagger-ui
+.download-url-wrapper{visibility: hidden}.swagger-ui
```

**Comment by lafriks** [comment]
Can this better be fixed first upstream as an option to disable it?

**Comment by 6543** [comment]
@lafriks I asked on there Slack:
me: ...how can I disable/remove this: `<the picture>`
casualjim: "I don't know probably some css rule to hide it, swagger ui is not our project"

so I did ...

**Comment by lafriks** [comment]
Maybe we can use https://github.com/swagger-api/swagger-ui/ more directly

**Comment by zeripath** [comment]
I'm approving - see my comments on discord.

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
Rather than messing with vendored CSS, perhaps we should just remove the topbar via config?

**Comment by 6543** [comment]
Tryed .. if you know how it works, woud be great :)

**Comment by jolheiser** [comment]
Based on [this comment](https://github.com/swagger-api/swagger-ui/issues/3229#issuecomment-336556255)

1. Remove `SwaggerUIStandalonePreset` from `presets`  
2. Remove `layout: "StandaloneLayout" `

https://github.com/go-gitea/gitea/blob/9600c27085df3f895b2128f1b77aa0ce0b57e7f2/templates/swagger/ui.tmpl#L82-L96

**Comment by 6543** [comment]
@jolheiser works but style would cange too ... :

Bildschirmfoto zu 2020-01-01 15-00-17

**Comment by jolheiser** [comment]
Yes, it removes the topbar completely.  
Other people can chime in, but personally I'd prefer this so it doesn't become a gotcha when updating vendor files.

**Comment by 6543** [comment]
@jolheiser done

**Comment by 6543** [comment]
@zeripath are you still ok with this?

**Review by lafriks — APPROVED** [review]

**Pull request merged**
