### PR TITLE
Change access token UI to select dropdowns

### PR DESCRIPTION
**Pull request by jtran**
The current UI to create API access tokens uses checkboxes that have a complicated relationship where some need to be checked and/or disabled in certain states.  It also requires that a user interact with it to understand what their options really are.

This branch changes to use `<select>`s.  It better fits the available options, and it's closer to [GitHub's UI](https://github.com/settings/personal-access-tokens/new), which is good, in my opinion.  It's more mobile friendly since the tap-areas are larger.  If we ever add more permissions, like Maintainer, there's a natural place that doesn't take up more screen real-estate.

This branch also fixes a few minor issues:

- Hide the error about selecting at least one permission after second submission
- Fix help description to call it "authorization" since that's what permissions are about (not authentication)

Related: #24767.

Screenshot 2023-06-07 at 5 07 34 PM

---

When it's open:

Screenshot 2023-06-07 at 5 07 59 PM

### CODE REVIEW

**Comment by silverwind** [comment]
We don't normally use plain `<select>` and the chevron on right looks a bit off and can not be fixed. So I would suggest using Fomantic selection dropdowns instead.

**Comment by jtran** [comment]
> We don't normally use plain `<select>` and the chevron on right looks a bit off and can not be fixed easily. So I would suggest using Fomantic selection dropdowns instead.

I specifically asked whether I need to use Fomantic in Discord because the feature I need is broken, and I was told that it was preferred to _not_ use Fomantic.  So who should I listen to?

**Comment by silverwind** [comment]
I do welcome using plain select and I can accept these, but a solution to align the chevrons would be nice. I will try something to get these looking better and push it to this PR then.

**Review by silverwind — APPROVED** [review]
I guess I can accept the suboptimal chevron styling for now and it can be iterated on later.

**Comment by jtran** [comment]
Based on my research, you cannot position the arrow of a select.  You can only turn off the built-in with `appearance: none` and add a completely custom arrow/chevron.  If we want this, it seems like we should have a uniform solution for all `<select>`s, and that seems out of scope for this PR.

**Comment by silverwind** [comment]
Yes, `appearance: none` and a pseudo element with the SVG mask added in https://github.com/go-gitea/gitea/pull/25098 would be the way to go.

**Comment by jtran** [comment]
@silverwind, thank you for pointing me to the other PR.  I changed it to be similar to that and updated the screenshots in the PR description.  I also tested the arc-green theme.  Hopefully it's better.

**Comment by silverwind** [comment]
1. We should apply this styling to all native select elements, not just these ones, e.g. `select` selector.
2. We can avoid duplicating the mask as it's just rotated variant by only defining the "down" variant and change the rotation in the other use case.

**Comment by silverwind** [comment]
I can't push to this branch, so could you instead `git am` this patch: [gitea-select.patch](https://github.com/go-gitea/gitea/files/11725870/gitea-select.patch)? It moves the styling to a global `gitea-select` class, making it generally useful.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
