### PR TITLE
Fix align issues and decrease avatar size on PR timeline

### PR DESCRIPTION
**Pull request by CirnoT**
Extension on https://github.com/go-gitea/gitea/pull/11623; as per https://github.com/go-gitea/gitea/pull/11623#issuecomment-633742363

chrome_2020-05-30_00-15-46

chrome_2020-05-30_00-18-53

chrome_2020-05-30_00-19-14

- Few vertical align issues solved and hacks removed
- Referenced issue title aligned to avatar
- Reduced avatar size on timeline to 20px (same as GitHub)

### CODE REVIEW

**Comment by silverwind** [comment]
Maybe increase the margin between timeline icon and avatar/text slightly. It looks a bit crammed.

**Comment by CirnoT** [comment]
Don't agree actually, and In fact it was not changed at all from what we have now.

**Review by silverwind — APPROVED** [review]
Guess it's actually fine

**Review by mrsdizzie — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Make lgtm work

**Pull request merged**
