### PR TITLE
Add localization docs

### PR DESCRIPTION
**Pull request by jolheiser**
This is also briefly mentioned in the [FAQ](https://docs.gitea.io/en-us/faq/#translation-is-incorrect-how-to-add-more-translations), however this page has been "TBD" for a while and it probably makes sense to give clarity.

locale

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
A thought, maybe we could have a drone step that looks at PRs attempting to merge into master for changes to non-english translations and fail with a link to crowdin, as that may help with reducing code-review feedback that a maintainer has to do, as the CI could then just report it.

**Comment by jolheiser** [comment]
> A thought, maybe we could have a drone step that looks at PRs attempting to merge into master for changes to non-english translations and fail with a link to crowdin, as that may help with reducing code-review feedback that a maintainer has to do, as the CI could then just report it.

This sounds great. However, can Drone report it directly to the PR page? If it's just in the Drone logs, I'm not sure how many translation passersby would see it without someone else telling them.

Is there any way it could automatically create a comment on the PR if it detects it? (Or if not, perhaps some service that could?)

**Comment by techknowlogick** [comment]
Possible with using Github/Gitea API

**Review by zeripath — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
