### PR TITLE
Implement Default Webhooks

### PR DESCRIPTION
**Pull request by aunger**
Partially implement #770. (This is only webhooks, not git hooks.)

- Add "Default Webhooks" page in site admin UI.
- Persist to the existing webhooks table, but store with RepoID=0 and OrgID=0.
- Add a few handlers and templates, but mostly modify the existing ones to serve double-duty. I should point out that installations that have customized the webhooks templates (probably uncommon) will need to edit them to accomodate a slight change in the semantics of .BaseLink.
- Upon repo creation, copy the set of default webhooks into the new repo.
- A repo owner may delete or edit these webhooks if he doesn't like the defaults.

### CODE REVIEW

**Comment by aunger** [comment]
It's been a while.  Should I merge master into this branch now to make review easier, or is it best to wait?

**Comment by aunger** [comment]
I'm confused about why drone failed.  Is it a drone bug, or something I did wrong?

**Comment by techknowlogick** [comment]
@aunger let me re-trigger drone.

**Comment by aunger** [comment]
Thanks for your help, @techknowlogick, but I've tried Discord a few times and don't get much response. Would you mind doing the review yourself?

@lunny, would you review this too? I see you hearted it. It's been languishing for two months now.

Thanks.

**Comment by lunny** [comment]
@aunger I will review and test it. but that maybe spend my some time.

**Comment by lunny** [comment]
LGTM

**Comment by aunger** [comment]
@ethantkoenig Mind reviewing this PR? This would turn one of your ufw customizations into an admin setting. https://github.com/unfoldingWord-dev/gogs/blob/a2489be2c7ab4d3d20838135bb1d538c2eb5f40c/models/repo.go#L1363

**Comment by ethantkoenig** [comment]
@aunger I won't be able to, sorry.

**Comment by lafriks** [comment]
Can default webhooks be stored to new table, so that this functionality could be later extended more easily?

**Comment by aunger** [comment]
@lafriks Someone could certainly implement it that way. This PR's KISS approach is better in some ways though, because the plumbing is more easily shared (don't need an abstraction of a webhook if they are all the same) and it requires less attention to table schemas. What future extensions do you have in mind?

**Comment by lafriks** [comment]
@aunger I would like to have ability to have forced webhooks for all repositories, updating webhooks for repositories when changing default webhook, ability to select/deselect from default webhooks in repository settings etc

**Comment by aunger** [comment]
@lafriks Great ideas. Site-wide hooks are more flexible. I was weighing most of that before I implemented this, but I didn't get any feedback (https://github.com/go-gitea/gitea/issues/770#issuecomment-398274022), so I decided to go simple ("agile"?) with this implementation, because it's all my organization needs right now (and because it's what #770 explicitly asked for).

**Comment by aunger** [comment]
@lafriks I won't tackle site-wide hooks right now. If you're going to code it up now, that's awesome. If not, I hope you consider merging this implementation in the meantime. Thanks.

**Review by sapk — APPROVED** [review]

**Pull request merged**
