### PR TITLE
Unit tests and bug fix for models/org

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes a SQL bug in `CountRepos()`, removes unused functions from `models/org.go`, and remove a unneeded load from database in `RemoveOrgUser()`

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
why close this

**Comment by ethantkoenig** [comment]
I accidentally deleted the branch on my fork, so the PR automatically closed. I couldn't figure out how to reopen it, so I just issued a new one (#776)

**Comment by lunny** [comment]
OK

**Pull request closed without merging**
