### PR TITLE
Fix dropzone JS error when attachment is disabled

### LINKED ISSUE #31485: Issue comments are not updated after editing (if attachments are disabled)
### Description

Attempting to edit a comment and then save it results in a javascript error withn repo-issue-edit.js, if attachments are disabled.

To reproduce:

* disable support for attachments
(https://docs.gitea.com/administration/config-cheat-sheet#issue-and-pull-request-attachments-attachment - set enabled to false)

From the UI:

* create new issue
* add a comment
* edit that comment
* saving the edit will throw a javascript error in the saveAndRefresh method in repo-issue-edit.js, when attempting to iterate through dropzoneInst

This appears to be a new issue introduced in 1.22. 

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Helm gitea chart 

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #31485

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
What was the JS error? `params` being empty?

**Comment by silverwind** [comment]
Actually I'm not sure the fix is correct because `querySelectorAll` result is always iterable, even if empty. Would the proper fix not be `dropzoneInst?.element.querySelectorAll` in case the error was that the element did not exist?

**Comment by ukct** [comment]
The specific error thrown is
`un?.element.querySelectorAll is not iterable (cannot read property Symbol(Symbol.iterator))`

dropzoneInst is null when it fails.

**Comment by silverwind** [comment]
I can't seem to reproduce the original issue on either main branch or 1.22 branch with `attachment.ENABLE = false`.

All I can say for sure is that this ` ?? []` does nothing because `querySelectorAll` results are guaranteed to be iterable, so the root cause must be something else.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> I can't seem to reproduce the original issue on either main branch or 1.22 branch with `attachment.ENABLE = false`.
> 
> All I can say for sure is that this ` ?? []` does nothing because `querySelectorAll` results are guaranteed to be iterable, so the root cause must be something else.

1. The root regression is  #29272, it breaks the dropzone uploading, and it caused the null access because `dz` is null if the attachment is disabled.
2. Some following up changes do not complete fix the `null` problem, `foo?.bar()` always returns null if `foo` doesn't exist, no matter what `bar()` does.

**Comment by silverwind** [comment]
Please explain how this addition of `?? []` fixes anything here.

**Comment by silverwind** [comment]
Ah I understand now. Yes when the optional chain is triggered, we need the fallback.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
