### PR TITLE
Git LFS support

### LINKED ISSUE #3732: Build error with 0.9.99.0915
- Gogs version (or commit ref): 0.9.99.0915
- Git version: 2.5.4 (Apple Git-61)
- Operating system: OSX deploying to Dokku on vagrant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
[INFO] Setting version for gopkg.in/redis.v2 to e6179049628164864e6e84e973cfb56335748dea.
+ make build TAGS=sqlite cert pam
fatal: Not a git repository (or any of the parent directories): .git
go install "-v" -ldflags '-X "github.com/gogits/gogs/modules/setting.BuildTime=2016-10-05 06:03:23 UTC" -X "github.com/gogits/gogs/modules/setting.BuildGitHash="' -tags 'sqlite cert pam'
github.com/gogits/gogs/vendor/github.com/Unknwon/cae
github.com/gogits/gogs/vendor/github.com/Unknwon/cae/zip
github.com/gogits/gogs/vendor/github.com/Unknwon/com
github.com/gogits/gogs/vendor/github.com/go-macaron/inject
github.com/gogits/gogs/vendor/gopkg.in/ini.v1
github.com/gogits/gogs/vendor/gopkg.in/macaron.v1
github.com/gogits/gogs/vendor/github.com/go-macaron/binding
github.com/gogits/gogs/vendor/github.com/go-macaron/cache
github.com/gogits/gogs/vendor/github.com/go-macaron/captcha
github.com/gogits/gogs/vendor/github.com/go-macaron/session
github.com/gogits/gogs/vendor/github.com/go-macaron/csrf
github.com/gogits/gogs/vendor/github.com/klauspost/cpuid
github.com/gogits/gogs/vendor/github.com/klauspost/compress/flate
github.com/gogits/gogs/vendor/github.com/klauspost/crc32
github.com/gogits/gogs/vendor/github.com/klauspost/compress/gzip
github.com/gogits/gogs/vendor/github.com/go-macaron/gzip
github.com/gogits/gogs/vendor/github.com/Unknwon/i18n
github.com/gogits/gogs/vendor/golang.org/x/text/internal/tag
github.com/gogits/gogs/vendor/golang.org/x/text/language
github.com/gogits/gogs/vendor/github.com/go-macaron/i18n
github.com/gogits/gogs/vendor/github.com/go-macaron/toolbox
github.com/gogits/gogs/vendor/github.com/go-xorm/core
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm
github.com/gogits/gogs/vendor/github.com/mcuadros/go-version
github.com/gogits/gogs/vendor/github.com/gogits/git-module
github.com/gogits/gogs/vendor/github.com/gogits/go-gogs-client
github.com/gogits/gogs/vendor/github.com/go-sql-driver/mysql
github.com/gogits/gogs/vendor/github.com/gogits/chardet
github.com/gogits/gogs/modules/log
github.com/gogits/gogs/vendor/github.com/bradfitz/gomemcache/memcache
github.com/gogits/gogs/vendor/github.com/go-macaron/cache/memcache
github.com/gogits/gogs/vendor/gopkg.in/bufio.v1
github.com/gogits/gogs/vendor/gopkg.in/redis.v2
github.com/gogits/gogs/vendor/github.com/go-macaron/cache/redis
github.com/gogits/gogs/vendor/github.com/go-macaron/session/redis
github.com/gogits/gogs/modules/bindata
github.com/gogits/gogs/modules/user
github.com/gogits/gogs/vendor/github.com/strk/go-libravatar
github.com/gogits/gogs/modules/setting
github.com/gogits/gogs/modules/base
github.com/gogits/gogs/vendor/github.com/satori/go.uuid
github.com/gogits/gogs/models/migrations
github.com/gogits/gogs/vendor/gopkg.in/asn1-ber.v1
github.com/gogits/gogs/vendor/gopkg.in/ldap.v2
github.com/gogits/gogs/modules/auth/ldap
github.com/gogits/gogs/vendor/github.com/msteinert/pam
github.com/gogits/gogs/modules/auth/pam
github.com/gogits/gogs/vendor/github.com/issue9/identicon
github.com/gogits/gogs/modules/avatar
github.com/gogits/gogs/modules/httplib
github.com/gogits/gogs/vendor/golang.org/x/net/html/atom
github.com/gogits/gogs/vendor/golang.org/x/net/html
github.com/gogits/gogs/vendor/github.com/jaytaylor/html2text
github.com/gogits/gogs/vendor/gopkg.in/gomail.v2
github.com/gogits/gogs/modules/mailer
github.com/gogits/gogs/vendor/github.com/microcosm-cc/bluemonday
github.com/gogits/gogs/vendor/github.com/shurcooL/sanitized_anchor_name
github.com/gogits/gogs/vendor/github.com/russross/blackfriday
github.com/gogits/gogs/modules/markdown
github.com/gogits/gogs/modules/process
github.com/gogits/gogs/modules/sync
github.com/gogits/gogs/modules/template/highlight
github.com/gogits/gogs/vendor/github.com/lib/pq/oid
github.com/gogits/gogs/vendor/github.com/lib/pq
github.com/gogits/gogs/vendor/github.com/mattn/go-sqlite3
github.com/gogits/gogs/vendor/github.com/nfnt/resize
github.com/gogits/gogs/vendor/github.com/sergi/go-diff/diffmatchpatch
github.com/gogits/gogs/vendor/golang.org/x/crypto/curve25519
github.com/gogits/gogs/vendor/golang.org/x/crypto/ed25519/internal/edwards25519
github.com/gogits/gogs/vendor/golang.org/x/crypto/ed25519
github.com/gogits/gogs/vendor/golang.org/x/crypto/ssh
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/internal/identifier
github.com/gogits/gogs/vendor/golang.org/x/text/transform
github.com/gogits/gogs/vendor/golang.org/x/text/encoding
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/internal
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/charmap
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/japanese
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/korean
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/simplifiedchinese
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/traditionalchinese
github.com/gogits/gogs/vendor/golang.org/x/text/internal/utf8internal
github.com/gogits/gogs/vendor/golang.org/x/text/runes
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/unicode
github.com/gogits/gogs/vendor/golang.org/x/text/encoding/htmlindex
github.com/gogits/gogs/vendor/golang.org/x/net/html/charset
github.com/gogits/gogs/models
# github.com/gogits/gogs/models
models/access.go:84: cannot use x (type *xorm.Engine) as type Engine in argument to accessLevel:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/access.go:94: cannot use x (type *xorm.Engine) as type Engine in argument to hasAccess:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/access.go:245: cannot use x (type *xorm.Engine) as type Engine in argument to r.recalculateAccesses:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/action.go:194: cannot use x (type *xorm.Engine) as type Engine in argument to newRepoAction:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/action.go:217: cannot use x (type *xorm.Engine) as type Engine in argument to renameRepoAction:


r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session


models/action.go:568: cannot use x (type *xorm.Engine) as type Engine in argument to transferRepoAction:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session


rewant Where(interface {}, ...interface {}) *xorm.Session
models/action.go:586: cannot use x (type *xorm.Engine) as type Engine in argument to mergePullRequestAction:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/issue.go:154: cannot use x (type *xorm.Engine) as type Engine in argument to issue.loadAttributes:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/issue.go:231: cannot use x (type *xorm.Engine) as type Engine in argument to i.hasLabel:
r*xorm.Engine does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/issue.go:312: cannot use e (type *xorm.Session) as type Engine in argument to issue.getLabels:
r*xorm.Session does not implement Engine (wrong type for Where method)
rehave Where(string, ...interface {}) *xorm.Session
rewant Where(interface {}, ...interface {}) *xorm.Session
models/issue.go:312: too many errors
github.com/gogits/gogs/vendor/github.com/Unknwon/paginater
github.com/gogits/gogs/vendor/gopkg.in/editorconfig/editorconfig-core-go.v1
github.com/gogits/gogs/vendor/github.com/gogits/cron
github.com/gogits/gogs/vendor/github.com/urfave/cli
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 2
remote: The command '/bin/sh -c ./docker/build.sh' returned a non-zero code: 2
To dokku@my.dokku:edit
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@my.dokku:edit'
```

This error looks very similar to https://github.com/gogits/gogs/issues/3712 to me, but the latest commit should have fixed it, trying to understand why it's still happening for me.
# Description

Trying to get gogs up and running, for the first time, here are the steps I took:
- git clone https://github.com/gogits/gogs.git (git log latest commit: 2bec8a4f1ef6b48220a0010c1482e561abd55810)
- git remote add dokku dokku@dokku.me:gogs
- git push dokku master (failed due to macaron version)
- manually applied the fix (https://github.com/gogits/gogs/pull/3727/files)
- git add/commit/push again
- encounter the error shown above

### PR DESCRIPTION
**Pull request by fabian-z**
**PR as requested by @lunny, merge conflicts originate from gitea commits. I'm using [Gogs](https://github.com/gogits/gogs) as upstream so I can't promise to correct those. Original PR: gogits/gogs#3868**

Feature requested in gogits/gogs#1322 

This PR implements Git LFS support for Gogs, supporting the [legacy v1 API](https://github.com/github/git-lfs/blob/master/docs/api/v1/http-v1-legacy.md) as well as the current [batch v1 API](https://github.com/github/git-lfs/blob/master/docs/api/v1/http-v1-batch.md).

Originally imported LFS server code base from https://github.com/git-lfs/lfs-test-server.

Features:
* Uses [recommended paths](https://github.com/github/git-lfs/tree/master/docs/api) with HTTP and SSH remotes, no custom user settings necessary
* Supports basic authentication with user credentials
* Supports [authentication with SSH](https://github.com/github/git-lfs/tree/master/docs/api) (passing JWT under the hood)
* Supports no authentication when pulling public repositories (however git-lfs still asks for credentials, where the prompt can be skipped - likely a bug in git-lfs)
* Settings transparently integrated into installation process
* Removes LFS objects when repositories are deleted. Works with forks (e.g. when parent repository is deleted)

Notes:
* https://github.com/fabian-z/gogs/commit/58375e6b8648527597339b4b4b042fa71cf41b76 was necessary to import ```github.com/dgrijalva/jwt-go```, as well as fix gogits/gogs#3732 
* ~Does not yet delete LFS objects when repository is removed~
* https://github.com/fabian-z/gogs/commit/0344f98166058a0e58d425fc5d25967c6f5901cc regenerates bindata in order to apply locale additions from https://github.com/fabian-z/gogs/commit/c166480ab0b5118ed9b7fbecb257406fdfab2daf

Looking forward to your review!

### CODE REVIEW

**Comment by lunny** [comment]
This will resolved #80

**Comment by strk** [comment]
Can you please rebase and avoid generating bindata.go in the PR ?
Also don't bother touching glide, we use govendor here

**Comment by fabian-z** [comment]
@strk 

Please read the note in my PR. I sent this PR to gogits/gogs and only copied it here on request by @lunny. As my time is limited and my upstream is Gogs, I currently won't be able to rebase / fix issues for gitea. Thanks for your understanding.

**Comment by strk** [comment]
On Tue, Nov 08, 2016 at 07:28:27AM -0800, bkcsoft wrote:

> -     "git-upload-pack":    models.ACCESS_MODE_READ,
> -     "git-upload-archive": models.ACCESS_MODE_READ,
> -     "git-receive-pack":   models.ACCESS_MODE_WRITE,
> -     "git-upload-pack":      models.ACCESS_MODE_READ,
> -     "git-upload-archive":   models.ACCESS_MODE_READ,
> -     "git-receive-pack":     models.ACCESS_MODE_WRITE,
> -     "git-lfs-authenticate": models.ACCESS_MODE_NONE,

And I think those constants are named AccessModeNone etc. now.
(but I understand the author is not interested in porting this to
Gitea)

**Comment by fabian-z** [comment]
Let me clarify on my statement.
Please correct me if I'm wrong or I misunderstood the situation, but Gitea seems to be maintained as a constantly rebased fork of Gogs (like a changeset maintained by downstream distributions). Therefore, my priority would be to get this reviewed and merged upstream with Gogs. If this is possible, a rebase would bring the feature to Gitea and the changeset which needs to be maintained can remain as small as possible.
However, my main interest is to bring this feature into active usage and to have continued development together with other contributors.
If my PR is not reviewed or merged into Gogs master in a reasonable amount of time, I'd be glad to work with you to port my changes to Gitea.

**Comment by strk** [comment]
@fabian-z you misunderstood: Gitea will never be rebased against Gogs, but rather continue on its own.
The fork was driven by the willingness to have a more open development method, so you're welcome to join the effort. You can compare Gogs and Gitea activity via the Pulse screen:

https://github.com/go-gitea/gitea/pulse
https://github.com/gogits/gogs/pulse

**Comment by fabian-z** [comment]
@strk 
Thank you for elaborating on the project status. Indeed I must have misjudged on first glance - thanks again for pointing me to the Pulse graphs.
I definitely prefer an open, collaborative development, too.
I will try to rebase this on Gitea master and provide a new PR incorporating your reviews.

**Pull request closed without merging**
