### PR TITLE
Improve queue and logger context

### PR DESCRIPTION
**Pull request by wxiaoguang**
Before there was a "graceful function": RunWithShutdownFns, it's mainly for some modules which doesn't support context.

The old queue system doesn't work well with context, so the old queues need it.

After the queue refactoring, the new queue works with context well, so, use Golang context as much as possible, the `RunWithShutdownFns` could be removed (replaced by RunWithCancel for context cancel mechanism), the related code could be simplified.

This PR also fixes some legacy queue-init problems, eg:

* typo : archiver: "unable to create codes indexer queue" => "unable to create repo-archive queue"
* no nil check for failed queues, which causes unfriendly panic

After this PR, many goroutines could have better display name:

image

image

### CODE REVIEW

**Review by delvh — APPROVED** [review]
In general, I think this change is quite good.
However, I can foresee some confused users as we simply say `couldn't initialize <x> queue` with a `log.fatal`, without providing a reason.
So, they will have to ask themselves `Is this a recurring problem or a one-time problem? And what did I do wrong?`

**Comment by delvh** [comment]
(Oops, when I started the PR wasn't WIP yet)

**Comment by wxiaoguang** [comment]
> (Oops, when I started reviewing, the PR wasn't WIP yet)

Almost ready 😄

**Comment by wxiaoguang** [comment]
> However, I can foresee some confused users as we simply say `couldn't initialize <x> queue` with a `log.fatal`, without providing a reason.

In real use case, there could also be enough error messages above such error message, eg: the levelqueue lock can't be required, redis server error, etc.

So, I think at the moment it won't confuse/mislead users. And this mechanism has been used for long time, no issue report for it.

**Comment by lunny** [comment]
Using `ctx` instead of `RunWithShutdownFns` is a highlight for me. That's Go's way.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Saw a new error on my dev setup that apparently came from this:

```
2023/05/27 10:30:38 ...les/queue/manager.go:108:]() [E] Failed to create queue "notification-service": unable to lock level db at /Users/silverwind/git/gitea/data/queues/common: resource temporarily unavailable
2023/05/27 10:30:38 ...otification/ui/ui.go:42:NewNotifier() [F] Unable to create notification-service queue
```

I deleted that folder and after gitea restart, the error was gone and the folder contents re-created. This was the content before:

```
$ ll /Users/silverwind/git/gitea/data/queues/common
-rw-r--r-- 1 silverwind staff  159 Apr 25 18:08 005718.ldb
-rw-r--r-- 1 silverwind staff  681 May 27 09:44 006368.log
-rw-r--r-- 1 silverwind staff  814 May 27 09:17 006370.ldb
-rw-r--r-- 1 silverwind staff   16 May 27 09:14 CURRENT
-rw-r--r-- 1 silverwind staff   16 May 27 09:14 CURRENT.bak
-rw-r--r-- 1 silverwind staff    0 Aug 17  2021 LOCK
-rw-r--r-- 1 silverwind staff 656K May 27 09:17 LOG
-rw-r--r-- 1 silverwind staff 1.1M Oct 18  2022 LOG.old
-rw-r--r-- 1 silverwind staff  565 May 27 09:17 MANIFEST-006369
```

**Comment by wxiaoguang** [comment]
I think it is air's problem

`make watch` (air) concurrent process problem #24845

**Comment by silverwind** [comment]
Could be that there was a gitea zombie process hanging around, yeah.

**Comment by wxiaoguang** [comment]
IMO it's not zombie, it's duplicate process.

Using channel queue won't cause the levelqueue lock race, but the listening port (and maybe some other resources) still races. Indeed Gitea wasn't designed  to have two web processes running at the same time.

If there are other queue bugs, let's find the root problems and fix the bugs.

**Pull request merged**
