### PR TITLE
Refactor docs

### PR DESCRIPTION
**Pull request by jolheiser**
This PR refactors the docs and moves some things from `advanced` to a new `developers` sections, as some of them may be more appropriate for someone looking to integrate rather than an end-user.

It also removes the CI/CD and Third-party pages in lieu of an Integrations page that directs users to `awesome-gitea` with some examples of what they will find.

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for giving some love to the docs. Improving the docs is always appreciated. Could you also add some redirects from the deleted pages to the new location, here is the redirect file: https://github.com/go-gitea/gitea/blob/d84490a0df308f0783637e39bf5302128f9f8584/docs/static/_redirects and here are docs from netlify on the redirect format: https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

**Review by lunny — APPROVED** [review]

**Comment by jolheiser** [comment]
@techknowlogick I _think_ I got it right? I'm not sure if I can test it locally, but afaik that should be correct. Not sure if there's a better way with the `en-us` part, but I don't think I changed the other languages (other than `api-usage` because it was just a dir change).

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
technically you can test locally (using the netlify cli tool), but this LGTM and will test once merged (If we were using Github integration w/ netlify then it have a URL for each URL, but Drone works better for our workflow and will allow us to switch to gitea.com with less issues)

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
