### PR TITLE
Upgrade xorm to fix rows bug

### LINKED ISSUE #17030: runtime error: invalid memory address or nil pointer dereference
- Gitea version (or commit ref):1.15.2
- Git version:
- Operating system:docker gitea/gitea:1.15.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

    ```
    2021/09/12 17:50:21 ...odels/repo_mirror.go:117:MirrorsIterate() [I] [SQL] SELECT `id`, `repo_id`, `interval`, `enable_prune`, `updated_unix`, `next_update_unix`, `lfs_enabled`, `lfs_endpoint` FROM `mirror` WHERE (next_update_unix<=?) AND (next_update_unix!=0) [1631469021] - 25.421658ms
    2021/09/12 17:50:21 .../graceful/manager.go:135:func1() [C] PANIC during RunWithShutdownContext: runtime error: invalid memory address or nil pointer dereference
        Stacktrace: /usr/local/go/src/runtime/panic.go:212 (0x43ea5a)
        /usr/local/go/src/runtime/signal_unix.go:734 (0x458a32)
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/rows.go:92 (0xc2235b)
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/rows.go:142 (0xc22367)
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/rows.go:78 (0xc21811)
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_iterate.go:19 (0xc41316)
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_iterate.go:38 (0xc412f3)
        /go/src/code.gitea.io/gitea/models/repo_mirror.go:117 (0x146012c)
        /go/src/code.gitea.io/gitea/services/mirror/mirror.go:55 (0x2009284)
        /go/src/code.gitea.io/gitea/modules/cron/tasks_basic.go:25 (0x2018374)
        /go/src/code.gitea.io/gitea/modules/cron/tasks.go:88 (0x2017c21)
        /go/src/code.gitea.io/gitea/modules/graceful/manager.go:139 (0xc61685)
        /go/src/code.gitea.io/gitea/modules/cron/tasks.go:82 (0x2015ba4)
        /go/src/code.gitea.io/gitea/modules/cron/tasks.go:56 (0x2015a27)
        /go/src/code.gitea.io/gitea/vendor/github.com/gogs/cron/cron.go:171 (0x2004498)
        /usr/local/go/src/runtime/asm_amd64.s:1371 (0x47b360)
        
    2021/09/12 17:50:21 ...eue/queue_channel.go:98:func1() [W] ChannelQueue: task-channel Terminated before completed flushing
    2021/09/12 17:50:21 ...eue/queue_channel.go:98:func1() [W] ChannelQueue: push_update-channel Terminated before completed flushing
    2021/09/12 17:50:21 ...eue/queue_channel.go:98:func1() [W] ChannelQueue: mail-channel Terminated before completed flushing
    2021/09/12 17:50:21 ...eue/queue_channel.go:98:func1() [W] ChannelQueue: notification-service-channel Terminated before completed flushing
    2021/09/12 17:50:21 ...eful/server_hooks.go:47:doShutdown() [I] PID: 18 Listener ([::]:3000) closed.
    2021/09/12 17:50:21 .../graceful/manager.go:226:doHammerTime() [W] Setting Hammer condition
    2021/09/12 17:50:21 cmd/web.go:244:listen() [I] HTTP Listener: 0.0.0.0:3000 Closed
    2021/09/12 17:50:22 .../graceful/manager.go:243:doTerminate() [W] Terminating
    2021/09/12 17:50:22 ...er/issues/indexer.go:169:2() [I] PID: 18 Issue Indexer closed
    2021/09/12 17:50:22 cmd/web.go:161:runWeb() [I] PID: 18 Gitea Web Finished
    ```

## Description
   see log above

### PR DESCRIPTION
**Pull request by lunny**
Fix #17030

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Hmm. There's quite a few other changes in there. This is fine for the 1.16 but do we want to backport all of these to 1.15?

**Comment by zeripath** [comment]
These changes have also resulted in interface changes and our code will need to be updated.

It might be better to just backport the rows fix on to 1.2.2 instead.

**Comment by lunny** [comment]
> These changes have also resulted in interface changes and our code will need to be updated.
> 
> It might be better to just backport the rows fix on to 1.2.2 instead.

OK. I will try to do that.

**Review by axifive — APPROVED** [review]

**Review by zeripath — CHANGES_REQUESTED** [review]
I'm gonna mark this as request changes so that re-review occurs when its ready.

**Comment by delvh** [comment]
@zeripath, Hasn't that already been fixed with #17059?
Or do you expect another solution?

**Comment by zeripath** [comment]
I agree - I think the underlying problem has been solved but I think lunny might be keeping it open to test against the new xorm.

**Pull request closed without merging**
