### PR TITLE
Return 404 when public gpg key is not exist

### PR DESCRIPTION
**Pull request by a1012112796**
I think it's better than return an empty string.

### CODE REVIEW

**Comment by zeripath** [comment]
It would be better to return something like:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: This user hasn't uploaded any GPG keys.


=twTO
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by lafriks** [comment]
@zeripath why? Imho that would be confusing

**Comment by bagasme** [comment]
@a1012112796 what use case for this PR?

**Comment by zeripath** [comment]
When writing any API you should ask yourself who is expected to be calling this API.

I'm going to go out on a limb and say the user of *.gpg urls is for gpg to use them when importing keys.

Therefore the output of this should be something gpg will be able to use.

A 404 page which is not in armored key output won't work.

A blank response does work as does my suggested response.

**Comment by a1012112796** [comment]
> When writing any API you should ask yourself who is expected to be calling this API.
> 
> I'm going to go out on a limb and say the user of *.gpg urls is for gpg to use them when importing keys.
> 
> Therefore the output of this should be something gpg will be able to use.
> 
> A 404 page which is not in armored key output won't work.
> 
> A blank response does work as does my suggested response.

I see, Now it will return empty with 404 status, How about this way?

**Comment by zeripath** [comment]
Well take a look at what GH returns for say: https://github.com/go-gitea.gpg

**Comment by a1012112796** [comment]
Then it's not so necessary also.

**Comment by lafriks** [comment]
@zeripath But this was for API not Gitea web route

**Pull request closed without merging**
