### PR TITLE
Fix logger refactoring regression: manager logging add

### PR DESCRIPTION
**Pull request by wxiaoguang**
The `rotate` option is optional.

Test result:

image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
IIRC, there is a lint rule for such missed secon arguments on casts, we should probably use it.

**Comment by wxiaoguang** [comment]
I do not think we need a lint for this case.

Eg: here is a real use case: for a field `t any` , the caller1 knows its type must be T1, caller2 knows its type must be T2, so the code could be written as : `x := t.(T1)` directly for caller1. If there is any bug, the runtime panic tells the developers that "you passed incorrect type here, please fix it".


But if it's written as: `x, _ := t.(T1)` , it loses the strict type check, the caller1 just gets a default T1, which is unexpected.

If it's written as `x, ok := t.(T1)`, then you need to write another `if !ok { panic }` to show the error.

So, `x := t.(T1)`  is good enough for many cases.

**Comment by silverwind** [comment]
> If there is any bug, the runtime panic tells the developers that "you passed incorrect type here, please fix it".

Runtime panics are bad because the condition for the panic may not be hit during testing.

> If it's written as x, ok := t.(T1), then you need to write another if !ok { panic } to show the error.

I think forcing this style would be okay. Go is (overly) explicit with it's error handling, just not in this case apparently, but it could be enforced with the linter rule.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
For reference, this is the lint option I'm talking about:

```
linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
```

**Comment by lunny** [comment]
> For reference, this is the lint option I'm talking about:
> 
> ```yaml
> linters-settings:
>   errcheck:
>     # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
>     # Such cases aren't reported by default.
>     # Default: false
>     check-type-assertions: true
> ```

Maybe another PR.

**Pull request merged**
