### PR TITLE
Fix yet another bug with diff file names

### LINKED ISSUE #12768: Since 1.12.4 diff not working with blanks in filename or pathname
- Gitea version (or commit ref): 1.12.4 or master e2043987543d6b1e94afc22d145d70ddaf814898
- Git version: 2.25.1
- Operating system: ubuntu 20.04 LTS or docker-image 'gitea/gitea'
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://try.gitea.io/fashberg/testrepo/commits/branch/master (check out both commits)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea Diff shows either wrong filenames or produces HTTP 500 if there is a blank in the filename/pathname of a changed file.

This bug applies only if git, but this seems to be default, does not quote the filenames at diff output.

Bug is since  issue #12554 (#12575) - which became live in 1.12.4

### Detail
_Originally posted by @fashberg in https://github.com/go-gitea/gitea/pull/12554#issuecomment-689000779_ 

This fix breaks filenames with blanks in path (filename or foldername).

If you have
```"diff --git a/folder/filename withBlank b/folder/filename withBlank"```

you get now this wrong variable assignments:
```
a="a/folder/filename"
b="withBlank"
```
And the this two lines at https://github.com/go-gitea/gitea/blob/master/services/gitdiff/gitdiff.go#L592 
```
	a = a[2:]
	b = b[2:]
```
are deleting the first two characters resulting in
```
a="folder/filename"
b="thBlank"
```

In the diff you see a renaming ```filename → thBlank``` and if  you click on the link to 'Show File' it links to 'thBlank' which results in 404.

The bug is getting worse if the filename has only a single character after the first blank, e.g. ```test - file```

Resulting in 
```
a="a/folder/test"
b="-"
```
Because strlen of b is only 2 the substring(b, 2)/ (```b = b[2:]```) will not work because string is too short, resulting in Error 500

```
2020/09/08 15:43:06 ...les/context/panic.go:35:1() [E] PANIC:: runtime error: slice bounds out of range [2:1]
	/usr/lib/go-1.13/src/runtime/panic.go:103 (0x436882)
		goPanicSliceB: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsSliceB})
	/home/fashberg/gitea/services/gitdiff/gitdiff.go:593 (0x1d4191a)
```

So the ```middle = strings.Index(line, " b/")``` hack was not so bad.

Now filenames with blanks are completely broken in 1.12.4 and master!

Why ignoring the lines with ```--- a/xxxx``` and ```+++ b/xxxx```?
There you can cat the real filename without any quoting problems. OK, new files are having ```--- /dev/null```  and maybe there are some more special cases.

Kind Regards
Folke

### LINKED ISSUE #12816: "View File" link creates 404 in particular scenarios
- Gitea version (or commit ref): 1.12.4
- Git version : 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

When reviewing code and clicking on “View File”, sometimes the view will fail and produce a 404 error. At first I thought this was an Nginx proxy issue, but in fact what I’m seeing is that for some of the files listed on the screen fail in View File when they are apparently missing part of their name. Please note that the underlying repository seems to have all the files intact and is fine - the code compiles, etc. Further review [in the forum](https://discourse.gitea.io/t/gitea-view-file-issue/2493) by kpfleming indicated that the issue might be that files were moved under folders with the same name. In fact, that seems to be true. 

It was a much older project and originally everything in the repository was in the root folder, “attire-allowance”.
A new sub-folder under the root folder was created with the same name, “attire-allowance”.
File # 1 stayed where it was.
File # 2 was moved into the new sub-directory (also named “attire-allowance”).
Both files throw a 404 error when "View File" is clicked. The other files that show the full file name are not problematic.
...

## Screenshots

image

### PR DESCRIPTION
**Pull request by zeripath**
Following further testing it has become apparent that the diff line
cannot be used to determine filenames for diffs with any sort of predictability
the answer therefore is to use the other lines that are provided with a diff

Fix #12768
Closes #12769
Replaces #12769

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by fashberg** [comment]
@zeripath 

zeripath/gitea/tree/fix-12768-**I-hate-our-diff-infrastructure**  😁

Haha, yes, i was very surprised about the buggy function of getting the filenames from diff, one of the most basic functionality of a git-gui.

Your current approach look great.

You must not forget to trim the tab-character at the end of the filename in the +++/--- lines, it results currently in broken links at "View file" .

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
@zeripath Could you add some tests from #12768?

**Comment by zeripath** [comment]
> @zeripath
> 
> You must not forget to trim the tab-character at the end of the filename in the +++/--- lines, it results currently in broken links at "View file" .

What do you mean tab character?

```
$ git diff master | grep '^+++' | xxd 

00000000: 2b2b 2b20 622f 6d6f 6475 6c65 732f 7465  +++ b/modules/te
00000010: 6d70 6c61 7465 732f 6865 6c70 6572 2e67  mplates/helper.g
00000020: 6f0a 2b2b 2b20 622f 7365 7276 6963 6573  o.+++ b/services
00000030: 2f67 6974 6469 6666 2f67 6974 6469 6666  /gitdiff/gitdiff
00000040: 2e67 6f0a                                .go.
```

There is no tab character.

**Comment by zeripath** [comment]
oh that's interesting...

a file with spacing gets \t at the end of the line.

WHY GIT WHY?!

**Comment by zeripath** [comment]
```
$ git diff -M 25d51d73c7 25d51d73c7'^' | xxd                        [08:46:01]
00000000: 6469 6666 202d 2d67 6974 2061 2f66 696c  diff --git a/fil
00000010: 6520 7769 7468 2062 6c61 6e6b 7320 622f  e with blanks b/
00000020: 6669 6c65 2077 6974 6820 626c 616e 6b73  file with blanks
00000030: 0a64 656c 6574 6564 2066 696c 6520 6d6f  .deleted file mo
00000040: 6465 2031 3030 3634 340a 696e 6465 7820  de 100644.index 
00000050: 3839 3836 3531 612e 2e30 3030 3030 3030  898651a..0000000
00000060: 0a2d 2d2d 2061 2f66 696c 6520 7769 7468  .--- a/file with
00000070: 2062 6c61 6e6b 7309 0a2b 2b2b 202f 6465   blanks..+++ /de
00000080: 762f 6e75 6c6c 0a40 4020 2d31 2c35 202b  v/null.@@ -1,5 +
00000090: 302c 3020 4040 0a2d 6120 626c 616e 6b20  0,0 @@.-a blank 
000000a0: 6669 6c65 0a2d 0a2d 6861 7320 6120 636f  file.-.-has a co
000000b0: 7570 6c65 206f 206c 696e 650a 2d0a 2d74  uple o line.-.-t
000000c0: 6865 2035 7468 206c 696e 6520 6973 2074  he 5th line is t
000000d0: 6865 206c 6173 740a                      he last.
```

**Comment by fashberg** [comment]
Hi @zeripath 

GNU itself says: blanks are not supported: https://www.gnu.org/software/diffutils/manual/html_node/Unusual-File-Names.html#Unusual%20File%20Names

They append a timestamp after the filename: https://www.gnu.org/software/diffutils/manual/html_node/Example-Unified.html#Example-Unified  - but this cannot be seen at GIT

GIT adds a 'tab' character after the ---/+++ filename, if it contains a blank

Take a look: https://github.com/git/git/blob/master/diff.c#L1504 

```c
	case DIFF_SYMBOL_FILEPAIR_MINUS:
		meta = diff_get_color_opt(o, DIFF_METAINFO);
		reset = diff_get_color_opt(o, DIFF_RESET);
		fprintf(o->file, "%s%s--- %s%s%s\n", diff_line_prefix(o), meta,
			line, reset,
			strchr(line, ' ') ? "\t" : "");
		break;
```

test:

```sh
cd testrepo 
date > 'testfile'
date > 'testfile A'
git add testfile*
git commit -m 'test"
git log -p -n 1 | grep "+++" | xxd
```

```sh
00000000: 2b2b 2b20 622f 7465 7374 6669 6c65 0a2b  +++ b/testfile.+
00000010: 2b2b 2062 2f74 6573 7466 696c 6520 4109  ++ b/testfile A.
00000020: 0a   
```

After the filename 'testfile A' there is a tab-character (0x09)

**Comment by zeripath** [comment]
yeah that's what I've found from looking at the git source code myself.

This whole section of code needs rewriting.

**Comment by fashberg** [comment]
Hi @zeripath you were faster.

Maybe my better testing: https://github.com/fashberg/gitea/commit/8c6231cb3e82e3bf5e5f87a127ea5bf05642edcd

It iterates all variants  and adds a timestamp after \t  (timestamp has to be removed)

**Comment by zeripath** [comment]
@lunny I've added several testcases to the ParsePatch test and renamed it singlefile and fixed a few more issues in the PR

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
> Hi @zeripath you were faster.
> 
> Maybe my better testing: [fashberg@8c6231c](https://github.com/fashberg/gitea/commit/8c6231cb3e82e3bf5e5f87a127ea5bf05642edcd)
> 
> It iterates all variants and adds a timestamp after \t (timestamp has to be removed)

So the reason why I went for the if `contains(name, " ")` route was because it exactly reverses what git does:

```c
			strchr(line, ' ') ? "\t" : "");
```

I didn't want to consider what would happen if say git decided that \t was not a reason to quote a filename.

In general I'm not really a fan of Split(...) because it creates (potentially n-1) strings unnecessarily, and if you really just want the 0th element you should just use Index and grab the preceding bit of the string i.e.:

```go
index := strings.Index(foo, "\t")
if index > -1 {
  foo = foo[:index]
}
```

that way if the rest of foo contains mulitple \t you don't end up with n individual strings. (It's also worth realising that go actually copies the bytes arrays around for each of those new strings.)

--- 

As I've said above this whole section of code needs rewriting with proper reference to what git does and can do. It's highly inefficient, makes bad assumptions about sizes, copies this data around multiple times and the resulting AST it creates is rather large.

**Pull request merged**
