### PR TITLE
Migrate margin and padding helpers to tailwind

### PR DESCRIPTION
**Pull request by silverwind**
This will conclude the refactor of 1:1 class replacements to tailwind, except `gt-hidden`. Commands ran:

```bash
perl -p -i -e 's#gt-(p|m)([lrtbxy])?-0#tw-$1$2-0#g'   {web_src/js,templates,routers,services}/**/*
perl -p -i -e 's#gt-(p|m)([lrtbxy])?-1#tw-$1$2-0.5#g' {web_src/js,templates,routers,services}/**/*
perl -p -i -e 's#gt-(p|m)([lrtbxy])?-2#tw-$1$2-1#g'   {web_src/js,templates,routers,services}/**/*
perl -p -i -e 's#gt-(p|m)([lrtbxy])?-3#tw-$1$2-2#g'   {web_src/js,templates,routers,services}/**/*
perl -p -i -e 's#gt-(p|m)([lrtbxy])?-4#tw-$1$2-4#g'   {web_src/js,templates,routers,services}/**/*
perl -p -i -e 's#gt-(p|m)([lrtbxy])?-5#tw-$1$2-8#g'   {web_src/js,templates,routers,services}/**/*
```

### CODE REVIEW

**Comment by delvh** [comment]
> This will conclude the refactor of 1:1 class replacements to tailwind

What do we do about `gt-hidden`?
Do we keep that, or do we migrate it as well?
If we migrate it, where do we put the docs telling the user to always use it?

**Review by delvh — COMMENTED** [review]
<details><summary>There's a small regression currently </summary>

```go
ag 'gt-(p|m)([lrtbxy])?-\d' --ignore-dir routers/ --ignore-dir web_src/ --ignore-dir templates/ --ignore-dir services/
modules/markup/markdown/goldmark.go
219:                    v.SetAttributeString("class", []byte("gt-py-3 attention attention-"+attentionType))
367:            _, _ = w.WriteString(`<span class="gt-mr-2 gt-vm attention-`)

modules/markup/sanitizer.go
67:     policy.AllowAttrs("class").Matching(regexp.MustCompile(`^gt-py-3 attention attention-\w+$`)).OnElements("blockquote")
69:     policy.AllowAttrs("class").Matching(regexp.MustCompile(`^gt-mr-2 gt-vm attention-\w+$`)).OnElements("span", "strong")
```
</details>

Edit: My bad, tested on the wrong branch locally. No regression present

**Comment by silverwind** [comment]
> > This will conclude the refactor of 1:1 class replacements to tailwind
> 
> What do we do about `gt-hidden`? Do we keep that, or do we migrate it as well? If we migrate it, where do we put the docs telling the user to always use it?

Not sure yet what to do about it. Ideally we would move to `tw-hidden`.

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
> ```go
> modules/markup/sanitizer.go
> ```

Are you on `main` branch? I see zero matches for `gt-` in `modules`.

**Comment by delvh** [comment]
Reload this page

**Review by denyskon — APPROVED** [review]
:rocket:

**Pull request merged**
