### PR TITLE
add changelog of v1.6.0

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by jonasfranz — APPROVED** [review]

**Comment by strk** [comment]
LGTM, although I'd prefer less details in the bugfixes section (maybe move it as last thing, minor releases are mostly interesting for features, not bugfixes, which should go in bugfix releases)

**Comment by strk** [comment]
Example of unneeded detail in the Bugfix section:

 - Fix: Let's Encrypt configuration settings (#4911)

Since Let's Encrypt is a new feature, there's no point in listing fixes to bugs in its implementation
(there may be more like that)

**Comment by adelowo** [comment]
Finally 💯 💯

**Review by adelowo — APPROVED** [review]

**Comment by lunny** [comment]
@lafriks @strk done.

**Review by appleboy — APPROVED** [review]

**Pull request merged**
