### PR TITLE
Add migration test

### PR DESCRIPTION
**Pull request by zeripath**
This commit adds a simple migration test to ensure that gitea migrate actually works on sqlite.

It does not test the migrated db actually works with Gitea but at least tests whether the migrate command will not barf.

It would not be hard to wire in the integration tests as a next step on the db. (In fact I have already tested this.) 

The command is `make test-migration` and will test migrations on sqlite from v1.4.3, v1.5.3, v1.6.4 and v1.7.0-rc3 to the current master.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
I have not wired the migration test in to the drone CI but this could also be done.

**Comment by zeripath** [comment]
OK I've rewritten this.

There are migration tests for mysql, pgsql and sqlite. If anyone can provide sqls for mssql then those can be added. The default database is the testfixtures.

The migration tests are wired into the drone file and are run just before the integration tests.

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
~~OK I've created a new gitea command: `gitea dump-fixtures` which will create `integrations/migration-test/gitea-vVERSION.DATABASE.sql.gz` file~~

Hmm... that doesn't work... I'll repush once I've got that working.

**Comment by zeripath** [comment]
OK I don't think the dump-fixtures command will work unfortunately. The xorm dump tables command doesn't quite translate the sql properly to make this. Perhaps this could be a different PR.

**Review by lunny — APPROVED** [review]

**Pull request merged**
