### PR TITLE
Catch the error before the response is processed by goth.

### PR DESCRIPTION
**Pull request by SteveTheEngineer**
The code introduced by #18185 gets the error from response after it was processed by goth.

That is incorrect, as goth (and golang.org/x/oauth) doesn't really care about the error, and it sends a token request with an empty authorization code to the server anyway, which always results in a `oauth2: cannot fetch token: 400 Bad Request` error from goth.
It means that unless the "state" parameter is omitted from the error response (which is required to be present, according to [RFC 6749, Section 4.1.2.1](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1)) or the page is reloaded (makes the session invalid), a 500 Internal Server Error page will be displayed.
This fixes it by handling the error before the request is passed to goth.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Review by zeripath — DISMISSED** [review]
Actually do we to tell goth that this request has failed and to cancel any data it has too?

**Comment by zeripath** [comment]
(My review can be dismissed if we can get an answer on this.)

**Comment by SteveTheEngineer** [comment]
> Actually do we to tell goth that this request has failed and to cancel any data it has too?

Yes.

**Comment by wxiaoguang** [comment]
IMO it's also fine for doing nothing in the error callback. Just like there is a network error occurring during the callback, Gitea even wont't get the response callback, then nothing happens, nothing wrong in the end.

And it's also fine to call the `Logout` to clear the data in session, just like what `oauth2Source.Callback` does (oauth2Source.Callback -> gothic.CompleteUserAuth -> Logout).

LGTM

**Review by wxiaoguang — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
