### PR TITLE
Tweak labeler config

### PR DESCRIPTION
**Pull request by silverwind**
Alternative to https://github.com/go-gitea/gitea/pull/27439. Removes a few spammy labels, and disables `sync-labels` which make it never remove labels (which is default behaviour).

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Let's merge this and take a look for a while.

**Comment by silverwind** [comment]
Lint failure is unrelated: https://github.com/go-gitea/gitea/pull/27488#issuecomment-1751698634

**Comment by denyskon** [comment]
Can we please talk about the label restructuring I proposed, before merging this?

**Comment by silverwind** [comment]
I'd say label restructure can come after this, it's not blocking.

**Review by KN4CK3R — APPROVED** [review]

**Comment by denyskon** [comment]
As the naming of the labels will change, we'd need to tweak this config once again. I think we should wait if it can happen during the next few days.

**Pull request merged**
