### PR TITLE
Allow users with write permissions to modify issue descriptions and comments

### LINKED ISSUE #10558: Not possible to edit issue description anymore
- Gitea version (or commit ref): 1.11.1
- Operating system: Debian Buster
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/cezar97/Gitea_Issue_Logout/issues/4
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In earlier versions, you were able to change the description of issues and PRs created by other users. This is no longer possible, which is very annoying for check lists etc.

### PR DESCRIPTION
**Pull request by jolheiser**
Users with write perms to issues can modify issue descriptions and comments.

Resolves #10558

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport.

**Comment by brunoais** [comment]
@lunny I'm not sure but does this allow any user who can create issues to edit other user's issue descriptions?

**Comment by lafriks** [comment]
@brunoais no, it allows users with **write** access to issues to edit other users descriptions. Issue can be created with **read** access.

**Comment by 6543** [comment]
We may have to specify zhis in future ... (spam protection & co ...)

**Comment by guillep2k** [comment]
@brunoais It's not intuitive, but "read" permissions include creating issues and editing/closing own issues. "Write" permissions include modifying/closing issues from other users.

**Comment by brunoais** [comment]
Thank you @lafriks & @guillep2k . It is really not intuitive... I think I'm giving too many permissions to my users, then...

**Comment by lafriks** [comment]
@brunoais that how it was also before and also same as it is for github

**Comment by lafriks** [comment]
If you need for users only to be able to create issues and update their own, just set them read rights for issues

**Comment by brunoais** [comment]
Used github a lot. Never managed accounts on github.

**Comment by guillep2k** [comment]
I think we should improve the way the permissions for groups are presented in the UI.

**Pull request merged**
