### PR TITLE
Enable spellcheck for EasyMDE, use contenteditable mode

### LINKED ISSUE #18532: web interface - spellchecker of the browser not available
### Feature Description

The default behavior for spell checking of the browser does not work in forms. e.g when editing a README.md and want to use spell checks

### Screenshots

not possible within a right mouse click

### PR DESCRIPTION
**Pull request by wxiaoguang**
As the title.

Fix #18532
* https://github.com/go-gitea/gitea/issues/18532

And: `CodeMirror docs indicate that "contenteditable" be the future default on Desktop as well`, so it's good to use `contenteditable` from now on.

Tested browsers:

* Chrome: works
* Firefox: works
* Safari: works (https://github.com/go-gitea/gitea/pull/19776#issuecomment-1165078236)

image

### CODE REVIEW

**Comment by silverwind** [comment]
Seems to work again on Firefox Mac when triggering spellcheck via context menu.

image

`contenteditable` generally makes me wary, but CodeMirror docs indicate that it'll be the future default on Desktop as well, so I trust their implementation to be stable enough.

**Comment by jolheiser** [comment]
I believe this was disabled for various reasons related to SimpleMDE. 
https://github.com/go-gitea/gitea/issues/9619
https://github.com/go-gitea/gitea/issues/10729

Perhaps the native one wasn't available back then? I don't recall. 
Just posting here for context, I'm generally in favor of enabling it. 🙂

**Comment by tyroneyeh** [comment]
Turning on the upload function of this image will not work

**Comment by wxiaoguang** [comment]
> Turning on the upload function of this image will not work

Yup, as mentions in the `Problems / TODO` section:

> the image paste and other features need to be rewritten.

**Comment by tyroneyeh** [comment]
Sorry i didn't notice, i tried changing it and it seems to work,
This attache patch is base on release/v1.16 branch for reference

[ImagePaste.zip](https://github.com/go-gitea/gitea/files/8966001/ImagePaste.zip)

**Comment by wxiaoguang** [comment]
Awesome 👍  I applied your patch.

I will do more tests with it later and confirm some details (eg: `$(document).on('paste', '.CodeMirror', ...` seems to be executed more than one time). Feel free to suggest more 😊

**Comment by tyroneyeh** [comment]
Sorry for my patch but didn't work in the editor comments :(

**Comment by tyroneyeh** [comment]
It seems that there is a problem with 1.16.8. It doesn't seem to be a problem with my patch, but I can't reproduce it on try.gitea.io

```
2022/06/23 18:56:39 routers/web/base.go:130:1() [E] PANIC: runtime error: invalid memory address or nil pointer dereference
        /usr/lib/go/src/runtime/panic.go:220 (0x4507f5)
                panicmem: panic(memoryError)
        /usr/lib/go/src/runtime/signal_unix.go:818 (0x4507c5)
                sigpanic: panicmem()
        /home/tyrone_yeh/workspace/github/gitea/modules/indexer/issues/indexer.go:309 (0x1a3ebfc)
                UpdateIssueIndexer: Poster:   issue.Poster.FullName,
        /home/tyrone_yeh/workspace/github/gitea/modules/notification/indexer/indexer.go:78 (0x1a41312)
                (*indexerNotifier).NotifyUpdateComment: issue_indexer.UpdateIssueIndexer(c.Issue)
        /home/tyrone_yeh/workspace/github/gitea/modules/notification/notification.go:123 (0x1e79443)
                NotifyUpdateComment: notifier.NotifyUpdateComment(doer, c, oldContent)
        /home/tyrone_yeh/workspace/github/gitea/services/comments/comments.go:69 (0x1e7939f)
                UpdateComment: notification.NotifyUpdateComment(doer, c, oldContent)
        /home/tyrone_yeh/workspace/github/gitea/routers/web/repo/issue.go:2222 (0x1eb0c77)
                UpdateCommentContent: if err = comment_service.UpdateComment(comment, ctx.User, oldContent); err != nil {
        /home/tyrone_yeh/workspace/github/gitea/modules/web/route.go:80 (0x1e2ad7a)
                Wrap.func1: t(ctx)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x16385f5)
                (*Mux).routeHTTP: h.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/web/route.go:119 (0x1e2b691)
                Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/web/route.go:119 (0x1e2b691)
                Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/web/route.go:119 (0x1e2b691)
                Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/get_head.go:37 (0x1e5af44)
                GetHead.func1: next.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/web/route.go:119 (0x1e2b691)
                Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/context/context.go:757 (0x164a174)
                Contexter.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 (0x163642c)
                (*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 (0x1637ddb)
                (*Mux).Mount.func1: handler.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x16385f5)
                (*Mux).routeHTTP: h.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/routers/web/base.go:169 (0x2016b71)
                Recovery.func1.1: next.ServeHTTP(w, req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/gitea.com/go-chi/session@v0.0.0-20211218221615-e3605d8b28b8/session.go:257 (0x1442a3d)
                Sessioner.func1.1: next.ServeHTTP(w, req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/public/public.go:42 (0x15760bb)
                AssetsHandler.func1.1: next.ServeHTTP(resp, req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 (0x163642c)
                (*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 (0x1637ddb)
                (*Mux).Mount.func1: handler.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x16385f5)
                (*Mux).routeHTTP: h.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/routers/common/middleware.go:78 (0x1e61121)
                Middlewares.func2.1: next.ServeHTTP(resp, req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/routers/common/logger.go:23 (0x1e603af)
                LoggerHandler.func1.1: next.ServeHTTP(w, req)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/strip.go:30 (0x1e5dcb8)
                StripSlashes.func1: next.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x1e5a5b6)
                ForwardedHeaders.func1.1: h.ServeHTTP(w, r)
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/workspace/github/gitea/routers/common/middleware.go:31 (0x1e60f79)
                Middlewares.func1.1: next.ServeHTTP(context.NewResponse(resp), req.WithContext(ctx))
        /usr/lib/go/src/net/http/server.go:2084 (0x7a508e)
                HandlerFunc.ServeHTTP: f(w, r)
        /home/tyrone_yeh/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 (0x16363e1)
                (*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
        /home/tyrone_yeh/workspace/github/gitea/modules/web/route.go:334 (0x1e2e4ed)
                (*Route).ServeHTTP: r.R.ServeHTTP(w, req)
        /usr/lib/go/src/net/http/server.go:2916 (0x7a867a)
                serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
        /usr/lib/go/src/net/http/server.go:1966 (0x7a3b36)
                (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
        /usr/lib/go/src/runtime/asm_amd64.s:1571 (0x46d600)
                goexit: BYTE    $0x90   // NOP
```

**Comment by tyroneyeh** [comment]
> Sorry for my patch but didn't work in the edit comments :(

Edit problem is my modify indexer.go issue, please skip it

**Comment by tyroneyeh** [comment]
Safari is work

image

**Comment by wxiaoguang** [comment]
> Still have a question. If you select a tag or assign a member after replying to a comment and pasting an image, the page will refresh and the submitted image will not be displayed.
> 
> But this is an inherent problem

Related issues:
* #17705
* #1315

I will hide some off-topic comments 😊

**Comment by wxiaoguang** [comment]
> Safari is work
> 

Thank you for confirming. I think this PR is ready for review.

**Review by lafriks — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖

**Comment by wxiaoguang** [comment]
(FYI: the last force-push brings no change, the last commit is still 7c44a3a)

**Comment by wxiaoguang** [comment]
This feature has been deployed on try.gitea.io

Feel free to test it and report bugs.

If there is something broken seriously, we should either fix it or revert this feature. Hopefully everything goes well.

**Comment by tyroneyeh** [comment]
There is a chance of missing characters in the Linux ibus input method framework

**Comment by wxiaoguang** [comment]
Besides Linux IME, the mobile IME may also be affected: [Contenteditable on Android is the Absolute Worst](https://discuss.prosemirror.net/t/contenteditable-on-android-is-the-absolute-worst/3810)

If the EasyMDE/CodeMirror still has difficulty to work correctly in some browsers, then it's worth to add a `default editor mode` option (before the CodeMirror can be fixed or replaced totally), use a simple textarea editor instead of the CodeMirror.

**Comment by silverwind** [comment]
If the UI would remember the switch to textarea per-user, it would be a big improvement.

**Comment by wxiaoguang** [comment]
Good idea, maybe remember it in LocalStorage is enough, then no need to write backend code.

**Comment by silverwind** [comment]
We need some simple schema-less key/value JSON ui setting in the db for ui settings like this. localStorage is a start but it should ideally sync across browers.

**Comment by delvh** [comment]
`models/user/setting.go`?

**Comment by silverwind** [comment]
Ah yes that seems suitable, I totally forgot we landed that :)

**Comment by tyroneyeh** [comment]
If the nativeSpellcheck default is false, an icon is added to the toolbar as a switch, do you know if there is still a problem?
`{
        name: 'spell-check',
        action(e) {
          const cm = e.codemirror.getTextArea().parentElement.querySelector('.CodeMirror-code');
          cm.spellcheck = cm.spellcheck ? false : true;
        },
        className: 'fa fa-check',
        title: 'Spell Check'
      }`

image

**Comment by wxiaoguang** [comment]
The usability problem is not related to spell-check but the editor itself (`inputStyle`).

**Comment by tyroneyeh** [comment]
Maybe let the user check spelling by themselves, and set contenteditable to false if they continue to type

[easyMDE_spellcheck.zip](https://github.com/go-gitea/gitea/files/9129808/easyMDE_spellcheck.zip)

**Comment by techknowlogick** [comment]
locking this, as closed PRs are the best place to ensure conversation is lost/not visible to everyone. please open a new ticket to discuss.

**Pull request merged**
