### PR TITLE
Make buttons in a modal form have proper type.

### LINKED ISSUE #25438: Pressing 'Enter' on repo settings modals hides the modal
### Description

When trying to delete/transfer/archive a repo from its settings, entering the name and pressing enter, the modal is simply being hidden instead of deleting the repo.

### Gitea Version

1.20-nightly

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker rootful

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix  #25438

All non-"ok" buttons which do not have "type" should not submit the form, should not be triggered by "Enter".

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm, I guess I would prefer the respective templates to be fixed, or is this change in JS because of dynamically created modals or something?

**Comment by wxiaoguang** [comment]
> Hmm, I guess I would prefer the respective templates to be fixed

There could be a lot, and there will be new templates and developers would forget to mark buttons as "type=button" again and again.

>  or is this change in JS because of dynamically created modals or something?

The problem is, Fomantic recommends to use `<div class="ui approve button">Approve</div>`, but, Gitea uses `<button>` (#23337) . And Fomantic Modal expects to use "onApprove", but Gitea uses "<form>". These mechanisms just conflict.

----

There could be a more general/transparent solution like what I have done for checkbox/dropdown, but it needs time

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by denyskon** [comment]
@wxiaoguang ...
Seems like this fix broke the normal confirm buttons in transfer/delete repo modals (probably others too) (confirming is now only possible by pressing Enter)
Adding `ok` class to those confirm buttons seems to help....

**Comment by wxiaoguang** [comment]
> @wxiaoguang ... Seems like this fix broke the normal confirm buttons in transfer/delete repo modals (probably others too) (confirming is now only possible by pressing Enter) Adding `ok` class to those confirm buttons seems to help....


 I see and I think I know the problem now. This change should be reverted

**Comment by wxiaoguang** [comment]
The revert PRs:

Revert "Make buttons in a modal form have proper type. (25446) (25478)" #25484 

Revert "Make buttons in a modal form have proper type. (25446)" #25485 


I will propose a complete solution later.

**Pull request merged**
