### PR TITLE
allow `token` parameter from the POST body

### PR DESCRIPTION
**Pull request by slingamn**
I encountered this while trying to patch [Forgejo](https://codeberg.org/forgejo/forgejo/pulls/4276) but thought that I should ask here as well about the validity of the proposed fix. It seems to me that the intent of #28390 was to deprecate passing `token` as a URL parameter, which is a security issue. However, blocking attempts to read from `(http.Request).Form` means that `token` cannot be read from the POST body either.

Since OIDC introspection actually [mandates](https://datatracker.ietf.org/doc/html/rfc7662#section-2.1) reading the token from the POST body, the proposed fix here is to check `(http.Request).PostForm` first and return successfully on finding the token there. (I'm only checking for `token` and not for `access_token`, since I'm not aware of any flows that send `access_token` in the POST body.)

Thanks for your time.

### CODE REVIEW

**Comment by slingamn** [comment]
cc @JackHay22 @kdumontnu ; sorry for the @'s but would you be able to look at this? As I understand it, without this patch, OIDC introspection will break in 1.23 when `DISABLE_QUERY_AUTH_TOKEN` starts defaulting to true.

**Comment by lunny** [comment]
I think this needs more discussions about the security. I couldn't find the big difference between GET and POST via API requests.

**Comment by techknowlogick** [comment]
Thanks @slingamn, this seems like a reasonable addition. Could you verify that the "token" field is not used in any other POSTs for the API as that would otherwise conflict, as well could you add some tests (that don't need to be super involved)? If not, let me know and I can make a complimentary PR.
Could you also send an example use-case so I can also run through some local integration tests myself?

**Comment by lafriks** [comment]
I don't think this is a good idea to accept that for all requests as this should be used for specific use cases in specific endpoints instead

**Comment by slingamn** [comment]
@lunny for the security rationale for the original change, see this comment, which clarifies that the issue is confined to GET and doesn't affect POST: https://github.com/go-gitea/gitea/pull/28390#issuecomment-1846161143

**Comment by slingamn** [comment]
@lafriks I looked into this and you're right. I opened #31632 as an improved (but riskier) version of this change).

**Pull request closed without merging**
