### PR TITLE
Fix ?render=1 option on raw files

### PR DESCRIPTION
**Pull request by pgaskin**
cc @bkcsoft @strk

### CODE REVIEW

**Comment by pgaskin** [comment]
@bkcsoft says I still need to write tests.

**Comment by strk** [comment]
Torture, but if we don't take the chance with new maintainers the testsuite will never complete :)

**Comment by lunny** [comment]
There is no potential security problem here?

**Comment by pgaskin** [comment]
@lunny 
From the #gitea channel (talking about ?render=1):

```
<BKC> geek1011: I said "if it was up to me, it would've never gotten in", breaking things for people isn't really in my interest though
<geek1011> BKC neither is it in mine
<BKC> So I don't wanna get rid of `&raw=1`, but I would've never added in the first place :package: <geek1011> I think caddy is good if we can get the subdmains to work right
<BKC> Yeah, I need to look at having gitea listen on a unix-socket ;)
<geek1011> and it's ?render=1
<BKC> right, render=1...
* geek1011 thinks about submitting a pr to make render=1 even better
<BKC> geek1011: "even better"? :)
<geek1011> making it serve proper mimetypes
<BKC> doit :)
<geek1011> OK
```

**Comment by strk** [comment]
@geek1011 I'm thinking a test would also be great because that piece of code was "recently" touched to fix another bug (README files not being rendered while navigating the repo, or something like that)

**Pull request closed without merging**
