### PR TITLE
Reduce number of layer

### PR DESCRIPTION
**Pull request by Dryusdan**
Somes layer are created and aren't usefull, so I compress this :)

### CODE REVIEW

**Comment by Dryusdan** [comment]
I suggest also use https://github.com/xataz/docker-alpine because his image are more updated than official alpine image :)

**Comment by bkcsoft** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by silverwind** [comment]
Alternatively, you could also use `docker build --squash` to reduce all layers to one automatically.

**Comment by Dryusdan** [comment]
But, I don't think if `--squash` is benefit for space disk because the layer from doesn't exist because it's compress with other so multiple image cannot use same FROM (mystic think, I know ^^ )
Another, update image and container are more longer because the 3 first layer doesn't exist, the download and extract are impact...
This is just hypothesis, I not know `--squash` before and I don't see it option before ^^

**Comment by silverwind** [comment]
It's a new option added in 1.13:

> docker build has a new experimental --squash flag. When squashing, Docker will take all the filesystem layers produced by a build and collapse them into a single new layer. This can simplify the process of creating minimal container images, but may result in slightly higher overhead when images are moved around (because squashed layers can no longer be shared between images). Docker still caches individual layers to make subsequent builds fast.

So you're right in that it doesn't allow sharing of intermediate layers, but if the aim is to produce the smallest possible image, it's the way to go.

**Pull request merged**
