### PR TITLE
Fix panic in storageHandler

### LINKED ISSUE #27409: panic when loading home page and 404 error
### Description

Gitea panics when loading home page in /avatars/ route (and therefore the avatar image doesn't load) and when opening the home page, it shows a 404 error.

### Gitea Version

1.20.4 and git main branch

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/sryze/68fb927ff8b95121597942a3fa118f3e

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Behind Apache web server as described at https://docs.gitea.com/next/administration/reverse-proxies#apache-httpd-with-a-sub-path

### Database

SQLite

### PR DESCRIPTION
**Pull request by sryze**
storageHandler() is written as a middleware but is used as an endpoint handler, and thus `next` is actually `nil`, which causes a null pointer dereference when a request URL does not match the pattern (where it calls `next.ServerHTTP()`).

Example CURL command to trigger the panic:

```
curl -I "http://yourhost/gitea//avatars/a"
```

Fixes #27409

---

Note: the diff looks big but it's actually a small change - all I did was to remove the outer closure (and one level of indentation) ~and removed the HTTP method and pattern checks as they seem redundant because go-chi already does those checks~. You might want to check "Hide whitespace" when reviewing it.

Alternative solution (a bit simpler): append `, misc.DummyOK` to the route declarations that utilize `storageHandler()` - this makes it return an empty response when the URL is invalid. I've tested this one and it works too. Or maybe it would be better to return a 400 error in that case (?)

### CODE REVIEW

**Comment by lunny** [comment]
The prefix parameter could be removed.

**Comment by sryze** [comment]
@lunny Do you mean that it could be extracted from request URL?

**Comment by lunny** [comment]
If it's a `http.HandlerFunc` function, It's OK.

**Comment by wxiaoguang** [comment]
```
if req.Method != "GET" && req.Method != "HEAD" {
   405 Method Not Allowed
}
```

**Review by wxiaoguang — APPROVED** [review]

**Comment by sryze** [comment]
A

> ```
> if req.Method != "GET" && req.Method != "HEAD" {
>    405 Method Not Allowed
> }
> ```

OK, added it back

**Comment by sryze** [comment]
> The prefix parameter could be removed.

If the prefix parameter is removed, `funcInfo` would be looked up on every request - is that OK?

**Review by lunny — APPROVED** [review]

**Comment by sryze** [comment]
I think the bot is trying to backport the same commit twice as it appears to be already in those release branches.

**Pull request merged**
