### PR TITLE
Disable redirect for i18n

### PR DESCRIPTION
**Pull request by techknowlogick**
As title

### CODE REVIEW

**Comment by lunny** [comment]
Why change that to false?

**Comment by zeripath** [comment]
So there's another option, which would mitigate other similar issues in future of sticking a handler before the the il8n handler which does a path.Clean() and redirects to the clean path if the path wasn't clean to begin with.

However this does solve the current problem, and it's not as if the lang query parameter can be used elsewhere - so I'm gonna approve.

**Review by zeripath — APPROVED** [review]

**Comment by lafriks** [comment]
I don't think this is correct solution, we should do fix to upstream lib or move that middleware to gitea code

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
@lafriks I think this is a temporary PR so that is able to be back port to release/v1.7

**Comment by lafriks** [comment]
But this does not fix problem completely, problem that currently is solved could be solved also keeping redirect by changing few lines up AppSubURL to AppURL

**Comment by techknowlogick** [comment]
@lafriks that doesn't entirely work, as i18n library uses AppSubURL to set cookie path

`Set-Cookie: lang=fr-FR; Path=/http://localhost:3000; Max-Age=2147483647`

**Comment by lafriks** [comment]
That's shity :D

**Comment by techknowlogick** [comment]
@lafriks :joy: yup.

**Pull request merged**
