### PR TITLE
Fix bound address/port for caddy's certmagic library

### PR DESCRIPTION
**Pull request by bminer**
This is my attempt to fix issue created by d2ea21d0d8103986b2ce53c17b7b99b1ce6828b0 when switching to Caddy's certmagic library. I believe that the call to `ManageSync` causes Gitea to try and listen on port 80 even if `PortToRedirect` is set.

Please test this fix, but I think it works.  Thoughts?

### CODE REVIEW

**Comment by zeripath** [comment]
the thing is certmagic shouldn't be opening any ports itself. We open and control these ports ourselves.

**Review by 6543 — DISMISSED** [review]
as per zeripath, we should find out why certmagic would (if ..) open a port itself and consider it a bug

**Review by zeripath — APPROVED** [review]
the ListenHost and AltHTTPPort are used in the challenge solvers - that's why they're needed

**Review by techknowlogick — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
