### PR TITLE
fix(#32667): 🐛 Fixe a keystring misuse and refactor duplicates keystrings

### LINKED ISSUE #32667: Reuse the same translation keystrings for the same labels in milestone dropdown menus
### Description

I noticed the Milestone dropdown selector used in the _sidebar_ of an issue/PR doesn't use the same translation keystring as the ones used in the _filters_ and _actions_ menubars

**Keystring used in the sidebar**

Screenshot 2024-11-28 at 17-10-27

**Keystring used in the actionbar & filterbar**

Screenshot 2024-11-28 at 17-09-56

Screenshot 2024-11-28 at 17-18-41

---

Further more, the _actions_ menubars misuses the 'open' keystring for both opened and closed milestones, whereas it should use the 'close' keystring.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Macos

### Browser Version

Firefox 132

### PR DESCRIPTION
**Pull request by Simandara**
- Fixes a translation keystring misuse where the string 'open milestones' is used in place of 'closed milestones'.
- De-duplicates the use of 'open milesones' and 'closed milestones' keystrings on the sidebar of an issue, reusing the ones on the issues filter and action bars.
- Closes #32667

### CODE REVIEW

**Comment by wxiaoguang** [comment]
> * De-duplicates the use of 'open milesones' and 'closed milestones' keystrings on the sidebar of an issue, reusing the ones on the issues filter and action bars.

Could the unused keys like "issues.new.closed_milestone" and "issues.new.open_milestone" be deleted from locale_en-US.ini ? (only en-US is enough, other files will be managed automatically)

**Review by wxiaoguang — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Could the unused keys like "issues.new.closed_milestone" and "issues.new.open_milestone" be deleted from locale_en-US.ini ? (only en-US is enough, other files will be managed automatically)

Wait for this for a while, in case there would be new changes.

**Comment by wxiaoguang** [comment]
> > * De-duplicates the use of 'open milesones' and 'closed milestones' keystrings on the sidebar of an issue, reusing the ones on the issues filter and action bars.
> 
> Could the unused keys like "issues.new.closed_milestone" and "issues.new.open_milestone" be deleted from locale_en-US.ini ? (only en-US is enough, other files will be managed automatically)

@SimonPistache  could you confirm whether these keys are unused and could be removed?

**Comment by SimonPistache** [comment]
> > > * De-duplicates the use of 'open milesones' and 'closed milestones' keystrings on the sidebar of an issue, reusing the ones on the issues filter and action bars.
> > 
> > 
> > Could the unused keys like "issues.new.closed_milestone" and "issues.new.open_milestone" be deleted from locale_en-US.ini ? (only en-US is enough, other files will be managed automatically)
> 
> @SimonPistache could you confirm whether these keys are unused and could be removed?

 → [github search for `issues.new.closed_milestone`](https://github.com/search?q=repo%3Ago-gitea%2Fgitea%20new.closed_milestone&type=code)
 → [github search for `issues.new.open_milestone`](https://github.com/search?q=org%3Ago-gitea+issues.new.closed_milestone&type=code)

@wxiaoguang it looks like the keystring are used on the [debian packaging](https://github.com/go-gitea/debian-packaging) repo, thus we should **not** remove until they get properly replaced.

I don't know this repo nor how safe it is to change it's content, but by scanning at the files names, it looks like they have the same job ([templates/repo/issue/view_content/sidebar.tmpl](https://github.com/go-gitea/debian-packaging/blob/921608fd1176c087c5546eea7f0f863c4112741f/templates/repo/issue/view_content/sidebar.tmpl#L51) and [templates/repo/issue/new_form.tmpl](https://github.com/go-gitea/debian-packaging/blob/921608fd1176c087c5546eea7f0f863c4112741f/templates/repo/issue/new_form.tmpl#L81)) as the ones in the main repo.

**Comment by wxiaoguang** [comment]
> it looks like the keystring are used on the [debian packaging](https://github.com/go-gitea/debian-packaging) repo, thus we should **not** remove until they get properly replaced.

Nope, there are not used there. I will remove these keys.

**Comment by SimonPistache** [comment]
> > it looks like the keystring are used on the [debian packaging](https://github.com/go-gitea/debian-packaging) repo, thus we should **not** remove until they get properly replaced.
> 
> Nope, there are not used there. I will remove these keys.

**Comment by wxiaoguang** [comment]
> [debian packaging](https://github.com/go-gitea/debian-packaging)

That "debian packaging" is a dead repo and it has its own "translations". The strings in this repo are unrelated.

**Pull request merged**
