### PR TITLE
Prevent possible XSS

### PR DESCRIPTION
**Pull request by Gusted**
- In the case of misuse or misunderstanding from a developer whereby, `data-panel` can receive user-controlled data. `$(sel)` can lead to the creation of a new element. Current usage is using hard-coded selectors in the templates, but nobody prevents that from expanding to user-controlled somehow.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by Gusted** [comment]
The code seems to originate from the BIDI feature(https://github.com/go-gitea/gitea/pull/17562) so I don't think this needs to be backported.

**Comment by Gusted** [comment]
make LGTM work

**Comment by 6543** [comment]
can we add some linter to catch this?

**Comment by wxiaoguang** [comment]
If we want to patch .... we had better patch all the code, but not one by one ....

image

**Comment by Gusted** [comment]
> If we want to patch .... we had better patch all the code, but not one by one ....

Hmm interesting, this was instance was catched by a CodeQL query I've been running locally. Seems to get confused when it sees a usage that is indirect and inlined.



> can we add some linter to catch this?

We might go a bit harsh and ban the usage of `$(...)`(exception of `$(this)`?) as it doesn't have 1 defined behavior, as it can be querySelector, but on the wrong data it can create a new element. E.g. a lot of instance like the mentioned one should be done via `$.find`.

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
I suggest to refactor all similar code together and write the rule into frontend guide, or just keep the code as it was.

Otherwise, this patch doesn't help the code base.

**Comment by silverwind** [comment]
I'm still of the opinion we should just replace jQuery with vanilla JS, e.g. `document.querySelectorAll`. It's better for performance and vanilla DOM APIs are not really that hard to learn. jQuery has no place in modern code.

**Comment by Gusted** [comment]
> I'm still of the opinion we should just replace jQuery with vanilla JS

What's the current argument to not do this? If none, expect a PR from me soon to do this. As that would resolve this issue and future ones entirely.

**Comment by silverwind** [comment]
There's no blocker, it's just that some people like @zeripath seem to prefer `jQuery` out of habit, but I'd certainly welcome a refactor towards replacing jQuery with vanilla JS.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind @wxiaoguang 

I think this pull is fine as is - I do not like to see heavy code refactor in freezing in it do not fix an issue ;)
the ongoing discussion about how our frontend should move towards (framework, libs, ...) is important and we should overthing some of it ... O I would suggest to let this pull be reviewed against proposed aim & open a new issue/discurese-thread/... to talk about this - it look's like it  (discussion) is needed :)

**Review by wxiaoguang — APPROVED** [review]
That's fast, awesome.

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
