### PR TITLE
Improve clarity between is_activated and prohibit_login

### PR DESCRIPTION
**Pull request by pgaskin**
It used to be unclear what the difference between the two are.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by sapk** [comment]
LGTM. Please rebase on master so the build will not failed since RepoCreationNum as been renamed in MaxCreationLimit.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by lunny** [comment]
@geek1011 please rebase

**Pull request merged**
