### PR TITLE
Do not show lock icon on repo list for public repos in private org

### PR DESCRIPTION
**Pull request by CirnoT**
Proposal. Brings it in-line with icon on repo page itself. Alternative to https://github.com/go-gitea/gitea/pull/11444

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
make lg-tm work

**Comment by 6543** [comment]
pleace change milestone!

**Comment by lafriks** [comment]
@6543 why? we have already created branch `release/v1.12`, we can already start merging 1.13.0 milestone PR

**Comment by 6543** [comment]
just noticed

**Pull request merged**
