### PR TITLE
Fix wrong text getting saved on editing second comment on an issue (#5608)

### PR DESCRIPTION
**Pull request by HarshitOnGitHub**

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
Is the change to `/public/js/index.js` from #5608 not needed in the backport?

**Comment by HarshitOnGitHub** [comment]
@techknowlogick Oops! By mistake I forgot to include that commit. :man_facepalming:

**Comment by techknowlogick** [comment]
That’s ok. Those things happen. This is why we have reviews to catch things like that, so everything is ok :) thanks for your contribution, it is appreciated.

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
Looks like I shouldn't be reviewing in New year's eve, missed that :)

**Pull request merged**
