### PR TITLE
Use the total issue count for UI

### LINKED ISSUE #20574: The "all" count on a user's Pull Requests page is misleading
### Description

When clicking around on the PRs from a user's Pull Requests page (the button in the main site header, e.g.: https://try.gitea.io/pulls), "All" is selected by default and shows the total count of all PRs in all repos.

image

Clicking on one of the repos, however, causes the "All" count to change to whatever is highlighted instead of showing the composite total:

image

image

image

I feel like All was always showing the total count in 1.16.9, but is exhibiting this behavior in 1.17.0. I am not sure if All is supposed to indicate "the number we're showing you based on your selection" or "the number we'd be showing you if you clicked on this". I tend to assume it should be the latter based on how the individual repos behave.

### Gitea Version

1.17.0, 1.18.0+dev-193-g335e918b1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Git Version

2.37.1

### Operating System

Linux

### How are you running Gitea?

Ubuntu apt package

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by parnic**
This fixes a problem where the "All" line item on the Issues or Pull Requests page was only showing the count of the selected repos instead of the total of all issues/prs in all repos.

The "total number of shown issues" number is now stashed in a different context variable in case it wants to be used by the frontend later. It's currently not being used.

Tested with open and closed issues and open and closed pull requests.

Fixes #20574

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
@parnic do you have any suggestions for where to put the `TotalIssueCount`?

**Comment by parnic** [comment]
> @parnic do you have any suggestions for where to put the `TotalIssueCount`?

`TotalIssueCount` is currently used by templates/user/dashboard/issues.tmpl. The new variable I introduced here, `TotalShownIssueCount`, _probably_ doesn't really need to exist? There are several places (such as the Open and Closed buttons on the right side) that currently show the number of "shown" issues. That context variable can just be removed if you'd prefer.

**Comment by Gusted** [comment]
Seems better to not introduce variables that aren't used.

**Comment by parnic** [comment]
Done.

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
