### PR TITLE
Center tables within markdown

### PR DESCRIPTION
**Pull request by ollien**
This fixes tables not being centered in markdown files, as described by #4916.

Before:
Before

After: 
After

I tried to avoid using `!important`, but Semantic seems to place a `text-align: inherit` on tables, so I had to (sadly) resort to using it.

### CODE REVIEW

**Comment by ollien** [comment]
Could you elaborate? It seems consistent with GitHub's markdown, which is what the original issue proposed.

**Comment by lafriks** [comment]
Current proposed solution would center also tables that should not be centered.

Example

```
| 参数 | 类型 | 说明 | 是否必填 |
| :----: | :----: | :----: | :----: |
| code | string | 机构编码  | 是 |
```

Should be centered and look like this:

| 参数 | 类型 | 说明 | 是否必填 |
| :----: | :----: | :----: | :----: |
| code | string | 机构编码  | 是 |

While standard tables should **not** be centered. Example:

```
| 参数 | 类型 | 说明 | 是否必填 |
| ---- | ---- | ---- | ---- |
| code | string | 机构编码  | 是 |
```

| 参数 | 类型 | 说明 | 是否必填 |
| ---- | ---- | ---- | ---- |
| code | string | 机构编码  | 是 |

**Review by lafriks — CHANGES_REQUESTED** [review]
This will break standard table layout

**Comment by ollien** [comment]
Got it. Did not realize there was a difference.

**Comment by techknowlogick** [comment]
Closing per @lafriks comment.

**Pull request closed without merging**
