### PR TITLE
Revert "Replies to outdated code comments should also be outdated"

### PR DESCRIPTION
**Pull request by lunny**
Reverts go-gitea/gitea#13217, per https://github.com/go-gitea/gitea/pull/13217/files#r518531211 and https://github.com/go-gitea/gitea/pull/13217/files#r518531552

### CODE REVIEW

**Review by BetaCat0 — APPROVED** [review]
LGTM

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
This should not have been reverted. The migration should have been fixed.

**Comment by lunny** [comment]
It's not quick to fix that PR when I found the problem because of different database pagination SQL. Since the PR is only online for several hours, so I think revert is the quickest method to prevent more people to upgrade to that commit.

**Comment by 6543** [comment]
migrations with raw SQL just need more :eyes: on review ...

**Pull request merged**
