### PR TITLE
only return head: null if source branch was deleted (#6705)

### PR DESCRIPTION
**Pull request by quantonganh**
* only return head: null if source branch was deleted

* add URL into GetPullRequest

* TestPullRequest_APIFormat

* log error if it is not Err(Branch)NotExist

(cherry picked from commit ff85a6331e02338100e3799b5787bf8b686fe003)

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@lunny you have pushed way too much commits imho

**Review by lafriks — CHANGES_REQUESTED** [review]
per comment above

**Comment by lunny** [comment]
> @lunny you have pushed way too much commits imho

Maybe you mean @quantonganh ?

**Comment by lafriks** [comment]
@lunny yes :) sorry

**Comment by quantonganh** [comment]
@lafriks fixed.

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
