### PR TITLE
Discord Oauth2 support

### LINKED ISSUE #4125: Discord Oauth2 support
Read the title!

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #4125

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Conflict

**Comment by jonasfranz** [comment]
If I try to authenticate via Discord, I'm getting this error:

```error
2018/07/20 10:44:54 [...routers/user/auth.go:542 handleOAuth2SignIn()] [E] UserSignIn: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error": "invalid_client"}
```

I've created a discord application and added the secrets. Then I've added the redirect link to OAuth2 at Discord.

**Comment by techknowlogick** [comment]
@JonasFranzDEV thanks for testing. I just tested and can confirm same results. Using same keys with `goth` example I was able to login, so it is 100% something wrong with my implementation. I'll go through and see what I did wrong.

**Comment by l0go** [comment]
yay!

**Comment by techknowlogick** [comment]
@jonasfranz I've update vendored dependency, and I am successfully able to login now, please review.

**Review by jonasfranz — APPROVED** [review]

**Pull request merged**
