### PR TITLE
enable systemd to reload gitea config

### PR DESCRIPTION
**Pull request by jnahmias**

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Really? I don't know that Gitea's config could be reloaded.

**Comment by lunny** [comment]
> Really? I don't know that Gitea's config could be reloaded.

The title is inaccurate. It's just reloading Gitea in the systemd configuration.

**Comment by silverwind** [comment]
There is a SIGHUP handler here:

https://github.com/go-gitea/gitea/blob/09dd4b42c7afe3f474d900b9d5856af2929a12ea/modules/graceful/manager_unix.go#L134-L136

If I understand correctly, it is a complete process restart, certainly not a config reload like this PR says.

**Comment by wxiaoguang** [comment]
Unless restart the Gitea process, at the moment, there is no feasible approach to make GItea fully reload the config dynamically.

It's the hardest part in Gitea, more difficult than the Template/Route refactoring / Queue rewrting / Logger system refactoring. The idea/implementation is not that hard, but it needs to rewrite a lot of code.

**Comment by wxiaoguang** [comment]
Hi @jnahmias , thank you for the contribution. According to the comments above, it seems that it's better not to add `ExecReload=/bin/kill -HUP $MAINPID` to the systemd config, because Gitea doesn't support the "config reloading" that way.

**Pull request closed without merging**
