### PR TITLE
Exclude generated files from language statistics

### PR DESCRIPTION
**Pull request by lafriks**
Fix to exclude generated files from language statistics

### CODE REVIEW

**Comment by lafriks** [comment]
It would be nice if we could also backport this to 1.12 so that there is no need to regenerate all language stats later on, what do you think?

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I think backporting to 1.12 is a good idea. It'll save the repeated issues opening about stopping generated files from being included and we'll save having to regenerate later.

I wonder if there is a relatively cheap way of using isGenerated on our diff pages.

**Comment by lafriks** [comment]
It could through it will need reading at least part of the file to detect it

**Comment by lafriks** [comment]
Wait until go-enry/go-enry#24 is fixed upstream

**Comment by silverwind** [comment]
> I wonder if there is a relatively cheap way of using isGenerated on our diff pages.

Seconding this, auto-collapsing generated files in diffs would indeed be a nice feature.

**Comment by lafriks** [comment]
I would think it would need to be cached

**Review by guillep2k — APPROVED** [review]
I think we should also consider #10335, regardless of this improvement.

**Review by CirnoT — APPROVED** [review]

**Comment by guillep2k** [comment]
> 
> 
> Wait until [go-enry/go-enry#24](https://github.com/go-enry/go-enry/pull/24) is fixed upstream

Merged. For some reason 2.5.0 and 2.5.1 point to the [same commit](https://github.com/go-enry/go-enry/commit/2880ccae4ac13ed5f98a94c9276dafe54fdace08), so I don't know if that was intentional. @mcuadros

**Comment by mcuadros** [comment]
Yes, it's intentional, I did a lame move. I deleted the 2.5.0 to avoid creating 2.5.1, 5 seconds after creating it, but then go modules didn't work with this new 2.5.0 so I ended creating the 2.5.1, to make it work, ending with two tags to the same commit :/

**Comment by lafriks** [comment]
Updated go-enry to v2.5.2

**Pull request merged**
