### PR TITLE
Fix drone release publishing and test steps

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Awesome, I've got to drop the pam support otherwise the cross compile will fail.

**Comment by tboerger** [comment]
```
[updater:L50:15s] + make release
[updater:L51:15s] mkdir -p dist/binaries dist/release
[updater:L52:15s] xgo -dest dist/binaries -tags 'sqlite tidb pam' -ldflags '-s -w -X "code.gitea.io/gitea/modules/setting.BuildTime=2016-12-04 10:59:36 UTC" -X "code.gitea.io/gitea/modules/setting.BuildGitHash=621a078"' -targets 'linux/*,darwin/*,windows/*' -out gitea-master code.gitea.io/gitea
[updater:L53:15s] Cross compiling code.gitea.io/gitea...
[updater:L54:15s] Fetching main repository code.gitea.io/gitea...
[updater:L55:15s] Fetching https://code.gitea.io/gitea?go-get=1
[updater:L56:16s] Parsing meta tags from https://code.gitea.io/gitea?go-get=1 (status code 200)
[updater:L57:16s] get "code.gitea.io/gitea": found meta tag main.metaImport{Prefix:"code.gitea.io/gitea", VCS:"git", RepoRoot:"https://github.com/go-gitea/gitea"} at https://code.gitea.io/gitea?go-get=1
[updater:L58:16s] code.gitea.io/gitea (download)
[updater:L59:58s] Compiling for linux/amd64...
[updater:L60:90s] Compiling for linux/386...
[updater:L61:93s] # code.gitea.io/gitea/vendor/github.com/msteinert/pam
[updater:L62:93s] /usr/bin/ld: cannot find -lpam
[updater:L63:93s] collect2: error: ld returned 1 exit status
[updater:L64:117s] 2016/12/04 23:01:18 Failed to cross compile package: exit status 2.
[updater:L65:117s] Makefile:101: recipe for target 'release-build' failed
[updater:L66:117s] make: *** [release-build] Error 1
```

**Comment by bkcsoft** [comment]
well, PAM feels like a hack anyway so I'm all for dropping it 😆

**Comment by tboerger** [comment]
I can't believe that anybody seriously uses pam anyway :)

**Comment by tboerger** [comment]
This should be fine for merge now. I have dropped the `tidb` tag because it increases the binary size by ~13MB and I have also dropped the `pam` build tag because this makes much trouble on cross-compiling the binaries. With the current configuration the publishing to s3 should be fixed and works reliable for our initial release and for continuously built binaries of the master branch.

**Comment by bkcsoft** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Pull request merged**
