### PR TITLE
Fix org owner cannot be removed if he is not in owner team

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by ethantkoenig — APPROVED** [review]

**Comment by ethantkoenig** [comment]
LGTM

**Comment by ethantkoenig** [comment]
What exactly is the difference between being an owner (i.e. `OrgUser.IsOwner` set to true) vs. being on the owner team? Do we need both, or can we combine the notions?

**Comment by lunny** [comment]
That should be a bug or something. The steps are:
1. create a new organization, then you will be owner of organization and also in owner team;
2. add another people to owner team;
3. leave the owner team.
Then you will be an owner of organization but not in owner team.

**Comment by ethantkoenig** [comment]
@lunny I understand how to reproduce the bug, I'm just asking why we need the `OrgUser.IsOwner` field, as well as an owner team. My comment was not specific to this PR, but was just a general question/suggestion.

Would it make sense to get rid of the `OrgUser.IsOwner` field completely? What do we need it for?

**Comment by lunny** [comment]
@ethantkoenig this is a history problem. Old gitea version allow add member who are not in any team, but new version ask all org members be at least one team. I think it's time to get rid of the `OrgUser.IsOwner` field completely in v1.4.

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
