### PR TITLE
Latvian translation for home page

### PR DESCRIPTION
**Pull request by lafriks**
As title ;)

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]
I trust your Latvian. 😉

**Review by zeripath — APPROVED** [review]
I think we need to restructure this page to use translate... 

I also trust your Latvian

**Comment by lafriks** [comment]
@zeripath I was thinking the same when doing this translation but wanted to do that outside this PR :)

**Comment by 6543** [comment]
I can do this if ...?

**Pull request merged**
