### PR TITLE
Do not create commit graph for temporary repos

### PR DESCRIPTION
**Pull request by brechtvl**
When fetching remotes for conflict checking, skip unnecessary and potentially slow writing of commit graphs.

In a test with the Blender repository, this reduces conflict checking time for one pull request from about 2s to 0.1s.

### CODE REVIEW

**Review by delvh — APPROVED** [review]
@zeripath does a temporary repo need the commit graph at any point?
If not: LGTM.

**Comment by delvh** [comment]
I know.
My question was if our temporary repos use them to speed anything up (it only makes sense to merge this PR in its current state if it doesn't make anything else noticeably slower).
That's why I forwarded the question to our Git expert, @zeripath.

**Comment by zeripath** [comment]
I think there should be a way to use the commit graphs from the other repos. But yes we should not be writing them here and not writing them will save time on big repos.

Sorry I missed this. It totally didn't occur to me that this was happening.

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
> @zeripath does a temporary repo need the commit graph at any point? If not: LGTM.

It should not because it could be reused only from the second time. For an one-time repository, it can't help.

**Pull request merged**
