### PR TITLE
On Migration respect old DefaultBranch

### PR DESCRIPTION
**Pull request by 6543**
fix a bug

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
tests failed related.

**Comment by 6543** [comment]
@lunny should be fixed

**Review by lunny — APPROVED** [review]

**Comment by 1byte2bytes** [comment]
Hi there! Thanks, I do believe this was the issue I am facing. I’m super sorry, I accidentally reported the Go version on the bottom of the page, not the Gitea version of 1.12.4. It’s been a very tiring time over here on the west coast, especially with my full work days, I must’ve just wrote the first version number looking thing I saw

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
backport: #12858

**Pull request merged**
