### PR TITLE
Set SemverCompatible to false for Conan packages (#21275)

### PR DESCRIPTION
**Pull request by KN4CK3R**
Backport of #21275

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Backported migration will break the new releases.

**Comment by KN4CK3R** [comment]
You are right, how to handle that?

**Comment by wxiaoguang** [comment]
No idea .... there was an old PR for backport migration (https://github.com/go-gitea/gitea/pull/10625) but no progress. I wasn't a member at that time.

**Comment by silverwind** [comment]
So in essence, the migration system can not detect whether a  certain migration, identified by a string, has already ran and skip it?

**Comment by wxiaoguang** [comment]
> So in essence, the migration system can not detect whether a certain migration, identified by a string, has already ran and skip it? I think the numbering scheme would have to be dropped to make it more smart then.

No at the moment. The Gitea's migration system is quite tricky and needs to be improved IMO.

For this backport, maybe the migration can be dropped, and tell users to run a SQL manually if they encounter the bug (very few), or provide temporary doctor command (although I prefer to avoid too many doctor commands).

**Comment by KN4CK3R** [comment]
> So in essence, the migration system can not detect whether a certain migration, identified by a string, has already ran and skip it? I think the numbering scheme would have to be dropped to make it more smart then.

The migration could be run multiple times in this case but yes, the "index" 224 would be marked as "already run" and the real 224 from Gitea 1.18 would be skipped.

**Review by wxiaoguang — APPROVED** [review]

**Comment by noerw** [comment]
Maybe the simplest change would be to reserve a couple (10?) migration IDs when starting a new major release, so there is room for migrations in point releases. This would still require that backported migrations are idempotent (as they potentially would be run twice), but at least the ambiguous-migration-ID-problem would be solved.

**Comment by silverwind** [comment]
For future improvement to the migration system, I would suggest using a map of unique strings that identify migrations, ideally inserted into a separate table once ran. That way, all the number collision problems go away as well.

**Review by lunny — APPROVED** [review]

**Pull request merged**
