### PR TITLE
Fix emojify image URL

### LINKED ISSUE #2759: Wrong emojify url
- Gitea version (or commit ref): 0e9e48b
- Git version: 2.7.4
- Operating system: Linux Mint
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/ahme-t/a910d75074c96df617baedca04eb296d

## Description
Emojify wrong public url.
True url starts with "vendor"
```
[Macaron] [Static] Serving /vendor/plugins/emojify/images/dog.png
[Macaron] 2017-10-22 00:17:22: Completed /vendor/plugins/emojify/images/dog.png 304 Not Modified in 376.731µs
```

## Screenshots

opera snapshot_2017-10-22_001932_localhost

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #2759

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
back port to 1.2?

**Comment by lafriks** [comment]
Yes

**Pull request merged**
