### PR TITLE
Don't render escaped HTML on plain text

### PR DESCRIPTION
**Pull request by Gusted**
- While viewing a plain readme file that has ambiguous characters, it currently will write HTML for escaped characters, however it's being rendered as a plain text and thus will not actually render the HTML elements.
- Only show the escape status, but render the content as plain text without trying to show the ambigious characters(escape button will have no effect due to this).
- Related https://codeberg.org/Codeberg/Community/issues/796

Before:
image

After:
image

### CODE REVIEW

**Comment by Gusted** [comment]
@zeripath, this feels hacky, but trying to render the plain text as HTML feels even more hacky.

**Comment by zeripath** [comment]
Yup this PR doesn't feel right to me.

**Comment by Gusted** [comment]
What should be the expected behavior be, indeed render the HTML? Or disable this feature altogether for plain READMEs?

**Comment by zeripath** [comment]
So there are two things we need to do:

1. In reality we should drop the ambiguous warnings for rendered content 
   - We should be like VSCode here and github and only warn about these on Source code views
2. We still need to do something about rendering README.txt files though, because we have to handle broken characters.
   - I think these should just be rendered as <pre> and we can stick the <code> bits in as necessary.

**Comment by silverwind** [comment]
Related but I would suggest making this box yellow instead of red. Also, I think we should reduce text to just one paragraph, those two are nearly identical. And finally, I still feel the warning shows up too often on innocuous code.

**Comment by Gusted** [comment]
> So there are two things we need to do:
> 
>     1. In reality we should drop the ambiguous warnings for rendered content
>        
>        * We should be like VSCode here and github and only warn about these on Source code views
> 
>     2. We still need to do something about rendering README.txt files though, because we have to handle broken characters.
>        
>        * I think these should just be rendered as  and we can stick the ```
>           bits in as necessary.
>          ````
>        ``
>        `
> 
>     ` `

So still stick in the html elements? But don't display them? I'm sorry I'm not following on your second point.

**Review by silverwind — APPROVED** [review]
Better than before

**Review by lafriks — APPROVED** [review]

**Review by zeripath — CHANGES_REQUESTED** [review]
I think this is still the wrong thing to do - instead we should just render the warning for `rendered` pages.

**Comment by zeripath** [comment]
See #22016

**Comment by Gusted** [comment]
Seems to be replaced by #22017

**Comment by zeripath** [comment]
Thanks @Gusted for your work

**Pull request closed without merging**
