### PR TITLE
Display current stopwatch in navbar

### LINKED ISSUE #4378: Feature enhancement: Dashboard should show active time tracker
I love the new time tracker function (see #967). 

But to avoid that there are several trackers running and are forgotten, it would be helpful if there would be an indicator on the dashboard for every running time tracker.

### PR DESCRIPTION
**Pull request by noerw**
Adds link to currently tracking issue into navbar
This also requires to extend the API response for stopwatches with the current tracked duration

timetrack

fixes #4378

### CODE REVIEW

**Comment by noerw** [comment]
Possible alternative UI (but this would require more JS & I don't have the time give the buttons a proper layout):

Screenshot from 2020-12-23 10-11-27

**Comment by lunny** [comment]
But if you start watch serval issues, how to display them?

**Comment by silverwind** [comment]
I would just display a single clock icon and make a dialog similar to what is in https://github.com/go-gitea/gitea/pull/13977 to display the running trackers.

**Comment by bobemoe** [comment]
Since https://github.com/go-gitea/gitea/pull/10533 there can be only one stopwatch.

**Comment by lunny** [comment]
> Since #10533 there can be only one stopwatch.

Missed that.

**Comment by bobemoe** [comment]
With this new functionality it would make managing multiple stopwatches much easier, I wouldn't be opposed to reverting #10533, or maybe implementing it as an config option as suggested in that PR? Personally I cant really see a use case for multiple tracking.

Could the current sidebar stopwatch message be removed once this navbar version is implemented? Especially if multiple stopwatches get reimplemented as its a bit confusing, see https://github.com/go-gitea/gitea/issues/10529

**Comment by lunny** [comment]
> With this new functionality it would make managing multiple stopwatches much easier, I wouldn't be opposed to reverting #10533, or maybe implementing it as an config option as suggested in that PR? Personally I cant really see a use case for multiple tracking.
> 
> Could the current sidebar stopwatch message be removed once this navbar version is implemented? Especially if multiple stopwatches get reimplemented as its a bit confusing, see #10529

I agree with you. I don't think #10533 needs to be reverted. A config option will make the things complicated.

**Comment by lunny** [comment]
CI failed is related.

**Comment by noerw** [comment]
I changed the UI with suggestions by @silverwind, I think it's good now:
Peek 2020-12-25 05-59

@bobemoe As long as there is a single timer, that notice should stay. Also I can certainly see usecases for multiple timers: tracking a specific issue for billing, and the general topic you're spending time with for personal overview. If we re-enable that, this will be in a separate PR.

**Comment by silverwind** [comment]
Looks nice. Can we maybe also live-update the displayed time in the dialog, using JS loop that updates it every second?

**Comment by noerw** [comment]
I added clientside live updates to the displayed time, but it's somewhat janky due to client/serverside synchroniziation / drift.
If you think that it's still good-enough, this PR is ready from my side.

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Pull request merged**
