### PR TITLE
Forcibly replace github.com/satori/go.uuid

### PR DESCRIPTION
**Pull request by zeripath**
There are several dependencies which still reference github.com/satori/go-uuid despite
the long recognised problem with this library.

This PR proposes replacing satori/go.uuid with my recently created fork which is shim
against google/uuid. This shim is not a perfect replacement for satori as it misses
several functions available on the old type - however, these should only be rarely used
in any case and certainly testing appears to imply that these functions are not used.

Close #18311

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by KN4CK3R** [comment]
https://github.com/satori/go.uuid/issues/115 mentioned https://github.com/gofrs/uuid as replacement. Could we use that instead?

**Comment by zeripath** [comment]
Which version of go-frs do you propose to use?

**Comment by KN4CK3R** [comment]
I have not looked into it but as it has the same api surface so it should be a drop in replacement. If maintaining your shim is not a problem we can use yours.

**Comment by zeripath** [comment]
If you're going to suggest a different library - please do the work to check and figure out which one.

One problem with not using the shim as above is that you won't them be able to forcibly update the version of go-frs using the replace notation.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
> [satori/go.uuid#115](https://github.com/satori/go.uuid/issues/115) mentioned https://github.com/gofrs/uuid as replacement. Could we use that instead?

looked at this lib too, i fafour googl/uuid

**Comment by noerw** [comment]
what do you think of hosting such gitea-related/maintained shims & forks on gitea.com?

**Comment by zeripath** [comment]
> what do you think of hosting such gitea-related/maintained shims & forks on gitea.com?

Happy to move these to gitea.com if preferred.

I think we could even consider hosting them on the system.

> looked at this lib too, i fafour googl/uuid

Unfortunately we can't force the go-frs/uuid code to use the same shim we'd have to create another one.

--- 

I honestly don't mind replacing to go-frs/uuid if we're happy that would work. Just need to decide the version value to go with.

**Review by KN4CK3R — APPROVED** [review]

**Comment by lunny** [comment]
> > what do you think of hosting such gitea-related/maintained shims & forks on gitea.com?
> 
> Happy to move these to gitea.com if preferred.
> 
> I think we could even consider hosting them on the system.
> 
> > looked at this lib too, i fafour googl/uuid
> 
> Unfortunately we can't force the go-frs/uuid code to use the same shim we'd have to create another one.
> 
> I honestly don't mind replacing to go-frs/uuid if we're happy that would work. Just need to decide the version value to go with.

Ah, please!!!

**Pull request closed without merging**
