### PR TITLE
Add easyMDE(simpleMDE) support for release content editor

### PR DESCRIPTION
**Pull request by a1012112796**
As title

example view:

-------------------

------------------

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
Have you tested the preview page and are happy that relative links from it match when they are finally rendered?

**Comment by a1012112796** [comment]
> Have you tested the preview page and are happy that relative links from it match when they are finally rendered?

yes, see https://github.com/go-gitea/gitea/pull/14744#issue-576288832

**Comment by zeripath** [comment]
I was meaning links like:

`[README.md]`

**Comment by a1012112796** [comment]
> I was meaning links like:
> 
> `[README.md]`

It's a link?
image

**Comment by zeripath** [comment]
Sorry `[README.md](README.md)`

**Comment by a1012112796** [comment]
> Sorry `[README.md](README.md)`

the results is same:
tp

**Review by zeripath — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Pull request merged**
