### PR TITLE
fix double 'push tag' action feed (#15078)

### PR DESCRIPTION
**Pull request by a1012112796**
Backport #15078

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by techknowlogick** [comment]
Does this affect webhooks? For example with Drone?

**Comment by lunny** [comment]
Imo it will. The PR should be reverted. We need to change the behaviour of push commits but not remove push tag.

**Comment by a1012112796** [comment]
here ....
https://github.com/go-gitea/gitea/blob/a587a284349e7c27d1bec39ef0dedb3972ef68c5/modules/notification/webhook/webhook.go#L563-L583

**Comment by silverwind** [comment]
Hope this won't introduce a regression in the tag webhooks sent to drone and the like, like the one fixed in https://github.com/go-gitea/gitea/pull/13999.

**Comment by a1012112796** [comment]
@techknowlogick @lunny @silverwind test result on master branch (``1.15.0+dev-14-g1a03fa7a4``)
tmp

**Comment by silverwind** [comment]
Ok, if the second hook there has `ref_type: tag`, it should be fine.

**Pull request merged**
