### PR TITLE
Don't show new pr button when page is not compare pull

### PR DESCRIPTION
**Pull request by yp05327**
Before:
image
After:
image
(TestOrg:test is a tag not branch)

Problem:
In the template, we will not add `compare pull` class when `PageIsComparePull` is false.
https://github.com/go-gitea/gitea/blob/a370efc13f0e1ea309e324639832832bc14cb6dc/templates/repo/diff/compare.tmpl#L2
But in the js, we are using `.repository.compare.pull` to find the button:
https://github.com/go-gitea/gitea/blob/a370efc13f0e1ea309e324639832832bc14cb6dc/web_src/js/features/repo-legacy.js#L552-L563
So, if `PageIsComparePull` is false, the `New Pull Request` button will be there, but has no response when we click it.

### CODE REVIEW

**Review by silverwind — APPROVED** [review]
Unrelated to this PR but I would ideally prefer if we eventually remove the need to click this button and just open directly into the PR form.

**Comment by a1012112796** [comment]
That's not a bug, `empty pull request` is a feature, which learned from gitlab, you can use this featue to create a coding plan  with a new branch before add the code. first added in #12543.

**Comment by a1012112796** [comment]
example:
test

**Comment by wxiaoguang** [comment]
Not a bug but a feature, need to write some comments for it.

**Comment by silverwind** [comment]
If empty PR is a feature, this change makes no sense. I'm sorry but I'll close it then.

**Comment by wxiaoguang** [comment]
> If empty PR is a feature, this change makes no sense. I'm sorry but I'll close it then.

why not keep it open and write some comments?

**Comment by silverwind** [comment]
You mean make this PR comment-only?

**Comment by yp05327** [comment]
No, this is a bug, I know we can create empty pull request, but
**when the base or the compare is a tag not branch, we should not display the new PR button**
as I have mentioned in the discription
> (TestOrg:test is a tag not branch)

You can confirm the difference in GitHub:
https://github.com/yp05327/test2/compare/main...testtag?expand=1
https://github.com/yp05327/test2/compare/main...testtagpr?expand=1

**Review by a1012112796 — APPROVED** [review]
Okay, I see it.

image

**Comment by a1012112796** [comment]
but looks it's not necessary to show this messsage also. because one of these is not a 'branch' ...

image

ref:

image

**Comment by a1012112796** [comment]
so looks this option is better:


```DIFF
diff --git a/templates/repo/diff/compare.tmpl b/templates/repo/diff/compare.tmpl
index 3bb7c2e81..2a4e97504 100644
--- a/templates/repo/diff/compare.tmpl
+++ b/templates/repo/diff/compare.tmpl
@@ -176,7 +176,7 @@
                </div>
        </div>
 
-       {{if .IsNothingToCompare}}
+       {{if and .PageIsComparePull .IsNothingToCompare}}
                {{if and $.IsSigned $.AllowEmptyPr (not .Repository.IsArchived)}}
                        <div class="ui segment">{{.locale.Tr "repo.pulls.nothing_to_compare_and_allow_empty_pr"}}</div>
                        <div class="ui info message show-form-container {{if .Flash}}gt-hidden{{end}}">
``

**Comment by silverwind** [comment]
Retracting review for now.

**Comment by yp05327** [comment]
> so looks this option is better:

Done.

**Comment by lunny** [comment]
But we still need the comment that the two branches are equal.

**Comment by yp05327** [comment]
`.PageIsComparePull` is not just used in the case of tag selected. 
We should use `if and .HeadIsBranch .BaseIsBranch` to check whether tag is selected.

**Comment by silverwind** [comment]
Can we remove the "New PR" button altogether and just show the form directly if applicable? I'm willing to collaborate on this here. It would be nice to have for https://github.com/go-gitea/gitea/pull/26743 because it's rather un-intuitive when you F5 on the PR page and it does not immediatly show the restored content.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
