### PR TITLE
Allow custom public files

### LINKED ISSUE #758: Not able to override default logo
- Gitea version (or commit ref): 1.0.1
- Operating system: Ubuntu 16.04
- Database (use `[x]`): SQLite
- Can you reproduce the bug at https://try.gitea.io: Not relevant

## Description
I am not able to change the default gitea icon in top navigation bar. I have posted this on gitter channel and as per suggestions tried to override them in custom folder.
@bkcsoft has suggested to replace custom/public/img/gitea-large-resize.png and custom/public/img/gitea-lg.png. The logo in the menu-bar is gitea-lg.png.
But this is not working.
...

### PR DESCRIPTION
**Pull request by tboerger**
This allows serving custom public files again, just place files into `custom/public/` and they will be available to the builtin server.

Fixes #758

### CODE REVIEW

**Comment by andreynering** [comment]
I just tried it, and you cannot override Gitea content, just serve aditional content. Is this the expected behavior?

Otherwise LGTM

**Comment by tboerger** [comment]
I have not tried to override a file. Need to check if I can do this by updating the ordering

**Comment by tboerger** [comment]
So I can confirm that changing the call order works. With this PR I'm able to override also existing files like the logo:

bildschirmfoto 2017-01-28 um 18 45 02

**Comment by Bwko** [comment]
LGTM

**Comment by 0xbaadf00d** [comment]
LGTM

**Comment by kristofer** [comment]
in spite of all this, favicon.ico doesn't work?

**Comment by lunny** [comment]
put your favicon in `custom/public/img/favicon.png`

**Comment by kristofer** [comment]
ah, yes. thank you.

**Comment by Spriithy** [comment]
Sorry for bumping this PR, but it doesn't seem to work for me.

I have successfuly served static images from the `public/img` folder (such as default avatar) but not to provide / override the favicon. I also tried `custom/public/img` but it didn't work for any image (such as `gitea-sm.png` when it worked in `public/img`).

I have noticed that when I go to the `localhost:3000/img/favicon.png` URL it serves me the default Gitea favicon and upon refreshing without cache it gives mine. But anytime I do this on an actual page, only the gitea default favicon is loaded. No sign of mine any.

Any ideas ? Thanks in advance

**Comment by tboerger** [comment]
Teabot getting crazy?

**Comment by Spriithy** [comment]
Hahaha, no ! I had an issue related to this (favicon wouldn't override) even when refreshing without cache and other media overrides worked (`gitea-sm.png` for instance). But rebooting my PC (not the server) seemed to fix this problem so I deleted my comment...

Sorry for the inconvenience !

**Comment by tboerger** [comment]
Which still doesn't explain the label change from the bot

**Comment by jolheiser** [comment]
It's probably confused since the PR has no reviews, yet had an `lgtm/done` label?  
Not sure how it calculates using `LGTM` comments, though, as there are technically two of those.

**Comment by Spriithy** [comment]
I didn't add one in my original comment for sure

**Comment by tboerger** [comment]
It already had the labels previously...

**Pull request merged**
