### PR TITLE
Remove singuliere from MAINTAINERS

### PR DESCRIPTION
**Pull request by singuliere**
I have been subject to hostile behavior from another Gitea maintainer.
Evidence were deleted by the Gitea owners and I will not provide names
to protect their privacy. This has been a recurring occurrence and I
do not want to be exposed to such behavior in the future, reason why I
will stop contributing to Gitea.

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Sorry to see you go.

To me, the most recent context did not seem like "hostile behavior", but rather like "offtopic discussion" instead.
Of course, I only noticed the most recent occurrence and cannot judge whether or not there were "recurring occurrences", so I can understand your decision at least in parts.

**Comment by zeripath** [comment]
@singuliere please don't go.

My comment deletions were to stop the fight from ongoing. I'd reached out to you on discord before things blew up but you had not logged on.

**Comment by zeripath** [comment]
Please could you please contact me on discord or matrix.

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
Or you can close this PR. @singuliere

**Review by 6543 — APPROVED** [review]
Sad to see you leave.

I respect your decision and welcome you back anytime you want

**Comment by zeripath** [comment]
@singuliere I'm extremely sorry that you feel this way and that you have been made to feel this way, but I wish you had chosen to get in touch with me or any of the other owners instead of going down this path. 

Leaving things to the point that there is an explosion does not give us any chances to fix things.

I'll merge this PR using my administrator powers. If you change your mind and decide you want to come back you'll be welcome to back. If you want to talk to us please do get in touch.

**Pull request merged**
