### PR TITLE
Make ParsePatch more robust

### PR DESCRIPTION
**Pull request by Gusted**
- Handle some possible but non-likely edge-cases of ParsePatch whereby
it was possible that it could crash.
- Tests are added and were the only 2 cases I could find.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
apologies for the miscount

**Comment by Gusted** [comment]
> apologies for the miscount

What miscount?

**Comment by zeripath** [comment]
I am responsible for the original miscount of characters that leads to this patch

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by Gusted** [comment]
> I am responsible for the original miscount of characters that leads to this patch

Ah got it, no worries. It was only after plugging in some values to see how it handled "ambitious" values it panicked, otherwise I wouldn't have seen it as well.

**Comment by techknowlogick** [comment]
@Gusted thanks for this PR (and all the other ones recently), could you send this as a backport to 1.15.x?

Also, are you on our discord? I have a question I'd like to ask.

**Comment by Gusted** [comment]
> @Gusted thanks for this PR (and all the other ones recently),

Happy to help!

> could you send this as a backport to 1.15.x?

#17580

> Also, are you on our discord? I have a question I'd like to ask.

I am on the Gitea discord server. Gusted#3726

**Pull request merged**
