### PR TITLE
Add myself to the MAINTAINERS

### PR DESCRIPTION
**Pull request by metalmatze**
:blush:

### CODE REVIEW

**Comment by strk** [comment]
Looking at the repo history there are just 3 commits of yours included (over 4 accepted PR required by CONTRIBUTING.md). Also, they are all from yesterday. Running too fast ? :)

Anyway, LGTM

**Comment by metalmatze** [comment]
Don't worry. We're just getting started. :)

**Comment by andreynering** [comment]
LGTM

**Comment by tboerger** [comment]
And since I already know him personally I really encourage that! LGTM

**Pull request merged**
