### PR TITLE
Add label next to size number in repo submenu

### PR DESCRIPTION
**Pull request by n0toose**
Every other label in that submenu has a clear indicator as to what it
does.

Even if the size is described using the format "12 MiB", the meaning
of the label doesn't seem to immediately register with the user
because the developer that worked on this feature may have thought
that this would have been superfluous, as "MiB" is a unit used to
describe the size of digital files.

The word "used" (example: "212 MiB used") was chosen over "Size:"
(example: "Size: 212 MiB") so as to preserve consistency. I also
thought about using the adjective "large", but it seemed way too
implicit.

### CODE REVIEW

**Comment by silverwind** [comment]
Screenshot would be helpful.

**Comment by wxiaoguang** [comment]
It's untranslatable for i18n.

Many languages do not use this syntax "123KB used"

**Comment by silverwind** [comment]
Yes, this needs to be one translation string like `%s used`. Label it `bytes_used` and move it to a top-level translation (removing the `repo` prefix).

**Comment by wxiaoguang** [comment]
But the layout seems also strange for some languages:

`[icon] 123KB used`

Actually, I'd like to keep the old UI/text (no extra "used")

**Comment by n0toose** [comment]
> Yes, this needs to be one translation string like `%s used`. Label it `bytes_used` and move it to a top-level translation (removing the `repo` prefix) because this is not repo-specific and generally useful.

Didn't think about this, thanks.

**Comment by n0toose** [comment]
However, there's a problem: Bold letters.

**Comment by n0toose** [comment]
In this case, it may be better to use the "Size:" alternative, so that it's also translatable. However, it may not be as consistent.

**Comment by silverwind** [comment]
> However, there's a problem: Bold letters.
> 
> image

You can interpolate HTML tags into the `%s` from the translation, see example in https://github.com/go-gitea/gitea/pull/23951/files#diff-7f25271f6c80f878fdb80a556b5fb2066352bc24d79736b32215205b5fc908c4R138 for how to do it.

**Comment by silverwind** [comment]
How about `123MB Space`?

**Comment by wxiaoguang** [comment]
I think I under the problem now. The key point is `MiB`, it is already a unit "Mega Bytes"

So the UI should be:

**123** MiB

The `123` gets bold styles, the `MiB` doesn't get bold.

Then it's consistent with: 12345 **commits**

**Comment by n0toose** [comment]
> the MiB doesn't get bold.

Possibly too technical? Makes much more sense, I'll adjust it that way.

**Comment by wxiaoguang** [comment]
> > the MiB doesn't get bold.
> 
> Possibly too technical? Makes much more sense, I'll adjust it that way.

I think `MiB/MB` could be very well-known.

And .... TBH I won't expect a user who doesn't understand "MiB/MB"  could use `git clone` ......

**Comment by n0toose** [comment]
> I think `MiB/MB` could be very well-known.
> 
> And .... TBH I won't expect a user who doesn't understand "MiB/MB" could use `git clone` ......

Thought so as well, just wanted to be sure.

**Comment by silverwind** [comment]
Sounds good. With that split we don't even need translation as `MiB` is universal.

**Comment by yardenshoham** [comment]
We could use `PrettyNumber` inside `FileSize`?

**Comment by n0toose** [comment]
I think I don't have enough capacity to work on this problem in particular right now (as in, within the next 7-14 days), feel more than free to take over in the meantime.

I think that MiB should perhaps stay bold, as it's also a variable. Or that it should be moved elsewhere.

**Comment by wxiaoguang** [comment]
Does this look good to you?

 Make repo size style matches others (commits/branches/tags) #24408

**Comment by silverwind** [comment]
Superceded by https://github.com/go-gitea/gitea/pull/24408.

**Pull request closed without merging**
