### PR TITLE
Fix unified diff view styling

### PR DESCRIPTION
**Pull request by mkuhlmann**
Fixing my own pull request (#584).

I've just noticed (20 minutes to late), the unified code view styling was wrong now. Put unified / split into own css classes and everything is perfect now.

Sorry sorry for that, won't happen again ;)

### CODE REVIEW

**Comment by appleboy** [comment]
@mkuhlmann Could you provide the screenshots?

**Comment by mkuhlmann** [comment]
Sure thing,

- [Unified view before this PR (bugged)](https://cloud.githubusercontent.com/assets/1389813/21666556/af1d1cc8-d2f2-11e6-94eb-7439757712a8.png)
- [Unified after this](https://cloud.githubusercontent.com/assets/1389813/21666559/b3dce91e-d2f2-11e6-9435-af00ed89c7af.png)
- [Split view still working nicely](https://cloud.githubusercontent.com/assets/1389813/21656103/f2daa092-d2bc-11e6-99ff-8faac692e32b.png)

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@mkuhlmann Good to merge.  LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
