### PR TITLE
Fix some animation bugs

### LINKED ISSUE #27286: Weird UI behavior when selecting multi-branch in  commit graph page
### Description

As the title, you can reproduce it  https://try.gitea.io/warren830/incubator-devlake/graph

### Screenshots

https://github.com/go-gitea/gitea/assets/50507092/7168b6a3-889d-428a-88f2-0eb21aa29a61

### Gitea Version

try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

chrome

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #27286
Replace #27279

### CODE REVIEW

**Comment by CaiCandong** [comment]
Wait, I think a checkbox is more reasonable to fix  # 27286
When I select a long name branch, It remains looks weird 
image

**Comment by wxiaoguang** [comment]
> Wait, I think a checkbox is more reasonable to fix #27286
> When I select a long name branch, it looks weird

That's a different problem. Your suggestion is to refactor the dropdown.

My PR is just to fix the broken dropdown display.

**Comment by silverwind** [comment]
Long branch name can be truncated to like 500px, but it's unrelated to the issue, yes.

**Comment by CaiCandong** [comment]
Ok, I got it.

**Review by silverwind — APPROVED** [review]
Works well

**Review by lunny — APPROVED** [review]

**Pull request merged**
