### PR TITLE
Change default Android theme color meta tag

### PR DESCRIPTION
**Pull request by andreynering**
- [Before](https://cloud.githubusercontent.com/assets/7011819/21204035/6e9d12b4-c23c-11e6-98e6-df0cb95c9afa.png)
- [After](https://cloud.githubusercontent.com/assets/7011819/21204045/81938b28-c23c-11e6-964f-d4e7a44438a4.png)

### CODE REVIEW

**Comment by tboerger** [comment]
Don't have a strong opinion on that, so LGTM

**Comment by strk** [comment]
> -- File Changes --
> 
>     M conf/app.ini (2)
>     M modules/bindata/bindata.go (1922)

I think bindata changes should be avoided as that file should not
even be in the repository.

**Comment by tboerger** [comment]
There are only changes to a single file. Beside that this change needs an update of the bindata to take an effect

**Comment by tboerger** [comment]
I don't really care about the android theme, so LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
