### PR TITLE
go1.15

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

### CODE REVIEW

**Comment by lafriks** [comment]
Build failing

**Comment by techknowlogick** [comment]
@lafriks blocked by upstream docker images

**Comment by lunny** [comment]
I would like to upgrade after v1.15.1 is released. :(

**Comment by lunny** [comment]
I would like to upgrade after v1.15.1 is released. :(

**Review by CirnoT — APPROVED** [review]

**Comment by CirnoT** [comment]
@lunny I don't see a need to wait for .1 release given that this is not backportable change and we'll have more time and chances to catch potential issues before Gitea 1.13 is done.

**Review by 6543 — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
