### PR TITLE
WIP: Add subTeam support

### PR DESCRIPTION
**Pull request by a1012112796**
- Detail:
  * The subTeam will Auto have access to parent's repositories whith their own permission leve settings.
  * Can't delete team which has subTeams
- example view:
image

- TODO
- [ ] API fix
- [ ] Add some test code

### CODE REVIEW

**Comment by lunny** [comment]
Could you describe the scene we will use the feature?

**Comment by lafriks** [comment]
Subteams seems a bit too much imho as they are limited to single organization

**Comment by a1012112796** [comment]
Yes, it's not so necessary. Now I know what I want, just allow using "/" in team name and add team name wildcard support in permission setting is enough.

**Comment by lunny** [comment]
As @lafriks said, We need global teams concept in fact.

**Comment by a1012112796** [comment]
> As @lafriks said, We need global teams concept in fact.

It's other things. for me, I just want give many teams permission to one repo quickly :)

**Pull request closed without merging**
