### PR TITLE
trim whitespace of MilestoneName at creation/rename

### LINKED ISSUE #10013: [Enhancement] trim whitespace of MilestoneName at creation/rename
as title - feel free to rename

### PR DESCRIPTION
**Pull request by 6543**
close #10013

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]
I wonder if parameter sanitization should be done at the router level. Otherwise LGTM.

**Comment by 6543** [comment]
@guillep2k if done by go not js, api behave the same

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport to v1.11

**Comment by 6543** [comment]
created backport #10034

**Pull request merged**
