### PR TITLE
Changed black color to white for (read) number label on issue list page

### PR DESCRIPTION
**Pull request by ghost**
About to #5978

My opinion is black color does look good for read label color in issue list page
I made color white but show blue option too to discuss

Light theme:
buttons light theme

Dark theme:
buttons dark theme

### CODE REVIEW

**Comment by lafriks** [comment]
Imho the white option would be better

**Comment by jaqra** [comment]
@lafriks do i should change it to white or wait other comments?

**Comment by lafriks** [comment]
Change and see what others say ;)

**Review by lafriks — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
I like white too. I think I'm gonna rework the issue/pr list display at some point with proper vertical centering and a few more tweaks.

**Pull request merged**
