### PR TITLE
Show OpenID Connect and OAuth on signup page

### LINKED ISSUE #19809: External openid connect (oidc, oauth) providers missing on sign up/register page
### Description

As a user I couldn't figure out how to sign up with an external provider on codeberg.org even though I was told this was enabled now. Turns out that you have to click on "I already have an account link" and then you can "sign in" with an external provider.

Usually websites provide both option so that is what users would expect, i.e. "Sign up with Github" and if they come back "Sign in with Github".

For example:

* Gitlab: https://gitlab.com/users/sign_up
* SO: https://stackoverflow.com/users/signup
* Weblate: https://hosted.weblate.org/accounts/register/
* Twitter: https://twitter.com/ (When not signed in)
* *Probably every single other website that offers using external oidc providers* 

### Screenshots

Missing on the reister page: image

It's here on the sign in page: image

### Gitea Version

1.17.0+dev-620-g9574626a2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

FF 100.0.2

### PR DESCRIPTION
**Pull request by dsseng**
Fix #19809

### CODE REVIEW

**Comment by sh7dm** [comment]
Before:
grafik

After change:
grafik

**Review by lunny — APPROVED** [review]

**Review by jackHay22 — COMMENTED** [review]
Looks good!

**Comment by denyskon** [comment]
@sh7dm The OAuth2 login page template has changed since your PR. Could you update it to match the new style?

**Comment by sh7dm** [comment]
It might not be done quick, but will try

**Comment by jackHay22** [comment]
@sh7dm Anything I can help with this to wrap up this PR?

**Comment by sh7dm** [comment]
I could probably work on it tomorrow. If you'd really like you could possibly edit the necessary templates and then open a PR against `ux/oauth-hint-reg` on my fork

**Comment by jackHay22** [comment]
See https://github.com/sh7dm/gitea/pull/1

**Comment by sh7dm** [comment]
Amazing, thanks @jackHay22!

**Review by kdumontnu — APPROVED** [review]
👍

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
