### PR TITLE
Updates SDK dep

### PR DESCRIPTION
**Pull request by richmahn**
Does a `dep ensure -update code.gitea.io/sdk` to add new structs in the sdk

Also updates commits.go to use the Identity substruct

### CODE REVIEW

**Review by axifive — APPROVED** [review]

**Review by lafriks — CHANGES_REQUESTED** [review]
~~This is totally breaking change... and make our API less like GitHub's~~

**Review by lafriks — APPROVED** [review]
sorry, overlooked :)

**Comment by lafriks** [comment]
I don't know why but looks like swagger json needs to be updated, see drone CI output

**Comment by richmahn** [comment]
@lafriks Yeah, saw that just now. Thanks for your input. Got the swagger updated.

**Pull request merged**
