### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by Morlinest**

### CODE REVIEW

**Comment by sapk** [comment]
Just for the proof if needed : https://github.com/go-gitea/gitea/pulls?utf8=%E2%9C%93&q=is%3Amerged%20is%3Apr%20author%3AMorlinest%20
😄 

LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by Morlinest** [comment]
@sapk thx

**Comment by lafriks** [comment]
Make LG-TM work again

**Comment by lafriks** [comment]
@go-gitea/owners please add @Morlinest also to maintainers team in GitHub & discord

**Comment by appleboy** [comment]
@Morlinest Done

**Pull request merged**
