### PR TITLE
Prevent double-login for Git HTTP and LFS and simplify login

### PR DESCRIPTION
**Pull request by zeripath**
There are a number of inconsistencies with our current methods for logging in for git and lfs. The first is that there is a double login process. This is particularly evident in 1.13 where there are no less than 4 hash checks for basic authentication due to the previous `IsPasswordSet` behaviour.

This duplicated code had individual inconsistencies that were not helpful and caused confusion.

This PR does the following:

* Remove the specific login code from the git and lfs handlers except for the lfs special bearer token.
* Simplify the meaning of DisableBasicAuthentication to allow Token and Oauth2 sign-in.
* The removal of the specific code from git http and LFS means that these both now have the same login semantics and can - if `DisableBasicAuthentication` is not set - login from external services. Further it allows Oauth2 token authentication as per our standard mechanisms.
* The change in the recovery handler prevents the service from re-attempting to login - primarily because this could easily cause a further panic and it is wasteful.

This does have the slight changes but I think these result in much more consistent behaviour:

* DisableBasicAuthentication does not prevent OAuth2 or Token auth using the Basic authentication header
* You cannot use Basic authentication to access the UI - this was broken in any case as it didn't manage the session properly

However it does fix a number of bugs with LFS authentication relating to external user sign-on.

Extract from #15186

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
@silverwind in https://github.com/go-gitea/gitea/pull/15186#issuecomment-813667514 asked:

> > Extend disable Basic Authentication to git and LFS
> 
> Care to explain? This does not disable basic auth on git endpoints, right?

So, yes it would (except for OAuth2, Token and LFS token authentication).

This is actually a very good idea - there are substantial costs to doing hashing and external sign-ons and as Gitea currently stands you can potentially overload Gitea or its backing identity server using Git authentication attempts.

I am happy to add another setting which will allow you to disable basic authentication for git and lfs separately if required.

**Comment by silverwind** [comment]
I'm thinking instead of disabling individual mechanisms, it might be better to have a list of options, e.g. something like this:

```
GIT_HTTP_AUTH_METHODS=basic,token,lfs-token
```

**Comment by zeripath** [comment]
@silverwind yeah the current SSO system is messy. I've tried doing it all in one PR but it got too big to make it coherent. 

We need this to then allow the cleaner refactor.

**Comment by zeripath** [comment]
conflicts resolved.

**Comment by zeripath** [comment]
Conflicts resolved

**Comment by kdumontnu** [comment]
@zeripath could you add unit tests for `isGitOrLFSPath`?

**Comment by zeripath** [comment]
I've pulled the same test from #15304

**Review by silverwind — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
