### PR TITLE
go-version constraints ignore pre-releases

### PR DESCRIPTION
**Pull request by zeripath**
Go-version constraints ignore pre-releases.

Rather than change the library further this PR simply changes
the git version comparison to use simple version compare ignoring the
issue of pre-releases.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by jolheiser — COMMENTED** [review]
Should this also revert to using the main library instead of the fork?

**Comment by zeripath** [comment]
No the main library can't parse the version.

**Review by jolheiser — APPROVED** [review]
Gotcha. I thought this func was doing something differently with the parsing so we wouldn't have to worry about it. 😅

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
just trying the zeripath's patch on my instance...

**Review by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf — APPROVED** [review]
works for me.
initial commit, webUI push and merge commits are properly signed with the default signing key I provided.
Gitea version `1.14.0+dev-42-g7cbfce5e0` 
git version `git version 2.29.0.311.g38ddec7408`

**Review by mrsdizzie — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
