### PR TITLE
Actually fix 'make build'

### PR DESCRIPTION
**Pull request by bkcsoft**
now it only rebuilds on changed files (again), but _actually_ rebuilds when something other than  `main.go` has been changed...

### CODE REVIEW

**Comment by tboerger** [comment]
But wildcard should act similar to that :)

**Comment by bkcsoft** [comment]
@tboerger nope, see https://github.com/go-gitea/gitea/pull/351#issuecomment-264888899

**Comment by Bwko** [comment]
LGTM

**Comment by tboerger** [comment]
You are right, but maybe you can define it like this?

```
TARGETS ?= linux/*,darwin/*,windows/*
PACKAGES ?= $(shell go list ./... | grep -v /vendor/)
SOURCES ?= $(...)

...

$(EXECUTABLE): $(SOURCES)
	go build -v -tags '$(TAGS)' -ldflags '-s -w $(LDFLAGS)' -o $@
```

**Comment by bkcsoft** [comment]
@tboerger done :)

**Comment by strk** [comment]
LGTM - thanks for the care !

**Pull request merged**
