### PR TITLE
Responsive view

### LINKED ISSUE #35: Responsive UI
We should provide a responsive UI on best afford. The best way should be a separate view like it's done on gitHub, but on the short term we could simply provide repsonsive elements to give a good view also on mobile devices.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38916129-responsive-ui?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by thehowl**
Other pages will come in future PRs. This PR closes #35. 

* First of all, the meta viewport has been set to one, the basic for any responsive website.
* Navbar has been simplified and refactored. It has some slightly different behaviour and look, but users without OCD should not see a big difference.
* Main reason for the change is to have a better system where it was easier to plug in a stackable navbar, alongside a hamburger button for expanding or collapsing the navbar.
* Dashboard, issues, and explore have been curated to make sure they look good on mobile devices.

## Screenshots

New navbar

screenshot-2017-10-20 gitea

Example of collapsed navbar (and dashboard)

screen shot 2017-10-20 at 17 16 20

[Collapsing/expanding demo](https://a.pomfe.co/nriaxjn.mp4)

Issues page (I ask you to disregard the issue titles I use for testing 😉)

screen shot 2017-10-20 at 17 21 12-fullpage

Explore

screen shot 2017-10-20 at 17 21 48-fullpage

### CODE REVIEW

**Comment by thehowl** [comment]
Need some help here: at the moment forms are organised to be like this:

sharenixtemp tatddejzecgl6ethvxt

This does not really cope well with mobile devices, because this is what you get:

screen shot 2017-10-20 at 21 07 18-fullpage

Would it be OK to replace these custom forms with Semantic UI's [stock forms](https://semantic-ui.com/collections/form.html), having the label of the field sitting on top of the field instead of on the side?

**Comment by hellasteph** [comment]
I use 2FA when logging into Gitea, any plans to support that in the initial responsive version?

**Comment by thehowl** [comment]
That should be included in the task of getting forms to look good (which is what I need to do for the login anyway). In any case, 100% of Gitea's functionality after this PR will be on mobile, too: the only difference is that some pages will look weird for the moment (and to not make this PR even bigger)

**Comment by hellasteph** [comment]
I don't mind QA-ing if that will help you along. I greatly appreciate the work done so far!

**Comment by lafriks** [comment]
In mobile version input buttons must be full width and labels aligned to left

**Comment by pgaskin** [comment]
I will also test the changes too.

**Comment by pgaskin** [comment]
Great job so far.

Some things to work on:
- [ ] The create menu is hard to use on mobile.
- [x] The initialize repository checkbox in the /repo/create is positioned far right off the page
- [x] The user/orgs/repo explore page's nav does not need to stack, it fits fine without, and it looks ugly when stacked
- [ ] The file list in the repo is a bit too thick (maybe remove the last commit name text)

**Comment by thehowl** [comment]
Hey there! Thanks for your feedback.

* What do you mean by hard to use?
* Fixed
* Fixed, done also for the login page.
* I'm not sure about this last one - unfortunately there is no pretty way to "hide" a column on tables only for mobile devices on semantic UI (due to its use of `!important`s). Perhaps a future PR could try to do that.

Also, I've pretty much implemented everything I previously said I would do in the first post and went ahead and removed the [WIP] tag. Reviews and further feedback welcome!

**Comment by lunny** [comment]
@thehowl CI failed.

**Comment by thehowl** [comment]
@lunny Unfortunately, it seems that it fails or succeeds with random chance. Can you or @tboerger run it again, or should I find something minor to change so that it can run again?

**Comment by pgaskin** [comment]
By hard to use, I mean it sometimes disappears too soon (but I don't think you can do something about this issue).

**Comment by lunny** [comment]
Please rebase

**Comment by thehowl** [comment]
done

**Comment by jonasfranz** [comment]
There are some conflicts with master.

**Comment by thehowl** [comment]
Ready for review... again

**Comment by lunny** [comment]
image
When covert to an organization role on dashboard, UI broke.

**Comment by lunny** [comment]
image
explore repository UI should be improved.

**Comment by thehowl** [comment]
@lunny addressed your issues and rebased ✅ sorry for taking long

**Comment by lunny** [comment]
@thehowl Good job!!! Maybe this PR could be merged before v1.4 released. But some issues below:

image

**Comment by thehowl** [comment]
@lunny done & rebased

**Comment by lunny** [comment]
Repository home needs some improvement, otherwise LGTM
image

**Comment by lunny** [comment]
@thehowl need rebase

**Comment by thehowl** [comment]
Sorry for the delay. Can we still get this in by 1.4.0 (in which case I'll proceed to the rebasing now) or since we're in the feature freeze already will this have to wait til 1.5?

**Comment by lunny** [comment]
@thehowl I would like this is in v1.4. Feature freeze means new feature coming PR will be in v1.5, not mean the PR which has been marked as v1.4.

**Comment by thehowl** [comment]
And the tests are green ☑️ 

If anyone reviews the code, make sure to append `?w=1` to the URL of the diff so you can ignore the whitespace changes

**Review by appleboy — APPROVED** [review]

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
