### PR TITLE
fix #1857 trim Windows line ending

### LINKED ISSUE #1857: problems with copying CRLF files in the browser
- Gitea version (or commit ref): 62f600c
- Git version: ?
- Operating system: Windows 8.1 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

When copying a file with CRLF line endings (https://try.gitea.io/mrexodia/testcopy/src/master/crlf.txt) there will be additional lines inserted when pasting in notepad:

### PR DESCRIPTION
**Pull request by appleboy**
fix #1857 cc @mrexodia

### CODE REVIEW

**Comment by lunny** [comment]
conflict with #1862 ?

**Comment by appleboy** [comment]
@lunny Yes. we need to choose one of the solutions so maybe @mrexodia can make the decision.

**Comment by lunny** [comment]
@appleboy I have tested #1862, that should be OK.

**Comment by appleboy** [comment]
OK. I closed this issue now.

**Pull request closed without merging**
