### PR TITLE
Require token for GET subscription endpoint

### LINKED ISSUE #28756: Subscription API Routes Broken
### Description

We're trying to write a script to unsubscribe (unwatch) users from all repos, but running into some issues. It looks like these API routes are broken in a couple of ways.

- First, I created a token with read + write access to all repos (non-admin user)
image

Then, using that token on a repo I own:
```
curl -X 'GET' \
  'https://try.gitea.io/api/v1/repos/kdumontnu/template/subscription' \
  -H 'accept: application/json' \
  -H 'Authorization: ---'
```
returns a 500 error

----

Next, when I try "PUT" or "DELETE", I get a 401 error. `"token is required"`. I should have access to this repo and I've provided all of the token routes.

### Gitea Version

1.22-dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by jackHay22**
Fixes  #28756

## Changes
- Require and check API token for `GET /repos/{owner}/{repo}/subscription` in order to populate `ctx.Doer`.

### CODE REVIEW

**Review by kdumontnu — APPROVED** [review]
👍 

We should really have a script/test that iterates all of the API routes with different token credentials...

**Comment by kdumontnu** [comment]
Shouldn't this have been caught by: https://github.com/go-gitea/gitea/blob/abfdaef5bd5b0430ccebc71f51d6504fecf127ac/tests/integration/api_token_test.go#L110

Can you extend that or have the integration test that hits the get route here?

**Review by KN4CK3R — APPROVED** [review]
Could you add tests for "unauthenticated" in https://github.com/go-gitea/gitea/blob/main/tests/integration/api_user_watch_test.go ?

**Review by delvh — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by jackHay22** [comment]
@KN4CK3R See https://github.com/go-gitea/gitea/pull/28773

**Pull request merged**
