### PR TITLE
Fix missing password length check when change password

### LINKED ISSUE #3036: MIN_PASSWORD_LENGTH ignored when changing the password in user settings
- Gitea version (or commit ref): 1.2.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

The `MIN_PASSWORD_LENGTH` configuration added in #223 is only checked when signing up or when resetting the password via email. When changing the password in the settings (e.g. https://try.gitea.io/user/settings/security) one can enter a password with any length.

### PR DESCRIPTION
**Pull request by lunny**
will fix #3036

### CODE REVIEW

**Comment by lafriks** [comment]
Test would be nice for this otherwise LGTM

**Comment by lafriks** [comment]
No need to add this to milestone as this will be in 1.3.1

**Comment by ethantkoenig** [comment]
+1 for adding tests. It should be straightforward to add some unit tests for `SettingsSecurityPost(..)`; see [routers/repo/wiki_test.go](https://github.com/go-gitea/gitea/blob/master/routers/repo/wiki_test.go) for some examples to follow.

**Comment by lunny** [comment]
@lafriks @ethantkoenig tests added.

**Comment by ethantkoenig** [comment]
LGTM

**Pull request merged**
