### PR TITLE
Fix some files are recognized as SVG incorrectly, make the diff UI unable to work

### LINKED ISSUE #19733: Some files are recognized as SVG incorrectly, make the diff UI unable to work.
### Description

When certain conditions are met gitea can't display the `blade.php` file diff when viewing the commit. It only works when I click "View source button". Second link is taken from network, it is causing the crash.

https://try.gitea.io/stuzer05/test-preview/commit/f97b3784f8c8efc222128f6dffd4e5abb5fda462
https://try.gitea.io/stuzer05/test-preview/raw/commit/e2f752e123151fea55959571d56d57462025f0f6/test.blade.php

image

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

_No response_

### PR DESCRIPTION
**Pull request by stuzer05**
SVG file displaying is broken, meanwhile also breaks other diff files (such as php html templates) from displaying in the diff ui

Every commit here does not display SVGs, and also showcaases broken php html template display
https://try.gitea.io/stuzer05/test-preview/commits/branch/master

So I removed "smart" svg detection at all

Closes #19733

### CODE REVIEW

**Comment by wxiaoguang** [comment]
> SVG file displaying is broken

It should work (I manually constructed those files, one side is valid while other side is invalid)

* https://try.gitea.io/wxiaoguang/test/commit/1f2a63ed813050e652637548bfab447d090e97e6
* https://try.gitea.io/wxiaoguang/test/commit/6c8f25fdf666bc853fea32eb869742906275e5cc

<details>

image

</details>

> meanwhile also breaks other diff files (such as php html templates) from displaying in the diff ui

What's the root problem of the breaking? eg: how the detection goes wrong?

**Comment by stuzer05** [comment]
> What's the root problem of the breaking? eg: how the detection goes wrong?

The initial problem is php files containing svg are not displaying as gitea returns svg mime type for them. The svg regex couse this issue
https://try.gitea.io/stuzer05/test-preview/commit/f97b3784f8c8efc222128f6dffd4e5abb5fda462

Example of the current regex used https://regex101.com/r/m1bCCP/1


image
image

And also on latest firefox (110.0.1) this is what I see

**Comment by wxiaoguang** [comment]
> > 
> 
> The initial problem is php files containing svg are not displaying as gitea returns svg mime type for them. The svg regex cause this issue

Yup, so I guess the detection should be improved, instead of removed?

**Comment by stuzer05** [comment]
> Yup, so I guess the detection should be improved, instead of removed?
There's so many cases when browser won't display an svg (e.g. https://try.gitea.io/stuzer05/test-preview/raw/commit/72f4584ea11cf8579f57d1ab909a6d7d349bc4e7/test%20%28copy%201%29.svg), I think it's better to remove this smart parsing

**Comment by wxiaoguang** [comment]
If remove the smart detection, will it make the SVG files won't be shown as image in the diff view?

**Comment by stuzer05** [comment]
> If remove the smart detection, will it make the SVG files won't be shown as image in the diff view?

Yeah. I think `http.DetectContentType(data)` does not detect svgs for a reason

**Comment by wxiaoguang** [comment]
Have you tried that? According to Golang's issue tracker:

`https://github.com/golang/go/issues/15888#issuecomment-237295881`

> http.DetectContentType is documented to be an implementation of https://mimesniff.spec.whatwg.org/ and that mimesniff spec doesn't define svg.
> And as you found, mime.TypeByExtension has ".svg" in its built-in table:
> https://github.com/golang/go/blob/release-branch.go1.6/src/mime/type.go#L35
> So I don't think there's anything to do here.

**Comment by stuzer05** [comment]
> Have you tried that? According to Golang's issue tracker:
> 
> `https://github.com/golang/go/issues/15888#issuecomment-237295881`
> 
> > http.DetectContentType is documented to be an implementation of https://mimesniff.spec.whatwg.org/ and that mimesniff spec doesn't define svg.
> > And as you found, mime.TypeByExtension has ".svg" in its built-in table:
> > https://github.com/golang/go/blob/release-branch.go1.6/src/mime/type.go#L35
> > So I don't think there's anything to do here.
> 
> I will take a look at this problem , and fix some more SVG related problems.

No, I didn't check that. Maybe we can detect svg by file extension alone. That should actually cover most cases. Embedded svgs shouldn't really be detected (e.g. in html) as we don't want to display html content in diff preview

**Comment by stuzer05** [comment]
> Have you tried that? According to Golang's issue tracker:
> 
> `https://github.com/golang/go/issues/15888#issuecomment-237295881`
> 
> > http.DetectContentType is documented to be an implementation of https://mimesniff.spec.whatwg.org/ and that mimesniff spec doesn't define svg.
> > And as you found, mime.TypeByExtension has ".svg" in its built-in table:
> > https://github.com/golang/go/blob/release-branch.go1.6/src/mime/type.go#L35
> > So I don't think there's anything to do here.
> 
> I will take a look at this problem , and fix some more SVG related problems.

Thank you! Maybe if you could make svg regex not match anything between html comments, except spaces and `\n`, that would resolve the initial bug. As of right now the bug is caused by the last html comment near `<svg` tag https://regex101.com/r/m1bCCP/1

**Comment by wxiaoguang** [comment]
The problem is that the detectors fails on this test:

```go
	assert.False(t, DetectContentType([]byte(`
<!-- comment1 -->
<div>
	<!-- comment2 -->
	<svg></svg>
</div>
`)).IsSvgImage())
```

the regexp was quite tricky before.

**Comment by wxiaoguang** [comment]
I proposed a new PR for SVG/ImageDiff fix:  Fix various ImageDiff/SVG bugs #23312

**Pull request closed without merging**
