### PR TITLE
Fixing redirection issue for logged-in users

### LINKED ISSUE #26005: about the router
### Feature Description

When I am not logged in, I open the webpage "https://gitea.com/user/login?redirect_to=https://gitea.com/work/myjob/issues/15", after logging in, it will redirect normally.

But, when I am already logged in, I open the webpage "https://gitea.com/user/login?redirect_to=https://gitea.com/work/myjob/issues/15", after logging in, I will be redirected to the homepage.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by cassiozareck**
This PR addresses an issue where logged-in users get redirected to the homepage when trying to access a URL with the redirect_to parameter. The issue was traced back to a middleware function in services/auth/middleware.go that redirects logged-in users to the homepage. This function didn't account the redirect_to parameter.

The fix modifies the middleware function to check for this case and redirect the user to the specified URL instead of the homepage.

Closes: #26005

### CODE REVIEW

**Comment by puni9869** [comment]
@wxiaoguang  need your feedback for this change.

**Comment by wxiaoguang** [comment]
I haven't understood why this change works.

In my mind, the straight fix could be:

1. Move the `m.Get("/login", auth.SignIn)` out from the `reqSignOut`
2. In `auth.SignIn`, if the current user "IsSigned", then redirect

**Comment by puni9869** [comment]
> I haven't understood why this change works.
> 
> In my mind, the straight fix could be:
> 
> 1. Move the `m.Get("/login", auth.SignIn)` out from the `reqSignOut`
> 2. In `auth.SignIn`, if the current user "IsSigned", then redirect

Thats what I thoughts

**Comment by puni9869** [comment]
> > I haven't understood why this change works.
> > In my mind, the straight fix could be:
> > 
> > 1. Move the `m.Get("/login", auth.SignIn)` out from the `reqSignOut`
> > 2. In `auth.SignIn`, if the current user "IsSigned", then redirect
> 
> Thats what I thought

**Comment by cassiozareck** [comment]
I haven't thought about it before, but your suggestion makes a lot more sense than changing the middleware itself. I've updated the PR accordingly. Now, I've moved the login route outside of the reqSignOut middleware and discarded the old changes.

The auth.SignIn route handler now checks if the user is logged in. If the user is logged in, it redirects them. If the URL doesn't have the redirect_to parameter, it simply redirects to the / route. This is useful in scenarios where the user wants to access the redirect page only if they're logged in.

**Review by wxiaoguang — APPROVED** [review]
Thank you, overall it looks good to me, while I think the "POST" method should be kept in the "reqSignOut"

**Review by lunny — APPROVED** [review]

**Review by puni9869 — APPROVED** [review]

**Comment by puni9869** [comment]
Thanks cassiozareck for these changes. 💯

**Comment by cassiozareck** [comment]
> Thank you, overall it looks good to me, while I think the "POST" method should be kept in the "reqSignOut"

I tried that first but the login wasn't being saved after login probably because it expects the user should had first signed out to save the post login.
Thanks for the help guys I'll keep contributing for Gitea.

**Comment by wxiaoguang** [comment]
Sorry maybe I misunderstood the problem. If "SignInPost" also needs to handle "redirect_to", IMO it needs a slightly different approach to keep the old behavior, I will try to figure it out.

**Pull request merged**
