### PR TITLE
fix #1501 ssh hangs caused by #1461

### LINKED ISSUE #1501: ssh operations refrain to work since d409d3
- Gitea version (or commit ref): d409d3ab5789
- Git version: 2.11.0
- Operating system: Ubuntu zesty
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
since commit d409d3ab5789 Sanitation fix ssh actions hangs

## Log
```
agaida@vmd18926:~$ git clone git@gitea:Test/pyfll p-10
Cloning into 'p-10'...
remote: Counting objects: 7528, done.
remote: Compressing objects: 100% (2441/2441), done.
remote: Total 7528 (delta 5067), reused 7517 (delta 5060)
Receiving objects: 100% (7528/7528), 3.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5067/5067), done.
agaida@vmd18926:~$ git clone git@gitea:Test/pyfll p-6 
Cloning into 'p-6'...
remote: Counting objects: 7528, done.
remote: Compressing objects: 100% (2441/2441), done.
remote: Total 7528 (delta 5067), reused 7517 (delta 5060)
Receiving objects: 100% (7528/7528), 3.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5067/5067), done.
agaida@vmd18926:~$ git clone git@gitea:Test/pyfll p-4
Cloning into 'p-4'...
remote: Counting objects: 7528, done.
remote: Compressing objects: 100% (2441/2441), done.
remote: Total 7528 (delta 5067), reused 7517 (delta 5060)
Receiving objects: 100% (7528/7528), 3.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5067/5067), done.
agaida@vmd18926:~$ git clone git@gitea:Test/pyfll p-2
Cloning into 'p-2'...
^C
agaida@vmd18926:~$ git clone git@gitea:Test/pyfll p-3
Cloning into 'p-3'...
^C
agaida@vmd18926:~$ git clone git@gitea:Test/pyfll p-4again
Cloning into 'p-4again'...
remote: Counting objects: 7528, done.
remote: Compressing objects: 100% (2441/2441), done.
remote: Total 7528 (delta 5067), reused 7517 (delta 5060)
Receiving objects: 100% (7528/7528), 3.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5067/5067), done.
```
This behaviour is reproducible - just branch the current master and hard reset it to some commits before.

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by bkcsoft** [comment]
LGTM

**Comment by lunny** [comment]
About the hang reason: when pull or push via SSH, `models.GetUserByName` will be invoked and then  https://github.com/go-gitea/gitea/blob/master/models/user.go#L166  will be invoked. But on `NewSanitizer` function `log.Trace` will output something to the `os.Stdout`. This is the reason which hang the SSH. So don't output any log to `os.Stdout` when SSH process. Any idea to avoid this situation next?

**Comment by lunny** [comment]
The direction I have said that is moving all database operations to internal HTTP operations. I will send another PRs to do that.

**Comment by strk** [comment]
Sorry but I don't get why outputting to os.Stdout hangs, is there a deadlock ?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@strk  I think maybe the extra output to `os.Stdout` lets other command wait until the output is end.  But this is not the expected output so it's hangs.

**Comment by tbaschak** [comment]
This pull fixes my SSH issues!

**Pull request merged**
