### PR TITLE
Added gogs migration script

### PR DESCRIPTION
**Pull request by Bwko**
## This script needs testing on multiple platforms

Usage:

- Copy gogs_migrate.sh to your gogs directory
- Run as your gogs user
- Answer the questions
- Done!

Optional parameters:

` gogs_migrate.sh [-b Gitea binary] [-i Gitea install dir] [-o gogs binary] [-h help]`

Tested on:
- [x]  arch linux 64bit

Needs testing on
- [ ] MacOS
- [ ] arm Vx
- [ ] mips
- [ ] bsd with arm

### CODE REVIEW

**Comment by Bwko** [comment]
I think I'm done with this migration script :smile: 
This script:

- Checks if gogs is stopped & your running as the Gogs user
- Checks if this version of Gogs is supported
- Creates a backup of the Gogs files
- Downloads Gitea & the Gitea app.ini to your installation folder
- Copy's Gogs custom & data files
- Starts Gitea

Any comments on this migration script?

**Comment by georgevanburgh** [comment]
As much as I hate to be that guy - what about migrations on Windows?

**Comment by Bwko** [comment]
@FireEater64 When this migration script gets approved I'll create a Windows migration script

**Comment by tboerger** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by CumpsD** [comment]
Just wondering, if I would be migrating from Gogs in Docker to Gitea in Docker, I would probably do:

 * Run gogs_migrate.sh in the existing gogs container
 * Stop the container
 * Start Gitea container using the named volume from gogs
 * Profit?

**Pull request merged**
