### PR TITLE
Integrate public as bindata optionally

### PR DESCRIPTION
**Pull request by tboerger**
Since there have been people crying because of the big bindata PR I'm trying to split it into multiple smaller pull requests. This is the first step which embeds the public folder optionally into the binary with the build tag `bindata`. This pull requests obsoletes parts of #74.

### CODE REVIEW

**Comment by metalmatze** [comment]
I thought this was a huge PR, but then I saw all the `/vendor` diffs 😄 

LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by bkcsoft** [comment]
Which package is pulling in BoltDB and EtcD? o.O

**Comment by tboerger** [comment]
I think boltdb is a missing dependency for tidb, etcd I have not checked.

**Comment by lunny** [comment]
Why put go files in `public` dir? I think only static files could be put in it.

**Comment by tboerger** [comment]
Then we should also move all assets into another subfolder

**Comment by lunny** [comment]
Why? And another thing, now all the golint pass except `bindata.go` maybe we should ignore the file?

**Comment by tboerger** [comment]
Because of package name

**Comment by tboerger** [comment]
So what's up with it now? I would build the other bindata changes based on that.

**Comment by tboerger** [comment]
Ha, I will try to move the .go files to modules.

**Comment by tboerger** [comment]
I have moved the bindata now into modules/public/ and updated the web cmd as well. This should be fine now, including optional bindata.

**Comment by bkcsoft** [comment]
LGTM :)

**Pull request merged**
