### PR TITLE
Add GitTouch to mobile tools list

### PR DESCRIPTION
**Pull request by pd4d10**
Source code here: https://github.com/git-touch/git-touch

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for PR, have you also considered adding it to: https://gitea.com/gitea/awesome-gitea/

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
@techknowlogick It has been added. https://gitea.com/gitea/awesome-gitea/#mobile

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
@pd4d10 Please rebase

**Review by 6543 — APPROVED** [review]

**Comment by pd4d10** [comment]
@techknowlogick Yeah, it has already been added by someone.

@lunny Done

**Comment by 6543** [comment]
pleace resolve conflict (GitNex link was updated)

**Comment by jolheiser** [comment]
As mentioned in the top of the file being changed, this page has been deprecated (my own understanding) in favor of awesome Gitea. Should we be adding new things to it?

It creates another place to update when there's a change. (For example the recent Gitnex PR to this same page 😉 )

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
