### PR TITLE
Fix poor table column width due to breaking words

### PR DESCRIPTION
**Pull request by brechtvl**
Caused by #31091

---

Before
before

After
after

Example markdown for testing:
```
| **Report** | **Commits in `main`**  | **Remarks** |
| -- | -- | -- |
| | https://projects.blender.org/blender/blender/commit/e3a02b9b025282a46e74271ccf9ecfa6d780aac0 | |
| #111028 | https://projects.blender.org/blender/blender-addons/commit/3f1674ef5213d1c369f5039614d62742fe4b4a5f | was a duplicate of https://projects.blender.org/blender/blender-addons/issues/104723 [which is in 3.6.3] |
| | 2549272f02bd732260a978e0f98067d1c9a9fb95 | conflicts, assume this needs additional prior commit(s)? |
| #110204 | c275f4219f1482c0a89b0f91179058d60c007643 | conflicts because of 4f3e2ee857b5b9d5625513c3e5258eb71a2314c8, might not be backported |
| #111779 | 30e3caaf8291811f9c86a5721a67a976d18e5af2 | conflicts because of 1b4b90f5f79e3f3b30ba489dec9d35a5c72a58c2, might not be backported, would also need e924f316a7a8c5defcebd417166ebe93dbc8f72a |
```

### CODE REVIEW

**Comment by brechtvl** [comment]
@silverwind: In #31091 the entire `.markup` was set to `overflow-wrap: anywhere`. This changes it back to `overflow-wrap: break-word` for just tables. But I'm not sure if it's that's the right level.

**Comment by silverwind** [comment]
Ah, I did notice as well that table columns were not rendering as nicely in 1.22, this is likely the cause. I will verify this change, I assume it's okay because tables disregard many CSS behaviours that work on other elements, so I assume they ignore/mishandle `overflow-wrap`.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
So I think we should have `overflow-wrap: break-word;` on `.markup`, but that presents the overflow issue on code comment, which I think should be fixed by targeting this comment box specifically:

image

**Comment by silverwind** [comment]
Pushed a fix that satisfies both cases, it's not ideal but I find it quite hard to make the text wrap in these `conversation-holder`:

Without the override:
Screenshot 2024-06-24 at 15 26 08

With it:
Screenshot 2024-06-24 at 15 26 15

Checking for other solutions...

**Comment by silverwind** [comment]
I see no easy solutions, so I suggest we find a cleaner fix later and this will suffice for now.

**Review by silverwind — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
