### PR TITLE
Docker: allow mailer configuration via env vars

### PR DESCRIPTION
**Pull request by pat-s**
Added the full `[mailer]` section for both `root` and `rootless` templates.

To avoid conflicts I prefixed all with `MAILER`.

Due to laziness I linked to the templatel `app.ini` instead of describing all options again.

Relates to #350

### CODE REVIEW

**Comment by zeripath** [comment]
@pat-s are you aware of the contrib/environment-to-ini command?

**Comment by pat-s** [comment]
Not until now. It is also not mentioned anywhere in the docs atm, isn't it?

Not sure though if I would like to go this way - I guess I would prefer to set startup related env vars directly in the docker environment rather than using an app-specific workaround.

In the end only the startup related env vars are important if I'm not mistaken - others can be set by mounting a custom `app.ini` into the container?

**Comment by pat-s** [comment]
@zeripath Is there any conceptual missing or anything else that blocks this PR?

**Comment by pat-s** [comment]
@techknowlogick Appreciated if some could take a look at this :)

**Comment by pini-gh** [comment]
Doesn't seem needed anymore since  #14762.
See https://docs.gitea.io/en-us/install-with-docker/#managing-deployments-with-environment-variables.

**Comment by techknowlogick** [comment]
@pini-gh yup.

@pat-s thank you for your work on this. I will close this as the more generic solution is now in place, and it can merge with previously existing app.ini.

**Pull request closed without merging**
