### PR TITLE
Fix enabling partial clones on 1.17

### LINKED ISSUE #21805: gitea serv to enable partial clones with ssh
### Description

Ubuntu 22.04 lts

GIT_TRACE=1 git clone --filter=tree:0 ssh://gitea@gitea:38745/common/kernel.git
15:58:08.342028 git.c:455               trace: built-in: git clone --filter=tree:0 ssh://gitea@gitea:38745/common/kernel.git
Cloning into 'kernel'...
15:58:08.348827 run-command.c:668       trace: run_command: unset GIT_DIR; GIT_PROTOCOL=version=2 ssh -o SendEnv=GIT_PROTOCOL -p 38745 gitea@gitea.amarulasolutions.com 'git-upload-pack '\''/common/kernel.git'\'''
warning: filtering not recognized by server, ignoring

Gitea processo during clone

    CGroup: /system.slice/gitea.service
             ├─4093562 /opt/gitea/gitea web
             ├─4093737 /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filte>
             ├─4093738 /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filte>
             ├─4093739 /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filte>
             └─4093740 /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.25.1, Wire Protocol Version 2 Enabled

### Operating System

ubuntu 22.04 LTS

### How are you running Gitea?

gitea is official run from systemd on kvm machine not docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by zeripath**
When backporting #20902 in #21058 there was a slight misbackport. It was missed that we needed to remove the global command option before setting the settings.

Fix #21805

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
I don't quite understand why allowing less fixes an issue where the logs say
> filtering not recognized

?

**Comment by zeripath** [comment]
Look at the two quoted PRs

**Review by delvh — APPROVED** [review]
Ah, I see. Thanks

**Review by KN4CK3R — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
