### PR TITLE
Prevent server 500 on compare branches with no common history

### LINKED ISSUE #6527: Gitea not able to handle un-mergable branches' PR
- Gitea version (or commit ref): 1.8.0-rc2
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/rakshith-ravi/test/compare/master...fresh
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
2019/04/06 12:48:31 [...routers/repo/pull.go:727 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1
2019/04/06 12:51:03 [...routers/repo/pull.go:727 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1
2019/04/06 12:51:13 [...routers/repo/pull.go:727 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1
```

## Description
When I create a new branch that's orphaned, then try to create a PR to the master branch, it gives a 500. Ideally, it should give a way to rebase it on top of master or at least show that "this is not possible because ......"

On a completely different note, how do you guys usually handle those kinds of PRs to master? Is there an "industry standard" way to handle it? Just curious. Also, is it possible to have gitea rebase an orphan branch on top of master or something like that? That would be really nice.

## Screenshots

Irrelevant

### PR DESCRIPTION
**Pull request by zeripath**
This PR prevents the compare branch from sending a server 500 if there is no common history between branches. Instead it presents a simple compare page.

Fixes #6527 and probably others.

### CODE REVIEW

**Comment by zeripath** [comment]
I think 1.8 could do with this too. It's far too easy to get a 500 with this endpoint.

**Comment by techknowlogick** [comment]
@zeripath I am not 100% sure about a backport of this due to new translation being required (usually translations aren't backported), although I do like that this prevents 500s. If anyone else has feedback on being pro/anti backport please add it to this PR.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
I'm for backport as it is better to get error in English than get 500 page

**Review by jolheiser — APPROVED** [review]

**Comment by zeripath** [comment]
Backport done and merged.

**Pull request merged**
