### PR TITLE
Use router param for filepath in GetRawFile

### PR DESCRIPTION
**Pull request by jolheiser**
Part of #19449 broke the `GetRawFile` endpoint because it coincidentally didn't get to a func that modified a pointer as a side-effect.

It used to hit 
https://github.com/go-gitea/gitea/blob/fef26c159c7f426d7f6331b31e6d4119e47a9188/modules/context/api.go#L369
, which in turn ended up setting `ctx.Repo.TreePath` 
https://github.com/go-gitea/gitea/blob/fef26c159c7f426d7f6331b31e6d4119e47a9188/modules/context/repo.go#L803

This PR just uses the router param directly.

### CODE REVIEW

**Comment by Gusted** [comment]
CI failures are related.

**Comment by jolheiser** [comment]
Aha, so our tests use the legacy API. 
Alright, will look at a proper refactor.

**Review by 6543 — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
Really a simple fix. It should be fine. 😊

**Comment by jolheiser** [comment]
🎺 🤖

**Pull request merged**
