### PR TITLE
Return the full rejection message and errors in flash errors

### PR DESCRIPTION
**Pull request by zeripath**
Previously Gitea would just return the last 512 characters of a flash error.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### Screenshots

Screenshot from 2020-10-20 18-17-58

Screenshot from 2020-10-20 19-42-00

### CODE REVIEW

**Comment by jolheiser** [comment]
Could you add screenshots (similar to the ones in `#configuration` on Discord)?

**Comment by zeripath** [comment]
done - I created pre-receive hook that rejects with the contents of this patch

**Comment by jolheiser** [comment]
I don't suppose it would look any better to left-align it? It seems odd to see terminal errors center-aligned. 😅

**Comment by silverwind** [comment]
If it's always terminal output, it can possible use monospace font and `white-space: pre`.

**Comment by zeripath** [comment]
done

**Comment by silverwind** [comment]
Forgot to push? 🤣

**Review by silverwind — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by gabyx** [comment]
Oh this is awesome! Really good PR! Thanks alot!

**Comment by gabyx** [comment]
Thanks a lot @zeripath

**Comment by gabyx** [comment]
I was already thinking about if we could send markdown ;-) and render it down in the browser :-). Maybe another feature.
This is already really helpful!!

**Comment by techknowlogick** [comment]
🚀

**Comment by gabyx** [comment]
Could we get this feature already in 1.12.X ?

**Comment by zeripath** [comment]
This isn't a bug fix but rather an enhancement so it shouldn't really backported to 1.12. 

Backporting to 1.13 is not out of the question but we'd have to backport locale strings for it too.

https://github.com/zeripath/gitea/tree/backport-13221 is a cherry-picked backport to 1.13 which if it was agreed could be used to make a PR to 1.13

https://github.com/zeripath/gitea/tree/backport-13221-1.12 has a cherry-picked and conflict fixed backport to 1.12.

**Comment by mrsdizzie** [comment]
Agree on 1.13

**Pull request merged**
