### PR TITLE
fix: avoid frequent string2bytes conversions

### LINKED ISSUE #20939: When there's a huge file, escapeStreamer.Text will be very slow
### Description

When there's a huge file, escapeStreamer.Text will be very slow.

### Gitea Version

103b94f96

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Run ./gitea on linux.

### Database

MySQL

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #20939

Every time the pos moves, then whole string will be converted to bytes, when the data is huge, it will be very slow.

Related to #19990

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
It should be possible to further improve this by using a technique that will avoid the allocation of the []byte slice.

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by zeripath** [comment]
BTW There will be other performance improvements in this code.

**Review by lafriks — APPROVED** [review]

**Comment by delvh** [comment]
How do you approve a PR 4 days after it has been merged?
Doesn't GitHub only allow to `Submit a review` then?

**Comment by lafriks** [comment]
Yeah, I did not notice in GitHub mobile app it was already merged 😅

**Pull request merged**
