### PR TITLE
Fix api doc response code

### LINKED ISSUE #14120: API document error: userCreateToken API success responses code should be 201.
Please check: 
https://try.gitea.io/api/swagger/#/user/userCreateToken

Responses Code is 200 on the api document. But actually the request returned is 201.

### PR DESCRIPTION
**Pull request by noerw**
fixes #14120

### CODE REVIEW

**Review by a1012112796 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
We can't merge if you skip ci.

**Comment by zeripath** [comment]
make lg-tm work

**Comment by 6543** [comment]
@noerw such things are breaking!

normaly I added a TODO note vor api v2 on souch kind of things

**Comment by noerw** [comment]
the docs were inconsistent with actual behaviour, so i'm not sure what is going to break here? 🤔

**Comment by 6543** [comment]
@noerw sorry you are right you just correct the swagger doc - dont know what I had in mind while looking at this pull ?!?

**Pull request merged**
