### PR TITLE
Improve Docker container name

### PR DESCRIPTION
**Pull request by melroy89**
Use a better Docker container name rather than the default 'server'

### CODE REVIEW

**Comment by lafriks** [comment]
Doesn't docker compose already prefix it with project/directory name?

**Comment by danger89** [comment]
No it will use a automated generated name based on the service name, which is 'server'. And in my case it used the username and number. Result: `melroy_server_1`. 

After this merge, it will be:
`gitea_server`

**Comment by silverwind** [comment]
I'd prefer simply `gitea` over `gitea_server`.

**Comment by danger89** [comment]
> I'd prefer simply `gitea` over `gitea_server`.

Also fine by me.

**Comment by danger89** [comment]
Changed, I also moved to [version 3](https://docs.docker.com/compose/compose-file/compose-versioning/) of docker compose, which is advised.

**Review by lunny — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
