### PR TITLE
Hash App token

### LINKED ISSUE #3789: Application Personal Access Tokens are stored as plaintext in the database. Easy fix maybe.
- Gitea version (or commit ref): 1.3.0
- Git version: 2.7.4
- Operating system: osx
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

After creating  an application token, I checked the database, and the token is stored in plaintext in the database! This is bad because anyone that may gain access to the database would have access to all tokens.

Suggested fix is just to hash the token before storing it locally, for example, the token you give the user is `30ab72898b83c8549e510ee36cde7c7d7be01d97` becomes `A6DCC734FFB0E5A1E871E10C1B2A48CA60E9104F8F61FD41BD1DC01789062D81` when ran through a sha256 hash.

This way you can take what the user provides turing an authorized token use, and run the value they give you through sha256, and validate that the result matches what's in your database.

...

## Screenshots

screen shot 2018-04-13 at 5 09 00 am
screen shot 2018-04-13 at 5 08 51 am

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #3789

### CODE REVIEW

**Comment by jonasfranz** [comment]
What do you think about using bcyrpt with salt.

**Comment by techknowlogick** [comment]
@jonasfranz

I thought about that, but Gitea needs to search for token in DB, and if it is hashed with a salt, then Gitea would have to loop through all keys that exist in system and compute which one is the match. It could be simplified if the `token_last_eight` was used as a part of the SQL select, but I went with less resource intensive operation, and less impactful code change.

Typing this out now, has made me consider this even more, and good news is that it wouldn't require another PR to go-sdk. So I think I will make the change. Thanks for prompting me to re-consider.

**Comment by tamalsaha** [comment]
@techknowlogick , I left a comment https://github.com/go-gitea/gitea/issues/3789#issuecomment-486001661

**Comment by techknowlogick** [comment]
Ready for review

**Review by zeripath — APPROVED** [review]
I think v85.go might need changes equivalent to #6823 (once we're sure that that is correct.)

**Comment by techknowlogick** [comment]
@zeripath ahah yeah. I’ve been keeping an eye on those changes and I’ve just set this to blocked so it will only get merged once the other PR does

**Review by adelowo — APPROVED** [review]

**Comment by tboerger** [comment]
Great that you introduce such a breaking change into a minor release, you just killed the current Drone authentication.

**Comment by lafriks** [comment]
@tboerger it has been fixed already in #6903

**Comment by zeripath** [comment]
@tboerger I think we've had a few of these problems lately - would it be possible to write an integration test for Gitea that would ensure that we don't kill drone authentication by mistake.

**Pull request merged**
