### PR TITLE
Fix wrong default value for update checker on app.example.ini

### LINKED ISSUE #22078: Update checker documentation say it is disabled by default but it is enabled
### Description

https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/services/cron/tasks_extended.go#L153 enables by default the checker but sample app.ini or html doc says it is disabled by default: https://github.com/go-gitea/gitea/blob/0a85537c79b65f3b10a4b66265a23a8de46a2e43/custom/conf/app.example.ini#L2150

Can you fix the published doc please?

### Gitea Version

master

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #22078 

Note from @jolheiser: this **is not** breaking, but deserves a note in the changelog/blog to let users know. 🙂 
The label can be removed after the note has been added.

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
1. `cheatsheet.en_us` also has the incorrect value
2. shouldn't we mark that PR breaking for anyone who assumed that the opposite is the case?
Even if it isn't actually breaking itself, it's still good to know that it is different than what you thought…

**Comment by lunny** [comment]
> 1. `cheatsheet.en_us` also has the incorrect value
> 2. shouldn't we mark that PR breaking for anyone who assumed that the opposite is the case?
>    Even if it isn't actually breaking itself, it's still good to know that it is different than what you thought…

1. Done. 
2. I don't think this PR is a break change. It just corrected the document which is inconsistent with code.

**Comment by delvh** [comment]
Yes, I also don't think it is a breaking change.
However, we should notify users somehow that the default behavior has changed so that they can disable it if necessary.

**Review by delvh — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by jolheiser** [comment]
I've marked this as breaking only so we remember to make a note about it when generating the changelog/blog.

**Pull request merged**
