### PR TITLE
Translations for repo buttons

### PR DESCRIPTION
**Pull request by jolheiser**
Translations for #20719

GoLand must have tried helping with some whitespace when I saved, may be easier to view https://github.com/go-gitea/gitea/pull/20834/files?diff=unified&w=1

### CODE REVIEW

**Comment by silverwind** [comment]
Think some are missing, e.g. `locale_de-DE.ini`.

**Comment by delvh** [comment]
(Yep, I saw the discussion on Discord, and force approved the translation to include it in the release)

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
I vote hold this for a bit so that we can hopefully catch a few more translations when these are done.

**Comment by silverwind** [comment]
Yeah, fine with me to wait a bit more.

**Comment by 6543** [comment]
@jolheiser are there new translations?

**Comment by jolheiser** [comment]
Just one that I've now pushed. 
I believe I got them all, but was sick last week and so had to manually go through some commits this morning.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
