### PR TITLE
Correctly handle moved files in apply patch

### LINKED ISSUE #22083: Server error 500 creating a PR against a branch with changes to a file that has been renamed in the target branch
### Description

Creating a PR against a branch with changes to a file that has since been renamed in the target branch will cause an error 500 and inability to open the PR. When this happens, the server logs only say

```
2022/12/09 14:35:19 ...ers/web/repo/pull.go:1244:CompareAndPullRequestPost() [E] NewPullRequest: git apply --check: exit status 1
```

so it's difficult to understand what to do to work around it. The appropriate workaround is to update the source branch with latest from the target branch before opening the PR.

Specific repro steps:

1. Create a repo.
   1. https://try.gitea.io/parnic-sks/pr-renamed-files-test
1. Create a file. Make sure it's long enough that a rename + changing contents will still detect the rename.
   1. https://try.gitea.io/parnic-sks/pr-renamed-files-test/commit/aebe80c2ae9dd290c8359cb4e6c4df45ed23fc19
1. Create a branch from this commit.
   1. https://try.gitea.io/parnic-sks/pr-renamed-files-test/src/branch/file-change
1. Change something in that file and branch.
   1. https://try.gitea.io/parnic-sks/pr-renamed-files-test/commit/0bb985908ca24a8fd06972ee8a38a28297957ed8
1. Back in the target branch, rename the file and make a small change in it as well.
   1. https://try.gitea.io/parnic-sks/pr-renamed-files-test/commit/323c74cae5fda0b276daad71df0905503af7d331
1. Attempt to open a PR from the outdated source branch to the target branch with the renamed + changed file.
   1. https://try.gitea.io/parnic-sks/pr-renamed-files-test/compare/main...file-change
1. The diff on this page looks fine, but trying to actually create the PR results in a 500 error on client and "git apply --check" error on server.

I can supply specific git commands needed for each step if it's helpful, but hopefully they're obvious from the given links.

Locally running the `git apply` command that the server is presumably running results in the following message (that doesn't show up on the server):

```
> git show 0bb985908ca24a8fd06972ee8a38a28297957ed8 | git apply --check
error: 1.txt: No such file or directory
```

which is what clued me into the problem.

### Gitea Version

1.17.3, can also repro on try.gitea.io at v1.19.0+dev-171-g2779d47ad

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

See description

### Screenshots

image

image

### Git Version

2.37.3 on the Gitea v1.17.3 instance, whatever version is on try.gitea.io

### Operating System

Ubuntu 20.04.5 aarch64

### How are you running Gitea?

Built myself with a few modifications from v1.17.3 (mostly cherry-picking things from the future).

https://try.gitea.io however that's built

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by zeripath**
Moved files in a patch will result in git apply returning:

```
error: {filename}: No such file or directory
```

This wasn't handled by the git apply patch code. This PR adds handling for this.

Fix #22083

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by jtran** [comment]
I ran into the same 500 error.  The only difference is that the file on the target branch wasn't renamed; it was deleted.  When I cherry-pick this change, it doesn't fix the 500 error.  Can you verify the deleted case?  It might actually be simpler to test since you don't need a file that git detects as a rename.

**Review by techknowlogick — CHANGES_REQUESTED** [review]
temp blocking merge on this PR per @jtran's comment, feel free to remove this block as needed

**Comment by zeripath** [comment]
@jtran it would be really helpful to see the log message

**Comment by jtran** [comment]
@zeripath, this?

```
2022/12/13 12:43:49 [6398b9d5] router: started   POST /jon/Archimajor/compare/main...jt/end-stops3 for 127.0.0.1:63122
2022/12/13 12:43:49 ...ices/auth/session.go:51:SessionUser() [T] [6398b9d5] Session Authorization: Found user[1]
2022/12/13 12:43:49 ...ices/auth/session.go:67:SessionUser() [T] [6398b9d5] Session Authorization: Logged in user 1:jon
2022/12/13 12:43:49 models/repo/repo.go:316:LoadUnits() [T] [6398b9d5] repo.Units, ID=1, Types: [TypeCode, TypeIssues, TypePullRequests, TypeReleases, TypeWiki, TypeProjects, TypePackages]
2022/12/13 12:43:49 ...s/repo_permission.go:157:func1() [T] [6398b9d5] Permission Loaded for 1:jon in 1:jon/Archimajor:
	Permissions: perm_model.AccessMode: 4:owner, 7 Units, 0 UnitsMode(s): [
	Units[0]: ID: 1 RepoID: 1 Type: 1:TypeCode Config: {}
	Units[1]: ID: 2 RepoID: 1 Type: 2:TypeIssues Config: {"EnableTimetracker":false,"AllowOnlyContributorsToTrackTime":true,"EnableDependencies":true}
	Units[2]: ID: 3 RepoID: 1 Type: 3:TypePullRequests Config: {"IgnoreWhitespaceConflicts":false,"AllowMerge":true,"AllowRebase":true,"AllowRebaseMerge":true,"AllowSquash":true,"AllowManualMerge":false,"AutodetectManualMerge":false,"AllowRebaseUpdate":true,"DefaultDeleteBranchAfterMerge":false,"DefaultMergeStyle":"merge"}
	Units[3]: ID: 4 RepoID: 1 Type: 4:TypeReleases Config: {}
	Units[4]: ID: 5 RepoID: 1 Type: 5:TypeWiki Config: {}
	Units[5]: ID: 6 RepoID: 1 Type: 8:TypeProjects Config: {}
	Units[6]: ID: 7 RepoID: 1 Type: 9:TypePackages Config: {} ]
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= show-ref --tags
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch-check
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= show-ref --heads
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file -e main
2022/12/13 12:43:49 ...s/repo_permission.go:157:func1() [T] [6398b9d5] Permission Loaded for 1:jon in 1:jon/Archimajor:
	Permissions: perm_model.AccessMode: 4:owner, 7 Units, 0 UnitsMode(s): [
	Units[0]: ID: 1 RepoID: 1 Type: 1:TypeCode Config: {}
	Units[1]: ID: 2 RepoID: 1 Type: 2:TypeIssues Config: {"EnableTimetracker":false,"AllowOnlyContributorsToTrackTime":true,"EnableDependencies":true}
	Units[2]: ID: 3 RepoID: 1 Type: 3:TypePullRequests Config: {"IgnoreWhitespaceConflicts":false,"AllowMerge":true,"AllowRebase":true,"AllowRebaseMerge":true,"AllowSquash":true,"AllowManualMerge":false,"AutodetectManualMerge":false,"AllowRebaseUpdate":true,"DefaultDeleteBranchAfterMerge":false,"DefaultMergeStyle":"merge"}
	Units[3]: ID: 4 RepoID: 1 Type: 4:TypeReleases Config: {}
	Units[4]: ID: 5 RepoID: 1 Type: 5:TypeWiki Config: {}
	Units[5]: ID: 6 RepoID: 1 Type: 8:TypeProjects Config: {}
	Units[6]: ID: 7 RepoID: 1 Type: 9:TypePackages Config: {} ]
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file -e jt/end-stops3
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse refs/heads/jt/end-stops3
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= merge-base -- refs/heads/main refs/heads/jt/end-stops3
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse refs/heads/main
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= log 35a9e8a31fdb86b969d6a93f663a5d43a4143220...refs/heads/jt/end-stops3 --pretty=format:%H
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= diff -z --name-only refs/heads/main...refs/heads/jt/end-stops3
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5] /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= show-ref --heads
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= init
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= remote add -t main -m main origin /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= fetch origin --no-tags -- main:base main:original_base
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= symbolic-ref HEAD refs/heads/base
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= remote add head_repo /Users/myusername/gitea-data-1.17/repositories/jon/archimajor.git
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= fetch --no-tags head_repo refs/heads/jt/end-stops3:tracking
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= merge-base -- base tracking
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch-check
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= read-tree -m 35a9e8a31fdb86b969d6a93f663a5d43a4143220 base tracking
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= ls-files -u -z
2022/12/13 12:43:49 ...ll/patch_unmerged.go:163:unmergedFiles() [T] [6398b9d5-15] Got line: 1 100644 EndStops.SchDoc 23ad8485b53eab033fd3049dbbaa6ab9a0349fc8 Current State:
	<nil>
	<nil>
	<nil>
2022/12/13 12:43:49 ...ll/patch_unmerged.go:163:unmergedFiles() [T] [6398b9d5-15] Got line: 3 100644 EndStops.SchDoc 3c753e5ef5edb43a250534b1c113c8572dfc4ddb Current State:
	1 100644 EndStops.SchDoc 23ad8485b53eab033fd3049dbbaa6ab9a0349fc8
	<nil>
	<nil>
2022/12/13 12:43:49 ...rvices/pull/patch.go:128:attemptMerge() [T] [6398b9d5-15] Attempt to merge:
	1 100644 EndStops.SchDoc 23ad8485b53eab033fd3049dbbaa6ab9a0349fc8
	<nil>
	3 100644 EndStops.SchDoc 3c753e5ef5edb43a250534b1c113c8572dfc4ddb
2022/12/13 12:43:49 ...rvices/pull/patch.go:270:AttemptThreeWayMerge() [T] [6398b9d5-15] Conflict: EndStops.SchDoc in PR[0] jon/Archimajor#0
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= diff -p --binary --histogram 35a9e8a31fdb86b969d6a93f663a5d43a4143220 tracking
2022/12/13 12:43:49 ...rvices/pull/patch.go:348:checkConflicts() [T] [6398b9d5-15] PullRequest[0].testPatch (patchPath): /var/folders/sh/w_lwf0ss7gb34z423z30g9780000gn/T/patch1675702107
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= read-tree base
2022/12/13 12:43:49 ...dules/git/command.go:182:Run() [D] [6398b9d5-15] /Users/myusername/gitea/data/tmp/local-repo/pull.git3226040920: /opt/homebrew/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= apply --check --cached --3way /var/folders/sh/w_lwf0ss7gb34z423z30g9780000gn/T/patch1675702107
2022/12/13 12:43:49 ...ers/web/repo/pull.go:1244:CompareAndPullRequestPost() [E] NewPullRequest: git apply --check: exit status 1
	/Users/myusername/gitea/routers/web/repo/pull.go:1244 (0x105c54574)
		CompareAndPullRequestPost: ctx.ServerError("NewPullRequest", err)
	/Users/myusername/gitea/modules/web/wrap_convert.go:47 (0x105a88ceb)
		convertHandler.func3: t(ctx)
	/Users/myusername/gitea/modules/web/wrap.go:41 (0x105a86e77)
		wrapInternal.func1: done, deferrable := handler(resp, req, others...)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x10531412f)
		(*Mux).routeHTTP: h.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/web/wrap.go:63 (0x105a872f3)
		Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/web/wrap.go:63 (0x105a872f3)
		Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/web/wrap.go:63 (0x105a872f3)
		Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/get_head.go:37 (0x105ae3b0b)
		GetHead.func1: next.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/web/wrap.go:63 (0x105a872f3)
		Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/context/context.go:838 (0x1056bced7)
		Contexter.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 (0x105312037)
		(*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 (0x10531393f)
		(*Mux).Mount.func1: handler.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x10531412f)
		(*Mux).routeHTTP: h.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/routers/web/base.go:174 (0x105c939a7)
		Recovery.func1.1: next.ServeHTTP(w, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/gitea.com/go-chi/session@v0.0.0-20211218221615-e3605d8b28b8/session.go:257 (0x1051abe5f)
		Sessioner.func1.1: next.ServeHTTP(w, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/web/wrap.go:110 (0x105a87d77)
		WrapWithPrefix.func1.1: next.ServeHTTP(resp, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 (0x105312037)
		(*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 (0x10531393f)
		(*Mux).Mount.func1: handler.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x10531412f)
		(*Mux).routeHTTP: h.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/routers/common/middleware.go:79 (0x105ae89fb)
		Middlewares.func2.1: next.ServeHTTP(resp, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/context/access_log.go:38 (0x1056b1d33)
		AccessLogger.func1.1: next.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/modules/web/routing/logger_manager.go:123 (0x105a8298f)
		(*requestRecordsManager).handler.func1: next.ServeHTTP(w, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/strip.go:30 (0x105ae62db)
		StripSlashes.func1: next.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x105ae30f7)
		ForwardedHeaders.func1.1: h.ServeHTTP(w, r)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/gitea/routers/common/middleware.go:32 (0x105ae8863)
		Middlewares.func1.1: next.ServeHTTP(context.NewResponse(resp), req.WithContext(ctx))
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2084 (0x1046dff7b)
		HandlerFunc.ServeHTTP: f(w, r)
	/Users/myusername/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 (0x105311ff3)
		(*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
	/Users/myusername/gitea/modules/web/route.go:200 (0x105a86373)
		(*Route).ServeHTTP: r.R.ServeHTTP(w, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:2916 (0x1046e313b)
		serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
	/Users/myusername/sdk/go1.18.8/src/net/http/server.go:1966 (0x1046decbb)
		(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
	/Users/myusername/sdk/go1.18.8/src/runtime/asm_arm64.s:1270 (0x104280643)
		goexit: MOVD	R0, R0	// NOP


2022/12/13 12:43:49 ...s/context/context.go:220:HTML() [D] Template: status/500
2022/12/13 12:43:49 router: completed POST /jon/Archimajor/compare/main...jt/end-stops3 for 127.0.0.1:63122, 500 Internal Server Error in 365.2ms @ repo/pull.go:1126(repo.CompareAndPullRequestPost)
2022/12/13 12:43:49 [6398b9d5-31] router: started   GET /assets/css/index.css?v=1.17.3~45-gddf1c5857 for 127.0.0.1:63122
2022/12/13 12:43:49 [6398b9d5-31] router: completed GET /assets/css/index.css?v=1.17.3~45-gddf1c5857 for 127.0.0.1:63122, 200 OK in 0.8ms @ public/public.go:42(AssetsHandler)
2022/12/13 12:43:49 [6398b9d5-32] router: started   GET /assets/css/theme-auto.css?v=1.17.3~45-gddf1c5857 for 127.0.0.1:63124
2022/12/13 12:43:49 [6398b9d5-32] router: completed GET /assets/css/theme-auto.css?v=1.17.3~45-gddf1c5857 for 127.0.0.1:63124, 200 OK in 0.2ms @ public/public.go:42(AssetsHandler)
2022/12/13 12:43:49 [6398b9d5-33] router: started   GET /assets/js/index.js?v=1.17.3~45-gddf1c5857 for 127.0.0.1:63124
2022/12/13 12:43:49 [6398b9d5-34] router: started   GET /assets/img/logo.svg for 127.0.0.1:63122
2022/12/13 12:43:49 [6398b9d5-34] router: completed GET /assets/img/logo.svg for 127.0.0.1:63122, 200 OK in 0.4ms @ public/public.go:42(AssetsHandler)
2022/12/13 12:43:49 [6398b9d5-33] router: completed GET /assets/js/index.js?v=1.17.3~45-gddf1c5857 for 127.0.0.1:63124, 200 OK in 1.3ms @ public/public.go:42(AssetsHandler)
2022/12/13 12:43:49 [6398b9d5-35] router: started   GET /avatars/00388ce725e6886f3e07c3733007289b?size=72 for 127.0.0.1:63124
2022/12/13 12:43:49 [6398b9d5-36] router: started   GET /assets/img/500.png for 127.0.0.1:63122
2022/12/13 12:43:49 [6398b9d5-36] router: completed GET /assets/img/500.png for 127.0.0.1:63122, 200 OK in 0.3ms @ public/public.go:42(AssetsHandler)
2022/12/13 12:43:49 [6398b9d5-35] router: completed GET /avatars/00388ce725e6886f3e07c3733007289b?size=72 for 127.0.0.1:63124, 200 OK in 0.6ms @ web/base.go:29(avatars)
```

**Comment by jtran** [comment]
I wanted to see what git was outputting.  I added a log statement in step 8 of `checkConflicts()` here:

```go
				for scanner.Scan() {
					line := scanner.Text()
					log.Warn("***************** line=%q", line)
```

This is what I got.  Only one line:

```
2022/12/13 15:15:33 ...rvices/pull/patch.go:419:func3() [W] [6398dd65-30] ***************** line="error: EndStops.SchDoc: does not exist in index"
```

**Comment by zeripath** [comment]
Thanks! 

I've added a `log.Trace` where you added the temporary `log.Warn` and added the "does not exist in index" suffix too.

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
