### PR TITLE
Make home.tmpl visible with Signin-View enabled

### LINKED ISSUE #3846: [Suggestion] Make home.tmpl visible with Signin-View enabled
Hello,
when you set `REQUIRE_SIGNIN_VIEW` to true, the frontpage/home is not visible, only the login form will show up. If you login your home is replaced by the dashboard. So you never see it. 

The signin view is a good feature to improve security for the code, but I would like to show a nice company logo and maybe some introduction, especially if used in intranet and internet. 

Any possibility to show the home.tmpl with signin_view enabled? Maybe beneath the login form, or the login form is only forced if you click any other link or does anyone has confidential information on home?

Cheers!

### PR DESCRIPTION
**Pull request by ghost**
Fix #3846

### CODE REVIEW

**Review by jonasfranz — APPROVED** [review]

**Comment by daviian** [comment]
LGTM

**Comment by agaida** [comment]
Not a good idea - with that merged the LANDING_PAGE setting is ignored

**Comment by lunny** [comment]
~So this result in a bug. @agaida maybe you can fire an issue.~ see #4079

**Comment by nillith** [comment]
Why can't you just add a new opt in option instead of changing the default behavior of REQUIRE_SIGNIN_VIEW? I upgraded from 1.1 to 1.5 now all the users, organizations and public repositories are exposed. What can I do? Stick with 1.1?

**Comment by lunny** [comment]
@nillith this PR will only expose home page that should have no any usable contents. I think your problem maybe not effected by this PR.

**Comment by cht47** [comment]
I can confirm that the change is working like intended. @nillith it seems you have configured something wrong. REQUIRE_SIGNIN_VIEW = true keeps everything save from anonymous users. The only thing you can see now is the home.tmpl (which was never visible before that change with require_signin true)

**Comment by nillith** [comment]
**home.tmpl >> base/head.tmpl >> base/head_navbar.tmpl >> Explore and BOOM** . This is the path where all the things are exposed.
I'm pretty sure this is the causal change. I did a clean install and got the same problem. REQUIRE_SIGNIN_VIEW literally means you can only see the login page. Any other things you'd like to expose must be explicitly specified.

**Comment by lafriks** [comment]
I would agree with @nillith as it is kind of annoying on having to click on login menu all the time

**Comment by lunny** [comment]
@nillith @lafriks I agree with that's some annoying but I think @nillith 's
> I upgraded from 1.1 to 1.5 now all the users, organizations and public repositories are exposed.

is not effected by this PR.

**Comment by nillith** [comment]
@lunny ~~I think its already written on the wall.  The `home.tmpl` contains more than just the home page.~~ And I tried the version `1.4.3` and `1.6`. `1.6` have the same problem and `1.4.3` is OK. 
It looks like the problem only happens after the first installation and disappeared after I restart the docker container. So I think it's fine.

**Comment by cht47** [comment]
Ok I'm not using a docker container, maybe there is another problem with it. Can't see a problem where it is annoying to click on login. For EU you must deliver an Imprint, Cookie Law, GDPR. Forcing it on the front page is the best option in this case as you can't add some fancy modals. For Intranet only you don't need REQUIRE_SIGNIN_VIEW. Right Management can handle access to repos.

**Comment by kandeshvari** [comment]
@cht47 Habitual behavior was changed. I(and many others) don't need home screen at all and yes - it's really annoying to click Login button every time I go to my intranet git (I even searched and found this issue!). There was a reasonable question - why don't provide new option instead of changing old one?

**Pull request merged**
