### PR TITLE
Fix 500 caused by branches settings introduced by #1198

### PR DESCRIPTION
**Pull request by lunny**
@geek1011

### CODE REVIEW

**Comment by strk** [comment]
trusted LGTM

**Comment by pgaskin** [comment]
It's good, sorry about the bug I caused. Thanks for fixing it @lunny. 

I will check more carefully that I pushed everything to my branch next time because I amended that same fix to my own PR, but forgot to force push.

**Comment by lunny** [comment]
@geek1011 don't worry, more tests will resolve this-like problems. I have ever pushed many broken PRs.

**Comment by strk** [comment]
@geek1011 the best way to be more careful is to write more tests, a lot of work has gone to that direction already, are you up to make your hands dirty in that land ?

**Comment by ethantkoenig** [comment]
LGTM

**Comment by pgaskin** [comment]
@strk Yes, I am getting familiar with tests right now.

**Pull request merged**
