### PR TITLE
Update JS dependencies and webpack

### PR DESCRIPTION
**Pull request by silverwind**
- Update all JS dependencies
- Adapt webpack config for version 5
- Update to Less 4.0, adapting usage of removed mixin syntax
- Enable new ESLint rules and fix discovered issues

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by CirnoT** [comment]
`webpack-cli` can be updated to v4, it's backwards compatible

**Comment by silverwind** [comment]
> webpack-cli can be updated to v4, it's backwards compatible

cli flags seem to have changed in an incompatible way and it also seems compilation gets slower with the upgraded cli. I'll check thought.

```
[webpack-cli] Unknown argument: --hide-modules
[webpack-cli] Unknown argument: --display-entrypoints=false
```

**Comment by silverwind** [comment]
I don't think we can upgrade `webpack-cli` without also upgrading `webpack` because of those output options. It seems the new way to set them is in the `stats` option in the config but they seem to have no effect, so I think we should skip that upgrade until we also do webpack.

**Comment by silverwind** [comment]
It looks like there's actually no more blockers for webpack 5, monaco plugin does not specify compatibilty but seems to work, so I'll try putting that update in here.

**Comment by silverwind** [comment]
Upgrade to webpack 5 is now included as well as some changes regarding nicer monaco language chunk filenames. The stats output has changed considerably and I've tried to replicate what we had before (e.g. just a list of output assets).

**Comment by silverwind** [comment]
Prod build is failing, it looks like we're blocked by https://github.com/xz64/license-webpack-plugin/issues/67 with webpack 5.

**Comment by silverwind** [comment]
Switched to a different license generation plugin that is compatible with webpack 5. Output should be nearly identical but that plugin does not offer a way to manually add modules so octicons is currently not featured in the output.

**Comment by silverwind** [comment]
Still some webpack issues.

**Comment by silverwind** [comment]
Ok it's ready now. I had to overwrite one module for license generation because it had a non-compliant `license` field. Maybe we can later switch back to `license-webpack-plugin` once it's compatible with webpack 5.

**Comment by CirnoT** [comment]
`license-webpack-plugin` should be compatible now https://github.com/xz64/license-webpack-plugin/releases

**Comment by silverwind** [comment]
Found one more issue with it: https://github.com/xz64/license-webpack-plugin/issues/89

**Comment by silverwind** [comment]
I think we shouldn't be holding off this update until `license-webpack-plugin` as there may be yet another issue with that plugin where it misses some licenses. The current plugin works and the only issue I have with it is that it offers no way to manually add modules or disable the license checking, but those are minor.

**Comment by silverwind** [comment]
Switched back to `license-webpack-plugin` as the latest version is now working, at least to some extend. It is missing detection of a few modules as compared to previously, see https://github.com/xz64/license-webpack-plugin/issues/91 for it. Not a blocker thought.

`monaco-editor-webpack-plugin` was updated as well which now officially states webpack 5 compat, even thought it was already working previously.

**Comment by silverwind** [comment]
Everything working now, squashed and ready.

**Comment by silverwind** [comment]
Gone back to the other license plugin because it performs much faster.

`license-webpack-plugin`09:20: https://drone.gitea.io/go-gitea/gitea/34349/1/8
`license-checker-webpack-plugin` 04:01 -  https://drone.gitea.io/go-gitea/gitea/34351/1/8

Overall, webpack 5 seems about 20% slower than webpack 4 but I guess it's something we have to accept for now.

**Comment by lunny** [comment]
@silverwind If it's slower, but an upgrade is really necessary?

**Comment by silverwind** [comment]
Right now we could live with webpack 4 but it will eventually go out of support and if I recall correctly, webpack 5 will be required for certain things like https://github.com/go-gitea/gitea/issues/12459 because if offers additional options.

I plan to look into pre-building monaco which is the biggest chunk of webpack build time, which should then get us down to probably half of what it is now.

**Comment by silverwind** [comment]
Actually the perf regression isn't so bad, maybe 10% and I expect it to become faster in future updates.

**Review by lafriks — APPROVED** [review]

**Comment by azhai** [comment]
Remove the dir named node_modules, and rebuild
删除 node_modules 目录，然后重新编译 
```bash
rm -rf node_modules/
TAGS="bindata sqlite sqlite_unlock_notify" make build
```

**Pull request merged**
