### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by 42wim**
Added myself as maintainer.
[List of PRs](https://github.com/go-gitea/gitea/pulls?q=is%3Apr+author%3A42wim+is%3Aclosed)

### CODE REVIEW

**Review by Gusted — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Congratulations @42wim

**Comment by zeripath** [comment]
Could please tell me your username on discord and I will add you to the maintainers. Unfortunately I can't do that on GH as it appears I don't have the right role although I am a member of the right team.

**Review by 6543 — COMMENTED** [review]
Welcome

**Comment by 42wim** [comment]
Thanks!

**Pull request merged**
