### PR TITLE
Attachment support repository route

### LINKED ISSUE #15550: Pasted images have wrong repo-based URL
- Gitea version (or commit ref): `1.15.0+dev-165-g5e85cdad2`
- Can you reproduce the bug at https://try.gitea.io: https://try.gitea.io/silverwind/symlink-test/issues/6#issuecomment-77653

## Description
Pasting an image results in it being linked on the wrong URL:

```
https://try.gitea.io/silverwind/symlink-test/attachments/265b512e-f7a7-46a0-922c-7afe1bc0f530
```
But it should be
```
https://try.gitea.io/attachments/265b512e-f7a7-46a0-922c-7afe1bc0f530
```

Markdown and HTML:

```md
![image](/attachments/265b512e-f7a7-46a0-922c-7afe1bc0f530)
```
```html
<a href="/silverwind/symlink-test/attachments/265b512e-f7a7-46a0-922c-7afe1bc0f530" rel="nofollow"><img src="/silverwind/symlink-test/attachments/265b512e-f7a7-46a0-922c-7afe1bc0f530" alt="image"></a>
```

Image attachments via dropzone are not affected, see comment below.

### PR DESCRIPTION
**Pull request by lunny**
The new route reuse old function to allow a new entry for easier reference from comments/issues .

Should fix #15550

### CODE REVIEW

**Comment by silverwind** [comment]
The regression (https://github.com/go-gitea/gitea/pull/15088) was not backported so I think this one wouldn't need a backport.

**Comment by silverwind** [comment]
If the attachment ids are guaranteed to be uuids, I think I would still prefer a regex route so users can have `/attachments/file.txt` working for a file in the repo.

**Comment by silverwind** [comment]
Actually this is LGTM because it seems it's not possible to link a image from the repo in issue comments so there is no actual namespace conflict.

**Review by silverwind — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
