### PR TITLE
Add docs on passing SSH through to container

### PR DESCRIPTION
**Pull request by Xiol**
Wasn't clear how to pass SSH connections through the container, found a
few blog posts which described roughly the same procedure I've
documented here.

Credit should really go to:

* https://blog.sakuragawa.moe/gitea-in-docker-container-and-sharing-ssh-with-host/
* http://www.ateijelo.com/blog/2016/07/09/share-port-22-between-docker-gogs-ssh-and-local-system

Signed-off-by: Dane Elwell <dane.elwell@ukfast.co.uk>

### CODE REVIEW

**Comment by adelowo** [comment]
Fixes https://github.com/go-gitea/gitea/issues/4978

**Comment by techknowlogick** [comment]
With the plan on removing OpenSSHD from the container, this would no longer work so I'm hesitant to add this to documentation

**Comment by lafriks** [comment]
When we switch to builtin ssh we can always remove this section but while we have not switched it is still good to have it

**Comment by techknowlogick** [comment]
@lafriks ok. sounds good.

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Review by lafriks — CHANGES_REQUESTED** [review]
Please add note somewhere that this will work only if using opensshd in container and will not work if `AuthorizedKeysCommand` is used with setting to disable authorized files key generation: https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample#L157

**Comment by techknowlogick** [comment]
@lafriks I've updated PR with changes from your feedback, please review

**Review by lafriks — APPROVED** [review]

**Pull request merged**
