### PR TITLE
When the git ref is unable to be found return broken pr

### LINKED ISSUE #13216: Add Fallback for Pulls Diff when missing commits
if a pull was **merged** and the pull head branch ref got missing or point to commits who are missimg, use the merged-sha as fallback to generate the diff view

To Test:
1. create repo A
2. frok repo A to repo B
3. backup bare repo A
4. create feature branch on B and add some commits
5. create pull from B to A & squash-merge
6. clone A to local disk
7. restore backup of A
8. push local clone back to gitea

what I expect -> cliking on Files-Changed will show the diff based on merged-commit as **fallback**

### PR DESCRIPTION
**Pull request by zeripath**
Fix #13216

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]
you are right.
By the way, maybe should set ``LANG`` envirment verb when init gitea to ``en_US.UFT-8`` to make sure git print error message in english.
for example
image

**Review by 6543 — CHANGES_REQUESTED** [review]
it will fix the 500 but wont fix the 13216 !

**Comment by zeripath** [comment]
@a1012112796 #8548 https://github.com/go-gitea/gitea/blob/5626811e5298fa45a8a9b4af76fd5644ac3d3b3b/modules/git/command.go#L125-L131

**Comment by 6543** [comment]
1. create repo A
2. frok repo A to repo B
3. backup bare repo A
4. create feature branch on B and add some commits
5. create pull from B to A & squash-merge
6. clone A to local disk
7. restore backup of A
8. push local clone back to gitea

without this pull: 500
with this pull: working pull view but `N/A` on "Files changed"-Tab

what I expect to fix 13216 -> cliking on Files-Changed will show the diff based on merged-commit as **fallback**

**Review by 6543 — APPROVED** [review]
nice bugfix - wont fix ref issue

**Pull request merged**
