### PR TITLE
Make TaskCheckBox render correctly

### LINKED ISSUE #11213: Markdown checkboxes are inverted
- Gitea version (or commit ref): 1.12.0+dev-217-g4ddfe0d07
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - https://try.gitea.io/test_org21/test_repo/issues/4
  - [ ] No
  - [ ] Not relevant

## Description

Most likely since 812cfd0ad9bb85b13ce77f611b3c80dad371d1ef; checkbox are inverted (that is, empty checkboxes are rendered selected, selected ones are rendered as unselected)

### PR DESCRIPTION
**Pull request by zeripath**
* Add correct styling to TaskCheckBoxes.
* Restore the correct check order

Fix #11213 

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
For some unknown reason prior to https://github.com/go-gitea/gitea/commit/812cfd0ad9bb85b13ce77f611b3c80dad371d1ef isChecked meant that the checkbox should be rendered not checked but after this commit it has returned to the correct sense. I have been unable to find any clear reason why this happened.

**Comment by CirnoT** [comment]
It would seem that tasklist renderer took over and `renderTaskCheckBox` was never executed in the first place.

**Comment by zeripath** [comment]
As discussed on discord previously these checkboxes were rendered incorrectly - I have now restored the correct fomantic styling.

**Comment by CirnoT** [comment]
Works fine here, but I have one small nitpick about how it looks on light style:

chrome_2020-04-25_22-30-57


I am wondering if it wouldn't be better to apply `read-only` instead of `disabled`:

chrome_2020-04-25_22-32-03


While I realize that `disabled` does a better job for cases like above, where it's a single checkbox, on a long lists of to-do items it might look a little weird.

**Comment by CirnoT** [comment]
^ Here's example with a rather long list, notice how links can't be clicked on when `disabled` is present:

chrome_2020-04-25_22-42-36

**Comment by zeripath** [comment]
Thanks for checking that I had totally missed that problem!

**Comment by zeripath** [comment]
Setting them to readonly instead appears to fix the problem.

**Review by lafriks — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Pull request merged**
