### PR TITLE
Remove jQuery from the image pasting functionality

### PR DESCRIPTION
**Pull request by yardenshoham**
- Switched to plain JavaScript
- Tested the image pasting functionality and it works as before

# Demo using JavaScript without jQuery
demo

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Nice work as always.

**Comment by yardenshoham** [comment]
🫡 Glad to be of service.

**Comment by delvh** [comment]
Offtopic, but: Did I forget to approve any of these PRs?

**Comment by yardenshoham** [comment]
https://github.com/go-gitea/gitea/pull/29230

**Pull request merged**
