### PR TITLE
 Fix aria.js bugs: incorrect role element problem, mobile focus problem, tippy problem (#23450)

### PR DESCRIPTION
**Pull request by wxiaoguang**
Manually backport #23450 (it's better to have it for 1.19 release)

----

Before: the `aria.js` is still buggy in some cases.

After: tested with AppleVoice, Android TalkBack (I tested it with 1.19 again)

* Fix incorrect dropdown init code
* Fix incorrect role element (the menu role should be on the `$menu` element, but not on the `$focusable`)
* Fix the focus-show-click-hide problem on mobile. Now the language menu works as expected
* Fix incorrect dropdown template function setting
* Clarify the logic in aria.js
* Fix incorrect tippy `setProps` after `destroy`
* Improve comments
* Implement the layout proposed by #19861

### CODE REVIEW

**Comment by wxiaoguang** [comment]
> I assume this backport now needs changes.

I have tested on my side, didn't see a problem. Do you find some problems?

**Comment by wxiaoguang** [comment]
> I mean it's outdated with original PR #23450.

I didn't see which part is outdated, can you elaborate?

**Comment by silverwind** [comment]
Ah, so you updated and I've misread the commit log. Was it a clean merge?

**Comment by wxiaoguang** [comment]
Yes, it's a clear merge, I cherry-picked and compared.

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
@wxiaoguang fyi, it seems some of your commit titles have a leading space, which causes isses in changelog generation like [here](https://github.com/go-gitea/gitea/pull/23583/files#r1141486827.). I opened https://gitea.com/gitea/changelog/issues/74 to fix it at changelog generator too, but would appreciate if you can check how those happen.

**Comment by wxiaoguang** [comment]
Thanks for reminding. Will pay more attention to it.

It's like caused by a Copy&Paste, but after submitting the PR, there is no chance to double-check the title, that's why I can't find the problem.


I guess the last chance is at the merging time, merger could make sure the commit message is properly formatted.

When I was doing merger's job, I almost edit every commit message manually, to fine tune them.

**Pull request merged**
