### PR TITLE
Fix renaming bug

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fix oversight from #1766

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
LGTM, but it's strange why the CI reported build success?

**Comment by ethantkoenig** [comment]
@lunny Usages of the old variable name had been added to master between when the PR CI ran and when the PR was merged into master.

**Comment by pgaskin** [comment]
LGTM, even though it's already done 😄

**Comment by lunny** [comment]
@ethantkoenig if another PR merged, the CI should be restarted again?

**Comment by appleboy** [comment]
@lunny The CI only build master branch if PR merged.

**Comment by ethantkoenig** [comment]
@lunny No, that would flood Drone (we already have a problem with CI jobs getting queued up)

**Pull request merged**
