### PR TITLE
Fix timezone on issue deadline

### LINKED ISSUE #11686: Issue due date affected by time zone
Setting a issue due date send a full UTC date `due_date: "2020-05-25T00:00:00.000Z"` to the backend but depending on the user's time zone, the displayed date may not be `2020-05-25`. We should probably convert the time to 00:00 in the user's current time zone and then send UTC for that.

### PR DESCRIPTION
**Pull request by CirnoT**
Fixes https://github.com/go-gitea/gitea/issues/11686
Closes https://github.com/go-gitea/gitea/pull/11688

Ensures that deadline is saved in server's timezone, not UTC.

### CODE REVIEW

**Comment by silverwind** [comment]
Can we keep the format change to `YYYY-MM-DD`? I don't like this inconsistency in the date formats.

```go
// FormatDate formats a date in YYYY-MM-DD server time zone
func (ts TimeStamp) FormatDate() string {
  return time.Unix(int64(ts), 0).String()[:10]
}
```

And use that instead of `formatShort` in `templates/repo/issue/view_content/sidebar.tmpl`.

**Comment by CirnoT** [comment]
Done

**Review by silverwind — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I think this fixes some other date based bugs too but I don't have the issue numbers to have

**Comment by techknowlogick** [comment]
@CirnoT please send backport :)

**Pull request merged**
