### PR TITLE
Fix https setup doc zh-cn

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by silverwind** [comment]
Has conflicts.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Let's wait on https://github.com/go-gitea/gitea/pull/24021 to merge here and then validate that PR with this one.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
> Let's wait on #24021 to merge here and then validate that PR with this one.

Sorry saw that afterwards

**Comment by silverwind** [comment]
This PR again [broke](https://drone.gitea.io/go-gitea/gitea/71962/1/4) the complicance pipeline because it fails markdownlint. Suggesting to land https://github.com/go-gitea/gitea/pull/24021 now and skip CI check for it so future docs-only PRs are validated correctly.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/24024 should fix the anchor

**Pull request merged**
