### PR TITLE
Remove simplemde console.log spam

### PR DESCRIPTION
**Pull request by silverwind**
simplemde seems to contain console.log spam which is visible on every page with it running. No idea why this is even in there, but I silenced it via replacing the two statements with `undefined` (the return value of console.log).

### CODE REVIEW

**Comment by silverwind** [comment]
Apparently this is https://github.com/sparksuite/simplemde-markdown-editor/pull/348/files

**Comment by silverwind** [comment]
I will move it to npm and upgrade to latest version which does not have the spam.

**Comment by silverwind** [comment]
Putting this up again because:

- Latest version of SimpleMDE is not a drop-in, it fails at some CodeMirror stuff
- Getting SimpleMDE+CodeMirror plugins/modes loaded in Webpack is a nightmare of its own because CodeMirror does not support bundlers with its lazy-loading approach.

**Comment by gary-kim** [comment]
I think it should be possible to use the version on npm by putting something like
```javascript
import 'simplemde';
```.

**Comment by silverwind** [comment]
`import 'simplemde';` will include the code in the main JS bundle that needs to parse on every page load and for that SimpleMDE is just too big (around 250kB).

This here is just a stop-gap solution to the console spam. Either https://github.com/go-gitea/gitea/pull/9973 or a proper upgrade to latest 2016 version of SimpleMDE will fully resolve it.

**Comment by lafriks** [comment]
@silverwind `import 'simplemde';` can be added to new entrypoint also to not bundle it with main

**Comment by silverwind** [comment]
Yeah, it can be lazy-loaded of course, but it's more than just that as codemirror's lazy-loading (which is incompatible with webpack) also needs to be re-implemented. See https://github.com/go-gitea/gitea/pull/9973#issuecomment-596125416.

**Comment by silverwind** [comment]
I guess a individual chunk with just the sync import and the script tag replaced and pointing to the webpack chunk may also work.

**Comment by lafriks** [comment]
Yes, that is what I mean

**Comment by silverwind** [comment]
Yeah that would be similar to how [jQuery](https://github.com/go-gitea/gitea/blob/master/web_src/js/jquery.js) is done currently. I'm not really a fan of such solutions because it will generate polyfill overhead as each chunk gets their own set of polyfills.

**Comment by lafriks** [comment]
But at least we can update dependencies using npm

**Comment by silverwind** [comment]
IMHO, our time is better invested removing SimpleMDE altogether. It weights in at 300kb for what could probably be done in 5-10kB with a simple `<textarea>` and a few buttons that insert snippets at the cursor.

**Comment by silverwind** [comment]
Closing as this does not seem to get any acceptance.

**Pull request closed without merging**
