### PR TITLE
Remove stars in dashboard repo list

### PR DESCRIPTION
**Pull request by yp05327**
Discussion is here: https://github.com/go-gitea/gitea/pull/22816

### CODE REVIEW

**Comment by silverwind** [comment]
It may be possible that there is some CSS to remove as well, should double-check.

**Comment by silverwind** [comment]
Don't see any CSS, so we should be good on that front.

Please remove `gt-mr-2` on line 75, it's no longer necessary.

**Comment by yp05327** [comment]
> Please remove gt-mr-2 on line 75, it's no longer necessary.

Done.

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Please remove `gt-mr-2` on line 75, it's no longer necessary.

I guess most styles are unnecessary now, because there is only one element for the link now. (just curious, not a must 😁  )

**Comment by silverwind** [comment]
> I guess most styles are unnecessary now, because there is only one element for the link now. (just curious, not a must 😁 )

Those flex-related styles are good to keep I think, especially the `f1`.

**Review by lunny — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping lg-tm

**Pull request merged**
