### PR TITLE
Optimize docker registry response code

### PR DESCRIPTION
**Pull request by hiifong**
Use `UNSUPPORTED` response code instead of `InternalServerError` response code.

Ref: https://github.com/distribution/distribution/blob/main/docs/content/spec/api.md#errors-2

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I do not think it is right, it seems to be an abuse of "UNSUPPORTED"

**Comment by hiifong** [comment]
> InternalServerError

Currently I think UNSUPPORTED will have detailed errors, at least better than InternalServerError

**Comment by wxiaoguang** [comment]
> > I do not think it is right, it seems to be an abuse of "UNSUPPORTED"
> 
> Currently I think UNSUPPORTED will have detailed errors, at least better than InternalServerError.

1. These errors shouldn't happen in daily usage, if it happens, end users still could do nothing.
2. It depends on what kind of error you'd like to show to, it is intentionally "not show every internal error to end users" because some errors might contain sensitive server side messages (eg: filesystem path, database IP, etc). If you'd like to show errors to end users, it's better to clearly define what end users would see.

**Comment by wxiaoguang** [comment]
Even you do not care about server-side sensitive information, always returning "unsupported' is definitely an abuse to the docker status code.


1. you are reporting internal errors, it doesn't mean it is not supported 
2. if you read docker's document, you could see that "unsupported" is not defined for every API response, if you'd like to strictly follow docker's document, many API should not respond "unsupported".


So I'd like to suggest do not spend more time on this, unless you have a clear plan to use it in some real cases.

**Comment by hiifong** [comment]
> > > I do not think it is right, it seems to be an abuse of "UNSUPPORTED"
> > 
> > 
> > Currently I think UNSUPPORTED will have detailed errors, at least better than InternalServerError.
> 
> 1. These errors shouldn't happen in daily usage, if it happens, end users still could do nothing.
> 2. It depends on what kind of error you'd like to show to, it is intentionally "not show every internal error to end users" because some errors might contain sensitive server side messages (eg: filesystem path, database IP, etc). If you'd like to show errors to end users, it's better to clearly define what end users would see.

But there was an error message returned before.
image
Maybe we should desensitize misinformation.

**Comment by wxiaoguang** [comment]
> But there was an error message returned before.

No, they don't.


image

**Review by lafriks — CHANGES_REQUESTED** [review]
It should not return unsupported for internal errors (ex when the database could be unavailable for a moment etc), also returning internal error message to client is no go from security perspective

**Comment by wxiaoguang** [comment]
> So I'd like to suggest do not spend more time on this, unless you have a clear plan to use it in some real cases.

Again, do not spend time on it unless you have a clear picture about it.

**Pull request closed without merging**
