### PR TITLE
Changelog for v1.3.0

### PR DESCRIPTION
**Pull request by lafriks**
As title

### CODE REVIEW

**Comment by bkcsoft** [comment]
Again a _very_ verbose Changelog 🙄 

LGTM

**Comment by lafriks** [comment]
Yeah, I think we need to include in milestone only important changes that we need on changelog

**Comment by strk** [comment]
is the git-1.7 support going to make it into 1.3 ? there's a backport/1.3 label on the corresponding PR

**Comment by lunny** [comment]
@strk so please send a backport PR to v1.3 before we merge this one.

**Comment by lunny** [comment]
LGTM

**Pull request merged**
