### PR TITLE
Use chronological commit order in default squash message

### LINKED ISSUE #13661: Commit messages in chronological order for default squash and merge message
- Gitea version (or commit ref): 1.12.6
- Operating system: docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/jpraet/test/pulls/3)
  - [ ] No

## Description

The default generated commit message for squash and merge places the commit messages in reverse chronological order. Wouldn't it make more sense to put these in chronological order, to keep the order of the steps that were done to implement the change? Also, there is a blank line in between each commit message which I don't think is really necessary?

## Screenshots

image

Desired:

image

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #13661

Note that the ticket also mentioned potentially removing the empty lines between commit messages. I haven't changed that for now because I'm not too sure about it. If you are squashing multiple commits, all with detailed multi-line commit messages, maybe the newlines are useful. Although one could also argue that the commit message details should maybe not be included in the squash message (only use the commit message titles)?

### CODE REVIEW

**Comment by silverwind** [comment]
PR looks fine.

As for newline squashing, I guess we could prefix the first line of a commit message with a `*` character like [GitHub does](https://github.com/go-gitea/gitea/commit/12c2efb45c112baf6013c304c35cbd404f7be21a), but with newlines squashed, except for the case when a multiline commit is followed by a single-line one, so for example:

````
* Remove fetch request from heatmap

Render heatmap data directly to HTML, eliminating one HTTP request on
frontpage and user profile. Also added min-height to the container so
the page content will no longer move after loading.

* rename and error display
* also log the js error
* add error handler
* remove useless inline style and hide divider on small screens
* Update routers/user/home.go
* Update routers/user/profile.go
* Remove fetch request from heatmap

Render heatmap data directly to HTML, eliminating one HTTP request on
frontpage and user profile. Also added min-height to the container so
the page content will no longer move after loading.

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]

**Comment by lafriks** [comment]
Please update branch

**Comment by jpraet** [comment]
> Please update branch

Could you clarify? Should I rebase on latest go-gitea:master?

**Comment by mrsdizzie** [comment]
There should be an update branch button at the bottom of the comments on this PR that will do it for you

**Pull request merged**
