### PR TITLE
Update markbates/goth

### PR DESCRIPTION
**Pull request by oscarlofwenhamn**
Update markbates/goth to 1.62.2

- Fixes a JWT decoding issue in the OpenID provider
- Updates the GitHub provider to use the authorization header for authentication
- Updates the Twitch provider for Twitch's v5 API changes
- Adds the email and is_private_email fields to the Apple provider's GetUser implementation
- Modifies gothic to export a non-collidable context key for setting the Provider in a context.Context
- Adds new scopes to the Spotify provider
- Adds the IDToken from OpenID providers on the user struct
- Make Apple provider's SecretParams public
- Adds support for sign in with Apple, and drops support for Go versions 1.7 and 1.8
- Fixes the Slack provider's FetchURL logic to use the appropriate scope for the info it needs

### CODE REVIEW

**Comment by techknowlogick** [comment]
Note: I've applied `bug` as label due to Github terminating the functionality that is used to auth users June 1, this is also why I've applied backport label.

**Review by techknowlogick — APPROVED** [review]

**Comment by oscarlofwenhamn** [comment]
Super, and thanks for the quick review.

**Review by 6543 — APPROVED** [review]

**Comment by oscarlofwenhamn** [comment]
Test successful and ready for merging.

**Comment by techknowlogick** [comment]
@oscarlofwenhamn thanks much :) could you also backport these changes to the release/v1.11 branch?

**Comment by oscarlofwenhamn** [comment]
I'd be happy to! Does that mean I make another PR with release/v1.11 as the target, or rather I checkout the release/v1.11 branch; patch and then make a new PR? I'm guessing the latter, but always best to check.

**Comment by techknowlogick** [comment]
That's correct, it'd be the latter. If you have any other questions please don't hesitate to ask :)

**Comment by oscarlofwenhamn** [comment]
Great, I'll get on it immediately. Cheers! And again, thanks for the fast responses, nice interacting actively. :)

**Pull request merged**
