### PR TITLE
Add services package

### PR DESCRIPTION
**Pull request by lunny**
Gitea contains many services. These services need to be initialized when Gitea starts and shut down when Gitea stopped. And some of them have dependencies on another services.

This PR create an uniform service struct with name, dependencies, initialize function and shut down function.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Doesn't it introduce ambiguity for the word `service`? There was already a `/services` but here is introducing new `/modules/services`.

From a Framework view, it's better to make the the essential package names clear.

**Comment by lunny** [comment]
> Doesn't it introduce ambiguity for the word `service`? There was already a `/services` but here is introducing new `/modules/services`.
> 
> From a Framework view, it's better to make the the essential package names clear.

Found a word `ministry`, are there any better word than `service` or `ministry`?

**Comment by wxiaoguang** [comment]
What's the problem that this PR tries to resolve? What the design and how to use this approach correctly in the future?

**Comment by lunny** [comment]
> What's the problem that this PR tries to resolve? What the design and how to use this approach correctly in the future?

I think currently we have no services shutdown sequences. Some services need to be shutdown first. There are no control for these.

**Comment by wxiaoguang** [comment]
To resolve what kind of known problems?

**Comment by lunny** [comment]
Closed as too many conflicts.

**Pull request closed without merging**
