### PR TITLE
Added bucket name to s3 drone plugin

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by jonasfranz** [comment]
Test fails after master rebase.

**Comment by tboerger** [comment]
But failing tests are not related to this change

**Review by jonasfranz — APPROVED** [review]

**Comment by lunny** [comment]
@tboerger yes. #2516 maybe fix that.

**Pull request merged**
