### PR TITLE
Check repository root path, run user and admin password before creating DB

### PR DESCRIPTION
**Pull request by linquize**
Check repository root path, run user and admin password before creating DB

This allows the user to correct those settings before DB is created

### CODE REVIEW

**Comment by lunny** [comment]
But for a windows installation, the path could contains \\ ?

**Comment by tboerger** [comment]
Slahes are working for windows instead of backslashes as well, but why do you need to check the format?

**Comment by linquize** [comment]
See https://github.com/go-gitea/gitea/commit/49aeb87e44b315b0a2de6ce82600311bd24be9f7#L206

**Comment by linquize** [comment]
See https://github.com/go-gitea/gitea/blob/49aeb87e44b315b0a2de6ce82600311bd24be9f7/modules/setting/setting.go#L206

**Pull request merged**
