### PR TITLE
Windows Video Guide

### PR DESCRIPTION
**Pull request by RamblingGeekUK**
Added video-guides.md page, which contains a video for YouTube Embed to a video which covers an overview of installing Gitea on Windows Server 2022. 

I have done my best to follow the contribution guide.   Sorry in advance if I have done this wrong. 

Thanks

### CODE REVIEW

**Comment by lunny** [comment]
I think this is not the first video to introduce Gitea Installations. Maybe it's necessary to add this to the third-party installation videos.

**Comment by RamblingGeekUK** [comment]
> I noticed you used the `gogit` package and then downloaded `git`. I think the `gogit` package is designed to use `gogit` instead of `git` binary. Maybe you can clarify it in your video.

Ahh, well spotted.  I must of selected the wrong one.   I'll see what I can do to add a note to the video. Thanks for the feedback.

**Comment by RamblingGeekUK** [comment]
> I think this is not the first video to introduce Gitea Installations. Maybe it's necessary to add this to the third-party installation videos.

No Problem, thanks for the feedback. I've had a quick look around (I'm at work 😝) I can't seem to find that section, is that in the existing docs or elsewhere?

**Comment by lunny** [comment]
> > I think this is not the first video to introduce Gitea Installations. Maybe it's necessary to add this to the third-party installation videos.
> 
> No Problem, thanks for the feedback. I've had a quick look around (I'm at work 😝) I can't seem to find that section, is that in the existing docs or elsewhere?

Please create a new one.

**Comment by eeyrjmr** [comment]
> I noticed you used the `gogit` package and then downloaded `git`. I think the `gogit` package is designed to use `gogit` instead of `git` binary. Maybe you can clarify it in your video.

You still need git installed. gogit has some of the git functions to improve performance on windows

**Comment by denyskon** [comment]
The docs were moved to https://gitea.com/gitea/docs. Please reopen there if you are still interested in this PR.

**Pull request closed without merging**
