### PR TITLE
Fix metrics auth token detection

### PR DESCRIPTION
**Pull request by barkap**
Metrics token authorization currently does not work with token and metrics enabled in config. There's always 401 response without any data. This fixes header detection.

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for PR @barkap, would you be able to add a test for this?

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by barkap** [comment]
> Thanks for PR @barkap, would you be able to add a test for this?

I'm not too familiar with gitea as a whole and existing go tests mostly fail for me so I'm probably unable to write new test with mocks for this package at the time.

**Comment by techknowlogick** [comment]
@barkap that's ok, thanks for explaining. My computer is so low powered that I rely on drone for running my tests as otherwise it'd be >1.5hours just to test against sqlite 😢 maybe it is time for me to get a new computer 🤔 

Would you be able to send a backport of this PR against the `release/v1.7` branch? If you need any clarification or assistance please let me know and I can help you out.

**Comment by barkap** [comment]
Yes, I'll send pr in a bit. Thank you.

**Pull request merged**
