### PR TITLE
add apple-touch-icon

### LINKED ISSUE #10003: [Enhancement] Add a touch icon.
Please add a "apple touch Icon".
If you add gitea website as app to homscreen on ios devices there is no icon shown because of missing touch icon.

Sample:

IMG_0322

Should be:

IMG_0323

It would be nice and of course gitea has it deserved that also a proper icon is displayed :)

Thanks for your work, Gitea is great :)

### PR DESCRIPTION
**Pull request by silverwind**
`favicon.png` conveniently is already in the correct size.

Fixes: https://github.com/go-gitea/gitea/issues/10003

### CODE REVIEW

**Comment by zeripath** [comment]
Can we add the precomposed thing for android whilst we're at it?

**Comment by silverwind** [comment]
I think Android requires a `manifest.json`, probably better to do that another time.

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Not according to the link I put on the issue... but if you're sure.

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Yeah, that Android advice seems strange, I would not implement it like that.

If we want to support add-to-homescreen on Android, we should do https://developers.google.com/web/fundamentals/web-app-manifest.

**Pull request merged**
