### PR TITLE
[refactor] Use const for wiki DefaultBranch

### PR DESCRIPTION
**Pull request by 6543**
just a nit, that will make it easier to change things and we now have a single source of truth

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]
More maintainable **and** less binary size. Win-Win!

**Comment by wxiaoguang** [comment]
off topic: but IMO most modern compilers support string pool optimization, then there would be only one copy of the duplicate string in binary. If Golang team is a modern team, Golang should also have such optimization. 😁  (I haven't looked into details, just a guess)

**Comment by 6543** [comment]
yes but it make it more maintainable, and that's my main point here

**Comment by 6543** [comment]
.

**Pull request merged**
