### PR TITLE
Apply Webpack processing for custom UI themes

### PR DESCRIPTION
**Pull request by leon-win**
There is currently no way to use the Webpack capabilities in custom UI theme files.

For example, if we take as a basis a standard theme (`theme-gitea-light.css`) that has imports:
```
@import "../chroma/light.css";
@import "../codemirror/light.css";
```

For this to work, you will need to duplicate the imported files in `custom/public/assets/css`. Moreover they will not be minified and glued together because `import` will work as a standard CSS directive, and not be processed by webpack.

To make working with custom themes similar to built-in ones, I suggest processing them with webpack. Placing it in similar path as main static files (`custom/web_src`) will help to further unify the work with CSS, JS and Vue files (this will be in the next PRs).

### CODE REVIEW

**Comment by silverwind** [comment]
What benefits does the webpack processing add? The idea with themes was that you provide all files when creating the theme. I think the only benefit of processing custom themes through webpack would be the transforms/minifaction that esbuild does, and I guess if we really want to, we can allow users to do this.

I think the docs change is also not correct. In a single-binary gitea deployment nothing exists except that binary, so `web_src` does not exist and `custom` is the user-created folder to put in the override files.

**Comment by leon-win** [comment]
> What benefits does the webpack processing add? The idea with themes was that you provide all files in the `custom` folder to the binary. I think the only benefit of processing custom themes through webpack would be the transforms/minifaction that esbuild does, and I guess if we really want to, we can allow users to do this.

Webpack provides file transformation and minification capabilities, since it is already used in Gitea, why deprive users of the opportunity to use it?

Specifically, I was faced with the fact that with the current approach it is necessary to duplicate files such as `chroma` and `codemirror` (and any others that are already used in Gitea).

At the same time, it remains possible to use the old approach (if it seems more convenient to someone).

> I think the docs change is also not correct. In a single-binary gitea deployment nothing exists except that binary, so `web_src` does not exist and `custom` is the optional user-created folder to put in the override files.

Yes, it would probably be more correct to indicate both possibilities in the documentation -- `custom/public/assets/css` if Webpack transformations are not needed and `custom/web_src/css` otherwise. I'll think about how to better formulate this.

**Comment by silverwind** [comment]
> Webpack provides file transformation and minification capabilities, since it is already used in Gitea, why deprive users of the opportunity to use it?

We can enable users to do this, it's not too far-fetched because other stuff like logo is also generated in a gitea checkout, like `generate-images`, but it would definitely need docs on how to create a custom theme within the checkout, likely it's enough to copy an existing theme in the `web_src/css/themes` folder with the relevant imports. Webpack should bundle it into one file in the `public/css` directory because every theme is it's own webpack entry point.

**Comment by wxiaoguang** [comment]
That's not the original purpose of "custom" folder.

* If you would like to add your own JS/CSS without re-building the Gitea binary, you could put your files into "custom" folder
* If you would like to pack your JS/CSS files into Gitea's assets, you need to build them by yourself, but not depending on the "custom" folder.

I think what you mean by this PR is the second case, so the "custom" folder related mechanisms shouldn't be changed.

**Comment by leon-win** [comment]
> That's not the original purpose of "custom" folder.
> 
>     * If you would like to add your own JS/CSS without re-building the Gitea binary, you could put your files into "custom" folder
> 
>     * If you would like to pack your JS/CSS files into Gitea's assets, you need to build them by yourself, but not depending on the "custom" folder.
> 
> 
> I think what you mean by this PR is the second case, so the "custom" folder related mechanisms shouldn't be changed.

Yes, closer to the second case, but only with the clarification that this is only for themes files (like `theme-my-custom.css`).

I thought it would be nice to give the ability to use webpack for custom themes without having to further create own build.

This makes it easier to work with themes without breaking current behavior.

**Comment by silverwind** [comment]
As I said, I think this can be achieved with no modification to webpack configs, so the change can be docs-only:

1. Put your theme in `web_src/css/themes/theme-mytheme.css`, importing what you need etc
2. Run `make frontend`
3. Grab compiled theme from `public/assets/css/theme-mytheme.css`

**Comment by wxiaoguang** [comment]
I think this PR could be closed, since the "custom" folder is not designed for webpack.

**Pull request closed without merging**
