### PR TITLE
Update code.gitea.io/git

### PR DESCRIPTION
**Pull request by ethantkoenig**
Updates code.gitea.io/git dependency. Includes https://github.com/go-gitea/git/pull/91, among other PRs.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lafriks** [comment]
/offtopic why drone tests still conflict with each other? :(

**Comment by sapk** [comment]
Trusted LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
