### PR TITLE
Drop migration for ForeignReference

### LINKED ISSUE #21086: Primary keys are required in MySQL DB cluster
### Description

We use a hosted MySQL DB cluster service on digital ocean which requires that all tables have primary keys. Since version 1.17 there are tables without primary keys. This has happened once already in #16802. 

Are you able to fix this regression so we are able to update to the newest version? Thank you for your time.

### Gitea Version

1.16.9 (trying to update to 1.17)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/aqos156/b9b9b9f097ab926bec9be84fb34a1910

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker on swarm

### Database

MySQL

### PR DESCRIPTION
**Pull request by wolfogre**
Fix https://github.com/go-gitea/gitea/issues/21086#issuecomment-1476560381

Related to #21721

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I guess `DropForeignReferenceTable` should also be fixed together, make it ignore the error

**Comment by wolfogre** [comment]
> I guess `DropForeignReferenceTable` should also be fixed together, make it ignore the error

Maybe it's safe to drop a nonexistent table?

image

**Comment by wxiaoguang** [comment]
> > I guess `DropForeignReferenceTable` should also be fixed together, make it ignore the error
> 
> Maybe it's safe to drop a nonexistent table?

Hmm, I am not sure. Some XORM behaviors are counterintuitive. if it's designed to do so, then no question from my side.

**Comment by zeripath** [comment]
As far as I can see xorm will tolerate dropping a non-existent table - in fact the comment preceding `sess.DropTable` promises this:

```
// DropTable drop table will drop table if exist, if drop failed, it will return error
func (session *Session) DropTable(beanOrTableName interface{}) error {
	if session.isAutoClose {
		defer session.Close()
	}

	return session.dropTable(beanOrTableName)
}
```

and the function `dropTable` is used by the code for `DropTables` so I think this is fine.

**Review by zeripath — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
