### PR TITLE
Improve basic button and label styles

### PR DESCRIPTION
**Pull request by silverwind**
- Simplify disabled styling of label by matching for the disabled attribute.
- Raise fomantic disabled opacity from .45 to .55 to for more contrast.
- Use CSS vars for basic button styles.
- Consolidate basic label and button styles.

Screen Shot 2020-12-24 at 12 33 12
Screen Shot 2020-12-24 at 12 33 30
Screen Shot 2020-12-24 at 12 33 18
Screen Shot 2020-12-24 at 12 33 36
Screen Shot 2020-12-24 at 12 33 50
Screen Shot 2020-12-24 at 12 34 02

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
I think I'll do another rework of the colors in use here so that labels and basic buttons get to use the same colors.

**Comment by silverwind** [comment]
Vars consolidation done. Basic labels and basic buttons now use the exact same color in all their state. Also applied these colors to the unsigned commit labels. Screenshots updated.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
conflicts

**Comment by silverwind** [comment]
rebased

**Pull request merged**
