### PR TITLE
Respect original content when creating secrets

### LINKED ISSUE #24721: Action Secrets remove the last new line
### Description

Hi there,

Im trying to SSH via basic commands to my SSH server.

- I added the correct pub key into my Server
- I added 3 secrets in my Gitea Installation `SSH_USER` `SSH_KEY` `SSH_HOST`

where SSH_KEY is the actual private key

And I'm using the following action.yaml

```
name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
          cat ~/.ssh/config
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Test SSH
        run: ssh staging 'ls'
```

After some debugging it seems that the Secrets field is removing the last new line of the Private Key. In my case I can fix it by using `echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/staging.key` instead.

However, the secret field should not trim the content. It should respect the last new line of the file.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Screenshot 2023-05-14 at 21 44 34

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Gitea is running in a docker container.

### Database

SQLite

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #24721.

Follow what GitHub does:
- Don't trim spaces for secrets.
- Newline should be `\n` instead of `\r\n`.

Did some tests with:

```yaml
name: secrets
on: push
jobs:
  show_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secrets context
        run: echo '${{ toJSON(secrets) }}' | base64
```

`AAAAAA`:
```text
   AAAAAA
AAAAAA


```
`BBBBBB`:
```text



BBBBBB
BBBBBB   
```

On GitHub:

image

On Gitea (before):

image

On Gitea (after):

image

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by wolfogre** [comment]
Need help:

The newline in textarea is `\r\n`, how to change it to `\n`?

image

image

**Comment by wxiaoguang** [comment]
> The newline in textarea is `\r\n`, how to change it to `\n`?

That's standard.

https://html.spec.whatwg.org/multipage/forms.html#the-textarea-element


> It is normalized so that line breaks use U+000A LINE FEED (LF) characters.

**Comment by wxiaoguang** [comment]
And this:

https://www.w3.org/TR/REC-html40/interact/forms.html#h-17.13.3.2

> Control names and values are escaped. Space characters are replaced by `+', and then reserved characters are escaped as described in [RFC1738], section 2.2: Non-alphanumeric characters are replaced by `%HH', a percent sign and two hexadecimal digits representing the ASCII code of the character. Line breaks are represented as "CR LF" pairs (i.e., `%0D%0A').

**Review by lunny — APPROVED** [review]

**Comment by delvh** [comment]
Hmm… I don't know why this PR was merged, and why it is necessary in the first place.

**Comment by delvh** [comment]
Oh, by the way, this PR was certainly not a bug but expected behavior. So, if at all it's an enhancement, although I'd still doubt that (see above).
I think I even commented something of the form
> I like that we trim trailing whitespace around Secrets unlike GitHub

on the original secrets PR.

**Comment by silverwind** [comment]
I generall prefer to trim all input fields as well, it's such a common user error that I think it warrants it. In case a user really wants untrimmed values, a option could be added to the user settings to disable the trimming.

**Pull request merged**
