### PR TITLE
Fix 'add code comment' button being invisible all the time

### PR DESCRIPTION
**Pull request by CirnoT**
As title; need to set opacity to non-zero value if we want it shown.

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Wonder when that broke. We may need to backport to 1.13.

Also, icon seems a bit off-center:

image

**Comment by silverwind** [comment]
It looks like these rules are meant to show that button:

https://github.com/go-gitea/gitea/blob/8176ba65731d9223cca984fbf2ea7dfbdc4855ce/web_src/less/_review.less#L43-L46

Those focus classes are only added by JS:

https://github.com/go-gitea/gitea/blob/8176ba65731d9223cca984fbf2ea7dfbdc4855ce/web_src/js/index.js#L1241-L1250

I think the reason why they don't trigger is the parent classes `.code-view .lines-code,.code-view .lines-num` are absent, probably since quite a long time.

I think it's quite bad that this is done in JS, this can be a pure CSS hover effect.

**Review by silverwind — CHANGES_REQUESTED** [review]
Redacting review for now as this is not the right fix.

**Comment by CirnoT** [comment]
Made it work on full-line hover like GitHub and removed remnants of JS solution.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Needs 1.13 backport.

**Review by mrsdizzie — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Comment by techknowlogick** [comment]
@CirnoT please send backport :)

**Pull request merged**
