### PR TITLE
fix: Crippled diff (#4726)

### LINKED ISSUE #4726: Gitea 1.5.0 crippled diff file font rendering
- Gitea version (or commit ref): 1.5.0
- Git version: 2.18.0
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/davidak/nixpkgs/commit/b7e50d52f018d0670614a58851b4fc2c0f93818b)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Since gitea 1.5.0 the font rendering for the diffs are crippled when viewing them with either Firefox or Chrome on Linux (see attached screenshot). The problem doesn't seem to appear with Firefox or Chrome on Windows and I don't have another distribution to test with so it might be some local problems involved. However I can't remember having this problem with the previous version 1.4.3. And I also didn't find any configuration for being able to adjust the fonts used for rendering the diffs. Also I didn't experience font rendering issues on any other websites yet.

## Screenshots
gitea_diff_rendering

### PR DESCRIPTION
**Pull request by tonivj5**
Fixes https://github.com/go-gitea/gitea/issues/4726

Before:
image
After:
image

### CODE REVIEW

**Comment by tonivj5** [comment]
I don't know why CI is failing... Any advice?

**Comment by jonasfranz** [comment]
Regenerate css via `make regenerate-stylesheets` and commit the result.

**Review by techknowlogick — APPROVED** [review]

**Comment by tonivj5** [comment]
Thanks @JonasFranzDEV, I used `make generate-stylesheets` :+1:

**Review by jonasfranz — APPROVED** [review]

**Comment by lunny** [comment]
Please send back port to v1.5.2

**Pull request merged**
