### PR TITLE
Revert "Make modules/structs as a separate go mod"

### PR DESCRIPTION
**Pull request by lunny**
Reverts go-gitea/gitea#7127

I think I'm wrong making a sub folder as a separate go mod will make PR merging difficult.

### CODE REVIEW

**Comment by saitho** [comment]
Currently CI fails because the mod files weren't updated in or after #7127 was merged.
If we're reverting this change we should do so ASAP. ;) Also that would probably mean reopening go-gitea/go-sdk#177.
If we're not reverting this change anytime soon we should update the files using `make vendor` to enable working builds again.

**Comment by lunny** [comment]
@saitho make vendor will save `code.gitea.io/gita/modules/structs` on `vendor`. That's not a good idea.

**Comment by saitho** [comment]
> @saitho make vendor will save `code.gitea.io/gita/modules/structs` on `vendor`. That's not a good idea.

At least that's what its telling me to do in the failing Drone build. ^^

**Review by saitho — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
This reopened https://gitea.com/gitea/go-sdk/issues/177

**Pull request merged**
