### PR TITLE
Remove unnecessary variable assignments

### PR DESCRIPTION
**Pull request by Gusted**
- Enable ineffassign

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
Seems like stuff a linter should be able to catch.

**Comment by Gusted** [comment]
> Seems like stuff a linter should be able to catch.

We can enabled `ineffassign` linter on golangci-lint to do this.

**Comment by Gusted** [comment]
ineffassign is now enabled with https://github.com/go-gitea/gitea/pull/17695/commits/fb6c628d963ca374429727d80ff85212c91fcfb2

**Review by zeripath — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work.

**Comment by lunny** [comment]
@zeripath Since it didn't affect any feature, I moved this to `kind/lint`

**Pull request merged**
