### PR TITLE
Skip non-regular files (e.g. submodules) on repo indexing

### LINKED ISSUE #7709: Repo indexer chokes with submodules
- Gitea version (or commit ref): v1.9.0
- Git version: 2.22.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When a repository has submodules, function `models/repo_indexer.go:addUpdate()` returns `exit status 128 - fatal: git cat-file: could not get object info` and further processing on the repo is aborted.

I've added additional logs to the function:

image

And I've got:
```
2019/08/01 15:56:01 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM "notification" WHERE (user_id = $1) AND (status = $2) []interface {}{9, 0x1}
2019/08/01 15:56:03 ...dels/repo_indexer.go:207:addUpdate() [E] addUpdate: exit status 128 - fatal: git cat-file: could not get object info
        ; update.BlobSha: 9aef6c8b728958f722f160c8c34fc85790ec2ae8; repo.path: /home/git/gitea-repositories/gprandi/avl-comunicaciones.git, filename: avl-libs-bin
```

In this case, `avl-libs-bin` is a submodule. The following command fails as expected:
```
$ cd /home/git/gitea-repositories/gprandi/avl-comunicaciones.git
$ git cat-file -s 9aef6c8b728958f722f160c8c34fc85790ec2ae8:avl-libs-bin
fatal: Not a valid object name 9aef6c8b728958f722f160c8c34fc85790ec2ae8:avl-libs-bin
```
The hash 9aef6c8b728958f722f160c8c34fc85790ec2ae8 does not belong to this repository, but to the submodule's. The object type for that entry is "commit":

```
$ git ls-tree master
100644 blob 07f549803e107d232d61e0a89c179f6d3a5c1abf    .gitattributes
100644 blob 892ca8e3c1bd4bcddab831e6ecde2910d1d80bc0    .gitignore
100644 blob 166aa8b77976abf066e12abae4f20570202a28ca    .gitmodules
040000 tree 68f80510880d7078e7937b3944cf395a203333e2    CommLib
040000 tree 4ab4458e94f2d63c16eb30645949c57db7eb3fc6    FullDevLogReplicator
100644 blob d1ba69f092c97d9ed3c5a0fabd1d4004c4863897    README.md
100644 blob 08906d481771dcade1cf7390f24d4ad83ce07965    avl-comunicaciones.sln
160000 commit 9aef6c8b728958f722f160c8c34fc85790ec2ae8  avl-libs-bin
[...]
```

I'll attempt a PR about this.

### PR DESCRIPTION
**Pull request by guillep2k**
Fix #7709 by filtering the output from git ls-tree; only regular files are considered for indexing.

### CODE REVIEW

**Comment by guillep2k** [comment]
Note: this should be easy to merge onto v1.9 as well.

**Review by zeripath — APPROVED** [review]
My only query is whether it's worth dereferencing symlinks too.

**Comment by guillep2k** [comment]
> My only query is whether it's worth dereferencing symlinks too.
I think symlinks will return the text of the path they point to (never tried them, though). Anyway, it's probably better to index only the original file (it should be in the repository as well). If the symlink is dereferenced, the contents would be indexed twice.

**Comment by sapk** [comment]
That be worth a try to test if a symlink to `/etc/passwd` index the content of the file.

**Review by sapk — APPROVED** [review]

**Comment by guillep2k** [comment]
> That be worth a try to test if a symlink to `/etc/passwd` index the content of the file.

Interesting concern, indeed. Before this commit, I don't know. With this modification, it won't.

**Comment by guillep2k** [comment]
Note: if /etc/passwd was previously indexed due to a symlink, this modification will not purge it from the index.

**Comment by sapk** [comment]
@guillep2k I tested it doesn't index the content of /etc/passwd but the string /etc/passwd.

**Comment by zeripath** [comment]
@sapk so I think that's ok at present they won't be being dereferenced at present and this PR won't deterrence them.

https://github.com/go-gitea/gitea/blob/54bd63cd5c5645202625368c185b645c7771f687/models/repo_indexer.go#L205

Will simply return the filename of the symbolic link

**Comment by zeripath** [comment]
Of note I particularly do not like

https://github.com/go-gitea/gitea/blob/54bd63cd5c5645202625368c185b645c7771f687/models/repo_indexer.go#L205

As it leads to loading of entire blobs in to memory which is really not very good.

**Comment by guillep2k** [comment]
@zeripath Yes, however it's somehow limited by setting.Indexer.MaxIndexerFileSize which by default is 1MB.
But! This leads to a new bug.... because if the file grows over the threshold after some commit, only its previous version will be indexed, which is inconsistent. The function should drop the index for that file. That should be a new issue, I think.

**Comment by guillep2k** [comment]
image
A change like this should in theory fix the aformentioned bug, but I lack the proper knowledge of the indexing engine to test it properly. In fact, I'm heavily hit by #5694, which led me to this investigation.

**Comment by zeripath** [comment]
@guillep2k I agree that change would fix it. Why don't you add another quick PR for that?

**Comment by zeripath** [comment]
Hmm. We should probably be doing this differently. I'm not certain why we have to pass around the content - and why we can't just pass around blob paths. We currently determine if a file is text by looking at the first 1 Kb of data so we can just load that in - check if it's text or an lfs pointer and then just pass something with the blob path to the indexer which would then do its job. Then there's no need for a 1Mb limit etc.

**Comment by guillep2k** [comment]
> @guillep2k I agree that change would fix it. Why don't you add another quick PR for that?

Done

**Comment by guillep2k** [comment]
> @guillep2k I agree that change would fix it. Why don't you add another quick PR for that?

@zeripath Done.

**Comment by lafriks** [comment]
Please backport to 1.9 branch

**Comment by guillep2k** [comment]
> 
> 
> Please backport to 1.9 branch

@lafriks Done on #7717.

**Pull request merged**
