### PR TITLE
Ignore files in diff with check-attr

### LINKED ISSUE #12653: [Feature] Ability to exclude files from diffs
Github uses Linguist for code analysis in its repositories, and resulting from that introduced a nifty feature in its .gitattributes definitions: `linguist-generated`. This attribute can be used to exclude specific file types from diffs, code reviews, and hide it from showing in the file listing.
I've found that to be invaluable to working with Unity3D in order to keep .meta and .prefab files from cluttering code reviews. It would be cool to have a similar feature in Gitea

---

[Bountysource](https://www.bountysource.com/issues/92731348-feature-ability-to-exclude-files-from-diffs)

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #12653
close #16250

This PR moves the `.gitattribute` file from the root of the default branch into `repo.git/info/attributes` after every push. The diff supports now the `linguist-generated` keyword and hides these file in the output.
test

### CODE REVIEW

**Review by kdumontnu — APPROVED** [review]
👍

**Comment by lafriks** [comment]
I think it should also set IsGenerated by using go-enry method IsGenerated

**Comment by lunny** [comment]
Is it really necessary to sync `.gitattribute` to `repo.git/info/attributes`?

**Comment by a1012112796** [comment]
@zeripath close?

**Comment by zeripath** [comment]
yeah I think this has been replaced.

**Pull request closed without merging**
