### PR TITLE
Fix Monaco IOS keyboard button

### LINKED ISSUE #16188: A large white box obstructs the file editor on iOS
- Gitea version (or commit ref): 1.14.2, from your releases
- Git version: 2.30.1
- Operating system: macOS 11.3, running from launchd
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (any file editing page)
  - [ ] No
- Log gist:

Shouldn't be relevant (it's a UI problem)

## Description

Title and screenshots are pretty self-explanatory. They were taken on an iPhone and on an iPad both running iOS 14.6 and using Safari. The problem doesn't occur on Safari on macOS.

## Screenshots

IMG_2126
IMG_0270

### PR DESCRIPTION
**Pull request by silverwind**
Fix https://github.com/go-gitea/gitea/issues/16188. Turns out the element was completely misaligned by fomantic styles. Add most of the original styles in `!important` form to fix.

Tapping the button doesn't do anything useful in Simulator.app, but I guess it's still better to not outright hide it in case it has a possiblity to work.

image

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
Do we know which Fomantic class destroys it?

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
> Do we know which Fomantic class destroys it?

Was something like `.ui.form .field textarea` because the button is a textarea.

**Comment by wxiaoguang** [comment]
> > Do we know which Fomantic class destroys it?
> 
> Was something like `.ui.form .field textarea` because the button is a textarea.

I guess we need a detailed comment for it......

**Comment by silverwind** [comment]
Maybe later. If you wanna check it out yourself, install XCode, then `open -a Simulator.app` will fire up the IOS simulator and open Safari to connect to it it's "Develop" menu. It's great to test mobile issues like this.

**Pull request merged**
