### PR TITLE
refactor webhook *EditPost

### PR DESCRIPTION
**Pull request by oliverpool**
Following #20729 this PR aims at reducing duplicated code in the `*HooksEditPost` functions.

I also moved the functions around, so that webhook types are grouped together, which makes it easier to read.

For instance the matrix endpoints is now simply (notice that `fmt.Sprintf` is not duplicated anymore!):
```

// MatrixHooksNewPost response for creating Matrix webhook
func MatrixHooksNewPost(ctx *context.Context) {
	createWebhook(ctx, matrixHookParams(ctx))
}

// MatrixHooksEditPost response for editing Matrix webhook
func MatrixHooksEditPost(ctx *context.Context) {
	editWebhook(ctx, matrixHookParams(ctx))
}

func matrixHookParams(ctx *context.Context) webhookParams {
	form := web.GetForm(ctx).(*forms.NewMatrixHookForm)

	return webhookParams{
		URL:         fmt.Sprintf("%s/_matrix/client/r0/rooms/%s/send/m.room.message", form.HomeserverURL, url.PathEscape(form.RoomID)),
		ContentType: webhook.ContentTypeJSON,
		HTTPMethod:  http.MethodPut,
		WebhookForm: form.WebhookForm,
		Type:        webhook.MATRIX,
		Meta: &webhook_service.MatrixMeta{
			HomeserverURL: form.HomeserverURL,
			Room:          form.RoomID,
			AccessToken:   form.AccessToken,
			MessageType:   form.MessageType,
		},
	}
}
```

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Certainly looks far cleaner from what I can see.

**Review by zeripath — APPROVED** [review]
I think there's more that can be done here with a register block.

But this is still a good improvement.

**Comment by KN4CK3R** [comment]
make L-G-T-M work

**Comment by techknowlogick** [comment]
Ping lg-tm bot

**Pull request merged**
