### PR TITLE
Detect truncated utf-8 characters at the end of content as still representing utf-8

### LINKED ISSUE #19743: Wrong display of cyrillic symbols in UTF-8 file
### Description

I have a file in UTF-8 encoding with cyrillic comment.
When i open this file in gitea web view, display of cyrillic symbols seems broken. 
But in gitea file editor, diff page and others, this symbols displays correct.

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

View file:

Edit file:

Diff changes in file:

reproduced it also on demo site
https://try.gitea.io/sIspravnikov/test/src/branch/main/build.gradle.kts

### Git Version

2.30.3

### Operating System

ubuntu 20.04

### How are you running Gitea?

official docker-container

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by zeripath**
Our character detection algorithm can potentially incorrectly detect utf-8 as iso-8859-x
if there is a truncated character at the end of the partially read file.

This PR changes the detection algorithm to truncated utf8 characters at the end of the
buffer.

Fix #19743

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Strangely I'm having some difficulty creating a test that replicates this issue from within the charset module.  

I'm not certain as to what's going on that means that  I can't replicate this.

**Comment by wxiaoguang** [comment]
See my comment in https://github.com/go-gitea/gitea/issues/19743, there is a test case.

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
> #19743

It's better to include this test case.

**Comment by zeripath** [comment]
> > #19743
> 
> It's better to include this test case.

I've already included a specific test case but I can add that if you really want it.

**Review by lunny — APPROVED** [review]

**Pull request merged**
