### PR TITLE
Add Korean support

### LINKED ISSUE #435: Add korean translation
https://github.com/gogits/gogs/commit/105c5283693fe2f0a2c167a8ced2eb17a86f82d1

### PR DESCRIPTION
**Pull request by lunny**
This will fix #435

### CODE REVIEW

**Comment by andreynering** [comment]
LGTM

**Comment by tboerger** [comment]
It got some Gogs references.

**Comment by lunny** [comment]
It's another PR's thing to change gogs' translation tool to gitea's.

**Comment by tboerger** [comment]
Sure, but it doesn't include the Korean translations

**Comment by lunny** [comment]
image

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
