### PR TITLE
Do not send notifications for draft releases

### LINKED ISSUE #21448: draft releases: update & delete events being sent while creation dont
### Description

Pretty much what the title says: while creation events are not being sent when creating an release marked as draft, update and deletion events are, which seems counter intuitive; it should either be all sent or non of them for draft releases.

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

linux

### How are you running Gitea?

Official binary release

### Database

MySQL

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #21448

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by Gusted — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm... Doesn't this mean that we won't ever get a CreateRelease for a release that is marked as Draft but then is not marked as Draft?

**Comment by Gusted** [comment]
> Hmm... Doesn't this mean that we won't ever get a CreateRelease for a release that is marked as Draft but then is not marked as Draft?

Draft --> Non-draft (notification issued)
Non-Draft --> Draft (notification not issued)

**Comment by zeripath** [comment]
> > Hmm... Doesn't this mean that we won't ever get a CreateRelease for a release that is marked as Draft but then is not marked as Draft?
> 
> Draft --> Non-draft (notification issued) Non-Draft --> Draft (notification not issued)

You won't get the create release...

**Comment by Gusted** [comment]
> You won't get the create release...

No? Because the release has been updated... Do you want to have an create release event when draft --> non-draft?

**Comment by lafriks** [comment]
Imho this behavior is broken, while I understand the logic, if you are wanting only create events you will never get them if draft is created and then updated to normal release. Even if I get the update event I can't know it was previously draft...

If we do not want release to send events for draft we should send create event for when status is changed from draft to normal and delete when from normal to draft imho

**Comment by lafriks** [comment]
Also imho this is breaking change now and I do not think it should be backported

**Comment by techknowlogick** [comment]
Good points from @lafriks , perhaps we should revert this as we are about to create an RC so we can discuss it more

**Comment by zeripath** [comment]
This is precisely what I was questioning about above.

We need still need to emit the create event - at least when the draft is finally undrafted (but then you're likely going to need to add a field on the release)

**Comment by Gusted** [comment]
That would make sense to do that... bummer it got merged already.

**Comment by lunny** [comment]
Please send backport

**Pull request merged**
