### PR TITLE
GitHub Actions enhancements for frontend

### PR DESCRIPTION
**Pull request by silverwind**
- Don't run DB tests for frontend-only changes
- Build frontend as part of frontend step
- Build everything when actions change

### CODE REVIEW

**Comment by lunny** [comment]
Those tests in fact are integration tests which will be affected by page HTML changes.

**Comment by silverwind** [comment]
I will push and later revert a change to frontend just to confirm that it runs correctly.

**Comment by silverwind** [comment]
Frontend run was fine, now doing the backend one.

**Comment by silverwind** [comment]
All looking good from my side

**Comment by silverwind** [comment]
I guess we should actually run a full build when actions workflow change because those changes can affect the whole build of course.

**Comment by silverwind** [comment]
> I guess we should actually run a full build when actions workflow files change because those changes can affect the whole build of course.

Done in https://github.com/go-gitea/gitea/pull/25150/commits/4272c78e65ac8e1c711a70f52f34aaf310ee0c94. When actions themselves change, everything has to run, so I added the condition everywhere.

@lunny what do you think? I think the frontend removal will save us a lot of unnecessary CI time for JS/CSS changes which have no influence on the backend/db tests.

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
