### PR TITLE
Migrate to dep

### PR DESCRIPTION
**Pull request by sapk**
Simply `dep init` without backporting from govendor since dep fail to resolve some old reference like tibd.

I will try to put most of the deps as before migration.
I need to update Makefile before this PR is ready to review

### CODE REVIEW

**Comment by sapk** [comment]
govendor allow some subpackage to differ from the root like https://github.com/go-gitea/gitea/blob/master/vendor/vendor.json#L134 vs https://github.com/go-gitea/gitea/blob/master/vendor/vendor.json#L128 and https://github.com/go-gitea/gitea/blob/master/vendor/vendor.json#L62 . I don't think this is possible with dep.
So this PR will need to update some deps to work. I will try to reduce the number of change.

**Comment by sapk** [comment]
I think that before to be able to migrate to dep we will need to update some package and first bleve since it as multiple version.

**Comment by techknowlogick** [comment]
@sapk now that bleeve has been updated to the latest version, is this PR still WIP?

**Comment by sapk** [comment]
@techknowlogick yes, I will rebase over.

**Comment by sapk** [comment]
~~~Weird but govendor seems to fail to find those deps.~~~
~~~So we are missing some deps like github.com/gorilla/mux https://github.com/markbates/goth/blob/4933f155d89c3c52ab4ca545c6602cf4a1e87913/gothic/gothic.go~~~

Govendor seems to have package some deps like github.com/gorilla/mux without storing them in the vendor.json

**Comment by sapk** [comment]
Ok, this is good for review. 
Some files are added since dep doesn't support build tag filtering (so file with build tag ignore are added + deps) fir lib/pq and x/text.
For x/text, I can maybe add a rule for some package like done for appengine but it will have no impact on build.

**Comment by lunny** [comment]
LGTM

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
conflict

**Comment by sapk** [comment]
@lunny I rebase the PR.

**Pull request merged**
