### PR TITLE
Fix escape problems in the branch selector

### LINKED ISSUE #25865: Branch name escape problem
### Description

Related: #25830

- https://github.com/go-gitea/gitea/pull/25812#discussion_r1262140690
This is the right link:
https://try.gitea.io/yp05327/testrepo/src/branch/test%2311

- https://github.com/go-gitea/gitea/issues/25830#issuecomment-1634050628

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fix #25865

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by puni9869** [comment]
Can we ship this PR.

**Review by puni9869 — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Backport needed?

**Comment by lunny** [comment]
If a branch named `aa#b`, should that be encoded as `aa%2311` or not?

**Comment by puni9869** [comment]
> If a branch named `aa#b`, should that be encoded as `aa%2311` or not?

Yes.

**Comment by puni9869** [comment]
> Backport needed?

I am not sure about it but it was reported before the release of 1.20 stable version.

**Comment by silverwind** [comment]
As per https://github.com/go-gitea/gitea/issues/26088, backport is needed.

**Pull request merged**
