### PR TITLE
Various Mermaid improvements

### PR DESCRIPTION
**Pull request by silverwind**
- Render into iframe for improved security
- Use built-in dark theme instead of color inversion
- Remove flexbox attributes, resulting in more consistent size rendering
- Update API usage and update to latest version
- Tested in Firefox, Chrome, Safari

Before:
Screen Shot 2022-02-15 at 19 40 05

After:
Screen Shot 2022-02-15 at 20 27 13
Screen Shot 2022-02-15 at 20 27 31

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by Gusted — APPROVED** [review]

**Comment by silverwind** [comment]
There is one more improvement to do: `mermaid.init` renders into the document until the JS picks it out and puts it into the `<iframe>`. Need to find a solution that does not go via DOM like that.

**Comment by Gusted** [comment]
> There is one more improvement to do: `mermaid.init` renders into the DOM until the JS picks it out and puts it into the `<iframe>`. Need to find a solution that does not go via DOM like that. Putting to draft until then.

Would it be possible to create the `<iframe>` beforehand and create the necessary SVG already and then pass that as "node" into the `init` function, the only thing you would need to do afterwards is to set the correct height style, but that should avoid to use the parent document instead of the iframe document.

**Comment by silverwind** [comment]
> Would it be possible to create the <iframe> beforehand and create the necessary SVG already and then pass that as "node" into the init function, the only thing you would need to do afterwards is to set the correct height style, but that should avoid to use the parent document instead of the iframe document.

Exactly my thoughts. With this method, I needed to parse the height from the SVG string, which is a bit clumsy, but should be faster than parsing the whole thing again.

Of note there is one tidbit to the `iframe` method. When calling `mermaidAPI.render`, one is instructed to bind JS events via second argument `bindFunctions` provided in the callback, but we can't do that without loading the whole library into each iframe, and I don't think we actually need this feature as it is disabled in `strict` security mode anyways.

**Comment by lunny** [comment]
make L-G-T-M work.

**Comment by lunny** [comment]
Please send backport

**Pull request merged**
