### PR TITLE
Fix wrong scopes caused by empty scope input

### LINKED ISSUE #18972: Gitea prepends requested openid scope with + after updating authentication source
### Gitea Version

1.16.2

### Git Version

2.30.2

### Operating System

Linux

### How are you running Gitea?

I'm running the official docker image `docker.io/gitea/gitea:1.16.2` on a Kubernetes cluster. I currently use my own manifests and not the one provided by helm.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/ftsell/831eadfeefa162eb1707152fda870a47

### Description

I have recently changed the Icon URL of my *Oauth2 -> OpenID Connect* Authentication Source in Gitea. Immediately afterwards, while validating that the icon works, I noticed that the authentication no longer functions correctly.

After debugging the problem I found that gitea redirects my user agent to a URL in the pattern `https://keycloak.…/openid-connect?client_id=gitea&redirect_uri=…&response_type=code&scope=+openid&state=…`. If you look closely, you can see an additional (encoded) + character before the requested scope. 
My OpenID Connect server does not accept this and redirects back to `https://git.…/user/oauth2/Keycloak/callback?error=invalid_scope&error_description=Invalid+scopes%3A++openid&state=…`.

I also tried to create a new separate authentication source but that one suffers from the same problem.

FYI: I am using Keycloak as an OpenID Connect provider. The log files given in the gist include the relevant part of Kekloak's logs as well as Gitea logs in trace mode.

### Screenshots

Gitea just shows a generic 500 page; I don't think that's relevant here.

### PR DESCRIPTION
**Pull request by wxiaoguang**
As the title, close #18972

Try to fix:
* https://github.com/go-gitea/gitea/issues/18972

And there are many bugs in the admin login source page, they can not be fixed easily in this PR, so I just left some FIXMEs.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by noerw — APPROVED** [review]
lgtm, but shouldn't those FIXMEs be github issues? (ok it's arguable where the note will get lost more quickly 🙃)

**Comment by wxiaoguang** [comment]
@noerw sorry, could you help to explain `shouldn't those FIXMEs be github issues`? I didn't get the point ... 😂

**Comment by wxiaoguang** [comment]
The related issue is created:
* https://github.com/go-gitea/gitea/issues/19036

**Comment by zeripath** [comment]
Please send backport,

**Pull request merged**
