### PR TITLE
Fix tests hostkeys (#17786)

### PR DESCRIPTION
**Pull request by 6543**
Backport (#17786)

allow ssh-rsa as hostkey algorithm

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
tests failure may related.

**Comment by 6543** [comment]
well yes see long conversation at #17786

two options:
1. move it ti next v1.15.x until we have new ssh version in our test environment
2. close this for now and only track this issue at #17786

**Comment by zeripath** [comment]
For this PR to work we'd need to detect which version of ssh was in use.

**Comment by 6543** [comment]
ok I'll close this to only track things at #17786

**Pull request closed without merging**
