### PR TITLE
Improve webhooks

### PR DESCRIPTION
**Pull request by jolheiser**
This PR is a little love for webhooks.  

1. For PR reviews, adds the content of the review to the webhook.
2. Changes the color names from things like `success` and `fail` to `green` and `red`
3. Change the verbiage for issue comments and PR comments to distinguish what the comment is for
4. Add a few more colors to help distinguish different events visually (this mostly affects Discord and MS Teams, as they shared a lot of similar color coding)

I used the same colors as GitHub.

gitea-colors

### CODE REVIEW

**Comment by mrsdizzie** [comment]
Seems like maybe comments are missing the [user/repo] full name part in the titles?

**Comment by mrsdizzie** [comment]
Also perhaps for this general improvement PR -- it seems the avatar is missing to the left of the usernames? I assume those test users have default generated avatars but it isn't picking those up?

**Comment by jolheiser** [comment]
> Also perhaps for this general improvement PR -- it seems the avatar is missing to the left of the usernames? I assume those test users have default generated avatars but it isn't picking those up?

I was also a little confused by that, but I'm not sure what exactly is going on there. 
This is a link that Discord attempts to use to render an avatar  
https://images-ext-2.discordapp.net/external/w7xbLEqkhz2oSv6TAz8h38ut5nDNdT82WfYjA3tApOo/http/localhost%3A3000/user/avatar/user2/-1

**Comment by mrsdizzie** [comment]
Perhaps just a temporary discord issue then 🙃

**Comment by jolheiser** [comment]
Added the `repo.FullName` to issue comments for Discord, MS Teams, and Dingtalk.  
Slack already had it.  
Telegram expected a slightly different format and I didn't want to break it inadvertently.

@mrsdizzie 

gitea-colors-2

**Review by 6543 — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
