### PR TITLE
Add redis built into Gitea in Docker image by default

### PR DESCRIPTION
**Pull request by techknowlogick**
As title

### CODE REVIEW

**Review by daviian — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
Where is the build tag?

**Comment by techknowlogick** [comment]
@lunny my understanding is that when docker builds it takes the environment variables set and passes them to the Makefile and builds the binary which adds it to the image. My change is to add another tag to the build.

Or do you mean the build label for this PR?

**Comment by lunny** [comment]
@techknowlogick I mean which source file will use this build tag `redis`? I didn't find the build tag on Gitea's source files maybe it's in macaron's source files?

**Comment by daviian** [comment]
@lunny It's mentioned in our docs (https://docs.gitea.io/en-us/config-cheat-sheet/ - in section `Cache`)

**Comment by lunny** [comment]
@daviian It seems the docs is too old. see https://github.com/go-gitea/gitea/blob/master/vendor/github.com/go-macaron/cache/redis/redis.go, no redis tag there.

**Comment by daviian** [comment]
@lunny You are totally right. I will send a PR updating the docs. So this PR is not necessary at all to use redis in docker ;-)

**Comment by lafriks** [comment]
Than probably this PR can be closed than just like issue that redis does not work in docker

**Comment by techknowlogick** [comment]
Closing this per above discussion. Thanks all for the above information.

**Pull request closed without merging**
