### PR TITLE
Fix empty commits now showing in repo overview

### LINKED ISSUE #7188: Empty commits not visible in repo page
Empty commits created via `git commit --allow-empty -m "empty commit"` do not show up in the repo page in the commit box above the file list. Example:

[Repo](https://try.gitea.io/silverwind/symlink-test) (Not OK)
[Commit](https://try.gitea.io/silverwind/symlink-test/commit/8e2cf0bbd561b4328cabcfe91639a4f1166abe1c) (OK)
[Commits](https://try.gitea.io/silverwind/symlink-test/commits/branch/master) (OK)

### PR DESCRIPTION
**Pull request by silverwind**
Empty commits were missing in parts of the UI because this check removed them while parsing commits. Removed the check to make empty commits show up in the repo summary again. Not 100% sure if this breaks anything else that might rely on these commits being absent.

Fixes: https://github.com/go-gitea/gitea/issues/7188

### CODE REVIEW

**Comment by silverwind** [comment]
(BTW: Would be nice if someone could grant me permission on Drone to restart builds)

**Comment by techknowlogick** [comment]
Seems docker hub is having an outage right now which is why builds are failing: https://status.docker.com/

**Comment by silverwind** [comment]
@filipnavara fyi, this partially reverts https://github.com/go-gitea/gitea/commit/b83114f1407247415b184f77f8f2f6ecea8cb994. If you have a better suggestion than outright removing the check, please shoot.

**Comment by filipnavara** [comment]
I am pretty sure this will break a lot of things, especially on the big repositories (Linux, Rails) but at the moment I am not available to give it a try and check it against GitHub behaviour which I tried to mimic.

**Comment by silverwind** [comment]
Maybe I'll add a separate function just to retrieve the last commit to be on the safe side. This comment mentions it's "free" during traversal, but if it happens to be a is a empty commit, it's just plain wrong.

``` go
	// Retrieve the commit for the treePath itself (see above). We basically
	// get it for free during the tree traversal and it's used for listing
	// pages to display information about newest commit for a given path.
	var treeCommit *Commit
	if rev, ok := revs[""]; ok {
		treeCommit = convertCommit(rev)
	}

**Comment by filipnavara** [comment]
Special-casing this probably makes more sense, if it is desired behavior at all.

Note that listing a [sub]directory shows the last commit that modified anything in the directory. This function returns exactly that since an empty commit does not modify the root directory.

You can probably special-case that if the path is empty you just return the commit you get as input to GetCommitsInfo (not necessarily the HEAD at the moment).

**Comment by filipnavara** [comment]
You can simply change

https://github.com/go-gitea/gitea/blob/e0d6d2f97816f972d408308c740bacc450584e00/modules/git/commit_info.go#L71-L73

to 

```go
	if treePath == "" {
		treeCommit = commit
	}
	else if rev, ok := revs[""]; ok {
		treeCommit = convertCommit(rev)
	}
```

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Could you add test for this?

**Review by filipnavara — APPROVED** [review]

**Comment by silverwind** [comment]
test added.

**Comment by silverwind** [comment]
and thanks @filipnavara. I still don't understand how your fix works, but it looks to work nicely.

**Review by lunny — APPROVED** [review]

**Comment by lafriks** [comment]
Please backport to 1.9

**Pull request merged**
