### PR TITLE
Fix regex for issues in commit messages

### LINKED ISSUE #7438: issue tags eg "#1" vs "someprefix#1"
- Can you reproduce the bug at https://try.gitea.io:
 https://try.gitea.io/company/commit-tags-problem/issues/2

## Description
in this issue2 should not be marked within the commit which belongs to issue1
I think for a work around could be writing `KB\#2` but feels uncomfortable and dont work. How to?

Kind regards

### PR DESCRIPTION
**Pull request by mrsdizzie**
Use same regex as markup for matching in commits. This requires adding a 2nd regex for normal matching because go regex doesn't have proper lookahead/lookbehind so you can't require both a space in front of the issue ref and a space after "closes:". I have an idea for a better built in lookbehind/lookahead type system to use in the future but this can be simple bug fix for 1.9 now.

Fixes #7438

### CODE REVIEW

**Review by kolaente — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by mrsdizzie** [comment]
I think this should be a 1.9 backport

**Comment by techknowlogick** [comment]
@mrsdizzie ok, please backport :)

**Comment by andysh-uk** [comment]
Since updating to 1.9, my commit messages weren't referencing the issue correctly. I was always using the format:

"#123: this is my message"

After some trial and error, I found this works if the issue # is after the comment - i.e.

"This is my message #123"

Could this PR be responsible for this change in behaviour?  Looking back I notice that the UI never links the issue # in the first example above, but it does in the second.

**Comment by guillep2k** [comment]
@andysh-uk This PR is about commit messages; you are talking about issue comments.
Ironically, there was an issue with colons and references for commit messages, fixed in #7207.

**Comment by andysh-uk** [comment]
I am talking about commit messages, where you reference the issue # in your commit message and it links the commit to the issue’s log with a “referenced in commit” entry.

Not sure where issue comments came into it?

**Comment by mrsdizzie** [comment]
@guillep2k no, @andysh-uk is exactly right about this. The issue you reference is unrelated in this case.

This PR was responsible was responsible and fixed recently in https://github.com/go-gitea/gitea/pull/8101

In general there used to be no boundaries for matches before 1.9 which caused many false positives (like the bug referenced in this PR) so for 1.9 boundaries were added to try and match Github. ```:``` wasn't added then because there isn't a published list of what they support so it mostly started out as a best guess effort, but was added in after the report above. So this should work on master and is pending a backport PR to 1.9 branch.

**Comment by andysh-uk** [comment]
@mrsdizzie ah perfect, many thanks!

**Pull request merged**
