### PR TITLE
Move repo setting menu to right side to keep consistent with org's

### PR DESCRIPTION
**Pull request by lunny**
Before

图片

After

图片

For mobile, it's the same as before.
图片

### CODE REVIEW

**Review by yardenshoham — APPROVED** [review]

**Review by denyskon — CHANGES_REQUESTED** [review]
Have to check how it looks on mobile...

**Comment by silverwind** [comment]
It bleeds into the fade-out effect at the end of the tab bar, which is imho unacceptable.

We should replace this fade out effect with a GitHub-like mechanism that moves overflowing tab bar elements into a `...` button, but that will require some JS to work. With that, settings could only stay left-aligned.

**Comment by lunny** [comment]
> Have to check how it looks on mobile...

I have checked it works. See the updated screenshots.

**Comment by lunny** [comment]
But now organization's settings are already aligned to the right. This PR will keep them both consistent.

**Review by wxiaoguang — APPROVED** [review]
I think it doesn't really cause any problem. If any, it could still be reverted or fixed easily.

**Comment by lunny** [comment]
> Have to check how it looks on mobile...

Mobile screenshots updated. It's not affected.

**Review by denyskon — APPROVED** [review]

**Comment by silverwind** [comment]
It does affect desktop where the "s" in "Settings" is faded out. Imho it looks to bad and I have to block it.

**Review by silverwind — CHANGES_REQUESTED** [review]
Does not work well for repo because of fade-out effect which is not present on org.

**Comment by silverwind** [comment]
Removing the fade-out on this `new-menu` might be one way to solve it that is borderline acceptable to me. A better way would be to implement a tab bar that overflows into a menu [like this](https://dynamic-tabs.charlesmarttinen.ca/).

**Comment by silverwind** [comment]
I will have a try at implementing such an overflow menu. Won't be a web component at least, though.

**Comment by silverwind** [comment]
Depends on https://github.com/go-gitea/gitea/pull/29400 and I will implement the moving of the settings menu in it I think.

**Pull request closed without merging**
