### PR TITLE
Updates vendor/code.gitea.io/git

### PR DESCRIPTION
**Pull request by richmahn**
Updates the dep for code.gitea.io/git

### CODE REVIEW

**Comment by richmahn** [comment]
@lunny Pending your review on how we should handle getting my changes to the git repo when you have changes in there for v1.9.

**Comment by richmahn** [comment]
@techknowlogick @lunny I also see the build fails due to there needing to be a change to a call to what lunny did for the cache in the gitea code.

**Comment by zeripath** [comment]
Given the caching code seems to be able to cope with nil for the cache it's probably quickest to just change the broken bits in Gitea to pass in nil

**Comment by lunny** [comment]
I think this has been replaced by #6224

**Comment by zeripath** [comment]
Actually Rich if you update this so that you use the latest git master you can fix #6292.

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
