### PR TITLE
Add precompressed brotli/gzip assets

### PR DESCRIPTION
**Pull request by silverwind**
This uses webpack to emit .gz and .br files for each js/css file into the public directory. The benefit of this is that our webpack-managed assets are now always optimally compressed without any runtime performance impact.

The backend will dynamically emit compressed public assets based on the client's content-encoding support and there is no interference with the existing gzip option (which does slow runtime compression).

Overall, this will increase bindata size and memory consumption when using bindata by around 20 MiB while saving around 25-50% of transfer size for every affected asset (in the case of brotli vs previous runtime gzip).

Node >= 10.16 is required for native brotli compression support.

### CODE REVIEW

**Comment by lunny** [comment]
I think the bindata tool github.com/shurcooL/vfsgen has compressed the assets.

**Comment by silverwind** [comment]
vfsgen transparently compresses if the resulting file is smaller (which will only be the case for the uncompressed variants) but gitea will always see uncompressed data coming out of it. It has no influence on the http compression which is still our responsibilty.

**Comment by silverwind** [comment]
It might be possible to access [vfsgen's raw gzip data](https://github.com/shurcooL/vfsgen#additional-embedded-information) to save some bindata size but I think that's an optimization can be done in another PR.

**Comment by lafriks** [comment]
Imho this should be done in startup with some kind of warmup method, this way it would not increase binary size and would still provide same performance

**Comment by silverwind** [comment]
Brotli compression is rather cpu-intensive, it takes around 15 seconds on a quad-core machine. I guess https://github.com/andybalholm/brotli could be used, but I don't see an extra 20MB binary size as a big issue either. Once https://github.com/shurcooL/vfsgen/pull/86 is merged and released, we can cut that requirement in half.

**Comment by silverwind** [comment]
Actually the 20mb was too generously estimated, it' less then that even:

````
$ find public -name '*.gz' -exec du -ch {} + | grep total$
4.0M    total
$ find public -name '*.br' -exec du -ch {} + | grep total$
3.0M    total
````

So we can either take that as-is or wait on above PR to reduce the 7MB to just 3MB for the brotli assets. I still kind of like to have both the `.br` and `.gz` assets thought because web servers can directly pick those up (`gzip_static` and `brotli_static` diretives in nginx for example).

**Comment by silverwind** [comment]
Actually I think using the vfsgen gzip data will introduce a dependency on `TAGS` on the frontend build. If `bindata` is absent, we need to emit `.gz`, and `.br`, otherwise only `.br` (because bindata provides gzip).

**Comment by silverwind** [comment]
https://github.com/shurcooL/vfsgen/pull/86 is merged so we can probably soon use it to get level 9 gzip data out of it.

The question remains whether we should keep the brotli assets (currently 3MB) which will of course mean 3MB higher memory and disk space requirement for around 30% less transfer size for the assets. To me it's pretty clear that we should keep the brotli files.

**Comment by silverwind** [comment]
Thought there's also a question whether we really need the gzip data. [Pretty much all](https://caniuse.com/#feat=brotli) modern browser support Brotli, so I don't imagine gzip being used all that often.

**Comment by lunny** [comment]
So could we send a PR to vfsgen to support `Brotli`?

**Comment by silverwind** [comment]
Yes, I think that'd be ideal for us and the author seems willing, see https://github.com/shurcooL/vfsgen/issues/71.

**Comment by silverwind** [comment]
Closing for https://github.com/go-gitea/gitea/pull/7109.

**Pull request closed without merging**
