### PR TITLE
Use flex instead of float for sort button and search input

### PR DESCRIPTION
**Pull request by HesterG**
Right now some sort buttons beside search input are unclickable because #25338 removed `max-width` and the sort button is using float, sort button is then covered by the `input`.

The way to fix this in this PR is changing the layout to `flex` and put `input form` and sort `button` into `secondary menu`. 

After:

Screen Shot 2023-06-26 at 16 40 52

Screen Shot 2023-06-26 at 16 34 06
Screen Shot 2023-06-26 at 16 34 22
Screen Shot 2023-06-26 at 16 34 32
Screen Shot 2023-06-26 at 16 35 21
Screen Shot 2023-06-26 at 16 36 14

### CODE REVIEW

**Comment by silverwind** [comment]
Ah, so the `max-width` did serve a (hacky) purpose.

**Comment by silverwind** [comment]
Note: `templates/code/searchform.tmpl` is the only form left with a `max-width` in templates, we should fix it here as well.

**Comment by silverwind** [comment]
Noticed on user page that the form now renders slightly outside its container:

Screenshot 2023-06-26 at 20 41 05

**Review by silverwind — APPROVED** [review]
Can't find any more similar issues, so LGTM

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
