### PR TITLE
Add Link to Stars and Forks Page to Repo List

### PR DESCRIPTION
**Pull request by JakobDev**
The Repolist contains the Number of Stars and Forks. Now these Numbers are a Link to the corresponding pages of the Repo.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Any screenshot? Does it need `muted`?

**Comment by delvh** [comment]
focused: 
image
hovered:
image

> Does it need muted?

I guess not?

**Comment by silverwind** [comment]
Yeah that's fine, some other style must already be setting the color there.

**Comment by JakobDev** [comment]
> Any screenshot?

It looks exactly the same as previous. Nothing changed here.

**Comment by silverwind** [comment]
> 

Yes, muting links be default may be worth considering given that we now have muted almost all of them already.

**Pull request merged**
