### PR TITLE
Add git dashes separator to some "log" and "diff" commands

### PR DESCRIPTION
**Pull request by wxiaoguang**
Reference: https://github.com/go-gitea/gitea/issues/22578#issuecomment-1444180053

Credits to @tdesveaux , thank you very much for catching the problem. If you'd like to open a PR, feel free to replace this one.

Git reports fatal errors for ambiguous arguments:

```
fatal: ambiguous argument 'refs/a...refs/b': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
```

So the `--` separator is necessary in some cases.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Hmm, wait for the author first.

**Comment by wxiaoguang** [comment]
Thank you very much. Then I would re-open this PR.

> why you used .AddArguments("--") instead of .AddDashesAndList()

I guess `AddArguments("--")` looks clearer and matches the comment (which also contains `--`), actually either is fine.

In history, we ever removed some "really redundant" dashes, like #22756, [remove the dashes](https://github.com/go-gitea/gitea/pull/22756/files#diff-eb96c4920cd1cce828a016dc1acdbf3cd320109a1c6c08f0ec5ac411c57cdc3cL138) , at that time, the removal was correct (`git check-attr --stdin [-z] [-a | --all | <attr>...]`). 

So I think if we need to add dashes to git command, we could make them more explicit to help future developers.

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
Are there other places where these `--` have been removed in the recent refactorings?

**Comment by wxiaoguang** [comment]
> Are there other places where these `--` have been removed in the recent refactorings?

No, the only one is that `git check-attr --stdin [-z] [-a | --all | <attr>...]`, which I have confirmed.

This PR related code were the same as before. I didn't change logic during refactoring.

**Comment by wxiaoguang** [comment]
> Are there other places where these `--` have been removed in the recent refactorings?

No, the only one is that `git check-attr --stdin [-z] [-a | --all | <attr>...]`, which I have confirmed.

This PR related old code was the same as before. I didn't change logic during refactoring.

**Comment by wxiaoguang** [comment]
Hmm, sorry that I found that that's a regression, so I will re-check #21535

**Comment by wxiaoguang** [comment]
OK, double confirmed, not a regression. The code was that long ago:


See the old  GetCompareInfo and GetDiffNumChangedFiles

https://github.com/wxiaoguang/gitea/blame/bdfd751af88c5bdb70dbdfb4f7f607f6fbf77896/modules/git/repo_compare.go#L90


https://github.com/wxiaoguang/gitea/blame/bdfd751af88c5bdb70dbdfb4f7f607f6fbf77896/modules/git/repo_compare.go#L140

**Pull request merged**
