### PR TITLE
Avoid new stack context for task list items

### PR DESCRIPTION
**Pull request by Gusted**
- Avoid creating a new stack context on a task list item, this PR does that by removing the `position: relative` which causes a new stack context to be created on that element. And thereby solving that popups weren't able to utilize their z-index and weren't able to show properly.

Before:
image

After:
image

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
I can't quite understand why they ever had the relative position set

**Comment by wxiaoguang** [comment]
Oh wait, to be more careful ..... I think this is incorrect. See the screenshot.

<details>

image

</details>

**Comment by Gusted** [comment]
Thanks for testing @wxiaoguang, https://github.com/go-gitea/gitea/pull/20377/commits/f15f897af923af9e02f73867d4ce9ee0642e6462 fixes the issue by making the checkbox relative to the parent element.

**Comment by wxiaoguang** [comment]
Better but there are still other cases. I think there should be more comments about all the cases.

<details>

image

</details>

**Comment by silverwind** [comment]
The root problem is that the popups are part of the regular DOM structure where unintended interactions like this happens.,

The real fix is to "portal" out the popup to be a direct descendant of `body`, positioned via popper.js or similar. Through that, all problems related to stacking context magically dissapear. We need to switch to somthing better than fomantic popups for this to happen, thought.

**Comment by silverwind** [comment]
Maybe fomantic [can actually do popup portalling](https://fomantic-ui.com/modules/popup.html#/settings). Worth a try adding a `#popup` element to `body`, and then initialize via options:

```js
$el.popup({popup: document.querySelector('#popup'), movePopup: false});
```

**Comment by Gusted** [comment]
> Maybe fomantic [can actually do popup portalling](https://fomantic-ui.com/modules/popup.html#/settings). Worth a try adding a `#popup` element to `body`, and then initialize via options:

We already [use fomantic's popup functionality](https://github.com/go-gitea/gitea/blob/main/web_src/js/features/contextpopup.js#L36). However portalling should work by specifying `inline: false`(default value) as it then should append the popup to the body, however this is currently not the case/not working and just act as `inline: true`, likely because we're specifying a pre-formatted popup.

**Comment by Gusted** [comment]
Popper looks interesting, don't have any experience with it. @silverwind would you like to take over this PR(or create a new one) otherwise I can have a look into popper some time soon.

**Comment by 6543** [comment]
are things fixed ?!?

**Comment by Gusted** [comment]
> are things fixed ?!?

Adding status/wip

**Comment by wxiaoguang** [comment]
My (draft) proposal is : https://github.com/wxiaoguang/gitea/tree/fix-stack-context , remove the `position: relative`

image

**Comment by silverwind** [comment]
> Popper looks interesting, don't have any experience with it. @silverwind would you like to take over this PR(or create a new one) otherwise I can have a look into popper some time soon.

Rewrite to popper (or maybe even the newer [floating-ui](https://github.com/floating-ui/floating-ui), but it's quite complex to implement) will be more involved. It'd be awesome if we get portalling popups to work with Fomantic, otherwise I guess a workaround like done here is borderline acceptable.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/20393 is a replacement for this which uses portalling, so surrounding CSS won't interfere anymore.

**Comment by Gusted** [comment]
Closing as #20393 is better solution to this.

**Pull request closed without merging**
