### PR TITLE
UI: Make dashboard navbar and footer full-width

### PR DESCRIPTION
**Pull request by silverwind**
As @lunny [suggested](https://github.com/go-gitea/gitea/pull/5998#issuecomment-461795804), make the dashboard navbar full-width as well.

#### Before
screenshot 2019-02-09 at 07 38 47

#### After
screenshot 2019-02-09 at 07 39 32

### CODE REVIEW

**Comment by lunny** [comment]
@silverwind thanks! Any chance to let all the pages full-width?

**Comment by silverwind** [comment]
Possible, but each page will need individual care because some of them don't look too good at full width, especially on smaller zoom levels, so we have to do individual fixes. I plan on starting with the dashboard later.

**Comment by silverwind** [comment]
Few more tweaks pushed. The page footer is now also full-width:

screenshot 2019-02-09 at 11 33 56

**Comment by silverwind** [comment]
One more tweak related to the footer. On small pages, there were unneccessary scrollbars because the page layout was 100% + 1px high with that 1px coming from the footer border. For some reason I had to add one more pixel to prevent the scrollbar from appearing. Maybe refactor to flexbox later.

**Review by lafriks — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Pull request merged**
