### PR TITLE
Drop deprecated GOGS_WORK_DIR use

### PR DESCRIPTION
**Pull request by cez81**
I think it's about time to drop GOGS_WORK_DIR

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
I don't really see the need for this
(speaking as one who didn't upgrade from GOGS yet...)

**Comment by lafriks** [comment]
@strk do you use it?

**Comment by strk** [comment]
I don't use it

**Pull request merged**
