### PR TITLE
Backport locales to v1.20

### PR DESCRIPTION
**Pull request by denyskon**

### CODE REVIEW

**Review by delvh — DISMISSED** [review]

**Review by yardenshoham — APPROVED** [review]

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
Sorry, this backport is wrong because the `_package_.documentation` strings are all broken.

**Comment by denyskon** [comment]
@wxiaoguang What do you mean? Why are they broken?

**Comment by wxiaoguang** [comment]
See https://github.com/go-gitea/gitea/issues/25638#issuecomment-1624591193

**Comment by denyskon** [comment]
I removed the broken translations

**Review by wxiaoguang — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Pull request merged**
