### PR TITLE
Remove the ServiceWorker and manifest.json

### LINKED ISSUE #12344: Generate manifest.json when gitea web start up but not rendering when requesting
The route /manifest.json could be rendered when start gitea web but not always rendering when requesting. The generated file could be saved to `data/html` directory or object storage in future. And the router could just serve the file.
So that we could add the file to a CDN to accelerate the site.

### PR DESCRIPTION
**Pull request by silverwind**
There is barely any performance benefit of SW-based caching and it causes a lot of issues after updating a instance and when the cache is stale, causing weird UI issues like chunk loading errors and other unexpected behaviour.

I kept the unregistration in the code so existing serviceworkers will properly uninstall after an update. We may be able to eventually drop the code completely in a future version after most users have ran the uninstallation.

manifest.json is removed because it serves no real purpose without a serviceworker and to eliminate another HTTP request for the sake of performance.

Fixes: https://github.com/go-gitea/gitea/issues/12344

### CODE REVIEW

**Comment by zeripath** [comment]
Is there no way we can stick monaco in the serviceworker to reduce the time it takes for that to start working?

**Comment by silverwind** [comment]
With no ServiceWorker, we still have the regular HTTP cache of the browser so things like Monaco will still be in there.

**Comment by silverwind** [comment]
Monaco is just one big chunk of JS (4MB) which takes time to execute. It may be worth to revisit https://github.com/go-gitea/gitea/pull/12193

**Comment by silverwind** [comment]
@zeripath revived that PR. It definitely increases monaco loading speed. https://github.com/go-gitea/gitea/pull/12401.

**Comment by CirnoT** [comment]
Not against (in fact strongly in favor) but as discussed before it will be a breaking change for those using or relying on Gitea being PWA.

**Comment by silverwind** [comment]
I don't see how this could be breaking. The ServiceWorker was only used to cache assets. None of those assets can work standalone without the server available so there was never any offline functionality.

**Comment by CirnoT** [comment]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

Simply speaking the 'Install' icon wont show anymore to create easy shortcut and open Gitea in its own window. Pretty useless for us to be honest, but nonetheless it will change the behavior.

**Comment by CirnoT** [comment]
Might as well drop manifest.json too as it won't be used without SW

**Comment by silverwind** [comment]
Indeed, removing manifest.json might be a good idea to eliminate another HTTP request on every page. It currently pretty much only serves to set `background_color` (wrongly in the case of non-default theme) and `theme_color` (has a HTML meta tag alternative).

**Comment by silverwind** [comment]
manifest.json removed as well and updated OP with a issue reference.

**Comment by silverwind** [comment]
Removed two images that were only used in manifest.json and README (replaced it with the SVG there).

**Comment by Floaf** [comment]
Will not this affect future Push notifications? https://github.com/go-gitea/gitea/pull/10884

**Comment by silverwind** [comment]
I guess it'd be possible to keep the SW but just disable the caching, so it essentially would do nothing.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
Wouldn't it be better to just change the `app.ini` config parameter `USE_SERVICE_WORKER` to disable SW by default, instead of removing the SW functionality entirely?
That way users who'd still prefer to have it would not be affected (they would get to keep the broken caching + mainfest.json) and the default would be not to use it.

**Comment by silverwind** [comment]
Hmm, actually not a bad idea but I'd introduce a new config switch (off by default) that controls whether the caching is enabled. When no SW-managed feature is enabled (currently there's only one), uninstall it.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Hmm, actually not a bad idea but I'd introduce a new config switch that controls whether the caching is enabled (off by default). When no SW-managed feature is enabled (currently there's only one), uninstall it.

cool, that'd do very well, too :)

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by silverwind** [comment]
Don't think I'll pursue this anymore. I have a fix in mind using `SKIP_WAITING` for the stale serviceworker issue but it's quite hard to test it, may check out again later.

**Pull request closed without merging**
