### PR TITLE
Change sqlite DB path default to data directory

### PR DESCRIPTION
**Pull request by jolheiser**
As titled, split from #6176

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
And why not `filepath.Join`?

**Comment by jolheiser** [comment]
I was unaware there were two different common join methods. Go has a few of these interesting "features" I've noticed.

After reading the docs and differences, filepath probably makes more sense here, though throughout the code I see both methods being used somewhat interchangeably.  
  
Would you prefer I change it to filepath?

**Comment by jolheiser** [comment]
@lunny @techknowlogick I doubt it would change your review, but just an FYI that I changed `path.Join` to `filepath.Join` 👍

**Comment by MCF** [comment]
FWIW, I did some research into path vs. filepath in go, and how it impacts paths in Windows.  Turns out it is not that much of a problem in _most_ cases:

https://github.com/go-gitea/gitea/issues/2845

There are a few additional notes in the pull request that fixed that issue if you are interested in all the gory details.

**Comment by jolheiser** [comment]
Thanks for the info! That's more or less what I read when looking in to it as well.  
Paths to a file (or other system location) should generally use `filepath` 

As Go explains it:
> The filepath package uses either forward slashes or backslashes, depending on the operating system. To process paths such as URLs that always use forward slashes regardless of the operating system, see the path package.

**Comment by techknowlogick** [comment]
Thanks for making this change 😃

**Comment by MCF** [comment]
It is true that filepath is preferable.  But I found in my testing that Go is very forgiving with the slashes, so you can mix and match slashes as you wish and Go will "do the right thing" in most cases on any operating systems. In other words you _can_ actually be pretty lazy about using path instead of filepath and get away with it in almost all cases.

The fly in the ointment that I found was UNC paths (i.e. Windows files share paths like: `\\my-cool-share\data\test.txt`).  Path does not always "do the right thing" with those paths.  But filepath does. 

But fundamentally everyone is right in saying that filepath should be used for paths to the filesystem.  I was just trying to provide context around why it still (mostly) works if you don't.

**Pull request merged**
