### PR TITLE
Fix wiki page list not rendering after UpdatedUnix changes

### PR DESCRIPTION
**Pull request by lafriks**
Was broken after #3142 changes

### CODE REVIEW

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
will fix #3184

**Comment by WallenHan** [comment]
when release this fixed version? in 1.4.0 ?

**Comment by lunny** [comment]
@WallenHan this will be master and not affect v1.3.x and should be in v1.4.0

**Comment by WallenHan** [comment]
@lunny   is there  a  bugfixed version  now?  I am using the docker gitea.

**Comment by lunny** [comment]
`docker pull gitea/gitea:latest` upgrade to latest version will resolve your problem.

**Comment by WallenHan** [comment]
thank you, give you  full score! 💯

**Pull request merged**
