### PR TITLE
Show Gitea version in swagger

### LINKED ISSUE #14645: Reflected gitea version in API version
Would be kinda nice if this was reflected by try.gitea.io :) - it shows 1.1.1 at the top

image

_Originally posted by @AuspeXeu in https://github.com/go-gitea/gitea/issues/14643#issuecomment-777504537_

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #14645

### CODE REVIEW

**Comment by jpraet** [comment]
Won't the API version need to evolve separately from the Gitea version?
Maybe in Gitea 1.15 there are no changes to the API, then why update its version?
Maybe in Gitea 2.x there are no major changes to the API and we want to keep the endpoint as /api/v1?

**Comment by 6543** [comment]
well it's only to generate swagger docs ... at the moment it is useless and i think it's save to use gitea's version to version the swagger json with it ...

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@techknowlogick now it looks good, we just have to replace `+` with `-` since it is displayed as `&#43;`

**Comment by jpraet** [comment]
If it's only for documentation purposes then I would suggest
`"description": "This documentation describes the v1 API of Gitea {{AppVer}}."` while still keeping the flexibility of being able to evolve the API version and Gitea version independently.

**Comment by 6543** [comment]
we did not evolve API and Gitea independently (We do not backport api features)

**Comment by lafriks** [comment]
From security perspective it should be show only if allowed by setting show version number

**Review by a1012112796 — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lafriks app version is visible many places elsewhere in app, such as the MD5 for cache busting of JS & CSS assets

**Comment by 6543** [comment]
:rocket:

**Comment by jpraet** [comment]
image

The + is displayed as `&#43;`

**Comment by lunny** [comment]
> image
> 
> The + is displayed as `&#43;`

Could you fire a new issue?

**Pull request merged**
