### PR TITLE
Fix margin on the new/edit project page.

### PR DESCRIPTION
**Pull request by puni9869**
New/Edit Project page consistent layout. Fix margin on the new/edit  page.

Before: 
image
image

After
image
image

### CODE REVIEW

**Comment by lunny** [comment]
Could you also have a mobile screenshot?

**Comment by puni9869** [comment]
> Could you also have a mobile screenshot?

I forget sorry :)

image

image

**Comment by silverwind** [comment]
Should do the same on new release page and possibly others to be consistent.

**Comment by puni9869** [comment]
> 
Yes, I have a curated a list of inconsistent layouts. 
This Pr I cooked long before in my local but not raised.
Currently working on release page and other places fixes. Will address those in one PR.

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
> > 
> 
> Yes, I have a curated a list of inconsistent layouts. This Pr I cooked long before in my local but not raised. Currently working on release page and other places fixes. Will address those in one PR.

You mean another PR? I'm ok with that as well.

**Comment by puni9869** [comment]
> 

Yes, In another Pr I will address those changes.

**Review by denyskon — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
