### PR TITLE
Fix postgres ID sequences broken by recreate-table

### LINKED ISSUE #14725: postgres ERROR: duplicate key value violates unique constraint "email_hash_pkey"
- Gitea version (or commit ref): v1.13.2 built with GNU Make 4.3, go1.15.7
- Git version:     2.26.2
- Operating system: Raspbian GNU/Linux 10, docker kunde21/gitea-arm   v1.13.2-armv7
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Using gitea 1.13.2 and postgres 13.0 I still have the following reoccuring postgres errors:

2021-02-16 21:31:14.345 UTC [20446] ERROR:  duplicate key value violates unique constraint "email_hash_pkey"
2021-02-16 21:31:14.345 UTC [20446] DETAIL:  Key (hash)=(xxxxxxxxxx) already exists.
2021-02-16 21:31:14.345 UTC [20446] STATEMENT:  INSERT INTO "email_hash" ("hash","email") VALUES ($1,$2)

I understand that this should be fixed in 1.13.0 via https://github.com/go-gitea/gitea/pull/12577 
...

### PR DESCRIPTION
**Pull request by zeripath**
Unfortunately there is a subtle problem with recreatetable on postgres which
leads to the sequences not being renamed and  being left at 0.

Fix #14725

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Should be backportable without the migration of course.

**Comment by zeripath** [comment]
Grargh looks like we can't rely on  `pg_sequences`

I think information_schema.sequences might just work

**Comment by lafriks** [comment]
Fails with relation "pg_sequences" does not exist

**Comment by zeripath** [comment]
Should now be fixed

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
