### PR TITLE
Add missing menu active item background back

### LINKED ISSUE #30578: Selected workflow will not be highlighted
### Feature Description

image
IIRC, it will be highlighted when workflow was selected before.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #30578

image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Not sure if this is a complete fix. I will check later. In v1.21, this style was provided by this rule:

```
.ui.menu .active.item,
.ui.menu .active.item:hover,
.ui.vertical.menu .active.item,
.ui.vertical.menu .active.item:hover {
  color: var(--color-text);
  background: var(--color-active);
}
```

Somehow this must have gotten lost during https://github.com/go-gitea/gitea/pull/30325 or another PR.

**Review by silverwind — CHANGES_REQUESTED** [review]
Blocking until I verified this.

**Comment by wxiaoguang** [comment]
I have checked there is `.ui.menu .active.item {  background: var(--color-active); `

And I think current UI looks good enough so there is no need to add `:hover`.


Feel free to double check and edit this PR if necessary

**Review by silverwind — APPROVED** [review]
Looks good. Another option may be to remove `.ui.vertical.menu .item { background: none }`, but I'm not sure whether this has side-effects.

**Pull request merged**
