### PR TITLE
Fix zip file upload problem

### PR DESCRIPTION
**Pull request by ghost**
as title

### CODE REVIEW

**Comment by silverwind** [comment]
How about we finally change the default to an unopinionated `*/*`? It's what most users want I guess.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
`application/x-zip-compressed` is nonstandard and may also used by executable `.jar` files. I think we should not concern ourselves with the insanity of mime-types and just allow everything by default.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/12465

**Comment by techknowlogick** [comment]
@jaqra thanks for your work on this PR. I am going to close it in favour of #12465

**Pull request closed without merging**
