### PR TITLE
Changelog v1.15.9

### PR DESCRIPTION
**Pull request by zeripath**
* BUGFIXES
  * Revert "Fix delete u2f keys bug (#18042)" (#18107)
  * Migrating wiki don't require token, so we should move it out of the require form (#17645) (#18104)
  * Prevent NPE if gitea uploader fails to open url (#18080) (#18101)
  * Reset locale on login (#17734) (#18100)
  * Correctly handle failed migrations (#17575) (#18099)
  * Instead of using routerCtx just escape the url before routing (#18086) (#18098)
  * Quote references to the user table in consistency checks (#18072) (#18073)
  * Add NotFound handler (#18062) (#18067)
  * Ensure that git repository is closed before transfer (#18049) (#18057)
  * Use common sessioner for API and web routes (#18114)
* TRANSLATION
  * Fix code search result hint on zh-CN (#18053)

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Awaiting merge of #18114

**Review by wxiaoguang — APPROVED** [review]
ps: should the date be 2021-12-29 now?   :D

**Comment by wxiaoguang** [comment]
BTW: could we take another backport in?
* https://github.com/go-gitea/gitea/pull/18095

**Comment by lunny** [comment]
Wait #18121's backport.

**Comment by wxiaoguang** [comment]
> Wait #18121's backport.

Sorry, I need to do more test for #18121. So please ignore that.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
