### PR TITLE
Fix migration file names

### PR DESCRIPTION
**Pull request by sorenisanerd**
The file names of the migrations and the comments in
`models/migrations/migrations.go` disagree on the version number.

For example:

    // v259 -> v260
    NewMigration("Convert scoped access tokens", v1_20.ConvertScopedAccessTokens),

...but the file containing `v1_20.ConvertScopedAccessTokens` is called
`v1_20/v259.go`.

Checking the `version` table indicates that the comments are correct
and the file names are wrong.

This PR fixes the filenames. It's spread over two commits in an attempt
to make git understand that they're renames. See individual commit
messages for more detail.

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]
Thanks for the individual commits.

Out of curiosity, does Gitea display the changes only as renames or like Github does?

**Comment by lunny** [comment]
Maybe we can rename v259.go -> 259.go so that git can recognize the rename. And next PR we can also rename back if we need that.

**Comment by wxiaoguang** [comment]
The root problem is "how to understand the 'version' and the comment".

For example:

```
	// v70 -> v71
	NewMigration("add issue_dependencies", v1_6.AddIssueDependencies),
```

Before:

* `version` means the next migration's starting number
* So the number of `AddIssueDependencies` is 70 (v70.go), and database.version=71 (for next)
* The comment means "the current step is v70 and after this step and then the database version becomes 71"

After:

* `version` means the current migration's starting number
* So the number of `AddIssueDependencies` will be 71, and database.version=71 (for current)
* The comment for each step can be simplified to "// v71" ... 
* The comment above (Gitea 1.5.0 ends at v69) seems unmatched, while fortunately, the database version for 1.5.x should be actually 70, so it's only a comment problem).

**Review by wxiaoguang — DISMISSED** [review]

**Comment by wxiaoguang** [comment]
I also agree with using some tricks like "v259.go -> 260.go" (or v-260.go) is better. (the `v` prefix seems more readable and easier to maintain)

**Comment by wolfogre** [comment]
My suggestion is `v259.go` -> `v0260.go`, so git can recognize the rename and the files order will be always correctly (`v0001.go` ... `v9999.go`). 

If one day we get `v9999.go`, we should be celebrating, not obsessing. 👀

**Comment by KN4CK3R** [comment]
> the pull diff is hard to read :/

If you look at the two individual commits you only see renames, so it's fine.

**Comment by wolfogre** [comment]
> > the pull diff is hard to read :/
> 
> If you look at the two individual commits you only see renames, so it's fine.

I don't think it's fine, if the final merged commit cannot recognize the rename, it can be annoying when git blame.

**Comment by wxiaoguang** [comment]
Agree with lunny and wolfogre. When this PR gets "squashed" into main branch, we should make sure there is a clear commit history. Although these two separate commits are clear one by one, but, when they get squashed, the commit history will be a mess.

So, there are some suggestions for "only one clear commit".

* lunny: v259.go -> `260.go`
* wxiaoguang: v259.go -> `v-260.go` (or use some suffix?) I think a proper prefix really helps about maintainability.
* wolfogre: v259.go -> `v0260.go`

**Comment by KN4CK3R** [comment]
Alternative `260-short_description.go` like the text in `NewMigration`.

**Comment by 6543** [comment]
Hmm or make an exemption and dont squashmerge?

**Comment by wxiaoguang** [comment]
> Alternative `260-short_description.go` like the text in `NewMigration`.
> 
> GitLab does the same: https://gitlab.com/gitlab-org/gitlab/-/tree/master/db/migrate

I also have asked so, but at that time, in discord discussion, maintainers explained that "Only use the v123.go, to make sure the filename conflicts for different PRs, that's the conflict-based workflow".

I am not sure whether maintainers have new ideas about this topic nowadays.

**Comment by techknowlogick** [comment]
@wxiaoguang I wrote https://github.com/techknowlogick/xormigrate to 1. backport migrations, 2. prevent conflicts from migrates having the same name, and 3. a cleaner developer experience.

**Comment by wxiaoguang** [comment]
> Agree with lunny and wolfogre. When this PR gets "squashed" into main branch, we should make sure there is a clear commit history. Although these two separate commits are clear one by one, but, when they get squashed, the commit history will be a mess.
> 
> So, there are some suggestions for "only one clear commit".
> 
>     * lunny: v259.go -> `260.go`
> 
>     * wxiaoguang: v259.go -> `v-260.go` (or use some suffix?) I think a proper prefix really helps about maintainability.
> 
>     * wolfogre: v259.go -> `v0260.go`

I think there should be some better solutions than this change, this change's "squash" merge would make the commit unreadable.

**Comment by sorenisanerd** [comment]
Alternatively, we could just get rid of the individual comments in `migrations.go`? They're not really adding anything but confusion. The order they're listed in is really what matters.

**Comment by wxiaoguang** [comment]
> Alternatively, we could just get rid of the individual comments in `migrations.go`? They're not really adding anything but confusion. The order they're listed in is really what matters.

IMO the comments should be kept, that's the only way to know the "version number" of a migration step.

**Comment by wxiaoguang** [comment]
Stale and a lot of conflicts.

Feel free to reopen if some comments (like https://github.com/go-gitea/gitea/pull/25735#issuecomment-1624911102) are addressed. It needs a clear "squahed" result.

**Comment by wxiaoguang** [comment]
-> Refactor the DB migration system slightly #32344

**Pull request closed without merging**
