### PR TITLE
Ignore check code.gitea.io/gitea/data on make test

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
let L-G-T-M work

**Comment by tboerger** [comment]
What is that?

**Comment by lunny** [comment]
It was created by some PR and there are some .go files in it.

**Comment by tboerger** [comment]
There is no data package within master branch.

**Comment by lunny** [comment]
Yes. It's created by some test function. Oh, It should be removed after test is over. @ethantkoenig but not send this PR.

**Pull request closed without merging**
