### PR TITLE
Add left padding for chunk header of split diff view

### PR DESCRIPTION
**Pull request by bagasme**
This commit adds 10px `padding-left` on chunk header element
(which is `<span>`).

For example (taken from commit 06268dcf53657ffe012abe878e1127ab4f954264):
chunk header with padding

Without padding, the chunk header looks less neat:
chunk header without padding

Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>

### CODE REVIEW

**Comment by silverwind** [comment]
Could also use the helper class `pl-2` for similar effect without any CSS needed:

https://github.com/go-gitea/gitea/blob/06268dcf53657ffe012abe878e1127ab4f954264/web_src/less/helpers.less#L65

**Comment by bagasme** [comment]
@silverwind I'd tried your suggestion at commit bagasme/gitea@adda0dc03c0347641960571088005c277cb8dd50.
Unfortunately, the resulting HTML after building does not change (the `px-3` class is stripped away), despite that I'd cleared browser cache and doing `make clean-all` before build.

**Comment by silverwind** [comment]
Try `make clean-all` followed by a `make watch`, it should rebuild after changes and work.

**Comment by bagasme** [comment]
@silverwind I still can't get the `px-3` class to appear on `<span>` chunk header element, and thus the padding.

**Comment by silverwind** [comment]
Will try later. Unless there is JS that overrides it, I see no reason why it shouldn't work.

**Comment by silverwind** [comment]
Where is that header seen? I thought it was diff but it seems that one has proper padding already?

image

**Comment by bagasme** [comment]
@silverwind that was what I mean for this PR

**Comment by silverwind** [comment]
Isn't there enought whitespace already (added by unremovable `.lines-type-marker`):

image

**Comment by mrsdizzie** [comment]
Hm seems like the screenshot in the PR description is misleading and has intentionally cropped out the existing whitespace from ```.lines-type-marker``` to the left then? I agree with @silverwind this seems to look OK already unless there is a misunderstanding of why changing it would be better. Looks about the same as Github now except they use ```@@``` to start the line

Screen Shot 2020-11-09 at 11 11 17 AM

**Review by zeripath — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
