### PR TITLE
Fix `organization` field being `null` in `GET /api/v1/teams/{id}` (#24694)

### LINKED ISSUE #20399: Organization is null from GET team API
### Description

When i call API endpoint `/api/v1/teams/{id}`, the organization property is `null`.
I would expect it to return Oraganization entity as value.
Same result if called from an Admin account or user member of this team.

Is this expected behaviour?

_I cannot reproduce this issue on official website because i cannot create organization there._

### Gitea Version

1.16.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Ubuntu Server 20.04

### How are you running Gitea?

Running Gitea on local server.

### Database

SQLite

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #24694 by @yardenshoham

Enabled the organization loading flag.

- Fixes #20399 

# Before
```json
{
  ...
  "description": "",
  "organization": null,
  "includes_all_repositories": true,
  "permission": "owner",
  ...
}
```

# After
```json
{
  ...
  "description": "",
  "organization": {
    "id": 2,
    "name": "bigorg",
    "full_name": "",
    "avatar_url": "https://3000-yardenshoham-gitea-3gfrlc9gn4h.ws-us96b.gitpod.io/avatars/e2649b0c016d9102664a7d4349503eb9",
    "description": "",
    "website": "",
    "location": "",
    "visibility": "public",
    "repo_admin_change_team_access": true,
    "username": "bigorg"
  },
  "includes_all_repositories": true,
  "permission": "owner",
  ...
}
```

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
wait a minute. I will add a test for that.

**Comment by lunny** [comment]
see #24699 24699

**Comment by yardenshoham** [comment]
We have to merge the fix before we backport the test...

**Comment by lunny** [comment]
> We have to merge the fix before we backport the test...

How about cherry pick that PR to this one?

**Comment by yardenshoham** [comment]
Sure, but I don't have push access

**Comment by yardenshoham** [comment]
It's fine to do it separately, merge it one-by-one

**Review by lunny — APPROVED** [review]

**Pull request merged**
