### PR TITLE
Use flex classes in package settings

### LINKED ISSUE #26130: "You pushed on branch" message shows branch from different repository
### Description

When you push to gitea, "new pull request" message shows up on "code" tab in repository. But the branch it shows is from a different repository

### Gitea Version

master

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image
image

### Git Version

latest

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### LINKED ISSUE #26310: css bug in /$org/-/packages/container/$foo/latest/settings
### Description

go to: /$org/-/packages/container/$foo/latest/settings to see that the css is broken

open your organization page -> packages -> select package -> click on settings in bottom right corner -> see broken red box

### Screenshots

image

### Gitea Version

1.21.0+dev-437-gb9baed2c74

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

arch

### Browser Version

chrome

### PR DESCRIPTION
**Pull request by KN4CK3R**
Regression of #25790
Fixes #26310

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Found another regression.
grafik

**Comment by silverwind** [comment]
cc: @denyskon

**Review by denyskon — APPROVED** [review]
Thanks for the fix, I must have overlooked this.......

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/26314#issuecomment-1666897367 is still unresolved as far as I can tell, in case you want to have a look @denyskon.

**Comment by denyskon** [comment]
> [#26314 (comment)](https://github.com/go-gitea/gitea/pull/26314#issuecomment-1666897367) is still unresolved as far as I can tell, in case you want to have a look @denyskon.

Isn't it resolved by https://github.com/go-gitea/gitea/pull/26314/commits/dbaa94bc195c543647308e546d4af01321e60fc2 ?

**Pull request merged**
