### PR TITLE
Remove superfluous argument

### PR DESCRIPTION
**Pull request by Gusted**
As title.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Please send back port to v1.15

**Comment by wxiaoguang** [comment]
I think it's not a bug (no affect), backport or not won't affect 1.15

**Comment by Gusted** [comment]
> I think it's not a bug (no affect)

Correct, superfluous arguments in javascript are fine and they won't _really_ effect function executions.

**Comment by lunny** [comment]
Hm, any better label do you think we should give it.

**Comment by Gusted** [comment]
> Hm, any better label do you think we should give it.

I personally would label such little code changes under refactoring.

**Pull request merged**
