### PR TITLE
chore: upgrade less which fixes a severity vulnerability

### PR DESCRIPTION
**Pull request by BANG88**
Upgrade less to the latest version due to npm found a severity vulnerability

```sh
➜  gitea git:(master) npm audit

                       === npm audit security report ===

# Run  npm update stringstream --depth 3  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Out-of-bounds Read                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ stringstream                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ less [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ less > request > stringstream                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/664                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 1 moderate severity vulnerability in 85 scanned packages
  run `npm audit fix` to fix 1 of them.
```

### CODE REVIEW

**Comment by techknowlogick** [comment]
CI fail: Please run `make generate-stylesheets` and commit the result

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
This looks like it only goes to less v3.5.3, but latest version of less is v3.6.0. There is a newer PR that goes to that version #4415 
If you go to latest version of less I'll close that other PR.

**Comment by BANG88** [comment]
The latest version published 11 hours ago. If you want the latest version you can merge #4415 and ignore this one. :)

**Comment by lafriks** [comment]
Closing in favor of latest version

**Pull request closed without merging**
