### PR TITLE
Support shortened commit SHAs in URLs

### LINKED ISSUE #6450: Proposal to add missing support for short-hash src URLs
Similar to #211, it would be convenient to support abbreviated commit IDs in file content/browsing URLs. This is a supported pattern in other Gitea URLs already (commit and archive at least), and also doable with similar interfaces like gitweb, cgit, bitbucket and github. Shorter IDs are handy for reducing the URL length when linking from media where column count is at a premium and wrapping tends to be avoided when possible (mailing list threads, IRC discussions, ...).

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #6450

Closes #6452

### CODE REVIEW

**Review by a1012112796 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Feedback from other PR:

> Can we support the shortened sha but redirect to the full actual one ?

**Comment by lafriks** [comment]
@techknowlogick I don't think that's needed as other it does kind of break desired behavior imho and other (ex. Github and Gitlab) also does not do redirection

**Comment by 6543** [comment]
hmm redirection could be a feature ...

**Comment by lafriks** [comment]
Also we don't do redirection also in other places where we already support short sha urls. Also if later added to API it would be even undesirable

**Comment by techknowlogick** [comment]
In that case is it possible to add `rel=canoical` tags to the commit page with the full sha (more info: https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls) so that search engines don't duplicate the information?

**Comment by lafriks** [comment]
@techknowlogick it's not fool proof but added :D

**Review by techknowlogick — APPROVED** [review]
Thanks :)

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
