### PR TITLE
Stop auto labelers because there are too many inacculate behaviours to make confusing

### PR DESCRIPTION
**Pull request by lunny**
It's very difficult to get to know the aim of PR creator according changed files. A file maybe changed project files but the PR maybe a bugfix/a refactor/a comment added and etc.

Revert #26962

### CODE REVIEW

**Comment by silverwind** [comment]
If our intend is to capture PR intend in the labels, then yes I agree, the labeler is unsuitable.

**Comment by silverwind** [comment]
Labeler is only suitable for "subsystem" style labels, like `ui`. Maybe keep those uncontested cases?

**Comment by silverwind** [comment]
Overall I think the labeler is more beneficial than it hurts. Take a look at recent PRs, they do have good labels.

Maybe we should disable the [`sync-labels`](https://github.com/actions/labeler#inputs) option so that it never removes labels? I think some of the issues come from this option.

**Comment by silverwind** [comment]
It correctly labeled what we told it to. Big refactors like that are likely to trigger most labels. I think we should probably just remove these labels from the config: `theme/package-registry`, `kind/api`, `kind/cli`, `kind/lint`.

**Comment by wxiaoguang** [comment]
If anyone really spent time on the label system, really ever maintained the labels, and then introduce the labeler carefully, then I could agree with them.

**Comment by silverwind** [comment]
I can guarantee that if we remove the labeler, many PRs will merge unlabeled because no one cares about those labels really. I'm fine with merging unlabeled PRs too, I don't need them. But the changelog tool might.

**Comment by wxiaoguang** [comment]
> I can guarantee that if we remove the labeler, many PRs will merge unlabeled because many do not care about those labels in reality.

Default/no-op is better than wrong.

> But the changelog tool might.

I can understand such requirement. IMO the solution for such "label problem" should start from the changelog tool.

Define which kinds of labels are really needed and necessary first, maintain the current labels, remove dead ones, clarify how to use the labels correctly, then fine tune the labeler bot.

**Comment by wxiaoguang** [comment]
> Another option might be to require a prefix on commit message to categorize the PRs and remove most if not all of the labels.

That's somewhat related. One of the problems is that the "changelog" rules are not clear. For example, why there is a separate "API" section? A change should be either a feature/enhancement/bugfix/misc. If a PR does a bugfix for both web and api, why it should appear in the API section?

The historical unclear rules are the root problem.

**Comment by silverwind** [comment]
I wouldn't mind if we just set a optional single category label manually. If we retain subsystem labels like `ui`, those should stay in the labeler imho.

**Comment by denyskon** [comment]
I agree that we need to rework our label system before we start applying labels automatically.

I would suggest:

1. split PR and issue labels
2. for issues, keep it simple and only separate by kind (proposal, bugreport, question, misc) and status (needs feedback, confirmed, in implementation)
3. decide what PR labels are for (which information are they supposed to provide?)
I can think of the following categories:
- section - which part(s) of the codebase does it affect: templates, web_src, backend, api
- kind - what does this PR do: feature, bugfix, enhancement, refactoring, docs
- topic - which functionality does it affect: package-registry, administration, actions, wiki, issues, repos, authentication, ui
- review status: wip, blocked, ready to merge, in review, pending, urgent
- MAYBE complexity, but not according to the useless size bot but according to the author

I think that would make labels more logical and useful for everyone. And the section part is the only one we can automatically apply according to the files changed.

**Comment by silverwind** [comment]
Alternative PR: https://github.com/go-gitea/gitea/pull/27502

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27502 was merged, pending further adjustments.

**Pull request closed without merging**
