### PR TITLE
Replace emojify with unicode emoji

### LINKED ISSUE #8953: [BUG] [UI] emoji dont work in markdown list
version 1.10.0 and current

preview: https://gitea.com/gitea/gitea.com/issues/8

### LINKED ISSUE #8974: [UI] emoji.js ToDo List
list what come up in #8950,  #8886, ...

## ToDo's
* [ ] Upgrade to latest fork ([hackmdio/emojify.js](https://github.com/hackmdio/emojify.js) since [joypixels/emojify.js](https://github.com/joypixels/emojify.js) is archived)

## Bug's
* [ ]  emoji dont work in markdown list (#8953)

## Enhancements
* [ ] utf8 emoji's (https://github.com/hackmdio/emojify.js/issues/21)
* [ ] optional use of CDN for emoji's
* [ ] custom skin color ? (https://github.com/go-gitea/gitea/pull/8950#issuecomment-553459528)

### LINKED ISSUE #9182: Replace emojify.js with openmoji set
[emojify.js](https://github.com/joypixels/emojify.js) is not maintained anymore.

At some point we would need to switch to another lib to manage emoji (or maintain a fork).
The lib emojify.js does two think :
- replace :emoji: with  tag
- provide a set of emoji

I suggest to move to [openmoji](https://openmoji.org/) for the emoji set.

It seems to be a large choice with good quality : https://openmoji.org/library/

### PR DESCRIPTION
**Pull request by silverwind**
- remove emojify and replace it with custom name-to-unicode replacement
- move tribute code to own file as it depends on emoji data

This depends on simplemap.json that emojilib publishes which is a 40kB JSON file containing name-to-unicode mappings. It supports 1571 emoji compared to the previous 881 of emojify.

Before:
image
image
image

After:
image
image
image

Fixes: https://github.com/go-gitea/gitea/issues/9182
Fixes: https://github.com/go-gitea/gitea/issues/8974
Fixes: https://github.com/go-gitea/gitea/issues/8953

### CODE REVIEW

**Comment by mrsdizzie** [comment]
👀 did we just write and submit the same pr?!?

**Comment by silverwind** [comment]
BTW it's not really intentional that the drometary turned a camel in those screenshots. From the data, which also matches GitHub's behaviour, meaning previous `:camel:` was incorrect:

```
  "dromedary_camel": "🐪",
  "camel": "🐫",
```

**Comment by silverwind** [comment]
@mrsdizzie oh damn 🤣

**Comment by mrsdizzie** [comment]
Let me know if you want to collaborate or what you think -- I kind of like doing it in go better but would love opinions from anybody who has spent time with emojis recently

**Comment by silverwind** [comment]
@mrsdizzie so your approach does it on the backend rendering? I think that's generally the better approach of the two because JS replacement always sucks as wrong content flashes. I will investigate your PR.

**Comment by silverwind** [comment]
Closing for https://github.com/go-gitea/gitea/pull/11032. Will repurpose some code from here there.

**Pull request closed without merging**
