### PR TITLE
Refresh codemirror on show pull comment tab

### LINKED ISSUE #10975: PR / Issue templates do not get rendered during PR creation
- Gitea version (or commit ref): 1.11.3
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
We created pull request template  in the same way it is written in the documentaton https://docs.gitea.io/en-us/issue-pull-request-templates/. That worked fine.

The only issue we see now is, that wenn yo create a Pull Request the description field is empty. Only when you click in the "Write" field the tempates get rendered. Otherwise it stays empty. So the users dont have a hint to fill it out. Worst case, no description as it is not mandatory field.

In github, it gets renderd, as soon you create the PR 

## Screenshots
new PR - no template rendered:
new_pr

click on Write-Field:
click_of_write
te - templates get renderd

### PR DESCRIPTION
**Pull request by zeripath**
When trying to create a new PR the comment field does not show the default data until the field is clicked. This PR calls `autoSimpleMDE.codemirror.refresh();` to cause the default data to be shown.

Fix #10975

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by jolheiser** [comment]
Does this also apply to new issues?

**Comment by zeripath** [comment]
damn this doesn't work.

**Comment by zeripath** [comment]
actually this might work and I might just be having a serviceworker meltdown.

**Comment by zeripath** [comment]
It certainly seems to fix http://localhost/gitea/administrator/merge-test/issues/new?body=rabbit+feet

**Comment by zeripath** [comment]
I don't think that issues were ever affected, certainly http://localhost/gitea/administrator/merge-test/issues/new?body=rabbits+feet just works on master.

**Review by jolheiser — APPROVED** [review]
🔥

**Review by mrsdizzie — APPROVED** [review]

**Comment by 6543** [comment]
didnt had time to check but nice 🎉

**Comment by silverwind** [comment]
I guess a proper fix would be to initialize `Codemirror` using the `value` Constructor option, if that's even exposed via SimpleMDE. We should get rid of this mess at some point (https://github.com/go-gitea/gitea/issues/10729).

**Review by lunny — APPROVED** [review]

**Comment by guillep2k** [comment]
Ping lg-tm

**Comment by zeripath** [comment]
@silverwind it's already initialised with the correct value. The issue appears to be that the field is hidden and then shown.

**Pull request merged**
