### PR TITLE
Implement delete release attachments and update release attachments' name (#14130)

### PR DESCRIPTION
**Pull request by kdumontnu**
Backport https://github.com/go-gitea/gitea/pull/14130

fix https://github.com/go-gitea/gitea/issues/677

Co-authored-by: [lunny](https://github.com/lunny)

### CODE REVIEW

**Comment by zeripath** [comment]
Not sure about this - it's technically a feature - but I know we tend to have relatively slow turnarounds for 1.15

**Comment by kdumontnu** [comment]
> Not sure about this - it's technically a feature - but I know we tend to have relatively slow turnarounds for 1.15

Understood - I'm perfectly happy either way. We should be diligent on not adding breaking changes & new features. The reason I thought this might be appropriate is:

- Not being able to delete attachments is (imo) such a large missing piece of releases that it borders on being a bug (making releases unusable)
- It has been merged into master for over a month (which is why I originally thought it had been in 1.14)

If you're uncomfortable with it, lets close this and work on `v1.15` 😄

**Comment by lunny** [comment]
Since there is no migration and break thing, I think it's OK.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@kdumontnu can you update the branch please :)

**Comment by 6543** [comment]
:rocket:

**Review by zeripath — APPROVED** [review]

**Pull request merged**
