### PR TITLE
bug: fix the wrong different view for first commit

### LINKED ISSUE #11650: [BUG] When view first commit it return "Diff Content Not Available"
- Gitea version (or commit ref):  1.13.0+dev-67-g24be06d7a
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/LJR/SuperProejeto/commit/98120fc540b39a4bb7be70fa8802867d03f09bb6
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When you view the first commit of a repo. It returns "Diff Content Not Available".
This error occur on https://try.gitea.io/. And the https://gitea.com/ everything works well.

After reviewing the recent commit history，The error may be related to this pr #11614 

## Screenshots
image

### PR DESCRIPTION
**Pull request by a1012112796**
After check, I think ``git.GetDiffShortStat`` is not necessary to be called, because it hase maken right message in ``ParsePatch``, and  ``git.GetDiffShortStat`` can't get right message if beforeCommitID is empty, which is the reason for #11650

@zeripath Please have a look. Maybe I forgot something. Thanks. 

fix #11650

### CODE REVIEW

**Comment by zeripath** [comment]
The results of the diffstat in ParsePatch are wrong - it's limited to 100 files.

**Comment by zeripath** [comment]
And this solution doesn't fix the proposed issue.

Here is the correct solution:

```
diff --git a/services/gitdiff/gitdiff.go b/services/gitdiff/gitdiff.go
index af88ed4d4..048022e9d 100644
--- a/services/gitdiff/gitdiff.go
+++ b/services/gitdiff/gitdiff.go
@@ -664,7 +664,7 @@ func GetDiffRangeWithWhitespaceBehavior(repoPath, beforeCommitID, afterCommitID
 	ctx, cancel := context.WithCancel(git.DefaultContext)
 	defer cancel()
 	var cmd *exec.Cmd
-	if len(beforeCommitID) == 0 && commit.ParentCount() == 0 {
+	if (len(beforeCommitID) == 0 || beforeCommitID == git.EmptySHA) && commit.ParentCount() == 0 {
 		cmd = exec.CommandContext(ctx, git.GitExecutable, "show", afterCommitID)
 	} else {
 		actualBeforeCommitID := beforeCommitID
@@ -711,7 +711,11 @@ func GetDiffRangeWithWhitespaceBehavior(repoPath, beforeCommitID, afterCommitID
 		return nil, fmt.Errorf("Wait: %v", err)
 	}
 
-	diff.NumFiles, diff.TotalAddition, diff.TotalDeletion, err = git.GetDiffShortStat(repoPath, beforeCommitID+"..."+afterCommitID)
+	shortstatArgs := []string{beforeCommitID + "..." + afterCommitID}
+	if len(beforeCommitID) == 0 || beforeCommitID == git.EmptySHA {
+		shortstatArgs = []string{"--cached", afterCommitID}
+	}
+	diff.NumFiles, diff.TotalAddition, diff.TotalDeletion, err = git.GetDiffShortStat(repoPath, shortstatArgs...)
 	if err != nil {
 		return nil, err
 	}
```

**Comment by zeripath** [comment]
The trick here is the `--cached` flag. 

As we are running these commands in a bare repository the index will always be empty. (This is as it should be - however if for some reason the index file is present this command will fail.)

An empty index file is assumed to represent an empty index by git diff - going back all the way to 1.7.2 and git diff will not create an index.

So ... if you wanted to clean this up and prevent any potential index file from breaking this setting the GIT_INDEX_FILE to a new clean - empty - temp file or better some file guaranteed to be empty would do that.

**Comment by L0veSunshine** [comment]
```diff --git a/services/gitdiff/gitdiff.go b/services/gitdiff/gitdiff.go
index af88ed4d4..8223ee697 100644
--- a/services/gitdiff/gitdiff.go
+++ b/services/gitdiff/gitdiff.go
@@ -711,7 +711,12 @@ func GetDiffRangeWithWhitespaceBehavior(repoPath, beforeCommitID, afterCommitID
 		return nil, fmt.Errorf("Wait: %v", err)
 	}
 
-	diff.NumFiles, diff.TotalAddition, diff.TotalDeletion, err = git.GetDiffShortStat(repoPath, beforeCommitID+"..."+afterCommitID)
+	if beforeCommitID == "" {
+		beforeCommitID = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
+		diff.NumFiles, diff.TotalAddition, diff.TotalDeletion, err = git.GetDiffShortStat(repoPath, beforeCommitID+".."+afterCommitID)
+	} else {
+		diff.NumFiles, diff.TotalAddition, diff.TotalDeletion, err = git.GetDiffShortStat(repoPath, beforeCommitID+"..."+afterCommitID)
+	}
 	if err != nil {
 		return nil, err
 	}
```
This is my solution. After testing the problem was solved.
Notice: git.GetDiffShortStat(repoPath, beforeCommitID+"**..**"+afterCommitID)

**Comment by zeripath** [comment]
@L0veSunshine that is not a general solution...

**Comment by zeripath** [comment]
does my suggested solution not work?

**Comment by L0veSunshine** [comment]
> does my suggested solution not work?

I am sorry i had not try. The previous pr is yours. I believe you soultion is best. 
I only comment for an new Idea.
Please feel free to refer. 
Thanks.

**Comment by L0veSunshine** [comment]
> @L0veSunshine that is not a general solution...

**4b825dc642cb6eb9a060e54bf8d69288fbee4904** is a special hash value in git which denotes an empty tree. And it does not change from repo to repo.
I also discovered it from Google 😀

**Comment by zeripath** [comment]
Well I never would have thought of doing that! Let me adjust my PR to use that SHA as it is seriously clever.

**Comment by zeripath** [comment]
Ah damn git 1.7.2 doesn't allow it I'm afraid

**Comment by zeripath** [comment]
but it does allow it in a different way.

**Comment by zeripath** [comment]
@a1012112796 would you like a co-author tag on my follow-up PR?

**Comment by zeripath** [comment]
Using the information from ParsePatch is not going to work - and in any case will disappear as soon as we start causing diffs to be rendered asynchronously - (which is part of the plan for rewriting/refactoring compare)

**Comment by zeripath** [comment]
Therefore we must use `git diff --shortstat`

**Pull request closed without merging**
