### PR TITLE
Remove requirement of gravatar custom email

### LINKED ISSUE #12: Stop making gravatar email required
It doesn't make sense to have the gravatar email field as an required field. We should stop that.

### PR DESCRIPTION
**Pull request by sapk**
Simply remove mandatory need for the gravatar email.

If the field is let empty it will be restore to the user email. 
Settings a fake email or simply any text would resutl in the defautl gravatar img

It may be neccesary to do more reflection on that problem.
May be change the custom gravatar email to a more commun custom img url ? 
The user could also define the url of is custom gravatar or anything else ?

Fix #12

### CODE REVIEW

**Comment by tboerger** [comment]
I think this needs a little bit more discussion. IMHO we can drop this seperate field and just take the user email as gravatar address.

**Comment by makhov** [comment]
Agree with @tboerger. We can use user email for Gravatar.

**Comment by sapk** [comment]
Maybe de can keep the Avatar field but use it as a URL img remplacement to use if the user declare it ?

**Comment by linquize** [comment]
is it optional in DB schema?

**Comment by tboerger** [comment]
> Maybe de can keep the Avatar field but use it as a URL img remplacement to use if the user declare it ?

Maybe, but currently we have more important stuff than an optional avatar URL so i would drop this gravatar email field and switch gravatar to user email.

**Comment by tboerger** [comment]
@sapk any update here? Just remove the gravatar field and switch gravatar to the user email address.

**Comment by tboerger** [comment]
Please reopen this pull request if you update it.

**Pull request closed without merging**
