### PR TITLE
checkboxes on password fields on install form to reveal typing

### PR DESCRIPTION
**Pull request by manfer**
Password fields are great to hide passwords from prying eyes but if you know there is noone arround sometimes is nice to be able to reveal the password to confirm there is no typo. It improves usability.

So I added a checkbox on the password fields on install form that when checked reveal the corresponding password field text.

If this is accepted and you think it is a good idea it can be implemented in other forms password fields.

### CODE REVIEW

**Comment by tboerger** [comment]
No need for adding seperate HTMl elements manually, there are multiple jQuery plugins out there that can add this functionality to all password fields. I have used [this](https://github.com/crowbar/barclamp-crowbar/blob/master/crowbar_framework/app/assets/javascripts/jquery/hideShowPassword.js) within a project I'm working on, just add ```$('input[type=password]').hideShowPassword();```
 to the main javascript file :)

**Comment by manfer** [comment]
That's better idea indeed. But I'm not sure how is gitea structured.

Should that 3rd party library hideShowPassword.js be placed in public/ng/js/lib ?

Which is the file in which global js scripts are loaded to load that js library?

And finally the $('input[type=password]').hideShowPassword() would be ok in ng/js/gitea.js ?

**Comment by manfer** [comment]
$('input[type=password]').hideShowPassword() looks that could fit in initCore function in ng/js/gitea.js, now I need to figure out where the 3rd party library is placed and how to load it

**Comment by manfer** [comment]
Ok. The library would need to be loaded in the head template if I'm not wrong. Now what I have not clear is where the third party library should be placed. I'm trying to figure it out by looking how the head template loads semantic.min.js. I'm looking for that file but I'm not able to find it anywhere.

Another thing that I have not clear is why gitea.js is in several places and if the pull request should had to deal with min versions of files?

**Comment by manfer** [comment]
Ok. I was looking to the wrong template. It is ng/base/head.tmpl the one I was looking for. And by inspecting that template looks fine the path public/ng/js/utils for the hideShowPassword third party library.

**Comment by tboerger** [comment]
```public/ng/js/lib```should be the right place until we switch to Grunt for preprocessing the assets.

**Comment by tboerger** [comment]
Currently the asset pipeline depends on codekit, we will get rid of that when @fuxiaohei merged the latest changes for the ng templates.

**Comment by manfer** [comment]
I think I finally had been able to implement it all.

Figuring out the proper CSS hasn't been easy. Hope it is ok. I'm going to open a different pull request as now the idea is not just to add the reveal button in install form but on every password field. As soon as I open the new pull request I will add here a link to it and we can close this one.

**Comment by tboerger** [comment]
You don't need to open a new pull request for same functionality, just do a force push :)

**Comment by manfer** [comment]
I have tested now and I see the CSS is not good enough for the whole app because there is not consistency between the CSS on the different forms in the app.

While the install form input fields has a 30% width and the form is responsive, in profile it has a fixed width and it is not responsive. In the sign in page it is different too.

So don't know what is the best solution from here.

I saw the library has options to copy the input field CSS into the wrapper but believe me if I tell you it won't work either. Or I don't know how.

So, I can continue tweaking the custom CSS for this library integration for the different forms which I find (there should not be a lot of password fields) or a real CSS master suggesting rules that would work on every case or that reviews the consistency of the app CSS.

The UI is responsive in some places and not in others.

**Comment by manfer** [comment]
I don't think this PR makes sense anymore as it is related to the UI and the UI is going to be totally rewritted.

**Pull request closed without merging**
