### PR TITLE
Add links to owner home page in explore

### PR DESCRIPTION
**Pull request by yp05327**
User can select access repo or owner's home page.

Before:
image

After:
image

### CODE REVIEW

**Comment by fnetX** [comment]
I do think that this potentially leads to confusion. I do not understand the use case for directly clicking on the user instead of having one page in between, but it could potentially lead to many inadvertent clicks especially on short repo names.

Reaching the owner from a repo is easy. The opposite is often not true, especially with custom searches, different filters or a different order.

I think this should be considered from a UX perspective.

**Comment by lunny** [comment]
I also think it's unnecessary.

**Review by delvh — APPROVED** [review]
I can see both sides, consistency with the remaining application (a link only links to what is displayed inside it) vs. potential confusion (I'm looking for repos, why am I landing on the user profile?).
Either way, since I don't care for which result we pick, here's my approval pro forma.

**Comment by sonjek** [comment]
Hi, this is a useful improvement because sometimes I have to go to the repository and then to the user's page, which is not convenient. This change will allow to choose where you want to go.

**Review by denyskon — APPROVED** [review]

**Pull request merged**
