### PR TITLE
Use goproxy.io instead of goproxy.cn

### PR DESCRIPTION
**Pull request by lunny**
Looks like goproxy.cn is not stable any more.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I think we can just remove the GOPROXY setting, and let users set their own environment variables.

**Review by wxiaoguang — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> > I think we can just remove the GOPROXY setting, and let users set their own environment variables.
> 
> This is for our build system, it does not affect users/developers

I know, I mean if any user need to run that build, they can set environments by themselves.

And, why `our build system` need the GOPROXY? Cannot these agents connect to golang or github site?

**Comment by 6543** [comment]
->  #19246

**Comment by lafriks** [comment]
> I know, I mean if any user need to run that build, they can set environments by themselves.
> 
> And, why `our build system` need the GOPROXY? Cannot these agents connect to golang or github site?

I don't think anyone is running his own drone himself for gitea as this pipeline is quite specific, for developers we have makefile

**Comment by silverwind** [comment]
For drone, one can set [
DRONE_RUNNER_ENV_FILE
](https://docs.drone.io/runner/docker/configuration/reference/drone-runner-env-file/) and in that file you can define for example `GOPROXY="https://proxy.golang.org"`, eliminating the need to having to do this in every `.drone.yml`.

**Comment by wxiaoguang** [comment]
> > I know, I mean if any user need to run that build, they can set environments by themselves.
> > And, why `our build system` need the GOPROXY? Cannot these agents connect to golang or github site?
> 
> I don't think anyone is running his own drone himself for gitea as this pipeline is quite specific, for developers we have makefile

@lafriks My question is  "why `our build system` need the GOPROXY? Cannot these agents connect to golang or github site?", is there an answer?

**Comment by lafriks** [comment]
Because as we don't use vendor directory anymore and if one of sites where dependencies are downloaded from is down our build system would also stop. For example not all dependencies are on github alone but some are also on private servers that could be easily inaccessible time to time. go proxy stores all dependency copy indefinitely so we can be sure that we will be able to download them even if original sites are down.

**Comment by lafriks** [comment]
oh, and using goproxy is also faster as you don't have to clone whole source repository (git) but only packed files for that version

**Pull request merged**
