### PR TITLE
Use import of OCI structs

### LINKED ISSUE #22758: License oddity and copying code insteed of importing?
### Description

I wanted to learn a bit more abotu the gitea registry implementation and found that it copies a lot of code, from the OpenContainers reference implementation.
the gitea OCI container registry implementation copies a lot of code (and has source code link such as ttps://github.com/opencontainers/image-spec/tree/main/specs-go/v1 directly above it.

But the license given in the file its copied to, is still stated at top to be MIT - but opencontainers implementation is Apache 2 license and AFAIK must not be copied without atleast including the apache2 license text and indicating the parts that belong to that license.
Thats how I understand https://www.gnu.org/licenses/license-compatibility.en.html

Should this perhaps not have been imported instead ? or copied as entire files to seperate folder in gitea repo and them imported - so it was easier to specify license?

This way it would also be much easier to detect when the gitea copies becomes out of date (due to newer releases in opencontainer ref. implementation) - and easier to update.

IANAL - but as a user of Gitea I care about its well being and wanted to highlight the issue, now that I stumbled over it.

### Gitea Version

1.8.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

in docker.

### Database

None

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #22758

Otherwise we would need to rewrite the structs in `oci.go`.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by yardenshoham** [comment]
Fix the description, you have a space after `#`

**Comment by yardenshoham** [comment]
We backport refactors?

**Comment by lunny** [comment]
> 

It will resolve a license problem.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport

**Pull request merged**
