### PR TITLE
Fix some broken css

### PR DESCRIPTION
**Pull request by wxiaoguang**
1. The "close" inside "modal" are likely broken for long time
    * There is no var called `--body-color`
    * There is no `fullscreen modal`
    * The `.ui.modal > .close.inside` doesn't seem to match most icons. It only matches a few like "fork-repo-modal" or "adopt repo". Other places are just buggy code copied again and again.
2. Convert the legacy `&:hover` LESS syntax to CSS syntax

### CODE REVIEW

**Comment by silverwind** [comment]
> There is no var called --body-color

We need a linter rule for undefined vars 😉

**Comment by silverwind** [comment]
Should try https://github.com/csstools/stylelint-value-no-unknown-custom-properties.

**Comment by silverwind** [comment]
> Convert the legacy &:hover LESS syntax to CSS syntax

Thanks for catching, I recall `linebuttons.css` was not ran through `lessc`. Another option would be to just run it through it now, but I assume it will yield the same output.

**Review by silverwind — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
I tested the stylelint plugin and it works, but we need to wait on https://github.com/csstools/stylelint-value-no-unknown-custom-properties/issues/32 before we can integrate it.

**Comment by delvh** [comment]
:trumpet: :robot:

**Pull request merged**
