### PR TITLE
Simplify grep regexp to be more compatible

### PR DESCRIPTION
**Pull request by stblassitude**
The new expression also works with the BSD implementation of grep, instead of just GNU grep.

Also, I believe the expression did not work consistently for all possible
version numbers, for example a two digit patch version would not have
been matched.

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
It does not work on single-digit minor version:

```bash
echo 'go version go2.0 linux/amd64' | grep -Eo '[0-9]+\.?[0-9]+\.?[0-9]+'
```

**Comment by stblassitude** [comment]
That is correct. Both Go and Node report three-part version numbers, so it shouldn't be a problem.

Would you prefer: `'[0-9]+\.?[0-9]+(\.[0-9]+)?'`

```
$ for v in 1.2 1.2.3 11.2 11.22.3 11.2.33 11.22.33 111.222.333; do echo $v | grep -Eo '[0-9]+\.?[0-9]+(\.[0-9]+)?'; done
1.2
1.2.3
11.2
11.22.3
11.2.33
11.22.33
111.222.333
```

**Comment by silverwind** [comment]
Go reports 2-part version and Node 3-part but I'd like it to work on 1-part too. These should all work:

```
echo 'v14' | grep -Eo '[0-9]+\.?[0-9]*\.?[0-9]*'
echo 'v14.1' | grep -Eo '[0-9]+\.?[0-9]*\.?[0-9]*'
echo 'v14.1.2' | grep -Eo '[0-9]+\.?[0-9]*\.?[0-9]*'

echo 'go version go1 linux/amd64' | grep -Eo '[0-9]\.?[0-9]*\.?[0-9]*[[:space:]]'
echo 'go version go1.2 linux/amd64' | grep -Eo '[0-9]\.?[0-9]*\.?[0-9]*[[:space:]]'
echo 'go version go1.2.3 linux/amd64' | grep -Eo '[0-9]\.?[0-9]*\.?[0-9]*[[:space:]]'
```

BTW, my version of bsd grep (`grep (BSD grep) 2.5.1-FreeBSD`) does support `[[:space:]]`. Also see https://github.com/go-gitea/gitea/pull/10508 about it.

**Review by silverwind — CHANGES_REQUESTED** [review]
Blocking for now

**Comment by stblassitude** [comment]
Why is the trailing space relevant? To deselect `amd64`? I would find it really surprising for go to report a single-part version number in the future.

**Comment by silverwind** [comment]
Yes it's for that. I don't like this whole grep business, maybe there are better alternatives to get the version directly. For node, one can do:

```
$ node -p process.versions.node
12.16.1
```

Don't know about go, thought.

**Comment by stblassitude** [comment]
```
for v in 1 1.2 1.2.3 11.2 11.22.3 11.2.33 11.22.33 111.222.333; do echo "go$v linux/amd64" | bsdgrep -Eo '[0-9]+(\.[0-9]+){0,2}[[:space:]]'; done
1 
1.2 
1.2.3 
11.2 
11.22.3 
11.2.33 
11.22.33 
111.222.333 
```

**Comment by silverwind** [comment]
Suggestion to not use `grep`:

``` console
$ go version | cut -c14- | cut -d' ' -f1
1.14
$ node -v | cut -c2-
12.16.1
```

The `go version ` string is static as per [this](https://github.com/golang/go/blob/019421d17fedd4af924dee6b969f2945d64a9eea/src/cmd/go/internal/version/version.go#L61).

**Comment by silverwind** [comment]
Apparently go's release tags can also have [suffixes](https://github.com/golang/go/releases) like `go1.14beta1`. So I think a regex is still needed to match those as well:

``` bash
go version | grep -Eo '[0-9]+\.[0-9.]+'
```

This assumes there will never be a single digit version, but I think that is safe to assume.

**Comment by assistcontrol** [comment]
It starts with go, so I'd suggest: `go[0-9].*[[:space:]] | tr -d a-z | tr '.' ' '`

**Review by mrsdizzie — APPROVED** [review]

**Comment by lafriks** [comment]
Please resolve conflict

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Oh, damn, sorry @silverwind I did not see that you requested changes

**Comment by silverwind** [comment]
It's fine. I should have cleared that anyways.

**Pull request merged**
