### PR TITLE
Redirect on bad CSRF instead of presenting bad page

### LINKED ISSUE #14167: Blank page with "Invalid csrf token."
- Gitea version (or commit ref): 1.13.0
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist: N/A

## Description

When clicking buttons or adding comments in issues I often see a blank page saying `Invalid csrf token.`, which I had to work around using a refresh and a re-click, which has problems such as losing text already typed up in the comments. This could be related to me using a lot of tabs.

Issues that this might be related to are:
- #4311: seems very similar, but locked so no discussion can be continued. Don't quite understand how it is closed as #11182 doesn't seem to be solution to this page appearing and proposes to log out instead (why though and how does it make things better?).
- #11188: proposes switching to `SameSite=strict` cookies instead, which seem to be able to fix this issue. Still filling this issue since this is not what a user might expect so should be better categorized as a bug than a proposal. Also, fixing this issue doesn't directly necessitate using #11188 and other fixes might be possible.

### PR DESCRIPTION
**Pull request by zeripath**
The current CSRF handler is a bit harsh with bad CSRF tokens on webpages
I think we can be a little kinder and redirect to base page with a flash error

Fix #14167

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by CL-Jeremy** [comment]
Hmm, this certainly improves UE greatly, but I don't think merging this should close that issue entirely (although that issue lacks details for further investigation to take place).

**Comment by lunny** [comment]
But the submitted form information will be lost. Before we can click `back` button on browser to return back to form page.

**Review by jpraet — APPROVED** [review]

**Comment by jpraet** [comment]
> But the submitted form information will be lost. Before we can click `back` button on browser to return back to form page.

The back button still works for me.

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
I think it's better to back port to v1.14

**Comment by 6543** [comment]
-> #16378

**Pull request merged**
