### PR TITLE
dump: Add option to skip index dirs

### LINKED ISSUE #20683: gitea dump should have option to ignore bleve index
### Feature Description

I noticed that about half of the size of our gitea dumps is the file `data/indexers/repos.bleve` (1.7 Gb)

I'm considering adding an option to skip these indexers when calling gitea dump, similar to how lfs and attachment data can be skipped.

However, before diving in the code: do you think this is a good idea? Would restore from such a dump still work?

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by johanvdw**
closes #20683

Add an option to gitea dump to skip the bleve indexes, which can become quite large (in my case the same size as the repo's) and can be regenerated after restore.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Does Gitea rebuild the index after a restore?

**Comment by lunny** [comment]
> Does Gitea rebuild the index after a restore?

Anyway, I agree we should ignore to dump index directories by default.

**Comment by lafriks** [comment]
> Does Gitea rebuild the index after a restore?

It does

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I think we're quickly getting to the point that we should have `--include-` options which will default to only include the required things.

We should also have something for `--skip-db`

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
