### PR TITLE
Enable new golangci-linters

### PR DESCRIPTION
**Pull request by Gusted**
- Partially resolvess #17596 
- Enable https://github.com/breml/bidichk
- Blocked by #??? Upcoming PR for updating golangci-lint version in Makefile

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by wxiaoguang** [comment]
CI failure is related

**Review by lunny — APPROVED** [review]

**Comment by Gusted** [comment]
> CI failure is related

That's expected, as the new linter was added in the latest version of golangci-lint, which cannot be upgraded before the new linting errors are fixed.

**Comment by Gusted** [comment]
Blocked by #17647

**Comment by lunny** [comment]
make L-G-T-M work.

**Pull request merged**
