### PR TITLE
Remove env user salt since no need to use

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by strk** [comment]
There's a GetEnv for that variable in cmd/hook.go

**Comment by lunny** [comment]
@strk  depends on #1514. I'm sorry I forgot that.

**Comment by lunny** [comment]
It's ready for review now sinc #1514 merged.

**Comment by lafriks** [comment]
It should be also removed from models/update.go as it is not used anymore then

**Comment by lunny** [comment]
done. @lafriks

**Comment by lafriks** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
make L-G-T-M work

**Pull request merged**
