### PR TITLE
Launch Gitea with custom UID/GID for 'git' user (fixes #2286)

### LINKED ISSUE #2286: Docker /app/gitea/gitea web runs as wrong user
why does /app/gitea/gitea web run as a different user instead of git?
Default docker configuration, no changes have been made.

# docker top ed60eb5133ed
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                2914                2896                0                   17:53               ?                   00:00:00            /bin/s6-svscan /etc/s6
root                2947                2914                0                   17:53               ?                   00:00:00            s6-supervise gitea
root                2948                2914                0                   17:53               ?                   00:00:00            s6-supervise openssh
root                2949                2914                0                   17:53               ?                   00:00:00            s6-supervise syslogd
root                2950                2948                0                   17:53               ?                   00:00:00            /usr/sbin/sshd -D
**karel               2951                2947                0                   17:53               ?                   00:00:00            /app/gitea/gitea web**
root                2952                2949                0                   17:53               ?                   00:00:00            /sbin/syslogd -nS -O-

### PR DESCRIPTION
**Pull request by HenrikBengtsson**
Fixes #2286

### CODE REVIEW

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
LGTM

**Comment by lunny** [comment]
@sapk how did you test that?

**Comment by sapk** [comment]
This method is used other image. You can test it (i haven't done it) by setting env variable at docker run. We could maybe provide a docker-copose.yml file now that the container is configurable by env variable.

Another solution for this problem, is to not create the user in the image (Dockerfile) and do a useradd with fixed UID and GID at startup of container.

**Comment by bkcsoft** [comment]
LGTM (Seen this in other docker images as well)

**Comment by HenrikBengtsson** [comment]
Not a formal unit test, but see https://github.com/go-gitea/gitea/issues/2286#issuecomment-339871903 for a manual test that shows how both UID and GID are modified.

**Pull request merged**
