### PR TITLE
Drop Node.js 16 and update js dependencies

### PR DESCRIPTION
**Pull request by harryzcy**
- Drop Node.js 16 since it reached EOL
- Upgrade js dependencies
- Two packages have major version bump
  - `updates`: require node 18
  - `eslint-plugin-array-func`: require `eslint` 8.40.0, which is satisfied
- Run `make svg` for `@primer/octicons` update

### CODE REVIEW

**Comment by lunny** [comment]
Why svgs changed?

**Comment by techknowlogick** [comment]
@lunny because the Octicons dependency was updated

**Review by techknowlogick — APPROVED** [review]

**Review by puni9869 — APPROVED** [review]

**Comment by puni9869** [comment]
🚀 

Backport.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
> Backport

No, not for 1.20.

**Pull request merged**
