### PR TITLE
Fix to reflect selected branch for fork

### PR DESCRIPTION
**Pull request by Bwko**
PullRequestCtx.HeadInfo did not contain the current selected branch causing issue #304

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
Let L-G-T-M work.

**Comment by rbukovansky** [comment]
@lunny @appleboy To be honest, I'm not sure this is correct solution for issue. As I said in #304 it's more like workaround than real solution.

**Comment by lunny** [comment]
@rbukovansky @appleboy if this will not close #304, please reopen it.

**Comment by Bwko** [comment]
I think that this is the correct solution (for now at least), since `ctx.Repo.PullRequest.HeadInfo` == `ctx.Repo.Owner.Name + ":" + ctx.Repo.BranchName`
But the reason why this fails is that the correct branchname gets set  [here](https://github.com/go-gitea/gitea/blob/master/modules/context/repo.go#L437) and `ctx.Repo.PullRequest.HeadInfo` gets set [here](https://github.com/go-gitea/gitea/blob/master/modules/context/repo.go#L317)
A real fix would be to refactor the complete [repo.go](https://github.com/go-gitea/gitea/blob/master/modules/context/repo.go) context, but that's not something that I wanted to do for now since we want to ditch go-macaron in a future release..

Another option is to ditch the `PullRequest.HeadInfo` 
@rbukovansky Correct me if I'm wrong

**Comment by rbukovansky** [comment]
@lunny It closes #304 with workaround I have provided, but as @Bwko says, it's Macaron related, which gitea is trying to get rid off, so in that case it's fine and no need for reopen.

@Bwko I have no idea, if you are wrong or not. I'm no Go developer, just user with some coding skills (C#, Swift), so I was able to find the issue and make a workaround.

**Pull request merged**
