### PR TITLE
Bump CI,Flake and Snap to Node 22

### PR DESCRIPTION
**Pull request by silverwind**
Node 22 is LTS since 2024-10-29. Updated it everywhere.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
Thanks!!

Are you able to do a `nix flake update` as well, or if not then I could.

**Comment by silverwind** [comment]
I don't have `nix` installed and I'm not sure I want to install it (don't want it to take over my system), so if you can, please do.

**Review by lunny — APPROVED** [review]

**Comment by techknowlogick** [comment]
> I don't have `nix` installed and I'm not sure I want to install it (don't want it to take over my system), so if you can, please do.

np, just pushed the patch :)

**Review by 6543 — COMMENTED** [review]
lgtm :)

**Pull request merged**
