### PR TITLE
Upgrade Drone Config to 0.6

### PR DESCRIPTION
**Pull request by bkcsoft**
Do DB-tests in parallel (even though we only have 1 agent for now).

Depends on go-gitea/infrastructure#19

### CODE REVIEW

**Review by appleboy — CHANGES_REQUESTED** [review]
http://docs.drone.io/release-0.6.0-secrets

We need to upgrade secret setting (like `docker_username` and `docker_password`) before upgrading to 0.6 and clear all logs since the log formats are different between 0.5 and 0.6.

**Comment by bkcsoft** [comment]
@appleboy indeed we do 🙂

**Comment by appIeboy** [comment]
@bkcsoft I heard you were quitting

**Comment by lunny** [comment]
replaced by #2362

**Pull request closed without merging**
