### PR TITLE
Fixes a11y behaviour for reaction button and comment options button in an issue view

### LINKED ISSUE #21742: The add reaction button and the comment options button are not accessible in the web view of an issue
### Description

Hello,
In each issue view to the right side of the issue's own comment and for each comment made there is a button to make reactions and another button for other options like reply, cite, etc.
Those buttons use foomantic dropdowns and are processed by the [recently added `aria.js` script](https://github.com/go-gitea/gitea/pull/19861) to make it accessible, but it doesn't work because the html markup is incompatible.

### The particular problem
Steps to reproduce **for a sighted person**:

* Go to any issue with some replies
* Go to any reply or to the post of the issue itself by a sequence of pressing the TAB key
* Iterate to the smiley face icon at the top right of that comment
* Select and press Enter on an emoji

Expected behavior: This reaction is added to the post.
Actual behavior: The reaction menu appears when focusing and it is possible to select items, but when pressing the ENTER key on an emoji nothing happens.

The same happens with the comment options button as well.

Any blind person can't even understand the name of the buttons because they are not labelled with aria.

### The main problem
As a general solution I think [adding](https://github.com/go-gitea/gitea/blob/694441fec5036bf2e5ee6a261b40ada2bfc76d61/web_src/js/features/aria.js#L10) [html markup](https://github.com/go-gitea/gitea/blob/694441fec5036bf2e5ee6a261b40ada2bfc76d61/web_src/js/features/aria.js#L54) [via javascript](https://github.com/go-gitea/gitea/blob/694441fec5036bf2e5ee6a261b40ada2bfc76d61/web_src/js/features/aria.js#L62) is a bad idea because in issues with large threads, the browser performance gets worse in loading as the page length increases. Also, the browser has parsed all the markup and has the corresponding DOM ready when it has to start again to change much part of its structure.
Perhaps for people with powerful machines this is not a big problem, but there is a lower limit thread length for any machine where performance degrades considerably. The better the DOM handling, the higher that lower limit will be.

Therefore, I think it's better to add the semantic aria markup directly to the templates and reserve JavaScript to add only the functionality needed to operate the controls where the markup can't do it on its own. This will also benefit the work of visual designers, as they can understand the meaning of the markup without digging into the JavaScript code.
Also, following this principle always result in better performance: less time to build the DOM, less JavaScript code, less network transfer, less bandwidth used by the server.

I suggest following this principle as a rule of thumb for dealing with a11y semantics (and other similar too).

### A solution

I have developed a [partial fix](https://github.com/go-gitea/gitea/commit/7df8d5f36d74a431a301f9f7a9f620ca0318d183) to make the add reaction button and the comment options button accessible following the principles detailed above, but the problem of colour contrast remains open.
Moreover, the markup used by foomantic dropdowns in Gitea is slightly different to that expected for menu roles, as there is no button assigned to toggle the display of menu options (see https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-links). Instead, the entire div container is assigned the menu role without a control button. A change to add this component I think is much deeper than what is being done here. If I'm wrong about this, please comment.

From now on the `attachOneDropdownAria` function should be replaced by the forked `attachOneDropdownAriaTemplated` function as long as every template behind a foomantic dropdown is being prepared with aria markup.

### Final thought
Is there a lot of [work](https://github.com/go-gitea/gitea/issues/5755) [to be done](https://github.com/go-gitea/gitea/pull/19922) on the Gitea web interface to make it [usable](https://github.com/go-gitea/gitea/issues/20752) for people with visual impairments. Although the perception of the main problem [is apparently different](https://github.com/go-gitea/gitea/issues/16660#issuecomment-1146506509). I have seen more issues than mentioned here analysing the interface for this particular problem.
It is not just a question of functionality of the buttons, is that there are many colour definitions that are not designed to provide the necessary contrast levels for partially sighted people.
Unfortunately, I have not been able to find any report of [the work that accessibility experts are said to have done with Gitea this year](https://github.com/go-gitea/gitea/issues/16660#issuecomment-1014806419). Perhaps they have not finished yet?
So I have probably started to repeat the analysis work done by some people over the last few years on many reported issues.

I hope that suggestions made here are welcome.

Thanks for reading this far.

### Screenshots

Firefox developer accessibility tool focusing add reaction button:
firefox developer accessibility tool focusing add reaction button

Capture of add reaction button with a warning about interactive semantics lack:
add reaction button with a warning about interactive semantics lack

Firefox developer accessibility tools focusing add reaction button with a warning popup:
firefox developer accessibility tools focusing add reaction button with a warning popup

### Gitea Version

dd7f1c0334dff5fb5eb93765dff3b951a9f6b3fc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 106.0.3

### PR DESCRIPTION
**Pull request by fsologureng**
Fixes #21742
* Added aria markup to the add_reaction and context_menu of issue comments templates.
* Added en_US locale text to comment context_menu button name.
* Added divergent and simplified version of attachOneDropdownAria function as attachOneDropdownAriaTemplated for apply to dropdowns made by templates with aria markup. The new function only attach control functionality to the dropdowns.

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thank you so much for this PR <3, I haven't tested it yet, but the CI is failing on some linting issues.

I copied the linting report below, but the originial can be found on [drone](https://drone.gitea.io/go-gitea/gitea/63010/1/4). They follow the format: Line number, column, whether it is an error or a warning, a description, and finally an error code.
```
/drone/src/web_src/js/features/aria.js
   99:3   error    Expected an assignment or function call and instead saw an expression         no-unused-expressions
   99:21  warning  Unexpected console statement                                                  no-console
   99:33  error    Unexpected string concatenation                                               prefer-template
   99:68  error    Operator '+' must be spaced                                                   space-infix-ops
  107:5   error    Expected an assignment or function call and instead saw an expression         no-unused-expressions
  109:9   error    '$active' is never reassigned. Use 'const' instead                            prefer-const
  110:5   error    Expected space or tab after '//' in comment                                   spaced-comment
  117:5   error    Expected an assignment or function call and instead saw an expression         no-unused-expressions
  117:23  warning  Unexpected console statement                                                  no-console
  117:35  error    Unexpected string concatenation                                               prefer-template
  117:45  error    Operator '+' must be spaced                                                   space-infix-ops
  123:5   error    Closing curly brace does not appear on the same line as the subsequent block  brace-style
```

**Review by techknowlogick — APPROVED** [review]
Thanks again <3

**Comment by wxiaoguang** [comment]
TBH, I agree to improve the a11y. But the current approach doesn't look good to me. The code is just copied twice. I do not see a strong reason that why the old code couldn't be reused.

* The performance: `attachOneDropdownAria` only changes the attributes which don't affect layout or rendering, so it could be fast enough.
* For the worry that `attachOneDropdownAria` changes the DOM structure and it's slow: I think it's not a real problem. The `attachOneDropdownAria` also updates `id` and `aria-controls`. I do not see how the new function `attachOneDropdownAriaTemplated` make `$dropdown.attr('aria-activedescendant', $active.attr('id'));` work. I doubt that some screen readers may not work properly without these IDs.
* From a development view, I do not think it's easy to make every developer(contributor) understand a11y clearly and write all dropdown elements with correct aria-attributes. In the end, `attachOneDropdownAria` is still widely used and it is a general solution, then `attachOneDropdownAriaTemplated` will become a one-time code just for the reactions.

**Comment by fsologureng** [comment]
> TBH, I agree to improve the a11y. But the current approach doesn't look good to me. The code is just copied twice. I do not see a strong reason that why the old code couldn't be reused.

Thanks for the review.
Actually, there is no compelling reason, it was just a proposal, would you prefer a sub-function dedicated only to adding control functionality? I'm open to doing it this way, but the proposed approach (probably poorly phrased, my fault) is not to leave 2 functions in production, but to make the whole change to the templates associated to the dropdowns so that only one remains.

> 
>     * The performance: `attachOneDropdownAria` only changes the attributes which don't affect layout or rendering, so it could be fast enough.

The aria tree works as a layout too. Feel free to read some aspects in https://marcysutton.com/accessibility-and-performance

> 
>     * For the worry that `attachOneDropdownAria` changes the DOM structure and it's slow: I think it's not a real problem. The `attachOneDropdownAria` also updates `id` and `aria-controls`. I do not see how the new function `attachOneDropdownAriaTemplated` make `$dropdown.attr('aria-activedescendant', $active.attr('id'));` work. I doubt that some screen readers may not work properly without these IDs.

Yes, it's my fault. In my haste I oversimplified the changes, I had made the addition of the ID to the templates, but in the end I made a reversal forgetting that action. Thanks for the review, I'll fix it. It won't work as it is.

> 
>     * From a development view, I do not think it's easy to make every developer(contributor) understand a11y clearly and write all dropdown elements with correct aria-attributes, and Fomantic UI Dropdown is quite special. In the end, `attachOneDropdownAria` is still widely used and it is a general solution, then `attachOneDropdownAriaTemplated` will become a one-time code just for the reactions. Then why not just keep one `attachOneDropdownAria`?

As I wrote above, that is the main idea.

> 
> 
> Just my opinion, not a blocker (if the code works)

Thank you (It needs a fix for the IDs)

**Comment by techknowlogick** [comment]
@fsologureng mind if I send you an email to the one listed in your commits?

**Comment by silverwind** [comment]
Latest merge seems to have gone wrong.

**Comment by lafriks** [comment]
I think something is broken with this PR branch 🤔

**Comment by fsologureng** [comment]
Closed in favor of https://github.com/go-gitea/gitea/pull/21964

**Pull request closed without merging**
