### PR TITLE
Bugfix: Align comment label and actions to the right

### PR DESCRIPTION
**Pull request by saitho**
Just noticed that the class "right" set for the comment label and actions is not applied correctly.
That is because of the wrapping flexbox. This fix aligns the comment label (if it has one) and the actions (edit, delete) to the right via flexbox.

**That's how it will look like:**
screen

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
Are you able to provide a screenshot of what it looks like after your changes have been applied?

**Comment by saitho** [comment]
> Are you able to provide a screenshot of what it looks like after your changes have been applied?

That's the screenshot at the top. :)

**Comment by lafriks** [comment]
Is screenshot fixed version? If so that bubble kind of thingy is way off, it should be to the right form user avatar not left

**Review by lafriks — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by saitho** [comment]
Ah, right. Shouldn't have removed `position: relative;` in header. :D

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Can you update screenshot?

**Comment by saitho** [comment]
Updated

**Review by adelowo — APPROVED** [review]

**Pull request merged**
