### PR TITLE
Add API to list tags

### PR DESCRIPTION
**Pull request by lunny**
~blocked by https://github.com/go-gitea/go-sdk/pull/139~

~blocked by https://github.com/go-gitea/git/pull/143~

### CODE REVIEW

**Review by kolaente — CHANGES_REQUESTED** [review]
Please generate swagger docs.

**Comment by lunny** [comment]
should fix #5693

**Review by techknowlogick — CHANGES_REQUESTED** [review]
Please add API tests

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
@kolaente need your approval

**Review by sapk — APPROVED** [review]

**Review by kolaente — APPROVED** [review]

**Pull request merged**
