### PR TITLE
Fix comment API paths

### PR DESCRIPTION
**Pull request by ethantkoenig**
Corrects the following comment API routes
- `PATCH /:owner/:repo/issues/:index/comments/:id` -> `PATCH /:owner/:repo/issues/comments/:id`
- `DELETE /:owner/:repo/issues/:index/comments/:id` -> `DELETE /:owner/:repo/issues/comments/:id`

The previous routes ignored the `:index` parameter, and were in conflict with [the Github API](https://developer.github.com/v3/issues/comments/). The previous route are marked as deprecated, but have not been removed.

### CODE REVIEW

**Comment by lafriks** [comment]
Can we create new v3 API route group for all these breaking changes?

**Comment by ethantkoenig** [comment]
@lafriks IMO, that seems like overkill. I doubt that fixing a few broken routes will cause much disruption.

**Comment by lafriks** [comment]
If we are sure no tool is using it I'm ok with that

**Comment by ethantkoenig** [comment]
@lafriks I'm not aware of any such tool, but of course I can't guarantee that no such tool exists.

**Comment by bkcsoft** [comment]
Well, any way to know if it'll break things is to do it and see if anyone complains :trollface: 

LGTM

**Comment by ethantkoenig** [comment]
@lafriks Instead of removing the old, incorrect routes, I've marked them as deprecated. This PR is no longer breaking.

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
