### PR TITLE
go version should be at least 1.16 because of `io.Discard`(Since Go 1.16, Feb 2021)…

### PR DESCRIPTION
**Pull request by wxiaoguang**
Currently the go version is `1.14` in `go.mod`, actually there are many usage of `io.Discard`(Since Go 1.16, Feb 2021) in code

image

So go version should be at least 1.16 now. And `README.md` is also updated.

### CODE REVIEW

**Comment by 6543** [comment]
@wxiaoguang Discard do work with 1.14 any moints in bumping requirement?

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@6543 we've already defined 1.16 as minimum, so it is good to have it in the places defined in this PR

**Comment by 6543** [comment]
oh yes that one dep.

**Review by 6543 — APPROVED** [review]

**Comment by kpfleming** [comment]
The release notes for Gitea 1.15.0 say that Go 1.15 or later is required, but this PR made the requirement 1.16 or later.

**Comment by zeripath** [comment]
* It's not this PR that's responsible but #16710

DAMN we should have updated the changelog at that point.

Realistically we can't support 1.15 as upstream projects like golang-jwt/jwt will not support out-of-support golang versions - and will not even attempt to provide security fixes for them.

I agree its not great but as 1.15 was released after the end of life for go 1.15 I don't think we can say we can support 1.15.

(If you really need to use go 1.15 the source for Gitea code will compile with go 1.15 if you change the Makefile.)

**Comment by zeripath** [comment]
I've put up a PR to update/fix the blog https://gitea.com/gitea/blog/pulls/171

**Comment by kpfleming** [comment]
I'm good,  I upgraded to Go 1.17 and Gitea 1.15 is working great (and quite a bit faster than 1.14 was when built with Go 1.15).

**Comment by zeripath** [comment]
> quite a bit faster than 1.14 

This is no accident, I (and lunny) have sent substantial numbers of PRs to improve speed. The one most likely responsible for your experience improvement is #16059.

**Pull request merged**
