### PR TITLE
Macaron 1.5

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by lafriks** [comment]
Compilation seems to fail

**Comment by techknowlogick** [comment]
Macaron now supports HTTP/2 Push mode and so gitea.com/macaron/gzip will need to implement the Push method. I've pushed a branch which may become a PR soon to that repo.

**Comment by techknowlogick** [comment]
Blocked by https://gitea.com/macaron/gzip/pulls/3

**Comment by lafriks** [comment]
@techknowlogick https://gitea.com/macaron/gzip/pulls/3 merged

**Review by mrsdizzie — APPROVED** [review]

**Pull request merged**
