### PR TITLE
Improve visibility of "Pending" indicator

### PR DESCRIPTION
**Pull request by guillep2k**
I sometimes forget to use the "Finish Review" button after adding some comments, so enhancing the visibility of the "Pending" indicator seemed like a good idea.

### Before

image

### After

image

### CODE REVIEW

**Comment by guillep2k** [comment]
I'm not sure if I should also change the dark color theme, or how/where to do it:

image

**Comment by jolheiser** [comment]
My favorite part is actually the `margin-left` 😉

**Comment by lafriks** [comment]
Maybe yellow could be a bit less so yellow? :)

**Comment by guillep2k** [comment]
> 
> 
> Maybe yellow could be a bit less so yellow? :)

@lafriks Of course. I've just used the yellow from the preview box. You mean for the base theme, right?

**Comment by guillep2k** [comment]
A new yellow.

image

image

**Review by lunny — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
