### PR TITLE
api: fix overly strict permissions on  edit PR

### LINKED ISSUE #14025: [API] Edit PR has wrong permission model
- Gitea version (or commit ref): 1.14.0+dev-374-g287b59480

## Description
Users may want to close their pull request via API.
To do so, currently only `PATCH /repos/{owner}/{repo}/pulls/{index}` is available.
This API is enabled only for repo owners, meaning a PR author gets `403 Forbidden`, even if they only update the `state` field.

Either make the permission check more granular, or add a separate API to open/close PRs.

~~I believe the same applies for Issues (`PATCH /repos/{owner}/{repo}/issues/{index}`), but I didn't verify~~
This problem does not apply to the matchin issues endpoint

### PR DESCRIPTION
**Pull request by noerw**
We can drop this overly strict permission requirement, as the more granular check (`IsIssuePoster`) is done in `repo.EditPullRequest()`

fixes #14025

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]

**Comment by lunny** [comment]
> We can drop this overly strict permission requirement, as the more granular check (`IsIssuePoster`) is done in `repo.EditPullRequest()`
> 
> fixes #14025

I think we just missed Poster, but the original permission check should be also there.

**Comment by noerw** [comment]
@lunny I can't follow, how would you do it instead? :)

Adding a new middleware `reqIssueEditor()` in `api.go` implementing the same checks as `EditPullRequest()` would be loads of duplicated code, as well as duplicated work during each request 🤔

**Comment by lunny** [comment]
Just change `reqIssueEditor` since Poster should have permission to edit the issue or pull request.

**Comment by 6543** [comment]
The permission is checked in the func itselve again ...

**Comment by noerw** [comment]
Here is an alternative implementation, that does the additional permission check via middleware: https://github.com/go-gitea/gitea/compare/main...noerw:fix-14025-variant2
Running some local benchmarks, there is no significant cost induced by the duplicate checks (before 105ms, after 110ms avg request time). Though this request time seems quite high in general, but that's another story ;)

**Comment by 6543** [comment]
-> #16081

**Pull request merged**
