### PR TITLE
feat: highlight issue references with :

### PR DESCRIPTION
**Pull request by grinat**
I changed regex pattern for highlight external bug tracker issue which contains : 
e.g.: "feat: TCP-100: my commit msg"
e.g.: "feat: #100: my commit msg"

before:
c5f18495af

after:
e568452f0a

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by mrsdizzie — CHANGES_REQUESTED** [review]
Thank you for the PR!

Can you add a few quick test cases to the existing set so this change won't get lost in the future:

If not familiar probably in these two spots:

 https://github.com/go-gitea/gitea/blob/85f56546c4259ed9c11d31973344228ad667084e/modules/markup/html_internal_test.go#L348

 https://github.com/go-gitea/gitea/blob/85f56546c4259ed9c11d31973344228ad667084e/modules/markup/html_internal_test.go#L234

and maybe

https://github.com/go-gitea/gitea/blob/85f56546c4259ed9c11d31973344228ad667084e/modules/markup/html_internal_test.go#L104

So just add an example or two that use a ```:```

Also can you update the regex here:

 https://github.com/go-gitea/gitea/blob/85f56546c4259ed9c11d31973344228ad667084e/models/action.go#L68

Just so it is consistent for now

**Review by mrsdizzie — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM bot

**Comment by lunny** [comment]
If we think it's a bug, maybe we should send it to v1.9 also.

**Comment by lafriks** [comment]
Please send backport to release/1.9 branch

**Pull request merged**
