### PR TITLE
Use docs.gitea.com instead of docs.gitea.io

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by silverwind** [comment]
Those 5 cases in translation should ideally be moved to `printf` solutions so the URL can be moved out.

**Comment by lunny** [comment]
> Those 5 cases in translation should ideally be moved to `printf` solutions so the URL can be moved out.

I just leave those to other PRs because there maybe different idea about how to move the URL out of translation.

**Comment by puni9869** [comment]
@lunny where we can see the dev version of `docs`, can we deploy it to dev environment. I want to give a try to this change.

**Comment by lunny** [comment]
> @lunny where we can see the dev version of `docs`, can we deploy it to dev environment. I want to give a try to this change.

It's a good question, I think it's impossible currently to do that. Maybe a PR could copy some scripts from https://gitea.com/gitea/gitea-docusaurus

**Comment by puni9869** [comment]
> > @lunny where we can see the dev version of `docs`, can we deploy it to dev environment. I want to give a try to this change.
> 
> It's a good question, I think it's impossible currently to do that. Maybe a PR could copy some scripts from https://gitea.com/gitea/gitea-docusaurus

Thanks, thats what I want.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
> > @lunny where we can see the dev version of `docs`, can we deploy it to dev environment. I want to give a try to this change.
> 
> It's a good question, I think it's impossible currently to do that. Maybe a PR could copy some scripts from https://gitea.com/gitea/gitea-docusaurus

Maybe we can have a `make docs-preview` that clones the docasaurus repo into a subdirectory, builds it in dev mode and then hosts it on a local port (3001?).

**Review by puni9869 — APPROVED** [review]

**Comment by puni9869** [comment]
> > > @lunny where we can see the dev version of `docs`, can we deploy it to dev environment. I want to give a try to this change.
> > 
> > 
> > It's a good question, I think it's impossible currently to do that. Maybe a PR could copy some scripts from https://gitea.com/gitea/gitea-docusaurus
> 
> Maybe we can have a `make docs-preview` that clones the docasaurus repo into a subdirectory, builds it in dev mode with live reload and then hosts it on a local port (3001?).


That will work too, but `docs/` should be in `.gitignore`.

**Pull request merged**
