### PR TITLE
packages: Calculate package size quota using package creator ID instead of owner ID

### PR DESCRIPTION
**Pull request by ghost**
Changed behavior to calculate package quota limit using package `creator ID` instead of `owner ID`.

Currently, users are allowed to create an unlimited number of organizations, each of which has its own package limit quota, resulting in the ability for users to have unlimited package space in different organization scopes. This fix will calculate package quota based on `package version creator ID` instead of `package version owner ID` (which might be organization), so that users are not allowed to take more space than configured package settings. 

Also, there is a side case in which users can publish packages to a specific package version, initially published by different user, taking that user package size quota. Version in fix should be better because the total amount of space is limited to the quota for users sharing the same organization scope.

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
I don't think this is right. Every user/org should have their package size quota. What we should do is to limit org's package size but not creators'.

**Comment by 6543** [comment]
hmm we dont have a org setting to limit right now ... so the fix is good.

but I agree that a long term solution should be to have orgs own limits

**Comment by KN4CK3R** [comment]
This should be reverted. If you use CI with bot users the quota limit is never reached for a user. A solution could be to have different quotes for owner and creator. Now the description of the ini setting is wrong too.

**Comment by SaintJacques** [comment]
🔥

**Pull request merged**
