### PR TITLE
Change parsing of postgresql settings

### LINKED ISSUE #4200: passwords with spaces seem to fail?
- Gitea version (or commit ref): 1.4.2
- Git version:
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If your postgres password contains a space, gitea will not install.

## Screenshots

image

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #4200

### CODE REVIEW

**Comment by lunny** [comment]
@techknowlogick could you add some tests?

**Review by jonasfranz — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@lunny I don't see how tests could be added for this

**Review by sapk — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lafriks / @lunny I could create a new function (similar to `parsePostgreSQLHostPort`) for generating postgres connection strings and test various variables for that. 

I have a couple of hours until I can get started on that, but that's what I was thinking. Let me know what you think.

**Comment by techknowlogick** [comment]
I pushed the function and now this is still pending tests.

**Comment by techknowlogick** [comment]
Ok. Tests added, and I know this already has 2 LG-TM, but I will wait for another merger/owner to merge this.

**Pull request merged**
