### PR TITLE
Fix repo_index_status lingering when deleting a repository

### LINKED ISSUE #7703: Deleting a repo does not delete repo_index
- Gitea version (or commit ref): v1.9.0
- Git version: 2.22.0
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

The function DeleteRepository() at models/repo.go doesn't delete repo indexes.
```
func DeleteRepository(doer *User, uid, repoID int64) error {
}
```

To reproduce:
- Configure your installation to create repo indexes.
- Create a repository with default README.md and .gitignore.
- Edit README.md and add enought text so at least some of it goes into the repo_index. For instance, I've added:
```
int WinMain(int argc, char* argv[])
{
}
```
- Make sure the index was created, and run the following query in the database:
```
gitea=# select r.id, r.name, i.commit_sha, s.sha, s.description
from repo_indexer_status i full outer join repository r on i.repo_id = r.id
left outer join commit_status s on s.repo_id = r.id order by r.id;
 id |           name           |                commit_sha                | sha | description
----+--------------------------+------------------------------------------+-----+-------------
 63 | repoindextest            | 6186ba7ae6d27769ac4e1da50ec25622ea13adbb |     |
(1 row)
```
- Delete the repository from Gitea using the GUI (or API too, I guess).
- Run the query in the database again:
```
gitea=# select r.id, r.name, i.commit_sha, s.sha, s.description
from repo_indexer_status i full outer join repository r on i.repo_id = r.id
left outer join commit_status s on s.repo_id = r.id order by r.id;
 id |           name           |                commit_sha                | sha | description
----+--------------------------+------------------------------------------+-----+-------------
    |                          | 6186ba7ae6d27769ac4e1da50ec25622ea13adbb |     |
(1 row)
```

As you see, there's an orphaned record in repo_indexer_status. Probably in the index itself.

### PR DESCRIPTION
**Pull request by guillep2k**
Fix #7703

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
This should probably need also migration to delete old data

**Comment by guillep2k** [comment]
> 
> 
> This should probably need also migration to delete old data

@lafriks What's the usual procedure in these cases? Should I'd add something to models/migrations?

**Comment by lafriks** [comment]
@guillep2k yes, check out https://github.com/go-gitea/gitea/pull/6068/files for sample

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k yes, check out https://github.com/go-gitea/gitea/pull/6068/files for sample

@lafriks Done in #7746.

**Pull request merged**
