### PR TITLE
Implement FSFE REUSE for golang files

### LINKED ISSUE #16132: Adopt REUSE best practices to clarify copyright and licensing
## Description

I suggest that Gitea becomes [REUSE](https://reuse.software) compliant. That would mean that every file in this repository is unambiguously marked with its copyright and licensing information. It would be a good timing to do so since the FSFE (heavy Gitea user itself) is currently [offering projects some help in adopting these best practices](https://reuse.software/booster/).

Gitea is distributed under MIT and a very popular project. So it is likely that developers may reuse whole files or parts of them in their own projects. That's completely fine, but it's beneficial if information about their license and copyright is retained in this step. 

Especially if some files are under a different license (e.g. Creative Commons) it's important to be aware of this to avoid a license violation. On a quick search I found that some files under `vendor/` are licensed under Apache-2.0, e.g. from [mongodb](https://github.com/go-gitea/gitea/tree/main/vendor/go.mongodb.org/mongo-driver) and [opentelemetry](https://github.com/go-gitea/gitea/tree/main/vendor/go.opentelemetry.io/otel). The whole `vendor` section might be the most difficult one to make REUSE compliant as it contains 3rd-party code for which editing license and copyright information should be avoided.

That is why external help is probably a good idea :)

### PR DESCRIPTION
**Pull request by flynnnnnnnnnn**
fixes #16132

### CODE REVIEW

**Comment by flynnnnnnnnnn** [comment]
I only changed comments, can someone help explain why CI is failing?

**Comment by jolheiser** [comment]
The errors in the CI should point them out, but for example https://github.com/go-gitea/gitea/pull/21840/files#diff-52617ef219e61332d7bc880cd52ab7f34e21fb813040907db1c210837ccc3e95

It looks like whatever you used to mass-replace also broke some of the package statements.

**Comment by flynnnnnnnnnn** [comment]
Thank you @jolheiser. My find replace was on an exact string, but there were some lines that had extra text it was not commented any longer.

**Comment by flynnnnnnnnnn** [comment]
@jolheiser I have fixed the tests so they now pass.

**Review by zeripath — APPROVED** [review]
I guess if this is the way that the OSS ecosystem is going then we should do this.

**Review by delvh — APPROVED** [review]
(I'm terribly sorry, GitHub, for DDOsing you with JS requests only to notice afterward that there were much easier options available…)

**Comment by zeripath** [comment]
make lgtm work

**Comment by zeripath** [comment]
OK this is going to take some work to ensure that we remain compliant as we go forward. This means that we should probably add a REUSE compliance check to gitea check

**Comment by jolheiser** [comment]
Was just about to post we should add this to our vet check

**Pull request merged**
