### PR TITLE
no global var

### PR DESCRIPTION
**Pull request by 6543**
last missing nit from #17919

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
What's wrong with the global variable?

**Comment by 6543** [comment]
It's only used inside the function - it should never be global!!!

**Comment by wxiaoguang** [comment]
Then you should also remove the `if supportedDbTypeNames == nil {`

**Comment by 6543** [comment]
in general we should avoid global vars if possible

they produce races, consume resources not needed after exec of code parts mostly ...

**Comment by wxiaoguang** [comment]
> in general we should avoid global vars if possible
> 
> they produce races, consume resources not needed after exec of code parts mostly ...

As comments before, it's just a install page, no race there. And it only consumes 8 bytes (a pointer) memory. Just one request consume much much more than that .... Personally I won't put too many loops in the common Context construction. Indeed there is no problem to remove the cache if you like to.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
After grep-ing `^var ` in *.go, I found some more global variables, like this (ps: there is a bug that the ctx is not used ....)

Maybe it's worth to do some clean up in the project.

image

**Comment by silverwind** [comment]
There still may be a performance benefit of keeping these top-level variables in case their instantiation is expensive. For example, I like to put regexes in top level.

**Comment by wxiaoguang** [comment]
`regex` vars can be kept, while `supportedDbTypeNames` and `delRepoArchiver` etc can be removed safely.

**Comment by wxiaoguang** [comment]
For the `supportedDbTypeNames`, I made another fix, move it from global to local and still cache the slice. And there is another fix for the installation page, need 👀

* #19291

**Pull request closed without merging**
