### PR TITLE
Upgrade binding to fix bug

### LINKED ISSUE #30518: Update failed if the `website` field is carried, when requesting `/user/settings` interface.
### Description

The request is:

`curl -X 'PATCH' \
  'https://172.16.161.221:8080/api/v1/user/settings' \
  -H 'accept: application/json' \
  -H 'authorization: Basic cm9vdDp6ZHd3QDIwMjQ=' \
  -H 'Content-Type: application/json' \
  -d '{
  "description": "",
  "location": "",
  "language": "zh-CN",
  "theme": "auto",
  "full_name": "root",
  "diff_view_style": "",
  "hide_email": true,
  "hide_activity": false,
  "website": "gitea.com"
}'`

The result is:

image

Is the parameter value wrong or  Is it a bug?

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #30518

### CODE REVIEW

**Comment by delvh** [comment]
> Error:      	Not equal: 
  expected: 201
  actual  : 500
  Test:       	TestAPICreateAndDeleteUser
  Messages:   	Request: POST /api/v1/admin/users?token=f666b394cc0438ee3394d60d55a3d5a69a75b0ab

Sounds related

**Review by techknowlogick — APPROVED** [review]

**Review by techknowlogick — DISMISSED** [review]
Ci Fail related

**Comment by yp05327** [comment]
https://gitea.com/go-chi/binding/pulls/17

**Comment by lunny** [comment]
Upgrade chi binding in a55c51051e661125dec4583ba22801d7a2821a20

**Review by yp05327 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Pull request merged**
