### PR TITLE
Fix "Error: No issue number specified"  when pushing

### PR DESCRIPTION
**Pull request by agrn**
This patch fixes issue #1111

### CODE REVIEW

**Comment by andreynering** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@agrn could make an empty force push to this PR to let drone work?

**Comment by agrn** [comment]
OK, did it

**Comment by lunny** [comment]
@agrn could you backport this to branch release/v1.1 ?

**Comment by agrn** [comment]
I included #1220 in the PR as it's also part of the bugfix.

**Pull request merged**
