### PR TITLE
Bindata is optional and over-writable on restart

### PR DESCRIPTION
**Pull request by tboerger**
Generally it already works pretty good with or without the `bindata` build flag, but since I have also dropped the bindata for the `app.ini` I have to make sure that all required default attributes for the config are set. This currently not the case but feel free to review the rest of the PR until I can finish the configuration issue.

### CODE REVIEW

**Comment by strk** [comment]
Was the `conf/` -> `options/` indispensable ? `Files changed: 233` is a scary message for any reviewer

**Comment by bkcsoft** [comment]
@strk not really that hard to review 😂 
2016-12-12-232852_1916x1036_scrot

**Comment by bkcsoft** [comment]
LGTM

**Comment by andreynering** [comment]
Trusted LGTM

**Comment by tboerger** [comment]
Resolved conflicts.

**Comment by lunny** [comment]
How should I test this PR?

**Comment by tboerger** [comment]
Just checkout the PR and execute `TAGS="bindata sqlite" make clean generate build && cp gitea ~/gitea`, than switch the CLI into your home directory and execute `./giteaweb`, this should result in that:

```
# ./gitea web
2016/12/22 18:23:06 [W] Custom config '/Users/thomas/custom/conf/app.ini' not found, ignore this if you're running first time
2016/12/22 18:23:06 [T] Custom path: /Users/thomas/custom
2016/12/22 18:23:06 [T] Log path: /Users/thomas/log
2016/12/22 18:23:06 [I] Gitea v0.9.99+467-g08e6ed0
2016/12/22 18:23:06 [I] Log Mode: Console(Trace)
2016/12/22 18:23:06 [I] Cache Service Enabled
2016/12/22 18:23:06 [I] Session Service Enabled
2016/12/22 18:23:06 [I] SQLite3 Supported
2016/12/22 18:23:06 [I] Run Mode: Development
2016/12/22 18:23:06 [I] Listen: http://0.0.0.0:3000
[Macaron] 2016-12-22 18:23:09: Started GET /install for [::1]
2016/12/22 18:23:09 [D] Session ID: 47b6b1ca45a04486
2016/12/22 18:23:09 [D] CSRF Token: aciiI_3qaSnUPF6wmjlm3hokcgc6MTQ4MjQyNzM4OTUxMzI4ODQzMA==
2016/12/22 18:23:09 [D] Template: install
[Macaron] 2016-12-22 18:23:09: Completed /install 200 OK in 54.47042ms
[Macaron] 2016-12-22 18:23:09: Started GET /img/favicon.png for [::1]
[Macaron] [Static] Serving /img/favicon.png
[Macaron] 2016-12-22 18:23:09: Completed /img/favicon.png 200 OK in 4.300748ms
```

**Pull request merged**
