### PR TITLE
Improve CSV rendering

### PR DESCRIPTION
**Pull request by silverwind**
Before:

Screenshot 2024-03-06 at 21 42 17

After:
Screenshot 2024-03-06 at 21 41 58

### CODE REVIEW

**Comment by delvh** [comment]
How is removing the `even-odd` distinction an improvement?

**Comment by delvh** [comment]
But yeah, the single border looks good.

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
> How is removing the `even-odd` distinction an improvement?

Just following Github style where they even-odd only in markdown, not csv.

**Comment by delvh** [comment]
That's one of the cases where I think it makes more sense to deviate from GitHub then.
After all, there is a reason for the different highlighting:
It helps the user keep track which row they are in.

**Comment by silverwind** [comment]
I really don't like it visually there. Excel also does not do it 😆.

**Review by KN4CK3R — COMMENTED** [review]
OK for me because the csv preview is not intended to display files with 10/20/... columns. For a moderate number of colums even/odd should not be needed.

**Review by KN4CK3R — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

**Comment by denyskon** [comment]
@delvh Do you block?

**Review by delvh — APPROVED** [review]
No.
But I don't like it either.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
