### PR TITLE
Add Dockerfile for running tests in container

### PR DESCRIPTION
**Pull request by Morlinest**
I've created Docker container to be able do tests on my local machine with Windows (but can be used on any platform) using Docker for Windows. I hope it can be helpful for someone else too.

### Build image
```
$ docker build -f Dockerfile.tests -t gitea-tests .
```
### Run image (only once, container is removed after finish)
```
$ docker run -ti --rm \
-e BRANCH=fix/missing-collaborative-repositories \
-e REPOSITORY=https://github.com/Morlinest/gitea.git \
gitea-tests
```
### Run image (first time clone repo, then just pull changes)
```
# First run
$ docker run -ti --name gitea-test \
-e BRANCH=fix/missing-collaborative-repositories \
-e REPOSITORY=https://github.com/Morlinest/gitea.git \
gitea-tests
```
```
# Second and next runs
$ docker start -i gitea-test
```
```
# See all run tests
$ docker logs gitea-test
```
You can run multiple containers with different names (`--name <my-super-branch-name>`) for each branch and run tests independently.

## Output example:
image

### CODE REVIEW

**Comment by lafriks** [comment]
Can this be done without cloning but mapping local gitea directory to docker?

**Comment by daviian** [comment]
In my current setup on Windows I use WSL for `make test` and for the integration tests you can use the already existing `Dockerfile`. Works pretty good for me ;-)

EDIT: sorry not the exsting one, but the webhippie/golang from the `make build` cmd. Just change the make command at the end.

**Comment by Morlinest** [comment]
@lafriks Not on windows, I think there is problems with CRLF and some others maybe.

**Comment by Morlinest** [comment]
@daviian Thanks for sharing, it is way to go too. I don't use WSL. It is possible solution just for someone who has met prerequisites `64-bit version of Windows 10 Anniversary Update or later (build 1607+)`. Also this is more general solution in my opinion.

**Comment by Morlinest** [comment]
@lafriks Added option to mount directory with source to `/gitea-src` (by default, can be changed by `LOCAL_REPOSITORY` env variable). Any branch can be used

On my PC it is as simple as
```
docker run -ti --rm -v c:/Users/Morli/Projects/Go/src/code.gitea.io/gitea:/gitea-src:ro gitea-test
```
or 
```
# First run
docker run -ti -v c:/Users/Morli/Projects/Go/src/code.gitea.io/gitea:/gitea-src:ro --name gitea-tests-master gitea-test
# Repeat tests after local change
docker start -i gitea-tests-master
```

**Comment by daviian** [comment]
Just for the sake of completeness I post my current solution in detail.
My current command is nearly as long as when using the new Dockerfile and uses the existing golang container from webhippie aka @tboerger (if I am right)

`docker run -i --rm -v D:\Development\go\src\code.gitea.io\gitea:/srv/app/src/code.gitea.io/gitea -w /srv/app/src/code.gitea.io/gitea --link gitea-pgsql-db:pgsql -e TAGS="bindata" webhippie/golang:edge make build test-pgsql`

Advantage of this one is that it is easily changed to unit tests by altering the make command at the end.
As you can see I use a separate docker container for my databases, which can be easily started after first run by calling `docker restart gitea-pgsql-db` and exchanged with mysql or mssql.

**Comment by Morlinest** [comment]
@daviian Thanks for sharing.

Your solution has no advantage over mine, as you can use any command with it too. `make test` is only default command so you dont need to write it everytime you want to start new container. Also, using another container for DB is same in both solutions (I am using it that way, but without deprecated legacy `--link` option - using custom network `--net gitea`).

Disadvantage of your solution is that it is not working on windows (Docker for Windows), where (or anywhere else) crlf endings is used in files. That's why I have to clone repository instead of just directly using folder or copying it.

Another thing is dependency on someone's custom image you don't know anything about (in this particular example you know who creted it and see Docker file, but...), has some general purpose and you can't change it.

Edit: + you can test any branch without checking it out on your host machine (if using mounted directory) or using branch from any remote repository.

**Comment by tboerger** [comment]
Why so complicated? Just install the drone cli binary and execute `drone exec`, than you can have the same behavior as on drone.

**Comment by lafriks** [comment]
@tboerger I don't think you can do it on windows

**Comment by tboerger** [comment]
@lafriks you can, with docker for windows and the cli binary for windows which also gets published

**Comment by bkcsoft** [comment]
I'm with @tboerger on this one, having a separate Dockerfile for this seems odd

**Comment by Morlinest** [comment]
@tboerger @bkcsoft How you add local repository to your container?

**Comment by bkcsoft** [comment]
I build the container and tell it to run `make test` :)

**Comment by Morlinest** [comment]
@bkcsoft Not a good answer :D Will you mount directory to it? If yes, will container do any operation with it like copying, clonnig?

Edit: And you can build image, not a container :D

**Comment by lunny** [comment]
@tboerger @bkcsoft maybe we could add some documents for contributors about how to write and run tests.

**Comment by tboerger** [comment]
Just use http://docs.drone.io/cli-exec/, if you are executing it without `--local=false` it will mount the source via volume into the pipeline.

**Comment by Morlinest** [comment]
@tboerger Only mounting volume is not enough. On Windows I am using crfl for line endings, it will fail on linux if you just mount directories. That's why I've added this Dockerfile. I just want to share my solution of problem I've encountered.

**Comment by daviian** [comment]
@Morlinest Mounting volume on Windows works fine at least for me.

**Comment by Morlinest** [comment]
@daviian I can mount directory, but my cloned git has incopatible line endings for linux. Maybe I am doing something wrong, don't know :) I am happy with my gitea testing image.

**Comment by tboerger** [comment]
It's ok that you are happy with it like it is, but the suggested way is to use Drone CLI.

**Comment by tboerger** [comment]
Beside that you are using a totally different image than our CI or Docker images and it's definitily using best practices for Docker.

**Pull request closed without merging**
