### PR TITLE
[WIP] Add more indices to action table for speed improvements

### PR DESCRIPTION
**Pull request by 6543**
without this a instance i do administrate run into timeout on try to load the landing page (when logged in) (sqlite).

and with mariadb the loading times of that page drop from 22s to 0.08s.

---
*Sponsored by Kithara Software GmbH*

### CODE REVIEW

**Comment by wxiaoguang** [comment]
TBH, this change doesn't look good to me.

1. It needs a migration
2. Most `xorm: INDEX` should be deleted, only keep `CreatedUnix INDEX`
3. I think `actDashboardIndex.AddColumn("repo_id", "created_unix")` should have the same result, while it makes smaller index data

**Comment by 6543** [comment]
well I do have real world data witch shows me that this fix it ...
... and xorm.Sync do autmatically generate or delete indexes

**Comment by 6543** [comment]
the query ```SELECT `action`.* FROM `action` INNER JOIN `repository` ON `repository`.id = `action`.repo_id WHERE user_id=? AND is_deleted=? ORDER BY `action`.`created_unix` DESC LIMIT 50``` is the exact cause of the issue ... if it helps you

**Comment by 6543** [comment]
my manaull workaround is to exec: `CREATE INDEX test_comb_1 ON action (repo_id,user_id,is_deleted,created_unix);` after gitea has started

**Comment by wxiaoguang** [comment]
> well I do have real world data witch shows me that this fix it ...

I totally agree that this change could fix, but it doesn't seem right.



> the query `` SELECT `action`.* FROM `action` INNER JOIN `repository` ON `repository`.id = `action`.repo_id WHERE user_id=? AND is_deleted=? ORDER BY `action`.`created_unix` DESC LIMIT 50 `` is the exact cause of the issue ... if it helps you

For such query, it needs index `repo_id, user_id, is_deleted, created_unix`, but not what you proposed in this PR.

**Comment by wxiaoguang** [comment]
> ... and xorm.Sync do autmatically generate or delete indexes

I am not xorm expert, but IIRC every database change requires a migration. Maybe it should be clarified: to follow it or not. If not follow, whether there will be anything wrong.

**Comment by lunny** [comment]
We should remove all wrongly added `index` after the fields but only use the `TableIndices` method.

**Comment by lunny** [comment]
Looks it's not bad on MySQL8 and I don't know what's the result for mariadb.

```
EXPLAIN
SELECT `action`.* FROM `action` INNER JOIN `repository` ON `repository`.id = `action`.repo_id WHERE user_id=1 AND is_deleted=false ORDER BY `action`.`created_unix` DESC LIMIT 20
```
image

**Comment by 6543** [comment]
-> increase RAM and it works

**Pull request closed without merging**
