### PR TITLE
chore(PR): Add Reviewed-on in commit message

### PR DESCRIPTION
**Pull request by appleboy**
Add `Reviewed-on` in the commit message.

Screenshot:

21312321___5__·_06470f8899_-_2132131_-_Gitea__Git_with_a_cup_of_tea

### CODE REVIEW

**Comment by 6543** [comment]
Dont know if this is usefull - the pr number is already in the commit title

**Comment by sapk** [comment]
@6543 it is from linux kernel convention. https://git.wiki.kernel.org/index.php/CommitMessageConventions

**Comment by zeripath** [comment]
I think I'd prefer `Referenced-PR:`  or something like that.

The trouble with `Reviewed-On:` is that it makes me think of a date, a particular commit or computer architecture not the PR number and so the PR number comes as a bit of a shock.

**Comment by appleboy** [comment]
I take https://github.com/golang/go/commit/edf3ec987ff51584c3bfdaeef7d0a24646d0fb4b as reference

**Comment by zeripath** [comment]
Ah I had no idea they were using that. Have you been able to find a document that has all their tags?

OK, I wonder if we should be putting the full url in there then or at least the reponame/username.

**Comment by zeripath** [comment]
Now sticking the full URL in could unintentionally expose private giteas.

I guess this needs probably needs a config value. (yet another)

I would guess options include: full URL, owner/reponame#1, owner/reponame!1, #1, !1, none?

**Comment by lunny** [comment]
@zeripath If you can visit the codes or the pull, then you have know the private repository URL before the commit message tell you. I don't think it's a problem.

If we put `owner/reponame#1`, it will only be a link on gitea but not git commands or other git tools.

**Review by sapk — APPROVED** [review]

**Comment by guillep2k** [comment]
> 
> 
> @zeripath If you can visit the codes or the pull, then you have know the private repository URL before the commit message tell you. I don't think it's a problem.
> 

Unless it's a public mirror of a private repo from another instance.

A full URL would not survive well a site migration, but a relative one will only work locally which is a boomer as well.

**Review by guillep2k — APPROVED** [review]

**Comment by sapk** [comment]
It could configurable on repository level (furthermore maybe add a commit template ?) but in the meantime the user can simply remove the text ?

**Comment by appleboy** [comment]
@sapk Yes. Users can simply remove the text before merging the PR.

_8_-_Update__README_md__-_2132131_-_Gitea__Git_with_a_cup_of_tea

**Comment by zeripath** [comment]
Make lg-tm work

**Comment by danwilliams** [comment]
@appleboy @sapk @zeripath is there an issue that covers making this configurable as a system-wide default? I'd like to keep my eye on it if so, as it is tedious to manually remove the text for every merge.

(I could not find one in a few minutes of searching.)

**Comment by sapk** [comment]
I don't think so but it could maybe be attached to #9823 to provide commit template for commit (update and merged) globally, by org/user or repo.

**Pull request merged**
