### PR TITLE
Hook go-licenses into tidy again

### PR DESCRIPTION
**Pull request by silverwind**
Running it as part of the build is really unnecessary because we have a valid output file in the repo and assuming go dependencies do not change unless go.mod also changes, tidy really is the best target to run the license generation after.

Also, regenerate the file as I missed to do so during the chroma update, and mark all json files in assets as generated.

### CODE REVIEW

**Comment by silverwind** [comment]
Test failure is unrelated, see https://github.com/go-gitea/gitea/issues/21355.

**Review by KN4CK3R — APPROVED** [review]

**Review by Gusted — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by zeripath** [comment]
running `make generate` on the current head already produces a different `assets/go-license.json`

I run `make vendor` on checkout so that I can solve bugs.

Adding this into tidy will result in making checkout even slower.

**Comment by silverwind** [comment]
`make vendor` is, since recently decoupled from `make tidy`, so this will not run at all. And even if you run `make tidy` directly, it will only run the ~15sec licence generation if `go.mod` changed during the checkout.

**Comment by silverwind** [comment]
Actually, I think I need to enforce CI to run the target because depending on git checkout order, the target might be skipped otherwise as seen in the recent run:

```
make[1]: 'assets/go-licenses.json' is up to date.
```

**Comment by silverwind** [comment]
Added a `touch`, which will be enough so `make` sees the target as out of date and always runs it.

**Comment by silverwind** [comment]
I just learned that `make` has the `--always-make` to achieve the same, so use that instead of `touch` hacks :)

**Comment by zeripath** [comment]
Wouldn't this mean you could make go-licenses part of tidy-check?

```patch
diff --git a/Makefile b/Makefile
index 3a9025746..f56997e82 100644
--- a/Makefile
+++ b/Makefile
@@ -403,12 +403,9 @@ unit-test-coverage:
 	@$(GO) test $(GOTESTFLAGS) -timeout=20m -tags='$(TEST_TAGS)' -cover -coverprofile coverage.out $(GO_PACKAGES) && echo "\n==>\033[32m Ok\033[m\n" || exit 1
 
 .PHONY: tidy
-tidy:
-	$(eval MIN_GO_VERSION := $(shell grep -Eo '^go\s+[0-9]+\.[0-9.]+' go.mod | cut -d' ' -f2))
-	$(GO) mod tidy -compat=$(MIN_GO_VERSION)
-	@$(MAKE) --no-print-directory $(GO_LICENSE_FILE)
+tidy: go.mod go.sum $(GO_LICENSE_FILE)
 
-vendor: go.mod go.sum
+vendor: tidy
 	$(GO) mod vendor
 	@touch vendor
 
@@ -424,6 +421,12 @@ tidy-check: tidy
 .PHONY: go-licenses
 go-licenses: $(GO_LICENSE_FILE)
 
+go.sum: go.mod
+	$(eval MIN_GO_VERSION := $(shell grep -Eo '^go\s+[0-9]+\.[0-9.]+' go.mod | cut -d' ' -f2))
+	$(GO) mod tidy -compat=$(MIN_GO_VERSION)
+	@touch go.sum
+
+
 $(GO_LICENSE_FILE): go.mod go.sum
 	-$(GO) run $(GO_LICENSES_PACKAGE) save . --force --save_path=$(GO_LICENSE_TMP_DIR) 2>/dev/null
 	$(GO) run build/generate-go-licenses.go $(GO_LICENSE_TMP_DIR) $(GO_LICENSE_FILE)

```

**Comment by silverwind** [comment]
`tidy` can and often will alter `go.mod` but that'd not be correctly pictured in these dependencies. Probably won't matter in practice.

I'm still not sure why you want to re-introduce the `tidy` dependency to `vendor` again. In my eyes, `tidy` and `vendor` should be independant and if you really want to run them back-to-back, you should use `make tidy vendor`.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
