### PR TITLE
Turn banner into a link to the github page

### PR DESCRIPTION
**Pull request by strk**
Makes it easier to get to the official repo from old Gogs forks..

### CODE REVIEW

**Comment by Bwko** [comment]
Rebase then lgtm

**Comment by tboerger** [comment]
I can't see where this should be useful

**Comment by Bwko** [comment]
@tboerger It's only useful when someone forks gitea and someone clicks on the header image.

**Comment by tboerger** [comment]
But even than I don't see why it's useful. The fork will be anyway already displayed on the page

**Comment by bkcsoft** [comment]
I'd just change it to `` instead (since otherwise it breaks when you're offline...)

**Comment by Bwko** [comment]
@tboerger You're right, then we'll use @bkcsoft solution

**Comment by strk** [comment]
Here's where it's useful:
https://github.com/strk/gogs/

**Comment by strk** [comment]
Try to get from there to gitea (which is clearly the upstream, judging from the logo)

**Comment by tboerger** [comment]
You have not forked from gitea, you have forked from Gogs

**Comment by strk** [comment]
Exactly, long ago. Now in order not to waste time with dropping the fork, recreating it from gitea and then re-pushing all feature branches and re-open the then broken PRs to gitea and gogs... I think it would be much easier to just have a Gitea banner be a link to a Gitea website. Can be gitea.io if you don't like the github link

**Comment by tboerger** [comment]
Please replace the link to the image with `public/img/gitea-large-resize.png`

**Comment by strk** [comment]
Done

**Comment by tboerger** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Pull request merged**
