### PR TITLE
Splitted the user settings code into several files to be more maintainable

### PR DESCRIPTION
**Pull request by daviian**
splitted up one huge router settings file into smaller files representing the actual page structure

No functionality changed. Just moved code from one file to others.

### CODE REVIEW

**Comment by lafriks** [comment]
Copyright year should be 2018. Also Gogs copyrigth line should added as well as code has not changed

**Comment by lunny** [comment]
@daviian I like the idea to create a new subfolder named settings and put related routers there and rename the routers name simpler.

**Comment by daviian** [comment]
@lunny That's already outdated :wink:

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Pull request merged**
