### PR TITLE
API endpoints for stars

### PR DESCRIPTION
**Pull request by DblK**
Migration of [Gogs PR #3815](https://github.com/gogits/gogs/pull/3815)

### CODE REVIEW

**Comment by DblK** [comment]
@ethantkoenig can you submit your PR here instead of on Gogs original repo?

**Comment by ethantkoenig** [comment]
Hi @DblK, I appreicate the response to my PR. However, I would like for this PR to eventually get merged into `gogits/gogs`. Are you planning to merge the changes on `gitea` into `gogits/gogs` at some point? What is the point of `gitea`?

**Comment by tboerger** [comment]
The author of Gogs is not responding again and he keeps rejecting more people with write rights, so we resurrected this fork to push development by multiple people forward.

**Review by tboerger — CHANGES_REQUESTED** [review]
Please use cherry-pick to take the original author commits.

**Comment by ethantkoenig** [comment]
In response to @tboerger's request, I have opened a new PR: #100.

**Comment by lunny** [comment]
Then close this one.

**Pull request closed without merging**
