### PR TITLE
Add HTML URL to API Issues

### PR DESCRIPTION
**Pull request by jolheiser**
After the recent refactor, webhooks are sending URLs pointing to the API rather than the instance.  

This PR adds the HTML URL to API Issues. API PRs already have the HTML URL, so I assumed it was okay to add to Issues as well.

### CODE REVIEW

**Comment by guillep2k** [comment]
Looks like the refactor introduced a breaking change. If that was not intentional, I'd rather add `APIURL` and use `URL` again for the HTML link.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
This is also consistent with what github returns

**Comment by jolheiser** [comment]
> Looks like the refactor introduced a breaking change. If that was not intentional, I'd rather add `APIURL` and use `URL` again for the HTML link.

This is consistent with how `structs/pull.go` does it as well.  
Since the `structs` package is generally used by APIs, I think the thought is that `URL` refers to the APIs URL?

**Comment by guillep2k** [comment]
>
> 
> This is consistent with how `structs/pull.go` does it as well.
> Since the `structs` package is generally used by APIs, I think the thought is that `URL` refers to the APIs URL?

No problem, I thought it could be a breaking change, that's all.

**Review by guillep2k — APPROVED** [review]

**Comment by jolheiser** [comment]
This will also need a backport FYI.

**Review by 6543 — APPROVED** [review]

**Comment by jolheiser** [comment]
Will backport in a bit.

**Pull request merged**
