### PR TITLE
Fix extra columns from `label` table

### PR DESCRIPTION
**Pull request by guillep2k**
Some fields were inadvertently introduced in the database in #5786. This PR removes the mapping, but does not remove the already created columns from existing databases.

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

**Comment by zeripath** [comment]
you could add a migration with dropTableColumns to remove these columns?

**Comment by guillep2k** [comment]
> 
> 
> you could add a migration with dropTableColumns to remove these columns?

No problem, I will, but I was under the impression that we seldomly do that, that's why I pointed it out.

**Comment by zeripath** [comment]
I think we couldn't easily drop the columns before - dropTableColumns now, finally after several commits fixing the damn thing, works.

**Comment by guillep2k** [comment]
> 
> 
> I think we couldn't easily drop the columns before - dropTableColumns now, finally after several commits fixing the damn thing, works.

Somehow I'd wish it was more like `dropTableColumnsIfTheyDontExists()`

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
CI failed is related.

**Comment by guillep2k** [comment]
Well, well, well... What should I do here? As the addition of the column was not intentional, there is no migration that *adds* the column. Therefore, this step fails when migration from an older version:

```
        migration_test.go:223: 
            	Error Trace:	migration_test.go:223
            	            				migration_test.go:242
            	Error:      	Received unexpected error:
            	            	migrate: do migrate: Drop table `label` columns [query_string]: pq: column "query_string" of relation "label" does not exist
            	Test:       	TestMigrations/Migrate-postgres-1.5.3
    --- FAIL: TestMigrations/Migrate-postgres-1.6.4 (9.65s)
```

Should I `Sync2()` the columns to ensure their existence?

**Comment by zeripath** [comment]
Yeah I guess there's two options make droptablecolumns cope with non existent columns, or get them added through a sync 2 first then drop them

**Comment by guillep2k** [comment]
I'll use the `Sync2()` method because checking for column existence requires more testing; I'd rather do that in a different PR. It's too AM for me ATM. I'll do it tomorrow. 😴

**Comment by guillep2k** [comment]
OK, I'm too soft.
@zeripath @jolheiser @lunny done.

**Comment by guillep2k** [comment]
Note: I've tested locally by rewinding my version number that the columns are properly created if they're missing.

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
Do you guys want me to backport the first commit? I mean this part:

image

**Comment by zeripath** [comment]
They're not doing any harm.

**Pull request merged**
