### PR TITLE
Fix redundant dividers on search for labels

### PR DESCRIPTION
**Pull request by HesterG**
Labels search dropdowns have redundant dividers when searching for labels

Screen Shot 2023-06-16 at 14 42 45

This PR adds `data-divider-index` and `data-divider-group` to dynamically toggle the visibility of dividers depending on filtered results. And slightly changed the logic for adding the divider if there are both `Labels` and `OrgLabels` exist.

After:

https://github.com/go-gitea/gitea/assets/17645053/5f905358-f6c3-40d9-a06d-a1306a72bd38

Locations of the dropdowns:

On sidebar of issue/pr, and on repo issue/pr list

### CODE REVIEW

**Comment by wxiaoguang** [comment]
At first glance, it's quite hacky. I guess it's not the right way.

**Comment by silverwind** [comment]
In the video, the extra dividers are still seen while typing, so yes I think the solution can't be right.

**Comment by silverwind** [comment]
BTW, I generally think we should rewrite these labels dropdown to a format similar to GitHub, it saves vertical space as well:

image

**Comment by wxiaoguang** [comment]
Actually, Fomantic UI does very well for "hiding dividers".


We only needs 2 lines:

```
  $dropdownLabelFilter.dropdown('setting', {'hideDividers': 'empty'});
  $dropdownLabelFilter.dropdown('refreshItems');
```

**Comment by HesterG** [comment]
> Actually, Fomantic UI does very well for "hiding dividers".
> 
> We only needs 2 lines:
> 
> ```
>   $dropdownLabelFilter.dropdown('setting', {'hideDividers': 'empty'});
>   $dropdownLabelFilter.dropdown('refreshItems');
> ```
> 
> * [Fix label list divider #25312](https://github.com/go-gitea/gitea/pull/25312)

That's great, I will close this.

**Pull request closed without merging**
