### PR TITLE
Remove explicit 'generate' calls, fix release task

### PR DESCRIPTION
**Pull request by silverwind**
`generate` is now implicit during `build` since #9114, it is no longer necessary or desired to specify it explicitely.

### CODE REVIEW

**Comment by silverwind** [comment]
Not 100% certain about the `release` tasks. It forks out to `xgo` while never explicitly calling `build`. I guess `xgo` does that?

**Review by zeripath — APPROVED** [review]

**Comment by axifive** [comment]
@techknowlogick  I can't find `make css js` call for the `release`. Is it builds static files now?

**Review by lafriks — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
I think you should remove the warning about the generate on build from source.

**Comment by techknowlogick** [comment]
@axifive It doesn't.

@silverwind I've just checked the most recent binaries for master branch and they don't include the generated CSS/JS, perhaps a Drone step could be added before the xgo one to generate the CSS/JS for releases.

**Comment by silverwind** [comment]
@techknowlogick what does `xgo` exactly call? Just `make`? Are the releases meant to be built with bindata?

**Comment by techknowlogick** [comment]
@silverwind `xgo` is just a nice wrapper around `go build` (you can see an example of how go build is called here: https://github.com/techknowlogick/xgo/blob/master/docker/base/build.sh#L192, note there are other ways go build is called based on which cross-compiled architecture you'd like). It is how we can generate all of our binaries for different platforms (eg, arm, powerpc, windows, etc..). The way xgo does this is if calling xgo not in a docker container, it actually mounts the go code into the container that has all of the dependencies for the other platform you need and runs go build, if called inside the xgo container (like we do with drone), then it knows that and runs the same go build.

It uses the command line flags that passes the TAGS to the go build, that way it knows to use bindata tag. Now that pregenerated css/js aren't included in repo they will have to be generated before xgo is called, as xgo doesn't have node dependancies in its docker image, a different drone step (before xgo is called) would be best place to put it (if you'd like me to do this step I can, and then push it to your branch).

**Comment by silverwind** [comment]
Okay. Does it have to be a drone step? I was thinking of just adding `js css` as a dependency in the `release` make task.

**Comment by silverwind** [comment]
Also, I see it passes `$(TAGS)` but that variable should be empty at this point. Where does `bindata` come in?

**Comment by silverwind** [comment]
@techknowlogick I added the dependencies, can you check if that fixes the issue? I prefer it that way instead of in drone because one can release outside of drone too and less calls to make it always faster.

**Comment by silverwind** [comment]
@lunny not sure what you mean. can you point me to that warning?

**Comment by lunny** [comment]
see https://github.com/go-gitea/gitea/blob/master/docs/content/doc/installation/from-source.en-us.md

and find `WARNING: generate method is deprecated and using it may cause build to miss some static files.`.

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
