### PR TITLE
Return 404 instead of 403 if user can not access the repo

### LINKED ISSUE #23150: You can view Private Repositories's name from other users
### Description

Technically you can't see the repositories of other users but you can see the name of that repository and know that it exists.

You have to use another account and the tool 'git clone' with the URL of the repository. You can see that the private repository exists because of the response.

Maybe this could lead to something else, in a CTF, I had to know the repository's name of the other user to make my user part of that repo by injecting a XSS and then, I could grab his SSH key to log into the machine.

The machine was Extension from HackTheBox.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

paso_1
paso_2

### Git Version

2.39.2

### Operating System

_No response_

### How are you running Gitea?

I runned it from https://try.gitea.io/ 

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fixes https://github.com/go-gitea/gitea/issues/23150

Before:
image

After:
image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport

**Comment by yardenshoham** [comment]
Please send backport v1.18

**Comment by yardenshoham** [comment]
> I was unable to create a backport for 1.18, please send one manually. 🍵

Fancy

**Comment by yardenshoham** [comment]
Backport to v1.18 is not critical

**Pull request merged**
