### PR TITLE
Populate URL field of API commits

### PR DESCRIPTION
**Pull request by ethantkoenig**
Also moves `URLJoin` to `modules/util` so that everyone can use it.

### CODE REVIEW

**Comment by appleboy** [comment]
build error:

```
modules/markup/markdown/markdown_test.go:36:9: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:37:13: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:46:10: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:55:13: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:56:9: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:57:14: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:58:12: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:59:13: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:60:18: undefined: markup.URLJoin
modules/markup/markdown/markdown_test.go:61:16: undefined: markup.URLJoin
```

**Comment by lunny** [comment]
maybe a `module/url` package but `util` package.

**Comment by ethantkoenig** [comment]
@appleboy @lunny No, it's just that drone didn't pick up the latest commit :cry:

**Comment by appleboy** [comment]
@ethantkoenig I don't think so.

```
# code.gitea.io/gitea/modules/markup/orgmode
modules/markup/orgmode/orgmode_test.go:33:9: undefined: markup.URLJoin
modules/markup/orgmode/orgmode_test.go:49:12: undefined: markup.URLJoin
```

Don't see any changes in `orgmode_test.go` file.

**Comment by ethantkoenig** [comment]
@appleboy Oh I see.. I had fixed `markdown_test.go` (those fixes were not picked by Drone the first time), but it seems there were still more tests to fix

**Review by sapk — APPROVED** [review]
Good code refactoring

**Review by appleboy — APPROVED** [review]

**Pull request merged**
