### PR TITLE
Rename ".button-link" to ".button-ghost"

### PR DESCRIPTION
**Pull request by wxiaoguang**
Mainstream frameworks:

* https://getbootstrap.com/docs/5.0/components/buttons/
* https://primer.style/css/components/buttons#link-button
* https://nextui.org/docs/components/button#light
* https://coreui.io/react/docs/components/button/
* https://design-system.hpe.design/components/button
* https://chakra-ui.com/docs/components/button/usage#button-variants
* https://mui.com/material-ui/react-button/

All (at least most?) of them make "link" button have "underline" when hovering.

So, a "link" is a "link", when it's hovered, it should have the underline by default. To be strict, Gitea's "button-link" is not link-style, so it needs a better name.

Actually, for the "plain" button, there are some different approaches:

* Some frameworks just make "default" button as no style (not feasible in Gitea/Fomantic UI)
* Primer uses "btn-invisible", which is not a proper word
* NextUI uses "light", which is not a proper word, either ...
* CoreUI / ChakraUI uses "ghost", I think this name is acceptable.

Welcome to suggest better name for such button.

Or, we just call it ".button-plain" or ".button-simple", in fact I prefer such simple and clear name.

### CODE REVIEW

**Comment by silverwind** [comment]
👍 for following chakra-ui naming, I think it's probably the most well thought-out framework around currently.

**Comment by wxiaoguang** [comment]
Then let's go with it? After this PR, I will change `.ui.tertiary.button` to this.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Yes, `.ui.tertiary.button` needs to go. We can also add hover/active background to this later, but I'd say it depends on `color-mix` to obtain the low-alpha shades which I'm still a bit vary to use.

image

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
Yup, I can also live with both.
I probably prefer `".button-plain"` too.

**Pull request merged**
