### PR TITLE
Correct broken unaligned load/store in armv5

### PR DESCRIPTION
**Pull request by psolyca**
This PR fixes issue #1354.

> armv5 devices and older (i.e. <= arm9 generation) require addresses that are stored to and loaded from to to be 4-byte aligned.
> 
> If this is not the case the lower 2 bits of the address are cleared and the load is performed in an unexpected order, including up to 3 bytes of data located prior to the address.
> 
> Inlined buckets are stored after their key in a page and since there is no guarantee that the key will be of a length that is a multiple of 4, it is possible for unaligned load/stores to occur when they are cast back to bucket and page pointer types.
> 
> The fix adds a new field to track whether the current architecture exhibits this issue, sets it on module load for ARM architectures, and then on bucket open, if this field is set and the address is unaligned, a byte-by-byte copy of the inlined bucket is performed.
> 

The fixe commes from https://github.com/resin-os/bolt/commit/97aba5586d36f9670a77dc6e60ec1b9ef31ce9ae
and has already been applied in the upstream boltdb repository https://github.com/boltdb/bolt/pull/578

I already tested this fixe on my armv5 board with success.

Thanks

### CODE REVIEW

**Comment by lunny** [comment]
please use `govendor` and that will update `vendor/vendor.json` to follow the `git rev`.

**Comment by psolyca** [comment]
For now, I can not compile anymore. Do not know why, I have «out of memory» problem each time the build process is linking.

**Comment by psolyca** [comment]
Ok, I manage to compile commit ae9b02b079954eabafc55ff1ab7527ba828f4bb6 in 3 ways :
- without any patch or update : same issue
- with manual patch : no more error
- with vendor update of BoltDB : no more error

I am updating my PR.

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
