### PR TITLE
Add missing repository setting docs in cheat sheet

### PR DESCRIPTION
**Pull request by strk**
Taken from app.ini-sample

### CODE REVIEW

**Comment by strk** [comment]
I started this to document `PREFERRED_LICENSES` but I don't really see that variable used in code, why was in app.ini-sample at all ?

**Comment by lafriks** [comment]
@strk it is used in here: https://github.com/go-gitea/gitea/blob/f2e20c81b66e6a937ecdb686f8d1011371433365/models/repo.go#L117

**Comment by lafriks** [comment]
LGTM

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
LGTM

**Pull request merged**
