### PR TITLE
always show assignees on right

### PR DESCRIPTION
**Pull request by metiftikci**
### Before

old_issue_list

### After

new_issue_list

### CODE REVIEW

**Review by wxiaoguang — DISMISSED** [review]

**Comment by wxiaoguang** [comment]
Oh wait, it make mobile view worse .......

**Comment by metiftikci** [comment]
what is the width you are checking?

**Comment by wxiaoguang** [comment]
Old:

<details>

image

</details>

New:

<details>


image

</details>

**Comment by metiftikci** [comment]
actually that does not looks bad to me 😆 what do you suggest?

**Comment by wxiaoguang** [comment]
> actually that does not looks bad to me 😆 what do you suggest?

I think on narrow screen, it's better to wrap the title and the right part (assignee)  in one line ..... I recalled an old issue :  Improve flex-item overflow #31404  (31404 is still draft but the screenshot looks better)

**Comment by metiftikci** [comment]
What about wrap only time?

large_issues

small_issues

**Comment by wxiaoguang** [comment]
> What about wrap only time?

LGTM

**Comment by metiftikci** [comment]
done

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
