### PR TITLE
Updating stale.yml to add the support for `actions/stale`

### PR DESCRIPTION
**Pull request by gaurangkudale**
Adding support for [Actions/stale](https://github.com/actions/stale) #27004

### CODE REVIEW

**Comment by gaurangkudale** [comment]
Hi @a1012112796 ,
Can you please review this PR and let me know if there are any suggetions

**Review by nanguanlin6 — CHANGES_REQUESTED** [review]
The stale action uses Github Actions instead of some stale bot. Probably you should add a cron job under `.github/workflows`

**Comment by gaurangkudale** [comment]
> The stale action uses Github Actions instead of some stale bot. Probably you should add a cron job under `.github/workflows`

Yes I have added it as a cron job under `.github/workflows`

**Comment by gaurangkudale** [comment]
Hi @lunny 
can you please review these changes?

**Review by nanguanlin6 — COMMENTED** [review]
1. delete the unnecessary file, comment, and KV pair
2. fix CI failure
3. don't be so rushed. On the first attempt, you asked for the review without knowing how stale action works, and on the second you asked for the review when the yaml file still has an indent error. Both mistakes are quite basic if you give them some attention. The reviewers will carry out their duties as usual, so there's no need to tag them in a hurry.

**Comment by denyskon** [comment]
We're currently discussing a restructuring of our labels, so we should wait until it's done before merging this.

Also I don't think we should close PRs. Give maintainers time, some of us go through the list regularly and try to review especially old PRs which have remained untouched for a while.

**Review by nanguanlin6 — COMMENTED** [review]
Is there a particular reason to use v3 instead of the current latest version v8?
The options in the [docs](https://github.com/actions/stale#list-of-input-options) seem to use '-' instead of the camel case. And some of the labels are not suited for our current label system.

**Comment by a1012112796** [comment]
ping @denyskon @go-gitea/technical-oversight-committee

**Comment by lng2020** [comment]
> Is there a particular reason to use v3 instead of the current latest version v8? The options in the [docs](https://github.com/actions/stale#list-of-input-options) seem to use '-' instead of the camel case. And some of the labels are not suited for our current label system.

I think those problems still exist.

**Comment by jolheiser** [comment]
Having been involved with both projects using and not using a stalebot, I think my preference is also to not have one where possible. 

We have a _lot_ of open issues, however I think many of the issues that _could_ benefit from some automation (i.e. reported on much older versions) are already labeled such that this config will likely miss them. (`confirmed` being the big one, as they were "confirmed" at the time but may no longer be relevant)

**Comment by lunny** [comment]
Since giteabot will close an issue which have `issue/needs-feedback` label with no reponse for a month. I think we can close this PR and even remove the old stale file.

**Comment by denyskon** [comment]
I also think a stale bot won't be a benefit.

**Pull request closed without merging**
