### PR TITLE
Do not send activation email if manual confirm is set

### LINKED ISSUE #17263: `REGISTER_MANUAL_CONFIRM` does not require manual change to `Activated` as described
### Gitea Version

1.15.3 

### Git Version

2.17.1

### Operating System

Ubuntu 20.04.3 LTS, but gitea runs under snap core 16-2.51.7  2021-09-30

### How are you running Gitea?

I am using the snap package of gitea, version `latest/stable:    v1.15.3                       2021-09-22 (5629) 59MB -`

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

I have reported this [on the discourse](https://discourse.gitea.io/t/moderation-of-new-users/3876) as well.

My use case is a gitea installation that is well cared-for during time when I can devote attention to personal projects, but which may stand neglected for part of the year.  My goal is to configure it so that strangers cannot surprise me by registering on it and uploading content over which I have no control.  To that end, I would like to be able to manually approve new signups after verifying that they are indeed my friends and project collaborators.

To this end, I am using `REGISTER_MANUAL_CONFIRM = true` in the `[service]` section of my configuration, which per the docs requires that I also set `REGISTER_EMAIL_CONFIRM = false`.  I am hard re-starting gitea after updating the `app.ini`, and testing creation of a new user.

Each time I create a user, it sends me a confirmation via e-mail.  Clicking that e-mail confirmation link results in a fully activated user, which I confirm by visiting the admin panel in another browser (per the screenshots).  Per the discord `configuration` channel, I was advised to file this as a bug, as it seemed to `norwin#8935` that the behaviour I am seeing is clearly at odds with the documentation for `REGISTER_MANUAL_CONFIRM`.

What follows is the complete and entire `[service]` section of my `app.ini`, in case some other option turns out to be conflicting with `REGISTER_MANUAL_CONFIRM`:

```ini
[service]
REGISTER_EMAIL_CONFIRM            = false
REGISTER_MANUAL_CONFIRM           = true
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.example.org
```

I am unable to reproduce on `try.gitea.io` because this is a problem with server configuration.  If I am mistaken and there are facilities on that site to perform these sorts of experiments, I am happy to give that a go.

### Screenshots

Screenshot from 2021-10-07 21-07-56
Screenshot from 2021-10-07 21-08-03
Screenshot from 2021-10-07 21-08-21
Screenshot from 2021-10-07 21-09-06
Screenshot from 2021-10-07 21-09-17
Screenshot from 2021-10-07 21-09-38

### PR DESCRIPTION
**Pull request by zeripath**
If the mailer is configured then even if Manual confirm is set an activation email
is still being sent because `handleUserCreated` is not checking for this case.

Fix #17263

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Backport will be slightly difficult as we can't use the new string.

Instead I suggest we just use the email confirmation is disabled string.

**Comment by skobkin** [comment]
Shouldn't Gitea send an email to the administrator when new user registered?

Probably it's out of `kind/bug` scope, but would be nice to have too.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
We need to clarify whether `RegisterManualConfirm` means a register will only be confirmed manually or `RegisterManualConfirm` means a register could be activated by email and also could be confirmed manually.

**Comment by skobkin** [comment]
> We need to clarify whether `RegisterManualConfirm` means a register will only be confirmed manually or `RegisterManualConfirm` means a register could be activated by email and also could be confirmed manually.

Currently it's already indirectly documented in the config cheat sheet.
But it'll only be better if it'd be written in a more clear way.

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
Please send back port.

**Pull request merged**
