### PR TITLE
upgrade to alpine 3.13

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

blocked by golang image upstream not yet being updated

### CODE REVIEW

**Comment by tomaswarynyca** [comment]
the image does not exist in dockerhub. golang: 1.15-alpine 3.13

**Review by jace788 — APPROVED** [review]

**Review by jace788 — APPROVED** [review]

**Review by jace788 — APPROVED** [review]

**Comment by techknowlogick** [comment]
@tomaswarynyca it usually takes a few days for the upstream image to be built. that is what is meant by blocked in my comment above. thanks for opening issue.

**Review by jace788 — APPROVED** [review]

**Comment by 6543** [comment]
@jace788 pleace dont SPAM!!!

**Review by jace788 — APPROVED** [review]

**Review by jace788 — APPROVED** [review]

**Review by jace788 — APPROVED** [review]

**Comment by gary-kim** [comment]
Image is built now

**Review by gary-kim — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Pull request merged**
