### PR TITLE
bug fixed for 500 caused by get org users

### PR DESCRIPTION
**Pull request by lunny**
This is not related with #147.

### CODE REVIEW

**Comment by bkcsoft** [comment]
@lunny how does this fix that issue?

**Comment by lunny** [comment]
`"` is only quote of postgres, so mysql will report error. ` is a common quote on XORM, XORM will replace it to every database's quote.

**Comment by bkcsoft** [comment]
But it's only for when an Org doesn't have any Repos. If _this_ was the error, it should happen all the time and not just in that case?

**Comment by lunny** [comment]
No. I make mistake. These two bugs. #147 and #149. They are different bugs.

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
