### PR TITLE
Remove vendored copy of fomantic-dropdown

### LINKED ISSUE #15172: When selecting a license you can't write in any field
When you try to create a repository and select a license you cannot continue working in the other fields.
I checked the bug in try.gitea.io v1.15.0+dev-27-gdc56fb7c8

### PR DESCRIPTION
**Pull request by silverwind**
jQuery 3.6.0 seems to have broke the dropdown focus handling (focus would get stuck on the dropdown) in this module which we have vendored on top of fomantic for accessibility improvements.

Either downgrading jQuery to 3.5.1 or removing the vendor copy seems to resolve the issue and I opted for removing the copy because I think such changes should be done upstream and the removal also lightens the JS by 155kB before minify/gzip.

Fixes: https://github.com/go-gitea/gitea/issues/15172
Ref: https://github.com/go-gitea/gitea/pull/8638
Ref: https://github.com/jquery/jquery/pull/4813

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]
:+1:

**Comment by techknowlogick** [comment]
Have these a11y fixes been upstreamed? I don't want to lose any accessibility by merging this.

**Comment by silverwind** [comment]
No, it was never followed up and it seems the original author also has [no interest](https://github.com/go-gitea/gitea/pull/8638#issuecomment-580992118) in upstreaming the patch. So yes, we'd loose some a11y with this removal, but I think it's overall a net gain to no longer have this crude way of patching fomantic.

**Comment by henningoschwald** [comment]
As expected this definitely breaks a11y for me using the Orca screenreader on Linux with Firefox, i.e. in the "create" drop-down in the main navigation. Tested with Gitea master from April 19th. Other browsers and screenreaders are affected too, of course. I really hope you don't intend to stick with this state and I wish you would give a11y a higher priority in general.

I am not deep enough into web development to come up with pull requests, but I would be available as a tester and I am able to build Gitea from sources.

**Comment by silverwind** [comment]
We are deeply dependant on Fomantic UI which was not created with accessiblity in mind. I think our best bet is to gradually replace it with something better, but I'm not sure what to replace it with.

**Pull request merged**
