### PR TITLE
Allow users with explicit read access to give approvals

### LINKED ISSUE #8297: Cannot add read-only users to the Pull Request Whitelist
Problem:
People's names/teams other than the first team I'm in (Owners, alone) do not appear in the settings area for whitelisting things. So I cannot set anything up as the owner. The only solution I can see it put everyone (me, support, admins, approvers) into one big team with full permission (since I need full permission)
image

I can already bet that this is because the autocomplete is ignoring anything other than the first team it finds that I am in (which is Owners), but of course I am also part of the developers team - which it is just ignoring.

This is also an issue when writing an issue and trying to @ mention someone - no autocomplete appears so I have to write them manually. Perhaps a `UserService` of some sort on the front end needs to be abstracted out, that can be used by different modules in Gitea: `UserService.GetAllUsersInOrg()`  `UserService.GetAllUsersInTeam()` `UserService.GetAllMyTeams()`

### PR DESCRIPTION
**Pull request by guillep2k**
Fixes #8297

Currently teams with read-only access can be added as whitelisted approvers, but not users.

This PR corrects that in that it allows the addition of users with **read-only access** to the whitelisted approvers *as long as the user was explicitly added as a collaborator to the repository*.

### CODE REVIEW

**Comment by worthy7** [comment]
@guillep2k Thanks for this. May I request we make a small text change to the UI so that it's very clear how this works.
1. `Allow only to merge pull request with enough positive reviews of whitelisted users or teams.`
-> `Allow merging of pull request's only with enough positive reviews from approvers.`
2. `Whitelisted reviewers:` -> `Approvers`
3. hint text underneath `Contributing teams or users of this repository`
4. Add a checkbox first saying "Use PR Approvals", when unchecked the two options are disabled, when checked, the "number of approvals" is minimum 1 and the input for Approvers should be "required" (input required). Doing a dynamic calculation to see if they match is not worth it since team sizes can change in the future

**Comment by guillep2k** [comment]
@worthy7 This PR only corrects the inconsistency about allowing individual users as approvers. This will not fix your GUI problem from #8297. I'm sorry I misunderstood your issue back there.

**Comment by worthy7** [comment]
Ah I see you linked them but regardless this PR is still an improvement, I'm grateful for you actively trying to fix things.

My comment above could be just another issue about "interface". Feel free to ignore it and proceed with the PR if you like

**Review by lunny — APPROVED** [review]

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k Thanks for this. May I request we make a small text change to the UI so that it's very clear how this works.
> 
>     1. `Allow only to merge pull request with enough positive reviews of whitelisted users or teams.`
>        -> `Allow merging of pull requests only with enough positive reviews from approvers.`
> 
>     2. `Whitelisted reviewers:` -> `Approvers:`
> 
>     3. hint text underneath `Contributing teams or users of this repository`
> 
>     4. Add a checkbox first saying "Use PR Approvals", when unchecked the two options are disabled, when checked, the "number of approvals" is minimum 1 and the input for Approvers should be "required" (input required). Doing a dynamic calculation to see if they match is not worth it since team sizes can change in the future

May be you can PR for that after this is merged? No golang knowledge needed for it.

**Comment by worthy7** [comment]
Ok cool, I'll take a look!

**Comment by worthy7** [comment]
Took a look, seems Gitea is very unix-only for dev, I'm on Windows and it's a work computer (so I'm not keen on setting up a whole VM dev environment to do it - sorry)
I could edit the files and push and then someone else could simply pull and test it, but that's not going to be as straightforward as me just creating a mock design for someone else to copy. Anyway, I'll open a separate issue.

**Comment by 6543** [comment]
@lunny add lable backport done?

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
