### PR TITLE
Do not fetch all refs in pull-request compare

### LINKED ISSUE #2837: Compare changes and new pull requests take a very long time.
- Gitea version (or commit ref): 1.2 windows-amd64
- Git version: 2.11.0 windows
- Operating system: windows 2008 R2 _16 CPU cores and 16GB RAM_
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I try to create pull requests and the 'compare changes' step takes 10 minutes!  Create pull requests make the browser crashed!

### PR DESCRIPTION
**Pull request by typeless**
Fixes #2837 again

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@typeless Have you tried this?

**Comment by 1902sysad** [comment]
will this be merge in 1.9.0.1?

**Comment by typeless** [comment]
@lunny I just ran the integration test for it. I can test it at my workplace, where I have access to a huge repo next Mondy. 

@1902sysad does the pr work for you?

**Comment by typeless** [comment]
I have confirmed that `git remote -f` is no longer the bottleneck when doing *new pull request*. The next bottleneck seems to be `git diff -M` according to my `ps -u git -o cmd` sampling.

**Review by lunny — APPROVED** [review]

**Comment by lafriks** [comment]
please send backport

**Comment by 1902sysad** [comment]
@typeless i have tested this to a big repository it works fine! :D

when this will be a part of stable release? :)

Thank you.

**Comment by lunny** [comment]
@1902sysad 1.9.1 has released which included the backport #7837

**Pull request merged**
