### PR TITLE
Fix Slack webhook payload title generation to work with Mattermost

### LINKED ISSUE #9195: Mattermost Issue notification formatting broken
- Gitea version (or commit ref): 1.10.0
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I integrated Gitea using a Webhook to Mattermost. When I create an issue in Gitea the following text gets posted on Mattermost:

```
[org/repo] Issue submitted by cornel

<https://host/org/test/pulls/1|#1 to do this>
```

The link can't be clicked as it's in text form.

Gitlab posts created issues as:

```
[[org/repo](https://host/org/repo)] Issue opened by Cornel (cornel)
```

which creates a link that can be clicked in Mattermost.

### PR DESCRIPTION
**Pull request by cornelk**
Fixes #9195

Works with Mattermost now but needs to be tested with Slack to work:

### CODE REVIEW

**Review by lafriks — CHANGES_REQUESTED** [review]
This does not work in Slack.

First notification before changes, second after:
image

We should probably create new webhook type for Mattermost to deal with this

**Comment by cornelk** [comment]
I pushed a new fix now based on the API documentation of https://docs.mattermost.com/developer/message-attachments.html and https://api.slack.com/messaging/composing/layouts - it should work for both.

Other changes:
* Fixes issue linking from `pulls` to `issues`
* Changes issue/pull request wording from `submitted` to `opened` to better match the usage of `re-opened` wording
* Links to milestone if assigned to issue/pull request
* Creates shorter posts by not using an attachment with title and title link if there is no text for the message attachment, as the title/link information is already posted in the main body:

**Comment by lafriks** [comment]
Can confirm, works in slack:
image

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lafriks** [comment]
Please send commit 04ab113 backport to `release/v1.10` branch

**Pull request merged**
