### PR TITLE
doctor: delete action entries without existing user

### PR DESCRIPTION
**Pull request by 6543**
just extend doctor with a usefully check :)

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
Should this be backported?

**Comment by 6543** [comment]
only in edgecases so I would not do that jet ... only on request

**Review by silverwind — APPROVED** [review]

**Comment by techknowlogick** [comment]
CI fail seems related

**Comment by lunny** [comment]
CI failure is related.

**Pull request merged**
