### PR TITLE
Range Requests Supported

### PR DESCRIPTION
**Pull request by marxangels**
Happy coding. Please let me know if there is anything to optimize.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I have a feeling that we could use http.ServeContent https://pkg.go.dev/net/http#ServeContent for this task, it can handle everything correctly.

**Comment by marxangels** [comment]
> I have a feeling that we could use http.ServeContent https://pkg.go.dev/net/http#ServeContent for this task, it can handle everything correctly.

Hi! wxiaoguang! Thanks for your reply! I tried `http.ServeContent` and it works!
That is a better way. Now only one real `modtime` parameter is missing.

**Comment by marxangels** [comment]
I'll close this and pull a new request.

**Comment by wxiaoguang** [comment]
In many cases, you do not need the modtime, because go code is:

```
func setLastModified(w ResponseWriter, modtime time.Time) {
	if !isZeroTime(modtime) {
		w.Header().Set("Last-Modified", modtime.UTC().Format(TimeFormat))
	}
}
```

**Pull request closed without merging**
