### PR TITLE
Allow to filter repositories by language in explore, user and organization repositories lists

### PR DESCRIPTION
**Pull request by lafriks**
Allow to filter by primary language in following repository lists:
* Explore repositories
* Organization repository list
* User repository list
* User starred repositories
* User watched repositories

To search by language user can click on language tag in repository list

### CODE REVIEW

**Review by Gusted — APPROVED** [review]
LGTM, maybe at a later point it's possible to add a separate UI/Menu to select the language based off the languages that's currently in the search results(kind of like github currently does).

**Comment by lafriks** [comment]
In code search we already do that just like GitHub does (showing languages that are for files in search results). Functionality implemented here is not available in GitHub at all. Closest to this is trending repositories where you can select language.

**Review by adelowo — APPROVED** [review]

**Comment by Gusted** [comment]
> In code search we already do that just like GitHub does (showing languages that are for files in search results). Functionality implemented here is not available in GitHub at all. Closest to this is trending repositories where you can select language.

Sorry, I meant a menu like:

image

**Comment by lafriks** [comment]
I could not find such filter, in what page is it in GitHub? But yes this could be added in the future

**Comment by Gusted** [comment]
https://github.com/search?q=gitea

**Pull request merged**
