### PR TITLE
Commit search appearence fixes

### LINKED ISSUE #1238: Search commits cosmetic
- Gitea version (or commit ref): `1.1.0`
- Git version: `N/A`
- Operating system: `N/A`
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) `https://try.gitea.io/Fastidious/Test-15/commits/master`
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The ticked box to search `All` is too close to its label. I think the tick box and label should be moved to before the search field instead, and the `Find` button replaced with `Search`, to make it consistent with the rest of search boxes used.

**Screenshot:**

search_bug

### PR DESCRIPTION
**Pull request by pgaskin**
Fix #1238

### CODE REVIEW

**Comment by Fastidious** [comment]
I would really love this to be fixed, but is adding `&nbsp;` the right solution? Can't it be done with CSS, perhaps adding padding, or something of the like?

**Comment by strk** [comment]
LGTM anyway, &nbsp can be fixed later :)

**Comment by lunny** [comment]
conflicted, otherwise LGTM

**Comment by andreynering** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by pgaskin** [comment]
Thanks @andreynering , I have been busy recently.

**Comment by lunny** [comment]
@geek1011 could make an empty force push to this PR to let drone work?

**Pull request merged**
