### PR TITLE
WIP: Rationalise Disable Basic Authentication and SSO

### LINKED ISSUE #2407: Bug: Users authenticated via proxy-auth can change username
In the current version of gitea, it is possible for users authenticated via proxy-auth to edit their username. I'm not able to find a config option to disable this. In cases where proxy authentication is being used, this allows users to change their username and orphan their repositories because a new userid will be immediately created with their correct user.

### PR DESCRIPTION
**Pull request by zeripath**
This PR adds a few changes:

* Extend disable Basic Authentication to git and LFS
* Extend authentication of LFS to use OAuth2
* Extend basic authentication of LFS to use user.SignIn
* Change disable BasicAuthentication to only disable user authentication with password
* Fix #2407 by preventing ReverseProxy authenticated users from changing username
* Default reverseproxy users to have an empty password not the username

### CODE REVIEW

**Comment by zeripath** [comment]
Need to make the basic authentication only get checked once on git and lfs endpoints

**Comment by silverwind** [comment]
> Extend disable Basic Authentication to git and LFS

Care to explain? This does not disable basic auth on git endpoints, right?

**Comment by zeripath** [comment]
> > Extend disable Basic Authentication to git and LFS
> 
> Care to explain? This does not disable basic auth on git endpoints, right?

Actually if DisableBasicAuthentication is set, it would.

There is an extremely good reason as to why we should do that but we should move this discussion to #15303.

**Comment by silverwind** [comment]
Ah, I see as long as token auth is still supported, I'm fine. Basic auth with username/password should be something that is discouraged.

**Comment by zeripath** [comment]
Closing as all of these changes have been split out into other PRs.

(Which aren't being reviewed...)

**Pull request closed without merging**
