### PR TITLE
WIP: Further improvements to Git Graph

### PR DESCRIPTION
**Pull request by zeripath**
- [x] Restructure to extract out Flow generation and allow flows to be associated with commits
- [ ] Provide an alternative flow generation that prefers trunks
  - [x] algorithm
  - [ ] provide a switch  
- [x] Provide a default palette to make colors more predictable
- [ ] Provide a way of pinning colors over page turns.
  - [x] When assigning colors to flows allow colors to be preassigned
  - [ ] Pass the colors on page turn
- [ ] It would be helpful if you could highlight commits/flows on mouseover of flows/commits

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
>  Provide a way of pinning colors over page turns. 
>  Pass the colors on page turn

This seems like a complicated approach. I would use https://github.com/zenozeng/color-hash to convert a branch name to a static color. On dark theme (use `isDarkTheme`) add a higher `lightness` than on light theme to ensure sufficient contrast over the background.

**Comment by zeripath** [comment]
Git branches are misnamed they are simply named commits - once a commit has been made there is no way to determine which of the parents had the branch name, or of any of them had it.

It would be lovely if we could apply fixed names to flows. There is no such naming system possible.

So as far as I can see this is the simplest approach.

**Comment by zeripath** [comment]
Even determining whether to create a new flow or end a flow is not even fixed: 

Given the following glyphs:

```
 |    or    \|
/|           |
```
Which flow continues, which flow creates a new flow? 

If we want pinning we will also have to apply #12142 - fortunately that appears to have no detrimental effects on my test machine although it definitely seems wasteful.

**Comment by zeripath** [comment]
But I think you're right in another way flow determination will have to go to the server for the same reason as #12142

**Comment by silverwind** [comment]
Regarding colors, I just suggest a static list of 16 (or more if you like) predefined colors, see https://github.com/go-gitea/gitea/issues/10217#issuecomment-657000790. It's the simplest way and we can tweak the colors to always look good.

**Pull request closed without merging**
