### PR TITLE
Global default branch setting

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Review by CirnoT — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Review by 6543 — CHANGES_REQUESTED** [review]
sadly it is not that easy

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/cmd/hook.go#L355

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/cmd/hook.go#L380-L381

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/cmd/hook.go#L411-L412

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/templates/repo/empty.tmpl#L55

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/262fce6db4ab87e03926ac7a21bc5e4bea7ea815/routers/private/hook.go#L414-L415

**Comment by CirnoT** [comment]
These issues existed before too if user changed their default branch, nice catch.

**Comment by CirnoT** [comment]
Actually, this looks like it was intentionally there so that even if repo is created with other branch as default, and then `master` is pushed, it would reset repo to that branch.

I am not sure this is desired at all, either with `master` or with any other name.

**Comment by silverwind** [comment]
Needs entry in `custom/conf/app.ini.sample`

**Comment by techknowlogick** [comment]
>  gitea/templates/repo/empty.tmpl

**Comment by techknowlogick** [comment]
@silverwind updated.

**Comment by lunny** [comment]
@techknowlogick We can add an extra git command `fmt.Sprintf("git branch -m master %s", settings.DefaultBranch)` to change the default branch name. 

ref. https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Review by lunny — DISMISSED** [review]
per my comment

**Comment by techknowlogick** [comment]
@lunny updated

**Pull request merged**
