### PR TITLE
updated readme logo

### PR DESCRIPTION
**Pull request by edm00se**
logo was breaking in ReadMe.md on GH repo. I grabbed the concept logo directly from the [feature request for an improved logo](https://github.com/go-gitea/gitea/issues/59), which seemed to be the generally accepted best option.

### CODE REVIEW

**Comment by tboerger** [comment]
:-1: Thank you for a contribution but that seems to be wrong. You have replaced an animated gif that displays the entire application with just an logo. And what is broken with the gif? For me it's getting displayed correctly. Beside that contributions have to be done always on develop branch and not on master directly.

**Comment by edm00se** [comment]
Well, I'm glad it's working for you; I may need to check my browser. In any case, mine looks like the image just fails to load. Here's the screen shot. If it's just me, then no worries and we can nuke this PR.
image

**Comment by FSMaxB** [comment]
@edm00se I also don't see an image there. Only a "Demo" link.

**Comment by tboerger** [comment]
But even if it's currently not working... Pull requests are done for develop and it's simply the wrong image.

**Comment by edm00se** [comment]
I was trying to help, looks like this isn't going through. I'll close it.

**Comment by tboerger** [comment]
Help is always welcome, but it should be more or less correct ;)

**Comment by edm00se** [comment]
I get that. You showed it wasn't, I closed it. Done and done.

I love the project, btw.

**Pull request closed without merging**
