### PR TITLE
Migrate to use jsoniter instead of encoding/json

### PR DESCRIPTION
**Pull request by zeripath**
`encoding/json` is  slow.

`jsoniter` is faster.

`jsoniter` also has a streaming interface which we can improve other parts e.g. `routers/api/v1/repo/file.go`

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by 6543** [comment]
for `build/generate-emoji.go` it's fine - but for the gitea binary can we init jsoniter.ConfigCompatibleWithStandardLibrary once?

**Comment by zeripath** [comment]
that's not initing - it's just a reference

**Comment by 6543** [comment]
```
CONTRIBUTING.md
143:  "encoding/json"

modules/templates/helper.go
11:     "encoding/json"
```

**Review by techknowlogick — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
This also needs chi to migrate to jsoniter too.

**Comment by zeripath** [comment]
https://gitea.com/go-chi/binding/pulls/1

**Comment by 6543** [comment]
@zeripath I think you can update our binding middleware here ...

**Comment by silverwind** [comment]
[`json-iterator/go`](https://github.com/json-iterator/go) is not always compatible with `encoding/json`, see their issue tracker for examples.

[`goccy/go-json`](https://github.com/goccy/go-json) may be a better alternative, it claims to be faster than `json-iterator/go`, but it's probably not as well tested as `encoding/json`.

**Comment by 6543** [comment]
we need benchmarks for gitea!!!

**Comment by zeripath** [comment]
@silverwind we only need to care about the incompatibilities that actually matter - if we're not hitting anything right now it's easy enough to handle in the future.

Not wedded to json-iterator though - looking at the code it certainly could be a lot faster.

My main reason was that it had a streaming interface but its API is not great. 

Happy to try go-json if you think that's better.

**Comment by 6543** [comment]
iterator is is opensource why not improve it upstream ... & this are now topics witch we should talk about i discord ... locking this issue now :D

**Comment by zeripath** [comment]
> we need benchmarks for gitea!!!

So in regards to JSON libraries our testsuite as a whole is actually a rather good benchmark.

It would be useful though to have a benchmark that just pushes files to a repo over the API as I know that that is something we're surprisingly slow at.

**Pull request merged**
