### PR TITLE
Update Goldmark to Goldmark 1.4.4

### PR DESCRIPTION
**Pull request by zeripath**
Update Goldmark libraries.

I've put a PR in to goldmark-highlight that should update it to use the latest chroma.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by techknowlogick** [comment]
CI fail is unrelated, but still needs to be resolved (probably for another PR though). Probably due to recent update to golangci-lint

**Comment by wxiaoguang** [comment]
> CI fail is unrelated, but still needs to be resolved (probably for another PR though). Probably due to recent update to golangci-lint

It's related, goldmark just deprecated `util.FindClosure`, so the code should be updated according to the new goldmark.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
who does deprecation in revision release :/

**Comment by zeripath** [comment]
I'll fix the deprecations later today. I'll block this until then.

**Comment by zeripath** [comment]
Lol even the file that this is deeply inspired by hasn't migrated from the deprecated function.

**Comment by zeripath** [comment]
damn this is not a simple update and will require test cases - would it be ok to simply nolint this?

**Comment by lunny** [comment]
Could we use another function?

**Comment by 6543** [comment]
It would be a refactor ... @lunny - I can have a look in this

**Comment by zeripath** [comment]
The issue is in footnoteBlockParser:

```go
func (b *footnoteBlockParser) Open(parent ast.Node, reader text.Reader, pc parser.Context) (ast.Node, parser.State) {
	line, segment := reader.PeekLine()
	pos := pc.BlockOffset()
	if pos < 0 || line[pos] != '[' {
		return nil, parser.NoChildren
	}
	pos++
	if pos > len(line)-1 || line[pos] != '^' {
		return nil, parser.NoChildren
	}
	open := pos + 1
	closes := 0
	closure := util.FindClosure(line[pos+1:], '[', ']', false, false) //nolint
	closes = pos + 1 + closure
	next := closes + 1
	if closure > -1 {
		if next >= len(line) || line[next] != ':' {
			return nil, parser.NoChildren
		}
	} else {
		return nil, parser.NoChildren
	}
...
```

This doesn't easily appear to map to the reader.FindClosure() code - as in the above the reader position appears to be at the start of the line so would need to be advanced to the pos and then reset as necessary.

So we'd need to write a couple of test cases to ensure that the code does the correct job if we were to refactor this to get rid of the deprecation.

**Comment by wxiaoguang** [comment]
ps: I can accept that we use `//nolint` to this deprecation then fix it later.

**Comment by lunny** [comment]
> The issue is in footnoteBlockParser:
> 
> ```go
> func (b *footnoteBlockParser) Open(parent ast.Node, reader text.Reader, pc parser.Context) (ast.Node, parser.State) {
> 	line, segment := reader.PeekLine()
> 	pos := pc.BlockOffset()
> 	if pos < 0 || line[pos] != '[' {
> 		return nil, parser.NoChildren
> 	}
> 	pos++
> 	if pos > len(line)-1 || line[pos] != '^' {
> 		return nil, parser.NoChildren
> 	}
> 	open := pos + 1
> 	closes := 0
> 	closure := util.FindClosure(line[pos+1:], '[', ']', false, false) //nolint
> 	closes = pos + 1 + closure
> 	next := closes + 1
> 	if closure > -1 {
> 		if next >= len(line) || line[next] != ':' {
> 			return nil, parser.NoChildren
> 		}
> 	} else {
> 		return nil, parser.NoChildren
> 	}
> ...
> ```
> 
> This doesn't easily appear to map to the reader.FindClosure() code - as in the above the reader position appears to be at the start of the line so would need to be advanced to the pos and then reset as necessary.
> 
> So we'd need to write a couple of test cases to ensure that the code does the correct job if we were to refactor this to get rid of the deprecation.

If that, I'm OK to merge it at first. But I think we have to resolve it in future version when the function will be removed.
Is there any other block things here ? Or you can remove the block label @zeripath

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
