### PR TITLE
[WIP] Compile with PIE buildmode when available

### PR DESCRIPTION
**Pull request by sapk**
This PR use `-buildmode=pie` flag for build command to provide better protection of memory at runtime.

https://docs.google.com/document/d/1nr-TQHw_er6GOQRsF6T43GGhFDelrAP0NqSS_00RgZQ/edit?pli=1#heading=h.nidcdnrtrn3n

### CODE REVIEW

**Comment by techknowlogick** [comment]
I don't think this works for the mips devices we are compiling for.

Per the document you linked `In the Go 1.6 release this is implemented for linux-386, linux-amd64, linux-arm, linux-arm64, linux-ppc64le, android-amd64, android-arm, android-arm64, android-386, or when using gccgo`. Although maybe it has changed since 1.6

**Comment by sapk** [comment]
Go1.10 also add darwin/amd64 but windows binaries are still not supported. 
I adjust to deactivate it for build command and only using it for compatible releases.

**Comment by sapk** [comment]
This seems to fail to build linux release ... I will have to look further down at it.

**Comment by sapk** [comment]
Looking at https://github.com/karalabe/xgo/blob/d164e4e53dfdc4e25de90a762d213f8d397e24a1/docker/base/build.sh#L162 for android specific (that enforce PIE binary), it seems to need some specific CGOFLAG. I will have to find a way to force them.

**Comment by techknowlogick** [comment]
Gitea uses https://github.com/techknowlogick/xgo/ xgo fork which has android & ios support removed.

**Pull request closed without merging**
