### PR TITLE
Prevent panic on error whilst getting storage

### PR DESCRIPTION
**Pull request by zeripath**
* The `.Use` of storageHandler before setting up the template renderer
causes a panic if there is an error to log.
* The error passed to `ctx.Error` in that case may contain sensitive
information and should not be rendered to the end user. We should
instead log the error and render a simple error message.
* There is no handling of missing avatars and this needs a 404. Minio
errors need to be mapped to standard golang errors such as
os.ErrNotExist.
* There is no logging when storage is set up.

Related #13159

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
I have not marked this a fixing #13159 because I am uncertain as to the root of their errors. It could simply be that the default location for avatars is now different but I think we looked very carefully at that to prevent that.

Unfortunately there was no logging so we cannot be sure what the configuration is. This PR now adds some logging.

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Damn damn damn. I got the error conversion incorrect here - this'll teach me for not actually making unit tests!

We should be mostly converting to os.PathError and checking that instead of plain os errors.

**Comment by 6543** [comment]
@zeripath I think, at this point we can invent a new error strukts ourselve :)

**Comment by zeripath** [comment]
I think if we just use errors.Is(err, os.ErrNotExist) then we can keep the convert very simple.

**Comment by techknowlogick** [comment]
Backport sent. It is #13193

**Pull request merged**
