### PR TITLE
Replace box-shadow for `floating` dropdown as well

### PR DESCRIPTION
**Pull request by silverwind**
Add `box-shadow` replacement to the `floating` dropdown variant as well, which was missed in https://github.com/go-gitea/gitea/pull/26469. The Fomantic style has `!important`, so this has to have too. Also made a tiny adjustment to shadow color on dark theme.

Screenshot 2023-08-18 at 16 40 34
Screenshot 2023-08-18 at 16 40 22

### CODE REVIEW

**Review by delvh — APPROVED** [review]
I see absolutely no difference, but if it improves something for you, I'm fine with it.

**Comment by silverwind** [comment]
It's the faint shadow outside the box. Fomantic has it as well but much less noticeable.

**Comment by delvh** [comment]
I know, I still don't see it :sweat_smile:

**Comment by silverwind** [comment]
I immediately notice this on the dropdowns, guess I have an eye for such detail 😄

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
