### PR TITLE
Show real mail in Webhooks

### LINKED ISSUE #27918: Webhooks: user email property
### Description

I am using gogs webhooks to integrate gitea events to Bitrix24.
I noticed some strange in json POST request.
```
X-Gogs-Event: pull_request
...
{
  "action": "opened",
  "number": 3,
  "pull_request": {
    ...
    "user": {
      ...
      "email": "user@noreplycompanydomain.ru",
      ...
    },
...
}
```
All structures with user info contains field **email** with wrong email. In my case sevice takes **NO_REPLY_ADDRESS** variable and put it after user name.
In [Config Cheats](https://docs.gitea.com/next/administration/config-cheat-sheet) page there is such description:
```
NO_REPLY_ADDRESS: noreply.DOMAIN Value for the domain part of the user's email address in the Git log if user has set KeepEmailPrivate to true. DOMAIN resolves to the value in server.DOMAIN. The user's email will be replaced with a concatenation of the user name in lower case, "@" and NO_REPLY_ADDRESS.
```
I checked KeepEmailPrivate property for account and it is disabled.

Also same could be discovered on test server
https://try.gitea.io/user/settings/hooks/1306

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Windows

### How are you running Gitea?

Windows build

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by JakobDev**
Regression of #25097
Fixes #27918

The API should not return the real mail of a User, if you are not logged in. Webhooks however should show the real mail. As `toUser()` is used in a lot of places, I decided that it is easier to just use a context variable to identify if the context belongs to a Webhook than refactoring half Gitea to pass an argument.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
I don't like that solution. You could get the same result with a simple `ToWebhookUser() { toUser(ctx, user, true, true) }`. But are we sure we want to ignore the users wish to not expose the email address?

**Comment by JakobDev** [comment]
> You could get the same result with a simple `ToWebhookUser() { toUser(ctx, user, true, true) }`

`ToUser` is also called by some other functions e.g. `ToRepo`, so it's not that easy. I already thought about this, but we would need to add many functions.

> are we sure we want to ignore the users wish to not expose the email address?

That's not ignored. If the User has enabled hiding the address, it will still be hidden.

**Comment by KN4CK3R** [comment]
> > You could get the same result with a simple `ToWebhookUser() { toUser(ctx, user, true, true) }`
> 
> `ToUser` is also called by some other functions e.g. `ToRepo`, so it's not that easy. I already thought about this, but we would need to add many functions.

How about using `ToUserWithAccessMode` which `ToRepo` uses?

> > are we sure we want to ignore the users wish to not expose the email address?
> 
> That's not ignored. If the User has enabled hiding the address, it will still be hidden.

Correct, my bad.

**Comment by JakobDev** [comment]
Repo was only a example. There are other objects like Issues or PullRequests, so this would involve a lot of work. Using the context is just the easiest way and I see no problems with this. I'm also not sure if a new Permission mode is the right place for that.

**Comment by KN4CK3R** [comment]
The context is the same as a global variable and using it here for control flow is bad design.

**Comment by JakobDev** [comment]
A context is not for global variables. the variables are just used within this context and are passed down the line.

**Comment by KN4CK3R** [comment]
Sure, still the context acts like a global variable (or thread local if you want) and you use it to pass variables down the callstack. That's a typical anti pattern.

https://news.ycombinator.com/item?id=24323564
> - And the worst of all is passing things that decide business logic in your context variables! First, you lose all benefits of go's static typing. Second, you will not realize all of the crazy places that a context scoped variable is coming from, have fun debugging that!

https://medium.com/@gosamv/context-patterns-antipatterns-6bc48eaf774e
> Passing required arguments a long way
Sometimes, you have a function which is very deep into the call stack, and it needs an ID or something which you know is available at a higher level. Resist the temptation to just throw it in the context: this hides what should be an explicit, required parameter.

**Comment by JakobDev** [comment]
I think in this case using a context is OK.

1. It not just passing down a single call stack. There are a lot of functions involved.
2. This just marks, that a context belongs to a Webhook. This is static and will never changed during the lifetime of the context, so you won't have to deal with typical problems of a global variable, like it's changed else where in the code.

**Comment by yp05327** [comment]
some related issues about hidden email, maybe we need a summary.
#29879
#27133

**Comment by wxiaoguang** [comment]
What do you think about " Fix missed doer #30231 " ? I think 30231 looks better and more intuitive

**Comment by wxiaoguang** [comment]
I have tested, the proper fix is  #30231 , this PR could be closed. 

-> Test webhook email #33033

**Pull request closed without merging**
