### PR TITLE
Support for grouping RPMs using paths

### LINKED ISSUE #25304: Assign a distribution to yum
### Feature Description

Sometimes we need to compile RPM packages for multiple distributions ` (el7, el9, f34 ...)`  All packages are put together and sometimes a package does not work on a particular distribution, which may lead to incorrect installation of a package not compiled for that distribution.

图片

图片

图片

After uploading:

图片

### LINKED ISSUE #27056: Installing package dependencies from RPM Package Repo fails
### Description

I have uploaded some rpm packages to my Gitea instance. Some of those packages have dependencies which are uploaded as well to the gitea package repo.

I have added my package repo to dnf.

```
# packages.rpm.distro.redhat
dnf config-manager --add-repo http://XXXX:3000/api/packages/cloned/rpm.repo
```
But have modified the `/etc/yum.repos.d/rpm.repo` and disabled gpgcheck
```
[gitea-cloned]
name=cloned - Gitea: Git with a cup of tea
baseurl=http://XXXX:3000/api/packages/cloned/rpm
enabled=1
gpgcheck=0
gpgkey=http://XXXX:3000/api/packages/cloned/rpm/repository.key
```

I have uploaded the required packages 

image

Due to simplification I now use Package 1 and Package 2
Package 1 is dependend on Package 2.

When trying to install Package 1 with dnf it correctly resolves dependencies and the source repository, but install fails due to checksum mismatch.
image

I did a bit of further analysis and found out that the filename of the downloaded file might be the reason.
All packages that are / were downloaded have the same filename `x86_64`.

When trying to install just from cache I see this error.
image

dnf is always refering to the same filename `x86_64` even if the package name is different.

Downloading the packages manually with `wget` also outputs filename (which is the last part of the URL)

`wget http://XXXX:3000/api/packages/cloned/rpm/package/package-1/1.0/x86_64`

image

Now I dont know where the rootcause is. Is gitea outputting a "wrong" filename or is dnf 

A few more annotations:
- Installing each package without dependencies one by one is working fine
- using `yum` instead of `dnf` results in the same error behaviour
- using `yumdownloader --resolve package-1` also outputs a single file named `x86_64`

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How are you running Gitea?

On-Premise with executable (no docker)

```
dnf version 4.0.9
```

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by ExplodingDragon**
The current rpm repository places all packages in the same repository, and different systems (el7,f34) may hit packages that do not belong to this distribution ( #25304 )  , which now supports grouping of rpm.

图片

Fixes #25304 .
Fixes #27056 .

Refactor: [#25866](https://github.com/go-gitea/gitea/pull/25866)

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by KN4CK3R** [comment]
I'm unsure if it is good to replicate the Debian style here. The RPM repo does not have fixed parameters like `distribution` or `component`. Some may just need one, some may need more parameters to structure their packages. It may be better to keep this optional but allow flexible parameters like the container registry does. The container can be named `domain/owner/package` but `domain/owner/my/flexible/named/package` is supported too.
The RPM registry would need more advanced routing then (like the container registry does) but the other code just need to respect the "flexible path" which defaults to `""` like it is at the moment.

**Comment by ExplodingDragon** [comment]
> I'm unsure if it is good to replicate the Debian style here. The RPM repo does not have fixed parameters like `distribution` or `component`. Some may just need one, some may need more parameters to structure their packages. It may be better to keep this optional but allow flexible parameters like the container registry does. The container can be named `domain/owner/package` but `domain/owner/my/flexible/named/package` is supported too. The RPM registry would need more advanced routing then (like the container registry does) but the other code just need to respect the "flexible path" which defaults to `""` like it is at the moment.

I reimplemented the route reference docker and it should now support uploading RPM under any path.

**Comment by ExplodingDragon** [comment]
@KN4CK3R After a period of use, this PR is ready to begin reviewing.

**Review by lafriks — APPROVED** [review]

**Comment by KN4CK3R** [comment]
There are some flaws I created a fix-PR for this PR but forgot to block this one, sorry. I will send the fix as a new PR.

**Comment by delvh** [comment]
Erm… Why did Giteabot mark the PR as breaking?
Why does it even mark a PR as breaking in the first place?
I don't think that feature exists…

**Pull request merged**
