### PR TITLE
Run processors on whole of text

### PR DESCRIPTION
**Pull request by zeripath**
There is an inefficiency in the design of our processors which means that Emoji
and other processors run in order n^2 time.

This PR forces all of the processors to process the entirety of text node before passing
back up. The fundamental inefficiency remains but it should be significantly
ameliorated.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by lunny** [comment]
It's better to add a benchmark.

**Comment by zeripath** [comment]
Benchmark added.

**Review by 6543 — APPROVED** [review]
142208659396 ns/op -> 1195548 ns/op

**Comment by zeripath** [comment]
Things can be further improved by not having the processors reprocess text that they have already seen - i.e. track the next sibling and don't do anything till that happens. However that would require more changes to the processor.

**Comment by 6543** [comment]
@zeripath this pull as is can be backported ... refactor should be done later :)

**Review by khmarbaise — APPROVED** [review]

**Pull request merged**
