### PR TITLE
Increase max length of org team names from 30 to 255 characters

### PR DESCRIPTION
**Pull request by tobiasbp**
This PR modifies the structs for editing and creating org teams to allow team names to be up to 255 characters. The previous maximum length was 30 characters.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]

**Comment by silverwind** [comment]
@techknowlogick do we need the migration mentioned in https://github.com/go-gitea/gitea/issues/31241#issuecomment-2153447355?

**Comment by techknowlogick** [comment]
@silverwind nope, the database already has that length, this PR only modifies the validation rules for creation/editing of the team names.

**Comment by techknowlogick** [comment]
Thanks @tobiasbp!

**Comment by wxiaoguang** [comment]
Let's backport it

**Comment by silverwind** [comment]
It seems no one actually tested it works. We need to be more dilligent and not assume that the contributor has actually tested their change.

**Pull request merged**
