### PR TITLE
Move swagger-ui under /api/v1

### LINKED ISSUE #2745: Swagger should be reserved when creating users (or: move /swagger to a different path)
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/swagger/this-exists - https://try.gitea.io/swagger

## Description

At the moment, if you try to access /swagger, it will not show the organization I created, but the org does exist. In order to address this issue, we should either forbid users creating new orgs or users with the name `swagger` (adding it to the list of blacklisted usernames), or move /swagger somewhere else (but thus generating some linkrot on gitea instances - perhaps redirect to new URL if there is no org, and show the org if there is one)

### PR DESCRIPTION
**Pull request by sapk**
Fix #2745 & update swagger-ui version

### CODE REVIEW

**Comment by thehowl** [comment]
As I said in #2745, for backwards compatibility I'd say it's best to redirect users to /api/swagger when they try to access the org or user on /swagger, and only show the org or user when there actually is one.

**Comment by sapk** [comment]
I don't think that it is really usefull to keep a backward compatibility on documentation link. The JSON containing the API specification that could be used by other system hasn't move. 

Before merging, I forgot to update the link in the footer template.

**Comment by thehowl** [comment]
yeah, that's true, however my concern is that this pr will effectively 404 all of the current links to /swagger around the web

**Comment by sapk** [comment]
@thehowl there should be only in the footer inside gitea itself. I will update other docs links like https://github.com/go-gitea/docs/blob/adef669bcc10c63300692839eb1b57f001777ee2/config.yaml#L34

**Comment by strk** [comment]
Is `public/vendor` to be managed manually like in this PR or shouldn't there be a vendoring tool configuration updated ? Other than that, here's my trusted LGTM

**Comment by lafriks** [comment]
@strk yes public vendor is currently managed manually.

LGTM

**Comment by sapk** [comment]
@strk I have added the task in the makefile for easing the process but it is better to keep it under manual update since there is also a template (serve under /api(/v1)/swagger) manually derivated from index.html to work under that url. Doing it manually also ensure that the specs at still working with the swagger-ui display.

For information, You can also open the swagger-ui interface directly via /vendor/assets/swagger-ui/index.html and it will load the specs but that's not a pretty url ^^.

**Comment by lafriks** [comment]
Make LG-TM work again

**Pull request merged**
