### PR TITLE
Wrap unless-check in docker manifests

### PR DESCRIPTION
**Pull request by jolheiser**
Should fix the following:
> failed to render template: Evaluation error: Helper 'unless' called with wrong number of arguments, needed 2 but got 3

https://go.dev/play/p/h7bt7MWKTcv

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
Does this method have an overloaded version?
The error message explicitly states that it expects **2** parameters…
I don't know if it'll work with a single one.

**Comment by jolheiser** [comment]
Good question....
The example seems to indicate a single argument https://github.com/aymerick/raymond#the-unless-block-helper

**Review by delvh — APPROVED** [review]
Well, in the worst case, `1.19.0-rc1` still won't be released :grin:

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖

**Pull request merged**
