### PR TITLE
Kd/fix team avatar aspect ratio

### PR DESCRIPTION
**Pull request by kdumontnu**
Fixes broken aspect ratio for avatars in org members list admin page.

### Before:
image

### After:
aspect ratio is preserved for avatar (with fixed width)
min-width is set to prevent single-character text lines
image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
@kdumontnu pleace "Update Branch"

**Comment by zeripath** [comment]
please update the branch. In general it's better if you allow maintainers to push to the branch.

**Comment by techknowlogick** [comment]
@zeripath this fork belongs to an org, so the standard maintainer checkbox isn’t an option :(

**Comment by kdumontnu** [comment]
@zeripath @6543 @techknowlogick all set

**Pull request merged**
