### PR TITLE
move CSS build to webpack

### PR DESCRIPTION
**Pull request by silverwind**
- added new 'make webpack' target
- deprecated 'make js' and 'make css'
- extend webpack config to load the less files
- updated docs

I had to rename the source file of `arc-green.less` to avoid generating a useless JS entrypoint via webpack-fix-style-only-entries which would not work with different source/destination filenames. I hear that there should be cleaner solutions possible once we upgrade to Webpack 5.

### CODE REVIEW

**Comment by silverwind** [comment]
Partially unrelated, but I reworked the "Building Gitea" in CONTRIBUTING.md to just link to the hacking guide as info in it was partially outdated.

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Rebased and squashed.

**Comment by zeripath** [comment]
@Silverwind is there any way we can stop having to rebuild fomantic and the webpack every time we do make build?

My machine is FAST but it's taking a considerable amount of time to test one line changes because of this.

(We could also do with something similar for go generate - it's a real shame that bindata is regenerated despite no changes - I might take a look at that...)

**Comment by silverwind** [comment]
@zeripath I thought https://github.com/go-gitea/gitea/commit/8ca07305fb0583e6121c9d56edb05cbf7dd9d7b5 fixed those useless rebuilds. Try running `make --trace --question <target>` to see why it's building those particular targets.

**Comment by silverwind** [comment]
Ah, I think I found something that triggers useless fomantic rebuilds, testing..

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/9999 for possible workaround.

Regarding `generate`: Yes, I'd also prefer it to run on-demand but @guillep2k had some concerns about it last time I tried that, see https://github.com/go-gitea/gitea/pull/9114#issuecomment-558740228.

**Comment by zeripath** [comment]
I was thinking of doing it in the generate functions themselves... They're the thing that is doing the work.

**Comment by silverwind** [comment]
@zeripath possible, but I think `make` is ideal for timestamp checks like that.

Rebased here and also added a `touch node_modules` in case npm fails to update that for whatever reason.

**Review by guillep2k — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Rebased

**Pull request merged**
