### PR TITLE
Fix chardet bug

### PR DESCRIPTION
**Pull request by lunny**
But for less text, the chardet maybe give wrong result.

### CODE REVIEW

**Comment by jonasfranz** [comment]
@lunny Why is this issue blocked, should it be moved to 1.7.0?

**Comment by lunny** [comment]
This is blocked because I found the detection is not always successful. This will be replaced by #4950

**Comment by lafriks** [comment]
Oh, I did not see that there is already PR about that issue

**Comment by lunny** [comment]
@lafriks I forgot it also until @JonasFranzDEV 's comment. 🤣

**Comment by jonasfranz** [comment]
Fixed by #4950

**Pull request closed without merging**
