### PR TITLE
Fix code view (diff) broken layout

### LINKED ISSUE #22911: Code diff UI goes misalignment with code review comments
### Description

https://jsfiddle.net/ob0y2x83/

The `padding` inside `td` makes the widths of `td` become larger.

<details>

```html
<table style="width: 100%">
  <tr>
    <td style="width: 10px;">a</td>
    <td style="width: 0"></td>
    <td style="width: 10px;">b</td>
    <td style="width: 49%">long content</td>
    
    <td style="width: 10px;">a</td>
    <td style="width: 0"></td>
    <td style="width: 10px;">b</td>
    <td style="width: 49%">long content</td>
  </tr>
  <tr>
    <td colspan="4">
      <div style="width: 30%"> 
        <div style="padding-left: 100px;">
          with padding
        </div>
      </div>
    </td>
    <td colspan="4">
      <div style="width: 30%"> 
        <div style="padding-left: 100px;">
          with padding
        </div>
      </div>
    </td>
  </tr>
</table>

<hr>

<table style="width: 100%">
  <tr>
    <td style="width: 10px;">a</td>
    <td style="width: 0"></td>
    <td style="width: 10px;">b</td>
    <td style="width: 49%">long content</td>
    
    <td style="width: 10px;">a</td>
    <td style="width: 0"></td>
    <td style="width: 10px;">b</td>
    <td style="width: 49%">long content</td>
  </tr>
  <tr>
    <td colspan="4">
      <div style="width: 30%"> 
        <div style="padding-left: 0;">
          no padding
        </div>
      </div>
    </td>
    <td colspan="4">
      <div style="width: 30%"> 
        <div style="padding-left: 0;">
          no padding
        </div>
      </div>
    </td>
  </tr>
</table>
```

</details>

image

image

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #22911

I think it's ready for review now, feel free to test it, welcome to help to improve.

### Before

image

### After

image

### CODE REVIEW

**Comment by silverwind** [comment]
Make sure to test the code expansion via these buttons:

Screenshot 2023-04-01 at 05 35 53


This stuff is sensitive to column number.

**Comment by wxiaoguang** [comment]
> Make sure to test the code expansion via these buttons:

Yes, I have tested, that's in `blob_excerpt.tmpl`

**Comment by jpraet** [comment]
Thanks @wxiaoguang. I have done some testing and it looks like this fixes the problem without any noticeable regressions.

So, functionally it works as expected. I don't feel experienced enough with html / css to approve the PR myself from the technical point of view though.

**Comment by wxiaoguang** [comment]
Since it works, I hope I can receive a LGTM from you later. No hurry, take enough time to test till you feel it works really well.

And no worry, I will fix all bugs caused by me.

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
