### PR TITLE
Update outdated label to use Fomantic UI style

### PR DESCRIPTION
**Pull request by ivanvc**
This is an update to #13148. As I mentioned the CSS could be improved, and I didn't realize styling could have been done by just using native elements from Fomantic UI.

### CODE REVIEW

**Comment by lunny** [comment]
Is the UI same as before?

**Comment by silverwind** [comment]
Got a screenshot?

**Comment by ivanvc** [comment]
Again, referencing my previous PR (and https://github.com/go-gitea/gitea/pull/13148#issuecomment-709416432). I noticed some unnecessary css/styling for labels that could be native Fomantic UI elements. I initially just change the one I recently added (the outdated label), but went ahead and updated the rest of them. I'm attaching screenshots from Firefox and Chrome for each of the affected elements, and both using the defualt theme and arc-green.

Emphasis in the labels:
* Pending
* Review
* Collaborator
* Owner
* Outdated

## Chrome default theme:
Screenshot from 2020-10-19 10-26-48
Screenshot from 2020-10-19 10-26-40
Screenshot from 2020-10-19 10-26-32

## Chrome arc-green theme:
Screenshot from 2020-10-19 10-27-15
Screenshot from 2020-10-19 10-27-07
Screenshot from 2020-10-19 11-06-38

## Firefox default theme:
Screenshot from 2020-10-19 10-48-29
Screenshot from 2020-10-19 10-48-01
Screenshot from 2020-10-19 10-47-54

## Firefox arc-green theme:
Screenshot from 2020-10-19 10-49-30
Screenshot from 2020-10-19 10-49-21
Screenshot from 2020-10-19 10-49-16

@silverwind, @lunny: updated the PR with screenshots :)

**Comment by ivanvc** [comment]
Crap, broke the frontend linter, will fix it...

**Review by silverwind — APPROVED** [review]

**Comment by 6543** [comment]
@ivanvc pleace resolve conflicts :)

**Comment by ivanvc** [comment]
@6543 done!

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
