### PR TITLE
Make token deduplication optional for the repo indexer

### PR DESCRIPTION
**Pull request by guillep2k**
This PR solves #7825 by _optionally_ removing the `unique` filter from the repository indexer analyzer.

The thing is: the current behaviour directly tracks to #3452, where the `unique` filter was added for the sake of space saving. So, I guess there _is_ a case where this is an acceptable trade-off. That's why I introduced an app.ini option (`REPO_INDEXER_DEDUPLICATE`) to make the change optional to avoid introducing problems to users that count on this.

However, I didn't notice much of a setback in the index size with this change in my tests (the resulting index was even a little smaller in my case):

* With the `unique` filter active (no patch): 26,935,296
* With the `unique` filter removed (with this patch): 26,136,576

I guess it really depends on the actual repository.

If the app.ini option is not desirable, I'll just remove it.

### CODE REVIEW

**Comment by guillep2k** [comment]
One thought:  is it possible that the size improvements experienced by @ethantkoenig were due to the action of actually rebuilding the index, and not because of the `unique` filter?

**Comment by guillep2k** [comment]
Or perhaps the gains came mostly from the fact that the `_all` mapping was removed as well. It would be nice to test this with a larger set of repositories.

**Comment by lunny** [comment]
@guillep2k I think the size improvement is because removed `_all` mapping

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k I think the size improvement is because removed `_all` mapping

@lunny I think so too, but I couldn't find anyone with a large index to try this change. If that's the case, then making the "unique" token optional makes no sense: it just should be removed. What you think?

**Comment by lafriks** [comment]
I also think that there is not much point in adding such things as configurable. We already have too many things in app.ini :)

**Comment by guillep2k** [comment]
> 
> 
> I also think that there is not much point in adding such things as configurable. We already have too many things in app.ini :)

@lunny, @lafriks Please check out my other PR, then: #7878. Much simpler.

**Pull request closed without merging**
