### PR TITLE
Implement pasting image from clipboard for browsers that supports that

### LINKED ISSUE #3032: Images in issues (copy/paste and reference)
- Gitea version (or commit ref): dab2b35

## Description

At the moment, there's no way to cut and paste an image into an issue on Gitea, whereas on Github we can comfortably do that. It's critical to the workflow of any team that is developing web applications to be able to cut and paste screenshots directly into the issue.

Second, we've been noticing that (a) the filenames of attachments change on upload, so there is no way to say, "hey check out file myscreen.png" and; (b) there is no way to point -- like we do in Github issues -- to files, inline with your issue text. The final outcome here is that there's no effective way to point someone to an attachment on the issue.

Perhaps we can implement more of a Github approach where as you upload attachments they are inlined as links? This was very useful in our previous workflows.

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #3032 

Implemented in new issue text area and when adding issue/pr comments

### CODE REVIEW

**Comment by lunny** [comment]
It seems it's not work for me. Chrome 70.0.3538.77 on macOS

**Comment by lafriks** [comment]
@lunny do you get any error in JavaScript console?

**Comment by lunny** [comment]
@lafriks no any error on console.

**Comment by lafriks** [comment]
@lunny can you describe steps you did?

**Comment by lafriks** [comment]
@lunny I just tested and it worked on both chrome and safari on Mac. Try pressing Ctrl+F5 or clearing cache, could be browser was using cached javascript version

**Review by lunny — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
