### PR TITLE
ssh bug fix #1517

### LINKED ISSUE #1517: Configuring time.FORMAT breaks ssh
- Gitea version (or commit ref): a2d365c8
- Git version: 2.11.0
- Operating system: CentOS-6.9
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Lately SSH access to a gitea instance of ours tracking the master branch has been broken. Doing a clone or pull over ssh simply hangs, with `gitea serv key-X --conf=...` blocking on `waitid(...)` and it's spawned `git-upload-pack org/repo.git` blocking on `read(0, ...)`.

After a little digging, I tried running the expected `gitea serv ...` command as the gitea user:
 ```
$ SSH_ORIGINAL_COMMAND="git-upload-pack '/org/test.git'" /usr/local/bin/gitea serv key-1 --config=/path/to/conf/app.ini
2017/04/20 03:45:15 [T] Custom TimeFormat: 2006-01-02 15:04:05 CET
00f263b78e06ee70f741ce1360f5c6c2e15a09df4d3e HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed symref=HEAD:refs/heads/master agent=git/2.11.0
003f63b78e06ee70f741ce1360f5c6c2e15a09df4d3e refs/heads/master
0000
```
The first line in the output is causing the problem - it's written to stdout, which git expects to "own".

Commenting out `[time]` -> `FORMAT` in the configuration or commenting out the `log.Trace("...")`-call in `modules/setting/setting.go` restores SSH access to gitea.

### PR DESCRIPTION
**Pull request by lunny**
will fix #1517

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by strk** [comment]
I don't like this hushing of logs to fix the ssh hanging. What about closing stdout/stderr from the "serv" command instead ? Would that work ?

**Comment by lunny** [comment]
@strk do you know how to do that?

**Comment by strk** [comment]
Did you try `os.Stdout.Close()` ?

**Comment by lunny** [comment]
No. And I think it's not a right usage for `os.Stdout`.

**Comment by strk** [comment]
Why do you think it is not right ?

**Comment by lunny** [comment]
I never use it.

**Comment by bkcsoft** [comment]
IMO this is invalid, `gitea serv` should setup `modules/log` to send logs to `/api/internal/log`so they are written from `gitea web` instead.

**Comment by lunny** [comment]
see #1517, the description shows the log on the console.

**Comment by mnsh** [comment]
For the record: when trace logging to the console is enabled, the "custom time format" message is the only one logged by `gitea serv`. `gitea web` remains chatty.

So, `gitea serv` is already doing something to avoid logging to stdout - maybe use that same method to silence the time format message in `serv` mode?

**Comment by bkcsoft** [comment]
Right, I'm not saying it's not a problem. I'm saying the solution can not be to remove part of the logging for the entire application. And this is a part of a larger problem, where `gitea serv` actually logs _to the user_ instead of to file.

**Comment by sapk** [comment]
Couldn't we check the state of `log.GitLogger` at this stage and use it instead if not null ? I haven't enough global picture analysis to know if it is a stupid question. ^^ 
Using a internal api like said before is also a good solution.

**Comment by strk** [comment]
I also think that removing logging traces is not the correct solution here. Hadn't done a full analysis to tell what the correct solution would be though.

**Comment by appIeboy** [comment]
@lunny is stupid

**Pull request closed without merging**
