### PR TITLE
Fix: passkey login not working anymore

### LINKED ISSUE #32595: Passkey login not working anymore
### Description

When trying to login with my Passkey to gitea.com I now get a http 403 error. Updating the passkey didn't help.

### Gitea Version

 1.23.0+dev-671-gc3dedcffa7 

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://gitea.com/

### Database

None

### PR DESCRIPTION
**Pull request by hiifong**
Quick fix #32595, use authenticator auth flags to login

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Yes, you will need to store the flags. This will break for everyone who doesn't have backup eligible flags.

**Review by lafriks — APPROVED** [review]

**Comment by james-d-elliott** [comment]
Looking at the way you're using this we can probably simplify this with tooling from the go-webauthn side, the binary value of the flags is already available so you don't need to convert it, but we can add a convenience method to derive the flags when reconstructing the credential.

**Comment by wxiaoguang** [comment]
> we can probably simplify this with tooling from the go-webauthn side, the binary value of the flags is already available so you don't need to convert it, but we can add a convenience method to derive the flags when reconstructing the credential. Let me know if this is preferable?

If there could be a simple and compatible (backward&forward) solution, it definitely helps a lot. Indeed as a library downstream, I think the fewer details the downstream knows, the more robust the system is. Thank you very much!

**Comment by james-d-elliott** [comment]
Inspect the change in https://github.com/go-webauthn/webauthn/pull/337 and see what you think. I still need to update the docs and will do that time permitting. It's worthwhile to note that I plan on releasing soon but have one other fix I'd like to merge first.

**Comment by wxiaoguang** [comment]
> Inspect the change in [go-webauthn/webauthn#337](https://github.com/go-webauthn/webauthn/pull/337) and see what you think. I still need to update the docs and will do that time permitting. It's worthwhile to note that I plan on releasing soon but have one other fix I'd like to merge first. It adds an additional field which you should just backup `Flags.Raw` which can restore the whole of the `Flags` field with `webauthn.NewCredentialFlags()`
> 
> Also it's worth noting I personally recommend storing the credential attestation (field named `Attestation`), using json encoding to a TEXT/BYTEA column. I personally also encrypt it in all of my implementations as well as the pub key to avoid database tampering, but depends on your tooling if this is practical.
> 
> You don't need to restore it each time, but it will allow you to validate the attestation at a later date if you decide to leverage metadata. I can also provide some fairly decent recommendations on how to handle this, though you can also expect that the recommendations will make their way into the library as well.

Thank you very much. After reading the code, I think maybe the current struct types are enough. We could just json encode/decode the flags.

Still a question in my mind, how could we recover the existing users without flags correctly? Should "setting BackupEligible=true" for them be enough?

**Comment by james-d-elliott** [comment]
> Still a question in my mind, how could we recover the existing users without flags correctly? Should "setting BackupEligible=true" for them be enough?

If I understand the issue correctly you're wondering how to deal with previously stored credentials that may be in a state that is not serviceable. In theory the best option here would be to use a default value for the relevant column of NULL, and if it's NULL you add intermediary logic to automatically add the values during the login phase.

If my recollection is correct before you validate the login you can see the challenge response from the authenticator where you can copy those values. If you need help finding that let me know and I'll take a look in about 12 hours.

Effective steps:

1. Add the column(s) with default values of NULL.
2. If the columns are NULL:
  1. During a login copy the values from the challenge.
  2. Store the values in the database with an UPDATE.

**Comment by wxiaoguang** [comment]
> In theory the best option here would be to use a default value for the relevant column of NULL, and if it's NULL you add intermediary logic to automatically add the values during the login phase.

Then what this PR did is not right .......

> During a login copy the values from the challenge.

Maybe the last question: how to get the flags value from the challenge? I am not familiar with the code base and haven't figure out the key point to get the flags from the login request.

**Comment by james-d-elliott** [comment]
> Hmm, get it from protocol.ParseCredentialRequestResponse => parsedResponse.Response.AuthenticatorData.Flags, is it right?

That's correct.

**Comment by wxiaoguang** [comment]
Thank you for your help, finally I think I somewhat could understand the details now.

Now we have 2 commits:

* c5a32f4fa462c6799a8ea5dedb5133e84e1eca1c revert unnecessary changes and make some necessary preparations, not that important
* 5eeac469dc9bf609f578bc306882d6cb22080f20 use the default authenticator flags when login, also added some comments there


I think we could resolve the problem now (the same behavior as webauthn 0.10), and leave the database migration to another PR (or if it doesn't really cause security problem, maybe we could just keep using the authenticator auth args without really storing them?)

**Comment by hiifong** [comment]
@wxiaoguang Still can't use passkey to log in to Gitea.

https://github.com/user-attachments/assets/20f10eaa-55b3-47e3-a8f8-f36dd12c20fa

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Confirmed that 555577e0e648c52a6f5eb03979110a8be57606e5 "fixes" the problem.

**Comment by DorianCoding** [comment]
On version 1.23.1, Bitwarden does not detect the passkey on first login page but does after logging succesfully as 2FA. Maybe some connection is broken between the two.

**No passkey found when "logging with passkey":**
infos
**However it works after login as 2FA**
key

Thanks.

**Comment by wxiaoguang** [comment]
> On version 1.23.1, Bitwarden does not detect the passkey on first login page but does after logging succesfully as 2FA. Maybe some connection is broken between the two. The website runs on https://
> 
> **No passkey found when "logging with passkey":**
> **However it works after login as 2FA** 
> Thanks.

The initial passkey support was add by " Add Passkey login support #31504 " (I haven't carefully looked into the details),  @anbraten do you have some ideas?

**Comment by DorianCoding** [comment]
> > On version 1.23.1, Bitwarden does not detect the passkey on first login page but does after logging succesfully as 2FA. Maybe some connection is broken between the two. The website runs on https://
> > **No passkey found when "logging with passkey":**
> > **However it works after login as 2FA**
> > Thanks.
> 
> The initial passkey support was add by " Add Passkey login support #31504 " (I haven't carefully looked into the details), @anbraten do you have some ideas?

Thanks for your quick answer.

The difference is on logging:
```
{"publicKey":{"challenge":"4KXVvpzyv7f98AIIWAyYDD6g9M0sBfxpz9Yo5bUDY9c","timeout":120000,"rpId":"xxxxxxx","userVerification":"discouraged"}}
```
And on 2FA
```
{"publicKey":{"challenge":"IxjvbxQipwKAIimB-ZRNrUz-iGDNWrK1zDSUSSm__RA","timeout":120000,"rpId":"xxxxxx","allowCredentials":[{"type":"public-key","id":"K2cxLFxKS8ONfdJP5ePZnQ"}],"userVerification":"discouraged"}}
```

Probably one solution would be to put userVerification to "preferred", at least for one sign-in (which is safer btw). It seems also it might cause some password managers to hide some keys.

**Pull request merged**
