### PR TITLE
Memory usage improvements and lower minimal git requirement to 1.7.2 (#3013)

### PR DESCRIPTION
**Pull request by lafriks**
Backport to 1.3

### CODE REVIEW

**Comment by strk** [comment]
LGTM

**Comment by lunny** [comment]
When I see https://github.com/go-gitea/git/pull/90/files, I think this is unnecessary. There are some risk to send an enhancement PR back port to 1.3.

**Comment by lunny** [comment]
We only need the change on
```diff
 -	GitVersionRequired = "1.8.1.6"
 +	GitVersionRequired = "1.7.2"
```

**Comment by strk** [comment]
Those additional files are just _tests_ (and CI/drone) related. Where's the risk you see ?

**Comment by lafriks** [comment]
@lunny there is either all or nothing here :)

**Comment by lunny** [comment]
oh, Yes. LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
