### PR TITLE
[ssh] fix the config specification in the authorized_keys template

### PR DESCRIPTION
**Pull request by das7pad**
The gitea flags must appear in front of the gitea command. Otherwise they are ignored.

```
# docker run --rm -it --entrypoint gitea gitea/gitea serv --config /my/cfg --help | grep CustomConf
     CustomConf:  /data/gitea/conf/app.ini
# docker run --rm -it --entrypoint gitea gitea/gitea --config /my/cfg serv --help | grep CustomConf
     CustomConf:  /my/cfg
```

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM bot

**Comment by techknowlogick** [comment]
@das7pad thanks for PR, could you send a backport PR to the release/v1.9 branch with these changes?

**Comment by das7pad** [comment]
A backport for v1.9 landed in #8193.

**Comment by 6543** [comment]
@techknowlogick add label:backport/done ?

**Pull request merged**
