### PR TITLE
Add finalizers to ensure that repos are closed and blobreaders are closed

### PR DESCRIPTION
**Pull request by zeripath**
It may be prudent to add runtime finalizers to the git.Repository and
git.blobReader objects to absolutely ensure that these are both properly
cancelled, cleaned and closed out.

This commit is an extract from #19448

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
There could be an error log to tell developers that the resource is not closed correctly. Otherwise this patch only hide problems.

**Comment by lunny** [comment]
I don't think it's a good idea to do that. We should find the real problem.

**Comment by zeripath** [comment]
> I don't think it's a good idea to do that. We should find the real problem.

I have no information to suggest that we have any leaks, nor that we should rely on finalizers to deal with them.

However, if we do have leaks - it is infinitely better for a finalizer to take care of them than to have a leak there.

But I do take your point that this could hide a leak - which isn't great so to that end I have pushed a commit that would add some warnings IF the finalizer were to be relied on.

**Review by wxiaoguang — APPROVED** [review]

**Comment by 6543** [comment]
I just wonder if this cost us performance?

**Comment by zeripath** [comment]
So there will probably be a small perf hit:

1. The addition of locks on the Repository will have some effect.
2. The GC will hit these objects twice. So in the finalizer it may be sensible to nil out as much of the struct as we can.

Now... the addition of locks is going to be helpful because if this gets merged we can try not opening the batch and batchcheck readers until they're actually first called for.

**Comment by Gusted** [comment]
> 2\. The GC will hit these objects twice.

We should remove the finalizer on the object on the `Close()` calls to avoid this as much as possible.

**Comment by Gusted** [comment]
Small note: since when are backports merged before the normal PR are merged?

**Comment by zeripath** [comment]
OK @Gusted I've setFinalizer(nil) for these structs on close. (except the go-git variant as I am fairly sure that the storage can be reopened e

**Comment by ashimokawa** [comment]
The backport version #19496 introduced a major memory leak.

I am not sure if the recent commits added this one would fix it.

**Review by 6543 — CHANGES_REQUESTED** [review]
https://github.com/go-gitea/gitea/pull/19659

**Comment by wxiaoguang** [comment]
FYI, I added a `Context.Close()` recently, it might help for closing http request context resources. Well, if there are some resources really leaked, the `Close` can not help them. And the reason why the finalizers caused more memory leaks needs to be investigated if it's really the case.

https://github.com/go-gitea/gitea/blob/cd99540cdcb38f53c7329218d3a21ed974f520c2/modules/context/context.go#L78-L86

**Pull request closed without merging**
