### PR TITLE
Statically compile the binaries

### PR DESCRIPTION
**Pull request by tboerger**
~~To also provide static binaries I have integrated 3 different flavors
for now. We got so far static, tidb and sqlite. I think the naming is
quite obvious.~~

Now we got really static compiled binaries that should also work on older linux distributions.

Signed-off-by: Thomas Boerger <thomas@webhippie.de>

### CODE REVIEW

**Comment by lunny** [comment]
build failed

**Comment by tboerger** [comment]
The static flags won't work for the darwin target.

**Comment by tboerger** [comment]
```
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-amd64
gitea-master-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=c3c0bfb58c61708854baa1cac0cb8c0a057084be, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-386
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-386
gitea-master-linux-386: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=a71b677b924f887e25e78c9a741b2443cff262db, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-arm-5
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-arm-5
gitea-master-linux-arm-5: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=01b57fe0bc56092c9fe367d9c3320e7094ffb647, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-arm-6
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-arm-6
gitea-master-linux-arm-6: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=e3fb65471377d6ca8e071d221367459c22d71c1e, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-arm-7
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-arm-7
gitea-master-linux-arm-7: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=4eeb43f0b80b9a599b1ea8034c8fff56062b8c38, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-arm64
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-arm64
gitea-master-linux-arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, for GNU/Linux 3.7.0, BuildID[sha1]=10a50db83b11a363b0a9565a6c1267ac476bfa15, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-mips
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-mips
gitea-master-linux-mips: ELF 32-bit MSB executable, MIPS, MIPS32 rel2 version 1, statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=ff06ab1ef23a309fe1ae514b2301d965ce7eb223, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-mips64
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-mips64
gitea-master-linux-mips64: ELF 64-bit MSB executable, MIPS, MIPS64 rel2 version 1, statically linked, BuildID[sha1]=bf612715c91fe973dbe0d6d4d8040b0bfa18b138, for GNU/Linux 3.2.0, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-mips64le
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-mips64le
gitea-master-linux-mips64le: ELF 64-bit LSB executable, MIPS, MIPS64 rel2 version 1, statically linked, BuildID[sha1]=a3404024386b7179cf30b89e43e35423e55f4dea, for GNU/Linux 3.2.0, not stripped
root@66368096fb5a:/mnt/dist/binaries# ldd gitea-master-linux-mipsle
	not a dynamic executable
root@66368096fb5a:/mnt/dist/binaries# file gitea-master-linux-mipsle
gitea-master-linux-mipsle: ELF 32-bit LSB executable, MIPS, MIPS32 version 1, statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=f78299deba24f1de541d3b3e46b78c9e5f0784d2, not stripped
```

**Comment by lunny** [comment]
trusted LGTM

**Comment by andreynering** [comment]
Trusted LGTM

**Comment by lunny** [comment]
fix #551

**Pull request merged**
