### PR TITLE
Clone panel overflow

### PR DESCRIPTION
**Pull request by 0x1793d1**
When both SSH and HTTPS are enabled, the clone panel is not large enough to hold all its contents.

I suggest to increase the size from 350px to 400px.

### CODE REVIEW

**Comment by techknowlogick** [comment]
@0x1793d1 Thank you for your PR 😄 are you able to include a screenshot of before/after changes?

**Comment by 0x1793d1** [comment]
Sure!

**Before:**
before

**After:**
after

**Review by lafriks — APPROVED** [review]

**Comment by adelowo** [comment]
I think the fix proposed in https://github.com/go-gitea/gitea/issues/5072 ( issue ) is better

**Comment by kolaente** [comment]
I'd agree with @adelowo .

**Review by lafriks — CHANGES_REQUESTED** [review]
As per comments

**Comment by lunny** [comment]
files conflicting.

**Comment by 0x1793d1** [comment]
It seems that the 1.6 version fixed this. I don't have the problem anymore.

**Comment by lunny** [comment]
So let's close this one and feel free to reopen it.

**Pull request closed without merging**
