### PR TITLE
Add maintainer label for docker file

### PR DESCRIPTION
**Pull request by appleboy**
`MAINTAINER` has been deprecated for docker.

### CODE REVIEW

**Comment by lafriks** [comment]
@appleboy should it be same as in copyright `The Gitea Authors`?

**Comment by appleboy** [comment]
Change to `Gitea Authors`? right?

**Comment by lunny** [comment]
@appleboy agree with @lafriks otherwise LGTM

**Comment by appleboy** [comment]
Done and rebase.

**Comment by lafriks** [comment]
LGTM

**Comment by sapk** [comment]
LGTM
Could we setup an alias like security@gitea.io to add. Ex: maintainers@gitea.io or docker@gitea.io ? A cool hack could be to have it send to a discord channel.

**Comment by appleboy** [comment]
@sapk Can't see any API from zoho document to trigger webhook after we got the email.

https://www.zoho.com/mail/help/api/

**Pull request merged**
