### PR TITLE
Do not set `Accept` header twice

### PR DESCRIPTION
**Pull request by KN4CK3R**
Revert #28550

Don't add the `Accept` header twice.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
How about removing another `Accept` to not make maintainers confusing?

**Comment by KN4CK3R** [comment]
Then you would have to set that header on every call which is the opposite of what should be done.

**Comment by lunny** [comment]
> Then you would have to set that header on every call which is the opposite of what should be done.

Why not? It will be clearer than before?

**Comment by KN4CK3R** [comment]
How is it clearer to set a mandatory value outside a method called by every place? Currently we have a method `createRequest` every caller uses which sets that mandatory value.

**Comment by lunny** [comment]
> How is it clearer to set a mandatory value outside a method called by every place? Currently we have a method `createRequest` every caller uses which sets that mandatory value.

Only 4 places invoking `createRequest`, I think it's clear that removing `req.Header.Set("Accept", MediaType)` in the function and add it to the function parameter header map.

**Comment by KN4CK3R** [comment]
Ok, I disagree on that one.

**Comment by lunny** [comment]
Anyway, let's merge this one first.

**Pull request merged**
