### PR TITLE
Change review buttons to icons to make space for text

### LINKED ISSUE #20922: Distorted PR changes UI with german localization
### Description

After an update from 1.16.x to 1.17.1, the menu of the PR changes page is distorted with German localization. Hitting Ctrl+F5 doesn't change anything. The UI looks normal if i switch to English.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

German:

image

English:

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Downloaded from the release page, running as a service via systemd

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by silverwind**
The layout on the review code view was broken depending on length of the text. Change all three buttons to icons with tooltip to make more space for these long texts.

Fixes: https://github.com/go-gitea/gitea/issues/20922

Before (broken layout because of too long text):
Screen Shot 2022-08-23 at 20 16 25

After:
image

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

**Comment by otbutz** [comment]
@silverwind  Can we change the first icon? We are basically changing the diff behavior for whitespace/EOL. Shouldn't we use a symbol that reflects this?

**Comment by silverwind** [comment]
Yeah, I tried other icons for "whitespace" but I'm not sure I found one I like yet.

**Comment by otbutz** [comment]
At least the combined use of gear and three dot icons is a bit confusing as both imply "options". Maybe create a new icon based on these two:

https://www.compart.com/en/unicode/U+2423
https://www.compart.com/en/unicode/U+21B5

Quick (ugly) sketch:

image

**Comment by silverwind** [comment]
I think I will go with https://www.svgrepo.com/svg/368767/indent-increase because often times the whitespace toggle is related to hiding indendation changes and such.

**Comment by silverwind** [comment]
New icon added:

image

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
.

**Comment by 6543** [comment]
please backport

**Comment by 6543** [comment]
-> https://github.com/go-gitea/gitea/pull/20978

**Pull request merged**
