### PR TITLE
Leave MAINTAINERS and the organization

### PR DESCRIPTION
**Pull request by yp05327**
## Why join
I didn’t talk about myself before, so some people may think that I am an employee from the company. So I think it is necessary to talk about why and how I joined. 
At the begining, my boss gave me a task to find a git software which can self hosted in on-premise. Then I found that there are not many project which meet our needs. But finally, I found Gitea. A easy use, easy maintenance, and without a good machine you can also run it.
At that time, I just finished my previous work which is using helm to deploy something in K8s. So I tried to use Gitea’s helm chart to deploy in my work PC to see whether we can use it. But soon, I found a bug, and reported it (https://gitea.com/gitea/helm-chart/issues/382), but after about 1 month, there’s no fix. So I try to check the source code, and I found that it is caused by Gitea’s code and it is easy to fix it. So I created an issue (https://github.com/go-gitea/gitea/issues/22523) in Gitea. But unfortunately, after a long time again, it is still not fixed. So I tried to finish it by myself.
I’m not a pro programmer, coding is just my hobby since I was 13 or 14 years old. (I will tell the reason later), I even don’t know the workflow about the contribution of OSS, so maybe I did some bad things at the early time, I apologize.
But the people here are very kind, at that time, I start to consider whether it has worth to recommend to my boss. So I started to use it, but I found more and more bugs in a short time. Japanese company is very sensitive to it, so I gave up to recommend.
But I can try to fix them! Because I can learn too many things during the contribution, not just about the programing but also the usage of other tools and the general contribution rule in the world of OSS. It let me grow up, and to become (maybe) a perfect full-stack engineer which is my dream. (Why it is my dream? I made a wrong decision in my college, I took/followed the advice of my parent, choosed communications engineering instead of computer science which is my favorite thing)
 
# Why leave
Several days ago, there’s an [article](https://juejin.cn/post/7446578471901626420#comment) came into my eye. Something about JiHu (GitLab Ltd in China) start to file a lawsuit to the company which is using GitLab CE version which is under MIT License. So people start to find other git service/application to avoid it. And in the this article, a project called Fogejo is mentioned. It says it is a hard-fork of Gitea. But I don’t know the meaning of `hard-fork`, so I access the home page of this project to find where it comes from. 
Finally, I found it here: https://forgejo.org/compare-to-gitea/#why-was-forgejo-created. They said:
> As of early 2024, Forgejo is developed independently of Gitea, as a “hard-fork”.

`hard-fork` has a quotation, so the meaning is not the original meaning of it, but they said `as`, which means `like` or `similar` I think. So just focus on the words before `as` is ok, because `hard-fork` is a simile, `As of early 2024, Forgejo is developed independently of Gitea` is what they want to say.
In my mind, this means:
since early 2024 Forgejo’s codes (new changes) are all written by themselves, and emphasize that these changes are not related to Gitea, because they can simply say `As of early 2024, Forgejo is developed independently, as a “hard-fork”`

But after I check the commit history, I can still find some strange commits in recent month:
https://codeberg.org/forgejo/forgejo/commits/branch/forgejo/search?q=author%3Ayp05327&all=
The author is me, but the commit is signed by someone I even never heard.
Considering the words they said above, it feels/sounds like my work has become their work. Although Gitea is under MIT license, is this allowed in the OSS world?
Even it is allowed, I can not accept it personally.
So I created a issue to ask them:
https://codeberg.org/forgejo/forgejo/issues/6236
https://codeberg.org/forgejo/discussions/issues/251

Finally, it seems that they understood the problem and promised to improve it. But I also required a public statement to explain it which means they need to apologize, otherwise it is hard to the users who believe these are all their work know it, and it seems they ignored some of my words again? So it is hard for me to believe they will really make changes and post the apologize. If they did, I will consider to come back. Otherwise, I think there’s no worth to continually contribute to any OSS project, so I decided to leave.

ps: TOC voting is still ongoing, please remove me from the list. And I will leave the organization after the merge.

At the end, thanks to all people who have helped me to finish the contribution and teach me new knowledges.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
@techknowlogick @lunny 

I believe more publicity is needed by Gitea.

**Comment by ExplodingDragon** [comment]
<details>
<summary>This is truly a sad matter.</summary>
Gitea cannot do without you, just as the West cannot lose Jerusalem.
</details>

**Comment by lunny** [comment]
Please don't leave. I have posted my comment https://codeberg.org/forgejo/discussions/issues/251#issuecomment-2513035 to try to protect your contributions.

**Comment by BLumia** [comment]
Hi, I respect whatever the choice you've made, but I'd like to add a few words before you make your final decision.

> The author is me, but the commit is signed by someone I even never heard.

I guess it could be a misunderstanding of how GPG sign in git works. While it might look like it's for representing who the author is, it's not. The commit (GPG) signing is **not** about the authorship at all, it's for knowing certain person who committed the patch to the target branch can be trusted. It could be an honest mistake.

> Considering the words they said above, it feels/sounds like my work has become their work. Although Gitea is under MIT license, is this allowed in the OSS world?
> Even it is allowed, I can not accept it personally.

Well, MIT indeed allows cherry-picking as long as they keep comply MIT license when developing and redistributing Forgejo with cherry-picked code. 

But that's not the focus point here, I guess the core issue is...

> Considering the words they said above, it feels/sounds like my work has become their work.

As we both contribute to a MIT-licensed repo, Forgejo is okay to cherry-pick any MIT-licensed patches from Gitea, as long as they comply the license itself. Regardless of your concern, I personally think it's more of a copywriting issue than licensing issue, and there are things that both Gitea and Forgejo can improve.

- Forgejo, can document/credit the author when they write related blogposts and/or documentations.
- Forgejo might worth to update the wording of the relationship with Gitea project. If they heavily rely on cherry-picking Gitea commits, **hard fork** might be a confusing wording.
- Gitea, as an open-governanced project, might need to introduce an AUTHORS file to track the individual authors (since we are currently forcing to use `Gitea Authors` in our SPDX license headers.

I'm not a wordsmith, but I believe we (both as community contributors) can improve the project together.

Again, whatever the choice you make, I really appreciate the contributions you've made and thanks again for these contributions!

**Comment by yp05327** [comment]
> As we both contribute to a MIT-licensed repo, Forgejo is okay to cherry-pick any MIT-licensed patches from Gitea, as long as they comply the license itself.

This is no problem. I understand it.

> hard fork might be a confusing wording.

It seems that you are intrested in `hard fork`. But actually, I think there's no need to focus on `hard fork` this word.
I don't know whether you have notice, as I said, they use quotation to `hard-fork`, so what is the definithion of `hard-fork` with quotation? You have your opinion, I have my opinion, they have their opinon. It is hard to expain a word with quotation.
Even there's an general expaination for `hard-fork`, then what is the meaning of the quotation?
So I think `hard fork` with quotation here equals `Forgejo is developed independently of Gitea`, because they used `as` to connect them. And that's where all my questions (like the issue title) or request from.

**Comment by BLumia** [comment]
> > hard fork might be a confusing wording.
> 
> It seems that you are intrested in `hard fork`. But actually, I think there's no need to focus on `hard fork` this word ...
> ...It is hard to expain a word with quotation. 
> ... And that's where all my questions (something like the issue title) or request from.

Yeah, that's what I talked about: these (weither "hard-fork" or "developed independently of Gitea") are wording issues that *can* be addressed if the Forgejo project wants to. And since we know the source issue that caused your frustrations, we should work on addressing them.

From what I get from the previous discussions, I guess there are misunderstandings at both (Gitea contributors and Forgejo contributors) ends. By addressing these issues, we can ensure both Gitea and Forgejo projects healthily grow together.

My main point is, choosing to no longer to be a Gitea maintainer/organization member really doesn't address any of these concerns *from both ends*. I understand you might still feel frustrated and if so, I can make some attempts to address these issues as well :)

**Comment by silverwind** [comment]
I too don't like what Forgejo is doing with our commmits, but I imagine a few years down the road, this issue will resolve itself when the repos have diverged sufficiently so that they can no longer port our commits directly without substantial effort.

**Comment by yp05327** [comment]
According to the response from '@ fnetX' in https://codeberg.org/forgejo/discussions/issues/251#issuecomment-2514513
There's no plan for them to apologize.

> So it is hard for me to believe they will really make changes and post the apologize. If they did, I will consider to come back.
> And I will leave the organization after the merge.

Although they made some changes but it didn't change anything.
And according to what I said, it seems that no one wants to approve this PR.
I can’t help it, so I will leave the organizaiton (both GitHub and Gitea.com) next Monday, if no thing changes.
Thanks all again.

**Review by silverwind — APPROVED** [review]
I don't understand why you leave this org because of actions of some 3rd party indivduals. But in any case, everyone is free to leave so I can approve.

**Review by BLumia — APPROVED** [review]
Approved as well, thanks again for your previous efforts!

**Comment by yp05327** [comment]
> I don't understand why you leave this org because of actions of some 3rd party indivduals.

The reason is simple: I’ve experienced something similar before. In the end, users from the other side eventually started making snide or passive-aggressive remarks, even though we have no relationship. After that, all my works are private.
Personally, I can’t tolerate dishonest behavior. So, if Gitea (Ltd.) acts against its promises, I’ll leave the community as well.

In addition, leaving the organization and maintainer doesn’t mean leaving the community. I can still help answer user questions, report bugs, or contribute in other ways—just nothing related to code that might be cherry-picked by Forgejo.

**Review by delvh — APPROVED** [review]
:frowning:   Sad to see you go.
I'm terribly sorry that I don't know how to improve the situation.
If you ever change your mind, we would be more than happy to welcome you back as a maintainer.

**Comment by yp05327** [comment]
I have left the organization in both GitHub and gitea.com

**Pull request merged**
