### PR TITLE
Add comment marking the end of database migrations in `1.19.0`

### PR DESCRIPTION
**Pull request by yardenshoham**
There will be no more migrations in `1.19.0`

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by delvh — CHANGES_REQUESTED** [review]
LGTM, but I'm holding it back until the feature freeze has actually passed, on the rare chance that we still merge another feature today.

**Comment by yardenshoham** [comment]
I think it's time

**Comment by delvh** [comment]
No, there are still two hours until feature freeze (https://discord.com/channels/322538954119184384/537668686173962260/1074769294090579998).
Especially #21563 could potentially still be merged.
However, I haven't reviewed the PR yet, I don't know if it is ready, so I'll leave it to those that reviewed it.

**Comment by yardenshoham** [comment]
I have to log off, if #21563 gets merged feel free to push to this branch/replace this PR

**Review by delvh — APPROVED** [review]

**Pull request merged**
