### PR TITLE
Fix color of tertiary button on dark theme

### PR DESCRIPTION
**Pull request by silverwind**
Before:
Screenshot 2023-02-03 at 14 07 34

After:
Screenshot 2023-02-03 at 14 07 52

This is the only instance of such a button in all templates.

### CODE REVIEW

**Review by yardenshoham — APPROVED** [review]
LGTM

**Comment by wxiaoguang** [comment]
> This is the only instance of such a button in all templates.

Yup, IIRC I introduced it by #18084 (the class name is also defined by Fomantic UI already). I think it's helpful to convert many `<a>` elements to `<button>` properly in the future. Or feel free to replace it with something better.

**Comment by silverwind** [comment]
I changed the border removal to a helper class. Much cleaner that way and does not break any future such buttons.

**Comment by wxiaoguang** [comment]
But `tertiary` button was already defined as a non-bordered button.

https://fomantic-ui.com/elements/button.html#tertiary

Gitea itself made it a mess with border, then make it mess again with `border-none` ...... more and more messy.

**Comment by silverwind** [comment]
Huh, I see so there must be a style of our own somewhere that adds border. If I remove that, buttons elsewhere will lose border, but I guess it's for the better to follow fomantic and not alter border.

**Comment by silverwind** [comment]
Putting WIP, I don't have time right now to investigate so deeply.

**Comment by wxiaoguang** [comment]
I think it's good enough to take https://github.com/go-gitea/gitea/pull/22739/commits/72417a4fa106a2c223812448db05cbfe92becf36 

And maybe add some comments about the problem.

```
// some comments about the border problem
.ui.tertiary.button {
  color: var(--color-text-light);
  border: none;
}

.ui.tertiary.button:hover {
  color: var(--color-text);
}
```

**Comment by silverwind** [comment]
Yeah I have reverted, so this is only about color and ready to land and backport as well.

Border issue will be done separately.

**Review by lafriks — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
LG-TM bot

**Comment by lunny** [comment]
Please send back port

**Pull request merged**
