### PR TITLE
Fix counting and filtering on the dashboard page for issues

### LINKED ISSUE #26361: The incoming request has too many parameters. This server supports a maximum of 2100 parameters.
### Description

visit http://giteaurl/issues
then click  "Closed" tab on right side
there is an error page displayed 500 internal error,and  in log file:The incoming request has too many parameters. This server supports a maximum of 2100 parameters. Please reduce the number of parameters and resend the request.

This is due to the default selection behavior of the issues page, as there are too many repos passed in later on &repos=...

There are differences in the concepts of  between "select all repos " and "select every repo"

If 'select all' is understood as' select everything ', then&repos=.... Later, if there are 1000+ repos, then 1000+ parameters need to be passed in ...

### Gitea Version

1.21.0+dev-892-g8e8f55839

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

1.21.0+dev-892-g8e8f55839

### Operating System

windows

### How are you running Gitea?

windows exe

### Database

None

### LINKED ISSUE #26653: Incorrect selection behavior at repo list , on the left side of the issues page.
### Description

this url : https://your-gitea-url/issues

When entering the issues page for the first time, the repo list on the left is all-selected state.
This resulted in a STRANGE behavior:
When I click on a repo name in the list, the actual result is that the issue title list on the right side excludes the repo I just clicked on.
The EXPECTED effect should be, which repo(s) did I choose and which repo(s) issue list should be displayed on the right side.

image

### Gitea Version

main branch

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

1.21.0-dev

### Operating System

windows

### How are you running Gitea?

windows exe

### Database

MSSQL

### PR DESCRIPTION
**Pull request by wolfogre**
This PR actually has multiple parts, and I didn't split them because it's not easy to test them separately since they are all about the dashboard page for issues.

1. Support counting issues via indexer, to fix #26361
2. Fix repo selection, so it also fix #26653
3. Keep keyword in filter links.

The first two are regressions of #26012.

After:

https://github.com/go-gitea/gitea/assets/9418365/71dfea7e-d9e2-42b6-851a-cc081435c946

Thanks to @CaiCandong  for helping with some tests.

### CODE REVIEW

**Comment by zjjhot** [comment]
Thank you very much. I have a suggestion.

Issues that have existed in history can be displayed in the repo list (even if this issue module is prohibited from accessing, it is reasonable to exist, and I can always see records of historical existence, which is fine).

However, those that have never been issued (count=0) should not be displayed in the repo list, especially those repos that disabled by issue module.

**Comment by wolfogre** [comment]
> Issues that have existed in history can be displayed in the repo list (even if this issue module is prohibited from accessing, it is reasonable to exist, and I can always see records of historical existence, which is fine).

Not sure, maybe another PR.

> However, those that have never been issued (count=0) should not be displayed in the repo list, especially those repos that disabled by issue module.

Done in e56c59a20450e405cc52fc1dec1516d6a6462420

**Comment by CaiCandong** [comment]
```
	for k, v := range issueCountByRepo {
		if _, ok := selectedReposMap[k]; !ok && v == 0 {
			delete(issueCountByRepo, k)
		}
	}
```
Maybe we can use https://pkg.go.dev/maps@go1.21.0#DeleteFunc

**Comment by wolfogre** [comment]
> Maybe we can use [pkg.go.dev/maps@go1.21.0#DeleteFunc](https://pkg.go.dev/maps@go1.21.0#DeleteFunc)

Not now, Gitea is still using go1.20: https://github.com/go-gitea/gitea/blob/1432d4eab94814db267577ec911a3375a1269fc0/go.mod#L3

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Review by CaiCandong — APPROVED** [review]

**Pull request merged**
