### PR TITLE
Remove jQuery from the code diff expansion buttons

### PR DESCRIPTION
**Pull request by yardenshoham**
- Removed all jQuery AJAX calls and replaced with htmx
- Tested the code diff expansion buttons functionality and it works as before plus a loading indicator

# Demo using `htmx` instead of jQuery AJAX
action

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
@yardenshoham 

Does htmx work with dynamic reloaded content? The "expand" button doesn't work on my side if the content is loaded dynamically.


image

image

**Comment by yardenshoham** [comment]
How to reproduce?

**Comment by wxiaoguang** [comment]
> How to reproduce?

The screenshot,  "Load Diff" button

**Comment by wxiaoguang** [comment]
Fixed in  Fix various Fomantic UI and htmx problems #33851 , by the way.

**Pull request merged**
