### PR TITLE
Add prefix to SVG id/class attributes

### PR DESCRIPTION
**Pull request by KN4CK3R**
Currently the svg minifier (`make svg`) rewrites all `id` and `class` attributes in svg files. Every file gets the ids `a, b, ...`. If multiple svgs with ids are used on a page these ids are conflicting and the results are broken images.

| minified ids | unique ids |
| - | - |
| grafik | grafik |

This PR adds a prefix (the filename) to every id/class.

Follow up problem: Because we embed svg images there are duplicated ids if one svg image is used multiple times on a page. As those ids refer to the same content it may be no real problem because browser handle that fine.

### CODE REVIEW

**Comment by silverwind** [comment]
How about removing `id` and `class` attributes instead? The `inlineStyles` rule is enabled so there shouldn't be an issue with stuff like embedded CSS that targets these ids/classes.

**Comment by KN4CK3R** [comment]
Is it possible to inline a `linearGradient` element as in the GitHub image?

**Comment by silverwind** [comment]
Should be possible using a datauri, but if svgo can not do it, I guess it's not worth it and your solution is better.

**Review by silverwind — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I think this needs a backport

**Pull request merged**
