### PR TITLE
modernize js and use babel

### PR DESCRIPTION
**Pull request by silverwind**
- add babel toolchain to transform modern JS to ES5
- extend eslint config for modern rules
- fixes linting issues via `eslint --fix` and manual fixes

This will enable us to use all modern JS features as well as `import` to load files or npm modules into the main bundle.

Not totally happy with how many rules I had to disable with `eslint-config-airbnb-base` but it seems to be one of the most popular configs so I went with it.

### CODE REVIEW

**Comment by silverwind** [comment]
CI failed because https://github.com/go-gitea/gitea/pull/8598 apparently dropped the `-moz-user-select` in the generated css. Maybe something specific to `@lunny's` setup (node version?) triggers it, I'm not really sure. Anyways, next build should pass.

**Review by zeripath — APPROVED** [review]

**Review by sapk — APPROVED** [review]
I haven't review all the index.js changes but the 10% viewed are good and the others files seems good. I will trust you on the rest. This feel good to have the big js file cleaned.

**Comment by silverwind** [comment]
Yes, diff is a bit noisy because of the indendation change. I tested a few JS features and they all seem to work fine. I'm quite surprised how well `eslint --fix` transformed the code. Most of my manual changes were `==` to `===`.

Will rebase and do a few minor tweaks.

**Comment by silverwind** [comment]
Rebased and pushed a few minor tweaks, should be good to merge now.

**Comment by sapk** [comment]
> Yes, diff is a bit noisy because of the indendation change. I tested a few JS features and they all seem to work fine. I'm quite surprised how well `eslint --fix` transformed the code. Most of my manual changes were `==` to `===`.
> 
> Will rebase and do a few minor tweaks.

Yes and it seems to have re-ordered some func that doesn't help the diff.

**Comment by silverwind** [comment]
Re-ordering might be because of https://eslint.org/docs/rules/no-use-before-define. I ended up disabling the rule but I guess it must already have fixed some cases where it could autofix it.

**Pull request merged**
