### PR TITLE
Add migration from GitBucket

### PR DESCRIPTION
**Pull request by KN4CK3R**
This PR adds [GitBucket](https://gitbucket.github.io/) as migration source. GitBucket claims to be api compatible with Github so I reused the Github downloader.

Supported:
- [x] Milestones
- [x] Issues
- [x] Pull Requests
- [x] Comments
- [x] Reviews
- [x] Labels

There is no usable public instance so I have not added tests.

### CODE REVIEW

**Comment by lunny** [comment]
GitBucket is not http://bitbucket.org . It seems online demo is not avaiable.

**Comment by roop90** [comment]
There is a Public Demo Instance:

[https://gitbucket.herokuapp.com/](https://gitbucket.herokuapp.com/)
Login is root/root.

Hope this helps.

**Comment by KN4CK3R** [comment]
That's right but for tests we need a reliable host. A repository there could/will change and is not usable for tests.

**Comment by 6543** [comment]
@KN4CK3R 
> There is no usable public instance so I have not added tests.

https://github.com/go-gitea/gitea/issues/12919#issuecomment-708704206

**Comment by KN4CK3R** [comment]
@6543 That's **Bitbucket** and not [**GitBucket**](https://gitbucket.github.io/).

**Comment by 6543** [comment]
aaa - did missed it too

**Comment by 6543** [comment]
@KN4CK3R please resolve conflicts - I'll test manually once https://gitbucket.herokuapp.com/ is up and running - code looks good so far :)

**Comment by lunny** [comment]
> @KN4CK3R
> 
> > There is no usable public instance so I have not added tests.
> 
> [#12919 (comment)](https://github.com/go-gitea/gitea/issues/12919#issuecomment-708704206)
> 
> EDIT: I worked on this a bit too but did not find a nice sdk so did focus on gogs, etc instead

see https://github.com/go-gitea/gitea/pull/16767#issuecomment-903202232

**Comment by 6543** [comment]
@KN4CK3R localy tested and got error:
`Migrate repository from http://localhost:8080/test/aaaa failed: error while listing repos: GET http://localhost:8080/api/v3/repos/test/aaaa/pulls/1/reviews?per_page=100: 404 Not Found []` - i think we have to ignore reviews like reactions too

**Comment by KN4CK3R** [comment]
The closed issues issue should now be gone. I created a PR for that: https://github.com/gitbucket/gitbucket/pull/2859

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
