### PR TITLE
Config For Deploy On heroku.com

### PR DESCRIPTION
**Pull request by tahaghafuri**
Added Files For Deploy Gitea On heroku.com

### CODE REVIEW

**Comment by Gusted** [comment]
Is it required to have these files at root level? Otherwise they can be placed at `contrib/heroku/`

**Comment by tahaghafuri** [comment]
For people who want to deploy directly from this repository, yes.

**Comment by Gusted** [comment]
Hmm `app.json` is a bit off as it's a general name and nobody will know(unless checking the history) of why that file is there.

Is there some documentation about these files? heroku.yml seems to be specifying what to build, but app.json seems to be for CI related things?

**Comment by tahaghafuri** [comment]
No, app.json contains software information and is a required file for herokul.

**Comment by Gusted** [comment]
Hi tahaghafuri,

We had a small discussion internally if we wanted to have these files in the root directory of the project. We came to a conclusion that:
1. We don't want these files in the root directory of the project as they provide no direct benefit to the project itself(therefor we use the `contrib` folder, but this clearly cannot be utilized as mentioned by you and the docs of Heroku)
2. We looked more closely to the real usage of these files and noticed that having them in `go-gitea/gitea` cannot be utilized by any person as you require admin permission of the repository and thus requires forking the project. We'd prefer to not give more reasons to fork big repositories like Gitea when other alternatives exists to deploy Gitea on Heroku.

Closing the PR. Feel free to join for a discussion over in a chatroom([Discord](https://discord.com/invite/Gitea) & [Matrix](https://matrix.to/#/#gitea:matrix.org)) if you think we misunderstood the intention of this PR. In it's current form we don't see any way that this can be merged.

**Comment by wxiaoguang** [comment]
Although this mechanism can make heroku deploy Gitea, IMO it's not an ideal method.

The `app.json` is for developers to deploy their projects on heroku easily.

For a large/public project like Gitea, it's better to deploy its dockerhub image directly.

At least, the `app.json` shouldn't be put in Gitea's main repo, there could be a separate repo like `gitea/gitea-heroku` for it.

**Review by 6543 — CHANGES_REQUESTED** [review]
Debian, arch, alpine, ... all these package build configs/scripts are maintained outside

**Comment by 6543** [comment]
A seperate repo would be fine ...

**Pull request closed without merging**
