### PR TITLE
Fix org label open count, including close count issue

### PR DESCRIPTION
**Pull request by tyroneyeh**
Fixed using organization tags to see open issues in the tag list including closed issues count

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
does it also affect v1.17.0 ?

**Comment by tyroneyeh** [comment]
> does it also affect v1.17.0 ?

yes, v1.16 also have this problem

**Comment by 6543** [comment]
can you backport it to release branches for v1.17 and v1.16 ?

**Comment by tyroneyeh** [comment]
> can you backport it to release branches for v1.17 and v1.16 ?

done #20364 #20365

**Pull request merged**
