### PR TITLE
Fix doer of rename repo

### LINKED ISSUE #11725: User is not shown on rename
- Gitea version (or commit ref): 1.12.0+rc1-27-g600bb545f
- Git version: 2.25.1
- Operating system: Ubuntu 20
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ x ] Yes (https://try.gitea.io/TestingGitea/Test2)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I renamed my repository in an organization and then went to my Overview...
I think there should be shown: "MenschenToaster has renamed the Repository .... to ... " but this was shown: "organization has renamed ... to ...".
I think there should be my name shown not the organization it was changed in.
I use gitea in german so I don't know what the text is exactly. A screenshot was provided. One from a commit and the other from the rename.

...

## Screenshots

http://prntscr.com/srzuuo

### PR DESCRIPTION
**Pull request by a1012112796**
As title

fix #11725

### CODE REVIEW

**Comment by a1012112796** [comment]
By the way, I found the icon type of "ActionRenameRepo” is not defined. How about using “octicon-repo"? Thanks.

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
nice catch!

**Review by zeripath — APPROVED** [review]

**Comment by lafriks** [comment]
Make lgtm work

**Comment by lafriks** [comment]
Please send backport

**Pull request merged**
