### PR TITLE
In File Create/Update API return 404 if Branch does not exist

### LINKED ISSUE #10982: [Bug] [API] repoCreateFile  return 500 if branch not exist
as title

try: `curl -X POST "https://try.gitea.io/api/v1/repos/abcKing/repo_uninit/contents/README.md?token=yourtocken" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"author\": { \"email\": \"user@example.com\", \"name\": \"string\" }, \"branch\": \"string\", \"committer\": { \"email\": \"user@example.com\", \"name\": \"string\" }, \"content\": \"c3RyaW5nCg==\", \"dates\": { \"author\": \"2020-04-06T01:37:35.137Z\", \"committer\": \"2020-04-06T01:37:35.137Z\" }, \"message\": \"string\"}"`

It return:
```
{
  "message": "branch does not exist [name: string]",
  "url": "https://try.gitea.io/api/swagger"
}
```

Gitea Version: 1.12.0+dev-89-gb264c3039

### PR DESCRIPTION
**Pull request by 6543**
close #10982

### CODE REVIEW

**Comment by zeripath** [comment]
make lg-tm work

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
Ping lgtm

**Comment by zeripath** [comment]
ʇɹodʞɔɐq puǝs ǝsɐǝlԀ

**Comment by 6543** [comment]
-> #11795

**Pull request merged**
