### PR TITLE
Have build tag for miniwinsvc

### PR DESCRIPTION
**Pull request by andreynering**

### CODE REVIEW

**Comment by tboerger** [comment]
And how does this simple lib conflict?

**Comment by andreynering** [comment]
This lib makes Gitea able to be registered as a Windows service.

NSSM kind of simulate a Windows service.

Somehow they conflict when used both, but I don't know enough to say how or why. So, minwinsvc should be opt-in, IMHO.

**Comment by lunny** [comment]
Maybe we can add a command flag to do that. 
```
gitea --run-service
```
Use another build tag is no need.

**Comment by andreynering** [comment]
Maybe we should have the build tag in 1.0.0 to don't block the release?

@lunny What you proposed may work, but I think we would have to create our own fork of minwinsvc to do that, because it hacks with Go's `init()` func.

**Comment by tboerger** [comment]
I still don't understand why this should conflict and why this is needed at all. From my side lets just drop it and provide some proper docs for a windows service.

**Comment by andreynering** [comment]
@tboerger You mean drop minwinsvc or NSSM?

**Comment by tboerger** [comment]
I would prefer a native windows solution and drop the other.

**Comment by andreynering** [comment]
@tboerger OK, the issue is that I never got it to work. But I'll try again any day.

**Pull request closed without merging**
