### PR TITLE
Ensure that all unmerged files are merged when conflict checking

### LINKED ISSUE #19527: CompareAndPullRequestPost() causes internal server error
### Description

I have a repository with a *vendor* folder in the master branch. In separate feature branch, I deleted this folder and replaced it with a git submodule. I then tried to create a Pull Request in the gitea UI, which causes a 500 Internal Server Error:

Error in the logs:  
```
2022/04/26 16:20:39 ...ers/web/repo/pull.go:1164:CompareAndPullRequestPost() [E] NewPullRequest: exit status 128 - vendor: unmerged (b9193c1afe1d0bd874d6f995bcbf1fc98d249588)
	fatal: git-write-tree: error building trees
```

### Gitea Version

     1.16.6 built with GNU Make 4.3, go1.18.1 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

     2.30.3

### Operating System

Official Gitea Docker image

### How are you running Gitea?

Via docker-compose

### Database

SQLite

### PR DESCRIPTION
**Pull request by zeripath**
There is a subtle bug in the code relating to collating the results of
`git ls-files -u -z` in `unmergedFiles()`. The code here makes the
mistake of assuming that every unmerged file will always have a stage 1
conflict, and this results in conflicts that occur in stage 3 only being
dropped.

This PR simply adjusts this code to ensure that any empty unmergedFile
will always be passed down the channel.

The PR also adds a lot of Trace commands to attempt to help find future
bugs in this code.

Fix #19527

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by Gusted — APPROVED** [review]
1 LOC bug fix, 26 lines for debugging code. LGTM!

**Comment by zeripath** [comment]
It would be better if I could come up with some tests but it seems it would be very difficult. Certainly it appears it would require us to store opaque git repositories which is not really very helpful.

There are quite a few little functions here that could lend themselves to a simple test case or two if someone were willing but I only think such testcases could hope to prevent regressions rather than actually spot errors. This particular problem was an assumption that stage 1 was always present so any testcase would have had the same assumption.

**Comment by Gusted** [comment]
This whole part of the codebase is quite untested and I remember we had a attempt at adding test for this when another bug arises(the "empty" PR one IIRC) from the conflict checking, but it's just too complicated to not end up hunderds of LOCs for one test-case.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by 6543** [comment]
-> #20536

**Pull request merged**
