### PR TITLE
Fix language names

### PR DESCRIPTION
**Pull request by 0rzech**
Make language names grammatical in defaults.go and app.ini.

### CODE REVIEW

**Comment by ethantkoenig** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lafriks** [comment]
Please rebase

**Comment by lunny** [comment]
Please rebase.

**Comment by sapk** [comment]
Why dropping the capitalization on some ?

**Comment by lafriks** [comment]
@sapk in some languages language names are not written capitalized as in English. At least I can confirm this is correct for Latvian, don't know about others

**Comment by sapk** [comment]
ok, I personally prefer with caps but after verification it seems to be also good for français and I am not the best at grammar. So LGTM.

**Comment by 0rzech** [comment]
@lafriks, @lunny: rebased.

**Pull request merged**
