### PR TITLE
Remove "CHARSET" config option for MySQL, always use "utf8mb4"

### LINKED ISSUE #25378: Newly installed instance could use incorrect "utf8" charset for MySQL
A default install could produce such app.ini:

```
APP_NAME=Gitea: Git with a cup of tea
RUN_USER=xiaoguang
RUN_MODE=prod

[database]
DB_TYPE=mysql
HOST=127.0.0.1:3306
NAME=gitea
USER=gitea
PASSWD=gitea
SCHEMA=
SSL_MODE=disable

CHARSET=utf8     !!!!!!!!!!!! wrong here

PATH=/Users/xiaoguang/work/gitea/data/gitea.db
LOG_SQL=false
```

"utf8mb4" is required for MySQL to work with emoji.

### PR DESCRIPTION
**Pull request by wxiaoguang**
In modern days, there is no reason to make users set "charset" anymore.

Close #25378

## :warning: BREAKING

The key `[database].CHARSET` was removed completely as every newer (>10years) MySQL database supports `utf8mb4` already.
There is a (deliberately) undocumented new fallback option if anyone still needs to use it, but we don't recommend using it as it simply causes problems.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
@techknowlogick I do not think this is "breaking"

**Comment by techknowlogick** [comment]
Marking as breaking so that should any user still have just utf8 in their config we can add a note to the blog post with a link to the doctor documentation

**Comment by wxiaoguang** [comment]
> Marking as breaking so that should any user still have just utf8 in their config we can add a note to the blog post with a link to the doctor documentation

I do not see a case how this change would affect end users, so I do not think it's worth to mark it as breaking or make end users spend time on reading it.

**Comment by wxiaoguang** [comment]
> Edit, it also changes the config variable name.

The new "MYSQL_CHARSET" is just a hidden fallback in case some users really really like to do something, but, I think we should never mention it. Just like `I_AM_BEING_UNSAFE_RUNNING_.....`

I do not think any one really needs it.

**Comment by techknowlogick** [comment]
It fully removes an option that users may have been using (even if they should be using the newer version), and also, due to the rename it means that users will have to use a new key in the future.

**Comment by wxiaoguang** [comment]
> It fully removes an option that users may have been using (even if they should be using the newer version), and also, due to the rename it means that users will have to use a new key in the future.

I am pretty sure the removal affects nothing.

The "rename" won't be exposed for end users in any case.

**Comment by lunny** [comment]
> > It fully removes an option that users may have been using (even if they should be using the newer version), and also, due to the rename it means that users will have to use a new key in the future.
> 
> I am pretty sure the removal affects nothing.
> 
> The "rename" won't be exposed for end users in any case.

The Gitea instance will not work if database is `utf8` but the connection string is `utf8mb4`

**Comment by wxiaoguang** [comment]
> The Gitea instance will not work if database is `utf8` but the connection string is `utf8mb4`

I have tested, it works flawlessly

If you have a bad case, please help me to know.

**Comment by lunny** [comment]
> > The Gitea instance will not work if database is `utf8` but the connection string is `utf8mb4`
> 
> I have tested, it works flawlessly
> 
> If you have a bad case, please help me to know.

Have you tested inputting an `emoji`? Maybe we just need to say on the release blog that you need to convert your database from utf8 -> utf8mb4 manually.

**Comment by wxiaoguang** [comment]
> Have you tested inputting an `emoji`? Maybe we just need to say on the release blog that you need to convert your database from utf8 -> utf8mb4 manually.

That's a longstanding problem. Not related to this PR.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
I don't think it's necessary to backport to v1.20

**Comment by wxiaoguang** [comment]
> I don't think it's necessary to backport to v1.20

Then 1.20 still needs other fix

**Comment by delvh** [comment]
But yes, we should document it as breaking when we **don't** use a key anymore.
And let it just be so that users can remove it from their config.

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
Oh, perhaps we should also remove the FAQ entry now.

**Pull request merged**
