### PR TITLE
Detect migrating batch size

### LINKED ISSUE #7348: New batch migration causes error on sqlite
(cc @lunny)

With the changes in #7050, I now get these when testing a migration:

```2019/07/03 11:52:30 routers/repo/repo.go:315:MigratePost() [E] MigratePost: too many SQL variables```

My example happened for comments, based on this INSERT statement (I think):

https://github.com/go-gitea/gitea/blob/b5aa7f7ceb4ca828f50395e404e19c5ba7679268/models/migrate.go#L121-L127

Here is the full gist:

 https://gist.github.com/mrsdizzie/681ea0295c11350fea4244a4289665ef

This is just testing migrating the "tea" repo here: https://github.com/go-gitea/tea

But it could maybe happen other places too for similar reasons. For each comment there would be a few dozen variables in that SQL statement, so it breaks depending how many comments there are. Each comment adds about 22 variables to the statement now (one for each column), so even something like 50 total comments (say 10 issues with 5 comments each) is enough to trigger this error since I believe the default SQLITE_MAX_VARIABLE_NUMBER is 999 (22 * 50 = 1,100).

I know this is sort of a limit of sqlite and probably wouldn't happen with others -- but still an issue (and makes testing new migration features difficult since it is nice to use sqlite locally for development).

Maybe we can detect if sqlite and use the old method (or limit it to a known good number like 25 comments at a time)?

### PR DESCRIPTION
**Pull request by lunny**
should fix #7348

### CODE REVIEW

**Comment by zeripath** [comment]
Does a batch size of 100 work by default for sqlite?

**Comment by lunny** [comment]
@zeripath it works for me but not @mrsdizzie

**Comment by mrsdizzie** [comment]
I left comment on #7348 about the size

**Review by mrsdizzie — APPROVED** [review]

**Comment by mrsdizzie** [comment]
This looks good thanks! Was able to migrate all Gitea with Sqlite

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I guess this needs to be 1.9

**Comment by mrsdizzie** [comment]
Yes should be in 1.9 since the batch processing is

**Pull request merged**
