### PR TITLE
Update JS and PY dependencies, build for `es2020` browsers

### PR DESCRIPTION
**Pull request by silverwind**
- Update all JS dependencies minus @mcaptcha/vanilla-glue
- Fix new lint errors
- Regenerate SVGs
- Switch to maintained stylelint stylistic plugin
- Tested Mermaid, Citation, Swagger, sorting
- Raise ESBuild target to `es2020` as dictated by `pretty-ms` dependency.

### CODE REVIEW

**Comment by silverwind** [comment]
Webpack chockes on BigInt literals in `pretty-ms`, which will require raising the webpack target to es2020, and I think it's not worth doing that as it will likely cause problems with older browsers like PaleMoon, so I will pin the dependency to the old version.

**Comment by silverwind** [comment]
On the other hand, PaleMoon seems to implement BigInt since v32.4.0 (https://www.palemoon.org/releasenotes.shtml), so I think it's worth to switch to `es2020`, it will also reduce bundle size.

**Comment by silverwind** [comment]
Now with `es2020`, there is a 70kB reduction in JS asset size:

```bash
# es2015
$ du -b --apparent-size public/assets/js
23235235  public/assets/js

# es2020
$ du -b --apparent-size public/assets/js
23300624  public/assets/js
```

**Comment by techknowlogick** [comment]
@wolfbeast a gentle ping as a heads up about this.

**Comment by wolfbeast** [comment]
@techknowlogick thanks for the ping. We should have complete support for ES2020 as of 6 months ago, but let me know if you want me to test something.
Ref for our final implementation of what we didn't yet have before: https://repo.palemoon.org/MoonchildProductions/UXP/issues/1734

**Review by delvh — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
