### PR TITLE
Migration will clone repository from the proxy

### LINKED ISSUE #12018: Migration does not clone repository from the proxy
- Gitea version (or commit ref): 1.12.1
- Git version: 2.27.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
Nothing.

## Description
I configured git's global http & https proxy to http://127.0.0.1:1086, but it seems that migration does not clone repository from the proxy.

## Screenshots

Nothing.

### PR DESCRIPTION
**Pull request by idealism-xxm**
Fix: #12018

Signed-off-by: idealism-xxm <biaochekuangmo@yeah.net>

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for this PR, my understanding of golang was that it picks up proxy settings via the `HTTP_PROXY` environment variable?

**Comment by idealism-xxm** [comment]
The `http.DefaultTransport` will use proxy from environment, and it's only used when there is no custom transport.

Gitea uses a custom transport without proxy in file `modules/migrations/gogs.go` and `modules/migrations/github.go`, so we need to add a proxy.

Maybe we can only use proxy from the environment?

**Comment by lafriks** [comment]
I think we should reuse `HTTP_PROXY` env and not introduce new config settings for this

**Comment by idealism-xxm** [comment]
> I think we should reuse `HTTP_PROXY` env and not introduce new config settings for this

Ok, I agree with you and I'll fix this.

**Comment by lunny** [comment]
> I think we should reuse `HTTP_PROXY` env and not introduce new config settings for this

I don't think so. Assume we want to add proxy for migrating from github but not another gitea instance, how should we do? We should have a global proxy i.e. #15234 and then set the proxy per domain.

**Comment by idealism-xxm** [comment]
> > I think we should reuse `HTTP_PROXY` env and not introduce new config settings for this
> 
> I don't think so. Assume we want to add proxy for migrating from github but not another gitea instance, how should we do? We should have a global proxy i.e. #15234 and then set the proxy per domain.

Alright. I thought we could set these rules in proxy software.

**Comment by lunny** [comment]
Since #16704 has been merged, I think we can close this one. @idealism-xxm You can also send another PR to improve the proxy feature.

**Comment by 6543** [comment]
-> https://github.com/go-gitea/gitea/pull/16704#discussion_r691322371

**Pull request closed without merging**
