### PR TITLE
Fix display since time round

### LINKED ISSUE #4917: Wording in "last changed date"
- Gitea version: d918e63
- Git version: 2.18
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

If the last changed date of a file in repository is more then 1.5 years ago, then it should say "2 years ago", instead of "1 year ago". 
In the example screenshot you can see the last changes on the file has been made on 26 Nov 2016. And that is in my opinion more "2 years ago" then "1 year" atm.

## Screenshots
grafik

### PR DESCRIPTION
**Pull request by lunny**
This PR introduces rounding off numbers for time since. 
i.e. Before, 1.6 year still displayed 1 year, 
After 1.4 year will display 1 year, but 1.5 year will display 2 years.

Fix #4917

### CODE REVIEW

**Comment by zeripath** [comment]
I wonder if we might benefit from writing out what times we're aiming to display.

I'd also note that in British English we're likely to consider 18 months a half-way point between 1 year & 2 years. Not sure if it is the same in US English & International English though.

**Comment by zeripath** [comment]
might be worth taking a look at http://timeago.yarp.com/

**Comment by lunny** [comment]
A frontend solution may make i18n difficult.

**Comment by lafriks** [comment]
unit tests fail

**Comment by zeripath** [comment]
I wasn't suggesting using that library rather check/copy its algorithm

**Review by bagasme — COMMENTED** [review]
but what about the case for leap years?

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
> but what about the case for leap years?

Just ignored that. We just calculate the time distance.

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport

**Pull request merged**
