### PR TITLE
Update documentation to disable duration settings with -1 instead of 0

### PR DESCRIPTION
**Pull request by jpraet**
To turn off the notification endpoint polling, the value should be set to -1, not 0.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
`-1` and `0` both should work. it's not breaking. and how to document it clearly? recommend to always use 0 from now on?

```go
// if you set MinTimeout=-1, it still becomes 0 in the end
"MinTimeout": int(setting.UI.Notification.MinTimeout / time.Millisecond)
```

```js
  // and in JS code
  if (notificationSettings.MinTimeout <= 0) {
    return;
  }
```

**Comment by delvh** [comment]
Yes, if 0 works as well, it indeed is not breaking.
I've assumed it wasn't, otherwise this PR does not make much sense.

**Review by 6543 — APPROVED** [review]

**Comment by jpraet** [comment]
0 does **not** work. I've put a console log of notificationSettings.MinTimeout in the JS code and it prints 10000 when MIN_TIMEOUT is set to 0. When MIN_TIMEOUT is set to -1, it prints 0.

Note that setting.UI.Notification.MinTimeout is of type time.Duration, I'm not sure where to find the conversion code from string to time.Duration?

**Comment by jpraet** [comment]
What about these? I think it's likely these duration properties may also not work as documented?

https://github.com/go-gitea/gitea/blob/8adba93498ccdde7edcb54e10f6a3d176c3815c4/docs/content/doc/advanced/config-cheat-sheet.en-us.md?plain=1#L261-L262
https://github.com/go-gitea/gitea/blob/8adba93498ccdde7edcb54e10f6a3d176c3815c4/docs/content/doc/advanced/config-cheat-sheet.en-us.md?plain=1#L289-L290
https://github.com/go-gitea/gitea/blob/8adba93498ccdde7edcb54e10f6a3d176c3815c4/docs/content/doc/advanced/config-cheat-sheet.en-us.md?plain=1#L418

https://github.com/go-gitea/gitea/blob/8adba93498ccdde7edcb54e10f6a3d176c3815c4/docs/content/doc/advanced/config-cheat-sheet.en-us.md?plain=1#L690

https://github.com/go-gitea/gitea/blob/8adba93498ccdde7edcb54e10f6a3d176c3815c4/docs/content/doc/advanced/config-cheat-sheet.en-us.md?plain=1#L695

**Review by wxiaoguang — DISMISSED** [review]
Then we should look into the problem. IMO `0` is a general value for defaults.

I will take a look at it, just put a request change mark here temporarily

**Comment by wxiaoguang** [comment]
It's a bug in the legacy `ini` package.

Then, at the moment, all `time.Duration` fields in `setting` can not accept option value 0 if there is already a non-zero default value.

```
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		// ParseDuration will not return err for `0`, so check the type name
		if vt.Name() == "Duration" {
			durationVal, err := key.Duration()
			if err != nil {
				if intVal, err := key.Int64(); err == nil {
					field.SetInt(intVal)
					return nil
				}
				return wrapStrictError(err, isStrict)
			}
			if isPtr {
				field.Set(reflect.ValueOf(&durationVal))
			} else if int64(durationVal) > 0 {  // 🐞 BUG HERE, even the key/value(0) exists, the ini code ignore the value
				field.Set(reflect.ValueOf(durationVal))
			}
			return nil
		}
```

**Comment by wxiaoguang** [comment]
After reading the ini code again, I do not have confidence that such behavior could be fixed soon if the author doesn't agree to change, it seems to cause some breaking behaviors.

So, at the moment, maybe all document should be updated accordingly, use `-1` for all duration.

**Comment by delvh** [comment]
@wxiaoguang That sounds to me as if this PR should indeed be marked `breaking`.
Otherwise users might not know to change their configurations.

**Comment by wxiaoguang** [comment]
IMO there is no code change, it doesn't break anything, it's a document bug fix only. And the fixes also works for 1.16.

If users do not find this bug (not affected), they do not need to change their configuration ......

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
