### PR TITLE
Fix dependency translations

### PR DESCRIPTION
**Pull request by justusbunsi**
Both `issues.dependency.issue_closing_blockedby` and `issues.dependency.pr_closing_blockedby` contained the other translation.

Signed-off-by: Steven Kriegler <61625851+justusbunsi@users.noreply.github.com>

### CODE REVIEW

**Comment by 6543** [comment]
beside eng all other translation will be overwritten by crowdin - in this case it's better to just fix english and let it retranslate by crowdin - the TM will help there :)

**Comment by 6543** [comment]
@justusbunsi but you can use current pull state to backport it to v1.15.0

**Comment by justusbunsi** [comment]
Done

> beside eng all other translation will be overwritten by crowdin - in this case it's better to just fix english and let it retranslate by crowdin - the TM will help there :)

Done.

**Review by techknowlogick — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@justusbunsi wana backport ?

**Comment by justusbunsi** [comment]
@6543 Already did 😉. https://github.com/go-gitea/gitea/pull/16755

**Pull request merged**
