### PR TITLE
Update vendor/go-sqlite3

### PR DESCRIPTION
**Pull request by typeless**
Update vendor/github/mattn/go-sqlite3.

### CODE REVIEW

**Comment by typeless** [comment]
Will update this PR when #5134 is merged.

**Comment by typeless** [comment]
> Will update this PR when #5134 is merged.

Done.

**Comment by lunny** [comment]
@typeless  I will rebuild the CI serval times to see if there is still random failed. And should this resolve #2040 ?

**Comment by lunny** [comment]
@typeless  I will rebuild the CI serval times to see if there is still random failed. And should this resolve #2040 ?

**Comment by typeless** [comment]
@lunny Yes

**Review by sapk — APPROVED** [review]

**Comment by typeless** [comment]
I split the PR into two. Now, this one is only for updating vendor/go-sqlite3. A later PR will update the build tags.

**Review by lunny — APPROVED** [review]

**Pull request merged**
