### PR TITLE
Fix windows build broken by #416

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by bkcsoft** [comment]
I am not a huge fan of doing this... is there not another lib we can use?

**Comment by lunny** [comment]
Maybe `endless`? But I only used this one.

**Comment by appleboy** [comment]
@bkcsoft [endless](https://github.com/fvbock/endless) doesn't also support windows platform now. I do the same way in my [gorush](https://github.com/appleboy/gorush) application.

for unix: https://github.com/appleboy/gorush/blob/v1.7.2/gorush/server_unix.go
for windows: https://github.com/appleboy/gorush/blob/v1.7.2/gorush/server_windows.go

LGTM 👍

**Comment by andreynering** [comment]
LGTM

**Pull request merged**
