### PR TITLE
Fixed Dutch spelling

### PR DESCRIPTION
**Pull request by jorisvddonk**
Minor spelling fixes for the Dutch translation.

### CODE REVIEW

**Comment by willemvd** [comment]
Since Dutch is my native language, I can say this is LGTM ;)

**Comment by strk** [comment]
trusted LGTM

**Comment by lunny** [comment]
please go to crowdin to do that, https://crowdin.com/translate/gitea

**Comment by willemvd** [comment]
Updated that in crowdin

**Comment by tboerger** [comment]
This can be updated via crowdin only.

**Pull request closed without merging**
