### PR TITLE
Fix blame row height alignment

### LINKED ISSUE #15858: Display problem in blame
- Gitea version (or commit ref): 1.15.0+dev-265-ge5723d655
- Git version: N/A
- Operating system: N/A
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (see screenshot)
  - [ ] No
- Log gist: N/A

## Description

There is a shift (which intensifies when the file grows) between the code and authors in blame page.

## Screenshot

Taken from https://gitea.com/gitea/git/blame/commit/e03eb393a2224110a4e3fde279bf67ae1ecd3b34/MAINTAINERS:
blame_gitea

### PR DESCRIPTION
**Pull request by noerw**
fixes #15858 (check there for a screenshot)

I'm not a CSS guru, so my approach may be suboptimal:
We ensure all rows have at least 20px height, and `.bottom-line` rows get 21px, to reproduce in `.lines-commit` what was already configured in for the code view.

I tested in current FF and chromium, **would be nice if someone could test on Safari as well.**

### CODE REVIEW

**Comment by silverwind** [comment]
I think this is the third time now that this alignment was broken. It should really be refactored to be line-based and not two columns side-by-side, but I guess we can workaround such a proper fix until then.

**Comment by silverwind** [comment]
Tested, working, except Safari which needs one additional fix to prevent line wrapping breaking the alignment:

```diff
diff --git a/web_src/less/_base.less b/web_src/less/_base.less
index e44e2ab84..c3a7f6ca2 100644
--- a/web_src/less/_base.less
+++ b/web_src/less/_base.less
@@ -1503,8 +1503,9 @@ a.ui.label:hover {

 .blame .code-inner {
   white-space: pre;
   word-break: normal;
+  word-wrap: normal; /* not using overflow-wrap because safari does not treat is an an alias */
 }

 .lines-commit {
   vertical-align: top;

**Review by zeripath — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
I think we need a backport of this to 1.14 too.

**Comment by silverwind** [comment]
Yeah looks like it.

**Pull request merged**
