### PR TITLE
[WIP] Release attachments replace if name exist

### LINKED ISSUE #9534: [feature] replace attachment when same name on uplaod
come up in #9529

@davidsvantesson point

### LINKED ISSUE #10919: Attachment links are not human readable again
- Gitea version (or commit ref): 1.11.4
- Operating system: CentOS 7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
After upgrading to v1.11.3 release attachment links are not human-readable again and now looks like `https://gitea.example/attachments/a0023262-7abf-461d-9271-2e9f195ecebc` instead of `https://gitea.example/xoxys/cups-rpm/releases/download/v.1.0.0`.

### PR DESCRIPTION
**Pull request by 6543**
close #10919
close #9534

TODO:
 * [x] revert parts of #9529
 * [ ] add check if attachment with name exist and delete old one
   * [ ] go backend
   * [ ] js frontend

### CODE REVIEW

**Comment by mxmehl** [comment]
Is this blocked by something? Would be great to have predictable/human-readable URLs again which are also shown in the UI, and do not have to be guessed :)

**Comment by 6543** [comment]
yes backend and frontend need changes see checkbox of that pull :/

**Comment by jolheiser** [comment]
fwiw I'm fine with moving the remaining TODOs to another PR.

**Comment by wxiaoguang** [comment]
It has been fixed by

* #23891

**Pull request closed without merging**
