### PR TITLE
Timeout test commands without complicated tricks

### PR DESCRIPTION
**Pull request by typeless**
Use `timeout` command to limit the run time of tests.

### CODE REVIEW

**Comment by zeripath** [comment]
So go test has an internal timeout of 10 minutes (from `go help testflag`):

```
	-timeout d
	    If a test binary runs longer than duration d, panic.
	    If d is 0, the timeout is disabled.
	    The default is 10 minutes (10m).
```

**Comment by typeless** [comment]
@zeripath 
`integration.sqlite.test` gives
```
  -test.timeout d
        panic test binary after duration d (default 0, timeout disabled)
```
So, that explains why we had to add the timeout in .drone.yml in the first place.

**Review by sapk — APPROVED** [review]

**Review by adelowo — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm shouldn't we just set the test.timeout on integration test?

**Comment by typeless** [comment]
@zeripath not sure if it’s the best way if we hardwire the timeout in the Makefile. It seems to me that the Makefile is for mechanisms and the .drone.yml is more or less for policies. Another way is to control the timeout flag provided by Go with an env variable.
That’s not bad either if it does not sound like an overkill.

**Pull request merged**
