### PR TITLE
Set the base url when migrating from Gitlab using access token or username without password

### LINKED ISSUE #11851: migrations: NewGitlabDownloader() will ignore baseUrl when using access token
When using the migrations from go 

- Gitea version (or commit ref): master 4a4977a1f0232bcef474495b8e2e2b4e3ce12c49

## Description

when creating a new GitlabDownloader with an access token instead of user/password, the provided baseUrl will be ignored.

### PR DESCRIPTION
**Pull request by gernoteger**
When migrating from gitlab, set the baseUrl in NewGitlabDownloader when using an access token or username without password

Fix #11851

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
From my little understanding of this code - this appears correct

**Comment by zeripath** [comment]
Have adjusted title and summary to more match our current system.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
yep it should not make problems - since SelfHosted GitLab is not supported jet (UI is blocking this)
but better change it now

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport

**Pull request merged**
