### PR TITLE
Refactor arch route handlers

### PR DESCRIPTION
**Pull request by wxiaoguang**

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Is it possible to replace `<...>` with `{...}` to keep the format of the usual chi parameters?

**Comment by wxiaoguang** [comment]
> Is it possible to replace `<...>` with `{...}` to keep the format of the usual chi parameters?

Nope, it is intentionally designed to distinguish it from the chi router's path parameter. Their behaviors are totally different.

**Comment by KN4CK3R** [comment]
Is it possible to mix `<...>` and `{...}` in a `MatchPath` call? If not there are less reasons to distinguish between them.

**Comment by wxiaoguang** [comment]
> Is it possible to mix `<...>` and `{...}` in a `MatchPath` call? If not there are less reasons to distinguish between them.

No, the reasons are strong e20fba38bd6393605d9b8d4e3bd5eac9bcc832d8

**Review by lunny — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]

**Pull request merged**
