### PR TITLE
Adding advanced label set.

### PR DESCRIPTION
**Pull request by ghost**
This pull request should add an advanced set of labels which can be used out of the box.

grafik

### CODE REVIEW

**Comment by opyale** [comment]
I was not sure about leaving semicolons where no description is needed, because i dont know how the parser handels it.

**Comment by opyale** [comment]
Current color of `Priority: Low`

grafik

**Comment by lunny** [comment]
You can just put it in your gitea instance custom folder. But I don't think it's necessary to merge it in gitea itself.

**Comment by 6543** [comment]
we can put into contrib?

**Comment by opyale** [comment]
@6543 Should i move my file to `contrib/options/label`?

**Comment by 6543** [comment]
@opyale would be nice :)

**Pull request closed without merging**
