### PR TITLE
Fix /orgs/{:orgname}/repos post endpoint

### PR DESCRIPTION
**Pull request by iondune**
Fixes the issue described in #11331 

`CreateOrgRepo` expects a parameter named `:org` but the route uses `:orgname` ([see here](https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L861)). Deprecated endpoint uses the same function, but its route uses `:org` so it works. This changes updates `CreateOrgRepo` to use the param name from the route, and updates the deprecated route to use the same.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@iondune now it does not match with swagger docu at all :(
can you either update swagger docu or move all to `org` as param?

**Review by adelowo — APPROVED** [review]

**Comment by 6543** [comment]
@adelowo @zeripath I know this fix it but the doc is outdated them :/

https://github.com/go-gitea/gitea/pull/11332/files#diff-6c945bcfcee3c77d704a5bd4218c6b68R309

needs an update + `make generate-swagger`

**Comment by zeripath** [comment]
@6543 that name isn't used by any code and it's not really a problem if the swagger name is different from the actual name used by the code. 

(Although I get your point that the swagger documentation is part of the documentation for the code and having it incorrect makes the whole process error prone.)

**Comment by 6543** [comment]
ok **orgname** -> **org** is not an option if we dont like to refactor all other functions :(

**Comment by 6543** [comment]
and `org` is used on all swagger docs ... -> this need a refactor but I'm ok with this now after having a look at this part of the api .... just meh

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
this will confilct with https://github.com/go-gitea/gitea/pull/11339

and I personaly prevere #11339

**Review by zeripath — CHANGES_REQUESTED** [review]
This will break multiple other org endpoints.

The correct solution is to change all of the :orgname endpoints to :org

**Comment by lafriks** [comment]
Closing as already fixed in other PR

**Pull request closed without merging**
