### PR TITLE
Fix view of readme file in the home code page.

### PR DESCRIPTION
**Pull request by jxshin**
Gitea attempts to display image file, pdf file, etc. named readme in the home code page (but it cannot).
I think only the markdown and plain-text file should be displayed, which is also the behavior of GitHub.

### CODE REVIEW

**Comment by silverwind** [comment]
Maybe we could also make the code more clear and rename `readmeExist` and `ReadmeExist` variables to `isReadmeFileName` and `IsReadmeFileName` which would make it more clear that the check is only for the filename.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
Can an image png/svg be a README?

**Comment by jxshin** [comment]
> Can an image png/svg be a README?

Hi, @lunny!   
In most cases, it does not, but  README.png / README.svg / README.pdf exists.
Examples: 
[https://github.com/funny/fastway](url)
[https://github.com/CYENS/ReinheritArApp](url)

**Comment by silverwind** [comment]
It seems GitHub's behaviour is to render the file as long as it's plaintext.

https://github.com/CYENS/ReinheritArApp/blob/main/docs/Readme.pdf does appear strange because the displayed bytesize (840kB) does not match the actual file size (131 bytes).

**Comment by lunny** [comment]
> It seems GitHub's behaviour is to render the file as long as it's plaintext.
> 
> https://github.com/CYENS/ReinheritArApp/blob/main/docs/Readme.pdf does appear strange because the displayed size (840kB) does not match the actual file size (131 bytes).

It's a LFS file.

**Comment by silverwind** [comment]
> > It seems GitHub's behaviour is to render the file as long as it's plaintext.
> > https://github.com/CYENS/ReinheritArApp/blob/main/docs/Readme.pdf does appear strange because the displayed size (840kB) does not match the actual file size (131 bytes).
> 
> It's a LFS file.

Ah, so that's an [LFS pointer](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage#pointer-file-format) which is plaintext, but GitHub does not support rendering the actual LFS file.

**Pull request merged**
