### PR TITLE
Add a stars link to the repo listed in dashboard repolist

### PR DESCRIPTION
**Pull request by yp05327**
I think it is better to add a stars link to the repo listed in dashboard repolist.

### CODE REVIEW

**Comment by yp05327** [comment]
image

**Comment by silverwind** [comment]
Seems this PR was missed, needs a rebase now because of SFC refactoring I think.

**Comment by lafriks** [comment]
From UX perspective imho it creates too much information that are secondary. I would understand if it was in repository explore page where that could be useful information but I don't see much added info in quick repository access list

**Comment by silverwind** [comment]
Agree on stars removal there. The list is fixed width and it takes away space for long repo names. GitHub frontpage `Top Repositories` also does not include stars fwiw.

**Comment by yp05327** [comment]
Agree to remove stars.

**Comment by yp05327** [comment]
Agree to remove stars.

**Comment by yp05327** [comment]
> Wanna make a new PR for it?

Yes. A new PR for it. And close this one.

**Pull request closed without merging**
