### PR TITLE
Revert increased width on pull pages

### LINKED ISSUE #21460: Regression for width on pull request
### Description

It seems like that there is a regression since #21012, which added `fluid padded` classes, regardless of split mode being enabled. This is causing the whole UI to take up all the available width, is this something we really want? In my eyes this seems like a regression/bug, it might make sense for the diff to be full-width(we are copying Github's behavior??) but not the other elements, which is currently happening.

CC @silverwind 

### Gitea Version

https://github.com/go-gitea/gitea/commit/94d6d93cc29dd8837d87e1aa58de8f52676d4963

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image
image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Not relevant

### Database

SQLite

### PR DESCRIPTION
**Pull request by Gusted**
- Revert a behavior from #21012, which liberally added `fluid padded` to non-split style pull pages, this caused it to take up the whole screen(such in split-style pull pages) on pull pages where the diff was shown.
- Resolves #21460

### Before
image
image

### After
image
image

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
LGTM.

My screen might be not wide enough at that moment so I didn't feel unusual 😁 

Maybe there could be some comments about why the IsSplitStyle is needed.

**Comment by lunny** [comment]
Since there are some diff UI in this page, I don't think making it narrow is a good idea.

**Comment by Gusted** [comment]
> Since there are some diff UI in this page, I don't think making it narrow is a good idea.

It was already narrow to begin with, but for some reason it was removed for the "unified" view(without any reason mentioned on the PR), which doesn't need that much space IMO.

I think if that's the design choice we want to go with, it should be adjusted as currently other elements are also being affected that shouldn't be affected(see Labels/Milestone buttons). But I don't see a lot of good reasons to increase the width of the diff one.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
I think we can discuss going full width for certain pages (GitHub also does full width on unified diff), but it needs to be done more carefully without affecting things like this did with the issue/pr page.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
