### PR TITLE
Fix delete pull head ref for DeleteIssue

### LINKED ISSUE #19655: delete a merged pull request return 500
```
exit status 1 - error: cannot lock ref 'refs/pull/2': 'refs/pull/2/head' exists; cannot create 'refs/pull/2'
 - error: cannot lock ref 'refs/pull/2': 'refs/pull/2/head' exists; cannot create 'refs/pull/2'
```

### PR DESCRIPTION
**Pull request by a1012112796**
In DeleteIssue the PR git head reference should be `/refs/pull/xxx/head` not `/refs/pull/xxx`

Fix #19655

### CODE REVIEW

**Comment by lunny** [comment]
Could you explain the bug and how this PR resolve it?

**Comment by a1012112796** [comment]
> Could you explain the bug and how this PR resolve it?

just a nit. the format of pull head ref is  ``refs/pull/{index}/head``, not ``refs/pull/{index}``.
image

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport to v1.17

**Comment by zeripath** [comment]
Honestly could we please try to write better PR opening comments. Explain what the PR is doing and why.

**Pull request merged**
