### PR TITLE
fix apple-touch-icon, regenerate images

### PR DESCRIPTION
**Pull request by silverwind**
Fixed semi-transparent pixels of apple-touch-icon.png.

I had to manually exclude public/img/loading.png from the commit because it's an APNG and one of the tools destroys the animation.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
Why delete public/img/telegram.png ...?

**Comment by jolheiser** [comment]
> Why delete public/img/telegram.png ...?

It wasn't deleted, just got smaller.

**Comment by silverwind** [comment]
Nothing is deleted here, just size-optimized.

APNG issue is https://github.com/google/zopfli/issues/118, by the way.

**Comment by 6543** [comment]
Ok, github bin diff view is missleading

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@NiTRoeSE can you confirm it is working now?

**Comment by NiTRoeSE** [comment]
> @NiTRoeSE can you confirm it is working now?

Yes i can confirm, looks good now.

@silverwind @6543 @zeripath 

Thanks for your work.

**Pull request merged**
