### PR TITLE
Use inline SVG for built-in OAuth providers

### PR DESCRIPTION
**Pull request by silverwind**
The plan is that all built-in auth providers use inline SVG for more flexibility in styling and to get the GitHub icon to follow `currentcolor`. This only removes the `public/img/auth` directory and adds the missing svgs to our svg build.

It should map the built-in providers to these SVGs and render them. If the user has set a Icon URL, it should render that as an `img` tag instead.

```
gitea-azure-ad
gitea-bitbucket
gitea-discord
gitea-dropbox
gitea-facebook
gitea-gitea
gitea-gitlab
gitea-google
gitea-mastodon
gitea-microsoftonline
gitea-nextcloud
gitea-twitter
gitea-yandex
octicon-mark-github
```

GitHub logo is now white again on dark theme:

Screenshot 2023-06-12 at 21 45 34

### CODE REVIEW

**Comment by silverwind** [comment]
@wxiaoguang can you assist me with this ImageHTML method mentioned in https://github.com/go-gitea/gitea/pull/25030#issuecomment-1584325413?

**Comment by wxiaoguang** [comment]
Almost done in eeaabf18d5225da08aed82d8decb04107ea7ad17

image

**Comment by silverwind** [comment]
Awesome, thanks!

**Comment by silverwind** [comment]
Ready again, it seems to work nicely. I tested adding a custom icon url and I fixed the loading spinner being misaligned as well, and the loading spinner now looks better with a single button because it is properly centered on the buttons.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
