### PR TITLE
SQLite has a query timeout. Hopefully fixes most 'database locked' errors

### PR DESCRIPTION
**Pull request by bkcsoft**
This adds a wait timeout for when the database is locked. Hopefully this should fix the `database table is locked` errors.

### CODE REVIEW

**Comment by ethantkoenig** [comment]
Does this actually fix the problem? From what I can tell, this just means we'll get an error of the form "Busy timeout" instead of an error of the form "Table XYZ is locked"

**Comment by bkcsoft** [comment]
@ethantkoenig With this PR, SQLite should in theory wait for `timeout` milliseconds trying to get a lock, which in theory means _less_ `table is locked`-errors, not that they go away. If you want that error to go away, don't use SQLite :trollface:

**Comment by ethantkoenig** [comment]
Oh I see, LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
