### PR TITLE
Fix broken avatars since #15301

### LINKED ISSUE #15727: Avatars missing after recent upgrade (47fd15693)
- Gitea version (or commit ref): `1.15.0+dev-223-g47fd15693`
- Git version: built from `next`, not pertaining to this issue
- Operating system: Arch Linux
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] haven't tried

## Description
After upgrading to a commit merged by #15301 user-supplied user avatars won't load and org avatars won't load at all.
org avatars that should load from gravatar are looked for locally and end up 404ing

## Screenshots
users:
image

orgs:
image

### PR DESCRIPTION
**Pull request by zeripath**
There was a missing * from the avatars routes in #15301.

Fix #15727

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by silverwind** [comment]
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf maybe you can confirm this.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf maybe you can confirm this.

on it

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
thanks @zeripath  && @silverwind , this definitely fixes #15727 🚀 
user-supplied user avatars: shown ✔️ 
org gravatars: shown ✔️ 
user-supplied repo avatars (those were missing, too :D): shown ✔️

**Review by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf — APPROVED** [review]
🚀 🚀 🚀

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
I've added a testcase to ensure that they don't break again

**Comment by zeripath** [comment]
make lgtm work

**Review by KN4CK3R — APPROVED** [review]

**Pull request merged**
