### PR TITLE
Don't require team membership for team search results

### PR DESCRIPTION
**Pull request by noerw**
Another regression from #18518. 

Note that tests for other routes expect non-team-members not to have access to it:
- https://github.com/go-gitea/gitea/blob/4aafe26007b51e806bd9529870def18223bc18f5/tests/integration/api_team_test.go#L42
- https://github.com/go-gitea/gitea/blob/79224316ae7db8cbdcf577a512e27ff4e8033ead/routers/web/org/teams.go#L342

But I'd argue this assumption breaks the quite valid use-case of searching for teams you are not a member of.
Also the `/api/v1/orgs/{org}/teams` endpoint (available to org members)  will happily list all existing teams, so there is some inconsistency here already. I'd say you don't need to be team member to see details, as the information gained is not exactly sensitive.

related discussion for permissions in the frontend:
- #20844
- https://github.com/go-gitea/gitea/issues/20658

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
CI failure is related.

**Comment by Gusted** [comment]
> as the information gained is not exactly sensitive.
```go
		apiTeams[i] = &api.Team{
			ID:                      teams[i].ID,
			Name:                    teams[i].Name,
			Description:             teams[i].Description,
			IncludesAllRepositories: teams[i].IncludesAllRepositories,
			CanCreateOrgRepo:        teams[i].CanCreateOrgRepo,
			Permission:              teams[i].AccessMode.String(),
			Units:                   teams[i].GetUnitNames(),
			UnitsMap:                teams[i].GetUnitsMap(),
		}
```

Which information is exactly needed, maybe we could limit it to just the necessary fields? I do find this to be quite "senstive" as it laids out the whole team structure in a organization.

**Comment by Gusted** [comment]
I'm sorry @noerw for the late reaction, I'm pretty sure I was misunderstanding this code and situation. Limiting the return results to Name + Description is fine IMO.

**Comment by lunny** [comment]
replaced by #20844

**Pull request closed without merging**
