### PR TITLE
Update Chroma to v2.13.0

### PR DESCRIPTION
**Pull request by JakobDev**
This adds new lexers and includes some fixes. See https://github.com/alecthomas/chroma/releases/tag/v2.13.0 for the full changelog.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by techknowlogick** [comment]
Thanks, @JakobDev. Could you run `make tidy` and push the changes?

@ maintainers: what do you think about backporting this? I don't see any breaking changes in the chroma changelog, and this could also be considered a bug fix.

**Review by jolheiser — APPROVED** [review]
lgtm pending tidy

**Comment by techknowlogick** [comment]
@jolheiser I've applied the backport label. As this changes go.mod I suspect our bot won't be able to apply it directly. @JakobDev, the bot will probably ping you once this is merged asking you to do a manual backport, but we can handle the backport (with attribution to you for the original PR ofc) to not add anything extra onto your plate.

**Comment by silverwind** [comment]
We don't usually backport stuff like this, but I guess if author is willing, they can do it.

**Pull request merged**
