### PR TITLE
Kill testing processes if the test takes too long

### PR DESCRIPTION
**Pull request by typeless**
A temporary band-aid to avoid resource-wasting CI build.
It prints the backtrace in case of timeout.

For #5172

### CODE REVIEW

**Comment by lunny** [comment]
@typeless please resolve the conflict

**Comment by typeless** [comment]
@lunny Done.

**Comment by lunny** [comment]
Could you reenable test-sqlite3 on this PR?

**Comment by typeless** [comment]
@lunny Sure.

**Comment by lunny** [comment]
I restarted the CI 3 times and everytime CI passed and there is no timeout.

**Comment by lunny** [comment]
And the killing maybe unnecessary.

**Review by lunny — APPROVED** [review]

**Comment by typeless** [comment]
@lunny If there are no concerns, I would like to keep it longer or even apply to all the database tests in the hope that some mysterious, sporadic hanging bug can be spotted (which could be very hard to reproduce).

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
