### PR TITLE
Fix empty file download

### PR DESCRIPTION
**Pull request by lafriks**

### CODE REVIEW

**Comment by lunny** [comment]
So this will let you download an empty file?

**Comment by lafriks** [comment]
This will return corectly empty file when viewing in Raw mode. Currently for empty files it did return 1024 zero byte file

**Comment by strk** [comment]
It looks to me that better error handling should be performed for the value of `n`.
What happens, for example, if n is negative ? Is that possible at all ?
Anyway, the change LGTM, although I'd be much much happier if it came with unit tests for various combinations of download files (including unreadable files, for checking error handling)

**Comment by strk** [comment]
Another problem with that code (current as well as proposed): it looks like it would truncate files bigger than 1024 bytes before sending them to client. Also, reading all files in memory before sending them to http socket doesn't seem to be the best way to do this. Just in case you feel like further improving this contribution @lafriks

**Comment by lafriks** [comment]
No it reads in memory only first 1024 bytes to detect file type (text/image/pdf/other) later in code it streams remaining bytes directly from reader

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Pull request merged**
