### PR TITLE
Add deleted_branch table fixture

### PR DESCRIPTION
**Pull request by lafriks**
As title

### CODE REVIEW

**Comment by Morlinest** [comment]
Why we need this "empty" file?

**Comment by lafriks** [comment]
@Morlinest to reset table to empty (delete all rows) between tests, otherwise anything that gets inserted there stays between tests that can result in failures or unexpected behaviour.

**Comment by Morlinest** [comment]
@lafriks OK, that makes sense.

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
CI failed.

**Comment by lafriks** [comment]
@lunny Tests where abusing that deleted branches table was not cleared between tests so I had to fix them :)

**Comment by Morlinest** [comment]
LGTM

**Pull request merged**
