### PR TITLE
hide delete/restore button on archived repos

### PR DESCRIPTION
**Pull request by 6543**
close issue #7653

reverence https://github.com/go-gitea/gitea/issues/7454

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@6543 should this be back port to v1.9?

**Comment by 6543** [comment]
@lunny  We can but i think git cherry pick wont work

**Comment by 6543** [comment]
new PR vor 1.9?

**Comment by 6543** [comment]
Or we backport PR #7624 and then this one it will work

**Comment by lunny** [comment]
@6543 I mean only back port this PR to v1.9 .

**Comment by lafriks** [comment]
Is it checked also in server-side correctly?

**Comment by 6543** [comment]
> Is it checked also in server-side correctly?

?

**Comment by lunny** [comment]
I think it's not yet. see https://github.com/go-gitea/gitea/blob/50d8d171f01b82f58aa38c16495590c798f3dccb/routers/repo/branch.go#L53

**Pull request merged**
