### PR TITLE
Replace pubkey with privkey in keys_ssh.tmpl

### PR DESCRIPTION
**Pull request by rluetzner**
If a user wants to verify an SSH public key from their account they have
to sign the randomly generated token with their private key.

Prior to this change the example command prompted to sign the token with
their public key instead.

Signed-off-by: Robert Lützner <robert.luetzner@pm.me>

### CODE REVIEW

**Comment by rluetzner** [comment]
Call me stupid, but I just ran into this when I tried to verify my SSH key. Of course it has to be the public key, but I blindly followed the instructions.

Here's an image showing what I changed:

image

**Review by wxiaoguang — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
it should work with pub too as it points to the priv ...
but directly pointing to priv do also work

**Comment by rluetzner** [comment]
> it should work with pub too as it points to the priv

@6543 , you're right. I didn't check that yesterday, but tried it out just now.

I encountered an issue when verifying my SSH key yesterday. It basically told me that something seems to have expired. Maybe if I had just retried it immediately with the path to my public key it would have worked as well. I used my private key the second time around and it worked, so I assumed that the hint is wrong.

Thanks for clearing that up. 🙂

**Comment by wxiaoguang** [comment]
According to `man`:

```
     -Y sign

The key used for signing is specified using the -f option and may refer to 
either a private key, 
or a public key with the private half available via ssh-agent(1)
```

Keep the `pubkey` is more likely to be how the key is used by ssh. Then I think we can keep the old prompt.

**Comment by 6543** [comment]
oh damed - just merged :X

**Comment by wxiaoguang** [comment]
nvm, either is fine. indeed the purpose is to check the key itself. private key works in all cases.

**Pull request merged**
