### PR TITLE
Apply #12576 to top right reaction picker

### PR DESCRIPTION
**Pull request by CL-Jeremy**
I'll just open this since I cannot find a reason for the bug below.

After this PR, the reaction emoji is slightly shifted toward right in the top right drop-down. Seeing this in both Chromium (81) and Safari, but not in Firefox. Bottom left picker is unaffected.

Bildschirmfoto 2020-08-27 um 21 30 23

Bildschirmfoto 2020-08-27 um 21 32 52

Edit: confirmed to be Apple-specific. Should have something to do with the rendering engine.

### CODE REVIEW

**Comment by lafriks** [comment]
how does it look in dark theme?

**Comment by CL-Jeremy** [comment]
In Arc Green theme the only change is the rule for overriding highlight color on hover. The two popups would match exactly except for the bug I mentioned earlier.

**Comment by silverwind** [comment]
I'm not sure what this change exactly fixes from the screenshots. Can you showcase a before/after comparison?

Last time I worked at that picker, I had the idea of rewriting it to flexbox because it's quite a hack currently, layout-wise.

**Comment by CL-Jeremy** [comment]
As the title suggests, this PR adds hover effect to the picker in the top right corner.

For comparison, goto try.gitea.io and click on any of the top right picker icons.

The previous `:hover` styling targeted `.select-reaction .item` in  `.segment.reactions` only, leaving out the top ones.

**Comment by silverwind** [comment]
Ah I see. Totally missed the fact that there's two ways to trigger that menu.

**Review by silverwind — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
