### PR TITLE
Use bind mount volumes

### PR DESCRIPTION
**Pull request by kdumontnu**
I recently migrated my deployment to rootless and could not get the config to work as described in https://docs.gitea.io/en-us/install-with-docker-rootless/ when running as an unprivileged user.

My environment is:
Ubuntu 20.04
Docker 20.10.3
Docker-Compose 1.25

The problem appears to be that the direct bind-mount we suggest in `./data:/var/lib/gitea` overrides the line in the dockerfile.rootless `RUN chown git:git /var/lib/gitea /etc/gitea` because it can only mount these with the permissions of the host user (which is root in the docker image). See the related upstream [issue](https://github.com/moby/moby/issues/2259)

Here I use a different method to bind the volumes. It adds some bloat to the config, but it works as intended.

Note: this might only work for Linux, so another option is I can revert most of the doc, but add a section "## Binding Volumes on Linux Host"

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by CirnoT** [comment]
This will work only on Linux. The alternative is to set `--user` so that the container's user matches with owner of mounted volume.

> overrides the line in the dockerfile.rootless RUN chown git:git /var/lib/gitea /etc/gitea

The `RUN` happens during container build, not on runtime, so nothing on runtime can override it. I don't see a point of doing chown on `/var/lib/gitea` however as it will be replaced (along with its permissions) by mounted volume.

**Comment by CirnoT** [comment]
The linked issue refers to named volumes (`docker volume`), which indeed are always owned by `root` (but are just directories so can be chown'd on host if necessary). For mounts, the container see permissions of files and directories inside the same as host, which is the same behavior as you would do normal `mount` on Linux (so, `chown git:git /mnt/test` has no meaning if you `mount` something on that directory)

**Comment by kdumontnu** [comment]
> This will work only on Linux. The alternative (or rather, requirement for rootless) is to set `--user` so that the container's user matches with owner of mounted volume.

In the docker container there are two users: `root` (which has the same UID as the host user running docker) and `git` (created in dockerfile). Setting `--user root` does indeed work, but kind of defeats the security benefits of using docker rootless.

> > overrides the line in the dockerfile.rootless RUN chown git:git /var/lib/gitea /etc/gitea
> 
> The `RUN` happens during container build, not on runtime, so nothing on runtime can override it.

Maybe I worded this poorly. As you say, when you mount the directory in dockerfile the above `chown` has no meaning.

**Comment by kdumontnu** [comment]
@CirnoT Can you take a look at the updates? Essentially, I just called out a section for linux. I haven't tested rootless on MacOS.

**Comment by CirnoT** [comment]
> In the docker container there are two users: root (which has the same UID as the host user running docker) and git (created in dockerfile). Setting --user root does indeed work, but defeats some of the benefits of using docker rootless.

Sorry but I believe you are missing the point of `--user` flag. https://docs.docker.com/engine/reference/run/#user
The provided UID:GID should match your HOST user that owns the directory with Gitea files, it does not have to exist in container.

**Comment by kdumontnu** [comment]
> Sorry but I believe you are missing the point of `--user` flag. https://docs.docker.com/engine/reference/run/#user
> The provided UID:GID should match your HOST user that owns the directory with Gitea files, it does not have to exist in container.

It's entirely possible I'm mistaken on this front (I'm far from a docker expert). However, I spent quite a bit of time trying to get this to work. From the link you sent "root (id = 0) is the default user **within a container**... operator can override by passing the -u option" This is essentially what I found - it only works when I set user=root. In the case of rootless `root (id = 0)` in the container is mapped to the host user running docker. 

Yes, I can run as container `root`, but that user still has elevated permissions compared to the `git` user in the container.

> As such, this PR is unnecessary, the requested scenario is possible right now out of the box, you just had wrong assumptions on what you could and could not do.

The [basic instruction](https://docs.gitea.io/en-us/install-with-docker-rootless/#basics) we provide in the docker rootless documentation fails on Linux. Can you show me the commands to run to make it work without using `--user=root`?

**Comment by CirnoT** [comment]
>The basic instruction we provide in the docker rootless documentation fails on Linux. Can you show me the commands to run to make it work without using --user=root?

```sh
# ls -l
drwx------ 7 git  git  4096 Mar  7 07:05 gitea
drwx------ 5 git  git  4096 Mar  7 07:06 repos

# ls /home/git/gitea
conf  custom  data  git  log

# id git
uid=1001(git) gid=1001(git) groups=1001(git)

# docker run -d --restart=always --pull=always --user 1001:1001 \
-v /home/git/gitea:/var/lib/gitea \
-v /home/git/gitea/conf:/etc/gitea \
-v /home/git/repos:/var/lib/repos \
-v /etc/timezone:/etc/timezone:ro \
-v /etc/localtime:/etc/localtime:ro \
--publish 127.0.0.1:3000:3000 --publish 22:2222 \
--name=gitea gitea/gitea:latest-rootless
```

```ini
RUN_MODE = prod

[repository]
ROOT           = /var/lib/repos

[server]
DOMAIN                   = gitea.com
HTTP_PORT                = 3000
SSH_PORT                 = 22
START_SSH_SERVER         = true
SSH_LISTEN_PORT          = 2222
BUILTIN_SSH_SERVER_USER  = git

[picture]
AVATAR_STORAGE_TYPE            = local
REPOSITORY_AVATAR_STORAGE_TYPE = local

[security]
INSTALL_LOCK          = true

[ssh.minimum_key_sizes]
ED25519 = 256
ECDSA   = 256
RSA     = 2048
DSA     = -1

[lfs]
STORAGE_TYPE = local

[attachment]
STORAGE_TYPE  = local
```

**Comment by sapk** [comment]
I may have not be especially clear but if you run without `--user`  or docker-compose equivalent you need to make sure that the folder is owned by `1000:1000` (default uid:gid of user git in the image) and it will work perfectly.

Using `$(id -u):$(id -g)` feel not better as it is less likely to be the default mode to run with the same uid:gid as the user you are logged. For example, on my machine it is `69201586:69200513` which far from what it will be in the running container by default.

(To be verified) If the folder is not created, you need to create it first or docker will create with root ownership.

The docs may definitively lack for corner cases.

**Pull request closed without merging**
