### PR TITLE
Avoid '0 new commits' messages to be send to webhook

### LINKED ISSUE #10498: Slack webhook showing message 0 new commits pushed
- Gitea version (or commit ref): 1.11.1
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When deleting a branch after a PR merge, the following messages are printed from Slack webhook:

`...branchname] branch deleted by cornel`
`...branchname] 0 new commits pushed by cornel`

is the `0 new commits pushed` message intentional/needed?

### PR DESCRIPTION
**Pull request by cornelk**
Fixes #10498

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
looks good - since only on push you will have new commits

**Review by guillep2k — APPROVED** [review]
Sounds about right.

**Comment by zeripath** [comment]
make lg-tm work

**Comment by CirnoT** [comment]
Should be marked as breaking possibly, Drone did depend on this to fetch additional data for tags https://github.com/drone/drone/blob/c81263687c4af650e4a0d05444f2fc5a1541e5be/service/hook/parser/parse.go#L189

**Pull request merged**
