### PR TITLE
Fix activity inconsistency when delete pull request

### PR DESCRIPTION
**Pull request by CaiCandong**
Description：
When I delete a PR, I find that the entry is still in the feed stream on the home page. If I click on it, I get 404 and 500 errors.

Causes:
	When deleting the Issue, the corresponding `activity` was deleted using `issue.ID` by mistake, when it should have used `issue.Index`.

Screenshot(gif):
gif

### CODE REVIEW

**Comment by wxiaoguang** [comment]
It's not right.

I fix it by the way in Bypass MariaDB performance bug of the "IN" sub-query, fix incorrect IssueIndex #26279

**Comment by CaiCandong** [comment]
> It's not right.

You're right, I didn't notice the operation related to `comment` .

**Comment by CaiCandong** [comment]
It's been fixed in #26279

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
Please review https://github.com/go-gitea/gitea/pull/26279 which has a full fix for this problem and has tests.

**Pull request closed without merging**
