### PR TITLE
Limit length of repo description and repo url input fields

### PR DESCRIPTION
**Pull request by JakobDev**
Both allow only limited characters. If you input more, you will get a error
message. So it make sense to limit the characters of the input fields.

Slightly relax the MaxSize of repo's Description and Website

### CODE REVIEW

**Comment by delvh** [comment]
repo struct
That doesn't look to me as if we limit it to 255 chars.
If we do throw an error after 256 chars, then we should probably investigate and fix that error beforehand.

**Review by lunny — DISMISSED** [review]

**Comment by 6543** [comment]
Would be nice to add a screenshot on how it looks like if you put to much chars into it

**Comment by wxiaoguang** [comment]
> That doesn't look to me as if we limit it to 255 chars. If we do throw an error after 256 chars, then we should probably investigate and fix that error beforehand.

IIRC, XORM has a "feature" that it implies to use `VARCHAR(255)` if there is no data-type in the `xorm:` tag.

So, adding `maxlength` could be good here.

(off-topic: is `varchar(255)` too short for the description field?)

**Comment by 6543** [comment]
> (off-topic: is varchar(255) too short for the description field?)

I would say yes

**Review by 6543 — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — DISMISSED** [review]
After reading the code again, I found that the data-types are messy.

For example: User.Description has no `xorm` tag (no data-type, default to `varchar(255)`), while Repository.Description is declared as `xorm:TEXT` shouldn't have the 255 limitation.

Instead of setting the `maxlength` everywhere, I think maybe we should fine tune every field accordingly.  delvh's first comment is more reasonable. For example: relax the form's MaxSize check?

And I think we have the agreement that 255 for a description field is too small 😂

So just put a Request Change here to get more time to think about it.

**Comment by wxiaoguang** [comment]
According to my test, 8-line description is around 1024 chars, it should satisfy most cases. (see the screenshot)

<details>

image

</details>


@JakobDev 

Could you also try this patch? It relaxes the repo Description MaxSize to 2048, Website MaxSize to 1024.

Then the form can have maxlength=2048/1024 accordingly.

These limitations should be good for most cases.

```diff
diff --git a/modules/structs/repo.go b/modules/structs/repo.go
index 6a5736898..c7358372c 100644
--- a/modules/structs/repo.go
+++ b/modules/structs/repo.go
@@ -111,7 +111,7 @@ type CreateRepoOption struct {
        // unique: true
        Name string `json:"name" binding:"Required;AlphaDashDot;MaxSize(100)"`
        // Description of the repository to create
-       Description string `json:"description" binding:"MaxSize(255)"`
+       Description string `json:"description" binding:"MaxSize(4096)"`
        // Whether the repository is private
        Private bool `json:"private"`
        // Label-Set to use
@@ -140,9 +140,9 @@ type EditRepoOption struct {
        // unique: true
        Name *string `json:"name,omitempty" binding:"OmitEmpty;AlphaDashDot;MaxSize(100);"`
        // a short description of the repository.
-       Description *string `json:"description,omitempty" binding:"MaxSize(255)"`
+       Description *string `json:"description,omitempty" binding:"MaxSize(4096)"`
        // a URL with more information about the repository.
-       Website *string `json:"website,omitempty" binding:"MaxSize(255)"`
+       Website *string `json:"website,omitempty" binding:"MaxSize(2048)"`
        // either `true` to make the repository private or `false` to make it public.
        // Note: you will get a 422 error if the organization restricts changing repository visibility to organization
        // owners and a non-owner tries to change the value of private.
@@ -208,7 +208,7 @@ type GenerateRepoOption struct {
        // Default branch of the new repository
        DefaultBranch string `json:"default_branch"`
        // Description of the repository to create
-       Description string `json:"description" binding:"MaxSize(255)"`
+       Description string `json:"description" binding:"MaxSize(4096)"`
        // Whether the repository is private
        Private bool `json:"private"`
        // include git content of default branch in template repo
@@ -316,7 +316,7 @@ type MigrateRepoOptions struct {
        LFS            bool   `json:"lfs"`
        LFSEndpoint    string `json:"lfs_endpoint"`
        Private        bool   `json:"private"`
-       Description    string `json:"description" binding:"MaxSize(255)"`
+       Description    string `json:"description" binding:"MaxSize(4096)"`
        Wiki           bool   `json:"wiki"`
        Milestones     bool   `json:"milestones"`
        Labels         bool   `json:"labels"`
diff --git a/services/forms/repo_form.go b/services/forms/repo_form.go
index 4eb20d297..d8e6294bb 100644
--- a/services/forms/repo_form.go
+++ b/services/forms/repo_form.go
@@ -34,7 +34,7 @@ type CreateRepoForm struct {
        UID           int64  `binding:"Required"`
        RepoName      string `binding:"Required;AlphaDashDot;MaxSize(100)"`
        Private       bool
-       Description   string `binding:"MaxSize(255)"`
+       Description   string `binding:"MaxSize(4096)"`
        DefaultBranch string `binding:"GitRefName;MaxSize(100)"`
        AutoInit      bool
        Gitignores    string
@@ -76,7 +76,7 @@ type MigrateRepoForm struct {
        LFS            bool   `json:"lfs"`
        LFSEndpoint    string `json:"lfs_endpoint"`
        Private        bool   `json:"private"`
-       Description    string `json:"description" binding:"MaxSize(255)"`
+       Description    string `json:"description" binding:"MaxSize(4096)"`
        Wiki           bool   `json:"wiki"`
        Milestones     bool   `json:"milestones"`
        Labels         bool   `json:"labels"`
@@ -116,8 +116,8 @@ func ParseRemoteAddr(remoteAddr, authUsername, authPassword string) (string, err
 // RepoSettingForm form for changing repository settings
 type RepoSettingForm struct {
        RepoName               string `binding:"Required;AlphaDashDot;MaxSize(100)"`
-       Description            string `binding:"MaxSize(255)"`
-       Website                string `binding:"ValidUrl;MaxSize(255)"`
+       Description            string `binding:"MaxSize(4096)"`
+       Website                string `binding:"ValidUrl;MaxSize(2048)"`
        Interval               string
        MirrorAddress          string
        MirrorUsername         string
```

**Comment by JakobDev** [comment]
@wxiaoguang I have now applied the patch

**Comment by wxiaoguang** [comment]
Let's try if it works well ~

**Pull request merged**
