### PR TITLE
Dockerfile for docs copy proper files into image

### PR DESCRIPTION
**Pull request by techknowlogick**
fixes docker build from: #2874

drone-docker plugin uses the base dir as context even when referring to other Dockerfiles in different dir

### CODE REVIEW

**Comment by lunny** [comment]
I think maybe add a route `/docs` to the folder and link Help to self `/docs`.

**Comment by techknowlogick** [comment]
Thanks for feedback @lunny 

For this PR I'm just trying to keep it as simple as I can to fix this build when on master branch: https://drone.gitea.io/go-gitea/gitea/2031/17

**Comment by lunny** [comment]
@techknowlogick That's OK. That could be done by future PRs.

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
@techknowlogick still failing :(

**Pull request merged**
