### PR TITLE
Add language search support in notification watching page

### PR DESCRIPTION
**Pull request by yp05327**
Mentioned https://github.com/go-gitea/gitea/pull/26425#discussion_r1289795836

After:
image

### CODE REVIEW

**Review by puni9869 — APPROVED** [review]

**Comment by lunny** [comment]
But how to remove the filter from UI?

**Comment by yp05327** [comment]
> But how to remove the filter from UI? Maybe you can get some ideas from #24212

We don't have this now, so #24212 is a solution for this which doesn't related to this PR.

**Comment by yp05327** [comment]
emmm, it can be added in #24212. But #24212 is broken now. Any plan to fix it?

**Comment by yp05327** [comment]
Let's wait #29044, then finish or close this one.

**Pull request closed without merging**
