### PR TITLE
Fix pull request commit status in user dashboard list

### PR DESCRIPTION
**Pull request by yzzyx**
Unfortunately, this list was missed in PR #8316
This pull-request fixes the issue in this list as well. The change makes this lookup identical to the on in `templates/repo/issue/list.tmpl`.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Please send backport to 1.9

**Comment by dschmidt** [comment]
Which branch do they need to be sent to for 1.9? release/1.9? Or is there some WIP branch before release/1.9 becomes 1.9.4?

**Comment by lafriks** [comment]
Yes cherey-pick merged commit and send it to `release/1.9` branch

**Comment by lunny** [comment]
@yzzyx Please send backport to release/1.9 branch so that we can release this ASAP.

**Comment by yzzyx** [comment]
@lunny backport created in PR #8339 with fixes from both this pullrequest and PR #8316.

**Pull request merged**
