### PR TITLE
Fix potential assignee query for repo

### LINKED ISSUE #18992: User assignment proposals broken
### Gitea Version

1.16.3 (codeberg)

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

codeberg deployment (= building from source with patches)

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

We have received several concerning reports of users that the "Assign user" feature for issues, as well as mentioning via `@` in the text box shows up strange users (users in no relation to the project). Also, some users who have access to the repo are apparently missing.

I could reproduce at https://try.gitea.io/repoCountIssues/9 (see screenshots). This user is not a collaborator of the repo, not in the org, not a watcher nor stargazer, nor has it opened an issue. I can't find any relation.

We received multiple reports via email, direct messages and a public post on Mastodon a while ago, see https://mastodon.social/@unfa/107875501190417072

It's a little concerning, and it would be nice to get a confirmation this does not grant strangers any permissions on those repos.

### Screenshots

image
image

### PR DESCRIPTION
**Pull request by fnetX**
Fix #18992

### CODE REVIEW

**Comment by fnetX** [comment]
@zeripath I think you should check this.

**Review by zeripath — APPROVED** [review]

**Review by Gusted — APPROVED** [review]

**Comment by Gusted** [comment]
Time to add a test for this function? 😅

**Comment by fnetX** [comment]
If someone would like to assist me there, I'm not yet familiar with the test system for Gitea ...

**Comment by Gusted** [comment]
@fnetX https://github.com/fnetX/gitea/pull/3 The code should be relatively self-exploinatary. The "mocked" database files are loaded from `models/fixtures/<table_name>.yml`, I've chosen for Repo 21 explicitly as there are 2 collaborates with write access added via `models/fixtures/collaboration.yml` so that should avoid regression for that part(not for the team part...)

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
wait https://github.com/fnetX/gitea/pull/3

**Review by Gusted — APPROVED** [review]

**Comment by Gusted** [comment]
@lunny has been merged.

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
