### PR TITLE
Fix webpack license warning

### PR DESCRIPTION
**Pull request by silverwind**
#19999 introduced a indirect dependency with a license that was not on our allowlist yet which produced this warning during webpack:

````
WARNING in License: citeproc@2.4.62 has disallowed license CPAL-1.0 OR AGPL-1.0
````

I've added both licenses to the allowed list and made it so webpack will now abort on such license errors so that we don't miss those next time.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
With AGPL being included what are the implications of that?

**Review by jolheiser — DISMISSED** [review]
As per @techknowlogick I would need to know the implications of AGPL code being used by Gitea. Do we need to revert the other PR as well that introduced it?

**Comment by lunny** [comment]
> 

I think maybe we have to revert because the two licenses are not compatible. And we need to have a tool to check the licenses problem in CI.

**Comment by silverwind** [comment]
The package repo in question is https://github.com/juris-m/citeproc-js. As the package is dual-licensed, I think we may also just allow [CPAL](https://en.wikipedia.org/wiki/Common_Public_Attribution_License) only and still satisfy the license check.

I think the main problem with the GPL family is "any [derivative work](https://en.wikipedia.org/wiki/Derivative_work) must be distributed under the same or equivalent license terms", but I'm no expert on this.

**Comment by silverwind** [comment]
According to https://github.com/Juris-M/citeproc-js/issues/79#issuecomment-406815993, the author just wants attribution, and we give them that via license.txt already.

**Comment by silverwind** [comment]
I've reduced the SPDX expression to accept just `CPAL-1.0`, which is the less-restrictive of the two and the validation still passes.

**Comment by jolheiser** [comment]
🎺 🤖

**Pull request merged**
