### PR TITLE
Markdown: Enable wrapping in code blocks and a color tweak

### PR DESCRIPTION
**Pull request by silverwind**
- Enable wrapping of long lines in code blocks like already done in code view.
- Slightly lighten the background of code blocks on default theme.
- Darken the background on inline code and kbd elements on arc-green.

Screen Shot 2020-12-07 at 23 11 14
Screen Shot 2020-12-07 at 23 11 23

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind can we somehow indicate if it's an auto linebreak?

so you can see the difference between
```
echo hi this is a joke .......
rm -r -f data
```
and
```
echo hi this is NO joke .......
rm -r -f data
```

**Comment by silverwind** [comment]
Hmm, I don't think it's possible to interact with forced linebreaks in CSS. Would probably be even hard to do in JS.

How would you want indicate it? Icon on the end of the line?

**Comment by 6543** [comment]
> ... Icon on the end of the line?
not a bad idear - but if it will create thousand of js/css lines then forgett it

**Comment by lafriks** [comment]
I don't think that's possible to add something like that

**Comment by silverwind** [comment]
Yeah, not easily possible. If we were to split each line into a `<div>` of its own, it may be possible with some advanced JS to detect wrapped lines, but I guess it'll be a bigger refactor and we'd want to also do that on the code view. Maybe something for later.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind thanks for the info :)

**Comment by silverwind** [comment]
For reference, something like https://github.com/xdamman/js-line-wrap-detector might be of use but it's a rather finicky thing to do in JS and I'd certainly expect it to break on edge cases.

**Pull request merged**
