### PR TITLE
Filter out the already added dependencies from the depends-on dropdown

### PR DESCRIPTION
**Pull request by HEREYUA**
Fix:[#27449](https://github.com/go-gitea/gitea/issues/27449)

**before**
image

**after**
image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Thank you for your PR but it doesn't look good to me .... there are some nits in code. 

The best approach should be: do it in backend, do not return added dependency, if possible.

----

If it is intentionally done in frontend, it could be simplified to:

```
<a class="title ..." data-issue-dependency-index="{{.Issue.Index}}">
```

then check whether the element `.item.dependency [data-issue-dependency-index]=${index}` exists in current dropdown items.

**Comment by HEREYUA** [comment]
> Thank you for your PR but it doesn't look good to me .... there are some nits in code.
> 
> The best approach should be: do it in backend, do not return added dependency, if possible.
> 
> If it is intentionally done in frontend, it could be simplified to:
> 
> ```
> <a class="title ..." data-issue-dependency-index="{{.Issue.Index}}">
> ```
> 
> then check whether the element `.item.dependency [data-issue-dependency-index=${index}]` exists in current dropdown items.



> Thank you for your PR but it doesn't look good to me .... there are some nits in code.
> 
> The best approach should be: do it in backend, do not return added dependency, if possible.
> 
> If it is intentionally done in frontend, it could be simplified to:
> 
> ```
> <a class="title ..." data-issue-dependency-index="{{.Issue.Index}}">
> ```
> 
> then check whether the element `.item.dependency [data-issue-dependency-index=${index}]` exists in current dropdown items.

I apologize for handling this directly in the front end, as I'm not well-acquainted with the backend process. May I close this PR for now?

**Comment by wxiaoguang** [comment]
Well ..... no need to apologize, I am just doing regular review for some new PRs and sharing some of my thoughts, that's only a technical suggestion and only represents my personal opinion.

Thank you again for helping to make Gitea better.

**Comment by HEREYUA** [comment]
> Well ..... no need to apologize, I am just doing regular review for some new PRs and sharing some of my thoughts, that's only a technical suggestion and only represents my personal opinion.
> 
> Thank you again for helping to make Gitea better.

It is indeed more reasonable to make modifications on the backend. In addition, thank you for your suggestions on front-end modifications

**Pull request closed without merging**
