### PR TITLE
Improve English translation for Gitea 1.5 features

### PR DESCRIPTION
**Pull request by bugreport0**
I noticed everyone's preparing for the Gitea 1.5 release so I went through all current English strings once more. Great work on the new layout and features, hopefully we can merge these fixes to have a polished user interface in English.

This PR contains mostly spelling, style and grammatical fixes, but I also removed the apparently unused 'issue_number' string for dependencies. I couldn't find it referenced in any code.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@bugreport0 thank you for the PR, please open a new PR with the same changes against the `release/v1.5` branch so it can be included in the 1.5.0 release.

**Comment by techknowlogick** [comment]
@lafriks no backport?

**Comment by lafriks** [comment]
No need to backport as translations will not be updated anyway and here are also strings updated for 1.6.0 features

**Comment by techknowlogick** [comment]
@lafriks that makes sense. thanks for clarification.

**Pull request merged**
