### PR TITLE
Allow user to set an external tracker url and forward to it

### PR DESCRIPTION
**Pull request by DblK**
This is the same as [my PR #3646](https://github.com/gogits/gogs/pull/3646) I suggest on Gogs

### CODE REVIEW

**Review by strk — APPROVED** [review]

**Review by strk — APPROVED** [review]
LGTM

**Comment by strk** [comment]
BTW, a rebase to master would be nice (to reduce the change to a single commit)

**Comment by tboerger** [comment]
@strk you need to write the LGTM as a regular comment, LGTM is not aware of approval comments yet.

Beside a required rebase it LGTM.

**Comment by strk** [comment]
Does it need to be just a single world: `LGTM` or would things like "I would not say LGTM" be taken as an approval ? :)

**Comment by strk** [comment]
Looks like it was interpreted as approval (ok, in this case)

**Pull request merged**
