### PR TITLE
Add bundle download for repository

### PR DESCRIPTION
**Pull request by jolheiser**
This PR adds another download type for repositories, [bundle](https://git-scm.com/book/en/v2/Git-Tools-Bundling).

This currently always bundles using `--all`, since I'd imagine it's almost always more useful to have the entire repo history.

In the future, bundling could be considered for backups since they are standalone repositories, more or less.

One thing that I couldn't seem to shake when writing this, it seems like the bundle file refused to copy correctly unless I closed the file after creation (and subsequently re-opened to allow the `io.Copy`).  
Please let me know if I missed something silly. :slightly_smiling_face:

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by jolheiser** [comment]
This should be ready to test again. 

1. Sorry for the unrelated changes, I'm not sure whether GoLand or gofmt is responsible for the build tags (my guess is the former), but they have been duplicated because the old style has been deprecated in favor of `//go:build`
2. Due to bundles needing to be written to a file (rather than to stdout), I had to re-add code to temporarily store them until they could be piped out to the caller.

**Comment by lunny** [comment]
Since .zip and .tar.gz will only include current branch codes, it's confusing that this will bundle --all. Maybe add two meanu items, one is for current branch another is --all.

**Comment by jolheiser** [comment]
Alright, this now downloads a bundle at the current branch/commit.

After merging, I will follow up with a PR that adds the `--all` bundle to repo settings, as it's more of a complete backup option.

**Review by lunny — APPROVED** [review]

**Pull request merged**
