### PR TITLE
Issue Templates: add option to have dropdown printed list

### PR DESCRIPTION
**Pull request by 6543**
Issue template dropdown can have many entries, and it could be better to have them rendered as list later on if multi-select is enabled.

so this adds an option to the issue template engine to do so.

DOCS: https://gitea.com/gitea/docs/pulls/19

---

## demo:

```yaml
name: Name
title: Title
about: About
labels: ["label1", "label2"]
ref: Ref
body:
  - type: dropdown
    id: id6
    attributes:
      label: Label of dropdown (list)
      description: Description of dropdown
      multiple: true
      list: true
      options:
        - Option 1 of dropdown
        - Option 2 of dropdown
        - Option 3 of dropdown
        - Option 4 of dropdown
        - Option 5 of dropdown
        - Option 6 of dropdown
        - Option 7 of dropdown
        - Option 8 of dropdown
        - Option 9 of dropdown
```

image
image

---
*Sponsored by Kithara Software GmbH*

### CODE REVIEW

**Comment by lunny** [comment]
Please send docs update to https://gitea.com/gitea/docs

**Review by lunny — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Does Github support this?

**Review by KN4CK3R — APPROVED** [review]

**Comment by 6543** [comment]
> Does Github support this?

no, but they should :D

(we already support all features github offers if I'm not mistaken)

**Comment by 6543** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#attributes-for-dropdown looks like we are missing the 'default' option ...

**Pull request merged**
