### PR TITLE
Enforce netgo build tag while cross-compilation (backport #1690)

### PR DESCRIPTION
**Pull request by cez81**
As title

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
make lg-tm work

**Comment by lunny** [comment]
@cez81 could you rebase this? I will merge it.

**Comment by cez81** [comment]
@lunny Done

**Pull request merged**
