### PR TITLE
Extract createComment

### PR DESCRIPTION
**Pull request by lunny**
This PR moved `sendCreateCommentAction` out of createComment

### CODE REVIEW

**Comment by guillep2k** [comment]
@lunny lint still complaining. 😉

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
@guillep2k needs your review.

**Review by guillep2k — APPROVED** [review]
LGTM. The names of the functions are a little weird now, but I understand that's needed for clarifying the nature of the change. 👍

**Comment by 6543** [comment]
:D same thought too

**Comment by lunny** [comment]
@guillep2k @6543 I think so. And finally I will rename them after moved the actions function out of models.

**Pull request merged**
