### PR TITLE
Update gitea-vet to v0.2.1

### PR DESCRIPTION
**Pull request by 6543**
as title

### CODE REVIEW

**Comment by 6543** [comment]
blocked by #11646

**Comment by 6543** [comment]
blocked by  #12286

**Comment by 6543** [comment]
a `for i in $(ls v*.go); do echo "$i:"; echo structs; go list -f '{{join .Deps "\n"}}' $i | grep structs; echo "gitea/models"; go list -f '{{join .Deps "\n"}}' $i | grep "gitea/models"; done` tells me:

there exist still some `code.gitea.io/gitea/modules/structs` dependencys in:
* v70.go
* v71.go
* v72.go
* v76.go
* v79.go
* v82.go
* v83.go
* v85.go
* v96.go
* v99.go
* v112.go
* v115.go
* v127.go
* v128.go
* v130.go
* v134.go
* v136.go
* v139.go
* v140.go

**Comment by mrsdizzie** [comment]
can we ignore old migrations and only apply this rule to newer ones?  it feels very wrong and error-prone to go back and re-write dozens of old migrations that have been working for a while

**Comment by 6543** [comment]
@mrsdizzie at this point this are indirect dependencys

for example on v70: the `setting.Service.DefaultEnableDependencies` value is used.
setting.Service struct as one field (not that one) who is a type decrlared in structs

So my suggestion where: for dependencys: ignores structs and just permit direct imports for structs

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Just ignore the previous is better I think. Maybe we need a white list for these files on vet to do that.

**Comment by 6543** [comment]
@lunny https://gitea.com/gitea/gitea-vet/pulls/9

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Pull request merged**
