### PR TITLE
Implement creating non-bare repositories

### PR DESCRIPTION
**Pull request by gzsombor**
Useful for hosting repositories where local access by scripts is needed.

For this, it is needed a checkbox in the initialization screen - a flag, which disables this totally.
The isBare flag is needed to push down to various places - for example the createUpdateHook assumed that the direct git directory was passed in. In the readme/licence/gitignore generation, with non-bare repository, it is possible to directly manipulate the content.

### CODE REVIEW

**Comment by bkcsoft** [comment]
I can't really find any good usecases for this, could you list some? 🙂

**Comment by gzsombor** [comment]
I'm trying to use gitea as a graphical git client, so my current workflow is to create a git repository on the gui, soft link it to my dev git checkouts, and modify in the database to be 'non-bare'. My other reason is, that I would like write scripts, which could edit/modify the content of the repository - instead of clone/modify/create pull request/push/merge in a separate, remote repo. I can understand neither is too mainstream usecase :)
 Otherwise, it seems, that gitea supports working with non-bare repositories, pretty fine - except installing the git-hooks, and creating the repositories itself, so I thought, why not eliminate this minor hiatus ? :)

**Comment by lunny** [comment]
I think maybe this is_bare option is no need.

**Comment by bkcsoft** [comment]
Closing as dead. Feel free to send another PR if you pick this up again. (This is so people won't wait on something that isn't coming)

**Pull request closed without merging**
