### PR TITLE
Update to work with latest VS Code go debugger

### LINKED ISSUE #18394: Cannot debug gitea in vscodium + default vscode-go 0.30.0 config
### Gitea Version

1.16

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Compilation from source.

### Database

_No response_

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

When you try to compile gitea in vscodium with current vscode-go extension version 0.30.0 using instructions from

https://github.com/go-gitea/gitea/blob/main/contrib/ide/README.md

debug binary will be build in /tmp not in ${workspaceRoot} and page http://127.0.0.1:3000/ will display only

`Unable to find status/500 template`

and debug console will contain errors like

```
2022/01/24 19:02:18 ...ers/common/logger.go:21:1() [I] Started GET / for 127.0.0.1:34106
2022/01/24 19:02:18 ...s/context/context.go:206:HTML() [E] Render failed: html/template: "install" is undefined
2022/01/24 19:02:18 ...s/context/context.go:290:PlainTextBytes() [E] PlainTextBytes: Unable to find status/500 template
2022/01/24 19:02:18 ...ers/common/logger.go:30:1() [I] Completed GET / 500 Internal Server Error in 469.837µs
```
Problem is caused probably by new debugger mode used in vscode-go extension (dlv-dap).

Workaround that seems to work is to turn on legacy mode by adding

```
    "go.delveConfig": {
        "debugAdapter": "legacy",
    }
```

to settings.json.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #18394

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
actually hang a sec I think we need the cwd.

**Comment by zeripath** [comment]
make lgtm work

**Comment by silverwind** [comment]
I'm not a vscode user, but I wonder if this config could be put into a `.vscode` directory in the repo root so it's automatically picked up.

**Comment by lunny** [comment]
> I'm not a vscode user, but I wonder if this config could be put into a `.vscode` directory in the repo root so it's automatically picked up.

It could but different developers may want different settings and launch configurations. So I think it's better to still keep it in `crontrib` directory.

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
