### PR TITLE
Add Commit message to PR

### PR DESCRIPTION
**Pull request by tyroneyeh**
Add commit message variable to pull template for PR in merge

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Good catch. I have tested it, LGTM.

And it has been confirm by  parnic (https://github.com/go-gitea/gitea/issues/20634#issuecomment-1202877581)

**Comment by parnic** [comment]
This change looks good, thanks!

Once this is fixed, the approvers still don't get listed like they used to, so that will need a separate change. The template looks like it's trying to generate that list, but it's not coming through for some reason.

image

**Review by techknowlogick — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Sorry for bothering. After some more thoughts, I think as a bug fix, it's better to keep the same behavior as 1.16.

In 1.16, only the squash merge has the commit messages.

https://github.com/go-gitea/gitea/blob/release/v1.16/templates/repo/issue/view_content/pull.tmpl#L407

So I made a new change to this PR: `'mergeMessageFieldText': {{.GetCommitMessages}} + defaultMergeMessage,` for `'name': 'squash',`.

**Comment by wxiaoguang** [comment]
bot

**Pull request merged**
