### PR TITLE
Fix some webhooks bugs

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by lunny** [comment]
~block by https://github.com/go-gitea/go-sdk/pull/107~

**Comment by appleboy** [comment]
@lunny update vendor. Done

**Comment by lunny** [comment]
@appleboy Thanks!

**Comment by lunny** [comment]
fix #3579, #3492

**Comment by lunny** [comment]
fix #895

**Comment by lafriks** [comment]
@lunny plaese fix fmt error

**Comment by lunny** [comment]
@lafriks done.

**Review by lafriks — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
