### PR TITLE
Actions are no longer experimental, so enable them by default

### PR DESCRIPTION
**Pull request by lunny**
This PR makes the actions enabled by default, so people will find it easier to enable actions in repository setting.

### CODE REVIEW

**Comment by JakobDev** [comment]
I'm not sure if this should be enabled by default. You still need a runner, so this will be not working by default.

**Comment by lunny** [comment]
> I'm not sure if this should be enabled by default. You still need a runner, so this will be not working by default.

Yes, but this change will reduce people asking why they cannot get the actions feature.

**Review by denyskon — APPROVED** [review]

**Comment by techknowlogick** [comment]
Should we add it as a default unit to repo_units too?

**Comment by jolheiser** [comment]
I'm also not convinced it should be enabled by default, considering it takes additional setup to get it working.  
What about instead adding it to the install page? It's getting a little big, but overall I think that might make more sense.

**Comment by techknowlogick** [comment]
> I think it may instead increase the amount of "why aren't actions working" questions if they are enabled but have no runners by default.

In that case we could add a warning to repo owners with actions pending that they need to add runners?

**Comment by jolheiser** [comment]
> > I think it may instead increase the amount of "why aren't actions working" questions if they are enabled but have no runners by default.
> 
> In that case we could add a warning to repo owners with actions pending that they need to add runners?

I think that may be a worthwhile change in itself, but it seems like of the two main install types:
1. Users who use the install page, a checkbox for enabling actions along with a link to "how to set up runners" may be a good solution, or 
2. Users who deploy with a ready config should likely be reading and understanding the configuration for actions/runners. Anyone in this category would also already have them enabled and so unaffected by this PR, but anyone who doesn't have them enabled will likely want to review before it is turned on for them.

It just seems like flipping the toggle from `false` to `true` doesn't improve the situation as a default, it just moves the work elsewhere.

As another alternative, a db-setting may work fine here as well, so it becomes easier to just go flip the switch when the admin is ready.

**Review by delvh — APPROVED** [review]

**Review by delvh — DISMISSED** [review]
Please also update the config cheat sheet and the example config.

**Comment by silverwind** [comment]
And update app.example. ini as usual.

I guess I don't mind it enabled by default if it does nothing. What we should eventually do is enable it automatically in a repo as soon as any workflow files are detected in the repo and at least 1 worker is registered. This will eventually require that we also enable it by default per-repo.

**Comment by lunny** [comment]
> Should we add it as a default unit to repo_units too?

I think that may have a bigger impact for users which can be leave to other PRs. This PR will not affect anything, the actions tab will not be enabled except they enable it in repository setting.

**Comment by lunny** [comment]
> I'm also not convinced it should be enabled by default, considering it takes additional setup to get it working. What about instead adding it to the install page? It's getting a little big, but overall I think that might make more sense.
> 
> > Yes, but this change will reduce people asking why they cannot get the actions feature.
> 
> I think it may instead increase the amount of "why aren't actions working" questions if they are enabled but have no runners by default.

This global configuration will not enable repository actions by default. In fact, after this PR, every repository still needs to enable actions in the setting.

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
