### PR TITLE
Remove row clicking from notification table

### LINKED ISSUE #22692: Cannot right or middle click notification background to follow the link
### Description

The notification area has both a text link and a background "box" that, when **left clicked**, both take you to the same location.
However **right** or **middle** clicking this box does not open a new tab or give you a context menu to open in a new tab like you get if you were to right or middle click the text.

### Screenshots

Right clicking the text:
image

Right clicking the box:
image

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux Mint 21

### Browser Version

Firefox 107.0.1

### PR DESCRIPTION
**Pull request by jolheiser**
Resolves #22692

I don't think there's a need for this entire row to be clickable (and even different links depending on which segment you click)
The links still point to the same spot, so no information is lost here.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by Daeraxa** [comment]
I would vote against this as it removes desired behaviour as far as I'm concerned. Not only is row clicking pretty standard UI practice but this is already the behaviour and the reported issue is about missing functionality on top of this. I don't really see justification to having to be pinpoint accurate when looking through a notification list.

**Comment by jolheiser** [comment]
The alternative, then, would be to make the `a` take up all of the space, which may require some more tweaking with CSS. 

I am fine if that's the consensus, but will need to fiddle around with it. Fomantic tables seem to want to generate padding, so it won't be quite as easy as just making the `a` take up given space.

**Comment by Daeraxa** [comment]
The other thought I had is wouldn't this negatively affect the touch/mobile interface as well?

**Comment by jolheiser** [comment]
> The other thought I had is wouldn't this negatively affect the touch/mobile interface as well?

If anything imo it would be better, less chance to misclick, as these table rows actually have different links depending on where in the segment you click.

**Comment by Daeraxa** [comment]
That's a good point, I hadn't noticed that bit. I'm not saying its something that would necessarily need to be adhered to (as GH is far from perfect on the UI front) is that the row click for the GH notifications only seems to stretch as far as it needs to then cuts off.

**Comment by zeripath** [comment]
So I recall making the whole row clickable deliberately to keep things the same as on GH which also did the same thing at that point. Making the `<a>` take up the whole space seemed to be too difficult.

Now you can still right/middle click on the link bit...

**Comment by wxiaoguang** [comment]
Interesting.

See #17388 , IMO the `click` behavior on the `td` was by purpose before.

If it's not, the JS should be removed together.

**Comment by jolheiser** [comment]
This is a far cry from making it full-height, but I could not find a "good" way to make it full-height without some very hacky CSS. (admittedly I am not a UI expert by any means)

What GitHub does, and what I suspect we should eventually do (if fomantic lets us), is instead of a table they use a list and cleverly styled divs to render the "table" which allows the anchor tag to encompass the content.

---

I am fine with taking pointers on clever CSS to make this work, accepting this PR as-is, or closing it as "the other way was good enough"

Screenshot from 2023-01-31 22-09-42

**Comment by wxiaoguang** [comment]
It will be hacky to make a full height `<a>`, it needs to remove the `td` padding and do other works. IMO it's not worth to make it that complex.

The `width: 100%` should be good enough. And maybe the dead JS code could be removed (if it is only used here) to save browser's CPU time slightly.

**Comment by wxiaoguang** [comment]
Hmm ... since the `HTMLURL` is touched, this PR will have conflicts with https://github.com/go-gitea/gitea/pull/21986/files#diff-40b7988fcd35c50d12157e06dc96b586404a4d1d3772a4b257340f11295bec5a 

I never understand why people like keeping refactor PRs stale and keeping resolving conflicts.

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by wxiaoguang** [comment]
Maybe the JS code should also be removed together. Since there won't be `<td data-href` anymore, the JS code becomes dead code.

https://github.com/go-gitea/gitea/blob/e7ef94e00f1319e5fb876f47fee28728bd671f07/web_src/js/features/common-global.js#L124-L137

**Comment by wxiaoguang** [comment]
Is this PR active? I am working on some JS clean-up work, and I could help to propose a sub PR for this PR (to clean the unused JS code).

**Comment by jolheiser** [comment]
> Is this PR active? I am working on some JS clean-up work, and I could help to propose a sub PR for this PR (to clean the unused JS code).

That would be great!

**Comment by wxiaoguang** [comment]
PR: https://github.com/jolheiser/gitea/pull/3

Although it looks like changing a lot, actually only the last commit is related. Other commits are all from "main" branch, because I have to merge the PR's branch with main first, to resolve conflicts.

**Comment by jolheiser** [comment]
@wxiaoguang looks like I messed something up in my merge, so I reconciled the updating my branch and then cherry-picked your `fix` commit. Would you mind taking a look to make sure I pulled it correctly and resolved the merge the same as you?

**Comment by wxiaoguang** [comment]
Nvm. I guess you did a squash merge? IMO a "fast foward" or a normal merge won't cause these messes 😁 

I think it looks good to me, thank you very much.

**Comment by jolheiser** [comment]
> Nvm. I guess you did a squash merge? IMO a "fast foward" or a normal merge won't cause these messes 😁

Yep, I used the default without considering it 😓 

Thanks for the review!

**Review by silverwind — APPROVED** [review]
This does also fix the padding issue on empty list. I think generally this list should be reworked to no longer be a `<table>`, but that can be done later.

**Pull request merged**
