### PR TITLE
Use the headline comment of pull-request as the squash commit's message

### LINKED ISSUE #12365: Duplicate headlines in commit message after pull merge
- Gitea version (or commit ref):
1.13.0+dev-258-g8f489131f

- Git version:
2.26.2

- Operating system:
x86_64 GNU/Linux synology_avoton_1817+

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
image

As you can see, the headline `Upgrade mtd-utils to 2.1.2 for UBIFS authentication` is repeated.  
It's okay to remove it manually. But the UX would be nicer if no such step is required.
...

### PR DESCRIPTION
**Pull request by typeless**
Originally, it was filled by the commit messages of the involved
commits. In this change, we use the headline comment of the pull
request as the commit message when it is a squash merge.

Thanks to @zeripath for suggesting the idea.

Fixes #12365

### CODE REVIEW

**Comment by typeless** [comment]
This is not quite correct yet. Because the texts provided by `GetCommitMessagtes` include the `Co-authored` lines which are still wanted.

**Comment by lafriks** [comment]
I'm ok of having first commit skipped but imho other commits could still be relevant...

**Comment by typeless** [comment]
@lafriks What the pr does is not about skipping the first commit, but rather using the PR's title and text as the squashed commit's message as https://github.com/go-gitea/gitea/issues/12365#issuecomment-666149532 describes.

**Comment by lafriks** [comment]
@typeless yes I know that... but this way it loses information from other commits that could contain needed information...

**Comment by typeless** [comment]
@lafriks After some contemplation, I think the circumstances that a user would want to keep the titles of the individual commits, while choosing to do squash merges at the same time, should be relatively rare than otherwise.  Of course, I can be wrong.

**Comment by zeripath** [comment]
I think @typeless is correct here - realistically if you're performing a squash commit the issue description is far more likely to be a better description of the PR commit message than the commit messages of all the squashed commits. 

I guess what we need is some sort of template reading thing.

**Comment by ZhouJiaZhi** [comment]
@typeless 
Please post the picture, I want to see the effect of the current square merge
I suggest that gitea's square merge is exactly the same as github's square merge, because most people should use github first,so it would be better to be consistent with github

**Comment by typeless** [comment]
@ZhouJiaZhi 
I am using a patched Gitea that has this PR applied, so if you want to see how the vanilla version works, you should probably look at https://try.gitea.io/.

圖片

**Comment by ZhouJiaZhi** [comment]
@typeless 
This looks much better than before. Is the following information automatically generated? Will this information be recorded in the commit message after square merge? I remember that the square merge in github will only keep the title information in the commit message
截屏2020-12-09 12 56 34

**Comment by typeless** [comment]
@ZhouJiaZhi 
>. Is the following information automatically generated? 
No, it is copied from the PR description.
Although it can be made more clever to automatically fill the description by default when the PR has only a single commit.

> Will this information be recorded in the commit message after square merge? 
All commit messages will be discarded.

**Comment by typeless** [comment]
@6543 I accidentally press the "request review" button. :/  No worries.

**Comment by ZhouJiaZhi** [comment]
@typeless 
Good job, but it seems your code has conflicts
截屏2020-12-09 21 54 44

**Comment by typeless** [comment]
I want to test the change with the latest master. But it doesn't seem to work at the moment.
I got stuck in clicking the "New Pull Request" green button as It didn't respond at all. 


圖片

**Review by 6543 — APPROVED** [review]

**Comment by ZhouJiaZhi** [comment]
Can anyone help approve this PR

**Review by lunny — APPROVED** [review]

**Comment by lafriks** [comment]
Tests fail

**Comment by 6543** [comment]
merge conflict relicts?

**Comment by typeless** [comment]
````
--- FAIL: TestAPIGitTags (0.20s)
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /user/settings/applications for 
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed GET /user/settings/applications 0  in 4.738624ms
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started POST /user/settings/applications for 
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed POST /user/settings/applications 0  in 20.162784ms
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /user/settings/applications for 
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed GET /user/settings/applications 0  in 4.595815ms
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /api/v1/repos/user2/repo1/git/tags/3431c83e7aa091f921788022dc7a8573fcf8e431?token=385fbbcdbeb5ecdf8e8a1bfd434dbcdb81d31089 for 
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed GET /api/v1/repos/user2/repo1/git/tags/3431c83e7aa091f921788022dc7a8573fcf8e431?token=385fbbcdbeb5ecdf8e8a1bfd434dbcdb81d31089 0  in 34.457315ms
    api_repo_git_tags_test.go:54: 
        	Error Trace:	api_repo_git_tags_test.go:54
        	Error:      	Not equal: 
        	            	expected: "user2"
        	            	actual  : "drone"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-user2
        	            	+drone
        	Test:       	TestAPIGitTags
    api_repo_git_tags_test.go:55: 
        	Error Trace:	api_repo_git_tags_test.go:55
        	Error:      	Not equal: 
        	            	expected: "user2@example.com"
        	            	actual  : "noreply@drone"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-user2@example.com
        	            	+noreply@drone
        	Test:       	TestAPIGitTags
    testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /api/v1/repos/user2/repo1/git/tags/65f1bf27bc3bf70f64657658635e66094edbcb4d?token=385fbbcdbeb5ecdf8e8a1bfd434dbcdb81d31089 for 
````
Hmmm, that's confusing.

**Comment by lunny** [comment]
> ```
> --- FAIL: TestAPIGitTags (0.20s)
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /user/settings/applications for 
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed GET /user/settings/applications 0  in 4.738624ms
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started POST /user/settings/applications for 
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed POST /user/settings/applications 0  in 20.162784ms
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /user/settings/applications for 
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed GET /user/settings/applications 0  in 4.595815ms
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /api/v1/repos/user2/repo1/git/tags/3431c83e7aa091f921788022dc7a8573fcf8e431?token=385fbbcdbeb5ecdf8e8a1bfd434dbcdb81d31089 for 
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:95:1() [I] Completed GET /api/v1/repos/user2/repo1/git/tags/3431c83e7aa091f921788022dc7a8573fcf8e431?token=385fbbcdbeb5ecdf8e8a1bfd434dbcdb81d31089 0  in 34.457315ms
>     api_repo_git_tags_test.go:54: 
>         	Error Trace:	api_repo_git_tags_test.go:54
>         	Error:      	Not equal: 
>         	            	expected: "user2"
>         	            	actual  : "drone"
>         	            	
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -1 +1 @@
>         	            	-user2
>         	            	+drone
>         	Test:       	TestAPIGitTags
>     api_repo_git_tags_test.go:55: 
>         	Error Trace:	api_repo_git_tags_test.go:55
>         	Error:      	Not equal: 
>         	            	expected: "user2@example.com"
>         	            	actual  : "noreply@drone"
>         	            	
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -1 +1 @@
>         	            	-user2@example.com
>         	            	+noreply@drone
>         	Test:       	TestAPIGitTags
>     testlogger.go:78: 2020/12/19 10:18:32 ...outers/routes/chi.go:88:1() [I] Started GET /api/v1/repos/user2/repo1/git/tags/65f1bf27bc3bf70f64657658635e66094edbcb4d?token=385fbbcdbeb5ecdf8e8a1bfd434dbcdb81d31089 for 
> ```
> 
> Hmmm, that's confusing.

It's a drone configuration problem. I have update the PR.

**Comment by 6543** [comment]
:rocket:

**Comment by ZhouJiaZhi** [comment]
Great, I wait it for a long time, When will this commit be published to docker?

**Comment by 6543** [comment]
it is already on :latest i think @ZhouJiaZhi

**Pull request merged**
