### PR TITLE
Remove unit types commits and settings

### PR DESCRIPTION
**Pull request by lafriks**
* Remove unit type commits & settings as they were not working correctly anyway
* Fix unit type checking as all unit types was always already set before loading user allowed unit types
* Fix style so that when "Settings" tab is not visible would still be aligned more to left not in all width with lot of space in between tabs.
* Fix RepoView3 test (user3 is organization and can not be used to log in)
* Fix invalid unit test (user4 is in team1 so it must have access to repo3, changed test to user5)
* Allow changing units only for teams with read or write access mode

### CODE REVIEW

**Comment by lafriks** [comment]
Code is ready for review

**Comment by lafriks** [comment]
FYI tests started to fail after I fixed units functionality thats why I fixed them in this PR

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Pull request merged**
