### PR TITLE
models/webhook.go linting

### PR DESCRIPTION
**Pull request by strk**
still incomplete

### CODE REVIEW

**Comment by strk** [comment]
This is ready for merge, please review.

**Comment by andreynering** [comment]
This is not building:

```
# code.gitea.io/gitea/models
models/webhook.go:395: t.SimpleMarshalJSON undefined (type *HookTask has no field or method SimpleMarshalJSON, but does have simpleMarshalJSON)
models/webhook.go:398: t.SimpleMarshalJSON undefined (type *HookTask has no field or method SimpleMarshalJSON, but does have simpleMarshalJSON)
```

**Comment by lunny** [comment]
^

**Comment by strk** [comment]
Build should be fixed now, sorry for the noise

**Comment by lunny** [comment]
LGTM

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by lunny** [comment]
resolved #70

**Pull request merged**
