### PR TITLE
Fixes indexed repos keeping outdated indexes when files grow too large

### PR DESCRIPTION
**Pull request by guillep2k**
> @guillep2k I agree that change would fix it. Why don't you add another quick PR for that?
> 
> _Originally posted by @zeripath in https://github.com/go-gitea/gitea/pull/7711#issuecomment-517500634_

For indexed repos, when a commited file grows larger than [indexer] MAX_FILE_SIZE, its index is no longer updated, but remain "frozen" and produce outdated results. Chaining the action with addDelete() should remove any lingering indexes the file might have.

This code will not fix indexes already outdated (not until a new commit is performed on it).

### CODE REVIEW

**Comment by guillep2k** [comment]
Sorry, this PR doesn't fix the issue. Don't merge it yet.

**Comment by guillep2k** [comment]
OK, it turns out the problem I spotted was not this fix but the one that lead to #7718. The fix is OK, I've tested it properly now. Sorry for the confusion.

**Comment by zeripath** [comment]
So this is no longer WIP?

**Comment by guillep2k** [comment]
> 
> 
> So this is no longer WIP?

No, it's good to go, now.

**Review by zeripath — APPROVED** [review]
I going to assume that asking the index to delete a file it doesn't have is tolerated.

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
> 
> 
> I going to assume that asking the index to delete a file it doesn't have is tolerated.

@zeripath Yes, I've tested with a MAX_FILE_SIZE of 100,000:
* File A of 50,000 bytes: indexed correctly.
* Add 40,000 bytes to A: changes still indexed correctly.
* Add other 40,000 bytes to A: result from A don't show in the index anymore (as expected).
* Edit A and make it below 100,000 bytes: results from A show up again.
* Add new file B of 200,000 bytes: doesn't show in search, doesn't crash Gitea, index looks fine for the other files.

**Comment by lafriks** [comment]
I think this should be backported to 1.9

**Pull request merged**
