### PR TITLE
Fix redirect when using lowercase repo name

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
Fixes ##18774.

### CODE REVIEW

**Comment by silverwind** [comment]
It feels like the wrong fix, especially `setting.AppSubURL` may contain significant case and that is eliminated here, which can be bad. Not sure I fully understand the issue but it would be better to accept both case variants in the router instead.

**Review by zeripath — APPROVED** [review]

**Comment by AbdulrhmnGhanem** [comment]
> It feels like the wrong fix, especially `setting.AppSubURL`

You are right about this one. Changed it to
```go
prefix := strings.TrimPrefix(setting.AppSubURL+strings.ToLower(strings.TrimSuffix(ctx.Req.URL.Path, ctx.Params("*"))), strings.ToLower(ctx.Repo.RepoLink))

```

> it would be better to accept both case variants in the router instead.

The bug in the `RepoRefLegacy` handling, other `RepoRefTypes` are handled right **and not in the router**, for consistency, I don't think this should be handled in the router.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
@AbdulrhmnGhanem Could you rebase and then we can merge this PR.

**Comment by fnetX** [comment]
We just hit this bug at Codeberg. Should I send a backport? Was this forgotten?

**Comment by Gusted** [comment]
> Was this forgotten?

This was marked as enhancement(not sure why), we only backport PR's marked as bug fixes. Feel free tl backport.

**Comment by fnetX** [comment]
Well it got the backport label, so it appeared to me as intended for backporting.

**Pull request merged**
