### PR TITLE
Add Location, Website and Description to API

### LINKED ISSUE #14248: Location, Website and Biography not readable with API
- Gitea version (or commit ref):  1.13.0 
- Git version: 
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

The User-Model provided by the API doesn't contains fields for "Location", "Biography" and "Website". This Values can only set via API by admin.

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #14248

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
I think we need to consider this slightly more carefully. I don't think we need to always return this data.

**Comment by 6543** [comment]
well it's public on your profile page & optional so I think there is no issue

**Review by zeripath — APPROVED** [review]
Still doesn't appear that these can be easily set by the API though

**Comment by 6543** [comment]
@KN4CK3R would you mind to extend user edit api or do you like to put this into a new pull?

**Comment by KN4CK3R** [comment]
I will change the edit api too.

**Pull request merged**
