### PR TITLE
Fix pull merge 500 error caused by git-fetch breaking behaviors

### LINKED ISSUE #8133: 500 Internal server error when trying to merge a pull request
- Gitea version: 19.3
- Git version: 1.8.3.1
- Operating system: RHEL 7.6
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
When trying to automatically merge a pull request, the following error occurs

```
2019/09/09 13:02:07 routers/repo/pull.go:629:MergePullRequest() [E] Merge: getDiffTree: git diff-tree [/opt/gitea/data/tmp/local-repo/merge-11476913.git base:master head:head_repo/remove_readme]: fatal: bad revision 'head_repo/remove_readme'
```

_Originally posted by @rmbleeker in https://github.com/go-gitea/gitea/issues/8029#issuecomment-529423708_

### PR DESCRIPTION
**Pull request by typeless**
Fixes #8133 

The git version before 1.8.4 would not update remote refs automatically.
That causes the following git-diff-tree command to get 'bad revision' errors.
Use refspec for git-fetch explicitly to avoid the problem.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
Why is this `kind/enhancement`?

**Comment by lunny** [comment]
@guillep2k This PR lets gitea support older git version, I don't think it's a bug since a git >= 1.9 should work.

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k This PR lets gitea support older git version, I don't think it's a bug since a git >= 1.9 should work.

Fair enough. But then what is the minimum supported `git` version?

**Comment by lunny** [comment]
It seems it's
```
	// GitVersionRequired is the minimum Git version required
	GitVersionRequired = "1.7.2"
```
OK. Let's label it as a bug.

**Comment by lunny** [comment]
@typeless Could you give the link about the fetch command syntax on older git?

**Comment by guillep2k** [comment]
@lunny I've found this:

> * "git fetch origin master" unlike "git fetch origin" or "git fetch"
   did not update "refs/remotes/origin/master"; this was an early
   design decision to keep the update of remote tracking branches
   predictable, but in practice it turns out that people find it more
   convenient to opportunistically update them whenever we have a
   chance, and we have been updating them when we run "git push" which
   already breaks the original "predictability" anyway.

From: https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.4.txt

I'm not sure if this is what @typeless is talking about.

**Comment by typeless** [comment]
@lunny @guillep2k Yes, that is it. https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.4.txt#L226-L232

**Review by guillep2k — APPROVED** [review]

**Pull request merged**
