### PR TITLE
Fix missing cors handler in `/api/healthz`

### LINKED ISSUE #22718: CORS headers not present on /api/healthz
### Description

I have a [homer](https://github.com/bastienwirtz/homer) dashboard on another subdomain to check the health status of my self hosted services, and have found that with correct settings in my `app.ini`:
```ini
[cors]
ENABLED = true
ALLOW_DOMAIN = *
SCHEME = http
ALLOW_CREDENTIALS = true
```
the endpoint `/api/v1/version` respond with the correct CORS headers, while `/api/healthz` does not. The endpoints are requested without user authentication, so I have only checked these.

This behavior is reproduced at https://gitea.com, but https://try.gitea.io does not respond with CORS headers at all. Not sure if they have the CORS config set.

For reference, here is the relevant part of my homer config:
```yaml
services:
  ...
  - name: "Gitea"
    icon: "fab fa-git-alt"
    url: "https://gitea.com"
    target: "_blank"
    type: Ping
    method: GET
    endpoint: "https://gitea.com/api/healthz"
    # endpoint: "https://gitea.com/api/v1/version"
```

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Ubuntu Server 22.04

### How are you running Gitea?

official binary from https://dl.gitea.io, as service with systemd

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by yardenshoham**
Added the CORS middleware to the `/api/healthz` route

Fix #22718

### CODE REVIEW

**Comment by yardenshoham** [comment]
Should I change the following line as well?
https://github.com/go-gitea/gitea/blob/1e0e79dcbfb21971ac4cd591585672517117d4f0/routers/install/routes.go#L112

If so, how can I reuse the `CorsHandler` defined in `web.go`?
https://github.com/go-gitea/gitea/blob/1e0e79dcbfb21971ac4cd591585672517117d4f0/routers/web/web.go#L62

**Comment by zeripath** [comment]
but does this need CORS?

**Comment by yardenshoham** [comment]
If CORS is enabled in `app.ini`, no?

**Comment by zeripath** [comment]
But it's not an actual useful endpoint for getting data - it's just for ensuring that the server is up. I don't understand why this would need CORS protection.

**Comment by yardenshoham** [comment]
So you don't consider #22718 a bug. If so, feel free to close

**Comment by delvh** [comment]
Yes, I don't consider it a bug either.
I've already been confused why someone would want to spend the time in the first place to open the issue.

CORS specifies where resources might be loaded from.
I don't even know why API requests should receive CORS headers at all.
They only return JSON, so there's nothing to load from somewhere else?
Or am I missing something fundamental?

**Comment by a1012112796** [comment]
I think it's better to move this router to `routers/api` directly.

**Comment by wxiaoguang** [comment]
> I think it's better to move this router to `routers/api/...` directly.

No. The `healthz` is a de-facto standard endpoint. There is nothing with Gitea's versioned API `/api/v1/xxx`.

**Comment by yardenshoham** [comment]
Gotcha, I'll close this then

**Pull request closed without merging**
