### PR TITLE
Fix wording

### PR DESCRIPTION
**Pull request by pgaskin**
For a key which never expires, it used to say `Valid until never`. It should be `forever`.

### CODE REVIEW

**Comment by lunny** [comment]
Maybe we should change the key and there are any other places to use this word?

**Comment by pgaskin** [comment]
@lunny No, there are not any other places using this word. If you want, I can change the key.

**Comment by lafriks** [comment]
I think the key should be changed

**Comment by pgaskin** [comment]
Done. I have added a new key `settings.valid_forever` and removed `settings.never`. 

The failed build is not because of this. 

Proof: https://staging.geek1011.net/user/login?redirect_to=%2fuser%2fsettings%2fkeys
screenshot from 2017-06-23 17-56-17

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Pull request merged**
