### PR TITLE
Fix loading content history on show more

### LINKED ISSUE #17767: Code comment history not shown on lazily loaded diffs
### Gitea Version

1.16.0+dev-581-gbaed01f24

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

try.gitea.io

### Database

_No response_

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

The comment edit history dropdowns are only initialized once when the page loads.
If additional diffs are loaded afterwards (via "Show More" or "Load Diff"), their code comments don't have the edit history. 

Example:
* https://try.gitea.io/jpraet-org/test-repo/pulls/1/files -> "Show More" -> you'll see the edited comment on file 99 has the edit history dropdown, while the edited comment on file 105 does not
* https://try.gitea.io/jpraet-org/test-repo/pulls/2/files -> "Load Diff" -> the edited comment does not have the dropdown

### Screenshots

ok:
image

not ok:
image

### PR DESCRIPTION
**Pull request by Gusted**
- Call `initRepoIssueContentHistory` so that the newly loaded comments also get their content history.
- Resolves #17767

### CODE REVIEW

**Comment by silverwind** [comment]
Kind of unrelated but I don't like it that `initRepoIssueContentHistory` does an unconditional fetch request. I feel like this is something that could have been rendered directly into the HTML instead.

**Comment by wxiaoguang** [comment]
I think we should prevent `init` something again and again. `init` usually means a one-time work.

As silverwind suggested, we may try to attach some event listeners to parent DOM node.

Or, we can use a re-call safe function, eg: `attachXxx`, like the existing `attachTribute`, then developers are clear that it can be called on demand.

**Review by silverwind — APPROVED** [review]
I guess it's a good short-term fix.

**Comment by jpraet** [comment]
Note that the ticket #17767 also mentions the scenario where a diff of a file is initially hidden because it is too large.
When you click "Load Diff", the comment edit history is missing too. I think this PR currently only handles the "Show More" scenario.

**Review by wxiaoguang — APPROVED** [review]

**Comment by zeripath** [comment]
So we'd need to add:

```patch
diff --git a/web_src/js/features/repo-diff.js b/web_src/js/features/repo-diff.js
index 5f231b6c8..f8f6c38b7 100644
--- a/web_src/js/features/repo-diff.js
+++ b/web_src/js/features/repo-diff.js
@@ -127,6 +127,7 @@ export function initRepoDiffShowMore() {
       }
 
       $target.parent().replaceWith($(resp).find('#diff-file-boxes .diff-file-body .file-body').children());
+      initRepoIssueContentHistory();
     }).fail(() => {
       $target.removeClass('disabled');
     });

```

if we wanted to catch the show diff too.

I think however, we should consider if we want to load the history like this - would it be better to have it be dynamically loaded when the user requests to see the history?

**Comment by Gusted** [comment]
> I think however, we should consider if we want to load the history like this - would it be better to have it be dynamically loaded when the user requests to see the history?

I think it's best if we add a attribute to a comment if it has history, and the front-end would request the history on demand. Any objections?

**Comment by zeripath** [comment]
No objections from me. This would simplify a lot of things and reduce the risk of serious problems with heavily edited issues and PRs.

**Comment by wxiaoguang** [comment]
> > I think however, we should consider if we want to load the history like this - would it be better to have it be dynamically loaded when the user requests to see the history?
> 
> I think it's best if we add a attribute to a comment if it has history, and the front-end would request the history on demand. Any objections?

I  think it can be done totally in frontend, then we do not need to change backend code  (no more dependencies or coupling)

1. `initRepoIssueContentHistory()` => `attachRepoIssueContentHistory(targetCommentId=null)`
2. `GET /content-history/overview` => `POST /content-history/overview` with `{commentIdList:  [...] }`, only query the overview information for `commentIdList`
3. If targetCommentId==null, attachRepoIssueContentHistory would collect all history-menu-not-attached comment IDs, and send to backend to query overview.
4. Then re-calling `attachRepoIssueContentHistory(null)` won't send redundant requests (Improvement)
5. If a content is edited, we can  call `attachRepoIssueContentHistory(commentId)` to do a refresh (Improvement)

**Pull request merged**
