### PR TITLE
Update xorm and dependencies vendor for feature to dump to other database

### PR DESCRIPTION
**Pull request by lunny**
This PR adds an optional parameter `-d=xxx` to `Gitea dump` so that we can dump the database from original database to another. `xxx` could be `sqlite3`, `mysql`, `postgres`, `mssql` or any third-party xorm dialect. For finish this feature, I have to update `xorm` to the latest version.

### CODE REVIEW

**Comment by appleboy** [comment]
Drone fail.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by lunny** [comment]
Need update `gitea dump` docs

**Comment by bkcsoft** [comment]
@lunny What is the difference between `DumpAllToFile` and `DumpTablesToFile` ?

**Comment by lunny** [comment]
Currently `DumpAllToFile` cannot convert between different databases, but `DumpTablesToFile` could. `DumpTablesToFile` ask you give the tables' struct model, but `DumpAllToFile` will retrieve the models itself. So I maybe need dynamic create structs on `DumpAllToFile` after some time later.

**Pull request merged**
