### PR TITLE
Fix comment for EmailNotificationsAndYourOwn constant

### PR DESCRIPTION
**Pull request by Infinoid**
This fixes some copypasta in the constant definitions for the `User.EmailNotificationsPreference` field.  No code changes.

---
The `EmailNotificationsAndYourOwn` value is described as if it were the `EmailNotificationsEnabled` value, above.

I noticed this while reading through the code to figure out some details of how email notifications work.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
Thanks for catching this :)

**Review by yardenshoham — APPROVED** [review]

**Comment by Infinoid** [comment]
Wuh?  I'm confused by the behavior of @GiteaBot.

**Comment by yardenshoham** [comment]
Sorry, we recently changed it to trigger too often. I let @techknowlogick know

**Comment by yardenshoham** [comment]
After https://github.com/GiteaBot/gitea-backporter/pull/41 lands we can add `reviewed/wait-merge` agains

**Comment by techknowlogick** [comment]
That PR is now merged, and hopefully, the bot won't spam updates anymore. apologies for the extra notifications.

**Pull request merged**
