### PR TITLE
Fix ordering in app.ini and fix run mode option

### PR DESCRIPTION
**Pull request by Morlinest**
Move `APP_MODE` to root section in app.ini (where it should be: https://github.com/go-gitea/gitea/blob/5866eb23217de4d29b181e30c26cee28ebc6aedc/modules/setting/setting.go#L652) and remove unused `APP_MODE` option.

### CODE REVIEW

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
LGTM

**Comment by lunny** [comment]
@Morlinest it's `RUN_MODE` not `APP_MODE`
```ini
; Either "dev", "prod" or "test", default is "dev"
RUN_MODE = dev
```

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work

**Pull request merged**
