### PR TITLE
Move editorconfig-checker to lint-backend and remove JS wrapper

### PR DESCRIPTION
**Pull request by silverwind**
It makes more sense there as templates are considered backend code.

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm this isn't so easy because the command depends on node and npx presence which isn't there in some docker images used on the CI. I guess we should probably just keep it in `lint-frontend` as I want to avoid installing node in those images.

**Comment by silverwind** [comment]
The `editorconfig-checker` tool itself is golang (https://github.com/editorconfig-checker/editorconfig-checker), so it might be possible to use it directly via `go install` instead of the `npx` wrapper.

**Comment by silverwind** [comment]
`go install` method seems to work, added it to their README in https://github.com/editorconfig-checker/editorconfig-checker/pull/195.

**Comment by silverwind** [comment]
Ready for review. Now this directly uses the golang tool, eliminating the JS wrapper and a bunch of indirect npm dependencies as well.

**Review by Gusted — APPROVED** [review]
This should also be added to the test environment: https://gitea.com/gitea/test-env just like golangci-lint

**Review by KN4CK3R — APPROVED** [review]

**Pull request merged**
