### PR TITLE
Re-disign repository's header

### LINKED ISSUE #184: Better repository header
I proposa a new repository header. There are three lines for every repository page:

1. [Logo]   Dashboard    Explore    Help              username    +     admin      settings      signout

2. [public or private icon]    [repo name]                                    watch    star    fork      download

3. [repo description]                                                                      ssh | https [git url] copy button

@makhov @fuxiaohei @tboerger

### PR DESCRIPTION
**Pull request by lunny**
This pr redisign the repository's header UI. And that will resolved #184 #200. Maybe it is not the best way, but it's a beginning of UI improvements.

### CODE REVIEW

**Comment by lunny** [comment]
@tboerger @makhov @fuxiaohei , please review it.

**Comment by tboerger** [comment]
screenshot

I think this is a good start :)

**Comment by tboerger** [comment]
Travis fails with ```routers/api/v1/user.go:22: unknown gogs.User field 'Id' in struct literal```

**Comment by lunny** [comment]
It's ok now. I have fork gogits/gogs-go-client to go-gitea/go-sdk. @tboerger

**Comment by tboerger** [comment]
:+1:

**Pull request merged**
