### PR TITLE
Split migrations folder

### PR DESCRIPTION
**Pull request by lunny**
There are too many files in `models/migrations` folder so that I split them into sub folders.

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]

**Comment by KN4CK3R** [comment]
A small problem may be a version change from x to y because existing PRs with migrations still have their code in x but it should be in y now.

**Comment by lunny** [comment]
> A small problem may be a version change from x to y because existing PRs with migrations still have their code in x but it should be in y now.

In fact, whatever the migration file is in any folder, it will work if migrations's sequence is right even if you put it in migrations folder directly. The folder just for we know which version the migration file should be in.

**Comment by KN4CK3R** [comment]
Sure, it's no functional problem but there may be migrations which get merged into the wrong folder.

**Comment by lunny** [comment]
> Sure, it's no functional problem but there may be migrations which get merged into the wrong folder.

Yes, that's why I would like we merge this one ASAP so that other PRs could change their migration file position.

**Comment by KN4CK3R** [comment]
I've looked into how other projects handle this.

Gitlab: one **big** folder
https://gitlab.com/gitlab-org/gitlab/-/tree/master/db/migrate

Wordpress: one big file
https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/upgrade.php

phpBB: same as this PR
https://github.com/phpbb/phpbb/tree/master/phpBB/phpbb/db/migration/data

The only problem I see, are version changes. If a PR is moved from milestone 1.18 to 1.19 the authors must remember to move the migration file. There is a chance that a 1.19 migration resides in the 1.18 folder. This doesn't break the functionality but is still not correct.

**Review by KN4CK3R — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
