### PR TITLE
bump vue-bar-graph

### PR DESCRIPTION
**Pull request by techknowlogick**
The change should be minimal. I've marked this PR as WIP/draft, as I still need to do local testing, but I wanted to get a PR up as quickly as possible. Please wait to review it until I take it out of draft.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
It seems that there was an indirect dependency for "vue-compiler", which affects something like `<div class="scoped-access-token-mount"><scoped-access-token-selector></div>`. So these dependencies are still necessary (and fortunately they are still there).

**Comment by silverwind** [comment]
Yes, runtime dependency on the compiler needs to be removed and moved to webpack, I'm just not sure how to do this as I'm no Vue expert 😆.

**Comment by lunny** [comment]
issue created https://github.com/lafriks/vue-bar-graph/issues/18

**Comment by techknowlogick** [comment]
This is now ready for review.

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by wxiaoguang** [comment]
->  scoped-access-token-mount not mounted anymore #31771 

Eventually, it is broken

**Comment by lafriks** [comment]
@wxiaoguang because of the vue bar graph?

**Comment by wxiaoguang** [comment]
> @wxiaoguang because of the vue bar graph?

yes

**Comment by lafriks** [comment]
How? They are not even in the same page 🤔

**Comment by wxiaoguang** [comment]
I have explained it https://github.com/go-gitea/gitea/pull/31705#issuecomment-2251807259

And you could check out the commit before this PR to test.

**Comment by silverwind** [comment]
Could it be that vue loads twice or something?

I know similar issues with react whith components that have dependency on `react-dom` which causes react to go haywire when it loads multiple times on the same page.

@lafriks I think you should check what the common practices are for publishing vue components. Check other popular components how they do it.

**Comment by lafriks** [comment]
I have and in vite vue is already set as external library/dependency and are not included in library

**Pull request merged**
