### PR TITLE
Fix strange UI behavior of cancelling dismiss review modal (#25133)

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #25133 by @yp05327

Fixes https://github.com/go-gitea/gitea/issues/25130

The old code uses `$(this).next()` to get `dismiss-review-modal`.
At first, it will get `$(#dismiss-review-modal)`, but the next time it will get `$(#dismiss-review-modal).next();`
and then `$(#dismiss-review-modal).next().next();`.
Because div `dismiss-review-modal` will be removed when `dismiss-review-btn` clicked.

Maybe the right usage is adding `show-modal` class and `data-modal` attribute.

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Review by techknowlogick — CHANGES_REQUESTED** [review]
adding blocked review so this doesn't get accidentally merged. feel free to dismiss this review as needed

**Comment by silverwind** [comment]
Blocked because of https://github.com/go-gitea/gitea/pull/25133#discussion_r1222849829. Once the fix is available, we can still merge this and then backport the fix.

**Comment by silverwind** [comment]
Merge this before the backport of https://github.com/go-gitea/gitea/pull/25162

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/25172 contains this backort.

**Pull request closed without merging**
