### PR TITLE
Pass link prefixes to external markup parsers

### LINKED ISSUE #5031: External markup renderers can't use in-repo images
- Gitea version (or commit ref): 1.5.1
- Git version: master
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

The logic in modules/markup/markdown's `(*Renderer).Image` is inaccessible to external renderers. Relative image URLs pass through unchanged and wrong.

I can think of two solutions:
 - Expose `urlPrefix`  to the process as an environment variable, such as `GITEA_PREFIX_SRC=/user/repo/raw/branch/master/subdir/` and `GITEA_PREFIX_RAW=/user/repo/raw/branch/master/subdir/`. Then you can at least wrap external tools in scripts; asciidoctor just needs to have the `imagesdir` attribute set appropriately.
 - Change all relative image `src`s in a `PostProcess` step to point to a `/raw/` location because they are pointless anyway (a brute force solution would be to use `<base href=>` in the header template).

### PR DESCRIPTION
**Pull request by Eisfunke**
Should close #5031.

This passes the current URL prefixes to external markup parsers as environment variables.

`GITEA_PREFIX_SRC` is the current link prefix in the `src` path tree, `GITEA_PREFIX_RAW` is the prefix for images in the `raw` path tree.

The `raw` prefix is obtained by string replacement. That's not quite elegant, but it's what `markdown.go` does, so I copied that.

I tested the change with Pandoc as markdown parser, and I was able to get links and images working using the environment variables.

Signed-off-by: Nicolas Lenz <nicolas@eisfunke.com>

### CODE REVIEW

**Comment by lunny** [comment]
~After this merged so  we can change the ini for example~:
```ini
[markup.ascii]
ENABLED = false
FILE_EXTENSIONS = .adoc,.asciidoc
RENDER_COMMAND = "asciidoc --imagesdir=$GITEA_PREFIX_SRC --out-file=- -"
IS_INPUT_FILE = false
```

**Review by techknowlogick — APPROVED** [review]

**Comment by Eisfunke** [comment]
> After this merged so we can change the ini for example:
> 
> ```ini
> [markup.ascii]
> ENABLED = false
> FILE_EXTENSIONS = .adoc,.asciidoc
> RENDER_COMMAND = "asciidoc --imagesdir=$GITEA_PREFIX_SRC --out-file=- -"
> IS_INPUT_FILE = false
> ```

For images `GITEA_PREFIX_RAW`, not `GITEA_PREFIX_SRC`, should be used, I think.

**Review by lunny — APPROVED** [review]
```ini
[markup.ascii]
ENABLED = false
FILE_EXTENSIONS = .adoc,.asciidoc
RENDER_COMMAND = "asciidoc --imagesdir=$GITEA_PREFIX_RAW --out-file=- -"
IS_INPUT_FILE = false
```
It's not right you can config as above, `$GITEA_PREFIX_RAW` is blank, you have to write a shell script and use `$GITEA_PREFIX_RAW` in your script.

**Comment by Cellebyte** [comment]
```ini
[markup.asciidoc]
ENABLED = true
FILE_EXTENSIONS = .adoc,.asciidoc
RENDER_COMMAND = 'asciidoctor -b html5 -a imagesdir="$GITEA_PREFIX_RAW" -a relfileprefix="$GITEA_PREFIX_SRC" --out-file=- -'
IS_INPUT_FILE = false
```

The config is not working with commit ref:078c404c3b0f283a242ad93b6a2f4cabb2575410

**Comment by lunny** [comment]
@Cellebyte Yes, it will not except you create a shell script and save that command there.

**Comment by Cellebyte** [comment]
@lunny thanks so i should copy a simple wrapper script with $@ to asciidoc?
Do you have an example?

**Comment by lunny** [comment]
I mean you can create a script file such as `convert.sh` and copy your command there, i.e.
```shell
#!/bin/bash
asciidoctor -b html5 -a imagesdir="$GITEA_PREFIX_RAW" -a relfileprefix="$GITEA_PREFIX_SRC" --out-file=- -
```

**Comment by Cellebyte** [comment]
Have done that. Will test it thanks for the reply ;)

```bash
#!/bin/bash
asciidoctor -b html5 -a imagesdir="$GITEA_PREFIX_RAW/" -a relfileprefix="$GITEA_PREFIX_SRC/" --out-file=- $1 | sed 's/lang="en">//'
```
Need to use sed, don't know why this lang="en" appears.

**Comment by andreashaerter** [comment]
> I tested the change with Pandoc as markdown parser, and I was able to get links and images working using the environment variables.

@Eisfunke Would you mind to share the used `RENDER_COMMAND` for pandoc? :-)

**Comment by garyritchie** [comment]
Sounds like this might close #3025 - can anyone confirm?

@Cellebyte did the shell script work in your case?

**Comment by Cellebyte** [comment]
Yes @garyritchie it worked very well. The only problem are svg images. But this is referenced in another Issue.

**Comment by garyritchie** [comment]
Thanks @Cellebyte !

Where should I put the script? I'll need to include it when I build my gitea-asciidoc docker image (based on gitea:1.8).

**Comment by Cellebyte** [comment]
```Dockerfile
FROM gitea/gitea:1.8

RUN apk add --update --no-cache \
    ruby \
    sed \
    ca-certificates \
    asciidoctor && \
    gem install --no-ri --no-rdoc coderay && \
    gem update --no-ri --no-rdoc asciidoctor && \
    gem cleanup && \
    rm -rf /tmp/* /var/cache/apk/*

COPY asciidoc.sh /usr/bin/asciidoc.sh
RUN chown 1000:1000 /usr/bin/asciidoc.sh && \
    chmod 0755 /usr/bin/asciidoc.sh
```
Thats my Dockerfile

**Comment by garyritchie** [comment]
Got it working, thanks!

**Pull request merged**
