### PR TITLE
Change default sort order

### LINKED ISSUE #2442: Default Sort in Explore Page
Since commit fa3abc22c06843bb27089e8c0f7aebf0f5d83fcc, the default sort criterion on the Explore page has been created_unix instead of updated_unix. I really preferred the earlier behavior, so I just wanted to make sure that the change was intentional (the commit didn't seem to be explicitly for that purpose so it may have been an accidental byproduct), and if it was intentional, request that it be changed back or have a config setting exposed for it.

### PR DESCRIPTION
**Pull request by kaz**
Change default sort key to `updated_unix` from `created_unix`
(repositories order on explore page)

it was suggested on (#2442)

Closes #2442

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by daviian** [comment]
You have changed sorting of users instead of repositories..

**Comment by kaz** [comment]
oops, fixed it

**Comment by daviian** [comment]
LGTM

**Comment by Morlinest** [comment]
Give me some time to test it, I think there is little problem.

**Comment by Morlinest** [comment]
@lafriks @daviian This PR can't be merged, there is reason for current default. It's used in conjunction with UI, where default option for sorting is `newest`.

image


@kaz You have to change UI (html templates) too. It's not so simple like changing 1 value :).

**Comment by lafriks** [comment]
When testing list looked correct for me, did not check sort menu, good catch

**Review by lafriks — CHANGES_REQUESTED** [review]
Need to fix also UI as @Morlinest pointed out

**Comment by kaz** [comment]
I fixed that UI problem.
Sorry for my insufficient testing :bow:

**Comment by Morlinest** [comment]
@kaz NP. You are not done yet :D. You have to add `case "newest":` to  `models.RenderRepoSearch()`.

**Review by lafriks — APPROVED** [review]

**Comment by Morlinest** [comment]
@kaz Please check every place, where your changes are used. If I search `explore/search`, it's used in 4 other templates. First that mean that you are changing more than 1 search page (@lafriks @daviian do you want to change it too?), second, I think you have to add `case "newest"` also to `models.RenderUserSearch()`

**Comment by daviian** [comment]
@Morlinest you are right @kaz has to add `newest` to `models.RenderUserSearch()` as well. Regarding the impact on the other search pages: it is fine more me, since sorting org and users by newest isn't that useful anyway, so doesn't hurt. But I have to add that we should change org and user searching to be alphabetically by default (will create separate issue for that).

**Comment by kaz** [comment]
I made some changes.

- Fix some problems which @Morlinest pointed out
- Set `ctx.Data["SortType"]` in default clause
	- to use different sort order in repos/users/orgs page with same template
- Change default sorting of user/org search to alphabetical (#2656)

This changes affects pages below:

| page | order(old) | order(new) |
| --- | --- | ---|
| `/explore/repos` | newest | recentupdate |
| `/explore/users` | newest | alphabetically |
| `/explore/organizations` | newest | alphabetically |
| `/{user_name}` (repositories tab) | newest | recentupdate |
| `/{user_name}` (stars tab) | newest | recentupdate |

**Review by daviian — APPROVED** [review]
Tested and approved again after new changes 👍

**Comment by lafriks** [comment]
Make LG-TM work again

**Pull request merged**
