### PR TITLE
API allow to create closed milestones

### PR DESCRIPTION
**Pull request by 6543**
as title

### CODE REVIEW

**Comment by 6543** [comment]
usefull for https://gitea.com/gitea/go-sdk/issues/356

**Review by zeripath — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Review by techknowlogick — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
