### PR TITLE
Avoid make-generate downloading packages from the internet

### LINKED ISSUE #7997: Can not build anymore since version 1.9.0
- Gitea version (or commit ref): 1.9.2
- Git version:2.16.4
- Operating system:  openSUSE Leap 15.1, openSUSE Leap 15.0, openSUSE Tumbleweed
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

A build using opensuse build service and also local is not possible.
First I want to build gitea in the opensuse build service.
But this fails, because the build process would like to load different packages from github, even though the files actually exist in the vendor directory of the source. The buildservice does not allow external sources to be downloaded during the build process.
Up to version 1.8.2 the build worked without problems.
As of version 1.9.0, this is no longer possible.
Even a build directly does not work. I first download the 1.9.2 release. Unzip the source and change to the directory. then I do the following:
TAGS = "bindata" make generate all
It then appears:
github.com/klauspost/compress/gzip
github.com/blevesearch/bleve/index/scorch
make: *** [Makefile: 315: gitea] Error 1

Why are the files in the vendor directory no longer used?
What do I have to do to reuse it so that I can recreate a package using opensuse buid service?

### PR DESCRIPTION
**Pull request by typeless**
Fixes #7997

### CODE REVIEW

**Comment by typeless** [comment]
I assume the `PACKAGES` and `SOURCES` env variables don't need to be configurable.

**Comment by lunny** [comment]
I think we have `-mod=vendor` on https://github.com/go-gitea/gitea/blob/master/Makefile#L100

**Comment by typeless** [comment]
@lunny yes, but after trying to `make generate` by myself, I found it does downloads from the internet. The root cause is actually `go list ./...`. 

What baffles me right now is that I cannot reproduce the CI error at my local machine.

**Comment by typeless** [comment]
We still have other dependencies which require downloads such as the swagger tool.
The latest version (https://github.com/go-swagger/go-swagger/issues/1681) of go-swagger has supported modules. Hopefully, we can remove the `GO111MODULE=off` workaround soon.

**Comment by sapk** [comment]
@typeless and current go-swagger version require to be in GOPATH which hold us to move to a real mod workflow.

**Review by sapk — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Pull request merged**
