### PR TITLE
Fix wrong status of `Set up Job` when first step is skipped

### LINKED ISSUE #32089: Gitea Actions shows Set up Job as failed
### Description

When skipping the first and last step in a workflow, the step "Set up Job" is indicating as failed, even though the workflow is running correctly. The workflow is running correctly and results in a success.

Somehow the complete log of the job is included in the "set up job" step. The "complete job" log is empty.

I replicated the issue on the demo instance here: https://demo.gitea.com/marekschneider/test-steps/actions/runs/3

### Screenshots

image
image

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

Chrome 128

### PR DESCRIPTION
**Pull request by yp05327**
Fix #32089

### CODE REVIEW

**Comment by yp05327** [comment]
But this is a bit strange that the status of prepare step is handled by the status of task and first step but not it self.

**Comment by wolfogre** [comment]
Could you please add some test cases for this?

**Comment by yp05327** [comment]
While I tried to add the test, I found the logic is not right for `LogLength`.
Need to rewrite some code here.

**Comment by yp05327** [comment]
> Could you please add some test cases for this?

@wolfogre test added

**Review by wolfogre — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
