### PR TITLE
Fix error 500 on organization dashboard page

### PR DESCRIPTION
**Pull request by lunny**
Fix the behaviour of the function `Count` in XORM

This will replace #147. So #147 could be closed.

### CODE REVIEW

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by andreynering** [comment]
LGTM

**Comment by thibaultmeyer** [comment]
@lunny Maybe you have to port this fix on the real XORM repository too

**Comment by lunny** [comment]
Of course I already did that

**Pull request merged**
