### PR TITLE
Add missing migrations for columns on repository and user

### PR DESCRIPTION
**Pull request by guillep2k**
Working in #9787 I've found that there are some columns in `repository` and `user` which have no migration step. For my PR I need these columns to exists before starting the main process, so I've created a migration step for them.

### CODE REVIEW

**Comment by lunny** [comment]
The columns are not missing but migrations maybe missed.

**Comment by guillep2k** [comment]
> 
> 
> The columns are not missing but migrations maybe missed.

Sorry, bad wording of the PR title. Changed.

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
think it can go in now

**Comment by zeripath** [comment]
make lg-tm work

**Pull request merged**
