### PR TITLE
feat(#31666): Set the columns height to hug all its contents

### PR DESCRIPTION
**Pull request by Simandara**
In Projects, columns heights are defined by the sum of all contents height of the biggest column, rather than a fraction of the viewport height. It default to 60vh when there is no cards to display.

---

See issue #31666

### CODE REVIEW

**Comment by SimonPistache** [comment]
I noticed a visual bug while dragging issues around

https://github.com/user-attachments/assets/dad847ee-b0bb-4639-b7fd-3b74fc25a903

Looking for a fix

**Comment by SimonPistache** [comment]
With the fix:

https://github.com/user-attachments/assets/f7dce465-8ee3-41d9-8493-f09f51578f31

**Comment by SimonPistache** [comment]
I improved the columns behaviours when there is no cards in it. Now, the columns either takes all available height in the viewport, except if it's too small, defaulting to 300px height (and forcing a viewport scrollbar). This makes a newly created Project board attractive to start with.

Boards already having cards are not affected by this (Columns takes all available height from the viewport, except if it's too small then it "hug" by its contents.)

https://github.com/user-attachments/assets/c8ffb20f-af06-4262-b561-cb339800283a

**Comment by SimonPistache** [comment]
There is an issue with this solution: The horizontal scrollbar is way down the board when there is more columns than the viewport can display at once.

Idea:
Using 2 divs to manage scrollbar individually:

```HTML
<div id="project_board">
  <div class="class="board sortable"">

  </div>
</div>
```

```CSS
#project_board {
    overflow-x: auto;
    overflow-y: hidden;
}

#project_board > .board {
    overflow-y: auto;
    display: inline-block;
    height: 100vh;
    white-space: normal;
}
```

This is going back as the idea of the board only overflowing a sub-rectangle of the viewport instead.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
