### PR TITLE
fix(api): owner ID should be zero when created repo secret

### PR DESCRIPTION
**Pull request by appleboy**
- Change condition to include `RepoID` equal to 0 for organization secrets

### CODE REVIEW

**Review by wolfogre — CHANGES_REQUESTED** [review]
Sorry, I don't get it, why?

And how to handle deleting org?

https://github.com/go-gitea/gitea/blob/0fe9f93eb4c94d55e43b18b9c3cc6d513a34c0b5/models/organization/org.go#L404

**Comment by appleboy** [comment]
> Sorry, I don't get it, why?
> 
> And how to handle deleting org?
> 
> https://github.com/go-gitea/gitea/blob/0fe9f93eb4c94d55e43b18b9c3cc6d513a34c0b5/models/organization/org.go#L404

Yes, `&secret_model.Secret{OwnerID: org.ID}` is right.

**Review by wolfogre — APPROVED** [review]
Sorry, I misunderstood. I get it now.

**Review by lunny — APPROVED** [review]

**Comment by wolfogre** [comment]
Please also review

- #31724
- #31725

**Pull request merged**
