### PR TITLE
Allows repo search to match against "owner/repo" pattern strings

### LINKED ISSUE #19617: Repository search ignores org/username
### Description

When searching for repositories (for example on the dashboard, or in the "Reference in new issue" popup), the search string only takes into account the repository name, but not the org or user name.

IE if a repository exists at:

`MyOrgName/WhataFunRepo`

then the search will ignore `MyOrgName`

The search should take into account the whole repo path. So a search for `MyOrgName/` should work.

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Self hosted on linux via a prebuilt binary

### Database

SQLite

### PR DESCRIPTION
**Pull request by Eekle**
Closes #19617

If the `teamID` is 0 so we're not searching in a specific team, and the keyword has a single slash in - try and match each part of "owner/repo" against the `owner_name` and `lower_name` fields.

Architecturally I don't know if this messes with API endpoints or something - I'm not that familiar. But I thought better to make the PR so there's something to discuss around at least.

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Yep, I thought for about two minutes if you missed any edge cases but couldn't find any, so LGTM.
(However, I would recommend running `make fmt`.)

**Comment by Eekle** [comment]
> Yep, I thought for about two minutes if you missed any edge cases but couldn't find any, so LGTM. (However, I would recommend running `make fmt`.)

Yeah my bad!

I used gofumpt based on the output from drone - is that equivalent?

**Comment by delvh** [comment]
I think so. `make fmt` basically downloads gofumpt if not present and runs it then.

**Comment by 6543** [comment]
a unit test to add this case would be nice ... if you need help just ask

**Comment by delvh** [comment]
@Eekle my definition of assignee is `the person working on this PR`, so I simply assigned you because you opened it.

**Comment by Eekle** [comment]
@delvh Oh cool np. I'm used to issue workflows where the assignee is whoever next has to do a thing - so if this were assigned to anyone I would expect it to be a second reviewer.

But this makes just as much sense :) Thanks

---

@6543 Sounds good. I will try and work that out tomorrow but will holler if I need help!

**Comment by lunny** [comment]
So then we cannot search `/` in the text?

**Comment by Eekle** [comment]
> So then we cannot search `/` in the text?

This change does not remove any results - it only adds them. IE anything that matched before will still match - and some new stuff might too.

**Comment by lunny** [comment]
> > So then we cannot search `/` in the text?
> 
> This change does not remove any results - it only adds them. IE anything that matched before will still match - and some new stuff might too.

Maybe we need have a sort so that repository matched `owner/repo` will be on the top.

**Comment by Eekle** [comment]
> > > So then we cannot search `/` in the text?
> > 
> > 
> > This change does not remove any results - it only adds them. IE anything that matched before will still match - and some new stuff might too.
> 
> Maybe we need have a sort so that repository matched `owner/repo` will be on the top.

That sounds sensible - I'm not sure I know how to do that but I'll give it a try. 

Out of curiosity how could a string with a forward slash match otherwise? I didn't think it was an allowed character?

**Comment by Eekle** [comment]
@6543 Unit tests added. Required a bit of change to the test runner just because of the way it checks pass/fail on matches.

**Comment by Eekle** [comment]
@lunny Adds search ordering such that owner matched repositories are at the top, only when the owner priority ID field isn't already filled.

It's hard to think how to validate this - because I don't think a search string with a slash in could match any other way.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
please "update branch"

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
