### PR TITLE
Make time diff translatable

### PR DESCRIPTION
**Pull request by lafriks**
Changed also all other language files as otherwise they would be in broken shape

### CODE REVIEW

**Comment by pgaskin** [comment]
The other language files will end up being overwritten.

**Comment by lafriks** [comment]
I know, if not translated they will be in English but while not regenerated from crowdin at least they will not have %!s(MISSING) texts as I have removed %s from some places and added to others

**Comment by pgaskin** [comment]
OK

**Comment by lunny** [comment]
@lafriks but that's difficult to merge when we import from crowdin.

**Comment by lafriks** [comment]
Ok, I will revert that one commit but it will break time diff display for non-english languages while not imported form crowdin

**Comment by sondr3** [comment]
Probably off-topic, but just curious: why not just output the time as a ISO-formatted string in the HTML and use a JS library to convert it as mentioned in #1906?

**Comment by lafriks** [comment]
Because it is sent also in email

**Comment by lafriks** [comment]
@lunny done

**Comment by lunny** [comment]
@sondr3 and also, we need a server locale config item.

**Comment by lunny** [comment]
LGTM, This maybe broken other languages UI until they upload the newest translations.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
