### PR TITLE
Remove easymde, tributejs and codemirror

### PR DESCRIPTION
**Pull request by silverwind**
WIP because the wiki editor is broken in various ways. Other editors should work as usual.

This also introduces a migration mechanism for `localStorage`, in this case to get rid of two unused keys.

### CODE REVIEW

**Comment by silverwind** [comment]
Maybe I will implement side-by-side mode that was previously only active on wiki which gets lost with this removal.

If I understand correctly, this mode was not a accurate markdown rendering because it was produced by EasyMDE instead of the backend renderer, so the new solution would definitely make use of the backend renderer, e.g. the same one that is used for the preview tab in issues/prs.

**Comment by wxiaoguang** [comment]
I strongly prefer do not do so until it is clear that there is no user uses EasyMDE. Although it is not modern, it does help some non-technical background people.

And I have objection for removing the "combo" prefix, the name was chosen intentionally, to distinguish it from other "markdown editors". And it is indeed a real "combo": it has toolbar, it works with uploader, etc.

**Comment by silverwind** [comment]
> I strongly prefer do not do so until it is clear that there is no user uses EasyMDE

There were zero complaints when we switched the default editor and it should be noticable because EasyMDE users see a flash of wrong on every page. So I think it's high time to get rid of it.

> And I have objection for removing the "combo" prefix

I thought the "combo" refered to it being two editors in one. Still prefer it without the prefix because the toolbar is part of the editor in my view, otherwise it would just be "textarea".

**Comment by silverwind** [comment]
Well, looks like no one here is interested cleaning up this legacy stuff it seems.

**Comment by delvh** [comment]
Oh, there is, I simply forgot about this PR like so many others on my bucket list.

**Comment by silverwind** [comment]
I would stil aim to remove it for 1.23. Anyone agree?

**Comment by delvh** [comment]
Yep, I agree. I'll go ahead and post an issue to gather community feedback.
If there is no heavy feedback not to remove it, then we should remove it for 1.23.

**Comment by delvh** [comment]
See #30474

**Comment by silverwind** [comment]
I think I would have a fresh go at another time. @wxiaoguang what is your preference on the name? Keep ComboMarkdownEditor? I find that an awefully long name.

**Comment by wxiaoguang** [comment]
> I think I would have a fresh go at another time as #30480 will introduce too many conflicts here. @wxiaoguang what is your preference on the name? Keep ComboMarkdownEditor? I find that an awefully long name.


And I have objection for removing the "combo" prefix, the name was chosen intentionally, to distinguish it from other "markdown editors". And it is indeed a real "combo": it has toolbar, it works with uploader, etc.

I do like long names, it doesn't make anything worse, it doesn't slow down, it doesn't wastes storage. It indeed make the code clear, conflict-free and maintainable. We can easily search anything from whole codebase easiliy.

**Pull request closed without merging**
