### PR TITLE
Add muted class to author name in repo commit list

### PR DESCRIPTION
**Pull request by yp05327**
Before:
image

After:
image

If repo is a mirror, external user's name will be white, but if user is existed, then you will see blue names and white names together:
image

### CODE REVIEW

**Comment by silverwind** [comment]
There is inconsistent margin in your second screenshot. Does `.author-wrapper` fix that?

**Comment by delvh** [comment]
I haven't quite understood, when will the name be displayed in blue?
To me, it looks like it will always be white…

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Yes, make it always muted please.

**Comment by yp05327** [comment]
> There is inconsistent margin between avatar and text in your second screenshot.

It is caused by these unknow spaces. Where does these spaces come from?
image
image
image

**Comment by silverwind** [comment]
HTML whitespace, we can make it insignficant by setting `display: flex` I assume.

**Comment by silverwind** [comment]
Pushed a margin increase:

image

**Review by silverwind — APPROVED** [review]

**Comment by yp05327** [comment]
> HTML inter-tag whitespace, we can make it insignficant by setting display: flex I assume.

image
flex caused username is not in the middle
image
image

**Pull request merged**
