### PR TITLE
Sort repos in issues dashboard sidebar

### PR DESCRIPTION
**Pull request by ethantkoenig**
Sort repos in the sidebar of the issues dashboard page. Previously, the order would vary each time the page (re)loaded (example below).

image
image

### CODE REVIEW

**Comment by silverwind** [comment]
Did you test if they sort the same like on the main dashboard. I noticed org repos there sort by `repo`, not `org/repo`, e.g. `org/a` sorts before `a/b`. Thought, I think that sorting by `org/repo` is probably more intuitive.

**Comment by lafriks** [comment]
I think they should be sorted by name

**Comment by ethantkoenig** [comment]
@silverwind @lafriks Done

**Comment by silverwind** [comment]
Ideally, I think it should first sort the user's own repos and after that the other ones, but that's just nitpicking at this point, any sorting is better than no sorting :)

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
