### PR TITLE
Fix text truncate

### LINKED ISSUE #25597: Font baseline is misaligned on issues page
### Description

https://try.gitea.io/issues

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image
image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by Maks1mS**
Fixes: https://github.com/go-gitea/gitea/issues/25597

Before:
image

After:

image

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Haven't found any ovious regression.

**Review by wxiaoguang — COMMENTED** [review]
Related to " Adjust line-height on dashboard sidebar #25600 " , it seems that it needs a complete solution.

**Comment by denyskon** [comment]
Maybe this is a good solution.... @silverwind what do you think?

**Comment by silverwind** [comment]
Using `overflow-x` only is better, yes. Whether the value is `clip` or `hidden` should not make any difference for us. I do wonder whether this change has any unintended side-effect, like with multi-line content, but I think it's probably safe.

**Review by silverwind — APPROVED** [review]
Should be fine, we prevent wrapping via `white-space: nowrap` so there can't be an issue with wrapped lines.

**Review by denyskon — APPROVED** [review]

**Comment by wxiaoguang** [comment]
## `overflow-x: clip`

It causes regression:


image

## `overflow-x: hidden`

image

**Comment by silverwind** [comment]
Works in Chrome, it seems this is a Firefox bug, I think both values are equal in terms of "cutting off content".

**Comment by silverwind** [comment]
Safari also has a bug with it:

clip:
Screenshot 2023-08-15 at 13 58 10

hidden:
Screenshot 2023-08-15 at 13 58 18

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/26520 will fix both.

**Pull request merged**
