### PR TITLE
When using API CreateRelease set created_unix to the tag commit time

### PR DESCRIPTION
**Pull request by jasder**
When creating a release with api, the release time of the version is wrong(is actually the user's update time)

Ex:
image

### CODE REVIEW

**Comment by 6543** [comment]
pleace "update" this branch

**Review by 6543 — APPROVED** [review]

**Review by guillep2k — COMMENTED** [review]
This looks good to me, but the current behavior looks kind of fishy... almost intended. Can this be considered a matter of preference? This PR will not affect _just_ the API.

**Comment by 6543** [comment]
same thought - but think this behaviour more intuetive - to controle it via an option would probably be the best ...

**Comment by 6543** [comment]
@jasder change this pull so it can be controled via option

**Comment by lunny** [comment]
A release is based on a tag, but should release created time be the same as the tag time? Since tag time has been saved on git, so it's unnecessary to save it again in the database.

**Comment by jasder** [comment]
@lunny But release's the return created time is based on release, and rend directly from the database.

**Review by guillep2k — APPROVED** [review]
OK, I think this makes sense.

**Comment by richmahn** [comment]
@lunny @jasder I am having problems due to this little change. Even if you update the content of a release (the message such as make a change to the changelog in the content), the created_unix time of the release gets updated again! It isn't when the tag was created any more.

**Comment by richmahn** [comment]
So somewhat related, in that this shouldn't be set when a tag is already set (before it didn't matter since it was going by the commit date that the tag pointed to): https://github.com/go-gitea/gitea/issues/12341. Please make backport to 1.12 if possible.

**Pull request merged**
