### PR TITLE
Backport: fix crippled diff (#4726)

### PR DESCRIPTION
**Pull request by tonivj5**
Backport of https://github.com/go-gitea/gitea/pull/4900

### CODE REVIEW

**Comment by SagePtr** [comment]
And make regenerate-stylesheet for this too (because it's quite different on different branches)

**Comment by tonivj5** [comment]
Thanks @techknowlogick, it was! :tada:

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by oscarlofwenhamn** [comment]
> @xxxtonixxx it may be that you need to `rm -rf node_modules` and `npm i` it again before building. I know there was a change to the less library that caused a different output

I am having a similar error,
Is this to be done in the gitea root folder or more so in the npm install folder?

**Comment by tonivj5** [comment]
In the gitea root folder, @oscarlofwenhamn

**Comment by oscarlofwenhamn** [comment]
Thanks!

**Pull request merged**
