### PR TITLE
Fix #6234 : Check organization visibility before everything else

### LINKED ISSUE #6234: Public repositories of a private organization are not hidden
- Gitea version (or commit ref): 8e202e28ad80452ced90ede3540e1662fa6d7da7
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) - https://try.gitea.io/secretorg/defaultrepo/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

TLDR: Public repositories of a private organization are not hidden properly.
1, create a private organization: _secretorg_
2, create a new repository in it, without marking as private, _defaultrepo_
3, check : https://try.gitea.io/secretorg/defaultrepo/ -> repository navigation header is visible, with a 404 in the  middle
4, check : https://try.gitea.io/secretorg/defaultrepo/ssues - everything visible, etc

For a private organization, I would expect, that their repositories would be invisible for non-members. 

## Screenshots

gitea_1
gitea_2

### PR DESCRIPTION
**Pull request by gzsombor**
Fixing #6234

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm... I think we need to formally specify what the authorisation and permission regime should be. We're getting a lot of these little fixes and although I don't think they're ending up inconsistent, I suspect edge cases are likely to be missed and we may end up with security holes.

**Review by zeripath — CHANGES_REQUESTED** [review]
repo.Owner may not be loaded - therefore you need to load the owner before dereferencing it.

That is:

```go
repo.MustOwner()
```

Or use:

```go
err:=repo.GetOwner()
```

And handle the error.

**Comment by gzsombor** [comment]
I hope I get it right.

Having a well defined permission model would be nice - for example, it's not clear for me, if having public repositories in a private organization would make any sense. But an organization can freely switch between it's visibility settings, their repository should behave consistently after switching back and forth.

**Comment by lunny** [comment]
I like @zeripath 's idea. I think maybe someone could add that on the docs.

**Comment by lunny** [comment]
But that's for another PR. @zeripath please review again.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
