### PR TITLE
CSS: Stronger colors for diffs

### PR DESCRIPTION
**Pull request by andreynering**
It looked a too lightier for me

[Before](https://cloud.githubusercontent.com/assets/7011819/20041080/d4ac9364-a44a-11e6-8634-a42f5e922d2a.png)

[After](https://cloud.githubusercontent.com/assets/7011819/20041081/e4286d5e-a44a-11e6-877a-1b4612d62db3.png)

### CODE REVIEW

**Comment by bkcsoft** [comment]
did you verify that the duplication isn't needed anymore?

**Comment by tboerger** [comment]
From the screenshots it LGTM but I have not tested it.

**Comment by andreynering** [comment]
@bkcsoft Yes. Actually, there's more cleanup that can be done (I didn't do because it's not related to this change).

**Comment by DblK** [comment]
LGTM

**Comment by tboerger** [comment]
Don't add that label manually, that should be done by LGTM later on :)
@bkcsoft if you are fine with it merge it.

**Pull request merged**
