### PR TITLE
Make  AvatarRenderedSizeFactor configurable and set it to 3

### LINKED ISSUE #16287: User avatar in profile page changed from s=290 to s=580 while rendered at s=128 anyway
Gitea 1.14.3 is requesting Libravatar avatar images with size 580 in profile page while rendering them at 128x128.
Older versino 1.12.3 was requesting a size of 290 instead.

I think it would make sense to request s=128 instead, to reduce the download time

### PR DESCRIPTION
**Pull request by silverwind**
Save a bit of bandwidth by only requesting 3-times the rendered avatar size. Factor 4 is only really beneficial on a [handful of mobile phones](https://www.mydevice.io/#compare-devices) and I don't think they are the primary device we design for.

Fixes: https://github.com/go-gitea/gitea/pull/17422
Fixes: https://github.com/go-gitea/gitea/issues/16287

### CODE REVIEW

**Comment by silverwind** [comment]
For reference, the devices with pixel ratio > 3 from the link above:

image

**Comment by silverwind** [comment]
CI failure unrelated, drone seems broken.

**Comment by zeripath** [comment]
@silverwind https://github.com/silverwind/gitea/pull/1 will make this configurable option which should make @strk happy

**Comment by strk** [comment]
Yes I'm happy with configurable, and merged your PR to mine (#17422)

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Merged and did some minor description adjustments. Default is `3` here and I think this is the ideal value.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
PR title and commit description updated.

**Comment by lunny** [comment]
CI failed is unrelated.

**Pull request merged**
