### PR TITLE
Normalize files with gofmt

### PR DESCRIPTION
**Pull request by thibaultmeyer**
Normalize Gitea Go files with the command `gofmt`

### CODE REVIEW

**Comment by andreynering** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM

**Comment by metalmatze** [comment]
Thanks it always bugs me. How about we make `gofmt` mandatory?

**Comment by lunny** [comment]
`make lint` on CI after we fix all the lint errors.

**Comment by strk** [comment]
On Fri, Nov 11, 2016 at 09:23:22AM -0800, Lunny Xiao wrote:

> `make lint` on CI after we fix all the lint errors.

Please expose a `make dev-setup` too, to install relevant
git hooks to ensure style upon commit :)

**Pull request merged**
