### PR TITLE
Handle more pathological branch and tag names

### PR DESCRIPTION
**Pull request by zeripath**
It's possible to push quite pathological appearing branch names to gitea using `git push gitea reasonable-branch:refs/heads/--` at which point large parts of the UI will break. Similarly you can `git push origin reasonable-tag:refs/tags/--` which wil return an error.

This PR fixes the problems these cause. It also changes the code from creating branches to pushing to ensure that branch restoration has to pass hooks.  

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
OK so there was a real issue - in addition to the test being broken - I had missed that we removed the deleted branch reference from the table which of course we no longer have to do as the push does that for us.

**Review by 6543 — APPROVED** [review]
escaping :D

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Comment by techknowlogick** [comment]
@zeripath please send backport :)

**Pull request merged**
