### PR TITLE
update drone discord plugin to 0.0.4 version

### PR DESCRIPTION
**Pull request by appleboy**
screen shot 2017-06-17 at 12 40 51 am

update to 0.0.4 version.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by sapk** [comment]
LGTM

**Comment by cotti** [comment]
Ok, this is pretty dangerous. How would one go into removing all code related to Discord on their build of Gitea?

**Comment by sapk** [comment]
@cotti This is just to post build information from the drone instance used to build and test gitea code. The code and binary doesn't contains any links to discord (you can setup a hook but it need configuration and activation).

**Pull request merged**
