### PR TITLE
Allow Gitea to run as different USER in Docker

### PR DESCRIPTION
**Pull request by techknowlogick**
This PR allows users to rename the default user in the Docker image by passing a different $USER environment variable

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by tboerger** [comment]
I don't see any need for that but code wise it could work

**Comment by lafriks** [comment]
@tboerger if someone wants to use different user for connecting to ssh for git operations

**Comment by tboerger** [comment]
But git is totally common for that. If Gitea is running on the host I really get it to avoid name collisions, but that can't be the case within Docker.

**Comment by daviian** [comment]
I agree with @tboerger in some degree, as the user `git` is widely used.
However if it's that easy to add and maybe some need that functionality then why not. So LGTM

**Pull request merged**
