### PR TITLE
Fix being unable to use a repo that prohibits accepting PRs as a PR source. (#26785)

### LINKED ISSUE #24585: Upstream branch missing in drop-down lists when creating pull request
### Description

This issue occurred after the update of Gitea from v1.19.1 to v1.19.3.

A mirror of a github project was created in Gitea, as shown below:
image

A fork to an organization account was created from the "dev" branch of that mirrored repository, still under the same username:
image

Now, if I am in the `TEST_ORG/axmol` fork, and I try to create a new pull request for the purpose of synchronising the fork with the latest changes from the upstream, I no longer see the upstream branch listed in the "merge into" and "pull from" drop-down lists:

image

In v1.19.1, it would have displayed the upstream "testuser/axmol:dev" as an option.  Once Gitea was updated to v1.19.3, it no longer shows the upstream link.

Is this a bug, or is there some setting that I need to change to get this working?

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/rh101/8912193d230f8f89a9cc6437620f8795

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Running Gitea in Docker, from https://registry.hub.docker.com/r/gitea/gitea

### Database

PostgreSQL

### LINKED ISSUE #26193: Unable to Create Pull Request in Forked Repo
### Description

Unable to test this on the demo site since you can't create orgs on it.

I have an organization on my Gitea (Bitwarden) which as the server repo which is a mirror of the repo on GitHub.  I have forked that repo to my user and that's where I create modified branches and things to test with.  Before I go to create a new modified branch I create a new pull request to pull changes in from the mirror to my fork... With 1.20.1 this is broken and only lets me pull changes from the repo into itself (and doesn't let me choose the source repo that the repo was forked from).

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Broken Pull Request

### Git Version

2.40.1

### Operating System

Ubuntu 18.04.6 LTS

### How are you running Gitea?

Binary download from release ran as a service with systemd.

### Database

MySQL

### LINKED ISSUE #26781: Derived repo cannot be merged with original repo
### Description

Unable to find a branch of the original Repository in the derived Repository, But this feature is normal in v1.17.4。

image

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I run gitea through the Docker container，The command is as follows。

docker-compose.yaml 

```yaml
version: '3'
services:
  gitea:
    image: 'gitea/gitea:1.20.3'
    container_name: dev_gitea
    hostname: "dev_gitea"
    ports:
      - '8030:3000'
      - '8022:22'
    volumes:
      - /data/gitea:/data
      - /etc/localtime:/etc/localtime:ro
    links:
      - mysql
    depends_on:
      - mysql
    user: root
    privileged: true
    restart: always
```

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #26785 by @CaiCandong

## Description 
Sometimes, we need to use an upstream mirror repository to update the current development repository, but mirror repositories are prohibited from PR. It should not appear in `merge to,` but it can appear in `pull from.`
Fix #24585 
Fix #26193 
Fix #26781
Related #24183

Many thanks to @apnote  for assisting me in reproducing this bug!

## ScreenShot
---

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
What happened to the diff? 🤔

**Comment by wxiaoguang** [comment]
GitHub's bug, it makes GiteaBot creates duplicate PRs.

**Review by puni9869 — APPROVED** [review]
image

But approving

**Comment by wxiaoguang** [comment]
No, do not merge. The backport has been merged.

**Pull request closed without merging**
