### PR TITLE
Bug fixes for repo permissions in API

### PR DESCRIPTION
**Pull request by ethantkoenig**
Correct repo permissions for the following API endpoints:
- `GET /users/:username/starred`
- `GET /user/starred`
- `GET /repos/:username/:reponame/`
- `GET /repositories/:id`

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by bkcsoft** [comment]
Maybe we should have `APIFormat` take a `models.AccessModel` instead and put the logic in there?

**Comment by ethantkoenig** [comment]
Updated based on @bkcsoft's suggestion

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
