### PR TITLE
Make bindata.go optional, remove from repository

### LINKED ISSUE #77: Externalize bindata.go to an auto-generated file
I think `bindata.go` dont have to be committed on repository and must be auto-generated during the make process.

It become a mess when two (or more) Pull Requests update different files (eg : app.ini for the first commit and add new files for the second) because the `bindata.go` file cause merge error each time.

### PR DESCRIPTION
**Pull request by strk**
By default will read assets from filesystems, but can embed them
by passing the "bindata" build tag (go build -tags bindata)

Fixes #77

### CODE REVIEW

**Comment by strk** [comment]
TODO:
- [x] Cache read files and directories
- [ ] Check if filenames need or not be canonicalized (moot point, I dubt anyone develops on windows)

**Comment by strk** [comment]
@tboerger if you're ahead of this feel free to discard it, or help is welcome :)

**Comment by tboerger** [comment]
I already said that I'm working on that...

**Comment by strk** [comment]
Will it show up in #74, then ?

**Comment by strk** [comment]
Caching was pushed, ready for review (or test if anyone is really on Windows)

**Comment by tboerger** [comment]
I would close that in favor of the ongoing work done by me as already asked in https://github.com/go-gitea/gitea/pull/78#issuecomment-258603679

**Pull request closed without merging**
