### PR TITLE
Add 1.5.0 changelog

### PR DESCRIPTION
**Pull request by techknowlogick**
As title

### CODE REVIEW

**Comment by lafriks** [comment]
@techknowlogick please target release/v1.5 first

**Review by sapk — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lafriks please see #4662 for targetting of other branch

**Comment by techknowlogick** [comment]
Blocking this PR until 1.5.0 is released.

**Comment by sapk** [comment]
@techknowlogick go go go :smile:

**Comment by techknowlogick** [comment]
Now that 1.5.0 has been released, this PR is no longer blocked.

**Review by 0rzech — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Pull request merged**
