### PR TITLE
Update npm package dependencies

### PR DESCRIPTION
**Pull request by stanthetiger**
Update npm package dependencies to the latest.
Keeping vue-loader the same at 15.9.7.
Needed to modify webpack.config.js to get css-loader 6.2.0 working - see [css-loader CHANGELOG](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by lafriks** [comment]
fronted check fails

**Comment by silverwind** [comment]
There is more work to be done here, like new eslint rule additions, svg rebuild, eslint rule additions, lint error fixes and possibly more stuff based on the changelogs of the affected modules. I can probably follow up with a more complete PR soon.

**Comment by stanthetiger** [comment]
I am unable to get eslint to resolve path to module 'monaco-editor'  (import/no-unresolved) in features/codeeditor.js

**Comment by silverwind** [comment]
I guess the ESM exports of `monaco-editor` may have changed or something, I can't find anything in the changelog thought.

**Comment by silverwind** [comment]
PR that should solve everything: https://github.com/go-gitea/gitea/pull/16708

**Pull request closed without merging**
