### PR TITLE
Update xorm

### PR DESCRIPTION
**Pull request by KN4CK3R**
Noticed in #25613 that the new xorm version does work with Gitea. Created this PR to keep the other one clean.

The method with the error is `models/unittest.GetCount` changed in #24963. This method generates a query like
```sql
SELECT  count(*) FROM "gtestschema"."user" WHERE (type = 0) ORDER BY id
```
which is invalid for pgsql and mssql:
`ERROR: column "user.id" must appear in the GROUP BY clause or be used in an aggregate function`
The error message is a bit strange but for `COUNT` the order should be irrelevant.
The old xorm version generates the query without `ORDER BY`
```sql
SELECT count(*) FROM "gtestschema"."user" WHERE (type = 0)
```

@lunny fyi

### CODE REVIEW

**Comment by lunny** [comment]
Yes. It's a break change of xorm new version. Previously, count with order by will ignore the `order by`  statement automatically. But the new xorm version will not ignore it automatically. Users should handle themselves.

For Gitea, when do count, order by should not be appended.

**Comment by lunny** [comment]
Should I revert back the change to ignore order by when it's counting?

**Comment by KN4CK3R** [comment]
No, I think it's fine if we need to write correct queries. But how does it work with `FindAndCount`. The find part should use the order and the count part should not. If xorm does ignore it in this case it's inconsistent handling which may be bad too.

**Comment by lunny** [comment]
> No, I think it's fine if we need to write correct queries. But how does it work with `FindAndCount`. The find part should use the order and the count part should not. If xorm does ignore it in this case it's inconsistent handling which may be bad too.

Yes, I have thought of that. And that's why I think maybe it's need to be reverted to original logic.

**Comment by KN4CK3R** [comment]
Yes, then the old logic may be better.

**Comment by lunny** [comment]
https://gitea.com/xorm/xorm/pulls/2307 merged.

**Comment by KN4CK3R** [comment]
Seems worse now?

**Comment by lunny** [comment]
> Seems worse now?

I found this is a bug of Gitea's test because Gitea use an empty string as `OrderBy`'s parameter.

**Comment by lunny** [comment]
This could be replaced by #26128

**Pull request closed without merging**
