### PR TITLE
Add autolinking extension for issue MD

### PR DESCRIPTION
**Pull request by svarlamov**
Signed-off-by: Sasha Varlamov <sasha@sashavarlamov.com>

Targeting: #3095

### CODE REVIEW

**Comment by svarlamov** [comment]
I see that the built-in autolink is breaking the custom parsing... Should we copy-paste the auto-link algo into the Gitea link func?

**Comment by andrew-boyarshin** [comment]
@svarlamov I didn't remove _AUTOLINK_ extension for nothing in #186. It broke things. So instead a frontend is now responsible for calling ```$(...).autolink()``` function. If you discover a way to fix autolinking without corrupting DOM on server _and_ without doing sth monstrous like DOM tree parsing in Go, it would be very welcome.

**Comment by svarlamov** [comment]
@andrew-boyarshin Thank you for pointing out the reasoning behind this... I see that it's happening client-side now... I haven't looked into the autolink function of `blackfriday` yet, so I will start there. If that's too big, then I think that there might be a simpler client-side fix -- something jquery-based

**Comment by lunny** [comment]
This should be closed by #3354

**Pull request closed without merging**
