### PR TITLE
Enforce token on api routes [fixed critical security issue #4357]

### PR DESCRIPTION
**Pull request by beeonthego**
Check and make sure an authentication has been made using token or basic auth in reqToken handler.

When a user logs into Drone using gitea password, the current integration with Drone depends on basic auth to authenticate a Gitea user and fetches/creates an access token with the name drone. So this PR treats a valid basic auth header as the equivalent of api token, in order for Drone integration continue to work.

The user dashboard uses a few API routes for searching user/repo. All these requests use GET methods, and return results depending on whether the user has signed in, including token and other methods. These routes do not use reqToken handler, and will continue to work as they are now.

Please review and comment if changes are required. It is highly appreciated if it can be merged soon to have API routes covered.

### CODE REVIEW

**Review by lunny — CHANGES_REQUESTED** [review]
I don't think it's necessary.

**Comment by beeonthego** [comment]
@lunny yes I agree the first expression can be removed. the result is the same.

the logic in the current test suites needs review and change, otherwise this pr won't pass all tests. 

In fact when token is enforced, some tests should be added to make sure cookie can not access protected api routes.

**Comment by techknowlogick** [comment]
From a preliminary review this looks good, however now a lot of the tests fail, and the GPG test has a panic

Edit: From posting this, I now see the post above mine. Sadly this won't be merged unless the tests pass (as the GitHub policies that are set up disable the button)

**Comment by beeonthego** [comment]
Can someone review the access policy and test suite, prepare and merge a PR so a token is enforced in API routes? This issue has been around for a long time now, and the fix is easy. I don't want to waste time on test suites, if the maintainers eventually decide "no, we will keep things as they are now".

**Comment by techknowlogick** [comment]
I'm a maintainer and can promise you that Cezar97's reports will always be something that I listen to. 

Speaking of being a maintainer, I have the ability to push to your branch, I can work on the tests, however I like to ask permission before I make changes to someones branch, so is it ok if I work on your branch to resolve these failing tests?

**Comment by beeonthego** [comment]
@techknowlogick  I think all maintainers can already make changes to the forked branch as I have enabled "Allow edits from maintainers". Please let me know if any action is required from me. thank you.

**Comment by techknowlogick** [comment]
Aha! Fixed one test, and the pattern is in place for resolving the other tests. Sorry for all of the commits. I'm on mobile and can't compile code locally so you see all of my changes. Will continue to go one by one.

**Comment by techknowlogick** [comment]
🎉 Woooo! Tests now pass!

(again, I'm so sorry for all of the commits, I'm still on mobile and am using the web editor which is extra difficult because it doesn't exist in mobile version of GitHub)

**Comment by beeonthego** [comment]
@techknowlogick Thank you for the hard work! I don't mind the commit emails at all. These serve as time sheets to show you have spent 6 hours debugging and fixing the tests. Well done. Highly appreciated.

**Review by lunny — CHANGES_REQUESTED** [review]
Some ajax requests on the UI used `/api/v1/**`, some page and feature will be broken if this PR merged. refs:
https://github.com/go-gitea/gitea/blob/master/public/js/index.js#L1459
https://github.com/go-gitea/gitea/blob/master/public/js/index.js#L1486
https://github.com/go-gitea/gitea/blob/master/public/js/index.js#L2087
https://github.com/go-gitea/gitea/blob/master/public/js/index.js#L2507
https://github.com/go-gitea/gitea/blob/master/public/js/index.js#L2630
That routes have to be replaced before this PR merged.

**Comment by techknowlogick** [comment]
@beeonthego oh my, I didn't even realize that was the amount of time I spent 😬 I would've been faster if only I wasn't on mobile.

**Review by lunny — APPROVED** [review]
@beeonthego that makes sense.

**Comment by beeonthego** [comment]
@techknowlogick It took me hours to trace functions in different modules, search the JavaScript to see the potential impact, and finally come up with 3 lines of code. Time goes by faster in front of screens, big or small. Thank you for the hard work on the tests. We now have one less thing to worry about. Cheers!

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@techknowlogick @beeonthego new test needs to get updated too, is good otherwise

**Comment by beeonthego** [comment]
@techknowlogick could you backport it to release/v1.5? thank you.

**Pull request merged**
