### PR TITLE
Return 409 when creating repo if it already exists.

### LINKED ISSUE #6329: Incosistency when Repo already exists between create/migrate
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/d7542bfde3e46b5b11d2296e69f86a0e32ce9565
- Git version: 1.7.4
- Operating system: any
- Database: any
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
There is an incosistency between handling an RepoAlreadyExists error between migrating a repo and creating a fresh one:
- [migrating repo](https://github.com/go-gitea/gitea/blob/7afe81f28e530c1c5aed1583654b3d772c368fa5/routers/api/v1/repo/repo.go#L412)
- [creating fresh repo](https://github.com/go-gitea/gitea/blob/7afe81f28e530c1c5aed1583654b3d772c368fa5/routers/api/v1/repo/repo.go#L232)

I think the migrating repo error response  (`409 Conflict`, `The repository with the same name already exists.`) should be used in both cases.

### PR DESCRIPTION
**Pull request by bogdanpetrea**
fixes #6329

### CODE REVIEW

**Comment by lafriks** [comment]
Moving this to 1.8 as this is more big thant enhancement

**Comment by bogdanpetrea** [comment]
It seems that currently the tests fail with a 500 error, because of an uncaught `UNIQUE constraint failed: repository.owner_id, repository.lower_name` error. Any clue on why it isn't transformed into a `ErrRepoAlreadyExist`?

**Comment by zeripath** [comment]
This is likely happening because user id 2's repo2 doesn't actually exist on the filesystem. 

If you look at isRepositoryExist():

https://github.com/go-gitea/gitea/blob/master/models/repo.go#L1284

It checks whether the repo is actually extant on the system, and I suspect that repo2 is one of the original test-fixtures so won't have a filesystem representation.

**Comment by bogdanpetrea** [comment]
Thanks for clarifying @zeripath!
Maybe `isRepositoryExist` could be split into a function with a similar name that checks if the model exists and another `isRepositoryReady` or similar, that checks if the repo is present on the filesystem. In this way there would be a clear distinction between the 2 situations and the error could be handled better.

**Comment by zeripath** [comment]
I agree.

**Comment by zeripath** [comment]
Anyway in this case you should just change your test to actually attempt to create the same repo twice rather than rely on an already "created" repo.

If the provided test environment is too simple for that - copy the style in test_git.go

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
