### PR TITLE
show warning on navigation if currently editing comment or title

### LINKED ISSUE #32223: Changes lost when updating title or comment and navigating
### Description

When adding a new comment for an issue, the browser navigation is blocked with a warning that changes will be lost.

This warning does not occur when editing issue titles or when editing an existing comment.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

None

### PR DESCRIPTION
**Pull request by TimsDevCorner**
This PR fixes the issue https://github.com/go-gitea/gitea/issues/32223

With this little event handler, I'm forcing the browser to show the popup, as it does with normal forms.

image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I think we only need to change the parent "div form" to a real "<form ...>" and use existing `areYouSure`, it is more consistent and no need to manually handle these events.

**Comment by TimsDevCorner** [comment]
I've replaced the custom logic with the `areYouSure` jquery plugin. Apparently the input element needs an "name" tag to function properly.

There is still a bug though. If you click "cancel", the form is still marked as dirty. This leads to the warning on page leave.

**Comment by wxiaoguang** [comment]
> There is still a bug though. If you click "cancel", the form is still marked as dirty. This leads to the warning on page leave.

No worry, I will fix it

**Comment by TimsDevCorner** [comment]
So you are taking over the PR?

I've got 2 ideas:
* Remove `dirty` class once "cancel" is clicked. But this doesn't feel right.
* Update the text to the original once "cancel" is clicked.

**Comment by wxiaoguang** [comment]
> So you are taking over the PR?

I will make some improvements in this PR, just a moment.

**Comment by wxiaoguang** [comment]
Does 74f80d471b44b5bdb4a7e000629d7f65e71b0b4c work for you?

The idea is to use an "ignore-dirty" class (we already used at in other places)

**Comment by wxiaoguang** [comment]
Hmm, I can see an easier solution without playing with the "ignore-dirty" class, we could just check whether the form is hidden. Will try it to see whether it could make the code clearer.

**Comment by TimsDevCorner** [comment]
Your changes are looking very decent.
Thank you very much for your input. And the fast response time as well.

Feel free to rebase and clean up the commit history.

Let me know, once you are ready.
Then I can remove the draft status.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Feel free to rebase and clean up the commit history.

(Oh by the way, no need to rebase or squash in a PR, the final merge (to main branch) will do a square merge to have a clear commit history 😄 )

**Comment by TimsDevCorner** [comment]
Yeah, I wrote a really big issue and then refreshed. Aaaand pooooof, everything was gone. 😆

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Need a follow up fix:  Fix areYouSure confirm #32941

**Pull request merged**
