### PR TITLE
Replace code fold icons with octicons

### PR DESCRIPTION
**Pull request by silverwind**
- replace font-awesome icons with octicons
- clean up js and css surrounding the code expansion and file folding
- fix hover color on arc-green

before:

image

after:

image

`blob_excerpt.tmpl` was re-indented, so best viewed with whitespace hidden in the diff.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by silverwind** [comment]
One more tweak pushed, bg hover effect on the fold buttons:

image
image

Also fixed background on fold line in gitea theme which was reddish for some reason.

**Comment by silverwind** [comment]
Doing a few more color tweaks, don't merge yet.

**Comment by silverwind** [comment]
Line number column colors tweaked and also incread vertical padding on fold line a bit:

image

image

**Comment by silverwind** [comment]
Should be good to go now.

**Comment by lafriks** [comment]
Please resolve conflicts

**Comment by silverwind** [comment]
rebased

**Comment by lafriks** [comment]
:rocket:

**Pull request merged**
