### PR TITLE
Temporarily disable PATs until next release

### PR DESCRIPTION
**Pull request by kdumontnu**
This might be a bit contentious, but I think we should try to limit the impact of deprecating scoped PATs with the rewrite proposed here we're working on for v1.20: https://github.com/go-gitea/gitea/issues/24501

We should have a PR opened shortly to re-scope the routes.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
So, I can see two options after this PR:
1. The replacement PR is merged in time.
2. The replacement PR is not merged in time, and this PR will be reverted.

Another thing to note is that handling the already existing scoped PATs will be absolutely horrifying.

**Comment by kdumontnu** [comment]
> So, I can see two options after this PR:
> 
> 1. The replacement PR is merged in time.
> 2. The replacement PR is not merged in time, and this PR will be reverted.
> 
> Another thing to note is that handling the already existing scoped PATs will be absolutely horrifying.

Well, we have a few options:
- Migrate existing scoped PATs to new ones (kind of annoying)
- Backport this to 1.19.3 and announce a breaking change, then reject all of the old scope tokens in 1.20 (so that users have to regenerate them)

**Comment by delvh** [comment]
> Backport this to 1.19.3 and announce a breaking change, then reject all of the old scope tokens in 1.20 (so that users have to regenerate them)

I don't see this as a viable option.
That is a **huge** violation of semver, for an outcome that is not yet known.

> Migrate existing scoped PATs to new ones (kind of annoying)

I know, but I see that as the only viable option here.

**Comment by techknowlogick** [comment]
Throwing a breaking label on this PR so it gets reviewed again when writing the next blog post in case the proposed solution above doesn't come about in time.

**Comment by delvh** [comment]
Looks like we'll be able to get the new design merged, hence removing the breaking label.

**Pull request merged**
