### PR TITLE
Use offline mode by default

### PR DESCRIPTION
**Pull request by strk**
Includes explicit disabling of gravatar plus change of avatar
defaults to libravatar when gravatar is enabled again and offline
mode is disabled.

See also #415

### CODE REVIEW

**Comment by lunny** [comment]
```Go
DisableGravatar = sec.Key("DISABLE_GRAVATAR").MustBool()
EnableFederatedAvatar = sec.Key("ENABLE_FEDERATED_AVATAR").MustBool()
if OfflineMode {
	DisableGravatar = true
	EnableFederatedAvatar = false
}
if DisableGravatar {
	EnableFederatedAvatar = false
}
```
If OfflineMode == false and DisableGravatar == true, it's also disabled.

**Comment by tboerger** [comment]
We already had this discussion, multiple people don't want this default enforcement.

**Comment by strk** [comment]
@lunny right, so the default with this PR is just NOT using any online service for avatar picture.

**Comment by lunny** [comment]
@tboerger This is only a default value. For all my instances, I will always set OFFLINE_MODE = true.

**Comment by tboerger** [comment]
I think the majority of the users should and will use the online mode, so I want to keep it like it is. People that prefer the offline mode like strk can configure it differently.

**Comment by tboerger** [comment]
We have already discussed about that on gitter, strk had been pretty much alone with the opinion on these options.

**Comment by tboerger** [comment]
My vote is to close this PR!
/cc @lunny @bkcsoft

**Comment by lunny** [comment]
^

**Comment by metalmatze** [comment]
Yep. Me too. I'll close because 3 people. Reopen if not.

**Pull request closed without merging**
