### PR TITLE
Allow to add organization members as collaborators on organization owned repositories

### LINKED ISSUE #4507: Proposal: Adding organization members as collaborators on org-owned repos
- Gitea version (or commit ref): v1.5.0-rc1
- Git version: 2.14.2
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description
Trying to add a user which is part of the organization owning a repository as collaborator fails with the message "The user is an organization member who cannot be added as a collaborator.". Would it be possible to allow this (GitHub for example does)? We want to explicitly grant write access to single users without creating new teams.
Code in question is [here](https://github.com/go-gitea/gitea/blob/1bff02de55331e11de3627d5c5628feb2cd97387/routers/repo/setting.go#L393).

## Screenshots
gitea-org-collaborator

### PR DESCRIPTION
**Pull request by adelowo**
Fixes #4507 

Deleted the translation text since I couldn't find it being used elsewhere with `ag "settings.user_is_org_member"`

### CODE REVIEW

**Comment by lafriks** [comment]
Won't there be side effects when checking rights?

**Comment by adelowo** [comment]
I just tried regular pushing via the cli and viewing the repo via the UI.. 
I could run more checks but if you do know of a potential side effect kindly inform me so I can verify

**Comment by adelowo** [comment]
Would update this comment as @lafriks after extensive testing

**Comment by lunny** [comment]
@lafriks Since #5314 has supported permission check for organization member as a collaborator, I think this is meaningful. See https://github.com/go-gitea/gitea/blob/master/models/repo_permission.go#L142 .

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by adelowo** [comment]
Heads up to anyone merging this. Can you kindly verify the deleted translation text is still not being used ?

**Comment by lafriks** [comment]
@adelowo does not seems to

**Pull request merged**
