### PR TITLE
Use tabs in Makefiles

### PR DESCRIPTION
**Pull request by strk**
Needed for producing valid Makefiles

### CODE REVIEW

**Comment by lunny** [comment]
Editorconfig should be a customized config. Every repository could derive the default config and can customize one. I don't know if everyone like 8 indent size.

**Comment by strk** [comment]
I removed the indent size, all that matters is using tab
(the size was more of a test on my side)

**Comment by metalmatze** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
@tboerger I think lgtm should be configed to ignore MAINTAINERS file.
@metalmatze You have to send a PR to add your name in MAINTAINERS file before you can lgtm.

**Comment by tboerger** [comment]
> @tboerger I think lgtm should be configed to ignore MAINTAINERS file.

Than we need to change it within the `.lgtm` config to simething like `NONE`.

**Comment by lunny** [comment]
I send a PR to lgtm project go-gitea/lgtm#2 to ignore the MAINTAINERS file.

**Pull request merged**
