### PR TITLE
Split up monaco's language chunks

### PR DESCRIPTION
**Pull request by silverwind**
This should speed up monaco's loading time by splitting the current 3.71MB chunk monaco.js into 63 individual files named 1 to 63.js in the output directory. There seems to be no way to get a better file naming scheme unfortunately. I opted to exclude those files in the webpack output for brevity.

(This is a exact revival of https://github.com/go-gitea/gitea/pull/12193)

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
Didn't monaco support load by language asynchronize?

**Comment by silverwind** [comment]
Yes it does load async but we inhibited previously by combining the language chunks into one, forcing it to load the big 4MB file. With this change, it will dynamically load the smaller per-languague files and this is also the recommended way.

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Comment by zeripath** [comment]
make lg-tm work already?

**Pull request merged**
