### PR TITLE
Clarify the suffices and prefixes of setting.AppSubURL and setting.AppURL

### PR DESCRIPTION
**Pull request by zeripath**
In more than a couple of places we're slightly confused about whether AppURL and AppSubURL have preceding or trailing slashes.

This PR adds comments to the definition of the setting.App*, removes an old unused setting variable, uses the clarity obtained to simplify several uses of AppURL and AppSubURL and fixes a potential issue with a missing QuoteMeta in regexp.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
setting.AppSubURLDepth has been removed as it is not used.

**Comment by lafriks** [comment]
Imho both appurl and appsuburl should end with `/` otherwise it will still be confusing and inconsistent

**Comment by zeripath** [comment]
The reason that AppSubURL doesn't have a terminal / is because it allows it to be empty when there is no suburl.

That's quite nice actually and leads to very compact relative URLs and easy handling of AppSubURL with relative addresses.

AppURL will have a terminal slash for other similar reasons in that some proxies will likely only proxy the slash terminal address and I suspect that means that it's easier to and simpler to just write AppURL instead of AppURL+"/"

This PRs intention was not change behaviour but rather to clarify what is actually happenin, but if we were to change anything I'd argue we should not have the terminal / on the AppURL.

That would make creating the "relpath" and making the absolute URL the same: clean the path to root it on the AppSubURL then either prefix with suburl or the URL as appropriate.

**Comment by lafriks** [comment]
I would prefer that non of them should have `/` at the end imho this way `AppURL + AppSubURL + /path` is always valid

**Comment by zeripath** [comment]
> I would prefer that non of them should have `/` at the end imho, this way `AppURL + AppSubURL + /path` is always valid

AppURL has to contain the AppSubURL so I think you mean `AppURL + "/path"`.

**Comment by lafriks** [comment]
> > I would prefer that non of them should have `/` at the end imho, this way `AppURL + AppSubURL + /path` is always valid
> 
> AppURL has to contain the AppSubURL so I think you mean `AppURL + "/path"`.

yes, I meant `(AppURL || AppSubURL) + /path` :)

**Comment by zeripath** [comment]
As a (partially relevant) aside:

Do you know if there is ever a reason for Gitea to be producing non-FQDN urls that point outside of its own root? My suspicion is that there is not and that there should not be.

**Comment by lafriks** [comment]
I don't know what did you mean by that but there should not be such urls

**Comment by 6543** [comment]
@uli-heller would you like to test now ?

**Comment by uli-heller** [comment]
@6543 : I'll do so but I'm not sure it it will work out today. Still busy @work...

**Review by 6543 — APPROVED** [review]

**Review by noerw — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
