### PR TITLE
Add support for using "libravatar" as the GravatarSource

### PR DESCRIPTION
**Pull request by strk**
Just to make it easier for administrator to configure libre avatar,
as it is done for "duoshuo" and "gravatar"

NOTE: I'd actually make it the default, but will keep that for
a separate PR to reduce eventual conflicts

### CODE REVIEW

**Comment by bkcsoft** [comment]
LGTM, though preferably i'd move this to a config-file in the future.

**Comment by andreynering** [comment]
LGTM

**Comment by tboerger** [comment]
@andreynering you merged a PR that have been flagged as `1.1.0` target...

**Comment by andreynering** [comment]
Ouch, sorry. :sweat: We can revert it, should we?

**Comment by lunny** [comment]
Let it be :)

**Pull request merged**
