### PR TITLE
API Endpoints for forks

### PR DESCRIPTION
**Pull request by ethantkoenig**
Adds the following endpoints:
- `GET /repos/:user/:repo/forks`: List a repository's fork
- `POST /repos/:user/:repo/forks`: Fork a repository

See also https://github.com/go-gitea/go-sdk/pull/30

### CODE REVIEW

**Comment by lunny** [comment]
It seems this pr will resolve #477

**Comment by lunny** [comment]
You have to `govendor update code.gitea.io/sdk` and not directly change the codes under `vendor/`

**Comment by ethantkoenig** [comment]
@lunny Sorry, was waiting for https://github.com/go-gitea/go-sdk/pull/30 to get merged. Fixed.

**Comment by bkcsoft** [comment]
@ethantkoenig still missing the `vendor/vendor.json`-file :)

**Comment by ethantkoenig** [comment]
@lunny @bkcsoft `vendor/vendor.json` updated.

**Comment by bkcsoft** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
