### PR TITLE
Add support for client basic auth for exchanging access tokens

### PR DESCRIPTION
**Pull request by jonasfranz**
Adds support for basic auth for exchanging access tokens. This is important since golang's oauth2 library requires that.

https://tools.ietf.org/html/rfc6749#section-2.3.1

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Test seems to fail with empty client id

**Review by zeripath — APPROVED** [review]

**Comment by gsantner** [comment]
@jonasfranz  / @zeripath 
Hey!
I'm running the daily version git-ca46385, tried to backup, but can't due missing tables.
Guess theres DB migration missing or like that?

```
gitea dump -c ~/gitea/custom/conf/app.ini 
2019/03/19 17:06:11 Creating tmp work dir: /tmp/gitea-dump-640591686
2019/03/19 17:06:11 Packing dump files...
2019/03/19 17:06:11 Dumping local repositories.../home/git/gitea/data/repositories
2019/03/19 17:07:39 Dumping database...
2019/03/19 17:07:40 Failed to dump database: Error 1146: Table 'gitea.o_auth2_application' doesn't exist
```

**Comment by jolheiser** [comment]
Just a note for whoever looks at this, since I don't know enough about Xorm's backend. 
The `OAuth2Application` struct is stored as `oauth2_application` which is why it can't find `o_auth2_application` when dumping. 

https://github.com/go-gitea/gitea/blob/e777c6bdc6f12f9152335f8bfd66b956aedc9957/models/oauth2_application.go#L43-L46

**Comment by jonasfranz** [comment]
That's not caused by this pull request. Please open up a new issue to better manage the bug.

**Comment by gsantner** [comment]
https://github.com/go-gitea/gitea/pull/6385 / https://github.com/go-gitea/gitea/issues/6310

**Pull request merged**
