### PR TITLE
Switch to non-deprecation setting

### PR DESCRIPTION
**Pull request by Gusted**
- Avoid by-default: "Deprecated fallback `[server]` `LFS_CONTENT_PATH` present. Use `[lfs]` `PATH` instead. This fallback will be removed in v1.18.0"

### CODE REVIEW

**Comment by wxiaoguang** [comment]
The `app.example.ini` should also be updated. I can not find `lfs.PATH` there.

**Comment by zeripath** [comment]
Actually could we just migrate all of these LFS settings to `[lfs]`?

**Comment by Gusted** [comment]
> Actually could we just migrate all of these LFS settings to `[lfs]`?
> 
> (LFS_JWT_SECRET - might need to stay where it is though - I think that needs to migrate to `[secrets]`)

Deprecate the current settings (like we do with `LFS_CONTENT_PATH`)?

**Comment by zeripath** [comment]
I guess for the fallback deprecation probably needs to be for 1.19 removal.

**Review by zeripath — APPROVED** [review]

**Comment by Gusted** [comment]
FYI: the Chinese config cheat sheet doesn't have a deprecation notice for the `LFS_CONTENT_PATH` key, the English one does.

**Comment by lunny** [comment]
> LFS_CONTENT_PATH

#18326

**Comment by wxiaoguang** [comment]
Hmm ... GitHub auto closes this one ..... nvm

**Review by wxiaoguang — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
