### PR TITLE
Fix integration test after librejs location change

### LINKED ISSUE #2373: Build failes since moving vendor dir files
Regression from https://github.com/go-gitea/gitea/pull/2241

Integration test `TestLinksNoLogin` failes because of 404 from `librejs.html`

### PR DESCRIPTION
**Pull request by strk**
Fixes #2373

### CODE REVIEW

**Comment by MTecknology** [comment]
Follow up: PR #2375

**Comment by ethantkoenig** [comment]
LGTM

**Comment by ethantkoenig** [comment]
@strk You may want to rebase to rerun drone?

**Comment by MTecknology** [comment]
@ethantkoenig It's not possible for tests to pass until #2375 is merged. If there are additional issues, I would like to address them in that PR.

**Comment by lafriks** [comment]
LGTM but next time please fix the tests in same PR that breaks them

**Comment by MTecknology** [comment]
@lafriks Absolutely, I will.

**Comment by strk** [comment]
On August 24, 2017 8:07:28 AM CEST, Michael Lustfield <notifications@github.com> wrote:
>@lafriks Absolutely, I will.

Tests *did* pass in the PR, as far as I can tell. Was this  a merge introduced issue ?
--strk;

Sent from hand-held device, sorry for brevity

**Pull request merged**
