### PR TITLE
Use Go 1.21 for golangci-lint

### PR DESCRIPTION
**Pull request by harryzcy**

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by puni9869** [comment]
Please update at other places also.
image

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
> Please update at other places also. Means whole CI should run on 1.21 version other wise we will face failures. image

At least `gitea/test_env` does not have a 1.21 tag yet: 

https://hub.docker.com/r/gitea/test_env/tags
https://gitea.com/gitea/test-env

**Comment by silverwind** [comment]
As the future of `test_env` is uncertain (we don't need it any more with actions), I'l fine to merge this as-is now.

**Comment by harryzcy** [comment]
Somehow the tests didn't caught a deprecation error, but running `golangci-lint` locally gives me:

```
models/migrations/v1_16/v210.go:132:23: SA1019: elliptic.Marshal has been deprecated since Go 1.21: for ECDH, use the crypto/ecdh package. This function returns an encoding equivalent to that of PublicKey.Bytes in crypto/ecdh. (staticcheck)
                                        PublicKey:       elliptic.Marshal(elliptic.P256(), parsed.PubKey.X, parsed.PubKey.Y),
```

The `crypto/ecdh` package was added in Go 1.20, and the old API is deprecated in Go 1.21.
But also Gitea v1.16 was released long ago. Do we still want to make this change?

**Comment by silverwind** [comment]
That would require us to bump minimum go version to 1.21 it seems. I think we can do this on `main` branch sometimes next week once the `release/v1.21` branch is cut.

Also, wonder why the deprecation did not catch earlier. Ideally we should probably update `go.mod` and `.golangci.yaml` only in-sync.

**Comment by harryzcy** [comment]
As of 1.21, the version in go.mod becomes the strict minimum requirement, so it will always lag everywhere else by 1 minor version.

> To improve forwards compatibility, Go 1.21 now reads the go line in a go.work or go.mod file as a strict minimum requirement: go 1.21.0 means that the workspace or module cannot be used with Go 1.20 or with Go 1.21rc1.

**Comment by silverwind** [comment]
Found the bug in our actions setup, which is why this did not run the linter:

https://github.com/go-gitea/gitea/pull/26799

Afraid we might have to revert this because now we should have a lint failure on `main` branch because of it.

**Comment by harryzcy** [comment]
I think fixing it now may still be fine, since `crypto/ecdh` is added in 1.20. As long as we don't need to support 1.19, the code should also compile.

**Comment by silverwind** [comment]
Ah, yes in that case we can keep 1.20 minimum. I thought it was only available with 1.21.

**Comment by silverwind** [comment]
@harryzcy could you raise a PR that fixes the deprecation on main branch?

**Comment by harryzcy** [comment]
> @harryzcy could you raise a PR that fixes the deprecation on main branch?

Done in #26800

**Pull request merged**
