### PR TITLE
Improve migrate page and add card CSS

### PR DESCRIPTION
**Pull request by silverwind**
- Use original gitea logo on migrate page
- Add card styles and map colors to css vars
- Tweak migrate page, adding hover effect to cards

Screen Shot 2020-11-29 at 21 51 42
Screen Shot 2020-11-29 at 21 51 33

### CODE REVIEW

**Comment by 6543** [comment]
@silverwind I think the wihte in the middle of gitea logo should be transparent, that's why I mainly did not use the original logo.
It just looks better on dark themes ... - any idear how to get same effect with original svg file?

**Comment by silverwind** [comment]
Actually, the non-white center is what got me to replacing the log. I think white parts of logos should stay white in dark themes.

**Comment by 6543** [comment]
I'm realy not a fain of white-center ... I wont block the refactor - but in my opinion, would not change the logo

**Comment by silverwind** [comment]
Happy with refactors already :)

**Comment by lunny** [comment]
> Actually, the non-white center is what got me to replacing the logo. I think white parts of logos should stay white in dark themes and it's also consistent with the page logo/favicon.

It's not consistent with other logos, both git and github has a transparent but gitea log doesn't.

**Comment by techknowlogick** [comment]
> It's not consistent with other logos, both git and github has a transparent but gitea log doesn't.

It makes our use of the logo consistent. Our logo in the upper left has the teabag filled in.

**Comment by silverwind** [comment]
I guess after a certain degree of "internal complexitity" of a logo, it's warrented to fill that part white as it's not meant to be seen as transparent. Maybe it's just a personal preference of some that those parts are white but I've been getting used to it.

**Review by mrsdizzie — APPROVED** [review]
Makes sense to me -- the white is a teabag string and card which are actually white and supposed to be on the outside of the cup. Other logos are not really based so directly off of real world objects.

**Comment by silverwind** [comment]
Rebased. @6543 maybe you want to reconsider?

**Comment by 6543** [comment]
yes LGTM for the JS & CSS

**Comment by 6543** [comment]
@silverwind conflicts ocure :/

**Comment by silverwind** [comment]
Rebased.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
