### PR TITLE
Update eslint config

### PR DESCRIPTION
**Pull request by silverwind**
- Remove unneeded `Tribute` global
- Separate globals for Node and Browser environments
- Update environment to [`es2020`](https://eslint.org/docs/user-guide/configuring#specifying-environments) to enable new globals like `BigInt`

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by CirnoT** [comment]
How does ES2020 affect our browser support?

**Comment by silverwind** [comment]
We already have language features at 2020 via `ecmaFeatures`, this just enables the new globals for them as well.

Babel should cover most cases except unpolyfillable stuff like BigInt literals (which of course we should not use yet).

**Comment by CirnoT** [comment]
In that case, shouldn't we enforce the 'should not use yet' policy with eslint config?

**Comment by silverwind** [comment]
It's not so easy as eslint does not really know which features can be polyfilled and which not. BigInt global can be polyfilled (enabled via env) but BigInt literal can not (as it's new syntax). I guess we will spot such cases during PRs I guess.

**Review by techknowlogick — APPROVED** [review]

**Review by CirnoT — APPROVED** [review]

**Comment by lafriks** [comment]
🚀

**Pull request merged**
