### PR TITLE
Standardize Co-Authored-By / Reviewed-By strings

### PR DESCRIPTION
**Pull request by CirnoT**
Make sure all these strings use same capitalization style.

- [x] Co-Authored-By -> Co-authored-by
- [x] Reviewed-By -> Reviewed-by

### CODE REVIEW

**Comment by CirnoT** [comment]
On unrelated note, we should perform check against noreply email to avoid situation where `Co-Authored-By` is inserted twice for same user, once from commits with email exposed and once with noreply variant when merging from UI (if user selected to hide email)

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
But it seems Github use `Co-authored-by` but not `Co-Authored-By`.

**Comment by CirnoT** [comment]
There seems to be both usages happening in the wild. Either one is fine with me, so long it's consistent across all places.

**Comment by silverwind** [comment]
Seems the lowercase variant is more common as far as git itself is concerned:

https://github.com/git/git/search?q=Reviewed-By&type=code

**Comment by CirnoT** [comment]
Switch to lowercase variant

**Review by lunny — APPROVED** [review]

**Pull request merged**
