### PR TITLE
Add support for database schema in PostgreSQL

### LINKED ISSUE #5152: gitea does not start - can not find public schema
- Gitea version: 1.5.2 (docker)
- Git version: 2.19.1
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant

Hello, I have multiple instances for gitea. Every installation should use one big postgres database with his own schema. 

So I create for one instance his own schema and username and changed the search_path to disable querying statements to the public schema, because I don't want, that any application or instance create his schema into public.

Here my psql statements
```sql
CREATE SCHEMA gitea;
CREATE ROLE gitea WITH LOGIN;
ALTER USE gitea SET search_path=gitea;
GRANT ALL ON SCHEMA gitea to gitea;
```

After installation gitea does not start and I get in my logs every time the same error.
```bash
root@vgttp:/srv/docker/gitea_01/data/gitea/log# tailf xorm.log
2018/10/23 20:37:33 [I] PING DATABASE postgres
2018/10/23 20:37:33 [I] [SQL] SELECT tablename FROM pg_tables WHERE schemaname = $1 AND tablename = $2 []interface {}{"public", "version"}
2018/10/23 20:37:33 [I] [SQL] CREATE TABLE IF NOT EXISTS "version" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "version" BIGINT NULL)
2018/10/23 20:37:33 [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [public version id]
2018/10/23 20:37:33 [I] [SQL] ALTER TABLE "version" ADD "id" BIGSERIAL PRIMARY KEY  NOT NULL ;
```

Gitea look in the public schema? I have installed the instance into his own schema! How can I change in my docker-compose or app.ini the schema name?

Volker

### PR DESCRIPTION
**Pull request by guillep2k**
Fixes #5152 

Currently Gitea does not support using a database schema different from the default "public". With this PR, a schema different from the default can be specified in `app.ini` and during install.

### CODE REVIEW

**Comment by lafriks** [comment]
Does this also update x.Exec queries?

**Comment by guillep2k** [comment]
> 
> 
> Does this also update x.Exec queries?

I've installed Gitea from scratch in a database with no permissions on `public` for the `gitea` user and no query failed on me -and there's plenty of those-, but I'll check tonight and document a few cases here.

**Review by zeripath — APPROVED** [review]

**Comment by guillep2k** [comment]
I'm sorry, it turns out that certain operations are problematic. Specifically, those escaping the `user` table get badly escaped:

```
2019/11/04 18:49:28 .../xorm/session_raw.go:81:queryRows() [I] [SQL] SELECT * FROM "schema5152".""user"" INNER JOIN schema5152.issue_assignees ON assigne
e_id = "user".id WHERE (issue_assignees.issue_id = $1) []interface {}{1} - took: 375.802µs
2019/11/04 18:49:28 ...outers/repo/issue.go:581:NewIssuePost() [E] NewIssue: newIssue: pq: zero-length delimited identifier at or near """"
```

Other `Exec()` can be sorted out by running an `ALTER USER SET search_path = schema_name`, but this particular case is apparently not escaped correctly in xorm.

I should have tested thoroughly. 😞 

I'm marking this as WIP.

**Comment by guillep2k** [comment]
Depends on [xorm/xorm#1476](https://gitea.com/xorm/xorm/pulls/1476)

**Comment by lafriks** [comment]
imho setting `ALTER USER SET search_path` defeats purpose of this as primary usecase for this is to be able to use same db for multiple instances/software.

**Comment by guillep2k** [comment]
> 
> 
> imho setting `ALTER USER SET search_path` defeats purpose of this as primary usecase for this is to be able to use same db for multiple instances/software.

@lafriks Mmmm..... I hadn't considered the scenario of many consumers using the the same login. I think Gitea should have its own login (user) and it can share the database with many other logins (users), but with its own schema. Other consumers should have their own logins and credentials.

The bug reported in #5152 talks about the bad practice of having a user's tables in the `public` schema, and I think that's when a single database is shared among different _users_. This PR should at least take care of that, and only the `gitea` user needs the `ALTER USER` statement.

Anyway, I feel that it should be xorm's job to append the schema name to all tables if so configured, even for `Exec()` statements. It doesn't, and that's the current limitation we have. As soon as xorm supports that properly, the `ALTER USER` statement is no longer required as the rest of the job is done.

**Comment by guillep2k** [comment]
> 
> 
> imho setting `ALTER USER SET search_path` defeats purpose of this as primary usecase for this is to be able to use same db for multiple instances/software.

Expanding on this concept, the configuration I think should be used in those cases is:

* A single database (e.g. `development`) for all projects.
* Three Gitea instances (for whatever reason):
    * Gitea1 with Linux user `gitea1`, dbuser `gitea1`, schema `giteaschema1`.
    * Gitea2 with Linux user `gitea2`, dbuser `gitea2`, schema `giteaschema2`.
    * Gitea3 with Linux user `gitea3`, dbuser `gitea3`, schema `giteaschema3`.
* One Bugzilla instance; Linux user `apache`, dbuser `bugzilla`, schema `bugzilla`.
* Other software, you get the idea.

The advantage of this is having all databases backed up at the same point in time, plus better resource sharing. There are disadvantages too, but they don't really matter for this discussion.

**Comment by guillep2k** [comment]
[xorm/xorm#1476](https://gitea.com/xorm/xorm/pulls/1476) has been merged. However, until a new version of xorm (and its companion library `lafriks/xormstore`) are released, this PR will have to wait. :sleeping:

**Comment by techknowlogick** [comment]
A new release of XORM was made (and our go.mod was updated), now just need for update to xormstore.

**Comment by guillep2k** [comment]
> 
> 
> A new release of XORM was made (and our go.mod was updated), now just need for update to xormstore.

Thank you. This PR is not in fact affected by `xormstore`, so I'm removing the WIP flag.

PR ready for review.

**Comment by lunny** [comment]
@guillep2k How about add a test for different schema from `public` on integration test?

**Review by techknowlogick — DISMISSED** [review]
Can you add the schema to the `templates/admin/config.tmpl` page (if db type is postgres)?

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k How about add a test for different schema from `public` on integration test?

@lunny Sorry, I'd rather skip that. If that's important, it will have to wait at least a couple of weeks. I only have a few free minutes a day lately.

**Review by sapk — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
I still think we need some tests.

**Comment by techknowlogick** [comment]
> I still think we need some tests.

In that case I’ve moved this to 1.12

**Comment by guillep2k** [comment]
> 
> 
> I still think we need some tests.

OK, I'll try when I have some time. But for the test to be meaningful we should run the entire integration tests through a different schema (to account for future bugs). So, the options are:

1. Change the schema Gitea uses for the PostgreSQL tests (and never use public for that).
2. Make two different tests: public and alternative, and run them both.

I think (1) is preferable, because it will run only once and we can consider it to be thorough. If any bug slips through (e.g. some case was not accounted for), the `public` schema will simply not be available and the test will fail. (2) means adding more load to our test servers and I don't see a real advantage to it.

**Comment by lunny** [comment]
@guillep2k I'm OK to just use 1) and set `SCHEMA` as a non-public one.

**Comment by guillep2k** [comment]
It turns out that supporting the migration process requires additional changes in xorm. Currently the tests passes if the database is created from scratch, but on migration the `Sync2()` function does some weird juggling with the table names to build the names for the indexes (it's sometimes including the schema name in the index name).

To solve this I've written two more PRs for xorm: [xorm/xorm#1505](https://gitea.com/xorm/xorm/pulls/1505) and [xorm/core#65](https://gitea.com/xorm/core/pulls/65).

We need to wait until those are approved or another solution comes up. 😅

**Comment by lunny** [comment]
both xorm/xorm#1505 and xorm/core#65 merged.

**Comment by guillep2k** [comment]
> 
> 
> both xorm/xorm#1505 and xorm/core#65 merged.

OK, I'll update `go.mod` targeting the latest commit of xorm so we can see how it goes in our CI tests. I have no preference as whether we use a commit or a named version for `go.mod`, but if a named version is preferred, I can update `go.mod` again when `0.8.2` is tagged.

**Comment by guillep2k** [comment]
@lunny Done. Build is passing. Now we have to decide if we want to use a commit ref or a version tag for xorm in `go.mod`.

A note on the tests:

Integration and migration tests use the database dumps from `integrations\migration-test`. Since I've forced the PostgreSQL tests to use the schema `gtestschema` instead of the default `public`, I had to hand-edit all the PostgreSQL dumps and change statements like:

```
DROP INDEX IF EXISTS public."UQE_watch_watch";

CREATE TABLE public.collaboration (
    id bigint NOT NULL,
    repo_id bigint NOT NULL,
    user_id bigint NOT NULL,
    mode integer DEFAULT 2 NOT NULL
);

CREATE SEQUENCE public.access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
```

into

```
DROP INDEX IF EXISTS gtestschema."UQE_watch_watch";

CREATE TABLE gtestschema.collaboration (
    id bigint NOT NULL,
    repo_id bigint NOT NULL,
    user_id bigint NOT NULL,
    mode integer DEFAULT 2 NOT NULL
);

CREATE SEQUENCE gtestschema.access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
```

(notice the change from `public` to `gtestschema`)

This is unavoidable since the tests now expect the data in the `gtestschema` schema.

**Comment by zeripath** [comment]
@guillep2k that seems to imply that the fixtures loading isn't going in to the giteatest schema?

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k that seems to imply that the fixtures loading isn't going in to the giteatest schema?

@zeripath They are, as always. Those are for the unit tests. The db dumps I've changed are used as starting points for the migration and integration tests (I don't know what role the fixtures play in that case, but I changed nothing about them). My only change was using an alternte schema in the case of PGSQL.

**Comment by zeripath** [comment]
They're also used for the integration tests. The migration data should really be dropped after its tests

**Comment by guillep2k** [comment]
> 
> 
> They're also used for the integration tests. The migration data should really be dropped after its tests

I didn't change any behaviour there. I just expanded the gzip files, edited the SQL, changed `public` into `gtestschema` as appropriate, and gzipped again. I just mentioned this because the commit has them as binary, so a line-by-line review is not possible with those files.

The yaml fixtures are not affected by this PR in any way, since those are loaded through the database connection so they inherit the proper enviroment.

**Comment by guillep2k** [comment]
I meant these files:

image

**Comment by zeripath** [comment]
Cool. I just misunderstood what you were saying.

**Review by zeripath — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
