### PR TITLE
Add button to revert SimpleMDE to plain textarea

### PR DESCRIPTION
**Pull request by zeripath**
This will allow android users to switch off the SimpleMDE editor in the review approve/comment/request changes area.

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]
It might be nice to be able to turn it _back_ into an MDE, but other than that LGTM. Can I approve this twice? :joy:

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Would be nice if it would not initialize simplemde if opened from mobile phone with option to enable it manually

**Comment by jolheiser** [comment]
Since this is technically a bug (not being able to easily review on mobile) can it be backported to 1.11? :grin:

**Comment by zeripath** [comment]
make lg-tm work

**Pull request merged**
