### PR TITLE
UI: Fix header menu misalignment

### PR DESCRIPTION
**Pull request by silverwind**
The icons in the '+' menu were misaligned, fixed it by using the same icon classes as on the user menu.

#### Before
screenshot 2019-02-08 at 08 33 34

#### After
screenshot 2019-02-08 at 08 33 22

### CODE REVIEW

**Comment by zeripath** [comment]
I assume this doesn't degrade the mobile view. I'm surprised the fitted was put there.

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Mobile view looks fine:

screenshot 2019-02-08 at 11 18 43

**Comment by lunny** [comment]
CI failed.

**Comment by adelowo** [comment]
Failure seems unrelated to this PR

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
