### PR TITLE
Only show conflicted files if not merged

### LINKED ISSUE #10192: [UI] Dont Display File-Conflicts on merged pulls
gitea version: 1.12.0+dev-251-g d4096ab6a
test url: https://gitea.com/gitea/go-sdk/pulls?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0

Bildschirmfoto zu 2020-02-08 12-40-37

### PR DESCRIPTION
**Pull request by zeripath**
Only show the conflicted files count if the pull request is not merged.

Fixes #10192

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
UI part done ;)

**Comment by zeripath** [comment]
Not sure what's causing the ci failure here certainly not the changes in this pr

**Review by guillep2k — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
Should we send backport to v1.11?

**Comment by 6543** [comment]
I think schowing conflucts is a feature of 1.12?

**Comment by zeripath** [comment]
Yup that's why I put skip-changelog

**Pull request merged**
