### PR TITLE
Add Image Diff for SVG files

### LINKED ISSUE #14329: [Feature Request] SVG Diff
Now that we support svg rendering we should consider adding support for rendered svg diff.

This shows the basic functionality in GitHub.

GH Demo

See [live GitHub example](https://github.com/go-gitea/gitea/commit/f8a668ab0c098476a47b9d96fb061fa31fec78ef?short_path=1cd669c#diff-1cd669c19b2783a59088190552136237bf1c8de6fdaf3f331a27a89bed63054b) (note: GitHub actually seems to have a bug in `swipe` mode when the SVG size has changed it shows both on tope of one-another)

Personally, I find the the onion skin mode to be the least helpful, but the other two modes are quite useful. 

### Request:
 - Like GitHub, we should render the svg diff in PRs and commit diff view
 - Like GitHub, we should have a toggle button to switch between code and render mode
 - Unlike GitHub, the toggle button should be "sticky" between sessions/page-views, so that a user navigating between PR tabs doesn't have to repeatedly toggle the button.
 - Unlike GitHub, the default toggle state should be configurable by either repository, user, or gitea instance

### LINKED ISSUE #15920: Image diff has 0 width/height images
Seems like image diff is currently broken, all images have inline styles with `width: 0; height: 0`. I think the JS calculations go wrong somewhere. Also, I think default view mode should be image diff. 

Example: https://try.gitea.io/silverwind/updates/commit/3d80fab2f8ee1d7bca1b7cff4f242461424866f8

cc: @KN4CK3R

### PR DESCRIPTION
**Pull request by KN4CK3R**
Addition to #14450
Close #14329
Close #15920

Added support for diffing svg images. Since svg images don't need to have a size the bounds are guessed and the display is hidden in this case.

No size info available:
grafik

Size info available:
grafik
grafik

Changes:
- Moved content type sniffing from base in own module which caches the result.
- Moved image size info logic from server to client.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Currently there is no source toggle for SVG images because I want to reuse the logic from #14661 after it gets merged. This will be added in a new PR.

**Comment by zeripath** [comment]
CI fails

**Comment by lunny** [comment]
Please resolve the conflicts.

**Review by lunny — APPROVED** [review]

**Review by kdumontnu — CHANGES_REQUESTED** [review]
Love this PR! Tested it against a number of files locally and it looks great.

One potential issue is that the image diff is suppressed if the git diff settings are exceeded. This essentially means that most svgs which have been minified won't get the image diff because character length will likely be greater than the default (5000). 
image

The calculated width ends up with a lot of margin in the max case. I wonder if the js logic to calculate the width is working properly. Can we borrow styling from file view page?
image

I think either of these are potential candidates for separate PR, so I'm happy to change this to an approval if you'd rather merge this as-is!

**Comment by silverwind** [comment]
I was briefly looking at the existing image diff code before and one thing I don't like about it is all these size calculations done in JS. I think most if not all these calculations could be replaced by CSS-sized images (e.g. using sensible `max-width` and `max-height`) values.

Or do you think some stuff is not possible without those calculations?

**Comment by KN4CK3R** [comment]
Honestly I don't know if/what you can do with pure CSS here.

**Comment by silverwind** [comment]
I can check this out later. Not sure whether I'm motivated to refactor to CSS sizes but to me it only seems natural to let images size without JS, but I guess some use  cases like swipe diff do require a bit of JS logic for the slider and such. But for side-by side, it seems certainly unnecessary.

**Comment by silverwind** [comment]
Hmm, doesn't seem to do anything for me, neither for PNG nor SVG diff. It puts up a spinner but I don't observe any network request and nothing is logged in the console either.

image

**Comment by silverwind** [comment]
@KN4CK3R my latest push seems to have introduced some commits from `main` on this branch, could yo do a rebase please? There are some conflicts so I prefer if you can it.

**Comment by silverwind** [comment]
The bug with the spinner is with this `IntersectionObserver`thingy, `entry.intersectionRatio` comes out as 0 on Firefox for me on page load so `onContainerVisibleHandler` is never triggered. I'd appreciate if you would not use such arcane APIs and istead just load in first click of View Rendered, I think that should be the default view mode.

**Comment by silverwind** [comment]
You can probably just use [``](https://web.dev/browser-level-image-lazy-loading/) which in my eyes is vastly superior alternative to `IntersectionObserver` because it does not even require JavaScript to work.

**Comment by KN4CK3R** [comment]
Did not work with lazy for me. Could you try this patch? I'm not happy with that because the image diff is now coupled with the toggle. If the rendered view would be the default view all of this should not be needed.

```diff
diff --git a/web_src/js/features/imagediff.js b/web_src/js/features/imagediff.js
index d41655259..645aa89d0 100644
--- a/web_src/js/features/imagediff.js
+++ b/web_src/js/features/imagediff.js
@@ -61,25 +61,21 @@ export default async function initImageDiff() {
 
   $('.image-diff').each(function() {
     const $container = $(this);
+    const $fileBodyContainer = $container.closest('.file-body');
+    $fileBodyContainer.data('activation-handlers', [onContainerActiveHandler])
+
+    let initialized = false;
 
     if ($container.is(':visible')) {
-      onContainerVisibleHandler();
-    } else {
-      const observer = new IntersectionObserver((entries) => {
-        for (const entry of entries) {
-          if (entry.intersectionRatio > 0) {
-            observer.disconnect();
-            onContainerVisibleHandler();
-            break;
-          }
-        }
-      }, {
-        root: document.documentElement
-      });
-      observer.observe(this);
+      onContainerActiveHandler();
     }
 
-    function onContainerVisibleHandler() {
+    function onContainerActiveHandler() {
+      if (initialized) {
+        return;
+      }
+      initialized = true;
+
       const diffContainerWidth = $container.width() - 300;
       const pathAfter = $container.data('path-after');
       const pathBefore = $container.data('path-before');
diff --git a/web_src/js/index.js b/web_src/js/index.js
index 6cb47cf10..32c6c8a37 100644
--- a/web_src/js/index.js
+++ b/web_src/js/index.js
@@ -2483,15 +2483,22 @@ function initIssueReferenceRepositorySearch() {
 }
 
 function initFileViewToggle() {
-  $('.file-view-toggle').on('click', function() {
-    const $this = $(this);
-    $this.parent().children().removeClass('active');
-    $this.addClass('active');
-
-    const $target = $($this.data('toggle-selector'));
-    $target.parent().children().addClass('hide');
-    $target.removeClass('hide');
-  });
+  for (const el of document.querySelectorAll('.file-view-toggle')) {
+    const target = document.querySelector(el.dataset.toggleSelector);
+    if (target) {
+      el.addEventListener('click', function() {
+        el.parentNode.children.forEach((child) => child.classList.remove('active'));
+        el.classList.add('active');
+
+        target.parentNode.children.forEach((child) => child.classList.add('hide'));
+        target.classList.remove('hide');
+
+        for (const handler of $(target).data('activation-handlers') || []) {
+          handler();
+        }
+      });
+    }
+  }
 }
 
 function initLinkAccountView() {
```

**Comment by kdumontnu** [comment]
I really think image diff needs to ignore `MAX_GIT_DIFF_LINE_CHARACTERS` and `MAX_GIT_DIFF_LINES` before this gets merged. Otherwise, pretty much all svgs will not be diffed in the default case (other than small icon files).

**Comment by KN4CK3R** [comment]
I merged the incomplete with the normal diff view. Now there is less code with more functionality.

test

**Review by kdumontnu — APPROVED** [review]
🎉 @silverwind is there anything else you wanted to check out here?

**Review by lafriks — APPROVED** [review]

**Pull request merged**
