### PR TITLE
Fix labels display

### PR DESCRIPTION
**Pull request by stuzer05**
Fixes #32758

image
image
image

also fixes exclusive from repo and org grouping
image
image

search fixed using css
image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
The divider between "repo" labels and "org" labels are added intentionally, if you hide it, people are not able to distinguish "reop/org" labels.

```
bug (repo)
bug (org)
...
```

**Comment by stuzer05** [comment]
> The divider between "repo" labels and "org" labels are added intentionally, if you hide it, people are not able to distinguish "reop/org" labels.
> 
> ```
> bug (repo)
> bug (org)
> ...
> ```

Is there a use case to have identical labels under org and repo? repo labls are more like "extension" of general, org labels

**Comment by wxiaoguang** [comment]
Besides the problem above, I do no think it could work. I have explained in the issue, the "filter" problem is one of the root problems.

image

**Comment by stuzer05** [comment]
> Besides the problem above, I do no think it could work. I have explained in the issue, the "filter" problem is one of the root problems.
> 
> image

Maybe js dropdown on refresh and template fix could be combined. I understand, dropdown js fix is a "crutch" of a sort

**Comment by stuzer05** [comment]
> > Besides the problem above, I do no think it could work. I have explained in the issue, the "filter" problem is one of the root problems.
> > image
> 
> Maybe js dropdown on refresh and template fix could be combined. I understand, dropdown js fix is a "crutch" of a sort

This could be fixed by css
```css
.filtered + .divider {
    display: none;
}
```

**Comment by stuzer05** [comment]
image
image

**Comment by wxiaoguang** [comment]
> > > Besides the problem above, I do no think it could work. I have explained in the issue, the "filter" problem is one of the root problems.
> > > image
> > 
> > 
> > Maybe js dropdown on refresh and template fix could be combined. I understand, dropdown js fix is a "crutch" of a sort
> 
> This could be fixed by css
> 
> ```css
> .filtered + .divider {
>     display: none;
> }
> ```

It can't be right either.

```
<div>label a</div>
---- <div class="divider"></div>
<div data-scope="xxx">label b-1</div>
<div data-scope="xxx" class="filtered">label b-2</div>
---- <div class="divider"></div> here, you shouldn't hide it.
<div>label c</div>
```

**Comment by stuzer05** [comment]
> It can't be right either.
> 
> ```
> <div>label a</div>
> ---- <div class="divider"></div>
> <div data-scope="xxx">label b-1</div>
> <div data-scope="xxx" class="filtered">label b-2</div>
> ---- <div class="divider"></div> here, you shouldn't hide it.
> <div>label c</div>
> ```

image
Visually it works, can you share a screenshot?

**Comment by wxiaoguang** [comment]
> Visually it works, can you share a screenshot?

Before "visual work", we should make it "theoretically right", right?

I have finished my " Fix duplicate dropdown dividers #32760 ", and added enough tests, I think it should work for all cases. The behavior is 100% controlled and we could always fine-tune it by what we need.

**Comment by stuzer05** [comment]
> > Visually it works, can you share a screenshot?
> 
> Before "visual work", we should make it "theoretically right", right?
> 
> I have finished my " Fix duplicate dropdown dividers #32760 ", and added enough tests, I think it should work for all cases. The behavior is 100% controlled and we could always fine-tune it by what we need.

Can we merge repo and org labels as well? I don't see any reason why we should separate them, because now:
1. repo and org labels aren't visually separated, only by position (not obvious)
2. should user really think about where labels are refined? - it's more an administrative work
3. grouping makes more sense and make find labels easy instead of confusing users

**Comment by wxiaoguang** [comment]
> Can we merge repo and org labels as well? I don't see any reason why we should separate them, because now:

I have no idea, I do not use these features, maybe you could open a proposal and invite the initial contributors to provide feedbacks.

**Pull request closed without merging**
