### PR TITLE
Fix the v78 migration "Drop is_bare" on MSSQL #6707

### LINKED ISSUE #6707: Unable to migrate from version 1.7.4 to version 1.8.0
- Gitea version (or commit ref): 1.8.0
- Git version:  2.16.2.windows.1
- Operating system: WIndows server 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description
Hi guys, I'm facing a issue when upgrading from version 1.74 to 1.8.0  :

2019/04/22 10:25:23 [I] Migration: add theme to users
2019/04/22 10:25:30 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:30 [I] Backing off for 3 seconds
2019/04/22 10:25:33 [I] ORM engine initialization attempt #2/10...
2019/04/22 10:25:33 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:34 [I] Backing off for 3 seconds
2019/04/22 10:25:37 [I] ORM engine initialization attempt #3/10...
2019/04/22 10:25:37 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:37 [I] Backing off for 3 seconds
2019/04/22 10:25:40 [I] ORM engine initialization attempt #4/10...
2019/04/22 10:25:40 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:40 [I] Backing off for 3 seconds
2019/04/22 10:25:44 [I] ORM engine initialization attempt #5/10...
2019/04/22 10:25:44 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:44 [I] Backing off for 3 seconds
2019/04/22 10:25:47 [I] ORM engine initialization attempt #6/10...
2019/04/22 10:25:47 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:47 [I] Backing off for 3 seconds
2019/04/22 10:25:50 [I] ORM engine initialization attempt #7/10...
2019/04/22 10:25:50 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:51 [I] Backing off for 3 seconds
2019/04/22 10:25:54 [I] ORM engine initialization attempt #8/10...
2019/04/22 10:25:54 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:54 [I] Backing off for 3 seconds
2019/04/22 10:25:57 [I] ORM engine initialization attempt #9/10...
2019/04/22 10:25:57 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:25:57 [I] Backing off for 3 seconds
2019/04/22 10:26:00 [I] ORM engine initialization attempt #10/10...
2019/04/22 10:26:00 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:01 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: Drop column failed: mssql: Error de ALTER TABLE DROP COLUMN is_bare debido a que uno o más objetos tienen acceso a columna.
2019/04/22 10:26:22 [I] Log Mode: File(Info)
2019/04/22 10:26:22 [I] XORM Log Mode: File(Info)
2019/04/22 10:26:22 [I] Cache Service Enabled
2019/04/22 10:26:22 [I] Session Service Enabled
2019/04/22 10:26:22 [I] Mail Service Enabled
2019/04/22 10:26:22 [I] Notify Mail Service Enabled
2019/04/22 10:26:22 [I] Beginning ORM engine initialization.
2019/04/22 10:26:22 [I] ORM engine initialization attempt #1/10...
2019/04/22 10:26:22 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:29 [I] Backing off for 3 seconds
2019/04/22 10:26:32 [I] ORM engine initialization attempt #2/10...
2019/04/22 10:26:32 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:33 [I] Backing off for 3 seconds
2019/04/22 10:26:36 [I] ORM engine initialization attempt #3/10...
2019/04/22 10:26:36 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:36 [I] Backing off for 3 seconds
2019/04/22 10:26:39 [I] ORM engine initialization attempt #4/10...
2019/04/22 10:26:39 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:39 [I] Backing off for 3 seconds
2019/04/22 10:26:42 [I] ORM engine initialization attempt #5/10...
2019/04/22 10:26:43 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:43 [I] Backing off for 3 seconds
2019/04/22 10:26:46 [I] ORM engine initialization attempt #6/10...
2019/04/22 10:26:46 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:46 [I] Backing off for 3 seconds
2019/04/22 10:26:49 [I] ORM engine initialization attempt #7/10...
2019/04/22 10:26:49 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:50 [I] Backing off for 3 seconds
2019/04/22 10:26:53 [I] ORM engine initialization attempt #8/10...
2019/04/22 10:26:53 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:54 [I] Backing off for 3 seconds
2019/04/22 10:26:57 [I] ORM engine initialization attempt #9/10...
2019/04/22 10:26:57 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:26:57 [I] Backing off for 3 seconds
2019/04/22 10:27:00 [I] ORM engine initialization attempt #10/10...
2019/04/22 10:27:00 [I] Migration: rename repo is_bare to repo is_empty
2019/04/22 10:27:01 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: Drop column failed: mssql: Error de ALTER TABLE DROP COLUMN is_bare debido a que uno o más objetos tienen acceso a columna.

Do you have any solution or workaround for this?

### PR DESCRIPTION
**Pull request by zeripath**
So #6707 appears to be reporting multiple issues with the drop bare constraint on MSSQL.

https://github.com/go-gitea/gitea/issues/6707#issuecomment-487873555 

suggests a piece of code which will try to detect the constraint and execute code to remove it.

This attempts to replicate this code.

~~Please note I do not have access to MSSQL - so this is untested. (Hence the WIP)~~

### CODE REVIEW

**Comment by lunny** [comment]
@zeripath we have a drone test about MSSQL. And you can run a mssql database on docker.

**Comment by zeripath** [comment]
Fixed and confirmed to be working!

**Review by lafriks — DISMISSED** [review]
Drop column is still beeded

**Comment by zeripath** [comment]
@lafriks what do you mean? The rest of the migrations don't explicitly drop the column - I think the sync2 does that?

**Comment by zeripath** [comment]
I thought this does the drop:

https://github.com/zeripath/gitea/blob/eccab67a3cf4bdb8c068075f1b481957ed756a01/models/migrations/v78.go#L68

**Comment by zeripath** [comment]
Actually it's dropped here:

https://github.com/zeripath/gitea/blob/a10debc778ff67b56d23876cae7f515c0d85891d/models/migrations/v78.go#L76

**Comment by lafriks** [comment]
Btw why aren't you using dropColumns function: https://github.com/go-gitea/gitea/blob/master/models/migrations/migrations.go#L275 ?

**Comment by zeripath** [comment]
OK @lafriks I've changed to use dropTableColumns

**Comment by techknowlogick** [comment]
`dropTableColumns` drops columns but only removes the constraints from MSSQL. It misses indexes on other DB types.

**Comment by zeripath** [comment]
Oh great so should we not update dropTableColumns to remove constraints on other types too?

**Comment by zeripath** [comment]
I've reverted the change to dropTableColumns as it's not quite the right thing at present.

**Comment by techknowlogick** [comment]
This migration has caused many issues to be reported, I'd like to have it in a working state, then we can move the logic of dropping constraints into `dropColumns`. 

On a related note: I wonder why our migration tests didn't catch the fail case. I'm guessing it's like that one user reported where they were using an older version of MSSQL.

**Comment by zeripath** [comment]
So we don't have migration tests for MSSQL as when I wrote the migration tests I didn't have access to MSSQL and it's not entirely clear how to get the T-SQL out of MSSQL.

If I knew XORM better I'd say it should be possible to get XORM to just dummy out the sql commands it would use to create and fill the database and we should be able to just store those but I don't know XORM well enough to do that.

**Comment by lunny** [comment]
@zeripath so, we need a migration test for MSSQL.

**Comment by zeripath** [comment]
Yes we do.

The correct way to do this, and one that would make it very easy in future to add more migrations is for xorm dump to work correctly - but it doesn't produce valid sql.

Another way would be to somehow get xorm to produce

**Comment by zeripath** [comment]
Anyway there are multiple users out there who are struggling to get to 1.8 because this migration step is **still** wrong.

If you know a way of getting a t-sql dump out of mssql or can provide a t-sql dump of 1.5.3, 1.6.4 and 1.7.0 I'm happy to add this or we can add it as another pr - however we need to get a fix in.

Similarly if you'd prefer that this was rebased on top of #6849 that's fine, but #6849 would also need to be backported.

**Comment by zeripath** [comment]
Build https://drone.gitea.io/go-gitea/gitea/8698/1/16 shows that when combined with #6851 and #6852 you can see fixes the v78 migration. I'm going to force rebase this back to be just the v78 fix now.

**Review by techknowlogick — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by techknowlogick** [comment]
@zeripath merged. Please backport 😃

**Pull request merged**
