### PR TITLE
add sorting to database query of repo_units

### PR DESCRIPTION
**Pull request by daviian**
If sorting is wrong and UnitTypeCode is not the first one, a user can't visit to the `Code` Tab even with required permissions.

Furthermore fixes wrong redirect to leftmost accessible tab in repo view.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lafriks** [comment]
Can you add integration test for this?

**Comment by daviian** [comment]
@lafriks Hopefully 😄

**Comment by daviian** [comment]
@lafriks Changed repo_unit fixtures. Wrong sorting breaks all integration tests which call /user2/repo1 without adding sorting.

**Comment by lunny** [comment]
But `index` is the column really designed for sorting.

**Comment by lafriks** [comment]
@lunny but it's not used anywhere. And current code logic depends on unit types to be in type order when checking rights and it fails if it is not so

**Comment by Morlinest** [comment]
@lafriks If you merge #2601, repo home will not fail... This PR can solve problem with showing leftmost tab.

**Comment by lafriks** [comment]
Might be that home just need to be changed so that order would not matter and fixtures moved to that PR than this one would not be needed at all

**Comment by Morlinest** [comment]
@lafriks Don't need to move fixtures there. That PR is just to fix function implementation that @daviian pointed me to while trying to solve sorting. This PR can be (at least quick) fix for redirecting to tabs in good order.

**Comment by Morlinest** [comment]
@daviian Can you use `index` column for sorting If we implement #2601?

**Comment by daviian** [comment]
@lunny @lafriks @Morlinest As long as index has the same sorting as the tab ordering in repo view it is fine to use index to sort types.

And since index is the integer value of the UnitType constant it is.

**Comment by lunny** [comment]
which issue will this PR fix?

**Comment by daviian** [comment]
@lunny Use the `models/fixtures/repo_unit.yml` I provided in this PR and run integration tests. A lot of tests will fail because of wrong sorting.

**Comment by Morlinest** [comment]
@daviian Index is not integer value of `UnitType`. It should be taken from `Unit.Idx` I think, but now it's just starting from 0 and is another bug.

Edit: Index from range is used as `Index`.
Edit2: Now I found places, where just int value of unit is used...

**Comment by Morlinest** [comment]
@lunny What should be source for `Index`? I think it should be `Unit.Idx`, right?

**Comment by lunny** [comment]
@Morlinest yes.

**Comment by lunny** [comment]
LGTM

**Comment by Morlinest** [comment]
@lunny Then #2621

**Comment by lafriks** [comment]
Actually I think fix should go into home handler so that it would not crash even if units come in different order

**Comment by lafriks** [comment]
Yes that's why I ask to hold on with this PR merging so that other can be fixed properly

**Comment by Morlinest** [comment]
@lafriks @lunny I think you have 1 PR for everything now :). This PR is about getting units sorted from DB, #2601 fixes home handler and #2621 fixes creating new repo units + fixes existing index data in DB.

**Comment by daviian** [comment]
@lafriks You mean that the Home handler should be capable of knowing the correct order of unit types (to open the leftmost accessible tab) without doing sorting at db layer?

**Comment by lafriks** [comment]
Yes. I think it should take unit order from models.AllUnitTypes and use it and then check if each of them is enabled

**Comment by Morlinest** [comment]
We can improve it later. And then we can just remove `Index` from DB as it will be useless.

**Comment by lunny** [comment]
@lafriks could this be merged?

**Comment by daviian** [comment]
Close in favour of #2621

**Pull request closed without merging**
