### PR TITLE
Godep Initial Commit, Second try

### PR DESCRIPTION
**Pull request by techzilla**
OK, I got it working, the gitea code structure prevented godep from resolving imports within the repository.  I had to add a symlink in the godep created workspace, which refers back to the root of the repo as gitea.

Now this allows the project to be fully built with one command,  

godep go build

I just cloned it with a new system, and it built without getting the dependencies.
Yea the inability to build this project outside of an established GOPATH introduces packaging complexity.  This becomes much easier when we can build from location interdependent clone with godep.

### CODE REVIEW

**Comment by techzilla** [comment]
DAMN, I forgot to fix the CI config.... will do over agin

**Comment by FSMaxB** [comment]
You can use `git rebase`, then you don't have to redo all those pull requests.

**Comment by tboerger** [comment]
If we switch to 1.5 build process we can use the new builtin vendor functionality.

**Comment by lunny** [comment]
Yes, but I expect it will be changed after v0.7.

**Comment by tboerger** [comment]
And for getting automated build i would suggest some ci service like drone :)

**Comment by lunny** [comment]
@tboerger That's a great idea.

**Pull request closed without merging**
