### PR TITLE
update git and fix #1133

### LINKED ISSUE #1133: Releases page don't show anything if git version less than 1.8
That means you have to upgrade your git version to more than 1.8

### PR DESCRIPTION
**Pull request by lunny**
will fix #1133

### CODE REVIEW

**Comment by sapk** [comment]
LGTM and drone will check if vendoring is good ^^

**Comment by lunny** [comment]
@sapk, I think maybe the check has some wrong. The vendor package could be older than the original package. It's not an error.

**Comment by lunny** [comment]
And I have run `govendor status +outside +unused` on my branch, it shows 
```
The following packages are missing or modified locally:
       	github.com/go-xorm/core
       	github.com/go-xorm/xorm
```
But the drone said `code.gitea.io/git` is missing or modified locally. So I think maybe the vendor-test has something wrong.

**Comment by sapk** [comment]
File `command_test.go` is missing https://github.com/go-gitea/git/compare/135704d70ee8dddec363e80f3235092493fea2c2...go-gitea:3f99247c0da807afc967c7e12b14f4109b7490ff to be compliant with commit 3f99247c0da807afc967c7e12b14f4109b7490ff

What did you used to update vendor ?

**Comment by sapk** [comment]
Can you try to do a `govendor sync` ? It should add file `command_test.go` and do a `git add` to commit it.

**Comment by lunny** [comment]
I used `govendor update`. I will update this.

**Comment by lunny** [comment]
It seems `govendor sync` also do not copy test files?

**Comment by sapk** [comment]
Oh it seems that https://github.com/go-gitea/gitea/blob/master/vendor/vendor.json#L3 is maybe blocking test_file ... 

But it shouldn't affect the command `govendor status +outside +unused` that should use the same config. I will have a look at it.

**Comment by sapk** [comment]
In fact there is no test_file in vendor so if this work in other dependencies this should also work here. I am searching why. https://github.com/search?utf8=%E2%9C%93&q=repo%3Ago-gitea%2Fgitea+language%3AGo+path%3Avendor+test&type=Code

**Comment by sapk** [comment]
I haven't try but https://github.com/kardianos/govendor/wiki/Govendor-CheatSheet#important-detail. I will test with fetch when I have access to a cli.

**Comment by sapk** [comment]
Ok I have tested and it seems that if you fetch it doesn't give the same checksumSHA1.

**Comment by sapk** [comment]
@lunny please do `govendor fetch code.gitea.io/git` and commit `vendor/vendor.json`

**Comment by sapk** [comment]
You should have a checksum starting with `spqE5x...`

**Comment by lunny** [comment]
@sapk done.

**Comment by sapk** [comment]
Perfect, I hope it will pass now ^^

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
