### PR TITLE
fix mail notification when close/reopen issue

### LINKED ISSUE #6580: Close/Reopen issue sends notification with the text of the issue
- Gitea version (or commit ref): v1.8.0-rc2
- Git version:
- Operating system: devuan
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

when closing/reopening an issue, the email doesn't say "Closed/Reopened issue #..." anymore, instead it sends the text of the issue.

### PR DESCRIPTION
**Pull request by lunny**
will fix #6580

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
I think we need to internationalise these emails in general.

**Review by adelowo — APPROVED** [review]

**Comment by femaref** [comment]
I think this should be backported, as it's a small, but highly impactful quality of life fix. we are working in a larger team, as such the throughput can be quite high. right now, I have to open every email to see if the ticket was closed or if it's a new ticket/comment. this is quite annoying and having to tell my team it will take some time until this stops isn't something I'm looking forward to.

**Comment by zeripath** [comment]
Seems reasonable to me that this could be backported. @lunny can we send a backport?

**Comment by lunny** [comment]
@zeripath done.

**Comment by zeripath** [comment]
@femaref The backport is in our release/v1.8 branch now.

**Comment by femaref** [comment]
thank you. are there builds available before they are released as rc? or do I have to build it myself?

**Pull request merged**
