### PR TITLE
Show a link to password reset from user settings requiring a password

### PR DESCRIPTION
**Pull request by strk**
... helpful, when you forgot your password thus cannot change it

### CODE REVIEW

**Comment by strk** [comment]
btw, I'd also change the path, from current `/forget_password` to the more correct `/forgot_password`, what do you think @bkcsoft, @lunny, @tboerger ? Would that break any API ?

**Comment by bkcsoft** [comment]
@strk Fine by me, it's not part of the API so I'm not that worried about it... just make sure that _all_ references to it are changed :)

**Comment by strk** [comment]
@bkcsoft done and rebased. Can we get this into 1.1.0 ?

**Comment by lunny** [comment]
please reset all non-english translation changes since we use crowdin

**Comment by strk** [comment]
I only changed the keys, not the translations. Is this something crowdin also does automatically ?

**Comment by lunny** [comment]
I don't know in fact. I'm not familiar with crowdin.

**Comment by strk** [comment]
Then I'd say let's merge this as-is and we'll see if anything goes wrong :)

**Comment by strk** [comment]
Rebased to current master.

**Comment by strk** [comment]
@lunny will I have your LGTM if I remove the `forget -> forgot` commit ? I don't want that to hold up the new link. Note I was asked by @bkcsoft to do that rename...

**Comment by lunny** [comment]
I think two problems:
1. you should drop all the non-en translation so that we can sync with crowdin.
2. It seems this is two PR. One is for typo, another is for put the link on the UI.

And I don't know why we should put the reset password link on the UI

**Comment by strk** [comment]
So I removed the `forget->forgot` change, and squash-rebased the
link itself. I want the link because when you login via OAuth2
or OpenID you might really forget about the password (or never
know it, with the current proposal of OpenID login).

Will file another PR for the `forget->forgot` change, so the
translation discussion does not block this PR.

**Comment by strk** [comment]
Why does this go to 1.2 ? I rebased it, it's really a simple change, just an additional link where password is requested (and no more change to localization files)

**Comment by lunny** [comment]
@strk I think OpenID and this one could be in v1.2 since we have already delayed. I have moved many features to v1.2.

**Comment by strk** [comment]
Can this be merged now that 1.1.0 is out ? Please review :)

**Comment by strk** [comment]
@lunny do I have your L-G-T-M then ? How about you @bkcsoft ? I have local change for the `forget->forgot` change waiting for this to be merged too

**Comment by lunny** [comment]
@strk don't know why we need put a link on this UI.

**Comment by strk** [comment]
@lunny every single time you're asked for a password, it makes sense to me to provide a `forgot password?` link. Don't you agree ? GitHub does it, as far as I can tell.

**Comment by lunny** [comment]
trusted LGTM

**Pull request merged**
