### PR TITLE
Bump goldmark to v1.4.11 (#19201)

### PR DESCRIPTION
**Pull request by xoxys**
Backport: #19201

Unfortunately goldmark 1.4.8 contains a bug whereby html comments on checklist elements are mistakenly rendered. This has been fixed upstream with goldmark 1.4.11.

Regression introduced in: https://github.com/go-gitea/gitea/pull/19127
Upstream issue: https://github.com/yuin/goldmark/issues/285

Fix: #19195

### CODE REVIEW

**Review by noerw — APPROVED** [review]

**Comment by noerw** [comment]
CI fail is related: `Please run 'go mod tidy' and commit the result:`

**Comment by zeripath** [comment]
Let me fix this.

**Comment by zeripath** [comment]
I've added a testcase to prevent this from happening again.

**Review by zeripath — APPROVED** [review]

**Comment by xoxys** [comment]
Thanks!

**Pull request merged**
