### PR TITLE
WIP: Add Diff Patch support 

### PR DESCRIPTION
**Pull request by zeripath**
This code adds a simple endpoint to add diff patch application to Gitea

- [x] Initial implementation of ApplyDiffPatch - can be tested at /owner/repo/_diffpatch/branch or on API
- [ ] Wire in to UI
- [ ] Better error support

### CODE REVIEW

**Comment by 6543** [comment]
step towards #9388?

**Comment by 6543** [comment]
add `_diffpatch` to the list of forbidden branchnames

**Comment by zeripath** [comment]
@6543 I'm not sure banning _diffpatch is needed?

**Comment by lafriks** [comment]
I also think it would not conflict with branch names

**Comment by 6543** [comment]
ping

**Comment by binyamin** [comment]
@6543 My understanding is that #13442 (send patches via email) depends on this pull request. I'm looking forward to that feature. How can I help get this merged?

**Comment by zeripath** [comment]
it's essentially ready depending on the UI but I was trying to get `` ```suggestion `` support sorted however I've been exceptionally busy fixing multiple bugs - (77 PRs to 1.14 fixing bugs)

**Comment by 6543** [comment]
->  #17902

**Pull request closed without merging**
