### PR TITLE
Migration failure during reaction migration from gitea (#13344)

### PR DESCRIPTION
**Pull request by techknowlogick**
* Migrating reactions is just not that important

A failure during migrating reactions should not cause failure of
migration.

Signed-off-by: Andrew Thornton <art27@cantab.net>

* When checking issue reactions check the correct permission

Signed-off-by: Andrew Thornton <art27@cantab.net>
Credit @zeripath

### CODE REVIEW

**Comment by techknowlogick** [comment]
Closing this as Gitea migration isn't in 1.12

**Comment by zeripath** [comment]
No but the reactions API is and it is those fixes which needs to be backported

**Comment by techknowlogick** [comment]
Ah yes.

**Review by zeripath — COMMENTED** [review]
This is missing the issue comment reactions changes

**Comment by techknowlogick** [comment]
@zeripath those aren't included because `modules/migrations/gitea_downloader.go` doesn't exist in release/v1.12.

**Comment by techknowlogick** [comment]
Adding blocked label

**Comment by zeripath** [comment]
Nope it's not that - unfortunately both the original and the 1.13 backport were missing one final change that I thought I had pushed up. 

Line 60 of the issue_reaction.go has the same bug and also needs to be fixed.

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
