### PR TITLE
Increase default LFS auth timeout from 20m to 24h

### PR DESCRIPTION
**Pull request by wxiaoguang**
According to the discussion with DanielGibson, the default "20m" seems too short. It would make LFS fail if the file is large / network is slow.

I think relaxing this timeout doesn't have side affect. So change the default value to 24h, IMO that should be long enough.

## :warning: BREAKING

If admins want the previous timeout, they should set the setting `[server].LFS_HTTP_AUTH_EXPIRY`.

### CODE REVIEW

**Comment by lunny** [comment]
I think it's just for authentication but not for transferring files. 20 minutes should be enough.

**Comment by wxiaoguang** [comment]
> I think it's just for authentication but not for transferring files. 20 minutes should be enough.

You get a token, push a 2G file into LFS, it takes 30 minutes, then how could you push another 2G file if the token expires in 20 minutes?

**Comment by earl-warren** [comment]
The full discussion on this problem can be found at https://codeberg.org/forgejo/forgejo/issues/715

**Comment by wxiaoguang** [comment]
> The full discussion on this problem can be found at https://codeberg.org/forgejo/forgejo/issues/715

That discussion is too long so I only summarize the key points to make it easier to understand.

**Comment by earl-warren** [comment]
The discussion provides a concrete use case which is helpful when considering a change that would otherwise be only theoretical.

**Comment by wxiaoguang** [comment]
> The discussion provides a concrete use case which is helpful when considering a change that would otherwise be only theoretical.

I agree that the original discussion contains some valuable information.

Indeed that's just different habits IMO.

I prefer to describe a problem clearly in short ( eg: It would make LFS fail if the file is large / network is slow.) . If people could understand , it saves everyone's time. If people don't understand I will explain more with a simple and concrete case like https://github.com/go-gitea/gitea/pull/24628#issuecomment-1541323018 .

**Comment by lunny** [comment]
> > I think it's just for authentication but not for transferring files. 20 minutes should be enough.
> 
> Suppose you get a token, push, transfer a 2G file into LFS, it takes 30 minutes, then how could you transfer another 2G file (in the same push operation) if the token expires in 20 minutes?

I don't know whether the 

> > I think it's just for authentication but not for transferring files. 20 minutes should be enough.
> 
> Suppose you get a token, push, transfer a 2G file into LFS, it takes 30 minutes, then how could you transfer another 2G file (in the same push operation) if the token expires in 20 minutes?

I'm not against to increase the time but I don't know how this resolve the problem.

The time was given to git-lfs client at https://github.com/go-gitea/gitea/blob/44deae8f3dfcbdc9edda5a817c168e110864266b/cmd/serv.go#L257

And then, the git-lfs could use the url and token to send requests to Gitea HTTP services.

In fact, Gitea lfs server implementation haven't check the expire time. https://github.com/go-gitea/gitea/blob/17c5c654a57ecf51c8c7c8ecfc6c86ae313d4000/services/lfs/server.go#L592

**Comment by wxiaoguang** [comment]
It is a JWT token, it contains "expiry", it is validdate by JWT library:

image

**Review by lunny — APPROVED** [review]
OK. Let's try it. And it's strange the `git-lfs` will not check the expire date and refresh it.

**Review by delvh — APPROVED** [review]

**Pull request merged**
