### PR TITLE
Fix Erlang and Elixir highlight mappings

### PR DESCRIPTION
**Pull request by rnowak**
Hi,

Without these changes, the highlighting language determination for both Erlang (.erl, .escript) and Elixir (.ex, .exs) files is left up to a dice roll -- sometimes it is typescript, some other times actionscript. Exciting.

I do not believe ".erlang" and ".elixir" to be extensions used wildly in the wild.

I realize this replaces a single entry with two for each of the languages, and .escript is not even that common and could be left out.

Thanks.

### CODE REVIEW

**Comment by lafriks** [comment]
Please reformat (`make fmt`)

**Comment by rnowak** [comment]
Done. A friend also made me aware that hightlight.js has an "erl" alias for erlang, so that one could be moved up to the upper mapping. The three other are less lucky. Would you prefer that?

**Comment by lafriks** [comment]
Yes please move erl up if it works with our used version

**Comment by rnowak** [comment]
Moved ".erl" up to be in the same place as ".erlang" was before. Not sure what the ordering is.

Tested with the shipped highlight.js - works as expected.

**Review by lafriks — APPROVED** [review]

**Review by adelowo — APPROVED** [review]

**Pull request merged**
