### PR TITLE
Fix followers and following tabs in profile

### LINKED ISSUE #10195: "followers" & "following" is a valid repository name
- Gitea version (or commit ref): 1.11.0+dev-534-ga864d61ee
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
Gitea uses the URL https://try.gitea.io/imtestingthis/followers to display my followers, and https://try.gitea.io/imtestingthis/following to display who I follow.

It is possible to create a repository called `followers` or `following`. In this case you cannot view the repository's content as the user's followers/following list appears instead. It is still possible to go to a repository's subpages such as [issues](https://try.gitea.io/imtestingthis/followers/issues), [wiki](https://try.gitea.io/imtestingthis/followers/wiki), etc.

## Solutions
1. Disallow the creation of repositories called `followers` and `following`.
2. Use https://try.gitea.io/imtestingthis?followers and https://try.gitea.io/imtestingthis?following as a URL for those pages. This would be consistent with other profile actions such as https://try.gitea.io/imtestingthis?tab=activity .

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #10195

Screenshot:
image

### CODE REVIEW

**Comment by 6543** [comment]
@lafriks why is this a fix and not a normal enhancement?

for me it looks like a ui restructure

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
I would make a backport fix -> witch simply add **followers** and **following** to `reservedUsernames` in `user.go`

**Comment by lafriks** [comment]
No need to add them to reserved usernames and that would not help anyway as problem is repository name

**Comment by lafriks** [comment]
I can of course backport this to 1.11 if needed

**Pull request merged**
