### PR TITLE
Use correct translation key for max repo limit error messages

### LINKED ISSUE #18122: Error message broken when migrating repo at max repo limit
### Gitea Version

1.15.6

### Git Version

_No response_

### Operating System

FreeBSD 13

### How are you running Gitea?

Using Gitea from the FreeBSD repos.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

When you have reached your max repo limit if you attempt to migrate a repo there is no error message indicating that it can't be done. When you actually press the migrate button an error pops up, but the formatting is broken:

> form.reach_limit_of_creation%!(EXTRA int=0)

### Screenshots

A screenshot showing the described error message

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #18122

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Could we refactor the function `TrN` and make them share the same code?

https://github.com/go-gitea/gitea/blob/a3d685077f5ce331d6899426eb70c89e0fe6443a/modules/templates/helper.go#L861

IMO we should have a unified behavior in both template and backend code.  

ps: the old `TrN` need to be refactored, too. The templates calls it by `{{.i18n.Tr (TrN .i18n.Lang ... ) }}`, it is complex and might be simplified to `{{.i18n.TrN ....}}` directly.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
> Could we refactor the function `TrN` and make them share the same code?
> 
> https://github.com/go-gitea/gitea/blob/a3d685077f5ce331d6899426eb70c89e0fe6443a/modules/templates/helper.go#L898
> 
> IMO we should have a unified behavior in both template and backend code.
> 
> ps: the old `TrN` need to be refactored, too. The templates call it by `{{.i18n.Tr (TrN .i18n.Lang ... ) }}`, it is complex and might be simplified to `{{.i18n.TrN ....}}` directly.

That could be another PR.

**Comment by lunny** [comment]
Please send backport.

**Comment by wxiaoguang** [comment]
I proposed a refactoring for `TrN`:
* https://github.com/go-gitea/gitea/pull/18141

**Pull request merged**
