### PR TITLE
Set user's 24h preference from their current OS locale

### LINKED ISSUE #28371: Allow to select 24h time format
### Feature Description

gitea seems already to support the 24h time format but it appears that this is bound to the language settings.

Please add either

- an option to select the time format explicitly, or
- add more language variants (e.g. "english(uk)" -> 24h, "english(colonies)" -> 12h)

Time format and interface language are usually two different things.  E.g. I prefer english language for technical content but 12h time format is completely unreadable for me.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/28371

Edit: Comment below is not accurate anymore, see https://github.com/go-gitea/gitea/pull/29651#issuecomment-1984600844 for solution.

--

`relative-time` uses the [closest `lang` attribute](https://github.com/github/relative-time-element/blob/1a42a317372e09b08fe430fe36f2598d2039bbfa/src/relative-time-element.ts#L86-L88) to format dates, but the problem our closest tag is on `<html>` which does contain the the selected locale for the UI, which may not necessarly match the user's currently locale.

For example any user with 24h clock preference that has set `en-US` as their language in gitea will receive US-based 12h formatting. To achieve locale-specific time formatting, set `lang=unknown` (the default value of [`lang`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang)) on `<relative-time>` which results in locale-aware formatting and likely a small speedup because the element does not have to search up the whole HTML tree.

Before:
Screenshot 2024-03-07 at 21 54 51

After:
Screenshot 2024-03-07 at 21 56 32

### CODE REVIEW

**Review by denyskon — APPROVED** [review]
Well it isn't pretty, but technically it's the correct solution :laughing:

**Comment by silverwind** [comment]
Basically I take it as our fault for setting `lang` on `<html>` in first place. Maybe we should evaluate removing that attribute in the future so that user's default locale settings are in effect everywhere.

**Comment by lafriks** [comment]
Wouldn't that affect date display language to differ from UI?

**Comment by silverwind** [comment]
Actually yes, there is the problem with mixed language now, so likely the fix will be more complex.

image

**Comment by silverwind** [comment]
Fixed by using a JS solution that formats according to `lang`, but explictely alters the 24h setting as per user's locale. This will work for all tooltips:

Screenshot 2024-03-07 at 23 03 35
Screenshot 2024-03-07 at 23 03 17

I think there is only one other place in the UI where we render such absolute dates, which is in the actions view and which I've also fixed:

Screenshot 2024-03-07 at 23 04 00

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Should be ready now. I think I will also upstream this fix into https://github.com/github/relative-time-element, because honestly I'm also tired of 12h format on GitHub. 😆

**Comment by silverwind** [comment]
I'll try do one more enhancement to detect availability of [`getHourCycles`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getHourCycles), which is the best API for this and it will also enable use of the rare 11h clock format.

**Comment by silverwind** [comment]
> I'll try do one more enhancement to detect availability of [`getHourCycles`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getHourCycles), which is the best API for this and it will also enable use of the rare 11h clock format.

Actually, no, I won't do it. The relevant Intl API usage is too hackish, maybe revisit this in a few years once they have introduced proper usable APIs.

```js
    const props = {};
    const intlLocale = new Intl.Locale(Intl.DateTimeFormat().resolvedOptions().locale);
    const hourCycle = intlLocale.getHourCycles?.()[0] ?? intlLocale.hourCycles?.[0];
    if (hourCycle) {
      props.hourCycle = hourCycle;
    } else {
      props.hour12 = !Number.isInteger(Number(new Intl.DateTimeFormat([], {hour: 'numeric'}).format()));
    }
```

**Review by denyskon — APPROVED** [review]

**Comment by lunny** [comment]
Sorry for the mistake of the commit message and I have to amend the commit message with magic power.

**Comment by silverwind** [comment]
Upstream issue: https://github.com/github/relative-time-element/issues/276

**Comment by silverwind** [comment]
Note for future: This workaround can be removed once https://github.com/github/relative-time-element/pull/329 is merged and released. If there is no progress on that, I will fork the repo.

**Pull request merged**
