### PR TITLE
Lint error.go

### PR DESCRIPTION
**Pull request by strk**
This was done semi-programmatically, not really documenting anything

### CODE REVIEW

**Comment by tboerger** [comment]
This doesn't make sense with real text

**Comment by bkcsoft** [comment]
_Really_? This isn't helping anywhere... it just hides the errors from the build, making it _harder_ to find them when someone _actually_ wants to fix them...

If you intend to _actually_ fix the lint-errors you can ask to get this reopened, but I'm close this for now as invalid

**Comment by strk** [comment]
I thought we wanted to make linting checks automatic ? Getting there earlier would give us automatic docs check for future changes, even if leaving existing code untouched...

**Comment by tboerger** [comment]
We want to automate lint checks, but these changes won't be detected anymore, so it's pretty useless

**Pull request closed without merging**
