### PR TITLE
Fix milestone title font problem

### PR DESCRIPTION
**Pull request by wxiaoguang**
Replace #22853 since it's closed, and actually there are 2 places need to be fixed.

~~Follow @fsologureng 's suggestion to keep the `<hX>` tags.~~ 

Update: from fsologureng: this doesn't change anything from a11y's point of view. So I think this PR could be fine to fix the UI looking problems as a quick patch, then defer the a11y problems to new PRs together.

Before: the font-size is too large.

After: it seems better.

image

image

### CODE REVIEW

**Comment by delvh** [comment]
Hmm… this appears to be a controversial topic on how to implement correctly (https://github.com/go-gitea/gitea/pull/22853#issuecomment-1426785277, https://github.com/go-gitea/gitea/pull/22853#issuecomment-1426269884).
I have no idea what the correct approach is as I can't evaluate how accessible it is.

**Comment by wxiaoguang** [comment]
> Hmm… this appears to be a controversial topic on how to implement correctly ([#22853 (comment)](https://github.com/go-gitea/gitea/pull/22853#issuecomment-1426785277), [#22853 (comment)](https://github.com/go-gitea/gitea/pull/22853#issuecomment-1426269884)). I have no idea what the correct approach is as I can't evaluate how accessible it is.

Ask fsologureng ?

**Comment by yardenshoham** [comment]
@fsologureng what do you think about this one?

**Comment by fsologureng** [comment]
> @fsologureng what do you think about this one?

This doesn't change anything from a11y's point of view because the bad header structure remains.

I would like to add that as long as the [resistance to changes in css](https://github.com/go-gitea/gitea/pull/22853#issuecomment-1426780953), and therefore in the html structure, is maintained, solving a11y's issues well will be very difficult; I already said this in the other thread; this could be solved by adding H1 to the actual page title (as Release page does), and adjusting styles to these H2s to make them look good.

**Comment by wxiaoguang** [comment]
What's your opinion about how to continue? Take this one as a quick fix, then improve other problems later? Or do you have a plan to propose new changes?

**Comment by fsologureng** [comment]
As I said, this changes nothing, I don't have a strong reason to blocking
it.

**Comment by wxiaoguang** [comment]
Thank you! Then I suppose this PR could be fine to fix the UI looking problems as a quick patch, then defer the a11y problems to new PRs together -- to avoid introducing too many uncertain changes at the moment.

**Review by yardenshoham — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
LG-TM bot

**Pull request merged**
