### PR TITLE
Fix only updated_unix when adding a comment

### PR DESCRIPTION
**Pull request by kolaente**
This pr fixes updating of the `created_unix` column of an issue when adding a comment.

While working on #3794, I discovered this destroyed my routine to update an issue deadline as it updated everything (not only `created_unix`), which lead to setting the deadline to the old deadline right after updating it to the new one.

Previous pr which added this behavior was #2204.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by techknowlogick** [comment]
LGTM. CI fail is unrelated.

**Review by techknowlogick — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by lafriks** [comment]
#3856 will fix CI

**Comment by lunny** [comment]
Please send a back port PR to v1.4

**Comment by kolaente** [comment]
@lunny Done with #3860

**Pull request merged**
