### PR TITLE
fix some ui bug about draft release

### LINKED ISSUE #15058: 404 Error on view draft release
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: 
  - [ ] No
- Log gist:
From the logs:
```
2021/03/19 22:33:42 ...ules/context/repo.go:824:1() [E] RepoRef invalid repo: branch or tag not exist: 
2021/03/19 22:33:42 ...s/context/context.go:184:HTML() [D] Template: status/404
```
## Description
I had an issue running this locally (Windows, using `make watch`) & confirmed on `try.gitea`. 

To recreate:
- Create new release, add required tag + title
- Save as draft
- Click on Release -> 404 error

If I select "edit" instead it works.

## Screenshots

image

### PR DESCRIPTION
**Pull request by a1012112796**
- should not show draft release in tag list because
  it will't create real tag
- still show draft release without tag and commit message
  for draft release instead of 404 error
- remove tag load for attachement links because it's useless

fix #15058

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by tomaswarynyca** [comment]
@a1012112796 Please resolve the conflicts.

**Comment by a1012112796** [comment]
waiting review

**Comment by lunny** [comment]
Could you add some tests?

**Comment by a1012112796** [comment]
> Could you add some tests?

done

**Comment by lunny** [comment]
> > Could you add some tests?
> 
> done

CI failed.

**Comment by richmahn** [comment]
@a1012112796 Doing a review for you today

**Comment by richmahn** [comment]
@a1012112796 Before I dig in, does this get drafts working like Github handles drafts for releases? I noticed just last week that GitHub does it different (doesn't require a tag, but if you do give it a tag it will lock the release to that commit ID even if the target branch head changes)

**Comment by a1012112796** [comment]
> @a1012112796 Before I dig in, does this get drafts working like Github handles drafts for releases? I noticed just last week that GitHub does it different:
> 
> 1. doesn't require a tag
> 2. if you do specify a tag it will lock the release to that commit ID even if the target branch head changes (i.e. makes the tag, but hides the release)

yes, in gitea curent design, it willn't create tag in git repository for  a draft release. so any link about git tag is not useable for a draft release. and it's also not correct to show draft release on tags list.

**Comment by richmahn** [comment]
@a1012112796 I noticed it still requires a tag if it is a draft. Github doesn't require that to be filled for a draft so that you can go back and tag it later (maybe want to set up the release info but developers/qa might still be trying to get a few more commits in). Is that outside the scope of this PR? https://github.com/go-gitea/gitea/issues/7693

**Comment by richmahn** [comment]
@a1012112796 Wow, already has conflicts again.

**Comment by richmahn** [comment]
For what it's worth, it looks like GitHub still locks the Draft to the commit ID of target at the time the draft is made, assigning a temporary tag to the draft release, and renaming it when the actual release is made, so probably useful in that you don't want the draft tag showing up in the list of tags for the repo.

**Comment by richmahn** [comment]
LGTM, just fix conflicts.

**Review by richmahn — APPROVED** [review]

**Review by richmahn — APPROVED** [review]

**Comment by richmahn** [comment]
@lafriks Needs your approval again.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
