### PR TITLE
Update JS and PY dependencies

### PR DESCRIPTION
**Pull request by silverwind**
- Update all JS and PY dependencies minus `@mcaptcha/vanilla-glue`
- Adapt to eslint rule rename
- Regenerate all SVGs  because of [new optimizations](https://github.com/svg/svgo/releases/tag/v3.0.4) from svgo.
- Tested mentions, mermaid, vue, api docs

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

**Comment by denyskon** [comment]
Backport?

**Comment by silverwind** [comment]
No real need to backport, so I'd say no

**Comment by delvh** [comment]
Why not?

**Comment by silverwind** [comment]
Well we ca, but at some point we should probably stop backporting stuff that brings no benefit :D

**Comment by silverwind** [comment]
Not gonna bother myself.

**Pull request merged**
