### PR TITLE
Add word-break to organization name and description

### LINKED ISSUE #24318: No word break for org name and description
### Description

Org home page:
image

### Gitea Version

1.20.0+dev-566-g8cc60ee01

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fix #24318

Before:
image
image
image

After:
image
image
image
image

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by yp05327** [comment]
`shared/user/org_profile_avatar` and `org/header` have almost same codes.
I will improve this in another PR after this one finished.

**Comment by yp05327** [comment]
image
This still seems not good enough. 🤔 

In GitHub:
https://github.com/yp05327/asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasda
image

**Comment by yp05327** [comment]
↑
Maybe we can improve this in another PR to change the design.
For example, convert owner name into owner's avatar with tooltip, and adjust the font size of repo name.
To make sure, at least in a normal maximized browser, repo name with 100 characters has no word break.

**Review by puni9869 — APPROVED** [review]

**Comment by puni9869** [comment]
@yp05327  is this PR complete?

**Comment by yp05327** [comment]
Before:
image
image
image
image

After:
image
image
image
image



Maybe this is not related to this PR:
image

**Pull request merged**
