### PR TITLE
Apply to become a maintainer

### PR DESCRIPTION
**Pull request by BLumia**
PRs: https://github.com/go-gitea/gitea/pulls?q=is%3Apr+author%3ABLumia+is%3Amerged

### CODE REVIEW

**Review by nanguanlin6 — APPROVED** [review]

**Review by delvh — APPROVED** [review]
Welcome :tada:

**Comment by techknowlogick** [comment]
Welcome @BLumia! Do you have a discord account?

**Comment by BLumia** [comment]
> Do you have a discord account?

Yes (also `@blumia`), and already in the Gitea server :)

**Comment by delvh** [comment]
@go-gitea/technical-oversight-committee can someone add @BLumia to the maintainers team?

**Pull request merged**
