### PR TITLE
Delete protected branch if repository gets removed

### PR DESCRIPTION
**Pull request by KN4CK3R**
If a repository gets removed the protected branch does not get removed too.
Added a doctor fix too.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
`mariadb  Ver 15.1`:

```
[3] Check consistency of database
 - [W] 13 protected branches without existing repository
```
--fix:
```
[3] Check consistency of database
 - [C] Error: Unsupported type whilst deleting orphaned objects
```

**Comment by 6543** [comment]
ok the detected issue looks like is also in `master` :/

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by 6543** [comment]
merged since we need this bugfix, the doctor bug is a other one ...

**Comment by KN4CK3R** [comment]
yes, the other bug gets fixed with #15657

**Pull request merged**
