### PR TITLE
doc: update command-line.en-us.md to match CLI provided by gitea 1.12.4

### PR DESCRIPTION
**Pull request by nodiscc**
ref. https://github.com/go-gitea/gitea/issues/2436

### CODE REVIEW

**Review by bagasme — APPROVED** [review]
ack

**Comment by zeripath** [comment]
I actually think this might be more confusing than just keeping the documentation up-to-date.

For example, the way this document is structured is that it looks like the `gitea doctor` command only does `recreate-tables` - however the reality is that `gitea doctor recreate-tables` is just a specific subcommand.

`gitea doctor` runs various checks, most of which can be viewed through `--list` and run individually with `--run` with autofixing by `--fix`. `gitea doctor recreate-tables` is a different thing - it's not a check.

Now, you could argue that `gitea doctor` should gain another subcommand `checks` but this documentation elides that subtly and makes it worse.

**Comment by 6543** [comment]
@nodiscc it would be nice if you just update outdated parts :)

**Comment by nodiscc** [comment]
> keeping the documentation up-to-date

I think the best way to keep up to date is to use the actual help text the program outputs, don't you think?

> the gitea doctor command only does recreate-tables - however the reality is that gitea doctor recreate-tables is just a specific subcommand.

I don't think `recreate-table` still exists in the current version. I don't see any mention of  `recreate-table` when I run `gitea doctor --list`. I think I just copied it from the previous version of the doc without checking. So that part was outdated too :) I will update accordingly.

> if you just update outdated parts

As I said most of this is outdated, and a maintenance burden, it's so much easier to copy-paste the output of `--help` since the program outputs a nice help text. Might as well update the whole page and get it **right**

I'll update this ASAP

**Comment by jolheiser** [comment]
Something to note, the CLI library we use also supports a `ToMarkdown` func that might be useful.

See sip's [`docs.go`](https://gitea.com/jolheiser/sip/src/branch/master/docs.go) and the [result](https://gitea.com/jolheiser/sip/src/branch/master/docs.md).

**Comment by nodiscc** [comment]
Sorry for the lag, I have updated my patch. You can view the resulting file [here](https://github.com/go-gitea/gitea/blob/f74764e9be452171048a7dc0d189a7729f1ac755/docs/content/doc/usage/command-line.en-us.md)

> I think the best way to keep up to date is to use the actual help text the program outputs, don't you think?
>> Something to note, the CLI library we use also supports a ToMarkdown func that might be useful.

That would indeed be the best solution. I tried, and failed (several times, think I'm not ready for golang yet). If you can send a patch implementing this I would gladly have a look. In the meantime I think this PR makes it better than the current version

**Comment by nodiscc** [comment]
Updated and rebased on master

**Comment by nodiscc** [comment]
@jolheiser @zeripath  @6543  @bagasme ping, does this look ok to merge?

Result can be seen [here](https://github.com/go-gitea/gitea/blob/f74764e9be452171048a7dc0d189a7729f1ac755/docs/content/doc/usage/command-line.en-us.md)

**Comment by techknowlogick** [comment]
@nodiscc 
Could you remove:
```
DEFAULT CONFIGURATION:
     CustomPath:  /usr/local/bin/custom
     CustomConf:  /usr/local/bin/custom/conf/app.ini
     AppPath:     /usr/local/bin/gitea
     AppWorkPath: /usr/local/bin
```
from the two outputs that have it? As these are likely not the defaults for many (and even if they were) some support requests may come not understanding that the their paths may be different.

Otherwise, this LGTM

**Comment by lunny** [comment]
Please resolve the conflict files.

**Pull request closed without merging**
