### PR TITLE
internal/ssh: ignore env command totally

### LINKED ISSUE #6085: Builtin SSH server bug when client sends environment variables
- Gitea version (or commit ref): 1.7.2
- Git version: 2.20.1
- OpenSSH version: 7.9p1
- Operating system: Linux on client, Docker official image on server
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Using the builtin SSH server, I have this in my `~/.ssh/config` on client side:
```
Host *
  SendEnv LANG LC_*
```

For an unrelated reason, `LC_MESSAGES` was set to an empty value. In this case all operations fail, with client side debug logs:
```
$ GIT_SSH_COMMAND="ssh -vvv" git clone [...]
debug1: Authentication succeeded (publickey).
Authenticated to [...].
[...]
debug1: Sending env LC_TELEPHONE = en_US.UTF-8
debug1: Sending env LC_MESSAGES = 
[...]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Server side logs (trace level):
```
[...a/modules/ssh/ssh.go:64 func1()] [E] env: exit status 1
```

If I set `LC_MESSAGES` to a non empty value, it works but the server logs makes me think some parsing is happening on server side and it fails:
```
[W] SSH: Invalid env arguments: '[]string{"", "LC_MESSAGES", "en_US.UTF-8"}'
[W] SSH: Invalid env arguments: '[]string{"", "LC_MONETARY", "en_US.UTF-8"}'
```

## Screenshots
N/A

### PR DESCRIPTION
**Pull request by sapk**
Looking at #6085, I discover that we do nothing with the env variable send via SSH. The [`env`](https://linux.die.net/man/1/env) command only set the variable for the command in args so calling it without a command is useless.

Proof:
```
env TEST=1
env | grep TEST
-> The variable TEST is not the set for the second call of env
 -- vs --
env TEST=1 env | grep TEST
-> The variable is TEST is set for the env command in arg of the env command :-)
```

The best solution would be to list the variable each time the env is called and add them to the array cmd.Env when calling exec but I think we would need a bit of filtering and I don't have enough background to know what to authorize or not.
So I suggest to simply ignore them (like we did previously by calling the `env` lonely) this will fix #6085 and windows user without the `env` command.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
Looks good. I think the code can be entirely removed instead of just being commented out, but I'm ok either way.

**Review by kolaente — APPROVED** [review]

**Comment by lunny** [comment]
Why not remove them but commented?

**Comment by sapk** [comment]
I kept it because in the future we should implement it and it explain why we have a switch with only one match left. But I can remove it if needed. 
In the meantime, I will create an issue related to the need to parse env command.

**Comment by lafriks** [comment]
I prefer that unneeded code is deleted :)

**Comment by sapk** [comment]
@lunny @lafriks done

**Comment by sapk** [comment]
Should I backport this PR ?

**Comment by lunny** [comment]
@sapk I don't think this need be back port since it's not a serious one.

**Pull request merged**
