### PR TITLE
Make backend code respond correct JSON when creating PR

### LINKED ISSUE #25351: Network Error when creating pull request
### Description

Press this button to create pull request and see the error

POST request returns HTML instead of json

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

image

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #25351

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Has some test failures.

**Comment by lunny** [comment]
Looks like there is no frontend changes?

**Comment by wxiaoguang** [comment]
> Has some test failures.

Fixed the tests

> Looks like there is no frontend changes?

Frontend has changed ahead.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Auto merge doesn't work due to " docker-dryrun Expected — Waiting for status to be reported "

**Comment by silverwind** [comment]
> Auto merge doesn't work due to " docker-dryrun Expected — Waiting for status to be reported "

Strange, as per https://github.com/go-gitea/gitea/pull/25329#issuecomment-1596398551, the check should have been removed.

**Pull request merged**
