### PR TITLE
Don't write to log NoCommitterAccount

### LINKED ISSUE #3602: NoCommitterAccount: user does not exist
- Gitea version (or commit ref): 1.3.3
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.4 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (no access to logs)
  - [ ] Not relevant
- Log gist:

## Description

I'm running my own instance of Gitea and I have some mirrors (linked to github mostly).
I have a lot of logs like this one which are errors:

```
[...ea/models/gpg_key.go:385 ParseCommitWithSignature()] [E] NoCommitterAccount: user does not exist [uid: 0, name: noreply@github.com, keyid: 0]
```

I don't know if this is relevant to the screenshot, plus I don't find any dock explaining what it means.

Does someone know what it means ? I have so many logs due to this thing I don't understand.

## Screenshots

image

### PR DESCRIPTION
**Pull request by thehowl**
It's way too verbose, and the information is also printed to the user
already. Fixes #3602.

### CODE REVIEW

**Review by Bwko — APPROVED** [review]

**Comment by lunny** [comment]
@thehowl You should determine if the `err` is `IsUserNotExist`. Only that error you could ignore the log.

**Comment by thehowl** [comment]
Done.

**Comment by lunny** [comment]
@thehowl there is a function could do that. see https://github.com/thehowl/gitea/blob/f42e2d4771b8d158a7dbb8ec5ab34ffa4e7e1893/models/error.go#L84

**Comment by lunny** [comment]
LGTM

**Pull request merged**
