### PR TITLE
Fix issue and commit status popup padding

### LINKED ISSUE #25249: No padding in issue preview on hover
### Description

When you hover over an issue number, popup has no paddings

https://try.gitea.io/stuzer05/test-preview/pulls/1

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #25249

Use "dialog" for the role

image

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm I think I would prefer `role` and `theme` to be set to `dialog` (a valid aria role) instead.

**Comment by wxiaoguang** [comment]
But it is a popup, not a dialog. Dialog means users couldn't interact with back elements.

**Comment by silverwind** [comment]
Yeah, it's not ideal. It's strange that the aria standard has no `popup` role, given that stuff like this exist:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup

**Comment by wxiaoguang** [comment]
Maybe it's fine to consider it as a non-modal dialog. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role

Updated in 045ae944407401b65e9513be2a50cd5bc71cecc4

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Yeah, definitely fine to use `dialog` as per that MDN link:

> Dialogs can be either non-modal (it's still possible to interact with content outside of the dialog) or modal (only the content in the dialog can be interacted with).

**Comment by silverwind** [comment]
Pushed one related fix for commit status which was also missing padding:

Screenshot 2023-06-14 at 22 25 16
Screenshot 2023-06-14 at 22 24 34

**Comment by wxiaoguang** [comment]
> Pushed one related fix for commit status which was also missing padding. Before and after:

I see the latest change, `role: dialog` looks much better to me. 👍

**Review by lunny — APPROVED** [review]

**Pull request merged**
