### PR TITLE
Use Go 1.20 for next release

### PR DESCRIPTION
**Pull request by wxiaoguang**

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Check if `make tidy` introduces any changes.

**Comment by wxiaoguang** [comment]
Quote from https://github.com/go-gitea/gitea/pull/24726#discussion_r1200469400

>  silverwind: With current policy of last two supported Go versions, we can only require Go 1.20 when Go 1.21 is out, which is in around 3 months. Maybe we should change that policy though.

> wxiaoguang: Hmm, yes, the problem is that if we still use Golang 1.19, then after Golang 1.21 gets released, Golang 1.19 won't get any updates. So, I think it's good to make Gitea's release can use active Golang version in its lifecycle (it's not a must if most people prefer to keep Gitea 1.20 on Golang 1.19)
> I also remembered that somewhere mentions that "Gitea supports the last two go versions", but I can not find it now .... where is it? 🤣 Has it already been removed?

**Comment by wxiaoguang** [comment]
> Check if `make tidy` introduces any changes. Though I guess CI would fail if it would.

I have done so before commit. And CI passes.

**Comment by silverwind** [comment]
Re https://github.com/go-gitea/gitea/pull/24726#discussion_r1200476367:

README says

> make backend which requires [Go Stable](https://go.dev/dl/), required version is defined in [go.mod](https://github.com/go-gitea/gitea/blob/main/go.mod).

"Go Stable" is equivalent to "last two versions":

image

**Comment by wxiaoguang** [comment]
Oh yes, that's also written by me (#19918), the reason is the same: 

> Use Golang 1.18 (as minimal requirement) for Gitea 1.17 release, make sure the Golang version is still actively supported during Gitea 1.17 lifecycle.

image

So, theoretically speaking, more stricter `go.mod` doesn't violate this rule.

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
Seems ok if there is no easy way to get it compatible with 1.19.

**Review by yardenshoham — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Pull request merged**
