### PR TITLE
Add missing parameter for error in log message

### PR DESCRIPTION
**Pull request by Gusted**
- Adds a `%v` for the last parameter, `err`.

### CODE REVIEW

**Comment by Gusted** [comment]
Noticed in the logs of CI. https://drone.gitea.io/go-gitea/gitea/56794/2/16
image

**Review by delvh — APPROVED** [review]
:laughing: how long went that unnoticed?

**Comment by delvh** [comment]
To answer my own question: 9 months (https://github.com/go-gitea/gitea/commit/8de44d1995e73ec139ede5626466af1fce8c571a). Nice.

**Comment by wxiaoguang** [comment]
> To answer my own question: 9 months ([8de44d1](https://github.com/go-gitea/gitea/commit/8de44d1995e73ec139ede5626466af1fce8c571a)). Nice.

Then not that serious 😁 

ps: LGTM

**Review by lunny — APPROVED** [review]

**Pull request merged**
