### PR TITLE
Use readonly input form to show the validated OpenID URI

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by lunny** [comment]
there is any screenshot?

**Comment by strk** [comment]
No screenshot. Imagine another input field, like the others.
Just you cannot change it.

**Comment by strk** [comment]
As I'm now on a computer with easier-to-take-screenshotter, here you go:

readonly-connect
readonly-create

**Comment by pgaskin** [comment]
@strk Speaking of screenshotters, use Kazam on linux. It is the best one.

**Comment by pgaskin** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
