### PR TITLE
Add support for `npm unpublish`

### PR DESCRIPTION
**Pull request by KN4CK3R**
related to #20670

This PR adds support for `npm unpublish` to delete a package.

There is a problem with the current npm cli [not working with private registries](https://github.com/npm/cli/issues/4331) which prevents testing (for me). Maybe someone with more npm knowledge can help.

### CODE REVIEW

**Comment by silverwind** [comment]
Maybe test with last known working cli, e.g. `npm i -g npm@8.3.0` to downgrade global npm on your machine.

**Comment by KN4CK3R** [comment]
I did but that version fails to resolve the delete url, so that may be fixed in the new version. 🤷‍♂️

**Comment by silverwind** [comment]
Odd, maybe try with `yarn` or `pnpm`, just to confirm it's working :D

**Review by silverwind — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Both do not support unpublish...

**Comment by silverwind** [comment]
Hmm okay. Generally I think unpublish should probably be abled to disabled via config, it's considered bad practice as it breaks dependants. Public npm [restricts](https://docs.npmjs.com/policies/unpublish) unpublish to the first 72h after publish or for unpopular packages.

**Comment by lunny** [comment]
A configuration to disable it is better.

**Review by wxiaoguang — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
It should be fine to use `Write` permission to control the deletion, it's the same to other logics at the moment.

The new config option for deletion policy may be done by a repo setting in the future.

**Comment by silverwind** [comment]
Still think one global package deletion policy would make sense, not only for npm but other package types as well.

**Comment by KN4CK3R** [comment]
I will add this to the package todo list.

**Pull request merged**
