### PR TITLE
Cleaner ui for admin, repo settings, and user settings page (#1269)

### PR DESCRIPTION
**Pull request by pgaskin**
~I will post a video after I test it.~ https://transfer.sh/EYam0/newui.mp4

**Please review this asap, because many templates have been modified, and I do not want any conflicts**

\cc @bkcsoft @tboerger @lunny @strk

### CODE REVIEW

**Comment by geek1011** [comment]
I'm testing it right now

**Comment by bkcsoft** [comment]
LGTM (merge is blocked until alpine fixes their shit 😉 )

**Comment by pgaskin** [comment]
@strk or @bkcsoft Can you merge this now?

**Comment by strk** [comment]
Only [owners](https://github.com/orgs/go-gitea/teams/owners) can merge it :(

**Comment by strk** [comment]
Oh, and "team maintainers" (@andreynering and @metalmatze) - I shall note that role (team maintainers) is not mentioned in the [CONTRIBUTING](https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md) file, so it's not really clear how they are elected (please feel free to file an issue to discuss this)

**Comment by bkcsoft** [comment]
> The owners or the team maintainers may invite the contributor.

@strk That role is mentioned, but not in any length, please make an issue 😉

**Comment by lunny** [comment]
fixed #1269

**Comment by Fastidious** [comment]
See:

screen shot 2017-03-15 at 21 34 37

Close attention to `Organisations`.

**Comment by bkcsoft** [comment]
@Fastidious US writes "organisations", UK writes "organizations". #NotABug 😂

**Comment by Fastidious** [comment]
@bkcsoft sorry, it is about the icon too close to the word (#certainlyabug), not the spelling of it (#ofcoursenotabug).

**Comment by plessbd** [comment]
#offtopic

@bkcsoft you have it backwards, American English: organizations, British English: organisations

http://writingexplained.org/organisation-vs-organization-difference

For a second I thought I had been spelling it "wrong" my whole life, same with grey and gray, I never know which one I am supposed to use...

And don't get me started on Aluminum vs Aluminium

English = Annoying

**Comment by Fastidious** [comment]
@plessbd thanks for the contribution. 😂 I wasn’t pointing out the spelling of a word, as explained above, but the fact that the `Organizations`’s icon is too close to the word itself.

**Comment by bkcsoft** [comment]
@Fastidious Ooh that explains it 😆 In any case, I think it's just the icon being broken. Should probably be fixed though 🙂

**Comment by pgaskin** [comment]
Speaking of the new ui I did, GitHub just changed their search to a horizontal nav.

**Comment by strk** [comment]
Damn, we lost the advantage ! :)

**Pull request merged**
