### PR TITLE
Make heatmap colors more distinct

### LINKED ISSUE #13529: Heatmap Color Shade
- Gitea version (or commit ref): 1.14.0+dev-196-g4117a443c (built from source with `TAGS=bindata make generate build`)
- Git version: 2.28.0
- Operating system: Debian 10 (run via systemd)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (not relevant)
- Log gist:
(not relevant)

## Description
Consider following heatmap screenshot from my instance:
heatmap

The gradation between level-2 and level-1 color shade is subtle; I can hardly differentiate both of them. The shade for the heatmap should be distinct enough per level, so that the colors can be differentiated easily.

Color for level-1 is `#8db4db`, and for level-2 is `#5791cb`

## Screenshots
(see above)

### PR DESCRIPTION
**Pull request by silverwind**
Screen Shot 2020-11-12 at 20 55 57
Screen Shot 2020-11-12 at 20 55 50

The second shade falls out of the scheme of 20% increases because it was too hard to see at just 20% opacity but it seems still distinct enough to me from the third color.

<details>
<summary>Random data generator code</summary>

```js
    this.values = new Array(400).fill().map((_, i) => {
      const date = new Date(new Date().setDate(new Date().getDate() - i));
      let count = Math.round(Math.random() * 100);
      if (count % 3 === 0) count = 0;
      return {date, count};
    });
```
</details>

Fixes: https://github.com/go-gitea/gitea/issues/13529

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by bagasme** [comment]
@silverwind not so much difference between second and third shade (on default scheme)

**Comment by silverwind** [comment]
Last I tested, there was barely any difference between grey background and 20% opacity primary color, at least on my screen. Will check again later.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
applied your patch @silverwind 
maybe it's just me but I also don't think the distinction between certain levels is perfectly visible 🙈 .
it is a laptop screen but it used to be a little more distinct (before the switch to a defined colour palette recently).
image
image

**Comment by silverwind** [comment]
Yes, at level 2 and 3 still need more distinction, don't land this yet.

**Comment by silverwind** [comment]
Another variation pushed that uses opaque colors and goes a bit more into the darker shades, how does that look to you two?

image
image

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Another variation pushed that uses opaque colors and goes a bit more into the darker shades, how does that look to you two?
> 
> image
> 
> image

lemme check 🚀

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
image
image
Tried it.
Looks fine 💯 
Maybe the first level could have a little more opacity (so as not to be as prominent, as it's the least significant one)?

**Comment by silverwind** [comment]
Ok, made the grey color less opaque (70% as before).

**Review by 6543 — APPROVED** [review]

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Ok, made the grey color less opaque (70% as before).

thanks, building...

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
