### PR TITLE
Don't run ci if only markdown files on root directory changed

### PR DESCRIPTION
**Pull request by lunny**
If changelog and other markdown files on root directory are updated, there is no reason for CI to run.

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
this might skip the docker build on tag when the tag happens on a changelog.md only commit

**Comment by silverwind** [comment]
More similar stuff could be done like don't run backend tests when only frontend changes, but I'm afraid this will need more individual pipelines, which brings the downside that each of them needs separate dependency installation, so it may slow down full CI runs.

**Comment by lunny** [comment]
> this might skip the docker build on tag when the tag happens on a changelog.md only commit

But looks like `*.md` only match all markdown files on the root folder? So only below files are affected

```
CHANGELOG.md       CODE_OF_CONDUCT.md CONTRIBUTING.md    README.md          README_ZH.md       SECURITY.md
```

**Comment by lunny** [comment]
Closed as we are converting to actions

**Pull request closed without merging**
