### PR TITLE
Support slashes in release tags

### LINKED ISSUE #12861: [Bug] [UI] Release Page dont support tags with "/"
Gitea Version: 1.13.0+dev-620-gb2bda1159

test url: https://gitea.com/gitea/go-sdk/releases/tag/gitea/v0.13.0

### PR DESCRIPTION
**Pull request by zeripath**
Fix #12861

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by 6543** [comment]
starting point :) but do not work - I'll have a look at it

**Comment by mrsdizzie** [comment]
Is title meant to say forward slashes based on linked issue?

**Comment by zeripath** [comment]
Sorry @mrsdizzie yes of course - I blame @6543

**Review by techknowlogick — APPROVED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
macaron is acting wrong!!
this should be right but if you try it, all tag pages become 404

~~so I guess it is a macaron bug :/~~

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
@6543 Is there still a break?

**Comment by bagasme** [comment]
`releases/` page work but 404 error for `tags/`

**Review by bagasme — APPROVED** [review]
ack: creating release tags with slashes worked

**Comment by 6543** [comment]
yes still breaks

**Comment by zeripath** [comment]
@6543 exactly which URLs are still broken?

Do you mean the URLs governed by:

https://github.com/zeripath/gitea/blob/912d577f60138bf0e8c0fa4f9ad222cfbd4ef7e5/routers/routes/routes.go#L629

Because I haven't changed those and frankly they need to be fixed to path escape the tag rather than changing the routing.

(It's worth noting that some of the first things I did in Gitea were fixing broken escaping and I still am doing so - we really need to get on top of this.)

**Review by 6543 — APPROVED** [review]
this did it

**Comment by zeripath** [comment]
Fixed now! Sorry I wasn't testing this properly as I didn't realise how to create a release properly.

---

As an aside - this is a terrible UI - tags get autoreleased but then you can't easily create a release from one without stating the name. I think this needs looking at again.

**Comment by 6543** [comment]
Pleace send backport ;)

**Pull request merged**
