### PR TITLE
Fix INI parsing for value with trailing slash (#26995)

### LINKED ISSUE #26977: INI value with trailing slash causes bugs
eg:

```
[foo]
key = C:\
xxx = yyy
```

The current code reads: `key = C:\xxx = yyy` and can't read `xxx`

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #26995 by @wxiaoguang

Fix #26977 (a temp fix)

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by delvh** [comment]
I am in favor of reverting this backport.
It is a breaking change.

**Comment by techknowlogick** [comment]
@delvh 1.20.4 broke this, and so this is reverting back to prior behaviour.

**Comment by delvh** [comment]
What about 1.20.4 broke it?

**Comment by wxiaoguang** [comment]
Is there any feedback? Who is affected and how it affects?

**Comment by techknowlogick** [comment]
@delvh it's due to an upstream golang change between Gitea .3 and .4. Can't find the original ticket on mobile but perhaps @wxiaoguang can send it.

**Comment by wxiaoguang** [comment]
> it's due to an upstream golang change between Gitea .3 and .4.

I don't understand and I do not think it is an "upstream Golang change".

**Comment by techknowlogick** [comment]
@wxiaoguang I thought the user who was having the problem was using 1.20.3 ok, but then when they updated to 1.20.4 the configuration didn't work. My memory may have had a bitflip 😆 so could you give background on this change?

**Comment by wxiaoguang** [comment]
https://discord.com/channels/322538954119184384/561007778139734027/1149706188548755606

Not only one user has reported such problem, if they put Gitea in Windows root directory like `E:\`

**Pull request merged**
