### PR TITLE
Add missed return to actions view fetch

### LINKED ISSUE #27213: JS error on action run page
### Description

[Bildschirmaufzeichnung vom 2023-09-23, 17-34-22.webm](https://github.com/go-gitea/gitea/assets/47871822/6045d6ed-bb63-4e39-aa19-303b21f4d2d6)

Switching from an action run page to another page, an error appears saying `JavaScript promise rejection: TypeError: t is undefined`

### Gitea Version

1.21.0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker-Compose

### Database

SQLite

### PR DESCRIPTION
**Pull request by silverwind**
Should fix: https://github.com/go-gitea/gitea/issues/27213

@denyskon can you test this? I can not reproduce this error locally.

### CODE REVIEW

**Comment by denyskon** [comment]
Unfortunately, I cannot test it where I get the error, as that is an instance I use in production, and as it runs off docker....

**Comment by silverwind** [comment]
Can you show exact line/column of the pretty-printed devtools source? Then I'd know for sure I guess.

We should probably think about enabling source maps for prod builds, too much of a pain to trace such errors.

**Comment by denyskon** [comment]
grafik
It points to the closing curly brace of the catch statement

**Comment by silverwind** [comment]
I see, so the `t` refers to the fetch return value in the screenshot. I'm pretty positive this will fix it then.

**Review by denyskon — APPROVED** [review]

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27291 will introduce a sourcemap for index.js, so we'll have a easier time debugging this next time.

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
