### PR TITLE
Fix link to customizing-gitea

### PR DESCRIPTION
**Pull request by kodermho**
The link to customizing-gitea in the label documentation is broken. This PR should adjust the relative path to fix the link

### CODE REVIEW

**Review by silverwind — APPROVED** [review]
I wonder if there is a linter to catch these.

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
@kodermho can you also fix the same link in `docs/content/doc/usage/labels.zh-cn.md`?

**Comment by silverwind** [comment]
Actually I think this may need this format:

```
{{< relref "doc/administration/customizing-gitea.en-us.md" >}}
```

At least I see that format used in various docs files, but not consistently.

**Comment by delvh** [comment]
The problem is the explicit section label.
That's probably why it isn't a `relref` yet.
I initially wanted to note that as well, then I noticed.

**Comment by silverwind** [comment]
I wonder what's the point of these `relref`. Is this some custom processing that we do?

**Comment by delvh** [comment]
AFAIK, it's a function we've

**Comment by silverwind** [comment]
Ah, this is https://gohugo.io/functions/relref/, but we are not actually using it in the recommended way.

>  For normal links, we can never be sure as they might point at an external URL outside our control.

Anything that starts with `./` can be statically analyzed and I think writing a linter for this "standard" format would be quite trivial actually.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
