### PR TITLE
Small UI fixes on form titles

### PR DESCRIPTION
**Pull request by joubertredrat**
Small fixed with center title, as below
gogs-title-before
gogs-title-after

Reference: https://github.com/gogits/gogs/pull/3786

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by bkcsoft** [comment]
@tboerger did we remove the less-files? :)

**Comment by tboerger** [comment]
Ooops, totally forgot the less file. @joubertredrat please update the .less file.

**Comment by joubertredrat** [comment]
wtf, sorry guys, was PR from wrong branch

**Pull request closed without merging**
