### PR TITLE
proposal: add max height limit and overflow for organization profile

### PR DESCRIPTION
**Pull request by a1012112796**
as title, maybe usefull for user to jump to repository quickly when the profile READEME is too long.
example view:

屏幕截图 2024-06-13 091330

### CODE REVIEW

**Comment by foxday** [comment]
Why not implement the same behaviour as Gitea user profile? Would be awesome to have the same github behaviour instead of a separate functionality.

**Comment by silverwind** [comment]
How does GitHub solve it? Surely there must be a way to limit overly long profile readmes on both org an user.

**Comment by silverwind** [comment]
Tested on GitHub, there is no limit and [here](https://github.com/testorg-los6aif9aol6CohQuoFier2ozer6Vei) is a org with a 20k lines README. Tbh, I still prefer that over any nested scroll mechanisms.

**Comment by axeldvera** [comment]
> Tested on GitHub, there is no limit and [here](https://github.com/testorg-los6aif9aol6CohQuoFier2ozer6Vei) is a org with a 3k lines README. Tbh, I still prefer that over any nested scroll mechanisms.

This works fine as long as the readme is viewed from a separate tab (Overview) and not at the top of the "Repositories" tab

**Comment by a1012112796** [comment]
> > Tested on GitHub, there is no limit and [here](https://github.com/testorg-los6aif9aol6CohQuoFier2ozer6Vei) is a org with a 3k lines README. Tbh, I still prefer that over any nested scroll mechanisms.
> 
> This works fine as long as the readme is viewed from a separate tab (Overview) and not at the top of the "Repositories" tab

a little not like too many tabs.

**Comment by techknowlogick** [comment]
I'm in favour of the alternative PR you created.

**Pull request closed without merging**
