### PR TITLE
[Backport/v1.15] Escape git fetch remote (#19487)

### PR DESCRIPTION
**Pull request by 6543**
backport #19487

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
Lunny mentioned that there would be some docker tag conflicts. I'm not sure whether it could be a blocker. If there is a chance, a fix for 1.15.x is good.

**Comment by lunny** [comment]
When you tag in v1.15, latest will point to the newly created docker. Then users will switch from 1.16.7 to 1.15.12 when upgrade.

**Comment by lunny** [comment]
If we won't tag, why did you change the ci file?

**Comment by 6543** [comment]
hmm the project did fal apart :O - ci just dont like to run anymore

**Pull request closed without merging**
