### PR TITLE
Revert "Remove fomantic image module (#21145)"

### LINKED ISSUE #22818: Avatar and labels misalignment
### Description

Up to Gitea 1.16, avatar and labels were aligned correctly. Since the refactoring of the Avatar component, styling breaks in element listings (e.g. users, organizations, etc). 

This issue is easily fixed by:

* replacing the `vm` class with `image` in the avatar component
* or adding `display: inline-block` to the `content` div next to the avatar

This breaks in other places, such the landing page of a repo.

## Gitea 1.16
image

## Gitea 1.19
image

### Gitea Version

1.19

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

Chrome 109.0.5414.119

### PR DESCRIPTION
**Pull request by Zettat123**
Close #22818.

This reverts commit afdab9d8d495590f215f9a2a54d925ed72ad75d0.

Misalignments in #22818 could be fixed.

### CODE REVIEW

**Comment by silverwind** [comment]
Can we just selectively restore the CSS rules that fix the cases instead? We aim to remove Fomantic, this gets us further from that. Anyways, landing this is better would be better than leaving it broken.

**Comment by wxiaoguang** [comment]
I do not think you need to do this. The misalignment could be fixed by fine-tuned CSS styles.

**Comment by Zettat123** [comment]
Yeah, I think I can fix the misalignment by tuning CSS rather than revert. I will close this PR and open another PR to fix it.

**Comment by silverwind** [comment]
You can put the rules in https://github.com/go-gitea/gitea/blob/main/web_src/less/_base.less, near the other fomantic rules.

**Pull request closed without merging**
