### PR TITLE
Fix code formating

### PR DESCRIPTION
**Pull request by mscherer**
"make fmt" always want to change this, so better merge it so
we do not introduce unrelated changes when running "make fmt" later

### CODE REVIEW

**Comment by mscherer** [comment]
So "make fmt" didn't catch this formatting error, but "make lint" did. I guess I stumbled on something weird. I am closing the PR, as I guess I surely did something wrong.

**Comment by wxiaoguang** [comment]
I think it comes from this PR:

* https://github.com/go-gitea/gitea/pull/17684

I just wrote our own formatter, used imports comes first, dummy imports (`_`) comes later.

**Comment by wxiaoguang** [comment]
Oh, the lint problem is caused by a space, I think we can re-open this PR

**Comment by mscherer** [comment]
So seems I can't reopen the PR, so I have to recreate it. "make fmt" had to be run twice to correct the issue.

**Comment by wxiaoguang** [comment]
Thanks. That's really a rare case 😂  I will improve our code formatter later.

**Pull request closed without merging**
