### PR TITLE
Restructure JS files

### PR DESCRIPTION
**Pull request by silverwind**
Pure file renames. Now the folders in `web_src` have no nested folders in it, everything inside those folders is "flat" which I find easier to work with and the amount of files in `features` is drastically reduced by moving all `repo-*` files to `repo` subdirectory.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Please do not do so too early.

It would make backporting much more difficult.

**Comment by silverwind** [comment]
Hmm we could postpone this after 1.22 release. I would also like to do the typescript which is another big upcoming refactor.

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/pull/30165#issuecomment-2026753913

Quote my comment again:

> I think it needs a clear roadmap about how to refactor. I ever wrote something in https://docs.gitea.com/contributing/guidelines-refactoring
> 
> > Non-bug refactoring is preferred to be done at the beginning of a milestone, it would be easier to find problems before the release.
> 
> What I meant for `at the beginning of a milestone` is:
> 
>     1. It should start at next milestone's beginning when the last release is overall stable (eg: after RC or after the first 1.22.1 or 1.22.2 with bug fixes)
> 
>     2. It should start before the RC period, to avoid introduce unnecessary regressions.
> 
> 
> However, since there are really a lot of frontend refactorings for 1.22 (especially when it was going into freezing time), so I think this time it is still better to merge some PRs back to 1.22, to make the future bug fixes easier to backport.
> 
>     * Then clearly define 1.22-rc1 as a "stable" RC, don't backport any unnecessary PRs at that time.

**Comment by silverwind** [comment]
So eiter we wait with this 1-2 months or do it now and backport it (assuming not too much work). I think I lean towards backporting it.

**Comment by wxiaoguang** [comment]
> So eiter we wait with this 1-2 months or do it now and backport it (assuming not too much work). I think I lean towards backporting it. It's completely without risk, eslint catches all `import`-related errors.

But there are still some frontend refactoring not backported. I don't know how you would clean up these problems.

TBH the 1.22-rc0 release procedure is totally a mess, since it is already a mess, I could be neutral and won't block.

**Comment by silverwind** [comment]
Let's do this later together with the typescript.

**Pull request closed without merging**
