### PR TITLE
WIP: Fix PR approvals counting

### PR DESCRIPTION
**Pull request by lunny**
Sometimes, when a user with no write permission of a repository but in the whitelist of approvals in the protected branch. If he refused a PR and then approved a PR, the approval will not be counted.

### CODE REVIEW

**Comment by silverwind** [comment]
Is adding a test possible?

**Comment by lunny** [comment]
> Is adding a test possible?

This PR is not finished and in fact, it hasn't resolved any problems. I think maybe it should become a refactor after it is finished.

**Comment by silverwind** [comment]
> > Is adding a test possible?
> 
> This PR is not finished and in fact, it hasn't resolved any problems. I think maybe it should become a refactor after it is finished.

Make sure to set WIP status then 😆

**Comment by lunny** [comment]
This PR doesn't fix anything. Just some slight refactor.

**Pull request closed without merging**
