### PR TITLE
add sqlite MaxOpenConns to 1 for fixing database locking

### PR DESCRIPTION
**Pull request by lunny**
see https://github.com/mattn/go-sqlite3#faq 
ref: https://github.com/go-gitea/gitea/issues/2040#issuecomment-417893409

### CODE REVIEW

**Comment by techknowlogick** [comment]
This might not work because even if max connections is set to 1, multiple processes will still try to connect to DB (for example `gitea serv` via SSH) and they will all need one connection per process.

**Comment by sapk** [comment]
The solution could be to use the gitea api in `gitea serv` in place of accessing the database directly ?

**Comment by lunny** [comment]
@techknowlogick @sapk  that's why we have `/internal/` routes but I haven't moved all the requests.

**Comment by techknowlogick** [comment]
@lunny that makes sense.

**Comment by sapk** [comment]
I could try to migrate serv to /internal and not use the models/database access.

**Comment by jonasfranz** [comment]
I've tried this a time ago and it resulted in random errors like the server hanging up.

**Comment by lafriks** [comment]
I think this should be closed in favor of #4886

**Comment by techknowlogick** [comment]
Closing as SQLite locking has mostly been resolved in other PRs

**Pull request closed without merging**
