### PR TITLE
add touch-icon with background

### PR DESCRIPTION
**Pull request by NiTRoeSE**
To prevent this ugly glitch while minimize app to homescreen because of transparent background of favicon.

IMG_0329

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

### CODE REVIEW

**Comment by silverwind** [comment]
Those images come from this [make task](https://github.com/go-gitea/gitea/blob/master/Makefile#L529), so it'd need to be added there. As for adding the background, you could try something like `convert favicon.png -fill white -opaque none apple-touch-icon.png`.

**Comment by NiTRoeSE** [comment]
> Those images come from this [make task](https://github.com/go-gitea/gitea/blob/master/Makefile#L529), so it'd need to be added there. As for adding the background, you could try something like `convert favicon.png -fill white -opaque none apple-touch-icon.png`.

.. thanks for the hint, in fact i have no clue from go but wanted to help to fix this little cosmetic problem.  ☺️  ..I hope its now in a correct way, if not i think its better that someone which have the needed knowledge do this job. regards 🙂

**Comment by techknowlogick** [comment]
> in fact i have no clue from go but wanted to help to fix this little cosmetic problem

no worries. thanks for this PR :) I think one last thing that needs to be done is if you run the make task and then commit the generated image from that

**Comment by NiTRoeSE** [comment]
> > in fact i have no clue from go but wanted to help to fix this little cosmetic problem
> 
> ..I think one last thing that needs to be done is if you run the make task and then commit the generated image from that

Ok 🙂, maybe a stupid question but how do i run the make task ..must it be done locally on my machine or is it automated processed through drone ci ? ..and if its done through drone, where can i find the newly generated files to commit it?

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Generated image still needs to be included in conmit

**Review by lafriks — DISMISSED** [review]
Generated icon missing

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
The image still has some transparent pixels left, making it look bad on a dark background:



I'd say revert this commit. If IOS can not deal with transparency, it's IOS's fault, not ours.

**Comment by NiTRoeSE** [comment]
> The image still has some transparent pixels left, making it look bad on a dark background:
> 
> 
> 
> I'd say revert this commit. If IOS can not deal with transparency, it's IOS's fault, not ours. I certainly prefer transparency over a opinionated white background. It certainly does not look out of place to me in the animation in the OP.

I ran make yesterday in the the evening, i needed more time to figure out how to do it because its my first time with go. As far i could see yesterday there was no transparency left and the icon looked good. I take a look again this evening and give feedback here..

Except of this .. why not just add an photoshop generated icon for this case ? (I could create one...) Or in other words, why must it be generated through makefile?

**Comment by 6543** [comment]
@NiTRoeSE it doesnt have to ... For me `generate-images` looks like a relict from the past ...
@techknowlogick any opinion of removing `generate-images` ?

**Comment by NiTRoeSE** [comment]
> it doesnt have to ... For me `generate-images` looks like a relict from the past ...

I'm sorry if I have initiated a discussion of principles about the icon now.
I just asking to better understand why this is done in this way. ( I'm newby to this project ;) )
For me its also okay if the commit is reverted. I think its also possible to achieve the goal simply through customizing possibilities from Gitea. So i just want to say.. i completely understand if there is no time to investigate in such a small cosmetic "problem".  ;) 

If you guys want to investigate and need icons made with photoshop , then i will gladly offer my help.

**Comment by 6543** [comment]
@NiTRoeSE I think just creat a new pull and add your the icon you mad with your photo-edit-software ;)

and hopefully this time we dont need to revert :sweat:

**Comment by 6543** [comment]
@silverwind to:
> If IOS can not deal with transparency, it's IOS ...

if i understand correctly `rel="apple-touch-icon"`  is only take in account by apple?
so if we add a icon for apple dev it wont afect android/wind/co ...
so why not generate a icon for ios manualy :) as @NiTRoeSE proposed to create

**Comment by silverwind** [comment]
Fix PR: https://github.com/go-gitea/gitea/pull/10065

**Pull request merged**
