### PR TITLE
Backport: Sync releases table with tags on push and for mirrors (#2459)

### PR DESCRIPTION
**Pull request by lafriks**
* Sync releases table with tags on push and for mirrors

* Code style fixes

* Fix api to return only releases

* Optimize release creation and update
Minimize posibility of race conditions

* Fix release lower tag name updating

* handle tag reference update by addionally comparing commit id

### CODE REVIEW

**Comment by lunny** [comment]
backport from #2459

**Comment by daviian** [comment]
LGTM

**Comment by daviian** [comment]
Make LG-TM work

**Comment by daviian** [comment]
@lafriks Tested and it does exactly the same as on master ;-)

**Comment by daviian** [comment]
@lafriks Can you do a force push / rebase to restart drone build?

**Comment by lafriks** [comment]
~~I will after other PR is merged as I will need to resolve conflicts then~~ EDIT: done

**Comment by sapk** [comment]
Trusted LGTM

**Pull request merged**
