### PR TITLE
Fix bound address/port for caddy's certmagic library (#15758)

### PR DESCRIPTION
**Pull request by zeripath**
Backport #15758

* Fix bound address/port for caddy's certmagic library

* Fix bug

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
Make lgtm work

**Comment by bminer** [comment]
I don't think this PR solves the issue. Still debugging...

**Comment by zeripath** [comment]
Some you win -- some you lose...

**Comment by bminer** [comment]
Yeah... so I have it sorted now. I will make a new PR referencing this one. Sorry for the confusion. Took me a bit to build gitea on ARMv7 with cgo.

**Pull request merged**
