### PR TITLE
Use more toned colors for selected line

### PR DESCRIPTION
**Pull request by CirnoT**
chrome_2020-05-18_22-06-16

### CODE REVIEW

**Comment by lafriks** [comment]
How does it look in dark theme?

**Review by lafriks — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by CirnoT** [comment]
@lafriks It's very subtle change for arc-green; not that the older color was ever used properly in arc-green to begin with, so...
chrome_2020-05-18_22-27-57

**Comment by techknowlogick** [comment]
ping LG-TM

**Comment by lafriks** [comment]
please send backport

**Pull request merged**
