### PR TITLE
refactor(model): update user method.

### PR DESCRIPTION
**Pull request by appleboy**
as title.

### CODE REVIEW

**Review by sapk — APPROVED** [review]

**Comment by thehowl** [comment]
LGTM

**Comment by lafriks** [comment]
Is this PR really does not change behaviour?

**Comment by thehowl** [comment]
I'm quite sure it should not: [this](https://github.com/go-xorm/xorm/blob/master/session_update.go#L145-L164) is the update code on xorm, so it is always run. Are you perhaps referring to the code running in cases where it wouldn't have before? (e.g. user_mail.go#L225)

**Comment by appleboy** [comment]
@lafriks No, just like @thehowl say.We always get user data from `x.Get(user)` before execute the `Update(user)` method.

**Comment by lunny** [comment]
LGTM

**Pull request merged**
