### PR TITLE
Fix #4090 by escaping filename page/img link (without path) for short link

### LINKED ISSUE #4090: wiki: URL encoding bug
- Gitea version (or commit ref): 728cc27
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
    - https://try.gitea.io/yasuokav/link-test/wiki/Home
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description
Since #4058, the links are no longer encoded.
But the URLs(files name) of the existing pages or new pages are still encoded.

The original link is
`https://try.gitea.io/yasuokav/link-test/wiki/Test%3F`
but now is
`https://try.gitea.io/yasuokav/link-test/wiki/Test?`

## Screenshots
N/A

### PR DESCRIPTION
**Pull request by sapk**
And add more tests

### CODE REVIEW

**Comment by techknowlogick** [comment]
Comment to link issue to PR #4090

**Comment by techknowlogick** [comment]
CI fail. I restarted Drone, but same fail happened. Looks like it is related to this change.

**Comment by lafriks** [comment]
Seems to me it breaks links like `path/name.jpg` as it escapes also `/` characters

**Comment by sapk** [comment]
@lafriks You are totally right!
I first think of removing it for image link but choose to only url-encode when we have only a filename like [[Test?#]]. The user could still use the format [[some/path/Test?#|some/path/Test%3F%23]] for advanced use cases.

**Comment by lafriks** [comment]
Or probably you can escape only last part by splitting `/`

**Comment by sapk** [comment]
@lafriks I think of it but I didn't go that way as I find it kind of strange to encode only part of the url and a other solution could be to encode all except /. 
I did some testing on github to know how they do it and I find that they encode all url and translate `/` in `-` and that they don't do support [[ ]] in issue comment but doing so may break how we do it and previous link.

So I choose a simple implementation only supporting filename without path but I can change if needed.

**Comment by lafriks** [comment]
I would prefer to have behaviour same as GitHub so that imported/mirrored GitHub wiki/md would work same also on Gitea but that probably can be done in other PR

**Review by lafriks — APPROVED** [review]

**Review by jonasfranz — APPROVED** [review]

**Comment by lunny** [comment]
@sapk please send a back port to v1.4

**Pull request merged**
