### PR TITLE
feat: allow set default merge style while creating repo

### PR DESCRIPTION
**Pull request by ttys3**
feat: allow set default merge style while creating repo

currently, we have something like `DEFAULT_BRANCH`, allow to init a repo with global pre-configured value while creating a repo.
but no way to do this for PR merge style, user have to do this over and over if they want all repo created with default merge style set to `squash` other than default `merge` style.

this PR allow user to set the default value while creating repo via the ini config file, user can below to gitea `app.ini`:

```ini
[repository.pull-request]
DEFAULT_MERGE_STYLE = squash
```

or use env var `GITEA__REPOSITORY__PULL_REQUEST__DEFAULT_MERGE_STYLE=squash`

### CODE REVIEW

**Comment by lunny** [comment]
How about put it into template.

**Comment by ttys3** [comment]
Sorry, what does it mean `put it into template` ?

**Comment by Gusted** [comment]
> Sorry, what does it mean `put it into template` ?

I think what @lunny meant is that we might want to move this option into a template repository or into a `.gitea/xx.yml` file?

**Comment by lunny** [comment]
> > Sorry, what does it mean `put it into template` ?
> 
> I think what @lunny meant is that we might want to move this option into a template repository or into a `.gitea/xx.yml` file?

I was but now I think it's not a good idea because we need some branch protected rules to protect it.

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
