### PR TITLE
code search with meilisearch

### PR DESCRIPTION
**Pull request by techknowlogick**
WIP

### CODE REVIEW

**Comment by silverwind** [comment]
In case the file sort order is part of the search engine code, could stable sort(https://github.com/go-gitea/gitea/issues/24170) be implemented here? :)

**Comment by pat-s** [comment]
@techknowlogick I tested this PR. While I can start Gitea without errors and set `meilisearch` as the code indexer, I always end up with `No source code matching your search term found.` for every search. Even just basic ones, e.g. searching for `get` or similar (fuzzy mode).

I can see that some indexing is happening in the connected meilisearch instance.

Let me know how I can dig deeper to provide some meaningful log insights or similar.

**Comment by poVoq** [comment]
> @techknowlogick I tested this PR. While I can start Gitea without errors and set `meilisearch` as the code indexer, I always end up with `No source code matching your search term found.` for every search. Even just basic ones, e.g. searching for `get` or similar (fuzzy mode).
> 
> I can see that some indexing is happening in the connected meilisearch instance.
> 
> Let me know how I can dig deeper to provide some meaningful log insights or similar.

This might also be a general problem in the Gitea repo search code. I have been trying to get the Elasticsearch support working with Zincsearch and what you describe is exactly the behaviour I see with Zincsearch as well.

**Comment by techknowlogick** [comment]
@poVoq I replied to @pat-s elsewhere, but I'll repost here so that anyone else tracking can also see. The reason no search results are coming up is that the code for searching in meilisesrxh doesn't exist yet, only indexing. That's what the WIP part of this PR is.

Your issue with zincsearch may be something else, and you may wish to open a an issue about that to track.

**Comment by Bisstocuz** [comment]
Maybe it's a related issue https://github.com/zincsearch/zincsearch/issues/538

**Comment by Bisstocuz** [comment]
> > @techknowlogick I tested this PR. While I can start Gitea without errors and set `meilisearch` as the code indexer, I always end up with `No source code matching your search term found.` for every search. Even just basic ones, e.g. searching for `get` or similar (fuzzy mode).
> > I can see that some indexing is happening in the connected meilisearch instance.
> > Let me know how I can dig deeper to provide some meaningful log insights or similar.
> 
> This might also be a general problem in the Gitea repo search code. I have been trying to get the Elasticsearch support working with Zincsearch and what you describe is exactly the behaviour I see with Zincsearch as well.

Maybe here is a related issue https://github.com/zincsearch/zincsearch/issues/538

**Comment by poVoq** [comment]
@techknowlogick no plans to finish this? Really a pity as otherwise only Elastic/Opensearch seem to work and those are really not great.

**Comment by lunny** [comment]
Because indexer will have a big refactor, so I think this PR will be affected. Maybe another PR could be created after the refactor finished. ref: #25174

**Pull request closed without merging**
