### PR TITLE
Revert "Fix EOL handling in web editor"

### LINKED ISSUE #28097: 1.21 broke Linux EOL in code editor
### Description

Updated to 1.21 and now any change via web editor always use Windows EOL, quite possibly because the browser itself runs in a Windows PC.

The stupid part is the editor itself successfully detected these are bash scripts, which must be Linux!
I can't find any documentation on how to permanently use Linux EOL so now I'm stuck.

Tried revert back to 1.20 and of course gitea blocked it too.

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Gitea docker on Ubuntu.
Browser access on Windows PC.

### Database

None

### PR DESCRIPTION
**Pull request by nanguanlin6**
Reverts go-gitea/gitea#27141
close #28097

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by silverwind — CHANGES_REQUESTED** [review]
I can't accept a full revert, the editorconfig detection has to stay, that is valuable in any case.

Also the linked issue seems odd, unless monaco uses browser OS, in which case we should override it to LF for cases with no .editorconfig and add a ini setting for it.

**Comment by wxiaoguang** [comment]
This behavior already effects end users.

If there is no quick fix (eg: in 1 or 2 days), let's revert it to old behavior. Then you have enough time to propose a new fix.

**Comment by silverwind** [comment]
It's a trivial fix, I will provide soon. That's assuming the current behaviour can even be considered "broken", I think monaco is doing the sensible thing by defaulting to user's platform.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/28119

**Comment by wxiaoguang** [comment]
Will merge it in 1 day.

**Comment by wxiaoguang** [comment]
@silverwind the last call for the merge in 12h, if you still have objection, please show a real case to help understanding the "problem" you are worrying about.

**Comment by lunny** [comment]
> I'm strongly against this because it removes editorconfig support.

But it broke many users' online editors. I was surprised when I edit a readme and only add one new line then all files were changed with no warning until I take a look at diff.

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
The only "necessary" revert is this line:

https://github.com/go-gitea/gitea/pull/27141/files#diff-898533f7342f43a8390c353ae398fa85578aaa93667b3ff99a5dd889c048e1c7L290

Ideally we should just convert line endings based on the new server pref.

**Comment by silverwind** [comment]
Added server-side convertion in https://github.com/go-gitea/gitea/pull/28119/commits/e58dcc03437dca23ed8bc24c8b7434ac088e14be, this will always be correct, no matter what happens on the client side.

**Review by silverwind — APPROVED** [review]
Revert if you want a quick fix. I guess I will then make another PR the cherry-picks #27141 and #28119 in that sequence which can then land only on 1.22.

**Pull request merged**
