### PR TITLE
Add release cycle to contributing

### PR DESCRIPTION
**Pull request by lunny**
This PR added release cycle section to CONTRIBUTING.md.

### CODE REVIEW

**Comment by tboerger** [comment]
IMHO it's better to place that on the website, no regular user cares about the contributors guideline

**Comment by appleboy** [comment]
I think to put this section on `README.md` and official website would be better than `CONTRIBUTING.md`

**Comment by lunny** [comment]
I think both are need. First is CONTRIBUTING, user can know the release cycle even if there are a copy of the Gitea code.

**Comment by appleboy** [comment]
Could you put the release cycle to readme too? People come here first or somebody who won't contribute to Gitea.

**Comment by lunny** [comment]
Yes. I will do it another PR after this is merged.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by andreynering** [comment]
LGTM

**Comment by lunny** [comment]
@tboerger @bkcsoft

**Comment by tboerger** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
