### PR TITLE
add experimental libSQL support

### LINKED ISSUE #29542: Support libsql
### Feature Description

I for love to see the SQLite driver swapped out for libsql, allowing us to use a highly available sqlite database. 

This should be close to a drop in replacement. 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by techknowlogick**
fixes #29542

an experimental inclusion of libsql that can be included with an optional build tag `libsql`

cc @rawkode

### CODE REVIEW

**Comment by rawkode** [comment]
This is awesome. I'll give it a run through tomorrow. 

Thanks you, @techknowlogick

**Comment by lunny** [comment]
I don't think we should merge this. Adding a new database support will increase many maintain works especially once the SQL syntax maybe changed in the future.

**Comment by rawkode** [comment]
The libsql team have it in their docs that their file format and API will always be compatible with SQLITE

https://docs.turso.tech/libsql

**Comment by rawkode** [comment]
☹️

**Pull request closed without merging**
