### PR TITLE
Update last_login_unix when using the API

### LINKED ISSUE #8878: A last_access field that indicates the last access via SSH/HTTP/REST API
- Gitea version (or commit ref): 1.9.5 built with GNU Make 4.1, go1.12.11 : bindata, sqlite, sqlite_unlock_notify
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Currently the `last_login` field (as returned by `/admin/users`) API only returns the last login to the gitea web interface. However, it does not take into account logins via HTTP or SSH using the git command itself (e.g. via git clone).

I think that the `last_login` field should be updated whenever the user has authenticated. Alternatively we could have a `last_access` field that indicates the last access via SSH/HTTP/REST API and leave `last_login` as it is.

### PR DESCRIPTION
**Pull request by 42wim**
Partially fixes #8878

Not sure about actually login ssh logins too as we already log the key activity.
Also not sure if we want to fail here if the logging fails or just ignore it and continue (currently the latter)

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
Maybe we need another column to do that but not reuse the previous column. Otherwise we cannot know the last time we login via web.

**Review by delvh — APPROVED** [review]

**Comment by 42wim** [comment]
> Maybe we need another column to do that but not reuse the previous column. Otherwise we cannot know the last time we login via web.

We can do that, but why does it matter how the login happened ? 
If it matters do we also need to split up the API in a column for which kind of API access happened? basic auth/oauth/httpsig etc ?

**Comment by lunny** [comment]
> , but why does it matter how the login h

Assume the situation, since there is no session for API, every time any API called with the token, user was considered login. I don't think it matches the name `Last Login`. It's last API request.

**Comment by delvh** [comment]
It depends on how you define it:
If you simply define it as `the last time this user was seen`, then there is no need for an additional field, because you are technically "seeing" the user through his API call.
If you define it, however, as `the last time this user logged in`, then you need an additional field.

Would there be a benefit in defining it the second way? I don't really think so: The test if a user is still active or not is equally valid with the first definition, and I don't know another benefit of storing the last logged in time...

**Comment by 6543** [comment]
why differ between api and web access?

I dont think store it in a different column

API should be used via token if you need dedicated usage info on this ...

**Comment by techknowlogick** [comment]
last_used (or something similar) should be a field for API keys (similar to SSH keys) so user can know the last time the API token was used.

**Comment by 42wim** [comment]
@techknowlogick  What if we for now exclude api token from this PR but only count basic auth and httpsig as user logins, will that work for you?

**Comment by wxiaoguang** [comment]
Web Login and API usage are different. There are already `Last used on ...` for API access tokens and SSH keys.

**Pull request closed without merging**
