### PR TITLE
Fix #4877 to follow the OpenID Connect Audiences spec

### LINKED ISSUE #4877: OpenID Connect is not parsing the JWT according to the spec, and thus is breaking
- Gitea version (or commit ref):   bd1bf2a (current master as of this post)
- Git version:  2.7.4
- Operating system:  Ubuntu Server
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:  N/A

## Description

At this line of code:
https://github.com/go-gitea/gitea/blob/bd1bf2a0720b771cfe2fac3fef0fd9edd68f6317/vendor/github.com/markbates/goth/providers/openidConnect/openidConnect.go#L202
```go
	if audience != p.ClientKey {
```
It is performing a string comparison between `audience` and `p.ClientKey`, however, according to the OpenID Connect spec that that very source file links to just 3 lines higher states (emphasis mine):

> The Client MUST validate that the `aud` (audience) Claim contains its `client_id` value registered at the Issuer identified by the `iss` (issuer) Claim as an audience. ***The `aud` (audience) Claim MAY contain an array with more than one element.*** The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client. 

And in fact an array is being passed in by some OpenID Connect servers, which is causing this to fail and be unusable.

The fix is fairly trivial conceptually, just need to perform a string comparison if `aud` is a string, else need to test if `p.ClientKey` is a member of the array of strings that is then in `aud`.

### PR DESCRIPTION
**Pull request by OvermindDL1**
This follows the OpenID Connect spec to support audiences with either a string or an array of strings instead of just a string.

This might want to be on the release branches as well as it is a bug fix, but I personally can use master until then.

I have tested this and am running it on my site now with the OpenID Connect with multiple audiences returned with no issue, the new code is not even run at all unless the old pure-string check fails.

Disclaimer:  I've never used and barely looked at Go thus far, and I was unable to find common functions like `filter` or so forth (or any higher order functions at all...) and based on some googling it appears that these large and unwieldy loops are the standard way to do this kind of thing in Go, but if any changes are needed please request as such with information on what I should change it to (great learning opportunity!).

And of course any rights or whatever there-of related to this code I give up for whatever use this project currently wants or will want in the future.  Etc... etc...  Commit is signed, etc...

### CODE REVIEW

**Comment by OvermindDL1** [comment]
No clue why the CI failed, it looks like it didn't even try to recompile this code...  o.O

**Comment by lunny** [comment]
@OvermindDL1 You have to send a PR to upstream repo github.com/markbates/goth and then push this one again.

**Comment by OvermindDL1** [comment]
@lunny Interesting.  Why is the dependency included 'inside' this repo if it is not actually code for this project itself?  (I'm learning the reasonings as I've never seen someone include the dependents directly in a project short of ancient C and Cobol work 30 years ago...).

What do you mean by push this again, as in push the entire 'goth' repo into it, as a git submodule, with a .git directory, without a .git directory (archived), etc...?  In anything from C++ to the JVM to many others I'm used to just updating a single reference in a single file to pull a new version of a dependent, thus including the entire dependent in the repo itself is extremely foreign to me (seems inefficient but I'm guessing there is a reason?) so I want to make sure I am doing it properly.  ^.^;

**Comment by OvermindDL1** [comment]
PR submitted:  https://github.com/markbates/goth/pull/240

**Comment by lunny** [comment]
@OvermindDL1 We don't want to maintain all the dependency libraries so we will always follow the upstream library's update. If some commit changed the dependency library directly, that maybe make the things more complexly in future. 
I'm sorry I mean after upstream PR merged, you could run `dep ensure -update github.com/markbates/goth` and then commit and push. We use `github.com/golang/dep` to manage dependency libraries. 
Thank you for your effort.

**Comment by OvermindDL1** [comment]
Makes sense, I did not know that the `go` style is to copy all dependencies into a `vendor` directory (seems like that would artificially inflate a repository size, a substantial amount...) so didn't know it had any special significance.  I've not seen a language copy in it's dependencies permanently since my old C/Cobal days 25 years ago so it was entirely unexpected for me.  ^.^;

Care if this is left open as a reminder for me when the `goth` PR gets submitted, the instructions you gave should be great for me to use at that time.  :-)

**Comment by OvermindDL1** [comment]
And https://github.com/markbates/goth/pull/240 was just merged, the goth dependency can now be updated.  :-)

I'm trying to do it myself, but I had to deal with some horror of `GOPATH` environment variable just to get rid of some message that it didn't know what gopath was, and no gopath worked except for putting gitea in a directory named 'src' for whatever reason, and all that does is print out nothing but this, no matter how I run it, try to update it, verify it, anything:
```go
# dep ensure -update github.com/markbates/goth
dep: WARNING: Unknown field in manifest: prune
The following errors occurred while deducing packages:
  * "code.gitea.io/gitea/modules/highlight": unable to deduce repository and source type for "code.gitea.io/gitea/modules/highlight": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/mailer": unable to deduce repository and source type for "code.gitea.io/gitea/modules/mailer": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/markup/external": unable to deduce repository and source type for "code.gitea.io/gitea/modules/markup": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/process": unable to deduce repository and source type for "code.gitea.io/gitea/modules/process": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/public": unable to deduce repository and source type for "code.gitea.io/gitea/modules/public": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/models": unable to deduce repository and source type for "code.gitea.io/gitea/models": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/base": unable to deduce repository and source type for "code.gitea.io/gitea/modules/base": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/setting": unable to deduce repository and source type for "code.gitea.io/gitea/modules/setting": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/user": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/httplib": unable to deduce repository and source type for "code.gitea.io/gitea/modules/httplib": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/indexer": unable to deduce repository and source type for "code.gitea.io/gitea/modules/indexer": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/pprof": unable to deduce repository and source type for "code.gitea.io/gitea/modules/pprof": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/org": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/swagger": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/org": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/test": unable to deduce repository and source type for "code.gitea.io/gitea/modules/test": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/minwinsvc": unable to deduce repository and source type for "code.gitea.io/gitea/modules/minwinsvc": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/misc": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/utils": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/templates": unable to deduce repository and source type for "code.gitea.io/gitea/modules/templates": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/auth": unable to deduce repository and source type for "code.gitea.io/gitea/modules/auth": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/auth/pam": unable to deduce repository and source type for "code.gitea.io/gitea/modules/auth": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/search": unable to deduce repository and source type for "code.gitea.io/gitea/modules/search": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/convert": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/auth/oauth2": unable to deduce repository and source type for "code.gitea.io/gitea/modules/auth": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/context": unable to deduce repository and source type for "code.gitea.io/gitea/modules/context": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/user": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/user": unable to deduce repository and source type for "code.gitea.io/gitea/modules/user": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/validation": unable to deduce repository and source type for "code.gitea.io/gitea/modules/validation": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/notification": unable to deduce repository and source type for "code.gitea.io/gitea/modules/notification": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/recaptcha": unable to deduce repository and source type for "code.gitea.io/gitea/modules/recaptcha": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/private": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/markup": unable to deduce repository and source type for "code.gitea.io/gitea/modules/markup": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/sync": unable to deduce repository and source type for "code.gitea.io/gitea/modules/sync": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/utils": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/models/migrations": unable to deduce repository and source type for "code.gitea.io/gitea/models": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/generate": unable to deduce repository and source type for "code.gitea.io/gitea/modules/generate": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/markup/markdown": unable to deduce repository and source type for "code.gitea.io/gitea/modules/markup": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/private": unable to deduce repository and source type for "code.gitea.io/gitea/modules/private": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/admin": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/admin": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/util": unable to deduce repository and source type for "code.gitea.io/gitea/modules/util": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/auth/openid": unable to deduce repository and source type for "code.gitea.io/gitea/modules/auth": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/cron": unable to deduce repository and source type for "code.gitea.io/gitea/modules/cron": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/lfs": unable to deduce repository and source type for "code.gitea.io/gitea/modules/lfs": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/ssh": unable to deduce repository and source type for "code.gitea.io/gitea/modules/ssh": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/dev": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/avatar": unable to deduce repository and source type for "code.gitea.io/gitea/modules/avatar": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/api/v1/repo": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/repo": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/options": unable to deduce repository and source type for "code.gitea.io/gitea/modules/options": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/user/setting": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/auth/ldap": unable to deduce repository and source type for "code.gitea.io/gitea/modules/auth": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/cache": unable to deduce repository and source type for "code.gitea.io/gitea/modules/cache": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/modules/log": unable to deduce repository and source type for "code.gitea.io/gitea/modules/log": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found
  * "code.gitea.io/gitea/routers/routes": unable to deduce repository and source type for "code.gitea.io/gitea/routers": unable to read metadata: go-import metadata not found

validateParams: could not deduce external imports' project roots
```

What am I doing wrong here...  I'm used to just updating some commit in some dependency file and running something like `cmake ..` or `mix deps.get` or `cargo build` and google is not being helpful talking about private repo's or whatever so I feel like I have to be doing something really wrong...  :-(

**Comment by lafriks** [comment]
I will look into this later when I get home

**Comment by OvermindDL1** [comment]
> I will look into this later when I get home

Cool thanks, I'd love to know what I'm doing wrong so I will know how to do it properly in the future.  :-)

**Comment by lafriks** [comment]
Command is correct. Might be you have old golang dep version. Did you try to:
```
go get -u github.com/golang/dep/cmd/dep
```

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by OvermindDL1** [comment]
> Command is correct. Might be you have old golang dep version. Did you try to:

No clue?  It was installed via asdf and it returns:
```zsh
╰─➤  go version         
go version go1.11 linux/amd64
```
And generally asdf is up-to-date?  Plus, if anything was out of date shouldn't it state to update due to a version check with the internal metadata of the project when ran (at least that is how cmake/mix/cargo/etc all work)?

EDIT:  Oh, and this is the first time I've ever installed golang, so no prior installations either.

**Comment by lafriks** [comment]
@OvermindDL1 it is not about GoLang but dep tool. It is hard to tell why it was not working for you

**Comment by lafriks** [comment]
I will move to 1.6.0 milestone as it is just dependency update

**Pull request merged**
