### PR TITLE
Include OriginalAuthor in Reaction constraint

### LINKED ISSUE #13271: Migration: migrating migrated repo fail
while try to migrate from gitea ( 1.14.0+dev-63-g26d6c1530) to gitea (1.14.0+dev-44-gf0fe5683f) a db deadlock ocure (mysql)

source repo: https://try.gitea.io/abcKing/GitNex

### PR DESCRIPTION
**Pull request by zeripath**
When migrating repositories with reactions with deleted users, the original
author id may be -1. This means that it is possible to end up attempting
to create multiple reactions with the same [ Type, IssueID, CommentID, UserID,
OriginalAuthorID ] thus breaking the constraints.

On SQLite this appears to cause a deadlock but on other dbs this will
cause the migration to fail.

This PR extends the constraint to include the original author username
in the constraint.

Fix #13271

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by 6543** [comment]
ok migration cant be backported ... I'll file a pull to drop entrys from API witch wont have any chance to get migrated to an existing user somehow

**Comment by zeripath** [comment]
The backport would just have to drop the reactions if they have originalauthorid -1 I think

**Comment by zeripath** [comment]
admittedly such a backport would not be a backport just an alternate fix but it's the only solution.

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
damn recreateTable has to be in a transaction for MSSQL - just put it in one

**Comment by gsantner** [comment]
potential issue from this -> https://github.com/go-gitea/gitea/issues/13588

**Comment by zeripath** [comment]
No this is not the cause of your issue.

**Pull request merged**
