### PR TITLE
Display Gitea logo in Readme

### PR DESCRIPTION
**Pull request by sapk**
I feel like the gitea logo is missing in the readme file.

After thinking it was a simple task:
- `h1` is needed instead of `#` for the image to be in front 
- The image can not be too big or it is offset of the text.

### CODE REVIEW

**Comment by 6543** [comment]
nice idear can we crop the images empty space at the top and butom somehow?

**Comment by 6543** [comment]
Bildschirmfoto zu 2019-10-19 19-57-40

for this preview i edited the img but i didnt found a css way until now ...
-> `<h1> logo Gitea - Git with a cup of tea</h1>`

**Review by guillep2k — APPROVED** [review]

**Comment by guillep2k** [comment]
Dark theme:

image

**Review by lafriks — APPROVED** [review]

**Comment by sapk** [comment]
@6543 there is limited control over render of markdown. May we can provide a specific image but I want to make it simple first.

**Pull request merged**
