### PR TITLE
resign drone and fix #1816

### LINKED ISSUE #1816: CI build failed because of signature
Since https://drone.gitea.io/go-gitea/gitea/3212, the build are failing in master. The reason is the sign wasn't updated in #1783 (lost after rebase).

cc @lunny sorry to ask but we need an update of sign. ^^

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by lunny** [comment]
will fix #1816

**Comment by DblK** [comment]
LGTM

**Comment by sapk** [comment]
LGTM

**Comment by sapk** [comment]
thx

**Pull request merged**
