### PR TITLE
Fix reading git notes from nested trees

### PR DESCRIPTION
**Pull request by filipnavara**
The [GIT documentation](https://git-scm.com/docs/git-notes) for notes states "Permitted pathnames have the form ab/cd/ef/.../abcdef...: a sequence of directory names of two hexadecimal digits each followed by a filename with the rest of
the object ID."

We use subgit to synchronize our git and Subversion repositories. It stores the revision mapping data in the git note format. Due to large number of notes the note tree structure is no longer flat and this was not handled properly.

Now the commit information looks like this:

image

### CODE REVIEW

**Comment by filipnavara** [comment]
Looks like the lookup for note commit revision is somewhat broken. It is slow and the retrieved information looks incorrect. I'll look into it.

**Review by lafriks — APPROVED** [review]

**Comment by filipnavara** [comment]
cc @lunny @zeripath ... can you review, please?

**Comment by lunny** [comment]
@filipnavara Thanks for your PR. Could you add some tests for this change? The old test haven't support this kind of path.

**Comment by filipnavara** [comment]
@lunny I wanted to but it's not as trivial as it seems. Git itself is quite reluctant to produce this layout unless you create a large number of notes which is overkill for a simple test. It is possible to create it with low-level commands but I will have to figure out how :)

**Comment by filipnavara** [comment]
I hand-crafted a repository to show the issue. Still need to make it into test.

[git-notes-test.zip](https://github.com/go-gitea/gitea/files/3583643/git-notes-test.zip)

**Comment by filipnavara** [comment]
@lunny Updated to include unit test.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
@filipnavara Thanks!!!

**Comment by lafriks** [comment]
Make lg-tm work

**Comment by lafriks** [comment]
make it work again :D

**Comment by lunny** [comment]
Please send backport to release/v1.9

**Pull request merged**
