### PR TITLE
Make user profile image show full image on mobile

### PR DESCRIPTION
**Pull request by Eekle**
This restyles the user profile page avatar in a mobile environment so that it displays the whole image at 30% of the viewport width

Old:

image

New:
image

### CODE REVIEW

**Comment by Eekle** [comment]
I don't think the build failure here is due to this change...?

**Comment by Eekle** [comment]
There is also the https://semantic-ui.com/views/card.html#text-alignment property which may be a more natural way to do this.

**Comment by silverwind** [comment]
Interesting, I thought the `object-fit: contain` would prevent such clipped images.

**Review by Gusted — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
Please update

**Comment by wxiaoguang** [comment]
bot

**Pull request merged**
