### PR TITLE
[Backport] Fix redirection path if Slack webhook channel is invalid

### PR DESCRIPTION
**Pull request by jamesorlakin**
A backport of #10548 because the label was added

### CODE REVIEW

**Comment by 6543** [comment]
@jamesorlakin you targeted the wrong branch for a backport!

**Comment by lafriks** [comment]
You need to create new commit for release/v1.11 branch

**Comment by 6543** [comment]
```sh
git checkout -f origin/release/v1.11 -b backport_xy
git cherry-pick c08c975d368771237d6509df915d3ec315186612
git push -u origin
```
and select **release/v.1.11** as target on pull create

**Comment by jamesorlakin** [comment]
Oh wow, whoops! I even did the cherry pick step but forgot to branch from release...

I'll be able to sort it tomorrow when I'm back home 🙂

**Comment by guillep2k** [comment]
I'll close this one. 😉

**Comment by jamesorlakin** [comment]
Haha, probably wise

**Pull request closed without merging**
