### PR TITLE
Style fixes (better rendering, smaller code, less redundancy)

### PR DESCRIPTION
**Pull request by wyattoday**
This pull request fixes 4 problems (all of them relatively minor):

1. It fixes headers rendered in the markdown so they're not squished together. It does this by...
    a. Fixing the *.less stylesheet to correctly compile to css that's evaluated only for the first header of the markdown document (rather than for every header -- as it is now).
  b. Gave the headers a bit more breathing room so not everything is crammed together (margin-top of 1.4em instead of 1em).

2. Remove redundant font-family from _markdown.less (it's already specified in the body element in _base.less).

3. Fix the font-family to use the "system" sans-serif fonts on each particular device to feel more like a native app (it also, consequently, matches the behavior of Github).

4. Remove the semantic-ui Font-family references so that the font-family from _base.less is respected.

The 3 pictures below show (1) how it was, (2) fixed header spacing, and (3) fixed font family.

1-orig-broken-styles
2-fixed-header-spacing
3-fixed-font-family

### CODE REVIEW

**Comment by lafriks** [comment]
I don't like that vendored semantic ui css is changed, it can easily be forgotten to do these changes when upgrading to newer version. Can these changes be made otherwise?

**Comment by wyattoday** [comment]
No, I don’t like that either. But unfortunately the semantic UI Library overrides any existing font faces. So, as I see it, we have a few (practical) options:

1. When the semantic Library is updated either force the person that updates it to remove their font-face css properties (which is all I did to ensure the Gitea font-faces were properly inherited)

2. Make a script to automate that css change.

3. Build the Semantic UI css from the .less source code.


Really, no matter what option is ultimately decided upon it requires changing the Semantic UI Library.

**Comment by lafriks** [comment]
I think best option would be building it from less as we are already building our own css from less files

**Comment by ethantkoenig** [comment]
Is there a reason we can't just use `!important` to override Semantic UI?

**Comment by wyattoday** [comment]
> Is there a reason we can't just use !important to override Semantic UI?

Yes, because we would have to re-implement the elements that they use to set the font-family. For example, we can't just set `body{font-family: font-name !important}` (because we already do that and it's not enough). You would also have to do it for textarea, h1, h2, h3, h4, etc., etc., etc.

We also can't use the global CSS selector `* {font-family: font-name, font-name2, etc. !important}` because it blows up the icon fonts that we actually want from the Semantic UI CSS.

Yeah, CSS aint pretty.

No matter what's ultimately decided it would require maintaining (and merging) a separate branch of semantic UI because they've decided to make this opinionated choice for font-families. And I don't have time to automate building the semantic-ui from source. Or creating a complicated infrastructure for merging changes when the Semantic UI is updated.


Honestly, the least time intensive option is to do what I've already done. And then every X months when someone chooses to update the Semantic-UI library (CSS, JS, etc.) have that person manually remove the default font-families so they don't override the font choices we make.

**Comment by daviian** [comment]
We could use semantic-ui's build tool with less files. Would allow changing fonts, colors etc.
So on update we just have to update semantic-ui's less files and build again with our fixed less variables.

Oh, just saw that it was already mentioned 😄 
So I simply want to vote for that solution

**Comment by lafriks** [comment]
I think think for this to merge we need to change semantic-ui building from less files, so currently I'm moving this to 1.4 milestone

**Pull request closed without merging**
