### PR TITLE
Update to xorm@v0.7.4

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
I wanted to remove dependency on `github.com/go-xorm/core` and just use `xorm.io/core`. 

https://github.com/lafriks/xormstore/pull/7 was updated. cc:@lafriks

**Comment by tamalsaha** [comment]
@lunny , do you know if there are known issues with the sqlserver driver version? It seems all the tests are failing.

**Comment by lafriks** [comment]
@tamalsaha xormstore v1.1.0 has been tagged

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by sapk** [comment]
For details on mssql, I found the last working commit and lock down to it. You can find tests on various commit in https://github.com/go-gitea/gitea/pull/7294 but couldn't find the reason of the failed reset on database.

**Pull request merged**
