### PR TITLE
Bump min required golang to 1.13

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
its time ...

**Comment by 6543** [comment]
perhaps #12701 is passing then

**Comment by silverwind** [comment]
Need to update README.md.

**Review by zeripath — APPROVED** [review]
min go1.13 for gitea 1.13!

**Comment by silverwind** [comment]
Also `go-check` make target error message.

**Pull request merged**
