### PR TITLE
Fix repo API listing stability

### PR DESCRIPTION
**Pull request by cboylan**
This addresses https://github.com/go-gitea/gitea/issues/12056

Repo listings are paginated in the API now. Unfortunately, they are
ORDER BY updated_unix which only has second resolution. This means that
if you do a listing when multiple projects were created at the same time
you can unstable ordering. If that unstable ordering happens at a page
boundary you may fail to get a complete repo listing.

To make things worse sorting by updated_unix means that we may never get
a complete listing because udpated_unix can change independent of our
API calls.

Fix this by making the API repo listing order by id instead.

### CODE REVIEW

**Comment by cboylan** [comment]
As noted in the Issue I'm not sure this is a complete fix as other API pagination methods may have similar problems. I'm also in the process of getting this tested properly locally, but I wanted to get this up so that others could offer suggestions or additional fixes if necessary.

**Comment by cboylan** [comment]
I'm doing more testing locally and I'm not sure this fixes the issue for us yet. In any case it should serve as a starting point for figuring it out.

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by cboylan** [comment]
New version does and ascending not descending sort. I realized that if a new repo is added during a listing we'll get that inserted at the front not the end using descending. If we use ascending it will be added at the end and a user paging through the list will see the new repo. In the end both should work, but ascending is a bit more friendly I think.

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Pull request merged**
