### PR TITLE
Reorder file actions

### PR DESCRIPTION
**Pull request by webjoel**
Currently the ordering of the file actions in Gitea is different from the ordering of the same actions in GitHub.

To improve the usability, since they are the same actions, I am sending this PR to leave equal in the two tools, Gitea and GiHub.

Follow the images for comparison:

GitHub:
github

Actual Gitea:
gitea

New Gitea:
giteaAfterPR

### CODE REVIEW

**Comment by lafriks** [comment]
I would actually prefer `Raw | History | Blame`

**Comment by webjoel** [comment]
@lafriks I suggested this order because I use GitHub a lot, as well as Gitea, so I'm sometimes confused, since they are the same actions.

**Comment by lafriks** [comment]
Yes me too but I use History more than Blame :P

**Comment by lunny** [comment]
@lafriks I will agree with @webjoel and I think this is also suitable for you. Since you use history more than blame, put it on the right maybe better? :)

**Comment by lafriks** [comment]
I'm in no way requesting that change I'm ok also with proposed order :)

**Review by adelowo — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Pull request merged**
