### PR TITLE
Fix `/repos/{owner}/{repo}/pulls/{index}/files` endpoint not populating `previous_filename`

### PR DESCRIPTION
**Pull request by ghost**
---
`status == "rename"` should have read `status == "renamed"`. The typo means that file.PreviousFilename would never be populated, which e.g. breaks usage of the Github Action at https://github.com/dorny/paths-filter.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by delvh** [comment]
> status == "rename" should have read status == "renamed"

Huh?
I don't understand the relationship between this sentence and the contents of the PR.

**Comment by yp05327** [comment]
> > status == "rename" should have read status == "renamed"
> 
> Huh? I don't understand the relationship between this sentence and the contents of the PR.

image
I think this is a typo.

**Review by yp05327 — APPROVED** [review]

**Review by delvh — APPROVED** [review]
Ah, now I see what you mean.
I didn't see that you got rid of that `if`, so that's why I was confused.

**Comment by charles-plutohealth** [comment]
failures in `db-tests / test-mssql` appear to be unrelated, maybe solved with a rerun?

**Pull request merged**
