### PR TITLE
jQuery 3

### LINKED ISSUE #7422: Upgrade jquery to 3.x
Since 1.x and 2.x may include security problem, maybe we should upgrade to 3.x. And for compitable, we could use jQuery Migrate .

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #7422

### CODE REVIEW

**Comment by lunny** [comment]
You should remove `public/vendor/plugins/jquery/.DS_Store`

**Comment by techknowlogick** [comment]
@lunny Thanks for noticing :) Looks like when I changed to a new computer I didn't update global gitignore file.

**Comment by silverwind** [comment]
Why is jquery.migrate included? Would prefer if we can do without it.

**Comment by techknowlogick** [comment]
@silverwind I too would prefer without it, but sadly semantic UI (at least the version we use) has deprecated code (and an upgrade for that should come in a different PR). There is also several places in index.js that need to be updated (but I was going to save that for a second PR too).

**Comment by silverwind** [comment]
Gah, goddamn semantic holding us back, okay.

**Review by silverwind — APPROVED** [review]
LGTM based on diff

**Review by mrsdizzie — APPROVED** [review]

**Comment by lunny** [comment]
Could this be back ported to v1.9 since it's related with security. Somebody reported me that.

**Pull request merged**
