### PR TITLE
1.9.0 Changelog

### PR DESCRIPTION
**Pull request by techknowlogick**
as title

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by sapk** [comment]
I would suggest to add detail on the fact that docker tag 1 and 1.9 will not follow anymore latest commit from branch release/v1.9 but the latest tag 1.9.X (more stable)

**Comment by techknowlogick** [comment]
@sapk maybe we put that in blog post?

Blocking this PR waiting for https://github.com/go-gitea/gitea/pull/7675 backport.

**Review by sapk — APPROVED** [review]

**Comment by rakshith-ravi** [comment]
Well, now that #7675 is merged, let's restart the build?

**Comment by lunny** [comment]
@rakshith-ravi waiting back port https://github.com/go-gitea/gitea/pull/7682
@techknowlogick could you update the change log to add #7682

**Comment by techknowlogick** [comment]
make LG-TM work

**Pull request merged**
