### PR TITLE
Refactor heatmap to vue component

### PR DESCRIPTION
**Pull request by lafriks**
Looks about the same but fixes problems reported in #5191. Also removed setting for range color and instead moved it to less/css so that colors can be specified in theme css

### CODE REVIEW

**Review by jonasfranz — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Comment by ghost** [comment]
@lafriks I don't know why this happened.


`console.log(this.colorRange);` return:
```
0: ""
1: ""
2: ""
3: ""
4: ""
5: ""
```
Chrome 70.0.3538.110

**Comment by sapk** [comment]
@lunny @yasuokav Can you send the result of http://jsfiddle.net/3wz4xdgq/13/ in your browser ? I suspect getComputedStyle to not work the same depending of browser.

**Comment by sapk** [comment]
For me on Firefox : 
```
test backgroundColor: "rgb(255, 0, 0)"
clone backgroundColor: "rgb(255, 0, 0)"
new backgroundColor: "rgb(255, 0, 0)"
non-existing backgroundColor: "rgb(255, 0, 0)"
```

**Comment by sapk** [comment]
On chrome :
```
test backgroundColor: "rgb(255, 0, 0)"
clone backgroundColor: ""
new backgroundColor: ""
non-existing backgroundColor: ""
```
That why it doesn't work ... Please use a browser that support standard 😆 
Just kidding, we just have to find a workaround getComputedStyle() variant.

**Comment by sapk** [comment]
Found the bug on chrome and it is still open : https://bugs.chromium.org/p/chromium/issues/detail?id=558165

**Comment by ghost** [comment]
@sapk The results are the same as yours

**Comment by tonivj5** [comment]
Maybe could we use a polyfill for getComputedStyle?

**Comment by lafriks** [comment]
ah shity browser standard support :D

**Comment by sapk** [comment]
@xxxtonixxx I don't think we can have a polyfill since the func is already defined. The workaround that I see is creating a hidden el with the class un order for webkit to compute the style. An other would be to define the variable in the theme or keep like before a config that define the JS var.

**Pull request merged**
