### PR TITLE
Create access token for user when creating a user

### PR DESCRIPTION
**Pull request by kimbj95**
Gitea command line provides an option to create access token when creating a user using `--access-token` parameter (https://docs.gitea.io/en-us/command-line/#admin). 
PR is to allow API to have same behavior.

### CODE REVIEW

**Comment by noerw** [comment]
- Why don't you use `POST /users/{user}/tokens` as a second call?
- You generate an access token but don't return it to the client. To return it, the `User` struct would need to be extended, but this does not seem like a good idea, as the access token conceptually does not belong to the user model.
- The CI complains, because when changing API parameters or responses, you need to run `make swagger` and commit the result

**Comment by lunny** [comment]
Looks like it's not very necessary.

**Comment by kimbj95** [comment]
@noerw @lunny Why is creating access token during user creation process implemented in the gitea command line?

**Comment by kimbj95** [comment]
Closing PR due to lack of necessity

**Pull request closed without merging**
