### PR TITLE
Fix panic when call api (/repos/{owner}/{repo}/pulls/{index}/files)

### LINKED ISSUE #22910: API unable to paginate on files endpoint
### Description

When calling the `GET /repos/{owner}/{repo}/pulls/{index}/files` endpoint the `MAX_RESPONSE_ITEMS` config parameter is correctly respected, but also the `MAX_GIT_DIFF_FILES` config parameter is used and, if exceded, a index out of bounds error occurs.

All acceptable so far, but the pagination is also affected.

For example, with the following:
```
[git]
MAX_GIT_DIFF_FILES = 100
[api]
MAX_RESPONSE_ITEMS  = 100
```

With a PR containing 120 files, the first request to the endpoint correctly returns the first 100 items with an header `X-HasMore: true`. When performing a call to the same endpoint with a `page=2` parameter, an error is produced:

```
...common/middleware.go:71:1() [E] [63ebf818] PANIC: runtime error: index out of range [100] with length 100
```
I would expect the API endpoint to ignore the `MAX_GIT_DIFF_FILES` param...

If this is the intended behaviour I suggest to introduce an additional configuration parameter to determine how many files are visbile through the UI.

I've created a test repo and a reference PR: https://try.gitea.io/rlogiacco/api-limit/pulls/1

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/rlogiacco/8a605132a73515f2c9277333a4e27b81

### Screenshots

_No response_

### Git Version

2.36.4

### Operating System

official docker image

### How are you running Gitea?

Inside a docker swarm using a a docker-compose file encompassing a mysql database

### Database

MySQL

### PR DESCRIPTION
**Pull request by sillyguodong**
Close: #22910 

---
I'm confused about that why does the api (`GET /repos/{owner}/{repo}/pulls/{index}/files`) require caller to pass the parameters `limit` and `page`.
In my case, the caller only needs to pass a `skip-to` to paging. This is  consistent with the api `GET /{owner}/{repo}/pulls/{index}/files`
So, I deleted the code related to `listOptions`

### CODE REVIEW

**Review by wolfogre — CHANGES_REQUESTED** [review]
Could you explain what causes the panic and why we have to break the current design instead of just fixing it?

Maybe this [doc](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files) can solve your confusion. I know it comes from GitHub, however, keeping the api compatible with GitHub is a good idea.

**Comment by sillyguodong** [comment]
> Could you explain what causes the panic and why we have to break the current design instead of just fixing it?
> 
> Maybe this [doc](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files) can solve your confusion. I know it comes from GitHub, however, keeping the api compatible with GitHub is a good idea.

After reading the doc, my confusion cleared up.
In the latest pr, the following changes have been made：
1.  Url no longer accepts the `skip-to`, the function of paging only needs `page` and `limit`(which means pageSize).
2. Setting `maxFiles` to a fixed value of -1 (**So this API has nothing to do with the `MAX_GIT_DIFF_FILES` in the configuration file**), function `GetDiff()` will return all files, then use `listOptions` to implement the actual paging logic.

**Comment by sillyguodong** [comment]
In latest commit, i make some **changes**:
1. Add a line of **FIXME** comment, I'm affraid of that if there are too many modified documents, may cause some performance issuses or other unpredictable issues.
2. Set `MaxFiles` in `gitdiff.DiffOptions` to `-1` directly, no longer declare a separate variable.
3. Allow user pass parameter `skip-to` again.

### The reson that why I set `MaxFiles` to `-1`:
1. In the original code logic, the start index of `for` loop is `start` instead of `0`, so I think that the previous author of the code was trying to get all files from `gitdiff.GetDiff()` function.
https://github.com/go-gitea/gitea/blob/e7ef94e00f1319e5fb876f47fee28728bd671f07/routers/api/v1/repo/pull.go#L1456
2. From the following code, we know that if `MaxFiles` less than or equal to `-1`,  `gitdiff.GetDiff()` function will return all files.
https://github.com/go-gitea/gitea/blob/ef11d41639dd1e89676e395068ee453312560adb/services/gitdiff/gitdiff.go#L499

**Review by wolfogre — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
LG-TM bot

**Pull request merged**
