### PR TITLE
Skip update for deps within make.go

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Without that it results in an error on fresh golang setups:

```
+ go get -u github.com/jteeuwen/go-bindata/...
+ go get -u github.com/Masterminds/glide/...
package github.com/codegangsta/cli: directory "/home/tboerger/Projects/golang/src/github.com/codegangsta/cli" is not using a known version control system
Error: Failed step deps
exit status 1
```

**Comment by lunny** [comment]
I think `-u` should not be removed and your problem is that you need update your `github.com/codegangsta/cli` package?

**Comment by tboerger** [comment]
@lunny i started with a totally fresh go environment. So `go get -u github.com/Masterminds/glide` or `go get -u github.com/Masterminds/glide/...` have to fetch all required dependencies. But that fails with the above error. If i drop `-u` it just works as expected.

**Comment by tboerger** [comment]
As gitea is more or less dead and gogs gets further development I'm closing this PR.

**Pull request closed without merging**
