### PR TITLE
Add team and collaborators permission adjustment logs

### PR DESCRIPTION
**Pull request by tyroneyeh**
You can view the record of who operated the increase or decrease of repository collaborators from the management interface notice

### CODE REVIEW

**Comment by Gusted** [comment]
I think this is not the correct way to achieve this functionality, this in the long-term should be resolved by https://github.com/go-gitea/gitea/issues/8.

Admin notices are only shown to Gitea admins and not to organization admins. This would make sense for some corporate setup, but any other kind of setup this doesn't make much sense that a Gitea admin will receive such notices.

**Comment by tyroneyeh** [comment]
This is in Site Administrator -> System Notices -> View Logs
Sections that only admins can see

#8 is very very long time no improvement

**Comment by Gusted** [comment]
> This is in Site Administrator -> System Notices -> View Logs
> Sections that only admins can see

Yes, but why does some organization things matters to the Gitea instance admins? Ideally this should be shown to the organization owners.

**Comment by tyroneyeh** [comment]
Seems like there is no place for the org owner to view the recorded page design?

**Comment by Gusted** [comment]
> Seems like there is no place for the org owner to view the recorded page design?

Nope, that would essentially mean to achieve that, it lays the foundation of #8

**Comment by lafriks** [comment]
imho these should be stored in new table (`audit`) not just with message but additional columns like
* organization id (optional - for audit events that are done in specific organization)
* user id (that did these changes)
* IP address (request IP address)

**Pull request closed without merging**
