### PR TITLE
Delete local branch when repo branch is deleted

### LINKED ISSUE #6490: Error 500 when recreating a deleted branch
- Gitea version (or commit ref): 1.4.0 (reproducible on https://try.gitea.io)
- Git version: 2.19.1
- Operating system: SLES 12
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I cannot recreate a deleted branch with the same name in Gitea.
I get error page 500.

1. Create a branch from Gitea.
1. Delete the branch from Gitea.
1. Re-create the branch from Gitea.

Log :
2019/04/02 14:50:38 [...uters/repo/branch.go:235 CreateBranch()] [E] CreateNewBranch: CreateNewBranch: git checkout -b 2.0 1.0: exit status 128 - fatal: A branch named '2.0' already exists.

It seems gitea keeps a cache of the repo.

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #6490 

Currently, when creating a branch from the web UI (not a commit, directly from the branch dropdown), Gitea creates the branch in its local cache and pushes it to the real repo. 

When the branch is deleted, it was not being deleted from the local cache and if a branch of the same name is created, Gitea panics because the local repo already has a branch with that name.

Since the Gitea's tmp directory is deleted on startup, the only (current) way to clear the local repo cache is to restart Gitea.

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
The local cache needs to go. Do we even need it still?

I cannot believe that we're actually requiring a full clone to just do a branch creation - particularly a full clone we keep around.

Can't we follow the technique in 

https://github.com/go-gitea/gitea/blob/master/modules/uploader/update.go

Where we just do a thin clone, create an index from the appropriate old branch and then push it as the new branch. We probably don't even need an index - We could just push our HEAD to the new branch.

In fact I wouldn't be surprised if we couldn't just do a push from an empty place to create a new branch. Would have to look at the documentation for git push.

A branch is simply a file with a hash to a tree object. It's nothing magical. The only benefit with pushing is that you make sure hooks etc will run.

**Comment by jolheiser** [comment]
If I do follow how the uploader does it, should I take that code and put it somewhere else (perhaps a new module) that can be re-used when we need to make a "temp" repo that gets cleaned up after use?

I could just use the existing code, but it would seem odd to use the `uploader` package when referencing temp repos.

**Review by zeripath — APPROVED** [review]
I'm gonna approve as this is a bug fix, but I'm gonna look at removing this unnecessary cloning from the codebase.

**Comment by zeripath** [comment]
Take a look at: https://github.com/go-gitea/gitea/pull/6505

**Comment by ngourdon** [comment]
@zeripath Even if it's out of scope of this PR, yes you can push a new branch without checking it out.

The form of the git push command which will permit to do so is
`git push <repository> <refspec>`
repository can be a name like "origin" but may also be a path like "/path/to/gitea-repositories/username/repo.git".

From the directory of the gitea bare repository (/path/to/gitea-repositories/username/repo.git) you can do
`git push . refs/heads/existing-branch:refs/heads/new-branch`
or from a sha1
`git push . sha1:refs/heads/new-branch`

This will trigger git hooks

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by jolheiser** [comment]
@zeripath Once your PR is merged I will look at submitting a new PR implementing those changes in this area. (Unless your PR just removes these changes as part of the conversion)

**Pull request merged**
