### PR TITLE
Run `npm audit fix`

### PR DESCRIPTION
**Pull request by yardenshoham**
The output of `npm audit` before this change:

```shell
$ npm audit
# npm audit report

vite  5.0.0 - 5.0.11
Severity: high
Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem - https://github.com/advisories/GHSA-c24v-8rfc-w8vw
fix available via `npm audit fix`
node_modules/vite

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```

After:

```shell
$ npm audit
found 0 vulnerabilities
```

### CODE REVIEW

**Comment by denyskon** [comment]
@yardenshoham Could you update the branch? Seems like the bot won't :laughing:

**Review by denyskon — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

**Comment by yardenshoham** [comment]
I don't think the backport will work

**Comment by denyskon** [comment]
Maybe you're right, merging package-lock can fail in many possible ways.....

**Comment by techknowlogick** [comment]
I think it's ok not to backport this as it affects the vite dev server which we don't use.

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
