### PR TITLE
Handle SetModel error, fixes one errcheck report (#257)

### PR DESCRIPTION
**Pull request by strk**
I guess it could be also backported to 1.0

### CODE REVIEW

**Comment by lunny** [comment]
I think the admin command is not very necessary? we can do it on the UI.

**Comment by strk** [comment]
you mean you would drop the runCreateUser function ?

**Comment by Bwko** [comment]
I agree with @lunny , maybe we should drop the admin command.

**Comment by lunny** [comment]
But for this one. I will give it LGTM.

**Comment by minecrafter** [comment]
I do see uses for the admin command outside of just batch account creation:

* reset a user's password from the command line
* disable two-factor authentication from an account in the event that the device is stolen and/or missing, they forget their scratch code, and the end user can verify they are the owner

**Comment by lunny** [comment]
@minecrafter Yes. Command `admin` is sometimes useful.

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
@strk bug-fix so yes, please backport :)

**Comment by strk** [comment]
I'm away from my main development machine, could anyone cherry-pick this to 1.0 and verify ?

**Pull request merged**
