### PR TITLE
Fix commit search in all branches

### PR DESCRIPTION
**Pull request by CirnoT**
We perform two commands on commit search, `--all` should not be used without `--grep`.

Fixes case where searching for commit with 'All Branches' selected would always return newest commit from newest ref instead of correct commit.

### CODE REVIEW

**Comment by zeripath** [comment]
OK I think that code needs comments as to what the hell it is doing. It's really not clear!

(Not your fault but as you've spent the time to understand this - you may be best placed to expand the commentary and make this clearer.)

**Comment by CirnoT** [comment]
Added comments; pretty detailed ones too.

**Comment by CirnoT** [comment]
Hopefully now you see that --all breaks logic of `hashCmd`

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]
🙏 ty for this PR!

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
