### PR TITLE
Fix null requested_reviewer from API

### LINKED ISSUE #31764: Details about pull request reviewers that are groups are not returned from the API
### Description

1. create a pull request
2. assign the pull request review to a group
3. query the API, for example: `curl -H "Token: ..."  -X GET https://demo.gitea.com/api/v1/repos/dmach-org/test/pulls/1`
this results in:
```
{
    ...
    requested_reviewers":[null],
    ...
}
```

It works fine when the review is assigned to a person.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

openSUSE

### How are you running Gitea?

openSUSE package running in podman (a container for test purposes)

### Database

SQLite

### PR DESCRIPTION
**Pull request by emrebdr**
If the assign the pull request review to a team, it did not show the members of the team in the "requested_reviewers" field, so the field was null. As a solution, I added the team members to the array.

fix #31764

### CODE REVIEW

**Comment by kemzeb** [comment]
Thanks for the contribution!

I believe it could be better to introduce a new field to the DTO rather than adding all team members to the requested_reviewers array, something similar to what GitHub does (see [here]()

I'm not quite sure if it would be a good idea to add all team members to the reviewers array.

There can be many team members within a team, and, if I'm not mistaken, multiple teams can be invited to a PR. This would increase the size

**Comment by kemzeb** [comment]
Thanks for the contribution!

I think it maybe better to create a separate array field in the DTO object for requested teams (similar to GitHub, see [here](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request)).

To me this makes more sense performance-wise (e.g. there can be many members in a team and, if I'm not mistaken, there may be multiple teams reviewing a PR; this is maybe too much data for us to send that consumers may not care much about).

I guess it makes sense logically too since we aren't requesting a review from individual team members but rather the team as a whole. This shouldn't be a breaking change either.

**Comment by emrebdr** [comment]
> Thanks for the contribution!
> 
> I think it maybe better to create a separate array field in the DTO object for requested teams (similar to GitHub, see [here](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request)).
> 
> To me this makes more sense performance-wise (e.g. there can be many members in a team and, if I'm not mistaken, there may be multiple teams reviewing a PR; this is maybe too much data for us to send that consumers may not care much about).
> 
> I guess it makes sense logically too since we aren't requesting a review from individual team members but rather the team as a whole. This shouldn't be a breaking change either.

so you mean create a separate array in response object for teams right? And this array field returns teams information? 🤔

**Comment by kemzeb** [comment]
> so you mean create a separate array in response object for teams right? And this array field returns teams information? 🤔

Yes

**Comment by emrebdr** [comment]
then I think now better 😄

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Pull request merged**
