### PR TITLE
Use argon as default password hash algorithm

### PR DESCRIPTION
**Pull request by zeripath**
This is a partial repush of #10602 

## Changes to Password-Based Key Derivation
Currently, Gitea uses pbkdf2 as the default password hashing function. In this pull request, I replace that with argon2 as the default, for the following reasons:

pbkdf2 is uniquely vulnerable to GPU and ASIC-based attacks that argon2 and scrypt are much less vulnerable against.
pbkdf2 is vulnerable to acceleration attacks and to a host of other attacks that argon2 and scrypt are not vulnerable to.
Therefore, given the above and especially given that argon2 is a well-specified, formally studied design that has won the Password Hashing Competition, I think using it as the default instead of pbkdf2 makes complete sense.

Closes #10602 

Many thanks to @kaepora for initial PR.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
LGTM

Is it worth it to create a migration to update the default value?

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
Ping bot

**Comment by zeripath** [comment]
Remember it's a hash. You don't have the original password so you can't write a migration you just have to let people login, test against the old hash and update to the new hash. The only other option is forcibly resetting everyone's password which we could make a doctor command for I guess?

**Comment by techknowlogick** [comment]
By migration I meant just the default value for the column rather than the content of the column itself, as otherwise the sync2 will update it. Although if we wanted to also update the column content we could have something in login that catches if existing hash is using  different algo and update when the user is logging in.

**Comment by bagasme** [comment]
What about specific notes for migrating for pbkdf2 to argon? Simply changing `app.ini` is enough?

**Comment by zeripath** [comment]
yes simply changing the app.ini is enough.

**Comment by silverwind** [comment]
Should this have included a migration? I'm seeing these warnings:

```
2020/09/09 21:21:11 ...rm/session_schema.go:360:Sync2() [W] Table user Column passwd_hash_algo db default is 'pbkdf2', struct default is 'argon2'
```

**Comment by lafriks** [comment]
Yeah, this should have migration to change default for column

**Comment by zeripath** [comment]
Can't change default columns without recreate-table.

**Comment by zeripath** [comment]
fortunately we now have recreate-table

**Comment by zeripath** [comment]
so if it's really wanted we could use recreate-table in a migration

**Pull request merged**
