### PR TITLE
Symlink icons (#1416)

### PR DESCRIPTION
**Pull request by tf198**
Uses the octicon icons for directory and file symlinks.

screenshot-2018-4-21 symlink_test

Directory symlinks will only be rendered if the target is present in the repository.  Broken links, targets outside the repo and links to other links will just be rendered as `file-symlink-file`.

### CODE REVIEW

**Comment by tf198** [comment]
I have some tests to add before this is merged but I need some advice as to the cleanest way to add a repository to the test server (gitea-repositories-meta, fixtures etc).

Is there an easy way to spin up the test server, push a new repository and spit out the fixtures?

**Comment by tf198** [comment]
I tried just adding a bare repo at `integrations/gitea-repositories-meta/user2/repo4.git` but the test instance wont pick it up unless it exists in the database as well...

**Comment by lafriks** [comment]
Yes you have to add needed database records in fixtures yml files

**Comment by lafriks** [comment]
Have not tested yet but does opening link also go to link target?

**Comment by tf198** [comment]
No, behaviour is identical github.

* all entries with mode `120000` render as `file-symlink-file`
* if the target resolves to a directory within the repo it renders as `file-symlink-directory`
* symlinks open as a text file with the location of the link.
* the edit button is present but editing disallowed on attempt to save.
* `link -> link -> directory` displays as `file-symlink-file` i.e. no recursive dereferencing.

See https://github.com/tf198/symlink_test

It would be easy to add an `goto target` button on the file view page for symlinks if that was considered a useful enhancement...

**Comment by thehowl** [comment]
Just a note: editing of symlinks is allowed on GitHub, and I think it should be kept this way (there may be a broken symlink because the dst directory changed - should be reasonable to keep the ability to change the symlink)

Please do add the `Go to target` button! (I'm wondering why GitHub considered it not necessary...) Thank you for your pull request!

**Comment by silverwind** [comment]
Thanks for doing this! Suggestions:

- Color the directory symlink icon blue like regular directories
- Maybe (if it's not too hard) sort directory symlink among directories

**Comment by lunny** [comment]
LGTM

**Comment by silverwind** [comment]
Here's a patch for the directory symlink color:

````patch
diff --git a/public/less/_repository.less b/public/less/_repository.less
index 3bbfe33ef..cb6245908 100644
--- a/public/less/_repository.less
+++ b/public/less/_repository.less
@@ -237,7 +237,8 @@
                     &.octicon-mail-reply {
                         margin-right: 10px;
                     }
-                    &.octicon-file-directory, &.octicon-file-submodule {
+                    &.octicon-file-directory, &.octicon-file-submodule,
+                    &.octicon-file-symlink-directory {
                         color: #1e70bf;
                     }
                 }
````

After applying, run `npm i && make generate-stylesheets` to generate the CSS.

**Comment by tf198** [comment]
Have applied the css patch from @silverwind - looks pretty smart now!
Regarding the second suggestion, any implementation would have to track the paths seen to avoid infinite loops `[ link_a -> link_b -> link_c -> link_a ]`.  Not sure the benefit justifies the complexity...

@thehowl - I am corrected, github currently allows editing of symlinks but gitea doesn't (existing behaviour).  Suggest a new issue is opened for modifying this behaviour.

**Comment by thehowl** [comment]
We could just avoid nested symlinks (if the target is a dir then it's a dir, otherwise if it's a file, symlink, or anything else, it's a file). Hacky, sure, but should suffice most use cases.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
