### PR TITLE
Fix sort order for organization home and user profile page (#31921)

### PR DESCRIPTION
**Pull request by yp05327**
Backport #31921

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Wait on review for https://github.com/go-gitea/gitea/pull/31921?

**Comment by yp05327** [comment]
not related to it.

**Comment by lunny** [comment]
Please update to follow #31921 and also the comment should be changed https://github.com/go-gitea/gitea/pull/31921#discussion_r1740162129

**Comment by yp05327** [comment]
The solution is not related to #31921. We can only add the options in the switch.

And the comment is also not related.
image

**Review by lunny — APPROVED** [review]

**Pull request merged**
