### PR TITLE
Remove docs sub folder since docs has been moved to https://gitea.com/gitea/docs

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Alternatively, which I'm more a fan of:
We push mirror `https://gitea.com/gitea/docs` to `https://github.com/go-gitea/docs`, and include it as a submodule here.
That's the best of both worlds (if we then add a workflow to update the main repo once the docs have been updated or at least daily)

**Comment by silverwind** [comment]
As I said, I don't like it. If this merges, the dev doc change in https://github.com/go-gitea/gitea/pull/31521 would need to be split out into that docs repo and I'm really not thrilled to do such extra work.

A major problem is that docs changes are no longer in sync with code changes and this asynchronity will introduce inaccuracies in the docs as they can no longer be reviewed along with the code change.

**Review by a1012112796 — COMMENTED** [review]
looks document related github action should be removed also

**Comment by silverwind** [comment]
> As I said, I don't like it. If this merges, the dev doc change in #31521 would need to be split out into that docs repo and I'm really not thrilled to do such extra work.
> 
> A major problem is that docs changes are no longer in sync with code changes and this asynchronity will introduce inaccuracies in the docs as they can no longer be reviewed along with the code change.

Okay I sneaked in https://github.com/go-gitea/gitea/pull/31521 now, so I am no longer affected and hope I won't have to do many doc updates in the future.

**Comment by lunny** [comment]
> > As I said, I don't like it. If this merges, the dev doc change in #31521 would need to be split out into that docs repo and I'm really not thrilled to do such extra work.
> > A major problem is that docs changes are no longer in sync with code changes and this asynchronity will introduce inaccuracies in the docs as they can no longer be reviewed along with the code change.
> 
> Okay I sneaked in #31521 now, so I am no longer affected and hope I won't have to do many doc updates in the future.

I created https://gitea.com/gitea/docs/pulls/16 to add the missing doc.

**Comment by lunny** [comment]
> looks document related github action should be removed also

I think I have removed all contents under `docs/`.

**Comment by yp05327** [comment]
> > looks document related github action should be removed also
> 
> I think I have removed all contents under `docs/`.

image

**Comment by techknowlogick** [comment]
+1 for submodule suggestion, as then it'll lessen the friction of contributions to docs (as then devs will at least have the repo already pulled down, and then docs writers can pull docs independently).

**Comment by silverwind** [comment]
> +1 for submodule suggestion, as then it'll lessen the friction of contributions to docs (as then devs will at least have the repo already pulled down, and then docs writers can pull docs independently).

I find submodules unergonomic to use and I don't see any benefit in having them as it still means that any  feature that touches docs need to raise a second PR against the other repo and I guarantee many contributors will not go that extra mile.

My vote is to split the docs into two: Keep configuration and contribution-related docs in the repo and split out another "website" repo that holds less strictly reviewed content.

**Comment by lunny** [comment]
> > +1 for submodule suggestion, as then it'll lessen the friction of contributions to docs (as then devs will at least have the repo already pulled down, and then docs writers can pull docs independently).
> 
> I find submodules unergonomic to use and I don't see any benefit in having them as it still means that any feature that touches docs need to raise a second PR against the other repo and I guarantee many contributors will not go that extra mile.
> 
> My vote is to split the docs into two: Keep configuration (the "cheat sheet") and contribution-related docs in the repo and split out another "website" repo (like [this one](https://github.com/nodejs/nodejs.org)) that holds less strictly reviewed content.

I have said I will not be against the proposal. Please fire another issue or PR to do that.
But for this PR it can be merged ASAP to make less confustion.

**Comment by lunny** [comment]
> looks document related github action should be removed also

Fixed

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
I’ll send the submodule PR shortly

**Pull request merged**
