### PR TITLE
docs: swagger show models by default

### PR DESCRIPTION
**Pull request by noerw**
...instead of the examples, which don't get updated all the time.

this is a more persistent fix to #14875

### CODE REVIEW

**Comment by 6543** [comment]
nice idear ... but it had no effect on my test-setup :/

**Comment by noerw** [comment]
hm, works for me.. 🤔

**Review by 6543 — APPROVED** [review]
whatever now it works

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
