### PR TITLE
Replace inline script for critical JS with standalone script

### PR DESCRIPTION
**Pull request by silverwind**
The new script utilizes requestAnimationFrame to run DOM transformations as soon as possible. In my testing, this method is equivalent of a synchronous inline script in terms of outcome (no content flashes).

On Firefox, the callback sometimes fires too early and if that happens we register for another frame. I had 100% sucess within 2 frames in Firefox.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Although I approved the previous PRs, because I think there are other valuable changes, but not because I consider using hacky methods and inline script to avoid flicker is the proper way.

Using hacky methods and inline scripts to avoid every flicker is the wrong way. In the end, not every flicker can be avoided, because there could be something rendered again after the page gets loaded.

Take GitHub as an example:

image

image

**Comment by wxiaoguang** [comment]
And one more thing, instead of using these inline scripts, I recalled that we have discussed about that moving the Clone URLs into a dropdown menu, then there will be no flicker problem anymore.

**Comment by silverwind** [comment]
`requestAnimationFrame` is the proper way to mutate DOM without flicker. It can and should be avoided. It's just slopiness on GitHub's side that they still have these flickers.

I will also move all stuff in [formatting.js](https://github.com/yardenshoham/gitea/blob/main/web_src/js/features/formatting.js) into this script as well. These are all critical replacements.

**Comment by wxiaoguang** [comment]
> requestAnimationFrame is the proper way to mutate DOM without flicker.

Hmm, I am still not convinced that it's the proper way. Why `attempts>100`, not `50` or `1000`?

>  It's just sloppiness on GitHub's side that they still have these flickers.

I wouldn't consider as they are sloppiness. Sometimes when the backend (tmpl) and frontend (vue) rendered HTML are mixed together, it's very difficult (nearly impossible) to have a clear way to avoid all flickers.

**Comment by wxiaoguang** [comment]
After reading the code of `formatting.js`, I have another question about "I will also move all stuff in [formatting.js](https://github.com/yardenshoham/gitea/blob/main/web_src/js/features/formatting.js) into this script as well. These are all critical replacements.":

Even if you move the `formatting.js` into the `init.js`, it still have problems. Imagine a case like this:

```html
<script init.js>

<time id=time1>

<!-- 
very long content, which need a few seconds to transfer, 
then browser will partially render the content above,
while the remaining content will be rendered a few seconds later.
 -->

<time id=time2>

<script index.js>
```

How could you handle such case?

**Comment by silverwind** [comment]
> Hmm, I am still not convinced that it's the proper way. Why attempts>100, not 50 or 1000?

That's just a last-effort way to run the init function in case we never find the script tag. Fast browsers usually complete in 1 attempt, but depending on connection speed, it might take a few couple of attempts to find the element in the DOM.

**Comment by wxiaoguang** [comment]
> That will work as-is. It's going by the assumption that if `<script index.js>` is in the DOM, all preceding elements are in the DOM as well, which think is a rather safe choice. Could also change it to match on other stuff like `<footer>`, but it needs to be something that is present on every page.
>
> > Hmm, I am still not convinced that it's the proper way. Why attempts>100, not 50 or 1000?
> 
> That's just a last-resort way to run the init function in case we never find the script tag. Fast browsers usually complete in 1 attempt, but depending on connection speed, it might take a few couple of attempts to find the element in the DOM.


How could it work properly? For example:  `if (document.querySelector('script[src*="index.js"]') || ++attempts > 100) return init();`, if the page is partially render, does the requestAnimationFrame work? If requestAnimationFrame works, then the `init()` will run on a partially rendered page, then `<time id=time2>` won't be updated?

**Comment by silverwind** [comment]
I think behaviour of `requestAnimationFrame` during page-load ist mostly undefined behaviour and browser-specific, but we do not need to concern ourselves with it. If the `<script>` tag is not found, the function will recurse into itself and request another frame, again looking for the script tag, and only if it's found, it will call `init()`.

**Comment by silverwind** [comment]
So assuming `requestAnimationFrame` callbacks happen at a 60th of a second, it might be wise to increase the maximum number of attempts. I initially had it based on the `elapsed` time since page load, might be wise to use that again, and use something like 30s to run `init()`.

**Comment by wxiaoguang** [comment]
`Right, anything that happens after init will not be mutated. `, then how could this solution be proper ....

If a user's network is a little slow, they spends more than 1 seconds to fully load the page, then the `init()` won't take affect on newly rendered elements. They will see broken pages frequently?

**Comment by wxiaoguang** [comment]
However, I am still not convinced that it's the proper way. The methods used are too hacky and do not seem to be easily tested or maintained.

**Comment by silverwind** [comment]
It seems better than inline scripts which we should eliminate in an case because those are often forbidden via CSP.

**Comment by wxiaoguang** [comment]
> And one more thing, instead of using these inline scripts, I recalled that we have discussed about that moving the Clone URLs into a dropdown menu, then there will be no flicker problem anymore.

**Comment by silverwind** [comment]
The final solution to clone states will be a backend user setting, than you can just render the right stuff into HTML, no JavaScript involved.

**Comment by wxiaoguang** [comment]
Yup, there could be better solutions than hack the JS&DOM loading

**Comment by silverwind** [comment]
Yeah, but the date formatting unfortunately has no server-side solution, so it will need this mutation mechanism even after clone states are properly fixed, so I consider this effort unavoidable :)

**Comment by wxiaoguang** [comment]
The only challenge for date/time formatting is timezone.

Timezone-based date formatting could also have a server-side solution, eg:
* let users set their own timezone
* use relative date/time instead of accurate ones
* or even more: automatically save the browsers timezone to session and refresh the current page
    * when a user visits a page, render the session-saved timezone into the page, and use JS to check whether current session already has a timezone setting, if no, show a "preparing ..." shadow dialog and update the timezone to backend by API, then reload current page.


Personally, I think it's better to tolerate the slight flicker for timezone-based date formatting by JS instead of making the problem too complex.

**Comment by silverwind** [comment]
Personally, I can't tolerate flicker/layout shift during load, it's a sign of low-quality to me.

**Comment by wxiaoguang** [comment]
I can make a flawless solution for "or even more: automatically save the browsers timezone to session and refresh the current page ", if you do not mind.

Then the backend can get the browser's locale and timezone, and users can get consistent rendered result by backend and by frontend. It could be the best solution for Gitea at the moment because Gitea's frontend mixes a lot of things together.

**Comment by wxiaoguang** [comment]
I made a simple demo:
* https://github.com/go-gitea/gitea/pull/21443

**Comment by silverwind** [comment]
Would still like to eventually have a script like this a not all things can be done in webcomponents and I'd like to remove all the inline scripts eventually. Maybe there is a solution without `requestAnimationFrame`.

As for this PR, it's no longer needed.

**Comment by wxiaoguang** [comment]
I will try to refactor the `number` and `time` JS to Custom Elements.

The "Clone" popup could be resolved by #23231

**Comment by silverwind** [comment]
See if you can use https://github.com/github/relative-time-element for time.

I was referring to the recent inline JS added in https://github.com/go-gitea/gitea/pull/23553. Those should really be in `.js` files instead.

**Comment by wxiaoguang** [comment]
`PrettyNumber` => `LocaleNumber`: #23861

**Pull request closed without merging**
