### PR TITLE
Unescape wiki filename string

### LINKED ISSUE #8284: Wiki pages with special characters in mirrors are broken
- Gitea version (or commit ref): 1.10.0+dev-327-ga8c024043 (try.gitea.io)
- Git version: 2.17.1 (at least on my system. I don't know what try.gitea.io is using. Probably doesn't matter)
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/Tekaoh/gitea-wiki-test/wiki/Title-with-comma%2C-ampersand-%26-%5Bbrackets%5D (working wiki page being mirrored is at https://github.com/Tekaoh/gitea-wiki-test/wiki/Title-with-comma,-ampersand-&-%5Bbrackets%5D)

## Description

Github allows you to use special characters in the titles of wiki pages. If you mirror a Github repository with Gitea, it pulls the wiki as well. However, any wiki pages with special characters in the titles cannot be accessed. They redirect to `/wiki/_pages` instead.

### PR DESCRIPTION
**Pull request by Tekaoh**
This pull request allows wiki pages with special characters in the title to be accessed.

Fixes https://github.com/go-gitea/gitea/issues/8284

### CODE REVIEW

**Comment by Tekaoh** [comment]
Hmm... This build on my machine. I'll have to figure out what I did wrong to make the test build fail... Sorry about that

**Comment by Tekaoh** [comment]
Well, now I'm not too sure what... Maybe someone has a suggestion

**Comment by guillep2k** [comment]
It's failing the unit test `TestEditWikiPost()`:

image

Are you able to run that test it in your computer?

**Comment by guillep2k** [comment]
You can test it yourself using:
```
cd routers/repo
go test -tags="sqlite sqlite_unlock_notify" -run TestEditWikiPost
```

Or even better:
```
TAGS="sqlite sqlite_unlock_notify" make clean generate test
```
(that would run *all* unit tests, but not the integration tests).

**Comment by Tekaoh** [comment]
@guillep2k Thanks for the tip!

I think I've worked out a better solution. Basically the issue is that when `WikiNameToFilename()` passes the name through `url.QueryEscape()`, it actually no longer matches the filename in cases where there are special characters in the name. But the unit test has a fit when it's not there. So I added `url.QueryUnescape()` to `wikiContentsByName()` to correct any special characters later so that these pages can be accessed.

**Comment by Tekaoh** [comment]
I'm so sorry, I've kind of made a mess in this PR lol... I'm a noob. But at least I'm learning lots!

My build seems to have finished... Just waiting for the notify.

**Comment by guillep2k** [comment]
No worries.
Now your PR passes the tests, but the CI got stuck on 'notify'. Somebody will look into that.

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@Tekaoh could you add a unit test?

**Comment by Tekaoh** [comment]
@lunny I wouldn't know how, or even really what that means lol... I just took a try at fixing the bug I found. My commit fixes it, but I'm not entirely sure about all the correct procedures...

**Comment by lunny** [comment]
@Tekaoh You can find many example on https://github.com/go-gitea/gitea/blob/master/models/wiki_test.go#L33 and I think it's not complicated.

**Comment by Tekaoh** [comment]
I did some deeper digging and found that this PR is not going to be a good solution. I am therefore going to just close it for now.

Maintainers: Please see my explanation at https://github.com/go-gitea/gitea/issues/8284#issuecomment-538779094 and perhaps consider weighing in on what you think should be done. Thanks!

**Pull request closed without merging**
