### PR TITLE
Fix bug in issue labels API

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fix bug in `POST /repos/:owner/:repo/issues/:index/labels` and `PUT /repos/:owner/:repo/issues/:index/labels` endpoints. Also add integration tests for those endpoints.

### CODE REVIEW

**Comment by lafriks** [comment]
make fmt fails and needs to be fixed otherwise looks good

**Comment by ethantkoenig** [comment]
gofmt fixed

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by pgaskin** [comment]
LGTM

**Pull request merged**
