### PR TITLE
Add integrations tests from git cli

### PR DESCRIPTION
**Pull request by sapk**
Extracted from  #3152 for easy review process.

- Keep TestGit/SSH/LFS/Locks commented in the wait of  #3152
- Add big file test for covering #2930
- Disable update of publickeyfile with internal server.

### CODE REVIEW

**Comment by lafriks** [comment]
Remove debug but otherwise LGTM

**Comment by sapk** [comment]
@lafriks done. I don't know why it fix the blocking situation in previous commit. (maybe related to drone ?)

**Comment by strk** [comment]
trusted LGTM although the code is very hard to review, lots of things removed!

**Comment by sapk** [comment]
@strk I refactor some code to be in some function like generateCommitWithNewData, commitAndPush, lockTest and that why I wanted to extract it from #3152 to "ease" the review. 
This mostly duplicate existing http git clone to also do ssh tests.

**Pull request merged**
