### PR TITLE
Fix container download counter

### PR DESCRIPTION
**Pull request by KN4CK3R**
Increment counter on container manifest download.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Refactored to use a single method for the download part. Sorry about the change after the review.

**Review by Gusted — APPROVED** [review]

**Comment by 6543** [comment]
I'll need to check that code part first now ;) - give me some minutes

**Review by 6543 — APPROVED** [review]

**Review by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf — COMMENTED** [review]
🚀

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
awesome, thanks, works like a charm!

**Pull request merged**
