### PR TITLE
fix delete branches include / charactors after PR failed

### LINKED ISSUE #1397: Cannot delete branch with slash in name after PR
- Gitea version (or commit ref):1.1.0
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/username/branch-slash/pulls/1
  - [ ] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/Aarup/75908798b147e91ffb1133357acb44a1

## Description
If a branch has has a slash in the name like
  - bug/bugsId
  - feature/featureName
It is impossible to delete this branch using the web UI after a PR has been merged into the repository.
When clicking the "Delete branch" button a generic popup comes, but after entering username and password nothing happens - a 404 is received from the post

## Screenshots
image
image

### PR DESCRIPTION
**Pull request by lunny**
should fix #1397, but now the tests cannot be PASS because it seems macaron route's bug.

### CODE REVIEW

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by lunny** [comment]
It seems that macaron don't support the route `/a/*/delete` to match `/a/b/c/delete`. @Unknwon

**Comment by unknwon** [comment]
You're right, unfortunately, it does not...

**Comment by lunny** [comment]
I will send another PR to fix this.

**Pull request closed without merging**
