### PR TITLE
[WIP] [API] add ReactionSummary to Commit and Issue

### PR DESCRIPTION
**Pull request by 6543**
rev: https://github.com/go-gitea/gitea/issues/8313#issuecomment-549163564

`reaction_summary` is nil or:

```json
"reaction_summary": { 
      "heart": 1,
      "laugh": 2,
      "rocket": 6
}
```
* [x] function itself
* [x] exposed for issues
  - [x] add test
* [ ] exposed for issue_comments (should but not working
  -  [ ] add test

* [ ] **dont return user -> only count emojy by type**

### CODE REVIEW

**Comment by lafriks** [comment]
I still think it should same as github with only counts:
```
{
  "total_count": 5,
  "+1": 3,
  "-1": 1,
  "laugh": 0,
  "confused": 0,
  "heart": 1,
  "hooray": 0,
  "url": "<api>/repos/octocat/Hello-World/issues/comments/1/reactions"
}
```

**Comment by 6543** [comment]
@lafriks the problem is that github's responce don't allow custom reaction

should i rename the field from `reaction_summary` to `gitea_reactions` or something else to make sure it wont colide with github one?

**Comment by lafriks** [comment]
Why wouldn't it allow custom reactions? Pretty much it would not allow only reactions with name `url` and `total_count`

**Comment by 6543** [comment]
dont think this is a nice format to parce! @lafriks `"reactions":` is no array or list!

**Comment by lafriks** [comment]
Also I think that returning all users is too verbose, let's say there will be 1000 likes for issue or comment, for summary we should return only counts and if users are needed than we already have api for that

**Comment by lafriks** [comment]
It's dictionary ;)

**Comment by 6543** [comment]
@lafriks this is why i only use usernames but i can make it smaler ... it should realy be a summary.

the api to get detailed reaction is well defined and done at #9220

-> I'll remove the user and only return counter of reactions

**Comment by lafriks** [comment]
https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by 6543** [comment]
@lafriks update https://github.com/go-gitea/gitea/pull/9497#issue-356840126

**Comment by 6543** [comment]
no stale - it was just not enouth time to talk about how the responce should look like

**Pull request closed without merging**
