### PR TITLE
Fix no edit/close/delete button in org repo project view page 

### PR DESCRIPTION
**Pull request by yp05327**
Part of #23318.

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Seems present in 1.19: https://github.com/go-gitea/gitea/blob/release/v1.19/templates/repo/projects/view.tmpl. Likely a copy-paste issue done a long time ago?

**Comment by silverwind** [comment]
Came in https://github.com/go-gitea/gitea/commit/beab1dd337250cdef4e4a7588a19e7d711eb870e.

**Comment by silverwind** [comment]
.

**Review by yardenshoham — APPROVED** [review]

**Comment by yp05327** [comment]
@GiteaBot 
Done.

ps: Why you can't backport, there's no conflicts. 😕

**Comment by silverwind** [comment]
cc: @yardenshoham how are backports done? Just a `cherry-pick`?

**Comment by yardenshoham** [comment]
Yep, here's the code
https://github.com/GiteaBot/gitea-backporter/blob/a109a31de384669c9ed22f4af15eecd073ffec15/src/git.ts#L43-L100

If it fails we post the comment:
https://github.com/GiteaBot/gitea-backporter/blob/a109a31de384669c9ed22f4af15eecd073ffec15/src/backport.ts#L48-L58

**Comment by silverwind** [comment]
@yp05327 maybe next time you see this issue, try to replicate the steps the bot does so we can figure out where it goes wrong.

**Comment by yp05327** [comment]
@silverwind 
I see. I will try next time. :)

**Pull request merged**
