### PR TITLE
Fix border-radius of header+segment boxes

### PR DESCRIPTION
**Pull request by silverwind**
This is a very old bug with the bottom border-radiuses not being there and the `:has` selector now makes it possible to cleanly solve it. It affects all header+segment boxes, which there are many throughout the UI:

Screenshot 2024-04-23 at 20 47 21

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
I created #30673 to list almost all the possible UI border-radius problems.

**Comment by silverwind** [comment]
I imagine this PR likely fixes half of them.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
> I imagine this PR likely fixes half of them.

That PR just listed all problems which haven't been fixed by this PR.

**Comment by silverwind** [comment]
Ok, wouldn't have thought there'd be still so many. I will check them out later.

**Pull request merged**
