### PR TITLE
Rephrase comment about RuntimeDirectory option in systemd config

### PR DESCRIPTION
**Pull request by anthonyvdotbe**

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
So I don't really understand that line at all. It probably needs rewriting to be clearer.

**Comment by anthonyvdotbe** [comment]
I've rephrased the comment.

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
Mouch more understandable

**Comment by 6543** [comment]
@zeripath kind/doc  perhaps?!?

**Comment by 6543** [comment]
@anthonyvdotbe can you make the issue title more specific & update the branch to start CI again?

**Pull request merged**
