### PR TITLE
Add Approval Counts to pulls list

### PR DESCRIPTION
**Pull request by zeripath**
Add simple approvals counts to pulls lists

As #9274 appears to have slightly stalled this PR adds simple approvals counts to the pull lists.

### CODE REVIEW

**Comment by jaqra** [comment]
Should we add this to `milestone_issues.tmpl` ?

**Comment by zeripath** [comment]
OK I think I'm gonna stop where I am. Realistically for simplicity we should have a column on the pulls which is set to whether they're ready to merge or not - but this is better than the current situation.

@jaqra I'm not sure about the milestones page, conflicting files are not listed on there at present so I didn't copy this.

**Comment by lunny** [comment]
The problem is still there when a reviewer approval at first but then rejected. @zeripath

**Comment by guillep2k** [comment]
@lunny as per #9055 only one "official" review per user is counted; approvals and rejections are mutually exclusive.

https://github.com/go-gitea/gitea/blob/9f1f2e66757d49a7e7096501514bd90a53190ec0/models/review.go#L290-L299

**Comment by lunny** [comment]
@guillep2k But that only for official reviewer. For un official reviewer, it always keeps false.

**Comment by guillep2k** [comment]
> 
> 
> For non-official reviewer, it always keeps false.

Now I see what you mean. Yes, the counts will be off like this.

**Comment by lunny** [comment]
@guillep2k Only official counts is reasonable.

**Comment by jamesorlakin** [comment]
> @jaqra I'm not sure about the milestones page, conflicting files are not listed on there at present so I didn't copy this.

I confess the reason it's not there is because I forgot about that page! 😀

**Comment by guillep2k** [comment]
@zeripath because of limitations in the way unofficial reviews are accounted, this PR will be displaying wrong information about them at its current state. If you could limit this PR as to only care about official reviews, then it would be proper; unofficial reviews could be fixed another time.

#### Details

There are "official" reviewers and there are "official" reviews. Unfortunately the word "official" is used differently in each case. An "official" review is _the latest_ review from a whitelisted user. Any other review is "unofficial", no matter who posted it.

Currently, the following happens when a review is added:

* If the user is **not** whitelisted, the review is marked "unofficial".
* If the user is whitelisted, any previous reviews from that user are changed to "unofficial". The new review is inserted as "official".

So, the "official" pool of reviews has exactly one approval or rejection from each reviewing whitelisted user. The "unofficial" pool contains all the other reviews, even outdated, mixing up indiscriminatedly approvals and rejections from all users, including whitelisted.

**Comment by lunny** [comment]
Thanks @guillep2k to clarify. That's really what I mean. :(

**Comment by zeripath** [comment]
We should be replacing the approval/rejection for non-official reviewers at the time of approval. I'll hide the non-official counts.

**Comment by zeripath** [comment]
I predict that within 1 week of this being merged without display of non-official reviewers we will get bug-reports stating that their reviews are not being shown.

**Review by guillep2k — APPROVED** [review]

**Comment by zeripath** [comment]
OK so it looks like the bulk of `templates/repo/issue/milestones_issues.tmpl` should not exist as it is essentially a copy of  `templates/repo/issue/list.tmpl`. Further there's an issue with this list in that it doesn't easily differentiate between issues and PRs.

**Comment by zeripath** [comment]
OK I've updated the milestones page - however this needs better thought as it mixes Issues and PRs in one list too. - That can be done as another PR I think

**Comment by lunny** [comment]
Just found #10624

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
