### PR TITLE
Prevent empty div when editing comment

### LINKED ISSUE #10220: Editing comment leaves empty div segment
- Gitea version (or commit ref): 1.11.0
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description
When editing comment, upon submission, `div` element with classes `ui bottom attached segment` is created/left. The element of course disappears on page refresh.

## Screenshots
After editing:
firefox_2020-02-10_21-56-30
Before editing:
firefox_2020-02-10_21-56-44

### PR DESCRIPTION
**Pull request by zeripath**
The template for attachments needs to remove whitespace and return an empty response when there are no attachments.
    
Fix #10220
    
Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Could be backported to v1.12

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
for everybody who like to have the documentation of the template changes:
https://golang.org/pkg/text/template/#hdr-Text_and_spaces

**Comment by zeripath** [comment]
make lg-tm work

**Comment by 6543** [comment]
backport: #12992

**Pull request merged**
