### PR TITLE
Fix random string generator

### PR DESCRIPTION
**Pull request by denji**
This PR fixes the following issues gogits/gogs#3953:

* The random string generator was [modulo-biased](https://stackoverflow.com/a/10984975).
* The random string generator silently ignored any errors returned by `rand.Read`. In the worst case, `GetRandomString` would simply return an empty string.

### CODE REVIEW

**Comment by lunny** [comment]
drone failed. seems build error

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
Is there a reason why we're only using alphanumeric characters?

**Comment by tboerger** [comment]
I can't see a real reason but this code looks more solid to me

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
