### PR TITLE
Disable WYSIWYG editor for mobile user agents (temporary fix)

### PR DESCRIPTION
**Pull request by corneliusroemer**
Written by @ashimokawa for codeberg.org here https://codeberg.org/Codeberg/build-deploy-gitea/commit/840fd48cad0c72933becafbe561addc6cdfb11e2
This PR adds a "custom header" that acts as if a user clicks on the "disable WYSIWYG" button if their user agent suggests a mobile device.

This is clearly only a temporary high-level hotfix for the problem until a more permanent solution is figured out.

Temporarily fixes mobile issues #10729 #12146 #10110

### CODE REVIEW

**Review by 6543 — CHANGES_REQUESTED** [review]
did  #13333 not solve the problem for v1.14.0 ?

I think we can use this pull as hotfix for v1.13.x versions ...

**Comment by corneliusroemer** [comment]
> did #13333 not solve the problem for v1.14.0 ?

I can't say anything about v.1.14.0 solving it. How can we test?

> I think we can use this pull as hotfix for v1.13.x versions ...

I don't know how to do this, do I need to do anything for that or can you handle the details?

Github says you requested changes, but I can't see any. Is that normal?

**Comment by 6543** [comment]
> I can't say anything about v.1.14.0 solving it. How can we test?

https://try.gitea.io run always on latest (master) - there you can test as you like ;)
 
> I don't know how to do this, do I need to do anything for that or can you handle the details?

for "backport" & hotfix ... for v1.13.x target `release/v1.13` branch for a pull (can be changed on github afterwards, but you have to rebase your branch)

> Github says you requested changes, but I can't see any. Is that normal?

yes - i just commented

**Comment by corneliusroemer** [comment]
I'll try to change branch... Let's see whether I can do it here within Github.

**Comment by 6543** [comment]
@corneliusroemer done - are you familiar with rebase?

If not just give me write permissions and I'll do

PS: this need more work anyway since we can use custom - we have to integrate it into the "real" template

**Comment by corneliusroemer** [comment]
@6543 Thanks for your help!
I've rebased the commit onto v1.13 and created a new PR - was that necessary or could I've kept this PR open and used the new commit instead of the old one?

#14022

**Comment by 6543** [comment]
you could have force pushed things ... but create a new pull is also fine

**Comment by corneliusroemer** [comment]
@6543 yeah I think I could have used amend on the commit, right? Looks a bit too complicated for me for the moment. Learning PRs in baby steps. https://github.com/github/hub/issues/198

**Pull request closed without merging**
