### PR TITLE
Godep Initial Commit

### PR DESCRIPTION
**Pull request by techzilla**
Godep Initial Commit, Best effort as the head would be the best to run godep save.

### CODE REVIEW

**Comment by tboerger** [comment]
Who said that we switch to godeps?

**Comment by techzilla** [comment]
Do we have a system in place now to maintain our dependencies?

**Comment by tboerger** [comment]
I have no problem with replacing gopm with godeps.

**Comment by linquize** [comment]
Why do you commit so many files? The use of dependency management system is to just declare the package versions in a manifest file.

**Comment by techzilla** [comment]
The files that are checked in were vendored in from my present workspace, It's all created by, 
   godep save

Vendoring dependencies, is what the go team recommends for non-library projects.  Godep is just the tool projects have been using most often, and it's supported by Travis CI.

Ideally again, we'd want Lunny to update this initial import, so then we could all work from his work space.  This will greatly aid developing for gitea also, because this provides us a buildable project at clone, and ensure we all work from the same project workspace.

**Comment by techzilla** [comment]
Not ready yet, I just tested the reproducibility, it bombed out.  I'm gonna fix this and req a new pull once I can get everything working on a fresh workspace.

**Comment by lunny** [comment]
Hi, I would like to convert to Go 1.5 with internal for sub folder and vendor for specify extenal packages. Of course, we can do it at v0.8 after v0.7.

**Pull request closed without merging**
