### PR TITLE
Rename custom/conf/app.ini.sample to custom/conf/app.example.ini for better syntax light on editor

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by silverwind** [comment]
Need to update docs and `.gitignore`.

**Comment by silverwind** [comment]
While we're renaming this, I'd prefer `app.example.ini` over `app.sample.ini`.

**Comment by mrsdizzie** [comment]
Maybe app.default.ini? since these aren't just examples/samples but actually contain the default values in use for everything (and makes it obvious to look there for all default settings)

**Comment by silverwind** [comment]
> Maybe app.default.ini

I think the general expectance is that users copy the file to the actual config file and in this case, I think "example" fits better than "default", even thought gitea can probably run without a config file in simple cases.

**Comment by zeripath** [comment]
Users really should not copy the app.ini.sample as the default. We really should not encourage that!

If we want to provide them with a basic app.ini we should do that.

**Comment by silverwind** [comment]
> Users really should not copy the app.ini.sample as the default

Why not? It gets you a full set of options. It's a perfect starting point imho :)

**Comment by jolheiser** [comment]
I've always just gone with the minimal one generated with installation and then added settings as needed.

I don't like the clutter of a bunch of settings that are all default if I can avoid it, if only because our config is massive.

**Comment by silverwind** [comment]
I see, a minimal approach can be viable as well so fine with naming it "default" as well.

**Comment by zeripath** [comment]
* It hardcodes all sorts of currently default options into your app.ini preventing you from benefiting from updates to defaults.
* There's examples in there that don't represent any real config - e.g. in the logging section.
* It prevents settings which change the default setting of other settings from working. (I'm not sure I can immediately think of a case but I bet there is a case.)
* It makes Gitea appear harder to configure than it really is.

In most configuration less is more.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
it got my lgtm - like the idear but it will need some update here:
```
docs/content/page/index.en-us.md
78:        - [app.ini](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)

docs/content/page/index.fr-fr.md
73:        - Voir [ici](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)

docs/content/doc/advanced/customizing-gitea.en-us.md
38:- [Complete List](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)

docs/content/doc/advanced/customizing-gitea.zh-cn.md
25:- [完整配置清单](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)

docs/content/doc/advanced/config-cheat-sheet.zh-cn.md
18:这是针对Gitea配置文件的说明，你可以了解Gitea的强大配置。需要说明的是，你的所有改变请修改 `custom/conf/app.ini` 文件而不是源文件。所有默认值可以通过 [app.ini.sample](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample) 查看到。如果你发现 `%(X)s` 这
样的内容，请查看 [ini](https://github.com/go-ini/ini/#recursive-values) 这里的说明。标注了 :exclamation: 的配置项表明除非你真的理解这个配置项的意义，否则最好使用默认值。

docs/content/doc/advanced/config-cheat-sheet.en-us.md
26:accurately recorded in [app.ini.sample](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)
466:- `ALLOWED_TYPES`: **see app.ini.sample**: Allowed MIME types, e.g. `image/jpeg|image/png`.

docs/content/doc/features/authentication.en-us.md
99:    app.ini](https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample)
```

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
