### PR TITLE
WIP: Rename project -> board, board -> column

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by delvh** [comment]
Should we perhaps make this PR breaking by also renaming the config options
(`[repository].{DEFAULT,DISABLED}_REPO_UNITS`, (description in `[ui].ISSUE_PAGING_NUM`),`[project].*`)
?

**Comment by lunny** [comment]
> Should we perhaps make this PR breaking by also renaming the config options (`[repository].{DEFAULT,DISABLED}_REPO_UNITS`, (description in `[ui].ISSUE_PAGING_NUM`),`[project].*`) ?

Maybe add depreciated in all `[project]` section configurations and start a new section named `[board]`? 
`[ui].ISSUE_PAGING_NUM` should be moved to database based system configuration.

**Comment by delvh** [comment]
`[ui].ISSUE_PAGING_NUM`: for that I simply meant the description, as it's probably best to purge `project` completely from the words used in this repo to prevent confusion.

> Maybe add depreciated in all [project] section configurations and start a new section named [board]?

That was also my intention.
We can also deprecate the now invalid values inside `{DISABLED,DEFAULT}_REPO_UNIT`, so that this PR does not break anything for now, only to warn that it will be removed in a later version.

**Comment by lunny** [comment]
Closed as too many conflicts.

**Pull request closed without merging**
