### PR TITLE
fix LFS listlocks API and locksverify API nextCursor bug

### PR DESCRIPTION
**Pull request by zh1C**
Fixed the bug of LFS listlocks API and locksverify API nextCursor, For a detailed description, please refer to the following issue: https://github.com/go-gitea/gitea/issues/27973

### CODE REVIEW

**Comment by KN4CK3R** [comment]
`cursor` is used as page and not as index, so the old code should be correct. `GetLFSLockByRepoID` uses `cursor * limit` as starting point.

**Comment by zh1C** [comment]
Sorry, I didn't see the code of the `GetLFSLockByRepoID` function. I would like to ask whether the `cursor` can be used as both an index and a page. Is it specifically related to the LFS server implementation?

**Comment by KN4CK3R** [comment]
I don't think I understand your question. I understand the LFS API like this: There may be support for a `cursor` parameter but we don't specify what's the content of that parameter. Therefore it could be an index, a page or event a "name" if you sort the locks by theri uuid and tell the client "continue with this one".

**Comment by zh1C** [comment]
Thank you for your explanation. I was under the impression that a `cursor` could only be an index, but it turns out it can be either an index or a page, depending on the specific implementation of the LFS server. I will close this PR.

**Pull request closed without merging**
