### PR TITLE
Use testing/benchmark interface

### PR DESCRIPTION
**Pull request by sapk**
Allowing us to do benchmark in integrations tests. (like for #1983)

### CODE REVIEW

**Comment by sapk** [comment]
Build fail because of "database table is locked" but I don't think this is related to those PR changes.

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
@sapk but it seems `testing.TB` is a new feature of go1.8?

**Comment by sapk** [comment]
Haven't checked this but even it's only use in test. So not a great impact on running platform.

**Comment by sapk** [comment]
@lunny I have checked and It has been in go source code for 4 year (https://github.com/golang/go/commit/35d8bb39bd7953dddead3d97db32af77d8941563)

**Pull request merged**
