### PR TITLE
finaly fix gitlab migration with subdir 2.0

### PR DESCRIPTION
**Pull request by 6543**
followup of  #13629 based on https://github.com/go-gitea/gitea/issues/13535#issuecomment-730542428

also fix an issue by ignoring 404 error when try to get mergerequest approval

yes befor declare it readdy I'll test this cases:
* [x] https://gitlab.alpinelinux.org/6543/aports
* [x] https://framagit.org/framasoft/peertube/PeerTube.git
* [x] https://gitlab2.pr.gitea.io/gitlab/root/normalprivate.git
* [x] https://gitlab2.pr.gitea.io/gitlab/root/newpublic/
* [x] https://gitlab2.pr.gitea.io/gitlab/g1/subgroup1/asubgroupproject.git
* [x] https://gitlab2.pr.gitea.io/gitlab/g1/subgroup1/subsubgrrr/now-you-know.git
* [ ] https://gitlab.com/Remmina/Remmina -> (#13648)
* [x] https://gitlab2.pr.gitea.io/gitlab/gitlab/root/t2.git
* [x] https://gitlab2.pr.gitea.io/gitlab/gitlab/g1/subgroup1/subsubgrrr/now-you-know.git

### CODE REVIEW

**Comment by 6543** [comment]
collected error logs:
```
Migrate repository from https://gitlab.alpinelinux.org/6543/aports failed: GET https://gitlab.alpinelinux.org/api/v4/projects/281/merge_requests/2/approval_state: 404 {error: 404 Not Found}
```

**Comment by 6543** [comment]
@pat-s I hope with THIS *final* one you can migrate

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by jolheiser** [comment]
Please packbort 🙃

**Comment by techknowlogick** [comment]
lets wait to backport until we can confirm that it works on @pat-s' gitlab install

**Comment by pat-s** [comment]
We're getting there but are not quite there yet for me

```
Migrating from http://DOMAIN/gitlab/patrick/test.git failed.

GET https://DOMAIN/gitlab/api/v4/projects/patrick/test: 404 {error: 404 Not Found}
````

The GET request seems ok now. Token was set - any idea? Internal rewriting issues of the GL install?

**Comment by 6543** [comment]
Did you set the subdir in gitlab or have you setup rewrite rouls via reverse proxy?

**Comment by pat-s** [comment]
> Did you set the subdir in gitlab

Yes - this is required when running GL in a subpath according to the docs. It also won't work without it.


NGINX config

```
   location /gitlab/ {

       client_max_body_size 0;
       gzip off;

       proxy_read_timeout      300;
       proxy_connect_timeout   300;
       proxy_redirect          off;

       proxy_http_version 1.1;

       proxy_set_header    Host                $http_host;
       proxy_set_header    X-Real-IP           $remote_addr;
       proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
       proxy_set_header    X-Forwarded-Proto   $scheme;

       proxy_pass http://localhost:8929/gitlab/;
   }
```

**Comment by 6543** [comment]
Do you have GL log's about requests, so we can see why it returns 404

**Comment by pat-s** [comment]
I don't see any errors in GL. Excerpt from `production.log`.
I've also looked through most other logs but might have missed some.

```
Started POST "/gitlab/profile/personal_access_tokens" for IPGITEA at 2020-11-23 06:36:46 +0000
Processing by Profiles::PersonalAccessTokensController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "personal_access_token"=>"[FILTERED]"}
Redirected to http://DOMAIN/gitlab/profile/personal_access_tokens
Completed 302 Found in 78ms (ActiveRecord: 29.7ms | Elasticsearch: 0.0ms | Allocations: 19098)
Started GET "/gitlab/profile/personal_access_tokens" for IPGITEA at 2020-11-23 06:36:46 +0000
Processing by Profiles::PersonalAccessTokensController#index as HTML
Completed 200 OK in 108ms (Views: 77.6ms | ActiveRecord: 6.1ms | Elasticsearch: 0.0ms | Allocations: 86789)
Started GET "/gitlab/help" for 127.0.0.1 at 2020-11-23 06:37:19 +0000
Processing by HelpController#index as */*
Completed 200 OK in 576ms (Views: 567.7ms | ActiveRecord: 1.6ms | Elasticsearch: 0.0ms | Allocations: 363122)
Started GET "/gitlab/api/v4/version" for IP at 2020-11-23 06:37:51 +0000
Started GET "/gitlab/api/v4/projects/patrick/cynkra-test" for IP at 2020-11-23 06:37:52 +0000
Started GET "/gitlab/help" for 127.0.0.1 at 2020-11-23 06:38:19 +0000
```

I suspect it might be an issue with the GL namespace in that install. I can do

```
curl --include "https://DOMAIN/gitlab/api/v4/projects/3?private_token=TOKEN"
HTTP/2 200
[...]
```

but I fail when doing

```
curl --include "https://DOMAIN/gitlab/api/v4/projects/patrick/cynkra-test?private_token=TOKEN"
HTTP/2 404
[...]
```

https://github.com/go-gitea/gitea/issues/13269 seems to be related.

Using the project ID in the importer directly as suggested in #13269 does not work for me though.

**Comment by 6543** [comment]
Ok in this case this patch works, and I'll backport it now - and I would try to look who is returning 404 and then why ...

**Comment by 6543** [comment]
Backport: #13678

**Pull request merged**
