### PR TITLE
use hosted runners for nightly actions (#27485)

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #27485 by @techknowlogick

I'm temporarily unable to properly evaluate actuated runners, and so I'm switching back to hosted runners until I am able to focus on that again.

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
blocking temporarily

**Comment by techknowlogick** [comment]
@silverwind I'm not sure I've done the reusable workflow correctly. I ended up moving to its own job in `main`, but that doesn't make sense since I think it should clean in each job rather than by itself.

**Comment by silverwind** [comment]
I wonder if there are more lightweight images available, would certainly be better than cleaning up all this crap 😆.

**Review by silverwind — DISMISSED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
There is a lint failure on main branch:

```
.github/workflows/release-nightly.yml:15:14: label "nscloud" is unknown. available labels are "windows-latest", "windows-2022", "windows-2019", "windows-2016", "ubuntu-latest", "ubuntu-22.04", "ubuntu-20.04", "ubuntu-18.04", "macos-latest", "macos-latest-xl", "macos-13-xl", "macos-13", "macos-13.0", "macos-12-xl", "macos-12", "macos-12.0", "macos-11", "macos-11.0", "macos-10.15", "self-hosted", "x64", "arm", "arm64", "linux", "macos", "windows", "actuated-4cpu-8gb", "actuated-4cpu-16gb". if it is a custom label for self-hosted runner, set list of labels in actionlint.yaml config file [runner-label]
   |
15 |     runs-on: nscloud
```

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
