### PR TITLE
Fix issue/pull request list assignee filter

### LINKED ISSUE #13641: Filtering in Pull Request kept all the time.
- Gitea version (or commit ref):  1.14.0+dev-239-gad2a28862
- Git version: See try.gitea.io (also 1.13.0-rc2)
- Operating system:
   - See try.gitea.io

- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes 
  - [ ] No
  URL to reproduce: https://try.gitea.io/khmtestorga/testrepo/pulls
 
## Description
If you goto the URL for the pull request you see a list (in this case exactly one) of pull request.

Now you can filter those entries by the Type as shown in the image:

pull-reqest-1

After the selection (as shown next) you will not see any entry which is perfectly fine:

pull-request-2

But now the problem arises: If you select from the "Type" -> `All Issues` the result kept empty in contradiction to before cause there was exactly one entry: (See the screen shot):

pull-request-3

Any selection of the filters does  not change the filter given in the URL (as you can see in the last screen shot) which results in not being able to remove all the filters and going back to the beginning with the plain url `https://try.gitea.io/khmtestorga/testrepo/pulls` ...which can only be achieved if you manually select a complete different part and going back to pull requests.... 

The point seemed to be that if I select of "Type" -> "Assigned to you" a parameter `assignee=42393` will be added to the URL. But that parameter can not be removed via "Type" -> "All Issues". 

This can only be achieved if I select from "Assignee" manually "All Assignees" ... 

Selecting the "Type->All Issues" could set the `assignee=0` in the URL. This would resolve this inconvenience? 

The question is: Is this a bug or intended behaviour?

### PR DESCRIPTION
**Pull request by khmarbaise**
- The URL contains all the time the assignee in cases
   where once a type has been selected.

Signed-off-by: Karl Heinz Marbaise <kama@soebes.de>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by jolheiser** [comment]
ping lgtm

**Comment by jolheiser** [comment]
Please send backport to `release/v1.13` 🙂

**Comment by khmarbaise** [comment]
> Please send backport to `release/v1.13` 🙂

does this mean I should create another PR against v1.13 branch?

**Comment by techknowlogick** [comment]
>does this mean I should create another PR against v1.13 branch?

Yup, a cherrypick would do.

For sake of convenience I've created a copy-paste you could use:
```
git remote add upstream git@github.com:go-gitea/gitea.git
git fetch upstream
git checkout upstream/release/v1.13 -b backport-13647
git cherry-pick 702e82d
git push origin backport-13647
```

**Comment by 6543** [comment]
example: #13591

**Pull request merged**
