### PR TITLE
Bug fixes and unit tests for org_team

### PR DESCRIPTION
**Pull request by ethantkoenig**
- Unit tests for `models/org_team.go`
- Fix a bug in `DeleteTeam(..)` where stale entries in the `team_repo` table were not deleted.
- Some minor cleanups in `models/org_team.go` (remove unused functions, fix misformated error message, etc.)

### CODE REVIEW

**Comment by andreynering** [comment]
LGTM

**Comment by lunny** [comment]
Build faild

**Comment by ethantkoenig** [comment]
@lunny Lint error from #1017, restarted.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
