### PR TITLE
models: break out of loops

### PR DESCRIPTION
**Pull request by alrs**
This fixes three spots in the `models` package where a `break` was being called from a `switch` that was inside a `for` loop, turning it into a no-op. This labels the outer loop so the `break` will make it out of both the `for` and the `switch`.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
mea culpa.

**Comment by cornelk** [comment]
will an empty case not result in the same result but not require a goto and lable?

**Comment by zeripath** [comment]
@cornelk compare:

https://play.golang.org/p/TFSvn_2IK6T

with:

https://play.golang.org/p/arHLETHlrm9

or:

https://play.golang.org/p/gi550S1EmOP

**Comment by zeripath** [comment]
the error came from when during a failed refactor attempt I tried to move this out to a method that returned directly - but didn't I unwind the refactor completely

**Comment by lafriks** [comment]
Maybe break could be replaced with `return true, signingKey, nil`. I know it duplicates code but at least label is not needed :)

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
