### PR TITLE
Markup color and font size fixes

### PR DESCRIPTION
**Pull request by silverwind**
1. Distinguish inline an block code with new CSS variable `--color-markup-code-inline`
2. Various color tweaks, better contrast from background

Screenshot 2024-04-05 at 00 51 00
Screenshot 2024-04-05 at 00 50 44

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Light theme needs a bit more contrast I guess, will tweak.

**Comment by silverwind** [comment]
This will fix https://github.com/go-gitea/gitea/issues/30292, but I will do another refactor to get rid of `:not` as discussed in https://github.com/go-gitea/gitea/pull/30294.

**Comment by silverwind** [comment]
Depends on https://github.com/go-gitea/gitea/pull/30298.

**Comment by silverwind** [comment]
Unnecessary rules removed, colors tweaked. Now that https://github.com/go-gitea/gitea/pull/30298 is merged, I was able to remove both new rules that were added before.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
