### PR TITLE
Add matrix to support

### PR DESCRIPTION
**Pull request by jolheiser**
This PR adds our matrix space to the support options and alphabetizes the list.

I also considered adding our Mastodon, however that isn't as suitable as the other options because it's just whoever has access to the account vs a community chat/forum.

### CODE REVIEW

**Comment by techknowlogick** [comment]
I'm leaving this as a non blocking comment. While I've linked the two rooms, reliability is spotty and this leads to many people thinking they are being ignored when messages are dropped. So by directing people to the other room they may receive a poor experience.

**Comment by jolheiser** [comment]
True, although I think IRC is more frequently the culprit.

I could add a comment about it being bridged, the main reason for this PR is to give an avenue for the Discord-averse users who want to chat vs use a forum.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Well, the bridging is not stable, so I also agree to recommend users to use discord as the first choice.

**Comment by silverwind** [comment]
Don't need to sort the list imho, a bit of self-advertizing by putting "Paid Commercial Support" first could also be good for the project health.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
