### PR TITLE
Support running subtests manually

### PR DESCRIPTION
**Pull request by typeless**
Since GNU Make does not allow '/' in the target patterns, we translate the subsequent '#' into '/' for "go test -run".

Example:, `make test-sqlite#TestGit.HTTP.Standard.PushCommit.Big`

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
I'm not sure how valid some of these subtests are by themselves but certainly we should support them

**Comment by typeless** [comment]
@zeripath  yeah, I skip the `pr#` target in particular as I am not sure if it is applicable. For the others, I suppose they are fine. The failures in the CI tests are more baffling to me though.

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
@typeless How about `make test-sqlite#TestGit.HTTP.Standard.PushCommit.Big`

**Comment by typeless** [comment]
@lunny SGTM. Updated.

**Comment by guillep2k** [comment]
Ping LG-TM

**Pull request merged**
