### PR TITLE
Show outdated comments in pull request

### LINKED ISSUE #12523: Show outdated comments in pull request
- Gitea version (or commit ref):
1.13.0+dev-295-g16980d13c

- Git version:
2.17.1

- Operating system: 
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
If I get comment and make change, this comment will close, and I need to click button "**Show outdated**" for see it. It is a problem. I must see the comments.

### PR DESCRIPTION
**Pull request by ivanvc**
This PR addresses issue #12523. Outdated comments are expanded by default and added an "Outdated" label to them. Resolved comments are collapsed by default. This is how it initially looks when loading the pull request:

Screenshot from 2020-10-14 17-34-04

* The first comment was marked as resolved.
* The second comment is outdated as that line was changed in a commit.
* The last comment is neither resolved nor outdated.

Fixes #12523.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
IMO could be backported to 1.13 as it's been a long-term gripe for users.

**Comment by lafriks** [comment]
what the hell... I did press update branch but it somehow got merged :/

**Comment by lafriks** [comment]
please send backport

**Comment by ivanvc** [comment]
@lafriks I'll start a new PR as I can't re-open this one. However, I was thinking if I should refactor, or create a generic "tip" css class as the same style is used in at least three places. I didn't do it before, because couldn't find a place in the css where the style for the basic elements is defined.

Thoughts? Or should I just keep it as is?

**Comment by 6543** [comment]
@ivanvc I'll have done the backport for you :)

```sh
git fetch --all
git checkout -f upstream/release/v1.13 -b backport_show-outdated-comments-in-pull-request_131
git cherry-pick -S 05c7e58
git push -u own backport_show-outdated-comments-in-pull-request_13148
```
-> #13162

"... I can't re-open ..." @ivanvc pleace do a new pull for each task/issue - and yes refactors are welcome too :)

**Comment by ivanvc** [comment]
@6543 Cool, thanks. I'll refactor later the CSS to make it more standard and open a PR against master, as I guess it is just an improvement.

**Pull request merged**
