### PR TITLE
Use time/tzdata for timezone in docker 

### PR DESCRIPTION
**Pull request by sapk**
We can remove tzdata of container and use go1.15 in binary timezone.

For details: https://golang.org/doc/go1.15#time/tzdata

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
any benefits to use build in func?

**Comment by sapk** [comment]
@6543 it is multiple little improvement:
- no need to download a package (time and data consuming)
- simplify/limit arch different comportement
- less file in image
- should reduce a little the image size

Those are not great improvement but a step forward to remove external binary and file dependency.

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Votes for 1.13? I think it's self-contained so can be merged into 1.13 as we build with 1.15.x

**Comment by zeripath** [comment]
@sapk if you update I think we can merge this in to 1.13

**Comment by techknowlogick** [comment]
@sapk can you allow commits from other maintainers to this PR?

**Pull request merged**
