### PR TITLE
Set appropriate `autocomplete` attributes on password fields

### PR DESCRIPTION
**Pull request by silverwind**
`new-password` prevents annoying autocompletion in some cases, thought it's not semantically correct to use that for example on all three fields on the user account page, so some annoyances remain.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I've set this as 1.14 but if it's approved before 1.13 is ready I think it would be reasonable to merge before.

**Review by lafriks — APPROVED** [review]
All current browsers will still ignore `autocomplete="off"` but it will not hurt :)

**Comment by lafriks** [comment]
:rocket:

**Comment by silverwind** [comment]
> All current browsers will still ignore autocomplete="off"

I'm still hoping that some password managers will eventually start to honour it 😉

**Pull request merged**
