### PR TITLE
Reduce conditionals in signin/signup inner forms

### PR DESCRIPTION
**Pull request by strk**
by always using SignInLink and SignUpLink in the form action

### CODE REVIEW

**Comment by lunny** [comment]
why not use `LinkAccountMode`?

**Comment by strk** [comment]
The goal of this PR is to _reduce_ conditionals, so the reason NOT to use `LinkAccountMode` is because it'd be another conditional. Why would you want to add so much logic in a template ?

Templates would ideally be as simple as possible, as they are meant to be customized.

Now why would you keep it ?
Also, what does `LinkAccountMode` mean, exactly ? What are you linking ? Where does it say it's about `OAuth2` ? Or should it also be for `OpenID` ? Let's start reducing the use of those conditionals, then maybe we'll be able to do w/out them completely.

**Comment by ethantkoenig** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by bkcsoft** [comment]
It's better than before so I'm merging :)

**Pull request merged**
