### PR TITLE
Move packages to internal

### PR DESCRIPTION
**Pull request by lunny**
As an application repository, Gitea should keep best practices to keep main sub-packages in `internal`.
This PR move `cmd`, `models`, `modules`, `services`, `routers` into `internal`.

- [x] Fix lint-yml, before this PR, looks like it never work.

### CODE REVIEW

**Comment by delvh** [comment]
If we are doing something like that, can we at least move it to a sane directory like `src`?

**Comment by delvh** [comment]
Reason: With `src` I always know that it contains the code of an application.
With `internal`, I always think that it can contain anything but something that should preferably not be seen by others as it is only relevant in really specific cases, not that the entire product depends on it.

**Comment by techknowlogick** [comment]
`internal` has specific connotations for go code, meaning it isn't meant to be imported by an external repo. It's a fairly standard directory structure for go apps.

**Comment by lunny** [comment]
> Reason: With `src` I always know that it contains the code of an application. With `internal`, I always think that it can contain anything but something that should preferably not be seen by others as it is only relevant in really specific cases, not that the entire product depends on it.

I also think that because many other languages use `src/`(especially rust) to do that. But as I know, many APP projects use `internal` which may be the current best practice.
Of course if most of us think we can move it to `src/` I can also do that. :)

**Comment by JakobDev** [comment]
I'm not a huge fan of. While I understand the motivation, I don't think it is wort it. Gitea is a widely used project. There are Users who patch their Gitea. There are also many open PRs on GitHub. Changing the file structure will cause a lot of work with almost none benefit.

**Comment by wxiaoguang** [comment]
I do not see any benefit.

**Comment by lunny** [comment]
Gitea should not provide as packages like I said above, this will prevent unnecessary requirements requests or blocks from those who want to depend on Gitea's packages as an import path. We ever done much bigger refactors than this one and I don't think this will make many PRs difficult.

**Comment by jolheiser** [comment]
I also don't know that this is worth the change. 
In general, `internal` can be useful for projects that _do_ expose an API in order to separate what should or should not be used, however in Gitea's case we do not promote our code as an API other than incidentally.

**Comment by techknowlogick** [comment]
Fwiw git is aware of directory moves and can accommodate it so that any conflicts rust do arise from this PR would be minimal.
This is also the approach that is recommended from go itself.

**Comment by wxiaoguang** [comment]
> this will prevent unnecessary requirements requests or blocks from those who want to depend on Gitea's packages as an import path.

What's the benefit? I do not see.

**Comment by JakobDev** [comment]
> Fwiw git is aware of directory moves and can accommodate it so that any conflicts rust do arise from this PR would be minimal.

It can still cause problems from my experience.

If you take a look at the changes, you will see git does not recognize every file as moved. Some are recognized as removed and added. This will cause a lot of problems.

**Comment by lunny** [comment]
Closed as too many conflicts.

**Pull request closed without merging**
