### PR TITLE
Fix RPM/Debian signature key creation

### LINKED ISSUE #28324: openpgp error on Debian package upload
### Description

```
openpgp: invalid argument: user id field contained invalid characters
```

I did not configure anything in the gitea config for packages. Maybe I am missing something ?
This error can maybe be handled upper in the code and provide a better hint

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

See: https://docs.gitea.com/next/usage/packages/packages/debian#publish-a-package
```
PUT /api/packages/wdes/debian/pool/bookworm/main/upload HTTP/2
```

the curl command outputs the server reply: `openpgp: invalid argument: user id field contained invalid characters`

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker rootless

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #28324

The name parameter can't contain some characters (https://github.com/keybase/go-crypto/blob/master/openpgp/keys.go#L680) but is optional. Therefore just use an empty string.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by jolheiser** [comment]
It seems like ideally this _would_ have something set, but is there a more predictable setting we could use? 
That is, this wants to set a UID like `jolheiser (a comment) <john.olheiser@gmail.com` and without a name would just be `(a comment) <john.olheiser@gmail.com`

I don't know much about RPM/Debian or where this signature is used/shown, so maybe it's of no consequence, but it seems like a full signature would be ideal if possible.

**Comment by KN4CK3R** [comment]
I thought about using the owner name here but I don't think you "see" this key somewhere. It's only used to check the repository files for consistency. Email was already empty, therefore I removed the name too.

**Comment by jolheiser** [comment]
> It's only used to check the repository files for consistency.

Changing this doesn't cause breakage, then?

**Comment by KN4CK3R** [comment]
Only new generated keys are affected. Once generated the key is stored as a user setting.

**Comment by jolheiser** [comment]
> Once generated the key is stored as a user setting.

Ah, right, packages are user/org level. In that case maybe the owner name would be good for this like you said. 

I think this is tentatively lgtm, but I would like if someone more familiar with debian packages could confirm whether it's the right strategy here.

**Comment by KN4CK3R** [comment]
In my mind exists a page where you can provide your own key-pair instead of generating one. Then you could reuse an existing key. If you don't need that, a generated key is fine.

The docs don't specify what info a key should contain:
https://wiki.debian.org/DebianRepository/UseThirdParty
There is just
> Repositories MUST be signed with an OpenPGP certificate.

**Review by lunny — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by williamdes** [comment]
It would be nice to have an ENV to change the value of the key.
Debian uses names like `Debian Archive Automatic Signing Key (10/buster)`

**Pull request merged**
