### PR TITLE
Fix variable name collision with import name

### PR DESCRIPTION
**Pull request by thibaultmeyer**
Fix variable name who collides with imported package name

### CODE REVIEW

**Comment by strk** [comment]
Please move to https://github.com/go-gitea/git

**Comment by 0xbaadf00d** [comment]
done.

**Comment by thibaultmeyer** [comment]
done. but since submodule is not in use, we have to port manually fix on gitea repo too

**Comment by tboerger** [comment]
Once you figured out how to use govendor to properly update the dependency you can create a new pr.

**Pull request closed without merging**
