### PR TITLE
Fix Ruby spec parsing

### LINKED ISSUE #19837: Error when uploading RubyGems packages
### Description

When trying to upload a RubyGem package to Gitea (main version 1.17.0+dev-629-ge0273bad7), I get a `cannot unmarshal !!seq into string` error. 

```bash
gem push --host http://localhost:3000/api/packages/dean/rubygems mygem.gem

Pushing gem to http://localhost:3000/api/packages/dean/rubygems...
yaml: unmarshal errors:
  line 57: cannot unmarshal !!seq into string
```

Looking at the server logs, it shows this:

```
2022/05/29 11:58:23 ...rubygems/rubygems.go:24:apiError() [E] [629351cf] yaml: unmarshal errors:
	  line 57: cannot unmarshal !!seq into string
2022/05/29 11:58:23 [629351cf] router: completed POST /api/packages/dean/rubygems/api/v1/gems for 127.0.0.1:39502, 500 Internal Server Error in 13.3ms @ rubygems/rubygems.go:193(rubygems.UploadPackageFile)
```

When trying to reproduce the error on try.gitea.io, it doesn't show an error but when checking my account, no Gem has been uploaded so I'm not sure if packages are fully enabled on that system?

### Gitea Version

1.17.0+dev-629-ge0273bad7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.34.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Just running the binary in the command line 

### Database

SQLite

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #19837

Problem is the `email` field which can be [a string or an array of strings](https://guides.rubygems.org/specification-reference/#email). The yaml parser does not support (?) the parsing of a single string into an array so I just removed the field as it is not used.

### CODE REVIEW

**Comment by silverwind** [comment]
> The yaml parser does not support (?) the parsing of a single string into an array

This is not the job of a YAML parser, but our own code, generally speaking.

**Comment by lafriks** [comment]
You could create new type StringArray []string with UnmarshalYAML function that would support both single email as string or array of strings

**Comment by KN4CK3R** [comment]
Sure, but this field is not needed. There is no benefit of having it at the moment.

**Comment by 6543** [comment]
As it's easy to fix I would go for new type ... - should I push to your branch @KN4CK3R ?

**Comment by KN4CK3R** [comment]
Sure, but this field is not needed. :-)

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
well this is backportable ...

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
.

**Comment by 6543** [comment]
->  #20525

**Pull request merged**
