### PR TITLE
fix(web): reduce page jitter on browsers that support overlay scrollbar

### PR DESCRIPTION
**Pull request by kecrily**
Reduce jitter caused by the presence or absence of scrollbars in page switching

---

Ref [scrollbar-gutter | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter)

https://user-images.githubusercontent.com/45708948/165972251-7d5a5017-f76d-4ba2-9106-a224b3ee521f.mp4

### CODE REVIEW

**Comment by silverwind** [comment]
`scrollbar-gutter: stable` will cause a ugly empty space besides our header, I'm not sure it's worth it.

Also, why remove the custom scrollbar colors? I realize it's a bit of an opinionated change of ours, but the change itself is unrelated to the PR description.

**Comment by kecrily** [comment]
The custom scrollbar should never have been removed.

—

I use 

```
overflow-y: overlay;
overflow-y: scroll;
```

to make the page seem blank in the fewest number of browsers.


Consider the fact that [`overflow-y: overlay` is only accessible with Chromium], whereas Safari (Apple's operating system) by default employs overleaf scrollbars. On actuality, whitespace will only be seen in Firefox.

**Comment by silverwind** [comment]
It depends on OS too. Firefox on Mac uses overlay scrollbars as well. So the issue is on Windows/Linux for non-Chrome-like users I guess. I'm still undecided.

**Comment by silverwind** [comment]
These CSS specs are a mess, there is `overflow: overlay` but it had been deprecated with a pointer to `scrollbar-gutter`, which in itself offes no option for overlay style, saying it should be controlled by the OS, but as far as I know, on macOS exposes this.

Does anyone know if recent versions of Windows/Linux also have a knob for overlay scrollbars?

**Comment by silverwind** [comment]
How about limiting it to Chrome?

```css
@supports (overflow: overlay) {
  body {
    overflow: overlay;
    scrollbar-gutter: stable;
  }
}
```

Try https://jsfiddle.net/silverwind/o36neL72/, I can't really it this on macOS, but I wonder if it helps on other OSs.

**Review by silverwind — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Pull request merged**
