### PR TITLE
feat: upgrade drone docker image to support multi-stage build.

### PR DESCRIPTION
**Pull request by appleboy**
Since the PR drone-plugins/drone-docker#124 has been merged. We need to upgrade `plugins/docker` image before merge https://github.com/go-gitea/gitea/pull/1615

I don't have permission to update drone sig file.

cc @tboerger @lunny @sapk

### CODE REVIEW

**Comment by tboerger** [comment]
AFAIK `pull` is not used for plugins.

**Comment by appleboy** [comment]
@tboerger It is working on my drone server (0.6) with `pull` flag.

see http://drone.wu-boy.com/appleboy/gorush/46

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by sapk** [comment]
@tboerger what do you suggest  ? We could use tag (like image: plugins/docker:17.05) ? 
I am not an expert in drone ^^ but I confirm that upgrating to 17.05 permit the usage of multi-stage Dockerfile. 

So LGTM,  except for the part of upgrating the image in drone that I don't handle.

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
This has worked for go-gitea/website#45 and go-gitea/docs#121. This will not have any effect on production (just force image update). Let's merge this ^^

**Comment by appleboy** [comment]
@sapk Rebase the latest `master` branch. Waiting for drone build.

**Comment by lunny** [comment]
LGTM

**Pull request merged**
