### PR TITLE
Reduce memory usage in testgit

### PR DESCRIPTION
**Pull request by zeripath**
There are several places where we are quite inefficient in test_git resulting in storing potentially large diffs and other things. 

This PR stops this.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Did this change make the test flaky? I see a lot of `EnsureDiffNoChange` failures lately, like https://drone.gitea.io/go-gitea/gitea/38213/2/14:

image
image
image

**Comment by zeripath** [comment]
nope they've been there for a while.

**Comment by zeripath** [comment]
the problem appears to be in the results of the first diff which I think are incorrect somehow but yet do not return an error in the first place.

**Comment by zeripath** [comment]
the main thing is that we can now see it.

**Pull request merged**
