### PR TITLE
Delete Microsoft YaHei (#4173)

### PR DESCRIPTION
**Pull request by xps2**
#4173

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
For a temporary fix, this is OK. We should define different fonts for different languages for a perfect UI.  `Microsoft YaHei` is beautiful than `Arial` on `Chinese` language. I think the similar situations are also in other languages.

**Comment by zeripath** [comment]
The Han unification problem strikes again!

**Comment by zeripath** [comment]
I don't know enough about the yahei font. It doesn't have the kanji and traditional variants?

Are we definitely setting the appropriate lang attribute on the html element as per:

https://www.growingwiththeweb.com/2014/03/languages-and-chinese-characters-on-the-web.html

Can we leverage lang specific font-family in CSS?

**Comment by sapk** [comment]
It seems (from the live [demo](https://codepen.io/Tyriar/pen/mqLkH)) that settings the lang attribute well should fix the problem.

**Comment by lunny** [comment]
We should add missing lang attribute on `<html lang='en/cn'>` according UI languages at least.

**Comment by sapk** [comment]
Following @lunny comment we could also use the attr [lang=lang_id] to select a font to use based on lang.

**Comment by xps2** [comment]
Microsoft Yahei is a Chinese font, but it is also installed by default in the Windows Japanese environment.
However, since Japanese Kanji and Chinese Hanja have different glyphs, Japanese speakers feel uncomfortable. (See also #4173)
Therefore, I submitted this PR.
For non-Windows, there is no problem so I want you to delete or switch by language.

**Comment by xps2** [comment]
Microsoft Yahei is a Chinese font, but it is also installed by default in the Windows Japanese environment.
However, since Japanese Kanji and Chinese characters have different shape, Japanese speakers feel uncomfortable. (See also #4173)
For Chinese speakers, Meiryo UI will feel uncomfortable as Japanese speakers feel uncomfortable with Microsoft Yahei. (cf. fd3b9ca)
Therefore, I submitted this PR.
In case of non-Windows environment there is no problem, please do not force Microsoft Yahei.

**Comment by zeripath** [comment]
Yes xps2 I understand that displaying the wrong glyph will make people feel uncomfortable - however, I think simply removing the font isn't going to be the answer to this.  If we aren't setting the correct lang attribute it's likely that forms of the UniHanned glyphs will be unpredictable - so therefore we need to set this. 

Now, the question comes as to whether YaHei has the other forms - it appears not from what you're saying therefore we will need to use lang specific css as our Chinese colleagues think that YaHei provides nice font-forms in Simplified Chinese. 

So how can we do that? Well there's the lang pseudo-selector on CSS which appears to have relatively good support: https://developer.mozilla.org/en-US/docs/Web/CSS/:lang so perhaps we need to add that to the CSS. Is "Meiryo Ui" a nice Japanese font? - We could add that back in wrapped into 

```css
:lang(ja)  {
  body {
     font-family:  "Helvetica Neue", "Meiryo Ui", Arial, Helvetica, sans-serif !important;
  }
}
```

Presumably, YaHei also doesn't have traditional Chinese or Korean forms? If so we should probably move it out of the default body and stick it in a `:lang(zh-hans)` and so on.

**Comment by xps2** [comment]
I agree to put Microsoft Yahei as the default value for Chinese.
However, since each of CJK's glyph may be different, I do not agree to put Microsoft Yahei in default values for all languages.
e.g. https://ja.wikipedia.org/wiki/CJK統合漢字#/media/File:CJKV_variant_glyphs.png

CJK unified ideographs is very difficult…

**Comment by sapk** [comment]
@xps2 Yes that what @zeripath suggest also at the end.

> Presumably, YaHei also doesn't have traditional Chinese or Korean forms? If so we should probably move it out of the default body and stick it in a `:lang(zh-hans)` and so on.

It will not drop down Chinese user experience and keep the default font for others (or add more in an other PR).

**Comment by silverwind** [comment]
Has thought been given about using a native font stack? I generally prefer them because there is no flash of invisible text on uncached page loads. I've been using [Bootstrap's font stack](https://github.com/twbs/bootstrap/blob/39b76861a7afc2ccc90752a61fa5aa998e94761f/dist/css/bootstrap.css#L34-L35) with good results for english texts, not sure if it's suitable for japanese.

Also, Github's current font stacks:

````
-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol
````
````
SFMono-Regular,Consolas,Liberation Mono,Menlo,Courier,monospace
````

**Comment by lunny** [comment]
@silverwind there is a new PR #6007 sent by @zeripath  will try to give different font stack according UI languages.

**Comment by techknowlogick** [comment]
Thanks for PR @xps2. I am going to close this in favour of #6007

**Comment by xps2** [comment]
@techknowlogick  OK👍

**Pull request closed without merging**
