### PR TITLE
ui: Add MergePull comment type instead of close for merge PR

### PR DESCRIPTION
**Pull request by a1012112796**
As title.

view:
jtng

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
Have you checked `actionToTemplate()` in `services/mailer/mail.go`? At first glance it shouldn't need any changes; asking just in case.

**Comment by a1012112796** [comment]
> Have you checked `actionToTemplate()` in `services/mailer/mail.go`? At first glance it shouldn't need any changes; asking just in case.

Hello, I think this change only about comment, it haven't do any change on notify and actions.
so it will't be influenced.

**Comment by guillep2k** [comment]
> 
> Hello, I think this change only about comment, it haven't do any change on notify and actions.
> so it will't be influenced.

Every time you create a comment, a notification is derived from that comment; and comment types (you've just added one) are important for the mail template system.

I don't expect a problem in this case, but it doesn't hurt to check.

**Comment by 6543** [comment]
## why add a MergedComment if we already indicate it with this:
Screenshot at 2020-04-13 21-30-08

## ?

**Comment by 6543** [comment]
OK ... to track when it was merged if the conversation in a pull goes on

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
ping lgtm

**Comment by 6543** [comment]
lgtm bot ?

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
