### PR TITLE
Refactor names

### PR DESCRIPTION
**Pull request by wxiaoguang**
Follow https://github.com/go-gitea/gitea/pull/31381#pullrequestreview-2123549783

This PR only does "renaming":

* `Route` should be `Router` (and chi router is also called "router")
* `Params` should be `PathParam` (to distingush it from URL query param, and to match `FormString`)
* Use lower case for private functions to avoid exposing or abusing

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Likely needs a breaking label as it affects custom go templates. BTW I wouldn't call out such changes too prominently in the changelog as only a very small number of users even use custom go templates.

No, it isn't breaking. No template is changed.

**Review by silverwind — APPROVED** [review]
Sadly, this is likely going to break a number of open PRs.

**Comment by wxiaoguang** [comment]
I could help to resolve conflicts, just ping me if needed.

**Comment by delvh** [comment]
> Likely needs a breaking label as it affects custom go templates. BTW I wouldn't call out such changes too prominently in the changelog as only a very small number of users even use custom go templates.

Technically, we don't consider breaking templates to be breaking as otherwise any PR modifying any template would be breaking

**Comment by silverwind** [comment]
> > Likely needs a breaking label as it affects custom go templates. BTW I wouldn't call out such changes too prominently in the changelog as only a very small number of users even use custom go templates.
> 
> Technically, we don't consider breaking templates to be breaking as otherwise any PR modifying any template would be breaking

I meant renaming template helper functions and these were considered breaking in the past. But I misread the PR, it does not change any of them.

**Pull request merged**
