### PR TITLE
Create missing database indexes

### PR DESCRIPTION
**Pull request by andreynering**
Part 1 of #180

### CODE REVIEW

**Comment by strk** [comment]
Should migrations be written to add indexes where missing ? (I don't know how XORM works, maybe @lunny can answer this)

**Comment by andreynering** [comment]
@strk I am also confused by how migrations work on Gogs/Gitea, but I discovered that by simple adding/changing fields it syncs automatically on initialization.

**Comment by tboerger** [comment]
Do we really need only these single index definitions? Or do we also need combined index definitions?

**Comment by lunny** [comment]
@andreynering database migration by two methods, one is `xorm.Sync2()`. It will automatically add new fields, and modify indexes. Another is migrations, it lets us manually write some functions to do migrations.

**Comment by andreynering** [comment]
Thank you for explaining @lunny I have to learn more of Xorm.

@tboerger I think I didn't add an index where an composite index existed before. If I did I'll update.

Some indexes may be not needed today, but I think foreign keys and timestamps should always have. Any column we may need to use in WHERE or ORDER BY in future its useful to have an index.

**Comment by tboerger** [comment]
IMHO we need to analyze the queries to see where composite indices make sense.

**Comment by lunny** [comment]
LGTM

**Comment by tboerger** [comment]
Any update? Have you checked if we need some composite index?

**Comment by andreynering** [comment]
@tboerger Not yet, will do.

But when in doubt single column indexes are better, because databases can merge multiple indexes when necessary, but can't use a composite index when not all columns are given on WHERE.

**Comment by andreynering** [comment]
@tboerger I would not change any index to a composite index.

**Comment by strk** [comment]
This needs a rebase (was about to test it but got blocked there)

**Comment by andreynering** [comment]
Deprecated by https://github.com/go-gitea/gitea/pull/596

**Comment by KangoV** [comment]
How will this affect gogs->gitea migration? I take it the indexes will not get created if the db already exists?

**Comment by lunny** [comment]
No. It will automatically migration from Gogs -> Gitea. This is a feature of XORM when call `x.Sync2()`.

**Comment by KangoV** [comment]
@lunny That's cool. I am currently a Java dev with a lot of Experience with Hibernate/Cassandra/PostgrSQL etc. I do not know much about XORM yet.

**Comment by lunny** [comment]
You can find the document here http://gobook.io/read/github.com/go-xorm/manual-en-US/

**Pull request closed without merging**
