### PR TITLE
Remove unnecessary forgot password link in delete user section

### PR DESCRIPTION
**Pull request by yp05327**
Before:
image

After:
image

### CODE REVIEW

**Comment by n0toose** [comment]
I previously assumed that the context of that button being there is people creating new accounts, staying logged in and then deleting them because they cannot remember their previous password (which is needed in order to change their password).

**Comment by lunny** [comment]
It's near the password input box. So maybe users forget the password, they can click the link. Why do you think it's unnecessary?

**Review by delvh — APPROVED** [review]

**Comment by yp05327** [comment]
image

There's already a `forget password` above.

**Comment by lunny** [comment]
> image
> 
> 
> 
> There's already a `forget password` above.

Yes, because there are two password input boxes.

**Comment by lunny** [comment]
> It's very unusual to have that link in your profile. If you don't know your password, you should not be logged in or you would change it in the settings.

If that, we should remove both of the links.

**Comment by yp05327** [comment]
> If you don't know your password, you should not be logged in.

If you use third party to login, for example, I usually use GitHub account to login into gitea.com, 
you can be logged in without password.

**Comment by delvh** [comment]
So, overall, let's just remove the duplicate one as currently suggested.
We can still argue later on about whether to remove the second one too.

**Review by lunny — APPROVED** [review]

**Pull request merged**
