### PR TITLE
Use minio/sha256-simd for accelerated SHA256

### PR DESCRIPTION
**Pull request by zeripath**
minio/sha256-simd provides additional acceleration for SHA256 using AVX512, SHA Extensions for x86 and ARM64 for ARM.

It provides a drop-in replacement for crypto/sha256 and if the extensions are not available it falls back to standard crypto/sha256.

### CODE REVIEW

**Comment by zeripath** [comment]
Clearly this is not a complete drop-in replacement... It appears to be missing the implementation for BinaryEncoder... 

OK...

**Comment by zeripath** [comment]
I think once https://github.com/minio/sha256-simd/pull/68 is merged there's potential for further improvement here.

**Comment by zeripath** [comment]
Given the CI failure in c304241 that means that the CI runners should have support for these extensions. 

That means that this is likely to cause a measurable improvement in speed of CI.

**Review by delvh — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
I wonder why they did not just upstream the improvements into `crypto`. I'm generally wary of such "speed improvements" as the code quality often does not match the standards of the stdlib.

**Comment by zeripath** [comment]
They're trying to upstream the changes but go is being a little slow to pull them.

Agreed in general about speed improvements not necessarily being worth it, but this is being used by minio and is written by minio and has a good test suite.

**Pull request merged**
