### PR TITLE
fix panic on gogs webhook creation

### PR DESCRIPTION
**Pull request by daviian**
As title.

Targets #2671
Needs backport to 1.2

### CODE REVIEW

**Comment by lafriks** [comment]
@daviian I think it should also be fixed on line 423 `func GogsHooksEditPost`

**Comment by daviian** [comment]
@lafriks Done

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
@daviian please send a backport PR to v1.2

**Pull request merged**
