### PR TITLE
replace Gogs to Gitea on locale files

### PR DESCRIPTION
**Pull request by avelino**

### CODE REVIEW

**Comment by strk** [comment]
LGTM, although we didn't yet define a policy for updating those files...

**Comment by lunny** [comment]
If we accept #114, so we can merge this? Or we have to use a tanslation tool to do that?

**Comment by strk** [comment]
#114 seems to be more than a policy, it's actually a proposal for a new development.
A policy could be something as simple as: "translation updates are accepted as pull-requests"

**Comment by lunny** [comment]
Yes. So let's LGTM first!

**Pull request merged**
