### PR TITLE
Allow only single fork per user/organization

### PR DESCRIPTION
**Pull request by Bwko**
Revert #761 solves #2019 & #2189

### CODE REVIEW

**Comment by lafriks** [comment]
Do not revert translation files except for en-US as otherwise it will be harder to sync translation changes from crowdin

**Comment by Bwko** [comment]
Done

**Comment by lafriks** [comment]
LGTM

**Comment by cez81** [comment]
LGTM

**Comment by lunny** [comment]
please fore empty push

**Pull request merged**
