### PR TITLE
fix the component of access token list not mounted

### LINKED ISSUE #31771: scoped-access-token-mount not mounted anymore
### Description

Generating application tokens is currently broken on main because scoped-access-token-mount doesn't get properly mounted anymore. So i'm unable to select permissions

### Gitea Version

1.23.0+dev-377-g13439f119e built with GNU Make 4.4.1, go1.22.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

Docker on Ubuntu server

### How are you running Gitea?

Docker compose

```yaml
gitea:
    image: gitea/gitea:nightly

``` 

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by sillyguodong**
try to fix #31771

### CODE REVIEW

**Comment by sillyguodong** [comment]
https://github.com/go-gitea/gitea/issues/31771#issuecomment-2283567174
@wxiaoguang @silverwind what are your thoughts on this?

**Comment by wxiaoguang** [comment]
Not right

**Comment by sillyguodong** [comment]
@wxiaoguang 
[ba52d01](https://github.com/go-gitea/gitea/pull/31824/commits/ba52d01b3458d8b5c5aa4d3f14928fed9ec5eb09)  no longer import the `createApp` in the SFC. I believe the Vue component will be compiled during the build stage. Is this right now?

**Comment by wxiaoguang** [comment]
Overall right.

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Comment by proxity** [comment]
It's a pity that the feature is broken in 1.22.1. Will you merge the fix?

**Comment by lunny** [comment]
> It's a pity that the feature is broken in 1.22.1. Will you merge the fix?

Yes, this will be backport to 1.22.2

**Comment by sillyguodong** [comment]
> I was unable to create a backport for 1.22. @sillyguodong, please send one manually. 🍵
> 
> ```
> go run ./contrib/backport 31824
> ...  // fix git conflicts if any
> go run ./contrib/backport --continue
> ```

i will take a look

**Pull request merged**
