### PR TITLE
Css adjust

### PR DESCRIPTION
**Pull request by L0veSunshine**
Fix 1 css config bug and adjust 1 css config to make the Icon look better。
unchanged:
批注 2020-03-04 132258
after change:
批注 2020-03-04 132231

Screenshoted from [https://try.gitea.io/clandmeter/aports](https://try.gitea.io/clandmeter/aports)

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Which part of the screenshot is this change refering to?

**Comment by L0veSunshine** [comment]
> Which part of the screenshot is this change refering to?

Programming language statistics bar.

**Comment by silverwind** [comment]
Wrapping change is fine, not sure I like the border removal thought. I think it does add some distinction to the background, especially on arc-green.

image

image

**Comment by silverwind** [comment]
Maybe we can do a quick vote:

👍 border
👎 no border

**Comment by L0veSunshine** [comment]
> Wrapping change is fine, not sure I like the border removal thought. I think it does add some distinction to the background, especially on arc-green.
> 
> image
> 
> image

I refer the Github style. Edges are a bit blurry at high contrast.
批注 2020-03-05 023235
and my platform is windows10 chrome

**Comment by silverwind** [comment]
I think the blurriness in that screenshot is mostly because of low DPI, not the border itself.

**Comment by L0veSunshine** [comment]
> I think the blurriness in that screenshot is mostly because of low DPI, not the border itself.

My screen's resolution is 2560*1440 and the window DPI is 100%. no zoom in nor zoom out. I also feel confused about this.

**Comment by L0veSunshine** [comment]
> I think the blurriness in that screenshot is mostly because of low DPI, not the border itself.

It is up to you. have a nice day, bye.

**Pull request closed without merging**
