### PR TITLE
ci: run notify on arm64

### PR DESCRIPTION
**Pull request by sapk**
- Free one jobs on amd64 (to win some time to start testing on amd64 of an other jobs)
- Update discord plugin to latest version. 
   - Support more paltform (including arm64)
   - Support upload of file if needed
   - Update deps and base docker image 

Changelog: https://github.com/appleboy/drone-discord/compare/1.0.0...v1.2.4

### CODE REVIEW

**Comment by sapk** [comment]
I don't exactly know why this doesn't work and complain about:
```
2020/01/14 16:10:27 missing discord config
```

**Comment by sapk** [comment]
Since it change of host maybe it need to be allowed by owners ?

**Comment by sapk** [comment]
Ok so this was already not working before: https://drone.gitea.io/go-gitea/gitea/19367/5/1 (thanks @techknowlogick for the insight).  
So I enabled it only on master and tags.  
I also taken some config from plugin .drone.yml https://github.com/appleboy/drone-discord/blob/master/.drone.yml#L339

**Review by 6543 — APPROVED** [review]

**Comment by sapk** [comment]
I will have to adjust the conditions here since I think I am missing releases branches.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
