### PR TITLE
fix button heights on commits page

### PR DESCRIPTION
**Pull request by silverwind**
Fixes a issue I introduced by changing the branch button. Basically, Semantic uses the selector `.ui.menu:not(.vertical) .item > .button` which does not work if `.button` is no direct child of `.item` which is the case for the branch button in our case, because it's wrapped in a dropdown.

Additionally, I fixed a indendation issue I introduced earlier while merging.

#### Before
screen shot 2017-12-04 at 18 52 22

#### After
screen shot 2017-12-04 at 19 06 06

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
@silverwind if this change will effect other menus?

**Comment by silverwind** [comment]
It will, but there should be no negative effect. You can see the override as sort of a bug fix for a bug in Semantic.

**Comment by silverwind** [comment]
I also created https://github.com/Semantic-Org/Semantic-UI/pull/5996 to fix this in Semantic itself. Thought, based on the recent activity in that repo, I don't see that one getting merged anytime soon.

**Comment by lunny** [comment]
LGTM

**Pull request merged**
