### PR TITLE
More arc-green fixes (#13247)

### PR DESCRIPTION
**Pull request by silverwind**
Backport of https://github.com/go-gitea/gitea/pull/13247, was a clean cherry-pick.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
~~blocking until #13263 got resolved~~

**Review by techknowlogick — DISMISSED** [review]
blocking via review so I don't accidentally merge

**Comment by silverwind** [comment]
Linked issue is not really related here, should be good to go.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@silverwind sorry mixed up css fixes somehow @techknowlogick :point_up:

**Pull request merged**
