### PR TITLE
Update alpine to 3.7

### PR DESCRIPTION
**Pull request by sapk**
Alpine 3.7 has been release :smile:

### CODE REVIEW

**Comment by ethantkoenig** [comment]
LGTM (CI failure seems unrelated)

**Review by 0rzech — COMMENTED** [review]
[Golang](https://hub.docker.com/_/golang/) based on Alpine 3.7 is still in beta. Maybe it would be better to wait for its release, so the same version of Alpine is used for compilation and deployment?

**Comment by sapk** [comment]
That go1.10 that is in beta but alpine 3.7 does have go1.9 as golang version and we don't even have go inside the final docker container.

**Comment by 0rzech** [comment]
Sorry, the golang image itself is rc, not beta.

Official Golang Docker images do not use Go from Alpine repositories (though there is Go 1.9 in Alpine 3.7 community repo) and yes, we do not have Go installed in deployment image, but we do use specific Go version and link to system libraries when building Gitea in build image.

Btw. This is one of the reasons for Docker's existence: to minimize differences between development and production environments. Also, Alpine 3.7 is absolutely brand new, so maybe it would be better to let it settle a bit?

Maybe it's nothing, but IMHO there's no reason to pursue novelty yet. Especially when there's #2927 just around the corner.

Just my $0.02. I'm not blocking anything. ;)

**Comment by sapk** [comment]
@0rzech I understand and I will update #2927 accordingly. ;-) 

edit: or the opposite if #2927 is merge before XD

**Comment by techknowlogick** [comment]
LGTM

**Comment by sapk** [comment]
Rebase and now tests are passing. \o/
Ready to be merge.

**Pull request merged**
