### PR TITLE
Fixed wrong api request url for instances running in subfolders

### LINKED ISSUE #5156: api request url for dependencies in issues is wrong
- Gitea version (or commit ref): 1.6.0-rc1
- Git version: 2.17.1
- Operating system: Ubuntu Server 18.04 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm hosting gitea in a subfolder called `/gitea/` via Apache (Reverse)Proxy.

Therefore my api base url is `/gitea/api/v1`. Now on searching issues with the provided input it queries `/api/v1/repos/gitea/<user>/<repo>/issues?q=...` - which of course 404s.

It should be `/gitea/api/v1/repos/<user>/<repo>/issues?q=...` instead.

### PR DESCRIPTION
**Pull request by kolaente**
Fixes #5156

### CODE REVIEW

**Comment by kolaente** [comment]
Should I directly send a backport to 1.6?

**Comment by techknowlogick** [comment]
@kolaente once this has been merged please do the backport. Thanks 😄

**Comment by kolaente** [comment]
@techknowlogick only to 1.6 or also 1.5? (Since 1.5 isn't released yet)

**Comment by techknowlogick** [comment]
@kolaente just 1.6 please 😄

**Review by techknowlogick — APPROVED** [review]

**Comment by kolaente** [comment]
Backport is up:  #5261

Awh shoot, I forgot to wait until this one is merged...

**Review by lafriks — APPROVED** [review]

**Pull request merged**
