### PR TITLE
Fix loading spinner on ContextPopup

### PR DESCRIPTION
**Pull request by silverwind**
Fix regression from https://github.com/go-gitea/gitea/pull/26670. Here with simulated delay:

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by kdumontnu — APPROVED** [review]
:100:

**Comment by silverwind** [comment]
Not easily backportable because of tailwind use and I think it's not critical enough either for me to bother, but if someone wants, they can backport.

**Comment by kdumontnu** [comment]
> Not easily backportable because of tailwind use and I think it's not critical enough either for me to bother, but if someone wants, they can backport with some CSS in place of tailwind.

`tw-*` should be supported in v1.21. I just tested this change on 1.21 and it fixed the issue.

Perhaps I'm missing something.

**Comment by silverwind** [comment]
It couldn't work because https://github.com/go-gitea/gitea/pull/29357 is only on 1.22 branch.

**Pull request merged**
