### PR TITLE
Add main landmark to templates and adjust titles

### PR DESCRIPTION
**Pull request by fsologureng**
* Add main aria landmark to templates
 * Adjust some titles to improve understanding of location in navigation

Contributed by @Forgejo

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I do wonder if this could have been automated in some way.

**Comment by fsologureng** [comment]
> I do wonder if this could have been automated in some way.

Do you mean centralizing the generation of the label for the landmark or Title value somewhere?

**Review by lafriks — APPROVED** [review]

**Review by delvh — APPROVED** [review]
Hmm, let's hope we inserted the `Title` as argument for the templates everywhere…
We'll notice it when someone complains about a panic in the templates.

**Comment by fsologureng** [comment]
Resolved conflict reverting change in templates/repo/settings/navbar.tmpl because is already resolved in the other pr.

**Pull request merged**
