### PR TITLE
use x.SQL instead of x.Sql

### PR DESCRIPTION
**Pull request by lunny**
Since xorm have provide SQL and will deprecate Sql, so we can use SQL instead of Sql.

### CODE REVIEW

**Comment by lunny** [comment]
It seems drone is not work.

**Comment by thibaultmeyer** [comment]
LGTM

**Comment by DblK** [comment]
LGTM

**Comment by bkcsoft** [comment]
@lunny In my opinion we shouldn't use `x.SQL` unless absolutely necessary. If you're fixing all of them, why not change them to `x.Select`/`x.Update` etc?

**Comment by lunny** [comment]
SQL method allow you custom your SQL statement when ORM can not satisfy your requirements . Select and Update have beend used on other place.

**Pull request merged**
