### PR TITLE
Preserve color when inverting emojis

### LINKED ISSUE #17795: Emoji heavy_check_mark: shown as pink instead of green
### Gitea Version

1.15.6

### Operating System

Debian 10

### Browser Version

Chrome 96.0.4664.45

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

I have seen that if I add `:heavy_check_mark:` to comments or something like that, it gets displayed in a different way based on the theme got selected, which leads to a miss understanding of it.

As you can see in the attached screenshots, it is green if the gitea theme is selected, but if you select the arc-green theme, it gets pink which leeds to a miss understanding of if

tested there as well: https://try.gitea.io/suchAdemon/test_sad

### Screenshots

image
image

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/17795

Windows:

image

Mac:

image

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
Magic!

**Review by Gusted — APPROVED** [review]

**Comment by Gusted** [comment]
Hmm Github somehow approved this while my browser crashes - Anyhow, I wanted to add a comment to my approval

"We should lookout for using invert+hue-rotate as they can create weird sub-pixel artifacts, but that's another issue for another day."

**Comment by silverwind** [comment]
> We should lookout for using invert+hue-rotate as they can create weird sub-pixel artifacts, but that's another issue for another day.

I never noticed anything like that on Mac or Windows at least. Maybe it's a Linux-only issue.

**Comment by Gusted** [comment]
> I never noticed anything like that on Mac or Windows at least. Maybe it's a Linux-only issue.

I've seen it happening on Windows as well - it's more how browsers are rendering certain things. It's most noticeable on text-like elements which get inverted. It shouldn't be a big problem in this case, but it's not something that should be used everywhere.

**Comment by silverwind** [comment]
Yeah I recall there having such issues with `filter` on non-text content, but I guess those are ultimately browser rendering bugs. Doing it on text-only seems fine in any case.

**Pull request merged**
