### PR TITLE
RFC: Add max concurrent hashes setting

### PR DESCRIPTION
**Pull request by zeripath**
Some hash algorithms can be very costly to generate. This PR adds a setting to limit the maximum concurrent hashes performed at any one time.

### CODE REVIEW

**Comment by zeripath** [comment]
Related #14702

**Comment by zeripath** [comment]
conflicts resolved

**Comment by 6543** [comment]
do you have time to resolve the conflicts?

**Comment by zeripath** [comment]
conflicts resolved

**Pull request closed without merging**
