### PR TITLE
CSS navbar and color tweaks

### PR DESCRIPTION
**Pull request by silverwind**
- Many fixes to `.new-menu`
- Fix admin bar overlapping menu bar
- Fixes file edit comment box
- Fix double border on review box
- Fix review timeline icons

Screen Shot 2020-11-17 at 20 53 34
Screen Shot 2020-11-17 at 21 02 32
Screen Shot 2020-11-26 at 00 08 12
Screen Shot 2020-11-26 at 00 08 05
Screen Shot 2020-11-26 at 00 04 55
Screen Shot 2020-11-26 at 00 04 48
Screen Shot 2020-11-25 at 23 55 26
Screen Shot 2020-11-26 at 00 04 28

### CODE REVIEW

**Comment by silverwind** [comment]
Working on some more fixes regarding the `new-menu` navbar.

**Comment by silverwind** [comment]
Many fixes done to `.new-menu` (the top menu seen on admin or user settings). It should now look correct in both themes, never overflow and also looks ok on mobile layout. OP screenshots updated.

**Comment by silverwind** [comment]
This is ready for review.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
So I think there's an issue with the commit graph page but I don't think this has been caused by this PR.

Screenshot from 2020-11-26 19-01-17

**Review by mrsdizzie — APPROVED** [review]

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> So I think there's an issue with the commit graph page but I don't think this has been caused by this PR.
> 
> Screenshot from 2020-11-26 19-01-17

this is indeed older, been meaning to report if for a while.

great changes btw @silverwind

**Comment by silverwind** [comment]
@zeripath can you link such an issue on try.gitea.io?

**Pull request merged**
