### PR TITLE
Cache last commit to accelerate the repository directory page visit

### LINKED ISSUE #491: Slow page loads with a large repo
Possibly linked/related to #490 

I like to keep some mirrors of popular projects such as Rails on my Gitea server however whenever I go to view that repo, it can take 10 seconds plus (sometimes causing an nginx 502 timeout error) to load the page

### PR DESCRIPTION
**Pull request by lunny**
Will replace #6045, resolve #491

On my local test (macOS ) with default cache setting(memory):

aports (home directory): 4010ms -> 225ms
vdsm (home directory): 1510ms -> 112ms

BTW: aports /main has many files, so I haven't tested it. We need a limitation on files listed. That will be another PR.

### CODE REVIEW

**Comment by 6543** [comment]
@lunny instead of a hard lim, could we paginate it somehow?

**Comment by 6543** [comment]
can you add some tests?

**Comment by silverwind** [comment]
Why the separate options? Is the new cache expected to go big?

**Comment by 6543** [comment]
I like the added Enable option!
@silverwind for me: I'm totaly fine with more options ...
so you can tweek around as instance admin

**Comment by lafriks** [comment]
I don't think we need separate cache for last commit, just use cache we already have in place

**Comment by silverwind** [comment]
Yeah, if there is no compelling reason to make it a separate cache, I'd prefer it to be included in the regular cache.

**Comment by lunny** [comment]
> @lunny instead of a hard lim, could we paginate it somehow?

That will be another PR.

@lafriks @silverwind I have sent another commit that will use the original cache config defautly.

**Comment by lunny** [comment]
@6543 I will try to add a test but since it's a page performance optimization for big repository but the test repositories are small. The test will only confirm the results are the same before enable the cache or after.

**Comment by 6543** [comment]
> @6543 I will try to add a test but since it's a page performance optimization for big repository but the test repositories are small. The test will only confirm the results are the same before enable the cache or after.

i think it is enouth if you add test to test if cache works at all ... (set cache-size to low value .. ; open repo & test if it is in the cash) ?

**Review by 6543 — APPROVED** [review]

**Review by lafriks — CHANGES_REQUESTED** [review]
@lunny only following settings are needed for `[cache.last_commit]` section
- ~~`ENABLED`: **true**: Enable the cache.~~ - **edit**: setting `ITEM_TTL` to 0 will disable cache so no need for this option also
- `ITEM_TTL`: **16h**: Time to keep items in cache if not used, Setting it to 0 disables caching.
- `COMMITS_COUNT`: **1000**: Only enable the cache when repository's commits count great than.

You can reuse same cache and set specific TTL for `last_commit` keys.

**Comment by lafriks** [comment]
@lunny I created PR to your PR with what I meant: https://github.com/lunny/gitea/pull/4

**Comment by lunny** [comment]
@lafriks done.

**Comment by 6543** [comment]
## without
- aports/src/branch/master/main: 78375ms(first) - 76574ms(snd.)
- aports/src/branch/master/community: 38033ms(first) - 36449ms(snd.)
## with
- aports/src/branch/master/main: 77753ms(first) - 591ms(snd.)
- aports/src/branch/master/community: 37208ms(first) - 685ms(snd.)

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
Maybe pre-populate cache on startup and push?

**Comment by 6543** [comment]
I think the endresult is just more load on the system ... if we implement this i like to be able to disable this  @silverwind

**Comment by lunny** [comment]
@silverwind I will send another PR to do that.

**Review by adelowo — APPROVED** [review]

**Comment by lunny** [comment]
@lafriks need your approval.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
