### PR TITLE
add thumbnail preview section to issue attachments

### LINKED ISSUE #13786: Bring back attachment preview/thumbnails
In older versions of Gitea (1.11) there was  image thumbnail/preview for attachments. My team found it really useful and since it's been removed in later version (1.12) (by PR #6089 ?) we really miss it! Any chance of seeing it re-implemented?

---

### Gitea 1.11.8
Screenshot_2020-12-02 test(1)

---
### Gitea 1.12.6
Screenshot_2020-12-02 test

### PR DESCRIPTION
**Pull request by bobemoe**
Closes #13786

This PR restores the image attachment preview thumbnails that were removed in https://github.com/go-gitea/gitea/issues/6089 but keeps the awesome filename/size list that was added in that PR.

image

### CODE REVIEW

**Comment by bobemoe** [comment]
I was thinking of hiding the thumbnail if the image was already displayed inline in the content, but couldn't figure out the best way to detect that, so this is what I've got so far

**Comment by 6543** [comment]
> I was thinking of hiding the thumbnail if the image was already displayed inline in the content, but couldn't figure out the best way to detect that, so this is what I've got so far

we potetial could use search the issue/comment content for atatchemnt uuid before disply preview. this uuid strings should be uniqe enouth ...

**Comment by lunny** [comment]
Thumbnails may should have the same height and width.

**Comment by bobemoe** [comment]
@lunny agreed, I will look into this.

@6543 I am trying this now. Any idea how I can do a substring search in the template?

**Comment by bobemoe** [comment]
I written what I think needs doing in psudo code (see commit b700c11) but I cant work out how to actually implement it

**Comment by 6543** [comment]
works sofar only if you edit stuff the view is kind a broken - after reload it works as is should

**Comment by bobemoe** [comment]
Looks like some js is expecting the old layout... think I've found it, just testing now

**Comment by bobemoe** [comment]
I had moved some duplicate html (`<div class="dropzone-attachments">`...) from the issue and comment template into the attachments template because it looked more suited there. This meant that the JS that updates the page after edit needed fixing (also contained the dupe code) so I tided that a little too. I've searched for any more occurrences but cant see any.

Also hidden thumbnails were reappearing during js update so I had to modify the router to use the new template functionality

Think its looking good now :)

Still want to look at limiting image height/width ratio next..

**Comment by bobemoe** [comment]
So at the moment image thumbnail uses the fomantic-ui `.small` class to restrict the thumbnail width, but height is not restricted so an tall thin image renders thousands of pixels high!! Unfortunately it seems no `.square` or fit/scale/crop classes available.

I've ended up using `.dropzone-attachments .ui.image{ max-height:150px; }` which works well, but where best to add this css?

And is using a hardcoded 150px a good idea, its meant to match fomantic-ui `ui.image.small` width of 150px but if this changes on different viewports then I may need a different approach?

**Comment by bobemoe** [comment]
I think I worked out the best place to put the CSS, please check: https://github.com/go-gitea/gitea/pull/13826/commits/acc5ad9006df3f78ad4c97e1a928d616a547d858

Also I removed a CSS block that I think is no longer used, the `bottom` class it targets was removed in https://github.com/go-gitea/gitea/pull/11141/files#diff-9faae32445ed9673de2830c9fc35e93f44487f0a0068202988adaf00a5bac850L66, again please check https://github.com/go-gitea/gitea/pull/13826/commits/f4a61ddafd831b6742e5890026bd8a434016c744

@6543 will check the lint issue now...

**Comment by bobemoe** [comment]
When the last attachment is delete and the JS updates the comment, all attachments are removed but there is still a divider line shown. Its not shown after refresh or on view, probably not worth worrying about? I could `if` it out in the template if you think its worth it?

image

**Comment by lunny** [comment]
> When the last attachment is delete and the JS updates the comment, all attachments are removed but there is still a divider line shown. Its not shown after refresh or on view, probably not worth worrying about? I could `if` it out in the template if you think its worth it?
> 
> image

If there is no attachment, just remove the divider.

**Comment by bobemoe** [comment]
OK, I think I'm happy with this now :)

**Review by 6543 — APPROVED** [review]

**Comment by bobemoe** [comment]
Anything more I need to do for this?

**Comment by 6543** [comment]
> Anything more I need to do for this?

no just wait for a second review - and hit "Update branch" some times ...

**Review by lafriks — APPROVED** [review]

**Pull request merged**
