### PR TITLE
Update comparison.en-us.md with RhodeCode Community edition

### PR DESCRIPTION
**Pull request by marcinkuzminski**
Added RhodeCode Community edition into comparison page

Comparison page lists some competitors, and i think it's worth mention RhodeCode too

### CODE REVIEW

**Review by sapk — APPROVED** [review]

**Comment by Mauladen** [comment]
How else can I add https://www.phacility.com/

**Comment by techknowlogick** [comment]
@Mauladen Create a PR similar to this one with information about Phabricator.

**Review by techknowlogick — APPROVED** [review]

**Comment by Mauladen** [comment]
https://kallithea-scm.org/

**Comment by axifive** [comment]
@Mauladen And also https://alternativeto.net/software/gitea/

- GitBucket (Scala)
- Gitblit (Java)
- GitPrep (Perl)
- Gitolite (Perl)

**Pull request merged**
