### PR TITLE
Fix redirect with non-ascii branch names (#4764)

### LINKED ISSUE #4764: Error with Japanese branch name
- Gitea version (or commit ref):
- Git version: 1.5.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/chanhlt/test-repo
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I created a branch with name: 期日情報
I make changes and push to remote server.
Then, I visit Gitea Dashboard page.
I see my last activity there.

And when I click on the branch name, I get error.

### PR DESCRIPTION
**Pull request by SagePtr**
Fixes #4764

ctx.Req.URL.String() contains URL-encoded version of URL, but ctx.Params("*") contains non URL-encoded params, so strings.TrimSuffix was unable to match them when they contained non-ascii characters.

Now ctx.Req.URL.Path is checked, which is the same but not URL-encoded (resulting URL gets encoded by Macaron anyway, i tested this with raw HTTP-queries)

### CODE REVIEW

**Comment by lunny** [comment]
@SagePtr could you add a test I think there are already some examples there.

**Comment by SagePtr** [comment]
Should I pre-create testing non-ascii branch in ```integrations/gitea-repositories-meta/user2/repo1.git/refs/heads``` ? Because gitea itself does not allow to create non-ascii branches through API.
Also I doubt this test will pass if git repo directory is on filesystem which doesn't support utf8 (because in git each branch physically is a file named as branch name)

**Comment by lafriks** [comment]
@SagePtr yes you can pre-create branch with utf8 name in git repo

**Comment by SagePtr** [comment]
Fixtures does not work for mysql when default_branch value is non-ascii - cannot be inserted to DB (but in production this works okay, probably testing DB charset is something non-unicode)

**Comment by lafriks** [comment]
If you would have added default branch with ascii only and second branch with non-ascii than it would probably not break mysql tests.
Also as you have added new repository some counts need to be updated for unit tests

**Comment by SagePtr** [comment]
Now it passes tests. I hope tests are okay and their style is acceptable too. Tell me if something is wrong, because i'm new to Go coding standards.

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
@SagePtr please send backport to the release/v1.5 branch

**Pull request merged**
