### PR TITLE
fix bug forget to remove Stopwatch when remove repository

### PR DESCRIPTION
**Pull request by linweijie2012**
Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Should we also add migration to remove stopwatches that are left for already deleted repositories?

**Comment by linweijie2012** [comment]
yeah, but I think doing it in codes is more safe

**Comment by adelowo** [comment]
I think a migration is better though

**Review by appleboy — APPROVED** [review]

**Comment by lunny** [comment]
@linweijie2012 please send back port to release/v1.5

**Pull request merged**
