### PR TITLE
Fix submodule parsing (#32571)

### LINKED ISSUE #32568: Submodules not linked if file format not in default order
### Description

A submodule that is listed in .gitmodules as,

```
[submodule "jakarta-servlet"]
        url = ../../ALP-pool/jakarta-servlet
        path = jakarta-servlet
```

is not linked in the repository view. A submodule that is listed in the other order is linked correctly.

```
[submodule "jakarta-servlet"]
        path = jakarta-servlet
        url = ../../ALP-pool/jakarta-servlet
```

The gitmodules.txt doesn't seem to impose any particular order on values.

NOTE: Demo site is down at this second so can't check if I can reproduce it there.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

It's built and running with systemd, using core git tools

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
A quick fix for #32568
Partially backport from #32571

### CODE REVIEW

**Comment by silverwind** [comment]
Would a ini parser work for parsing `.gitmodules`?

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
> Would a ini parser work for parsing `.gitmodules`?
> 
> Also, imho this needs unit tests. Extract parsing logic into a function and test it?

This is partially backport from #32571

**Comment by silverwind** [comment]
I see. I would have ported the whole `configParseSubModules` function, unless it has more dependencies.

**Comment by wxiaoguang** [comment]
> Would a ini parser work for parsing `.gitmodules`?

No

> Also, imho this needs unit tests. Extract parsing logic into a function and test it?

The logic is same as #32571 , but it is not easy to test it in a backport, otherwise it would introduce too many unnecessary changes. I have manually tested it in m 1.22 branch.

**Comment by wxiaoguang** [comment]
Added tests in adb668a82d4b51f785a807b098a6dbefc3ee4396

**Review by silverwind — APPROVED** [review]

**Pull request merged**
