### PR TITLE
Update JS dependencies, add new eslint rules

### PR DESCRIPTION
**Pull request by silverwind**
- Result of `make update-js`.
- Tested build, vue, clipboard copy, swagger ui, citation.
- Added new eslint rules.

### CODE REVIEW

**Comment by silverwind** [comment]
The linter errors are bugs in the linter because missing `exports` support (https://github.com/un-ts/eslint-plugin-import-x/issues/9). Checking if there are workarounds.

**Comment by silverwind** [comment]
> The linter errors are bugs in the linter because missing `exports` support ([un-ts/eslint-plugin-import-x#9](https://github.com/un-ts/eslint-plugin-import-x/issues/9)). Checking if there are workarounds.

Fixed with https://github.com/go-gitea/gitea/pull/30840/commits/397a58e1cc1c71c177c4540a325a3759fed6aa46 to make it use the typescript resolver which does not have that problem.

**Comment by silverwind** [comment]
I've re-added the `main` property in package.json for those packages, so in theory it should lint again without a switch in the parser.

**Comment by silverwind** [comment]
Ready again, eslint changes are undone and this now includes a svg regeneration.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Updated once more, apparently svgo has reverted their changes so the svg's are back to original.

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
