### PR TITLE
fix wrong theme class when logged out if default theme is changed

### PR DESCRIPTION
**Pull request by crystalcommunication**
If you don't use the `auto` theme as the default, the `<html>` tag has `theme-auto` as it's class when users are logged out. This PR changes it to use the correct theme class for the default theme when logged out.

### CODE REVIEW

**Comment by jolheiser** [comment]
I am a bit conflicted on this, as it means we disrespect the user's preference for the sake of the instance admin's preference.

**Comment by jolheiser** [comment]
My apologies, I was referring to a non-logged-in user's preference, as set in their browser or wherever.

**Comment by jolheiser** [comment]
Ah, I see. It _used_ to rely on this, but it appears that was changed since then. 
My final thought, then, is whether this belongs in a custom template vs in the main codebase. 
I think for default installs this would resolve the same, so it may be fine.

@silverwind thoughts on this?

**Review by lunny — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]
Forgot to approve after last convo. 
SGTM

**Review by delvh — APPROVED** [review]

**Pull request merged**
