### PR TITLE
Disable federation by default (#20045)

### PR DESCRIPTION
**Pull request by Gusted**
- Backport #20045
  - A Gitea instance should choose whetever they want to federate(as once it has more features also brings extra costs/moderation/unexpected behavior) with other AP/ForgeFed software.

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
I think it can have `skip-changelog` since it didn't exist before 1.17...

**Comment by Gusted** [comment]
> I think it can have `skip-changelog` since it didn't exist before 1.17...

Yeah but should 1.18 also have the skip-changelog, as it wasn't introduced in that release either/

**Comment by delvh** [comment]
Both?

**Comment by Gusted** [comment]
> Both?

Yeah seems to make sense, never thought about it, but definitely had these situations before. So seems like some changelogs might be not accurate 🙈.

**Review by 42wim — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

**Pull request merged**
