### PR TITLE
Fix inconsistency in layout

### PR DESCRIPTION
**Pull request by pgaskin**
@strk This fixes the overlap you introduced in #618

### CODE REVIEW

**Comment by strk** [comment]
is this change in staging for review?

**Comment by strk** [comment]
Trusted LGTM anyway

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
I still see an inconsistency in layout here: https://try.gitea.io/user/settings/openid

**Comment by strk** [comment]
Version on try.gitea.io is 1.1.0+47-g1c3bd436 so it looks like it wasn't synced with latest merge from 21 hours ago ! @tboerger

**Pull request merged**
