### PR TITLE
Use Go 1.21 and update dependencies

### PR DESCRIPTION
**Pull request by wxiaoguang**
To make sure Gitea's next release's lifecycle could have active Golang support.

And min/max are builtin now.

### CODE REVIEW

**Comment by harryzcy** [comment]
Does it mean Gitea 1.21 drops support for Go 1.20?

**Comment by delvh** [comment]
Yes, effectively.
That's also why I'm unsure yet if I should approve or not.

**Comment by techknowlogick** [comment]
Let's hold off until Gitea 1.21 is out. We tend to keep the supported versions of golang supported by Gitea, and go1.20 is still supported.

**Comment by wxiaoguang** [comment]
I do not think it needs to be "hold"

We have done so many times, and see the discussions:

* #24859
*  #19918

I do not think there would be any problem.

**Comment by harryzcy** [comment]
It's about whether we want to let Gitea compile on Go 1.20 or not.

> To improve forwards compatibility, Go 1.21 now reads the go line in a go.work or go.mod file as a strict minimum requirement: go 1.21.0 means that the workspace or module cannot be used with Go 1.20 or with Go 1.21rc1.

**Comment by wxiaoguang** [comment]
> It's about whether we want to let Gitea compile on Go 1.20 or not.

My answer is "not". The code also uses Golang 1.21 new features like `min/max`

**Comment by harryzcy** [comment]
Windows 7 support ended already, and windows server 2012 won't be supported in Oct. I don't feel that's an issue.

Since gitea is not a library, I feel bumping go is fine, and it will make maintaining easier in the future.

**Comment by wxiaoguang** [comment]
> Windows 7 support ended already, and windows server 2012 won't be supported in Oct. I don't feel that's an issue.

Agree, and a few months later, Golang 1.20 will reach EOL. So the ending of Windows 7 support doesn't make much difference.

**Review by delvh — APPROVED** [review]
I don't have anything against it.
So, it's a cautious LGTM from my side.
I wonder how many times you'll need to discuss this exact scenario again, @wxiaoguang…

**Review by KN4CK3R — APPROVED** [review]

**Pull request merged**
