### PR TITLE
Fix inconsistent wiki path converting.

### LINKED ISSUE #24276: CI Flake: TestUserWebGitPathConsistency
### Description

Haven't seen that one yet.

https://drone.gitea.io/go-gitea/gitea/73145/3/8

```
--- FAIL: TestUserWebGitPathConsistency (0.05s)
    wiki_test.go:130: 
          Error Trace:  /drone/src/services/wiki/wiki_test.go:130
          Error:        Not equal: 
                        expected: ")&1]n7<G.md"
                        actual  : ")&1]n7<G"
                        
                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1 +1 @@
                        -)&1]n7<G.md
                        +)&1]n7<G
          Test:         TestUserWebGitPathConsistency
          Messages:     UserTitle for userTitle: ")&1]n7<G.md"
    wiki_test.go:131: 
          Error Trace:  /drone/src/services/wiki/wiki_test.go:131
          Error:        Not equal: 
                        expected: "%29%261%5Dn7%3CG.md"
                        actual  : "%29%261%5Dn7%3CG"
                        
                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,2 +1,2 @@
                        -(wiki.WebPath) (len=19) "%29%261%5Dn7%3CG.md"
                        +(wiki.WebPath) (len=16) "%29%261%5Dn7%3CG"
                         
          Test:         TestUserWebGitPathConsistency
          Messages:     WebPath for userTitle: ")&1]n7<G.md"
```

### PR DESCRIPTION
**Pull request by wxiaoguang**
The Infinite Monkey Random Typing catches a bug, inconsistent wiki path converting.

Close #24276

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
The test was newly  added by  #24143 , so "skip-changelog"

**Comment by silverwind** [comment]
@wxiaoguang can you set labels yourself?

**Comment by wxiaoguang** [comment]
No, I think I am not in the github team yet.

**Comment by silverwind** [comment]
CI Fail `TestRepoCommitsStatusParallel` unrelated.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
.

**Pull request merged**
