### PR TITLE
bug: fix assignees double load bug

### LINKED ISSUE #10853: [bug] Users with only read rights can select assignees on new PR page
- Gitea version (or commit ref): mast , mabe v1.11.x is same
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

there are a small bug about New PR page
user who don't have write permission can choose assignees on here:
jta
test on gitea.com
jtc

### PR DESCRIPTION
**Pull request by a1012112796**
Because the assigness has been loaded in

compare.go 416:
    RetrieveRepoMetas(ctx, ctx.Repo.Repository, true)
then
issue.go 381
	RetrieveRepoMilestonesAndAssignees(ctx, repo)
then

issue.go 361 -- 365 , they are load assignees

So the code on compare.go 425 -- 427 is double work,
and which is the reason of #10853

close #10853

### CODE REVIEW

**Comment by zeripath** [comment]
I'm going to add the lines here:

https://github.com/go-gitea/gitea/blob/90919bb37e2bcc62440e393439825fe0e1e1f343/routers/repo/compare.go#L416

I.e.

https://github.com/go-gitea/gitea/blob/9d3e69e8677008384d159ee138515ff7498064d7/routers/repo/issue.go#L368-L397

https://github.com/go-gitea/gitea/blob/9d3e69e8677008384d159ee138515ff7498064d7/routers/repo/issue.go#L347-L366 

In particular https://github.com/go-gitea/gitea/blob/9d3e69e8677008384d159ee138515ff7498064d7/routers/repo/issue.go#L361

**Comment by zeripath** [comment]
Now the trouble is `RetrieveRepoMetas` is only called if:

https://github.com/go-gitea/gitea/blob/90919bb37e2bcc62440e393439825fe0e1e1f343/routers/repo/compare.go#L393

And

https://github.com/go-gitea/gitea/blob/90919bb37e2bcc62440e393439825fe0e1e1f343/routers/repo/compare.go#L414

So it's not always a necessarily duplicate call. (Although it may be a completely unnecessary call ... I'm looking at this code likely for the first time from my phone and bed so I don't know completely.)

Would it be sufficient to add the opposite conditions on the ctx.Data['Assignees'] bit? Or is this call totally unnecessary in the first place?

**Comment by a1012112796** [comment]
> Now the trouble is `RetrieveRepoMetas` is only called if:
> 
> https://github.com/go-gitea/gitea/blob/90919bb37e2bcc62440e393439825fe0e1e1f343/routers/repo/compare.go#L393
> 
> And
> 
> https://github.com/go-gitea/gitea/blob/90919bb37e2bcc62440e393439825fe0e1e1f343/routers/repo/compare.go#L414
> 
> So it's not always a necessarily duplicate call. (Although it may be a completely unnecessary call ... I'm looking at this code likely for the first time from my phone and bed so I don't know completely.)
> 
> Would it be sufficient to add the opposite conditions on the ctx.Data['Assignees'] bit? Or is this call totally unnecessary in the first place?

Hello, I think this two check is all to check if it's ready to make a new pr, if not , It's not necessary to load them.  because It's not useed in compare page. thanks.

you see them in compare.tml :
https://github.com/go-gitea/gitea/blob/7cd47046ea6e1fde2c88290a42f345795aee0ea4/templates/repo/diff/compare.tmpl#L6
and
https://github.com/go-gitea/gitea/blob/7cd47046ea6e1fde2c88290a42f345795aee0ea4/templates/repo/diff/compare.tmpl#L60

**Comment by zeripath** [comment]
OK the Assignees box is only shown if those two conditions are passed:

https://github.com/go-gitea/gitea/blob/7cd47046ea6e1fde2c88290a42f345795aee0ea4/templates/repo/diff/compare.tmpl#L60-83

in particular the Assignees box comes from: 

https://github.com/go-gitea/gitea/blob/7cd47046ea6e1fde2c88290a42f345795aee0ea4/templates/repo/diff/compare.tmpl#L78

Therefore LGTM

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
