### PR TITLE
Use disable_form_autofill on Codebase and Gitbucket

### PR DESCRIPTION
**Pull request by qwerty287**
Removes the old fake input on the Codebase migration screen, and adds the disable_form_autofill

### CODE REVIEW

**Comment by zeripath** [comment]
I think the fake password is there to prevent autocomplete from filling in the password.

You'll need to replace it with:

```
				{{template "base/disable_form_autofill"}}
```

**Comment by zeripath** [comment]
See https://github.com/go-gitea/gitea/blob/b59875aa123f2cc3a5026d30ac557e99c05603a6/templates/repo/migrate/onedev.tmpl#L6

**Comment by qwerty287** [comment]
OK, thanks! I just removed it because there was the same issue on the GitBucket screen and there it was removed

**Comment by zeripath** [comment]
Oh could you add it to the gitbucket one then too.

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
