### PR TITLE
Internal ssh server respect Ciphers, MACs and  KeyExchanges settings

### LINKED ISSUE #14518: build in ssh server ignore restricting macs settings
- Gitea version (or commit ref): 1.13.1
- Git version: 1:2.17.1-1ubuntu0.7
- Operating system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Package download from https://dl.gitea.io/gitea/ and running via systemd

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

Setting `SSH_SERVER_MACS` seems to be ignored.

app.ini contains `SSH_SERVER_MACS = hmac-sha2-256-etm@openssh.com, hmac-sha2-256` but `ssh -Q mac gitea@<gitea-host>` still lists all:

```
ssh -Q mac gitea@...
hmac-sha1
hmac-sha1-96
hmac-sha2-256
hmac-sha2-512
hmac-md5
hmac-md5-96
umac-64@openssh.com
umac-128@openssh.com
hmac-sha1-etm@openssh.com
hmac-sha1-96-etm@openssh.com
hmac-sha2-256-etm@openssh.com
hmac-sha2-512-etm@openssh.com
hmac-md5-etm@openssh.com
hmac-md5-96-etm@openssh.com
umac-64-etm@openssh.com
umac-128-etm@openssh.com
```

### PR DESCRIPTION
**Pull request by root360-StefanHeitmueller**
Fix `// TODO: Handle ciphers, keyExchanges, and macs` for internal ssh server.
Fix #14518

Details see [here](https://github.com/gliderlabs/ssh/pull/95) (despite it was [renamed](https://github.com/gliderlabs/ssh/pull/112)).

Testconfig:

```
START_SSH_SERVER = true
SSH_SERVER_MACS  = hmac-sha2-256-etm@openssh.com, hmac-sha2-256
SSH_PORT                   = 2222
```

Before:
```
# nmap --script ssh2-enum-algos -sV -p 2222 gitea.example.com
Starting Nmap 7.80 ( https://nmap.org ) at 2021-01-29 17:46 CET
Nmap scan report for gitea.example.com (xxx.xxx.xxx.xxx)
Host is up (0.00055s latency).

PORT     STATE SERVICE VERSION
2222/tcp open  ssh     (protocol 2.0)
| fingerprint-strings: 
|   NULL: 
|_    SSH-2.0-Go
| ssh2-enum-algos: 
|   kex_algorithms: (5)
|       curve25519-sha256@libssh.org
|       ecdh-sha2-nistp256
|       ecdh-sha2-nistp384
|       ecdh-sha2-nistp521
|       diffie-hellman-group14-sha1
|   server_host_key_algorithms: (1)
|       ssh-rsa
|   encryption_algorithms: (5)
|       aes128-gcm@openssh.com
|       chacha20-poly1305@openssh.com
|       aes128-ctr
|       aes192-ctr
|       aes256-ctr
|   mac_algorithms: (4)
|       hmac-sha2-256-etm@openssh.com
|       hmac-sha2-256
|       hmac-sha1
|       hmac-sha1-96
|   compression_algorithms: (1)
|_      none
```

Afterwards:
```
# nmap --script ssh2-enum-algos -sV -p 2222 gitea.lan | sed 's,gitea\.lan,gitea.example.com,g'
Starting Nmap 7.80 ( https://nmap.org ) at 2021-01-29 17:47 CET
Nmap scan report for gitea.example.com (xxx.xxx.xxx.xxx)
Host is up (0.00052s latency).

PORT     STATE SERVICE VERSION
2222/tcp open  ssh     (protocol 2.0)
| fingerprint-strings: 
|   NULL: 
|_    SSH-2.0-Go
| ssh2-enum-algos: 
|   kex_algorithms: (6)
|       diffie-hellman-group1-sha1
|       diffie-hellman-group14-sha1
|       ecdh-sha2-nistp256
|       ecdh-sha2-nistp384
|       ecdh-sha2-nistp521
|       curve25519-sha256@libssh.org
|   server_host_key_algorithms: (1)
|       ssh-rsa
|   encryption_algorithms: (6)
|       aes128-ctr
|       aes192-ctr
|       aes256-ctr
|       aes128-gcm@openssh.com
|       arcfour256
|       arcfour128
|   mac_algorithms: (2)
|       hmac-sha2-256-etm@openssh.com
|       hmac-sha2-256
|   compression_algorithms: (1)
|_      none
```

### CODE REVIEW

**Comment by 6543** [comment]
@root360-StefanHeitmueller pleace `make fmt` and commit

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
@root360-StefanHeitmueller pleace update

**Comment by 6543** [comment]
@morph027 ping

**Comment by root360-StefanHeitmueller** [comment]
@6543 what's missing in the commit? the format fix has been pushed already, CI is passing.

**Comment by lafriks** [comment]
Need to update with base branch

**Comment by root360-StefanHeitmueller** [comment]
Done.

**Comment by 6543** [comment]
@root360-StefanHeitmueller can you send a backport?

**Comment by root360-StefanHeitmueller** [comment]
Sure. For the `release/v1.13` branch?

**Comment by 6543** [comment]
@root360-StefanHeitmueller yes, just cherry pick the squashed commit ...

**Comment by root360-StefanHeitmueller** [comment]
Should be there in https://github.com/go-gitea/gitea/pull/14530

**Pull request merged**
