### PR TITLE
Provide actions badge svgs

### LINKED ISSUE #23688: Add badge for Gitea Actions to display result in README.md
### Feature Description

Like it exists on GitHub or other CI, it could be interesting to add a SVG badge to integrate into markdown in example.

The documentation to use it on GitHub could be found https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

An URL like `https://<GITEA_INSTANCE>/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg` with:
* `GITEA_INSTANCE` the domain/url of the Gate server
* `OWNER` the project owner/organisation
* `REPOSITORY` the repository name
* `WORLFLOW_FILE` the filename of the action that trigged the build, and so, the result of the build

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by lunny**
Fix #23688

### CODE REVIEW

**Comment by silverwind** [comment]
If we could template the SVGs in gotemplate, that would be even more flexible, for example the user could change the name string via a URL argument, if they so desire.

**Comment by silverwind** [comment]
Also, I suggest lowercasing the status text, and likely it should just mirror the 4 commit statuses we currently have in the displayed string.

**Comment by silverwind** [comment]
https://github.com/essentialkaos/go-badge seems like a package we could use.

**Comment by lunny** [comment]
> If we could template the SVGs in `html/template` (I asssume it would be suitable), that would be even more flexible, for example the user could change the name string via a URL argument, if they so desire, but in any case, I can accept the current solution as well.

The current method could use CDN and web browser cache better to reduce possible network requests.

**Comment by silverwind** [comment]
Caching can be achieved with proper cache headers as well even when generating those badges dynamically.

BTW, I would personally short the text to `CI: success`, so I guess many people would want to be able to customize the left side text at least.

**Comment by puni9869** [comment]
Could you share the screenshots, if applicable?

**Comment by lunny** [comment]
> Could you share the screenshots, if applicable?

There is no screenshots. Only svg files on files changed tab.

**Comment by lunny** [comment]
> Caching can be achieved with proper cache headers as well even when generating those badges dynamically.
> 
> BTW, I would personally short the text to `CI: passing`, so I guess many people would want to be able to customize the left side text at least.

This is only for Gitea Actions but not any other integrated third-party CI/CD system. So use `Gitea Actions` will not make user confusing but `CI` maybe.

**Comment by silverwind** [comment]
Checking how GitHub [does it](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge), they require the workflow name and render it into the SVG. I guess this would be good to have because because if there are multiple workflows, having all of them show "Gitea Actions" would be very confusing. 

Example GitHub badges:

**Comment by silverwind** [comment]
I think it can not easily templated with golang because the `width` of the SVG needs to be dynamically set based on text. So I think https://github.com/essentialkaos/go-badge might still be the best option.

**Pull request closed without merging**
