### PR TITLE
fix ssh repo clone link

### PR DESCRIPTION
**Pull request by kanoulis**
Add missing RepoRootPath for ssh clone link

### CODE REVIEW

**Comment by lunny** [comment]
I think you make a mistake. The path should be a relative path and Gitea will resolve the relative path to absolute path.

**Comment by kanoulis** [comment]
That is true for the HTTP/HTTPS clone link. How would that work for SSH ?

**Comment by lunny** [comment]
We have rewrite the authorized_keys file, when `git push` invoked, `gitea serv` will be called so that we can detect that.

**Comment by kanoulis** [comment]
I do not use authorized_keys for authentication.

**Comment by lunny** [comment]
If you use system SSH server, It will use authorized_keys. And you have to add public key in personal settings before using SSH.

**Pull request closed without merging**
