### PR TITLE
Add severity/priority feature for issues #2616

### PR DESCRIPTION
**Pull request by andrebruch**
The PR is a solution for issue #2616.

The database table "issue" has been extended by the column "severity". This can take the values: "Low", "Medium", "High" and "Urgent".

### CODE REVIEW

**Comment by lunny** [comment]
We would like to add a score with label and sort by socres of issue.

**Comment by zeripath** [comment]
Hmm ..  This appears to be codifying and rigidifying a method of working that doesn't necessarily match every project's way of working - (and perhaps even within the same project over time)

Maybe what you're after is to add some inherent order to labels? We can think about adding a score to these and perhaps some better way of selecting all labels with a prefix?

**Comment by jolheiser** [comment]
This is targeting `release/v1.10` as well, which we are no longer accepting features for. 😅   
Thank you for taking the time to contribute, though!

**Comment by lafriks** [comment]
I have started working on this a bit different based on labels

**Comment by andbruch** [comment]
Thanks everyone for the feedback.
I see that the consensus is that the feature should be solved with labels.

@jolheiser I could have migrated the implemented feature.
@zeripath You can see it like this, but you can also see it as a kind of structuring of the project.

@lafriks Will it have a separate severity dropdown menu? If it is in the labels menu, it would be good if the labels (severity levels) were sorted according to the score. So that the entries appear at the top of the list.
It would also be good to have a setting that adds default labels to a new issue, such as "low" severity.
Is something similar also planned for the additional states (in-progress and review)?

**Comment by lafriks** [comment]
Default labels is out of scope of my PR but sorting will be added based on priority/severity

**Comment by no-go** [comment]
I love this simple (still implemented !) priority feature. Maybe it would be great, to make issue-handling (scores, colors, label names, additional issue attributes) more "module like". I like to add this version to my gitea without getting in trouble with gitea updates.

The "module like" version could help to finalize the discussion about many years, which kind of prioritization would be the best.

**Comment by 6543** [comment]
what do you mean with `"module like" version`?

**Comment by no-go** [comment]
I am thinking of a customizable (i.e. replaceable) code part to add the function without recompiling the whole part of gitea.

**Comment by 6543** [comment]
ah you refere to the "plugin feature" wo do not exist at the moment

**Comment by no-go** [comment]
yes!

**Comment by no-go** [comment]
Hi, my opinion has just changed somewhat: plugin idea ok, but I use "priority feature" via the new Kanban Board ;-)

**Pull request closed without merging**
