### PR TITLE
Show if File is Executable

### PR DESCRIPTION
**Pull request by JakobDev**
This simply shows if a File has the executable Permission

grafik

### CODE REVIEW

**Comment by silverwind** [comment]
Would shorten it to just "Executable" because it's already obvious that it's a file. And like move it after Lexer name.

**Comment by silverwind** [comment]
Or maybe just show "10755" which would be [consistent with diffs](https://github.com/go-gitea/gitea/pull/24966). Would probably not show non-executable mode.

**Comment by JakobDev** [comment]
> Would shorten it to just "Executable" because it's already obvious that it's a file. And move it after Lexer name.

Sure, i can do that

> Or maybe just show "10755" which would be [consistent with diffs](https://github.com/go-gitea/gitea/pull/24966). Would probably not show non-executable mode "10644".

I don't think we should show the full Permissions. the only thing a User might be interested in, is if a File is Executable or not. And I think, showing those as octal might confuse Users, because today you often don't work directly with octal.

**Comment by silverwind** [comment]
Thought I guess we can keep "Executable File" as well for consistency with GitHub:

Screenshot 2023-06-15 at 19 40 15

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Think we can backport this tiny feature.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
> Think we can backport this tiny feature.

As an enhancement we can do that.

**Pull request merged**
