### PR TITLE
Fix the truncate and alignment problem for some admin tables

### PR DESCRIPTION
**Pull request by wxiaoguang**
Some "text truncate email" code were just copied&pasted, they are not suitable for most admin tables.

For the table layouts, some "max-width" helpers could be very helpful. At least, we can get rid of the confusing "email" CSS class.

image

image

image

### CODE REVIEW

**Comment by silverwind** [comment]
Did you check all admin tables?

**Review by silverwind — APPROVED** [review]
Works and is the same approach I had used in https://github.com/go-gitea/gitea/pull/25942#issuecomment-1645802272.

**Comment by wxiaoguang** [comment]
> Did you check all admin tables?

I have checked, I thin that's all .

**Comment by silverwind** [comment]
Yes, looks complete for admin tables. Quick search for `text.+truncate`:

```
templates/admin/emails/list.tmpl:50
templates/admin/packages/list.tmpl:59
templates/admin/packages/list.tmpl:60
templates/admin/user/list.tmpl:88

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Some odd failures with a ldap test, already the second time now:

````
    auth_ldap_test.go:246: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/auth_ldap_test.go:246
        	Error:      	Not equal: 
        	            	expected: "professor@planetexpress.com"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-professor@planetexpress.com
        	            	+
        	Test:       	TestLDAPUserSync
    testlogger.go:60: 2023/07/21 17:01:52 ...eb/routing/logger.go:102:func1() [I] router: completed GET /admin/users?q=hermes for test-mock:12345, 200 OK in 25.4ms @ admin/users.go:38(admin.Users)
    auth_ldap_test.go:246: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/auth_ldap_test.go:246
        	Error:      	Not equal: 
        	            	expected: "hermes@planetexpress.com"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-hermes@planetexpress.com
        	            	+
        	Test:       	TestLDAPUserSync
    testlogger.go:60: 2023/07/21 17:01:52 ...eb/routing/logger.go:102:func1() [I] router: completed GET /admin/users?q=fry for test-mock:12345, 200 OK in 26.5ms @ admin/users.go:38(admin.Users)
    auth_ldap_test.go:246: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/auth_ldap_test.go:246
        	Error:      	Not equal: 
        	            	expected: "fry@planetexpress.com"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-fry@planetexpress.com
        	            	+
        	Test:       	TestLDAPUserSync
    testlogger.go:60: 2023/07/21 17:01:52 ...eb/routing/logger.go:102:func1() [I] router: completed GET /admin/users?q=leela for test-mock:12345, 200 OK in 26.7ms @ admin/users.go:38(admin.Users)
    auth_ldap_test.go:246: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/auth_ldap_test.go:246
        	Error:      	Not equal: 
        	            	expected: "leela@planetexpress.com"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-leela@planetexpress.com
        	            	+
        	Test:       	TestLDAPUserSync
    testlogger.go:60: 2023/07/21 17:01:52 ...eb/routing/logger.go:102:func1() [I] router: completed GET /admin/users?q=bender for test-mock:12345, 200 OK in 25.7ms @ admin/users.go:38(admin.Users)
    auth_ldap_test.go:246: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/auth_ldap_test.go:246
        	Error:      	Not equal: 
        	            	expected: "bender@planetexpress.com"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-bender@planetexpress.com
        	            	+
        	Test:       	TestLDAPUserSync
````

**Comment by silverwind** [comment]
I think there is some integration that hooked onto the `.text` class.

**Comment by denyskon** [comment]
The LDAP test is one I have been breaking a few times now..... We have some tests including this one which rely on some CSS classes - I wonder if there's any better solution for it....

**Comment by wxiaoguang** [comment]
Removed all "HTML-baesd tests", now CI psases

**Pull request merged**
