### PR TITLE
Fix empty checkbox in dashboard repolist's filter

### LINKED ISSUE #22800: The checkbox in repositories filter of dashboard will always be empty after click
### Description

the checkbox of `private` and `archived` will always be empty after click.
if you refresh the page, it will show rightly.

Im trying to fix this.

image

after click, `title` is same but the checkbox is empty
image

### Gitea Version

1.19.0+dev-442-g3ae78bc0a

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

try.gitea.io
gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fixes https://github.com/go-gitea/gitea/issues/22800

I found [this issue comment](https://github.com/vuejs/vue/issues/4094#issuecomment-338483683).
It seems that there is an easy way to set `indeterminate` state to the checkboxes in Vue.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Some changes look a little strange to me.

If you don't mind, I could try to fine tune some changes based on your PR. Do you think it is okay?

**Comment by yp05327** [comment]
> Some changes look a little strange to me.
> 
> If you don't mind, I could try to fine tune some changes based on your PR. Do you think it is okay?

@wxiaoguang 
Sure, you are welcome.

**Comment by wxiaoguang** [comment]
Fix incorrect checkbox behaviors in the dashboard repolist's filter #23147

**Comment by yp05327** [comment]
Move to https://github.com/go-gitea/gitea/pull/23147

**Pull request closed without merging**
