### PR TITLE
Respect `REQUIRE_SIGNIN_VIEW` for packages (#20873)

### PR DESCRIPTION
**Pull request by KN4CK3R**
Backport of #20873

### CODE REVIEW

**Comment by lafriks** [comment]
go lint failure

**Comment by KN4CK3R** [comment]
For files not touched by this PR. Could your restart the build? `go fmt` changes nothing on my side.

**Comment by wxiaoguang** [comment]
I think the reason is that the `gitea/test_env` image used by drone pipeline has just upgraded the Golang to 1.19.x

Go 1.19 has different `go fmt` output.

**Review by wxiaoguang — APPROVED** [review]
LGTM while the lint failure should be fixed in another PR (when using Go 1.19.x fmt, more than 10 files will be changed)

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> LGTM while the lint failure should be fixed in another PR (when using Go 1.19.x fmt, more than 10 files will be changed)

Go 1.19 fmt fix:
* #21239

**Review by wxiaoguang — APPROVED** [review]

**Pull request merged**
