### PR TITLE
Add logic to build stable and edge builds for gitea snap

### PR DESCRIPTION
**Pull request by popey**
This adds some logic to enable the snapcraft builds of the gitea snap to create both builds of the latest tip of master for edge channels, and stable releases.

The logic simply looks for a new upstream release in github, and if that latest tagged release is not the same as the release in the candidate channel in the snap store, then it must be new, and so we checkout that tag and build that. If the current released tag is the same as what's in candidate, we build whatever is in git master.

The process for using this is:

Initially: When this lands, it will build the latest stable release of gitea and push to the edge channel in the snap store. Someone on the release team can go to https://snapcraft.io/gitea/releases and release that build to stable and candidate.

Ongoing: The next build to be triggered will be a git master build, and can just sit in edge, nothing for the release team to do.

On new release: The next build triggered will contain the stable release, and will be published to edge. Someone on the release team can login to the above URL and release that again to stable & candidate. Alternatively they can release to candidate, do some additional testing on that release before releasing to stable.

Hope that all makes sense. Questions / comments welcome.

I'm super keen to see stable releases of Gitea in the stable channel of the Snap Store. I'd like to promote it but I can't really until it's in stable.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
This doesn't prevent a downgrade from 1.12 to 1.11, right? Also, what about tags like `v1.12.0-rc2`?

````
$ git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -5
v1.12.0-rc2
v1.11.7
v1.12.0
v1.11.8
v1.12.1
````

**Comment by techknowlogick** [comment]
@silverwind As I understand it we need to manually release to beta/stable using the snap website, and that would prevent a downgrade.

**Comment by techknowlogick** [comment]
@silverwind just checked and my assumption is correct, we would have to manually promote specific versions and this would prevent downgrades.

Example of how we would promote using snapcraft GUI:
Screen Shot 2020-07-15 at 11 41 48 PM

**Review by 6543 — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Comment by techknowlogick** [comment]
@popey I've just released a stable version of the snap 🎉

**Comment by popey** [comment]
@techknowlogick Sorry I missed the notifications. This is super news! :D

**Pull request merged**
