### PR TITLE
Fix span wrapping all the things

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
As it is in the title. Wrap in ```<span>``` only if text contains link to autolink. Fixes double sized table borders. Ready as it is. Fixes regression introduced in #186.

### CODE REVIEW

**Comment by lunny** [comment]
For example?

**Comment by andrew-boyarshin** [comment]
@lunny <https://try.gitea.io/STALKER_2010/wine-staging/wiki>, notice horizontal table borders. Double sized compared to the ones before my PR #186.

**Comment by andrew-boyarshin** [comment]
And most likely, it was also the reason why ```display: block``` worked badly with table headers after my PR. Spans were also inserted even between tags, even when there was no text there.

**Comment by lunny** [comment]
Out of the topic. Do you know https://try.gitea.io/STALKER_2010/wine-staging/wiki the right sidebar seems not correct?

**Comment by andrew-boyarshin** [comment]
@lunny yes, I noticed it long ago, when I was working on #186 PR version for Gogs, yet I didn't work on that. It must be tabulation (or spacing, whatever), that drives blackfriday crazy. As far as I have found out, blackfriday works with list items incorrectly when list items do not start at the beginning of the line. Most likely, it is also the cause of #411.

**Comment by lunny** [comment]
trusted LGTM

**Comment by andrew-boyarshin** [comment]
Anyone willing to review?

**Comment by andreynering** [comment]
LGTM

**Pull request merged**
