### PR TITLE
Upgrade fomantic ui from 2.8.7 -> 2.9.3

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I guess it's not right. IIRC Fomantic library is manually maintained and should need to "build" and update the css/js files manually.

**Comment by silverwind** [comment]
You need to run `make fomantic` to rebuild it. We should definitely test this upgrade for any regressions. I recall the last fomantic upgrades all broke the UI in subtle ways, especially regarding our CSS overrides.

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
not as simple as changing a version

**Comment by lunny** [comment]
> make fomantic

Looks like `make fomantic` generated many changes. I don't know whether they are correct.

I will close this one to leave the problem to others.

**Pull request closed without merging**
