### PR TITLE
Add ENABLE_PPROF to app.ini and start pprof if true on localhost:6060

### PR DESCRIPTION
**Pull request by metalmatze**
For #753 I want a simple way for people to enable pprof so they can debug with our help, or on their own, growing memory consumption or CPU usage.

For that I added `ENABLE_PPROF` to the `app.ini`.

```
[server]
ROOT_URL         = http://localhost:3000/
...
ENABLE_PPROF     = true
```

If set to true gitea will start pprof on localhost:6060 with the `gitea web` command.

https://blog.golang.org/profiling-go-programs
https://golang.org/pkg/net/http/pprof/

### CODE REVIEW

**Comment by lunny** [comment]
why not put it on the admin panel

**Comment by metalmatze** [comment]
If one enables pprof in the admin panel, would they just set this variable that I used to `true`, or would they simply start pprof in a goroutine with everything else continuing as before? So basically just starting another goroutine next to the webserver?!

**Comment by strk** [comment]
Should there be a PPROF_LISTEN_PORT too ?

**Comment by metalmatze** [comment]
I don't think so. Port `6060` is the standard for pprof and it should only be temporary enabled for debugging.

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
let L-G-T-M work

**Pull request merged**
