### PR TITLE
[Vendor] upgrade google/go-github to v32.1.0

### PR DESCRIPTION
**Pull request by 6543**
as title

important since GH deprecated lot of stuff and added/moved things

### CODE REVIEW

**Comment by 6543** [comment]
I think this is worth backporting to let the migration tool work on v1.12 properly in the future :)

**Review by techknowlogick — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Comment by zeripath** [comment]
make lg-tm work

**Comment by 6543** [comment]
Backport: #12390

**Pull request merged**
