### PR TITLE
update for simplest build instructions

### PR DESCRIPTION
**Pull request by coolaj86**
This method works out of the box with just the standard go tooling - no make tools, no C compiler, no special environment variable setting, etc.

Actually, it could be reduced even simpler:

```go
go generate ./...
go build -tags 'bindata'
```

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Only difference it will not have version number compiled in

**Comment by solderjs** [comment]
@lafriks Please review https://github.com/go-gitea/gitea/pull/6567 also. The two go hand-in-hand.

**Review by sapk — APPROVED** [review]
Need #6567 to be merged before

**Review by sapk — APPROVED** [review]
Need #6567 to be merged before

**Comment by lunny** [comment]
@solderjs I have commented on #6567 that you could add docs on that PR and just notice this one. Ignore that comment.

But I think we could give two build process there and don't remove `make` one.

**Comment by lunny** [comment]
This will not work since we have removed generated js/css files. We have to use `make` to do all the build.

**Pull request closed without merging**
