### PR TITLE
Move issue notifications and assignee man

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]
PR LGTM, but the title is a little misleading 😉

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@lunny thanks for refactoring the code ... :+1:

**Comment by lunny** [comment]
@guillep2k Any idea about the title?

**Comment by lunny** [comment]
@6543 :)

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k Any idea about the title?

@lunny `Move issue notifications and assignee management` ? It's already merged, anyway. :grin:

**Comment by lunny** [comment]
@guillep2k changed. Merged is not this PR's end. It will be used when we write release notes.

**Pull request merged**
