### PR TITLE
Skip TestRepoCommitsStatusParallel on CI

### PR DESCRIPTION
**Pull request by silverwind**
Related: https://github.com/go-gitea/gitea/issues/22109

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I am sure it's fixable and should be fixed, I don't think it is right to skip failed tests. Otherwise why the tests are written?

**Comment by lunny** [comment]
> 

I think maybe silverwind means we have know the bug and just skip it but keep the issue open. After we fix it, then reenable the test.

**Comment by silverwind** [comment]
Yes, keep the issue open, but skip it as not skipping is just a waste of contributor time and CI resources.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I have objection for skipping it.

You have the PR #24567 and I think bug should and could be fixed.

**Comment by wxiaoguang** [comment]
Just took  a look at the details again, it looks like due to the ability limitation of XORM and how Gitea uses databases and the supported database version requirements. I guess there is no easy way to make all database happy for some transaction problems.

So I won't block the "Skip" . The similar thing also applies to the container's in-process mutex workaround.

**Review by wxiaoguang — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by lunny** [comment]
I will continue working on #24567

**Comment by silverwind** [comment]
> I will continue working on #24567

Merge this until then?

**Comment by silverwind** [comment]
Decided to merge, real fix can come in https://github.com/go-gitea/gitea/pull/24567.

**Pull request merged**
