### PR TITLE
[Docs] Git Setup

### PR DESCRIPTION
**Pull request by bagasme**
As title.

Installing Git from binary package and source

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
@bagasme can you add a link to this page on ? https://github.com/go-gitea/gitea/blob/8a828500e689b7958e050ebd2dc46d380c3d6ae6/docs/content/doc/installation/from-binary.en-us.md#L52

**Review by techknowlogick — CHANGES_REQUESTED** [review]
I’m unsure if we need this entire page for instructions on installing git, especially if we link to git-scm.org for most of it. There are links below that would need to be updated and monitored for changes, where the official git site already handles that

**Comment by jolheiser** [comment]
Perhaps just adding some links to the binary page or FAQ? In my opinion, building Git from source is out of scope for Gitea documentation.

**Comment by 6543** [comment]
@jolheiser if git users lookup gitea's docs then we made it :laughing:

**Comment by bagasme** [comment]
@techknowlogick `git-scm.com` site mention this (build from source) on [Pro Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

**Comment by techknowlogick** [comment]
I'm not concerned about specifically building from source, but rather there links to specific tar bundles that would need to be updated, as well as reviewing the link you just posted the content covers the same but in greater detail. Maybe instead you could add a small note to the installation page that mentions git is also required and link to the page that you just did so that we don't need to maintain it and the official docs from git will always be most accurate and most maintained.

**Pull request closed without merging**
