### PR TITLE
fix orgnization webhooks

### PR DESCRIPTION
**Pull request by lunny**
fix missing discord webhook wrong route and missing template on orgnization webhooks and fix bug on deliver webhook.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
What was the bug that led to the changes to the `HookTask.deliver()` method?

**Comment by lunny** [comment]
@ethantkoenig that should be a bug of `GetWebhookByRepoID` when the webhook is an orgnization webhook. Then the latest status will not be updated. And I added `UpdateWebhookLastStatus` for only update the `last_statu` but not all the columns.

**Comment by ethantkoenig** [comment]
LGTM

**Pull request merged**
