### PR TITLE
Compute proper foreground color for labels

### PR DESCRIPTION
**Pull request by clarfonthey**
This properly ensures that the contrast ratio is maximised for any given color choice.

The comments explain the exact calculations done (you can check that I transcribed it correctly), but to fully clarify for review:

1. Human eyes are better at detecting contrast than absolute differences in brightness. So, it's easier to see the difference between 0% and 10% brightness, than 90% and 100% brightness, even though it's the same absolute difference.
2. As a result, sRGB scales the colours so that the 0-255 range for each component has more dark shades than bright shades.
3. If you want to check the contrast between two colours, you need to undo this scaling.

### CODE REVIEW

**Comment by silverwind** [comment]
Note there is a similar function in JS that should match the backend implementation:

https://github.com/go-gitea/gitea/blob/c9bca8c5e0d31d7c844c8e9c96588d0c7c5e0392/web_src/js/components/ContextPopup.vue#L75-L86

**Comment by clarfonthey** [comment]
Good catch! I'll fix that this evening

**Comment by clarfonthey** [comment]
Fixed!

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
I think this all looks great, would you be able to attach a couple example images?

**Comment by clarfonthey** [comment]
Sure thing! I'll take some tonight with some sample colours.

**Review by jolheiser — APPROVED** [review]
Disregard my other comment, for some reason I thought this was changing colors, rather it's just a different formula for choosing white/black text.

**Comment by clarfonthey** [comment]
I'll still take some tonight anyway, since it might be helpful for the changelog

**Pull request merged**
