### PR TITLE
Pr hook branch info

### PR DESCRIPTION
**Pull request by kmadel**
Please check the following:

1. Make sure you are targeting the `master` branch.
2. Read contributing guidelines:
   https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue
   you're targeting (if any)

**You MUST delete above content including this line before posting;
too lazy to take this action considered invalid pull request.**

### CODE REVIEW

**Comment by strk** [comment]
It looks like you missed the `too lazy to take this action` message ...

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
LGTM isn't working, still counts 0/2 while there @lunny one -- if these tools aren't stable we should consider dropping their use

**Comment by kmadel** [comment]
This was a PR from GoGits that was asked to be pushed here as well - I will update when I get a chance. If someone needs it sooner, by all means take it.

**Comment by bkcsoft** [comment]
@kmadel I have a working branch for this (and more) that needs migration to Gitea anyways so I'll hijack this one :slightly_smiling_face:

**Comment by tboerger** [comment]
@bkcsoft so what happens to it?

**Comment by bkcsoft** [comment]
New PR here: https://github.com/go-gitea/gitea/pull/248

**Comment by lunny** [comment]
So this one could be closed?

**Comment by tboerger** [comment]
Yep, since it's done by @bkcsoft we should close this PR.

**Comment by bkcsoft** [comment]
@lunny AFAICR they conflict with eachother, and implement the same thing in different ways... so IMO this should be closed in favour of #248 which follows githubs api more closely :)

**Pull request closed without merging**
