### PR TITLE
Update JS deps and linting config

### PR DESCRIPTION
**Pull request by silverwind**
- update js deps to latest versions
- remove eslint-plugin-sonarjs to prevent a warning on install. can be added again once it's updated to support eslint 7.x
- enable new linting rules from eslint-plugin-unicorn

### CODE REVIEW

**Comment by silverwind** [comment]
Updated deps again, webpack and dropzone bumped.

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by techknowlogick** [comment]
please resolve conflicts :)

**Comment by silverwind** [comment]
Resolved and pushed some more misc dependency updates: css-loader,mermaid and terser-webpack-plugin. The css-loader update did require a minor change in the webpack config as a function signature was changed. Looks to work well otherwise.

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
