### PR TITLE
Do docker releases for pushes to release branches (#10330)

### PR DESCRIPTION
**Pull request by zeripath**
Backport #10330 

Co-authored-by: Lauris BH <lauris@nix.lv>

### CODE REVIEW

**Comment by sapk** [comment]
I am adding the blocked status because I would prefer that we discuss this before in #10330.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
o sory ... this is blocked

**Comment by zeripath** [comment]
@sapk I don't understand. What will go wrong here? We previously had dockers being made for the heads of our release branches.

**Comment by lunny** [comment]
Should 1.11 point to release/v1.11 or to latest tag on release/v1.11? That's the problem.

**Comment by zeripath** [comment]
I would have thought that it would point to the latest release/v1.11 not the latest tag.

**Comment by zeripath** [comment]
Can we decide what to do? Does #10330 need reverting?

**Comment by lafriks** [comment]
We should probably vote

**Comment by zeripath** [comment]
Let's discuss it on the revert PR

**Pull request closed without merging**
