### PR TITLE
Code review UI improvements and bugfixes

### LINKED ISSUE #4752: Add single comment when reviewing code in deleted file generates fatal: no such path
Gitea version (or commit ref):

/var/lib/gitea>sudo /usr/local/bin/gitea --version
Gitea version 1b2aff0 built with: bindata, sqlite
[master snapshot grabbed on Aug 15th]

- Git version:
git version 2.18.0

- Operating system:
CentOS release 6.4 (Final)

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Very likely, but I couldn't turn up an example PR to comment on right away.

- Log gist:

    2018/08/20 09:29:23 [.../repo/pull_review.go:77 CreateCodeComment()] [E] CreateCodeComment: LineBlame[refs/pull/1/head, /home/git/gitea-repositories/mlk/ebill.git, WEB-INF/lib/.gitignore, 1]: exit status 128 - fatal: no such path WEB-INF/lib/.gitignore in refs/pull/1/head

## Description

Attempting to add a review comment to a deleted file generates an error and 

1) Create PR including deleted file
2) Click "Files changed"
3) Click "+" on any line of a deleted file.
4) Enter any comment.
5) Click "Add single comment"

Generates log entry above.    Redirects to 500 Internal Server Error page.

## Screenshots

See before and after here.

https://gist.github.com/mkienenb/016013ce9a50653ec02859d9fff14415

### LINKED ISSUE #4901: Cannot add review comment
- Gitea version (or commit ref): 6e03390 (1.5+)
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/go-gitea/chardet/pulls/1/files
## Description

If I try to add a review comment at try.gitea.io it results in an unreported error.

### LINKED ISSUE #4909: Arc Green (dark) theme Review result is near unreadable
- Gitea version (or commit ref):  bd1bf2a
- Git version:  2.7.4
- Operating system:  Ubuntu 18.04
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant (because it is not using the Arc Green theme)
- Log gist:  N/A

## Description

The Arc Green theme review result is not themed well, fairly unreadable, black text on dark background.  See image.  The background needs to be changed up, the 'rejected' review needs to be more obvious (perhaps a red tinted background?), etc...

## Screenshots

image

### PR DESCRIPTION
**Pull request by lafriks**
1. Allow review comment/reject without message if code comments have been already added
2. Dark theme fixes for code comments
3. Make visually better padding for code comment replies
4. Do not show button `Add single comment` if there is already started review
5. Fixes #4901
6. Fixes #4752 
7. Fixes #4909

### CODE REVIEW

**Comment by lunny** [comment]
It seems I cannot post comment on code lines any more.

**Comment by lafriks** [comment]
@lunny try Ctrl+F5. What error do you get?

**Comment by lunny** [comment]
```
PANIC: runtime error: index out of range
/Users/xxx/goroot/src/runtime/panic.go:502 (0x402d798)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/Users/xxx/goroot/src/runtime/panic.go:28 (0x402c5dd)
	panicindex: panic(indexError)
/Users/xxx/gopath/src/code.gitea.io/gitea/models/git_diff.go:321 (0x488592f)
	CutDiffAroundLine: begin = com.StrTo(groups[3]).MustInt64()
/Users/xxx/gopath/src/code.gitea.io/gitea/models/issue_comment.go:848 (0x48a30f6)
	CreateCodeComment: patch = CutDiffAroundLine(strings.NewReader(patchBuf.String()), int64((&Comment{Line: line}).UnsignedLine()), line < 0, setting.UI.CodeCommentLines)
/Users/xxx/gopath/src/code.gitea.io/gitea/routers/repo/pull_review.go:67 (0x4a0a59f)
	CreateCodeComment: comment, err := models.CreateCodeComment(
/Users/xxx/goroot/src/runtime/asm_amd64.s:575 (0x405a211)
	call128: CALLFN(·call128, 128)
/Users/xxx/goroot/src/reflect/value.go:447 (0x40bdde8)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/Users/xxx/goroot/src/reflect/value.go:308 (0x40bd363)
	Value.Call: return v.call("Call", in)
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x43b7634)
	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x43b6fb9)
	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43e386d)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x43e37ae)
	(*Context).Next: c.run()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:186 (0x4434305)
	Sessioner.func1: ctx.Next()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:79 (0x43e3680)
	ContextInvoker.Invoke: invoke(params[0].(*Context))
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x43b7346)
	(*injector).fastInvoke: return f.Invoke(in)
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x43b70aa)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43e386d)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x43e37ae)
	(*Context).Next: c.run()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x43f43da)
	Recovery.func1: c.Next()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x43e69d3)
	LoggerInvoker.Invoke: invoke(params[0].(*Context), params[1].(*log.Logger))
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x43b7346)
	(*injector).fastInvoke: return f.Invoke(in)
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x43b70aa)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43e386d)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x43e37ae)
	(*Context).Next: c.run()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:52 (0x43f36f0)
	Logger.func1: ctx.Next()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x43e69d3)
	LoggerInvoker.Invoke: invoke(params[0].(*Context), params[1].(*log.Logger))
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x43b7346)
	(*injector).fastInvoke: return f.Invoke(in)
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x43b70aa)
	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x43e386d)
	(*Context).run: vals, err := c.Invoke(c.handler())
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:187 (0x43f5581)
	(*Router).Handle.func1: c.run()
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:303 (0x43eef7b)
	(*Router).ServeHTTP: h(rw, req, p)
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x43e7cc4)
	(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
/Users/xxx/gopath/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x4752fca)
	ClearHandler.func1: h.ServeHTTP(w, r)
/Users/xxx/goroot/src/net/http/server.go:1947 (0x429f223)
	HandlerFunc.ServeHTTP: f(w, r)
/Users/xxx/goroot/src/net/http/server.go:2694 (0x42a1f7b)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/Users/xxx/goroot/src/net/http/server.go:1830 (0x429e240)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/Users/xxx/goroot/src/runtime/asm_amd64.s:2361 (0x405c8c0)
	goexit: BYTE	$0x90	// NOP
2018/08/13 17:34:06 http: multiple response.WriteHeader calls
[Macaron] 2018-08-13 17:34:06: Completed POST /lunny/git/pulls/2/files/reviews/comments 500 Internal Server Error in 203.638717ms
```

**Comment by lunny** [comment]
@lafriks conflicted

**Comment by lafriks** [comment]
@lunny conflicts resolved. ~~Can you give more details on your error? I'm not able to reproduce it and~~ I don't think it is related to my changes.
That error was not related to my changes but I did fix it I think :)

**Review by jonasfranz — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
