### PR TITLE
Update index doc

### PR DESCRIPTION
**Pull request by CaiCandong**
In the previous feature description, numerous functionalities of Gitea were listed, which appeared redundant and failed to highlight the unique characteristics of Gitea. Therefore, I have rewritten this section based on the description provided on the official Gitea website

### CODE REVIEW

**Comment by silverwind** [comment]
There is a feature table somewhere in these docs, maybe also put a link to it.

**Comment by CaiCandong** [comment]
> There is a feature table somewhere in these docs, maybe also put a link to it.

https://docs.gitea.com/installation/comparison#general-features ?

**Review by techknowlogick — APPROVED** [review]
<3 Thanks so much!!!

**Review by denyskon — APPROVED** [review]
Thanks a lot! I can only check the English page, so I'd like another review from somebody who speaks Mandarin.

**Review by lunny — APPROVED** [review]

**Pull request merged**
