### PR TITLE
Do not allow commiting to protected branch from online editor

### PR DESCRIPTION
**Pull request by lafriks**
Fix issue #1498

### CODE REVIEW

**Comment by strk** [comment]
Could you please add a unit test for this too ?

**Comment by lafriks** [comment]
As there are no unittests for editor I dont think I have time to add them

**Comment by strk** [comment]
Unit tests are a great way to secure the time spent on fixing a bug. That time could be easily wasted if there's no test making sure nobody breaks again what you fixed.

**Comment by lafriks** [comment]
Yes, I know but as there are no integration tests yet, I don't see how I can implement them...

**Comment by strk** [comment]
See the integrations/ directory.
@typeless maybe you can add a README there to help people add tests ?

**Comment by typeless** [comment]
@strk `/integrations` is going to be replaced by https://github.com/go-gitea/gitea/pull/1290 soon. Please take a look.

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
#1290 is now merged. @lafriks do you want to give it a try?

**Comment by lafriks** [comment]
I will take a look

**Comment by lafriks** [comment]
Was not easy as there was no single authorized user integration test, so had to add quite many new stuff to integration tests. I did not want to introduce new dependency but in future it would probably be wise to replace my html parser to something like github.com/PuerkitoBio/goquery

**Comment by strk** [comment]
LGTM, thanks for the time you put into the tests !

**Pull request merged**
