### PR TITLE
fix calReleaseNumCommitsBehind (#24148)

### PR DESCRIPTION
**Pull request by oliverpool**
Backport #24148

`repoCtx.CommitsCount` is not reliably the commit count of the default branch (Repository.GetCommitsCount depends on what is currently displayed).

_contributed in the context of @forgejo_

### CODE REVIEW

**Comment by oliverpool** [comment]
There were merge conflicts in the test cases, which I manually resolved (I could also drop them all if you prefer).

**Review by silverwind — APPROVED** [review]

**Comment by yardenshoham** [comment]
Gonna do a quick label test here

**Comment by yardenshoham** [comment]
Ok done

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
.

**Comment by silverwind** [comment]
.

**Pull request merged**
