### PR TITLE
Open result repository on search enter

### PR DESCRIPTION
**Pull request by aceArt-GmbH**
image
Pressing enter on search opens the first result. This allows for faster navigation without any mouse involvement.  
I could add a focus ring to the first element to indicate this new behavior.

### CODE REVIEW

**Comment by silverwind** [comment]
I think the feature also needs the up and down arrow keys be able to move this selection.

You could indicate a selection via something like border. It should be subtle.

```css
border-left: 2px solid var(--color-primary);
padding-left: calc(1em - 2px);
```

image

**Comment by aceArt-GmbH** [comment]
> I think the feature also needs the up and down arrow keys be able to move this selection.

I did not intend this PR to make the UI totally keyboard driven. I am not even sure how to capture the arrow keys without changing behavior on the rest of the page.
Normally the page should be navigated using the <kbd>tab</kbd> key.

> You could indicate a selection via something like border. It should be subtle.

I am not sure if this is subtle enough to just indicated the onEnter.

I could also just add this logic to `footer.tmpl` on our instance

**Comment by aceArt-GmbH** [comment]
>Also please make it so the feature only becomes active when at least 1 character has been typed into the search box.

Why this?

@silverwind I updated according to your suggestion

**Comment by silverwind** [comment]
> Why this?

Because the input element has autofocus and if someone accidentially hits enter, they might go somewhere they did not intend to go to.

> I am not sure if this is subtle enough to just indicated the onEnter.

I think border is probably not too good looking, probably should slightly alter background color.

**Comment by aceArt-GmbH** [comment]
image
I added a small outline, just like the normal tab focus outline would be

>Also please make it so the feature only becomes active when at least 1 character has been typed into the search box.
Added it

**Comment by aceArt-GmbH** [comment]
Is there any interest in this feature or rather not? :upside_down_face:

**Pull request closed without merging**
