### PR TITLE
fix bug on status API

### PR DESCRIPTION
**Pull request by lunny**
This will fix bug caused by #1332

### CODE REVIEW

**Comment by strk** [comment]
How about adding a testcase for this ? Presence of such test would have prevented this break ...

**Comment by bkcsoft** [comment]
Adding a test-cast for the rest of the commands would be fairly simple yes.

**Comment by bkcsoft** [comment]
but otherwise LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
