### PR TITLE
Use on/trigger event

### PR DESCRIPTION
**Pull request by yp05327**

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I think it's correct 👍

**Comment by lunny** [comment]
> What's the benefit?

`on` could work on those dynamiclly added elements but `click` not.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
> > What's the benefit?
> 
> `on` could work on those dynamiclly added elements but `click` not.

No, that would only go for delegated listeners which these are not.

Still I think it's a good change and we should probably install [this eslint rule](https://github.com/wikimedia/eslint-plugin-no-jquery/blob/master/docs/rules/no-event-shorthand.md) later to eliminate all such cases.

**Comment by silverwind** [comment]
Actually I think that eslint plugin can come later. Adding new plugin is a bit of a more  involved task as each rule needs to be evalutated etc.

**Review by silverwind — APPROVED** [review]

**Comment by yp05327** [comment]
@silverwind 
Try adding it in https://github.com/go-gitea/gitea/pull/24198

**Comment by yp05327** [comment]
Change to draft as I think we need to fix all lint error in https://github.com/go-gitea/gitea/pull/24198

**Comment by silverwind** [comment]
Let's continue in https://github.com/go-gitea/gitea/pull/24198, it's more thorough and does the same.

**Pull request closed without merging**
