### PR TITLE
 Make Clone in VSCode link get updated correctly (#21225)

### LINKED ISSUE #21224: The js-clone-url-vsc element is located below the script
### Description

So this part is useless

https://github.com/go-gitea/gitea/blob/main/templates/repo/clone_script.tmpl#L25
https://github.com/go-gitea/gitea/blob/main/templates/repo/home.tmpl#L129

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

gentoo

### How are you running Gitea?

systemd

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Backport #21225, fix for #21128 (also in 1.17.3), close #21224

The indent was incorrect before, so this PR did some formatting work. 

Bypass Golang's template bug for JS string interpolation. And since there are JS lint rules for templates, so the string interpolation is also a must.

[Compare with ignoring white spaces](https://github.com/go-gitea/gitea/pull/21226/files?diff=unified&w=1)

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Any reference to mentioned Golang bug?

**Comment by wxiaoguang** [comment]
> Any reference to mentioned Golang bug?

Now here it is: `https://github.com/golang/go/issues/55341`

**Comment by silverwind** [comment]
Thanks, we should definitely remove this script and move this localStorage setting to backend database, then we will no longer need inline scripts and the headaches they bring.

**Comment by tyroneyeh** [comment]
If it's a go bug, why is there no problem with v1.18?

**Comment by wxiaoguang** [comment]
> If it's a go bug, why is there no problem with v1.18?

Because Gitea 1.18 doesn't use string interpolation, there is no lint rule for templates, and the code has been tested carefully.

But when it's backported to 1.17-dev, the lint rule in 1.17 forced to use string interpolation, then no one tested it, then bug occurs.

**Comment by wxiaoguang** [comment]
bot

**Pull request merged**
