### PR TITLE
[Vendor] Update go-version to v1.2.4

### LINKED ISSUE #13067: Gitea fails to start with git 2.29.0.rc0.261.g7178c9af9c
- Gitea version (or commit ref): [`Gitea version 1.13.0+dev-743-ge0b772780 built with GNU Make 4.3, go1.15.2 : bindata, sqlite, sqlite_unlock_notify`](https://github.com/go-gitea/gitea/commit/e0b772780)
- Git version: `2.29.0.rc0.261.g7178c9af9c`
- Operating system: Arch Linux and Fedora 33
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist:
```log
Oct 07 19:24:10 nebula gitea[27964]: 2020/10/07 19:24:10 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 27964
Oct 07 19:24:10 nebula gitea[27964]: 2020/10/07 19:24:10 ...s/setting/setting.go:804:NewContext() [I] Default UI Location is Europe/Vienna
Oct 07 19:24:10 nebula gitea[27964]: 2020/10/07 19:24:10 ...dules/setting/git.go:68:newGit() [F] Failed to initialize Git settings%!(EXTRA *log.ColoredValue=Git version missing: Malformed version: 2.29.0.rc0.261.g7178c9af9c)
Oct 07 19:24:10 nebula systemd[1]: gitea.service: Main process exited, code=exited, status=1/FAILURE
```

## Description
Gitea fails to start after a recent update, I suppose the reason might be an error in parsing of the git version string, as it recently moved on to an rc for `2.29.0` (see git version above) and changed the format a little - note the added `rc0`.
A rollback to an earlier version of git (`git version 2.28.0.788.g542b3c2573` - which has been working just fine before) as well as to a previous release version (such as `2.28.0`) solves this for me momentarily and Gitea starts without issues.

### PR DESCRIPTION
**Pull request by 6543**
* github.com/6543/go-version v1.2.3 -> v1.2.4

close #13067

### CODE REVIEW

**Review by techknowlogick — COMMENTED** [review]
Could you add some tests? To either Gitea or the library itself?

**Comment by 6543** [comment]
@techknowlogick -> https://github.com/6543/go-version/actions/runs/309663485

**Comment by 6543** [comment]
@techknowlogick https://github.com/6543/go-version/pull/2/files#diff-2e0e5f9157b8e88ebe27e98732cd70b20a2ab48d5946caaa6788a7742ce4c45f

**Review by techknowlogick — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
🚀

**Comment by lafriks** [comment]
please send backport

**Comment by 6543** [comment]
Backport -> #13172

**Pull request merged**
