### PR TITLE
Integrate templates into bindata optionally

### PR DESCRIPTION
**Pull request by tboerger**
I have created this pull request to get early feedback. To finish this PR I still need to figure out how we can use the embedded templates for the mailer. Looks like the used macaron.TemplateSet doesn't like bindata.

Partially obsoletes https://github.com/go-gitea/gitea/pull/74.

### CODE REVIEW

**Comment by lunny** [comment]
Why not just use `template` but `templates`, two directories named template are strange.

**Comment by tboerger** [comment]
@lunny as said, it's work in progress. If we want to add the func map into the same package I can do that in the end

**Comment by strk** [comment]
It looks like custom templates are not used when building with `bindata` tag.

Tried with `custom/templates/home.tmpl` (used by `gitea` only when built with no `bindata` tag)

**Comment by tboerger** [comment]
> It looks like custom templates are not used when building with bindata tag

Looks like that, but nothing we can fix within Gitea as it seems to be an issue of https://github.com/go-macaron/bindata

**Comment by tboerger** [comment]
The mail templates are always overwritable as we do it manually to read the templates.

**Comment by strk** [comment]
If I read it correctly TemplateFileSystem allows you to define
an handler, so I guess a custom handler might implement the custom
directory seek.

**Comment by metalmatze** [comment]
Not tested but the code:
LGTM

**Comment by bkcsoft** [comment]
code LGTM

**Pull request merged**
