### PR TITLE
Fix WORK_DIR for docker (root) image

### LINKED ISSUE #25726: Docker image not using the `/data` volume for `actions_log` and `packages`
### Description

Hi, and thanks for gitea. I especially love the new gitea actions!

I've noticed I can't look at old gitea actions logs. The HTTP request fails with the following HTTP body (status 500):
```
storage open "w-flo/[..]/27/39.log": open /app/gitea/data/actions_log/w-flo/[..]/27/39.log: no such file or directory
```

And indeed that is expected, because my docker container only has a persistent `/data/` volume like the gitea docs recommend, everything else will be dropped along with the container itself when I upgrade gitea.

I could probably set a `PATH` for `[storage.actions_log]`, or preferably `[storage]`, in app.ini, but I'd say the docker image should be configured to store actions logs in `/data` by default, along with everything else that should be stored permanently?

I have noticed previously that avatars go missing on a regular basis, so maybe avatars are not stored in `/data` either. Looking at the possible app.ini keys, maybe packages and attachments are affected as well? Edit: I have checked the container file system, and indeed the /app/gitea/data contains packages, avatars, attachments etc. (but I haven't used these features a lot so I hadn't noticed in the past years). So it's not only about actions_logs.

Repositories and issue trackers are not lost on docker upgrade though, as I have manually set `[database] PATH` and `[repository] ROOT` in app.ini. These should probably default to something inside /data as well if that is not the case already.

If the issue is that I should have changed something in app.ini to `/data`, I think it would be great to mention that in the "[Installation with Docker](https://docs.gitea.com/next/installation/install-with-docker)" documentation.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Official docker image through docker-compose, with some modifications to app.ini (not through environment variables, directly in the file on the volume)

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #25726 

#17846 chose an incorrect WORK_DIR path for docker root image.

Gitea's work-path was already used as the base path for various paths (like AppDataPath), so, the work-path should be mounted to a volume in a docker image.

Now, for docker root image, it's unavoidable to mix the WorkPath/CustomPath/AppDataPath in the same directory ("/data/gitea"), because some of them have already been mixed.

Some directories in the screenshot are for "CustomPath" , while others are for "AppDataPath", due to the technical debts in old code:

```
CUSTOM_PATH="/data/gitea"
APP_DATA_PATH = /data/gitea
```

<details>

image

</details>

This PR is breaking but this is the only way at the moment to avoid users losing their data accidently

### CODE REVIEW

**Comment by wolfogre** [comment]
Actually, I don't think it's really breaking. It's for docker only, and it's almost impossible for anyone to mount `/app/gitea` because of `GITEA="/app/gitea/gitea"`. So

- If there is any data in `/app/gitea`, this PR will lose it.
- Even without this PR, the data will be lost because it's not mounted.

**Review by wolfogre — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Thank you for your reviewing.

Let's wait for enough days before merging, to see whether there are more ideas/concerns about this problem.

🙏

**Comment by silverwind** [comment]
"Breaking" section is missing

**Comment by wxiaoguang** [comment]
> "Breaking" section is missing

Nothing need to do. https://github.com/go-gitea/gitea/pull/25738#issuecomment-1624789284

**Comment by silverwind** [comment]
Ok then let's remove the label.

**Pull request merged**
