### PR TITLE
Several fixes for mobile UI (#25634)

### PR DESCRIPTION
**Pull request by denyskon**
Backport #25634 

Resolves https://github.com/go-gitea/gitea/issues/25622

<details>
<summary>Screenshots</summary>

Bildschirmfoto vom 2023-07-02
20-47-34
Bildschirmfoto vom 2023-07-02
20-47-45
Bildschirmfoto vom 2023-07-02
20-48-37
Bildschirmfoto vom 2023-07-02
20-49-08
Bildschirmfoto vom 2023-07-02
20-50-28
Bildschirmfoto vom 2023-07-02
20-51-46
Bildschirmfoto vom 2023-07-02
20-54-12

</details>

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Wait for https://github.com/go-gitea/gitea/issues/25693#issuecomment-1621749350

**Review by silverwind — CHANGES_REQUESTED** [review]
Resolve https://github.com/go-gitea/gitea/issues/25693 first and then include the same fix here.

**Comment by denyskon** [comment]
@silverwind I included the fix from #25710

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
waiting for @silverwind before merge :)

**Review by silverwind — APPROVED** [review]

**Pull request merged**
