### PR TITLE
Add class to page content to unify top margin

### PR DESCRIPTION
**Pull request by silverwind**
Previously pages would individually set this margin but some didn't so content would stick to the header without any space. Resolve this by adding a new class that is added on all pages. The only place where we remove this margin again is on the pages with menu or wrapper in the header.

Before:
Screen Shot 2020-11-30 at 20 43 12

After:
Screen Shot 2020-11-30 at 20 43 06

### CODE REVIEW

**Comment by zeripath** [comment]
it's a shame to have to change so many files. Is there really no way to use CSS selectors to do this?

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Not really, the pages use various classes for the root content element which makes them hard to consistently target for things like this.

**Comment by silverwind** [comment]
I do believe it's possible with CSS selectors but I also think such a class is generally useful to have and might come in handy for the future.

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
