### PR TITLE
Vendor Update

### PR DESCRIPTION
**Pull request by 6543**
created by `grep 'git' go.mod | grep '\.com' | grep -v indirect  | grep -v replace | cut -f 2 | cut -d ' ' -f 1 | while read line; do go get -u "$line"; make vendor; git add .; git commit -S -m "update $line"; done`

### CODE REVIEW

**Comment by zeripath** [comment]
Looks like there is a change in one of the underlying packages meaning that the error code has changed:

```
469	        	            	-The email address is invalid.
388s
470	        	            	+Email address is not a valid email address.
388s
```

**Comment by 6543** [comment]
1746186fb93c4d055c905f437758d9342c5b70d6 caused it ...

**Comment by zeripath** [comment]
I think you just have to skip that one - unless you can work out why that would happen.

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
A note about bleve though: https://twitter.com/blevesearch/status/1401558497335156740 the 2.0.5 release is an emergency release due to a breaking upstream dependency of theirs that needed to be resolved.

**Comment by 6543** [comment]
@techknowlogick yes noticed, we are affected by this too ...

**Comment by 6543** [comment]
@KN4CK3R will send a pull specific for that, this pull only bump dependencys

**Review by a1012112796 — APPROVED** [review]

**Pull request merged**
