### PR TITLE
Backport: Fix double-generation of scratch token (#6833)

### PR DESCRIPTION
**Pull request by SagePtr**
Backport #6833

### CODE REVIEW

**Comment by lafriks** [comment]
0 changed files? :/

**Comment by lafriks** [comment]
Could it be that 1.8 is not affected

**Comment by SagePtr** [comment]
Whoops, looks like i pushed a wrong branch)

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
That's better :)

**Review by adelowo — APPROVED** [review]

**Pull request merged**
