### PR TITLE
Use Request.URL.RequestURI() for fcgi

### LINKED ISSUE #14312: Empty URI in logs when using fcgi protocol
- Gitea version (or commit ref): 1.13.1
- Git version: 2.26.2
- Operating system: Official Docker image; gitea/gitea:1.13.1
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
```
[Macaron] 2021-01-12 10:00:58: Started GET  for xxx.xxx.xxx.xxx
[Macaron] [Static] Serving /serviceworker.js
[Macaron] 2021-01-12 10:00:58: Completed GET  304 Not Modified in 479.996µs
[Macaron] 2021-01-12 10:00:58: Completed GET  304 Not Modified in 479.996µs
[Macaron] 2021-01-12 10:00:58: Started GET  for xxx.xxx.xxx.xxx
[Macaron] 2021-01-12 10:00:58: Started GET  for xxx.xxx.xxx.xxx
[Macaron] 2021-01-12 10:00:58: Completed GET  200 OK in 3.775066ms
[Macaron] 2021-01-12 10:00:58: Completed GET  200 OK in 3.775066ms
```

## Description

When using `PROTOCOL = fcgi`, request paths(`http.Request.RequestURI`) are not shown in the logs.

Go's `net/http/cgi.RequestFromMap()`, which `net/http/fcgi` uses, does not populate `RequestURI`(but does `URL`). As `RequestURI` [is documented](https://golang.org/pkg/net/http/#Request) "Usually the URL field should be used instead", `req.URL.RequestURI()` may be a simple and recommended alternative.

https://github.com/go-gitea/gitea/blob/9659808172b0d33a79eca44e37cabaf33fbf1b8b/routers/routes/chi.go#L89
https://github.com/go-gitea/gitea/blob/9659808172b0d33a79eca44e37cabaf33fbf1b8b/routers/routes/chi.go#L96

## Screenshots

None

### PR DESCRIPTION
**Pull request by WKBae**
Closes #14312

Since #9473, new usages of `Request.RequestURI` seems to have added, which yields empty string on fcgi protocol.
This commit rewrites current usages of `Request.RequestURI` to `Request.URL.RequestURI()`.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by bagasme — COMMENTED** [review]
Where are mentions to fcgi in this diff?

**Comment by Meano** [comment]
> Where are mentions to fcgi in this diff?

The server configured with fcgi cannot get any avatar / repo-avatar since v13.0 (returned 404), because `routers/routes/chi.go routers/routes/chi.go : storagehandeler() : req.RequestURI` is empty.

**Comment by lunny** [comment]
> > Where are mentions to fcgi in this diff?
> 
> The server configured with fcgi cannot get any avatar / repo-avatar since v13.0 (returned 404), because `routers/routes/chi.go routers/routes/chi.go : storagehandeler() : req.RequestURI` is empty.

It's v1.14 and the master branch. v1.13 hasn't introduce chi

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Comment by zeripath** [comment]
please send backport

**Pull request merged**
