### PR TITLE
Extract header and footer content to separate templates

### PR DESCRIPTION
**Pull request by lukasbestle**
This change makes it easier to customize the header and footer content. Before this change, the whole header and footer had to be overridden, including the meta, style and script tags.

Apart from moving the code to separate files, there are no other changes to the templates in this PR.

### CODE REVIEW

**Comment by techknowlogick** [comment]
There is a PR #4651 that is pending a merge that will likely require changes to be made in this PR

**Comment by lukasbestle** [comment]
Thanks for letting me know. If my change is accepted, I'm happy to rebase it so that you can merge it directly. :)

**Comment by lafriks** [comment]
@lukasbestle please resolve conflict

**Comment by lukasbestle** [comment]
Done :)

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
