### PR TITLE
Revert "Show View at this point in history for every commit (#29122)"

### LINKED ISSUE #30098: View at this point in history is 404 in wiki revisions page
### Description

- access:
https://try.gitea.io/yp05327/longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong/wiki/Home?action=_revision
- click the button:
image
- you will see 404 page
image

maybe we need to hide this button in wiki page?

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix  #30098

### CODE REVIEW

**Comment by zokkis** [comment]
Why should this be reverted and not fixed?

**Comment by wxiaoguang** [comment]
> Why should this be reverted and not fixed?

At the moment, a complete fix needs more time, and "wiki" doesn't support such "file view at history point".

To make it easier to backport for 1.22, this is a quick fix IMO

**Comment by zokkis** [comment]
> > Why should this be reverted and not fixed?
> 
> Quote my comment from #29122 :
> 
> > Actually I have a question for this change: if there is no `FileName`, why it should show a link to the commit? The commit link is already shown in the second column. If I understand correctly, `View at this point in history` is only for viewing a "file", but not a "commit". I think the change 29122 is not right.
> 
> At the moment, a complete fix for "wiki" needs more time, and "wiki" doesn't support such "file view at history point". So even if you could check it is a wiki, no link could be used.
> 
> To make it easier to backport for 1.22, this is a quick fix IMO

The button does a similar thing as a click on "sha1" column
image

On the sha1 click you see the commit but with `View at this point in history` you see the repo at this commit 

So the absolute best and also a easy fix is to check for wiki and then dont show the link
So the feature is not reverted and the bug is fixed

**Comment by wxiaoguang** [comment]
I do not understand why there should be a duplicate button on the UI.

The commit sha is already in the second column, so I do not think it is right to add one more button in the last column.

**Comment by wxiaoguang** [comment]
Hmm, sorry, I think I can see the point now. Will propose a new one.

**Comment by wxiaoguang** [comment]
Sorry for my misundestanding and sorry for bothering, the new PR: -> https://github.com/go-gitea/gitea/pull/30297/files?diff=split&w=1

**Pull request closed without merging**
