### PR TITLE
Small UI fixes on full width form titles

### PR DESCRIPTION
**Pull request by joubertredrat**
Small fixed with center title, as below
gogs-title-before
gogs-title-after

### CODE REVIEW

**Comment by andreynering** [comment]
LGTM

**Comment by lunny** [comment]
OK. Beacause we rename master to release-branch.gitea0.9, so this PR was closed automatically. You can send it to release-branch.gitea0.9 again.

**Comment by tboerger** [comment]
This is targetted to master, i have reopened the develop one.

**Comment by joubertredrat** [comment]
:+1:

**Pull request closed without merging**
