### PR TITLE
feat: add support for a credentials chain for minio access

### PR DESCRIPTION
**Pull request by bohde**
We wanted to be able to use the IAM role provided by the EC2 instance metadata in order to access S3 via the Minio configuration. To do this, a new credentials chain is added that will check the following locations for credentials when an access key is not provided. In priority order, they are:

1. MINIO_ prefixed environment variables
2. AWS_ prefixed environment variables
3. a minio credentials file
4. an aws credentials file
5. EC2 instance metadata

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
Thanks! Would you be able to add this to the documentation (app.ini example and config cheatsheet) as well? (the body of the PR is more than suitable to be used)

**Comment by bohde** [comment]
I updated the en-us config cheatsheet and app.ini example to document the changes in minio credentials logic. I don't know how to translate this for the zh-cn config cheatsheet. Is there a process for translating these?

**Review by delvh — APPROVED** [review]
Regarding the zh-CN:
 Nope, unfortunately not yet.

**Comment by lunny** [comment]
Can we have a test?

**Comment by bohde** [comment]
I added a test that verifies correct credentials are pulled from all of the possible credential providers in the chain.

**Pull request merged**
