### PR TITLE
Fix golint to new URL

### PR DESCRIPTION
**Pull request by lafriks**
Will fix drone builds

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by adelowo — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lafriks I think the built in github review required check doesn't account for non-mergers

**Comment by lafriks** [comment]
Yeah, seems so... I stiil can merge tho as owner :D

Update: disabled github built in aproval check

**Comment by lunny** [comment]
@lafriks why disabled github built-in approvals check?

**Comment by techknowlogick** [comment]
@lunny because it only works if the person has write access, so @adelowo's apprval didn't count.

**Pull request merged**
