### PR TITLE
Added deletion of an empty line at the end of the file (#4050)

### LINKED ISSUE #4050: Gitea shows an extra non-existing blank line at the end of every file
- Gitea version (or commit ref): 1.4.1 and 2eabf18 (try.gitea.io)
- Git version: 1.4.1 built with: bindata, sqlite
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (example URL in description)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When viewing any file in the repository, it shows an extra, blank line at the end that shouldn't be there. When using the web editor to change the file, the additional blank line is also there. 

## Example
On GitLab the file is shown **correctly**, with 3 lines:
https://gitlab.com/higan/higan/blob/master/.gitignore
```
1  higan/profile/WonderSwan.sys/internal.ram
2  higan/profile/WonderSwan Color.sys/internal.ram
3  docs_build/
```

But on Gitea, the same file is shown **incorrectly** with 4 lines:
https://try.gitea.io/giteauser/example/src/branch/master/.gitignore
```
1  higan/profile/WonderSwan.sys/internal.ram
2  higan/profile/WonderSwan Color.sys/internal.ram
3  docs_build/
4
```

If you clone the repo from Gitea and open the file in vim, it correctly has 3 lines:
```
  1 higan/profile/WonderSwan.sys/internal.ram
  2 higan/profile/WonderSwan Color.sys/internal.ram
  3 docs_build/
~
~
```

### PR DESCRIPTION
**Pull request by axifive**
fix #4050
Now the same viewing behavior as the GitHub.

While viewing:

While editing:

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by jonasfranz — APPROVED** [review]

**Comment by jonasfranz** [comment]
@lunny I think this issue is more an enhancement then a bug.

**Comment by lunny** [comment]
@JonasFranzDEV I don't think so. see 
```Go
lines := strings.Split(fileContent, "\n")
```
And assume we have a file 
```ini
a = b\n
c = d\n
```
This will always output 3 lines, because we used `strings.Split` but in fact there are only 2 lines. see https://play.golang.org/p/AnU7W3inKz4

**Comment by lunny** [comment]
@axifive please send a backport PR to relase/v1.4

**Pull request merged**
