### PR TITLE
Require codereview to have content

### LINKED ISSUE #18151: Incorrect nested webUI when submitting an empty inline review within a PR
### Gitea Version

1.15.8/1.16

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When you start a review associated with a PR, if you select a line-number and "start review" the vast majority of the Gitea WebUI is reproduced causing layout issues. **The key point is "submitting an empty comment" (or trigger some other errors).**

https://try.gitea.io/eeyrjmr/test_issues/pulls/2/files

Steps to reproduce

1. Start a PR
2. view PR 
3. View PR files
4. click blue + on one of the  lines 
5. keep content empty, click green start review UI button
6. error message:  "Content cannot be empty."

### PR DESCRIPTION
**Pull request by Gusted**
- Report a validityError when the codeReview have no comment.
- Resolves #18151

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Could we introduce a util function like `validateTextareaNonEmpty(form, textarea)`? 

Then the wiki editor and the comment editor all can benefit from this function:

```js
if (!validateTextareaNonEmpty(...)) {
    return;
}
```

And we can leave only one copy of the comment why `validateTextareaNonEmpty` is needed beside `validateTextareaNonEmpty`.

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by wxiaoguang** [comment]
It seems not correct for Wiki editor.

We need to stop the event from being processed. eg: `preventDefault` or `return false` in jQuery.

I would propose a new PR to fix it.

**Comment by wxiaoguang** [comment]
Please help to review

* #18161

**Pull request merged**
