### PR TITLE
Gitignore and license list update

### LINKED ISSUE #46: Use github gitignore list
What do you guys think about just using the gitignore list provided by github? You can see the full list here: https://github.com/github/gitignore

### PR DESCRIPTION
**Pull request by tboerger**
I have integrated the gitignore template list of github that you can find at https://github.com/github/gitignore and I have updated the license list a little bit opinionated based on https://spdx.org/licenses/. Additionally I have regenerated the bindata.

Fixes #46.

### CODE REVIEW

**Comment by lunny** [comment]
Why not use a submodule reference to github.com/github/gitignore ?

**Comment by tboerger** [comment]
> Why not use a submodule reference to github.com/github/gitignore ?

If you prefer that i can do that, but in that case I have to update the selector as well as all the github gitignore templates got a .gitignore suffix.

**Comment by lunny** [comment]
A gitignore file could have no  extension name or .gitignore extension name(no extension file has higher priority). We can change code and keep it compatible with old versions. And I think using a submodule, we could save more time on copying the files to this project.

**Comment by tboerger** [comment]
As you can see at https://github.com/github/gitignore github uses totally different file names like we are doing. So there are 2 options.

1. Keep it like I have done it now
2. Use ```git subtree``` to merge github's templates directly in and patch the gitignore fetcher to remove the ```.gitignore``` suffix

**Comment by Xe** [comment]
LGTM as is. Would be nice to have a script to automate the cloning of the gitignores.

**Comment by sapk** [comment]
May be a simple sub-repo it can be updated by git process ?

**Comment by tboerger** [comment]
When i have more time i will update the pull request based on subtree and i will patch the gitignore selector.

**Comment by tboerger** [comment]
I have updated the pull request and I decided against the submodule integration to avoid thousands of commits polluting out history and to avoid refactoring all pieces of the gitignore selector just to get rid of a file extension like ```.gitignore``` and a subfolder called ```Global```.

From my side it's fine to merge it like it is!

**Comment by tboerger** [comment]
@lunny @makhov fine to merge now? :)

**Comment by lunny** [comment]
And how to keep update the ignore list and license?

**Comment by tboerger** [comment]
Do you want to have some script for that? I don't know how often we need to update it.

**Comment by lunny** [comment]
I think we can merge it now. @makhov @fuxiaohei

**Comment by tboerger** [comment]
So I'm merging that now as @lunny said on gitter it can be merged :)

**Pull request merged**
