### PR TITLE
Abort synchronization from LDAP source if there is some error.

### PR DESCRIPTION
**Pull request by davidsvantesson**
If there is some error retrieving entries from LDAP source, the processing shall skip this LDAP source and continue to next. If receiving an empty list of users from LDAP, they will still be deactivated.

Related to #7949 (not confirmed if this is the issue described there!)

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]

**Comment by lafriks** [comment]
Please send backport to release/1.9 branch

**Comment by aravindhsampath** [comment]
I have not tested a build with this commit, but my issue - #7949 is not addressed by this.
> If receiving an empty list of users from LDAP, they will still be deactivated.
I dont understand this logic. If Gitea receives an empty list from LDAP how can it assume that ALL users are to be de-activated? 
Shouldn't Gitea de-activate users ONLY if it is certain that LDAP says that they are infact de-activated? In my mid, an empty list from LDAP should lead to Gitea doing _nothing_

**Comment by lafriks** [comment]
@aravindhsampath gitea receives filtered out list of users (for example only users in specific groups). If all users are removed from that group they should be deactivated in gitea

**Comment by aravindhsampath** [comment]
@lafriks I commented on this issue at the thread from my issue. 
[https://github.com/go-gitea/gitea/issues/7949#issuecomment-524661109](https://github.com/go-gitea/gitea/issues/7949#issuecomment-524661109)

It is somehow possible to have a working LDAP source and still get a response that can make Gitea wrongly believe that there are no active users .

**Pull request merged**
