### PR TITLE
Use caddy's certmagic library for extensible/robust ACME handling

### PR DESCRIPTION
**Pull request by techknowlogick**
Also bumps minimum required version of go.

By using [certmagic](https://github.com/caddyserver/certmagic) we can use the same ACME library that Caddy uses. This also allows us to increase the number of ACME challenges that we can run. This PR adds TLSAPLN challenge, but in a later PR could be extended to use DNS challenges.

Additional things that could be added in a later PR are storing certs using different storage managers (such as minio, or redis).

### CODE REVIEW

**Comment by lafriks** [comment]
How would you use it on docker/k8s?

**Comment by techknowlogick** [comment]
> How would you use it on docker/k8s?

In k8s you would use cert-manager to request LE certs, but for standard docker installs you'd set it up as before with `-p 443:3000 -p 80:3080` assuming you have the `redirect_port` setup to be 3080

**Comment by lafriks** [comment]
> > How would you use it on docker/k8s?
> 
> In k8s you would use cert-manager to request LE certs, but for standard docker installs you'd set it up as before with `-p 443:3000 -p 80:3080` assuming you have the `redirect_port` setup to be 3080

Nevermind, I somehow thought you moved out letsencrypt to other command 😅

**Comment by zeripath** [comment]
OK, so this seems great except:

* it adds a whole DNS implementation
* and another logging framework (zap)

likely other things too in the >400 files changed.

Now I think we could reasonably drop modules/log and switch to Zap and consider using the DNS implementation elsewhere for things like libravatar but we should be careful we're not adding way too much code here.

**Comment by techknowlogick** [comment]
[libdns](https://github.com/libdns/libdns) is a library for working with APIs of various DNS providers (for updating DNS records for the DNS-01 ACME challenge), so not for resolving anything. In terms of adding too much code, I agree. I'd prefer if zap weren't included at all, but most of the other code added is either golang.org/x/net/... and golang.org/x/crypto/... It sucks because technically zap isn't being used at all, as certmagic doesn't log unless it is passed the logger.

**Review by zeripath — APPROVED** [review]
I think we have to approve - it might be reasonable in future to provide a build tag that removes this functionality to reduce and remove these dependencies.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
