### PR TITLE
Mark TemplateLoading error as "UnprocessableEntity" (#19445)

### LINKED ISSUE #19399: Internal Server error returned when doing a POST at /v1/user/repos with invalid data
### Description

While doing some fuzzing using https://github.com/Endava/cats I discovered an issue for the `/v1/user/repos` endpoint. Doing a POST with invalid data results in a 500, rather that something more meaningful.

You can reproduce the issue using (just replace $token with your own token):

`cats replay Test245.json`

[Test245.json.zip](https://github.com/go-gitea/gitea/files/8484397/Test245.json.zip)

Or using the following payload:

```json
{
  "auto_init": true,
  "template": true,
  "issue_labels": "eEitLJaqLAv8GH",
  "license": "EJ4mZaqiB",
  "private": true,
  "trust_model": "default",
  "gitignores": "PnCQ60J8mksk8",
  "name": "L6fxpx",
  "description": "16udnqV6IumI",
  "default_branch": "J7ysZ6klvPLAP1G",
  "readme": "xN9l4LLHnL",
  "catsFuzzyField": "catsFuzzyField"
}

```

### Gitea Version

1.17.0+dev-423-g4396d0e7c

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using https://try.gitea.io/.

### Database

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- Backport #19445
  - Don't return Internal Server error if the user provide incorrect label template, instead return UnprocessableEntity.
  - Resolves #19399

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by delvh — COMMENTED** [review]
LGTM if it would work, which it currently doesn't, see CI.

**Review by wxiaoguang — APPROVED** [review]

**Comment by Gusted** [comment]
Fixed CI error

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
CI failure is related.

**Comment by Gusted** [comment]
> CI failure is related.

Ehm which CI failure?

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:point_up: docker failed because of this outdated dependency ?!? ... upgraded

**Pull request merged**
