### PR TITLE
tests: configure github remaining limit + read token

### PR DESCRIPTION
**Pull request by sapk**
In order to not trigger API limits in CI,

This is a simple configuration to not failed when we have 3 running jobs of unit-test in parallel for CI.

~We should also provide a github key (I think I have the rights to do it) with minimum permission to increase the limit and not have to wait.~ Done!

### CODE REVIEW

**Comment by sapk** [comment]
This doesn't work we already are over API rates. I think I could create a function to refresh api rate before.

**Comment by sapk** [comment]
Another improvement, could also to call RefreshRate if rate is nil  in sleep function.

**Comment by sapk** [comment]
While other jobs aren't filtering it will still keep failing when they consume the full api rate in  parallel.

**Review by zeripath — APPROVED** [review]

**Comment by sapk** [comment]
Now the test use GITHUB_READ_TOKEN env variable as access token (empty by default)

**Comment by sapk** [comment]
I added github_read_token (user https://github.com/gitea-test with only read email) to drone

**Review by guillep2k — APPROVED** [review]

**Comment by sapk** [comment]
I have merged #9796 before this one to re-validate that it passed with the token will others are failing.

**Comment by sapk** [comment]
Now CI failed for an other reason on sqlite test ... It will never end :smile:

**Review by 6543 — APPROVED** [review]
nice !

**Comment by 6543** [comment]
and it passed :+1:

**Pull request merged**
