### PR TITLE
[Branch View] Delete Table Header

### PR DESCRIPTION
**Pull request by 6543**
part of PR https://github.com/go-gitea/gitea/pull/7520
and issue https://github.com/go-gitea/gitea/issues/7454

conflict with https://github.com/go-gitea/gitea/pull/7604 depending wich pull is merged first the other will be updated

# Before:

# After:

### CODE REVIEW

**Comment by 6543** [comment]
[The Header Isnt Usefull anymore if with PR https://github.com/go-gitea/gitea/pull/7602 because buttons  show what they will do if you click them]

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
because of https://github.com/go-gitea/gitea/pull/7622/commits/2f1581fb35014c4322eeccc900d6224390f16c03 can we set a fixed size for a table column ?

**Comment by 6543** [comment]
@zeripath ready to merge :rocket:

**Comment by 6543** [comment]
# Before:

# After:

**Pull request merged**
