### PR TITLE
add XSLT to specialLanguages

### PR DESCRIPTION
**Pull request by silverwind**
It's a subset of XML that should not be treated as being code for the language stats.

### CODE REVIEW

**Review by CirnoT — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by lafriks** [comment]
Isn't it already in XML group?

**Review by lafriks — APPROVED** [review]

**Comment by CirnoT** [comment]
Yeah @lafriks groups are kinda weird in that way, it seems it's more for SCSS/CSS or Twig/HTML cases rather than XSLT and XML, which is weird.

**Comment by silverwind** [comment]
FWIW, the file I noticed this with has a `.xml` extension and it's a WSDL specification. Checking GitHub, they also seem to exclude those ([example](https://github.com/forcedotcom/wsdl)).

**Comment by lafriks** [comment]
@silverwind could you add also WSDL?

**Comment by silverwind** [comment]
Where can I find the exact supported values? The addition of `XSLT` was more of a wild guess but it worked.

**Comment by zeripath** [comment]
XSLT is actually a programming language - I'm not certain that it's just XML.

**Comment by silverwind** [comment]
Actually, I can not reproduce the XSLT detection now with a bunch of WSDLs on try:

https://try.gitea.io/silverwind/xslt-test/src/branch/master/spec/fixtures

Might be something else in the repo, need to test more. Don't land yet.

**Comment by silverwind** [comment]
Found the source, it's a vendored copy of https://github.com/tomi-vanek/wsdl-viewer which GitHub also identifies as XSLT so I think it should not be actually included but the file marked as `linguist-vendored` (once we support that) to exclude from stats. WSDL seems to correctly identify as XML already, so I don't think there's anything to do.

**Pull request closed without merging**
