### PR TITLE
UI: Make document body a flexbox

### LINKED ISSUE #6118: Site footer isn't fixed on commits graph page
- Gitea version: master
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Open https://try.gitea.io/swoldemi/NervBot/graph and scroll down the page. The site footer scrolls with page content.

## Screenshots

https://imgur.com/7aj2xdL

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/6118

Also got rid of `@footer-margin` which added 40px padding on bottom of some pages. Did that in the parent instead, so now the graph page also has some needed padding at the bottom.

### CODE REVIEW

**Comment by lafriks** [comment]
Did you check on ie11?

**Comment by silverwind** [comment]
Not yet, but Firefox, Chrome and Safari all look well.

**Comment by silverwind** [comment]
IE11 appears to affected by some kind of [flexbug](https://github.com/philipwalton/flexbugs), not sure. Somehow `flex: 1` has no effect on `.full.height` and the footer floats.

What's the plan for IE11? I dropped support in most of my projects, maybe we can too?

**Comment by silverwind** [comment]
Removing `flex: 1` and giving the footer a explicit height of `40px` appears to solve it on IE11, so weird.

**Comment by lafriks** [comment]
I think we still should support IE11 as that is latest IE version

**Comment by silverwind** [comment]
IE 11 fixed and rebased. This should be ready to review.

**Review by lafriks — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Pull request merged**
