### PR TITLE
Remove x/net/context vendor by using std package

### PR DESCRIPTION
**Pull request by sapk**
This PR update 
- github.com/markbates/goth
- github.com/blevesearch/bleve
- golang.org/x/oauth2

To remove the unneeded vendor x/net/context since Go1.7.

~This PR is still in WIP since it wait for an other PR on golang.org/x/oauth2. https://github.com/golang/oauth2/pull/339~

### CODE REVIEW

**Comment by techknowlogick** [comment]
@sapk can you link to PR that is blocking this in golang.org/x/oauth2?

**Comment by sapk** [comment]
@techknowlogick https://github.com/golang/oauth2/pull/339

**Comment by techknowlogick** [comment]
Thanks @sapk

**Review by techknowlogick — APPROVED** [review]

**Comment by sapk** [comment]
There is still x/net/context in vendor since I found that x/net/context/ctxhttp is use at one (and only) point in x/oauth2. I will try to push the fix to oauth2 as it not really needed to use ctxhttp for it. 
Still this PR could be merge as it still update deps that were using x/net/context and will ease the process for the next.

**Review by adelowo — APPROVED** [review]

**Comment by lunny** [comment]
conflicted

**Comment by sapk** [comment]
@lunny I rebased on master. It should be good.

**Pull request merged**
