### PR TITLE
Don't stack PR tab menu on small screens

### PR DESCRIPTION
**Pull request by sebastian-sauer**
the stacking takes up screen space - display the tabs as the navigation bar. github uses the same layout.

Screenshots (left before, right after):

image image

Large screen:

image

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by denyskon — CHANGES_REQUESTED** [review]
Could you please do it in the CSS file? https://github.com/go-gitea/gitea/blob/be23b73e8523738a1d3c214a01c0f162146da1c0/web_src/css/repo.css#L750

**Comment by sebastian-sauer** [comment]
> Could you please do it in the CSS file? https://github.com/go-gitea/gitea/blob/be23b73e8523738a1d3c214a01c0f162146da1c0/web_src/css/repo.css#L750

sorry - not sure what I should do in the CSS file?

**Comment by denyskon** [comment]
Please set 
```css
overflow-x: auto;
overflow-y: hidden;
```
inside the existing CSS class for `.pull.tabular.menu` instead of adding helper classes. They are a good idea if there is no existing class for an element or if it is using a generalized class, but if there is already a class for the element, it is cleaner to use it.

**Comment by wxiaoguang** [comment]
I am afraid this change is not right on desktop view.

IIRC the "bottom line" of the menu would be broken

**Comment by sebastian-sauer** [comment]
> 

Good catch - i've now added a divider below and fixed layout for large screens.

Screenshots in PR description are updated.

**Review by denyskon — APPROVED** [review]
Looks good now in both mobile and desktop view :+1:

**Review by lunny — APPROVED** [review]

**Pull request merged**
