### PR TITLE
Have the default 'all' rule just build

### PR DESCRIPTION
**Pull request by strk**
Clean and test are saner being seperate targets

### CODE REVIEW

**Comment by thibaultmeyer** [comment]
I agree, the rule `all` mustn't clean compiled files. LGTM

**Comment by tboerger** [comment]
I personally also expect clean build and test. That's for me the meaning of all

**Comment by strk** [comment]
GNU Coding Standard suggests using "all" for just build:
https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets

Also the GNU Make manual:
https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html#Standard-Targets

All the software I ever built with a Makefile had
a default "make" invocation build but not test.

Surely would have not filed this PR if what happened on running `make`
wasn't unexpected to me.

What do others think about it ?

**Comment by thibaultmeyer** [comment]
A good Makefile **must** print "Nothing to be done..." the second time `make` was invoked with success.

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
