### PR TITLE
Allow spaces in username for LDAP users

### PR DESCRIPTION
**Pull request by jochenrill**
PR #342 was only partially applied. Spaces should not be at the start
and end of a username but they can be inside.

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
Why we allow a username with a space in the middle of the word?

**Comment by jochenrill** [comment]
Because it is allowed by the specification and Microsoft uses it:
https://msdn.microsoft.com/en-us/library/aa366101(v=vs.85).aspx

**Comment by ethantkoenig** [comment]
Shouldn't we add a check for leading/trailing spaces, since those are disallowed?

**Comment by lafriks** [comment]
@ethantkoenig is right. Best solution should be just to trim spaces for entered username

**Comment by jochenrill** [comment]
Space at the begining and end are already being trimed (models/login_source.go) and triming them inside the username would be wrong. Suppose I wanted to bind to CN=Jeff Smith,OU=Sales,DC=Fabrikam,DC=COM (which is a valid Windows CN), I would like be able to configure cn=%s,OU=Sales,DC=Fabrikam,DC=COM as bind dn.

**Comment by lafriks** [comment]
No I meant only at the begining and end. If they are already trimmed than all is good

**Comment by lunny** [comment]
LGTM

**Pull request merged**
