### PR TITLE
Remove unnecessary IssueList attribute loads

### PR DESCRIPTION
**Pull request by ethantkoenig**
`IssueList.loadAttributes()` loads attachments and comments, but these fields are rarely used for lists of issues. This PR updates `IssueList.loadAttributes()` to load everything except attachments and comments, and add separate methods for explicitly loading attachments/comments.

### CODE REVIEW

**Comment by lunny** [comment]
@ethantkoenig if any place which reference LoadAttributes really needs comments or attachments?

**Comment by ethantkoenig** [comment]
@lunny Only in `models/issue_indexer.go` (which needs comments), and I've added a call to `LoadComments(..)` there

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Pull request merged**
