### PR TITLE
Bump playwright to 1.26.1

### PR DESCRIPTION
**Pull request by kdumontnu**
Potentially addresses https://github.com/go-gitea/gitea/issues/21355

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
I wonder whether this `browser` object is really needed or if one can just use only `page`.

**Review by silverwind — APPROVED** [review]
Dependency bump is good to have on its own.

**Comment by wxiaoguang** [comment]
The `browser` is not related to this problem. The problem here is firefox can not call `newPage` (even without the browser, the test framework still need to call newPage to open a new page for test).

Just a guess: I can see a suspicious error log `Sandbox: thread-synchronized seccomp failed: Unknown error 524`, so I suspect that this problem is caused by host docker's seccomp policy. Firefox needs to set seccomp+tsync, but it fails, then firefox crashes.

**Comment by wxiaoguang** [comment]
bot

**Pull request merged**
