### PR TITLE
Show callstack backstraces for 'Internal Server Error 500

### PR DESCRIPTION
**Pull request by typeless**
It would save time for debugging.

### CODE REVIEW

**Comment by lunny** [comment]
But maybe only when debug mode?

**Comment by sapk** [comment]
LGTM but like @lunny I would prefer (not mandatory if other people don't want it) in debug mode only since I don't expect to have stacktrace in normal (info) log.

Have you try to display information return by debug.PrintStack() and if it respect how the rest of the logs are output normally? It would be the biggest point to specifing to debug and not disturb production where anyone would want to catch 500 but analyzing it in testing.

**Comment by typeless** [comment]
@sapk Yes, I have tried it for debugging the 500 error on my local machine. It doesn't mess up other  other logs (I mean like how kernel log interfere with application log. Broken formatting ..etc.). It's literally like what a Go `panic` would display.

**Comment by lunny** [comment]
Or maybe a config item could disable it.

**Comment by typeless** [comment]
@lunny The PR's primary purpose is for those scenarios where the bug report is not informative enough when reported from the end-users. For developers who intend to look into the problem by themselves, adding that line doesn't add much effort. So I don't expect it to be as useful as being enabled in production mode.

That said, I can try to add a switch for it if it doesn't introduce too many changes.

**Comment by lunny** [comment]
I mean keep it open default and end-user could disable it. This is not against your idea.

**Comment by typeless** [comment]
I think the usefulness of the PR doesn't warrant the extra complexity after just having handled a real 500 error just a moment ago 😆 . So I will back off the PR for now. If I am proved wrong again, it's not too hard to try this again.

**Pull request closed without merging**
