### PR TITLE
apply exclude label on milestone issue list

### PR DESCRIPTION
**Pull request by ghost**
Peek 2019-10-29 22-59

This also improve icon position (before image)

Screenshot_2019-10-29_22-58-07

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by jolheiser — CHANGES_REQUESTED** [review]
What is `__debug.bin`?

**Comment by jaqra** [comment]
@jolheiser  omg. i am done with this __debug.bin file. Its created by vscode on debug. Can i add it on gitignore in another pr?

i am going to delete it

**Comment by jolheiser** [comment]
> @jolheiser omg. i am done with this __debug.bin file. Its created by vscode on debug. Can i add it on gitignore in another pr?
> 
> i am going to delete it

There is a line in the `.gitignore` for VSCode, so you could certainly add it to that section in another PR

**Comment by jaqra** [comment]
@jolheiser done, removed. ok i will add

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
