### PR TITLE
Move license.txt to misc and update reserved usernames/known entries

### PR DESCRIPTION
**Pull request by silverwind**
- Move license.txt from /js to /misc
- Update reserved usernames to match public entries
- Update list of known public entries for bindata router

I hope this is the last time we need to change the reserved usernames and we can put all new files in /misc/.

### CODE REVIEW

**Comment by silverwind** [comment]
Removed the `public/fonts` directory which also frees up the reserved username name "fonts".

**Review by zeripath — COMMENTED** [review]
We really should avoid creating more reserved user names. Is there really no way of using what we already have without making misc reserved? I can easily imagine that someone already has an organisation called misc. 

We cannot just keep adding to these lists and need to consider if we can actually reduce the size of these lists considerably.

**Comment by silverwind** [comment]
Could move everything to a single subdirectory like `public/assets` served as `/assets` which would free up everything except names `assets` and `serviceworker.js`.

**Review by 6543 — APPROVED** [review]
...

**Comment by zeripath** [comment]
Yeah I think putting it in assets would be better - tbh we could move more out to that that would be better.

This reserved-usernames stuff annoys me - it's really not hard to structure urls in such a way that this isn't necessary. For example we should have structured our urls as "~owner/reponame" instead of "owner/reponame" and then a lot of things would have been easier overall and/or enforced that names had to start with a letter and not an underscore and then we could have all of our stuff start with an underscore.

I guess we could prefix all of our stuff with a ! and/or consider a move to prefixed tilde in future.

Sigh.

**Review by 6543 — COMMENTED** [review]
yes if we use 'assets' we wont have a next reserved username

and i like the refactor done at https://github.com/go-gitea/gitea/pull/11872/files#diff-46259196476f860fea33754fcb22e9eeR917

**Comment by silverwind** [comment]
I think "assets" isn't so bad. Another option may be "static" which would fit a bit better with the existing `STATIC_URL_PREFIX` option.

**Comment by silverwind** [comment]
Moving to a assets directory will be more work and may require breaking changes. I'll open another PR with just the `KnownEntries` change which is still valuable.

**Pull request closed without merging**
