### PR TITLE
Fix setting.AppPath for integration tests

### LINKED ISSUE #1910: Integrations.test is erroneously used as the hook in pre-receive.d of a forked repo in integration testing
- Gitea version (or commit ref):
v1.1.0-289-g9ddc35e

- Git version:
2.7.4

- Operating system:
Ubuntu 16.04 64bit

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Under the environment created by integrations.test, a forked repo will contain a hook which looks like the following:
```
cat /tmp/repo1.git/hooks/pre-receive.d/gitea
#!/usr/bin/env bash
"/home/mura/devel/go/src/code.gitea.io/gitea/integrations.test" hook --config='/home/mura/devel/go/src/code.gitea.io/gitea/integrations/sqlite.ini' pre-receive
```

For some clues I've found so far: 
https://github.com/go-gitea/gitea/blob/master/models/repo.go#L946
https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L510
...

P.S. The problem can be reproduced with https://github.com/go-gitea/gitea/pull/1912

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #1910.

@typeless, please confirm this fixes the issue.

### CODE REVIEW

**Comment by lunny** [comment]
@ethantkoenig It seems it's not fixed.

**Comment by ethantkoenig** [comment]
@lunny How so? When I run with my changes locally, I get the following hook in `hooks/pre-receive.d/gitea`:

```
#!/usr/bin/env bash
"/home/ethantkoenig/.gopath/src/code.gitea.io/gitea/gitea" hook --config='integrations/mysql.ini' pre-receive
```

**Comment by ethantkoenig** [comment]
Fix so that the `--config` flag is given as an absolute path; now `hooks/pre-receive.d/gitea` is

```
#!/usr/bin/env bash
"/home/ethantkoenig/.gopath/src/code.gitea.io/gitea/gitea" hook --config='/home/ethantkoenig/.gopath/src/code.gitea.io/gitea/integrations/mysql.ini' pre-receive
```

**Comment by typeless** [comment]
@ethantkoenig It doesn't seem to work.

```
 ~/w/go/code.gitea.io/gitea  ⑂ pr1923 +    ./tt.sh PullMerge
2017/06/10 12:15:55 [T] Custom path: /Users/mura/w/go/code.gitea.io/gitea/custom
2017/06/10 12:15:55 [T] Log path: /Users/mura/w/go/code.gitea.io/gitea/log
2017/06/10 12:15:55 [I] Gitea v
=== RUN   TestPullMerge
[Macaron] 2017-06-10 12:15:55: Started GET  for 
[Macaron] 2017-06-10 12:15:55: Completed  200 OK in 3.314036ms
[Macaron] 2017-06-10 12:15:55: Started POST  for 
[Macaron] 2017-06-10 12:15:55: Completed  302 Found in 28.692161ms
[Macaron] 2017-06-10 12:15:55: Started GET  for 
2017/06/10 12:15:55 [...ules/context/repo.go:209 func1()] [E] GetRepositoryByName: repository redirect does not exist [uid: 1, name: repo1]
[Macaron] 2017-06-10 12:15:55: Completed  404 Not Found in 6.389829ms
[Macaron] 2017-06-10 12:15:55: Started GET  for 
[Macaron] 2017-06-10 12:15:55: Completed  200 OK in 183.768102ms
[Macaron] 2017-06-10 12:15:55: Started GET  for 
[Macaron] 2017-06-10 12:15:55: Completed  200 OK in 4.063705ms
[Macaron] 2017-06-10 12:15:55: Started POST  for 
[Macaron] 2017-06-10 12:15:55: Completed  302 Found in 103.904046ms
[Macaron] 2017-06-10 12:15:55: Started GET  for 
[Macaron] 2017-06-10 12:15:55: Completed  200 OK in 207.495342ms
[Macaron] 2017-06-10 12:15:55: Started GET  for 
[Macaron] 2017-06-10 12:15:56: Completed  200 OK in 207.359152ms
[Macaron] 2017-06-10 12:15:56: Started POST  for 
[Macaron] 2017-06-10 12:15:56: Completed  200 OK in 351.53824ms
[Macaron] 2017-06-10 12:15:56: Started GET  for 
[Macaron] 2017-06-10 12:15:56: Completed  200 OK in 163.403833ms
--- FAIL: TestPullMerge (1.28s)
        Error Trace:    editor_test.go:137
			pull_merge_test.go:13
	Error:  	Not equal: 
			expected: 302
			received: 200
		
        Error Trace:    editor_test.go:144
			pull_merge_test.go:13
	Error:  	Not equal: 
			expected: "Hello, World (Edited)\n"
			received: "# repo1\n\nDescription for repo1"
		
FAIL
 ~/w/go/code.gitea.io/gitea  ⑂ pr1923 +    git log
commit 9029aafb885f90defd12c4e1f900300540ce9dbf
Author: Mura Li <mura_li@castech.com.tw>
Date:   Tue Jun 6 17:25:37 2017 +0800

    Add integration test for pull-request merge

commit 23d0735f906498ca273b7cac399e9c8f0a0f08e8
Author: Ethan Koenig <ethantkoenig@gmail.com>
Date:   Fri Jun 9 22:27:13 2017 -0400

    Absolute path for setting.CustomConf

commit e9b1b908ee7c5b0722f6bce51aef4519990fae0b
Author: Ethan Koenig <ethantkoenig@gmail.com>
Date:   Fri Jun 9 14:13:46 2017 -0400

    Fix setting.AppPath for integration tests
```

**Comment by ethantkoenig** [comment]
@typeless I said it fixed #1910, not #1912 :smile:

**Comment by ethantkoenig** [comment]
But #1912 passes for me when I run it locally with these changes

**Comment by typeless** [comment]
@ethantkoenig Did you have a built gitea binary in $GITEA_ROOT?

**Comment by ethantkoenig** [comment]
@typeless Yes, that is the point of the `$GITEA_ROOT` variable

**Comment by typeless** [comment]
@ethantkoenig Nice. Then I can confirm the problem has been fixed as well. 👍

**Comment by typeless** [comment]
By the way, IIRC the `path` package handles only slashes (mainly for URLs) and Windows paths are not supported. You might have to use `filepath` instead.

**Comment by lunny** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
make LG-TM work

**Pull request merged**
