### PR TITLE
update latest xorm version to vendor

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by lafriks** [comment]
@lunny drone fails

**Comment by lunny** [comment]
@lafriks could you help me? don't know what's wrong with my govendor.

**Comment by sapk** [comment]
@lunny I suspect that you have a different EOL than the one on linux. So, when computing hash it doesn't come to the same result. There is an issue on govendor : https://github.com/kardianos/govendor/issues/129#issuecomment-270008849

I will try to generate the hash today and give them to you if anyone haven't done it yet.

**Comment by lafriks** [comment]
@lunny @sapk I just pushed commit with correct hashes to this PR

**Comment by lafriks** [comment]
LGTM (if I'm allowed to do that :) )

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
