### PR TITLE
Sqlite supports memory database for test purpose

### PR DESCRIPTION
**Pull request by lunny**
To make tests run faster, allow sqlite's PATH as a `:memory:` which means run sqlite memory-only. The data will disappear when Gitea or Gitea test exit.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
> It is not right to use `:memory:`

ref from https://github.com/mattn/go-sqlite3?tab=readme-ov-file#faq

image

**Comment by wxiaoguang** [comment]
`cache=shared` is a must if you use `:memory:`, but `cache=shared` is also highly discouraged:  https://www.sqlite.org/sharedcache.html

I do not see real benefits to play with them.

**Comment by lunny** [comment]
> `cache=shared` is a must if you use `:memory:`, but `cache=shared` is also highly discouraged: [sqlite.org/sharedcache.html](https://www.sqlite.org/sharedcache.html)
> 
> I do not see real benefits to play with them.

I think this is the only method to use memory because memory cannot be used with WAL. https://sqlite.org/forum/info/a44bddd65750d084

**Comment by wxiaoguang** [comment]
But the sqlite tests are fast enough, I do not think these tricks would save more minutes.

The slowest test is still mysql

**Comment by lunny** [comment]
And I think we already used `:memory:` in our unit test.

https://github.com/go-gitea/gitea/blob/5d57c287fb5ce2f5da82d75ed7837758701d5b1e/models/unittest/testdb.go#L206

But I think you are right. SQLite test is not the bottleneck of tests. So I will close this pull request.

**Comment by wxiaoguang** [comment]
> And I think we already used `:memory:` in our unit test.

That's different. Other test uses the same connection pool.

But migration tests create 2 isolated connection pools, that's why it's difficult to play tricks with it.

**Pull request closed without merging**
