### PR TITLE
Add myself to MAINTAINERS

### PR DESCRIPTION
**Pull request by ethantkoenig**
:grinning:

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@ethantkoenig You have to send to all repos. :)

**Comment by Bwko** [comment]
@ethantkoenig First of all: great job on all the unit test :smile:! Second: you need to join the go-gitea/develop channel to become a [maintainer ](https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#maintainers)

**Comment by ethantkoenig** [comment]
@Bwko joined

**Comment by JetpackDuba** [comment]
Congrats! Thanks for your effort adding features and fixing bugs! 👍

**Pull request merged**
