### PR TITLE
add changelog for v1.10.5 (#10628)

### PR DESCRIPTION
**Pull request by lunny**
forward port for #10628

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Should we remove the related BUGFIXES from changelog 1.11.2?

**Comment by zeripath** [comment]
(I suspect not)

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
make lg-tm work

**Comment by zeripath** [comment]
LGTM work?!

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
Ping lgtm

**Pull request merged**
