### PR TITLE
Fix swagger errors

### LINKED ISSUE #4010: API fails swagger validation
Either I'm doing something wrong or the API (as of d94472e) is not currently emitting swagger-compliant JSON. This is causing problems when trying to use various parsers and client generators/libraries to create gitea clients, as they try to validate when parsing.  The error messages I'm getting vary by library, but as a simple check, try this:

<pre>
$ curl https://try.gitea.io/swagger.v1.json > swagger.v1.json 
$ npm install -g swagger-cli
$ swagger-cli validate swagger.v1.json 
Swagger schema validation failed. 
  Missing required property: description at #/responses/parameterBodies
 
JSON_OBJECT_VALIDATION_FAILED
</pre>

I've tried other parsers and validators, both CLI and online, and get different errors; still trying to figure out if there's any common denominator other than PEBCAK.  Anyone else seeing this?

### LINKED ISSUE #4088: Add `swagger validate` to drone run
Once we get the swagger validation errors cleaned up in #4010, we'll want to add a test case to keep them that way:

<pre>
swagger validate public/swagger.v1.json
</pre>

Background:  Various swagger clients try to validate at startup; when validation breaks, the clients break.  In my own case, we need working clients to be able to migrate to gitea from legacy systems, and we'll continue to need them for daily ops after that.

### PR DESCRIPTION
**Pull request by sapk**
Fix all the resting errors to have a valid swagger file.

They are still some warnings but nothing blocking.

Doing so I found that some request still misses son parameters for some POST/PUT/PATCH request. This means the a client generated from the swagger file will not work completely. 

Fix #4088 by activating validation in drone
Should fix #4010.

### CODE REVIEW

**Comment by sapk** [comment]
Ping @stevegt, if it can confirm that it solve #4010 to be used by his cli.

**Comment by sapk** [comment]
This one could maybe be in 1.5 milestone since it is only comments editing and that it can help use/generate swagger client. If not it will need to be backport I think.

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by stevegt** [comment]
Totally awesome @sapk!  Thanks for the ping @bkcsoft!  I'm leaving a conference right now, headed for the airport.  Just pulled master so I can look while unplugged -- I was puzzling over the correct way to implement some of these fixes myself.  This lets me get back to working on client side this week; will publish repos as I go.  (/me is still in conference mode and can't remember if we already have a docs or other page for listing API clients...)

**Pull request merged**
