### PR TITLE
Sync latest translations from crowdin

### PR DESCRIPTION
**Pull request by lafriks**
Latest translations from CrowdIn

### CODE REVIEW

**Comment by lunny** [comment]
have you build the project before run update?

**Comment by lunny** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by lafriks** [comment]
@lunny I did not know I have rights to build crowdin project. Just proofreaded new translations and built project in crowdin. So these should be latest now

**Comment by lunny** [comment]
@lafriks you have the rights.

**Pull request merged**
