### PR TITLE
Set TLS minimum version to 1.2

### PR DESCRIPTION
**Pull request by zeripath**
Partial of #10602 

## Changes to TLS
Currently, Gitea allows TLS 1.0 and TLS 1.1 for HTTPS connections. These versions of TLS have long been deprecated due to security vulnerabilities, and are also no longer necessary for wide browser compatibility. The change I propose in this pull request sets TLS 1.2 as the minimum TLS version, with additional support for TLS 1.3.

On SSLLabs, we can see the difference. Before the changes:

Screen Shot 2020-03-04 at 9 46 22 AM

After the changes:

Screen Shot 2020-03-04 at 10 40 38 AM

Closes #10602 

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
Thanks for splitting up PR :)

**Review by 6543 — COMMENTED** [review]
do this is need a opt out? Via app.ini ?

**Comment by techknowlogick** [comment]
> do this is need a opt out?

As there is a way for users to use less secure way (reverse proxy in front of gitea configured with lower TLS version) I'm ok if we don't provide opt-out.

**Comment by 6543** [comment]
yes had that in mind too - just like to have a bit consent :)

**Review by 6543 — APPROVED** [review]
go secure :D

**Comment by lunny** [comment]
This is a breaking change we should mention on release notes.

**Pull request merged**
