### PR TITLE
Option to set default branch at repository creation

### LINKED ISSUE #9542: Feature request - changing default branch name
Right now, gitea always defaults to creating a `master` branch as the default, and the default can be changed per repo with a setting. It would be nice if we could change the default branch name so that new repos would be created with the given name, e.g. if you wanted to use `prod` instead of `master`.

### PR DESCRIPTION
**Pull request by zeripath**
Fix #9542

Also fixes bug whereby template repos without a master branch cannot be templated and master branch rather than the default branch will be templated.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### Repository Creation Screen
Screenshot from 2020-03-23 10-08-48

Leaving the new option blank will default to master

### Empty Repository Screen
Screenshot from 2020-03-23 10-10-07

Here the new empty repository has been created with the default branch called NotMaster. Note how the instructions have changed to suggest that the initial push is sent to NotMaster rather than master.

### Default Commit
Screenshot from 2020-03-23 10-11-14

A new repository created with the default branch called rabbit

### From a template
Screenshot from 2020-03-23 10-38-51

A new repository called testemplate was  created similar to the above - it was then marked as a template and the repository testcreate was created from it.

### Example of a bad default branch name
Screenshot from 2020-03-23 10-45-12

### CODE REVIEW

**Comment by mrsdizzie** [comment]
Could this be added to the `api/v1/repo/repo.go` repo create too?

**Comment by zeripath** [comment]
@mrsdizzie Done - Sorry I missed it.

**Review by mrsdizzie — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]
Requires `make generate-swagger`. Otherwise looks good to me.

**Comment by zeripath** [comment]
d'oh

**Pull request merged**
