### PR TITLE
Fix project counter in organization/individual profile

### LINKED ISSUE #28052: Project counter missing, again
### Description

After #26826, project counter at organization level is still missing

At repository level all counters are in place

### Screenshots

image

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

119

### PR DESCRIPTION
**Pull request by yp05327**
Fix #28052
Before:
image
image

After:
image
image

### CODE REVIEW

**Comment by JakobDev** [comment]
You should also add this to the API

**Comment by yp05327** [comment]
Which API do you mean?
In current design, we don't return these counters in API. 🤔

**Comment by JakobDev** [comment]
> In current design, we don't return these counters in API

Maybe we should add that. I think 3rd Party Apps should also be able to show this counter.

**Comment by yp05327** [comment]
Maybe we should do this in another PR? 
As we should add these counters in both user and org 's API, if it is necessary.
Then maybe we need to add some tests for this change.
So for a quick fix, this PR will only fix the frontend UI.

**Comment by yp05327** [comment]
Created an issue for this, let's do this later.

**Review by lunny — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

**Pull request merged**
