### PR TITLE
Avatar autogeneration fixed

### PR DESCRIPTION
**Pull request by pboguslawski**
This mod fixes problem with initial avatar autogeneration and
avatar autogneration after deleting previous avatar.

Related: https://github.com/go-gitea/gitea/issues/13159
Related: https://github.com/go-gitea/gitea/pull/13233
Fixes: 80a6b0f5bce15a641fc75f5f1ef6e42ef54424bc
Author-Change-Id: IB#1105243

### CODE REVIEW

**Comment by pboguslawski** [comment]
This PR is backport of

https://github.com/go-gitea/gitea/pull/13233#issuecomment-715489489

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by lafriks** [comment]
Please rebase with release branch

**Comment by pboguslawski** [comment]
According to [The Golden Rule of Rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing#the-golden-rule-of-rebasing) we do not rebase public branches. Just merged current release/v1.13 to this PR.

**Comment by lafriks** [comment]
please merge again or set option to allow contributors to change PR branch as it needs up to date with base branch to be mergable

**Comment by pboguslawski** [comment]
> please merge again

Just merged current release/v1.13 to this PR.

> or set option to allow contributors to change PR branch as it needs up to date with base branch to be mergable

I don't see option described on

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

in this PR. Please drop me hint if you'll need access to this PR.

**Comment by lafriks** [comment]
There should be checkbox when creating new PR, I have no idea how to change it later on ;)

**Pull request merged**
