### PR TITLE
Remove annoying difference in button heights.

### PR DESCRIPTION
**Pull request by SanPilot**
Why was that even there?

See before & after: http://imgur.com/a/yKdUR

### CODE REVIEW

**Comment by appleboy** [comment]
Please chage the `less` file not css.

**Comment by SanPilot** [comment]
Okay. Updated my pull request.

**Comment by appleboy** [comment]
@SanPilot Just change the less file. You don't need to change CSS file. Otherwise LGTM

**Review by appleboy — APPROVED** [review]

**Comment by SanPilot** [comment]
I'm a little confused; will less be compiled in ci?

**Comment by appleboy** [comment]
@SanPilot Your are right. 👍

**Comment by SanPilot** [comment]
Ok, I'll fix it in the morning.

**Comment by appleboy** [comment]
@SanPilot No. You don't need to change anything. I say you are right for `CI doesn't compile less file`

**Comment by lafriks** [comment]
Blue buttons height is still 1px too much, see:
attels

**Comment by sapk** [comment]
LGTM for at least have the same position. Like @lafriks show, blue buttons are larger than the url and can be fixed.

**Comment by silverwind** [comment]
Took a look at the CSS. It's not obvious what causes the different height and there are a number of padding hacks in place, especially for the clone bar. While the ideal solution would be to refactor the hacks to Semantic UI classes, a 7.5px padding on the buttons works on my screen.

**Comment by lunny** [comment]
@silverwind that maybe another PR. Let's merge this at first.

**Pull request merged**
