### PR TITLE
Fix usage of removed jqXHR.success

### LINKED ISSUE #11228: U2F doesn't work on gitea/gitea:latest docker image
- Gitea version (or commit ref): docker: gitea/gitea:latest
- Git version: n/a
- Client Operating system: Windows 10
- Client browser: Firefox and Edge
- Host OS: CentOS 7
- Host Docker version: Docker CE version 19.03.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
When I upgrade my docker container to the newest gitea release (gitea/gitea:latest) the yubikey authentication attempt causes the error attached. When I downgrade the gitea to 1.11.4 (gitea/gitea:1.11.4) the yubikey authentication works without issues.

## Screenshots
gitea_u2f_error

### PR DESCRIPTION
**Pull request by CirnoT**
Introduced by https://github.com/go-gitea/gitea/commit/b57a735e7739550ed4677af71c5eb0a8032a69f3 via removal of jQuery-Migrate.

This PR changes usage of `.success` on `jqXHR` to `.done`.

Fixes https://github.com/go-gitea/gitea/issues/11228 and few other places, such as removal of code comments.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@CirnoT I would not close #11311 since it contains refacot too

**Comment by 6543** [comment]
or should we send a new pull for refactor?

**Comment by lafriks** [comment]
It will conflict anyway

**Comment by lafriks** [comment]
But I removed closes part, refactor can be done anyway in other PR

**Comment by CirnoT** [comment]
#11311 is superseded by https://github.com/go-gitea/gitea/pull/9451 anyway (https://github.com/go-gitea/gitea/pull/11311#issuecomment-624862200), it was supposed to be only a fix until full Webauthn and its refactor is in place.

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Make lg-tm work

**Pull request merged**
