### PR TITLE
commithgraph / timeline

### PR DESCRIPTION
**Pull request by kjellkvinge**
Hi.

As mentioned in #410 - this is what I have so far. I do not have much experience with go and projects like gitea, so I will be happy for any comments and guidance :)

This patch contains functionality to:
-  gather data from the repo by running something like 'git log --graph --pretty=oneline -n 100'
- adds route to graph endpoint
- use js to draw the actual graph. (using gitgraph - https://github.com/bluef/gitgraph.js )

### CODE REVIEW

**Comment by bkcsoft** [comment]
`gitgraph.js` goes in `public/js/libs/` :)

**Comment by bkcsoft** [comment]
Could you make a benchmark-function for `models.GetCommitGraph`? I'm very interested in the performance impact of this...

**Comment by kjellkvinge** [comment]
Added benchmarktests. got these numbers on my laptop:

```
 BenchmarkGetCommitGraph-4   	2000000000	         0.04 ns/op 
 BenchmarkParseCommitString-4	2000000000	         0.00 ns/op
```

**Comment by bkcsoft** [comment]
Awesome, LGTM 🎉

**Comment by lunny** [comment]
@kjellkvinge Is this still wip ?

**Comment by lunny** [comment]
I think maybe it's not ready? I tested it and visit , it shows:
untitled

**Comment by kjellkvinge** [comment]
@lunny Yes, it is stil WIP. I would like to do the following tasks:

  *  [x] - link to the graph from somewhere, maybe in the "commits" section?
  *  [x] - test on windows.
  *  [x] - if there is a bug, fix it :)
  *  [x] - maybe link to branch, commit in the nodes?
  *  [x] - move the js, ref @bkcsoft comment.

In your example, did you get any errors? in the log, or in frontend (javascript console)?

Update:
tested on windows. Cant reproduce any bugs. @lunny Can you please let me know a bit about your system? and let me know if you see any errors in the javascript console?

kk

**Comment by Bwko** [comment]
@kjellkvinge It works/looks great. No errors whatsoever :smile: 
Maybe you could add a paginator?

**Comment by kjellkvinge** [comment]
@bwko thanks. Did you try running it on windows?

**Comment by Bwko** [comment]
Nope I only have Linux

**Comment by kjellkvinge** [comment]
Ok. I will borrow my kids computer and see if there is any bugs on windows.
I suspect splitting on "\n" could cause some problem. :)

**Comment by kjellkvinge** [comment]
I think I am done with this PR now. I cant find any bugs on my systems. I have tested on linux and windows.

kk

**Comment by Bwko** [comment]
Could you squash your commits? Put all the template related stuff into 1 commit. And squash commits like `Comment on func Graph()` & `Move js to from js/ js/libs/` & `Add route for graph`

**Comment by kjellkvinge** [comment]
@Bwko sure :)

**Comment by Bwko** [comment]
Could you squash it a little bit more? `Add router for graph` & `Add route for graph` could go into 1 commit.
 And `Add assets for graph` & `require assets for graph`.
 And `Link to graph from commits view` & `Add template for graph`

**Comment by kjellkvinge** [comment]
Yes. Thank you. Did not know how fine grained you wanted the commits. Is this ok?

**Comment by Bwko** [comment]
Yes :+1:  LGTM

**Comment by lunny** [comment]
Is this show correct? Safari on macOS
untitled

**Comment by Bwko** [comment]
@lunny on chrome it looks normal. Have you tried it on chrome?

**Comment by lunny** [comment]
Is this right? chrome on macOS
untitled

**Comment by Bwko** [comment]
@lunny Yes :)

**Comment by kjellkvinge** [comment]
That looks good. The previous screenshot seems to miss some details. Is it
always like this on that repo ( a clone of gitea perhaps?)

**Comment by Bwko** [comment]
@kjellkvinge Could you remove the empty ()?

**Comment by kjellkvinge** [comment]
Yes. I will do that. Also, I am think I should remove the link on user/email. I dont think that works. its only a bunch of links to 404's :grimacing:

**Comment by Bwko** [comment]
@kjellkvinge Thanks, removing the link to user/email makes sense

**Comment by thibaultmeyer** [comment]
@kjellkvinge

It could be nice if, like other pages, you resolve existing user accounts to use user profile fullname.  

I think too email dont have to be printed here.

**Comment by bkcsoft** [comment]
@kjellkvinge `draw.js` should still be in `public/js/draw.js` IMO :) otherwise LGTM

**Comment by kjellkvinge** [comment]
I made the following changes:

* moved `draw.js` to `public/js` @bkcsoft 
* removed empty () @Bwko 
* added underline on hover on commit links.
* removed email and link to user.

**Comment by lunny** [comment]
Thanks!

**Comment by kjellkvinge** [comment]
just a comment: I wrote an email to the author of the lib, gitgraph.js - He is very happy if his code can come to use in this project.

**Comment by lunny** [comment]
Great

**Comment by Misterke** [comment]
Am I the only one wanting to scroll down (much) more down than 100 commits (preferably dynamically loaded on-demand, but paging could perhaps be an easier way out)?

**Comment by kjellkvinge** [comment]
@Misterke probably not :) I suggest you make a new issue for this feature requst

**Pull request merged**
