### PR TITLE
Fix sys4 init script

### PR DESCRIPTION
**Pull request by strk**
Without this fix Gitea is attempted to be started with no argument

### CODE REVIEW

**Comment by lafriks** [comment]
This is duplicate of #2902

**Comment by strk** [comment]
#2902 is for 1.2 branch, this one is for master branch - please reopen

**Comment by lafriks** [comment]
In future please send backports only after PR has been reviewed and merged to master

**Comment by strk** [comment]
can I get some LGTM here please ?

**Comment by strk** [comment]
I've just tested and `setcap` call works on an ubuntu 17.04 machine.
It wasn't working in a Debian 6 though, thus this PR.

Maybe @MTecknology can help testing this ?

**Comment by tboerger** [comment]
Debian 6 is EOL, so I would vote to close this and the backport PR.

**Comment by MTecknology** [comment]
LGTM

**Comment by ghost** [comment]
I think this is already merged from different PR. This can be closed.

**Comment by techknowlogick** [comment]
Closing, please re-open & resolve conflicts if you still need the PR.

**Pull request closed without merging**
