### PR TITLE
Support relative paths to videos from Wiki pages

### PR DESCRIPTION
**Pull request by sergeyvfx**
This change fixes cases when a Wiki page refers to a video stored in the Wiki repository using relative path. It follows the similar case which has been already implemented for images.

Test plan:
- Create repository and Wiki page
- Clone the Wiki repository
- Add video to it, say `video.mp4`
- Modify the markdown file to refer to the video using `<video src="video.mp4">`
- Commit the Wiki page
- Observe that the video is properly displayed

### CODE REVIEW

**Comment by Mets3D** [comment]
I would really appreciate this getting merged. ReadMe pages can be a lot more attractive with some video embeds of use cases, and using absolute paths for those sucks big time, eg. when working on a branch. Thanks for the patch, Sergey.

**Comment by wxiaoguang** [comment]
I will take a look (resolve conflicts and improve and approve)

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Did some changes:

1. Make `video` function shares some logic from `img` and put them in a separate file to avoid bloating `html.go`
2. Use similar tests as `img` and add a case for "absolute path"

**Review by techknowlogick — APPROVED** [review]

**Comment by Mets3D** [comment]
Much appreciated, mate!

**Pull request merged**
