### PR TITLE
Update guideline and code for un-awaited promises

### PR DESCRIPTION
**Pull request by silverwind**
Been using this in other code and I think it's more clear than assigning to a unused variable.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Is there a lint rule for it? To catch misused promises.

**Review by yardenshoham — APPROVED** [review]

**Comment by silverwind** [comment]
> Is there a lint rule for it? To catch misused promises.

No, this is a hard topic for linters to solve. Typescript [can do it](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) and I would recommend us to eventually convert to it.

**Comment by wxiaoguang** [comment]
But, smart IDEs could help to detect it.


Your `// no await` comment doesn't make smart IDEs happy.

the `const _ = foo()` is more explicit.


image

**Comment by silverwind** [comment]
> But, smart IDEs could help to detect it.

Can you find out what triggers your editor there and whether we can use it? It might be a eslint rule that I'm not aware of yet.

**Comment by wxiaoguang** [comment]
It's called `JSIgnoredPromiseFromCall` in Goland (Intellij family)

image

**Comment by silverwind** [comment]
Ugh, that seems like something not runnable outside the editor. Does putting a `// eslint-disable-line` affect it? `// noinspection JSIgnoredPromiseFromCall` would I guess but it's specific to that editor.

**Comment by wxiaoguang** [comment]
> Does putting a `// eslint-disable-line` affect it?

Nope .... it's not controlled by `eslint-disable` family.

**Comment by wxiaoguang** [comment]
Actually, I think "assigning to a unused variable" is pretty clear: we do not want to use its Promise.

So could we just keep this rule?

**Comment by silverwind** [comment]
Hmm I don't think we can cater to such editor-only linters like that then. I guess if it's a big issue to you, we can keep the old style.

**Pull request closed without merging**
