### PR TITLE
Fix migration svg color

### PR DESCRIPTION
**Pull request by KN4CK3R**
The SVGs on the migration page inherit the current text color which created wrong icons.

Before:
grafik

After:
grafik

Possible alternative: `color: unset;`
@silverwind I don't know what is better in this case. `unset` works nice with themes but is still the wrong color.

### CODE REVIEW

**Comment by silverwind** [comment]
How does one get  this icon to show? I don't see it on https://try.gitea.io/repo/migrate.

**Comment by KN4CK3R** [comment]
It's in #16356. The original svg contains `fill="#000000"` but `make svg` strips the black fill because it is the default color.

**Comment by silverwind** [comment]
I see two options given that this icon needs to change color on dark themes:

```css
.migrate .card {
  color: var(--color-text);
}
```

or specifically override the icon to a different color:

```css
svg.gitea-onedev {
  fill: var(--color-secondary-dark-11);
}
```

**Comment by KN4CK3R** [comment]
Does it really "need" to change color on dark themes? If the icon is black it should be black with all themes or not? We do not adjust the git icon on orange themes.
An alternative would be to use `fill="#000001"` in the icon which does not get stripped.

**Comment by silverwind** [comment]
> Does it really "need" to change color on dark themes

I prefer to change it because it gives more contrast, even if it's not a original color anymore.

>  An alternative would be to use fill="#000001" in the icon which does not get stripped.

I'm sure there is a [svgo plugin](https://github.com/svg/svgo#built-in-plugins) to disable somewhere.

**Review by silverwind — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
