### PR TITLE
[CI] Use node v14 instead of node v16 untill it will pass again

### PR DESCRIPTION
**Pull request by 6543**
followup of  #16591

fix https://drone.gitea.io/go-gitea/gitea/42522/4/3

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
TBH if we're doing this we should really change to 1.14 full stop

**Comment by 6543** [comment]
hmm can do it ... then just go back to 1.14 until fix

**Comment by 6543** [comment]
@zeripath ajusted

**Review by silverwind — APPROVED** [review]
don't think we use any node 16 feature yet, so this should work.

**Pull request merged**
