### PR TITLE
Change the element layout of the installation page to improve the visual experience

### PR DESCRIPTION
**Pull request by kerwin612**
Comparison of page effects：
before:
截图 2023-08-04 11 19 57
after:
截图 2023-08-04 11 32 24

Comparison of partial effects：
before:
截图 2023-08-04 11 37 11
after:
截图 2023-08-04 11 35 14

**Aligns the layout of the other tip on the page, centering the ***CustomConfFile*** tip.**

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
It introduces another misalignment.

I'm sure you haven't tested this code block

image

**Comment by kerwin612** [comment]
> It introduces another misalignment.
> 
> I'm sure you haven't tested this code block
> 
> image

image

**Comment by wxiaoguang** [comment]
TBH, the new layout doesn't look good to me, it looks more strange than before .....

image

**Comment by kerwin612** [comment]
image
I am based on the overall layout of the page to think, based on the original page layout, **tip** is independent of the center, the **content** is right;

**Comment by kerwin612** [comment]
Before this PR, that is, Gitea is like this now: 
截图 2023-08-04 16 57 01
As for which one looks more comfortable/natural, leave it to gitea-team to judge.

**Comment by kerwin612** [comment]
Is there any feedback?

**Comment by wxiaoguang** [comment]
> As for which one looks more comfortable/natural, leave it to gitea-team to judge.

I also think the old layout looks more comfortable/natural.

To improve the "install" page, it needs a non-trivial refactoring. re-design the whole page's layout.

**Comment by denyskon** [comment]
Closing, as there seems to be no will for this change. Feel free to reopen if you have a different opinion

**Pull request closed without merging**
