### PR TITLE
Initial implementation of Keybindings

### PR DESCRIPTION
**Pull request by JakobDev**
This PR brings Keybindings to Gitea! You can bind a shortcut to a element with the new `keybinding-shortcut` attribute. I also added some of [GitHub's shortcuts](https://docs.github.com/en/get-started/using-github/keyboard-shortcuts) as example.

### CODE REVIEW

**Comment by silverwind** [comment]
Would suggest you use https://github.com/ccampbell/mousetrap to capture the key events. It has multiple benefits, for example it (by default) does not trigger keybinds while a `<input>` element is focused.

**Comment by JakobDev** [comment]
It looks like mousetrap is no longer maintained, but I can add a check for input elements into my own code

**Comment by silverwind** [comment]
It's stable, it does really not need maintainance. But there's also https://github.com/jaywcjlove/hotkeys which is very similar.

**Comment by JakobDev** [comment]
I use now hotkeys-js. Each lib my need some changes or bugfixes at some point in the future, so it's better to use a maintained one.

For anyone who wonders why I don't use the `hotkeys()` function: The Keybindings should be defined by a HTML attribute, to keep it as easy as possible for most things. Of course, this could also be done with the `hotkeys()` function, but this need a lot of binding and unbinding if something chnaged. This could cause problems, if somebody else want to use this lib in JavaScript code in the future. So I decided to use a `keydown` event combined with `hotkeys.getPressedKeyString()`. `hotkeys.getPressedKeyString()` has all benefits of the lib. If the User inputs texts in some Input field, it just returns a empty array.

**Comment by silverwind** [comment]
Using `hotkeys()` would make the code clearer, but it'd likely need detection when the target element is removed from the DOM, which is tricky. Though I do wonder if we could just gracefully ignore keybindings targeting non-existant elements, should definitely be possible.

**Comment by silverwind** [comment]
It may be necessary in the future to have some bindings work inside `input`,`textarea` and `select`. Ideally by defining an additional attribute on the target element. The method to allow these via `hotkeys.filter` seems very clumsy and unsuitable to me. So if we want that, I think we may be better off removing the dependency actually.

**Comment by JakobDev** [comment]
> So if we want that, I think we may be better off removing the dependency actually.

So I should return back to the old code and add a check if currently some input filed in focus?

**Comment by JakobDev** [comment]
This is currently death because of I got no answer how to process. If there is interest in this, I can open anew PR, which would be easier than solving the conflicts.

**Comment by denyskon** [comment]
@JakobDev I'll close this, and if you want you can open an issue for this feature idea not to be forgotten

**Comment by silverwind** [comment]
On topic, I recently found https://github.com/RobertWHurst/Keystrokes which seems like a modern and suitable keybinding library.

**Comment by JakobDev** [comment]
If there is interest in this (it don't looks like that) I can open a new PR. But keep in mind: If we use a library, we need to stick with it, as this library has some custom formats that may not be supported by another one.

**Comment by silverwind** [comment]
I think it's good that the library distinguises key sequences (`>`) from combos (`+`). Here is something to play with:

https://codesandbox.io/s/shy-cookies-zvrgcc?file=/src/index.js

You notice it will capture events when focus is inside the `<input>` too, so this is something we need to check via `document.activeElement`.

I'm generally favorable of having some keybindings, but really the only one I personally use on GitHub is the [Y shortcut](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files) on file view. Documenting these is also a challenge.

**Comment by silverwind** [comment]
Another possible contender: https://github.com/jamiebuilds/tinykeys. It does seem promising at least in the size department. I will soon attempt using one of these libs in another application of mine and then i should be able to give a recommendation, so maybe wait on that.

**Pull request closed without merging**
