### PR TITLE
Replace deprecated String.prototype.substr() with String.prototype.slice()

### PR DESCRIPTION
**Pull request by CommanderRoot**
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with the [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) method which works similarily but isn't deprecated.
substr() probably isn't going away anytime soon but it doesn't hurt to replace it as the change isn't difficult at all.

### CODE REVIEW

**Comment by lunny** [comment]
`web_src/fomantic/build/semantic.js` should not be changed directly?

**Comment by silverwind** [comment]
`web_src/fomantic/build/semantic.js` is vendored third-party code, please revert the changes there and possibly file a PR against https://github.com/fomantic/Fomantic-UI.

**Comment by CommanderRoot** [comment]
My apologies. I ignore the files in the vendor folder but didn't check if the other files are possibly vendored as well. I have now changed the commit to exclude the mentioned file

**Review by silverwind — APPROVED** [review]

**Review by Gusted — APPROVED** [review]

**Comment by silverwind** [comment]
CI failure is unrelated, maybe https://github.com/go-gitea/gitea/pull/18793 will resolve it.

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
