### PR TITLE
Fix http path bug

### PR DESCRIPTION
**Pull request by lunny**
Added some tests

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Could you add a test for a existing file with the name `test..txt` which should work?

**Review by KN4CK3R — APPROVED** [review]

**Comment by 6543** [comment]
-> #16120

**Comment by zeripath** [comment]
`path.Clean("/" + filepath.ToSlash(pth))[1:]` would have been simpler.

**Comment by lunny** [comment]
So should we support `/username/reponame/objects/info/a\b\c`?

**Comment by zeripath** [comment]
I don't think it really matters on linux - such refs would be invalid refs by git's standards so they'd return 404 in any case.

**Pull request merged**
