### PR TITLE
Forcibly clean and destroy the session on logout

### PR DESCRIPTION
**Pull request by zeripath**
Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
need backport

**Review by zeripath — COMMENTED** [review]
I think we also need to unset the `setting.SessionConfig.CookieName` cookie

**Comment by zeripath** [comment]
Ah I think I understand! 

We don't necessarily have to destroy the session completely.

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by lunny** [comment]
Please send backport to v1.11

**Pull request merged**
