### PR TITLE
Fix missed migration in #22235

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]
It's my fault too. So surprised that I didn't find it when I reviewed it.

**Review by KN4CK3R — APPROVED** [review]

**Comment by yardenshoham** [comment]
How does this affect v1.19.0?

**Comment by lunny** [comment]
Have no idea. Since `Sync` also do the same work. So people may not find the problem if they don't run tests.
Maybe we can have a doctor command to check all the database schema inconsistent problems and fix that?

**Comment by yardenshoham** [comment]
Is it possible to backport a migration?

**Comment by lunny** [comment]
> Is it possible to backport a migration?

Not yet.

**Comment by delvh** [comment]
Not a good idea.

**Comment by yardenshoham** [comment]
Will projects work in v1.19?

**Comment by lunny** [comment]
> Will projects work in v1.19?

I think yes except some bugs.

**Pull request merged**
