### PR TITLE
Add auto-expanding running actions step

### PR DESCRIPTION
**Pull request by bytedream**
Auto-expands the currently running action step.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
I think that's a feature some people will like but others will not like it. So a toggle/option may be needed.

**Comment by silverwind** [comment]
Seems alright to me, even with no opt-out as GitHub does this too.

**Comment by bytedream** [comment]
I got inspired from GitHub for this. Besides being nice in general (imo), this PR is a useful addition to action auto-scrolling (#30057) . With both merged, when the user opens a running action, it directly jumps to the latest output log, without the need of manually opening the currently running job step and scrolling down.

**Comment by silverwind** [comment]
I think this is a valuable feature to have, but I need to get around to testing it first as I don't have a persistent action runner in my dev environment yet, so it's always a bit of a pain to test actions.

**Comment by lunny** [comment]
> I think this is a valuable feature to have, but I need to get around to testing it first as I don't have a persistent action runner in my dev environment yet, so it's always a bit of a pain to test actions.

You can run a runner with docker in the same dev machine.
I have tested it locally and noticed it will only expand the first step but I haven't took into the code.

**Comment by wxiaoguang** [comment]
> I think that's a feature some people will like but others will not like it. So a toggle/option may be needed.

I could agree with it.



> when the user opens a running action, it directly jumps to the latest output log, without the need of manually opening the currently running job step and scrolling down.

The question is why users need to see the "latest output log" for a "running step".  Think about 2 cases:

* Case 1: all steps are done, end users do not need to expand any step to see details, because nothing interesting there.
* Case 2: a step is running, the user should already know that the step is running, if the step succeeds in the end, then it is case 1: end users do not need to see the logs if they do not care about the details at the moment.

So IMO case1 and case2 are similar: if a user is interested in some steps, they could expand the logs, otherwise no need to expand automatically.

**Comment by wxiaoguang** [comment]
Or maybe we could use local storage to introduce 2 lightweight config options: "always auto expand", "always auto scroll", then it could satisfy all users.

**Comment by wxiaoguang** [comment]
Now it should satisfy all users. @bytedream does it look good to you?

image

**Comment by bytedream** [comment]
@wxiaoguang looks good 👍 ty

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
