### PR TITLE
Fix import path of go-sdk

### PR DESCRIPTION
**Pull request by strk**
From code.gitea.io/go-sdk/gitea
  To code.gitea.io/sdk/gitea

Deprecates #140

### CODE REVIEW

**Comment by strk** [comment]
Should work once https://github.com/go-gitea/redirects/pull/5 is merged

**Comment by 0xbaadf00d** [comment]
OK, could you fully test when https://github.com/go-gitea/redirects/pull/5 will be merged?  if everything is OK, i close this PR

**Comment by thibaultmeyer** [comment]
go-gitea/redirects#5 is now merged.

**Comment by strk** [comment]
We need to wait for something (drone?) to update the website, which seemd to have failed:
https://drone.gitea.io/go-gitea/redirects/18

**Comment by thibaultmeyer** [comment]
Hmm yeah, drone fail to get access to docker...

**Comment by strk** [comment]
@tboerger set it up, I hope all owners have access to it. @lunny ?

**Comment by lunny** [comment]
LGTM

**Comment by thibaultmeyer** [comment]
LGTM

**Pull request merged**
