### PR TITLE
Commit Graph: Pull-Requests should not link to issues

### LINKED ISSUE #15730: Commit Graph: Pull-Requests should not link to issues
- Gitea version (or commit ref): 1.14.1

## Description

With Gitea 1.14.0 and #12766 the commit graph (`<repository-url>/graph`)  includes links to pull requests instead of the names of the ref's.

I like this change a lot, however I can't really use it, because my repositories use an external issue tracker.

The links associated with the pull requests are generated as: `<repository-url>/issues/<pr-id>`
The links would work if they were generated as: `<repository-url>/pulls/<pr-id>`

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #15730

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I understand there was an edge case this was supposed to fix but it caused another issue.
I am mirroring this repo.
Issue tracker is set to external and links to GH's issue tracker of this repo.
I disabled PR's for the repo since it's a mirror and that's no place to accept PR's.
PR links (since they were linking to issues) were being redirected the same way as issues were as an external issue tracker is set -> they redirected to GH PR links.
This is now broken and I  get linked to a 404 on my instance, because obviously the mirror doesn't have any PR's to show there, since a) PR's are disabled there and b) it's a mirror and yeah, DRY.
Could something be done about this?

**Comment by 6543** [comment]
ok we should add it back with a note that this is intended, the smal refactor is still nice :)

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> yeah I knew there was a reason why I didn't use /pulls for this

 ikr, I recall at some point we were even talking about it..

**Comment by 6543** [comment]
#15740 is ready to fix this, only the comment could be improved ...

**Pull request merged**
