### PR TITLE
Add result check in TestAPIEditUser

### LINKED ISSUE #29514: The usage of `NewRequestWithValues(t, "PATCH", url, data)` doesn't work in tests
### Description

~~`PATCH` request will read data from `Form`, but `NewRequestWithValues` will insert data into `Body`, so these data will not be readed correctly.~~
As title, the usage of `NewRequestWithValues(t, "PATCH", url, data)` doesn't work in tests
image

e.g.
image
image
image

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fix #29514
there are too many usage of `NewRequestWithValues`, so there's no need to check all of them.
Just one is enough I think.

### CODE REVIEW

**Comment by yp05327** [comment]
wait for https://gitea.com/go-chi/binding/pulls/16

**Comment by techknowlogick** [comment]
> wait for https://gitea.com/go-chi/binding/pulls/16

now that the binding PR has been merged, can this be reviewed?

**Comment by yp05327** [comment]
CI failure seems related, I will check it.

**Comment by yp05327** [comment]
https://gitea.com/go-chi/binding/pulls/17
still have some issues, wait for this one.

**Review by lunny — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Pull request merged**
