### PR TITLE
When starting new stopwatch stop previous if it is still running

### LINKED ISSUE #10529: Automatically stop tracking time on one issue if I start tracking time on another
Currently if I'm already tracking time on an issue and view a different issue there is a notice saying that I am already tracking time and links to the issue I am tracking on. Good :)

It doesn't prevent me starting to track time on a second issue though. At this point the "already tracking time" message disappears (confusing) if I'm viewing one of the two issues I'm tracking time on.

If I view another issue, there is the "already tracking time" message but it only links to one of the two issue. (confusing - I never know I'm accidentally tracking two issues until I stop tracking on one and the notice remains). Personally I cant see a need to track time on two issues at once - is this a bug??

Maybe needs a config option if multiple tracking is deemed a required feature. Perhaps even 3 options `Multiple Tracking: Prevent|Stop Other|Allow`

### PR DESCRIPTION
**Pull request by bobemoe**
Currently it is possible to start tracked time stopwatches on multiple issues at the same time. 

The UX feedback of this is a bit confusing, fixes #10529

This PR will prevent multiple stopwatches running by stopping the current stopwatch when another one is started.

Maybe needs a config option if multiple tracking is deemed a required feature. Perhaps even 3 options Multiple Tracking: Prevent|Stop Other|Allow

### CODE REVIEW

**Comment by bobemoe** [comment]
I still have this merged in locally. It's proving very useful for my workflow.

**Comment by zeripath** [comment]
I think no one has looked at this because it is still marked WIP.

**Comment by zeripath** [comment]
@bobemoe Could you update the first comment and title, and provide a bit more explanation as to what this is supposed to do and why it is useful.

**Comment by bobemoe** [comment]
@zeripath I've removed WIP so it can get some attention and updated the description, thanks.

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Pull request merged**
