### PR TITLE
[WIP] Grunt asset processing

### PR DESCRIPTION
**Pull request by tboerger**
**To get early feedback I have opened this pull request, don't merge it yet!**

I have started to integrate Grunt and Bower to handle the assets like concat, minify and so on. On top of that I'm vendoring out all external assets like bootstrap, jquery and so on. If you've got questions or suggestions you know where to comment :)

### CODE REVIEW

**Comment by tboerger** [comment]
@fuxiaohei especially you should review the stuff! I'm not totally sure if I have replaced the stuff in ```lib.js``` with the correct external libs.

**Comment by fuxiaohei** [comment]
I think I can review it after all ng template and assets are migrated.. It should be done before 0.7

**Comment by tboerger** [comment]
> I think I can review it after all ng template and assets are migrated.. It should be done before 0.7

What do you think when this will happen? I would like to build this on top of it of course :)

**Comment by tboerger** [comment]
Closing this for now, I will reopen it when we continue on that :)

**Pull request closed without merging**
