### PR TITLE
Use vue instead of plain template to render suscribe div of issue

### PR DESCRIPTION
**Pull request by lunny**
This PR did two things.

- Introducing `initComponent` which can make the component initlize simple than before
- Introducing `issue/Suscribe.vue` to instead of old template method

This can be compared with #28908 about a different framework to do the same thing.

Screen Recording 2024-01-24 at 19 05 54 2024-01-24 19_08_26

### CODE REVIEW

**Review by wxiaoguang — COMMENTED** [review]
I think "partially page reloading" (eg: `htmx` or `jQuery.load` or some Gitea's frontend mechanisms) is more suitable for this case, because overall Gitea is using backend template rendering heavily.

Using Vue for small components would make some things more complex:

1. Page flickering (because the Vue components are rendered after the page is loaded/rendered), some people dislike such flickering, then to fix such flickering it requires more hacky code.
2. Additional work for maintaining status/locale, additional JavaScript code.

Personally I prefer to fine tune existing mechanisms like `link-action` / `form-fetch-action`, while since most people like htmx and there would be some standards, so I think htmx could also do well.

**Comment by denyskon** [comment]
Isn't for example the loading indicator missing?

Overall, I can mostly agree with @wxiaoguang - we should not mix go templates and vue heavily, it creates confusion, makes refactoring harder, adds additional code which can be avoided usind htmx and so on.

I could imagine full Vue rewrites being beneficial for some components that are designed as dynamic in the first place, but for such small elements htmx looks like a better solution.

**Comment by lunny** [comment]
> Isn't for example the loading indicator missing?
> 
> Overall, I can mostly agree with @wxiaoguang - we should not mix go templates and vue heavily, it creates confusion, makes refactoring harder, adds additional code which can be avoided usind htmx and so on.
> 
> I could imagine full Vue rewrites being beneficial for some components that are designed as dynamic in the first place, but for such small elements htmx looks like a better solution.

The loading added, but the real problem is the div flickering @wxiaoguang mentioned. An obvious layout reaggrange can be found in the area of the subscribe button. The external div of the button needs a fixed height if we want to avoid that.

**Comment by lunny** [comment]
Close as htmx version merged.

**Pull request closed without merging**
