### PR TITLE
Comment box tweaks and SVG dropdown triangles

### PR DESCRIPTION
**Pull request by silverwind**
- Change all dropdown triangles to SVG
- Bring inline review comment box closer to regular comment boxes
- Enhance arc-green checkbox contrast
- Minor reaction tweaks
- Flexbox the diff file header

Screen Shot 2020-10-31 at 18 06 02
Screen Shot 2020-10-31 at 19 31 27
image

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
more thanks for these changes.

We should be careful though that with the octiconning of the UI we don't end up looking too much like GH

**Comment by silverwind** [comment]
Doesn't have to be strictly octicons but I came to like them. I mainly want to get rid of the icon fonts :)

**Comment by silverwind** [comment]
Those two comment boxes are like 95% the same, except they use slightly different context variables.

**Comment by silverwind** [comment]
Done pushing tweaks :)

**Comment by silverwind** [comment]
Noticed a regression with the triangle position, hold on.

**Comment by silverwind** [comment]
Regression fixed. Turns out Fomantic needed those old classes for its positioning.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
Hello there.
Is it possible I am getting the below because of this?
image

**Comment by silverwind** [comment]
Yes, I saw something similar. https://github.com/go-gitea/gitea/pull/13378 should have the fix.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
right..that's great. 🎉
cheers.

1 Nov 2020 17:27:27 silverwind <notifications@github.com>:

**Pull request merged**
