### PR TITLE
refactor: check the error returned by os.MkdirAll()

### PR DESCRIPTION
**Pull request by appleboy**
As title.

### CODE REVIEW

**Comment by lunny** [comment]
If the dir is exist, it will return nil or an error that dir is exist?

**Comment by appleboy** [comment]
It will return nil if the folder is exist.

**Comment by lunny** [comment]
https://godoc.org/os#MkdirAll seems that you don't need to change anything.

**Comment by lunny** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by metalmatze** [comment]
LGTM

**Pull request merged**
