### PR TITLE
Remove Noto Color Emoji fallback

### PR DESCRIPTION
**Pull request by silverwind**
It's causing browser errors logged in Firefox under certain circumstances, and I think we're better off recommending Linux users to install a proper emoji font into their system.

### CODE REVIEW

**Review by mrsdizzie — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
I marked it as "breaking" but alternative I think adding a hint into FAQ `my emojis have no color / not displayed correctly` would also do it ...

**Comment by 6543** [comment]
@silverwind should we add a FAQ instead?

**Comment by silverwind** [comment]
Yes, I'll add something in the docs.

**Comment by silverwind** [comment]
FAQ entry added.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
