### PR TITLE
WIP: Move git as modules/git

### PR DESCRIPTION
**Pull request by lunny**
This will still keep all the git commit histories.

### CODE REVIEW

**Comment by zeripath** [comment]
Hey @lunny I hope you don't mind that I took the liberty of getting this to build.

I think there's still a few things left:
- [ ] Ensure that everything in `modules/git/Makefile` is covered by the main gitea `Makefile`.
- [ ] There's a still a `modules/git/docker` folder which should probably be removed.

**Comment by zeripath** [comment]
I looked a bit more at this earlier today, there are issues in terms of the tests and benchmarks of the git module. These will add files to modules/git directory by default - these aren't cleaned and as some are go files will then cause other make tasks to fail.

They should probably be changed to download to a temporary directory which is deleted at the end of a test.

**Comment by lunny** [comment]
@zeripath please feel free to submit your commits. This PR still needs many changes.

**Comment by zeripath** [comment]
They should already be there - I used my manager rights to push changes to your GitHub branch. If you pull from that locally you should get the changes.

**Comment by techknowlogick** [comment]
We don’t need to keep git history because 1. We will have it in old repo (and can archive that repo), and 2. When this is merged it’ll be squashed into one commit then merged.

**Comment by lunny** [comment]
should fix #5954

**Comment by lunny** [comment]
Please go #6364 to discuss further.

**Pull request closed without merging**
