### PR TITLE
Improve issue icon vertical alignment

### LINKED ISSUE #15386: Issuelist icon too high
- Gitea version (or commit ref): 1.15.0+dev-108-g84f5a0bc6
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL): https://try.gitea.io/issues
  - [ ] No

## Description

The issue list icon is now too high

## Screenshots

Screenshot from 2021-04-10 12-36-02

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/15386

Screen Shot 2021-04-10 at 18 15 37

### CODE REVIEW

**Comment by silverwind** [comment]
I think the issue is more involved actually. All this PR changes is move it down by 0.45px but the screenshot in the issue shows more of a difference than I'm seeing.

From https://try.gitea.io/pulls using Firefox:

image

**Comment by zeripath** [comment]
I'm using chrome.

**Comment by silverwind** [comment]
https://try.gitea.io/silverwind/symlink-test/issues looks alright to me in Chromium 89.0.4389.90 on macOS:

image

Are you sure it's not something about your browser?

**Comment by silverwind** [comment]
Don't think this is the right fix and I also think original issue is invalid.

**Pull request closed without merging**
