### PR TITLE
ci: go back to golangci-lint 1.20.0

### PR DESCRIPTION
**Pull request by sapk**
Revert https://github.com/go-gitea/gitea/pull/9711

I don't really know if it will fix thing but worth a try. 😄

### CODE REVIEW

**Comment by sapk** [comment]
I will retstart multiple time the job to find if it solved the problem.

**Comment by bagasme** [comment]
@sapk what's wrong so that you did this?

**Comment by sapk** [comment]
@bagasme golangci-lint fail "randomly" on various test. ex: https://drone.gitea.io/go-gitea/gitea/19284/1/10

**Comment by sapk** [comment]
So far 3 builds without problem

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
working CI is more important than a new version :)

**Comment by sapk** [comment]
Yes, I pretty sure that golangci-lint maintainer will figure it out.

**Pull request merged**
