### PR TITLE
Backport: Restricting access to fork functioanlity to users with Code access

### PR DESCRIPTION
**Pull request by jonasfranz**
Backport for v1.2 of #2534

### CODE REVIEW

**Comment by lunny** [comment]
Trusted LGTM

**Comment by lafriks** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by jonasfranz** [comment]
@lunny @appleboy CI test fail is not related to this changes

**Comment by bkcsoft** [comment]
Force-merging :trollface:

**Pull request merged**
