### PR TITLE
Fix swagger title

### PR DESCRIPTION
**Pull request by yp05327**
image
Don't know why there's a `.` behind. 🤔

### CODE REVIEW

**Review by denyskon — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I guess it's not the right file to change.

Have you tried `make generate-swagger`?

**Comment by denyskon** [comment]
However what'd even be the correct path to fix if the file is being generated?

**Review by lunny — CHANGES_REQUESTED** [review]
per https://github.com/go-gitea/gitea/pull/28164#issuecomment-1822131435

**Comment by yp05327** [comment]
> However what'd even be the correct path to fix if the file is being generated?

I don't know too. I'm trying to figure out.

**Comment by yp05327** [comment]
Done in https://github.com/go-gitea/gitea/pull/28164/commits/1caa6c95b5996390272023bbd9db1509aa89a1cb

**Review by lunny — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

**Pull request merged**
