### PR TITLE
Update golang.org/x/crypto (#19097)

### PR DESCRIPTION
**Pull request by Gusted**
- Backport #19097

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
we need to migrate from deprecated func ... see linter

**Comment by techknowlogick** [comment]
@6543 I uhh, just set the linter to ignore those. If my 1.18 and @silverwind's PR that was related to using go install, are both backported that'll probably help resolve a lot of the CI stuff we are seeing with 1.16 branch

**Comment by silverwind** [comment]
That'd mean we bump the build requirement to golang 1.17, but I guess we are free to do that in a patch-level release :)

**Comment by lunny** [comment]
I have fixed `strings.Title` lint problem in another PR.

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
