### PR TITLE
go back to using CFB for AES decryption/encryption for 2FA

### LINKED ISSUE #3187: Internal Error – 500 – when trying to log in with 2FA enabled
- Gitea version (or commit ref): [master: c06cc74](https://github.com/go-gitea/gitea/commit/c06cc740dea46f3aff58e0eded4208232bb5902d)
- Git version: 2.15.1
- Operating system: GNU (Running on arm64, distribution: Arch Linux ARM)
- Database (use '[x]'):
- [ ] PostgreSQL
- [ ] MySQL
- [ ] MSSQL
- [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
- [X] Yes (provide example URL): [Sign in page](https://try.gitea.io/user/login?redirect_to=)
- [ ] No
- [ ] Not relevant
- Log gist: [GitHub gist](https://gist.github.com/FrostyPenguin/88c9a807051fd95ca660289fd31d1288)

## Description
After I updated my Gitea installation to the newest build in [master](https://dl.gitea.io/gitea/master/) (2017-12-13 18:00 UTC+1) signing in with 2FA was broken. Surprisingly, this is not a “local” issue as logging in to try.gitea.io with an already existent account that's got 2FA enabled did not work either.

I tried restarting my Browser (Firefox 57.0.2) in Safe Mode (with uMatrix, uBlock, and HTTPSEverywhere disabled), but that didn't help. So it must be a problem with some newer commits to Gitea's master branch.

**Even though at first sight this might look like #1851, it definitely is *a new and reproducible* bug as “downgrading” my Gitea binary to 1.3.1 solved the problem for me.**

## Screenshots

I'm not sure if you this will help you, but sure… here's a screen cast.

https://streamable.com/4jv6u

### PR DESCRIPTION
**Pull request by thehowl**
Closes #3187.

Commit b7ebaf6d2078cbf4de00d0782be8bc1b1de644bb updated Unkwown/com, yet again another unidiomatic piece of Go code that shouldn't exist (it would be much better to have different packages with meaningful name instead of a large "common" package that packs together a bunch of utility functions). Among the utility functions that were updated were AESEncrypt and AESDecrypt, which changed name to AESGCMEncrypt and AESGCMDecrypt.

As you can guess, the change wasn't just in the name; in fact, previously the function used CFB, while after a [PR](https://github.com/Unknwon/com/pull/12) it started using AES-GCM. And as you can pretty much guess now, this change is backwards incompatible, which is why issue #3187 arised.

This PR rollbacks the behaviour and goes back to using CFB. It may be useful to implement GCM one day; however this should be done carefully and ensuring backwards compatibility with the previous encrypted secrets in AES-CFB.

### CODE REVIEW

**Comment by lafriks** [comment]
Does this change will break 2fa codes created in instances  after that commit was done?

**Comment by thehowl** [comment]
I just verified - it does, however, since the commit was done during 1.4.0's lifecycle, it should not affect many end users if not those who enrolled in 2FA while being on an unstable branch (e.g. try.gitea.io)

**Comment by lafriks** [comment]
I agree on that. Also CI failure does not seems to be related to this change so LGTM

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
LGTM

**Pull request merged**
