### PR TITLE
De-extract some inline functions related with create comment

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]

**Comment by zeripath** [comment]
This reads rather like a de-extraction of inline functions... Why?

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@zeripath these functions are anyway used just once so it is easier to read what it actually does

**Comment by lunny** [comment]
@zeripath just like @lafriks said. These functions were invoked only once and they are a simple wrap of `createComment`. It's unnecessary.

For a further reason, I want to move `notifyWatcher` on `createComment` to notification, but it's difficult. I have to send serval PRs to refactor them.

**Comment by zeripath** [comment]
make lg-tm work

**Pull request merged**
