### PR TITLE
Add more test directory to exclude dir of air, remove watching templates from air include dir because gitea has internal mechanism

### PR DESCRIPTION
**Pull request by lunny**
Since #20218 introduced internal watching template, template watching should be removed from `air`. This will prevent restart the whole server but only recompile templates once the template files changed to speed up developing when using `make watch`. Now a template change will only spend less than `1s` in my macbook 2019 but over `20s` before.

To ensure `make watch` will reuse template watching, this PR introduced a new ENV `GITEA_RUN_MODE` to make sure `make watch` will always run in a dev mode of Gitea so that template watching will open.

This PR also added more exclude testdata directories.

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]

**Review by fuxiaohei — APPROVED** [review]

**Comment by silverwind** [comment]
Will template changes still reload the dev server after this? I don't quite understand.

**Comment by KN4CK3R** [comment]
Same question from my side. Editing a template file was also a very fast way to force a restart.

**Comment by lunny** [comment]
> Will template changes still reload the dev server after this? It'd certainly be useful to not have to manually restart on template change.

Template changes will not reload the dev server any more but will fire internal template watching, that means only templates will be recompiled again. This is obviously faster than before, because there is no server restart, no database init, no web listen and etc.

**Comment by lunny** [comment]
> Same question from my side. Editing a template file was also a very fast way to force a restart.

You could change a go file to implement it now.

**Comment by KN4CK3R** [comment]
> > Same question from my side. Editing a template file was also a very fast way to force a restart.
> 
> You could change a go file to implement it now.

Sure but now I need to search for a file which does not force recompilation of a big part of our codebase to make it fast. But that was just convenience.

**Comment by lunny** [comment]
> > > Same question from my side. Editing a template file was also a very fast way to force a restart.
> > 
> > 
> > You could change a go file to implement it now.
> 
> Sure but now I need to search for a file which does not force recompilation of a big part of our codebase to make it fast. But that was just convenience.

You can always edit `main.go` because no other code depend it.

**Comment by silverwind** [comment]
If template changes automatically reload it in the server without a restart, that's fine with me. So on next F5, it should serve the new template. I will try it.

**Pull request merged**
