### PR TITLE
Add MulanPSL-2.0

### PR DESCRIPTION
**Pull request by a1012112796**
link: http://license.coscl.org.cn/MulanPSL2

published on 1st, 2020

### CODE REVIEW

**Review by jolheiser — CHANGES_REQUESTED** [review]
Can you instead run https://github.com/go-gitea/gitea/blob/master/build/generate-licenses.go for updates. 🙂

**Comment by 6543** [comment]
@jolheiser ... what if .. we had a make task for it ;)

**Comment by jolheiser** [comment]
> what if .. we had a make task for it ;)

Not a bad idea. Could also add one for the gitignores if you want.

**Comment by a1012112796** [comment]
> Can you instead run https://github.com/go-gitea/gitea/blob/master/build/generate-licenses.go for updates. 🙂

Maybe it's not necessary, because https://github.com/spdx/license-list hasn't updated after 2017.

**Comment by techknowlogick** [comment]
@a1012112796 the script pulls from https://github.com/spdx/license-list-data which was update 3 days ago

**Comment by a1012112796** [comment]
> @a1012112796 the script pulls from https://github.com/spdx/license-list-data which was update 3 days ago

okay, I see, I will do it soon.

**Comment by 6543** [comment]
@a1012112796 MulanPSL-2.0 is there too - tested :)

**Comment by a1012112796** [comment]
Maybe we can let giteabot update licences path each month. :)

**Comment by 6543** [comment]
@a1012112796 https://github.com/go-gitea/gitea/pull/12682

**Comment by 6543** [comment]
> Maybe we can let giteabot update licences path each month. :)

a nice idear ...

**Comment by 6543** [comment]
@jolheiser I did it

**Comment by techknowlogick** [comment]
closing in favour of other PR

**Pull request closed without merging**
