### PR TITLE
Fix repo indexer and submodule bug (#3107)

### PR DESCRIPTION
**Pull request by ethantkoenig**
Backport of #3107.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by lunny** [comment]
@ethantkoenig please send an empty push for CI running correctly.

**Comment by lunny** [comment]
make L-G-T-M

**Pull request merged**
