### PR TITLE
Fix frontpage newsfeed commit avatars, remove img-* classes

### LINKED ISSUE #13844: E-Mail based avatar rendering default images
https://github.com/go-gitea/gitea/commit/9269a038a4e904bdeaf5470e76e3a4f8a2a4685b seems to include a regression where e-mail derived avatars on the frontpage commits that were previously working now only render the default image, so something about that lookup must've changed. If I click such a commit, the commit view page shows the correct avatar.

Also reproducible on [try](https://try.gitea.io/silverwind/updates/commit/6e92987bda3bc21c548be76d1e8e3e996edf47dd):

image
image

### PR DESCRIPTION
**Pull request by silverwind**
The frontpage uses a rather strange method to obtain the commit's avatar which I've overlooked earlier. I don't exactly understand how it works but this change fixes the wrong default avatars by using the function that was in previous use.

Also introduced a few constants for size an size increase factor.

Fixes: https://github.com/go-gitea/gitea/issues/13844

### CODE REVIEW

**Comment by silverwind** [comment]
Some more related fixes included here:

- Remove `img-*` classes to allow browsers to optimize using explicit `width/height`.
- Fix image alignment on webhook dropdown and misc fixes to that dropdown.

Screen Shot 2020-12-05 at 13 46 01

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
Ok, I'll stop piling on unrelated fixes now 😉

**Comment by 6543** [comment]
@silverwind Conflicts apear

**Comment by silverwind** [comment]
Rebased.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
