### PR TITLE
Replace all master with main when necessary

### PR DESCRIPTION
**Pull request by nanguanlin6**
As title. Still need to polish some details so WIP.
Should I break this PR into different parts?
Edited: 
I probably should break this PR into three parts.
1. for docs and URL in comments
2. for wiki, which still uses `master` as default. (not sure if should change this one)
3. for the test case

### CODE REVIEW

**Comment by silverwind** [comment]
This is supposed to be non-breaking, right? Wiki might need a new config option.

**Comment by lng2020** [comment]
Yes. It supposed to be Non-breaking. If I found something breaking, I will raise another PR to solve that part.

**Comment by wxiaoguang** [comment]
> 2. for wiki, which still uses master as default. (not sure if should change this one)

The wiki default branch is changeable now.

> 3. for the test case

IMO no need to change the test fixtures.

**Comment by lunny** [comment]
This is outdated and hard to merge. Let's close it at the moment.

**Pull request closed without merging**
