### PR TITLE
WIP: Katex rendering with yaml frontmatter control

### PR DESCRIPTION
**Pull request by zeripath**
Extension to #20571 with the ability to add yaml frontmatter to control recognition of latex/tex code e.g.:

```markdown
---
math:all
--- 

$x = 5$
```

### CODE REVIEW

**Comment by silverwind** [comment]
Does this present an alternative to https://github.com/go-gitea/gitea/pull/20571 or replace it?

**Comment by zeripath** [comment]
This is more of an extension to #20571 than replacement or alternative - if it's preferred to have this level of control we can merge it into #20571 or do it as another PR.

I think I need to look at controlling the goldmark parser/renderer a bit closer - it might just be that we should just create new goldmark structs each request instead of reusing but I'm not certain. We currently reuse because we can not because it's proven costly to recreate.

**Comment by silverwind** [comment]
I still don't understand this YAML frontmatter business. How does it apply to Markdown? How is it used?

**Comment by zeripath** [comment]
> I still don't understand this YAML frontmatter business. How does it apply to Markdown? How is it used?
The simple idea is that users use the yaml frontmatter to control aspects of the markdown renderer, enabling and disabling extensions as needed. 

This is similar to how Hugo works.

**Comment by silverwind** [comment]
Yes, but we don't write YAML in markdown content, or do we?

**Comment by zeripath** [comment]
Frontmatter is a common extension that lots of markdown renderers provide:

https://gohugo.io/content-management/front-matter/

https://jekyllrb.com/docs/front-matter/

https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#:~:text=When%20you%20create%20a%20Markdown,and%20end%20of%20the%20block.

We've had a very basic front matter parser available in Gitea for quite some time - just essentially undocumented. (this includes a very basic implementation of `include_toc` functionality.

**Comment by silverwind** [comment]
Ok, I see it's https://docs.gitlab.com/ee/user/markdown.html#front-matter, basically some metadata that can be rendered on top of markdown.

**Pull request closed without merging**
