### PR TITLE
Fix reverting a merge commit failing

### LINKED ISSUE #22236: reverting a merge commit fails
### Description

Steps to reproduce:

Create a repository
create a commit
create a new branch 
make a change to the file from the original commit in the new branch
create a pull request
merge the pull request
click the merge commit id  e.g. https://try.gitea.io/JensTimmerman/test/commit/84f4738d2ab5263abe4dc2460b24c4d78aa6c68c
click on operations, revert
select the main branch in the pop up
select `create a new branch for this commit and start a pull request` on the revert page that shows up (e.g. https://try.gitea.io/JensTimmerman/test/_cherrypick/84f4738d2ab5263abe4dc2460b24c4d78aa6c68c/main?ref=main&refType=branch&cherry-pick-type=revert )
click propose file change

You get an error (on the page https://try.gitea.io/JensTimmerman/test/_cherrypick/84f4738d2ab5263abe4dc2460b24c4d78aa6c68c/main ):
`Unable to apply patch 'Error: Stdout: Stderr: error: No valid patches in input (allow with "--allow-empty") Err: exit status 128'`

(this error is slighty different on different versions of gitea, or perhaps depending on the exact test scenario)

The 'new patch' textfield shows
`revert 84f4738d2ab5263abe4dc2460b24c4d78aa6c68c`

instead of the code to be changed

The debug logs state:
```
2022/12/24 22:36:02 ...dules/git/command.go:179:Run() [D] [63a77ed2] /var/lib/gitea/data/tmp/local-repo/upload.git1909367275: /usr/bin/git -c protocol.version=2 -c uploadpack.allowfilter=true -c uploadpack.allowAnySHA1InWant=true -c credential.helper= read-tree -m a0830bee2fbb72fb55370bc8a9c0c4e05acba853 686d56c5e84498ca372c8ed86b9e743aa57c4955 b269bbeb490033dd65b029dce65b85780cd2a519
2022/12/24 22:36:02 ...rvices/pull/patch.go:238:AttemptThreeWayMerge() [E] [63a77ed2] Unable to run read-tree -m! Error: exit status 128 - fatal: this operation must be run in a work tree
	 - fatal: this operation must be run in a work tree
```	

### Gitea Version

1.17.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

2.31.1

### Operating System

centos8 stream

### How are you running Gitea?

I'm using the [do1jlr.gitea ansible role](https://github.com/DO1JLR/ansible-role-gitea) to deploy on a container on centos8stream running on proxmox.
But this is probably not relevant since I'm able to reproduce this issue on try.gitea.io.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by me-heer**
Fixes #22236

---
Error occurring currently while trying to revert commit using read-tree -m approach:
> 2022/12/26 16:04:43 ...rvices/pull/patch.go:240:AttemptThreeWayMerge() [E] [63a9c61a] Unable to run read-tree -m! Error: exit status 128 - fatal: this operation must be run in a work tree
> 	 - fatal: this operation must be run in a work tree

We need to clone a non-bare repository for `git read-tree -m` to work.
https://github.com/go-gitea/gitea/commit/bb371aee6ecf5e570cdf7b5f7f0d6f47a607a325 adds support to create a non-bare cloned temporary upload repository.

After cloning a non-bare temporary upload repository, we [set default index](https://github.com/go-gitea/gitea/blob/main/services/repository/files/cherry_pick.go#L37) (`git read-tree HEAD`). 
This operation ends up resetting the git index file (see investigation details below), due to which, we need to call `git update-index --refresh` afterward.

Here's the diff of the index file before and after we execute SetDefaultIndex: https://www.diffchecker.com/hyOP3eJy/

Notice the **ctime**, **mtime** are set to 0 after SetDefaultIndex.

You can reproduce the same behavior using these steps:
```bash
$ git clone https://try.gitea.io/me-heer/test.git -s -b main
$ cd test
$ git read-tree HEAD
$ git read-tree -m 1f085d7ed8 1f085d7ed8 9933caed00
error: Entry '1' not uptodate. Cannot merge.
```

After which, we can fix like this:
```
$ git update-index --refresh
$ git read-tree -m 1f085d7ed8 1f085d7ed8 9933caed00
```

### CODE REVIEW

**Review by wxiaoguang — COMMENTED** [review]
Could there be some tests to cover the behavior? (Haven't read the details carefully yet)

**Comment by me-heer** [comment]
> Could there be some tests to cover the behavior? (Haven't read the details carefully yet)

Yes, I was going to work on them after this is merged/I'm sure the approach is right.

Do tests covering this new behavior go in the same PR or another PR usually?

**Comment by wxiaoguang** [comment]
> > Could there be some tests to cover the behavior? (Haven't read the details carefully yet)
> 
> Yes, I was going to work on them after this is merged/I'm sure the approach is right.
> 
> Do tests covering this new behavior go in the same PR or another PR usually?

Usually (and preferred) to make the tests go in the same PR.

**Comment by lunny** [comment]
It seems it works in my manually local tests.

**Review by wxiaoguang — APPROVED** [review]
I haven't thought deeply about this (eg: potential other approaches? no idea yet ....). Since it has been covered by tests and is better than before, I would vote my approval.

**Review by lunny — APPROVED** [review]

**Pull request merged**
