### PR TITLE
Set version to 1.2.0

### PR DESCRIPTION
**Pull request by strk**
Will be shown by `go get` based builds

### CODE REVIEW

**Comment by lunny** [comment]
No. This is the correct version. This is not the v1.2.0.

**Review by lafriks — COMMENTED** [review]
To be less confusing I think this should be `devel` or `master`

**Comment by strk** [comment]
+dev appended, but before tagging final you should drop the +dev

**Comment by strk** [comment]
And right after tagging final with version "1.2.0" you should
update the file again to read "1.2.1+dev"

**Comment by sapk** [comment]
We should keep -dev or +dev in repo but no need to change for release since the `make release` will use the tag for the versionning.

**Comment by sapk** [comment]
otherwise LGTM.

**Comment by strk** [comment]
The need to change is is because we're including patch-level
so it would be weird for "1.2.0-dev" to be used for code which
is about to become "1.2.1", because "1.2.0" would be already out
and we want the current (WIP) code to be more recent than "1.2.0"

**Comment by sapk** [comment]
I must have misunderstood. Dis you mean  ? :
- use "1.2.0-dev"
- git tag "1.2.0" -> release but don't change the file
- use "1.2.0+dev"

If it is the case, I am ok with you what I meant is we don't have to write to file the exact version "1.2.0".

**Comment by strk** [comment]
Actually no, I meant to commit "1.2.0" too, but now that I 
see your workflow I'm convinced we don't really needed.

It's enough to make sure production binaries are made using `make`

Only nitpick is I'd use "1.2.1-dev" instead of "1.2.0+dev"
as it's more informative for users (although of course it takes
knowing in advance where the branch is aiming at)

**Comment by strk** [comment]
NOTE: the "1.2.1-dev" approach also allows to distinguish
between release branch and master branch (which would be "1.3.0-dev").
In the "+" approach both branches would be sticking at "1.2.0+dev"
till the next 1.2 release...

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@strk please rebase

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
