### PR TITLE
Add branch/event select option to webhook test

### PR DESCRIPTION
**Pull request by yp05327**
Issue:
User can not select which branch/event to test in webhook edit page.
And if an error happens, no error info displays in the page. For example, when default branch is not in `branch filter`, 
test will fail and user can not know what happened.

image

TODO:
- [x] Locale
- [x] Only display valid branch and event in dropdown.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
TBH, the problem seems more complex, and there are different payload types.

Even if you only consider "branch" related, there are other fields related to branch, they must match.


----

The question is: is it necessary to simulate all webhook events to end users? Coud the test be as simple as only "test whether the user's webhook server works", then users could use real actions to fine tune their webhook server?

**Comment by wxiaoguang** [comment]
To resolve the problem: "And if an error happens, no error info displays in the page. For example, when default branch is not in branch filter, test will fail and user can not know what happened."


I think it could be resolved by: make users see the failed webhook requests and see the errors, in the delivery history.

**Comment by yp05327** [comment]
> I think it could be resolved by: make users see the failed webhook requests and see the errors, in the delivery history.

The webhook requests will not be created and no error info shows, because in `PrepareWebhook` if HookEventType/Branch is invalid, it will return nil. Then the render function will render a success message even it is failed.
So there are two types of failure:
- The creation of webhook request is failed
- The webhook request is failed
Do you mean that we can display both of these two failures in the delivery history?

ps: Maybe in some places, `PrepareWebhook` should return nil when HookEventType/Branch is invalid?

> The question is: is it necessary to simulate all webhook events to end users? Coud the test be as simple as only "test whether the user's webhook server works", then users could use real actions to fine tune their webhook server?

This question is from another user in QQ group. Maybe he can run the default test (default branch and default event) successfully, but have some problems in other cases, so there's a need to test webhook in custom branch and custom event? 
IMO, it is perfect if we can offer a customable webhook test.

**Comment by wxiaoguang** [comment]
I see your point. I have no more idea about this problem at the moment. 🤔

**Comment by wxiaoguang** [comment]
IMO  it's better to clarify the problem and have a whole design.

Current solution doesn't look good to me (the concerns haven't been addressed)

**Comment by lunny** [comment]
Maybe it should be work of a third-party tool. For gitea, we should not spend too much time on test the webhook. A simple test will tell us the webhook endpoiint can address. I think that's enough.

**Comment by yp05327** [comment]
image
image
One question here, why PR reviewed include comment hook.
If I select PR reviewd, only `approved` and `rejected` will pass the filter check.
image

**Pull request closed without merging**
