### PR TITLE
Update the contribution guidelines

### PR DESCRIPTION
**Pull request by Bwko**
Added `If a maintainer is inactive for more than 3 months` to the last line and added a link to the maintainers & advisors team

### CODE REVIEW

**Comment by thibaultmeyer** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
@tboerger @bkcsoft

**Comment by makhov** [comment]
@lunny it's really tiny but useful PR. Just merge it :)

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
