### PR TITLE
Support Range header end in lfs

### PR DESCRIPTION
**Pull request by burbon**
Current implementation of Range header support in LFS only uses range start and ignores range end.
We have a use case where for media files we want to download a fixed range data including range end. This change is an attempt to allow it.

### CODE REVIEW

**Comment by zeripath** [comment]
@burbon Thanks for the PR. 

## More Range support

Unfortunately, your proposed PR breaks the unspecfied end range option: `Range: bytes=<range-start>-` which should continue to support. It may also be helpful to support the `Range: bytes=-<suffix-length>` format too.

Take a look at:  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

There are a few others that could be useful to support too.

## Tests

I wonder if you would be able to add a test into either:

1. `integrations/git_test.go` preferably around here:

https://github.com/go-gitea/gitea/blob/505e456f26e11d4ee2f7a807a037b11b59defb1f/integrations/git_test.go#L109

`bigLFS` is the git SHA of the large object.  Here shows how to get the pointer file 

https://github.com/go-gitea/gitea/blob/505e456f26e11d4ee2f7a807a037b11b59defb1f/integrations/git_test.go#L227

or

2. In `integrations/lfs_getobject_test.go`, probably within this function:

https://github.com/go-gitea/gitea/blob/505e456f26e11d4ee2f7a807a037b11b59defb1f/integrations/lfs_getobject_test.go#L59

**Comment by burbon** [comment]
Hi @zeripath 
Thanks for looking at it. Indeed previous change broke unspecified end range. This is fixed now and covered by integration tests - thanks for pointing to them.
If this is OK i'm happy to add suffix length as well in the same fashion, but not that keen on multiple range sets.
Found Range header implemented here:
https://github.com/golang/go/blob/master/src/net/http/fs.go#L219

**Comment by burbon** [comment]
Pressed the close button accidentally.

**Comment by zeripath** [comment]
Unfortunately the way you've changed the tests is not going to work. I'll have a think about how best to fix this.

**Comment by zeripath** [comment]
You would need to move the preamble:

```go
defer prepareTestEnv(t)()
setting.CheckLFSVersion()
if !setting.LFS.StartServer {
	t.Skip()
	return
}
```

to the start of each of those Test... functions.

I would also remove the use of the `do...` prefix from `doLFS` function as we should save the `do` is for declarative tests - that is a test that is self contained and could be run from any other test. Here doLFS is a function that returns a value rather than test.

Let's take an example of (at least what I call) a declarative test:

```go
func doAPICreateRepository(ctx APITestContext, empty bool, callback ...func(*testing.T, api.Repository)) func(*testing.T) {
	return func(t *testing.T) {
		createRepoOption := &api.CreateRepoOption{
			AutoInit:    !empty,
			Description: "Temporary repo",
			Name:        ctx.Reponame,
			Private:     true,
			Gitignores:  "",
			License:     "WTFPL",
			Readme:      "Default",
		}
		req := NewRequestWithJSON(t, "POST", "/api/v1/user/repos?token="+ctx.Token, createRepoOption)
		if ctx.ExpectedCode != 0 {
			ctx.Session.MakeRequest(t, req, ctx.ExpectedCode)
			return
		}
		resp := ctx.Session.MakeRequest(t, req, http.StatusCreated)

		var repository api.Repository
		DecodeJSON(t, resp, &repository)
		if len(callback) > 0 {
			callback[0](t, repository)
		}
	}
}
```

I can use `doAPICreateTestRepository` as a subtest in multiple other tests without having to rewrite it and if I care about the results I can pass in a callback that will still run in that current subtest so I can mark that subtest failing. In fact we use `doAPICreateTestRepository` in multiple places , the most declarative example is in `ssh_key_test.go`:

https://github.com/go-gitea/gitea/blob/dbb74978f7a4574d237952349437e7ac03764e3b/integrations/ssh_key_test.go#L87-L214

In particular take a look at:

https://github.com/go-gitea/gitea/blob/57b6f831916af59b7ad8ad0a9d0dd9083da88a6f/integrations/ssh_key_test.go#L169-L187

The style almost self-documents - it says exactly what it is testing and you can see how using these components you can build a progressively more complex test. A test that follows a simple story of what it is doing.

(That's not to say these tests are bad - they're just not declarative and componentisable. Making these componentisable may not be sensible - I cannot at present imagine we would want to request specific ranges in other tests, but we should try to keep the componentised test namespace as clean as possible.)

**Review by zeripath — APPROVED** [review]

**Comment by burbon** [comment]
Thanks for fixing tests. There is no need to `return` after `t.Skip()` isn't it?

**Comment by zeripath** [comment]
I think it's good practice to just return tbh

**Review by guillep2k — APPROVED** [review]

**Comment by burbon** [comment]
> I think it's good practice to just return tbh

Can't find it being used in golang src.

Myself I found it a bit confusing, suggesting that code after `Skip()` is still being executed, while it is not. `Skip()` just calls `runtime.Goexit()`.

**Pull request merged**
