### PR TITLE
Upgrade alpine to v3.5 in Dockerfile

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by lunny** [comment]
@tboerger any idea?

**Comment by tboerger** [comment]
Please update also the base image for rpi to a proper 3.5 image

**Comment by PeterDaveHello** [comment]
@tboerger I don't think it has v3.5, the last time it's updated was 9 months ago:
https://hub.docker.com/r/hypriot/rpi-alpine-scratch/tags/

Did I miss anything?

**Comment by sapk** [comment]
[multiarch/alpine](https://hub.docker.com/r/multiarch/alpine) could be used as a replacement of hypriot ?

**Comment by PeterDaveHello** [comment]
Maybe, but it'll be another issue?

**Comment by sapk** [comment]
I think that if one image of gitea is updated the others should have the same treatment in the same time (same PR) to be consistent. We just have to clarify which new base for arm and I am maybe a little to new in the maintainers to choose the one ^^.

**Comment by tboerger** [comment]
The mulriarch image sounds good.

**Comment by ptman** [comment]
Fix vs. improvement? First update to 3.5. Later change it to improve more architectures?

**Comment by tboerger** [comment]
> Fix vs. improvement? First update to 3.5. Later change it to improve more architectures?

It's all about using a more up2date base image. So nothing really about more architectures to support.

**Comment by PeterDaveHello** [comment]
@tboerger so you want me to change rpi base image here?

**Comment by sapk** [comment]
@PeterDaveHello I wouldn't talk for @tboerger but he say that multiarch is good so please update multiarch/alpine:armhf-v3.5 for .rpi and multiarch/alpine:aarch64-v3.5 for .aarch64

**Comment by tboerger** [comment]
> @PeterDaveHello I wouldn't talk for @tboerger but he say that multiarch is good so please update multiarch/alpine:armhf-v3.5 for .rpi and multiarch/alpine:aarch64-v3.5 for .aarch64

That's exactly what I mean :)

**Comment by PeterDaveHello** [comment]
Updated!

**Comment by sapk** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Pull request merged**
