### PR TITLE
Fix bug of branch/tag selector in the issue sidebar

### LINKED ISSUE #32731: Issue reference selection empty tips should not be selectable.
### Description

In the issue referenece selecting list in a no-tag repo, the `no results found` option should be disabled.

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

image
https://demo.gitea.com/shugen/Wow/issues/1

### Git Version

Not related

### Operating System

Not related

### How are you running Gitea?

Docker ! Docker yyds ~

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by hiifong**
Fix: #32731

----

Original proposal (rejected due to https://github.com/go-gitea/gitea/pull/32744#issuecomment-2540013894):

The Issue.Ref was added by "Add possibility to record branch or tag information in an issue (#780)"

After 8 years, this "branch selector" does nothing more than saving the branch/tag name into database and displays it.
So there is a plan to remove it:

* Only hide it from the UI in 1.23, and collect feedbacks.
* If nobody complains and explains how to use it, remove code and drop database column in next release.

What if I still would like to record branch or tag information in my workflow?

* Write it in the issue title then it will still be displayed, eg: [bug] (fix/ui-broken-bug) there is a bug ....
* Use PR workflow, and use issue/PR reference in the comment, eg: This issue will be fixed by PR #123
* There will be a new feature #31899

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by yp05327** [comment]
Didn’t look into it, but why RepoBranchTagSelector is not used here?

**Comment by wxiaoguang** [comment]
TBH, this selector should be completely removed.

I don't it is useful in modern Gitea. It seems that selector was added in old days when Gitea doesn't have proper Issue/PR support.

Anyone is really using that selector?

**Comment by yp05327** [comment]
It seems that it is used only in this pkace.

**Comment by wxiaoguang** [comment]
History: Add possibility to record branch or tag information in an issue (#780)

It does nothing more than just saving the branch/tag name into database ..............

**Comment by hiifong** [comment]
> TBH, this selector should be completely removed.
> 
> I don't see it is useful in modern Gitea. It seems that selector was added in old days when Gitea doesn't have proper Issue/PR support.
> 
> Anyone is really using that selector?

I think it is not a selector here, but a hint.

**Comment by shugen002** [comment]
Just some notice: 
this selector , in other word, this sidebar also used in the new issue page.
if someone want to do some refactor, don't forget to check the page.

**Comment by lunny** [comment]
> History: Add possibility to record branch or tag information in an issue (#780)
> 
> It does nothing more than just saving the branch/tag name into database ..............

After reviewed the history, the feature aims to record which branch/tag happened of this issue. It looks like it maybe useful when reporting a bug. It's incomplete to have filter in issues page. Since Github has no such feature, we commonly record a version, OS, and other things in the issue content. Another alternative feature is label. Users can create labels with the same name as versions and track them with labels. So is this a really necessary feature? Maybe not.

**Comment by yp05327** [comment]
I think this feature can be merged into development as it is used for developers to track in which branch/tag happened of this issue.
Or at least, giving it a description and a title. For now, I think most users don’t know the correct usage which it is designed for, especially after the implementation of development section.

**Comment by hiifong** [comment]
remove it

**Comment by wxiaoguang** [comment]
> remove it

Although I suggested to remove it, actually "how to remove it" should be carefully designed.

Since this feature has been there for long time, we are not sure whether it is sure that nobody needs it.

If you just remove it completely and drop the column, then what if some 1.23 users come to complain: please give that selector back to me, what could you do?


Ideally the removal should be like this:

1. only hide it from the UI in 1.23, and collect feedbacks
2. if nobody explains, completely remove it in 1.24 or 1.25

**Comment by hiifong** [comment]
> > remove it
> 
> Although I suggested to remove it, actually "how to remove it" should be carefully designed.
> 
> Since this feature has been there for long time, we are not sure whether it is sure that nobody needs it.
> 
> If you just remove it completely and drop the column, then what if some 1.23 users come to complain: please give that selector back to me, what could you do?
> 
> Ideally the removal should be like this:
> 
> 1. only hide it from the UI in 1.23, and collect feedbacks
> 2. if nobody complains and explains how to use it, remove code and drop database column   in 1.24 or 1.25

Done

**Comment by wxiaoguang** [comment]
I will add some comments

**Comment by wxiaoguang** [comment]
Added `TODO: RemoveIssueRef:` to the occurrences, then we could find them easily in the future.

**Comment by wxiaoguang** [comment]
Keep this PR open for a few days to collect first round feedbacks.

**Review by wxiaoguang — APPROVED** [review]

**Comment by eeyrjmr** [comment]
Two questions.

1.what is shown/managed for issues that do have this information ? Will this break something for those instances that this was previously used one
2. How is this capability still realised (options were listed at in the OP)

This might not impact how we work... Just trying to collect the information. Multiple LTS feature branches at different branching from MAIN... I guess review comments can mention what branch the chreeypicked fix should be a applied to (or rewritten for). Not sure how 31899 works ATM so I can't comment

**Comment by wxiaoguang** [comment]
> 1.what is shown/managed for issues that do have this information ? Will this break something for those instances that this was previously used one

Nobody knows at the momemt, that's why it needs to collect feedbacks. This info is only stored in database and displayed on the UI, no other logic.


>  2. How is this capability still realised (options were listed at in the OP)

For example: just write the branch/tag name in the issue title? then it is still "stored in database" and "displayed on the UI"


> Multiple LTS feature branches at different branching from MAIN...

It could also use other approaches, eg: labels, milestones, projects to bind an issue to a "feature"

**Comment by lunny** [comment]
Or maybe we can migrate the data to the new table in the coming PR. Then I need to support tag

**Comment by wxiaoguang** [comment]
> Or maybe we can migrate the data to the new table in the coming PR. Then I need to support tag

Why? Have you figured out how end users use that field? Is it certain that the Ref could be used in your PR?

**Comment by eeyrjmr** [comment]
> > 1.what is shown/managed for issues that do have this information ? Will this break something for those instances that this was previously used one
> 
> Nobody knows at the momemt, that's why it needs to collect feedbacks. This info is only stored in database and displayed on the UI, no other logic.
> 

so if it is only for display purposes then how it is being used presently can be complimented (honestly in my dev setup its only me that does this out of 4 of us :) ). Be it labels or text, yes there are ways to indicate to the wider team what branch to consider or what tag to check the issue again.  I am just nervous about what happens to the db etc if this is dropped/removed.

**Comment by wxiaoguang** [comment]
> I am just nervous about what happens to the db etc if this is dropped/removed.

So in 1.23 we only hide it, and will drop it in next release if it is not used.

**Comment by lunny** [comment]
Is this ready to review or merge?

**Comment by shugen002** [comment]
Few question , will the replacement #31899 block next release if this pr merged?

**Comment by lunny** [comment]
> Few question , will the new feature #31899 block next release if this pr merged? In the other word, can we make sure there is something to record a tag/branch in next branch.

I would like #31899 merged first.

**Comment by wxiaoguang** [comment]
> In the other word, can we make sure there is something to record a tag/branch in next branch.

This PR's question is: how do you use that branch/tag selector?

**Comment by lunny** [comment]
I moved #31899 from v1.23. And I think that will not be a block of this PR. The purpose is different. That PR added a development sidebar section to record which branches/commits/pull requests which resolved/will resolve the issue. But this feature is recording which branch does the issue happen.

**Comment by didim99** [comment]
> Anyone is really using that selector?

Yes! Our team uses this feature for more than 20 projects with many branches. When your repo has more than 2-3 branches with different stuff (features, refactoring, etc) developing on them, it is a really useful feature to specify a branch in which issue found.

**Comment by wxiaoguang** [comment]
> it is a really useful feature to specify a branch in which issue found.

@didim99 Thank you very much for the feedback, it is valuable. Just have some more questions, could you help us to understand more about "selector"?

* If it is used to "record the branch where a problem is found", what is the difference from "writing the branch name in issue title or description"? I can see the the branch selector's value isn't even searchable .... Could "using issue title/description to record the branch" be a feasible approach?
* Is "GitHub-like development sidebar (`#31899`)" good enough (or better) for your usage?
    * #31899

**Comment by wxiaoguang** [comment]
To avoid "breaking" in 1.23, I reverted the selector with the bug fix and added more comments. Then this PR could be merged, the discussion could be continued ( https://github.com/go-gitea/gitea/pull/32744#issuecomment-2540195359 ) to figure out how to improve the branch selector in the future.

**Comment by didim99** [comment]
@wxiaoguang

> what is the difference from writing the branch name in issue title or description

At first, it's a standardized approach to specifying a branch reference. Of course, using issue title/text can be a compromise solution, but it needs additional convention for team members to implement this (especially if we want to use this information for some automated pipelines, parsing a human written text is a terrible thing! At the moment I not sure in possibility to retrieve branch ref via API/webhook, but having a separate field seems better than text). Second, "selector" decreases chance of human-related mistakes such as typo (hello parsing, again). Also current implementation is good enough to handle branch renaming, clicking to branch link in issue list redirect you to actual (renamed) branch. And last (but not least), it's just convenient! You don't need to remember all branch names in repo or go to another page in another tab to find a branch name, just use selector!

> Is "GitHub-like development sidebar (#31899)" good enough (or better) for your usage? 

Actually, I'm not sure at the moment. I'm using Gitea (thanks, dev team, great work!) in 95% of time rather than Github in last three years. This new feature looks cool, but not sure it suitable to solve our task "specify a (existing) branch on which issue/task should be solved". I need some time to playing with this new approach to answer for your question.

Of course, I understand if maintainers decide remove this functionality without any replacement as unmaintanable/legacy/buggy stuff, but if you want to remove this only because "nobody uses this", please, no!

P. S. Our team using Gitea as global task tracker (not only for code, for everything), it's lightweight and easy to use, good enough for small team. We tried OpenProject and some other open source solutions, and Gitea's issues system wins.

**Pull request merged**
