### PR TITLE
Remove bsdtar

### PR DESCRIPTION
**Pull request by zeripath**
`bsdtar` on ubuntu 18.04 does not support `--no-xattrs`. This means it is unsuitable for
use and is currently breaking release.

This PR simply removes the `bsdtar` use from `.drone.yml` and changes the Makefile to allow users to set
`TAR="bsdtar --no-xattrs"` in future should they wish to use that.

Fix #14578 (again)

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]
jup

**Comment by CL-Jeremy** [comment]
#15256

**Comment by CL-Jeremy** [comment]
I'm apologizing again here. I wouldn't have thought it could even bork twice on CI even after many testing by then, and npm 7 was another big issue I had no idea about before. If only there were some sort of guidance on creating a similar CI workflow on my own fork (which has CI enabled on drone.io) I would have discovered these stuff long before.

**Comment by silverwind** [comment]
bsdtar removal is also included in https://github.com/go-gitea/gitea/pull/15273.

**Comment by 6543** [comment]
Since two mentioned pulls are not ready jet i propose: mergebthis first & let the other pulls be followups that can be checked & reviewed without blocking things

**Comment by silverwind** [comment]
I'd prefer the other one to be merged but if @zeripath would port the bsdtar changes from https://github.com/go-gitea/gitea/pull/15273 into here, we can merge this first.

**Pull request closed without merging**
