### PR TITLE
Fixes #794 by moving emoji tag to the correct span

### LINKED ISSUE #794: Emojis not rendered in release and commits tab
- Gitea version (or commit ref): latest
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/DeltaEvo/emoji/)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Emoji are not rendered in commit tab (see https://try.gitea.io/DeltaEvo/emoji/commits/master) and in release name (see https://try.gitea.io/DeltaEvo/emoji/releases). I think it's a bug because in all other places emojis are rendered (see https://try.gitea.io/DeltaEvo/emoji , https://try.gitea.io/DeltaEvo/emoji/issues , https://try.gitea.io/DeltaEvo/emoji/pulls )

### PR DESCRIPTION
**Pull request by evolvedlight**
Signed-off-by: Stephen Brown <steve@evolvedlight.co.uk>

This is a simple CSS fix for #794. Tested locally and works.

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
Trusted LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Pull request merged**
