### PR TITLE
Fix math and mermaid rendering bugs

### PR DESCRIPTION
**Pull request by silverwind**
1. Fix multiple error display for math and mermaid:

err

2. Fix height calculation of certain mermaid diagrams by reading the iframe inner height from it's document instead of parsing it from SVG:

Before:
Screenshot 2023-04-11 at 11 56 27

After:
Screenshot 2023-04-11 at 11 56 35

3. Refactor error handling to a common function
4. Rename to `renderAsciicast` for consistency
5. Improve mermaid loading sequence

Note: I did try `securityLevel: 'sandbox'` to make mermaid output a iframe directly, but that showed a bug in mermaid where the iframe style height was set incorrectly. Opened https://github.com/mermaid-js/mermaid/issues/4289 for this.

### CODE REVIEW

**Comment by silverwind** [comment]
I've also improved the mermaid loading sequence where previously it would sometimes flash the iframe background when many diagrams were present on the page. The `sandbox` attribute was removed because having both `allow-scripts` and `allow-same-origin` (which is necessary to measure dom height) is equivalent to no sandbox.

**Comment by silverwind** [comment]
No backport as it won't be a clean merge and the issues are rather minor.

**Review by lunny — APPROVED** [review]

**Review by HesterG — APPROVED** [review]

**Comment by techknowlogick** [comment]
🤖 🎺

**Comment by silverwind** [comment]
.

**Pull request merged**
