### PR TITLE
Add option to app.ini to enable local import paths

### PR DESCRIPTION
**Pull request by Bwko**
Adds #715

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by tboerger** [comment]
Why that? It's anyway only allowed to admins or people with the matching permission.

**Comment by Bwko** [comment]
@tboerger Some people (like myself) want to disable this feature altogether. Even though this feature is only "allowed to admins or people with the matching permission". I don't want my admins to import local directories.

**Comment by tboerger** [comment]
True, I have updated the label of the referenced issue, it's an enhancement but not something I would call a security issue

**Comment by Bwko** [comment]
I agree, i'ts only a minor security issue.
When you give a user the right to import local paths he/she can import other peoples private repo's. Do we want to add additional checks to prevent this?

**Pull request merged**
