### PR TITLE
List all branches and tags the commit exists in on diff page

### PR DESCRIPTION
**Pull request by CirnoT**
chrome_2020-12-20_18-03-11

chrome_2020-12-20_18-03-40

### CODE REVIEW

**Comment by CirnoT** [comment]
Marking as draft since I think we would need to have some interactive element, otherwise this list can get quite long really fast.

**Comment by silverwind** [comment]
That first screenshot, is that one commit tagged multiple times or is it also including future commit's tags?

**Comment by CirnoT** [comment]
It includes all tags and branches the commit is present in, similar to GH (https://github.com/go-gitea/gitea/commit/aaaaeb7050b57971b348665cced38a1a4fe61821)

**Comment by silverwind** [comment]
Hmm yes, we'd need some `first...last` expandable ui too.

**Comment by lafriks** [comment]
tag order should probably be in other order also

**Comment by lunny** [comment]
closed as it's outdated.

**Pull request closed without merging**
