### PR TITLE
ui: Add dividing line between heatmap and feeds in dashboard view

### PR DESCRIPTION
**Pull request by a1012112796**
I think it's necessary to add dividing line between heatmap and feeds in dashboard view, or the first items in feed is too near with heatmap which is not a good view.

from:

from

to:

to

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
why not just move the divider to the start of each of the feeds in templates/user/dashboards/feeds?

**Comment by a1012112796** [comment]
> why not just move the divider to the start of each of the feeds in templates/user/dashboards/feeds?

good, I didn't thought it. Thanks for your suggestion.

**Comment by a1012112796** [comment]
@lafriks I wander why move this pr to v1.13? 🤔

**Comment by mrsdizzie** [comment]
I think this should already work but there is a bug:

https://github.com/go-gitea/gitea/blob/5cf224abe3acd1e4336ec6672293397bc0e271de/templates/user/dashboard/heatmap.tmpl#L7-L8

The divider should be on the outside of the heatmap div. It should be moved there

**Comment by lunny** [comment]
@a1012112796 Since v1.12 will be rc1. All non-bug PRs should be moved to v1.13.

**Comment by a1012112796** [comment]
> I think this should already work but there is a bug:
> 
> https://github.com/go-gitea/gitea/blob/5cf224abe3acd1e4336ec6672293397bc0e271de/templates/user/dashboard/heatmap.tmpl#L7-L8
> 
> The divider should be on the outside of the heatmap div. It should be moved there

I see, I know the reason, That's because heatmap is generate by vue, whch will replace all message, so after loading, they will be changed.But I don't like add dividing line  in here. because if feeds is empty. dividing line is not necessary.
view:
image

**Comment by mrsdizzie** [comment]
I don't think it looks bad putting a divider line below the heatmap and having a completely empty feed seems pretty rare.

However if you disable heatmap having the divider line on top of feed looks bad because it comes right after another dividing line in the header and then will always look bad. 

Also that breaks general behavior of always having the dividing line below the element.

**Comment by a1012112796** [comment]
@mrsdizzie done

**Review by zeripath — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Pull request merged**
