### PR TITLE
ui: improve mobile review-box sizing

### PR DESCRIPTION
**Pull request by sapk**
On mobile, review is not possible because the button are on the left out of the screen.
This PR is using viewport unit for sizing the review-box.
(which is supported on most browser now https://caniuse.com/#feat=viewport-units)
This also add a scrollbar if needed to the editor bar.

<details>
<summary>After</summary>
<h4>On small screen the review box is kept inside the viewport:</h4>

<h4>On full screen nothing change:</h4>

</details>

<details>
<summary>Before</summary>
<h4>On small screen the review box is was outside the viewport:</h4>

<h4>On full screen nothing change:</h4>

</details>

### CODE REVIEW

**Comment by guillep2k** [comment]
Could you please add a height maximum as well? Since I use a larger DPI setting on my notebook (not mobile), the review buttons always get placed outside the screen (I can scroll down, however):

image

**Comment by sapk** [comment]
@guillep2k can we guard that for an other PR ? 
I have seen the same problem during testing but it easy to scrolldown to access the button.

**Comment by guillep2k** [comment]
> 
> 
> @guillep2k can we keep that for an other PR ?
> I have seen the same problem during testing but it easy to scrolldown to access the button.

OK, I can't do it myself because I don't have enough experience with CSS and its endless list of caveats. 😄

**Review by guillep2k — APPROVED** [review]

**Comment by sapk** [comment]
@guillep2k not an expert also so I try to limit to the strict minimum even on the css selector to not impact other element

**Review by lafriks — APPROVED** [review]

**Pull request merged**
