### PR TITLE
Fix the bug that user may logout if GetUserByID return unknow error

### PR DESCRIPTION
**Pull request by lunny**
backport #29962

This PR fixed a bug when the user switching pages too fast, he will logout automatically.

The reason is that when the error is context cancelled, the previous code think user hasn't login then the session will be deleted. Now it will return the errors but not think it's not login.

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I do not think it needs to be backported. Becaseu 1.21 uses `user_model.GetUserByID(db.DefaultContext`, it won't be canceled.

**Comment by lunny** [comment]
> I do not think it needs to be backported. Becaseu 1.21 uses `user_model.GetUserByID(db.DefaultContext`, it won't be canceled.

But it may return other errors like temporary network problems between Gitea and database. Should the user be logout because of that reason?

**Comment by wxiaoguang** [comment]
Then the title/description/comment don't match

**Comment by lunny** [comment]
> Then the title/description/comment don't match

Updated.

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
