### PR TITLE
Fix topics dropdown

### LINKED ISSUE #10160: Autocomplete of topics doesn't work anymore
- Gitea version (or commit ref): `1.12.0+dev-255-g70dd3faad` (current version on `try.gitea.io`)
- Git version: all
- Operating system: all
- Database (use `[x]`):
  - [?] PostgreSQL
  - [?] MySQL
  - [?] MSSQL
  - [?] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Autocomplete of topics doesn't work anymore. I [forked a repository and gave it the topic `girafe`](https://try.gitea.io/alexanderadam/girafe). When I try to type `g` `i` `r` `a` `f`… it won't be autocompleted anymore.

## Screenshots

Probably not helpful but here you are:
Screenshot_20200206_083917

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #10160

Related to fomantic switch, so needs a backport as well.

Note that `{variable}` is semantic syntax, not JS `${variable}`

### CODE REVIEW

**Review by silverwind — APPROVED** [review]
Seems correct according to https://semantic-ui.com/modules/dropdown.html#match-search-query-on-server

**Review by zeripath — APPROVED** [review]
Presumably fomantic is doing the encodeUriComponent itself?

**Comment by silverwind** [comment]
> Presumably fomantic is doing the encodeUriComponent itself?

I think fetch/XHR do that automatically in any case.

**Comment by alexanderadam** [comment]
Awesome, thank you for this fast fix! :pray:

**Pull request merged**
