### PR TITLE
Fix scrollable header on dropdowns

### LINKED ISSUE #11865: Branch/Tag selector is scrollable
Reproducible on any repository on https://gitea.com/ and https://try.gitea.io/

## Description

There is a scroll bar on the branch/tag selector and you can scroll down.
When you scroll down the text is not readable.

## Screenshots
Anmerkung 2020-06-12 125040

**This is how it looks when scrolled down:**
Anmerkung 2020-06-12 125105

### PR DESCRIPTION
**Pull request by CirnoT**
Fix #11865

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping LG-TM

**Comment by lafriks** [comment]
Does this needs backporting?

**Comment by silverwind** [comment]
Pretty sure it does.

**Comment by lafriks** [comment]
please send backport

**Pull request merged**
