### PR TITLE
Allow custom profile repository name

### PR DESCRIPTION
**Pull request by a1012112796**
As title.

### CODE REVIEW

**Comment by a1012112796** [comment]
nobody see this pull request? sad :(

**Comment by wxiaoguang** [comment]
> nobody see this pull request? sad :(

How about helping to review some other PRs? For example, review my PRs, then I could review back.

**Comment by lunny** [comment]
> nobody see this pull request? sad :(

I want to why this custom name is necessary. Why not just use the default one?

**Comment by delvh** [comment]
Yes, but why?
It makes the logic much more complicated, and I don't see a reason for it.
What's so bad about having one path where it is always expected?
On the contrary, it makes it harder for others to guess where your profile repo is located, i.e. if they want to copy something from your bio in raw markdown.

**Comment by a1012112796** [comment]
> Yes, but why?
> It makes the logic much more complicated, and I don't see a reason for it.
> What's so bad about having one path where it is always expected?
> On the contrary, it makes it harder for others to guess where your profile repo is located, i.e. if they want to copy something from your bio in raw markdown.

Okay, I see, maybe you are right.   But still a little wonder about why the name of 'pofile repository' must be `.profile`?  Who rulered it?  the government or laws?  a little sad about the gitea become `closing`

**Comment by lunny** [comment]
> > Yes, but why?
> > It makes the logic much more complicated, and I don't see a reason for it.
> > What's so bad about having one path where it is always expected?
> > On the contrary, it makes it harder for others to guess where your profile repo is located, i.e. if they want to copy something from your bio in raw markdown.
> 
> Okay, I see, maybe you are right. But still a little wonder about why the name of 'pofile repository' must be `.profile`? Who rulered it? the government or laws? a little sad about the gitea become `closing`

Discussion is here https://github.com/go-gitea/gitea/issues/12233 .
I don't think it's `closing`, as a product, we have to chose to do something and not do something.

**Comment by a1012112796** [comment]
> I don't think it's closing, as a product, we have to chose to do something and not do something.

In my view. An open software should be more and more configable , cuttable and extensible. in other words it meanings user should have abilty to using this softerware in any ways they like. a completely immutable product is unlikely to adapt to the needs of the all users it uses.

**Comment by lunny** [comment]
> > I don't think it's closing, as a product, we have to chose to do something and not do something.
> 
> In my view, An open software should be more and more configable , cuttable and extensible. in other words it meanings user should have abilty to using this softerware in any ways they like. a completely immutable product is unlikely to adapt to the needs of the all users it uses.

I don't think so. Back to the code, gitea does not allow users to define user-level `.gitea` folder's name and `README`'s name and so on. These should be hard-code, otherwise it will make code too hard to maintain.

**Comment by delvh** [comment]
> In my view, An open software should be more and more configable , cuttable and extensible

Yes, **at points where it makes sense**.
However, over-configurability is also a thing.
I have no problem with a setting when there are valid usecases/concerns.
But `I want it` is not a valid concern for it, unless you can give me a practical reason for it.
If we make **everything** configurable, no one wants to use Gitea either.

**Comment by wxiaoguang** [comment]
I like the idea of "keep it simple" and Occam's razor https://en.wikipedia.org/wiki/Occam%27s_razor

**Pull request closed without merging**
