### PR TITLE
default show closed actions list if all actions was closed

### PR DESCRIPTION
**Pull request by a1012112796**
as title, that's same with issues and pull list
image

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by yp05327** [comment]
``` golang
if (ctx.FormString("state") == "open" && numOpenRuns != 0) || (numClosedRuns == 0  && ctx.FormString("state") != "cloesd") {
    // show open runs
} else {
    // show closed runs
}
```
Maybe one `if` is enough?

**Comment by yardenshoham** [comment]
> ```go
> if (ctx.FormString("state") == "open" && numOpenRuns != 0) || (numClosedRuns == 0  && ctx.FormString("state") != "cloesd") {
>     // show open runs
> } else {
>     // show closed runs
> }
> ```
> 
> Maybe one `if` is enough?

If `ctx.FormString("state") == "open"` we should show the open runs, even if there are none

**Comment by wolfogre** [comment]
Why not follow the logic of the issue page?

https://github.com/go-gitea/gitea/blob/5e389228f61844c0d59d5bc5974483dae0aa1b8b/routers/web/repo/issue.go#L224-L228

**Comment by a1012112796** [comment]
> Why not follow the logic of the issue page?
> 
> https://github.com/go-gitea/gitea/blob/5e389228f61844c0d59d5bc5974483dae0aa1b8b/routers/web/repo/issue.go#L224-L228

Hasn't read them before, but I think the result is same, isn't it?

**Comment by wolfogre** [comment]
> Hasn't read them before, but I think the result is same, isn't it?

I'm not sure.

image

What if `state == closed` and `numOpenRuns == numClosedRuns == 0`?

**Review by techknowlogick — APPROVED** [review]

**Comment by silverwind** [comment]
@wolfogre looking good?

**Review by wolfogre — APPROVED** [review]

**Pull request merged**
