### PR TITLE
Clean up and fix clone button script (#20415 & #20600)

### PR DESCRIPTION
**Pull request by silverwind**
Backport #20415 and #20600 to 1.17.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
-> #20558

**Comment by 6543** [comment]
waiting for issue to be closed ...

**Comment by silverwind** [comment]
Issue is actually not related to this PR. The "regression" happened earlier.

**Review by 6543 — APPROVED** [review]

**Comment by silverwind** [comment]
Fix for missing default in https://github.com/go-gitea/gitea/pull/20600.

**Comment by silverwind** [comment]
I've pushed https://github.com/go-gitea/gitea/pull/20600 onto here as well, so this is now backporting 2 PRs :)

**Review by noerw — APPROVED** [review]

**Pull request merged**
