### PR TITLE
verify nodeinfo response by schema 

### PR DESCRIPTION
**Pull request by MFTabriz**
... using [github.com/xeipuuv/gojsonschema](https://github.com/xeipuuv/gojsonschema)

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thank you for this PR! Extra test cases are always appreciated. Rather than adding this in as you have, could you validate the schema in the existing way we already do for openapi/swagger? That way we match with existing norms, and don't need to add in an additional external dependencies (CLI tools are treated separately than go modules).

I'm happy to provide advice answer any questions you may have about this other direction.

**Comment by MFTabriz** [comment]
> Thank you for this PR! Extra test cases are always appreciated. Rather than adding this in as you have, could you validate the schema in the existing way we already do for openapi/swagger? That way we match with existing norms, and don't need to add in an additional external dependencies (CLI tools are treated separately than go modules).
> 
> I'm happy to provide advice answer any questions you may have about this other direction.

Hi @techknowlogick! Thanks for your helps. After checking out `tests/` and also CI pipelines, I couldn’t find what you are referring too. Can you please give me a pointer/link to check out? I will adapt this test to follow the others.

**Comment by techknowlogick** [comment]
> Hi @techknowlogick! Thanks for your helps. After checking out `tests/` and also CI pipelines, I couldn’t find what you are referring too. Can you please give me a pointer/link to check out? I will adapt this test to follow the others.

Even though I wrote the nodeinfo endpoint I have confused it with a different code section. As I went through writing a reply to you, and tracing everything I have discovered my mistake, and the way you are doing it is the way that we should proceed with. Sorry about my confusion.

For reference sake, here is the content of the comment that I had started to write:
```
Happy to help :) You can see the `checks-backend` makefile command https://github.com/go-gitea/gitea/blob/main/Makefile#L335-L336

Which calls `swagger-check` https://github.com/go-gitea/gitea/blob/main/Makefile#L301-L322 where it generates the swaggerfile and does a diff.

With nodeinfo, you could pr...(this is where I realized my mistake)
```

**Review by zeripath — APPROVED** [review]

**Comment by MFTabriz** [comment]
@techknowlogick by the way, nodeinfo response was already schema-conforming. Also, Gitea got added to the [list of nodeinfo-supporting software](https://nodeinfo.diaspora.software).

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@MFTabriz that's great! thanks again :)

**Pull request merged**
