### PR TITLE
add tooling dependencies

### PR DESCRIPTION
**Pull request by coolaj86**
This demonstrates how to lock down to specific versions of the tooling dependencies, rather than potentially getting a different version of tooling dependencies each time.

It also allows the dependencies to be run with `go run -mod=vendor` in the future, meaning greater consistency between platforms, faster deploys via docker, drone, etc.

We may not want _all_ of the tooling locked down like this, but I think it would be particularly helpful for `go-bindata` (anything that's part of `go:generate`, for sure).

### CODE REVIEW

**Comment by solderjs** [comment]
This is the particularly important part:

https://github.com/go-gitea/gitea/pull/6565/files#diff-f0e0c1740f44d2288ec4c6976535d50e

**Comment by zeripath** [comment]
You probably need to run make vendor and commit the result to get the ci to run.

**Comment by solderjs** [comment]
I just want to open this for discussion as to whether or not it's desirable.

The advantages that come from it (aside from locking down the version) can't be fully realized until the minimum Go version is 1.11.

As long as it's Go 1.10, we can't even get the speed-up from having it all pre-downloaded.

**Comment by solderjs** [comment]
Thoughts?

**Comment by lafriks** [comment]
I'm for locking also tool versions and vendoring them

**Comment by solderjs** [comment]
> I'm for locking also tool versions and vendoring them

Both this and the `remove sed` PR will be easiest to accomplish once the decision is made that explicit support for go1.10 and below is not necessary.

I realize some of the lint-style tooling still requires earlier versions, but that's not necessary for building and contributing in general.

**Comment by lunny** [comment]
The change is too big that made it difficult to review.

**Comment by solderjs** [comment]
@lunny I think you misunderstood what the change is.

There was **only one** change, which was to add tooling dependencies:

* https://github.com/go-gitea/gitea/pull/6565/files#diff-37aff102a57d3d7b797f152915a6dc16

Everything else is locking down dependencies in `vendor/`

However, this is way out of date. It looks like someone has since added files to vendor.

**Comment by solderjs** [comment]
@lunny:

Rebased

* **1 file change**: add tooling dependencies - e5daaa9
* **Dependencies Updated**: go mod tidy; go mod vendor c2f5004
* **Missing Dependencies Resolved**: update vendor/ ed53c16

**Comment by lunny** [comment]
We have used `vsfgen` instead `go-bindata`. And could you also change Makefile to use -mod=vendor ?

**Comment by solderjs** [comment]
I think we decided that we can't change the Makefile until after the 1.9 release due to some issues with previous versions of Go that are till supported.

Once we drop support for GOPATH and use Go modules exclusively I'll circle back around to this and the PR for removing `sed`.

**Comment by lunny** [comment]
Since v1.9 branch is created, could you resolve the conflicted files?

**Comment by 6543** [comment]
https://github.com/Masterminds/glide was recommended to me for dependencie management ...

**Comment by solderjs** [comment]
@6543 
* https://www.youtube.com/watch?v=F8nrpe0XWRg
* https://github.com/golang/go/wiki/Modules
* https://blog.golang.org/using-go-modules

Go now has the best module system on the planet, nay, the universe.

**Comment by 6543** [comment]
ok you got me

**Comment by kolaente** [comment]
> the best module system on the planet, nay, the universe.

Ever used composer?

**Pull request closed without merging**
