### PR TITLE
Release API endpoints

### PR DESCRIPTION
**Pull request by ethantkoenig**
Adds the following endpoints:
- `GET /repos/:user/:repo/releases`: List a repository's releases
- `GET /repos/:user/:repo/releases/:id`: Get a release
- `POST /repos/:user/:repo/releases`: Create a new release
- `PATCH /repos/:user/:repo/releases/:id`: Edit a release
- `DELETE /repos/:user/:repo/releases/:id`: Delete a release

See also https://github.com/go-gitea/go-sdk/pull/31, #330

### CODE REVIEW

**Comment by bkcsoft** [comment]
https://developer.github.com/v3/repos/releases/

**Comment by ethantkoenig** [comment]
@bkcsoft Updated to include changes to https://github.com/go-gitea/go-sdk/pull/31

**Comment by lunny** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
