### PR TITLE
Use ErrKeyUnableToVerify if fail to calc fingerprint in ssh-keygen

### LINKED ISSUE #3985: Provide more meaningful error message when adding SSH keys fails
- Gitea version (or commit ref): 1.4.1
- Git version: 2.16.2
- Operating system: Windows Server 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When trying to add a SSH key to a user profile, any type of failure with the `ssh-keygen` command returns a generic HTTP 500 error to the UI (screenshot attached). In the log you can see what the actual error was, but none of this info is conveyed to the end user.

Reason: Path to ssh-keygen not configured correctly
`2018/05/16 17:00:23 [...ters/user/setting.go:430 SettingsKeysPost()] [E] AddPublicKey: 'ssh-keygen -lf C:\Windows\TEMP\gitea_keytest659272622' failed with error 'exec: "ssh-keygen": executable file not found in %PATH%': `

Reason: SSH key is not a valid public key - OR - the key is password protected
`2018/05/16 17:04:14 [...ters/user/setting.go:430 SettingsKeysPost()] [E] AddPublicKey: 'ssh-keygen -lf C:\Windows\TEMP\gitea_keytest763165203' failed with error 'exec(4:AddPublicKey) failed: exit status 255(<nil>) stdout:  stderr: C:\\Windows\\TEMP\\gitea_keytest763165203 is not a public key file.
': C:\\Windows\\TEMP\\gitea_keytest763165203 is not a public key file.`

It would be helpful to have a better error message returned to the user instead of a generic HTTP 500 error (e.g. "Invalid public key or key is password protected", "Path to ssh-keygen is invalid. Contact administrator", etc.)

## Screenshots
sshkey-500error

### PR DESCRIPTION
**Pull request by zeripath**
Fix #3985

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by sapk — APPROVED** [review]
Looks good to me but would be better with a new test case here:
https://github.com/go-gitea/gitea/blob/f9f2c163b12f60a6bf9c3652cdc4bdf59e3d53c4/models/ssh_key_test.go#L159
 and even better with an integration test using : 
https://github.com/go-gitea/gitea/blob/f9f2c163b12f60a6bf9c3652cdc4bdf59e3d53c4/integrations/api_helper_for_declarative_test.go#L140:6

**Comment by zeripath** [comment]
unfortunately I don't have an example otherwise I'd have done the tests

**Comment by zeripath** [comment]
I found one in https://github.com/Ganapati/RsaCtfTool/blob/master/examples/weak_public.pub#L1

**Comment by sapk** [comment]
@zeripath I have created a rsa 1023 bit public key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgFSbX7pXBc5xW5ByF4RB6Lr8HbfW0/LXq90UjWpRSR6z+HEfN/4m8jRF5Vl/GCtu86YSi9au1TeZ0kHgTTCgQIv5vc+zZJkx4mbzpQ+WzEYB9SET4W3AZBv3diJVXQX6KuMICgq30PeVB4PsZoyBasjSS422pCCgFDpH/l6JgYlJ
```

**Comment by sapk** [comment]
I have just seen your message and you can use either. 
I have tested the key I provided with ssh-keygen:
```
ssh-keygen -lf rsa_test.pub
rsa_test.pub is not a public key file.
```

**Comment by zeripath** [comment]
OK so the issue is that calcFingerprintNative will happily parse both of those keys but calcFingerprintSSHKeygen will not.

**Comment by zeripath** [comment]
Happily however, testing with both those keys has shown to me that I missed passing up the error upstream.

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
So I've discovered that `CheckPublicKeyString` doesn't seem actually checking the length correctly.

**Comment by zeripath** [comment]
Ah, if we have Native SSH key gen we should probably have the minimum key sizes set by default to at least what they are in ssh keygen

**Comment by sapk** [comment]
@zeripath yes the standard go lib for rsa is not restricting size (we should check it).
That how I generate the rsa for the test.

**Pull request merged**
