### PR TITLE
Add init file for Ubuntu

### PR DESCRIPTION
**Pull request by Lycolia**
Created an init file for Ubuntu that will be useful when running it on WSL.

### CODE REVIEW

**Comment by wolfogre** [comment]
I'm not familiar with WSL. Could you please show me more context?

**Comment by Lycolia** [comment]
WSL stands for Windows Subsystem for Linux, a convenient tool that allows native Linux command-line tools to be run directly on Windows and is utilized by many developers. Ubuntu is generally the preferred distribution for WSL, and solution for such users. Since the use of systemd can cause problems in this environment, I chose as a solution to create an init file that can be used more simply as a daemon. It should also work fine on native Ubuntu.

**Comment by silverwind** [comment]
Is there a difference between the debian file and this one?

**Comment by Lycolia** [comment]
Yep has difference.
The method of set environment variables at start is different. 
Environment variables are not setled correctly with the Debian file, and I get the following error
> …s/setting/setting.go:656:loadFromConf() [F] Failed to get home directory: cannot get home directory

FYI: Debian files may not work on Debian.
https://github.com/go-gitea/gitea/issues/9541

Also I'm an Ubuntu user so I made it as Ubuntu file.

**Comment by silverwind** [comment]
OK I guess we can leave the debian script, those two OS do sometimes work differently.

**Review by silverwind — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖

**Pull request merged**
