### PR TITLE
Fix dependency link rendering in PR sidebar

### PR DESCRIPTION
**Pull request by justusbunsi**
Signed-off-by: Steven Kriegler <61625851+justusbunsi@users.noreply.github.com>

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lunny** [comment]
It's not a bug, it will automatically redirect to the right URL.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> It's not a bug, it will automatically redirect to the right URL.

indeed, the autoredirect is a very nice feature. not sure what exactly this PR was fixing.
possibly all the change will do (again) is pose issues with redirecting to external pulls.
now, truthfully, I am yet to test this change but I recall having issues with similar stuff before, in particular with mirrored repos where PRs were disabled and issues were pointed to the remote repo's issue index.

**Comment by justusbunsi** [comment]
The redirect feature is a great one. That's true. This PR faces an issue with external issue trackers. If configured, the redirect feature seems to not always correctly separate issues from pulls. In this particular case it identifies a link pointing to a pull request as an issue reference and therefore redirects to the external tracker.

I agree that the fix might not be the best. Maybe I should've identified the issue inside the redirect feature instead of this change. 🤔

**Comment by zeripath** [comment]
Sorry @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I forgot about your case. 

Unfortunately I think this needs to be reverted. What were you trying to fix @justusbunsi?

**Comment by justusbunsi** [comment]
@zeripath 
> This PR faces an issue with external issue trackers. If configured, the redirect feature seems to not always correctly separate issues from pulls. In this particular case it identifies a link pointing to a pull request as an issue reference and therefore redirects to the external tracker.

Given a repository with "External Issue Tracker" configured and having two PRs where PR 1 is added as dependency for PR 2. If you open the discussion page of PR 2 and have a look at the right sidebar, you can click on the dependency (which is PR 1). Without this fix, I get redirected to the external tracker instead of navigated to the PR 1 page in Gitea.

image

It's ok to revert, if this breaks others environments. I guess, we need to identify the actual root cause of my described behavior and fix it, since it's a generic problem for links when an external issue tracker is configured.

**Comment by zeripath** [comment]
I guess what we need is @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf to try this on their configuration to double check that this PR has broken things...

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
thank you both for considering me, yay.
 
alright, I have checked and this does not break my use case, I suppose that is because my mirrors in fact have the PR pages disabled.
sorry if I caused too much of a stir.

on closer look, I still think a better suited place for a more complete solution *might* have been the issue router redirection logic.
happy this fix solved your issue, though, @justusbunsi

**Comment by zeripath** [comment]
Cool ... we can all stand-down!

**Comment by zeripath** [comment]
Thanks @justusbunsi for the fix.

**Pull request merged**
