### PR TITLE
Remove less/_repository.less 

### PR DESCRIPTION
**Pull request by wxiaoguang**

### CODE REVIEW

**Review by delvh — APPROVED** [review]
When was that re-added?
I don't have it on my local state that's at most a hundred commits behind main…

**Review by lunny — APPROVED** [review]
Because #23508 missed this file.

**Review by yardenshoham — CHANGES_REQUESTED** [review]
This is on v1.19

**Review by silverwind — APPROVED** [review]
Seems this was missed somehow.

**Pull request merged**
