### PR TITLE
docs: add SSH passthrough instructions to with-docker-rootless (#17505)

### LINKED ISSUE #17505: Add tested rootless SSH passthrough configuration to the docs
### Feature Description

I found a simple and effective way to set up an SSH passthrough that works with the rootless docker image. It leverages the AuthorizedKeysCommand configuration in sshd, and doesn't require mounting the `~/.ssh` directory or synchronizing the `authorized_keys` file between host and container. It also works fine with the internal gitea ssh server.

I've tested it under podman, but it should work with docker as well. I can write and submit a PR for the rootless documentation.

I suspect it would also work for the rootfull docker image, but haven't tested. It's a lot simpler to setup than the current method, so if valid it could also replace it.

The details are as follows for podman, but will likely work for docker by just changing the binary name:

In the host, create an executable containing the following, replacing <container-name> with the actual name of the container:
```bash
# cat /usr/bin/gitea-shell
#!/bin/bash
/usr/bin/podman exec -i --env SSH_ORIGINAL_COMMAND="$SSH_ORIGINAL_COMMAND" <container-name> bash "$@"
```

Then set it as the shell for the gitea user (`git` in this case) on the host:
```bash
# usermod -s /usr/bin/gitea-shell git
```

Finally add the following to `/etc/ssh/sshd_config`, also replacing <container-name> with the actual container name:
```bash
Match User git
  AuthorizedKeysCommandUser git
  AuthorizedKeysCommand /usr/bin/podman exec -i <container-name> /usr/local/bin/gitea keys -c /etc/gitea/app.ini -u %u -t %t -k %k
```

Don't forget to restart sshd for these settings to take effect:
```bash
# systemctl restart sshd
```

And that's it.

EDIT: forgot to remove the `-t` options from `podman exec`. These can modify the output and break the git protocol.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by rmsc**
The passthrough is based upon AuthorizedKeysCommand and a custom shell wrapper that forwards commands to the container.

Close #17505

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
Thanks for contributing this PR :)

**Comment by zeripath** [comment]
I'm slightly confused here.

The results of the AuthorizedKeysCommand will be a line like:

```
command="/path/to/gitea/in/docker/container --config=/path/to/app.ini serv key-1",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAA... user@localhost
```

The host SSH would then attempt to run that command. 

How are you ensuring that that command can be run?

I worry that the `gitea-shell` you're suggesting here implies that your host isn't running the `command`? (or more likely this is only working because you still have an `/app/gitea/gitea` shadow on the host.)

---

I think your passthrough idea is trying to suggest a different kind of passthrough.

The original docs suggested:

```
 client -- SSH --> host -- SSH --> gitea_container. 
```

These appear to be trying to do: 

```
client -- SSH --> host -- docker --> gitea_container
```

Is that right?

--- 

If so, then instead of the shadow `/app/gitea/gitea` being a SSH passthrough you'd simply need to be a docker passthrough 
like your `gitea-shell` idea.

Your docker shell idea could simply shadow `/app/gitea/gitea` and it would all just work.

---

Other thoughts:

If actual network passthrough was desired, there is nothing preventing you from having the gitea executable on the host system with an app.ini that has a different `[server]` `SSH_AUTHORIZED_KEYS_COMMAND_TEMPLATE` and appropriate `INTERNAL_ROOT_URL`. `gitea keys` simply communicates over HTTP with the running gitea server at `/api/private/ssh/authorized_keys`. (You could not run the `gitea serv` command directly though.)

**Comment by rmsc** [comment]
> The host SSH would then attempt to run that command.

Not exactly, the host SSH would pass it verbatim as an argument to `gitea-shell -c`. Which would run it **in the container**.

> 
> How are you ensuring that that command can be run?

I'm not. In the end the command is passed to the container. If it fails, it fails there and never on the host.

```
/usr/bin/docker exec -i --env SSH_ORIGINAL_COMMAND="$SSH_ORIGINAL_COMMAND" gitea sh "$@"
```

The shell wrapper above then calls `docker exec`, which runs `sh "$@"` inside the container, not on the host.

When cloning a repo, for instance, what ends up happening is that the following is run **inside** the gitea container:

```
SSH_ORIGINAL_COMMAND="git-upload-pack 'user/repo.git'" sh -c "/path/to/gitea/in/docker/container --config=/path/to/app.ini serv key-1"
```

> 
> I worry that the `gitea-shell` you're suggesting here implies that your host isn't running the `command`? (or more likely this is only working because you still have an `/app/gitea/gitea` shadow on the host.)

I hope the above clarifies how this works. I never had an `/app/gitea/gitea` in the first place :smile:

> I think your passthrough idea is trying to suggest a different kind of passthrough.
> (...)
> Is that right?

Yes, I suppose so.

> 
> If so, then instead of the shadow `/app/gitea/gitea` being a SSH passthrough you'd simply need to be a docker passthrough like your `gitea-shell` idea.
> 
> Your docker shell idea could simply shadow `/app/gitea/gitea` and it would all just work.

I suppose that might work, BUT:

- Having an `/app/gitea/gitea` on the host feels like a hack. It's a fixed hardcoded non-standard path, whereas the shell wrapper could be anywhere and still work.
- A shell wrapper runs **all** commands inside the container, which is more secure. Having a shadowed `gitea` on the host means that if a malicious entity could somehow override the `command` in `authorized_keys` (say by hacking the SSH_AUTHORIZED_KEYS_COMMAND_TEMPLATE), it could run other commands on the host's shell. This definitely defeats the benefits of having containers in the first place.

> 
> Other thoughts:
> 
> If actual network passthrough was desired, there is nothing preventing you from having the gitea executable on the host system with an app.ini that has a different `[server]` `SSH_AUTHORIZED_KEYS_COMMAND_TEMPLATE` and appropriate `INTERNAL_ROOT_URL`. `gitea keys` simply communicates over HTTP with the running gitea server at `/api/private/ssh/authorized_keys`. (You could not run the `gitea serv` command directly though.)

I don't think having a `gitea` executable on the host is desirable at all when running a containerized system.

That said, I can see a network passthrough being needed between different hosts. Perhaps your suggestion above could be made to work with a containerized gitea on the 'gateway' host?

**Comment by zeripath** [comment]
> > The host SSH would then attempt to run that command.
> 
> Not exactly, the host SSH would pass it verbatim as an argument to `gitea-shell -c`.

Aha! I'd forgotten that the the user's shell is used to parse the `command`. This now makes sense.

> > I think your passthrough idea is trying to suggest a different kind of passthrough.
> > (...)
> > Is that right?
> 
> Yes, I suppose so.

OK we should probably be explicit that this will require that the host `git` user needs to be allowed to run `docker exec`. This may/may not be the default.

> >Other thoughts:
> >
> > If actual network passthrough was desired, there is nothing preventing you from having the gitea executable on the host system with an app.ini that has a different [server] SSH_AUTHORIZED_KEYS_COMMAND_TEMPLATE and appropriate INTERNAL_ROOT_URL. gitea keys simply communicates over HTTP with the running gitea server at /api/private/ssh/authorized_keys. (You could not run the gitea serv command directly though.)
>
> ...
>
> That said, I can see a network passthrough being needed between different hosts. Perhaps your suggestion above could be made to work with a containerized gitea on the 'gateway' host?

You could use a combination of the two techniques. IIRC the AuthorizedKeysCommand is run by root - so you should be able to use the docker shell technique to run gitea keys but just pass a different `app.ini` that has the SSH_AUTHORIZED_KEYS_COMMAND_TEMPLATE to use the network passthrough ssh command which doesn't have to refer to apppath at all.

**Comment by rmsc** [comment]
> OK we should probably be explicit that this will require that the host `git` user needs to be allowed to run `docker exec`. This may/may not be the default.

That's a good point, thanks! I'll update the documentation.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
