### PR TITLE
Fix misaligned button in settings

### PR DESCRIPTION
**Pull request by garritfra**
I noticed that the buttons in the LFS tab of the settings is slightly misaligned when compared to the rest of the tabs. This was due to icons that were not scaled properly. 

Every other tab does not display icons, so I figured they probably shouldn't be there anyway to keep the UI consistent.

### Before

image

### After

image

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

**Comment by bagasme** [comment]
> I noticed that the buttons in the LFS tab of the settings is slightly misaligned when compared to the rest of the tabs. This was due to icons that were not scaled properly.
> 
> Every other tab does not display icons, so I figured they probably shouldn't be there anyway to keep the UI consistent.
> ### Before
> 
> image
> ### After
> 
> image

I don't see any misalignment in before, however

**Review by silverwind — APPROVED** [review]

**Comment by KN4CK3R** [comment]
> I don't see any misalignment in before, however

Not the icon is misaligned in the button but the button in the header.

**Comment by garritfra** [comment]
@bagasme The icons are too large for the button, so they stretch it out vertically. "Alignment" is maybe the wrong word here. What I'm referring to is the position of the button inside it's surrounding component.

**Comment by silverwind** [comment]
It misaligns because `ui right` absolutely positions the button. A better fix ought to be to remove this absolute positioning but I guess that would be a more involved change as it affects many places.

**Comment by techknowlogick** [comment]
🚀

**Pull request merged**
