### PR TITLE
Fix data-race problems in git module (quick patch)

### PR DESCRIPTION
**Pull request by wxiaoguang**
This patch is somewhat hacky, it might be the most simple one to resolve the data-race problem in `git.Init`.

Details:

Before git refactoring: `git.Init` was only called once in `GlobalInitInstalled`, which is incomplete, because the tests also need to init the git module.

With the last git refactoring #19732: `git.Init` was called in  `GlobalInitInstalled` and many `prepareTestEnv` functions, but `git.Init` changes many global variables, then it leads to data-race problem.

This PR: introduce `git.InitOnceWithSync` which only changes the global variables once, just like what [git.CheckLFSVersion](https://github.com/go-gitea/gitea/blob/52c2e82813c2519cd08c9ecd66ef7b0815682770/modules/git/lfs.go#L17)  does.

Although this PR is not ideal and hacky, (hopefully) it should work and be enough for 1.17 release. In the future, the setting related code should be refactored (eg: by using `atomic.Value`), including the `git.CheckLFSVersion`.

### CODE REVIEW

**Comment by zeripath** [comment]
By using a sync.Once we're limited to configuring this function once and once only per run (which is fine for Gitea as we are currently) but this also applies to the tests too.

Any attempt to call this function to reconfigure will fail but that means it could be possible that a different order of calling Tests could cause a different configuration to be set.

So ... the first function calling this Init should probably be being called from within the TestMain(s) to ensure that there is a consistent configuration.

**Comment by wxiaoguang** [comment]
> By using a sync.Once we're limited to configuring this function once and once only per run (which is fine for Gitea as we are currently) but this also applies to the tests too.

Yes, but the same problem to [git.CheckLFSVersion](https://github.com/go-gitea/gitea/blob/52c2e82813c2519cd08c9ecd66ef7b0815682770/modules/git/lfs.go#L17)  ......

Without a big refactoring, the problem can not be resolved clearly.

**Comment by wxiaoguang** [comment]
Why I think this PR is enough:

Before refactoring:
* Gitea web: call git.Init once
* Gitea serv: no call to git.Init
* Test code: no call to git.Init before `GlobalInitInstalled` (which calls git.Init)

After the refactoring and this PR:
* Gitea web: call git.InitOnceWithSync once, it can be guaranteed to be correct
* Gitea serv: call git.InitSimple once, not bad, no side effect
* Test code: call git.InitOnceWithSync in `prepare` with the same settings as `GlobalInitInstalled`, and at the moment everything works fine.

Indeed, the situation of refactoring the git module is more complex than I thought. IMO at the moment it's impossible to achieve the ideal status with a few PRs, especially there is a blocker in `git.CheckLFSVersion`, the changing to them will cause a lot of changed code.

And I am open to learn ideas about how to make the git module better.

**Review by zeripath — APPROVED** [review]
I guess we're somewhat forced to do the syncOnce here.

**Review by lunny — APPROVED** [review]

**Pull request merged**
