### PR TITLE
Use next gen codecov uploader

### PR DESCRIPTION
**Pull request by 6543**
current plugin do use https://github.com/codecov/codecov-bash witch will stop working on **On February 1, 2022**

### CODE REVIEW

**Comment by techknowlogick** [comment]
Does anyone of us use the codecov report? Maybe we should remove it instead? Cc: @go-gitea/owners

**Comment by lunny** [comment]
It will not work after we moved to gitea.com and I have sent email to codecov to ask them to support Gitea but they rejected that time.

**Comment by 6543** [comment]
I would say with switching to gitea.com - we should switch to a self-hosted code coverage explorer ... there exist some but i did not test them

**Comment by lunny** [comment]
But he recommend https://github.com/codecov/uploader ?

**Comment by 6543** [comment]
yes https://github.com/woodpecker-ci/plugin-codecov is exact that just a wrapper to be a plugin for drone/woodpecker

**Comment by 6543** [comment]
> But he recommend https://github.com/codecov/uploader ?

**who** did?

**Comment by silverwind** [comment]
Why even have a external service like this? For example with jest, one can just do a text-only output of the coverage report, which works offline as well as directly in the CI.

> move to gitea.com

What's the plan here? I think it's better to stay on GH for the overall project health.

**Comment by lunny** [comment]
> Why even have a external service like this? For example with jest, one can just do a text-only output of the coverage report, which works offline as well as directly in the CI. I think it's better to not depend on an external service.
> 
> > move to gitea.com
> 
> What's the plan here? I think it's better to stay on GH for the overall project health.

The first big stage is Gitea hosted Gitea.

**Comment by 6543** [comment]
https://alternativeto.net/software/codecov-io/?platform=self-hosted
-> https://github.com/danhper/opencov

**Review by zeripath — APPROVED** [review]
I think codecov could still be useful - but equally I don't particularly use the reports.

I'm gonna approve this because if we don't do this this drone step will fail and break all of our CI in 2 days time.

However, I would equally consider approving a PR that removed it.

**Comment by zeripath** [comment]
We'll need backports of this or the removal PRs too. So we need to get a decision in in the next 2 days.

**Review by techknowlogick — APPROVED** [review]
+1 to what zeripath said. I don't use this, but would prefer our builds don't break. Let's discuss future options for either removing or using a different service elsewhere

**Comment by 6543** [comment]
I'll remove it on the release branches (v1.16 & v1.15) ... - and will **merge this** - we should talk about what's next ... once backports done I'll open an issue for it

**Comment by 6543** [comment]
:rocket:

**Comment by 6543** [comment]
PS: we dont need to remove it in release branches -> because it get skiped:

```yml
    when:
      branch:
        - main
      event:
        - push
        - pull_request
```

**Review by masstez — COMMENTED** [review]
Suggestions to change

**Comment by 6543** [comment]
@masstez ?

**Pull request merged**
