### PR TITLE
Change import reference to match gitea instead of gogs

### PR DESCRIPTION
**Pull request by DblK**
Missing change to source to match the repository.
Should be done before accepting all PR from my point of view.

I simply did a search & replace for this PR.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by andreynering** [comment]
LGTM

**Comment by willemvd** [comment]
Someone forgot 1 entry that is causing the docker image not to build: 
- go install
- mkdir -p /tmp/go/src/github.com/gogits/
- ln -s /app/gogs/ /tmp/go/src/github.com/go-gitea/gitea
  ln: /tmp/go/src/github.com/go-gitea/gitea: No such file or directory
  The command '/bin/sh -c ./docker/build.sh' returned a non-zero code: 1

The line causing this issue is in build.sh

**Comment by DblK** [comment]
@willemvd, if it's not working, please fill an issue and if you know the fix, please also submit a PR with the link to your issue.

**Comment by strk** [comment]
I think @xinity is working on Dockerfile rewrite

**Pull request merged**
