### PR TITLE
Update TRANSLATORS

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by lafriks — CHANGES_REQUESTED** [review]
Please move your name to correct position in list, it is in alphabetical order

**Comment by ghost** [comment]
@lafriks hmm is this better? i just updated it.

**Review by ghost — COMMENTED** [review]
Oh, that is what you meant sorry that i wasted your time.

**Review by jonasfranz — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by lunny** [comment]
@lafriks need your approval.

**Comment by techknowlogick** [comment]
@lafriks pending your approval

**Review by lafriks — APPROVED** [review]

**Pull request merged**
