### PR TITLE
push + pull now works with reverse proxy + basic auth on apache 2.4

### PR DESCRIPTION
**Pull request by dl5rcw**
@strk asked me to offer my gogs contribution to gitea
https://github.com/gogits/gogs/pull/3785

Setup:
I use gogs // gitea with reverse proxy and basic auth. Users are auto created.
http pull and push did not work, so I started to look in the code.

We use SSO (AuthBasicProvider dbd, Apache 2.4, Location /gogs - since today /gitea AuthType Basic)
Reverse Proxy is pointing to /gogs - since today /gitea.
[security]
REVERSE_PROXY_AUTHENTICATION_USER = X-WEBAUTH-USER
[service]
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true

Issue: SSO was not handeled by http.go 
Solution: now added to the section, see contribution.

### CODE REVIEW

**Comment by strk** [comment]
LGTM, but I hadn't tested it

**Comment by dl5rcw** [comment]
It is in production mode on our server now.

**Comment by dl5rcw** [comment]
Dear all,
for those to review, please focus on line 86 to 97. https://gist.github.com/dl5rcw/2dd2dac42ee46996c3e7166ba15b3b38
Everything else is indentation. Lint would complain causing the check to fail. Fixing the indentation makes the diff look big - which it is not when having a second glance on it.

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
