### PR TITLE
Use `filepath` instead of `path` to create SQLite3 database file

### LINKED ISSUE #28300: Unable to open database file: The system cannot find the path specified
### Description

On windows:
image

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

gitea-1.21.0-windows-4.0-amd64.exe

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #28300

### CODE REVIEW

**Review by delvh — APPROVED** [review]
I wonder how often we'll manage to confuse `path` and `filepath` :grin:

**Comment by JakobDev** [comment]
Why did this work on Linux but not on Windows?

**Comment by techknowlogick** [comment]
@JakobDev as windows uses different slashes that don't always convert when sending the Linux path :(

**Comment by wxiaoguang** [comment]
> Why did this work on Linux but not on Windows?
>
> > as windows uses different slashes
> 
> Just a sidenote: Modern Windows versions also support / as path separator, so we don't need to convert anything


Golang (Windows): `path.Dir("D:\\foo\\bar")` => `"."`

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
