### PR TITLE
Change to vertical navbar layout for secondary navbar for repo/user/admin settings 

### PR DESCRIPTION
**Pull request by HesterG**
Co-Author: @wxiaoguang 

This is the first step of #24229. And this PR will only includes html changes, and followed by other PRs that fine tune css and change to submenus. 

After:

Admin Level

Screen Shot 2023-04-21 at 10 07 16

User Level

Screen Shot 2023-04-21 at 10 07 23

Repo Level

Screen Shot 2023-04-21 at 10 07 07

### CODE REVIEW

**Comment by wxiaoguang** [comment]
The old layout is already:

```html
<div role="main" class="page-content admin ....">
	{{template "admin/navbar" .}}
	<div class="ui container">
	</div>
</div>
```

I think we just need some `flex` tricks:

```html
<div role="main" class="page-content admin FLEX">
	{{template "admin/navbar" .}}  Make it flex-left
	<div class="ui container">  Make it flex-right
	</div>
</div>
```

Then we do not need to change so many files, and the layout is simpler.

**Comment by HesterG** [comment]
> The old layout is already:
> 
> ```
> <div role="main" class="page-content admin ....">
> 	{{template "admin/navbar" .}}
> 	<div class="ui container">
> 	</div>
> </div>
> ```
> 
> I think we just need some `flex` tricks:
> 
> ```
> <div role="main" class="page-content admin admin-main-flex">
> 	{{template "admin/navbar" .}}  Make it flex-left:  class="admin-left-nav"
> 	<div class="admin-right-container">  Make it flex-right
> 	</div>
> </div>
> ```
> 
> Then we do not need to change so many files, and the layout is simpler.

Right now main contents of all pages are wrapped by `ui container`, even use the flex method, it should be 

```
<div role="main" class="page-content admin admin-main-flex">
  <div class="ui container">
	{{template "admin/navbar" .}}  Make it flex-left:  class="admin-left-nav"
	<div class="admin-right-container">  Make it flex-right
	</div>
  </div>
</div>
```

**Comment by wxiaoguang** [comment]
> Right now main contents of all pages are wrapped by ui container, even use the flex method, it should be

I think there could be better solutions, eg:

```
<div role="main" class="page-content admin admin-main-flex ui container">
</div>
```

Make the `ui container` on the `page-content`, then we do not need to indent so many lines -- which causes unnecessary conflicts with other PRs.

**Comment by HesterG** [comment]
> > Right now main contents of all pages are wrapped by ui container, even use the flex method, it should be
> 
> I think there could be better solutions, eg:
> 
> ```
> <div role="main" class="page-content admin admin-main-flex ui container">
> 	{{template "admin/navbar" .}}  Make it flex-left:  class="admin-left-nav"
> 	<div class="admin-right-container">  Make it flex-right
> 	</div>
> </div>
> ```
> 
> Make the `ui container` on the `page-content`, then we do not need to indent so many lines -- which causes unnecessary conflicts with other PRs.
> 
> Even more, drop the `ui container` classes, we write our own styles for `admin-main-flex`

This can work now because there is only navbar and the related contents on user/repo/admin settings page except for the top navbar. But if in the future, structure like below is added, this won't work well. The main contents will need their own container. 

Screen Shot 2023-04-21 at 10 46 07

**Comment by wxiaoguang** [comment]
Do you mean this?

https://jsfiddle.net/g6wc7hjs/

image

**Comment by HesterG** [comment]
> Do you mean this?
> 
> https://jsfiddle.net/g6wc7hjs/
> 
> image

Yes, but if this is changed, then the structure of organization settings is different from these. I don't know why we need two kinds of implementation which give the same ui results.

**Comment by wxiaoguang** [comment]
I think keeping the old layout is good enough, the ` +4,967 −4,723` changes would cause unnecessary conflicts with other PRs.

If `ui grid` works, could the layout becomes this?

```html
<div role="main" aria-label="{{.Title}}" class="page-content admin config">
	<div class="ui container grid">
		{{template "admin/navbar" .}}
		<div class="twelve wide column content">
		</div>
	</div>
</div>
```

It could also avoid that 4000+line changing.

**Comment by HesterG** [comment]
> I think keeping the old layout is good enough, the ` +4,967 −4,723` changes would cause unnecessary conflicts with other PRs.
> 
> If `ui grid` works, could the layout become this?
> 
> ```
> <div role="main" aria-label="{{.Title}}" class="page-content admin config">
> 	<div class="ui container grid">
> 		{{template "admin/navbar" .}}
> 		<div class="twelve wide column content">
> 		</div>
> 	</div>
> </div>
> ```
> 
> `ui container grid` could also avoid that 5000-line changing.

Yes I think this is the structure I can try to reduce the number of lines changed

**Comment by HesterG** [comment]
> 
> `ui container grid` could also avoid that 5000-line changing.

Tried this, but this does not reduce the lines significantly.. Because the following div is added to wrap around the original contents to make `four column` and `twelve cloumn` structure effective inside `ui grid`

```html
<div class="twelve wide column content">
</div>
```

**Comment by wxiaoguang** [comment]
If you don't mind, I would take a try on this PR .... I'd like to do my best to make the template files simple 😁 

If I fail, then keep the nearly 5000 lines changes 🤣

**Comment by HesterG** [comment]
> If you don't mind, I would take a try on this PR .... I'd like to do my best to make the template files simple 😁
> 
> If I fail, then keep the nearly 5000 lines changes 🤣

Sure, it will be awesome if the PR has less changes. Thanks!

**Comment by wxiaoguang** [comment]
I think in the future we should introduce "template layout" support (at the moment, Go template doesn't support it well).

So I think we can have this at the moment:

* https://github.com/go-gitea/gitea/compare/main...wxiaoguang:gitea:vertical-navbar-temp
* https://github.com/wxiaoguang/gitea/tree/vertical-navbar-temp

Then the admin pages could be written as:

```html
{{template "admin/layout_head" (dict "ctxData" . "pageClass" "admin dashboard")}}
	<div class="admin-main-content">
		dashboard .....
	</div>
{{template "admin/layout_footer" .}}
```

Developers do not need to repeat the "ui container" / "twelve wide column" / "alert" in all templates.

What do you think about this approach?

**Comment by silverwind** [comment]
> Then the admin pages could be written as:

So you basically want a template that has the ability to render HTML nodes passed from outside? In React, one would use special [children](https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children) property for it, but I assume `html/template` has no equivalent.

**Comment by wxiaoguang** [comment]
> > Then the admin pages could be written as:
> 
> A template that has the ability to render HTML nodes passed from outside? In React, one would use special [children](https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children) property for it, maybe that can be achieved by passing such a html template type through as a dict property to the subtemplate.

Golang template has a [semi-finished "layout block"](https://pkg.go.dev/text/template#example-Template-Block) support, but it doesn't work in Gitea. Golang template team just hope developers to clone the templates again and again and manually prepare their dependencies .....  while Gitea has 400 templates .....

But the good news is, after our Template Context Function (#24056) support, I can make our own "layout block" support later.

**Comment by HesterG** [comment]
> I think in the future we should introduce "template layout" support (at the moment, Go template doesn't support it well).
> 
> So I think we can have this at the moment:
> 
> * [main...wxiaoguang:gitea:vertical-navbar-temp](https://github.com/go-gitea/gitea/compare/main...wxiaoguang:gitea:vertical-navbar-temp)
> * https://github.com/wxiaoguang/gitea/tree/vertical-navbar-temp
> 
> Then the admin pages could be written as:
> 
> ```
> {{template "admin/layout_head" (dict "ctxData" . "pageClass" "admin dashboard")}}
> 	<div class="admin-main-content">
> 		dashboard .....
> 	</div>
> {{template "admin/layout_footer" .}}
> ```
> 
> Developers do not need to repeat the "ui container" / "twelve wide column" / "alert" in all templates.
> 
> What do you think about this approach?

I see, I think this is a feasible solution, which is similar to children in React or slot in Vue lol. And it will also help to reduce line changes. I will rework this PR using this approach later.

**Comment by silverwind** [comment]
So this is WIP again?

**Comment by HesterG** [comment]
> So this is WIP again?



> So this is WIP again?

Yes.. I  Converted this to draft for now.

**Comment by HesterG** [comment]
> > So this is WIP again?
> 
> Yes.. I Converted this to draft for now.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
