### PR TITLE
Add ledis cache support

### PR DESCRIPTION
**Pull request by lunny**
This PR adds a new cache provider `ledis` which have been implemented in `go-chi/cache` but not supported.

For those Gitea instances which have lower memory but want to cache last commit information, it's a better case than memory or redis.

### CODE REVIEW

**Comment by silverwind** [comment]
What is `ledis`? Some kind of `redis` fork?

**Comment by zeripath** [comment]
I am slightly concerned that this is adding another different level dB to the system.

It would not be difficult to add a leveldb caching provider using our current leveldb by looking at this code nor should it be difficult to switch our leveldb provider over to the rdb that is in here but we shouldn't have two leveldbs.

Interestingly in the dependencies for this rdb is a mmap implementation - which (if we were happy to add - I think this is a cgo dependency) could be used in go-git for its commit-graph reader and some other places in gitea.

**Comment by lunny** [comment]
> What is `ledis`? Some kind of `redis` fork?
It's a pure golang k/v database which have a redis similiar interface but stored all data into disk. It's based on go leveldb.

@zeripath The cache interface requires `Incr` and something other feature which needs some work based on leveldb. I don't think we need to create a new one since go-chi/cache have implemented that.

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
I've just understood the reasoning behind this.

Is it really the case that the memory cache just grows without limit? That's kinda crazy. 

Is there any limit on this cache?

**Comment by lunny** [comment]
> I've just understood the reasoning behind this.
> 
> Is it really the case that the memory cache just grows without limit? That's kinda crazy.
> 
> Is there any limit on this cache?

If the cache haven't given a timeout when set, it will always be kept in memory.

**Comment by zeripath** [comment]
Ok this absolutely needs fixing. I just don't understand why anyone would write a cache that's not size limited in some way...

Are the redis and ledis caches at least size limited in some way?

**Comment by lunny** [comment]
> Ok this absolutely needs fixing. I just don't understand why anyone would write a cache that's not size limited in some way...
> 
> Are the redis and ledis caches at least size limited in some way?

The cache library derived from macaron middlewares and as I know there is no size limit for all these implementations.

**Comment by zeripath** [comment]
o_O

Then this just swaps the problem of memory for one of disk space and is not much better.

**Comment by zeripath** [comment]
Ok. 

I think we need to change the memory one to be a wrapper around an lru. If you get a cache hit just check if it's already expired and delete it if so.

That's probably the simplest thing to do - as although that means that the cache may contain expired data that data is likely not to be hot anyway and is more likely to get thrown out in an lru cache.

There's probably a library out there that has this kind of wrapping already. 

For the ledis and redis caches - we can't be the first to have to do this surely? There has to be a way of limiting these caches.

**Comment by zeripath** [comment]
Ok redis has volatile-lru, volatile-ttl and allkeys-lru options. I think therefore Redis is a configuration issue for redis users - as long as our implementation is setting expires correctly. 

(Likely we should not be recommending allkeys-lru if they're using redis for queues.) 

We should check that sessions have an expire set on them too.

**Comment by 6543** [comment]
Ledis lib looks stale as zeripath pointed out :/

**Comment by wxiaoguang** [comment]
The ledis project seems not active anymore. Should we give it up?

**Pull request closed without merging**
