### PR TITLE
Use ISO date format instead of hard-coded English date format for date range in repo activity page

### PR DESCRIPTION
**Pull request by yardenshoham**
January 2, 2006 -> 2006-01-02

See:
* #21380 
* #21387

image

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
I think we should take this one before Gitea's i18n module can handle complex i18n features.

**Comment by silverwind** [comment]
> I think we should take this one before Gitea's i18n module can handle complex i18n features.

I'd rather handle date formatting completely in frontend with https://github.com/github/time-elements. The backend can not know which timezone the user is in, while the frontend can.

**Comment by wxiaoguang** [comment]
> > I think we should take this one before Gitea's i18n module can handle complex i18n features.
> 
> I'd rather handle date formatting completely in frontend with https://github.com/github/time-elements. The backend can not know which timezone the user is in, while the frontend can.

How about having this PR now, and refactor later?

This PR is simple and clear, and it helps people who do not read English, ISO date is also widely used and can be read by most people. I would say this PR is a quick and good enhancement.

**Comment by silverwind** [comment]
Yeah my suggestion was not for this PR 😉

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by yardenshoham** [comment]
Added another commit to render according to locale

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
Sorry but I do not think it's good to make all empty `<time></time>` tags has the long-date format. The long-date format couldn't be assumed to be the default and general one.

**Comment by yardenshoham** [comment]
The codebase has no `<time></time>` tags, I see no problem here. What if I scope it to the activity page instead of globally?

**Comment by wxiaoguang** [comment]
But what if there are other `<time>` tags come in the future? The future developers may not know this code and then they would spend a lot of time resolving the conflicts.

**Comment by yardenshoham** [comment]
How about a new Vue component, so it'll be a different tag?

**Comment by wxiaoguang** [comment]
Well, that's more complex than I thought.

My preference is:
* Just change it to ISO format in first step (that's my approval for this PR)
* Make a clear CSS class for the customized `<time>` format (I could also accept if other reviewers also agree @silverwind @delvh )

If there are other changes, I think it need to be re-reviewed.

**Comment by yardenshoham** [comment]
Ok, I'll take it in another PR

**Comment by delvh** [comment]
I think either differentiating by class, or probably better by a custom attribute such as `data-format` or similar, is the best course of action.

**Comment by yardenshoham** [comment]
> I think either differentiating by class, or probably better by a custom attribute such as `data-format` or similar, is the best course of action.

Sounds good, let's merge this now and I'll start this on a new PR

**Comment by wxiaoguang** [comment]
Maybe silverwind  suggestted  https://github.com/github/time-elements  could be used, instead of writing components from scratch.

**Pull request merged**
