### PR TITLE
Show more settings for empty repositories

### LINKED ISSUE #29060: Deploy keys no longer available for uninitialized repository
### Description

When creating a new repository, I need to create a deploy key for my external process to push changes. The UI for this is no longer available unless a file exists.

### Screenshots

Screenshot 2024-02-05 at 10 25 00 AM

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

Safari

### PR DESCRIPTION
**Pull request by zokkis**
Shows more settings for empty repositories with setting `EnableCode` true (Fixes #29060)

before:
image

after:
image

### CODE REVIEW

**Comment by delvh** [comment]
In other words, reverts #28631?

**Comment by delvh** [comment]
As I already mentioned in the PR above, the best approach would probably be to disable the settings and display a tooltip why it is disabled.

**Comment by zokkis** [comment]
> In other words, reverts #28631?

No its not a revert
When you disable the setting `Access source code, files, commits and branches.` its correct to disable the settings, but not on empty repos
image

**Comment by zokkis** [comment]
> As I already mentioned in the PR above, the best approach would probably be to disable the settings and display a tooltip why it is disabled.

Then this should be work for all settings like

- webhooks
- branches
- tags
- git-hooks
- ssh-keys
- lfs
- runners/secrets/variables

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
Regarding my previous comment: I misunderstood you, I thought you meant showing all settings even when code is disabled. Not for empty repos.
But yeah, it might as well apply to this, but only in the future.

**Pull request merged**
