### PR TITLE
[Tests] fix gitlab migration testdata

### PR DESCRIPTION
**Pull request by 6543**
it looks like env `GITLAB_READ_TOKEN` is not set or CI would fail all the time :O

### CODE REVIEW

**Comment by 6543** [comment]
this pull is included in #12695

**Review by zeripath — APPROVED** [review]

**Comment by lafriks** [comment]
Please resolve conflicts

**Comment by lafriks** [comment]
Closing as already merged than

**Comment by 6543** [comment]
Didn't thought the other one will go in so quick - thats why I splitted the fix and the enhancement

**Pull request closed without merging**
