### PR TITLE
fix: only run test coverage on master branch.

### PR DESCRIPTION
**Pull request by appleboy**
As @tboerger mention https://github.com/go-gitea/gitea/pull/1783#issuecomment-304476001. `drone-coverage` plugin doesn't support `command` attribute so we change test command behavior. Just run test coverage on the master branch.

cc @tboerger @lunny @bkcsoft

### CODE REVIEW

**Comment by appleboy** [comment]
cc @ethantkoenig and need @lunny resign the drone sig file.

**Comment by lunny** [comment]
@appleboy I think you already had resign drone permission.

**Comment by appleboy** [comment]
@tboerger @lunny Done. Please help to review.

**Comment by ethantkoenig** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
