### PR TITLE
fix: render job title as commit message

### LINKED ISSUE #32724: Commit id not clickable in when viewing action log
### Description

Screenshot_20241205-143423~2

### Gitea Version

Dev latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker 

### Database

None

### PR DESCRIPTION
**Pull request by metiftikci**
resolves #32724

i dont know if this is correct approach, waiting for suggestions

### CODE REVIEW

**Comment by wxiaoguang** [comment]
To be honest, I do not think it is "correct". 🤣 

1. It shouldn't use `RenderCommitMessage` because issue-like title has its own render function, IIRC it is `RenderIssueTitle`
2. I think it should avoid bypass Vue framework , so `attachRefIssueContextPopup` is not needed if the gain is small.
    * attachRefIssueContextPopup is only used to attach some pure issue numbers in case there is no context: `The issue #123 said ....`
    * but here, the title already have enough related information
    * so I do not think attachRefIssueContextPopup is necessary, removing it would hugely improve code maintainability.

----

In my mind, the brief ideas are either:

* Let backend render (RenderIssueTitle), frontend only use `v-html` and no need to do anything else
* Let frontend render (add links to the title by regexp and element construction), then no need to touch backend or `v-html`

ps: you could use the mocked RepoActionView on devtest page to do test easily.

**Comment by metiftikci** [comment]
> Let backend render (RenderIssueTitle), frontend only use v-html and no need to do anything else

Are you sure to use RenderIssueTitle? Because what we see on the title is commit message

> so I do not think attachRefIssueContextPopup is necessary, removing it would hugely improve code maintainability

Ok. I will remove issue context popup

> Let frontend render (add links to the title by regexp and element construction), then no need to touch backend or v-html

Should i do it in this PR? Because as i see backend code more complex then to replace #number to link

**Comment by wxiaoguang** [comment]
> > Let backend render (RenderIssueTitle), frontend only use v-html and no need to do anything else
> 
> Are you sure to use RenderIssueTitle? Because what we see on the title is commit message

Then there is a RenderCommitMessageLinkSubject. TBH I haven't really looked into the problem and not sure which one is the best (has the best render behavior)

> > Let frontend render (add links to the title by regexp and element construction), then no need to touch backend or v-html
> 
> Should i do it in this PR? Because as i see backend code more complex then to replace #number to link

It depends, either frontend or backend should work (only one is enough)

But the question is whether it needs other render processors besides the link?

**Comment by wxiaoguang** [comment]
Hmm sorry it seems that I misread, after reading the code again, `RenderCommitMessage`  seems to be the right function to call

**Comment by metiftikci** [comment]
@wxiaoguang done. is it ok. feel free to request anything else

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Pull request merged**
