### PR TITLE
Add Size column to attachment

### PR DESCRIPTION
**Pull request by jonasfranz**
This PR adds a size column to attachments to decrease the amount of unnecessary disk usage.
The migration calculates the file size of each existing attachment.

### CODE REVIEW

**Comment by jonasfranz** [comment]
I dont't know if I should break on error while calculating file sizes or only log them.

**Comment by jonasfranz** [comment]
@lafriks done

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Pull request merged**
