### PR TITLE
Fix Dropzone following #15315

### PR DESCRIPTION
**Pull request by zeripath**
#15315 appears to have caused a change in the way Dropzone is imported - and it
now produces a module rather than the constructor.

This PR rather hackily just adds another Dropzone call to the result.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
@silverwind - you got any ideas?

(git bisect narrowed it down to #15315 as the causative commit.)

**Comment by silverwind** [comment]
Interesting. I would not have thought that webpack suddenly behaves differently in terms of import handling with the `type=module` change in package.json.

The proper fix would be `const [{Dropzone}]` above but I need to check closer first.

**Comment by silverwind** [comment]
It's so weird. `function Dropzone` is on `.Dropzone` and on `.default.default` of the `import` return value. Dropzone itself seems to be a pure CJS module. Tribute and ClipboardJS are imported similarily and still work off the `default` property.

I'll push the proper fix here. It doesn't seem any other imports are affected.

**Review by silverwind — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
