### PR TITLE
Fix a resource leak when open a lfs file

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
There is `defer dataRc.Close()` further above, shouldn't it take effect when the function returns?

**Comment by wxiaoguang** [comment]
> There is `defer dataRc.Close()` on line 255, shouldn't it take effect when the function returns?
> 
> Also, we probably shouldn't shadow the `dataRc` variable here.

Yup, and even more, line 410

**Comment by lunny** [comment]
> There is `defer dataRc.Close()` on line 255, shouldn't it take effect when the function returns?
> 
> Also, we probably shouldn't shadow the `dataRc` variable here.

This will close the previous `dataRc` because the next lines will override the `dataRc` variable.
I also don't like the shadown, I also created #22042 to resolve them. But for backport, this is also necessary.

**Comment by KN4CK3R** [comment]
Is the double `defer dataRc.Close()` correct? The docs say
> The behavior of Close after the first call is undefined.

**Comment by silverwind** [comment]
> This will close the previous dataRc because the next lines will override the dataRc variable.

But the previous `Close` should still execute on the first instance, right? When does go resolve the variable? At time of parsing or at time when the `defer`executes?

**Comment by lunny** [comment]
Looks like this PR is unnecessary. see https://go.dev/play/p/2d8BuU5ZVeg

**Comment by silverwind** [comment]
I'm actually quiet surprised that the code executed during `defer` sees the variable before the shadowing. I would have thought because `defer` executes last, it should see the last instance of the variable.

**Pull request closed without merging**
