### PR TITLE
Implement custom regular expression for external issue tracking.

### LINKED ISSUE #3468: Allow custom regex patterns for linking external issues
- Gitea version (or commit ref): 1.3.2
- Git version: 2.16.1
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
For external issue tracker: alphanumeric issue recognition does not work when:
- Key before the dash contains a number. Example: `BLG5-456`
- Key is enclosed in quotes. Example: `'BLG-456'` or `"BLG-456"`
- Key follows a slash: Example `BLG-123/BLG-564` (first key is recognized, second one not)

We think implementing so many additional 'rules' could lead to many false positives.
Thus we propose to add a third _External Issue Tracker Naming Style_ for specifying custom patterns to apply for matching issue keys. Then we could specify a pattern like `(WP-\d+)|(BLG5-\d+)` ourselves.
The matched group should then be used for replacing `{index}` in the _External Issue Tracker URL Format_.

### PR DESCRIPTION
**Pull request by AlexanderBeyn**
This PR adds regex as a third style of external issue tracking. The regular expression must have at least one captured group, which will be used as the index for the link. The entire match replaced by the link when rendered.

Fixes #3468

### CODE REVIEW

**Comment by techknowlogick** [comment]
I've resolved the merge conflicts, however due to some recent changes the tests are failing

**Comment by lunny** [comment]
Please resolve the conflicts

**Comment by strk** [comment]
@AlexanderBeyn thanks a lot for this, are you planning to resolve the conflicts ?

**Comment by strk** [comment]
@lunny I've resolved the conflicts in #17624 (using a rebase operation - don't know if I'm authorized of committing to *this* branch)

**Comment by wxiaoguang** [comment]
Thank you for your contribution! There is a new PR based on your work.

* #17624

**Pull request closed without merging**
