### PR TITLE
Update Arch linux URL from community to extra

### PR DESCRIPTION
**Pull request by minijaws**
Arch linux package link has changed from the community repo to the extra repo. The link has been updated

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

**Comment by delvh** [comment]
Backport?

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
@GiteaBot?
Where's the second PR?

**Comment by delvh** [comment]
No wonder, that PR has already been merged.
But where's 1.19?

**Comment by lunny** [comment]
The robot cannot find a suitable milestone for v1.19, so then he refuse to work.

**Pull request merged**
