### PR TITLE
Move dropzone.js to npm/webpack

### PR DESCRIPTION
**Pull request by silverwind**
- unvendor dropzone and upgrade it from 4.2.0 to 5.7.0
- make `csrf` available on window.config

I noticed one bug already present on master while testing which is when 1 attachment is present, comment is edited and another one is added, it won't save correctly.

This PR should not introduce any regressions.

### CODE REVIEW

**Review by guillep2k — APPROVED** [review]

**Comment by silverwind** [comment]
I think this upgrade allows us to remove `jquery-migrate`. I will investigate separately.

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
We also need to look at making dropzone less difficult to configure - there are repeated user complaints about not being allowed to upload jars, zips etc.

**Comment by silverwind** [comment]
> there are repeated user complaints about not being allowed to upload jars, zips etc.

This is because we have this opinionated default:

````
; One or more allowed types, e.g. image/jpeg|image/png
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip
````

I think we should drop the default and allow everything by default.

**Comment by silverwind** [comment]
Will do a few more refactors, don't land yet.

**Comment by silverwind** [comment]
Refactors removed, they require more work. Should be good to land.

**Pull request merged**
