### PR TITLE
Fix wrong translations

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Review by jonasfranz — APPROVED** [review]
Approve, since it simply moves some steps from make update-translations to drone.

**Comment by lafriks** [comment]
I think it should be fixed in crowdin translations not in drone step...

**Comment by lunny** [comment]
I don't think so. Crowdin plugin is not only for Gitea A

**Comment by lafriks** [comment]
There was also wrong translation in pt-BR, I already fixed that
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
