### PR TITLE
Do not overwrite empty DefaultBranch

### LINKED ISSUE #19470: DefaultBranch is not set correctly when using template which has 'master' as default
### Description

In #19354 the default branch for new repositories was changed from 'master' to 'main'. When running this new version on existing data where 'master' was still used as default this causes a problem when creating a new repository from a template which still uses 'master'.

The files and master branch are correctly copied to the newly generated repository however giteas internal default branch is set to 'main' instead of 'master'. This causes giteas "Branches" page to remain blank despite showing 1 branch and when cloning the repository git shows `warning: remote HEAD refers to nonexistent ref, unable to checkout.`.

When opening the "Branches" page gitea throws an error: `2022/04/23 10:48:22 ...s/web/repo/branch.go:177:loadBranches() [W] [6263bd56] loadBranches: missing default branch main for 60:sschroe/template_test`

Example of a broken repo on the demo site: https://try.gitea.io/steffen/template_test/branches

To reproduce:
- Run gitea with the default config
- Create a new template repository and set its main branch to 'master'
- Create a new repository and select the previously made template with "Git Content(Default Branch)" checked
- Open the "Branches" page on the new repository

### Gitea Version

9550e5a23e9f8581cc13f54b336307ee02d430cc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.36.0

### Operating System

Arch Linux

### How are you running Gitea?

git clone': git clone --recursive https://github.com/go-gitea/gitea.git
cd gitea
TAGS="bindata sqlite sqlite_unlock_notify" make build
./gitea

### Database

SQLite

### LINKED ISSUE #21994: Create from template does not reference the right branch.
### Description

If you create a template with a different default branch (e.g. not 'main') and create another repository from that template, it sets the default branch to an empty reference to 'main' causing this error when cloning it `warning: remote HEAD refers to nonexistent ref, unable to checkout.`. This can be resolved by changing the default branch to the one from the template but that should be the default behavior or at least it should provide an option to specify the name of the branch.

To reproduce:
1. Create a template repository with the default branch as anything but 'main'.
2. Create a repository from that template including the git content of the template.
3. Check to see if the default branch points to an invalid ref.

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Problem exists on both https://try.gitea.io/ and docker.

### Database

_No response_

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #21994. 
And fix #19470.

While generating new repo from a template, it does something like "commit to git repo, re-fetch repo model from DB, and update default branch if it's empty".

https://github.com/go-gitea/gitea/blob/19d5b2f922c2defde579a935fbedb680eb8fff18/modules/repository/generate.go#L241-L253

Unfortunately, when load repo from DB, the default branch will be set to `setting.Repository.DefaultBranch` if it's empty:

https://github.com/go-gitea/gitea/blob/19d5b2f922c2defde579a935fbedb680eb8fff18/models/repo/repo.go#L228-L233

I believe it's a very old temporary patch but has been kept for many years, see:  [2d2d85bb](https://github.com/go-gitea/gitea/commit/2d2d85bb#diff-1851799b06733db4df3ec74385c1e8850ee5aedee70b8b55366910d22725eea8)

I know it's a risk to delete it, may lead to potential behavioral changes, but we cannot keep the outdated `FIXME` forever. On the other hand, an empty `DefaultBranch` does make sense: an empty repo doesn't have one conceptually (actually, Gitea will still set it to `setting.Repository.DefaultBranch` to make it safer).

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
I have a feeling that backporting may be a mistake - unless we really do go through EVERY use of defaultBranch and make sure it's not empty before using it.

**Comment by wxiaoguang** [comment]
Is it related to https://github.com/go-gitea/gitea/issues/19470 ? I haven't looked into details, just a guess.

**Comment by wolfogre** [comment]
> Is it related to #19470 ? I haven't looked into details, just a guess.

Yes, it's the same as #21994.

**Comment by wolfogre** [comment]
> I have a feeling that backporting may be a mistake - unless we really do go through EVERY use of defaultBranch and make sure it's not empty before using it.

I have another idea, just check if the `DefaultBranch` could be empty in DB, that would be easier, you know, the times of writing are much less than reading. I did some checking (maybe not enough) and haven't found anything wrong, the `DefaultBranch` always has a value even if it's an empty repo.

**Comment by zeripath** [comment]
An alternative is to keep the afterload and just prestore the provided default branch at line 243 above before re-getting the repo from the db.

**Comment by wolfogre** [comment]
> An alternative is to keep the afterload and just prestore the provided default branch at line 243 above before re-getting the repo from the db.

Of course we can fix it in another way, but why do we do extra work for the lagacy code? It is an opportunity to remove it. If it's not harmful we don't have remove it, however, why do we keep it when it's harmful?

**Comment by wolfogre** [comment]
@zeripath How about this: we don't packport it to v1.18, just merge it to main, so we'll have enough time to test it and eliminate potential risks. 
If you agree, please feel free to remove the backport label.

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
I'm going to merge this and backport discussion can happen if needed.

**Pull request merged**
