### PR TITLE
Remove NULs byte arrays passed to PostProcess

### PR DESCRIPTION
**Pull request by zeripath**
PostProcess is supposed to be parsing and handling HTML
fragments, but on fuzzing it appears that there is a weird
issue with NUL elements that could cause a memory address
error in downstream libraries.

The simplest solution is to strip out the weird NULs - they
should not be there in any case and would be stripped out
anyway.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by mohe2015** [comment]
No offense and I don't know Golang but is there not a stdlib function to do this?

**Comment by jolheiser** [comment]
Would [`bytes.ReplaceAll`](https://golang.org/pkg/bytes/#ReplaceAll) work for this?

**Comment by zeripath** [comment]
Bytes.ReplaceAll will create a new []byte or change the original []byte array. As far as I understand we are not supposed to be changing the original []byte array passed in to postprocess

**Comment by zeripath** [comment]
> No offense and I don't know Golang but is there not a stdlib function to do this?

The point is to avoid multiple allocations of the (potentially large) byte array.

Yes bytes.ReplaceAll would replace the nil however at the expense of creating yet another copy of the []byte passed in. 

This is the same code as bytes.ReplaceAll just replacing into the prefixed copy.

**Review by 6543 — APPROVED** [review]
wold be nice if we could find witch dependency cause the issue and fix it there ...
I'm good with his for now

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
