### PR TITLE
Update nginx recommendations

### PR DESCRIPTION
**Pull request by silverwind**
- `Connection` and `Upgrade` [needed for websockets](https://www.nginx.com/blog/websocket-nginx/)
- ~~`X-Real-IP` unnecessary and duplicate with `X-Forwarded-For`. [chi checks  both headers](https://github.com/go-chi/chi/blob/master/middleware/realip.go), but XFF is definitely the more "standard" one.~~

### CODE REVIEW

**Comment by silverwind** [comment]
I guess `X-Real-IP` has the benefit of [parsing faster](https://github.com/chi-middleware/proxy/blob/ec449188a973ac5c43df941c04a31277d67d76fc/middleware.go#L44), so I'm indifferent whether to keep it. cc: @lafriks.

**Comment by lafriks** [comment]
This really depends on the situation, I would keep both. Generally nowadays there will be at least two proxies when deploying HA in K8s/docker etc edge reverse proxy -> ingress reverse proxy -> gitea and if not correctly configured x-real-ip could be incorrect and x-forwarded-for will be more reliable in that case. In the case of a single VM and nginx in front, yes it does not really matter what to use

**Comment by lafriks** [comment]
For more general use case I would recommend leaving them both

**Comment by silverwind** [comment]
I guess I will restore x-real-ip based on your opinion. Generally I think XFF is much better and likely better handled in a chain of proxies. There is also a https://datatracker.ietf.org/doc/html/rfc7239 but it seems no one is adopting it 😆

**Comment by silverwind** [comment]
So now this is only about websocket config, which does not hurt to have and will be needed for https://github.com/go-gitea/gitea/pull/26679 anyways.

**Comment by wxiaoguang** [comment]
In many cases, `X-Real-IP` can be trusted while `X-Forwarded-For` can't.

**Comment by lafriks** [comment]
> In many cases, `X-Real-IP` can be trusted while `X-Forwarded-For` can't.

That's why there is configuration on how many last IP's from `X-Forwarded-For` can be trusted by default we have 1 I think all others are discarded

**Review by lafriks — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Not worth the backport imho, Websocket will come in 1.22 earliest.

**Pull request merged**
