### PR TITLE
Add EdDSA JWT signing algorithm

### PR DESCRIPTION
**Pull request by amenzhinsky**
Hi there.

Currently `EdDSA` signing algorithm is missing and this PR adds the support.

Here are few links to RFCs:
https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms
https://datatracker.ietf.org/doc/html/rfc8037

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]
I wondered why I should have left that one out... it was added a month ago in the jwt lib 😏

**Comment by KN4CK3R** [comment]
Could you please fix the spelling error in `CreateJWTSingingKey` while you are there? We are not singing.

**Comment by amenzhinsky** [comment]
@KN4CK3R tbh I'm not getting what is the typo.

**Comment by KN4CK3R** [comment]
```
CreateJWTSingingKey
CreateJWTSigningKey
           ^^
```

**Comment by amenzhinsky** [comment]
@KN4CK3R done, didn't see that whatsoever, the British scientists claim that it's enough to see the first and the last letter in the word to read it :smile:

**Review by lunny — APPROVED** [review]

**Pull request merged**
