### PR TITLE
Integrated bindata for public and templates

### LINKED ISSUE #30: Embed bindata optionally
I would like to embed the bindata optionally based on a build tag, since we are running a Go application I really love the feature to server everything from the single file.

### PR DESCRIPTION
**Pull request by tboerger**
Fixes #30 

Things left to do:

* [ ] Integrate the switch for mailer templates
* [ ] Make conf also aware of builtin or external

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
Does public/ already support override via custom/public? 
As I think I'm using public/img to store custom logo and favicon...

**Comment by thibaultmeyer** [comment]
I think `bindata.go` dont have to be committed on repository and must be auto-generated during the make process.

It become a mess when two (or more) Pull Requests update different files (eg : app.ini for the first commit and add new files for the second) because the `bindata.go` file cause merge error each time.

**Comment by strk** [comment]
I tend to agree with @0xbaadf00d  but would rather avoid blocking this change due to that issue. Rather, I suggest a new issue is filed for the bindata.go threatment.

**Comment by tboerger** [comment]
I'm currently thinking about rebuilding the bindata interface that handles static directories instead of embedding the data, switched via a build tag.

**Comment by andreynering** [comment]
@tboerger I don't know if it helps you, but I like [fileb0x](https://github.com/UnnoTed/fileb0x) because it prevents the need of two different tools: [bindata](https://github.com/jteeuwen/go-bindata) and [bindata-assetfs](https://github.com/elazarl/go-bindata-assetfs).

Also, bindata-assetfs has [this bug](https://github.com/elazarl/go-bindata-assetfs/issues/34) on Windows.

**Comment by bkcsoft** [comment]
@andreynering +1 on not using go-bindata-assets WRT https://github.com/elazarl/go-bindata-assetfs/issues/34#issuecomment-256142878

> One of the reasons **I'm not putting too much effort in this project**, is
because there are better alternative available.

**Comment by tboerger** [comment]
fileb0x won't work because we rely on tags with the new bindata.

**Comment by bkcsoft** [comment]
Does Rice? https://github.com/GeertJohan/go.rice

**Comment by tboerger** [comment]
I will avaluate it with go.rice, looks like it also supports loading from a directory natively.

**Comment by andreynering** [comment]
@tboerger 

> I will evaluate it with go.rice, looks like it also supports loading from a directory natively.

Like this? https://github.com/UnnoTed/fileb0x/pull/3

Just trying to help, I'm fine with any option 👍

**Comment by tboerger** [comment]
@andreynering currently we want to embed the data optionally via a build tag, `bindata` builds all assets into the binary while `!bindata` always reads the assets from the filesystem.

**Comment by andreynering** [comment]
You're right, this would not be possible using fileb0x and build tags.

A workaroud would be having two fileb0x files ( `fileb0x-debug.yml` and `fileb0x.yml`) and two distinct commands on makefile to build with one or other option.

But if rice supports build tags, it would be way simpler.

**Comment by tboerger** [comment]
Obsolete via https://github.com/go-gitea/gitea/pull/354 https://github.com/go-gitea/gitea/pull/314 https://github.com/go-gitea/gitea/pull/293

**Pull request closed without merging**
