### PR TITLE
Added support for multiple LDAP servers in a auth source (go-gitea#6898)

### PR DESCRIPTION
**Pull request by Rob61**
Fixes Feature-Request go-gitea#6898

Added support for multiple LDAP(S) servers in a auth source.
Servers are separated by space characters.

Before this pull request:
`func dial` gets a string containing the LDAP server and try to connect.

With this pull request:
`func dial` gets a string containing the LDAP server or multiple LDAP servers separated by space character.
It splits the string into a list of strings and try to connect to the first, but will try the second, if the first fails, etc.
Leading to the possibility to provide a backup LDAP servers if the main server is not reachable e.g. because of maintaince.

Best
~Rob

### CODE REVIEW

**Comment by silverwind** [comment]
Suggestions:

- Split on comma instead of space, it's more intuitive I think
- Any reason not to parallelize the connections? If for example a server fails with a network timeout, all authorizations would need to wait for that timeout or forever if there's not timeout. (I could not find what the default timeout value for that module on https://godoc.org/gopkg.in/ldap.v2 and it doesn't look we set one either).
- Docs need to be updated probably (at least a hint in the UI)

**Comment by lunny** [comment]
We needs some tests for this PR.

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by wxiaoguang** [comment]
It has been stale for a long time and I can't think of a way to handling it other than closing it. Feel free to reopen if there's any new progress and I could also help.

**Pull request closed without merging**
