### PR TITLE
Allow token as authorization for accessing attachments

### PR DESCRIPTION
**Pull request by davidsvantesson**
This PR makes it possible to access attachments using token as authorization. You can currently get information about a release attachment using the API with token as authorization (e.g. `GET ​/repos​/{owner}​/{repo}​/releases​/{id}​/assets​/{attachment_id}`). However to download the actual attachment you need to use normal login as token is restricted to API. 

Currently you can download attachment like this:
```
curl -u user:password "https://try.gitea.io/attachments/262c8395-a089-410a-be88-985e319ea058" -o "File.ext"
```

This PR makes it possible to download attachment like this:
```
curl  -H "Authorization: token <token>" "https://try.gitea.io/attachments/262c8395-a089-410a-be88-985e319ea058"-o "File.ext"
```

Note: Currently this will only have affect when `REQUIRE_SIGNIN_VIEW = true`, as attachments always accessible otherwise. See #7908.

### CODE REVIEW

**Comment by guillep2k** [comment]
This looks like it will give access to uploading attachments with tokens as well. Is that alright?

**Comment by davidsvantesson** [comment]
> This looks like it will give access to uploading attachments with tokens as well.

I did not consider that. However I am not sure it actually will allow uploading. I match against `/attachments/` and not `/attachment`. Would /attachments/ also be routed for uploading?

**Comment by guillep2k** [comment]
> I did not consider that. However I am not sure it actually will allow uploading. I match against `/attachments/` and not `/attachment`. Would /attachments/ also be routed for uploading?

Check here:
https://github.com/go-gitea/gitea/blob/08c63190c68ca63f99f510f7f2c6cda41d531343/routers/routes/routes.go#L512

**Comment by davidsvantesson** [comment]
To ensure this has no side affects, I added a check that it is a GET request to attachment.

**Review by guillep2k — APPROVED** [review]

**Comment by silverwind** [comment]
Will this work if gitea is hosted on a subpath, e.g. `/gitea/attachments`?

I have a feeling this check is not right and too specific to attachments. Shouldn't a access token with access to a specific repo can do everything on that repo? I think we're missing the bigger picture.

**Comment by guillep2k** [comment]
> 
> Will this work if gitea is hosted on a subpath, e.g. `/gitea/attachments`?
> 
> I have a feeling this check is not right and too specific to attachments. Shouldn't a access token with access to a specific repo can do everything on that repo, including posting attachments to their own comments and retrieving attachments of all comments?
> 
> I think we're missing the bigger picture.

@silverwind This is the same method used for `IsAPIPath()`, so I guess it's alright. See:
https://github.com/go-gitea/gitea/blob/ca6fb004ac50fc924861112403895d637c6a2d1d/modules/auth/auth.go#L28-L30
and
https://github.com/go-gitea/gitea/blob/ca6fb004ac50fc924861112403895d637c6a2d1d/modules/context/auth.go#L75-L83

**Comment by davidsvantesson** [comment]
> Will this work if gitea is hosted on a subpath, e.g. `/gitea/attachments`?

I think it is handled by macaron (trimming site prefix), in macaron.go:
```
// ServeHTTP is the HTTP Entry point for a Macaron instance.
// Useful if you want to control your own HTTP server.
// Be aware that none of middleware will run without registering any router.
func (m *Macaron) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
	if m.hasURLPrefix {
		req.URL.Path = strings.TrimPrefix(req.URL.Path, m.urlPrefix)
	}
	for _, h := range m.befores {
		if h(rw, req) {
			return
		}
	}
	m.Router.ServeHTTP(rw, req)
}
```

It might not be a security risk to allow token generally, but tokens are usually used for scripts and integrations or similar, and I think it should not be encouraged to use the web interface for that (which is for humans). For example even if allowed to post attachments with tokens, there is a check for csrf cookie so it would be complicated to implement. Better to extend the API and encourage to use it. Unless it should be possible to login on web interface with token as well, but I don't think that is a good idea.

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
make LGTM works !

**Pull request merged**
