### PR TITLE
refactor: update debian script.

### PR DESCRIPTION
**Pull request by appleboy**
This PR fix script on Debian 8.

### CODE REVIEW

**Comment by strk** [comment]
Does this handle #210 too ?

**Comment by appleboy** [comment]
@strk No.

**Comment by appleboy** [comment]
Just fix start/stop/reload on Debian 8 using system init.

**Comment by strk** [comment]
LGTM -- I noticed it drops the redirection of stdout to `/dev/null` (or am I wrong?)

**Comment by appleboy** [comment]
@strk Yes, you are right. I will fix that.

**Comment by strk** [comment]
I actually like that. I mean... hiding outputs is never a good idea to me.
If it has to be directed somewhere, better direct to a logfile (which is
what the issue I linked was asking, bascially).

**Comment by appleboy** [comment]
@strk Yes I know your point. I think we need create another PR to fix problem you reference.

**Comment by appleboy** [comment]
@strk Missing your comment. All messages already logged on `/home/git/log` not `/dev/null`

```
$ cat /home/git/log/
gitea.log  http.log   xorm.log
```

But missing some http log like below:

```
[Macaron] 2017-02-16 21:25:57: Started GET /appleboy/4 for [::1]
[Macaron] 2017-02-16 21:25:57: Completed /appleboy/4 500 Internal Server Error in 44.258252ms
[Macaron] 2017-02-16 21:25:59: Started GET /favicon.ico for [::1]
[Macaron] 2017-02-16 21:25:59: Completed /favicon.ico 200 OK in 4.514718ms
```

**Comment by strk** [comment]
@appleboy when I first filed that issue (in Gogs) what I was after was mostly Panic messages, which were printed to stderr I think (or stdout) and so always got lost. I proposed a PR which redirected stdout/stderr to a file but was not merged because not portable. Indeed it looks like having the *caller* (the Debian script, in this case) doing that redirection was one simple way to obtain what I was asking for. I don't know what the current idea is. Me I'd be ok with having everything going to stdout and then delegate redirection to the wrapper, so as I see you're touching that script I wonder... is there a standard way to deal with stdout/stderr in those scripts ? Should we adopt the same way ? Just let's make sure Panic messages are not lost though, as that's really bad when your server respond with `Internal Server Error` messages and you can't know what's going on.

**Comment by appleboy** [comment]
@strk I know your point. I will take look at it and create another after this is merged. ok?

**Comment by strk** [comment]
Thanks @appleboy !

**Comment by andreynering** [comment]
Trusted LGTM

**Pull request merged**
