### PR TITLE
upgrade xorm to v1.2.2

### PR DESCRIPTION
**Pull request by lunny**
as title.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Err ... this has a requirement for goccy/go-json which doesn't work on Gitea main so is concerning that it won't work here either.

**Comment by zeripath** [comment]
See #14914 which has goccy/go-json 0.7.4 and still fails our tests.

**Comment by zeripath** [comment]
I really don't think goccy is ready yet.

**Comment by lunny** [comment]
There is a build tag to enable `go-json` or `jsoniter`, defaultly xorm 1.2.2 still use `encoding/json`. But vendor will always includes all packages however the build tag enabled.

**Review by a1012112796 — APPROVED** [review]

**Comment by zeripath** [comment]
Make lgtm work

**Comment by 6543** [comment]
:rocket:

**Pull request merged**
