### PR TITLE
Backport locales to 1.19

### PR DESCRIPTION
**Pull request by wxiaoguang**
Backport locales

Generated by `go run build/backport-locales.go release/v1.19`

### CODE REVIEW

**Review by yardenshoham — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
.

**Comment by silverwind** [comment]
.

**Comment by yardenshoham** [comment]
Change milestone to 1.19.1?

**Comment by techknowlogick** [comment]
🤖 🎺

**Pull request merged**
