### PR TITLE
Automatically remove Watches, Assignments, etc if user loses access due to being removed as collaborator or from a team

### LINKED ISSUE #5673: Can't unassign removed collaborators
- Gitea version (or commit ref): 30560b0

## Description

I just removed a collaborator (chris) from a project, but he's still an assignee on a few pull requests, and he can't be removed because he doesn't appear in the dropdown, and clicking `Clear assignees` does nothing.

### The assignees:
image

### The dropdown:
image

### PR DESCRIPTION
**Pull request by 6543**
continue #5676
fix #5673

Include  #11003

### CODE REVIEW

**Comment by 6543** [comment]
THIS is ready for review

**Review by zeripath — COMMENTED** [review]
I think this is right but I have two questions:

* The deletecollaboration call just removes watchers etc without checking if the user would still have access, should we check if the user would still have access before doing those? 
* Do we need to do a similar change for removal from team

**Comment by 6543** [comment]
@zeripath
 *  "...watches etc ..." -> https://github.com/go-gitea/gitea/pull/11003
 *  similar for teams I'll do this in another pull after this got merged (generalized the function for this)

**Comment by zeripath** [comment]
It might be better to just move them all in to this. They're all related.

**Comment by 6543** [comment]
@zeripath done

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
ping

**Comment by adelowo** [comment]
Thanks a lot mate. Really appreciated.

**Pull request merged**
