### PR TITLE
Fix default for allowing new organization creation for new users

### PR DESCRIPTION
**Pull request by jpicht**
When creating users DefaultAllowCreateOrganization was ignored.

This is simple two-line fix for issue #6542.

### CODE REVIEW

**Comment by zeripath** [comment]
Looking at the code I think these two settings need to coalesced. It doesn't appear that DEFAULT_ALLOW_CREATE_ORGANIZATION is wired into anything at all.

**Comment by zeripath** [comment]
We should probably just kill DEFAULT_ALLOW_CREATE_ORGANIZATION

**Comment by jpicht** [comment]
I can certainly do that as well. Should there be a warning if somebody has it set in the config file? Is there a place to add a message to, so it will end up in the release notes?

**Comment by zeripath** [comment]
Hmm... let's just fix the test. I think that's the correct thing to do.

Make:

https://github.com/go-gitea/gitea/blob/6eb53ac570ab9af51fc9cbd79f1db782edce57e0/models/user_test.go#L263

```go
setting.Service.DefaultAllowCreateOrganization = true
```

**Comment by jpicht** [comment]
I ran the drone test locally before creating this pull request. It seems the test did not fail for me. What did I do wrong? The output can be found here: https://gist.github.com/jpicht/6337485ab466776fded3ee22089d45dc

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
You didn't run the unit tests

**Comment by jpicht** [comment]
> You didn't run the unit tests - that is `make test` - your logs indicate you only ran the integration tests

Thanks! Than that step should probably be added to the contributers guide.

**Review by adelowo — APPROVED** [review]

**Comment by lafriks** [comment]
Make lgtm work

**Comment by lafriks** [comment]
Please send backport to release/v1.8 branch

**Pull request merged**
