### PR TITLE
Make URL scheme unambiguous

### LINKED ISSUE #2364: 404 when browser tag tree
- Gitea version (or commit ref): 8aadf79
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/zhsj-pkg/packer/src/upstream/1.0.2+dfsg
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I can't browser the git tree, maybe caused by the tag contains slash?

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #2364. Modifies URL schemes to remove ambiguity (see https://github.com/go-gitea/gitea/issues/2364#issuecomment-325174937)

The `GET /:owner/:repo/src/*` endpoint becomes three endpoints:
- `GET /:owner/:repo/src/branch/*`
- `GET /:owner/:repo/src/tag/*`
- `GET /:owner/:repo/src/commit/*`

Similarly for `GET /:owner/:repo/raw/*` and `GET /:owner/:repo/commits/*`. The old routes are redirected to the new routes to maintain backward compatibility.

### CODE REVIEW

**Comment by jonasfranz** [comment]
Is it possible to migrate links from older comments to the new URL scheme to avoid dead links?

**Comment by ethantkoenig** [comment]
@JonasFranzDEV I think a better solution to dead links is to have old links redirect to their new counterparts. I'll work on adding redirects soon.

**Comment by sapk** [comment]
~~~If possible add missing swagger comment (like #2274). And deprecated the old method.~~~ ~~~If I am not mistaken it is just like golang method of deprecating https://blog.golang.org/godoc-documenting-go-code.~~~
~~~Add a paragraph inside swagger comment starting with "Deprecated:"~~~

**Comment by ethantkoenig** [comment]
@sapk Isn't swagger just for API endpoints?

**Comment by lunny** [comment]
Yes. I think swagger only for API? This PR's break links is for UI.

**Comment by sapk** [comment]
@lunny @ethantkoenig sorry misread ...

**Comment by ethantkoenig** [comment]
@JonasFranzDEV @sapk Added redirects from old URL scheme to new scheme

**Comment by ethantkoenig** [comment]
Rebased to resolve conflicts

**Comment by lafriks** [comment]
@ethantkoenig can you please resolve conflicts so this can be tested?

**Comment by ethantkoenig** [comment]
@lafriks Rebased

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
cannot switch to another branch on the menus.

**Comment by ethantkoenig** [comment]
@lunny Will take a look by Sunday at latest

**Comment by ethantkoenig** [comment]
@lunny Fixed. There were actually two problems:
1. The branch dropdown template used the old URL scheme
2. The redirect to the new URL scheme did not work

Both problems are fixed

**Comment by ethantkoenig** [comment]
Rebasing to re-run CI (passes locally)

**Comment by lunny** [comment]
LGTM

**Pull request merged**
