### PR TITLE
UI: Fix overflow issues in repo

### LINKED ISSUE #7180: Long commit message hides commit status icon
- Gitea version (or commit ref): 1.8.2
- Git version: 2.11.0
- Operating system: Debian 9.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

In the commits table (both in commits and pull request page), the commit status icon will be hidden if the commit message is too long.

I think the commit status icon is not part of the commit message. It'll be better if the icon is always shown.

## Screenshots

The long commit message is truncated with ellipsis, hiding the commit status icon.
truncated

Narrow the browser, and the commit status icon appears.
narrow

### PR DESCRIPTION
**Pull request by silverwind**
- Fix layout overflow in repo file list.
- Fix invisible status icon in file view and commit list. In file view, the icon was moved to the left because I could not figure out a proper fix because of HTML tables.
- Added title attribute to commit messages.
- Fixed two CSS linter warnings in existing CSS.
- Fixed CI variable check in 'make css'.

Fixes: https://github.com/go-gitea/gitea/issues/7180

Screenshots:

### CODE REVIEW

**Comment by silverwind** [comment]
If anyone has a better idea on how to get the icon (and text-overflow) to work correctly on the right side of the file view header, shoot. Couldn't figure it out while testing with Firefox. I imagine it being easier to fix in Chrome as it seems to handle text overflow in tables quite differently than Firefox (which for some reason falls back to display no text at all in some cases).

**Comment by silverwind** [comment]
Thinking about maybe truncating the commit line to 50 or 72 chars before rendering and making sure the UI has enough space for that so we don't have to rely on wonky CSS-based truncation.

**Comment by mrsdizzie** [comment]
Looks like Github cuts off at 70 characters(plus an ellipse) which seems reasonable for this.

**Comment by silverwind** [comment]
Yeah, will look into doing that, so please consider this PR a WIP.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Imho that character limit can be done in other PR

**Comment by silverwind** [comment]
Feel free to merge this now. I will follow up with another PR that does the truncation and moves the icon in the file table to the right again later.

**Review by zeripath — APPROVED** [review]

**Pull request merged**
