### PR TITLE
Add myself to maintainers

### PR DESCRIPTION
**Pull request by davidsvantesson**
[My PRs](https://github.com/go-gitea/gitea/pulls?q=is%3Apr+author%3Adavidsvantesson). I think I will have time to do some reviewing as well 😄. 

I have the same username on discord and gitea.com.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]
Thanks for your contributions ;)

**Review by lunny — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]
Welcome!!

**Review by sapk — APPROVED** [review]
Welcome. I restarted the CI that fail for unrelated version.

**Comment by sapk** [comment]
I will let @go-gitea/owners add you on gitea.com and github to maintainer teams and discord.

**Comment by jolheiser** [comment]
I'm late to this party, but welcome!!

**Comment by lunny** [comment]
@davidsvantesson Welcome! @sapk done.

**Comment by techknowlogick** [comment]
@davidsvantesson welcome! Do you have a discord user, if so let me know and I can give you the appropriate permissions.

**Pull request merged**
