### PR TITLE
Split mail sender sub package from mailer service package

### PR DESCRIPTION
**Pull request by lunny**
Move all mail sender related codes into a sub package of services/mailer. Just move, no code change.
Then we just have dependencies on go-mail package in the new sub package. We can use other package to replace it because it's unmaintainable. ref #18664

### CODE REVIEW

**Comment by Neustradamus** [comment]
@lunny: Nice work, thanks!

**Review by wolfogre — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by Neustradamus** [comment]
@lunny: Good job!

Can not wait to see next steps ^^

**Comment by lunny** [comment]
> @lunny: Good job!
> 
> Can not wait to see next steps ^^

I have a new pull request as next step #32682

**Comment by Neustradamus** [comment]
@lunny: Excellent, good job!
If all devs were like you! :)

Linked to:
- https://github.com/go-gitea/gitea/issues/18664
- first PR: https://github.com/go-gitea/gitea/pull/32618
- Second PR: https://github.com/go-gitea/gitea/pull/32682

**Pull request merged**
