### PR TITLE
Admin teams should get all units regardless of form selection

### LINKED ISSUE #4771: Admin team's permission is dependent on user selected permissions
- Gitea version (or commit ref): 6ca8fbd2f94a1a02e1776a1d62ad2fb897839e47
- Git version: git version 2.15.2 (Apple Git-101.1)
- Operating system: MacOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

STEPS :

- Create new team
- In permissions, choose any of read and write, then untick code, issues, pull requests .
- Then choose Administrator access in permissions
- Then Update settings

- Add a repository to the team,
- Add a non admin user to the team 
- Access the repository, The user would not have any of the unticked permissions earlier even though he is in a team with admin access. ( for instance, he cannot view issues, PRs )

I would expect that the admin team gets all available permissions regardless of the selection(s)

### PR DESCRIPTION
**Pull request by adelowo**
Fixes #4771 and kind of related to #4713

### CODE REVIEW

**Comment by lafriks** [comment]
What if you only want team to have admin rights only for issues but still not be able to see code?

**Comment by adelowo** [comment]
@lafriks Wouldn't that be ___write permission___ with only the issue unit ?

**Comment by lafriks** [comment]
@adelowo not really, IMHO with write permission you can not create new labels/milestones

**Comment by adelowo** [comment]
Just tested and it turns out with write permissions, you can create both labels and milestones

**Comment by adelowo** [comment]
@lafriks I think this is a bug since if  for example you untick all the units ( with either read/write), and then go on to choose admin permission for the team, the users in the team  would be unable to do anything even though they have admin permissions ( technically, admin permissions over nothing )...

If you don't touch any of the units, just select admin permissions, then everything is fine.. There is a reproduction ___how to___ in https://github.com/go-gitea/gitea/issues/4771

**Comment by lafriks** [comment]
Was not that fixed already with #4719 ?

**Comment by adelowo** [comment]
No, this is a different bug report/fix... Should units given to an admin be read from the form being posted as in  

https://github.com/go-gitea/gitea/blob/3c39b6351c1ad44d73bc4eb46e1199f3f3901a61/routers/org/teams.go#L192

If I had seen this bug earlier, I wouldn't not have sent #4719 but this instead since we can let other permission types read units from the form and just give the admin team all available units... 

The major question is ___should admins be able to select units or an admin team should get everything ?___ . If yes, then the UI should take that into consideration and be fixed ( see above screenshots ).

Ideally, I'd want to revert #4719 (this PR already does that anyways) since https://github.com/go-gitea/gitea/issues/4713 is a deeper problem than what it initially looked like.... With it, admins can potentially not have any permissions at all

Were you able to follow the reproduction steps ?

**Comment by lunny** [comment]
@lafriks #4719 didn't fix the bug I think.

**Comment by techknowlogick** [comment]
Removing `backport/v1.5` as a label because 1.5.3 just went out, and we should focus on getting 1.6 out as stable.

**Comment by lunny** [comment]
I think this is unnecessary since admin team should have all the units. So save it on database is not a good idea. I think #5314 has fixed almost all the unit permission problem.

**Pull request closed without merging**
