### PR TITLE
Fix URL calculation in clone input box

### LINKED ISSUE #29462: repo page still shows incorrect clone url under different domain names
### Description

I reported this issue weeks ago, see #29084 , it was quickly patched and marked as fixed.
But after the merge of that patch, the bug is still there.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

wrong

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
Ported the function as-is and added comments so we don't forget about this in the future.

Fixes: https://github.com/go-gitea/gitea/issues/29462

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Comment by jolheiser** [comment]
I haven't looked at the frontend closely in a while, is there no way to reuse the same code instead of trying to keep them in sync?

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
Well… there is one: 
We can move the inline function to JS, with the drawback
> 	// synchronously set clone button states and urls here to avoid flickering on page load

**Comment by silverwind** [comment]
No easy way to share code between a inline scripts and scripts that build with webpack. Moving the inline script to webpack causes rendering flashes, only web components could avoid those while staying in webpack.

**Comment by silverwind** [comment]
Maybe https://github.com/icelam/html-inline-script-webpack-plugin can do it in the future.

**Review by jolheiser — APPROVED** [review]

**Pull request merged**
