### PR TITLE
Fix tag webhook 404 error

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by bkcsoft** [comment]
LGTM

**Comment by HZ89** [comment]
i have tested, but still 404
gitea log is  
```
2016/12/20 20:21:37 [T] AddTestPullRequestTask [base_repo_id: 5, base_branch: refs/tags/v0.1.1]: finding pull requests
[Macaron] 2016-12-20 20:21:37: Started GET /api/v1/repos/RPM_Builder/Youzu_RPMs/raw/refs/tags/v0.1.1/.drone.yml for 10.6.32.11
2016/12/20 20:21:37 [D] Session ID: 6350fcfda5e09e92
2016/12/20 20:21:37 [D] CSRF Token: DDdGnCtqLbL8HVx7uS248vX-hMc6MTQ4MjIzNjQ5NzgwNjM4MDI5MQ==
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/heads/refs
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/tags/refs
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/heads/refs/tags
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/tags/refs/tags
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/heads/refs/tags/v0.1.1
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/tags/refs/tags/v0.1.1
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/heads/refs/tags/v0.1.1/.drone.yml
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/tags/refs/tags/v0.1.1/.drone.yml
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/heads/refs/tags/v0.1.1/.drone.yml
[git-module] /data/gitlab/ceph/gogs/rpm_builder/youzu_rpms.git: git show-ref --verify refs/tags/refs/tags/v0.1.1/.drone.yml
2016/12/20 20:21:37 [...ules/context/repo.go:431 func1()] [E] RepoRef invalid repo: branch or tag not exist: refs/tags/v0.1.1/.drone.yml
```  
post data is  
```
{
  "secret": "IRDJVHGR5YWZ5RREDA2RGVTPRQW3BG6TYLOENAMIJOFB4KQWZFIA====",
  "sha": "a16dd9a098e900afa5a08261d53bfc7a2da2bb47",
  "ref": "v0.1.0",
  "ref_type": "tag",
  "repository": {
    "id": 5,
    "owner": {
      "id": 7,
      "login": "RPM_Builder",
      "full_name": "",
      "email": "",
      "avatar_url": "http:///avatars/7",
      "username": "RPM_Builder"
    },
    "name": "Youzu_RPMs",
    "full_name": "RPM_Builder/Youzu_RPMs",
    "description": "",
    "private": true,
    "fork": false,
    "html_url": "http:///RPM_Builder/Youzu_RPMs",
    "ssh_url": "git@:RPM_Builder/Youzu_RPMs.git",
    "clone_url": "http:///RPM_Builder/Youzu_RPMs.git",
    "website": "",
    "stars_count": 1,
    "forks_count": 0,
    "watchers_count": 2,
    "open_issues_count": 0,
    "default_branch": "master",
    "created_at": "2016-10-19T13:04:37+08:00",
    "updated_at": "2016-12-19T20:59:35+08:00",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": false
    }
  },
  "sender": {
    "id": 2,
    "login": "",
    "full_name": "",
    "email": "",
    "avatar_url": "http:///avatars/2",
    "username": ""
  }
}
```
drone log is  
```
time="2016-12-20T12:21:38Z" level=error msg="failure to get build config for RPM_Builder/Youzu_RPMs. 404 Not Found" 
time="2016-12-20T12:21:38Z" level=error msg="Error #01: 404 Not Found\n" ip=10.0.3.223 latency=367.328512ms method=POST path="/hook" status=404 time="2016-12-20T12:21:38Z" user-agent=GogsServer
```

**Comment by bkcsoft** [comment]
This here is definitively incorrect, but not a fault of Gitea AFAICS:
```
GET /api/v1/repos/RPM_Builder/Youzu_RPMs/raw/refs/tags/v0.1.1/.drone.yml
Should be
GET /api/v1/repos/RPM_Builder/Youzu_RPMs/raw/v0.1.1/.drone.yml
```

**Comment by HZ89** [comment]
so it is a drone bug?

**Comment by tboerger** [comment]
I think this LGTM, another issue will be solved within drone.

**Comment by lunny** [comment]
After drone/drone#1889 merged, we could test it.

**Pull request merged**
