### PR TITLE
support health check via / and fix #969

### LINKED ISSUE #969: Gitea instance returns HTTP status 404 when only asking for headers
- Gitea version (or commit ref): 1.0.1 (all Gitea and Gogs versions are affected)
- Git version: 1.9.1
- Operating system: Ubuntu 14.04 through 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (see below)
  - [ ] No
  - [ ] Not relevant

## Description

When requesting headers only, from a Gitea-server, it wrongly returns HTTP status 404.

Expected: HTTP 200.

```
~ curl -I https://try.gitea.io
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Sat, 18 Feb 2017 12:22:11 GMT
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=003f17e962323116; Path=/; HttpOnly
Set-Cookie: _csrf=-GQNJ7f6zhbIHnvi9zdMfG1sha86MTQ4NzQyMDUzMDk5NjQ4MTc4OA%3D%3D; Path=/; Expires=Sun, 19 Feb 2017 12:22:10 GMT; HttpOnly
X-Frame-Options: SAMEORIGIN
```

This is not expected behavior for a site that is available. Uptime-Monitors will show gitea instances as down because they usually only request the headers.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/42176476-gitea-instance-returns-http-status-404-when-only-asking-for-headers?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F47456670&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lunny**

### CODE REVIEW

**Comment by lunny** [comment]
will fix #969

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
let L-G-T-M work

**Comment by strk** [comment]
LGTM (and sounds like an easy thing to put under unit testing...)

**Comment by lunny** [comment]
let L-G-T-M work

**Pull request merged**
