### PR TITLE
In basic auth check for tokens before call UserSignIn

### LINKED ISSUE #5701: Clone repo using access tokens validate user against external authentication source
Using  access tokens to clone a repo (for example in droneci) with an user with external authentication, you can block your external account because your are doing failed authentications with the token to this external authentication. Also you can send the access token as the user to the external authentication source.

The use of the external authentication source in an clone with access tokens is commented in: https://github.com/go-gitea/gitea/issues/4952

Feel free to close this issue if is considered duplicate, I opened the issued because I think this is a problem.

- Gitea version (or commit ref): 1.7.0rc2
- Git version: 2.20.1
- Operating system: Fedora 29
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When you clone a repo using access tokens, for example if your are using drone:

    git clone https://{USER}:{TOKEN}@gitea.domain.org/test/test.git

If the external authentication source (for example LDAP) has a account locking mechanism you can block your password.

And if you use the other form with the x-oauth-basic as a password:

    git clone https://{TOKEN}:x-oauth-basic@gitea.domain.org/test/test.git

You are not blocking the account, but You are sending the token to the external authentication source as the user. I think that this is a problem because this token will be in the logs of the external authentication system.

When you clone a repo with:

    git clone https://{USER}:{TOKEN}@gitea.domain.org/test/test.git
    or
    git clone https://{TOKEN}:x-oauth-basic@gitea.domain.org/test/test.git

you are doing two calls:

    GET /test/test.git/info/refs?service=git-upload-pack
    POST /test/test.git/git-upload-pack

and with every call you are done two authentications to the external authentication source, in total 4.
You can block you external account very quickly.

The problem is that **modules/context/context.go:Contexter**  is execute in every  http request and
it's calling **modules/auth/auth.go:SignedInUser** that calls **models/login_source.go:UserSignIn** that do the external authentication.

If the path is a repo **routers/repo/http.go:HTTP** is called, and that function calls 
 **models/login_source.go:UserSignIn** before check if user or password is a token.

## Fix
Without doing big changes in the authentication code:

**modules/auth/auth.go:SignedInUser** calls **SignedInID** to check with **IsAPIPath** if this is an api path. I don't see an easy way to do check if this is a repo call and do something similar with the token in **SignedInID**. SignedInUser is called inside a macaron middleware **Contexter** so it's called for every route. Any Idea?

Change in **routers/repo/http.go:HTTP** the check if the user or password is an access token before the call to **UserSignIn**

## How to reproduce:

1. Use an user that validates against a external authentication source.
2. Create a new private repository
3. Add a new application under your profile settings
4. Try to clone the repository using the application's token 
  **git clone https://{USER}:{TOKEN}@gitea.domain.org/test/test.git**
5. You see four invalid authentications in the external authentication system.

### PR DESCRIPTION
**Pull request by manuelluis**
With this change we fix https://github.com/go-gitea/gitea/issues/5701

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
Heya, thanks for your PR.

Changing login code is always a bit worrisome as it's an area fraught with consequences.

Your proposed login scheme is somewhat concerning to me. Is this used elsewhere? (either in Gitea or elsewhere?) I really don't like the idea of overloading the password field in this way, or of putting tokens in to the username. (Too many places will log usernames.)

If we have to overload fields - which I guess we have to because git won't let us add other fields. My suggestion would be to instead overload the username field with the type of login plus a separator not allowed in usernames on Gitea (likely +) followed by the username. The password field could then be kept for secrets.

If I'm being stupid and this is already in Gitea and you're just fixing a bug please tell me and I'll look again.

I do think this is a good idea though.

**Comment by manuelluis** [comment]
@zeripath, I think there is a bug. https://github.com/go-gitea/gitea/issues/5701

The  {USER}:{TOKEN} and {TOKEN}:x-oauth-basic  are already using for cloning repos, I'm not adding new authentication schemes.

When you use the token to clone a repo, actually gitea check first the user, twice, with UserSignIn. If the user is a gitea user (not an external user) this is not a problem,  but if you are validating user to  LDAP, for example, you are validating the tokens to LDAP: you can block your user since you are sending the username and the token as the password (not your user passwd) or you can ex-filtrate the token if you use the token as the username and "x-oauth-basic" as the password.

For every clone you are doing 4 user validations, it's very easy to block or disable the user in the LDAP.

In routers/repo/http.go I only change the order of the validation, first I check if is a token and then the password of the user.

In modules/auth/auth.go, SignedInUser is call in the middelware Contexter for every request. I didn't find an easy way to know if we are cloning a repo. There is already a check for the api that is very simple (checks if the path begin with "/api/") but detect if the path is a route for Git smart HTTP will be more complicated.
I added the check for the token in the basic auth. This is new since that type of auth is not permitted before: use {USER}:{TOKEN} or {TOKEN}:x-oauth-basic as basic auth.

With the Git smart HTTP requests there is a problem of double validation that is not solve in this pull.

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by lafriks** [comment]
Make lgtm work

**Comment by lafriks** [comment]
Please backport this to release/v1.7 branch

**Pull request merged**
