### PR TITLE
Fix branch selector UI

### LINKED ISSUE #30802: broken styles on branch selector when creating an issue
### Description

image
image

### Gitea Version

1.22.0+rc1-23-ga988237eb4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix  #30802

### CODE REVIEW

**Comment by silverwind** [comment]
I too had recent fun with the pain in the ass that is the branch selector in https://github.com/go-gitea/gitea/pull/28163#issuecomment-2076008504. Hope we can make one single component for it soon in vue.

**Comment by silverwind** [comment]
What needs to be done is make it work in all places and not have any dependencies on being rendered inside an issue. E.g. a clean reusable interface that works anywhere in a repo.

**Comment by silverwind** [comment]
image

Can you put a small spacing between button and dropdown? 4px should be good.

**Comment by silverwind** [comment]
image

Last item could use border-radius on bottom.

**Comment by silverwind** [comment]
image

"g" is cut off by `overflow-hidden` caused by a previous PR of mine. Would be a nice to have fix, but must work with long branch names.

**Comment by wxiaoguang** [comment]
> I too had recent fun with the pain in the ass that is the branch selector in [#28163 (comment)](https://github.com/go-gitea/gitea/pull/28163#issuecomment-2076008504). Hope we can make one single component for it soon in vue, it's a absolute mess currently.

That's impossible at the moment because there are a lot of legacy code, especially the messy "repo-legacy.js"

----

For other changes: a4f323618f9550a593156befcd7085df32322fb5

image

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
