### PR TITLE
Enable federated avatars by default

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by lunny** [comment]
User could change themselves. Why change this?

**Comment by bkcsoft** [comment]
@strk does this add any overhead on Giteas side? (DNS-lookups, double HTTP-hits, etc)

**Comment by jhasse** [comment]
> User could change themselves. Why change this?

Most users probably won't know about federated avatars. As they are probably a good thing, it might be the right thing to push them a little :)

**Comment by strk** [comment]
Change for pushing usrers a little toward freedom.

The added server overhead is a daily cached DNS lookup for
each user's email domain.

**Comment by reinerj** [comment]
You are serious? Pushing users toward freedom? Not sure users want to get pushed in any way.

**Comment by jhasse** [comment]
"Push" is definitely not the right word. This just enables an awesome feature of Gitea by default.

**Comment by strk** [comment]
"Push" may not be the best word, but we're currently effectively pushing
users toward gravatar.com, by default, as that's the way for them to get
their avatar shown in a default gitea instance.

**Comment by tboerger** [comment]
I prefer it like it was before.

**Comment by lunny** [comment]
I think user could do it himself. And default we suppose user in an intranet and cannot visit the internet. I will close this and please feel free to reopen it if you have further informations.

**Comment by strk** [comment]
@lunny the current default is already using the internet (pushing toward Gravatar) so if intranet use is your concern the default should be OFFLINE=true. I would agree with that.

**Comment by lunny** [comment]
So maybe we need change Offline to default false?

**Pull request closed without merging**
