### PR TITLE
Switch migration icon to svg

### PR DESCRIPTION
**Pull request by silverwind**
Followup on https://github.com/go-gitea/gitea/pull/15952, use SVG for migration icon.

Screen Shot 2021-05-23 at 00 26 12
Screen Shot 2021-05-23 at 00 25 39

### CODE REVIEW

**Comment by silverwind** [comment]
If people prefer the colored icons from the migrate page for these icons, I could go ahead and do that.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
CI failed is not related.

**Comment by silverwind** [comment]
Marking as WIP as I think I will refactor this to not having to alter `fill` in the git svg.

**Comment by zeripath** [comment]
make lgtm work

**Pull request merged**
