### PR TITLE
Fix org visibility bug when git cloning

### LINKED ISSUE #6491: Public repositories of a private organization are hidden but can be checked out by anyone
Relevant to #6234

- Gitea version (or commit ref): 1.8.0 (docker image)

On UI side such repository is protected from user access which gives false sense of security, because any authenticated user (anonymous not tested) can still check it out.

### PR DESCRIPTION
**Pull request by lunny**
Should fix #6491, ~but if someone could add some tests are better. I'm so sleepy so have to go to bed now.~
Integration tests added.

### CODE REVIEW

**Comment by lunny** [comment]
It's ready to review.

**Comment by lafriks** [comment]
Drone fails

**Review by zeripath — COMMENTED** [review]
Use: "anonymous user", or "not logged in user" instead of "unlogin user" in comments.

Change the names of user22 and user23 to limitedorg and privateorg or similar - then it's clear what they are for future tests and makes the tests less confusing.

**Comment by lunny** [comment]
@lafriks @zeripath done.

**Review by lafriks — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
Please backport

**Pull request merged**
