### PR TITLE
Go linting adjustments

### PR DESCRIPTION
**Pull request by silverwind**
Seems a major source of linter slowness is that it ventures into directories not containing any go files. Fix that by excluding the worst offending dirs.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by techknowlogick — COMMENTED** [review]
could you also include an upgrade to golangci-lint v1.33.0 in this PR?

**Review by techknowlogick — COMMENTED** [review]
Perhaps also excluding `node_modules` from revive as well would decrease time to complete linting.

**Comment by silverwind** [comment]
Actually it does not seem to help much if any for golangci-lint but `revive` certainly seems to digs into `node_modules`:

````
GO111MODULE=on go run -mod=vendor build/lint.go -config .revive.toml -exclude=./vendor/... ./... \|\| exit 1
--
```

I'll see if I can fix that, marking wip.

**Comment by silverwind** [comment]
Interestingly I get a bunch of new `revive` errors if I explicitely specify files to it (`GO_SOURCES_OWN`):

```
modules/setting/database_sqlite.go:10:2: a blank import should be only in a main or test package, or have a comment justifying it
modules/public/static.go:22:1: exported function Asset should have comment or be unexported
modules/public/static.go:31:1: exported function AssetNames should have comment or be unexported
modules/public/static.go:40:1: exported function AssetIsDir should have comment or be unexported
modules/public/static.go:43:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
modules/public/static.go:47:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
modules/templates/static.go:49:1: exported function NewTemplateFileSystem should have comment or be unexported
modules/templates/static.go:206:1: exported function Asset should have comment or be unexported
modules/templates/static.go:215:1: exported function AssetNames should have comment or be unexported
modules/templates/static.go:224:1: exported function AssetIsDir should have comment or be unexported
modules/templates/static.go:227:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
modules/templates/static.go:231:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
modules/templates/static.go:49:30: exported func NewTemplateFileSystem returns unexported type templates.templateFileSystem, which can be annoying to use
build/generate-gitignores.go:26:3: var githubApiToken should be githubAPIToken
modules/options/static.go:56:1: exported function AssetDir should have comment or be unexported
modules/options/static.go:116:1: exported function Asset should have comment or be unexported
modules/options/static.go:125:1: exported function AssetNames should have comment or be unexported
modules/options/static.go:134:1: exported function AssetIsDir should have comment or be unexported
modules/options/static.go:137:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
modules/options/static.go:141:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
build/generate-licenses.go:26:3: var githubApiToken should be githubAPIToken
cmd/embedded.go:327:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
cmd/embedded.go:230:21: error strings should not be capitalized or end with punctuation or a newline
```

**Comment by silverwind** [comment]
Revive still goes into node_modules, I have no idea why. I'm thinking we should maybe replace `build/lint.go` with a static binary download for it.

**Comment by silverwind** [comment]
Doesn't look like this is really going anywhere and there's no actual speed gain, so closing this. We should look into that revive issue with node_modules later.

**Pull request closed without merging**
