### PR TITLE
Remove digitalocean section

### LINKED ISSUE #29911: DigitalOcean Marketplace app seems to no longer be available
### Description

The [documentation website](https://docs.gitea.com/installation/install-on-cloud-provider#digitalocean) refers to a [DigitalOcean Marketplace app](https://marketplace.digitalocean.com/apps/gitea) that appears to no longer be available (dead link).

### Gitea Version

Latest deployed version (presumably?)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I'm not.

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/29911

### CODE REVIEW

**Review by techknowlogick — CHANGES_REQUESTED** [review]
I'm working on getting this back up on DO, their review process for each update takes time.

**Comment by silverwind** [comment]
Ah okay, so they remove outdated apps? We could update docs to note that fact, or better yet, automate it 😆

**Comment by techknowlogick** [comment]
@silverwind I have the process mostly scripted (building VM, and taking the image of it). Submitting updates for the "app" is only available via a manual form submission. It was removed due to a conflict due to a few of them that had the snap installed that failed to update, and stopped the process. The snap was only present on a few of them as a test to ensure that those who used the appliance were updated to the latest version with security and bug fixes.

**Comment by silverwind** [comment]
Ok so let's close it then if it's WIP.

**Pull request closed without merging**
