### PR TITLE
Remove avatarHTML from template helpers

### PR DESCRIPTION
**Pull request by wxiaoguang**
The HTML code is more readable and more correct (it needs `"ui avatar"` class)

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Ideally should use normal avatar helper, but I see the problem here is that it is indexed by email address instead of username.

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Ideally should use normal avatar helper, but I see the problem here is that it is indexed by email address instead of username.

Actually, `$push.AvatarLink` is not for the "user". `$push` is a special model (`*repository.PushCommits`)

**Comment by silverwind** [comment]
Can it be easily refactored to user regular avatar helper?

**Comment by wxiaoguang** [comment]
> Can it be easily refactored to use regular avatar helper?

IMO, no. Or, how?

**Comment by silverwind** [comment]
Don't wanna dig into this now :)

**Pull request merged**
