### PR TITLE
vendor: update swagger-ui to v3.24.3

### PR DESCRIPTION
**Pull request by sapk**
This PR also improve the related make task to only package needed file.

The update of swagger-ui fix various security bug :
- https://github.com/swagger-api/swagger-ui/releases/tag/v3.18.0
- https://github.com/swagger-api/swagger-ui/releases/tag/v3.23.11
- https://github.com/swagger-api/swagger-ui/releases/tag/v3.24.1

### CODE REVIEW

**Comment by silverwind** [comment]
I just unvendored and updated `swagger-ui` in https://github.com/go-gitea/gitea/pull/9714 so I fear this PR might be obsolete.

**Comment by sapk** [comment]
@silverwind sorry I haven't see your PR.

**Comment by sapk** [comment]
@silverwind I feel after reviewing your PR that we should be better to keep this outside js build chain and stick to provided releases by swagger-ui. 
I may miss one advantage to use the custom webpack build. What do you think building the swagger js add compared to using the released version ?

**Comment by silverwind** [comment]
I primarily want the dependency managed by npm for easy updating.

We could use the pre-built module `swagger-ui-dist` and just copy it to `public`, but with that, we'd have to inline the initialization in the go template again which I'm not a fan of because that code will never be linted or polyfilled for our supported browsers.

**Pull request closed without merging**
