### PR TITLE
upgrade and fix dependencies

### PR DESCRIPTION
**Pull request by carnott-snap**
All dependencies have been upgraded to @latest. These changes are safe,
trivial, and tests pass. Many unnecessary indirect dependencies have now
also been purged after running go mod tidy.

github.com/russross/blackfriday contains a broken v2.0.0 tag, thus
upgrade to @latest is impossible. The correct @latest for the v1 series
is v1.5.2.

### CODE REVIEW

**Comment by lunny** [comment]
CI failed.

**Comment by sapk** [comment]
You must have missed to vendor the dependencies update.
In general, I would prefer to update one at time to indicate what as changed.

**Comment by carnott-snap** [comment]
you want multiple commits or multiple PRs?

**Comment by zeripath** [comment]
@carnott-snap multiple PRs please. Thanks for your work though.

**Comment by carnott-snap** [comment]
After rebasing and the closure of editorconfig/editorconfig-core-go#27, this change only impacts `go.mod`, `go.sum`, and `vendor`. Based on the compatibility guarantees that modules require, this should be a safe bulk upgrade. As well, all changes are enacted by `go mod tidy`, thus disentanglement could be tricky. To confirm, are you requesting I open 45 PRs for the following changes:
```
gitea.com/macaron/cors v0.0.0-20190821152825-7dcef4a17175                               | gitea.com/macaron/cors v0.0.0-20190826180238-95aec09ea8b4
github.com/RoaringBitmap/roaring v0.4.7 // indirect                                     | github.com/RoaringBitmap/roaring v0.4.21 // indirect
github.com/blevesearch/bleve v0.0.0-20190214220507-05d86ea8f6e3                         | github.com/blevesearch/bleve v0.8.1
github.com/blevesearch/blevex v0.0.0-20180227211930-4b158bb555a3 // indirect            | github.com/blevesearch/blevex v0.0.0-20190916190636-152f0fe5c040 // indirect
github.com/blevesearch/go-porterstemmer v0.0.0-20141230013033-23a2c8e5cf1f // indirect  | github.com/blevesearch/go-porterstemmer v1.0.2 // indirect
github.com/blevesearch/segment v0.0.0-20160105220820-db70c57796cc // indirect           | github.com/blevesearch/segment v0.0.0-20160915185041-762005e7a34f // indirect
github.com/chaseadamsio/goorgeous v0.0.0-20170901132237-098da33fde5f // indirect        | github.com/chaseadamsio/goorgeous v2.0.0+incompatible
github.com/couchbase/vellum v0.0.0-20190111184608-e91b68ff3efe // indirect              | github.com/couchbase/vellum v0.0.0-20190829182332-ef2e028c01fd // indirect
github.com/denisenkom/go-mssqldb v0.0.0-20190924004331-208c0a498538                     | github.com/denisenkom/go-mssqldb v0.0.0-20191001013358-cfbb681360f0
github.com/etcd-io/bbolt v1.3.2 // indirect                                             | github.com/etcd-io/bbolt v1.3.3 // indirect
github.com/ethantkoenig/rupture v0.0.0-20180203182544-0a76f03a811a                      | github.com/ethantkoenig/rupture v0.0.0-20181029165146-c3b3b810dc77
github.com/facebookgo/grace v0.0.0-20160926231715-5729e484473f                          | github.com/facebookgo/grace v0.0.0-20180706040059-75cf19382434
github.com/facebookgo/httpdown v0.0.0-20160323221027-a3b1354551a2 // indirect           | github.com/facebookgo/httpdown v0.0.0-20180706035922-5979d39b15c2 // indirect
github.com/go-redis/redis v6.15.2+incompatible                                          | github.com/go-redis/redis v6.15.6+incompatible
github.com/issue9/identicon v0.0.0-20160320065130-d36b54562f4c                          | github.com/issue9/identicon v1.0.1
github.com/jaytaylor/html2text v0.0.0-20160923191438-8fb95d837f7d                       | github.com/jaytaylor/html2text v0.0.0-20190408195923-01ec452cbe43
github.com/kballard/go-shellquote v0.0.0-20170619183022-cd60e84ee657                    | github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
github.com/keybase/go-crypto v0.0.0-20170605145657-00ac4db533f6                         | github.com/keybase/go-crypto v0.0.0-20190828182435-a05457805304
github.com/klauspost/compress v0.0.0-20161025140425-8df558b6cb6f                        | github.com/klauspost/compress v1.8.6
github.com/klauspost/cpuid v0.0.0-20160302075316-09cded8978dc // indirect               | github.com/klauspost/cpuid v1.2.1 // indirect
github.com/markbates/goth v1.56.0                                                       | github.com/markbates/goth v1.57.0
github.com/mattn/go-isatty v0.0.7                                                       | github.com/mattn/go-isatty v0.0.10
github.com/mcuadros/go-version v0.0.0-20190308113854-92cdf37c5b75                       | github.com/mcuadros/go-version v0.0.0-20190830083331-035f6764e8d2
github.com/microcosm-cc/bluemonday v0.0.0-20161012083705-f77f16ffc87a                   | github.com/microcosm-cc/bluemonday v1.0.2
github.com/msteinert/pam v0.0.0-20151204160544-02ccfbfaf0cc                             | github.com/msteinert/pam v0.0.0-20190215180659-f29b9f28d6f9
github.com/nfnt/resize v0.0.0-20160724205520-891127d8d1b5                               | github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
github.com/pquerna/otp v0.0.0-20160912161815-54653902c20e                               | github.com/pquerna/otp v1.2.0
github.com/remyoudompheng/bigfft v0.0.0-20190321074620-2f0d2b0e0001 // indirect         | github.com/remyoudompheng/bigfft v0.0.0-20190728182440-6a916e37a237 // indirect
github.com/russross/blackfriday v0.0.0-20180428102519-11635eb403ff                      | github.com/russross/blackfriday v1.5.2
github.com/shurcooL/httpfs v0.0.0-20190527155220-6a4d4a70508b // indirect               | github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749 // indirect
                                                                                        > github.com/ssor/bom v0.0.0-20170718123548-6386211fdfcf // indirect
github.com/tecbot/gorocksdb v0.0.0-20181010114359-8752a9433481 // indirect              | github.com/tecbot/gorocksdb v0.0.0-20190930194452-65a88f08537a // indirect
github.com/unknwon/cae v0.0.0-20190822084630-55a0b64484a1                               | github.com/unknwon/cae v1.0.0
github.com/unknwon/com v0.0.0-20190804042917-757f69c95f3e                               | github.com/unknwon/com v1.0.1
github.com/unknwon/paginater v0.0.0-20151104151617-7748a72e0141                         | github.com/unknwon/paginater v0.0.0-20170405233947-45e5d631308e
github.com/urfave/cli v1.20.0                                                           | github.com/urfave/cli v1.22.1
github.com/yohcop/openid-go v0.0.0-20160914080427-2c050d2dae53                          | github.com/yohcop/openid-go v1.0.0
golang.org/x/crypto v0.0.0-20190927123631-a832865fa7ad                                  | golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
golang.org/x/net v0.0.0-20190909003024-a7b16738d86b                                     | golang.org/x/net v0.0.0-20191011234655-491137f69257
golang.org/x/sys v0.0.0-20190910064555-bbd175535a8b                                     | golang.org/x/sys v0.0.0-20191010194322-b09406accb47
gopkg.in/asn1-ber.v1 v1.0.0-20150924051756-4e86f4367175 // indirect                     | gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d // indirect
gopkg.in/editorconfig/editorconfig-core-go.v1 v1.3.0                                    | gopkg.in/editorconfig/editorconfig-core-go.v1 v1.3.1
gopkg.in/ini.v1 v1.46.0                                                                 | gopkg.in/ini.v1 v1.48.0
gopkg.in/ldap.v3 v3.0.2                                                                 | gopkg.in/ldap.v3 v3.0.3
gopkg.in/testfixtures.v2 v2.5.0                                                         | gopkg.in/testfixtures.v2 v2.5.3
```
As an alternative, I could open 31 PRs for the direct dependencies only, but this too seems like a lot of work.

**Comment by lunny** [comment]
@carnott-snap it's not easy to review since so many changed files.

**Comment by guillep2k** [comment]
@carnott-snap only one for each dependency you modify manually. Automatic dependencies don't need PRs. Moreover, I wouldn't make too many PRs at once, because they will not be merged all at the same time and it would cause all PRs to be reworked.

**Pull request closed without merging**
