### PR TITLE
Rename modules -> pkgs

### PR DESCRIPTION
**Pull request by lunny**
Go packages and go modules are different things, so the package name `modules` is not suitable. Rename `modules` to `pkgs` will make less confusing.

Packages could be found in Golang specification  https://golang.org/ref/spec#Packages , modules is not in that but we can find it here https://pkg.go.dev/cmd/go#hdr-Modules__module_versions__and_more

The name `modules` was created in Gitea before Golang introduce go modules, but now almost all Golang repositories are using go modules. So I think we should change it.

- [x] Rename `code.gitea.io/gitea/modules` -> `code.gitea.io/gitea/pkgs` on all go files and doc files
- [x] Rename `repo_module` -> `repo_pkg`
- [x] Rename `csv_module` -> `csv_pkg`
- [x] Rename `lfs_module` -> `lfs_pkg`

### CODE REVIEW

**Comment by techknowlogick** [comment]
Tagged as breaking as some downstream packagers use -X to override values to comply with FHS

**Comment by silverwind** [comment]
Why not `packages`? I prefer to avoid such silly abbreviations :)

**Comment by lunny** [comment]
> abbreviations

It's shorter than `packages`, so that all import path will be shorter.

**Review by 6543 — APPROVED** [review]
I will get used to it again ...

**Comment by cmitsakis** [comment]
You missed [docs/content/doc/developers/migrations.en-us.md](https://github.com/go-gitea/gitea/blob/9c116f2bb51ab3da9385ecdbd538a91c0393e609/docs/content/doc/developers/migrations.en-us.md)

**Comment by lunny** [comment]
> docs/content/doc/developers/migrations.en-us.md

done.

**Comment by cmitsakis** [comment]
on [this](https://github.com/lunny/gitea/blob/lunny/rename_modules_pkgs2/docs/content/doc/developers/migrations.en-us.md) and [this file](https://github.com/lunny/gitea/blob/lunny/rename_modules_pkgs2/docs/content/doc/developers/developers/api-usage.en-us.md) (and other files on the same directory) you can still find links to modules

**Comment by lunny** [comment]
> on [this](https://github.com/lunny/gitea/blob/lunny/rename_modules_pkgs2/docs/content/doc/developers/migrations.en-us.md) and [this file](https://github.com/lunny/gitea/blob/lunny/rename_modules_pkgs2/docs/content/doc/developers/api-usage.en-us.md) (and other files on the same directory) you can still find links to modules

done.

**Comment by zeripath** [comment]
I remain deeply unconvinced of the merits of this.

**Comment by techknowlogick** [comment]
I think it's better if we wait for this (if we do it), until closer to release of RC for 1.16, because otherwise when we backport things to 1.15 we will have many modifications to do for each backport.

**Comment by lunny** [comment]
This PR is difficult to maintain. So I close it now. But I still think rename `modules` to `pkgs` is a right way.

**Pull request closed without merging**
