### PR TITLE
Allow markdown table to scroll

### PR DESCRIPTION
**Pull request by pgodwin**
`overflow:auto` isn't effective when a table is wider than the container. Adding `display:block` fixes this issue.

### CODE REVIEW

**Comment by lafriks** [comment]
can you give screenshots with before and after?

**Comment by pgodwin** [comment]
No worries. 

I should point out that this is on Firefox 61 under Windows.

#### Before:
table block before

#### After:
table block after

**Review by techknowlogick — APPROVED** [review]
Please resolve conflict, but otherwise LGTM.

**Comment by lafriks** [comment]
@pgodwin please resolve conflict

**Comment by techknowlogick** [comment]
@lafriks conflict resolved.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Hopefully it does not have side effects :)

**Pull request merged**
