### PR TITLE
Fix markdown URL parsing

### LINKED ISSUE #17625: Some markdown links aren't rendered correctly
### Gitea Version

1.16.0

### Operating System

_No response_

### Browser Version

Firefox 94.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Some links aren't rendered correctly by the md parser. 
1. compare links are rendered like a link to a single commit, but the chars `...<second commit sha>` is coming after this text.
2. if I link to a permanent code snippet and add a single char after the link, the char is included in the rendered link (and in the link the `href` param is wrong too)

For an example on try with all issues: https://try.gitea.io/ktdkydkycoyf/ex/issues/2#issuecomment-112142

### Screenshots

Examples:
1. see https://codeberg.org/gitnex/GitNex/pulls/1008#issue-77442 - the fifth list point contains a compare link
2. see https://codeberg.org/gitnex/GitNex/pulls/1014 (there is only one link in this comment, a permanent lines link with a trailing `:`

### PR DESCRIPTION
**Pull request by wxiaoguang**
This PR fixes some URL parsing bugs in markdown render.
* Close https://github.com/go-gitea/gitea/issues/17625
* Add one-level sub-path support to `anySHA1Pattern` (hacky)
* Fix wrong usage of `setting.AppSubURL`, rename `const AppSubURL` to `const TestRepoURL`

For test content reported in #17625 :

```
1. issue with line permalinks https://try.gitea.io/ktdkydkycoyf/ex/src/commit/a702ddb6e48b4b6a6cf002fe78b2a051b3c030f6/example.txt#L2:
2. issue with file permalinks https://try.gitea.io/ktdkydkycoyf/ex/src/commit/a702ddb6e48b4b6a6cf002fe78b2a051b3c030f6/example.txt:
3. issue when comparing two commits https://try.gitea.io/ktdkydkycoyf/ex/compare/e4787c3b4c8a4c301081c3f188d7fc73096a38b8...a702ddb6e48b4b6a6cf002fe78b2a051b3c030f6
```

### Before

image

### After

image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
Hmm... This pr basically makes auto URLs only work if they're ASCII. This would prevent auto linking of things like: https://example.com/Verknüpfung/auf/Zeug 

The main issue, apart from the compare URL, appears to be terminal punctuation - I wonder if we should just be checking if the final character is punctuation and if so just removing it like you've proposed for the terminal dot might just work instead.

**Comment by wxiaoguang** [comment]
> Hmm... This pr basically makes auto URLs only work if they're ASCII. This would prevent auto linking of things like: [https://example.com/Verknüpfung/auf/Zeug](https://example.com/Verkn%C3%BCpfung/auf/Zeug)
> 
> The main issue, apart from the compare URL, appears to be terminal punctuation - I wonder if we should just be checking if the final character is punctuation and if so just removing it like you've proposed for the terminal dot might just work instead.

Yep, I made it only works for ASCII URL by purpose. Because due to RFC, the URL should be correctly encoded.

Especially for non-Latin family languages (eg: Korean/Japanese/Chinese), there is no space between URL and sentences. It's more difficult to guess and parse "这个https://xxx/描述了一个问题"

**Comment by wxiaoguang** [comment]
Oh, by the way, I only changed the `anySHA1Pattern` and `comparePattern`.

So if there is an external URL like `https://example.com/Verknüpfung/auf/Zeug`, the behavior is not changed. It should work as before.

**Review by silverwind — APPROVED** [review]

**Comment by lafriks** [comment]
🚀

**Pull request merged**
