### PR TITLE
Update comparison page with RhodeCode CE & EE

### PR DESCRIPTION
**Pull request by marcinkuzminski**
Update RhodeCode features and add EE version

### CODE REVIEW

**Comment by lunny** [comment]
I would like to remove Gogs and RhodeCode, because both them are outdated and it will take much time to follow than other 3 platforms.

**Comment by marcinkuzminski** [comment]
What do you mean by outdated?

I'm the author of RhodeCode, and we just made the biggest release ever supporting python3.

I think it's fair to have a comparison page that people could look into and compare options.

I created this PR especially for someone who was checking different options for GIT and pointed out that the page is missing RhodeCode EE.

**Comment by lunny** [comment]
> What do you mean by outdated?
> 
> I'm the author of RhodeCode, and we just made the biggest release ever supporting python3.
> 
> I think it's fair to have a comparison page that people could look into and compare options.
> 
> I created this PR especially for someone who was checking different options for GIT and pointed out that the page is missing RhodeCode EE.

Congratulations! !!

And thank you for contributing. I mean this comparison documentation hasn't been updated for a long time. So it may missed many things. Keeping less platforms here will allow us spending less time to track them.

**Comment by marcinkuzminski** [comment]
Understood,

We can track this page and constantly refresh it up-to-date for RhodeCode at least.

**Review by lunny — APPROVED** [review]

**Pull request merged**
