### PR TITLE
Replace deprecated `elliptic.Marshal`

### PR DESCRIPTION
**Pull request by harryzcy**
In PR #26786, the Go version for golangci-lint is bumped to 1.21. This causes the following error:

```
models/migrations/v1_16/v210.go:132:23: SA1019: elliptic.Marshal has been deprecated since Go 1.21: for ECDH, use the crypto/ecdh package. This function returns an encoding equivalent to that of PublicKey.Bytes in crypto/ecdh. (staticcheck)
                                        PublicKey:       elliptic.Marshal(elliptic.P256(), parsed.PubKey.X, parsed.PubKey.Y),
```

The change now uses [func (*PublicKey) ECDH](https://pkg.go.dev/crypto/ecdsa#PublicKey.ECDH), which is added in Go 1.20.

### CODE REVIEW

**Review by puni9869 — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Interestingly the CI run in https://github.com/go-gitea/gitea/pull/26799 did succeed, so no deprecation was detected. Still good to merge this.

**Comment by silverwind** [comment]
Leave it open a bit more, I'm not 100% sure the change is correct.

**Comment by puni9869** [comment]
Backport?

**Review by KN4CK3R — APPROVED** [review]
It's identical.

**Review by delvh — APPROVED** [review]

**Pull request merged**
