### PR TITLE
Don't run 'make release' on PRs

### PR DESCRIPTION
**Pull request by bkcsoft**
Don't run `make release` on PRs. Takes 20-25 minutes to run (90% of total time) on drone-servers... Make-shift solution until we bring up more drone-agents...

The only thing this does is disabling build-tests on all architectures excluding amd64

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by tboerger** [comment]
We had disabled that in the past, until some architectures failed on master. That's why we always enabled it

**Comment by appleboy** [comment]
@bkcsoft @tboerger What time do we start to upgrade Drone to `0.7.x` version?

**Comment by sapk** [comment]
LGTM

**Comment by bkcsoft** [comment]
@tboerger right, but running `make release` takes a shit-ton of time 😞

**Pull request merged**
