### PR TITLE
Defer closing the gitrepo until the end of the wrapped context functions (#15653)

### PR DESCRIPTION
**Pull request by zeripath**
Backport #15653

There was a mistake in #15372 where deferral of gitrepo close occurs before it should.

This PR fixes this.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@zeripath please resolve conflict :)

**Comment by zeripath** [comment]
resolved

**Comment by zeripath** [comment]
ugh I messed up with that resolve commits - now fixed

**Review by 6543 — APPROVED** [review]

**Review by kdumontnu — APPROVED** [review]
👍

**Pull request merged**
