### PR TITLE
Fix wrong i18n keys

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by 6543** [comment]
there are more in there :/ e.g. L35 ...

**Comment by 6543** [comment]
```
web/user/setting/keys.go
212:			ctx.Flash.Error(ctx.Tr("setting.ssh_externally_managed"))

web/user/setting/security_twofa.go
35:			ctx.Flash.Error(ctx.Tr("setting.twofa_not_enrolled"))
65:			ctx.Flash.Error(ctx.Tr("setting.twofa_not_enrolled"))
153:		ctx.Flash.Error(ctx.Tr("setting.twofa_is_enrolled"))
178:		ctx.Flash.Error(ctx.Tr("setting.twofa_is_enrolled"))
```

**Review by 6543 — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
mea culpa

**Comment by 6543** [comment]
-> #17153

**Pull request merged**
