### PR TITLE
Fix tests hostkeys

### PR DESCRIPTION
**Pull request by 6543**
allow ssh-rsa as hostkey algorithm for integration tests

source: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/26273

### CODE REVIEW

**Comment by zeripath** [comment]
Tests fail as the version of ssh we are using does not have this option - but instead has the older version instead: 

```
pubkeyacceptedkeytypes
```

**Comment by 6543** [comment]
so should we update our test environment or let it just stay open until the ssh version is common?

**Comment by zeripath** [comment]
We should really fix the ssh problem - although that will mean forking X/crypto/ssh

**Comment by techknowlogick** [comment]
@zeripath Ive only been casually following the upstream issue, but my understanding is that there were two recent PRs that were merged to resolve this. Would updating our go.mod to use latest x/crypto be suitable enough

**Comment by zeripath** [comment]
I think you're referring to https://github.com/golang/crypto/commit/b4de73f9ece8163b492578e101e4ef8923ac2c5c

This is handling the host key certificate problem in much the same way as my merged PR for Gitea does. It's unfortunately not going to handle the client public key problem that this PR is referring to.

It's worth noting that the above commit has not addressed the design flaw that keys and signers are related but are not the same. Neither Gitea nor the X/crypto/ssh can actually turn off ssh-rsa signature verification for hosts right now.

**Comment by techknowlogick** [comment]
Ah yes, that was it. Thanks for that explanation of the situation. It seems the current possible options are rather suboptimal in that case, the least preferred option (at least personally) would be to fork x/crypto.

**Comment by zeripath** [comment]
> Ah yes, that was it. Thanks for that explanation of the situation. It seems the current possible options are rather suboptimal in that case, the least preferred option (at least personally) would be to fork x/crypto.

Yeah I don't particularly fancy the idea of having to maintain an SSH server... (Although to some extent our hope that we can abstract that problem away to someone else has now failed and I've had to learn (something) about the SSH protocol and KEY_EXT_INFO etc.)

I guess the question is how long do we think upstream will take to fix this issue? 

Whilst this issue is still unsolved our SSH server is not a production ready item and cannot be used out of the box with up-to-date ssh. Upstream do not appear to be moving with any speed to resolve this, and from looking at the code there are several fundamental design issues including one that means we cannot in future disable host-key signature verification with the `ssh-rsa` signing algorithm. This is far from ideal.

For me to work out how to properly fix this and propose a PR would involve me gaining a much more complete understanding of the SSH protocol and the design of x/crypto/ssh. We would need to change the handshake.go file considerably and we're going to need to properly separate signers from keys as I proposed on the golang issue. Such a PR would not only take some time to write but no doubt sometime to merge. In the meantime it would entail Gitea using and maintaining that fork until the PR or an equivalent was merged in. The trouble is that I don't have a complete understanding of the SSH protocol or how x/crypto/ssh is designed but do have enough knowledge to say that this is not a trivial task, I therefore expect that x/crypto/ssh might be slow to merge such a PR.

I wonder if gliderlabs' @belak has a better understanding of the design in x/crypto/ssh and whether they would be able to workaround the issue.

**Comment by zeripath** [comment]
We need to collect these issues in one place and open a proper Gitea issue for this. 

---

For speed I'm going to collect things here:

* #17175 reported that there was a key negotiation failure with newer versions of SSH and Gitea.
* Through investigation this was revealed to be a HostKey algorithm failure due to the key type being used to determine the signing algorithms available for the key. 
* Fortunately the HostSigners are exposed on the underlying ssh server so although there is a fundamental flaw in the way signers (their type is not reportable separate from the key) #17281 was able to work around this by wrapping those keys around something to pretend to be signers.
* This then fixes the hostkey issue - however, I was unaware of the next issue...
* @andypost then commented on https://github.com/go-gitea/gitea/issues/9691#issuecomment-955776326 (Which is unfortunately an unrelated feature request issue relating to HTTPS not SSH.)
* My comment here https://github.com/go-gitea/gitea/issues/9691#issuecomment-956753681 describes that the issue is actually relating to the next step of authentication - the pubkeyalgorithm 
* I then discovered that the problem is relating to the pubkey signing algorithms offered to the client https://github.com/go-gitea/gitea/issues/9691#issuecomment-962434683
* There is an upstream issue: https://github.com/golang/go/issues/49269 relating to supporting the required extension.
* And there is a PR here: https://github.com/golang/crypto/pull/197 that implements this but I'm not completely convinced its totally correct.
* In the meantime go have merged: https://github.com/golang/crypto/commit/b4de73f9ece8163b492578e101e4ef8923ac2c5c
* This does a similar bodge to the one I did in #17281, however, whereas #17281 leaves the possibility of disabling certain host key signing algorithms in the future, if we support ssh-rsa we have to support rsa-sha2-256 and rsa-sha2-512, and no way is provided to support only  rsa-sha2-256 and rsa-sha2-512. (The above commit does provide certificate support which is something that #17281 missed.)

---

What is actually needed:

* Signers need to be separately configurable and advertisable apart from the key types that they sign.
* The Handshake needs to support extension negotiation https://datatracker.ietf.org/doc/html/rfc8308 and in particular the SSH_MSG_EXT_INFO extension described therein.

**Comment by belak** [comment]
After digging through this for the past hour or so (which is probably a mistake for me since it's almost 4am here), I've come to pretty much the same conclusion - the only way I'm aware of to fix this is in the Go ssh internals, a hack in gliderlabs/ssh wouldn't be enough. I really have no desire at all to fork and maintain the core SSH code, especially when that isn't a part of my job, but I'd be happy to update or review PRs for gliderlabs/ssh to support upstream changes (if needed).

On a related note, I think [your comment here](https://github.com/golang/go/issues/39885#issuecomment-943101689) is relevant. It does a good job summarizing the changes which would need to happen to the Signer interface.

I'm also available in Discord for any quick questions, or if you just need someone to bounce ideas off of.

**Comment by wxiaoguang** [comment]
Could we get this fix in 1.16, or should we leave it to 1.17 ?

**Comment by techknowlogick** [comment]
@wxiaoguang if CI passes I'm happy to have it merged before 1.17

**Comment by zeripath** [comment]
As I say above - this PR currently relies on an option that our testing version of ssh doesn't have and that only affected versions of ssh have.

If we want to merge this we need to detect if ssh has this option before setting it. There's likely little point setting the old option as only unaffected versions should be affected.

However this is only a workaround bodge for the more substantial problem that the ssh package in x/crypto/ssh is broken and lacks the functionality to handle pubkey authentication with RSA except through the old deprecated ssh-rsa algorithm.

**Comment by lunny** [comment]
CI failed is related.

**Comment by 6543** [comment]
-> #17798 :D

**Comment by 6543** [comment]
I think it could be simpler if we should generate a new id_ed25519 ssh key and replace the old rsa key with it ...

**Pull request closed without merging**
