### PR TITLE
Remove New PR button in PRs

### LINKED ISSUE #15996: [Bug] Active Pull Requests Should Not Have Option For "New Pull Request"
## Description
Pull requests should not have the option to create a "New Pull Request". I believe this is an artifact from using the same template for "compare" as used for PRs.

## Screenshots

image

### PR DESCRIPTION
**Pull request by kdumontnu**
Closes #15996

### CODE REVIEW

**Comment by noerw** [comment]
Hmm, not sure this is an improvement. Maybe do it like github, and show a "new issue" button on PR page & vice versa?

**Comment by kdumontnu** [comment]
> Hmm, not sure this is an improvement. 

This actually came as feedback from some of our users asking why there was an option to create a "New Pull Request" when looking at someone else's PR. I don't see a case where anyone would need to do that... In general, I think gitea suffers from a bit "everything including the kitchen sink". This is a clear example - lets keep the interface clean and simple.

> show a "new issue" button on PR page & ~vice versa~ as on issue page?
> edit: Seems like I'm hallucinating and GH doesn't do that.. but would still be neat imho

To your other point I also don't see a case where users will want to create an issue from a PR (we do have the "reference in new issue option" btw). From a UX perspective these are two different workflows - no need to link them together.

**Review by noerw — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by lunny** [comment]
Please rebase

**Comment by lunny** [comment]
make L-G-T-M work

**Pull request merged**
