### PR TITLE
Upgrade to Node 20 on CI, enable actions cancellation

### PR DESCRIPTION
**Pull request by silverwind**
- Upgrade node, the [snap](https://github.com/go-gitea/gitea/blob/7abe958f5b507efa676fb3b2e27d30517f6d1908/snap/snapcraft.yaml#L47) is excluded from this because [there is no Node 20 snap yet](https://snapcraft.io/node).
- Add actions build cancellation based on [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value).

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]
LGTM, thanks :)

If you want to get the concurrency changes in here too, otherwise I can get another PR for them.

**Comment by silverwind** [comment]
> LGTM, thanks :)
> 
> If you want to get the concurrency changes in here too, otherwise I can get another PR for them.

Added the concurrency group to all `pull-*` pipelines. See [here](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) for the description of `github.ref`. So it should now cancel previous runs in the same concurrency group. I will test with a push now.

**Comment by silverwind** [comment]
Cancelling seems to work fine:

image

**Comment by silverwind** [comment]
Maybe the icon would go to a grey stop sign if all steps in the build are cancelled, but I don't know how to cancel giteabot 😆.

**Comment by techknowlogick** [comment]
> Also I wonder why giteabot is still pending on the cancelled build.

Giteabot won't go grey, it'll stay "pending" until the PR receives all approvals.

**Comment by techknowlogick** [comment]
I'm not sure if you are seeing this too, but in the required checks area below there are duplicated checks. Perhaps the concurrency stuff is indeed best saved for another PR so as to not hold this one up. Sorry for the extra work you have done.

**Comment by silverwind** [comment]
Hmm I don't see duplicates but there are "6 successful, 8 expected" and the expected ones do not run, strange.

**Comment by silverwind** [comment]
Trying this now: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

**Comment by techknowlogick** [comment]
Ah yup, I'm not seeing any dupes anymore. What you have done has worked :)

**Comment by silverwind** [comment]
There is one more variation of this cancelling which can be configured so that only pull requests cancel, release builds and main branch builds won't cancel. I'll copy the syntax that the [node repo uses](https://github.com/nodejs/node/commit/5348552b9396b69cc5d49a287a573e20ce55751c).

**Comment by silverwind** [comment]
Done, this new cancellation will only cancel on pull requests. I see the workflows currently only run `on: pull_request`, but should we ever decide to run them on main branch, this syntax will be good to have.

**Review by yardenshoham — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Pull request merged**
