### PR TITLE
Drop the correct deleted branch table

### PR DESCRIPTION
**Pull request by yp05327**
There's a typo in #22743
The correct table name is `deleted_branch` not `deleted_branches`

### CODE REVIEW

**Comment by lunny** [comment]
> There's a typo in #22743 The correct table name is `deleted_branch` not `deleted_branches`

Could you also fix that typo?

**Comment by yp05327** [comment]
> > There's a typo in #22743 The correct table name is `deleted_branch` not `deleted_branches`
> 
> Could you also fix that typo?

Done.

**Review by lunny — APPROVED** [review]

**Review by yardenshoham — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Needs `make fmt`

**Comment by silverwind** [comment]
Conflict in migration number.

**Pull request merged**
